hw/ip/edn/data/edn_testplan.hjson
- Update edn interrupt, alert and error tests covergroup
=> [edn, dv] Update edn testplan covergroup

sw/host/opentitansession/src/main.rs
Add ability for opentitansession to start and stop a background daemon process.
Signed-off-by: Jes B. Klinke <jbk@chromium.org>
Change-Id: I99241a477f9625e0a7effca4afc20576e4e2c123
=> [opentitantool] Proper daemon support

hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
EDIT: The approach of this PR has changed.
~~RNG bit select mode is meant to filter the RNG sequence to only use
one line.  Data can still be fips compliant even in this mode.~~
RNG single bit mode is not considered FIPS compliant by the DUT.
This commit reflects that in the scoreboard.
It also includes scoreboard diagnostics to help detect similar errors.
=> [entropy_src/dv] Properly predict fips_mode signal

sw/host/opentitanlib/src/backend/mod.rs
Errors like "Permission denied" or "JSON parse error on line 5" ought
to be shown in the context of which file path was attempted loaded
or parsed, in order to help the operator figure out what is the issue.
This CL introduces two new error Enum values, each of which carry a
file path, and an underlying error, for the above purpose.
Signed-off-by: Jes B. Klinke <jbk@chromium.org>
Change-Id: I721bab68dbf511aa0397c84be5e8a213638ebdd7
=> [opentitantool] Include context in conf errors

hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
- identified by weicai in #11235
=> [flash_ctrl] Fix init_busy glitches

hw/top_earlgrey/formal/chip_conn_cfg.hjson, hw/top_earlgrey/formal/conn_csvs/lc_escalate_en.csv
This PR finishes a TODO in #11208
=> [conn/top] Add lc_escalate_en connectivity checks

hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
Update pinmux FPV according to issue #11194.
=> [fpv/pinmux] Update pinmux counter threshold

hw/top_earlgrey/formal/top_earlgrey_fpv_cfgs.hjson
This PR updates the IPs that has security countermeasures.
=> [fpv/sec cm] Update the list of sec IPs

hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv, hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_reg_pkg.sv, hw/ip/kmac/rtl/kmac_reg_top.sv
This PR addresses an AI in #10823 
As I'm new to register changes, any comments are more than welcome; especially concerning needed adaptions of sw or dv.
=> [kmac] changed hash-threshold reg to shadow reg

hw/ip/entropy_src/data/entropy_src_testplan.hjson, hw/ip/entropy_src/doc/dv/index.md
- Adds many more cover points for all registers and usage models
- Minor updates & formatting fixes to testplan
=> [Entropy_src/dv] Flesh out test plan more fully

hw/dv/sv/jtag_riscv_agent/jtag_riscv_monitor.sv
This triggered some warnings in Xcelium (because we were assigning raw
bits to an enum type without an explicit cast).
Add explicit casting and an auxiliary "raw" variable to make it clear
which bits use the cast (now always inside a branch where we know the
value is good, or just used for debug prints).
=> [dv,jtag] Fix casting in jtag_riscv_monitor

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_vseq_list.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.core, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_if.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson
This test will verify the ultra low power feature of sysrst_ctrl block.
=> Added ultra low power testcase

doc/project/checklist.md
Add an item - SIM_COVERAGE_REVIEWED
Also clean up some TODO
Once this is in, will make an PR to update each checklist in IPs
=> [dv] Update V2S checklist

hw/dv/verilator/cpp/scrambled_ecc32_mem_area.cc
This reverts commit 0c97225904d1264d7ae33e9d236394743a30faee. The weak
symbol cleverness was done there to allow Ibex simulations to run
without an icache. Unfortunately, it doesn't really work properly with
Xcelium. See the commit message for [c15f3b888 in the Ibex repository](https://github.com/lowRISC/ibex/commit/c15f3b88883781808eaa96bda205a9bdaff5eb98)
for full details (and a work-around).
=> Revert "[dv] Allow using memutil_dpi_scrambled even without prim_ram_1p_scr"

hw/ip/tlul/rtl/tlul_assert.sv
This PR supports common d_errors in `tlul_assert.sv`:
1). legalAOpcodeErr
2). sizeGTEMaskErr
3). sizeMatchesMaskErr
4). addrSizeAlignedErr
The rest of errors I will cover them in generated csr assertions.
This PR implements the TODO from issue: https://github.com/lowRISC/opentitan/issues/11243
=> [fpv/tlul_assert] Support d_error[Part1]

sw/host/opentitanlib/Cargo.toml, sw/host/opentitanlib/src/transport/common/uart.rs, sw/host/opentitanlib/src/transport/verilator/uart.rs, sw/host/opentitantool/Cargo.toml, sw/host/opentitantool/src/main.rs
1. Fix timeout detection for the verilator UART.
2. Add timeout detection for the common-case UART.
3. Print backtraces if available.
=> [opentitantool] Fix UART timeout issues

hw/ip/clkmgr/data/clkmgr.prj.hjson, hw/ip/clkmgr/doc/checklist.md
- fixes all but spreadsheet syncing item in #10926
=> [clkmgr] move to d2s

hw/ip/pwrmgr/data/pwrmgr.prj.hjson, hw/ip/pwrmgr/doc/checklist.md
- fixes all but spreadsheet syncing in #10825
=> [pwrmgr] Move to d2s

hw/ip/rstmgr/data/rstmgr.prj.hjson, hw/ip/rstmgr/doc/checklist.md
- fixes all but spreadsheet sync item in #10899
=> [rstmgr] move to d2s

hw/ip/kmac/rtl/kmac.sv
In issue #10760, @cindychip found that the alert status does not keep
its value as the status register is set to external register. As
`alert_operation` just asserts one cycle, the STATUS value becomes zero
at the next cycle.
In this commit, reg is defined to keep the value. It can be reset by
err_processed (not the alert but the STATUS value) for recoverable
error but the fatal error remains high until the IP is being reset.
=> [kmac] Make alert status stay

hw/ip/tlul/lint/tlul_socket_1n.waiver, hw/ip/tlul/rtl/tlul_pkg.sv, hw/ip/tlul/rtl/tlul_socket_1n.sv
- xbar portion fix to #11036
- Technically this should be applied to m1 as well for reads
=> [tlul] xbar data blanking

hw/ip/kmac/data/kmac.prj.hjson, hw/ip/kmac/doc/checklist.md, hw/ip/kmac/rtl/kmac.sv
As all AIs have been addressed, KMAC moves to D2S officially.
Co-Authored-by: Michael Tempelmeier <michael.tempelmeier@gi-de.com>
=> [kmac] Move to D2S

hw/ip/entropy_src/data/entropy_src.hjson, hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
Extra exclusions were tested and removed to let the auto testing
get more coverage.
=> [entropy_src/hjson] Remove some exclusion statements

hw/ip/usbdev/rtl/usbdev.sv
=> [usbdev] lint fixes

hw/ip/keymgr/data/keymgr.hjson, hw/ip/keymgr/rtl/keymgr.sv, hw/ip/keymgr/rtl/keymgr_ctrl.sv, hw/ip/keymgr/rtl/keymgr_kmac_if.sv, hw/ip/keymgr/rtl/keymgr_pkg.sv, hw/ip/keymgr/rtl/keymgr_reg_pkg.sv, hw/ip/keymgr/rtl/keymgr_reg_top.sv
Addresses the spurious valid item from kmac d2c list #10823 
=> [keymgr] Detect spurious done's from kmac as a fault

sw/device/lib/testing/check.h
=> [sw/runtime] Add return code in CHECK_DIF_OK

hw/ip/otp_ctrl/dv/env/otp_ctrl_if.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv, hw/ip/otp_ctrl/dv/tb.sv
Signed-off-by: Dror Kabely <dror.kabely@opentitan.org>
=> [dv/otp_ctrl] added external voltage input to interface

hw/ip/keymgr/data/keymgr.hjson, hw/ip/keymgr/data/keymgr_sec_cm_testplan.hjson, hw/ip/keymgr/rtl/keymgr_kmac_if.sv
- Also slightly tweak some error permanence
=> [keymgr] Add missing countermeasure labels

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_common_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_vseq_list.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.core, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_if.sv, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson, hw/ip/sysrst_ctrl/dv/tb.sv
This PR contains the test which will verify the sysrst_ctrl combo detect feature
=> [sysrst_ctrl,dv] Add sysrst_ctrl_combo_detect test

hw/ip/tlul/rtl/tlul_lc_gate.sv
=> [tlul_lc_gate] Fix gating condition

sw/device/lib/dif/dif_aes.c, sw/device/lib/dif/dif_aes_unittest.cc
This PR is spread out in different commits, please look at the commits for better understanding.
=> Aes unittest all registers

util/reggen/gen_html.py
=> [reggen] If no regs are defined, indicate that explicitly in the docs

sw/device/lib/dif/dif_clkmgr.c, sw/device/lib/dif/dif_clkmgr.h, sw/device/lib/dif/dif_clkmgr_unittest.cc
=> [dif/clkmgr] Add support for count measurements

hw/ip/spi_device/rtl/spi_device.sv
CSb `cio_csb_i` is used as a reset and a signal in SPI_DEVICE. To not be
confused, this commit added buffers to the CSb and used the buffer
signals in reset mux, sys clock, sck clock.
=> [spi_device] Explicit reset buffer for CSb

hw/top_earlgrey/formal/conn_csvs/clkmgr_idle.csv, hw/top_earlgrey/formal/conn_csvs/clkmgr_trans.csv
This PR fixes some port change in clkmgr
=> [conn/clkmgr] Fix clkmgr port change

sw/device/lib/base/macros.h
This macro is intended for writing chip-level tests that want to check
that some kind of exception-ey thing happened in a range of program
counters. It is a maximally compiler-portable implementation that won't
be optimization-hostile like GCC's label references (&&label), whose
support in LLVM is... not something we should rely on.
This macro is mostly made of caveats, but it has a narrow use
regardless.
=> [sw, base] Add a macro for creating addressable code labels

util/reggen/gen_html.py
The existing code didn't work very will if you had e.g. just one entry
in the window. In that case, it would generate addresses like
+0x180, +0x184, ..., +0x180, +0x184
which looked a bit funny!
Fixes #1542. Now the fifo entries look like this:
=> [reggen,doc] Fix rendering of windows with fewer than 5 indices

sw/device/tests/aon_timer_wdog_bite_reset_test.c
- The bug was caused by a delay of 3 cycles between the matching of timer counter with the threshold and the irq state register to rise, which becomes more evident when the cpu clock is higher.
Signed-off-by: Douglas Reis <doreis@lowrisc.org>
=> [test, aon_timer] Fix bug on the aon bite reset test

hw/ip/otbn/dv/otbnsim/sim/sim.py, hw/ip/otbn/dv/otbnsim/sim/state.py
There should be no functional change, but this makes things much easier to reason about and modify. In particular, the changes needed to get the lc_escalate tests working were a nightmare until I realised I could refactor like this.
=> [otbn,dv] Restructure ISS to step/commit more cleanly

sw/device/tests/aon_timer_irq_test.c
- The bug happens when executing the chip level test with vcs.
- The reason was a different irq firing before the wakeup irq.
=> [test, aon] Fix bug on the aon irq test

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_vseq.sv
Enabling creator and owner pages for sw rw access.
=> [flash_ctrl] Small fix for flash_ctrl_phy_arb test

hw/ip/rstmgr/data/rstmgr.prj.hjson, hw/ip/rstmgr/doc/checklist.md
=> [dv/rstmgr] Declare V2

hw/ip/clkmgr/data/clkmgr.hjson.tpl, hw/ip/clkmgr/doc/_index.md, hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson
=> [clkmgr] clarify documentation for clkmgr

hw/top_earlgrey/data/chip_conn_testplan.hjson, hw/top_earlgrey/data/chip_testplan.hjson
This PR adds a testplan for chip-level connectivity tests.
=> [conn/doc] Add a testplan for connectivity test

hw/dv/sv/push_pull_agent/push_pull_agent_cov.sv, hw/dv/sv/push_pull_agent/push_pull_monitor.sv
Sample all the combination of valid/ready or req/ack
=> [dv] Add valid/ready and req/ack coverage for push_pull agent

COMMITTERS
=> [opentitan] Remove Silvestrs from committers

hw/ip/kmac/rtl/kmac_app.sv, hw/ip/kmac/rtl/kmac_pkg.sv
=> [kmac] Added errorcode for fatal-fault #10804

hw/ip/usb_fs_nb_pe/rtl/usb_fs_nb_pe.sv, hw/ip/usb_fs_nb_pe/rtl/usb_fs_rx.sv, hw/ip/usbdev/data/usbdev.hjson, hw/ip/usbdev/data/usbdev.prj.hjson, hw/ip/usbdev/doc/_index.md, hw/ip/usbdev/doc/checklist.md, hw/ip/usbdev/doc/wake_resume.md, hw/ip/usbdev/dv/env/usbdev_scoreboard.sv, hw/ip/usbdev/rtl/usbdev_usbif.sv, site/docs/layouts/shortcodes/regref.html
1. Add SVAs for validating parameters.
2. Clean up TODOs.
3. Update docs and add recipe for handling low power modes.
4. Update checklist.
=> [usbdev] Bring usbdev to D2(S)

doc/project/technical_committee.md
Adding Michael Tempelmeier to the technical committee as discussed
by the steering committee. Welcome Michael!
=> [doc] Add Michael Tempelmeier to technical committee

hw/ip/keymgr/dv/env/keymgr_if.sv, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_hwsw_invalid_input_vseq.sv
Updated to sample it when starting advance operation at StInit
Aligned with design update at #11459
Also cleaned up some unused code
=> [keymgr/dv] Update otp key sample point

util/dvsim/Testplan.py
The actual change here is quite small (pass 'unsafehtml' to tabulate
when generating HTML output), but the patch is a bit bigger because it
includes comments that nail down exactly what format the text is in at
each stage (it took me a while to figure out!)
Fixes #11481.
=> [doc] Fix rendering of special characters in testplan table

hw/ip/clkmgr/data/clkmgr.hjson.tpl, hw/ip/clkmgr/data/clkmgr.sv.tpl, hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson, hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv, hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr_reg_pkg.sv, hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr_reg_top.sv
- Fixes #11450
- This is not technically a bug fix, but eases DV automation
=> [clkmgr] Combine shadow error registers into a single field

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_auto_blk_key_output_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_pin_override_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson
This pull request has following updates:
1. Randomize the enable/disable auto block feature
2. Randomize the enable/disable ultra low power feature
3. Add randomize check for the pin override test
=> [sysrst_ctrl,dv] Minor updates to fill the coverage holes

hw/ip/clkmgr/data/clkmgr.hjson.tpl, hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson
=> [doc/clkmgr] Fix trivial typo

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_erase_suspend_vseq.sv
Fix of erase suspend test for creator and owner partition
=> [flash_ctrl] Small fix for flash_erase_suspend test

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_ctrl_arb_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
A few small mods to the constraints, and a review of test iterations
=> [flash_ctrl] SMALL CHANGES TO THE HOST CTRL ARBITER TEST

hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/data/flash_ctrl_pkg.sv.tpl, hw/ip/flash_ctrl/doc/_index.md, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_pkg.sv
- state the difference in behavior between the protocl and physical
controllers
- make sure host transactions are error'd back as well
=> [flash_ctrl] Clarify usage of disable

hw/ip/otp_ctrl/data/otp_ctrl_sec_cm_testplan.hjson, hw/ip/otp_ctrl/data/otp_ctrl_testplan.hjson
This PR updates the auto-generated sec_cmd testplan to include matching
DV tests.
=> [dv/otp] Update sec_cm testplan

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_edge_detect_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_vseq_list.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.core, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_pkg.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_if.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson
This test will verify sysrst_ctrl key-triggered interrupt Module.
=> Added sysrst_ctrl_edge_detect testcase

hw/cdc/tools/verixcdc/run-cdc.tcl
Add clock domains, matrix to the reports to debug.
=> [verix] Add more reports for debugging

hw/ip/lc_ctrl/data/lc_ctrl.hjson, hw/ip/lc_ctrl/dv/tb.sv, hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_reg_top.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, sw/device/lib/dif/dif_lc_ctrl.c, sw/device/lib/dif/dif_lc_ctrl.h
=> [lc_ctrl] Add 32bit hardware revision register 

hw/ip/otp_ctrl/doc/_index.md
=> [otp_ctrl] Correct description to reflect current behavior

sw/device/lib/dif/dif_aes_unittest.cc, sw/device/lib/dif/dif_clkmgr_unittest.cc
=> [sw, dif] Use EXPECT_DIF_* in some places that were missing it.

hw/ip/flash_ctrl/rtl/flash_mp.sv
=> [flash_ctrl] Update bank erase assertion

hw/ip/pwrmgr/doc/_index.md
- addresses a few items in #11452
- add documentation about escalate timeout
- add documentation about fsm sparse error
=> [pwrmgr] Add documentation on a few countermeasures

hw/top_earlgrey/cdc/cdc_waivers.spi_device.tcl, hw/top_earlgrey/cdc/cdc_waivers.tcl
Adding W_CNTL waivers that are passing through prim_flop_2sync.
=> [spi_device] Waiving CDC violations through prim_flop_2sync

sw/host/opentitansession/src/main.rs
Daemons should generally not keep a reference to the current directory as of when they were
started, doing so runs the risk of random references preventing the unmounting or other management
of filesystem volumes, due to some accident in the way a daemon was started.  For that reason, the
opentitansession daemon it started with the root directory ( / ) as its current directory.
However, the first business of the daemon process is to bind to a socket, and read configuration
files according to command line arguments.  Those arguments could include relative paths to some
files.  In order to support that, this CL delays switching to the root directory until the daemon
process has finished initializing, and at the same time when it drops its connection to the
terminal that was used to start …
=> [opentitantool] Conf files relative to current directory

hw/ip/otbn/dv/smoke/smoke_test.s
Fixes #7336
Didn't feel actual code changes to replace the li/csrrw method of loading mod with lid were worth it, just updated comments so they better match current reality.
=> Update comments in OTBN smoke test

hw/ip/clkmgr/dv/cov/clkmgr_cov_bind.sv, hw/ip/clkmgr/dv/env/clkmgr_env_pkg.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_extclk_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_trans_vseq.sv
=> [dv,clkmgr] sec cm dv component

sw/device/tests/sim_dv/uart_tx_rx_test.c
When RX watermark fires, read the data, but if remaining items are less
than 16, RX watermark won't fire. In that case, changed to keep reading
until all items are received.
=> [chip dv] Fix uart unexpected watermark interrupt

hw/ip/rv_dm/data/rv_dm.prj.hjson, hw/ip/rv_dm/doc/checklist.md
This commit updates the RV_DM V1 checklist to show all V1 tasks are
complete, and advances the block from V0 to V1.
=> [rv_dm V1] Certify V1 milestone for RV_DM

README.md
=> [doc] Fix broken links in the docs

util/topgen.py
Make the string quote character consistent in the topgen.py
=> [topgen] Cleanup topgen script quotation style

hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.prj.hjson, hw/top_earlgrey/ip/sensor_ctrl/doc/checklist.md
=> [sensor_ctrl] Move to D2

hw/ip/rstmgr/data/rstmgr_sec_cm_testplan.hjson, hw/ip/rstmgr/data/rstmgr_testplan.hjson, hw/ip/rstmgr/dv/env/rstmgr_env.core, hw/ip/rstmgr/dv/env/rstmgr_env_cfg.sv, hw/ip/rstmgr/dv/env/rstmgr_env_pkg.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_sec_cm_scan_intersig_mubi_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_vseq_list.sv, hw/ip/rstmgr/dv/rstmgr_sim_cfg.hjson, hw/ip/rstmgr/dv/sva/rstmgr_bind.sv
- everything except LEAF.RST.BKGN_CHK and LEAF.RST.SHADOW
=> [dv,rstmgr] rstmgr security countermeasures

hw/ip/prim/rtl/prim_packer.sv
These are all to do with width conversion. Almost all of the changes
are just putting explicit widening casts where Verilog was doing it
implicitly before.
The one awkward place was the expression used to compute shiftl_data /
shiftl_mask. The eventual size was wrong (should be ConcatW, not
Width). But it's also a bit difficult to cast shifts and the resulting
expression was rather noisy, so I've split the expression into two
stages, which seems to tidy things up nicely. As a plus, this also
gives us a place to add a comment to document the step in the
computation.
=> [prim] Fix a bunch of Verilator lint errors in prim_packer.sv

hw/ip/spi_host/rtl/spi_host_fsm.sv
This commit corrects the timing delays in the bit_shifting,
byte_starting and byte_ending signals when operating in CPHA=1 mode.
=> [spi_host] Properly handle CPHA = 1

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_common_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_edge_detect_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson
This pull request has misc fix for the failing tests in regression
=> [sysrst_ctrl,dv] Add misc fix

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, sw/device/lib/testing/otp_ctrl_testutils.c, sw/device/lib/testing/otp_ctrl_testutils.h, sw/device/tests/sim_dv/keymgr_key_derivation.c, sw/device/tests/sim_dv/meson.build
=> [top dv] Add chip_sw_keymgr_key_derivation test

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_vseq.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv
=> [sysrst_ctrl,dv] Add remaining set of combo detect registers

hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
- Fix a path reference issue in edn intr/err test
=> [edn, dv] Fix a bug for edn intr/err test

sw/device/lib/runtime/print.c, sw/device/lib/runtime/print.h, sw/device/lib/runtime/print_unittest.cc
=> [sw, lib] Add a hexdump function in the style of xxd

hw/ip/flash_ctrl/doc/_index.md
=> [flash_ctrl] some language clarification

hw/ip/otbn/dv/rig/rig/gens/bad_bnmovr.py, hw/ip/otbn/dv/rig/rig/gens/bad_load_store.py, hw/ip/otbn/dv/rig/rig/gens/branch.py, hw/ip/otbn/dv/rig/rig/gens/branch_gen.py, hw/ip/otbn/dv/rig/rig/gens/edge_load_store.py, hw/ip/otbn/dv/rig/rig/gens/jump.py, hw/ip/otbn/dv/rig/rig/gens/known_wdr.py, hw/ip/otbn/dv/rig/rig/gens/loop.py, hw/ip/otbn/dv/rig/rig/gens/misaligned_load_store.py, hw/ip/otbn/dv/rig/rig/snippet_gen.py
Code now makes all the shape checks before returning the instruction
from mnemonic.
=> [otbn,dv] RIG Code Cleanup

hw/top_earlgrey/formal/conn_csvs/clkmgr_peri.csv
This PR fixed a duplicated naming error.
=> [conn] connectivity test naming fix

hw/ip/clkmgr/dv/clkmgr_sim.core, hw/ip/clkmgr/dv/clkmgr_sim_cfg.hjson, hw/ip/clkmgr/dv/env/clkmgr_env_pkg.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_common_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_extclk_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_trans_vseq.sv, hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr_sec_cm_testplan.hjson
=> [dv,clkmgr] sec cm testplan

hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
Added initial scoreboard extension for passthrough mode. Checks enabling of commands, filtering of commands and address translation. For now works for 3B addresses (the ones used in current tests).
=> [spi_device] Scoreboard for passthrough mode

hw/ip/aes/rtl/aes_control_fsm.sv
This reverts commit 8d507ad3f9dc47705b292a8e9568f73b772976ed.
=> Revert "[aes] Fix clearing of data input registers"

hw/ip/aes/dv/env/aes_scoreboard.sv, hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
relaxing the constraints showed a problem in the DV that is fixed with this PR
=> [aes/dv] fixed issue with env not discarding invalid items

hw/dv/sv/cip_lib/doc/index.md, hw/formal/README.md
This PR adds a section under formal README to document how to create a
FPV environment to test common security countermeasures.
=> [doc/fpv] Add doc on how to create a FPV security check env

hw/dv/sv/csrng_agent/csrng_agent.sv, hw/dv/sv/csrng_agent/csrng_agent_cfg.sv, hw/dv/sv/csrng_agent/csrng_if.sv, hw/ip/csrng/dv/tests/csrng_cmds_test.sv
Add ability to generate random genbits ready delays and associated coverage points.
=> [csrng/dv] Add random genbits ready delays

.gitignore, bazelisk.sh
1. Create downloader script.
2. Git ignore //.bin since we dont want to commit binaries to the codebase.
=> [bazel] Automate download of `bazelisk`

hw/ip/pwrmgr/data/pwrmgr_sec_cm_testplan.hjson, hw/ip/pwrmgr/data/pwrmgr_testplan.hjson, hw/ip/pwrmgr/dv/cov/pwrmgr_cov_bind.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv, hw/ip/pwrmgr/dv/pwrmgr_sim.core, hw/ip/pwrmgr/dv/pwrmgr_sim_cfg.hjson, hw/ip/pwrmgr/dv/sva/pwrmgr_bind.sv, hw/ip/pwrmgr/dv/sva/pwrmgr_sec_cm_checker_assert.sv, hw/ip/pwrmgr/dv/sva/pwrmgr_sva.core, hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr_sec_cm_testplan.hjson
=> [dv,pwrmgr] sec cm testplan

sw/device/lib/testing/BUILD, sw/device/lib/testing/keymgr_testutils.c, sw/device/lib/testing/keymgr_testutils.h, sw/device/lib/testing/meson.build, sw/device/tests/sim_dv/keymgr_key_derivation.c, sw/device/tests/sim_dv/meson.build
Created keymgr_testutils and moved these 2 functions to it, as Sri
suggested in #11493
- keymgr_advance_state
- keymgr_check_state
=> [dv top] Add keymgr_testutils

hw/ip/pwm/data/pwm_testplan.hjson, hw/ip/pwm/dv/env/pwm_scoreboard.sv
Added heartbeat mode, phase calculation and resolution to generate_exp_item task.
Signed-off-by: Jason Hoddinett <jason.hoddinett.ensilica@opentitan.org>
=> [pwm/scoreboard] Added heartbeat, phase and resolution

hw/ip/adc_ctrl/adc_ctrl.core, hw/ip/adc_ctrl/rtl/adc_ctrl_fsm.sv, hw/ip/adc_ctrl/rtl/adc_ctrl_pkg.sv
- this makes it easier for dv and others to re-use.
=> [adc_ctrl] move fsm package definition

hw/ip/edn/data/edn_testplan.hjson, hw/ip/edn/doc/dv/index.md, hw/ip/edn/dv/cov/edn_cov_bind.sv, hw/ip/edn/dv/cov/edn_cov_if.sv, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv
Addresses checked issues brought up at V2 review highlighted in Issue #11489 
- Fix formatting/link errors in the dv doc
- Add cross of num_endpoints/mode in edn_cfg_cg
- Remove "endpoint requests completed at various times" from edn_endpoints_cg
- Add cross between coverpoints in cs_cmds_cg
- Randomize csrng_req_bus to increase coverage
=> [edn/dv] Update testplan/checklist, add coverage

hw/ip/spi_device/pre_dv/tb/spid_upload_tb.sv
Revise direct testcase tB to add SRAM arbiter grant signal
=> [spi_device] Revise Upload TB to add grant ports

hw/ip/otbn/data/otbn.prj.hjson
At last! :-)
We've done all the tasks tracked in https://github.com/lowRISC/opentitan/issues/10705 (following up from the V2 review meeting) and last night our code coverage made it over the line:
=> [otbn] Declare V2

hw/ip/lc_ctrl/rtl/lc_ctrl.sv
=> [lc_ctrl] change the assert construction for clarity

hw/ip/spi_device/pre_dv/spid_readcmd.core, hw/ip/spi_device/pre_dv/spid_readcmd_sim_cfg.hjson, hw/ip/spi_device/pre_dv/tb/spid_common.sv, hw/ip/spi_device/pre_dv/tb/spid_readcmd_tb.sv
This PR implements the testcase for SPI_DEVICE SFDP command.
The return data is not correct. I will analyze the waveform and design then fix in following PRs.
=> [spi_device] Direct Testcase for SFDP

hw/ip/otbn/rtl/otbn.sv, hw/ip/otbn/rtl/otbn_core.sv
As suggested [here](https://github.com/lowRISC/opentitan/pull/11408#discussion_r826178349).
=> [otbn,rtl] Add a couple of consistency assertions about error bits

hw/ip/keymgr/data/keymgr.prj.hjson, hw/ip/keymgr/doc/checklist.md
=> [keymgr] Officially move to d2s

hw/ip/otp_ctrl/dv/otp_ctrl_sim_cfg.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson
=> [dv] Fix OTP and full chip OTP mem gen cmd

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
Add test for MP regions with full randomization of enable bits with overlapping regions.
=> [flash_ctrl] MP REGION TEST

hw/ip/rstmgr/data/rstmgr_sec_cm_testplan.hjson, hw/ip/rstmgr/dv/cov/rstmgr_cover.cfg, hw/ip/rstmgr/dv/env/rstmgr_env.core, hw/ip/rstmgr/dv/env/rstmgr_env_pkg.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_cnsty_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_shadow_attack_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_vseq_list.sv, hw/ip/rstmgr/dv/rstmgr_sim_cfg.hjson
- RSTMGR.LEAF.RST.BKGN_CHK
- RSTMGR.LEAF.RST.SHADOW
=> [rstmgr,dv] Add remaining sec cm items.

hw/dv/sv/csrng_agent/csrng_item.sv, hw/ip/csrng/data/csrng_testplan.hjson, hw/ip/csrng/doc/dv/index.md, hw/ip/csrng/dv/cov/csrng_cov_if.sv, hw/ip/csrng/dv/env/csrng_env_cfg.sv, hw/ip/csrng/dv/env/csrng_scoreboard.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
=> [csrng/dv] Update testplan/checklist, add coverage

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_stress_all_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_vseq_list.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.core
This pull request combines all sysrst_ctrl seqs in one seq to run sequentially.
=> [sysrst_ctrl,dv] Add sysrst_ctrl_stress_all test

hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_deinit_vseq.sv
Small update to support the newly added feature that made the IV readable.
the change adds a check that the IV is cleared correctly
=> [aes/dv] added read check for IV

hw/dv/tools/dvsim/xcelium.hjson, util/dvsim/utils.py
The first commit tidies up an error message. The second fixes my mistake that was causing it :-)
=> [dvsim,xcelium] Minor fixes

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
This commit adds a write to the cmd register whenever the otbn is
locked. The write is added in run_otbn task of otbn_base_vseq.
Fixes #11547 
=> [otbn, dv] Writes to the CMD register to start an operation when locked

hw/ip/spi_device/pre_dv/tb/spid_common.sv, hw/ip/spi_device/pre_dv/tb/spid_readcmd_tb.sv
- Add mis-algiend + boundary crossed SFDP commands
- Add get_sfdp_data() function to get the data from DPSRAM
Please ignore the first commit, as it is in #11833
=> [spi_device] Add data checker in spid_readcmd testbench

rules/cc_side_outputs.bzl, rules/opentitan.bzl, rules/scripts/clean_up_cpp_output.sh
=> [bazel] Add preproccessed files as a type of side-product

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh, hw/ip/clkmgr/data/clkmgr_testplan.hjson, hw/ip/clkmgr/dv/clkmgr_sim_cfg.hjson, hw/ip/clkmgr/dv/env/clkmgr_env_cfg.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/clkmgr/dv/tb.sv, hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr_sec_cm_testplan.hjson
=> [clkmgr,dv] add shaow reg auto test and fix auto test

hw/ip/pinmux/data/pinmux.hjson, hw/ip/pinmux/data/pinmux.hjson.tpl, hw/ip/pinmux/rtl/pinmux.sv, hw/ip/pinmux/rtl/pinmux_reg_pkg.sv, hw/ip/pinmux/rtl/pinmux_reg_top.sv, hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson, hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_pkg.sv, hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_top.sv
This enables software to have hjson-linked macros for accessing the
fields.
Signed-off-by: Alexander Williams <awill@google.com>
=> [pinmux] Promote pad attribute comment to fields

hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_repeat_wakeup_reset_vseq.sv
- pwrmgr_sec_cm_lc_ctrl_intersig_mubi : disalbe assertion
=> [dv,pwrmgr] fix regression failure

sw/device/silicon_creator/lib/sigverify/BUILD, sw/device/silicon_creator/mask_rom/BUILD, sw/device/silicon_creator/mask_rom/boot_policy_ptrs.h, sw/device/silicon_creator/mask_rom/mock_boot_policy_ptrs.cc, sw/device/silicon_creator/mask_rom/mock_boot_policy_ptrs.h, sw/device/silicon_creator/mask_rom/mock_sigverify_keys_ptrs.cc, sw/device/silicon_creator/mask_rom/mock_sigverify_keys_ptrs.h, sw/device/silicon_creator/mask_rom/sigverify_keys.c, sw/device/silicon_creator/mask_rom/sigverify_keys_ptrs.h
Child of https://github.com/lowRISC/opentitan/pull/11850
=> [bazel] Merge mock targets in mask_rom

hw/ip/adc_ctrl/rtl/adc_ctrl_intr.sv
- fixes #11759
- switch to prim_reqack instead of prim_pulse_sync
- since many events can occur during low power, split
the sync source into staging and request.
=> [adc_ctrl] Fix adc interrupt synchronization

hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/pattgen/rtl/pattgen.sv, hw/ip/pwm/rtl/pwm.sv, hw/ip/sysrst_ctrl/rtl/sysrst_ctrl.sv, hw/ip/uart/rtl/uart.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
=> [all] Add assertions for constant output enables 

sw/device/info_sections.ld, sw/device/silicon_creator/lib/BUILD, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/mock_rom_ext_boot_policy_ptrs.cc, sw/device/silicon_creator/rom_ext/mock_rom_ext_boot_policy_ptrs.h, sw/device/silicon_creator/rom_ext/rom_ext_boot_policy_ptrs.h, sw/device/silicon_creator/rom_ext/rom_ext_common.ld, sw/device/silicon_creator/rom_ext/rom_ext_epmp.c
Fixes https://github.com/lowRISC/opentitan/issues/11498.
Child of https://github.com/lowRISC/opentitan/pull/11856 and https://github.com/lowRISC/opentitan/pull/11830.
=> [bazel] Bazelize the ROM_EXT

sw/device/info_sections.ld
=> [sw] Fix spelling mistake in a comment

sw/device/silicon_owner/bare_metal/BUILD, sw/device/silicon_owner/bare_metal/bare_metal_common.ld
Fixes https://github.com/lowRISC/opentitan/issues/11497
=> [bazel] Bazelize the example BL0

hw/dv/sv/csr_utils/csr_seq_lib.sv, hw/dv/sv/dv_utils/dv_macros.svh, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.sv, hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_common_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_gpio_vseq.sv, hw/top_earlgrey/dv/tb/tb.sv, hw/top_earlgrey/dv/tests/chip_base_test.sv
Some basic fixes including increased timeout, CPU clock delays
testplan mapping fix etc.
=> [chip dv] Fixes for tests failing in nightly

hw/ip/csrng/dv/sva/csrng_assert_if.sv
- Turn off the assertions that fired unexpectedly
=> [csrng, dv] Fix the assertion fail issue

hw/ip/sysrst_ctrl/dv/cov/sysrst_ctrl_cov.core, hw/ip/sysrst_ctrl/dv/cov/sysrst_ctrl_cov_bind.sv, hw/ip/sysrst_ctrl/dv/cov/sysrst_ctrl_cov_if.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_in_out_inverted_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_pin_override_vseq.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_cov.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim.core, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson, hw/ip/sysrst_ctrl/dv/tb.sv
=> [sysrst_ctrl,dv] Add sysrst_ctrl functional coverage

third_party/riscv-compliance/defs.bzl
=> [bazel] Fix riscv-compliance rule imports

hw/ip/sysrst_ctrl/data/sysrst_ctrl.hjson
=> [sysrst_ctrl,dv] Remove CSR excl for KEY_INTR_STATUS register

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_base_vseq.sv
Due to merging of these 2 PR - #11823 and #11770
=> [flash, dv] Fix CI failures

doc/getting_started/setup_verilator.md
This is simpler and has the benefit of matching what we do in CI (so
we know it will continue to work).
=> [doc] Simplify example for building the Verilator model

hw/ip/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_shadow_attack_vseq.sv, hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr_sec_cm_testplan.hjson
- add normal glitch shadow check.
- update sec_cm_testplan under top_earlgrey/ip
=> [rstmgr,dv] leaf_rst_shadow test update

hw/top_earlgrey/dv/env/seq_lib/chip_sw_spi_tx_rx_vseq.sv, sw/device/tests/sim_dv/spi_tx_rx_test.c
The wait time isn't enough now. Changed to wait for an msg event
=> [top, dv] Fix spi test failure

hw/ip/lc_ctrl/data/lc_ctrl_sec_cm_testplan.hjson
This addresses #11731 and #11919.
=> [lc_ctrl] Add more details to countermeasure testplan

sw/device/silicon_creator/lib/drivers/spi_device.c, sw/device/silicon_creator/lib/drivers/spi_device.h, sw/device/silicon_creator/lib/drivers/spi_device_unittest.cc
This PR adds `spi_device_cmd_get()` and configures READ_STATUS, CHIP_ERASE, SECTOR_ERASE, PAGE_PROGRAM, and RESET commands.
@cfrantz, This PR rounds up the payload size to next word boundary as we discussed since flash_ctrl interface is word-based. I don't think we want/need to support other (misaligned) cases, at least right now. @a-will PLMK if this sounds like a reasonable limitation to reduce overall complexity.
Related issues:
* #11869
* #11871
* #11782
=> [sw/silicon_creator] Add spi_device_cmd_get() and commands handled in sw

sw/device/lib/dif/BUILD, sw/device/lib/dif/dif_pinmux.c, sw/device/lib/dif/dif_pinmux.h, sw/device/lib/dif/dif_pinmux.md, sw/device/lib/dif/dif_pinmux_unittest.cc, sw/device/lib/dif/meson.build
Add DIFs for input and output muxes, sleep states, and wakeup detectors.
Signed-off-by: Alexander Williams <awill@google.com>
=> [pinmux/dif] Implement most pinmux DIFs

hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/rtl/kmac_reg_top.sv
- this ensures these values cannot change during an operation
- addresses #11751
=> [kmac] Add regwen to prefix and key registers for kmac

hw/ip/otbn/rtl/otbn_core.sv
=> [otbn, dv] Removes stray lines in otbn_core

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/data/flash_ctrl_sec_cm_testplan.hjson, hw/ip/flash_ctrl/doc/_index.md, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
- see https://github.com/lowRISC/opentitan/issues/11675
=> [flash_ctrl] address the d2s documentation items

hw/ip/sysrst_ctrl/data/sysrst_ctrl_testplan.hjson
This pull request will update the testplan
to include new additional requirements.
It includes the stress_all test. 
It has new covergroups for debounce, status registers.
=> [sysrst_ctrl,dv] Updated the testplan

hw/ip/tlul/rtl/tlul_lc_gate.sv, hw/ip/tlul/tlul_lc_gate.core
=> [tlul_lc_gate] Use prim_blanker instead of muxes and buffers

sw/device/silicon_owner/bare_metal/BUILD
=> [bazel] Format a file

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/meson.build, sw/device/tests/rstmgr_sw_rst_ctrl_test.c
This test checks rstmgr.sw_rst_ctrl_n[] with peripheral devices.
=> [chip,dv,rstmgr] chip_sw_rstmgr_sw_rst

sw/device/lib/base/macros.h, sw/device/sca/BUILD, sw/device/sca/aes_serial.c, sw/device/sca/lib/BUILD, sw/device/sca/lib/sca.c, sw/device/sca/lib/sca.h, sw/device/sca/sha3_serial.c
Fixes: https://github.com/lowRISC/opentitan/issues/11509
Alphan, would you mind checking this is a sensible setup?
=> [bazel] Bazelize the SCA targets

WORKSPACE, third_party/README.md
=> [bazel] Add a //third_party readme

hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
This fixes an oversight on my end (inconsistent token mux select signals did not trigger this error before).
This should not cause functional V2 tests to break.
=> [lc_ctrl] Ensure inconsistent token mux triggers TRANSITION_ERROR

hw/ip/entropy_src/rtl/entropy_src_core.sv
The entropy_data and observe FIFOs are cleared with the entropy_src
is disabled, but any interrupts saying they have data must be
cleared by FW.
As noted in issue #11951, there is also a delay between when the
IP is disabled and the FIFO is cleared.  This means that
even when FIFO interrupts are cleared after disabling, the interrupt
can reassert itself in this brief delay period.
This PR therefore suppresses these interrupt events from
retriggering when the IP is disabled.
=> [entropy_src/rtl] Suppress re-assertion of interrupts

hw/dv/sv/cip_lib/cip_base_scoreboard.sv, hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh, hw/dv/sv/cip_lib/seq_lib/cip_tl_seq_item.sv, hw/dv/tools/dvsim/testplans/tl_device_access_types_testplan.hjson
=> [dv] Add a TL error case - write with instr_type = True

hw/ip/otp_ctrl/data/otp_ctrl.prj.hjson, hw/ip/otp_ctrl/doc/checklist.md
This PR updates the checklist for OTP_CTRL and signoff on project
status.
=> [dv/otp] OTP_CTRL V2S signoff

hw/ip/clkmgr/dv/env/clkmgr_env_pkg.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_frequency_timeout_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_frequency_vseq.sv
A new bit was added in this CSR, which caused failures in frequency
measurements.
=> [dv/clkmgr] Fix handling recov_err_code CSR

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fetch_code_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
Verify the Code Fetch Feature.
The reading of data via the Hardware Interface, can be allowed or denied, dependent
on an Execution Key, written via a register.
=> [flash_ctrl] ADD TEST FOR THE FETCH CODE FUNCTIONALITY

hw/dv/sv/spi_agent/spi_monitor.sv, hw/ip/spi_host/data/spi_host_testplan.hjson, hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_performance_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_smoke_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_speed_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv, hw/ip/spi_host/dv/env/spi_host_env.core, hw/ip/spi_host/dv/env/spi_host_env.sv, hw/ip/spi_host/dv/env/spi_host_env_cfg.sv, hw/ip/spi_host/dv/env/spi_host_env_cov.sv, hw/ip/spi_host/dv/env/spi_host_env_pkg.sv, hw/ip/spi_host/dv/env/spi_host_scoreboard.sv, hw/ip/spi_host/dv/env/spi_passthrough_if.sv, hw/ip/spi_host/dv/env/spi_segment_item.sv, hw/ip/spi_host/dv/tb.sv
- Added Speed Test
- Added Constraints to Segment Item
- Added Quad And Dual To Device Resp Seq
- Added Tag For Cover Points To Speed Test
- Added Sw Reset Test
- Added Performance Test
- Added Spi Monitor Update Dual And Quad Mode
=> [spi_host/dv] coverage branch

hw/ip/prim/lint/prim_cdc_rand_delay.vlt, hw/ip/prim/prim_cdc_rand_delay.core
=> [prim] Stub out guts of prim_cdc_rand_delay for Verilator

hw/ip/prim/lint/prim_onehot_check.vlt, hw/ip/prim/lint/prim_onehot_check.waiver, hw/ip/prim/prim_onehot_check.core
=> [prim_onehot_check] Add lint waivers

hw/ip/spi_device/rtl/spi_device.sv, hw/ip/spi_device/rtl/spid_upload.sv
Add last written payloadptr and overflow event and synchronization logic
to SYS clock domain.
This PR is the first of multiple changes in SPI_DEVICE. As the logic will add a few CSRs and an interrupt, DV should be aware of this.
=> [spi_device] Add payloadptr (last written) and overflow event

hw/ip/spi_device/data/spi_device_testplan.hjson
Functional coverage proposal for flash and passthrough modes.
Added merged tests to hjson file to be mapped.
=> [spi_device] Functional coverage flash and pass

hw/ip/adc_ctrl/rtl/adc_ctrl_fsm.sv
- fixes #11784
- The original intent of the spec was not clear whether periodic scanning
should trigger on any match or specific debounced matches.
- After going through some of the older documentations, there is no clear
evidence that "any" was needed, as a result, switch the design to
debounced checks.
=> [adc_ctrl] Periodic scanning fix

hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.hjson, hw/top_earlgrey/ip/sensor_ctrl/doc/_index.md
=> [sensor_ctrl] Minor documentation update

hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_pkg.sv, hw/ip/otbn/rtl/otbn_start_stop_control.sv
This was actually motivated by the fix that appears in the second commit. But getting that right means that the start/stop controller needs to know that we've stopped.
=> [otbn,rtl] Start/stop controller escalation

hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.hjson, hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv, hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_pkg.sv, hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_top.sv, hw/top_earlgrey/ip/sensor_ctrl/sensor_ctrl.core, hw/top_earlgrey/ip_autogen/rv_plic/data/rv_plic.hjson, hw/top_earlgrey/ip_autogen/rv_plic/data/top_earlgrey_rv_plic.ipconfig.hjson, hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic.sv, hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_reg_pkg.sv, hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_reg_top.sv, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_earlgrey/sw/autogen/top_earlgrey.c, hw/top_earlgrey/sw/autogen/top_earlgrey.h, sw/device/lib/dif/autogen/dif_sensor_ctrl_autogen.c, sw/device/lib/dif/autogen/dif_sensor_ctrl_autogen.h, sw/device/lib/dif/autogen/dif_sensor_ctrl_autogen_unittest.cc, sw/device/lib/dif/dif_rv_plic_unittest.cc, sw/device/lib/testing/autogen/isr_testutils.c, sw/device/lib/testing/autogen/isr_testutils.h, sw/device/lib/testing/autogen/meson.build, sw/device/tests/autogen/meson.build, sw/device/tests/autogen/plic_all_irqs_test.c
First seven commits will be rebased away. 
Dependent on #12074 and #12079
=> [sensor_ctrl] Add IO status change as an interrupt

doc/getting_started/setup_fpga.md
=> [doc] Update documentation for downloading bitstreams from GCP

hw/top_earlgrey/dv/env/ast_supply_if.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_full_aon_reset_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_main_power_glitch_vseq.sv
Incorporate fix for issue #12048.
=> [dv,full_chip,pok] Fix generation of pok glitch

hw/ip/tlul/rtl/tlul_err.sv
=> [tlul] Generate instruction type error from reg also

azure-pipelines.yml, ci/scripts/quick-bazel.sh, sw/device/examples/hello_world/BUILD, sw/device/lib/base/BUILD, sw/device/lib/testing/BUILD, sw/device/tests/BUILD, sw/host/rom_ext_image_tools/signer/image/BUILD, third_party/bazel_embedded/repos.bzl, third_party/lint/repos.bzl
This is https://github.com/lowRISC/opentitan/pull/11922 but re-filed by me, since Drew is currently out on vacation and landing this earlier is nice.
AIUI this is ready to merge as-is. I've made sure to maintain Drew's authorship on the commit.
=> [bazel] Run software unit-tests in CI

hw/ip/prim/lint/prim_cipher.vlt, hw/ip/prim/prim_cipher.core
=> [prim_present] Add Verilator lint waiver

hw/ip/clkmgr/doc/_index.md, hw/ip/lc_ctrl/doc/_index.md
=> [doc] Clarify lc requested external clock switch

hw/ip/aes/data/aes.prj.hjson
Update the AES checklist DIF to S2
=> [dif, aes] Update the check list to S2

hw/ip/spi_device/pre_dv/tb/spid_common.sv, hw/ip/spi_device/pre_dv/tb/spid_upload_tb.sv
This commit revises the pre_dv upload direct testcase to test the
payload greater than 256B.
=> [spi_device] Revise Upload Pre DV to test payload > 256B

hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv, sw/device/lib/dif/BUILD, sw/device/lib/dif/dif_sensor_ctrl.c, sw/device/lib/dif/dif_sensor_ctrl.h, sw/device/lib/dif/dif_sensor_ctrl_unittest.cc, sw/device/lib/dif/meson.build
- also minor fix on wakeup request filtering
=> [sw, sensor_ctrl] First draft of sensor_ctrl DIF / unittest

hw/ip/clkmgr/data/clkmgr.sv.tpl, hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
=> [clkmgr] Connect prim count failure to right alert

hw/ip/spi_device/doc/_index.md, hw/ip/spi_device/rtl/spid_upload.sv
This PR cleans up the code and spec for the recent changes (Payload Index and Overflow).
Please take a look at last two commits only.
=> [spi_device] clean up

hw/ip/aes/data/aes_testplan.hjson, hw/ip/aes/dv/aes_base_sim_cfg.hjson, hw/ip/aes/dv/env/aes_env.core, hw/ip/aes/dv/env/aes_env_cfg.sv, hw/ip/aes/dv/env/seq_lib/aes_reseed_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_vseq_list.sv, hw/ip/aes/dv/sva/aes_bind.sv, hw/ip/aes/dv/sva/aes_masking_reseed_if.sv, hw/ip/aes/dv/sva/aes_reseed_if.sv, hw/ip/aes/dv/sva/aes_sva.core, hw/ip/aes/dv/tb/tb.sv, hw/ip/aes/dv/tests/aes_reseed_test.sv, hw/ip/aes/dv/tests/aes_test.core, hw/ip/aes/dv/tests/aes_test_pkg.sv
- Add a sequence to test the PRNG reseeding of AES module
- Verifify the PRNG is correctly reseeded at the specified rate
=> [aes, dv] Test AES PRNG reseeding

hw/top_earlgrey/cdc/cdc_waivers.uart.tcl
Add W_DATA waiver for the path from tx_out to PINMUX
=> [uart] Add UART Waiver

hw/ip/keymgr/dv/env/seq_lib/keymgr_sideload_one_intf_vseq.sv
This macro has been changed. Need to add another argument
=> [keymgr, dv] fix DV_GET_ENUM_PLUSARG input args

hw/ip/otbn/doc/_index.md
=> [otbn] Document type of local PRNG used for URND

hw/ip/prim/prim_cdc_rand_delay.core, hw/ip/prim/rtl/prim_cdc_rand_delay.sv
=> [prim] Add dv_macros missing dependency

hw/ip/spi_device/pre_dv/tb/spid_common.sv, hw/ip/spi_device/pre_dv/tb/spid_status_tb.sv
This commit revises the spid_status pre_dv to test WREN/ WRDI/ SW update
of STATUS CSR.
=> [spi_device] Update Status TB to test WREN/ WRDI

doc/getting_started/setup_verilator.md
=> [doc] Minor fix in Verilator docs

hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
It has been found that the detection window for unstable RMA bits is very short (just 2 cycles, see #11874).
This patch makes the check more robust by extending the token check window from 2 to 4 cycles, and by introducing a background check for the RMA signals during the programming phase.
=> [lc_ctrl] Make RMA and token checks more robust

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/meson.build, sw/device/tests/pwrmgr_sleep_disabled_test.c
=> [dv,full_chip] Add test chip_sw_pwrmgr_sleep_disabled

azure-pipelines.yml
This is not supported in Bazel (and won't be for the foreseeable future).
=> [ci] Don't build embedded code with GCC

hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
=> [lc_ctrl] Correct escalation logic

doc/getting_started/setup_verilator.md
This appears to have gotten out of date...
=> [doc] Correct Verilator invocation path

sw/device/silicon_creator/lib/epmp_unittest.cc
=> [silicon_creator] Fix warnings and clean up epmp_unittest.cc

hw/ip/lc_ctrl/lc_ctrl.core, hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_signal_decode.sv, hw/top_earlgrey/formal/top_earlgrey_fpv_cfgs.hjson
=> [lc_ctrl] Add linear control flow SVA property

hw/dv/sv/sim_sram/sim_sram.sv
=> [dv] Fix Xcelium compile error in chip-level

azure-pipelines.yml, ci/scripts/whitespace.sh, util/fix_trailing_whitespace.py
The check is incremental, so we can fix bits and pieces of the tree as they come up.
=> [ci] Add a script for checking whitespace endings of files

hw/ip/prim/rtl/prim_onehot_check.sv
For some reason the initial fix was not enough for AscentLint.
=> [prim_onehot_check] Rework lint fix

hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_comboact.sv, hw/top_earlgrey/data/chip_testplan.hjson
=> [sysrst_ctrl] Refine GSC reset behavior and associated testplan item

hw/ip/pwrmgr/rtl/pwrmgr_slow_fsm.sv
=> [pwrmgr] Force clocks on when slow fsm is invalid

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
=> [flash_ctrl] Update the shadow alert assignment

hw/ip/flash_ctrl/doc/_index.md
=> [flash_ctrl/docs] Fix a few typos

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
This commit adds random writes with 25% probability and reads with
50% probability to err_bits when otbn is idle.
=> [otbn, dv] Adds random writes and reads to err_bits when otbn is idle

hw/ip/adc_ctrl/doc/checklist.md
=> [adc_ctrl/dv] Updated checklist for V2

hw/dv/tools/vcs/cover.cfg
The assertions are under substructure, so I change it from module to
moduletree.
=> [dv/vcs] Update cdc exclusion keyword

hw/ip/kmac/kmac.core
=> [kmac] Include comportable IP waivers

hw/ip/flash_ctrl/data/flash_ctrl.prj.hjson, hw/ip/flash_ctrl/doc/checklist.md
All D2S items have now been completed: https://github.com/lowRISC/opentitan/issues/11675
Therefore we can move it to D2S.
=> [flash_ctrl] Move to D2S

hw/ip/flash_ctrl/rtl/flash_phy_core.sv
=> [flash_ctrl] RTL fix for DC elab failure

hw/ip/adc_ctrl/data/adc_ctrl.prj.hjson
- Updated adc_ctrl.prj.hjson
- verification_stage: "V2S"
=> [adc_ctrl/dv] Moved project to V2S

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_ctrl_arb_vseq.sv
=> [flash_ctrl/dv] Update test on rma boundary handling

sw/device/lib/dif/dif_sysrst_ctrl.h
This completes the System Reset Controller DIF library API by adding the following features to the header:
1. configuration, getter, and setter DIFs for pin inversion, override, and read features, and
2. configuration, getter, and setter DIFs for the Ultra-Low-Power (ULP) wakeup feature.
**_Note: this depends on #12303._**
=> [dif/sysrst_ctrl] Add remaining DIFs to header.

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/meson.build, sw/device/tests/rstmgr_alert_info_test.c
=> [dv,top,rstmgr] top rstmgr alert_info test

doc/rm/_index.md
This is just a note to suggest a policy that I've found helpful in streamlining code review in the past.
=> [docs] Added a note regarding preference for enforced style guides

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_jtag_mem_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
=> [dv,top,jtag] jtag memory access test

hw/dv/sv/csr_utils/csr_utils_pkg.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
This PR has two commits:
1). Clean up some error message regarding mem_rd/wr
2). Increase smoke test reseed number in flash_ctrl nightly regression.
=> [dv] Small clean ups

hw/ip/keymgr/keymgr.core, hw/ip/keymgr/rtl/keymgr_ctrl.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv, hw/ip/prim/rtl/prim_assert.sv, hw/top_earlgrey/formal/top_earlgrey_fpv_cfgs.hjson
This creates a macro for the linear control flow SVA that we have added to the life cycle controller, and adds that SVA to the keymgr also (since that FSM has the same properties).
=> Keymgr linear fsm

hw/ip/spi_device/rtl/spi_p2s.sv
This commit addresses the issue #12342.
As dummy cycle may not be byte granularity, the output logic `spi_p2s`
now runs only when `data_valid_i` is high.
Now, `data_sent_o` is asserted when `data_valid_i` is high. The
data_sent_o is high based on the io_mode to compare `cnt` with the
correct value. The logic increases `cnt` only when `data_valid_i` is
high.
As `last_beat` is not asserted anymore, the `io_mode` does not latch
`io_mode_i` at `last_beat`. The logic uses `io_mode_i` directly. It is
OK as spi_device top latches comb logic io_mode at @ iSCK.
=> [spi_device] spi_p2s to run only when `data_valid`

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_edge_detect_vseq.sv
=> [sysrst_ctrl,dv] Randomize clock gating to check interrupt

hw/ip/spi_device/pre_dv/tb/spid_common.sv, hw/ip/spi_device/pre_dv/tb/spid_readcmd_tb.sv
This commit revises check_data() to check the received and expected
sizes then added `spiflash_read()` task to issue read commands.
It has configurations to send multiple variations of read commands.
Configurable knobs are: address size, dummy size, # of read lines
(Single, Dual, Quad).
This PR includes #12317  Please review the second commit only (pre_dv)
=> [spi_device] Adding wrapper function for SPIFlash read command

hw/ip/otbn/data/otbn.hjson, hw/ip/otbn/data/otbn_sec_cm_testplan.hjson, hw/ip/otbn/otbn.core, hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_rf_base.sv, hw/ip/otbn/rtl/otbn_rf_base_ff.sv, hw/ip/otbn/rtl/otbn_rf_base_fpga.sv, hw/ip/otbn/rtl/otbn_rf_bignum.sv, hw/ip/otbn/rtl/otbn_rf_bignum_ff.sv, hw/ip/otbn/rtl/otbn_rf_bignum_fpga.sv
=> [otbn] Add spurious WE check to regfiles

doc/project/checklist.md
Draft for updated IP_INSTANTIABLE item - to be discussed in the TC.
This also fixes a bunch of typos.
Addresses #91.
=> [doc] Refine description of D1 checklist item IP_INSTANTIABLE

hw/ip/prim/rtl/prim_clock_div.sv, hw/top_earlgrey/ip/ast/lint/ast.waiver, hw/top_earlgrey/ip/ast/rtl/aon_osc.sv, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv, hw/top_earlgrey/ip/ast/rtl/io_osc.sv, hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv, hw/top_earlgrey/ip/ast/rtl/sys_osc.sv, hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
This fixes all remaining AST lint errors either by patching the RTL, or by adding / updating the waivers.
=> [ast] Lint fixes and waiver updates

hw/ip/kmac/rtl/kmac_entropy.sv
This should fix two lint errors in AscentLint that I've recently introduced. Since I don't have the tool, I would need someone to check the lint errors indeed go away.
=> [kmac] Fix AscentLint errors

hw/top_earlgrey/data/chip_testplan.hjson
Added some clarification and added testpoints for DFT SW straps
=> [dv, chip] Update testplan for chip_sw_tap_strap_sampling

hw/ip/otbn/rtl/otbn.sv
The previous assertion that I wrote was a bit too strong. Document
what's supposed to happen a bit more clearly in a comment and fix up
the assertions.
=> [otbn,rtl] Fix some assertions about state signals

doc/getting_started/setup_fpga.md
Wanted to suggest a workflow that resolved a problem quickly on my end,
and give a more detailed explanation of how to view errors.
Removed "$"s from console blocks for better copying and pasting. (Not that that's something you should do)
=> [docs] CW310 may need intervention to properly connect to workstation

hw/ip/pattgen/data/pattgen_testplan.hjson
=> [pattgen,dv] Update pattgen cov plan

hw/top_earlgrey/dv/chip_sim_cfg.hjson
A lower baudrate may be selected, need to increase timeout timer
=> [top, dv] Fix uart test timeout

hw/dv/tools/dvsim/sim.mk
This fixes #11562 by update dvsim.py to build ROM images with bazel.
Note, flash images are still built with meson, and will be transitioned
to bazel in a future PR.
=> [bazel] update dvsim.py to build ROMs with bazel

hw/ip/pwrmgr/dv/env/pwrmgr_if.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_common_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_glitch_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_reset_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv
- update tb to expected fatal alert for MAIN_PD_GLITCH
- adjust reset status check
- clean up rom check driver
=> [pwrmgr,dv] regression fix

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/cov/flash_ctrl_cov.core, hw/ip/flash_ctrl/dv/cov/flash_ctrl_cov_bind.sv, hw/ip/flash_ctrl/dv/cov/flash_ctrl_cov_if.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cov.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim.core, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
Add covergroups for functional coverage defined in Testplan.
=> [flash_ctrl]: ADD FUNCTIONAL COVERAGE

hw/ip/sysrst_ctrl/doc/dv/index.md
=> [sysrst_ctrl,dv] Updated SYSRST_CTRL DV documents

hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_mem_addr_attrs.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_erase_suspend_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_fetch_code_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_full_mem_access_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_buff_evict_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_smoke_hw_vseq.sv
Hi,
This PR is mainly about ordering the usage of the data and address local types with some small other updates related the memory model usage that required by the CS env and some small other fixes.
Thanks!
=> [flash_ctrl/dv] Ordering data types and some CS model related updates

hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
This includes the following updates:
1] Break up the mid-range bins into more bins for the counters
2] Added the missing covergroup
3] Match the covergroup names with the testplan
=> [pattgen,dv] Improve pattgen coverage for V2 milestone

hw/ip/spi_device/rtl/spid_readbuffer.sv
The first commit belongs to #12431 Please review last two commits.
**[spi_device] Update flip/ watermark ONLY when active**
This commit revises the readbuffer module behavior. The module updates
and reports the flip/ watermark events only when active.
The active signal represents the exact time the buffer needs to be
updated. The signal comes from the upper module `readcmd`. It is a pulse
signal that represents the last beat of a byte. (e.g the second beat in
Quad mode).
**[spi_device] Watermark and Flip handling**
This commit revises the watermark logic to handle the corner case
correctly. The case is when `watermark` and `flip` both events occur at
the same cycle.
If both events happen at the same cycle, it means host system issues a
read request to the next buffer above the threshold. …
=> [spi_device] Fix watermark/ flip event in Read Buffer.

hw/ip/pattgen/doc/dv/index.md
=> [pattgen,dv] Updated pattgen DV document

hw/ip/prim/rtl/prim_assert.sv
See https://github.com/lowRISC/opentitan/pull/12365#discussion_r864317608
=> [prim_assert] Minor rewording in comment

hw/ip/pattgen/dv/env/seq_lib/pattgen_cnt_rollover_vseq.sv
=> [pattgen,dv] Improve pattgen count rollover test

hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
=> [top] Chip rev/gen update

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
Perform accesses in order to provoke the 'program type' error.
Test via the Software interface
=> [flash_ctrl] ADD TEST FLASH CTRL ERROR PROG TYPE

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_vseq.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_if.sv
=> [sysrst_ctrl,dv] Fix combo detect test

sw/host/opentitanlib/src/image/image.rs, sw/host/opentitantool/src/command/image.rs
Implementation for the `opentitantool image digest` command. Given an input image this command will produce a digest for the signed region of that image.
=> [opentitantool] Implement image digest command

hw/ip/spi_device/pre_dv/program/prog_passthrough_host.sv, hw/ip/spi_device/pre_dv/program/prog_passthrough_sw.sv, hw/ip/spi_device/pre_dv/program/prog_spiflash.sv, hw/ip/spi_device/pre_dv/program/spiflash.sv, hw/ip/spi_device/pre_dv/spid_passthrough.core, hw/ip/spi_device/pre_dv/tb/spid_common.sv, hw/ip/spi_device/pre_dv/tb/spid_passthrough_tb.sv
This PR scaffolds the SPI Flash behavioral model to test passthrough logic. It only has the command opcode receiver as of now.
=> [spi_device] SPI Flash Behavioral Model Skeleton

sw/device/tests/BUILD
=> [sw, test] Add missing otbn_randomness Bazel test

hw/ip/clkmgr/rtl/clkmgr_trans.sv
- Address issue brought up in #12274
=> [clkmgr] De-couple idle count from mubi

hw/ip/sysrst_ctrl/dv/cov/sysrst_ctrl_cov_if.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_auto_blk_key_output_vseq.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv
=> [sysrst_ctrl,dv] Change sampling cond of func cov

hw/top_earlgrey/data/chip_testplan.hjson
Add more descriptions to clarify `lc_ctrl_transition` test and
`lc_walkthough` test.
=> [dv/chip] Update chip level testplan

sw/device/tests/rstmgr_sw_rst_ctrl_test.c
=> [dv,top,rstmgr] rstmgr_sw_rst_ctrl_test reg fix

hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_flash_rma_unlocked_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_ctrl_transition_vseq.sv
This PR moves the commonly used `get_otp_token` task to base_vseq, and
rename to better reflect its purpose.
=> [dv/chip] Move common test to base sequence

hw/ip/pwm/data/pwm_testplan.hjson, hw/ip/pwm/dv/env/pwm_env.core, hw/ip/pwm/dv/env/seq_lib/pwm_perf_vseq.sv, hw/ip/pwm/dv/env/seq_lib/pwm_vseq_list.sv, hw/ip/pwm/dv/pwm_sim_cfg.hjson
A simple test designed to cover the perf testpoint within the testplan.
Signed-off-by: Jason Hoddinett <jason.hoddinett.ensilica@opentitan.org>
=> [pwm/pwm_perf_vseq] Created a sequence to test performance

hw/ip/adc_ctrl/rtl/adc_ctrl.sv, hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_comboact.sv, hw/top_earlgrey/data/chip_testplan.hjson, sw/host/opentitanlib/src/transport/hyperdebug/c2d2.rs
=> [hw,sw,docs] redact acronyms

hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/seq_lib/chip_sw_main_power_glitch_vseq.sv, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/pwrmgr_sleep_power_glitch_test.c
=> [dv,top,pwrmgr] fix pwrmgr_sleep_power_glitch_reset regression failure

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
Perform accesses in order to provoke the 'program resolution' error.
Test via the Software interface.
=> [flash_ctrl] ADD TEST FLASH CTRL ERROR PROG WIN

hw/dv/tools/vcs/cover_reg_top.cfg
It was only removed in cover.cfg
Need to remove it in cover_reg_top as well
=> [dv] Temporarily remove CDC assertions

hw/ip/spi_device/pre_dv/program/prog_passthrough_host.sv, hw/ip/spi_device/pre_dv/program/spiflash.sv, hw/ip/spi_device/pre_dv/tb/spid_passthrough_tb.sv
This commit implements Read Command in SPIFlash behavioral model. Host
now reads twice and compare the data.
=> [spi_device] Add Read Cmd to SPIFlash

hw/ip/spi_host/rtl/spi_host_fsm.sv
This commit fixes several small bugs found when CPHA = 1, which delays
the assertion of SD data by 1/2 SCK cycle.  Problems exist when
the shift register receives the delayed control pulses, but
other control signals have been updated prematurely.  This
commit solves the problem by maintaining delayed copies more
required signals such as speed and byte counts.
Fixes #12262
=> [spi_host/rtl] Improve handling of CPHA=1 transactions

hw/ip/otbn/dv/tracer/rtl/otbn_trace_if.sv, hw/ip/otbn/dv/tracer/rtl/otbn_tracer.sv, hw/ip/otbn/dv/uvm/sva/otbn_idle_checker.sv, hw/ip/otbn/rtl/otbn.sv, hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_start_stop_control.sv
These are all fall-out from the "simple", "obviously correct" timing rejig that I did in 48e4bb6. Aargh!
=> [otbn] Fix a glitch in locking signal and then a couple of bogus assertions

azure-pipelines.yml, ci/jobs/quick-lint.sh, ci/jobs/slow-lint.sh
These checks take around 4-5 minutes to run on each PR before the rest of CI starts.
=> [ci] Move verible checks to slow-lint

hw/ip/rom_ctrl/util/mem.py, hw/ip/rom_ctrl/util/scramble_image.py, hw/top_englishbreakfast/util/prepare_sw.py, util/design/lib/common.py, util/dvsim/dvsim.py, util/fix_trailing_whitespace.py, util/reggen/gen_tock.py
Just stumbled over these lint messages and thought I'll clean them up...
=> [python] flake8 lint cleanups

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv
This pull request has updates to ultra low power test which will improve the FSM coverage.
=> [sysrst_ctrl,dv] Fix ultra low pwr test to improve fsm cov

azure-pipelines.yml, ci/scripts/run-fast-verilator-tests.sh, ci/scripts/run-slow-verilator-tests.sh, rules/opentitan_test.bzl
This PR implements the workarounds in #12603.
=> [ci] Temporary workarounds for Verilator test flakiness

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/doc/_index.md, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
- clarify documentation for #12600
=> [doc/flash_ctrl] Clarify memory protection matching mechanism

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/chip_env.sv, hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwrmgr_deep_sleep_all_wake_ups_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, hw/top_earlgrey/dv/tb/tb.sv, sw/device/lib/dif/dif_adc_ctrl.c, sw/device/lib/dif/dif_adc_ctrl_unittest.cc, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/meson.build, sw/device/tests/sim_dv/pwrmgr_deep_sleep_all_wake_ups.c
=> [dv,top,pwrmgr] pwrmgr deep sleep all wakeups test

sw/device/lib/crypto/drivers/aes_test.c, sw/device/lib/testing/test_framework/check.h, sw/device/tests/aes_entropy_test.c
=> [lib] Delete CHECK_BUFFER macros

hw/ip/otbn/dv/model/otbn_model.cc, hw/ip/otbn/dv/model/otbn_model_dpi.h, hw/ip/otbn/dv/model/otbn_model_dpi.svh, hw/ip/otbn/dv/uvm/env/otbn_loop_if.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv, hw/ip/otbn/dv/uvm/otbn_model_agent/otbn_model_if.sv, hw/ip/otbn/dv/uvm/tb.sv, hw/ip/otbn/dv/verilator/otbn_top_sim.cc, hw/ip/otbn/dv/verilator/otbn_top_sim_waivers.vlt, hw/ip/otbn/rtl/otbn.sv, hw/ip/otbn/rtl/otbn_loop_controller.sv, hw/ip/otbn/rtl/otbn_pkg.sv, hw/ip/otbn/rtl/otbn_rf_base.sv, hw/ip/otbn/rtl/otbn_stack.sv
=> [otbn,rtl] Harden loop stack iteration counters

hw/ip/i2c/data/i2c_testplan.hjson, hw/ip/i2c/dv/env/i2c_env.core, hw/ip/i2c/dv/env/i2c_scoreboard.sv, hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv, hw/ip/i2c/dv/env/seq_lib/i2c_fifo_reset_fmt_vseq.sv, hw/ip/i2c/dv/env/seq_lib/i2c_fifo_reset_rx_vseq.sv, hw/ip/i2c/dv/env/seq_lib/i2c_rx_oversample_vseq.sv, hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv, hw/ip/i2c/dv/i2c_sim_cfg.hjson
=> I2c host rx sample

hw/ip/otbn/rtl/otbn_loop_controller.sv
This adds an integrity check to the start and end address of loops on
the loop stack. The integrity code used is the same 39,32 inverted Hsaio
SECDED code used throughout OTBN.
=> [otbn, rtl] Add integrity checking to loop addresses

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/lc_walkthrough_test.c, sw/device/tests/sim_dv/meson.build
This PR adds one walkthrough test from RAW to ProdEnd state.
Upcoming PRs will walkthrough other paths of LC state transitions.
=> [dv/chip] Lc_walkthrough test part1

hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv
Added the sampling of intr_cg, intr_pins_cg and intr_test_cg.
=> [sysrst_ctrl,dv] Added sampling of interrupt covergroup

hw/ip/sysrst_ctrl/dv/cov/sysrst_ctrl_cov_if.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_vseq.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_cov.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv
=> [sysrst_ctrl,dv] Add sampling of combo_detect covergroup

hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
A few slight modifications to align this previously released test
with the later flash_ctrl_error_mp test
=> [flash_ctrl] FLASH_CTRL_ERROR_PROG_TYPE - Updates

hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv
A few slight modifications to align this previously released test
with the later flash_ctrl_error_mp test
=> [flash_ctrl] FLASH_CTRL_ERROR_PROG_WIN - Updates

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_stress_all_vseq.sv
Added more vseq to stress_all to improve coverage
=> [sysrst_ctrl, dv] Update stress_all test

hw/ip/otbn/dv/uvm/env/otbn_loop_if.sv
Xcelium didn't support the targeted $assertoff/$asserton for the
assertion that isn't compatible with loop warping. Instead just disable
all assertions in the loop controller hierarchy when running a test that
uses loop warping.
=> [otbn,dv] Disable all loop controller assertions for loop warping

hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_start_stop_control.sv
=> [otbn,rtl] Add fatal error on bad ack from URND

hw/ip/spi_device/pre_dv/program/prog_passthrough_host.sv, hw/ip/spi_device/pre_dv/program/prog_passthrough_sw.sv, hw/ip/spi_device/pre_dv/program/spiflash.sv, hw/ip/spi_device/pre_dv/tb/spid_common.sv
This commit implements the issuing of program and reading back of
mailbox and the written space from SPIFlash.
The data checker logic and the sw copying the program to mailbox are not
ready yet.
=> [spi_device] Program & Mailbox Tests

hw/ip/lc_ctrl/data/lc_ctrl.prj.hjson, hw/ip/lc_ctrl/doc/checklist.md
- Updated checklist for V2S
- Moved project to V2S
=> [lc_ctrl/dv] Updated checklist and moved project to V2S

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson
=> [dv/top] Add jitter enabled tests and create dedicated regression

hw/ip/spi_device/pre_dv/program/prog_passthrough_host.sv, hw/ip/spi_device/pre_dv/program/prog_passthrough_sw.sv, hw/ip/spi_device/pre_dv/spid_passthrough_sim_cfg.hjson, hw/ip/spi_device/pre_dv/tb/spid_common.sv, hw/ip/spi_device/pre_dv/tb/spid_passthrough_tb.sv, hw/ip/spi_device/rtl/spi_device_pkg.sv
This commit adds failed upload sequence to the test.
https://github.com/lowRISC/opentitan/issues/11871#issuecomment-1127940485
The Page Program sees incorrect command with this test.
=> test(spi_device): Upload sequence

util/reggen/reg_html.css
=> [doc] Avoid trailing whitespace in auto-generated reggen pages

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_mp_vseq.sv
A few small, non functional modifications, to the iteration count, and
the display of an item
=> [flash_ctrl] flash_ctrl_error_mp - Update

hw/dv/tools/xcelium/cover.ccf
We only need toggle coverage at port level, add back 2 lines removed at #12400
=> [dv] Fix Xcelium toggle collection

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv, hw/dv/sv/pwrmgr_clk_ctrl_agent/pwrmgr_clk_ctrl_monitor.sv, hw/ip/pwrmgr/dv/env/pwrmgr_env_cfg.sv, hw/ip/pwrmgr/dv/env/pwrmgr_if.sv, hw/ip/pwrmgr/dv/env/pwrmgr_scoreboard.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_aborted_low_power_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_common_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_wakeup_race_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_reset_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_stress_all_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_vseq.sv, hw/ip/pwrmgr/dv/sva/pwrmgr_bind.sv, hw/ip/pwrmgr/dv/sva/pwrmgr_clock_enables_sva_if.sv, hw/ip/pwrmgr/dv/sva/pwrmgr_rstmgr_sva_if.sv, hw/ip/pwrmgr/dv/tb.sv
following test errors are fixed
- pwrmgr_stress_all
- pwrmgr_same_csr_outstanding
- pwrmgr_stress_all_with_rand_reset
=> [dv,pwrmgr] regression fix

hw/ip/spi_device/rtl/spi_device.sv
This PR includes #12714 . Please review the last commit only.
This commit fixes one of the issue https://github.com/lowRISC/opentitan/issues/11871
Problem:
SW read incorrect opcode for Page Program.
Analysis
--------
The Page Program (0x02) opcode is adjacent to other commands that
SPI_DEVICE processes. So, the Datapath is fixed when the exact last beat
of the command opcode arrives. It is the second half of the 7th SCK.
The command parser activates Upload module at that time. However, the
top module switches the SRAM mux to the Upload module when the datapath
is latched by inverted SCK, which is right after the 8th posedge of SCK.
The Upload module, however, pushes the CMDFIFO entry (0x02 Page Program)
prior to 8th posedge of SCK to safely update the FIFO content as SCK
may not have 9th …
=> fix(spi_device): Missed Command Upload

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv, hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_pkg.sv, hw/vendor/patches/pulp_riscv_dbg/0001-Use-lowrisc-instead-of-PULP-primitives.patch, hw/vendor/patches/pulp_riscv_dbg/0002-Minor-lint-fix.patch, hw/vendor/pulp_riscv_dbg/src/dm_csrs.sv
=> [hw] Minor lint fixes

sw/device/lib/base/bitfield.c, sw/device/lib/base/bitfield.h, sw/device/lib/dif/BUILD, sw/device/lib/dif/dif_csrng.c, sw/device/lib/dif/dif_csrng_shared.c, sw/device/lib/dif/dif_csrng_shared.h, sw/device/lib/dif/dif_edn.c, sw/device/lib/dif/dif_edn.h, sw/device/lib/dif/dif_edn_unittest.cc, sw/device/lib/dif/meson.build
This also breaks out some common code out of the CSRNG DIF, since EDN is just a thin interface over the CSRNG.
=> [dif/edn] Implement the EDN DIFs

sw/device/silicon_creator/lib/drivers/spi_device.h, sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/bootstrap/eeprom.rs, sw/host/opentitanlib/src/bootstrap/mod.rs, sw/host/opentitanlib/src/spiflash/flash.rs
The first commit of this PR (authored by @cfrantz) adds the spi flash based bootstrap protocol while the second commit includes some minor changes to match the new bootstrap implementation.
=> [opentitantool] SPI flash bootstrap updates 

sw/device/lib/base/bitfield.h
This addresses some outstanding issues with #12625.
=> [sw/base] fix documentation comments in bitfield.h

sw/device/silicon_creator/lib/drivers/alert_unittest.cc, sw/device/silicon_creator/lib/drivers/otbn_unittest.cc
Increate unittest converage for otbn and alert drivers.
=> [Mask_rom, test] Add tests for alert and otbn drivers

sw/host/opentitantool/src/command/load_bitstream.rs
=> [opentitantool] Fix comment typo

sw/device/silicon_creator/lib/drivers/spi_device.c
=> [sw/silicon_creator] Update erase and program times in the SFDP table

sw/device/lib/dif/BUILD, sw/device/lib/dif/dif_hmac.c, sw/device/lib/dif/dif_hmac_unittest.cc
Add unittests for the function `dif_hmac_mode_hmac_start`.
=> [dif, Hmac] Unittest part1

hw/top_earlgrey/data/chip_testplan.hjson
=> [top, dv] update rv_dm testplan

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_auto_blk_key_output_vseq.sv
=> [sysrst_ctrl,dv] Improve auto_blk_key_output group coverage

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_testunlocks_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/lc_walkthrough_testunlocks_test.c, sw/device/tests/sim_dv/meson.build
This is another walkthrough test that walks through all test lock and
unlock states.
=> [dv/chip] walkthrough for all test lock/unlocks

hw/top_earlgrey/data/chip_testplan.hjson
This PR adds more description to one chip level test.
=> [dv/chip] Clarify one chip level test

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_vseq.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_cov.sv
=> [sysrst_ctrl,dv] Improve the combo detect group coverage

hw/ip/otbn/doc/_index.md
This is mostly just a rejig to make it easier to understand. But it
also documents the new cache-clearing behaviour implemented in
8e97525.
=> [otbn,doc] Reword documentation of the RND ISPR

sw/device/lib/dif/dif_spi_device.c, sw/device/lib/dif/dif_spi_device.h, sw/device/lib/dif/dif_spi_device.md, sw/device/lib/dif/dif_spi_device_unittest.cc
=> [spi_device/dif] Add TPM DIFs

hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- Added Addr0 Addr1 Cfg
- Added Tasks Program Txdata And Read Acqdata
- Added Checks Read Acqdata and Task Program Stretch Ctrl
- Added Dut Target Intrs Process
=> [I2C/DV] Target Cfg

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_vseq.sv, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/lc_walkthrough_test.c, sw/device/tests/sim_dv/meson.build
Adding a transition to RMA state using the RMA token.
This PR adds the following transitions:
1). RAW -> TESTUNLOCK0 -> PROD -> RMA
2). RAW -> TESTUNLOCK0 -> DEV -> RMA
=> [dv/chip] LC_walkthrough test [PART3]

hw/ip/lc_ctrl/doc/_index.md, hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
This partially addresses #12822.
=> [lc_ctrl] D3 fixes

hw/ip/pattgen/doc/checklist.md
=> [pattgen,dv] Updated pattgen DV checklist

sw/device/tests/aon_timer_sleep_wdog_sleep_pause_test.c
The pause test is currently failing because the test_rom takes
too long to execute and the watchdog triggers sooner than the
test expects. As a result, the test sees two reset reasons at
the same time and fails.
While we could adjust the delays such that it is passing again,
such tests may be prone to failures in the future.
Instead, the test was converted to not rely on resets but instead
on the watchdog / wakeup counts.  The pause function causes the
watchdog to stop counting during low power, and thus creates an
inverse relationship with wakeup.  The test checks on that instead.
=> [dv/top] Adjust test parameters

hw/top_earlgrey/cdc/cdc_waivers.tcl
This PR to remove W_DATA ending with PADs output as PADs output does not have any flops in PINMUX.
=> [cdc] Add PADs to waivers

hw/ip/rv_core_ibex/data/rv_core_ibex.hjson, sw/device/lib/dif/dif_rv_core_ibex.c, sw/device/lib/dif/dif_rv_core_ibex.h, sw/device/lib/dif/dif_rv_core_ibex_unittest.cc
Add error status DIF functions and unittest
=> [dif, rv_core_ibex] Error status functions and unittest

hw/ip/otbn/dv/uvm/env/otbn_controller_if.sv, hw/ip/otbn/rtl/otbn_controller.sv
This was triggered by a slight bug in the previous
implementation (where a `CSRRS` caused `ispr_rdata_into_ispr_bignum_wdata`
to be high, meaning that a `CSRRS` on `RND_PREFETCH` caused an error).
However, the previous design also doesn't really match the rest of
OTBN. In particular, an instruction like `BN.WSRR` reads ISPR data. It
writes that data (together with the integrity bits) straight to the
bignum register file. With the previous design, it didn't check
whether these bits were valid or not. This doesn't match the rest of
OTBN, where instructions like `BN.MOV`, `BN.MOVR`, `BN.LID` and `BN.SID` pass
integrity bits through unchanged *but* also check them for
correctness.
This commit tweaks things to work the same, and also writes a big
comment to explain what's going on (because …
=> [otbn,rtl] Tweak how we check integrity for ISPRs

hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_ctrl_arb_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Hi,
This PR fixes and rewrites the memory model update method and in addition increase some of the tests timeouts for the closed-source.
Thanks! 
=> [flash_ctrl/dv] Fix model update moethod and increase timeouts

hw/ip/rstmgr/dv/env/rstmgr_env_pkg.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_shadow_attack_vseq.sv
- update leaf shadow registers
=> [rstmgr,dv] regfix rstmgr_leaf_rst_shadow_attack_vseq

hw/ip/flash_ctrl/dv/cov/flash_ctrl_cov.vRefine, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Add code exclusions defined in issue #12325.
=> [flash_ctrl] ADD FIRST CODE EXCLUSIONS

hw/ip/lc_ctrl/data/lc_ctrl.prj.hjson, hw/ip/lc_ctrl/doc/checklist.md
This is pending the cleanup tasks tracked on #12822.
=> [lc_ctrl/doc] Move to D3

hw/ip/otbn/dv/model/iss_wrapper.cc, hw/ip/otbn/dv/model/iss_wrapper.h, hw/ip/otbn/dv/model/otbn_model.cc, hw/ip/otbn/dv/model/otbn_model.h, hw/ip/otbn/dv/otbnsim/sim/sim.py, hw/ip/otbn/dv/otbnsim/sim/state.py, hw/ip/otbn/dv/otbnsim/stepped.py
The first three commits are simple tidy-ups, but they made the last commit (which contains the bug-fix) a bit easier to write.
=> [otbn,dv] Tidy-ups and a small bug-fix in ISS memory wiping code

hw/dv/sv/cip_lib/cip_base_env_cfg.sv, hw/dv/sv/cip_lib/cip_base_scoreboard.sv, hw/dv/sv/dv_lib/dv_base_env_cfg.sv, hw/dv/sv/dv_lib/dv_base_test.sv, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_rstmgr_alert_info_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
=> [chip,rstmgr,dv] regression fix rstmgr_alert_info test

sw/device/tests/closed_source/README.md
=> [docs] remove newline in closed-source test hooks docs

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/meson.build, sw/device/tests/sim_dv/pwrmgr_deep_sleep_power_glitch_test.c
=> [dv,full_chip,pwrmgr] Add pwrmgr_sleep_power_glitch_reset test

hw/ip/prim/lint/prim_xnor2.waiver, hw/ip/prim/prim.core, hw/ip/prim/prim_xnor2.core, hw/ip/prim_generic/prim_generic_xnor2.core, hw/ip/prim_generic/rtl/prim_generic_xnor2.sv
Adding an exclusive nor generic prim cell.
=> [prim] Added generic xnor2

bazelisk.sh
Before this change, running lots of instances of `bazelisk.sh` at once
meant downloading lots of copies of Bazel. Oops!
Now, if you run `bazelisk.sh` on its own on a clean checkout, the first
call to `up_to_date` will fail. We'll then take a lock, check again that
we need to download bazelisk (we do!) and then download it, finally
releasing the lock.
If we run `bazelisk.sh` in a clean checkout with 100 threads at once,
they will will all race to get the first flock. One of them will win
the race and follow the steps above. All of the others will sit and
wait for that first thread. Once it is done, they will run in order,
each checking that bazelisk is up to date (it is!) and then do
whatever job they are supposed to be doing.
Of course, the usual situation is that we've already got …
=> [bazelisk] Use a lock to avoid downloading Bazel lots of times

hw/ip/otbn/rtl/otbn_alu_bignum.sv
ISPR read data is muxed out in two stages in the bignum ALU. The first
stage muxes between all of the ISPRs that don't have integrity bits. The
result goes through an integrity encoder and is fed into the second
stage. The second stage chooses the final read data choosing between the
first stage with the calculated intergrity and the ISPRs that have
integrity bits.
This refactoring makes this structure more explicit and should result in
area savings as the previous RTL fed the same signal into multiple
inputs of the second stage mux. As there is an optimization barrier in
the mux these would not have been optimized down to a single input.
=> [otbn,rtl] Refactor ISPR read muxing

rules/scripts/bitstreams_workspace.py
This fixes the log messages from the bitstreams cache python script to
be of the appropriate severity level.
=> [bazel] fix bitstream cache log message types

sw/device/silicon_creator/mask_rom/BUILD, sw/device/silicon_creator/mask_rom/mask_rom_epmp_test.c, sw/device/silicon_creator/mask_rom/meson.build
=> [sw/silicon_creator] Use sram_ctrl DIFs in mask_rom_epmp_test.c

hw/ip/rstmgr/doc/_index.md
=> [doc/rstmgr] Fix link in rstmgr functional spec

hw/top_earlgrey/cdc/cdc_waivers.spi_device.tcl
=> fix(cdc): Typo in waiver file

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_vseq.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv
1. fix the ec_rst pulse
2. fix missing en_cov which causes null object
=> [sysrst_ctrl/dv] Fix combo_detect

hw/dv/sv/sec_cm/prim_sparse_fsm_flop_if.sv
=> [dv] Remove 2 cycle delay after injecting the fault

hw/top_earlgrey/cdc/cdc_waivers.spi_device.tcl, hw/top_earlgrey/cdc/cdc_waivers.tcl
- Add PADS attribute waivers
- SPI_Device static signals: control.mode, cfg.?x_order, CMD_INFO entries
- Waive Generic mode in phase signals.
=> [cdc] Pads attr & SPI_DEVICE statics

hw/ip/spi_host/doc/dv/index.md, hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_overflow_underflow_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_performance_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv, hw/ip/spi_host/dv/env/spi_host_env_cov.sv, hw/ip/spi_host/dv/env/spi_host_env_pkg.sv, hw/ip/spi_host/dv/env/spi_host_scoreboard.sv, hw/ip/spi_host/dv/env/spi_host_seq_cfg.sv, hw/ip/spi_host/dv/spi_host_sim_cfg.hjson, hw/ip/spi_host/dv/tb.sv
- Regression Fixes For Over & Under Flow Test
- Assertion Coverage Test for Reg Rd
=> [SPI_HOST/DV] Regression FIX and Assertion Cov

sw/device/lib/dif/dif_aes.h
=> [sw,dif_aes] Fix output param doc

sw/device/lib/dif/dif_rstmgr.h, sw/device/lib/testing/rstmgr_testutils.c
=> [sw,rstmgr] Fix doc and checks for dump code

hw/dv/sv/pwm_monitor/pwm_item.sv, hw/dv/sv/pwm_monitor/pwm_monitor.sv, hw/dv/sv/pwm_monitor/pwm_monitor_cfg.sv, hw/ip/pwm/dv/env/pwm_env_pkg.sv, hw/ip/pwm/dv/env/pwm_scoreboard.sv, hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv, hw/ip/pwm/dv/env/seq_lib/pwm_perf_vseq.sv, hw/ip/pwm/dv/env/seq_lib/pwm_rand_output_vseq.sv
The following commits each individually address changes made to the environment, sequences and agent, originally these changes are from the following failing PRs: #12066 , #12860 , #12861 , #12862.
These previous pull requests had been closed due to failing CI checks, the cause of which a shared dependency. Upon attempts to break the pull request into multiple commits as per request in #12066, I had introduced this issue.
=> [pwm] Changes implemented from previous pull requests failing due to CI failures.

util/opentitantool_test_runner.sh
=> [opentitan-tool/bazel] echo the invocation of opentitan tool

hw/dv/sv/pwrmgr_clk_ctrl_agent/pwrmgr_clk_ctrl_common_pkg.sv, hw/dv/sv/pwrmgr_clk_ctrl_agent/pwrmgr_clk_ctrl_if.sv, hw/dv/sv/pwrmgr_clk_ctrl_agent/pwrmgr_clk_ctrl_monitor.sv, hw/ip/pwrmgr/data/pwrmgr_sec_cm_testplan.hjson, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_glitch_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_global_esc_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv, hw/ip/pwrmgr/dv/pwrmgr_sim_cfg.hjson, hw/ip/pwrmgr/dv/sva/pwrmgr_bind.sv, hw/ip/pwrmgr/dv/sva/pwrmgr_sec_cm_checker_assert.sv, hw/ip/pwrmgr/dv/tb.sv, hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr_sec_cm_testplan.hjson
complete [jaedon] action items from https://github.com/lowRISC/opentitan/issues/12075#issue-1202200812
=> [pwrmgr,dv] v2s cleanup review item

hw/top_earlgrey/data/chip_testplan.hjson, sw/device/tests/aes_idle_test.c
=> [chip,aes_idle] Fix comments in aes_idle test

hw/top_earlgrey/dv/chip_sim_cfg.hjson
For test:
chip_sw_sleep_sram_ret_contents
Signed-off-by: Dave Williams <dave.williams@ensilica.com>
=> [sw,tests] Update timeout for retention SRAM contents test

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/clkmgr_off_aes_trans_test.c, sw/device/tests/clkmgr_off_hmac_trans_test.c, sw/device/tests/clkmgr_off_kmac_trans_test.c, sw/device/tests/clkmgr_off_otbn_trans_test.c, sw/device/tests/clkmgr_off_trans_impl.c, sw/device/tests/clkmgr_off_trans_impl.h
=> [dw,chip_sw] Add clkmgr_off_trans tests

.gitattributes, azure-pipelines.yml, ci/scripts/get-build-type.sh
This commit let CI skip FPGA tests, SW tests when only CDC related
changes are made.
=> [ci] Skip FPGA , SW test for CDC changes

.gitattributes, azure-pipelines.yml, ci/scripts/get-build-type.sh
This reverts commit 2f48edc13fec8fd3787988100028f2ee107e766d.
=> Revert "chore(ci): Skip FPGA , SW test for CDC changes"

hw/dv/tools/dvsim/sim.mk, hw/dv/tools/dvsim/xcelium.hjson
the fix in #12236 gave some other issues at least for WDC
I have created what I believe is a more robust fix.
@cindychip I was not able to reproduce the original problem - can you confirm this still fixes that issue?
=> Refixed 12236 to a more rubust solution

hw/ip/otp_ctrl/rtl/otp_ctrl.sv
This PR fixes the CDC issue on otp_keymgr_key_t.valid signal. Also
there's chance the key_share0, key_share1 can be changed during the
operation but the chance is limited to the escalation stage, in which
case the CDC is not meaningful anymore.
So rather than latching the key_shares, this commit adds assertion to
check the stability of the key_shares during the normal operation.
=> fix(otp_ctrl): Keymgr Key valid glitch

hw/dv/sv/sec_cm/prim_sparse_fsm_flop_if.sv
Disabled restore_fault for sparse_fsm, so as to avoid some complication,
because restore_fault may cause misalignment on signal_forced and custom_signal_forced
signal_forced is net, while custom_signal_forced is a flop.
For example, if the state_d stays at error_state, we restore the net (signal_forced) and
the flop (custom_signal_forced) to an idle_state. signal_forced won't be changed to
idle_state as state_d has no change, while custom_signal_forced will become idile_state as
it's updated in every cycle.
Another approach is to deposit the value in the flop but we will have different
implementation in the prim and the path is different in the close source
=> [dv] Fix sec_cm test failures at sparse_fsm

hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_instruction_fetch.sv, hw/ip/otbn/rtl/otbn_pkg.sv, hw/ip/otbn/rtl/otbn_predecode.sv
=> [otbn,rtl] Add predecode checking for control flow related signals

hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_instruction_fetch.sv, hw/ip/otbn/rtl/otbn_loop_controller.sv, hw/ip/otbn/rtl/otbn_predecode.sv
Note the first commit belongs to another PR (https://github.com/lowRISC/opentitan/pull/13069), https://github.com/lowRISC/opentitan/commit/56f87cb63d9bc10c15758d47c7d279a0c8460cbc is the one to review
=> Otbn ctrl flow target check

doc/project/technical_committee.md
Nir has been appointed to the technical committee by the steering committee. Welcome Nir!
=> [doc] Add Nir Tasher to the technical committee

ci/scripts/target-location.sh
add the -v argument I use to debug the location script.
=> Verbose location script

hw/top_earlgrey/data/chip_testplan.hjson
=> [dv,chip_testplan] Add sleep frequency tests

hw/ip/prim/rtl/prim_dom_and_2share.sv
revise Assertion to reduce the memory footprint (eliminating `[0:$]`)
It splits:
- check the stableness of input signals until entropy becomes valid
- check the correctness of the output
=> [prim] High memory usage of Assertion (dom_2share)

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_stress_all_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv
=> [sysrst_ctrl,dv] Fix stress_all test

hw/ip/sysrst_ctrl/data/sysrst_ctrl.prj.hjson, hw/ip/sysrst_ctrl/doc/checklist.md
=> [sysrst_ctrl,dv] Updated sysrst_ctrl checklist

hw/top_earlgrey/data/chip_testplan.hjson
=> [top] update testplan

hw/dv/sv/i2c_agent/i2c_driver.sv, hw/dv/sv/i2c_agent/i2c_if.sv
- Added Interface Tasks Host Start Stop RStart Data And Nack
- Added Tasks To Drive Host Item I2C Driver
=> [I2C/DV] I2c Agent Driver Host Mode Tasks

hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_scramble_ctrl.sv
This commit adds assertions for global and local escalation
countermeasure.
=> [otbn, dv] Adds checks for GLOBAL_ESC and LOCAL_ESC

sw/device/lib/dif/dif_usbdev.c, sw/device/lib/dif/dif_usbdev_unittest.cc
Also fix up handling of CONFIGIN to ensure that new buffers have completely fresh state.
--
Note that this PR builds on top of another, and only the last two commits are new.
=> [usbdev/dif] Add rest of DIF unit tests

hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
=> [dv,flash_ctrl] change tool to vcs

hw/ip/otp_ctrl/rtl/otp_ctrl_ecc_reg.sv
=> [otp_ctrl] Remove TODO from RTL

sw/device/sca/aes_serial.c
Capture rate increased from 300 traces/s to 880 traces/s for
AES fixed-vs-random key batch capture. Also some cleanup is
done.
Signed-off-by: Abdullah Varici <abdullah.varici@lowrisc.org>
=> [sca] Optimize and clean-up AES capture functions.

hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv, hw/ip/sram_ctrl/rtl/sram_ctrl.sv, hw/ip/tlul/rtl/tlul_lc_gate.sv
=> [sram_ctrl] Switch to tlul_lc_gate for transaction blocking

hw/ip/prim_generic/rtl/prim_generic_clock_buf.sv, hw/ip/prim_xilinx/rtl/prim_xilinx_clock_buf.sv, hw/ip/spi_device/rtl/spi_device.sv, hw/top_earlgrey/data/clocks.xdc
updates to fpga constraints and rtl to address #13155
=> [top, spi_device] constraint and clock connection update

hw/dv/tools/dvsim/sim.mk
Fixes write permission errors in top level test builds.
Signed-off-by: Dave Williams <dave.williams@ensilica.com>
=> [sw,tests] Add -f option to copy in sim.mk

hw/top_earlgrey/sw/autogen/top_earlgrey_memory.ld, util/topgen/templates/toplevel_memory.ld.tpl
=> Remove eflash_virtual

hw/ip/prim_xilinx/rtl/prim_xilinx_clock_buf.sv
=> [prim] Add description to parameters

hw/ip/entropy_src/dv/cov/entropy_src_cov_if.sv
=> Fixes Issue #13120

hw/ip/clkmgr/doc/_index.md
=> [clkmgr] Minor documentation updates

hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_stress_all_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
- Add stress_all test as part of V2 requirement.
- More qualified tests will be added to 'stress_all_vseq'
=> [dv,flash_ctrl] stress_all test

doc/getting_started/build_sw.md
See https://github.com/lowRISC/opentitan/pull/13157#discussion_r894063882
Add a description of what kind of Bazel artifacts are produced by the OTBN build flow, and a little guidance on how to use them.
=> [doc] Add documentation for OTBN build artifacts.

hw/ip/spi_host/dv/env/seq_lib/spi_host_status_stall_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_stress_all_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_vseq_list.sv, hw/ip/spi_host/dv/env/spi_host_env.core, hw/ip/spi_host/dv/env/spi_host_env_cfg.sv, hw/ip/spi_host/dv/env/spi_host_scoreboard.sv, hw/ip/spi_host/dv/spi_host_sim_cfg.hjson
- Added Spi Host Status Stall Tx RX Test
=> [SPI_HOST/DV] Spi host stall

hw/ip/pwm/data/pwm_testplan.hjson, hw/ip/pwm/dv/env/pwm_env.core, hw/ip/pwm/dv/env/pwm_scoreboard.sv, hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv, hw/ip/pwm/dv/env/seq_lib/pwm_stress_all_vseq.sv, hw/ip/pwm/dv/env/seq_lib/pwm_vseq_list.sv, hw/ip/pwm/dv/pwm_sim_cfg.hjson
- Modified The Scoreboard To Check Transction-By-Transaction
- Modified The Base Test To Accomodate Counter Overflow
Signed-off-by: dharanendrak <dharanendra.kumar@ensilica.com>
=> [PWM/DV] Updated Scoreboard And Added Stress Test

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
=> [dv] Remove workaround in the common mem test

sw/device/sca/sha3_serial.c
Batch-capture support for KMAC data acquisition. 
Added support for fixed-vs-random key general TVLA.
Signed-off-by: vrozic <vrozic@lowrisc.org>
=> [sca] Batch-capture support for KMAC fixed-vs-random key.

sw/device/lib/crypto/api.h
The crypto API header file is updated to be in sync with the latest crypto lib specification changes (as of 16Jun22)
Signed-off-by: Srinivasan Y <srinivasan.yadhunathan@seagate.com>
=> [sw,crypto] Update crypto API header file to align with the latest crypto library spec

sw/device/lib/dif/dif_gpio.c, sw/device/lib/dif/dif_gpio.h, sw/device/lib/dif/dif_gpio_unittest.cc
=> [dif/gpio] Check bounds of pin indices

hw/ip/pwm/dv/env/pwm_scoreboard.sv
Updated pwm_scoreboard.sv to accommodate the changes in RTL
For the issue #13200
Signed-off-by: Dharanendra Kumar <dharanendra.kumar@ensilica.com>
=> [PWM/DV] Updated Checker For issue #13200

sw/device/lib/testing/test_framework/BUILD, sw/device/lib/testing/test_framework/freertos_hooks.c, sw/device/lib/testing/test_framework/freertos_port.c, sw/device/lib/testing/test_framework/ottf_main.c
=> [bazel] cleanup FREERTOS_IS_BAZEL

hw/ip/otp_ctrl/data/otp_ctrl_img_dev.hjson, hw/ip/otp_ctrl/data/otp_ctrl_img_rma.hjson, hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- backdoor load otp value based on jitter_en arg
- also add default values for jitter_en in the otp hjsons
=> [top] Update jitter enable

hw/ip/spi_host/data/spi_host_testplan.hjson, hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_idlecsbactive_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_status_stall_vseq.sv
- Fixed regression failures
- Testplan update for unmapped tests
=> [SPI/DV] Regression Failure Fixes And Testplan Update

doc/getting_started/_index.md, doc/getting_started/setup_dv.md, doc/getting_started/setup_verilator.md, doc/rm/continuous_integration/index.md, hw/ip/edn/doc/_index.md
Changes include:
- Make $ in front of bash commands consistent within page
- Some grammatical fixes
- Fixed EDN initialization function name
=> [doc] Minor improvements to docs

util/BUILD, util/generate_compilation_db.py, util/generate_compilation_db_test.py
This script generates compile_commands.json.
=> [util] Add util/generate_compilation_db.py

hw/ip/aon_timer/doc/_index.md
=> [aon_timer/doc] Update description for escalation

doc/project/checklist.md
=> [doc] update D1 checklist item descriptions

hw/dv/sv/flash_phy_prim_agent/flash_phy_prim_agent_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_virtual_sequencer.sv, hw/ip/flash_ctrl/dv/env/flash_otf_item.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/tb/tb.sv, hw/ip/flash_ctrl/dv/tests/flash_ctrl_base_test.sv
Scramble env update is split into 3 parts and this is part2.
Completion version with test sets will be the third part. 
=> [dv,flash_ctrl] on the fly scoreboard and env update

hw/ip_templates/alert_handler/dv/env/alert_handler_scoreboard.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/alert_handler_scoreboard.sv
This PR aligns design change with crashdump feature #13177.
=> [dv/alert_handler] Align crashdump

hw/formal/tools/jaspergold/conn.tcl, hw/top_earlgrey/formal/chip_conn_cfg.hjson
Fix script issue that causes the weekly connectivity test to fail.
=> [formal/conn] Fix bbox command

hw/ip/pwm/dv/env/pwm_scoreboard.sv
Updated for VCS Run
Changed some of the code to support VCS
Signed-off-by: Dharanendra Kumar <dharanendra.kumar@ensilica.com>
=> [PWM/DV] Updates For VCS Run

hw/dv/sv/flash_phy_prim_agent/flash_phy_prim_monitor.sv
=> [flash_ctrl,dv] non-otf timeout fix

hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_smoke_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_trans_vseq.sv
Updates in idle inputs need some cycles to settle.
=> [dv/clkmgr] Fix failure in smoke test

hw/ip/otbn/data/otbn_sec_cm_testplan.hjson
This commit maps existing testcases to V"S countermeasures
=> [otbn, dv] Maps testcases to V2S countermeasures

azure-pipelines.yml
This should reduce loadm, and won't affect a PR's critical path.
=> [ci] Combine bazel build steps

hw/ip/prim/rtl/prim_edn_req.sv
The repetition check is performed inside the prim_edn_req module and in case of a repetition failure, the error signal is just pulsed. It thus needs to be captured and hold until the data is read. Previously, repetition check failures just got ignored.
@ctopal would mind giving this PR a try please?
=> [otbn] Capture edn_rnd_err_i and hold it until the data is consumed

doc/getting_started/setup_fpga.md
Meson was removed in #13156, making Bazel the only supported build system
for OpenTitan.
This PR updates the website documentation on FPGA setup to reflect this
change.
=> [docs] update FPGA website docs to reflect meson removal

hw/dv/tools/xcelium/common.ccf
=> Modify common.ccf file for proper expression coverage

sw/host/opentitanlib/src/transport/ti50emulator/uart.rs
Fix state handling due to changes introduced by [ PR#13277](https://github.com/lowRISC/opentitan/pull/13277/commits)
with function get_socket(..).
Signed-off-by: Michał Mazurek <maz@semihalf.com>
=> [opentitanlib] Fix Ti50Emulator Uart Sub-process state handling.

sw/host/opentitanlib/src/spiflash/sfdp.rs
My CW310 FPGA is producing 256 0xff bytes for the SFDP buffer instead of
something valid. As a result, we're parsing a signature of 0xffffffff
instead of the expected 0x50444653.
This commit changes Sfdp::try_from() to fail fast with an informative
error message about the invalid header, rather than blunder on and fail
farther down the line with "attempt to add with overflow".
Fixes #13477 
=> [sw/host/opentitanlib] Add SFDP signature check

util/dvsim/Scheduler.py, util/dvsim/StatusPrinter.py
This commit enhances the dvsim status bar to indicate what
job is currently running, truncated to 30 characters.
=> [dvsim] Indicate what is currently running

hw/top_earlgrey/formal/chip_conn_cfg.hjson, hw/top_earlgrey/formal/conn_csvs/ast_entropy_src_cfg.csv, hw/top_earlgrey/formal/conn_csvs/ast_mem_cfg.csv
Also fix path to usbdev ram.
Fixes #13460
=> [formal,conn] Add ast to entropy_src connectivity check

hw/ip/pwm/data/pwm.hjson
=> [pwm/doc] Explicitly document pwm_en_o outputs

hw/dv/sv/flash_phy_prim_agent/flash_phy_prim_monitor.sv, hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_otf_item.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_rnd_wd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_word_sweep_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_ro_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_rnd_wd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_wo_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_rnd_wd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_word_sweep_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
- Change ditribution of the number of ctrl req
- Add small word (less than 1 page) test
=> [dv,flash_ctrl] Add more scramble test

hw/ip_templates/alert_handler/dv/alert_handler_sim_cfg.hjson.tpl, hw/top_earlgrey/ip_autogen/alert_handler/dv/alert_handler_sim_cfg.hjson
This PR updates alert_handler test timeout timing.
=> [dv/alert_handler] Update alert_handler output timing

hw/ip/spi_host/data/spi_host_testplan.hjson, hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_status_stall_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv
- Fixed event test when txwm is set 1
=> [SPI_HOST/DV] Regression Fixes

hw/ip/pwm/dv/env/pwm_env_cov.sv, hw/ip/pwm/dv/env/pwm_scoreboard.sv
Improved FC coverage
Added OVF/UF fixes in SB
Signed-off-by: Dharanendra Kumar <dharanendra.kumar@ensilica.com>
=> [PWM/DV]  PWM Functional Coverage And SB Fixes

hw/dv/sv/cip_lib/cip_base_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/flash_ctrl/dv/tests/flash_ctrl_base_test.sv
Address issue #12944 partially.
- Update randomization to create correlation between config and transaction
- Add per transaction exp_alert support for flash_ctrl  test
- Clean up unused codes.
=> [flash_ctrl,dv] refactoring mp region test

.github/CODEOWNERS
=> [.github] Add advice to ignore unknown user errors

rules/autogen.bzl, util/design/gen-otp-img.py, util/design/lib/OtpMemImg.py
=> [util/design] Encode bit width in OTP vmem filename

hw/ip_templates/alert_handler/doc/_index.md, hw/top_earlgrey/ip_autogen/alert_handler/doc/_index.md
=> [alert_handler] Align docs for crashdump latching

hw/ip/otbn/dv/rig/rig/gens/bad_ispr.py, hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv
Related with #7949. I am not exactly sure if this PR would be enough for that so any feedback on that front is also highly appreciated.
=> [otbn,dv] Add UNIMP to RIG and have an explicit coverpoint about it

hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_pkg.sv, hw/ip/otbn/rtl/otbn_predecode.sv, hw/ip/otp_ctrl/rtl/otp_ctrl.sv, hw/ip/prim/lint/prim_onehot_check.waiver, hw/ip/prim_generic/lint/prim_generic_clock_buf.waiver, hw/ip/spi_device/lint/spi_device.waiver, hw/ip/usbdev/rtl/usbdev.sv, hw/ip/usbdev/rtl/usbdev_usbif.sv, hw/ip_templates/alert_handler/rtl/alert_handler_lpg_ctrl.sv, hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_lpg_ctrl.sv
Lint fix drive towards a lint-clean repo.
=> [lint] Several fixes

hw/ip/spi_host/data/spi_host.prj.hjson, hw/ip/spi_host/doc/checklist.md
- Modified prj hjson
- Modified Checklist md
=> [SPI_HOST/DV] Spi Host V2 Checklist Done

hw/ip/flash_ctrl/rtl/flash_phy_core.sv, hw/ip/flash_ctrl/rtl/flash_phy_rd.sv
- make the arbitration count 5
- only select new fill buffer when there is no match on request
=> [flash_ctrl] Minor tweak of arbitration behavior

hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv, hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
=> [alert_handler] Fix TODO in WaitCycMask SVA

hw/ip/pwm/data/pwm.prj.hjson, hw/ip/pwm/doc/checklist.md
This PR copies the context from PR #13417. The PR #13437 has some
merging conflict.
=> [dv/pwm] V2S checklist update

hw/top_earlgrey/formal/top_earlgrey_fpv_cfgs.hjson
this PR turns on the FPV coverage for prim_count module.
=> [fpv/prim_count] Turn on coverage

hw/ip_templates/alert_handler/data/alert_handler_sec_cm_testplan.hjson, hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler_sec_cm_testplan.hjson
This PR matches sec_cm testplan with the actual test cases.
=> [dv/alert_handler] match sec_cm testplan with tests

hw/ip/spi_host/data/spi_host_sec_cm_testplan.hjson
=> [spi_host/dv] Fix an unmapped test for sec_cm_bus_integrity

hw/ip/prim/rtl/prim_clock_meas.sv
=> [clkmgr/prim] Make frequency measurement disable more robust

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv
- Add region enable to p2r map update
- Remove naked wait
- Add wait alert checker status complete at the end of the loop.
=> [dv,flash_ctrl] regression fix : mp_region test

hw/top_earlgrey/dv/env/seq_lib/chip_sw_full_aon_reset_vseq.sv
Enhance chip_sw_pwrmgr_full_aon_reset test to send an AON power glitch
once the CPU is running.
Fixes #13502
=> [dv,chip,rstmgr] Send AON power glitch after CPU is up

doc/getting_started/_index.md, doc/getting_started/build_sw.md, doc/getting_started/setup_dv.md
- Added method to install GCC version 9
- Updated Bazel version
- Added missing comma
=> [doc] Getting started improvements

hw/ip/otbn/dv/model/iss_wrapper.cc, hw/ip/otbn/dv/model/iss_wrapper.h, hw/ip/otbn/dv/model/otbn_core_model.sv, hw/ip/otbn/dv/model/otbn_model.cc, hw/ip/otbn/dv/model/otbn_model.h, hw/ip/otbn/dv/model/otbn_model_dpi.h, hw/ip/otbn/dv/model/otbn_model_dpi.svh, hw/ip/otbn/dv/otbnsim/sim/state.py, hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv, hw/ip/otbn/dv/uvm/otbn_model_agent/otbn_model_monitor.sv
This PR improves OTBN DV in various aspects. They are prerequisites for #13321, but I split them out of that PR to get them reviewed and merged separately.
=> [otbn,dv] Various improvements

azure-pipelines.yml, ci/scripts/build-bitstream-vivado.sh
=> [ci] Upload MMI files to GCP after Vivado build

sw/device/lib/dif/dif_entropy_src.c, sw/device/lib/dif/dif_entropy_src.h, sw/device/lib/dif/dif_entropy_src_unittest.cc
This PR adds health test stat DIFs and corresponding unit tests for the entropy_src IP.
=> [dif/entropy_src] add health test stats DIFs

hw/dv/sv/spi_agent/seq_lib/spi_host_flash_seq.sv, hw/dv/sv/spi_agent/spi_host_driver.sv, hw/dv/sv/spi_agent/spi_monitor.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv, hw/ip/spi_device/dv/env/spi_device_env_pkg.sv, hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
1. compare upstream items with downstream items
2. some minor fixes
=> [spi_device/dv] Update scb to check passthrough items

hw/top_earlgrey/data/chip_testplan.hjson, sw/device/silicon_creator/mask_rom/data/mask_rom_testplan.hjson
=> [dv] Add unmapped tests

hw/ip/kmac/rtl/kmac_app.sv
Issue #13655
Problem
-------
CSR Key is used incorrectly if:
1. App Intf is configured to KMAC mode
2. App Intf sends short message length.
Analysis
--------
`kmac_app` sends sideloaded key to `kmac_core` if:
1. !!CFG.sideload is set
2. Or, the mux selection is configured to `SelApp`
The issue here is, the logic does not maintain `mux_sel` value to
`SelApp` until the hashing operation is completed. Right after the FSM
moves to `StAppOutLen`, the `mux_sel` is changed to `SelOutLen` to send
the key length to `kmac_core`.
The FSM moves to `StAppOutLen` when the App Interface logic receives the
last message byte. If the message size is small, FSM may move to the
state before the `kmac_core` processes the sideloaded key in the SHA3
engine.
The key shall be maintained, at least, until the SHA3 …
=> [kmac] Maintain Sideload Key

hw/cdc/tools/verixcdc/run-cdc.tcl, hw/top_earlgrey/cdc/cdc_waivers.tcl
AST clocks : waived S_GENCLK errors
SPI_DEVICE :
- Black-boxing dual port SRAM
- Waived paths from TLUL error to u_reg
=> [cdc] misc. waivers

.gitignore, hw/rdc/tools/dvsim/common_rdc_cfg.hjson, hw/rdc/tools/dvsim/meridianrdc.hjson, hw/rdc/tools/dvsim/rdc.mk, hw/rdc/tools/meridianrdc/run-rdc.tcl, hw/top_earlgrey/rdc/chip_earlgrey_asic_rdc_cfg.hjson, util/dvsim/BUILD, util/dvsim/CfgFactory.py, util/dvsim/RdcCfg.py, util/dvsim/dvsim.py, util/dvsim/meridianrdc-report-parser.py
This commit adds meridian rdc skelecton flow to dvsim.
It scaffolds the environment from CDC environment as they are similar.
RdcCfg has been added to dvsim but parsing the result is not ready yet.
=> feat(rdc): Add Meridian RDC flow to dvsim

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/lib/testing/clkmgr_testutils.c, sw/device/lib/testing/clkmgr_testutils.h, sw/device/tests/BUILD, sw/device/tests/ast_clk_outs_test.c, sw/device/tests/clkmgr_sleep_frequency_test.c
=> [dv,chip,clkmgr] Add clkmgr_sleep_frequency test

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/clkmgr_reset_frequency_test.c
=> [dv,chip,clkmgr] Add chip_sw_clkmgr_reset_frequency test

util/otbn_build.py
Make sure otbn_build.py looks for existing object files in the correct place.
Signed-off-by: Sven Bauer <sven.bauer@gi-de.com>
=> [OTBN] Improve linking of OTBN code.

hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_mp_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_win_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv
Address remaining issue #12944 by removing scb_set_exp_alert knob from process_tl_access
=> [dv,flash_ctrl] remove scb_set_exp_alert

sw/device/lib/dif/dif_entropy_src.c, sw/device/lib/dif/dif_entropy_src.h, sw/device/lib/testing/entropy_testutils.c, sw/device/lib/testing/entropy_testutils.h
- add a testutil function to wait until a certain entropy state
=> [sw/dif] Add a dif function to grab current state

hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_stress_all_vseq.sv
This PR temp disables entropy_rng_test with issue #13741 filed for
tracking.
=> [dv/entropy_src] temp disable entropy_rng_test

hw/rdc/tools/dvsim/common_rdc_cfg.hjson, hw/top_earlgrey/rdc/rdc_waivers.tcl
This PR adds RDC waiver template to top_earlgrey.
=> [rdc] Add rdc waiver template

hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_stress_all_vseq.sv
This reverts commit 12c9d0b5924f0403b3b349e963f36c1796676a0d.
Signed-off-by: Cindy Chen chencindy@opentitan.org
=> Revert "[dv/entropy_src] temp disable entropy_rng_test"

hw/ip/aes/dv/aes_base_sim_cfg.hjson, hw/ip/aes/dv/env/aes_env.core, hw/ip/aes/dv/env/aes_env_cfg.sv, hw/ip/aes/dv/env/seq_lib/aes_ctr_fi_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_vseq_list.sv, hw/ip/aes/dv/err_injection_if/aes_err_injection.core, hw/ip/aes/dv/err_injection_if/aes_err_injection_bind.sv, hw/ip/aes/dv/err_injection_if/fi_ctr_fsm_if.sv, hw/ip/aes/dv/err_injection_if/fi_ctr_fsm_wrapper.sv
final PR for the FI
same as the others
=> Adding part 3 of 3 of signal specific fault injections

hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/data/sram_ctrl_sec_cm_testplan.hjson, hw/ip/sram_ctrl/rtl/sram_ctrl.sv
=> [sram_ctrl] Enable secure FIFO counters

hw/ip/sram_ctrl/data/sram_ctrl.prj.hjson, hw/ip/sram_ctrl/doc/checklist.md
To be merged once all cleanup items have been addressed.
Fix #13676
=> [sram_ctrl] Update checklist and move to D3

hw/ip/tlul/rtl/tlul_adapter_sram.sv
=> [tlul_adapter_sram] Update comment describing the ByteAccess parameter

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/data/flash_ctrl_sec_cm_testplan.hjson, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv, hw/ip/flash_ctrl/rtl/flash_phy.sv, hw/ip/flash_ctrl/rtl/flash_phy_rd.sv, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_core_reg_top.sv
=> [flash_ctrl] Enable secure FIFO pointers on read path

azure-pipelines.yml, ci/jobs/quick-lint.sh, ci/jobs/slow-lint.sh
This should cut 2 minutes off the total time to test a PR.
=> [ci] move Check Gen tests to slow lint

hw/ip/spi_device/dv/env/seq_lib/spi_device_intercept_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv, hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
Enable testing it in intercept_vseq and pass_all_vseq
Update scb to check the returne data
=> [spi_device/dv] Support testing JEDEC command

hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv
The while loop causes sim to hang, add DV_SPINWAIT so that it doesn't
take too long to finish
Will fix the root cause soon
=> [spi_device/dv] Add DV_SPINWAIT for a while loop

sw/device/lib/testing/flash_ctrl_testutils.c
=> [dv/sw] Minor correction to flash_ctrl_testutil

_index.md, doc/_index.md, doc/ug/dv_methodology/index.md, hw/_index.md, hw/dv/_index.md, hw/dv/doc/dv_doc_template.md, hw/dv/sv/_index.md, hw/dv/tools/_index.md, hw/formal/doc/index.md, hw/ip/_index.md, hw/lint/doc/index.md, site/docs/layouts/partials/menu.html, sw/_index.md, sw/device/_index.md, sw/host/_index.md, util/_index.md, util/dvsim/examples/testplanner/foo_dv_doc.md
Various site content and menu updates to make navigation UX more intuitive. See commit descriptions for more details.
=> [docs] Various updates to docs.opentitan.org

hw/top_earlgrey/data/chip_testplan.hjson
This PR modifies the testplan for chip_sw_nmi_irq
=> [dv/chip] Update sw_nmi_irq testplan

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_ro_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_vseq.sv
Increase direct read traffic close to ctrl traffic
=> [flash_ctrl,dv] adjust ctrl / host traffic ratio

hw/ip/flash_ctrl/rtl/flash_mp.sv
- When an out-of-bound info partition address is supplied, the previous
memory protection would compare against unknown values even though
an invalid address was already registered.
- Move the invalid address indication into the datapath to fix this issue.
- fixes issue identified in #13751
=> [flash_ctrl] Fix info access overflow

hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
Updates the scoreboard to to more accurately the behavior particularly
around the SW_REGUPD register and the ERR_CODE registers.
=> [entropy_src/dv] Minor scoreboarding updates

doc/rm/comportability_specification/index.md
=> [doc] Clarify security countermeasure format

hw/ip_templates/alert_handler/data/alert_handler.prj.hjson, hw/ip_templates/alert_handler/doc/checklist.md, hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.prj.hjson, hw/top_earlgrey/ip_autogen/alert_handler/doc/checklist.md
To be merged once all cleanup items have been addressed.
Fix #13576
=> [alert_handler] Update checklist and move to D3

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv, hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_otf_item.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_derr_detect_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/flash_ctrl/dv/tests/flash_ctrl_base_test.sv
- Add double bit error detect test
- Add integrity ecc test
=> [flash_ctrl,dv] double bit error tests and tb support

hw/top_earlgrey/dv/chip_sim_cfg.hjson
=> [dv/top] Correct test name in sim config

sw/device/sca/lib/sca.c, sw/device/sca/lib/sca.h, sw/device/sca/sha3_serial.c
=> [sca] Add SW key masking for KMAC.

hw/ip/hmac/data/hmac.prj.hjson, sw/device/lib/dif/dif_hmac.md
This updates the HMAC DIF checklist to reflect the state of the SW.
=> [dif/hmac] move to S2

hw/dv/sv/sw_logger_if/sw_logger_if.sv, hw/top_earlgrey/dv/env/seq_lib/chip_rv_dm_ndm_reset_vseq.sv
- Pick up file name only without directory
- Add fatal if logger is enabled but cannot pick up the file
=> [chip,dv] sw logger update

hw/ip_templates/alert_handler/data/alert_handler.prj.hjson, hw/ip_templates/alert_handler/doc/checklist.md, hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.prj.hjson, hw/top_earlgrey/ip_autogen/alert_handler/doc/checklist.md
This PR updates the checklist to signoff alert_handler to V2S.
=> [dv/alert_handler] Sign off alert_handler to V2S

doc/getting_started/setup_fpga.md
Add some instructions for connecting the debugger and setting the TAP
straps.
Signed-off-by: Alexander Williams <awill@google.com>
=> [doc] Show how to use JTAG with the CW310

util/dvsim/Deploy.py, util/dvsim/Launcher.py, util/dvsim/LocalLauncher.py, util/dvsim/LsfLauncher.py, util/dvsim/Modes.py, util/dvsim/Scheduler.py, util/dvsim/SimCfg.py, util/dvsim/dvsim.py
Add a timeout for builds and runs. Set it in Modes, and enable overriding it
via dvsim arguments.
=> [utils,dvsim] Add wall-clock timeout feature

hw/dv/sv/cip_lib/cip_base_scoreboard.sv, hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv, hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_integrity_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_rnd_wd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_word_sweep_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_ro_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_rnd_wd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_wo_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_rnd_wd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_word_sweep_vseq.sv, hw/ip/flash_ctrl/dv/tests/flash_ctrl_base_test.sv
- Add info region tests
- Add random mp config support
=> [flash_ctrl,dv] mp conig support and region test

hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_intercept_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_all_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_cmd_filtering_vseq.sv, hw/ip/spi_device/dv/env/spi_device_env_pkg.sv, hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
1. Enable testing mailbox
2. Move opcode, payload size, address to rand class-member variables,
with base constraint, and extended classes can override the constraint
to control them
3. Update scb to check mailbox read data
Only test case `ReadAddrWithinMailbox`, will test crossing boundary in
another PR
=> [spi_device/dv] Test flash mailbox

hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_lc_escalation_vseq.sv, hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
lc escalation no longer gates the sram access, update scb for update
simplify the sequence to avoid driving lc_esc and issue sram access at the same time
as it's hard to predict due to async timing
=> [sram/dv] Fix lc_esc test

sw/device/silicon_creator/lib/drivers/keymgr_functest.c, sw/device/tests/aes_sideload_test.c, sw/device/tests/clkmgr_off_peri_test.c, sw/device/tests/flash_ctrl_clock_freqs_test.c, sw/device/tests/flash_ctrl_idle_low_power_test.c, sw/device/tests/flash_ctrl_ops_test.c, sw/device/tests/rstmgr_cpu_info_test.c, sw/device/tests/sensor_ctrl_alerts.c, sw/device/tests/sim_dv/flash_ctrl_lc_rw_en_test.c, sw/device/tests/sim_dv/flash_init_test.c, sw/device/tests/sim_dv/flash_rma_unlocked_test.c, sw/device/tests/sim_dv/keymgr_key_derivation_test.c, sw/device/tests/sim_dv/pwrmgr_b2b_sleep_reset_test.c, sw/device/tests/sim_dv/pwrmgr_deep_sleep_all_reset_reqs_test.c, sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_reset_reqs_test.c, sw/device/tests/sim_dv/pwrmgr_random_sleep_all_reset_reqs_test.c, sw/device/tests/sim_dv/pwrmgr_sysrst_ctrl_test.c
A recent change I made to flash_ctrl_testutils missed updating
many tests, which started failing after the change.
=> [dv,chip] Fix tests failing for flash_ctrl_testutils change

hw/ip/rv_timer/data/rv_timer.prj.hjson, hw/ip/rv_timer/doc/checklist.md
Reviewd by @jeoongp @timothytrippel @msfschaffner
=> [rv_timer] Make it D3

hw/ip_templates/alert_handler/dv/env/seq_lib/alert_handler_common_vseq.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/seq_lib/alert_handler_common_vseq.sv
Fix regression error regarding alert_handler_sec_cm:
1). Add a checking about ping timeout.
2). Add one cycle wait period after disabled assertions because the
assertion lasts for two clock cycles.
=> [dv/alert_handler] Fix regression error

util/reggen/gen_cfg_html.py
This commit builds hw_cfg to include the Inter-Module Signal table.
Related issue #12332
=> doc: Add Inter-module Signal in the IP spec

hw/ip/adc_ctrl/data/adc_ctrl.prj.hjson, hw/ip/adc_ctrl/doc/checklist.md
see #13765 for the final cleanup
=> [adc_ctrl] Officially move to D3

hw/top_earlgrey/data/chip_testplan.hjson
=> [dv/top] Fix typo with unmapped test

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_reset_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otp_reset_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/flash_ctrl/dv/sva/flash_ctrl_bind.sv, hw/ip/flash_ctrl/dv/sva/flash_ctrl_dv_if.sv, hw/ip/flash_ctrl/dv/sva/flash_ctrl_sva.core, hw/ip/flash_ctrl/dv/tb/tb.sv
- reset with rma test
- reset with otp test
=> [flash_ctrl,dv] more reset tests

sw/host/opentitanlib/src/transport/ti50emulator/emu.rs, sw/host/opentitanlib/src/transport/ti50emulator/mod.rs
Add support for creating UART,I2C devices based on generated
configuration file.
Signed-off-by: Michał Mazurek <maz@semihalf.com>
=> [opentitanlib] Improve configuration handling for Ti50Emulator

util/reggen/reg_block.py, util/reggen/register.py
Add support for overriding REGWENs with the alias mechanism.
=> [reggen] Add support for overriding REGWENs with the alias mechanism

hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- check outstanding same address traffice for ierr assertion
=> [dv,flash_ctrl] integrity test fix

hw/top_earlgrey/data/chip_testplan.hjson
=> [chip/dv] Fix an unmapped test

hw/ip/kmac/dv/env/kmac_env_pkg.sv, hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
This PR fixes the compile error from PR #13884
=> [dv/kmac] Kmac fi enhancement

hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
=> [dv/pwrmgr] Cleanup sequence side-effects in post_apply_reset

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_derr_detect_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_serr_address_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_serr_counter_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/flash_ctrl/dv/tests/flash_ctrl_base_test.sv
- removed 'most' of redundent seqs
=> [flash_ctrl,dv] tb refactoring

hw/top_earlgrey/data/chip_testplan.hjson
Signed-off-by: Douglas Reis <doreis@lowrisc.org>
=> [chip/dv] Fix the unmapped hmac idle test

hw/ip/kmac/dv/env/seq_lib/kmac_app_vseq.sv, hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv, hw/ip/kmac/dv/env/seq_lib/kmac_sideload_vseq.sv, hw/ip/kmac/dv/env/seq_lib/kmac_smoke_vseq.sv
This PR enhances the kmac_app sequence to randomly set en_sideload key
to 0 or 1.
=> [dv/kmac] enhance app sequence

hw/ip/csrng/rtl/csrng_core.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_rd.sv, hw/ip/gpio/rtl/gpio.sv, hw/ip/keymgr/rtl/keymgr_ctrl.sv, hw/ip/kmac/rtl/kmac_app.sv, hw/ip/otbn/lint/otbn.waiver, hw/ip/otbn/rtl/otbn_mac_bignum.sv, hw/ip/otbn/rtl/otbn_start_stop_control.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv, hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv, hw/ip/prim/rtl/prim_xoshiro256pp.sv, hw/ip/prim_generic/rtl/prim_generic_flash.sv, hw/ip/prim_generic/rtl/prim_generic_flop_en.sv, hw/ip/prim_generic/rtl/prim_generic_pad_attr.sv, hw/ip/prim_generic/rtl/prim_generic_pad_wrapper.sv, hw/ip/rv_core_ibex/rtl/ibex_pmp_reset.svh, hw/top_earlgrey/ip/ast/lint/ast.waiver, hw/top_earlgrey/lint/chip_earlgrey_asic.waiver, hw/top_earlgrey/lint/top_earlgrey.waiver
This cleanup pass gets everything clean except for the top/chip-level and rv_core_ibex, which will be handled separately.
=> [lint] Cleanup pass

hw/ip/entropy_src/rtl/entropy_src_core.sv
This commit introduces minor fixes to the SHA handshaking
implementation put forward in PR #13921.
- The `sha3_ready_mask` is now deasserted starting with the
fw_ov_sha3_disable_pulse (previously it just covered words
starting at the process pulse).  Expanding the mask by these
few clock cycles out ensures that SHA message inputs inserted
(illegally) after the SHA block is closed, still yield
verifiable outputs.
- The `sha3_ready_mask` is now applied both to the SHA input as
well as to the FIFO pop signal on the preconditioning FIFO
(The last lint fix removed the mask from the SHA inputs,
leading to new assertion failures in the most stressful tests)
- The SHA disable alert is now triggered by `fw_ov_sha3_start_pfe`
as opposed to `fw_ov_sha3_start_pfa` (which is only asserted
if …
=> [entropy_src/rtl] Fixes to SHA3 handshaking & alert

sw/device/silicon_creator/lib/drivers/spi_device.h, sw/device/silicon_creator/lib/drivers/spi_device_unittest.cc
=> [sw/silicon_creator] Fix density byte in JEDEC ID

hw/ip_templates/rv_plic/data/rv_plic.prj.hjson.tpl, hw/ip_templates/rv_plic/doc/checklist.md, hw/top_earlgrey/ip_autogen/rv_plic/data/rv_plic.prj.hjson, hw/top_earlgrey/ip_autogen/rv_plic/doc/checklist.md
All items on #13828 have been addressed.
=> [rv_plic] Sign-off to D3

hw/ip/kmac/dv/env/kmac_scoreboard.sv
This PR updates error code information for SwCmdSequence according to
design change #13884.
=> [dv/kmac] Update err code info

sw/device/lib/crypto/aes_gcm/aes_gcm.c
Like GHASH, the GCTR function is a building block for AES-GCM authenticated encryption/decryption. It's based on AES-CTR with a special incrementing function.
Also added some TODOs for a few places where bit manipulation can produce significant GHASH optimizations, as a follow-up to https://github.com/lowRISC/opentitan/pull/13418.
=> [crypto] Implement AES-GCTR for AES-GCM.

hw/dv/sv/mem_model/mem_model.sv, hw/dv/sv/spi_agent/spi_flash_cmd_info.sv, hw/dv/sv/spi_agent/spi_host_driver.sv, hw/ip/spi_device/data/spi_device_testplan.hjson, hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_intercept_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_all_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_upload_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv, hw/ip/spi_device/dv/env/spi_device_env.core, hw/ip/spi_device/dv/env/spi_device_env_pkg.sv, hw/ip/spi_device/dv/env/spi_device_scoreboard.sv, hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
1. randomly enable upload for non-read cmd and randomize busy bit
2. read upload status, fifo depth and read all items in fifos
3. update scb to check upload cmd, addr, payload
4. small refactor scb to handle internally processed cmd
=> [spi_device/dv] Add upload sequence

hw/ip/spi_device/rtl/spi_device.sv
=> [spi_devce] Fix Intercept assertion

hw/ip/entropy_src/dv/cov/entropy_src_cov_if.sv, hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
The cont_ht_cg provides functional coverage for the REPCNT and REPCNTS
health tests.  These so-called continuous health tests do not operate
on fixed windows of data, and thus have different sampling and
binning conditions.
=> [entropy_src/dv] Impl. covergroup for continuous HTs

.github/ISSUE_TEMPLATE/chip-level-test.yml
Add a field to indicate no host-side component.
=> [chip-level tests] fix issue template

hw/dv/sv/cip_lib/cip_base_scoreboard.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_common_vseq.sv
Update seq for new added cm `TLUL_FIFO.CTR.REDUN`
=> [sram_ctrl/dv] Update sec_cm to test `TLUL_FIFO.CTR.REDUN`

hw/ip/prim_generic/lint/prim_generic_pad_wrapper.waiver, hw/top_earlgrey/ip/ast/ast.core, hw/top_earlgrey/ip/ast/lint/ast.waiver, hw/top_earlgrey/lint/chip_earlgrey_asic.waiver
With this, the entire design will be lint-clean.
=> [lint] Get the top-level lint clean

util/container/Dockerfile
Signed-off-by: Hugo McNally <hugo.mcnally@gmail.com>
=> [docker] Fixed typo in Dockerfile ARG.

sw/device/silicon_creator/lib/drivers/spi_device_unittest.cc
Signed-off-by: Cindy Liu <hcindyl@google.com>
=> [sw/silicon_creator] Fix spi_device_unittest gcc-12 compatibility

hw/ip/sysrst_ctrl/data/sysrst_ctrl.prj.hjson, hw/ip/sysrst_ctrl/doc/checklist.md
This can be merged once the pending question on #13995 has been resolved and #14042 has been merged.
=> [sysrst_ctrl] Update checklist and sign-off to D3

.github/ISSUE_TEMPLATE/triage-test.yml
=> [issue-template] Add an issue template for regression triage

.github/ISSUE_TEMPLATE/test-triage.yml
=> [issue-template] Rename template for consistency

hw/top_earlgrey/dv/chip_sim_cfg.hjson
=> [dv,chip] Fix blaze targets in chip sim_cfg

hw/ip/otbn/data/otbn_sec_cm_testplan.hjson
This commmit maps some of the existing tests to correspondiing
V2S countermeasures.
=> [otbn, dv] Mapped existing testcases to V2S countermeasures

doc/project/development_stages.md, doc/rm/comportability_specification/index.md
This alings the terminology to be consistent, as discussed in the TC.
=> [doc] Rename owner to maintainer

hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv, util/topgen/templates/chiplevel.sv.tpl
=> [top] revert ast pok bypass

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_intr_rd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_intr_wr_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/flash_ctrl/dv/tb/tb.sv
=> [flash_ctrl,dv] interrupt mode test

hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv, hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv, hw/ip/entropy_src/dv/tb/tb.sv
=> [entropy_src/dv] Fixes for VCS

sw/device/silicon_creator/mask_rom/data/mask_rom_testplan.hjson
This commit fixes some typos and removes some obsolete test points.
=> [test] Update mask ROM test plan

hw/dv/sv/mem_model/mem_model.sv, hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
Need to consider z/x as high z may be collected
Also changed mem_model data type from bit to logic
=> [spi_device/dv] Fix payload check

hw/dv/sv/spi_agent/spi_agent_cfg.sv, hw/dv/sv/spi_agent/spi_host_driver.sv, hw/dv/sv/spi_agent/spi_monitor.sv
This reduces some replicated code
=> [spi_device/dv] extract a common task for monitor and diver

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
=> [otbn,dv] Fix loop warping force

hw/dv/sv/mem_bkdr_util/mem_bkdr_util__rom.sv
- follow up #13883.
- fix the digest update routine to propertly account for the
new kmac/rom_ctrl interface
=> [dv/mem_bkdr] Fix digest update

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/chip_env.sv, hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_clkmgr_escalation_reset_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, hw/top_earlgrey/dv/env/top_earlgrey_error_injection_ifs_bind.sv, hw/top_earlgrey/dv/tb/tb.sv, sw/device/lib/testing/aon_timer_testutils.c, sw/device/lib/testing/clkmgr_testutils.c, sw/device/tests/sensor_ctrl_alerts.c, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/clkmgr_escalation_reset_test.c
=> [dv,chip_sw] Add clkmgr_escalation_reset test

sw/device/silicon_creator/rom/boot_policy_ptrs.h
=> [sw/silicon_creator] Remove stale TODO

sw/device/tests/alert_handler_ping_timeout_test.c
This PR fixes chip_sw_alert_handler_ping_timeout error.
When alert's ping timeout is set to a small value, it might trigger
spurious alert depends on the timing. And eventually might fire an
unexpected interrupt.
To avoid this issue, this PR slightly modify the C test to check timeout
interrupt but also allows other interrupt to fire in the meantime.
=> [dv/chip] Fix alert ping timeout error

hw/ip/prim/rtl/prim_reg_cdc_arb.sv
- the old design had the term `dst_update_i & dst_latch_d`.
- the UNR tool determined the case where dst_update_i = 0 and dst_latch_d = 1 does not exist.
- this is true, because the conditions that would `dst_latch_d` to become 1 would also always lead
to dst_update_i to be true.  However, writing the terms as the above makes the intent clearer.
- re-write the code a bit to indicate the actual scenario that occurs, and also add a couple of
assertiosn to ensure the original spirit of the design is always met.
=> [prim] More refactoring to remove UNR generation

hw/ip/spi_device/data/spi_device_testplan.hjson, hw/top_earlgrey/dv/env/seq_lib/chip_sw_deep_sleep_all_reset_vseq.sv, sw/device/tests/sim_dv/pwrmgr_deep_sleep_all_reset_reqs_test.c, sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_reset_reqs_test.c
Also some small updates for others and fix unmapped tests and testpoints
=> [spi_device/dv] Update testplan for wren/wrdi and mailbox crossing

hw/ip/rom_ctrl/data/rom_ctrl.prj.hjson, hw/ip/rom_ctrl/doc/checklist.md
Merge after https://github.com/lowRISC/opentitan/pull/14371 has landed.
Fixes https://github.com/lowRISC/opentitan/issues/14097.
=> [rom_ctrl] Move to D3

hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
This commit refactors the RNG and Base VSeq's to recover from simulated
failures of the RNG push-pull agent.
The interrupt handler thread in then the RNG Vseq  has been reorganized
to take advantage of the fact that the main thread is now responsible
for doing random reconfigurations whenever any failure has been
detected.  A RNG-failure recovery sequence has then been added to the
main thread.  The health test interrupt thus just triggers a shutdown
of all background operations and a transition to the main thread.
Furthermore, the random health-check statistics gathering operations
(which were previously only performed after health test failures), have
now been added to a general disable_dut task in the base entropy_src
vseq, along with the associated random variables.
Signed-off-by: …
=> [entropy_src/dv] Recover from RNG failures

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cov.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_ctrl_arb_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Fix 2 regression errors
- flash_ctrl_mp_regions
- flash_ctrl_rma
And add missing covergroups
=> [flash_ctrl,dv] add misc cg

hw/ip/pinmux/data/pinmux.prj.hjson, hw/ip/pinmux/doc/checklist.md, hw/ip/pinmux/rtl/pinmux.sv
Addresses https://github.com/lowRISC/opentitan/issues/14341
=> [pinmux] Move to D3

hw/ip/prim/rtl/prim_reg_cdc_arb.sv
=> [prim] Add () to s_eventually

hw/ip/prim/rtl/prim_reg_cdc.sv
- there is no functional change
- the code is tweaked slightly to make UNR spit out fewer
unreachable sections.
- the original code made the intent clearer, so to compensate,
an assertion was added for the original spirit of operation.
=> [prim] Tweak code slightly to avoid UNR entries

hw/ip/otbn/dv/model/iss_wrapper.cc, hw/ip/otbn/dv/model/iss_wrapper.h, hw/ip/otbn/dv/model/otbn_core_model.sv, hw/ip/otbn/dv/model/otbn_model.cc, hw/ip/otbn/dv/model/otbn_model.h, hw/ip/otbn/dv/model/otbn_model_dpi.h, hw/ip/otbn/dv/model/otbn_model_dpi.svh, hw/ip/otbn/dv/otbnsim/sim/sim.py, hw/ip/otbn/dv/otbnsim/sim/state.py, hw/ip/otbn/dv/otbnsim/stepped.py, hw/ip/otbn/dv/uvm/env/otbn_escalate_if.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_escalate_vseq.sv, hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson, hw/ip/otbn/dv/uvm/tb.sv, hw/ip/otbn/dv/verilator/otbn_top_sim.sv
Includes works towards finishing up [#13964](https://github.com/lowRISC/opentitan/issues/13964)
=> [otbn,dv] Connect and test RMA connections in OTBN

hw/formal/tools/jaspergold/fpv.tcl, hw/top_earlgrey/formal/top_earlgrey_fpv_cfgs.hjson
This PR updates some syntax for the latest JG version.
=> [fpv] Update tcl syntax for latest JG version

doc/ug/bazel_notes.md
Add details on how to create a `.bazelrc` file.
=> [bazel] update Bazel notes on `.bazelrc` files

hw/ip/spi_device/dv/env/seq_lib/spi_device_cfg_cmd_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_flash_all_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_flash_mode_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_intercept_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
Created a parallel thread to update read buffer based on watermark or
flip event.
=> [spi_device/dv] Enhance read buffer sequences

sw/device/silicon_creator/rom/data/rom_testplan.hjson
=> [test] Finalize ROM e2e test plan

hw/ip/spi_device/data/spi_device_testplan.hjson
Add a test entry and a covergroup for it
=> [spi_device/dv] Add TPM + flash/passthrough in testplan

hw/ip/spi_device/doc/_index.md
=> [spi_device/doc] Update a typo

hw/ip/csrng/dv/env/csrng_env_cfg.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
Will be covered as discussed in OT silicon meeting and described by #14407, so removing.
=> [csrng/dv] Remove forces for reset/error state transitions

hw/dv/tools/dvsim/sim.mk, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/seq_lib/chip_tap_straps_vseq.sv
Fixes chip_sw_example_rom, chip_tap_straps_* tests.
Fixes ##14192, #14321.
=> [chip dv] Fixes for chip level falures

azure-pipelines.yml
=> [ci] Write test output to log in sw_build

hw/ip/flash_ctrl/dv/env/flash_ctrl_dv_if.sv, hw/ip/flash_ctrl/dv/sva/flash_ctrl_bind.sv, hw/ip/flash_ctrl/dv/tb/tb.sv
move ctrl_dv_if binding to tb.sv
=> [flash_ctrl,dv] fix fpv compile error

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
Also fixes a failure in VCS related with forcing loop warp value. That was the reason for failures regarding the loop warping in the nightly regression.
=> [otbn,dv] Verible formatting for base_vseq

hw/ip/spi_device/rtl/spi_readcmd.sv
Related Issue: https://github.com/lowRISC/opentitan/issues/14538
This commit revises logic to latch read address only pointing to the
read buffer space.
However, this still does not track the last byte host read. It latches
the address field in the read command. The issue is being tracked in
https://github.com/lowRISC/opentitan/issues/14586
=> [spi_device] Latch read command address only for Readbuffer

sw/device/silicon_creator/rom/data/rom_testplan.hjson
=> [sw/silicon_creator] minor fixes in rom e2e test plan

hw/top_earlgrey/dv/env/seq_lib/chip_sw_flash_init_vseq.sv
- Address tb issue #14317
- At LcStProd, check otp_ctrl secret0/2 digest with expected seed_hw_rd_en value.
=> [chip,dv] Add seed_hw_rd_en check to flash_init

hw/top_earlgrey/data/chip_conn_testplan.hjson, hw/top_earlgrey/data/chip_testplan.hjson
=> [top/testplan] Add some description to csrng test items

hw/ip/prim/rtl/prim_reg_cdc_arb.sv
- fixes part of https://github.com/lowRISC/opentitan/issues/14585
- in addition to the aon_timer related assertion failure, there is also
one in usbdev.
- to fix these issues, update prim_reg_cdc_arb to only create a handshake
event when the update actually contains a different value from the
one currently sitting in the transit register.   This ensures that
even if the instantiator ties a particular register's de to 1, it will
not generate continuous update requests unless it actually has a
different value.
=> [dv/top] Regression triage

azure-pipelines.yml
This PR bumps the Azure-hosted runners from Ubuntu 18.04 to Ubuntu 20.04.
=> [ci] Bump Azure runners up to Ubuntu-20.04

.github/ISSUE_TEMPLATE/test-triage.yml
- Add an example to help filer fill in details
=> [issue-template] Add example for dvsim invocation

hw/ip/flash_ctrl/doc/dv/index.md
=> [flash_ctrl,dv] update dv doc

.gitattributes
Add doc attributes to `.gitattributes`
=> ci: Define doc in .gitattributes

hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
The SHA conditioner does not always get reset during a disable event.
When the scoreboard gets detected a disable event it need to determine
which data will be purged as raw data, living in a FIFO vs. data
that has been absorbed in the SHA conditioning state.  In order to
simplify this these two classes of data are now stored in separate FIFOs.
This commit also adds some further timing adjustments to properly predict
a number of corner cases in dealing with processing of enable or disable
pulses close to SHA data inputs or SHA3 start commands.
=> [entropy_src/dv] Refine scoreboard handling of data

hw/ip/entropy_src/rtl/entropy_src_core.sv
The PR makes a couple of minor adjustments after #14390, notably to
revert the FIFO clear mechanism in FW_OV_INSERT_ENTROPY mode.
Both changes treat minor corner cases, yet ones that come up often
in regression.
FW_OV mode requires special treatment as the FW_OV write FIFO does
not apply any backpressure when the IP is disabled (which the
RNG mode does have), thus we cannot assume that the user will
not _try_ to insert entropy during this time.  This is a narrow
corner case, and one which generates an exception, but it is
still important for the DUT to behave in a predictable fashion.
This commit also corrects the cases where the user inserts entropy
at a valid time, but then disables the DUT before the SHA3 block can
accept it.  This is technically legal, and should result in the word …
=> [entropy_src/rtl] Fine-tune SHA3 in FW_OV mode.

hw/dv/sv/csr_utils/csr_utils_pkg.sv, hw/dv/sv/dv_utils/dv_utils_pkg.sv, hw/dv/sv/jtag_dmi_agent/jtag_dmi_reg_frontdoor.sv, hw/dv/sv/jtag_riscv_agent/jtag_riscv_agent_pkg.sv, hw/ip/rv_timer/dv/env/seq_lib/rv_timer_base_vseq.sv, hw/top_earlgrey/dv/env/ast_ext_clk_if.sv
No functional change.
follow-up cleanup PR of #14593
=> [dv] Replace wait_timeout with DV_WAIT_TIMEOUT

hw/top_earlgrey/data/chip_testplan.hjson
Updated as it's clear what we need to test in
`chip_sw_spi_device_pass_through_collision`
=> [chip, dv] update SPI device testplan

hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_connect_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
- Address #12820
- Add jtag / ast io connectivity test
- Add random flash_ctrl.init csr assert to rma test
=> [flash_ctrl,dv] DV AI update

hw/top_earlgrey/cdc/cdc_waivers.tcl
W_ASYNC_RST_FLOPS :
-spi_device and dmi jtag
W_RECON_GROUPS :
-Signals driven by AST
-Recon in RV PLIC
=> [cdc] misc. waivers including PAD reset issue

doc/sg/c_cpp_coding_style.md
I'm putting together some stylle rules that I got from feedbacks I received on my own PRs. These rules are common sense for the engineers working on the Opentitan for a longer period, but it is helpful for incomers to have them summarized in the Coding style guide
=> Update the C/Cpp coding style guide

azure-pipelines.yml, hw/ip/otp_ctrl/data/otp_ctrl_img_rma.hjson
=> [ci, sw/silicon_creator] Fix handling of CW310 test results, update OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA

hw/ip/prim/doc/prim_clock_gp_mux2.md
Updated doc file for this new prim library
Signed-off-by: Joshua Park [jeoong@google.com](mailto:jeoong@google.com)
=> [doc] Updated doc file for this new prim library

hw/top_earlgrey/cdc/cdc_waivers.alert_handler.tcl, hw/top_earlgrey/cdc/cdc_waivers.tcl
-W_RECON_GROUPS
-S_GENCLK
-W_ASYNC_RST_FLOPS
-W_MASYNC
This PR includes https://github.com/lowRISC/opentitan/pull/13739.
Previous discussion can be found.
=> [CDC] multiple waivers in

sw/host/opentitanlib/src/spiflash/flash.rs, sw/host/tests/rom/e2e_bootstrap_entry/src/main.rs
Fixes https://github.com/lowRISC/opentitan/issues/14458
=> [test] Add rom_e2e_bootstrap_write_enable_disable

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
Disabled TL abort for shadow reg.
if there is any shadow reg, we shouldn't abort TL access, otherwise, it may do only one
write to the shadow reg, which may cause an unexpected recoverable error.
=> [dv] Fix CSR sequence with shadow regs

util/container/Dockerfile
Bump the Ubuntu version used in the Docker container.
=> [docker] Bump Docker image to Ubuntu 20.04

sw/host/opentitanlib/src/transport/ti50emulator/emu.rs
Adds a function that removes the devices file in case they are left by
the Emulator sub-process.
Signed-off-by: Michał Mazurek <maz@semihalf.com>
=> [opentitanlib] Ti50Emulator add cleanup function

hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
=> [dv/sensor_ctrl] Fix alert for WE_ONEHOT_ERROR assertion

hw/top_earlgrey/ip/ast/data/ast.hjson, hw/top_earlgrey/ip/ast/doc/ast_regs.html, hw/top_earlgrey/ip/ast/lint/ast.waiver, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_reg_pkg.sv, hw/top_earlgrey/ip/ast/rtl/usb_clk.sv, hw/top_earlgrey/ip/ast/rtl/usb_osc.sv, hw/top_earlgrey/lint/chip_earlgrey_asic.waiver
USB Clock Calibrate Test Supports
@arnonsha @zi-v @sha-ron 
=> [AST] USB Clock Calibrate Test Supports

hw/ip/prim/rtl/prim_clock_meas.sv
=> [prim] Patch up design to help with coverage

hw/ip/lc_ctrl/rtl/lc_ctrl.sv
This is something that @matutem discovered while writing the chip-level alert test in #14449.
This integrity error remained unconnected because initially the reg_top only checked for bus integrity errors (and the TAP side does not support that). However, since we now also have WE checkers inside the reg_top, this signal should be connected for the TAP side also.
=> [lc_ctrl] Fix for unconnected WE checker on tap side

hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.hjson, hw/top_earlgrey/ip/sensor_ctrl/doc/_index.md, sw/device/lib/dif/dif_sensor_ctrl.c
=> [sensor_ctrl] D3 Cleanup

hw/ip/otp_ctrl/data/otp_ctrl.prj.hjson, hw/ip/otp_ctrl/doc/checklist.md
To be merged once all cleanup items have been addressed.
Fix #13438
=> [otp_ctrl] Update checklist and move to D3

rules/opentitan_gdb_test.bzl, sw/device/examples/sram_program/BUILD, sw/device/examples/sram_program/sram_program.c, util/openocd/target/BUILD
=> [bazel] Add SRAM program test rule for CW310

sw/device/tests/sim_dv/BUILD
=> [chip,dv] update include path for pinmux reg from ip to top

sw/device/tests/sim_dv/rv_dm_ndm_reset_req.c
This PR was originaly fixing the `chip_rv_dm_ndm_reset_req` failure in the nightly.
But now it changed to just fix a typo and and a minor refactor to improve readability.
=> Refactor rv dm ndm reset req test

hw/ip/otbn/dv/tracer/rtl/otbn_trace_if.sv, hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv
Related with https://github.com/lowRISC/opentitan/issues/14540
=> [otbn,dv] Add rf_base_we_err to bad_internal_cg

hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/prim_generic/rtl/prim_generic_flash_bank.sv
=> [flash_ctrl,dv] Enable random device param for all tests

hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
=> [flash_ctrl] fix is_fatal connection

hw/ip/flash_ctrl/dv/cov/flash_ctrl_cov_bind.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_otf_item.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_disable_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/flash_ctrl/dv/tests/flash_ctrl_base_test.sv
Add flash disable test. This PR only use lc_escalate_en_i.
Othe disable mode (by sw command) will be added in V2S test.
=> [flash_ctrl,dv] flash disable test

sw/device/silicon_creator/rom/data/rom_testplan.hjson
=> [test] Update rom_e2e_asm_init test point

hw/top_earlgrey/data/chip_testplan.hjson
This adds a testpoint for #14782.
=> [test] Add extended range clock frequency testpoint

util/dvsim/Scheduler.py
This commit adds a SIGTERM handler for dvsim. The kokoro CI runner terminates the dvsim invocation if it exceeds the 24 hour runtime. Without the SIGTERM handler, the jobs running on the cloud (GCP) end up as zombies. With this change, dvsim will attempt to kill the cloud jobs cleanly, generate and print the final reports before exiting.
=> [dvsim] Install a SIGTERM handler

hw/ip/entropy_src/rtl/entropy_src_core.sv
The DV changes added in PR #14643 immediately revealed that there are
some gaps in the backpressure pipeline in the entropy_src core, and
that stalls from the cs_aes_halt_ack can cause entropy to be dropped
before it gets SHA conditioner, which could lead to poor entropy
outputs if enough entropy is dropped.
This PR corrects the problem by applying consistent backpressure
throughout the entropy_src data processing chain.  With a
long enough delay entropy can be stalled all the way back at the
RNG input. Even if the external RNG source does not support
backpressure, this is fine because entropy dropped at the is not
counted when calculating the number of inputs gathered to create
the output seeds.
Applying backpressure all the way back to the RNG input also helps
for verification, as the …
=> [entropy_src/rtl] Provide backpressure on core FIFOs

hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.prj.hjson, hw/top_earlgrey/ip/sensor_ctrl/doc/checklist.md
Can be merged once #14723 has landed.
=> [sensor_ctrl] Move to D3

_index.md, doc/security/_index.md, doc/security/threat_model/index.md
This PR introduces a lightweight threat model for OpenTitan.
=> [doc] Add lightweight threat model

hw/dv/tools/dvsim/xcelium.hjson, hw/ip/edn/dv/tests/edn_alert_test.sv, hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv, hw/ip/pwm/dv/env/pwm_scoreboard.sv, hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
This addresses #14032 and one part of #13985.
=> [dvsim] Promote xcelium warning ENUMERR to an error 

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
This PR fixes the same_csr_outstanding test to support multi-ral.
Previous code uses default virtual sequencer for the `tl_access` task, which does not include the case where the model has more than one RAL.
Fix issue #14789
=> [dv/common] Same csr outstanding test support multi ral

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- add better handling for flash that deposits data too fast for interrupts to be practical
=> [flash_ctrl/dv] update the flash interrupt read handling

sw/host/opentitanlib/src/bootstrap/rescue.rs
As part of the "rescue" protocol for Ti50 updates, OpenTitan tool needs
to recognize the "RW" part of the given image file.  This is done
through heuristics that recognize the header of each section, and
relying on the order in which sections appear.
Recent images happen to have the header signature in more places in the
image, causing mis-identification of the RW section.  This CL improves
the heuristics.
Change-Id: I3f9e0003ecf71b3967d25af88db962b87d041b0f
=> [opentitantool]: Adapt heuristics for Ti50 images

hw/top_earlgrey/ip/ast/rtl/sys_osc.sv
Adding an option to set the calibrated SYS clock to 70MHz using a plusearge flag, `cal_sys_clk_70mhz`.
Currently the the calibrated SYS clock is set to 100MHz unles this flag is activated.
Do we need to randomize this flag?
@tjaychen @sriyerg @sha-ron 
=> [ast] Add 'plusargs' to set Calibrated SYS clock to 70MHz

sw/device/silicon_creator/lib/drivers/spi_device.c, sw/device/silicon_creator/lib/drivers/spi_device_unittest.cc
This PR changes the order in which is spi_device initialized. Specifically, we now initialize the SFDP buffer, payload buffer, and the status register before registering the commands per @a-will's request. IIUC this helps DV + should have been done this way from start. I didn't have the chance to come back to this after the conversations about buffers.
=> [sw/silicon_creeator] Register spi commands after initializing spi_device buffers

sw/host/opentitanlib/src/util/bigint.rs
Fixes #14863
Thanks for walking through this with me @jadephilipoom!
=> [opentitanlib] Update FixedSizeBigInt to_bytes methods to return BYTE_LEN long vectors

sw/device/silicon_creator/rom/data/rom_testplan.hjson, sw/host/tests/rom/e2e_bootstrap_entry/src/main.rs
This PR adds e2e tests for the second phase of bootstrap:
* #14463
* #14464
* #14465 
* #14466
=> [test] Add rom_e2e_bootstrap_phase2 tests

hw/ip/kmac/dv/env/kmac_env_pkg.sv, hw/ip/kmac/dv/env/kmac_scoreboard.sv, hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv, hw/ip/kmac/dv/env/seq_lib/kmac_smoke_vseq.sv
This PR adds a checking for hash_cnt register.
=> [dv/kmac] Add checking for hash_cnt

util/dvsim/LauncherFactory.py, util/dvsim/SGE.py, util/dvsim/SgeLauncher.py, util/dvsim/dvsim.py, util/dvsim/qsubopts.py
Signed-off-by: Sharon Topaz <sharon.topaz@nuvoton.com>
Hi,
This PR include the changes/additions needed to support SunGrid launcher.
=> SunGrid launcher support

hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv, sw/device/lib/testing/keymgr_testutils.h
Addressed #14835
fixed SW and SV key version mismatch
=> [chip, dv] Fix chip_sw_keymgr_key_derivation

hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/lib/testing/flash_ctrl_testutils.c, sw/device/lib/testing/flash_ctrl_testutils.h, sw/device/tests/BUILD, sw/device/tests/sensor_ctrl_alerts.c
fixes #14844
randomize the events tested each time and increase the number of reseeds
=> [top/dv] shorten sensor_ctrl_alert_test

hw/top_earlgrey/data/chip_testplan.hjson
This fixes https://github.com/lowRISC/opentitan/issues/14140.
=> [test] Cross reference chip_sw_rstmgr_alert_info test

hw/ip/flash_ctrl/data/flash_ctrl.prj.hjson, hw/ip/flash_ctrl/doc/checklist.md
AI(#14527) has been addressed as below.
item1: https://github.com/lowRISC/opentitan/pull/14641
item2: https://github.com/lowRISC/opentitan/pull/14672
item3: https://github.com/lowRISC/opentitan/pull/14745
item4: https://github.com/lowRISC/opentitan/pull/14837
item5: https://github.com/lowRISC/opentitan/pull/14641
item6: https://github.com/lowRISC/opentitan/pull/14740
=> [flash_ctrl/dv] Sign off V2

hw/ip/entropy_src/rtl/entropy_src_core.sv, hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
This commit handles a number of corner cases that can occur due to the
non-zero processing time of the SHA engine. Though all of these were
identified as by long delays in verifying the cs_aes_halt_req/ack
handshake, the following issues could all come up due to rapid
poorly-timed programming sequences.
The general issues are that:
1. The SHA engine is unresponsive to disable events while processing, and
2. The bypass FIFO can stall for a number of reasons (BOOT mode
finished, mismatch between HT window size and seed size, etc).
The following corner-case delay scenarios are handled in this commit.
**Missed Disable Pulses**
The `main_sm` does not see disable pulses while the SHA block is
processing. (NOTE: For the purposes of this discussion AES-halt
handshakes are considered part of the …
=> [entropy_src/rtl] Corner cases in handling delays

doc/ug/bazel_notes.md
Add some additional notes about cleaning the disk cache and general advice for using Bazel with Git worktree.
=> [doc] Add more bazel usage notes (disk cache and worktrees)

hw/top_earlgrey/dv/env/chip_if.sv
Not needed because there is only one interface
attached to DIOs. This also fixes the SPI device
tests (SPI agent drives an X on sio pin).
=> [chip dv] Disable X-check on DIOs

hw/top_earlgrey/ip/ast/rtl/sys_osc.sv
=> [ast] Update the useability of the Jitter model

doc/getting_started/setup_fpga.md, doc/rm/ref_manual_fpga.md, rules/opentitan_gdb_test.bzl, rules/opentitan_test.bzl, sw/host/opentitantool/BUILD, sw/host/opentitantool/src/command/fpga.rs, sw/host/opentitantool/src/command/mod.rs, sw/host/opentitantool/src/main.rs
I am grouping these commands in preparation of adding a third FPGA command that resets the board (issue #14686).
=> [opentitantool] Move load-bitstream and set-pll into a new fpga command group.

hw/ip/kmac/dv/env/kmac_scoreboard.sv, hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv, hw/ip/kmac/dv/env/seq_lib/kmac_entropy_refresh_vseq.sv, hw/ip/kmac/dv/env/seq_lib/kmac_smoke_vseq.sv
This PR supports entropy_req reg to request entropy.
=> [dv/kmac] support entropy request reg

sw/device/tests/otbn_mem_scramble_test.c, sw/device/tests/sim_dv/sram_ctrl_main_scrambled_access_test.c
This PR adjusts the false positive tolerance for ECC error on otbn and sram mem scramble test.
This is the rationale discussed with @vrozic
Each word has 7 bits of ECC, so the probability that a word would generate an ECC error is (127/128). Then the probability that all `kWordsAmount` will generate ECC error is `pow(127/128, kWordsAmount)` after re-scrambling.
Based on that this PR increases the tolerance to false positive in order to fail less in the nightly regression. 
Fixes #14841
=> Fix mem scramble test

util/prep-bazel-airgapped-build.sh
The airgapped image requires an "initialized" bitstreams cache in order for the bitstream cache "offline" mode to properly function. This reduces the number of bistreams included to just one to reduce the size of the airgapped images.
=> [bazel] reduce number of bitstreams included in the airgapped image

hw/dv/sv/i2c_agent/i2c_driver.sv, hw/dv/sv/i2c_agent/i2c_item.sv, hw/dv/sv/i2c_agent/i2c_monitor.sv, hw/dv/sv/i2c_agent/seq_lib/i2c_base_seq.sv, hw/dv/sv/i2c_agent/seq_lib/i2c_device_response_seq.sv, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/chip_env.sv, hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/chip_env_pkg.sv, hw/top_earlgrey/dv/env/chip_if.sv, hw/top_earlgrey/dv/env/chip_virtual_sequencer.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_host_tx_rx_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
Integrate #14778 with i2c_host_tx_rx test.
Also make some minor clean-up to the i2c_agent.
#14778 will need to be merged before this one can go forward. 
This PR is now WIP from the chip_if update.
It works, but there is some clean-up that has to be done inside chip_if
=> [top/dv] i2c_host_tx_rx_test

hw/ip/kmac/dv/env/kmac_env_pkg.sv, hw/ip/kmac/dv/env/kmac_scoreboard.sv, hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv, hw/ip/kmac/dv/env/seq_lib/kmac_entropy_refresh_vseq.sv
Upon entropy request or hash_cnt reaches threshold, we expect to see an entropy fetch.
=> [dv/kmac] Add scb checkings for entropy

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_sleep_pin_mio_dio_val_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/sleep_pin_mio_dio_val_test.c
This PR scaffolds the test framework and basic communication logics.
The test is not yet fully implemented (to reduce the burdens to reviewers). The test can be compiled and runnable but the test is failed always.
=> [chip] chip_sw_sleep_pin_mio_dio_val

hw/dv/sv/spi_agent/spi_agent_cfg.sv, hw/dv/sv/spi_agent/spi_monitor.sv, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_if.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_spi_host_tx_rx_vseq.sv, hw/top_earlgrey/dv/tests/chip_base_test.sv, sw/device/tests/sim_dv/spi_host_tx_rx_test.c
=> [top/dv] Add some basic IO tests to the smoke regression

sw/device/tests/autogen/plic_all_irqs_test.c, util/topgen/templates/plic_all_irqs_test.c.tpl
This additional check makes sure that the configured PLIC target ID corresponds to the hart ID of the processor this is executed on. To be used in single-hart systems only.
This addresses this comment here: https://github.com/lowRISC/opentitan/pull/8574#discussion_r968990198
=> [test/rv_plic] Add a hart_id check to the test

hw/dv/sv/spi_agent/spi_device_driver.sv
2 places that kill the thread when csb is dropped, which caused errors in xcelium
=> [spi_device/dv] Fix xcelium errors

hw/dv/sv/spi_agent/seq_lib/spi_device_flash_seq.sv, hw/dv/sv/spi_agent/seq_lib/spi_host_flash_seq.sv, hw/dv/sv/spi_agent/seq_lib/spi_host_seq.sv, hw/dv/sv/spi_agent/spi_agent_cfg.sv, hw/dv/sv/spi_agent/spi_agent_pkg.sv, hw/dv/sv/spi_agent/spi_device_driver.sv, hw/dv/sv/spi_agent/spi_host_driver.sv, hw/dv/sv/spi_agent/spi_item.sv, hw/dv/sv/spi_agent/spi_monitor.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv, hw/ip/spi_device/dv/env/spi_device_env_cfg.sv, hw/ip/spi_device/dv/env/spi_device_env_pkg.sv, hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
1. Update spi sequence to be able to select CSB
2. update agent to switch polariy/phase when CSB is changed
3. Update agent to pick CSB from either cfg or item
Also fixed TPM tests due to a polarity issue
=> [spi_device/dv] Update to handle TPM transaction in spi agent (part1)

COMMITTERS
=> [COMMITTERS] Name Change

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson
=> [dv, edn] Add the test chip_sw_edn_entropy_reqs_jitter

hw/top_earlgrey/data/chip_testplan.hjson
- enhance existing tests
- add new test points.
=> [top/dv] update testplan for manufacturing

hw/top_earlgrey/data/chip_testplan.hjson
=> [chip, dv] Fix unmapped spi_host test

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sleep_pin_mio_dio_val_vseq.sv
Added more debug info (printout).
=> [chip] sleep_pin_mio_dio_val #5

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/env/seq_lib/chip_sw_sleep_pin_mio_dio_val_vseq.sv
This PR contains #15046. Please review last two commits.
=> [chip dv] chip_sw_sleep_pin_mio_dio_val #6 (last)

sw/device/tests/BUILD, sw/device/tests/pmp_smoketest_tor.c, sw/device/tests/rv_core_ibex_address_translation_test.c, sw/device/tests/sram_ctrl_execution_test.c
Fixes a merge skew issue between #14855 and #15056.
=> fix merge skew

hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_access_after_disable_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson
- Add local escalation test
- Update test plan with auto_gen csr tests for regwen and shadow
- Remove unused arg from otf_direct_read
- Add ctrl only option to random op send
=> [flash_ctr,dv] Add more v2s tests

hw/dv/sv/dv_utils/dv_macros.svh, hw/dv/sv/spi_agent/seq_lib/spi_host_tpm_seq.sv, hw/dv/sv/spi_agent/seq_lib/spi_seq_list.sv, hw/dv/sv/spi_agent/spi_agent.core, hw/dv/sv/spi_agent/spi_agent_cfg.sv, hw/dv/sv/spi_agent/spi_agent_pkg.sv, hw/dv/sv/spi_agent/spi_host_driver.sv, hw/dv/sv/spi_agent/spi_item.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_locality_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_read_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_write_vseq.sv
1. Moved TPM read/write sequence to spi_host_driver and added spi_host_tpm_seq
2. Simplified the virtual sequences in order to support more free random sequences
=> [device/dv] Update to handle TPM transaction in spi agent (part2)

hw/ip/i2c/dv/env/i2c_scoreboard.sv
=> [i2c/dv] update scoreboard handling for chained reads

hw/ip/otbn/rtl/otbn.sv
Added assertions are making sure that two things happen. First, a secure wipe would trigger a change of key value in I/DMEM in which the new value should come from URND. Second, after that change key should change a second time, this time with valid being high and value should come from OTP interface (meaning it is sideloaded).
Goes towards completing assertions that checks secure wipe functionality, mentioned here: https://github.com/lowRISC/opentitan/pull/14895#issuecomment-1246998004
=> [otbn,dv] Add assertions to check I/DMEM SEC_WIPE

hw/top_earlgrey/data/chip_testplan.hjson
It's a subset of chip_sw_tap_strap_sampling.
=> [chip, dv] chip_sw_rv_dm_jtag_tap_sel

util/prep-bazel-airgapped-build.sh
=> [bazel] Refresh bitstreams cache before copying to airgapped dir

bazelisk.sh
This is just a convenience feature that makes it easier to build a target and then do something with the output files.
I found myself frequently building disassemblies, using "./bazelisk.sh outquery" to find the filename, and then opening the output file in "less". This workflow can now be accomplished with a command like this:
./bazelisk.sh build-then "less %s" //sw/device/silicon_creator/rom:rom_fpga_cw310_dis
=> [bazel] Add 'build-then' command to bazelisk.sh

hw/dv/sv/spi_agent/spi_agent_pkg.sv, hw/dv/sv/spi_agent/spi_host_driver.sv, hw/ip/spi_device/data/spi_device_testplan.hjson, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_read_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_rw_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv, hw/ip/spi_device/dv/env/spi_device_env.core, hw/ip/spi_device/dv/env/spi_device_env_pkg.sv, hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
1. Consolidate tpm read and write vseq
2. Randomized the data size from 1-16
the 2nd commit only rename tpm_read_vseq -> tpm_rw_vseq
=> [device/dv] Update to handle TPM transaction in spi agent (part3)

hw/top_earlgrey/ip/ast/rtl/adc.sv, hw/top_earlgrey/ip/ast/rtl/aon_clk.sv, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_alert.sv, hw/top_earlgrey/ip/ast/rtl/ast_bhv_pkg.sv, hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv, hw/top_earlgrey/ip/ast/rtl/ast_dft.sv, hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv, hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv, hw/top_earlgrey/ip/ast/rtl/io_clk.sv, hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv, hw/top_earlgrey/ip/ast/rtl/rng.sv, hw/top_earlgrey/ip/ast/rtl/sys_clk.sv, hw/top_earlgrey/ip/ast/rtl/usb_clk.sv
Add to files header auto-generated warning:
```
//
// -------- W A R N I N G: A U T O - G E N E R A T E D  C O D E !! -------- //
// PLEASE DO NOT HAND-EDIT THIS FILE. IT HAS BEEN AUTO-GENERATED.
//
```
=> [ast] Update AST files header with auto-generated information

hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
=> [entropy_src/dv] VCS compatibility
