- hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_filesystem_support_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv
- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Test and testplan update for #15037 
See the testplan(https://github.com/lowRISC/opentitan/blob/9a971e1559d4ad3253116ed30ae537f3771f2ef5/hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson#L377)
for detail.
> [flash_ctrl,dv] general filesystem support test

- doc/security/specs/ownership_transfer/_index.md
Adds a step-by-step summary of how ownership transfer works and a few concrete examples to the ownership transfer documentation page. This is designed to complement the more detailed information already there and give newcomers some context.
> [doc] Add a high-level summary of ownership transfer.

- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/pwrmgr_low_power_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_sleep_pin_mio_dio_val_vseq.sv
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/sleep_pin_mio_dio_val_test.c
This PR randomizes the sleep mode (normal vs deep). The revised test covers `chip_sw_random_sleep_pin_mio_dio_val` too.
> [chip] random sleep pin mio dio val

- hw/dv/sv/spi_agent/spi_agent_cfg.sv
- hw/dv/sv/spi_agent/spi_host_driver.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_locality_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_rw_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_write_vseq.sv
- hw/ip/spi_device/dv/env/spi_device_env_cfg.sv
- hw/ip/spi_device/dv/env/spi_device_env_pkg.sv
1. Update locality sequence to use the new method
2. Remove csb_consecutive and clean up used task/functions
> [spi_device/dv] Update TPM sequences

- hw/ip/kmac/dv/env/kmac_env.core
- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_entropy_ready_error_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_vseq_list.sv
- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
This PR adds a service rejected error check in kmac app interface. Once issue #15140 is resolved, we will add the similar cases for sw interface.
Signed-off-by: Cindy <chencindy@google.com>
> [dv/kmac] Add service rejected error

- hw/ip/spi_device/data/spi_device.hjson
- hw/ip/spi_device/dv/env/spi_device_env_pkg.sv
- hw/ip/spi_device/rtl/spi_device_reg_top.sv
Also update the corresponding parameter in TB
> [spi_device] Update max_rd_size to 64 bytes

- hw/ip/kmac/dv/env/seq_lib/kmac_lc_escalation_vseq.sv
FSM coverage is low for kmac due to the transaction to lc_escalation stage.
This PR adds more possibility for DUT to issue lc_escalation during kmac busy.
Signed-off-by: Cindy <chencindy@google.com>
> [dv/kmac] Enhance lc_escalation test

- hw/dv/sv/spi_agent/spi_agent_cfg.sv
- hw/dv/sv/spi_agent/spi_agent_pkg.sv
- hw/dv/sv/spi_agent/spi_device_driver.sv
- hw/dv/sv/spi_agent/spi_host_driver.sv
- hw/dv/sv/spi_agent/spi_monitor.sv
1. small refactor to reuse the part that kills threads after CSR drops
2. Completed `collect_tpm_trans` task
3. Renamed a few task as they can be reused for TPM mode
> [spi_device/dv] Update monitor for TPM mode

- hw/dv/sv/i2c_agent/i2c_if.sv
- hw/ip/i2c/doc/_index.md
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/rtl/i2c_fsm.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_host_tx_rx_vseq.sv
- sw/device/tests/sim_dv/i2c_host_tx_rx_test.c
> [i2c] flop i2c scl and sda outputs

- hw/ip/i2c/rtl/i2c_fsm.sv
- addressess https://github.com/lowRISC/opentitan/issues/14961
> [i2c] Remove scl glitch on transaction start

- azure-pipelines.yml
> [lint] Make the flake8 check mandatory on CI

- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_connect_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_disable_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_filesystem_support_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_info_part_access_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otp_reset_vseq.sv
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson
DV clean up for regression failtures 9/23
> [flash_ctrl,dv] regression fix

- hw/dv/sv/spi_agent/spi_agent_pkg.sv
- hw/dv/sv/spi_agent/spi_monitor.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
1. Added checking to compare TPM items for CRB mode
2. Minor updates to fix some issues on spi_monitor
Next PR will add checking for TPM Fifo mode
> [spi_device/dv] Update scb for TPM

- hw/ip/prim/lint/prim_rst_sync.waiver
- hw/ip/prim/prim.core
- hw/ip/prim/prim_rst_sync.core
- hw/ip/prim/rtl/prim_rst_sync.sv
This commit adds a reset synchronizer for async resets.
> feat(prim): prim_rst_sync

- .github/CODEOWNERS
* added @drewmacrae to CI to help monitor flows related to azure-pipelines.yml and CI scripting
> [CODEOWNERS] Stop reviewing Bazel BUILD files directly

- hw/dv/sv/cip_lib/cip_base_env_cfg.sv
- hw/dv/sv/tl_agent/tl_reg_adapter.sv
> [dv/sv] Fix comment typos and improve format

- dependabot.yml
This adds a dependabot config file to trigger automatic updates to Python packages in response to #14941. This fixes #14956.
> [dependabot] add dependabot config file

- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
Reverts #15101 to fix #15148.
The PR #15216 is missing the sign-off.
> Revert "[rv_core_ibex] Add SVA to check PC is not advancing"

- hw/ip/i2c/rtl/i2c_fsm.sv
- instead of looking for start / stop in specific states, jump directly
to AcquireSrP when in target mode.
- stop detection is cleared in AcquireSrP, while start_detection is
only cleared once we cycle through start address decode handling
again.
> [i2c] fix target mode start / stop handling

- hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_filesystem_support_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
- hw/ip/flash_ctrl/dv/tests/flash_ctrl_base_test.sv
Update filesystem support test(#15037)
- Shift focus from 'erase' to 'double write'
- Improve access resolution from 'page' to '8bytes'
> [flash_ctrl,dv] Update filesystem support test

- hw/ip/spi_device/rtl/spi_tpm.sv
_Related Issue: https://github.com/lowRISC/opentitan/issues/15251_
As described in the issue above, the TPM module uploaded a CMDADDR entry even for an invalid locality command. The read command pointing to invalid locality space, TPM HW returns itself with `0xFF`. There's no need for SW to consume the command and process.
If SW wants to receive the command in any case, SW may turn off invalid locality feature and process the command manually.
> fix(spid): To not push cmdaddr for invalidlocality

- hw/ip/spi_device/rtl/spi_tpm.sv
_Related Issue: https://github.com/lowRISC/opentitan/issues/15266_
This PR fixes a bug for unaligned access in TPM read commands.
fifoaddr is latched with the counter being `'h1F`. The counter, however, runs on SPI_CLK, while the latching logic is running on inverted SPI_CLK domain.
As a result, the latching logic captures the fifo address at a cycle earlier with prematured address. So it always assume address[1] as address[0].
This commit fixes the issue by:
1. Convert `sck_fifoaddr_latch` into iSCK domain.
2. To not shift the address one bit more, use `sck_cmdaddr_wdata_q` rather than `sck_cmdaddr_wdata_d`.
> fix(spid): Latch FIFOADDR at correct time

- hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl
- hw/ip/flash_ctrl/rtl/flash_ctrl.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
> [flash_ctrl] Fix assert bit location

- sw/host/opentitantool/src/command/fpga_reset.rs
> [cleanup] Fix merge skew

- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/empty_test.c
> [test] Add rom_e2e_boot_policy_newer

- sw/device/silicon_creator/rom_ext/docs/manifest.md
Thanks for catching this @cdgori!
> [doc] Fix typo in manifest.md

- hw/dv/sv/csrng_agent/csrng_agent_pkg.sv
- hw/dv/sv/csrng_agent/csrng_item.sv
- hw/dv/sv/csrng_agent/csrng_monitor.sv
- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/doc/_index.md
- hw/ip/csrng/dv/cov/csrng_cov_if.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_smoke_vseq.sv
- hw/ip/csrng/rtl/csrng_core.sv
- hw/ip/csrng/rtl/csrng_reg_pkg.sv
- hw/ip/csrng/rtl/csrng_reg_top.sv
- hw/ip/edn/data/edn.hjson
- hw/ip/edn/dv/cov/edn_cov_if.sv
- hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_intr_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv
- hw/ip/edn/rtl/edn_reg_top.sv
- sw/device/lib/crypto/drivers/entropy.c
- sw/device/lib/dif/BUILD
- sw/device/lib/dif/dif_csrng_shared.c
- sw/device/lib/dif/dif_csrng_unittest.cc
- sw/device/lib/dif/dif_edn_unittest.cc
Implemented flags field in command as a MuBi4 in both block-level dv and rtl. @tjaychen indicated he will make the necessary chip-level changes.
> Csrng/edn flags field MuBi4

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
> [top] Update stale comment in testplan

- hw/ip/prim/rtl/prim_lc_sync.sv
- hw/ip/prim/rtl/prim_mubi12_sync.sv
- hw/ip/prim/rtl/prim_mubi16_sync.sv
- hw/ip/prim/rtl/prim_mubi4_sync.sv
- hw/ip/prim/rtl/prim_mubi8_sync.sv
- util/design/data/prim_mubi_sync.sv.tpl
> [prim_mubi] Fix sampling issue in MUBI sync assertions

- doc/security/specs/device_life_cycle/_index.md
> [doc] Correct life cycle documentation inconsistency

- hw/ip/rv_core_ibex/doc/_index.md
- addresses the documentation portion of #15052
> [rv_core_ibex] Documentation fix

- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
> [dv] Add end to end debug test to testplan

- sw/device/examples/sram_program/BUILD
> [bazel] Update success pattern for sram_program_fpga_cw310_test

- hw/ip/pwrmgr/data/pwrmgr.prj.hjson
- hw/ip/pwrmgr/doc/checklist.md
post review actions items(#12075) have been resolved by
#12129
#12758
#12831
#15001
#15025 
#15124 
> [pwrmgr,dv] Sign off V2S

- hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_config_regwen_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv
- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson
Add designated test for 'ro' type regwen register #15340 
> [flash_ctrl,dv] flash_ctrl.ctrl_regwen test

- hw/top_earlgrey/data/chip_conn_testplan.hjson
- hw/top_earlgrey/formal/conn_csvs/clkmgr_powerup.csv
- hw/top_earlgrey/formal/conn_csvs/clkmgr_secure.csv
- hw/top_earlgrey/formal/conn_csvs/rstmgr_resets_o.csv
> [conn/pwrmgr] Update conn tests due to recent change

- util/generate_compilation_db.py
- util/generate_compilation_db_test.py
```
I tried running util/generate_compilation_db.py in a git worktree and
discovered that the "bazel-opentitan" symlink did not exist! It turns
out that "bazel-opentitan" was just a special case and the general rule
is "bazel-${workspace_name}" [0].
This PR removes the hardcoded "bazel-opentitan" and instead builds the
path relative to the source file. It moves some related path
construction into a class and adds tests.
[0]: https://bazel.build/remote/output-directories
```
> [util] Fix compile_commands.json for git worktrees

- hw/dv/sv/dv_utils/dv_test_status.core
- hw/dv/sv/dv_utils/dv_test_status_pkg.sv
- hw/ip/prim/prim_util.core
- hw/ip/prim/rtl/prim_util_pkg.sv
> [dv] Add a global end-of-test signaling for RTL

- hw/ip/otp_ctrl/data/otp_ctrl_img_raw.hjson
> [otp] Remove unneeded flash key seeds in RAW

- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
Updated seq and scb to test it.
> [spi_device/dv] Test upload payload overflow

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/cov/chip_fsm.cfg
> [dv] Exclude PLIC FSM coverage due to a tool issue

- hw/formal/tools/jaspergold/fpv.tcl
This PR adds clk and reset for clkmgr module.
> [fpv] add correct settings for clkmgr

- hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl
- hw/ip/flash_ctrl/rtl/flash_ctrl.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
- hw/ip/rv_dm/rtl/rv_dm.sv
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
- hw/ip/tlul/rtl/tlul_lc_gate.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
> [rv_dm] Stall tlul transactions when issuing ndm reset

- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
When scoreboarding results from the ExtHT agent the scoreboard needs to wait for the ExtHT agent to report back.  Since the agent is slightly delayed by the DUT, this means that the health test scoring must also be delayed.
This commit breaks entropy collection and health test scoring into separate threads so that the health test scoring can be done at the appropriate time.
> [entropy_src/dv] Refactor scoreboarding collect_entropy

- hw/ip/clkmgr/data/clkmgr.prj.hjson
- hw/ip/clkmgr/doc/checklist.md
> [dv/clkmgr] Declare V2S

- hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_err_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv
- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson
Error injection test during rma wipe process (item 6 of #15340).
> [flash_ctrl,dv] rma wipe error injection test

- hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
> [flash_ctrl] Clean-up comments

- hw/ip/otp_ctrl/data/otp_ctrl_img_creator_sw_cfg.hjson
- sw/device/silicon_creator/rom/data/rom_manual_testplan.hjson
- sw/device/silicon_creator/rom/rom.c
> [sw/silicon_creator, test] Mask MSb of cpuctrl CSR and ddd manual test

- hw/ip/aes/data/aes_sec_cm_testplan.hjson
- hw/ip/aes/data/aes_testplan.hjson
- hw/ip/aes/dv/aes_base_sim_cfg.hjson
- hw/ip/aes/dv/env/aes_env.core
- hw/ip/aes/dv/env/aes_env_cfg.sv
- hw/ip/aes/dv/env/aes_seq_item.sv
- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_readability_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_vseq_list.sv
- hw/ip/aes/dv/err_injection_if/aes_err_injection_bind.sv
AI on https://github.com/lowRISC/opentitan/issues/13579
This updates the se testplan - with correct testcases + adds a new test case to cover the missing states
This will be followed up with another PR that adds missing coverpoints and tests
> Added misssing sec test and udpated sec doc

- sw/device/lib/dif/dif_kmac.c
- sw/device/lib/dif/dif_kmac_unittest.cc
Fix suggestion for the issue #15405.
> [kmac, dif] Fix dif_kmac_config_is_locked

- hw/top_earlgrey/ip/ast/doc/_index.md
Signed-off-by: Ziv Hershman <ziv.hershman@nuvoton.com>
> [ast] update doc

- hw/dv/sv/spi_agent/spi_if.sv
- hw/ip/spi_device/data/spi_device_testplan.hjson
- hw/ip/spi_device/dv/env/seq_lib/spi_device_csb_read_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv
- hw/ip/spi_device/dv/env/spi_device_env.core
- hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
Assign both CSB pins with random values and read the CSB CSRs to check the values
> [spi_device/dv] Add a direct test to read CSB values from CSR

- hw/ip/spi_device/rtl/spi_device.sv
_Related Issue: https://github.com/lowRISC/opentitan/issues/15282_
**This change may affect SW ISR for TPM command handling**
The current interrupt scheme assumes the input is an event (pulse). If the input is a status, it was recommented to add an edge detector to create a pulse.
In certain cases, this may create unwanted (phantom) interrupts or missing interrupts depending on the SW approach to handling the interrupts.
To remove the race condition, HW now connects the status signal to the interrupt in this commit. With the change, now SW is responsible to mask the interrupt while the SW queues the interrupt to event queues.
> refactor(spid)!: Change `tpm_header_not_empty` to level

- hw/top_earlgrey/data/chip_testplan.hjson
> [top-test] xref csrng_lc_hw_debug_en to test point

- sw/device/lib/testing/test_rom/test_rom.c
This updates the test ROM to enable the icache (and other cpuctrl controlled Ibex security features) based on the OTP-stored configuration word.
This fixes #12883.
> [test_rom] enable icache / Ibex security features

- python-requirements.txt
- util/topgen/entropy_buffer_generator.py
- util/topgen/strong_random.py
A class for generating random numbers using an entropy pool. The intention is to use this class to generate random netlist constants and permutations.
This commit contains:
1. strong_random.py containing class strong_random()
-Constructor
-load() function for loading the entropy buffer from an external entropy buffer file.
-getrandbits(k) - a function for fetching k random bits
-randbelow(n) - a function for generating a random integer smaller than n
-shuffle(x) - for generating a random permutation of x
-bookkeeping and debugging functions isempty() and printstatus().
In case that the buffer runs out of entropy the class issues an error and exits.
2. entropy_buffer_generator.py - a script for generating an entropy file using random.py
> [topgen] Strong random class.

- hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cov.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_ack_consistency_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_host_grant_err_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_path_intg_vseq.sv
- hw/ip/flash_ctrl/dv/tb/tb.sv
> [flash_ctrl,dv] std_fault covergroup

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
In OTP_CTRL and FLASH_CTRL, there are `alert_test` failure due to accessing `alert_test` register together.
This is because there are too many `fork join_none` inside the alert_test.
It is not necessary to have these parallel tasks because we cannot write two CSRs together in tlul bus. So I removed the forks and keep the for loop instead.
> [dv/common] Fix common alert_test failure

- hw/ip/spi_device/doc/_index.md
* _Related PR: https://github.com/lowRISC/opentitan/pull/15442_
* _Related Issue: https://github.com/lowRISC/opentitan/issues/15282_
This commit describes how-to process the `tpm_cmdaddr_notempty` interrupt.
> doc(spid): TPM_CMDADDR_NOTEMPTY interrupt

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwrmgr_deep_sleep_all_wake_ups_vseq.sv
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_wake_ups.c
- sw/device/tests/sim_dv/pwrmgr_random_sleep_all_wake_ups.c
- sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c
> [dv,chip] Add chip_sw_random_sleep_all_wake_ups

- hw/ip/spi_device/dv/spi_device_cov_excl.el
- hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
> [spi_device/dv] Exclude mbyte related FSM coverage

- quality/BUILD.bazel
- sw/host/cryptotest/BUILD
> [quality] Add a rust formatting check

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/dv_utils/dv_macros.svh
- hw/ip/rstmgr/dv/rstmgr_cnsty_chk/tb.sv
> [dv] Use positive check in DV_CHECK* macros

- hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_all_vseq.sv
Exit loop without finishing reading all the requests and rely on interrupt to fire again.
> [spi_device/dv] Update seq to utilize tpm level interrupt

- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
- Tests the rom logic for rma bootstrap.
- Test contains two iterations, one positive test and one negative test.
> [top] Add testplan item for RMA bootstrap

- hw/ip/entropy_src/rtl/entropy_src_core.sv
This commit reverts the window_cntr_clr behavior to the original design
where this counter is cleared on disable.   When health_test_clr was
changed to a pulse emitted on enable, this counter was left uncleared
after disable.
This has been observed to cause spurious `window_wrap_pulse`'s when reconfiguring the module, particularly if the window_size is shrunk while reconfiguring the DUT.
> [entropy_src/rtl] Clear window_cntr on disable

- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
- sw/host/tests/rom/e2e_bootstrap_entry/src/main.rs
Add test `e2e_bootstrap_watchdog_disable`
> [Rom e2e] bootstrap watchdog disable

- hw/ip/edn/rtl/edn_core.sv
The EDN module does not delay commands when the CSRNG bus interface ready signal is de-asserted. This is a handshake violation. An output FIFO has been added to make all modes and variations work.
> [edn/rtl] fix to handle ready de-asserted

- hw/ip/spi_device/data/spi_device.hjson
- hw/ip/spi_device/dv/env/seq_lib/spi_device_common_vseq.sv
Removed some unnecessary exclusions
> [spi_device/dv] Update CSR exclusions

- hw/formal/tools/jaspergold/fpv.tcl
This PR fixes flash_ctrl sec_cm name
> [fpv/flash_ctrl] Fix flash_ctrl_sec_cm name

- sw/device/silicon_creator/rom/e2e/BUILD
> [test] Add rom_e2e_sigverify_mod_exp

- rules/manifest.bzl
- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_owner/bare_metal/BUILD
> [test] Add rom_e2e_boot_policy_bad_manifest

- hw/dv/sv/csrng_agent/csrng_agent.sv
- hw/dv/sv/csrng_agent/csrng_agent_cfg.sv
- hw/dv/sv/csrng_agent/csrng_monitor.sv
- hw/ip/edn/dv/tests/edn_base_test.sv
Goes along with hw fix in PR#15478
> [edn/dv] Randomly deassert cmd_ready

- hw/dv/sv/spi_agent/seq_lib/spi_host_seq.sv
- hw/ip/spi_device/data/spi_device_testplan.hjson
- hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_stress_all_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_txrx_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv
- hw/ip/spi_device/dv/env/spi_device_env.core
- hw/ip/spi_device/dv/env/spi_device_env_cfg.sv
- hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
> [spi_device/dv] Add stress_all test

- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/hang_test.c
> [test] Add rom_e2e_shutdown_watchdog

- hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/env/spi_device_env_cfg.sv
> [spi_device/dv] Change to SW only update addr_4b after reset

- hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
- addresses #15632
- increase the burstiness by 2x. This should be cleaned up to be more parameterizable in the future.
> [flash_ctrl] Increase flash rma program burst

- hw/ip/spi_device/data/spi_device_testplan.hjson
- hw/ip/spi_device/dv/env/seq_lib/spi_device_mem_parity_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv
- hw/ip/spi_device/dv/env/spi_device_env.core
- hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
> [spi_device/dv] Add a test to verify memory parity error

- sw/device/tests/sim_dv/clkmgr_escalation_reset_test.c
- Previously, the test would inject a fatal alert and wait
for the alert to happen. However, the injected alert
would cause an escalation and as a result accesses to
the sram and flash would begin to error.
- The processor would create these errors because it used a
busy loop to wait out the expected time for escalation to
trigger.
- In this test, drop the busy loop altogether since the watchdog
already serves the same function.
- Also disable the classA interrupt after seeing it for the first time,
since the fatal alert effectively causes an interrupt storm that
triggers again and again.
fixes #15533
> [top/dv] Slightly restructure clkmgr_escalate_reset_test

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv
Resume prim intg err test and check fatal_prim_flash_alert
> [flash_ctrl,dv] update coverage for prim reg

- hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
> [spi_device/dv] Fix a few xcelium compile errors

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_base_vseq.sv
Hi,
This PR is making some small updates to flash_ctrl_rand_ops_base_vseq.
> Small updates to flash_ctrl_rand_ops_base_vseq

- rules/scripts/bitstreams_workspace.py
Requesting the list of all bitstreams in the bitstream cache can cause GCP to paginate the response. This has become a problem as our bitstream cache has grown. In particular, commits with hashes that were alphabetically later were being missed on cache refreshes. This PR updates the cache to continue making requests to the GCP bucket until the entire list of bitstreams is fetched.
Thanks @dmcardle for helping with the debugging!
> [bitstream cache] Handle pagination when querying for all bitstreams

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_data_integrity_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c
> [dv,top-level] Add data_integrity_escalation_reset test

- rules/fusesoc.bzl
This is effectively a duplicate to #15450 but the args are handled as requested.
I couldn't come up with a particularly elegant way to specify the "--name=value" style args that verilator wants and I think we lose most of the benefits as written here, but it's more concise, so I'm comfortable going in this particular direction
WDYT?
> Bazel fusesoc invocation with ctx.actions.args

- hw/dv/sv/dv_base_reg/dv_base_reg.core
- hw/dv/sv/dv_base_reg/dv_base_reg.sv
- hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
- hw/dv/sv/dv_base_reg/dv_base_reg_pkg.sv
- hw/dv/sv/dv_base_reg/dv_base_shadowed_field_cov.sv
This PR collects the following coverage for shadow register's each field: 
1). update error
2). storage error
Fix issue #7845 
> [dv/shadow_reg] Add shadow reg fcov

- hw/dv/sv/spi_agent/spi_flash_cmd_info.sv
- hw/ip/spi_device/data/spi_device_testplan.hjson
- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_addr_payload_swap_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/env/spi_device_env_cov.sv
1. fixed wrong variable type int -> bit
2. fixed dummy_cycles cross, as write doesn't allow dummy_cycles
3. reduced auto_bin to reduce cross coverage
4. adjusted randomization to increase chance for swap data/addr
> [spi_device/dv] Fix some coverage issues

- hw/ip/spi_device/data/spi_device_testplan.hjson
- hw/ip/spi_device/dv/env/seq_lib/spi_device_ram_cfg_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv
- hw/ip/spi_device/dv/env/spi_device_env.core
- hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
> [spi_device/dv] Add connectivity test for ram_cfg

- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
@tjaychen is this something that we can test on the fpga (maybe with hyperdebug)?
> [test] Add rom_e2e_weak_straps to the rom e2e testplan

- hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv
- hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
See https://github.com/lowRISC/opentitan/issues/15280#issuecomment-1289816964 for context.
> [alert_handler] Increase chance that pinged alert ID is valid

- rules/opentitan_test.bzl
> [bazel] Allow opentitan_functest to accept custom bitstreams

- sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c
This was a suggested review change that didn't make it in a prior PR.
> [dv,top-level] Make minor change in data_integrity test

- hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
- util/design/mubi/prim_mubi.py
As discussed in our last meeting.
> [mubi/lc] Add comment regarding mubi encoding changes

- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
This commit updates roms_e2e_testplan.hjson to reflect the latest changes in the rom e2e test issues.
I've also removed the checklist from all rom e2e test issues for the sake of conciseness. For example: #14271. 
> [test] Update rom_e2e_testplan.hjson

- hw/rdc/tools/meridianrdc/run-rdc.tcl
- hw/top_earlgrey/rdc/chip_earlgrey_asic_scenario.tcl
- hw/top_earlgrey/rdc/rdc_waivers.spi_device.tcl
>  [rdc] SPI_DEVICE TPM CSb reset scenario

- hw/top_earlgrey/dv/env/chip_common_pkg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_exit_test_unlocked_bootstrap_vseq.sv
- sw/device/lib/testing/test_rom/test_rom.c
- sw/device/tests/sim_dv/exit_test_unlocked_bootstrap.c
> [top/dv] Address review comments

- hw/top_earlgrey/data/chip_testplan.hjson
> [test] List tests for chip_lc_test_locked testpoint

- hw/top_earlgrey/ip/xbar_main/rtl/autogen/xbar_main.sv
- util/tlgen/xbar.rtl.sv.tpl
Fix issue identified in #14204
> [top] Reduce async fifo depth

- bazelisk.sh
> [bazel] Use bazel if its already present

- hw/dv/sv/spi_agent/seq_lib/spi_host_dummy_seq.sv
- hw/dv/sv/spi_agent/spi_host_driver.sv
Updated the sequence due to #15721
> [spi_device/dv] Constrain dummy transaction due to a design issue

- hw/top_earlgrey/data/chip_testplan.hjson
- Enhance testplan descriptions due to reset domain change
- Move P3 tests to V3.
> [top/dv] Testplan updates

- ci/scripts/test-airgapped-build.sh
> [ci] rollback airgapped build test script changes in #15775

- hw/top_earlgrey/dv/env/chip_env_cfg.sv
Aligned with design update #15766
Addressed this regression failure #14204
> [top, dv] Update max TL req to 3

- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_cipher_fi_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_control_fi_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_ctr_fi_vseq.sv
This PR contains two commits to fix issues in the FI tests and in particular the aes_control_fi test.
> [aes, dv] Fix aes_control_fi tests

- hw/ip/keymgr/dv/env/seq_lib/keymgr_common_vseq.sv
1. Excluded checking working_state in the csr_rw thread in tl_err or shadow_reg tests, because it's hard to update predicted value due to a timing issue.
2. Disabled some SVAs for sec_cm test
3. small consolidation to remove some duplicated code
> [keymgr/dv] Update common vseq

- third_party/rust/deps.bzl
- util/prep-bazel-airgapped-build.sh
This broke our airgapped environment.
> [bazel] rollback #15775 rust toolchain update

- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
If Windowed, Continuous and/or External HT's simultaneously fail in the same sample the DUT's alert count only registers one failure, for the sample, which in generally fine.  However the previous approach at counting these coincident failures overestimated the overcounting factor and was unable to predict certain alerts.
This commit corrects the accounting for alert counts when simultaneous alerts occur.
> [entropy_src/dv] Properly count coincident HT failures

- hw/ip/edn/dv/env/edn_scoreboard.sv
This PR fixes nightly regression failure in intr_pin comparison. Scb compares intr pin value with intr_state read out value at the read_data_phase time, but intr_pin might change at that time.
So a better solution is to store the intr_pin at read_addr_phase, and compare the read results later in read_data_phase time.
> [dv/edn] Fix nightly regression failure

- hw/dv/sv/i2c_agent/i2c_if.sv
- hw/ip/i2c/dv/i2c_sim.core
- hw/ip/i2c/dv/tb/i2c_port_conv.sv
- hw/ip/i2c/dv/tb/tb.sv
- hw/top_earlgrey/dv/env/chip_if.sv
> [i2c/dv] Correctly model i2c connections

- hw/ip/entropy_src/rtl/entropy_src_core.sv
This commit delays the clear of the window_cntr after disable until the last data admitted has cleared the health checks
> [entropy_src/rtl] Window_cntr disable timing

- hw/ip/tlul/rtl/tlul_adapter_reg.sv
Follow up for https://github.com/lowRISC/opentitan/pull/15737#pullrequestreview-1160824397.
> [tlul] Add comment regarding refactor to tlul_adapter_reg

- hw/top_earlgrey/data/chip_conn_testplan.hjson
- hw/top_earlgrey/formal/chip_conn_cfg.hjson
- hw/top_earlgrey/formal/conn_csvs/rstmgr_crashdump.csv
> [conn] Add conn test for crashdump signals

- hw/ip/edn/rtl/edn_ack_sm.sv
- hw/ip/edn/rtl/edn_core.sv
- helps mititage issue raised in https://github.com/lowRISC/opentitan/issues/15349
- Currently, if edn disable happens during the acknowledge state, the acknowledge is
still sent, and one cycle later, the entropy is 0'd.  Normally, this is not an issue,
but a large number of blocks communicate with edn through an async interface
(prim_edn_req).  Prim_edn_req currently assumes that the data remains stable with the
ack until a new request is made, the disable function makes this untrue.
- This commit tweaks the fsm slightly to not ack when enable goes low. We cycle back to
a Disabled state that waits for edn to be enabled again.  This function relies on
`edn_i.req` being fed directly from external consumers and not latched/cleared inside
edn.
> [edn] Address possible 0-entropy on disable

- util/reggen/gen_cfg_html.py
This commit adds an interrupt type column to the interrupt section in the IP technical specification.
> [reggen] Interrupt Type to CFG doc

- hw/dv/tools/dvsim/sim.mk
- third_party/rust/deps.bzl
- util/prep-bazel-airgapped-build.sh
This also rolls-forward #15831.
> [dvsim] fix bindgen error in nightlies

- hw/ip/edn/rtl/edn_ack_sm.sv
- hw/ip/edn/rtl/edn_core.sv
- Address issues identified in https://github.com/lowRISC/opentitan/pull/15695
- Make fsm and counter errors unconditional alerts.
- Add local escalation to the ack_fsm, the effect is to
stop responding to edn requests.
- Add enable enums to make edn_enable_fo a bit more
maintainable in the long term.
> [edn] Minor fixes and refactoring

- sw/device/lib/testing/flash_ctrl_testutils.c
- sw/device/lib/testing/flash_ctrl_testutils.h
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c
- sw/device/tests/sim_dv/sysrst_ctrl_outputs_test.c
> Fix chip sw sysrst ctrl ec rst l

- third_party/rust/repos.bzl
> [rust] Update serde-annotate

- hw/ip/edn/rtl/edn_core.sv
This reverts commit 3ad51c3b4fa9a10c865d9e9ea0b6b87266ebd392.
> Revert "[edn] Tweak fifo clear logic"

- hw/top_earlgrey/rdc/rdc_waivers.spi_device.tcl
The current env. setup in RDC does not describe the relationship between CSb and SCK or the current description (below) is not well defined:
```
\# chip_earlgrey_asic.env:26
\# Define SPI_DEVICE CSB as reset
create_reset -interval 10 -high -waveform SPI_DEV_CLK top_earlgrey.u_spi_device.rst_csb_buf
```
Due to the issue, RDC reports many (27) errors starting from io_mode, or bitcnt to a few SPI_DEV*_CLK flops. They can be waived as CSb will be de-asserted (0 -> 1) avoiding any edges of SCK.
> [rdc/spid] Waive CSb to any flops @ SPI_DEV*CLK

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/sysrst_ctrl_ulp_z3_wakeup_test.c
This is a simple test case for ulp wakeup. The test passes on dvsim, and I could use some suggestions to improve it.
> [chip_sw, sysrst_ctrl] Test ulp wakeup of sysrst_ctrl

- hw/top_earlgrey/data/chip_testplan.hjson
> [top] Add test to to testpoint

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
- clarifies some issues found in #15862, #15858
- This better describes what the check does and makes it slightly more useful.
> [keymgr] Clarify the sideload_sel error function

- third_party/rust/repos.bzl
> [rust] Update to serde-annotate v0.0.5

- hw/dv/sv/spi_agent/spi_host_driver.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_spi_device_tpm_vseq.sv
> [top/dv] Add missing queue constraint

- hw/top_earlgrey/ip/ast/doc/ast_regs.html
- hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv
The code is updated to include:
1. Comments updates.
2. Add plusargs.
See issue: [dv/ast] Speed up clocks enabled #15599
@sha-ron  @arnonsha 
> [ast] Add 'plusargs' for regulators power-up acceleration

- third_party/rust/repos.bzl
> [bazel] rollback 15905 to triage Bazel airgapped issues

- hw/dv/sv/i2c_agent/i2c_driver.sv
- hw/dv/sv/i2c_agent/i2c_if.sv
- hw/dv/sv/i2c_agent/i2c_monitor.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_base_seq.sv
- hw/ip/i2c/dv/env/i2c_env_cfg.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_fmt_empty_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_overflow_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_reset_rx_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_watermark_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_stretch_timeout_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_rx_tx_vseq.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
Reverts lowRISC/opentitan#15867
> Revert "[i2c,dv] Refactoring host mode tb"

- hw/ip/flash_ctrl/data/flash_ctrl.prj.hjson
- hw/ip/flash_ctrl/doc/checklist.md
All v2s review items are address (#15340)
See #15340 for details.
> [flash_ctrl,dv] Sign off V2S

- sw/device/silicon_creator/rom/e2e/BUILD
> [test] Complete rom_e2e_boot_policy_valid

- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/empty_test.c
> [test] Complete rom_e2e_sigverify_mod_exp

- sw/device/silicon_creator/rom/e2e/BUILD
> [test] Complete rom_e2e_boot_policy_bad_manifest

- sw/device/tests/rstmgr_cpu_info_test.c
Due to #15219, it appears the current PC information on double faults is now changed. Update to reflect the latest.
Also change illegal read to an illegal write at address 0, since this reduces the number of "glue" instructions surrounding the one that actually creates the illegal access.
> [top] Update cpu_info test

- doc/getting_started/setup_fpga.md
I had an issue where OpenOCD complained it was unable to open the JTAG adapter's USB device. This happened while I was working on #15853, but I think it was unrelated. I also happened to have disconnected and reconnected the JTAG adapter before seeing the error, so I assume some policy rolled out to my workstation and I only triggered it when I reconnected the adapter.
@arunthomas Hopefully, you were running into the same issue and these steps will fix it.
> [doc] Add udev instructions for ARM-USB-TINY-H JTAG adapter

- hw/ip/edn/rtl/edn.sv
Fix #16000.
A seperate PR will add assertions in prim_edn_req.
> [dv/edn] Fix assertion error

- hw/top_earlgrey/data/chip_testplan.hjson
Also remove testpoints that are no longer required.
> [top/dv] Several x-ref updates to the testplan

- sw/device/tests/sim_dv/all_escalation_resets_test.c
> [top/dv] Also exclude sram fatal from isr handling

- sw/device/silicon_creator/rom/e2e/BUILD
> [test] Complete rom_e2e_shutdown_watchdog

- sw/device/silicon_creator/rom/e2e/BUILD
> [test] Complete rom_e2e_boot_policy_rollback

- third_party/rust/repos.bzl
> [rust] Update serde-annotate to v0.0.6

- hw/ip/pwrmgr/dv/env/pwrmgr_scoreboard.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_invalid_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_repeat_wakeup_reset_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_reset_invalid_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv
- hw/ip/pwrmgr/dv/sva/pwrmgr_bind.sv
- hw/ip/pwrmgr/rtl/pwrmgr.sv
- hw/ip/pwrmgr/rtl/pwrmgr_cdc.sv
- hw/ip/pwrmgr/rtl/pwrmgr_fsm.sv
- hw/ip/pwrmgr/rtl/pwrmgr_pkg.sv
- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- fix cdc crossing issue between rv_core_ibex and pwrmgr
- fix potentialy cdc crossign issue between rom_ctrl and
pwrmgr
- fixes https://github.com/lowRISC/opentitan/issues/15960
> [pwrmgr] Fix cdc issues

- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
> [rom_e2e,dv] update verification stage for ROM E2E tests

- hw/ip/edn/rtl/edn_core.sv
This reverts commit 8aff88ccc12afd90179361987c611f07409e8410.
> Revert "Revert "[edn] Tweak fifo clear logic""

- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
> [rv_core_ibex] Add assertions for ibex fetch enable

- hw/ip/rstmgr/dv/env/rstmgr_env_pkg.sv
> [dv/rstmgr] Update reset consistency checker instances

- hw/ip/prim/rtl/prim_sync_reqack.sv
- The check flag always disables upon reset.  When the first rising edge of the request is seen, it is then activated again until the next reset.  This ensures we check only during active periods and not accidentally across a reset, which is what caused the failure previously.
> [prim] Add an internal check flag

- hw/dv/tools/dvsim/common_sim_cfg.hjson
> [tools/dvsim] Remove old cdc plusargs from common_sim_cfg

- util/reggen/BUILD
Signed-off-by: Cindy Liu <hcindyl@google.com>
> [bazel, reggen] Fix gen_rtl python library

- hw/ip/otp_ctrl/data/BUILD
> [otp/ast] Enable AST initialization in Bazel-generated OTP images

- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/tests/crypto/BUILD
> [bazel] Mark tests with known and filed issues as broken

- sw/device/silicon_creator/rom/e2e/BUILD
Fix https://github.com/lowRISC/opentitan/issues/14477
Signed-off-by: Douglas Reis <doreis@lowrisc.org>
> [dv, e2e] Add the test `sigverify_always`

- hw/dv/sv/i2c_agent/i2c_agent.core
- hw/dv/sv/i2c_agent/i2c_agent_cfg.sv
- hw/dv/sv/i2c_agent/i2c_driver.sv
- hw/dv/sv/i2c_agent/i2c_if.sv
- hw/dv/sv/i2c_agent/i2c_item.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_seq_list.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_target_base_seq.sv
- hw/ip/i2c/dv/env/i2c_env.core
- hw/ip/i2c/dv/env/i2c_env.sv
- hw/ip/i2c/dv/env/i2c_env_pkg.sv
- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/i2c/dv/env/i2c_seq_cfg.sv
- hw/ip/i2c/dv/env/i2c_virtual_sequencer.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_smoke_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
- hw/ip/i2c/dv/tests/i2c_base_test.sv
Target mode smoke test write path.
- Support multiple transactions and random size
- acq fifo data checker
> [i2c,dv] target mode write path tb

- sw/device/sca/ecc384_serial.c
- sw/device/sca/ecc_serial.c
EDN in auto mode is required for long running captures.
> [sca] ECC switch to entropy auto mode

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_sideload_kmac_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/lib/testing/keymgr_testutils.c
- sw/device/tests/sim_dv/keymgr_key_derivation_test.c
- sw/device/tests/sim_dv/keymgr_sideload_kmac_test.c
> [chip-test, kmac] Keymgr sideload kmac

- hw/ip/aes/data/aes.prj.hjson
- hw/ip/aes/doc/checklist.md
This resolves lowRISC/OpenTitan#13579.
Before we can merge this, #16001 has to go in which will resolve the remaining block-level issue.
> [aes] V2S sign-off

- hw/ip/clkmgr/data/clkmgr_sec_cm_testplan.hjson
> [dv/clklmgr] Comment about the sec_cm testplan location

- hw/ip/keymgr/dv/env/seq_lib/keymgr_common_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_custom_cm_vseq.sv
1. Addressed a TODO
2. Added coverage sampling
> [keymgr/dv] Update sec_cm test

- hw/ip/entropy_src/rtl/entropy_src_core.sv
In `es_bypass_mode` FW_OV data goes to directly to the bypass FIFO, not to the precon fifo.  This commit updates the fw_ov_wr_fifo_full register to reflect that.
In a related vein, the es_bypass_mode signal now updates immediately when even fips_enable, es_route or es_type are updated so that changes in the states of this signal can be tracked in FW.
> [entropy_src/rtl] Proper checking of fw_ov_wr_fifo_full

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_tap_straps_vseq.sv
This addresses [these](https://github.com/lowRISC/opentitan/pull/16053#pullrequestreview-1171260122) review comments to cleanup DV testbench / a test.
> [dv] implement review feedback from #16053

- hw/top_earlgrey/data/chip_testplan.hjson
Update testplan to reflect plan in #14193
> [testplan] Describe chip_sw_entropy_src_cs_aes_halt

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/data/keymgr_sec_cm_testplan.hjson
> [keymgr] Countermeasure doc update

- hw/dv/sv/csrng_agent/csrng_monitor.sv
This PR moves the timing to increment counters.
Currently the counter will increment when we see the gen request. With this change, will only increment the count if the `ack` is sent. This will eliminate the case where reset is issued.
> [dv/csrng_agent] Only increment the count if the ack is sent

- hw/top_earlgrey/dv/env/chip_if.sv
- sw/device/tests/sim_dv/spi_device_tpm_tx_rx_test.c
> [top] Address regression failure

- hw/ip/aes/rtl/aes_cipher_core.sv
> [aes] Add coverage instrumentation pragmas

- hw/ip/csrng/doc/dv/index.md
- hw/ip/csrng/dv/cov/csrng_cov_if.sv
- hw/ip/csrng/dv/env/csrng_path_if.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
Pretty minor stuff, just wanted to open up a PR for these so that I won't end up opening a huge PR in the future :)
Let me know if any change looks off, they're merely suggestions of enhancement.
> [csrng,dv] Minor enhancements in CSRNG DV environment

- sw/device/silicon_creator/rom/e2e/BUILD
> [test] Add rom_e2e_sigverify_key_validity

- hw/top_earlgrey/rdc/chip_earlgrey_asic.env
- hw/top_earlgrey/rdc/chip_earlgrey_asic_scenario.tcl
- hw/top_earlgrey/rdc/rdc_waivers.spi_device.tcl
- hw/top_earlgrey/rdc/rdc_waivers.tcl
Revise aon Power OK reset scenario.
- vcaon_pok reset signal from the regulator
- toggle vcmain_pok together (as expected scenario)
Now 2003 errors and 307 warnings.
> [rdc/scn] Revise reset scenario

- rules/const.bzl
- rules/manifest.bzl
- sw/device/silicon_creator/rom/e2e/BUILD
~~**Note: This PR depends on #16031. Only need to review the last commit.**~~ That PR has been merged. Please review all commits in this PR.
Closes #14482
> [test] Implement rom_e2e_sigverify_usage_constraints test

- hw/top_earlgrey/data/chip_testplan.hjson
> [test] Fix an unmapped test in the testplan

- hw/ip/prim/rtl/prim_sync_reqack.sv
- the current assertions do not work well when clocks are also killed around the time of reset. It makes the detection of rose / fell unreliable and triggers false positives.
- instead switch to using async flags (not very elegant) that should in theory serve very similar purposes.
> [prim] Adjust reset assertion

- hw/ip/keymgr/rtl/keymgr.sv
> [keymgr] Make debug csr more accurate

- hw/ip/hmac/rtl/hmac.sv
> [hmac] Make alert fatal

- hw/top_earlgrey/data/chip_testplan.hjson
> [chip dv] Update chip_sw_entropy_src_cs_aes_halt

- hw/ip/prim/rtl/prim_sync_reqack_data.sv
This is similar to the flag that was added to the prim_sync_reqack module itself.
Fixes #16115.
> [prim_sync_reqack_data] Add check flag to better capture async resets

- hw/ip/keymgr/data/keymgr_sec_cm_testplan.hjson
> [keymgr/dv] Fix a test-testpoint mapping

- hw/ip/keymgr/data/keymgr_sec_cm_testplan.hjson
Updated as discussed in v2s review meeting and partially addressed #16183
> [keymgr/dv] Update sec_cm testplan

- hw/ip/edn/dv/edn_sim_cfg.hjson
- hw/ip/edn/dv/env/edn_env.core
- hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_vseq_list.sv
- hw/ip/edn/dv/tests/edn_disable_auto_req_mode_test.sv
- hw/ip/edn/dv/tests/edn_test.core
- hw/ip/edn/dv/tests/edn_test_pkg.sv
This PR tries to disable EDN during auto_req_mode.
> [dv/edn] Disable EDN during auto_req_mode

- sw/device/tests/entropy_src_kat_test.c
The entropy_src KAT test's use of non-blocking data reads is important. However it leaves the test vulnerable to false failures due to timing
delays within the IP.   This commit issues a number of retry attempts
whenever the ENTROPY_DATA register is read.
> [entropy_src,sw] Make KAT test more robust

- hw/dv/sv/i2c_agent/i2c_agent_cfg.sv
- hw/dv/sv/i2c_agent/i2c_agent_pkg.sv
- hw/dv/sv/i2c_agent/i2c_driver.sv
- hw/dv/sv/i2c_agent/i2c_if.sv
- hw/dv/sv/i2c_agent/i2c_item.sv
- hw/dv/sv/i2c_agent/i2c_monitor.sv
- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env.sv
- hw/ip/i2c/dv/env/i2c_env_cfg.sv
- hw/ip/i2c/dv/env/i2c_env_pkg.sv
- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/i2c/dv/env/i2c_seq_cfg.sv
- hw/ip/i2c/dv/env/i2c_virtual_sequencer.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_smoke_vseq.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
Target smoke test
This PR is dependent on #16108 and vice versa.
> [i2c,dv] target smoke test

- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
- DUT Enable only occurs after other threads have started (needed for FSM coverage closure)
- Modified delay constraints to have reduced probability of long response delays (e.g., to interrupt events etc).
> [entropy_src/dv] Minor RNG Seq Updates

- hw/ip/keymgr/dv/cov/keymgr_cov_excl.el
- hw/ip/keymgr/dv/keymgr_sim_cfg.hjson
These transitions are non-idle -> error
> [keymgr/dv] Add FSM exclusion

- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_aborted_low_power_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_common_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_disable_rom_integrity_check_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_esc_clk_rst_malfunc_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_glitch_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_global_esc_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_invalid_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_wakeup_race_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_reset_invalid_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_reset_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_sec_cm_ctrl_config_regwen_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_sw_reset_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_vseq.sv
- hw/ip/pwrmgr/dv/pwrmgr_sim_cfg.hjson
Change some delays in order for CDC instrumentation to work. Fixed some corner cases in tests that were failing. Many changes for verible-format.
> [dv/pwrmgr] Enable CDC instrumentation and fix tests

- ci/.bazelrc
I'm curious what folks will think about this. I think these changes will improve the quality of the logs, but I recognize that it's more opinion that fact :)
(More details in commit messages.)
> [ci/.bazelrc] Add color and reduce noisiness of Bazel output

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_data_en_state.sv
> [keymgr] Clarify and update the key redundancy controls

- hw/dv/sv/cip_lib/cip_macros.svh
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
- hw/ip/pwrmgr/dv/tb.sv
This has two separate commits.
> [dv/pwrmgr] Fix alert_if connection and objection handling

- ci/scripts/run-fpga-cw310-tests.sh
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/rom_ext_upgrade_test.c
This test will pass, running through the procedure described in the testplan.
Fixes: #14488
> [e2e test] implement rom_ext_upgrade

- hw/top_earlgrey/data/chip_testplan.hjson
> [top] Minor update to testplan

- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/epmp_init_test.c
> [test] Implement rom_e2e_epmp_init

- sw/device/silicon_creator/rom/e2e/BUILD
> [test] Implement rom_e2e_shutdown_exception_asm

- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/rom_e2e_ret_ram_init_test.c
> [test] Implement rom_e2e_ret_ram_init_test

- hw/ip/edn/dv/tests/edn_genbits_test.sv
This PR increases genbits max size to increase toggle and functional coverage.
> [dv/edn] Increase edn genbit max size

- rules/opentitan_gdb_test.bzl
- rules/scripts/gdb_test_coordinator.py
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/rom.c
~~This is intentionally based on an old commit due to #16067.
**Ignore all commits until `[test] Implement rom_e2e_debug`.**~~
TODO:
@alphan Can you give me pointers on the TODOs above? I can probably find a GPR listing, but I'm not sure how to figure out which CSRs we expect to be readable/writeable.
Fixes #14484
> [test] Implement rom_e2e_debug 

- sw/host/opentitanlib/src/otp/alert_handler.rs
Register values for enabled alert classes were being set incorrectly due to the order of a fallthrough switch case in ROM being read in reverse.
> [opentitantool] Fix CRC computation for alert_handler

- hw/ip/pwrmgr/rtl/pwrmgr_slow_fsm.sv
- Handle the case where a power glitch can cause the main power state
to change asynchronously.
> [pwrmgr] rdc fixes

- hw/ip/keymgr/data/keymgr.prj.hjson
- hw/ip/keymgr/doc/checklist.md
All review AIs are addressed #16183.
Coverage and passing rate are above 90%.
> [keymgr] V2S sign-off

- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/rom_e2e_ret_ram_keep_test.c
> [test] Implement rom_e2e_ret_ram_keep test

- hw/ip/usbdev/rtl/usbdev.sv
Fixes https://github.com/lowRISC/opentitan/issues/16159.
> [usbdev] Make integ alert fatal

- hw/ip/entropy_src/data/entropy_src.prj.hjson
- hw/ip/entropy_src/doc/checklist.md
> [entropy_src/doc] Checklist updates in preparation for V2 review

- hw/ip/csrng/data/csrng_testplan.hjson
I have added some details to the test plan of CSRNG. I intentionally did not look at the current tests and wrote the test plan purely based off of reading the CSRNG documentation and the NIST specification.
There might be some things that I misunderstood, so any comments are welcome. These are some questions I had when I was writing the test plan and could not find in the documentation. I've opened up a separate issue for those questions: https://github.com/lowRISC/opentitan/issues/16203
> [dv,csrng] Add more details to testplan

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/alert_handler_lpg_sleep_mode_pings.c
Initial commit to address the issue #15765
Signed-off-by: Bilgiday Yuce <bilgiday@google.com>
> [alert_handler] Add chip_sw_alert_handler_lpg_sleep_mode_pings

- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv
This is not really the right fix, but extends the previous fix so that the resets are made concurrent (even by routines that call apply_reset and not apply_reset_concurrently).
The right fix probably needs to happen in the dv_base somewhere so that there is a notion of what kind of reset relationship we want.
Leaving that to another day and just get the regressions cleaner for now. This resolves both csr_outstanding and stress_all failures.
> [aon_timer] Workaround for concurrent resets

- hw/ip/rv_core_ibex/dv/sva/rv_core_ibex_sva.core
- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/top_earlgrey/formal/top_earlgrey_fpv_sec_cm_cfgs.hjson
Note this fix is needed in Ibex: https://github.com/lowRISC/ibex/pull/1917 before we can successfully run this in Jasper (without it we get a build error). So that must be merged into Ibex and vendored into OT before we merge this
> Rv core ibex fpv

- rules/const.bzl
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/rom_e2e_shutdown_alert_config_test.c
Adds the rom_e2e_shutdown_alert_config test.
Fixes #14275
> [rom_e2e] Add rom_e2e_shutdown_alert_config

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_host_tx_rx_vseq.sv
- sw/device/tests/sim_dv/i2c_host_tx_rx_test.c
> [top, dv] Update i2c test to support multiple instances

- ci/scripts/run-fpga-cw310-tests.sh
- sw/host/opentitanlib/src/transport/cw310/usb.rs
> [ci] set_pll at start of FPGA tests

- hw/ip/rstmgr/dv/sva/rstmgr_bind.sv
As discussed in the V2S meeting.
> [rstmgr/dv] Correct tlul_device bind reset connection

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_random_power_glitch_vseq.sv
- sw/device/tests/sim_dv/pwrmgr_random_sleep_power_glitch_reset_test.c
> [DV] Fix timout issue in #14164

- sw/device/tests/alert_handler_lpg_sleep_mode_pings.c
Fixes #16413
- Fixes the C code to properly clear the cause registers after the wakeup in phase 2. This enables proper checking of fresh ping-fail alerts.
- For phase 2, reduces the ping_timeout_cyc config from 2 to 1. As a result, more ping requests will result in ping-fail alerts.
- Tested on FPGA and in DVsim (reseed:10).
Signed-off-by: Bilgiday Yuce <bilgiday@google.com>
> [chip-test] Fix chip_sw_alert_handler_sleep_mode_pings

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
* Move some test points to V3 based to reflect prioritization discussions. 
* Update test target references to reflect a couple of test renames.
> [top-test] Test plan updates

- hw/ip/csrng/dv/csrng_sim_cfg.hjson
> [csrng] Increase the number of csrng_err test executions

- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
> [top, dv] Fix SVA FpvSecCmIbexLoadRespIntgErrCheck_A

- hw/ip/csrng/dv/cov/csrng_cov_if.sv
This commit introduces cp_fifo_err_type and fifo_err_type_cross for checking which SFIFO had an error and what type. Illegal bin in that cross also makes sure that whenever we see a SFIFO error we expect either FIFO_WRITE_ERR FIFO_READ_ERR or FIFO_STATE_ERR.
> [csrng,dv] Extend err_code_cg to check SFIFO err

- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv
Update regulator block interface to match implementation needs.
@arnonsha 
> [ast] Regulator block interface update (implementation)

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_power_idle_load_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/BUILD
- sw/device/tests/chip_power_idle_load.c
Chip level test for scenario chip_sw_power_idle_load.
> [top-test] chip_sw_power_idle_load

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/alert_handler_lpg_sleep_mode_alerts.c
Implements the chip-level test described in the issue #15764.
Signed-off-by: Bilgiday Yuce <bilgiday@google.com>
> [chip-test] Implement chip_sw_alert_handler_sleep_mode_alerts

- hw/ip/csrng/data/csrng_sec_cm_testplan.hjson
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_path_if.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
~~The first commit belongs to #16427.~~
> [csrng, dv] Add verification for AES_CIPHER.CTRL.SPARSE countermeasure

- hw/ip/csrng/data/csrng_sec_cm_testplan.hjson
- hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
- hw/ip/csrng/dv/tb.sv
~~The first commit is from #16447.~~
> [csrng, dv] Add verification for remaining CMs inside embedded AES core

- hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
pre_randomize has to be a function
> [spi_host/dv] Fix a VCS compile error

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
> [test] Correct test reference and enable previously failing Xcelium tests

- rules/opentitan.bzl
This enables running the JTAG SRAM inject and debug ROM E2E tests in DV.
> [bazel] build RAM binary VMEM

- hw/ip/entropy_src/data/entropy_src.prj.hjson
- hw/ip/entropy_src/doc/checklist.md
This resolves https://github.com/lowRISC/opentitan/issues/16330.
> [entropy_src] V2S sign-off

- hw/ip/lc_ctrl/rtl/lc_ctrl.sv
This PR updates sec_cm assertion gated condition according to PR #15962.
> [fpv/sec_cm] Update assertion for sec_cm failure

- hw/ip/pwrmgr/dv/sva/pwrmgr_ast_sva_if.sv
When the power glitch occurs the AST reacts by changes in *clk_val. Previously there was an assertion requiring changes in the pwrmgr *clk_en outputs, which were violated.
Also, the assertions are really edge triggered by changes on por_n_i. The *clk_en to *clk_val handshake are also triggered by edges. The maximum number of cycles to wait for transitions is increased. The macros local to this file are undefined before the end of file.
This fixes one of the failure scenarios in #14164.
> [dv/pwrmgr_ast] Fix pwrmgr_ast SVAs

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_asm_init_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
> [rom_e2e,dv] add `rom_e2e_asm_init` test to DV

- hw/ip/csrng/dv/env/csrng_env_cfg.sv
This commit tunes the err_code distribution for the csrng_err and csrng_intr test to improve functional coverage numbers. This is useful as for many error codes, actually multiple error sources are collected in the same error bit. For example, aes_cipher_sm_err collects errors from 4 distinct countermeasures of which each can be triggered in three different logic rails. Similarly, every FIFO can experience 3 different errors (write, read, state).
> [csrng, dv] Tune err_code distribution for csrng_err test

- hw/ip/rstmgr/data/rstmgr.prj.hjson
- hw/ip/rstmgr/doc/checklist.md
Fixes #16475 (to be merged when all items have been addressed).
> [rstmgr] Update checklist and move to V2S

- sw/device/tests/alert_handler_ping_timeout_test.c
Change class config to defer triggering escalation, and do not trigger NMI during escalation.
Enable interrupts only for class B alerts, since there can be spurious class A alerts as a side effect of the ping failure. Print out the external alerts received at the end, for informational purposes.
Also eliminate the race between WFI and the ISR.
Thanks to @msfschaffner and @cindychip for helping to resolve the issue.
> [tests] Remove race with software for alert ping test

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_power_sleep_load_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/BUILD
- sw/device/tests/chip_power_sleep_load.c
Test for scenario chip_sw_power_sleep_load
> [top-test] chip_sw_power_sleep_load

- hw/ip/rv_core_ibex/data/rv_core_ibex.prj.hjson
- hw/ip/rv_core_ibex/doc/checklist.md
- hw/ip/rv_core_ibex/doc/dv/_index.md
> [doc] Point to Ibex documentation for verification status

- hw/ip/i2c/data/i2c_sec_cm_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env_cfg.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_fmt_empty_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_overflow_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_reset_rx_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_watermark_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_stretch_timeout_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_rx_tx_vseq.sv
- Revert previous refactoring for 'host_send_trans'
- Add 'tl_intg_err' test 
> [i2c,dv] host mode regression fix

- doc/getting_started/setup_fpga.md
Updates after some issues setting up a new FPGA:
- Add a note to the CW310 setup stating that you should run `set-pll`
- Add `test_rom` suffix to test targets
- Include some troubleshooting notes that suggest adding the `--rcfile=` option and pressing `USR_RST`
> [doc] Update FPGA setup docs.

- ci/scripts/run-fpga-cw310-tests.sh
Emit a debug message to help capture more infor for #16543
> [ci] Continue if PLL fails to be set

- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_reset_fmt_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_perf_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_rx_tx_vseq.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
update tlow minimum to meet timing constraint change.
> [dv,i2c] host_perf failure fix

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
> [test] Update rom target name for DV tests

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_core_ibex_lockstep_glitch_vseq.sv
> [dv] Fix typo in ibex port name

- hw/ip/csrng/data/csrng.prj.hjson
- hw/ip/csrng/doc/checklist.md
~There are just very few outstanding PRs that need to pass CI to be merged, we need to re-collect coverage with these changes (currently ongoing), and then we can hopefully hit V2/V2S. For now I make this a draft.~
All things are merged, the next nightly should show the updated coverage results.
> [csrng] V2 and V2S signoff

- hw/ip/rstmgr/dv/rstmgr_cnsty_chk/cov_unr_excl.el
- hw/ip/rstmgr/dv/rstmgr_cnsty_chk/tb.sv
- hw/ip/rstmgr/lint/rstmgr.waiver
- hw/ip/rstmgr/rtl/rstmgr_cnsty_chk.sv
- hw/ip/rstmgr/rtl/rstmgr_leaf_rst.sv
See https://github.com/lowRISC/opentitan/issues/9314#issuecomment-1319471823 for full explanation and rationale.
> [rstmgr_cnsty] Do not hold child handshake under reset

- hw/formal/tools/dvsim/common_formal_cfg.hjson
- hw/lint/tools/dvsim/common_lint_cfg.hjson
- hw/syn/tools/dvsim/common_syn_cfg.hjson
- util/dvsim/Deploy.py
This PR supports build_pass_pattern field in OneShotCfg.
Fix #16295 
> [fpv] Fix jg command not found report

- .bazelignore
> [bazel] Ignore built documentation

- hw/top_earlgrey/data/chip_testplan.hjson
> [test] Map unmapped tests to testpoints

- hw/ip/clkmgr/rtl/clkmgr_root_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
- hw/ip/pinmux/rtl/pinmux_strap_sampling.sv
- hw/ip/prim/rtl/prim_mubi12_sync.sv
- hw/ip/prim/rtl/prim_mubi16_sync.sv
- hw/ip/prim/rtl/prim_mubi4_sync.sv
- hw/ip/prim/rtl/prim_mubi8_sync.sv
- hw/ip/spi_device/rtl/spi_device.sv
- util/design/data/prim_mubi_sync.sv.tpl
This should address https://github.com/lowRISC/opentitan/issues/16586 - please let me know if you have other suggestions.
> [prim_mubi*_sync] Coverage improvements

- hw/ip/aon_timer/data/aon_timer.prj.hjson
- hw/ip/aon_timer/doc/checklist.md
All items in #13704 have been addressed, so this should be g2g.
Fixes #13704
> [aon_timer] Move to D3

- sw/device/silicon_creator/rom/e2e/rom_e2e_ret_ram_init_test.c
- sw/device/silicon_creator/rom/e2e/rom_e2e_ret_ram_keep_test.c
> [tests] Clean up retention SRAM E2E tests

- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv
Increase the possibility of _cycles = _timer + 1 in sysrst_ctrl_ultra_low_pwr test to see a transition from DetectSt to IdleSt in sysrst_ctrl_ulp._sysrst_ctrl_detect FSM blocks.
Check wakeup only when _cycles > _timer + 1.
This was from the coverage report:
With this PR, DetectSt->IdleSt state transitions in tb.dut.u_sysrst_ctrl_ulp.u_sysrst_ctrl_detect_* are hit often.
Signed-off-by: Abdullah Varici <abdullah.varici@lowrisc.org>
> [sysrst_ctrl/cov] Fix SYSRST_CTRL FSM coverage

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
> [test] increase coremark test timeout

- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
- sw/device/silicon_creator/rom/e2e/BUILD
> [test] Add rom_e2e_default_otp_bootup test

- hw/dv/sv/csrng_agent/csrng_agent_cov.sv
this pr fixes regression failure regarding the recent update on CSRNG agent illegal bins.
The `sts` is a random input for EDN and thus agent can randomly drive true or false.
There is a constraint in CSRNG side that sts will also be pass if it is genbits command. But since it has no effect on EDN side, I think it might be better to keep it driving random values.
So I separate coverage collection for host and device agent.
> [dv/edn] Fix regression illegal bin failure

- hw/ip/i2c/rtl/i2c_fsm.sv
After timeout (and interrupt triggered), recount the timeout period again instead of allowing it to immediately re-trigger.
> [i2c] Do not make timeouts persist.

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
This supersedes #16675 as it fixes the actual issue.
> [dv] Remove echo statement that causes issues in regressions

- hw/ip/adc_ctrl/doc/_index.md
- clarifies conditions that would cause a match to clear
- fixes #16611
> [adc] Clarify documentation

- sw/device/silicon_creator/rom/e2e/weak_straps/gpio.bzl
> [bazel] Add tags to test_suite emitted by weak_strap tests.

- release/BUILD
- release/azure-pipelines-release.yml
This PR currently does not trigger anything in Azure. After this is merged, I will create a new pipeline from the Azure dashboard to use this file to perform the release at the scheduled time.
This PR addresses #15007
> [release] Add new Azure pipeline to perform release

- rules/scripts/bitstreams_workspace_test.py
Addresses the comment from the original PR here: https://github.com/lowRISC/opentitan/pull/15603#discussion_r1000549644
> [test] Add tests for bitstream cache pagination-handling

- hw/ip/i2c/doc/_index.md
Matches recent target stretch usability updates.
> [doc] Update i2c documentation.

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
> Revert "[dv] Re-enable RndCnst randomization with build seed"

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_ast_clk_rst_inputs_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/ast_clk_rst_inputs.c
Added test for testing ast_clk_rst_inputs according to issue #14132
> [dv,chip] add chip_sw_ast_clk_rst_inputs test

- hw/top_earlgrey/rdc/rdc_waivers.tcl
- AES, HMAC, KMAC, OTBN hint to CG metastability issue
* Modules above are reset by POR_N together. no metastability corrupts the logic.
- PINMUX Retention to PAD
> [rdc] Various waivers (CG, PINMUX)

- hw/ip/lc_ctrl/doc/_index.md
This PR updates lc_ctrl documentation according to issue #16529.
> [doc/lc_ctrl] update wording for ext_clock_en

- hw/dv/sv/cip_lib/cip_base_env.sv
- hw/dv/sv/cip_lib/cip_base_env_cfg.sv
- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_cipher_fi_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_control_fi_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_core_fi_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_ctr_fi_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_fi_vseq.sv
- hw/ip/clkmgr/dv/env/seq_lib/clkmgr_common_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
- hw/ip/keymgr/dv/env/keymgr_env_cfg.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
- hw/ip/otbn/dv/uvm/env/otbn_env_cfg.sv
- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rnd_sec_cm_vseq.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_background_chks_vseq.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_init_fail_vseq.sv
- hw/ip/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_cnsty_vseq.sv
- hw/top_earlgrey/dv/env/chip_env.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_alert_handler_entropy_vseq.sv
1. fix names m_alert_agent_cfg[string] -> m_alert_agent_cfgs[string] m_edn_pull_agent_cfg[] -> m_edn_pull_agent_cfgs[]
2. Remove some addressed TODOs (see my comments in the PR)
> [dv] Address a few TODO in cip_base

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
Signed-off-by: Douglas Reis <doreis@lowrisc.org>
> [dv] Fix the build of `keymgr_key_derivation_test`

- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
This PR adds the ability to handle multiple SPI target devices through
HyperDebug.  Similarly to how GPIOs are handled, the text command
protocol is used to "look up" instances based on a symbolic name.
HyperDebug firmware supports "QSPI" in addition to the existing
"SPI2", though only standard two-line SPI is currently supported.
> [opentitantool] HyperDebug support for multiple SPI instances

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
We recommend to consolidate interrupts to only a few in design, so I don't think we will have more than 32 interrupts for a block.
Removing the suffix and indices support to resolve the TODO.
> [dv] Remove interrupt suffix and indices support

- sw/device/tests/keymgr_sideload_otbn_test.c
Test clearing the sideload key for OTBN and key regeneration afterwards
Signed-off-by: {Ghada Dessouky} <gdessouky@google.com>
> Test OTBN sideloading

- hw/dv/sv/dv_lib/dv_base_env_cov.sv
- hw/dv/sv/dv_lib/dv_base_test.sv
> [dv] Clean up TODOs in dv_lib

- hw/ip/i2c/rtl/i2c_fsm.sv
- fixes #16746
- previously on re-starts, the fsm would cut the low clock pulse short and go directly to start. While there is not technically anything wrong this with this, it does make things inconsistent.
- update the design slightly to always go through the normal clock sequence on restarts.
> [i2c] Adjust re-start in host mode

- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
This PR fix two tb lock up conditions for tb target mode interrupt handler
1. When tx_fifo is full and tx_stretch interrupt is set, handler waiting tx_fifo not full forever
before it read acq fifo to causes tb lock up.
So, read acq fifo to make ack_fifo depth < 2 then check tx_fifo full.
2. cmd_complete interrupt can assert right after de assert in some tests.
So replace clear & check deassert with clear only to handler next back to back assert.
> [i2c,dv] target regfix

- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson
> [flash_ctrl] Update stale sec_cm hjson for flash_ctrl

- hw/top_earlgrey/data/chip_testplan.hjson
- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
> [chip testplan] Map ROM E2E debug tests

- hw/ip/hmac/data/hmac_sec_cm_testplan.hjson
> [hmac,dv] add bus integrity test

- hw/top_earlgrey/ip/ast/lint/ast.waiver
- hw/top_earlgrey/ip/ast/rtl/ast.sv
One file, `ast.sv,`  is updated with the review comments.
@arnonsha @zi-v 
> [ast] Update D2S review comments

- hw/ip/spi_device/dv/env/seq_lib/spi_device_mem_parity_vseq.sv
> [spi_device/dv] Fix an Xcelium compile error

- doc/rm/ref_manual_fpga.md
- util/fpga/bitstream_bisect.py
This PR documents the tool added in #16406. (Some followup tasks remain in #16788.)
> [doc, fpga] Add bitstream_bisect tool to FPGA reference manual

- azure-pipelines.yml
- release/azure-pipelines-release.yml
I tested this pipeline manually, and it seems to work. The output can be found [here](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=105319&view=results). After this is merged, this pipeline should produce a release artifact once a night.
This PR contributes to #15007.
> [release] Set up release pipeline configuration

- .github/ISSUE_TEMPLATE/darjeeling-issue.md
> [general] Create issue template for top_darjeeling

- doc/project/checklist.md
- doc/ug/dv_methodology/index.md
Update Xprop section of the dv methodology doc and the checklist to make it clear what is expected.
> [doc] Improve wording on Xprop

- .gitignore
> Add Clangd index to .gitignore

- hw/ip/hmac/data/hmac_sec_cm_testplan.hjson
> [hmac,dv] fix typo in v2s test plan

- hw/dv/sv/common_ifs/clk_rst_if.sv
- hw/dv/sv/common_ifs/common_ifs.core
- hw/dv/sv/common_ifs/common_ifs_pkg.sv
- hw/dv/sv/dv_base_reg/dv_base_reg.sv
- hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
- hw/dv/sv/dv_lib/dv_lib.core
- hw/dv/sv/dv_utils/dv_utils_pkg.sv
1. make an eunum for rst_scheme as suggested in the TODO
2. clean up the other TODOs which needs no further action
3. fix core file dependency - common_ifs isn't used in dv_utils, but needed for dv_lib
> [dv] Resolve/clean up more TODOs

- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env.core
- hw/ip/i2c/dv/env/seq_lib/i2c_target_perf_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
Run smoke test with minimum timing value
> [i2c,dv] target performance test

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
Some initial tweaks to the test plan, as discussed in the meeting.
More refinements will come once we work on the tests.
> [rv_dm] Block-level testplan updates

- hw/dv/sv/tl_agent/tl_agent_cov.sv
- hw/dv/sv/tl_agent/tl_monitor.sv
- hw/dv/sv/tl_agent/tl_reg_adapter.sv
> [dv] Clean up TODOs in tl_agent

- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_ast_clk_rst_inputs_vseq.sv
- sw/device/tests/sim_dv/ast_clk_rst_inputs.c
This PR address the comments mentioned in PR #16581. 
Signed-off-by: Ariel Cohen <ariel.cohen@nuvoton.com>
> [dv,chip] Fix PR#16581 comments

- hw/dv/sv/mem_bkdr_scb/mem_bkdr_scb.sv
- hw/dv/sv/mem_bkdr_util/mem_bkdr_util.sv
> [dv] Clean TODOs in mem_bkdr_*

- hw/ip/flash_ctrl/data/flash_ctrl.hjson
- hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
> [flash_ctrl] Fix reset value typo

- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
The RAL has one more level of reg blocks at the chip-level than at the block level, which means that we have to figure out which regblock a register belons to before calling get_supports_sub_word_csr_writes(). I.e., calling it on the top-most RAL (which is the chip RAL in this case) does not return the property we are looking for.
This partially addresses #15803.
> [rv_dm/top] Fix TL errors on the DV side

- hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
- hw/ip/csrng/rtl/csrng_core.sv
- hw/ip/csrng/rtl/csrng_main_sm.sv
- hw/ip/csrng/rtl/csrng_pkg.sv
These errors were flagged by Verilator Lint.
> [lint,csrng] Resolve overwriting state params and enums

- hw/dv/sv/dv_utils/dv_macros.svh
- hw/dv/sv/dv_utils/dv_test_status_pkg.sv
- hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
- hw/dv/tools/dvsim/xcelium.hjson
- hw/ip/prim/rtl/prim_cdc_rand_delay.sv
- hw/ip/rstmgr/data/rstmgr.sv.tpl
- hw/top_earlgrey/dv/env/seq_lib/chip_padctrl_attributes_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_spi_passthrough_collision_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_spi_passthrough_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_in_irq_vseq.sv
- hw/top_earlgrey/ip/ast/rtl/rng.sv
- hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr.sv
> [chip dv] Fix compile time warnings - Xcelium

- doc/getting_started/build_sw.md
- doc/getting_started/setup_fpga.md
> [docs] update descriptions to point to .elf files for debug

- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env.core
- hw/ip/i2c/dv/env/i2c_env_cfg.sv
- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_runtime_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_stress_all_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
Add i2c_target_stress_all test.
set max_outstanding_request = 1 by default.
> [i2c,dv] target stress_all test

- .github/ISSUE_TEMPLATE/general-issue.md
- .github/ISSUE_TEMPLATE/general-issue.yml
Add a few prompts to perform best-practice activities when filing an issue.
> [github] migrate general issue to a yml template

- hw/ip_templates/alert_handler/dv/env/seq_lib/alert_handler_entropy_stress_vseq.sv
- hw/ip_templates/alert_handler/dv/env/seq_lib/alert_handler_entropy_vseq.sv
- hw/ip_templates/alert_handler/dv/env/seq_lib/alert_handler_smoke_vseq.sv
- hw/top_earlgrey/ip_autogen/alert_handler/dv/env/seq_lib/alert_handler_entropy_stress_vseq.sv
- hw/top_earlgrey/ip_autogen/alert_handler/dv/env/seq_lib/alert_handler_entropy_vseq.sv
- hw/top_earlgrey/ip_autogen/alert_handler/dv/env/seq_lib/alert_handler_smoke_vseq.sv
This PR fixes xcelium warnings.
> [dv/alert_handler] Fix xcelium warning

- sw/host/opentitanlib/src/util/usb.rs
The current eager error logging has led to some confusion recently. OpenTitanTool prints the following "ERROR" lines on CI, even though it proceeds to find a suitable device.
[2022-11-11T03:40:43Z ERROR opentitanlib::util::usb] Could not open device at bus=1 address=97
[2022-11-11T03:40:43Z ERROR opentitanlib::util::usb] Could not open device at bus=3 address=95
This commit defers the errors until we know how many USB devices were found so we can choose a suitable severity.
> [ott] Defer determination of log severity for USB errors

- util/dvsim/FlowCfg.py
- util/dvsim/LocalLauncher.py
- util/dvsim/dvsim.py
Related issue: https://github.com/lowRISC/opentitan/issues/16841
> [dvsim] `--interactive` argument on local tasks.

- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_init_fail_vseq.sv
This PR fixes the otp_Init_failure regression error where: the sequence tries to trigger a LC transition failure by clearing the memory, then do a manual check and expect a LC partition failure. But if the partition is previously locked, this will trigger a HW partition failure before the LC partition failure.
> [dv/otp] Fix otp_ctrl_init_failure regression error

- util/dvsim/Deploy.py
- util/dvsim/dvsim.py
> [dvsim] timeout 0 to disable timeout

- hw/ip/uart/dv/env/seq_lib/uart_rx_oversample_vseq.sv
Made the oversampling clock center more accurate
Ran with 500+ seeds and all passed
> [uart/dv] Fix a regression failure

- hw/dv/sv/alert_esc_agent/alert_esc_base_driver.sv
- hw/dv/sv/alert_esc_agent/alert_esc_base_monitor.sv
- hw/dv/sv/alert_esc_agent/alert_esc_if.sv
- hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv
- hw/dv/sv/alert_esc_agent/esc_sender_driver.sv
This PR cleans up TODOs in alert_esc_agent.
> [dv/alert_esc_agent] Clean up TODOs

- hw/ip/pwrmgr/rtl/pwrmgr.sv
> [fpv/pwrmgr] Clean up strong property in simulation

- hw/dv/sv/sec_cm/prim_count_if.sv
- hw/dv/sv/sec_cm/prim_double_lfsr_if.sv
- hw/dv/sv/sec_cm/prim_onehot_check_if.sv
- hw/dv/sv/sec_cm/prim_sparse_fsm_flop_if.sv
- hw/dv/sv/sec_cm/sec_cm_pkg.sv
- hw/dv/sv/sec_cm/sec_cm_prim_count_bind.sv
- hw/dv/sv/sec_cm/sec_cm_prim_double_lfsr_bind.sv
- hw/dv/sv/sec_cm/sec_cm_prim_onehot_check_bind.sv
- hw/dv/sv/sec_cm/sec_cm_prim_sparse_fsm_flop_bind.sv
> [dv,sec_cm] Format code per verible and add simple function

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/rstmgr_cnsty_fault_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rstmgr_cnsty_fault_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- hw/top_earlgrey/dv/env/top_earlgrey_error_injection_ifs_bind.sv
- sw/device/tests/sim_dv/all_escalation_resets_test.c
> [dv,top-level] Add rstmgr reset consistency error test

- hw/ip/edn/data/edn.hjson
- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/kmac/data/kmac.hjson
- hw/ip/pinmux/data/pinmux.hjson.tpl
- hw/ip/sram_ctrl/data/sram_ctrl.hjson
- hw/ip_templates/alert_handler/data/alert_handler.hjson.tpl
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.hjson
- sw/device/lib/dif/autogen/dif_entropy_src_autogen.h
- util/reggen/gen_html.py
- util/reggen/html_helpers.py
> [reggen/doc] Fix a incorrect register references to multiregs

- hw/ip/aon_timer/data/aon_timer_sec_cm_testplan.hjson
- hw/ip/gpio/data/gpio_sec_cm_testplan.hjson
- hw/ip/pattgen/data/pattgen_sec_cm_testplan.hjson
- hw/ip/pwm/data/pwm_sec_cm_testplan.hjson
- hw/ip/rv_timer/data/rv_timer_sec_cm_testplan.hjson
- hw/ip/sysrst_ctrl/data/sysrst_ctrl_sec_cm_testplan.hjson
- hw/ip/uart/data/uart_sec_cm_testplan.hjson
- hw/ip/usbdev/data/usbdev_sec_cm_testplan.hjson
> [dv] Fix some unmapped tl_intg tests

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_core_ibex_lockstep_glitch_vseq.sv
Instead of waiting for a fixed number of cycles and checking for a potential alert in a single clock cycle, we now continuously check for potential alerts during a window of max_delay_clks clock cycles after injecting the glitch. This helps to make the test more robust.
This resolves lowRISC/OpenTitan#16954.
> [top/dv] Make alert checking in Ibex lockstep glitch test more robust

- hw/cdc/tools/verixcdc/run-cdc.tcl
Two fixes
1. Simple and efficient script to resolve unnecessary async_fifo errors reported by VerixCDC
- This script is recommended by RI
- We don't need to use multiple cdc_ignore commands to cover all various paths
- Result is the same as existing one which came from manual multiple cdc_ignore commands
2. Stopping propagation option 2 of AST_CLK_EXT as discussed in #16897
> [CDC|VerixCDC] Simple and efficient script to resolve unnecessary async_fifo errors reported by VerixCDC

- hw/ip/i2c/rtl/i2c_fsm.sv
> [i2c] Fix UNR compile error

- util/dvsim/Deploy.py
- util/dvsim/Modes.py
- util/dvsim/dvsim.py
> [dv,dvsim] Add run timeout multiplier option

- hw/ip/csrng/dv/csrng_sim_cfg.hjson
- hw/ip/edn/dv/edn_sim_cfg.hjson
- hw/ip/gpio/dv/gpio_sim_cfg.hjson
- hw/ip/hmac/dv/hmac_sim_cfg.hjson
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
- hw/ip/pattgen/dv/pattgen_sim_cfg.hjson
- hw/ip/rom_ctrl/dv/rom_ctrl_sim_cfg.hjson
- hw/ip/rv_timer/dv/rv_timer_sim_cfg.hjson
- hw/ip/spi_host/dv/spi_host_sim_cfg.hjson
> [dv/cdc] Add cdc instrumentation for some ips

- hw/ip/flash_ctrl/rtl/flash_phy_rd.sv
- fixes #16979
- In the previou design, the buffer enable was allowed to change whenever the read pipeline was idle.  This however does not account for the scenario where on the same cycle there is a new flash read request.  In the buffer enable were changed from 1->0, it would allow a new request to match a buffer entry, while disallowing that buffer from responding in subsequent cycles.
- Update the design such that when buffer enable is changed the request is back pressured during that same cycle.
> [flash_ctrl] Fix buffer enable / disable timing

- util/reggen/reg_block.py
- util/reggen/register.py
> [reggen] Disallow async REGWENs

- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/ip/ast/rtl/sys_osc.sv
- hw/top_earlgrey/ip/ast/rtl/vcc_pgd.sv
- hw/top_earlgrey/ip/ast/rtl/vio_pgd.sv
Add (* xprop_off *) attributes in some specific processes.
> [dv,xprop] Fix some more xprop issues

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_lc_escalation_vseq.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
Test lc_esc and mem access simultaneously to improve code coverage.
Update scb for it - ignore checking in the period that lc_esc just happens
Also fixed the sequence that drives one reset after the other.
> [sram_ctrl/dv] Update lc_esc test

- doc/rm/register_tool/index.md
> [doc] Add language re. current usage of devmode

- hw/dv/sv/cip_lib/cip_base_env_cfg.sv
Discussed at #16739
We have decided to tie it 1 for the current design, so ICEBOX the TODO.
> [dv] ICEBOX devmode TODO

- hw/ip/sram_ctrl/dv/cov/sram_ctrl_cov_excl.el
> [sram_ctrl/dv] Fix a typo

- hw/ip/i2c/doc/_index.md
- hw/ip/i2c/i2c.core
- hw/ip/i2c/i2c_pkg.core
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_fsm.sv
- hw/ip/i2c/rtl/i2c_pkg.sv
> [i2c] Add loopback support for target mode

- hw/ip/rv_dm/doc/_index.md
> [rv_dm] Documentation update

- sw/device/lib/dif/dif_rstmgr.c
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/rom_e2e_bootstrap_rma_test.c
- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/bindgen/BUILD
- sw/host/opentitanlib/bindgen/difs.h
- sw/host/opentitanlib/src/app/config/opentitan.json
- sw/host/opentitanlib/src/dif/mod.rs
- sw/host/opentitanlib/src/dif/rstmgr.rs
- sw/host/tests/rom/e2e_bootstrap_rma/BUILD
- sw/host/tests/rom/e2e_bootstrap_rma/src/main.rs
This is the first half of #15677.
> [test] Add rom_e2e_bootstrap_rma, iteration 1

- hw/top_earlgrey/doc/design/index.md
> [doc] Update earlgrey documentation for ast clock/reset mapping

- doc/ug/dv_methodology/index.md
> [dv,doc] Add xprop details and make simple improvements

- sw/device/tests/autogen/plic_all_irqs_test.c
- util/topgen/templates/plic_all_irqs_test.c.tpl
> [dv,top-level,tests] Fix plic_all_irqs_test race

- sw/device/tests/autogen/plic_all_irqs_test.c
- util/topgen/templates/plic_all_irqs_test.c.tpl
This PR fixes a small typo on plic test.
> [dv/chip] Fix a typo on plic_all_irqs_test

- hw/ip/otbn/doc/_index.md
- sw/device/tests/otbn_smoketest.c
- sw/otbn/code-snippets/barrett384.s
- sw/otbn/code-snippets/mul256.s
- sw/otbn/code-snippets/mul384.s
- sw/otbn/code-snippets/solinas384.s
For more detail regarding the problem this PR fixes: https://github.com/lowRISC/opentitan/issues/17154
> [otbn] Fix mismatch caused by uninitialised WDRs

- hw/ip/otbn/dv/rig/rig/README.md
I am also planning to add an example of changing the internals to hit a coverage hole but I thought better to have it here for the first feedback.
> [otbn,doc] Add README for RIG internals

- hw/dv/dpi/usbdpi/usb_crc.c
- hw/dv/dpi/usbdpi/usb_monitor.c
- hw/dv/dpi/usbdpi/usb_monitor.h
- hw/dv/dpi/usbdpi/usb_transfer.c
- hw/dv/dpi/usbdpi/usb_transfer.h
- hw/dv/dpi/usbdpi/usbdpi.c
- hw/dv/dpi/usbdpi/usbdpi.core
- hw/dv/dpi/usbdpi/usbdpi.h
- hw/dv/dpi/usbdpi/usbdpi.sv
- sw/device/lib/testing/usb_testutils.c
- sw/device/tests/BUILD
- sw/device/tests/usbdev_test.c
Supersedes #16809, resolves confusion resulting from laptop change. Apologies!
First commit fixes DPI model to allow usbdev_test to pass, and adds diagnostics.
Second commit is initial refactoring of USB DPI model to support top-level testing effort;
no unintended behaviour changes observed when comparing logs and waveforms with earlier simulations
> USB DPI Top-level fixes and refactoring

- doc/ug/dv_methodology/index.md
This resolves lowRISC/OpenTitan#13280
> [doc] Fix broken link to Ibex DV documentation

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_device_tx_rx_vseq.sv
- sw/device/lib/testing/BUILD
- sw/device/lib/testing/i2c_testutils.c
- sw/device/lib/testing/i2c_testutils.h
- sw/device/tests/sim_dv/i2c_device_tx_rx_test.c
> [dv] Update chip_sw_i2c_device_tx_rx test to support multiple instances

- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
The OctoSPI support of HyperDebug firmware has now been merged into the Chrome OS codebase.  In the process, a few adjustments had to be made, which unfortunately required changes to the text-based protocol with the host machine.  This CL makes corresponding changes to transport/hyperdebug, with fallback to handle older firmwares.
Signed-off-by: Jes B. Klinke <jbk@chromium.org>
> [opentitantool] Updates for final HyperDebug firmware

- doc/use_cases/_index.md
- hw/dv/_index.md
- hw/dv/sv/_index.md
- hw/dv/sv/cip_lib/doc/index.md
- hw/dv/sv/common_ifs/index.md
- hw/dv/sv/dv_utils/doc/index.md
- hw/dv/sv/flash_phy_prim_agent/doc/index.md
- hw/dv/sv/jtag_dmi_agent/doc/index.md
- hw/dv/sv/mem_bkdr_util/doc/index.md
- hw/dv/sv/scoreboard/doc/index.md
- hw/dv/sv/tl_agent/doc/index.md
- hw/dv/sv/uart_agent/doc/index.md
- sw/host/_index.md
- util/i2csvg/smbus/SMBus.md
Minor improvements to documentation, including:
- Making sure each page has a Hugo title.
- Adding TODO statements to pages that are empty.
- Minor readability improvements to DV pages.
> [doc] Add titles and TODOs

- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/tb/tb.sv
This PR reverts #17124 as design is not fixed.
> [dv/spi_device] revert #17124

- hw/ip/sysrst_ctrl/data/sysrst_ctrl_testplan.hjson
- hw/ip/sysrst_ctrl/dv/cov/sysrst_ctrl_cov.core
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_auto_blk_key_output_vseq.sv
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_vseq.sv
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ec_pwr_on_rst_vseq.sv
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_edge_detect_vseq.sv
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_flash_wr_prot_vseq.sv
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv
- hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson
In this PR I make some minor changes to the test plan and the tests after a first review:
- Correct some comments.
- Correct some white-space alignment.
- Correct test plan descriptions to match what is actually being tested.
- Added a TODO in `sysrst_ctrl_ec_pwr_on_rst_vseq` to actually do a chip reset.
> [sysrst_ctrl,dv] Review of test plan

- azure-pipelines.yml
> [ci] Increase timeout for cw310 bitstream

- hw/ip/otbn/pre_sca/alma/README.md
- hw/ip/otbn/pre_sca/alma/verify_otbn.sh
Signed-off-by: Abdullah Varici <abdullah.varici@lowrisc.org>
> [otbn, pre_sca] Add usage of init-delay and label generation.

- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_vseq.sv
Updated sequence to release ec_rst_l_o using PIN_OUT_CTL.ec_rst_l. This is to make sure transitions of ec_rst_l_o can be observed in the test for cases where ec_rst_l_o is selected as a output combo action
Signed-off-by: Raviteja Chatta <crteja@lowrisc.org>
> [sysrst_ctrl] Added a task to release ec_rst_l_o after reset

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_smoke_vseq.sv
Hi,
In this PR the partition randomization in rand_ops and smoke tests is updated to more correct and specific manner.
Thanks!
> [dv/flash] Update rand_ops & smoke partitions randomizations

- hw/ip/sysrst_ctrl/data/sysrst_ctrl_testplan.hjson
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_ec_rst_vseq.sv
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_ec_rst_with_pre_cond_vseq.sv
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_vseq.sv
- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_vseq_list.sv
- hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.core
- hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv
- hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson
This PR is based on PR #17217 , then it implements a direct test to check pre-conditions.
Following this, the plan is to fully support pre-condition in scb.
> Sysrst pre cond direct test

- util/dvsim/qsubopts.py
Hi,
This PR is fixing an issue we had with SunGrid.
This will make the command file created by SunGrid to be exclusive to each run and to be deleted after the run is finished.
> [dv/util/sungrid] Fix issue when running sungrid in parallel

- sw/device/tests/power_virus_systemtest.c
This configure SPI Host 1, and transmits data over it, for the power virus test. This partially addresses #14814.
> [test] drive SPI host 1 in power virus test

- sw/host/opentitanlib/src/transport/hyperdebug/gpio.rs
Take advantage of recent addition to HyperDebug firmware, to be able to simultaneously set opend drain / push pull, as well as output level and weak pulling mode of a GPIO pin.  This avoids glitches on the signals, which could otherwise happen if mode and level were set separately.
> [opentitantool] Atomic gpio manipulation for HyperDebug

- sw/device/silicon_creator/lib/sigverify/sphincsplus/BUILD
- sw/device/silicon_creator/lib/sigverify/sphincsplus/address_unittest.cc
Add some basic unit testing for the SPHINCS+ hypertree address interface.
> [crypto] Add SPHINCS+ address unit tests.

- sw/otbn/crypto/p256.s
See https://github.com/lowRISC/opentitan/issues/16952 for context. Follow-up for #16953
This change:
- Adjusts scalar_mult_int to use the new extra-long shares
- This required some register rearranging in order to reduce register pressure
- Adjusts random-scalar generation code to generate extra-long shares
> [crypto] Use extra bits in all P-256 point-scalar multiplication and random scalar generation

- hw/ip/flash_ctrl/dv/env/flash_ctrl_if.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip/flash_ctrl/dv/tb/tb.sv
Hi,
This PR is adding a control of both the width of the reset and the timing between the reset and the power-down.
This came to be needed by extending environments.
Thanks!
> [dv/flash] Add timing control for the apply-reset and power-down

- WORKSPACE
Added support for analog output.
> [opentitantool] New HyperDebug firmware

- sw/device/silicon_creator/lib/sigverify/sphincsplus/BUILD
- sw/device/silicon_creator/lib/sigverify/sphincsplus/wots.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/wots.h
This is one of the key building blocks of SPHINCS+ and the most performance-critical portion of the code.
> [crypto] Add WOTS signatures for SPHINCS+.

- hw/dv/sv/i2c_agent/i2c_if.sv
Previously it waited til SCL was high then set SDA low. This resulted in SDA transitioning from high to low at an SCL positive edge in various cases which is not correct I2C behaviour. With this change SDA will be set low before the positive SCL edge.
> [i2c_agent] Fix host_stop behaviour

- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_edge_detect_vseq.sv
- hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_pkg.sv
- hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv
- hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim.core
- hw/top_earlgrey/lint/top_earlgrey_dv_lint_cfgs.hjson
Resolve TODOs in system reset control based on this issue: https://github.com/lowRISC/opentitan/issues/17278
> [sysrst_ctrl] Resolve outstanding TODOs

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
Fixes false constraint error that caused by PR #17299 in some of the flash tests.
Thanks!
> [dv/flash] Fix reset randomization constraint error

- hw/ip/usbdev/rtl/usb_consts_pkg.sv
- hw/ip/usbdev/rtl/usb_fs_rx.sv
- hw/ip/usbdev/rtl/usb_fs_tx.sv
- hw/ip/usbdev/rtl/usbdev.sv
- hw/ip/usbdev/rtl/usbdev_linkstate.sv
Correct off-by-one error in microsecond timer
Fix minor typographical errors in comments
> [usbdev] Fix 1us timing reference

- hw/ip/otbn/pre_sca/alma/rtl/otbn_top_coco.v
This will allow us to label them.
Signed-off-by: Abdullah Varici <abdullah.varici@lowrisc.org>
> [otbn, pre_sca] Make sideload key signals as input

- COMMITTERS
Remove Canberk from the list committers. Thanks for all your contributions!
> [COMMITTERS] Update list of committers

- doc/project/priority_definitions.md
This commit addresses the RFC referenced by #17104.
Fixes https://github.com/lowRISC/opentitan/issues/17104
> [doc] Add generalized issue priority definitions

- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv
- util/topgen.py
- util/topgen/entropy_buffer_generator.py
- util/topgen/merge.py
- util/topgen/validate.py
[topgen] Amend topgen to use strong_random class
> Topgen strong random

- hw/ip/otbn/util/otbn_sim_test.py
This saves me some hassle when I get OTBN error codes and need to figure out what they mean (added it while developing https://github.com/lowRISC/opentitan/pull/17324).
Previously, a failing `otbn_sim_test` target would give me a result like:
```
ERROR: OTBN encountered an unexpected error.
ERR_BITS	= 0x00000008
INSN_CNT	= 0x00000060
STOP_PC	= 0x00000030
```
...and then I'd have to go look up what error `0x00000008` was. Now, I get the error name too:
```
ERROR: OTBN encountered an unexpected error: ILLEGAL_INSN.
ERR_BITS	= 0x00000008
INSN_CNT	= 0x00000060
STOP_PC	= 0x00000030
```
> [otbn, test] Print the error name in OTBN simulator tests.

- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv
Only the last commit is relevant.
This PR is based on comment: https://github.com/lowRISC/opentitan/pull/17247/files#r1102650481
@crteja please let me know if this meets your suggestion?
> [dv/sysrst] Sysrst z3 test

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_erase_suspend_vseq.sv
Hi,
This PR is fixing the erase_suspend test.
Thanks!
> [dv/flash] fix erase_suspend test

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_vseq.sv
- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Hi,
This PR is adding some controls to RW & OTF sequences that are required by extending env.
Thanks!
> [dv/flash] add controls to RW & OTF vseqs

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_otp_ctrl_vendor_test_csr_access_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/otp_ctrl_vendor_test_csr_access_test.c
This PR implements the V3 chip level test
`otp_ctrl_vendor_test_csr_access` according to issue #17417.
> [dv/chip] otp_ctrl_vendor_test_csr_access test

- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
Previously, when the DUT was busy, but didn't set the stall flag, and didn't have valid output, wasn't ready for new input the environment assumed the DUT was stuck and would abort the simulation with a fatal error after some time.
However, this condition is actually perfectly legal if the DUT is requesting entropy for reseeding the PRNGs which may take a long time. For this reason, this commit changes the check to only error out if no entropy is requested.
This is related to lowRISC/OpenTitan#17399.
> [aes, dv] Don't abort simulation when DUT is busy and requesting entropy

- hw/top_earlgrey/sw/autogen/top_earlgrey.rs
- hw/top_earlgrey/sw/autogen/top_earlgrey_memory.rs
- util/topgen.py
- util/topgen/lib.py
- util/topgen/rust.py
- util/topgen/templates/toplevel.rs.tpl
- util/topgen/templates/toplevel_memory.rs.tpl
Add rust language support for topgen.
Add template for generating all chip level constants and enum for rust.
In order to test this commit pleas run following command:
"cd $REPO_TOP"
"make -C hw top"
> [utils/topgen] Add automatic generated Rust file for topgen

- hw/dv/doc/dv_doc_template.md
- hw/ip/i2c/dv/README.md
- hw/ip/otbn/dv/README.md
- hw/ip/sram_ctrl/dv/README.md
- hw/ip_templates/alert_handler/dv/README.md
- hw/top_earlgrey/dv/README.md
- hw/top_earlgrey/ip_autogen/alert_handler/dv/README.md
- util/uvmdvgen/index.md.tpl
Update DV results of i2c DV page to
https://reports.opentitan.org/hw/ip/i2c/dv/latest/report.html
> [i2c,doc] Update DV page simulation results link

- sw/host/opentitanlib/src/transport/common/uart.rs
Add an explicit sleep rather than using an I/O poll with timeout.
> [otlib] Adjust the UART pacing

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
This PR implemented a nonblocking method to set the sw strap pins only when ROM / tes ROM is executing, and release the pins afterwards. Issue #17488
> [dv/chip] Add an independent task set and release sw_strap_pins

- sw/host/opentitanlib/src/uart/console.rs
- sw/host/tests/chip/spi_passthru/src/main.rs
> [spi_passthru] Test the page_program opcode

- doc/security/specs/secure_boot/README.md
- sw/device/silicon_creator/rom/keys/README.md
Document how to generate keys and also document how the key slots work and what they are.
> Rom key documentation update

- util/design/gen-flash-img.py
This PR contains two commits that:
1. computes the flash scrambling keys from the seeds stored in OTP,
2. checks if the the flash scrambling enablement field is set in the OTP image to trigger scrambling of the flash image.
Note: this depends on #17498, only review the last two commits.
> [util] compute flash scrambling keys in flash VMEM processing script

- sw/host/opentitanlib/src/transport/hyperdebug/gpio.rs
In a few places, the driver code did not pay attention to the textual output from commands sent to HyperDebug, with the result that incorrect pin names would sometimes be silently ignored.  This change adds additional validation to make sure that errors surface as errors in opentitantool.
> [opentitantool] Stricter validation of HyperDebug responses

- util/design/gen-flash-img.py
- util/design/gen-lc-state-enc.py
- util/design/gen-otp-img.py
- util/design/gen-otp-mmap.py
Experiment to see if this reduces IOPs. The default output buffer size is 8KiB so this is a 256x increase.
> [util] Increase output buffer sizes and write in binary mode

- util/site/site-builder/builder.Dockerfile
Update Node JS from v18.7.0 to v18.15.0.
> [util/site] Update Node JS version

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_power_virus_vseq.sv
- sw/device/tests/power_virus_systemtest.c
- In the C code:
- Fix the SDA and SCL connections
- Add I2C read-back code to the end of the max-power task
- Transmit 63 bytes instead of 64 bytes
- In the SV sequence:
- Fix the I2C agent configuration
- Hard-code the peripheral_clock_nanos variable
- Add <target_addr0> parameter to the I2C agent config
> [test] Add I2C acknowledgement to power virus test

- util/dvsim/FlowCfg.py
(When called by an appropriately-authenticated host), this change will allow a dvsim job that publishes its results to trigger a rebuild of the website. This will make the nightlies trigger a rebuild upon completion of their report-publication step.
This is deliberately brittle, as it depends on CLI tools being present as well as a locally-authenticated host with appropriate permissions for the Gcloud project. It also hardcodes the project name and requires the manual setup of a Cloud-Build Trigger.
If any of those prereqs change, then it might be a good idea to make this more generic.
> [site,ci] Add function called by dvsim publish to trigger a website rebuild

- sw/host/opentitantool/src/command/spi.rs
Sometimes HyperDebug could be connected to a non-eeprom/flash device, or sometimes the user might want to send some non-standard command to a SPI eeprom/flash.
This CL introduces commands similar to what exists for I2C to send and receive arbitrary byte sequences.
> [opentitantool] Allow sending/receiving plain bytes via SPI

- doc/project_governance/technical_committee.md
Welcome to the Technical Committee @timothytrippel! Thanks for all your contributions to OpenTitan so far.
> [doc] Add new member to Technical Committee

- hw/ip/otbn/pre_sca/alma/README.md
- hw/ip/otbn/pre_sca/alma/verify_otbn.sh
This option may be buggy and should not be used for analysis.
> [otbn, pre_sca] Remove loose glitch behaviour option

- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
Hi,
This fix is required for extending env for some OTF tests.
Thanks!
> [flash/dv] Add some functionality to otf read required by extending env

- sw/device/lib/testing/csrng_testutils.c
- sw/device/lib/testing/csrng_testutils.h
- sw/device/lib/testing/test_framework/check.h
- sw/device/tests/csrng_edn_concurrency_test.c
- sw/device/tests/csrng_kat_test.c
- sw/device/tests/csrng_smoketest.c
Fix https://github.com/lowRISC/opentitan/issues/17528
> [Csrng] Refactor tests to use status t

- sw/device/lib/testing/lc_ctrl_testutils.c
- sw/device/lib/testing/lc_ctrl_testutils.h
- sw/device/silicon_creator/rom/e2e/epmp_init_test.c
- sw/device/tests/sim_dv/lc_ctrl_transition_impl.c
- sw/device/tests/sim_dv/lc_walkthrough_test.c
- sw/device/tests/sim_dv/lc_walkthrough_testunlocks_test.c
- sw/device/tests/sim_dv/otp_ctrl_lc_signals_test.c
- sw/device/tests/sim_dv/sram_ctrl_execution_main_test.c
The first commit comes from #17563
> [lc_ctrl] Refactor tests to use status t 

- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/keymgr_testutils.h
- sw/device/silicon_creator/lib/drivers/keymgr_functest.c
- sw/device/silicon_creator/rom/e2e/rom_e2e_keymgr_init_test.c
- sw/device/tests/entropy_src_edn_reqs_test.c
- sw/device/tests/keymgr_key_derivation_test.c
- sw/device/tests/keymgr_sideload_aes_test.c
- sw/device/tests/keymgr_sideload_kmac_test.c
- sw/device/tests/keymgr_sideload_otbn_test.c
- sw/device/tests/sim_dv/alert_handler_escalation.c
- sw/device/tests/sim_dv/otp_ctrl_lc_signals_test.c
Fix https://github.com/lowRISC/opentitan/issues/17535
> Keymgr testutils refactor

- sw/host/opentitantool/src/command/i2c.rs
In order to interact with many I2C devices, a write-then-read transaction in needed where the write phase contains the offset of the desired register.
> [ottool] Add a `raw-write-read` command for I2C

- sw/device/tests/BUILD
- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/app/mod.rs
- sw/host/opentitanlib/src/io/jtag.rs
- sw/host/opentitanlib/src/io/mod.rs
- sw/host/opentitanlib/src/proxy/errors.rs
- sw/host/opentitanlib/src/transport/cw310/mod.rs
- sw/host/opentitanlib/src/transport/errors.rs
- sw/host/opentitanlib/src/transport/mod.rs
- sw/host/opentitanlib/src/util/mod.rs
- sw/host/opentitanlib/src/util/openocd.rs
- sw/host/tests/chip/jtag/BUILD
- sw/host/tests/chip/jtag/src/main.rs
- util/openocd/target/BUILD
- util/openocd/target/lowrisc-earlgrey-lc.cfg
@timothytrippel this is work in progress
To run the test:
```
bazel test --test_output=all //sw/device/tests:test_openocd
```
> [opentitantool] Add JTAG I/O using OpenOCD

- sw/device/lib/testing/entropy_testutils.c
- sw/device/lib/testing/entropy_testutils.h
- sw/device/sca/ecc256_keygen_serial.c
- sw/device/sca/ecc256_sign_serial.c
- sw/device/sca/ecc384_serial.c
- sw/device/silicon_creator/lib/drivers/kmac_functest.c
- sw/device/silicon_creator/lib/drivers/rnd_functest.c
- sw/device/tests/aes_entropy_test.c
- sw/device/tests/aes_idle_test.c
- sw/device/tests/crypto/ecdsa_p256_functest.c
- sw/device/tests/csrng_edn_concurrency_test.c
- sw/device/tests/entropy_src_csrng_test.c
- sw/device/tests/entropy_src_edn_reqs_test.c
- sw/device/tests/entropy_src_fw_ovr_test.c
- sw/device/tests/entropy_src_kat_impl.c
- sw/device/tests/entropy_src_smoketest.c
- sw/device/tests/keymgr_sideload_aes_test.c
- sw/device/tests/otbn_ecdsa_op_irq_test.c
- sw/device/tests/otbn_irq_test.c
- sw/device/tests/otbn_randomness_test.c
- sw/device/tests/otbn_rsa_test.c
- sw/device/tests/otbn_smoketest.c
- sw/device/tests/power_virus_systemtest.c
- sw/device/tests/rv_core_ibex_rnd_test.c
- sw/device/tests/sim_dv/ast_clk_rst_inputs.c
- sw/device/tests/sim_dv/csrng_lc_hw_debug_en_test.c
Fix https://github.com/lowRISC/opentitan/issues/17530
> [test_utils] Refactor entropy complex testutils

- hw/ip/csrng/dv/csrng_sim_cfg.hjson
- hw/ip/edn/dv/edn_sim_cfg.hjson
- hw/ip/edn/dv/env/edn_env_pkg.sv
- hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson
- hw/ip/pattgen/dv/pattgen_sim_cfg.hjson
- hw/ip/sysrst_ctrl/dv/tb.sv
Some cleanup of TODOs that I encountered during the effort estimation exercise.
> [dv] TODO cleanup

- sw/device/lib/testing/spi_device_testutils.c
- sw/device/lib/testing/spi_device_testutils.h
- sw/device/tests/power_virus_systemtest.c
- sw/device/tests/sim_dv/spi_passthrough_test.c
- sw/device/tests/spi_passthru_test.c
Fix https://github.com/lowRISC/opentitan/issues/17546
> [spi_dev, testutils] Refactor to return status_t

- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/otp_ctrl_testutils.c
- sw/device/lib/testing/otp_ctrl_testutils.h
- sw/device/silicon_creator/lib/drivers/keymgr_functest.c
- sw/device/tests/entropy_src_edn_reqs_test.c
- sw/device/tests/keymgr_key_derivation_test.c
- sw/device/tests/lc_ctrl_otp_hw_cfg_test.c
- sw/device/tests/otp_ctrl_smoketest.c
- sw/device/tests/sim_dv/csrng_fuse_en_sw_app_read.c
- sw/device/tests/sim_dv/csrng_lc_hw_debug_en_test.c
- sw/device/tests/sim_dv/entropy_src_fuse_en_fw_read_test.c
- sw/device/tests/sim_dv/inject_scramble_seed.c
- sw/device/tests/sim_dv/lc_walkthrough_test.c
- sw/device/tests/sim_dv/lc_walkthrough_testunlocks_test.c
- sw/device/tests/sim_dv/otp_ctrl_lc_signals_test.c
- sw/device/tests/sim_dv/sram_ctrl_execution_main_test.c
Fix https://github.com/lowRISC/opentitan/issues/17539
> [otp_ctrl, testutils] Refactor to return status_t

- sw/device/lib/testing/rand_testutils.c
- sw/device/lib/testing/rv_core_ibex_testutils.c
- sw/device/lib/testing/rv_core_ibex_testutils.h
- sw/device/tests/rv_core_ibex_rnd_test.c
Fix https://github.com/lowRISC/opentitan/issues/17545
> [rv_core_ibex, testutils] Refactor to return status_t

- sw/device/sca/ecc256_keygen_serial.c
This PR contains two updates to improve OTBN ECC256 keygen capture setup:
- Mute ibex during the OTBN operation to reduce noise
- Move seed masking outside of the batch capture loop to prevent "fake leakage".
> [otbn/sca] Improve OTBN SCA capture setup

- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/lib/sigverify/spx_key.h
- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/keys/fake/spx/BUILD
- sw/device/silicon_creator/rom/keys/fake/spx/dev_key_0_spx.h
- sw/device/silicon_creator/rom/keys/fake/spx/prod_key_0_spx.h
- sw/device/silicon_creator/rom/keys/fake/spx/sigverify_spx_keys_fake.c
- sw/device/silicon_creator/rom/keys/fake/spx/sigverify_spx_keys_fake_unittest.cc
- sw/device/silicon_creator/rom/keys/fake/spx/test_key_0_spx.h
- sw/device/silicon_creator/rom/sigverify_keys_spx.h
Marked as draft since the fake keys need to be updated.
> [sw/silicon_creator] Add fake SPHINCS+ keys

- hw/ip/flash_ctrl/rtl/flash_mp.sv
This PR temp fix all_escalation CI failure. This PR will help unblock current CI issues. But for real fix, we can keep discussing in issue number #17692.
> [dv/chip] fix all_escalation CI failure

- azure-pipelines.yml
This reverts commit aa7d5990e69c26cc55a1c655ab1b0123d1ce299d.
Azure runners are running once again. Revert switch to self-hosted runners to resume usual CI operation.
> Revert "[ci] Switch all jobs to self-hosted runners"

- sw/host/opentitanlib/src/transport/common/uart.rs
In order for SW flow control to work, we cannot allow very many characters to accumulate in buffers/FIFOs of the operating system or hardware debuggers.  For that reason, the current code "paces" its output, to ensure that there cannot be any built-up.
The overhead of such pacing may reduce the throughput, depending on timer precision and system load.  The effect is large enough that the Ti50 serial "rescue" bootstrapping takes 5 minutes instead of around 1 minute, which causes timeouts in automated tests.
This PR disables the pacing of the output, of software flow control is disabled.  There can be no use cases for pacing without flow control, as it could allow continuous output of characters at maximum speed, assuming optimal timer behavior.  It cannot be "worse" than that without …
> [opentitantool] Only do UART pacing when SW flow control enabled

- hw/ip/rstmgr/rtl/rstmgr.sv
- hw/ip/rstmgr/rtl/rstmgr_pkg.sv
As rstmgr is at D2S these TODOs do not apply
> [rstmgr] Remove old TODOs

- hw/top_earlgrey/sw/autogen/chip/BUILD
- sw/device/tests/BUILD
- sw/host/opentitanlib/src/app/config/opentitan.json
- sw/host/opentitanlib/src/app/config/opentitan_cw310.json
- sw/host/opentitanlib/src/io/jtag.rs
- sw/host/opentitanlib/src/util/openocd.rs
- sw/host/tests/chip/jtag/BUILD
- sw/host/tests/chip/jtag/src/main.rs
- util/openocd/target/lowrisc-earlgrey.cfg
> [opentitantool] add support for RISC-V JTAG TAP

- ci/azure-pipelines-nightly.yml
This reverts commit fe61f04e099b579df466a722a76dc89ae9555031.
> Revert "[ci] Switch all nightly jobs to self-hosted runners"

- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_parallel_lc_esc_vseq.sv
This PR enhances OTP lc sequence to handle the case where during OTP program we issue a LC escalation.
> [dv/otp_ctrl] Enhance OTP lc esc sequence

- hw/ip/tlul/rtl/tlul_adapter_reg.sv
This TODO related to issue #15822 and not applicable to M2.5. So moved to ICEBOX.
> [tlul] Move TODO to ICEBOX

- hw/dv/sv/i2c_agent/i2c_if.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_device_tx_rx_vseq.sv
Updates to fix `i2c_target_smoke` test failures
> [hw,i2c,dv] I2c target_smoke test fixes

- sw/device/lib/testing/sram_ctrl_testutils.c
- sw/device/lib/testing/sram_ctrl_testutils.h
- sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c
- sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test.c
Fix https://github.com/lowRISC/opentitan/issues/17547
> [Sram ctrl] Testutils refactor 

- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/kmac_testutils.c
- sw/device/lib/testing/kmac_testutils.h
- sw/device/tests/keymgr_sideload_kmac_test.c
- sw/device/tests/sim_dv/otp_ctrl_lc_signals_test.c
Fix https://github.com/lowRISC/opentitan/issues/17536
> [Kmac] refactor testutils

- sw/device/lib/testing/spi_flash_emulator.c
- sw/device/lib/testing/spi_flash_testutils.c
- sw/device/lib/testing/spi_flash_testutils.h
- sw/device/tests/sim_dv/spi_passthrough_test.c
- sw/device/tests/spi_host_smoketest.c
- sw/device/tests/spi_passthru_test.c
> [Spi flash] testutils refactor to return status_t

- rules/scripts/gdb_test_coordinator.py
At the moment, the script will either terminate openocd or just exit early when a failure is detected. This is inconvenient because some important output/error messages maybe still be in the pipe or some other process is not dead yet and still printing. This commit gives a chance to print more messages before exiting. Currently the timeout is one second but it can easily be changed.
> [gdb_test_coordinator] flush the output of all processes before quitting

- doc/security/implementation_guidelines/hardware/README.md
> [doc] Minor fix in intro of Sec HW Design Guideline

- sw/device/lib/dif/dif_spi_host.c
- sw/device/lib/dif/dif_spi_host.h
- sw/device/lib/dif/dif_spi_host_unittest.cc
Add DIFs and unittests to read and write the EVENT_ENABLE register.
> [Spi host]  Add DIFs to read and write the EVENT_ENABLE register

- hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
- hw/ip/flash_ctrl/dv/env/flash_mem_addr_attrs.sv
These 'TODO's are either obsolete or outdated.
> [flash_ctrl,dv] clean up TODO

- sw/device/lib/crypto/impl/BUILD
- sw/device/lib/crypto/impl/ecc.c
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/ecdh_p256_functest.c
Also modifies tests to use the top-level interface.
> [crypto] Connect ECDH-P256 to the cryptolib API.

- hw/ip/i2c/rtl/i2c_fsm.sv
Related to this issue: https://github.com/lowRISC/opentitan/issues/18004
> [i2c,rtl] Put TODO related to multi-host in icebox

- hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
- hw/ip/flash_ctrl/dv/env/flash_otf_item.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_base_vseq.sv
Review all remaining TODOs and updated
> [flash_ctrl,dv] TB cleanup for M2.5

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_adc_ctrl_sleep_debug_cable_wakeup_vseq.sv
Change the test to use the AST ADC output port.
> [dv, chip-test, adc-ctrl] Update chip_sw_adc_ctrl_sleep_debug_cable_wakeup test

- hw/ip/lc_ctrl/dv/env/lc_ctrl_if.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv
- hw/ip/lc_ctrl/dv/lc_ctrl_sim_cfg.hjson
This PR removes some stale TODO and filed issue for future enhancement.
> [dv/lc_ctrl] remove some stale TODOs

- sw/device/lib/testing/README.md
- sw/device/lib/testing/clkmgr_testutils.c
- sw/device/lib/testing/clkmgr_testutils.h
- sw/device/lib/testing/test_framework/check.h
- sw/device/tests/aes_idle_test.c
- sw/device/tests/ast_clk_outs_test.c
- sw/device/tests/clkmgr_external_clk_src_for_sw_impl.c
- sw/device/tests/clkmgr_reset_frequency_test.c
- sw/device/tests/clkmgr_sleep_frequency_test.c
- sw/device/tests/hmac_enc_idle_test.c
- sw/device/tests/otbn_randomness_test.c
- sw/device/tests/sim_dv/ast_usb_clk_calib.c
- sw/device/tests/sim_dv/uart_tx_rx_test.c
Fix https://github.com/lowRISC/opentitan/issues/17527
> Clkmgr testutils refactor

- hw/ip/i2c/data/i2c_testplan.hjson
- Update Stimulus description for target glitch test
- Fixed typos in test names
> [hw,i2c,dv] Update descriptions in testplan

- sw/device/lib/testing/rstmgr_testutils.c
- sw/device/lib/testing/rstmgr_testutils.h
- sw/device/tests/alert_handler_reverse_ping_in_deep_sleep_test.c
- sw/device/tests/clkmgr_off_peri_test.c
- sw/device/tests/clkmgr_off_trans_impl.c
- sw/device/tests/clkmgr_reset_frequency_test.c
- sw/device/tests/pwrmgr_smoketest.c
- sw/device/tests/rstmgr_smoketest.c
- sw/device/tests/sim_dv/adc_ctrl_sleep_debug_cable_wakeup_test.c
- sw/device/tests/sim_dv/ast_clk_rst_inputs.c
- sw/device/tests/sim_dv/pwrmgr_b2b_sleep_reset_test.c
- sw/device/tests/sim_dv/pwrmgr_deep_sleep_all_reset_reqs_test.c
- sw/device/tests/sim_dv/pwrmgr_deep_sleep_power_glitch_test.c
- sw/device/tests/sim_dv/pwrmgr_main_power_glitch_test.c
- sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_reset_reqs_test.c
- sw/device/tests/sim_dv/pwrmgr_random_sleep_all_reset_reqs_test.c
- sw/device/tests/sim_dv/pwrmgr_random_sleep_power_glitch_reset_test.c
- sw/device/tests/sim_dv/pwrmgr_sleep_power_glitch_test.c
- sw/device/tests/sim_dv/rv_dm_ndm_reset_req.c
- sw/device/tests/sim_dv/rv_dm_ndm_reset_req_when_cpu_halted.c
- sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c
- sw/device/tests/sim_dv/sysrst_ctrl_reset_test.c
- sw/device/tests/sim_dv/sysrst_ctrl_ulp_z3_wakeup_test.c
- sw/device/tests/sleep_pwm_pulses_test.c
- sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test.c
Fix https://github.com/lowRISC/opentitan/issues/17543
> Rstmgr testutils refactor

- sw/device/silicon_creator/manuf/lib/provisioning.c
This is to facilitate a good known initial configuration for the flash_ctrl, which expects both secrets to be configured correctly for regular device operations. An invalid Creator or Owner secret will cause the flash_ctrl to trigger a fatal alert early in the boot sequence.
Part of https://github.com/lowRISC/opentitan/issues/17393
> [manuf] Add owner secret to provisioning test

- hw/ip/prim_generic/lint/prim_generic_usb_diff_rx.waiver
- hw/ip/prim_generic/prim_generic_usb_diff_rx.core
- hw/ip/prim_generic/rtl/prim_generic_usb_diff_rx.sv
This models the USB pullup behavior in open-source. 
Let me know if this aligns with your understanding.
Fixes #17986
> [usb_diff_rx] Model pull-up behavior

- sw/device/lib/testing/alert_handler_testutils.c
- sw/device/lib/testing/alert_handler_testutils.h
- sw/device/tests/alert_handler_lpg_clkoff_test.c
- sw/device/tests/alert_handler_lpg_reset_toggle.c
- sw/device/tests/alert_handler_lpg_sleep_mode_alerts.c
- sw/device/tests/alert_handler_lpg_sleep_mode_pings.c
- sw/device/tests/alert_handler_ping_timeout_test.c
- sw/device/tests/alert_handler_reverse_ping_in_deep_sleep_test.c
- sw/device/tests/aon_timer_wdog_lc_escalate_test.c
- sw/device/tests/autogen/alert_test.c
- sw/device/tests/chip_power_idle_load.c
- sw/device/tests/chip_power_sleep_load.c
- sw/device/tests/entropy_src_edn_reqs_test.c
- sw/device/tests/rstmgr_alert_info_test.c
- sw/device/tests/rv_core_ibex_nmi_irq_test.c
- sw/device/tests/sim_dv/alert_handler_entropy_test.c
- sw/device/tests/sim_dv/all_escalation_resets_test.c
- sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c
- sw/device/tests/sim_dv/pwrmgr_deep_sleep_all_reset_reqs_test.c
- sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_reset_reqs_test.c
- sw/device/tests/sim_dv/pwrmgr_random_sleep_all_reset_reqs_test.c
- sw/device/tests/sim_dv/pwrmgr_random_sleep_power_glitch_reset_test.c
- util/topgen/templates/alert_test.c.tpl
Fix https://github.com/lowRISC/opentitan/issues/17525
> Alert handler testutils refactor

- hw/ip/lc_ctrl/dv/env/lc_ctrl_if.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_base_vseq.sv
- hw/ip/lc_ctrl/dv/tb.sv
This PR removes some stale todos, or file issue for icebox todos.
> [dv/lc_ctrl] remove todos from lc testbench

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson
- Add status register check for new sec_cm entries (#16794)
> [flash_ctrl,dv] add lc_gate sec_cm

- doc/security/specs/identities_and_root_keys/README.md
The OwnerIdentitySeed should be cleared, there is no such thing as an OwnerRootSeed.
> doc: Fix OwnerIdentity clearing step

- hw/ip/lc_ctrl/dv/env/lc_ctrl_env_cfg.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
Filed issue #18078 to track iceboxed/stale ambiguous lc_ctrl dv todos.
> Icebox ambiguous LC_CTRL DV TODOs

- hw/ip/pinmux/rtl/pinmux.sv
As discussed in https://github.com/lowRISC/opentitan/pull/17956#discussion_r1164781366.
Fix #17956 #17413
@cindychip would you mind testing this with the FPV environment?
> [pinmux] Add assertion for bus integrity error

- SUMMARY.md
- sw/device/silicon_creator/rom/doc/rom_overview_specification.md
- sw/device/silicon_creator/rom/doc/shutdown.md
Convert from Google doc to Markdown.
> [doc] Add shutdown spec

- SUMMARY.md
- sw/device/silicon_creator/rom/doc/rom_overview_specification.md
- sw/device/silicon_creator/rom/doc/sigverify.md
Google doc to Markdown conversion.
> [doc] Add the ROM signature verification spec

- sw/host/opentitanlib/src/io/eeprom.rs
- sw/host/opentitanlib/src/io/spi.rs
- sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
Support for multi-lane SPI flash.
For now, requires this stack of patches to HyperDebug firmware:
https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4336270
> [opentitantool] HyperDebug SPI multi-lane support

- hw/dv/sv/jtag_agent/jtag_driver.sv
- hw/dv/sv/jtag_agent/jtag_item.sv
- Add four fields in `jtag_item` to support introducing Pause states in an active TAP request
-  `dr_pause_cycle` -> indicates on which cycle pause state is introduced
-  `dr_pause_count` -> indicates number of cycles pause state is retained
-  `ir_pause_cycle` -> indicates on which cycle pause state is introduced
-  `ir_pause_count` -> indicates number of cycles pause state is retained
- Update jtag_driver such that there are minimal changes in environment
This PR partially addresses https://github.com/lowRISC/opentitan/issues/17032
> [hw,rv_dm,dv] Update jtag_item to support random pauses

- hw/ip/csrng/rtl/csrng.sv
- hw/ip/csrng/rtl/csrng_cmd_stage.sv
- hw/ip/csrng/rtl/csrng_core.sv
As discussed previously in the Sec WG, this resolves #16564.
> [csrng, rtl] Remove some unneeded I/O muxes

- hw/ip/spi_device/doc/programmers_guide.md
> [spi_device/doc] Update wording and add note regarding limitation

- hw/ip/clkmgr/doc/theory_of_operation.md
- hw/ip/rstmgr/doc/theory_of_operation.md
Add some more info about clock gated / reset indications output from the `clkmgr` and `rstmgr`.
> [clkmgr/rstmgr/doc] Add description of LPG output signals

- hw/ip/adc_ctrl/data/adc_ctrl_testplan.hjson
- hw/ip/adc_ctrl/doc/theory_of_operation.md
- hw/ip/adc_ctrl/dv/adc_ctrl_sim_cfg.hjson
- hw/ip/adc_ctrl/dv/env/adc_ctrl_scoreboard.sv
- hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_base_vseq.sv
- TODO clean up
- Add oneshot mode to 'theory of operation'
> [adc_ctrl,dv] clean up TODO and update doc.

- sw/device/lib/dif/dif_spi_host.c
- sw/device/lib/dif/dif_spi_host_unittest.cc
- sw/device/lib/testing/BUILD
- sw/device/lib/testing/spi_host_testutils.c
- sw/device/lib/testing/spi_host_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/spi_host_irq_test.c
This PR adds coverage for the events:
- SpiHostEvtRxWm
- SpiHostEvtRxFull
- SpiHostEvtTxWm
- SpiHostEvtTxEmpty
Fix https://github.com/lowRISC/opentitan/issues/18034
> [Spi host] Increment irq test

- sw/device/lib/testing/clkmgr_testutils.c
- sw/device/tests/ast_clk_outs_test.c
Allow a 3% cycle count variability in the various clocks, per the AST specification. The settings were too tight, which is okay for open source testing, but fail when using more accurate AST models.
The AON clock is also subject to 3% variability, so the effective variability is set to 5%i, plus an extra cycle for CDC synchronizers.
Fixes #18037
> [top-level,clkmgr] Allow higher clock counts variability

- hw/top_earlgrey/ip/ast/doc/ast_regs.html
- hw/top_earlgrey/ip/ast/rtl/adc.sv
- hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv
Minor fixes according to @msfschaffner  comments on https://github.com/lowRISC/opentitan/pull/17967#pullrequestreview-1394739872
> [ast] removing redundant assertion and comment

- sw/device/lib/crypto/drivers/entropy.h
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/lib/provisioning.c
- sw/device/silicon_creator/manuf/lib/provisioning.h
This generates and provisions the RMA unlock token. It does not attempt to export it yet. That will be done separately in #18127.
> [manuf] provision the RMA unlock token

- hw/ip/adc_ctrl/data/adc_ctrl_testplan.hjson
Address issue #17359.
Reviewed requirement and update covergroup name.
> [adc_ctrl,dv] rename covergroup

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/doc/programmers_guide.md
- hw/ip/entropy_src/dv/env/entropy_src_dut_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_env.core
- hw/ip/entropy_src/rtl/entropy_src_core.sv
- hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
- hw/ip/entropy_src/rtl/entropy_src_pkg.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
This PR contains two commits to resolve remaining TODOs in the RTL (for details see commit messages) as well as a third commit which is a minor drive-by cleanup.  This PR is required for D2.5 sign-off.
> [entropy_src] Solve remaining TODOs in RTL code

- hw/ip/prim/dv/prim_alert/prim_alert_sim_cfg.hjson
- hw/ip/prim/rtl/prim_alert_sender.sv
Add an extra cycle to some assertions due to CDC.
Fixes #18108
> [dv/prim_alert] Enable CDC instrumentation

- sw/device/examples/hello_usbdev/hello_usbdev.c
- sw/device/lib/testing/usb_testutils.c
- sw/device/lib/testing/usb_testutils.h
- sw/device/lib/testing/usb_testutils_controlep.c
- sw/device/lib/testing/usb_testutils_controlep.h
- sw/device/lib/testing/usb_testutils_simpleserial.c
- sw/device/lib/testing/usb_testutils_simpleserial.h
- sw/device/lib/testing/usb_testutils_streams.c
- sw/device/lib/testing/usb_testutils_streams.h
- sw/device/tests/usbdev_stream_test.c
- sw/device/tests/usbdev_test.c
Fix https://github.com/lowRISC/opentitan/issues/17550
> Usb testutils refactor

- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/lc_ctrl/dv/tb.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_kmac_if.sv
See https://github.com/lowRISC/opentitan/issues/18201#issuecomment-1524669364 for context.
> [lc_ctrl] SVA fix in kmac interface 

- hw/ip/pwrmgr/dv/pwrmgr_sim.core
> [dv/pwrmgr] Remove last TODO

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
Adjust test timeout for closedsource run.
> [chip,dv] extend flash_ctrl_ops timeout

- hw/ip/rstmgr/dv/rstmgr_sim.core
- hw/top_earlgrey/lint/top_earlgrey_dv_lint_cfgs.hjson
> [dv/rstmgr] Address TODO about lint configuration

- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv
As discussed in issue #18201, we decided to disable these three assertions when cdc enabled and in jtag mode.
Fix #18201
> [dv/lc] fix cdc assertion error

- azure-pipelines.yml
This reverts commit be6a60df1c8fc60ab500a4d7b67ee489f5fb9dfb.
> Revert "[ci] Switch FPGA builds to GCP"

- sw/otbn/crypto/rsa_keygen.s
This routine is used to compute the private exponent, d. It's passing a local test with a random modulus, but this PR was big enough that I'll merge the test separately.
> [crypto] Add specialized modular inversion for RSA key generation.

- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/mod.rs
- sw/host/tests/chip/spi_passthru/src/main.rs
1. Test dual and quad SPI reads in the spi_passthru test.
> [spi_passthru] Test dual and quad SPI reads 

- util/reggen/gen_tock.py
Tock requires that if there are gaps between registers, it should be marked in a `register_structs!` declaration by `_reserved` fields.
See: https://github.com/tock/tock/tree/master/libraries/tock-register-interface
> [util] Explicitly mark gaps in register addresses

- hw/ip/i2c/dv/env/seq_lib/i2c_host_perf_vseq.sv
- In the sequence `i2c_rx_tx_vseq`, timing parameters are randomized for every transaction. Disable this randomization to fix some of the test failures
- Modify the metric for comparison to scl_period instead as it is simpler to calculate and observable in waves as well
This PR fixes https://github.com/lowRISC/opentitan/issues/18113
> [hw,i2c,dv] Disable rerandomization of timing parameters

- hw/ip/spi_host/doc/theory_of_operation.md
Align ordering of polarity and phase with rest of sentence
> [spi_host,doc] Minor cleanup

- hw/ip/lc_ctrl/data/lc_ctrl.hjson
- hw/ip/lc_ctrl/rtl/lc_ctrl.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_reg_top.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_signal_decode.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_state_decode.sv
- hw/top_earlgrey/dv/env/chip_env_pkg.sv
This makes testing, debugging and bringup more straightforward.
TBD whether we can absorb the change (I need to talk to @cindychip RE DV impact).
> [lc_ctrl] Add ext_clk_switched CSR for debuggability 

- sw/host/opentitanlib/src/transport/hyperdebug/dfu.rs
The Ti50 team plans a test lab, with hands-off HyperDebug devices connected to OpenTitan as well as previous generation security chips.
As the first thing, before running a test suite, our script currently runs: `opentitantool --interface hyperdebug transport update-firmware`, which ensures that the firmware version of the debugger matches the current version of opentitantool.  (opentitantool will only rarely be updated, but it is cheap to perform the `update-firmware` as it skips if the USB version string of HyperDebug already matches.)
We have become aware of a possible error case, if the update process is interrupted, then HyperDebug will remain in the DFU bootloader mode, meaning that it presents itself with alternative USB VID:DID, resulting in `--interface hyperdebug` not …
> [opentitantool] Recovery from failed HyperDebug firmware update

- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_callback_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_legacy_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- Add more hook to update memory preload
- Add option to exclude info2 partition
> [flash_ctrl,dv] Add closed hook part2

- sw/device/lib/dif/dif_i2c.c
- sw/device/lib/testing/i2c_testutils.c
- sw/device/lib/testing/i2c_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/i2c_host_power_monitor_test.c
- sw/device/tests/power_virus_systemtest.c
- sw/device/tests/sim_dv/i2c_device_tx_rx_test.c
- sw/device/tests/sim_dv/i2c_host_tx_rx_test.c
Add an i2c communication test with a power monitor device.
> [I2c, test] Power monitor

- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
The cov object is only initialized is cfg.en_cov.
> [dv/entropy_src] Fix coverage for VCS

- hw/ip/pwrmgr/rtl/pwrmgr.sv
This assertion needs to handle the case when an escalation reset request is cancelled, which is only okay when the fast fsm is inactive.
> [dv/pwrmgr] Fix PwrmgrSecCmEscToSlowResetReq_A

- sw/device/tests/rv_core_ibex_rnd_test.c
This test was doing a single attempt of cases where operations should happen in quick succession. It is more reliable to attempt it multiple times and check at least one attempt fails as expected.
> [top-level,ibex_rnd] Harden rv_core_ibex_rnt test

- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
This PR removes a todo to icebox.
> [dv/kyemgr] Remove a todo to icebox

- util/generate_compilation_db.py
**Audit results from commit 0a7a2415abd7193275300474c678ded065529344: https://gist.github.com/dmcardle/b0a11cbce883d846d72e08f8ff9c5d81**
Now, we can audit device CC flags with the following command:
util/generate_compilation_db.py \
--audit_device_cc_flags \
--target //sw/device/... \
--out cc_flags_audit_compile_commands.json
This new mode restricts the output to source files that are missing required flags. Each object in the emitted JSON file contains a "missing_cc_flags" key that contains exactly which keys are missing.
For example, here's one of the results, with some arguments deleted for clarity:
{
"directory": "/home/dan/REPOS/opentitan/bazel-opentitan",
"arguments": [
"external/crt/toolchains/lowrisc_rv32imcb/wrappers/clang",
"--target=riscv32",
... …
> [util] Add audit feature to compilation DB generator

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
spi-flash needs more time to complete write.
> [chip,dv] relax timeout regarding closed source

- sw/device/lib/crypto/drivers/otbn.h
- sw/device/lib/crypto/impl/sha2/BUILD
- sw/device/lib/crypto/impl/sha2/sha512.c
- sw/device/lib/crypto/impl/sha2/sha512.h
- sw/otbn/crypto/BUILD
- sw/otbn/crypto/run_sha512.s
- sw/otbn/crypto/sha512.s
The basic core here will work for SHA-384 as well, just with different initial values.
It's passing local tests but I'll merge those in a separate PR for diff-size reasons.
> [crypto] Add a C interface for SHA-512.

- sw/device/tests/rstmgr_cpu_info_test.c
Allow cases where the current pc is not updated due to pipe stalls.
> [top_level, tests] Fix chip_sw_rstmgr_cpu_info test

- hw/ip/clkmgr/dv/env/clkmgr_if.sv
- hw/ip/clkmgr/dv/env/clkmgr_scoreboard.sv
Remove TODOs to collect coverage on error codes, since that is already done and their coverage is at 100%.
Changed a cleanup TODO to ICEBOX issue #18379.
Fixes #17907
> [dv/clkmgr] Finish M2.5 pending items

- util/topgen.py
Replaces entropy_buffer_generator in /util/topgen.py with strong_random.unsecure_generate_from_seed toimprove consistency with `gen-lc-state-enc.py` and `gen-otp-mmap.py`
Currently, entropy file is generted from seed using the ebg, a strong_random buffer is loaded from the file and in the end the file is deleted. This change uses the new function `strong_random.unsecure_generate_from_seed()` to directly generate entropy buffer without making additional files.
> [util] Modify topgen entropy buffer generation

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_all_escalation_resets_vseq.sv
- sw/device/tests/sim_dv/all_escalation_resets_test.c
> [dv,chip] Test software fatal alert in chip_sw_all_escalation_resets

- sw/host/tests/manuf/provisioning/src/main.rs
The provisioning_functest performs an LC transition to check the provisioned RMA unlock token is correct. The checks that the RMA transitioned happened successfully were incorrect.
> [manuf] fix LC state check in provisioning_functest

- sw/device/lib/testing/otp_ctrl_testutils.h
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/lib/idle_functest.c
- sw/device/silicon_creator/manuf/lib/sram_exec_test.c
- sw/host/tests/manuf/manuf_cp_ast_test_execution/BUILD
- sw/host/tests/manuf/manuf_cp_ast_test_execution/src/main.rs
Resolves #17388. the test is not complete at the moment due to some unsolved problem when running the OTP code from SRAM, it seems to mess up with the jtag connection, I don't know why yet.
> [manufacturing] manuf_cp_ast_test_execution

- sw/device/lib/testing/test_framework/check.h
Print status in hex format to be able to be able to pipe it through the `u_sim_sram_if` interface, otherwise the DV log will only print the %r preprocessor specifier, which is not very helpful.
> [sw/test] Print status_t in hex format in DV

- sw/host/hsmtool/BUILD
- sw/host/hsmtool/src/commands/mod.rs
- sw/host/hsmtool/src/commands/object/destroy.rs
- sw/host/hsmtool/src/commands/object/list.rs
- sw/host/hsmtool/src/commands/object/mod.rs
- sw/host/hsmtool/src/commands/object/show.rs
- sw/host/hsmtool/src/commands/object/update.rs
Add commands to manipulate objects:
- list
- show
- destroy
- update
> [hsmtool] Object manipulation commands 

- sw/device/examples/hello_world/hello_world.c
Update leftover comment and gpio output enable control from https://github.com/lowRISC/opentitan/commit/ae9a6bae
> [sw/hello_world] Fix LED GPIO control

- hw/ip/spi_host/data/spi_host_testplan.hjson
- hw/ip/spi_host/dv/cov/spi_host_cov_if.sv
- hw/ip/spi_host/dv/spi_host_sim_cfg.hjson
This PR contributes to verification sign-off for M2.5.
Closes: #18366
> [spi_host,dv] Resolve TODOs

- hw/ip/i2c/dv/README.md
- hw/ip/i2c/dv/env/i2c_env_pkg.sv
Updated I2C DV documentation based on review in preparation for V2.
Made a couple of clean-ups along the way.
Contributes to: https://github.com/lowRISC/opentitan/issues/17890
> [i2c,doc] DV documentation review

- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_disable_rom_integrity_check_vseq.sv
> [dv/pwrmgr] Increase coverage of rom_active_blockers

- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_volatile_unlock_smoke_vseq.sv
- hw/ip/lc_ctrl/dv/tb.sv
1). move some todo to icebox for future release
2). check lc_cnt and lc_state for successful lc volatile unlock
transition.
> [dv/lc] remove todos

- sw/device/lib/ujson/rust/roundtrip_test.rs
> [sw/device] Fix flaky ujson roundtrip_test

- sw/host/tests/manuf/manuf_cp_ast_test_execution/src/main.rs
The test programs and verifies the OTP in the SRAM program. To make the test more robust, also check the content of the OTP via JTAG directly.
> [manufacturing] Verify DEVICE ID in manuf_cp_ast_test_execution

- rules/scripts/gdb_test_coordinator.py
A previous commit introduce a one second delay between the start of the console, and the start of OpenOCD, to prevent interference when opentitantool reconfigures GPIOs as part of the init when starting the console. This commit makes this fix more robust by replacing the fixed delay with a proper sync. We wait until opentitantool prints a specific message indicating that it is ready. This message occurs after the GPIO reconfiguration which ensures proper synchronization.
> [gdb coordinator] Fix race condition between console and OpenOCD

- python-requirements.txt
- util/py/BUILD
- util/py/__init__.py
- util/py/packages/BUILD
- util/py/packages/__init__.py
- util/py/packages/impl/BUILD
- util/py/packages/impl/__init__.py
- util/py/packages/impl/object_size/BUILD
- util/py/packages/impl/object_size/__init__.py
- util/py/packages/impl/object_size/elf.py
- util/py/packages/impl/object_size/memory.py
- util/py/packages/impl/object_size/report.py
- util/py/packages/impl/object_size/types.py
- util/py/packages/lib/BUILD
- util/py/packages/lib/__init__.py
- util/py/packages/lib/bazel.py
- util/py/packages/lib/bazel_test.py
- util/py/packages/lib/ot_logging.py
- util/py/packages/lib/ot_logging_test.py
- util/py/packages/lib/run.py
- util/py/packages/lib/run_test.py
- util/py/packages/lib/wrapper.py
- util/py/packages/lib/wrapper_test.py
- util/py/scripts/BUILD
- util/py/scripts/__init__.py
- util/py/scripts/object_size.py
```bash
$ python3 -m util.py.scripts.object_size --configs riscv32 //sw/device/silicon_creator/rom:rom_with_fake_keys_fpga_cw310.elf
```
> [py/scripts] Add size_script.py

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_ctrl_scrap_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_testunlocks_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_vseq.sv
Inrease timeout and switch to external clock
> [chip,dv] closed source lc_ctrl test cleanup

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_ctrl_scrap_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_ctrl_transition_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
Initial chip level lc test cleanup.
There will be more cleanup coming in separate PR.
> [chip,dv] Add chip_sw_lc_base_vseq

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_core_ibex_lockstep_glitch_vseq.sv
Previously the test only checked the ibex top-level outputs signalled the appropriate alert. This adds a check to ensure the alert is also signalled from the rv_core_ibex ensuring the ibex alert is correctly signalled to the alert_handler.
Noticed we weren't checking this when reviewing what we might need for https://github.com/lowRISC/opentitan/issues/16838 and felt it was worth adding for M2.5.1.
> [dv,chip] Check rv_core_ibex top-level alerts in lockstep test

- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip/flash_ctrl/dv/tests/flash_ctrl_base_test.sv
Hi,
This PR add option to shorten the RMA entry process for timing purposes.
Thanks!
> [flash/dv] Add small RMA also for IP level

- sw/host/opentitanlib/src/tpm/driver.rs
- sw/host/opentitanlib/src/tpm/status.rs
- sw/host/tpm2_test_server/src/main.rs
[tpm2_test_server] Add parameter for I2C address.
[tpm2_test_server] Support autoselecting ports.
> [opentitanlib] Implement TPM driver for I2C

- sw/device/lib/dif/dif_spi_host.c
- sw/device/lib/dif/dif_spi_host.h
- sw/device/lib/dif/dif_spi_host_unittest.cc
- sw/device/tests/spi_host_irq_test.c
This PR adds a test checking the cmd busy error irq.
> Spi irq error test

- rules/scripts/bitstreams_workspace.py
Prior to this commit, `rules/scripts/bitstream_workspace.py` would always try to load `latest.txt` from the bitstream cache -- and fail if it does not exist -- even if the user requests a specific bitstream by Git hash rather than the 'latest' bitstream.  This forced users to have a dummy `latest.txt` even if they were not using the 'latest' functionality, in order to be able to use `bitstream_workspace.py` at all.
This commit fixes this by changing `bitstream_workspace.py` to load `latest.txt` from the bitstream cache only if the 'latest' bitstream is desired.
> [rules/bitstreams_workspace] Make `latest.txt` optional

- doc/project_governance/checklist/sw_checklist.md.tpl
- util/uvmdvgen/checklist.md.tpl
In the existing documents that were derived from this template, these links seem to have been changed/fixed in
aef0a667f7c4b2dcebe09af35ae8a693d277c496 (PR #17323).  This commit makes the same changes in the template.
> [governance] Fix links in HW and SW checklist templates

- sw/device/silicon_creator/rom/rom_epmp_init.S
- sw/device/silicon_creator/rom/rom_start.S
> [sw/silicon_creator] Address issues identified during rom_start.S review

- hw/top_earlgrey/dv/env/seq_lib/chip_tap_straps_vseq.sv
Updating tap straps sequence with the following:
Release DFT straps after they are sampled.
Remove illegal DFT values.
> [dv, straps] Release DFT straps and remove illegal values

- python-requirements.txt
- util/coverage/BUILD
- util/coverage/combined_report.py
- util/coverage/common.py
- util/coverage/common_test.py
- util/coverage/coverage.py
- util/coverage/coverage_test.py
- util/fpga/splice_rom.sh
- util/prep-bazel-airgapped-build.sh
- util/sh/lib/called_from.sh
- util/sh/lib/log.sh
I've also updated the [dashboard](https://storage.googleapis.com/sw-coverage/index.html) to display combined coverage reports. These reports include links to functional and unit test coverage reports:
> Combined SW Coverage Report

- hw/top_earlgrey/data/pins_cw310.xdc
- sw/device/examples/hello_usbdev/hello_usbdev.c
- sw/device/examples/hello_world/hello_world.c
~~The only changed pins are IOB6-9 from USRDIP0-3 to PMOD2_IO5-8.~~
IOB7 : V7(USRDIP1) -> N23(PMOD2_IO5)
IOB8 : V8(USRDIP2) -> N26(PMOD2_IO6)
IOB9 : W9(USRDIP3) -> V7(USRDIP1)
IOB10 : V9(USRDIP4) -> V8(USRDIP2)
IOB11 : W8(USRDIP5) -> M20(PMOD2_IO7)
IOB12 : W10(USRDIP6) -> P25(PMOD2_IO8)
IOR5 : V11(USRDIP7) -> W9(USRDIP3)
> [cw310] pins_cw310.xdc changes for BoB

- sw/host/opentitanlib/src/transport/hyperdebug/dfu.rs
The special flag `--interface hyperdebug_dfu` allows opentitantool to recognize a HyperDebug device whether it is in its normal mode or DFU bootloader mode.  This is particularly useful when requesting firmware update, as doing so can recover from previous interrupted update attempts.
However, the logic to skip updating, in case the device is already running the newest firmware version had been omitted from the `hyperdebug_dfu` path, probably because the first incarnation of that mode recognized only a board already in DFU mode, and hence was special purpose for developers or first-time users.
Now that `hyperdebug_dfu` should be used as the default for scripted updating, we want it to recognize the common case, in which updating can be skipped.  This PR adds logic for that.
> [opentitantool] Avoid no-op HyperDebug firmware updates

- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/tb/tb.sv
Adding some more updates required for GLS simulation.
> [dv,chip] Compilation required changes for gate-level

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_volatile_raw_unlock_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_testunlocks_vseq.sv
> [chip,dv] prevent time 0 jtag polling

- sw/device/silicon_creator/rom/rom.c
This PR adds a check for the rom_ext entry point before exiting ROM.
Additionally, the ePMP state check is moved into `rom_pre_boot_check`
> [rom] Check rom_ext entry point before jump

- .bazelrc
- sw/device/lib/base/status_report_unittest_c.c
- sw/device/lib/base/status_report_unittest_c.h
- sw/device/lib/crypto/drivers/otbn.c
- sw/device/lib/crypto/impl/status.h
- sw/device/lib/testing/hmac_testutils.h
- sw/device/lib/testing/usb_testutils_controlep.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/kmac_unittest.cc
- sw/device/silicon_creator/manuf/lib/sram_exec_test.c
- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom/rom_epmp.c
- sw/device/tests/i2c_host_clock_stretching_test.c
- sw/device/tests/i2c_host_hdc1080_humidity_temp_test.c
- sw/device/tests/spi_host_smoketest.c
- third_party/coremark/BUILD.coremark.bazel
- third_party/coremark/top_earlgrey/BUILD
> [bazel] Enable C warning flags in .bazelrc

- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
Prior to this commit, Entropy Source's scoreboard did not check the value read from the `repcnt_hi_watermarks` (i.e., bit repetition count watermarks) and `repcnts_hi_watermarks` (i.e., symbol repetition count watermarks) registers.
This commit models the internal repetition counters as well as their propagation to the watermark register fields (which are separate for FIPS and bypass mode) in the scoreboard and enables the check of the watermark registers against the modeled value.
> [entropy_src/dv] Predict value of repcnt watermarks

- hw/ip/entropy_src/doc/programmers_guide.md
- hw/ip/entropy_src/dv/README.md
- hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson
- hw/ip/entropy_src/dv/env/entropy_src_dut_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
- hw/ip/entropy_src/dv/tests/entropy_src_fw_ov_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_rng_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_smoke_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_stress_all_test.sv
This PR separates TODOs that are relevant for M2.5 from those that are not relevant. It resolves the former and ensures the latter are tracked in issues.
This resolves #18220.
> [entropy_src/dv] Resolve or update TODOs relevant for M2.5 

- hw/ip/lc_ctrl/dv/env/lc_ctrl_env.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_jtag_priority_vseq.sv
- hw/ip/lc_ctrl/dv/lc_ctrl_sim_cfg.hjson
tb clean up after enabling cdc instrumentation
> [lc_ctrl,dv] tb update with cdc_inst enable

- hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv
Move `z3_wakeup_o` from `check_z3_wkup_nonblocking` to the body of the sequence and disable the forked process at the end of the sequence. This will fix the `sysrst_ctrl_stress_all` errors related to `z3_wakeup_o` check
> [hw,sysrst_ctrl,dv] Disable z3_wakeup_o check after end of sequence

- hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_common_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_idlecsbactive_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_overflow_underflow_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_performance_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_smoke_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_spien_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_status_stall_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv
- hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
~~[IGNORE FIRST 4 COMMITS, WILL BE REBASED AWAY WHEN #18850 IS MERGED]~~ 
Now rebased.
> [spi_host,dv,cleanup] Cleanup and add comments to dv code.

- hw/ip/aes/data/aes_testplan.hjson
- hw/ip/aes/dv/cov/aes_cov_if.sv
- hw/ip/aes/dv/env/seq_lib/aes_reseed_vseq.sv
- hw/ip/aes/dv/tests/aes_reseed_test.sv
- hw/ip/aes/dv/tests/aes_stress_test.sv
For details see commit messages.
This is related to #18425.
> [aes, dv] Resolve first set of TODOs for V2.5

- hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
- hw/ip/pinmux/rtl/pinmux.sv
- hw/ip/pinmux/rtl/pinmux_strap_sampling.sv
This takes care of the last 3 CEX in the pinmux FPV checks.
> [pinmux/fpv] Additional FPV fixes

- hw/top_earlgrey/doc/design/README.md
Keep in sync with #17484 and #17346
> [earlgrey] document ROM key slots for earlgrey

- hw/top_earlgrey/doc/design/README.md
Fixes the broken link introduced in https://github.com/lowRISC/opentitan/pull/17474 .
@jwnrt suggested using [merge queues](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue) to avoid this happening for new CI checks in the future (or require a rebase before merging a PR).
> [doc] broken link fix

- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/lib/sram_program.ld
- sw/device/silicon_creator/manuf/lib/sram_start.S
- sw/device/silicon_creator/manuf/lib/sram_start.h
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/host/opentitanlib/bindgen/BUILD
- sw/host/opentitanlib/bindgen/lib.rs
- sw/host/opentitanlib/src/test_utils/load_sram_program.rs
- sw/host/tests/chip/jtag/src/sram_load.rs
- sw/host/tests/manuf/manuf_cp_device_info_flash_wr/src/main.rs
See issue #18635 and original PR #18844.
Create a crt for SRAM programs to setup the stack pointer, global pointer and clear BSS.
> [manuf] Add SRAM program CRT and update infrastructure

- hw/ip/sram_ctrl/data/sram_ctrl_testplan.hjson
- hw/ip/sram_ctrl/dv/cov/sram_ctrl_unr_excl.el
- hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
- hw/ip/sram_ctrl/dv/sram_ctrl_sim.core
- hw/top_earlgrey/lint/top_earlgrey_dv_lint_cfgs.hjson
> [sram_ctrl] Resolve misc TODOs

- ci/azure-pipelines-nightly.yml
- sw/device/tests/i2c_host_accelerometer_test.c
- sw/device/tests/i2c_host_compass_test.c
- sw/device/tests/i2c_host_eeprom_test.c
The job was mistakenly involking bazel instead of bazelisk.sh which generates the error:
https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=119328&view=logs&j=ac8a02a7-2778-53b1-c82e-cd21a7d698f0&t=d325bfd8-fd6c-518b-a699-bb4f07334985
> [ci] Fix the bob job

- hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv
- hw/ip/spi_host/dv/env/spi_host_env_cov.sv
- hw/ip/spi_host/dv/spi_host_sim_cfg.hjson
~~IGNORE ALL BUT LAST COMMIT, WILL BE REBASED AWAY
(please do not merge until rebased)~~
---
> [spi_host,dv] Capture outstanding TODOs against tracking issue #18886

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/doc/checklist.md
- hw/ip/i2c/rtl/i2c_fsm.sv
This PR is here to perform the V2 sign-off for I2C. It completes the V2 checklist issue: https://github.com/lowRISC/opentitan/issues/18741
Closes: #18741
> [i2c] V2 checklist

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_csrng_lc_hw_debug_en_vseq.sv
> [chip,dv] increase time out for chip_sw_csrng_lc_hw_debug_en_vseq

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_flash_host_gnt_err_inj_vseq.sv
> [chip,dv] increase test time out for flash_hsot_gnt_err_inj_seq

- hw/ip/aes/dv/env/seq_lib/aes_alert_reset_vseq.sv
- hw/ip/aes/dv/sva/aes_bind.sv
- hw/ip/aes/dv/sva/aes_masking_reseed_if.sv
- hw/ip/aes/dv/sva/aes_reseed_if.sv
- hw/ip/aes/dv/tb/tb.sv
This PR contains two more commits to resolve tool warnings for AES DV. For details, see commit messages.
This is related to #18428.
> [aes, dv] Resolve tool warnings

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
- hw/ip/rom_ctrl/dv/rom_ctrl_sim_cfg.hjson
> [rom_ctrl/dv] Remove stale TODOs

- hw/ip/aes/dv/aes_base_sim_cfg.hjson
- hw/ip/aes/dv/env/aes_scoreboard.sv
This is required for V2.5. This resolves #18425.
> [aes, dv] Resolve or document remaining TODOs

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_flash_rma_unlocked_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_vseq.sv
- sw/device/tests/sim_dv/flash_rma_unlocked_test.c
short rma mode has beed added to expedite
closed source regression turn around time.
Update follow tests to support the feature.
- chip_sw_lc_walkthrough_rma
- chip_sw_flash_rma_unlocked
> [chip,dv] closed source short rma support

- hw/dv/tools/dvsim/sim.mk
Bazel cqueries were failing in the airgapped environments due to to missing arguments in the dvsim `sim.mk`. This was causing simulation failures.
> [bazel,dvsim] fix airgapped cquery bug

- sw/device/tests/BUILD
- sw/device/tests/i2c_host_irq_test.c
This PR add tests for all the I2C host IRQs.
> [I2c] Test the host IRQs

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
- hw/ip/rom_ctrl/dv/rom_ctrl_sim_cfg.hjson
- hw/ip/rom_ctrl/rom_ctrl.core
- hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv
- hw/top_earlgrey/formal/top_earlgrey_fpv_sec_cm_cfgs.hjson
> [rom_ctrl/dv] Improve FSM coverage by injecting more faults

- sw/device/tests/sim_dv/ast_usb_clk_calib.c
This test set calibration tollerance range too tight (+/- 2 cycles). 
Given both AON / USB clock can be varied within (+/- 3%), 
the test need larger calibration tollerance range. Modified the range based on other clock calibrations. 
Plus, ast finishes usb clock calibration by the time ast_init_done. 
If the usb is enabled after `ast_init_done` event, which is the case in the current test, 
the test cannot see the uncalibrated clock. 
Therefore, remove uncalibrated check from the test.
> [chip,dv] test adjustment with cs env - ast_usb_clk_calib

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_raw_unlock_vseq.sv
`apply_reset` turned off bypass_enable.
After reset, test needs to re-enable bypass clock to supply external clock.
> [chip,dv] Adjust reset and external clock location for rom_raw_unlock

- hw/top_earlgrey/dv/env/chip_env_cfg.sv
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_otp_ctrl_vendor_test_csr_access_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_power_virus_vseq.sv
Following closed source test failures are fixed
- chip_sw_otp_ctrl_vendor_test_csr_access
- chip_sw_power_virus
> [earlgrey_es, chip,dv] closed source regression fix

- sw/device/lib/crypto/impl/rsa/BUILD
- sw/device/lib/crypto/impl/rsa/rsa_modexp.c
- sw/device/lib/crypto/impl/rsa/rsa_modexp.h
This interface can be used for both signatures and encryption.
> [crypto] Add C interface for RSA modular exponentiation.

- hw/dv/tools/dvsim/vcs.hjson
Cherry-pick from master from #19111.
> [dv,vcs] add an option to override debug_region vcs flag

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/chip_env_cfg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/tb/tb.sv
- hw/top_earlgrey/dv/tests/chip_base_test.sv
Cherry-picks  #19084 onto `earlgrey_es`.
> [dv] add plusarg to skip ROM backdoor load

- hw/ip/tlul/generic_dv/env/seq_lib/xbar_random_vseq.sv
short_xbar_test manually assign num_trans value.
So disable num_trans_c
> [chip,dv] update constraint with short_xbar_test

- sw/otbn/crypto/p256.s
These changes are done regarding to outcomes of the COCO-Alma tool usage. Moreover, many more rules are put in the OTBN Security Guidance Document. Please see it before developing algorithms on OTBN which handle secret data.
If we don't have these changes, the tool reports there are transient leakage and we may see leakage on the final product even if we don't see a leakage on FPGA experiments.
We are also seeing a stable leakage on the MSB of the intermediate values. We acknowledge that and since the algorithm runs with 64-bit excess randomness, we don't expect that to be possible to use that leakage and retrieve secret values. We also verified that the stable leakage disappeared after running the routine on 320-bit instead of 321-bit.
> [otbn, pre_sca] Modify boolean_to_arithmetic routine against SCA

- sw/device/tests/BUILD
- sw/device/tests/spi_host_gigadevice256Mb_flash_test.c
This commit adds a test for a gigadevice NOR flash with 256Mb.
> [spi_host, flash] Add test for a gigadevice flash

- hw/ip/aes/dv/cov/aes_cov_if.sv
- hw/ip/aes/dv/env/aes_env_cfg.sv
- hw/ip/aes/dv/env/aes_env_pkg.sv
- hw/ip/aes/dv/env/aes_message_item.sv
- hw/ip/aes/dv/env/aes_scoreboard.sv
- hw/ip/aes/dv/env/seq_lib/aes_alert_reset_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_readability_vseq.sv
- hw/ip/aes/dv/tests/aes_config_error_test.sv
This resolves #19039. With these changes I get the same pass rates as on master with function coverage increasing to roughly 98% from previously 92% (masked) and 91% (unmasked).
I recommend reviewing commit by commit.
> [aes, dv] Improve functional coverage

- hw/ip/prim/rtl/prim_subreg.sv
Implement fix as proposed in #5416.
Fix #5416
> [prim_subreg] Fix RC access corner case

- sw/device/tests/BUILD
- sw/device/tests/spi_host_micron512Mb_flash_test.c
This PR:
The new test run on the FPGA for a Micron 512 Mb flash on the BoB.
> [spi_host, test] Add a micron flash test

- hw/dv/sv/sec_cm/prim_count_if.sv
- hw/dv/sv/sec_cm/prim_double_lfsr_if.sv
- hw/dv/sv/sec_cm/prim_onehot_check_if.sv
- hw/dv/sv/sec_cm/prim_sparse_fsm_flop_if.sv
- hw/dv/sv/uart_agent/uart_logger.sv
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/flash_ctrl_host_gnt_fault_if.sv
- hw/top_earlgrey/dv/env/rstmgr_cnsty_fault_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_prim_tl_access_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_csrng_lc_hw_debug_en_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_raw_unlock_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_otp_ctrl_vendor_test_csr_access_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_uart_tx_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/sim_dv/all_escalation_resets_test.c
- sw/device/tests/sim_dv/otp_ctrl_vendor_test_csr_access_test.c
Following test failures are fixed
- chip_sw_coremark
- rom_raw_unlock
- chip_prim_tl_access
- chip_sw_flash_crash_alert
- chip_sw_otp_ctrl_vendor_test_csr_access
- chip_sw_csrng_lc_hw_debug_en_test
> [earlgrey_es,chip,dv] closed source regression fix ver 121 

- hw/top_earlgrey/dv/env/ast_supply_if.sv
Move forcing point out of regulator.
Change power glitch model to be higher frequency.
And replace force to 1 with `release` to detect reset asserted by OT.
> [chip,dv] update power glitch modeling align with the close source AST

- hw/ip/aes/data/aes_testplan.hjson
- hw/ip/aes/dv/aes_base_sim_cfg.hjson
- hw/ip/aes/dv/env/aes_env.core
- hw/ip/aes/dv/env/aes_env_cfg.sv
- hw/ip/aes/dv/env/aes_scoreboard.sv
- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_stress_all_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_vseq_list.sv
Please just review the last three commits of this PR. This PR depends on #19205 and #19206.
This resolves #19025.
> [aes, dv] Enable stress_all(_with_rand_reset) tests

- hw/top_earlgrey/dv/env/ast_supply_if.sv
- hw/top_earlgrey/dv/env/chip_env_cfg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_base_vseq.sv
- hw/top_earlgrey/dv/tests/chip_base_test.sv
- sw/device/tests/otp_ctrl_smoketest.c
Following tests are fixed
- chip_sw_otp_ctrl_smoketest
-  *_power_glitch_reset
Also add early cpu init
> [earlgrey_es,chip,dv] closed source regression fix ver 122

- .github/workflows/pr_lint_review.yml
Workaround https://github.com/curl/curl/issues/11475
> [ci] downgrade curl on CI runner

- hw/top_earlgrey/dv/env/ast_supply_if.sv
Hi,
This PR is putting the release of the main_pok into ifndef GL.
Thanks
> [dv/ast/pok] Put the release of the POK in ast_supply_if under ifndef GL

- sw/host/opentitanlib/src/crypto/rsa.rs
In many places in `crypto/rsa` error messages produced by other crates were previously dropped and replaced with generic errors. To help make errors more clear, include the source error when it's available.
Thank you to @timothytrippel for bringing this to my attention!
> [opentitanlib] Improve rsa error messages

- util/topgen/strong_random.py
Several tests in this file work in the same way: iterate over a list of things and check that a property holds for each element. The existing code collected up a list of booleans and then checked that each was True. With this rewrite, we early-exit with False if anything fails, and return True otherwise.
This should be a minor clean-up, following suggestions of @vrozic when I fixed up some types in this code in 3b92a31.
(Follow-up to #19176)
> Simplify paths in topgen's strong_random

- hw/ip/kmac/dv/env/seq_lib/kmac_edn_timeout_error_vseq.sv
- hw/ip/kmac/rtl/kmac.sv
- hw/ip/kmac/rtl/kmac_entropy.sv
For details, see commit messages.
> [kmac, rtl] Fix issues around EDN timeouts

- signing/logs/2023-06-06.md
- signing/logs/2023-06-07.md
- signing/logs/2023-06-12.md
- signing/logs/README.md
This PR belatedly documents the HSM initialization and key generation process for `earlgrey_a0`.
> [signing] Document the HSM initialization ceremony

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_raw_unlock_vseq.sv
Hi,
This PR is making some required bypass for gate-level.
Can you can please merge it to the earlgrey_es branch once it will be merged in the master?
Thanks!
> [dv/ROM/GL] Small change to rom-raw-unlock test

- hw/dv/sv/cip_lib/cip_base_env.sv
- hw/dv/sv/tl_agent/tl_reg_adapter.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_raw_unlock_vseq.sv
- tlul debug update
- GLS test failure update
> [earlgrey_es,chip,dv] dv cherry pick for earlgrey es

- sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c
Perform a single increment of flash counters, so the chances of attempting a new one before the previous one is pending are restricted to separate interrupt or exception types, which are much easier to control and seem to work very reliably.
Notice this test still has a potential flakiness related to failing error injections: see #19268 for a proposed fix.
Fixes #18489
> [dv,top-level] Fix flakiness of chip_sw_data_integrity_escalation

- ci/scripts/check_bazel_test_suites.py
Cherry picked over to prevent divergence
> [ci] Fix warning/error mix-up in `check_bazel_test_suites.py`

- sw/device/sca/otbn_vertical/ecc256_keygen_serial.c
- sw/device/sca/otbn_vertical/ecc256_keygen_serial.h
- sw/device/sca/otbn_vertical/otbn_vertical_serial.c
Adds batch capture for ECC256 keygen TVLA fixed-vs-random key test.
> [sca] Add batch capture for ECC256 keygen

- hw/top_earlgrey/dv/tb/tb.sv
Hi,
This PR removes a redundant entropy force that has no effect.
Thanks!
> [dv/chip] remove redundant force from tb

- sw/device/lib/crypto/drivers/entropy.c
- sw/device/lib/dif/dif_csrng.c
- sw/device/lib/dif/dif_csrng_shared.h
- sw/device/lib/dif/dif_edn.c
For now: blind commit, as I'm unable to build the master branch on our machine. To be edited...
> Fix typos in CSRNG enumerated values

- hw/dv/sv/alert_esc_agent/alert_esc_agent_cfg.sv
- hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv
- hw/dv/sv/flash_phy_prim_agent/flash_phy_prim_monitor.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
- hw/ip/flash_ctrl/dv/env/flash_otf_read_entry.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_err_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_prog_rma_wipe_err_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_ack_consistency_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_host_grant_err_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_ooo_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_wr_path_intg_vseq.sv
- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwrmgr_deep_sleep_all_wake_ups_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_ctrl_integrity_check_vseq.sv
- hw/top_earlgrey/dv/tb/tb.sv
- sw/device/tests/aon_timer_irq_test.c
- sw/device/tests/power_virus_systemtest.c
- Clean up flash_ctrl block regressions
- Remove obsolete force for GLS
- GLS regfix
> [earlgrey_es,dv] closed source dv cherry pick for ealgrey es

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
> [dv,top_level] Enable CDC instrumentation for top_level tests

- hw/dv/sv/mem_bkdr_util/mem_bkdr_util__sram.sv
- hw/top_earlgrey/dv/env/chip_env_pkg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_data_integrity_vseq.sv
Try injecting ecc errors multiple times until an error is flagged.
Fixes #19268
> [dv/top-level] Harden chip_sw_data_integrity_escalation

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_derr_detect_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_prog_reset_vseq.sv
following tests need scoreboard cleanup during intermittent reset event
> [flash_ctrl,dv] more tb cleanup for reset event

- sw/device/silicon_creator/rom_ext/rom_ext.c
This PR hardens the boot_svc related code in rom_ext.c added in #19286 .
> [sw/silicon_creator] Hardened boot_svc related code in rom_ext.c

- sw/host/opentitanlib/src/transport/ti50emulator/emu.rs
- sw/host/opentitanlib/src/transport/ti50emulator/mod.rs
- sw/host/opentitanlib/src/transport/ti50emulator/uart.rs
Host emulation works by compiling the GSC code into a Linux executable, instead of an image for OpenTitan, and running this executable as a sub-process to `opentitansession`.
The sub-process will create a number of unix pipes, for UARTs and other peripherals, and will use these to communicate with the simulation environment.
Prior to this CL, `opentitantool console` would not capture the first serial console output, because of a race.  The sub-procces would create the unix pipes, tell opentitansession that it was ready, and then immediately proceed to produce output to the unix pipe representing the serial console.  This allowed opentitansession no time to connect to the pipe, and any data sent before a reading process had connected would be lost.
This CL introduces a handshake, such that …
> [opentitantool] Improve UART on ti50 emulation

- sw/host/opentitanlib/src/bootstrap/rescue.rs
Changes in how the GSC binary images were padded revealed a bug in the implementation of the legacy rescue protocol in opentitantool.
This PR introduces two changes.  One is to look at a length field in a section header inside the image, rather than detect the effective length of the binary image in the section based on padding with FF.
The other is relates to the serial protocol.  The size of the blocks transferred via UART is not a multiple of the 128 byte flash page size, meaning that the last block transferred may extend past the end of the image.  If that happens, it is important to send all FF in the bytes "past" the image, to ensure that the GSC bootloader does not attempt to actually flash past the end.
> [opentitantool] Fixes to the GSC rescue bootstrap protocol

- hw/ip/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_cnsty_vseq.sv
This test can trigger fatal alerts while the alert handshake is being performed after a recent POR reset, which causes the outgoing alert to happen past the expected time, making the test flakey. This change delays the error injection until after the alert differential pairs are complementary, indicating the handshake mentioned above has ended.
> [dv/rstmgr] Fix leaf_rst_cnsty test

- azure-pipelines.yml
> [earlgrey_es][ci] Actually build all software in the sw_build job

- hw/ip/flash_ctrl/data/BUILD
- hw/ip/otp_ctrl/data/BUILD
- hw/ip/rom_ctrl/data/BUILD
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/BUILD
- rules/autogen.bzl
- util/BUILD
- util/reggen/gen_tock.py
- util/reggen/ip_block.py
- util/regtool.py
Cherry-pick from `master` onto `earlgrey_es`:
#19341 
#19354
> [earlgrey_es,tock] Update license header in autogenerated files

- sw/device/lib/crypto/impl/BUILD
- sw/device/lib/crypto/impl/rsa.c
- sw/device/lib/crypto/include/rsa.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/rsa_2048_keygen_functest.c
- sw/device/tests/crypto/rsa_2048_signature_functest.c
Implements the final layer of code connecting the core RSA-2048 implementations to the exact crypto library API and updates tests to use the API interface.
> [crypto] Connect RSA-2k operations to the API.

- sw/device/lib/testing/test_framework/ujson_ottf.h
- sw/host/opentitanlib/src/test_utils/rpc.rs
**Merge after https://github.com/lowRISC/opentitan/pull/18914**
This PR adds integrity checks to the response sent by `RESP_OK` and `RESP_ERR`.
Part of https://github.com/lowRISC/opentitan/issues/17496
> [ujson] Add crc checks to `RESP_OK/ERR`

- hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv
Create an associative array indexed by clock containing structs holding per clock relevant info to avoid repetitive case statements.
> [dv/clkmgr] Improve handling of clock measure control CSRs

- hw/ip/rstmgr/data/rstmgr_rst_en_track_sva_if.sv.tpl
- hw/ip/rstmgr/dv/sva/rstmgr_bind.sv
- hw/ip/rstmgr/dv/sva/rstmgr_sva.core
- hw/top_earlgrey/ip/rstmgr/dv/sva/autogen/rstmgr_rst_en_track_sva_if.sv
- hw/top_earlgrey/ip/rstmgr/system_rstmgr_sva.core
- util/topgen.py
> [dv/rstmgr] Add SVA checking rst_en_o track resets_o

- util/container/Dockerfile
- util/container/README.md
> [util/container] Use Verible released for Ubuntu 20.04

- BLOCKFILE
This reverts commit a2e34042128fc48f24c1df92fbb9a3665c5450e0.
> [BLOCKFILE] Re-enable blockfile

- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_derr_detect_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_prog_rma_wipe_err_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_lcmgr_intg_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_ack_consistency_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_prog_reset_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_path_intg_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_evict_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_wr_path_intg_vseq.sv
- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Clean up flash_ctrl block regressions
> [earlgrey_es,dv] flash_ctrl block tb cleanup

- ci/jobs/quick-lint.sh
> [ci] Update shellcheck command in quick-lint.sh

- util/dvsim/FlowCfg.py
- util/dvsim/SimCfg.py
- util/dvsim/results_server.py
There should be no functional change, but the code in `FlowCfg.py` is now hopefully a bit easier to follow. Mainly because I've cheated and put the "interact with GCP" logic into a helper class.
> [dvsim] Minor tidyups to the way things are published

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_busy_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
I have added new test sequence in sequences of RV_DM.
> Rv dm new test cases

- hw/ip/clkmgr/data/clkmgr_testplan.hjson
- hw/ip/clkmgr/dv/clkmgr_sim_cfg.hjson
- hw/ip/clkmgr/dv/env/clkmgr_env.core
- hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv
- hw/ip/clkmgr/dv/env/seq_lib/clkmgr_frequency_vseq.sv
- hw/ip/clkmgr/dv/env/seq_lib/clkmgr_regwen_vseq.sv
- hw/ip/clkmgr/dv/env/seq_lib/clkmgr_vseq_list.sv
This test fills some coverage holes towards V3.
> [dv/clkmgr] Add test for regwen functionality

- sw/host/opentitanlib/src/image/image.rs
- sw/host/opentitanlib/src/transport/dediprog/mod.rs
- sw/host/opentitanlib/src/transport/hyperdebug/dfu.rs
- sw/host/opentitanlib/src/transport/hyperdebug/servo_micro.rs
- sw/host/opentitanlib/src/transport/verilator/transport.rs
- third_party/rust/BUILD
- third_party/rust/deps.bzl
- third_party/rust/repos.bzl
- util/prep-bazel-airgapped-build.sh
Tock is using nightly-2023-07-30
> [rust] Update the rust toolchain for building tock

- hw/ip/flash_ctrl/dv/env/flash_otf_item.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_mid_op_rst_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_wr_path_intg_vseq.sv
- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Following test failures are fixed. See each commit messages for detail
- flash_ctrl_re_evict
- flash_ctrl_hw_rma
- flash_ctrl_wr_intg
- flash_ctrl_mid_op_rst
- flash_ctrl_full_mem_access
> [flash_ctrl,dv] closed source regression fix

- hw/ip/usbdev/dv/env/seq_lib/usbdev_csr_test_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
Verifying register reset behavior and validating proper CSR read/write.
> [usbdev,dv] CSR TEST!

- WORKSPACE
- hw/ip/flash_ctrl/dv/env/flash_otf_item.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_mid_op_rst_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_wr_path_intg_vseq.sv
- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_vseq.sv
- hw/top_earlgrey/formal/conn_csvs/ast_infra.csv
- hw/top_earlgrey/formal/conn_csvs/clkmgr_secure.csv
- hw/top_earlgrey/formal/conn_csvs/rstmgr_resets_o.csv
- rules/hooks_setup.bzl
closed source regression fix
#19487 
#19490 
chip formal fix
#19486 
infra
#19402
> [earlgrey_es] cherry-pick

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_exception_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test verifies the handling of command error when an exception occurs during the execution of the command.
> [RV_DM] Command error exception test

- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/flash_otf_item.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_callback_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv
This is opensource update for closed source tests(error injection tests with redundancy enabled).
Tests will be added to closed source after this PR.
Add `virtual` for method override from cs env.
Add more comments and task for more visibility.
> [flash_ctrl,dv] env update for new closed source tests

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_hart_unavail_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test verifies whether the debugger can read the status of an unavailable
hart.
> [RV_DM,dv] hart_unavail test

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_halt_resume_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test verify that generating command error will set corresponding cmderr bit of abstractcs register to 4.
> [RV_DM]cmderr_halt_resume_test

- doc/security/cryptolib/cryptolib_api.md
Make the tone a little more conversational and change the focus from background information to practical usage.
In #19297 I moved the working cryptolib API document onto a public documentation page. I didn't change any text at the time, to minimize the size of the change. But I think it makes sense to shift the focus of the text a little bit now, since the purpose of a public documentation page (communicate how to use the crypto library) is different from an internal document (to provide background, explain why certain things are included, and agree on what to implement). So I went through the text and made some edits:
- adding additional explanation where I think it is helpful for usage (e.g. explaining how the key structs work, specific security considerations for ECC/RSA)
- shortening …
> [doc] Refocus cryptolib documentation text.

- sw/host/opentitanlib/src/transport/common/uart.rs
`opentitantool console` will attempt to create lock files in /var/lock, such that a conflict with a minicom process accessing the same /dev/ttyUSBn device will be detected.
ChromeOS chroot environment however, for some reason does not allow processes to create files in /var/lock.  Even if it did, it would not offer only limited protection, since a minicom outside the chroot would not "see" the file created by opentitantool inside the chroot.
For this reason, this PR adds code to silently proceed without creating a file in /var/lock, in cases where permissions prevent it. opentitantool will still lock the open file descriptor using `flock()` system call, and that way prevent multiple instances of opentitantool from simultaneously accessing the same device.
> [opentitantool] Tolerate non-writeable /var/lock

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_halted_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_resuming_vseq.sv
Fixing HALTED and RESUMING register issues in halted and resuming test.
> [RV_DM, dv] Updated HALTED and RESUMING test

- doc/security/specs/identities_and_root_keys/README.md
Remove stale details from the specification. A follow up commit will add cross references to the implementation.
> [docs] Update identities and root keys spec

- .github/ISSUE_TEMPLATE/chip-level-test.yml
This commit fixes yaml schema validation issues in the chip-level-test.yml issue template.
> [github] Fix issue template issues.

- hw/dv/sv/alert_esc_agent/alert_monitor.sv
This task expects to see the alert_tx differential signal go high and then low again. This is reasonable enough, but that signal is actually driven in alert_receiver_driver.sv, where it's synchronised with the async clock.
In alert_monitor.sv, we were reading it in a clocking block that is synchronised with the main (possibly slower) clock. It turns out that some seeds cause this short pulse of "on; then off" to be missed, causing the test using alerts to get stuck while it waits for them to initialise.
This commit switches the monitor task to use receiver_cb (which is synchronised to the async clock) instead, ensuring that we don't miss the pulse.
(For an example of a test/seed combo that fails because of this, try: `util/dvsim/dvsim.py hw/ip/usbdev/dv/usbdev_sim_cfg.hjson -i …
> [alert_handler,dv] Tweak clocking block used in wait_alert_init_done

- sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
At present, HyperDebug is using all the USB interfaces supported by the hardware, so it is not possible to directly add a CMSIS-DAP interface for JTAG support,
Instead, in order to prepare for JTAG support, the I2C protocol is going to be modified to be encapsulated in CMSIS-DAP, thereby sharing an USB interface with JTAG.
This CL allows opentitantool to look at HyperDebug USB descriptors, and recognize either the old dedicated I2C interface, or an CMSIS-DAP interface.
When communicating via the CMSIS-DAP protocol, every I2C request must be preceded by a "custom command" byte (0x81), which is referred to as the "encapsulation header" in `i2c.rs`.
Corresponding change to HyperDebug firmware:
https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4852251
> [opentitantool] Recognize CMSIS-DAP HyperDebug USB interface

- SUMMARY.md
- ci/scripts/check-links.sh
- doc/getting_started/unofficial/README.md
- Fixed a broken link introduced after rebase in https://github.com/lowRISC/opentitan/pull/19357
- Added `SUMMARY.md` to the files who's links are checked in CI.
> [doc] Fixed broken link in SUMMARY.md and added it to link checks

- hw/ip/otbn/dv/otbnsim/sim/ext_regs.py
When I added the possibility of double-flopped (external) registers, I split up ExtRegChange and TraceExtRegChange. An ExtRegChange contains the actual change to a register ("Set value to 123"). A TraceExtRegChange contains the ExtRegChange plus the register's actual name (so it now says "Set INSN_CNT to 123").
I messed up the type diagram a bit, though. In particular, I left ExtRegChange as a descendent of Trace which is not right at all! This commit changes things so that it's no longer a subclass. We also change a field name from "trace" to changes, since its value is a list of changes, rather than a list of trace items.
This should cause no functional change.
> [otbn,dv] Make types slightly cleaner in ext_regs.py

- hw/ip/flash_ctrl/data/flash_ctrl.hjson
- hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
Update tpl file to modify flash_ctrl.hjson
> [flash_ctrl,doc] fix format error

- hw/ip/prim/doc/prim_xoshiro256pp.md
Fixing a few typos in XoShiRo256pp documentation.
> [doc] Fixing a few typos in xoshiro PRNG documentation

- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/app/config/structs.rs
- sw/host/opentitanlib/src/app/gpio.rs
- sw/host/opentitanlib/src/app/mod.rs
- sw/host/opentitanlib/src/transport/errors.rs
Introduce GpioPinWrapper to handle optional inversion of GPIO sense.
> [opentitantool] Support inverted GPIO sense

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_dataaddr_rw_access_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test verify rw access of data registers through memory mapped dataaddr registers.
> [RV_DM]Dataaddr_rw_access Test

- hw/ip/pwrmgr/doc/theory_of_operation.md
Make a few simple corrections to the doc.
> [doc/pwrmgr] Improve theory of operation doc

- ci/install-package-dependencies.sh
- python-requirements.in
- python-requirements.txt
> [ci] only use pinned python packages

- hw/ip/rstmgr/data/rstmgr.hjson.tpl
- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
- hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson
This contains 4 commits: the first two create and move the chip_rstmgr_testplan.hjson file, the third creates the rstmgr features from templates, and the last one updates chip_rstmgr_testplan.hjson for sival.
> [sival,rstmgr] Update rstmgr chip testplan for sival

- doc/security/cryptolib/cryptolib_api.md
Also move the "asynchronous operations" section to the end of the document.
This addresses some post-merge feedback from https://github.com/lowRISC/opentitan/pull/19551
> [doc] Add some more signposting to cryptolib API documentation.

- hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv
Solving cdc issue with sw_clk_byp_en by synchronizing the reset deassertion from aon to external clock.
Solving usb glitch when disabling the usb clock by synchronizing its enable signal to the usb clk negative edge.
> [ast] solving two cdc issues

- sw/device/lib/testing/nv_counter_testutils.h
Fix simple doxygen issues in nv_counter_testutils.h. Remove declaration of a non-existent function.
> [testlibs,nv_counters] Fix trivial issues in header

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env_pkg.sv
- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
- Update testplan and tb collateral
> [rv_dm,dv] update testplan for halt/going/resume

- sw/device/lib/crypto/impl/sha2/sha256.c
- sw/device/lib/crypto/impl/sha2/sha512.c
- sw/device/tests/crypto/sha384_functest.c
Also adds a regression test and slightly reorganizes that piece of the code in both SHA-256 and SHA-512 to make it easier to reason about.
> [crypto] Fix a bug in SHA-512 padding.

- hw/ip/pinmux/data/pinmux.hjson
- hw/ip/pinmux/data/pinmux.hjson.tpl
- hw/ip/pwrmgr/data/pwrmgr_testplan.hjson
- hw/ip/rstmgr/data/rstmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/ast/data/ast.hjson
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
There have been some whitespace problems creeping into the codebase, mainly from the work on HJSON files for silicon validation. This PR fixes some of these.
> [dv] Whitespace fixes

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_halt_resume_whereto_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
this test verify the halt/resume/going behaviour of DM.
> [RV_DM]halt_resume_whereto

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
this test verify that debugger can issue non-debug reset to rest of the system.
@jdonjdon
> [RV_DM]ndmreset_req sequence

- hw/ip/pwm/data/pwm.hjson
- hw/top_earlgrey/data/chip_testplan.hjson
This is an initial go at silicon validation tests for PWM.
> [pwm,SiVal] Silicon validation tests for PWM module

- hw/ip/prim/rtl/prim_mubi_pkg.sv
- util/design/data/prim_mubi_pkg.sv.tpl
This has no functional changes.
> [mubi,gen] Fix comments

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
This is work in progress. I hope to continue this on THU. FYI @marnovandermaas .
What's missing:
- Finish description of features.
- Check what existing TLTs cover already / how they can be modified to cover what's missing.
- Check if new tests are needed.
> [chip-test, sival] ENTROPY_SRC SiVal test plan

- sw/host/opentitanlib/src/transport/common/uart.rs
In the `Uart` trait, `read()` and `read_timeout()` may be augmented by using the `register_nonblocking_read()` function, for `mio`-style polling for incoming data.  However, the convention is that the `write()` method is always blocking (there is no `register_nonblocking_write()`).
The implementation in `transport/common/uart.rs` does tricks with `port.as_raw_fd()` in order to get a file descriptor out of the `serialport` library for use with the `mio` library.  It seems that a side effect of this is that `mio` puts the file descriptor into non-blocking mode, which may cause `write_all()` to return an `Err()` in response to getting `EAGAIN` from the operating system due to queues being full.
I assume that `write_all()` could make multiple OS `write()` calls, and we have no way of knowing …
> [opentitantool] Handle writing of large amounts of UART data

- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
Preliminary clean up before group review.
- add si_tage: None
- add `chip_sw_flash_idle_low_power` to sv3
> [sival,flash_ctrl] update sival testplan

- doc/security/cryptolib/cryptolib_api.md
- sw/device/lib/crypto/impl/key_transport.c
- sw/device/lib/crypto/include/key_transport.h
1. Added the key import and export function for the unblinded and blinded keys;
2. Updated the crypto API doc to reflect the changes.
> [crypto, doc] Add key import and export functions
