sw/device/lib/testing/keymgr_testutils.c, sw/device/lib/testing/rstmgr_testutils.c, sw/device/lib/testing/test_rom/test_rom.c, sw/device/silicon_creator/lib/drivers/keymgr_functest.c, sw/device/silicon_creator/lib/drivers/retention_sram.h, sw/device/silicon_creator/lib/drivers/rstmgr_functest.c, sw/device/silicon_creator/lib/drivers/watchdog_functest.c, sw/device/silicon_creator/lib/irq_asm_functest.c, sw/device/silicon_creator/manuf/lib/provisioning_functest.c, sw/device/silicon_creator/rom/e2e/rom_e2e_bootstrap_rma_test.c, sw/device/silicon_creator/rom/e2e/rom_e2e_ret_ram_init_test.c, sw/device/silicon_creator/rom/e2e/rom_e2e_ret_ram_keep_test.c, sw/device/silicon_creator/rom/e2e/rom_e2e_shutdown_alert_config_test.c, sw/device/silicon_creator/rom/rom.c, sw/device/tests/sim_dv/otp_ctrl_lc_signals_test.c, sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test.c
This PR adds a version field to the `retention_sram_t` so that `rom_ext` can detect the current format and migrate to a different format if needed.
=> [sw/silicon_creator] Add version field to retention SRAM

sw/device/tests/BUILD, sw/device/tests/i2c_host_eeprom_test.c
This PR adds a manual test for the i2c host using an EEPROM device. Run with `bazel test //sw/device/tests:i2c_host_eeprom_test` (requires this particular EEPROM connected to the i2c).
The test covers:
* Writing and reading back a single byte at a random address (and in particular, not page aligned).
* Writing and reading back multiple bytes from the start of a page (page read).
* Acknowledgement polling - testing if the EEPROM is still busy writing by doing a zero-byte READ and waiting for it to acknowledge the device address.
The 80ms delay for acknowledgement polling is a bit of a magic number. Somewhere between 50ms and 70ms started passing, so 80ms gives us a buffer. I left the test running on a loop for a while and it didn't fail in 300 runs.
=> [i2c, test] Add i2c host test for using an EEPROM device

hw/ip/i2c/rtl/i2c_fsm.sv
Prior to this change, if the FMT FIFO doesn't yet have its next entry from software and the transaction is not done (i.e. STOP hasn't been issued), the i2c FSM would cause a glitch on SCL. The FSM would follow the sequence HostHoldBitAck -> PopFmtFifo -> Idle, and the Idle state would unconditionally cause a 0 -> 1 transition on SCL, even if the user intended to follow up with more data. Consequently, the host and device would fall out of alignment for the bit count.
For the purposes of an ECO, change the Idle state to only release SCL if it is not in the middle of a transaction in host mode. A subsequent commit may change the FSM for readability (e.g. going to Active if this IP is still in the middle of a bus transaction and fixing up the Active state to wait for instructions from the …
=> [i2c] Remove SCL glitch when FMT FIFO empties mid-transaction

sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/image/image.rs, sw/host/opentitanlib/src/image/manifest_def.rs, sw/host/opentitanlib/src/image/manifest_ext.rs, sw/host/opentitanlib/src/image/mod.rs, sw/host/opentitanlib/src/image/testdata/manifest.hjson, sw/host/opentitanlib/src/image/testdata/manifest_ext.hjson, sw/host/opentitanlib/src/util/num_de.rs
Adds HJSON deserialization for manifest extensions and adds support for applying extensions to images.
Uploading this as a draft right now, since opentitantool is still using the extension support added in https://github.com/lowRISC/opentitan/pull/18584.
=> [opentitanlib] Add support for manifest extensions specs

util/topgen/strong_random.py
Adds tests to evaluate statistical quality of the entropy buffer. These tests are triggered when the entropy buffer is loaded from a file and report an error if any of the tests fails.
=> [util] Add entropy tests to strong_random.py

hw/ip/aes/pre_dv/aes_sbox_tb/rtl/aes_sbox_tb.sv
This change is ensuring that the internally buffered entropy is updated such that the next S-Box evaluation will get fresh entropy for the first multiplier stage.
This is related to https://github.com/lowRISC/opentitan/pull/18480
=> [aes, pre_dv] Align S-Box Verilator TB with latest changes to DOM S-Box

sw/device/lib/testing/spi_device_testutils.h, sw/device/lib/testing/spi_flash_emulator.c, sw/device/lib/testing/spi_flash_testutils.c, sw/device/lib/testing/spi_flash_testutils.h, sw/device/lib/testing/test_framework/ottf_main.h, sw/device/tests/BUILD, sw/device/tests/spi_host_flash_test_impl.c, sw/device/tests/spi_host_flash_test_impl.h, sw/device/tests/spi_host_smoketest.c, sw/device/tests/spi_host_winbond_flash_test.c
This PR:
- Refactor the `EXECUTE_TEST` to accept and forward parameter to the test.
- Refactor the spi host flash smoke test to pass the spi_host handler as an argument.
- Refactor the spi host flash smoke test and move the tests implementation to a new file.
- create a new test called winbond as we communicate to a winbond memory in the FPGA.
- Add new commands to the winbond test.
=> [Spi host, flash] Add new tests

hw/top_earlgrey/dv/env/seq_lib/chip_sw_adc_ctrl_sleep_debug_cable_wakeup_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_ast_clk_rst_inputs_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwrmgr_deep_sleep_all_wake_ups_vseq.sv
Update chip_sw_ast_clk_rst_inputs_vseq and chip_sw_pwrmgr_deep_sleep_all_wake_ups_vseq tests to use the AST ADC output port.
=> [dv, chip-test]: Update some chip tests to use AST ADC output port

hw/ip/pinmux/fpv/tb/pinmux_tb.sv, hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv, hw/ip/pinmux/rtl/pinmux_strap_sampling.sv, hw/top_earlgrey/ip/pinmux/fpv/tb/pinmux_tb.sv
Fixes a syntax error in the pinmux_chip_fpv testbench and aligns several SVAs with the newest design state.
Fix #18397.`
=> [pinmux/fpv] Fix FPV testbench

hw/top_earlgrey/syn/chip_earlgrey_asic.sdc
Fix up JTAG constraints
- Target the clock inverter inside the TAP for set_clock_sense.
Previously, this was hitting the same clock buffer as the original
clock.
- Focus constraints on just the RV_DM and LC_CTRL TAPs. Remove the DFT
TAP and any paths that go through the pinmux.
- Fix the JTAG async clock group to include the generated clocks.
- Ramp up the target frequency to 30 MHz.
Fix odds and ends for SPI constraints
- Remove scan mode paths from the SPI clocks. These paths are specific
to a different mode, and they should use a different clock definition
for their constraints.
- Relax hold constraints for the passthrough clock gates. Primarily,
there were issues with the clock gate intended for CPOL=1, as it would
do same-edge hold timing and fail, while the incoming data would …
=> [sdc] Fix up SPI and JTAG constraints

sw/device/silicon_creator/lib/drivers/keymgr.h
This commit adds two notes to the keymgr driver regarding a case we noticed during the sec_mmio audit with @dmcardle. After a keymgr transition, ROM_EXT must update the cached values in the sec_mmio expectations table using either `sec_mmio_read32()` or `sec_mmio_write32()` before performing a sec_mmio check. Otherwise, the stale values in the table will trigger a shutdown.
=> [sw/silicon_creator] Add comments about sec_mmio expectations to the keymgr driver

hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_ctrl_scrap_vseq.sv
cpu_init has some disruptive backdoor writes.
So if there is timedelay between post_reset and body, cpu_init can causes spurious data corruptions.
Try this new option for some selected tests to address the issue
=> [chip,dv] move cpu_init to pre_start for some tests

hw/dv/dpi/usbdpi/usbdpi.h
As we discussed in #18818 change default frame interval following usb 2.0 spec
=> [usb,dv] change default frame interval to 1ms

hw/top_earlgrey/dv/chip_sim_cfg.hjson
After discussing in #18855 
`chip_sw_lc_ctrl_volatile_raw_unlock_ext_clk_96mhz` is not supported by lc_ctrl. So removed from testplan.
=> [chip,dv] remove obsolte test

sw/device/tests/BUILD, sw/device/tests/i2c_host_fram_test.c
This PR adds a test for using an FRAM i2c device.
* Reads the product and manufacturer IDs.
* Writes and reads back a single byte.
* Writes multiple bytes in one go (page write).
* Reads back multiple bytes in one go (sequential read).
* Reads back a byte from the current address counter (current address read).
Run using `bazel test //sw/device/tests:i2c_host_fram_test` with the break-out-board connected.
=> [i2c, test] Add i2c host test to drive an FRAM device

hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_jtag_mem_vseq.sv
Closed source has requirement to skip por_n at the beginning of the power up.
Adjust test sequence accordingly to support this feature.
=> [chip,dv,jtag] Add skip por_n reset support

hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
An intermediate variable in do_predict did not have adequate width, which led to some interrupt test failures in the GPIO block-level environment.
Fixes #17345
=> [dv] Fix multibit bug in interrupt test register prediction

hw/top_earlgrey/dv/chip_sim_cfg.hjson
Following tests need more run time to pass in the closed source tb. 
- chip_sw_rv_core_ibex_rnd
- chip_sw_csrng_edn_concurrency
- chip_sw_csrng_edn_concurrency_reduced_freq
- chip_sw_entropy_src_csrng
=> [chip,cs,dv] increase timeout for cs tests

doc/guides/getting_started/src/setup_verilator.md, hw/dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc, hw/dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.h
For the long option --trace only, add the ability to specify an optional argument for where to place the waveform file.
Add information about how to use opentitantool and bazel's test_arg to get waveforms from a test run. Also mention how to update the timeout, so tests with traces don't time out from the much-reduced execution speed.
Resolves #13042
=> [verilator] Add support for specifying a trace file and document how to use it

hw/ip/aes/dv/env/seq_lib/aes_reseed_vseq.sv
Previously, this test had a couple of serious issues:
- The reseed checking function was pretty broken. It did not get updates of the probed signals inside the busy loop as the function was call-by-value. In most cases function the function just timed out.
- There was no failure in case the reseed didn't happen.
- Writes to shadow registers were not correctly handled which in some rare cases caused recoverable alerts and test failures.
Also, the test did not properly verify automatically triggered reseed operations based on the reseed rate setting.
This resolves lowRISC/OpenTitan#17357.
=> [aes, dv] Fix reseed test

hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_walkthrough_testunlocks_vseq.sv
Similar issue with #18147 
Test does lc state transition from raw state with uncalibrated clock. Fixed by adding external clock.
=> [chip,dv] add switch to external clock for lc state transition

hw/ip/pwrmgr/data/pwrmgr.hjson
This file is supposed to be autogenerated from pwrmgr.hjson.tpl, but it appears we don't always do that! Indeed, the comment went away from the template file two years ago, in
d7f00ea49fe2eea5bebf6d1e579f9f5b582d3438.
There's clearly some scope for clean-ups (enforce autogeneration, or do away with it altogether!), but let's just get this line in sync for now.
Fixes #18834.
=> Remove stale comment in pwrmgr.hjson

hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv, hw/ip/spi_host/dv/env/spi_host_env_cov.sv, hw/ip/spi_host/dv/env/spi_host_env_pkg.sv, hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
This required a bit of refactoring to the scoreboard and some base_vseq routines to handle what is effectively an on-the-fly reset condition. (e.g. spinwaiting tasks prevent us from accessing the bus to trigger the reset!)
The testcase now triggers a SW_RESET both during and between transactions, and an extra cross-coverage point (`sw_rst_active_cross`) has been added for this.
closes #16510
=> [spi_host,dv] Extend sw_reset test to trigger mid-transaction

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_ec_rst_with_pre_cond_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ultra_low_pwr_vseq.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_cov.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson
- Update `dut_shutdown` to handle end of test
- Instead of adding enum write to `pre_cond_sel` register using the name of the field
- `z3_wakeup` check is tightly coupled with the test, so no need to move the check
- all the configs in sim_cfg.json apply, so remove the TODO
=> [hw,sysrst_ctrl,dv] Address TODO and warnings in DV environment

hw/formal/tools/jaspergold/conn.tcl
This PR allows CS to run additional TCL script after the first `analyze` command, which gives the flexibility to add some additional design files/overwrite existing modules.
=> [chip/conn] run additional TCL for loading CS design files outside core files

util/reggen/gen_md.py
Should be one level higher, can be seen easily by looking at the ToC. e.g. https://opentitan.org/book/hw/ip/spi_host/data/spi_host.html#rxdata
@HU90m
=> [doc,reggen] Fixup window register header level

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ec_rst_l_vseq.sv
Update the wait time for the de-assertion of `ec_rst_l_o` before the start of the test. Use default value in specification of `sysrst_ctrl`
This PR resolves https://github.com/lowRISC/opentitan/issues/18595
=> [hw,top_earlgrey,dv] Increase wait time before start of test

sw/device/lib/testing/pinmux_testutils.c, sw/device/tests/BUILD
This would only be for the SAM3X variant. Also, we might want to check whether the switching speed is reasonable for the LEDs--Other than the time it takes to execute the DIF instructions, there is no wait between write and read in the test.
Fixes #18623
=> [test] Retarget gpio_smoketest to the LEDs on CW310

site/book-theme/css/chrome.css
Previously on hover, the animation transitioned from a background to a foreground color. However, the background colour of white in this case would show up on-top-of page content under circumstances with a narrow page width.
Change to animate the opacity instead, so chevrons are entirely transparent when not-hovered.
Closes #18891
=> [site] Animate opacity of nav-chapter chevrons

hw/ip/i2c/doc/programmers_guide.md, sw/device/lib/testing/i2c_testutils.c, sw/device/lib/testing/i2c_testutils.h
This PR documents and implements the NAK detection workaround discussed in the issue #18764. 
Fix https://github.com/lowRISC/opentitan/issues/18764
=> I2c nak detection workarround

sw/device/lib/testing/test_framework/ottf_main.h
Cast cycle count to 32 bits so it prints correctly. I think this broke in f96cd289, which fixed a bug in the cycle count computation by changing `cycles_` to 64 bits but confused the printing as a side effect.
Before this change:
```
I00000 ottf_main.c:143] Running sw/device/tests/crypto/sha256_functest.c
I00001 sha256_functest.c:166] Starting test simple_test...
I00002 sha256_functest.c:166] Successfully finished test simple_test in 536899220 cycles or 1343 us @ 0 MHz.
I00003 sha256_functest.c:167] Starting test empty_test...
I00004 sha256_functest.c:167] Successfully finished test empty_test in 536899320 cycles or 1185 us @ 0 MHz.
I00005 sha256_functest.c:168] Starting test one_update_streaming_test...
I00006 sha256_functest.c:168] Successfully finished test one_update_streaming_test in …
```
=> [test] Fix bounds for printing cycle count.

sw/host/hsmtool/src/commands/exec.rs, sw/host/hsmtool/src/commands/mod.rs, sw/host/hsmtool/src/commands/object/destroy.rs, sw/host/hsmtool/src/commands/object/list.rs, sw/host/hsmtool/src/commands/object/mod.rs, sw/host/hsmtool/src/commands/object/show.rs, sw/host/hsmtool/src/commands/object/update.rs, sw/host/hsmtool/src/commands/rsa/decrypt.rs, sw/host/hsmtool/src/commands/rsa/encrypt.rs, sw/host/hsmtool/src/commands/rsa/export.rs, sw/host/hsmtool/src/commands/rsa/generate.rs, sw/host/hsmtool/src/commands/rsa/import.rs, sw/host/hsmtool/src/commands/rsa/mod.rs, sw/host/hsmtool/src/commands/rsa/sign.rs, sw/host/hsmtool/src/commands/rsa/verify.rs, sw/host/hsmtool/src/commands/token.rs, sw/host/hsmtool/src/hsmtool.rs, sw/host/hsmtool/src/module.rs
`hsmtool` normally loads the relevant `pkcs11` module which is then used by some of the various command functions.  In order to add PQ crypto support, `hsmtool` will need to load another vendor library and pass it to the command functions.  In preparation for PQ support, migrate the `Pkcs11` library state into a `Module` struct.
=> [hsmtool] Encaspulate library state in a `Module` struct

hw/top_earlgrey/dv/chip_rom_tests.hjson
The toplevel testbench was updated a couple days ago to facilitate using pre-signed binaries. This broke existing tests, which are now fixed in this commit.
=> [dv] fix failing ROM E2E tests in DV

hw/top_earlgrey/sw/autogen/chip/top_earlgrey_memory.rs, util/topgen/templates/toplevel_memory.rs.tpl
A newer version of clippy catches this with clippy::suspicious-doc-comments.
=> [topgen] fix broken doc comments

hw/dv/sv/tl_agent/dv/tl_agent_sim_cfg.hjson
This is sort of trivial: the `tl_agent` tests don't really do anything with multiple clocks anyway. But I guess it makes sense if `tl_agent` is on a list of blocks where we'd like to see things working with CDC checks enabled.
=> Enable CDC for tests of tl_agent

ci/azure-pipelines-nightly.yml, sw/device/lib/testing/i2c_testutils.c, sw/device/lib/testing/i2c_testutils.h, sw/device/tests/BUILD, sw/device/tests/i2c_host_accelerometer_test.c, sw/device/tests/i2c_host_ambient_light_detector_test.c, sw/device/tests/i2c_host_clock_stretching_test.c, sw/device/tests/i2c_host_compass_test.c, sw/device/tests/i2c_host_eeprom_test.c, sw/device/tests/i2c_host_fram_test.c, sw/device/tests/i2c_host_gas_sensor_test.c, sw/device/tests/i2c_host_hdc1080_humidity_temp_test.c, sw/device/tests/i2c_host_power_monitor_test.c, sw/device/tests/i2c_target_test.c, sw/device/tests/sim_dv/i2c_device_tx_rx_test.c
This PR:
- Refactor the i2c testutils function that configures the pinmux to improve readability.
- Change the i2c tests that requirers the BoB from i2c0 to i2c2.
- Create a CI nightly job to run the tests.
=> [ci] New nightly job for the BoB

hw/ip/pwm/dv/pwm_sim_cfg.hjson
Enable CDC instrumentation in `pwm` block level TB as part of https://github.com/lowRISC/opentitan/issues/16689
There are no new errors with this change
=> [hw,pwm,dv] Enable CDC instrumentation

hw/ip/uart/dv/env/seq_lib/uart_loopback_vseq.sv, hw/ip/uart/dv/env/seq_lib/uart_noise_filter_vseq.sv, hw/ip/uart/dv/env/seq_lib/uart_rx_oversample_vseq.sv, hw/ip/uart/dv/uart_sim_cfg.hjson
- Enable CDC randomization in uart block level TB
- Add delays to account for CDC randomization
- Clear `RDATA FIFO` at the end of the line loopback sequence to make sure data captured in this mode won't affect the sys_loopback sequence
- Disable CDC randomization for noise_filter test https://github.com/lowRISC/opentitan/issues/18912
This PR resolves https://github.com/lowRISC/opentitan/issues/18895
=> [hw,uart,dv] Enable CDC instrumentation

hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv
- Disable `DstPulseCheck_A` assertion of `prim_pulse_sync.sv` in case of CDC randomization.
- Even though `src_pulse` to the module is separated by a minimum number of cycles, CDC randomization can cause two output pulses to overlap resulting in assertion errors.
This PR partially addresses https://github.com/lowRISC/opentitan/issues/18364
=> [hw,spi_device,dv] Fix failures related to DstPulseCheck_A assertion in spi_device nightly regression

hw/top_earlgrey/dv/chip_rom_tests.hjson
One was missing a singing key tag, and one was timing out.
=> [dv] fix ROM tests in DV

hw/ip/aes/dv/cov/aes_cov_bind.sv, hw/ip/aes/dv/env/seq_lib/aes_readability_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_reseed_vseq.sv, hw/ip/aes/dv/err_injection_if/fi_cipher_if.sv, hw/ip/aes/dv/err_injection_if/fi_control_if.sv, hw/ip/aes/dv/err_injection_if/fi_core_if.sv, hw/ip/aes/dv/err_injection_if/fi_ctr_fsm_if.sv, hw/ip/aes/dv/err_injection_if/force_if.sv, hw/ip/aes/dv/sva/aes_idle_check.sv, hw/ip/aes/dv/sva/aes_masking_reseed_if.sv, hw/ip/aes/dv/sva/aes_reseed_if.sv, hw/ip/aes/dv/tb/tb.sv
This PR resolves most of the tool warnings we're currently seeing for AES DV. Most of them are related due to ignoring return values of built in UVM functions. As these functions take string arguments and we use a couple of different ways in AES DV to pass these strings, it's not always possible to simply wrap the function calls using with a call to the `DV_CHECK_FATAL` macro as we do in other places of the project. In some cases, we also need to wrap the resulting `if/else` constructs with pragmas to turn off and on again coverage collection.
This is required for V2.5. This is related to lowRISC/OpenTitan#18428.
=> [aes, dv] Resolve tool warnings

hw/ip/pinmux/doc/theory_of_operation.md, hw/top_earlgrey/dv/env/seq_lib/chip_padctrl_attributes_vseq.sv
This cleans up remaining TODOs in the pinmux TLT and adds a reference to the USB device in the pinmux module (for the USB wakeup detector module).
=> [pinmux/dv] Update pinmux TLT and address TODOs

hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c
sram_ctrl_scrambled_access_test.c has unnecessary end of test reset
https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c;drc=78036ec7cb0ca2a70f88ebc8ca05b31694a05e62;l=399
This issue has been discovered in #16259 and #16597 but closed by #16662 which explains 
sw reset is needed for retention sram test but not exactly at the end of test.
I reviewed the test and find the end of test reset is added to avoid test timeout.
The timeout happens because this test creates several "expected" rv_core_ibex_fatal_hw_err
and chip level test bench only uses alert monitor.
So instead of using rtl reset, add "+bypass_alert_ready_to_end_check=1" to the test and let the test
finish gracefully after run_phase.
=> [chip,dv] remove unecessary eot reset

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sensor_ctrl_status_intr_vseq.sv
The VIO POK path for both VIOA and VIOB in the test needs to be updated due to changes in the AST's RTL in the closed source.
=> [dv, chip-test] Update VIO POK paths

hw/dv/tools/dvsim/common_sim_cfg.hjson, hw/ip/gpio/data/gpio_testplan.hjson, hw/ip/gpio/dv/env/seq_lib/gpio_smoke_vseq.sv, hw/ip/gpio/dv/gpio_sim_cfg.hjson, hw/ip/gpio/dv/tb/tb.sv
This covers the input path through CDC prims.
Other tests unfortunately don't run with CDC prims since the scoreboard is cycle accurate and currently can't account for additional delay on the input path.
Fixes #9941
=> [gpio/dv] Add second build mode for CDC prims

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_outputs_vseq.sv
Some test benches use different time scale.
Add time unit to avoid wrong interpretation.
=> [chip,dv] replace implicit time delay

hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
The `target` argument is used in the `find_index` function in comparisons against an indexed string, which returns a byte.  Thus, it's type must also be a byte.  This caused warnings in VCS, which are fixed by this commit (and which are relevant for V2.5 sign off).
After this fix, there are no more compile-time or run-time warnings by the simulator tool. The `ALL_TOOL_WARNINGS_ARE_REVIEWED` checklist item for V2.5 sign-off can thus get ticked off.
=> [edn/dv] Fix type of `target` argument to `find_index`

hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
In the scoreboard, wait for two extra cycles (to account for CDC) before the wakeup interrupt check, since this is synchronized to AON clock domain
=> [hw,aon_timer,dv] Fix test failures related to CDC randomization

release/azure-pipelines-release.yml
Even with a time limit of 4h (increased in 6537129b68079d1196de105dae0fb0c0cff352d4 / PR #18906), the *Release* job still times out.  New logs indicate that:
- Building the regular CW310 bitstream takes ca. 3h 20min.
- Bitstream splicing then takes ca. 10min.
- Building the Hyperdebug CW310 bitstream then starts and times out. According to logs from CI checks, that would take ca. 1h 40min.
Thus, the runtime of the *Release* job should be some 10min above 5h.
This commit increases the timeout to 6h, so that there's some margin for when additional work is added or the complexity of existing tasks increases.
=> [release] Increase timeout of CI job

sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c
chip_sw_data_integrity_escalation test uses flash access to store interrupt counter.
In closed source, write/read delay of flash is large and sometimes it surpasses phase0 timeout.
Inrease pahse0/1 timer value to avoid interrupt counter read failure from closed source test.
=> [chip,dv] increase escalation phase due to flash delay

hw/ip/i2c/data/i2c.hjson, hw/ip/i2c/data/i2c_testplan.hjson, hw/ip/i2c/doc/programmers_guide.md, hw/ip/i2c/doc/theory_of_operation.md
This PR is meant to check off the remaining checklist items for I2C V2: https://github.com/lowRISC/opentitan/issues/18741 Please refer to that issue for the relevant issue links, etc.
There are a couple of RTL fixes necessary in a future release, but this PR explains these in the documentation to pass V2: https://github.com/lowRISC/opentitan/issues/18962 and https://github.com/lowRISC/opentitan/issues/18962
=> [i2c,doc] Documentation changes for V2 sign-off

hw/ip/edn/dv/env/seq_lib/edn_disable_vseq.sv
This PR makes three small improvements and fixes (see commits for details) to `edn_disable_test`. After this PR, the test covers transitions from *all* Boot modes to Idle. The pass rate remains 48/50.
=> [edn/dv] Improve coverage of and fix `edn_disable_test`

hw/top_earlgrey/dv/chip_rom_tests.hjson
Same reason as described in #18735, 
need to add external clock to access otp from raw lc state
=> [chip,dv] add external clock to rom_volatile_raw_unlock

hw/ip/rv_timer/dv/env/rv_timer_scoreboard.sv
The TODO suggested checking the interrupt pin could be changed if the interrupt CSRs were implemented as hwext. However, that did not occur on the design side and is not planned. So, remove the TODO.
For the production release, I think we'll want to tackle #18918 on the design side, but that is not relevant for the shuttle. That may have an effect on the scoreboard here, though.
=> [rv_timer/dv] Remove TODO for interrupt checking

hw/ip/i2c/dv/env/i2c_scoreboard.sv, hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_full_vseq.sv, hw/ip/i2c/dv/env/seq_lib/i2c_rx_tx_vseq.sv, hw/ip/i2c/dv/sva/i2c_protocol_cov.sv
This PR is, as far as I know, the last task remaining for closing I2C verification for M2.5:
https://github.com/lowRISC/opentitan/issues/17890
Assuming V2 sign-off is merged as well: https://github.com/lowRISC/opentitan/pull/18211
It mainly puts DV TODOs into iceboxes as described in the commit messages.
=> [i2c,dv] I2C todo cleanup

hw/ip/prim/dv/prim_present/tb/prim_present_tb.sv
This reoarganizes the prim_present testbench so that only the relevant instantiations are tested: 1) full round, 2) iterative single round. In particular, by emulating iterations with 2) in the testbench, the code coverage is increased substantially.
=> [prim_present/dv] Only test relevant configs and improve coverage

sw/device/silicon_creator/lib/sigverify/rsa_verify.c, sw/device/silicon_creator/lib/sigverify/sigverify_unittest.cc, sw/device/silicon_creator/rom/e2e/BUILD
We update the ROM to always read the OTP setting for what sigverify mode to use (SW vs OTBN), regardless of the LC state (previously, the mode setting was only read from OTP when the LC state was NOT TEST_UNLOCKED*).
Additionally, we default the sigverify mode to SW, if the `CREATOR_SW_CFG_SIGVERIFY_RSA_MOD_EXP_IBEX_EN` field OTP is uninitialized (i.e., all 0s).
We make these changes because we want to run GLS tests in the TEST_UNLOCKED* LC state using the real ROM, and not enabling the use of OTBN signature verification causes GLS runtimes to explode.
=> [rom] update sigverify mode behavior

hw/ip/rv_timer/dv/rv_timer_sim_cfg.hjson
`rv_timer_random` seems to occasionally fail in the nightlies due to a timeout.
This increases the timeout by 10x so that there is plenty of margin.
=> [rv_timer/dv] Increase timeout for random test

sw/device/tests/i2c_host_compass_test.c
There's an early return in the compass test. That means the product id is never tested.
=> [i2c, test] Removed early return in compass test.

hw/top_earlgrey/dv/chip_rom_tests.hjson
This adds an example ROM E2E test (the self hash test) that does not backdoor load the ROM to test the ROM has been properly integrated into the netlist.
=> [dv] add test that does not backdoor load ROM

hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_otp_ctrl_vendor_test_csr_access_vseq.sv
otp_vendor_test status hook is tied to zero in open source. 
Add proper place holder to update otp_vendor_test_status in closed source test
=> [chip,dv] add otp_vendor_test_status hook

hw/ip/edn/dv/edn_sim_cfg.hjson, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/edn_if.sv, hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv, hw/ip/edn/dv/tests/edn_err_test.sv, hw/ip/edn/dv/tests/edn_intr_test.sv, hw/ip/edn/dv/tests/edn_test.core, hw/ip/edn/dv/tests/edn_test_pkg.sv
This PR reworks the `edn_err` test so that it achieves full coverage of transitions from *each* FSM state to the Error state. This was one of the main coverage gaps left for M2.5.
Please see the commit messages for details. Reviewing this commit by commit is highly recommended to understand the motivation for each change.
=> [edn/dv] Rework `edn_err` test to substantially increase coverage

hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv
The first 7 commits fix smaller problems in `edn_base_vseq`; the last commit rewrites `edn_disable_auto_req_mode_vseq` to fix its coverage and functional checking problems. Please see the individual commit messages for details. Reviewing commit by commit is highly recommended.
A full regression run showed an overall FSM coverage of 98.5% (98% in Main FSM, 100% in Ack FSM, though dvsim reported only 94%). This PR thus resolves #18370 (together with the already merged PRs #18960 and #18976). Test pass rates are nominal.
The rewrite of `edn_disable_auto_req_mode_vseq` also addresses the missing disable-and-re-enable testing in Auto mode. Thus, this PR also resolves #16429 (as Boot mode already got tested in `edn_disable_vseq`).
=> [edn/dv] Fix `edn_disable_auto_req_mode_vseq` and a few smaller problems in `edn_base_vseq`

sw/device/tests/BUILD, sw/device/tests/i2c_host_compass_test.c
Appended a reset and re-test to the compass test to check the i2c peripheral functions after a reset.
This should tick "Reset via Reset manager" in https://github.com/lowRISC/opentitan/issues/18711.
=> [i2c, test] Appended a reset and test run to the compass device test

hw/ip/csrng/dv/env/csrng_scoreboard.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
The TODOs in CSRNG's DV are not relevant for M2.5. This PR links them to an existing and a new issue to track their resolution post M2.5.
=> [csrng/dv] Clean up TODO items for M2.5

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv
chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq uses
very delicate sync between c and sv test.
Add test sync at the beginning of the sv test to avoid out of sync when boot process takes longer than usual.
=> [chip,dv] fix test out of sync

sw/device/silicon_creator/manuf/data/manuf_testplan.hjson, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/sram_empty_functest.c, sw/device/silicon_creator/manuf/lib/sram_program.ld, sw/device/silicon_creator/manuf/lib/sram_start.S, sw/device/silicon_creator/manuf/lib/sram_start.h, sw/host/opentitanlib/src/io/jtag.rs, sw/host/opentitanlib/src/test_utils/load_sram_program.rs, sw/host/opentitanlib/src/util/openocd.rs, sw/host/tests/manuf/manuf_sram_program_crc_check/BUILD, sw/host/tests/manuf/manuf_sram_program_crc_check/src/main.rs
WIP see #18635
Tasks:
Left to another PR:
- have the loader read back a tiny bit of the program (the sram start) to make sure that the code CRC'ing the everything else is not corrupted.
=> Sram program integrity

third_party/python/gen_requirements.sh
The bash script that prepares the sanitized package list did not work on different bash versions due to missing quotes.
=> [bazel] fix bug in ot_python_wheels repo setup

hw/ip/usbdev/rtl/usb_fs_nb_out_pe.sv
The link_active_i term was misplaced, and data toggles should not be cleared in suspended state. In fact, they should be retained, and usbdev will need to give software greater visibility and control, so it can save / restore state in coordination with deep sleep.
For the purposes of an ECO, leave link_active_i unused. It was intended to help prevent the packet engines from responding to packets and dirtying FIFOs before software is ready, but that is left for a later commit.
Found by @alees24 in #18940
=> [usbdev] Remove data toggle clear in suspend

hw/ip/spi_device/rtl/spid_addr_4b.sv
The update mechanism uses a stable value after the spi_clk synchronizers.
=> [rtl/spi_device] Add extra cycle for CDC in spid_addr_4b

hw/ip/i2c/rtl/i2c_fsm.sv
If the clock is stretched, the FSM must not sample SDA. NACK detection must wait until the clock is ready.
Fixes #19014
=> [i2c] Hold off NACK detection until posedge SCL

sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/sleep_pin_wake_test.c
Test `sleep_pin_wake_test.c` relies on rand_utils_gen to generate random number. 
This utils happen to generate the same random number over the multiple reset events 
in open source while in closed source, it creates different random number for every reset event.
Since the intention of this test is to generate random number once 
and use the number after another reset event,
preserve the generated random number to flash and read back after the 2nd boot event.
=> [chip,dv] use flash to preserve non-volatile variable

hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
Read `flash_status` register after the register write and after the end of the SPI transaction, to avoid using a thread for register read.
This PR fixes corner case failures of https://github.com/lowRISC/opentitan/issues/18854 bucket 1 (partially fixed with PR https://github.com/lowRISC/opentitan/pull/18888)
=> [hw,spi_device,dv] Simplify the check for flash_status

hw/ip/aon_timer/data/aon_timer_testplan.hjson, hw/ip/aon_timer/dv/aon_timer_sim_cfg.hjson, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv
Opened an issue here: https://github.com/lowRISC/opentitan/issues/19059)  to track resolution of the use of reset_aon_first (Note this is not a concern for M2.5.2)
=> Aon timer todos

hw/dv/sv/i2c_agent/i2c_agent_cfg.sv, hw/dv/sv/i2c_agent/i2c_driver.sv, hw/dv/sv/i2c_agent/i2c_if.sv, hw/ip/i2c/dv/env/seq_lib/i2c_host_perf_vseq.sv, hw/ip/i2c/dv/i2c_sim_cfg.hjson, hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_device_tx_rx_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_host_tx_rx_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_tx_rx_vseq.sv, sw/device/tests/sim_dv/i2c_host_tx_rx_test.c
This is kind of a grab bag of timing and other fixes, where each individual commit addresses something different.
There are a couple other changes I haven't yet pushed up, but this set should eliminate errors for target mode tests (except I haven't done the target_stress_all* tests yet).
|  Stage  |         Name         | Tests                     |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:--------------------:|:--------------------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V1    |     target_smoke     | i2c_target_smoke          |      19.100s      |     9.073ms      |    50     |   50    |  100.00 %   |
|   V1    |                      | **TOTAL**                 |                   | …
=> [i2c,dv] Various timing fixes for the agent and CDC

hw/top_earlgrey/dv/env/seq_lib/chip_prim_tl_access_vseq.sv
tag - excl is set in some closed source prim csrs. 
Apply those settings to the relevant test.
=> [chip,dv] apply exclusion to chip_prim_tl_access_vseq

hw/ip/rom_ctrl/dv/env/rom_ctrl_env_cfg.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_kmac_err_chk_vseq.sv
This should take care of the remaining smoke test timeout errors in the regression.
=> [rom_ctrl/dv] Increase TL access timeout 

hw/ip/spi_device/dv/env/spi_device_env_cov.sv
Exclude some bins to increase the coverage of `flash_cmd_info_cg` and `flash_upload_payload_size_cg` above thresholds for the milestone.
=> [spi_device,dv] Cov refinements

hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_rx_async_fifo_reset_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tx_async_fifo_reset_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_txrx_vseq.sv
- Schedule the mirror value update for `addr_4b_en` after next SPI transaction since this field gets updated in SPI clock domain
- Disable destination pulse assertion in prim module similar to https://github.com/lowRISC/opentitan/pull/18829
=> [hw,spi_device,dv] Schedule reg prediction for cfg_addr_4b_en

hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
These covergroups intend to sample when a given tx/rx fifo is full to the space "allocated" to it within the DPSRAM buffer. Previously when the covergroups were sampled, we passed the upper-limit address of each fifo, rather than the size (upper-lower).
=> [spi_device,dv] Fixup fifo_size sampling conditions

ci/scripts/check-ascii.sh, hw/dv/sv/sw_logger_if/sw_logger_if.sv, hw/top_earlgrey/dv/chip_rom_tests.hjson, sw/device/silicon_creator/rom/e2e/BUILD, sw/device/silicon_creator/rom/e2e/presigned_images/BUILD, sw/device/silicon_creator/rom/e2e/presigned_images/rom_e2e_self_hash_sim_dv.logs.txt, sw/device/silicon_creator/rom/e2e/presigned_images/rom_e2e_self_hash_sim_dv.rodata.txt, util/fix_trailing_whitespace.py
This updates the ROM self hash test:
1. add missing backdoor logging DB files so the pre-signed test can print the hash in DV environment (via backdoor), and
2. to run with an OTP image that has OTBN signature verification enabled and is in the RMA LC state (for both DV and FPGA test platforms).
=> [rom_e2e] update ROM self hash test configuration

sw/device/silicon_creator/manuf/lib/sram_program.ld, sw/host/opentitanlib/src/test_utils/load_sram_program.rs
At the moment we rely on the device code to verify the CRC of the entire program at runtime. This catches most errors but in the unlikely case where the corruption happens in the CRC code itself, the test could pass even though the program is corrupted. This commit adds a feature to the ELF loader to read back the data from the section that contains the entry point of the program. The linker script is modified accordingly so that a tiny section is created that contains the entry point and the only the code to verify the CRC. Since this section is tiny, reading it back has a negligible impact on loading time.
This should close #18635
=> [manuf] Read back and verify device that performs the CRC check

hw/top_earlgrey/dv/chip_sim_cfg.hjson
chip_if.cc_if are connected by analog source in closed source env. 
For pad_ctrl test, these should be disconnected otherwise cc_if are driven by '0' and test will fail.
To mitigate this, add ifdef to close source and add define to open source
=> [chip,dv] add define for close source env

hw/ip/tlul/generic_dv/env/seq_lib/xbar_random_vseq.sv, hw/ip/tlul/generic_dv/env/xbar_env_cfg.sv, hw/ip/tlul/generic_dv/tests/xbar_base_test.sv
In closed source env, xbar test run too long(+20hrs). 
Add short run option for fast regression.
=> [chip,dv] add short iteration option to xbar test

sw/device/lib/testing/BUILD, sw/device/lib/testing/spi_flash_emulator.c, sw/device/lib/testing/spi_flash_testutils.c, sw/device/lib/testing/spi_flash_testutils.h, sw/device/lib/testing/spi_host_testutils.c, sw/device/lib/testing/spi_host_testutils.h, sw/device/tests/BUILD, sw/device/tests/spi_host_flash_test_impl.c, sw/device/tests/spi_host_flash_test_impl.h, sw/device/tests/spi_host_macronix_flash_test.c, sw/device/tests/spi_host_winbond_flash_test.c
This PR only add a new spi_host test. The test execute various commands of a Macronix flash on the BoB.
=> [Spi_host] Test a Macronix flash

sw/device/lib/testing/test_framework/ottf_main.c, sw/device/lib/testing/test_framework/ottf_main.h, sw/device/tests/BUILD, sw/device/tests/status_report_overflow_test.c
See #17703
- add mecanism to override the list size
- add unittest to exercise the behavior in case of overflow
This PR changes the behaviour on overflow: it now records the last N reports (N=size of the list) and prints it backwards.
=> [device] OTTF status report queue improvements

hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_otp_ctrl_vendor_test_csr_access_vseq.sv
otp_vendor_test requires lc_raw_test_rma = on.
Therefore, exclude LcStProd,LcStProdEnd,LcStDev from vendor_csr access test.
=> [chip,dv] update lc state for otp vendor csr test

hw/top_earlgrey/dv/env/chip_if.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_power_virus_vseq.sv
This part of the tests checks if all of the IPs are active during the max-power-epoch.
The CSRNG state machine was toggling between the idle and active states, and it was causing the test fail once in a while.
This commit changes the activity indicator for CSRNG to the "acmd_q" signal, which shows the last executed CSRNG operation. The chip_sw_power_virus_vseq.sv file checks if the last CSRNG command is the reseed (0x2) or generate(0x3).
Tested on the local EDA farm instance.
=> [test] Fix activity-checking part of the power virus test

azure-pipelines.yml, ci/scripts/check-module-ids.sh, rules/quality.bzl, sw/host/opentitantool/src/command/status_cmd.rs
See #17605.
The goal of this PR is to add a check to enforce that module IDs are not conflicting.
The approach is to run the `opentitantool status lint` command on every relevant ELF file (see commits for details).
One downside of this approach is it triggers a build of `opentitantool` and also builds all the test ELF files. The former is quite slow because opentitanlib depends on `pqcrypto-sphincsplus` even though this is not useful for this particular check. This can also be fixed by reorganizing `opentitanlib`.
One possibility would be to run those checks at the same time as we run the device tests on FPGA since everything has to be built anyway, but this could be a bit confusing.
Questions:
- At the moment I am using an aspect with an explicit output group, but apparently bazel …
=> Verify module IDs

.github/workflows/pr_lint_review.yml, .github/workflows/pr_trigger.yml
actions/checkout@v2 and actions/upload-artifact@v2 use Node.js 12, which will be deprecated from GitHub's Ubuntu runner in the summer of 2023.
Update: also updated actions/github-script@3.1.0 to v6 to use Node.js 16. This is used in the `pr-lint-review` pipeline which isn't run on this pull request's context, so isn't checked here.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> [ci] Update EOL GitHub Actions

.github/workflows/pr_lint_review.yml
This reverts commit 325636b7cc53657e142eed21f7293b8dc49d07a8.
As part of #18900, I updated the "github-script" action to v6, which updates the version of Node.js it uses from 12 (now deprecated) to 16. We were hoping this wouldn't break the script, but it has.
Reverting that update to fix the verible lint.
#18910 provides a proper upgrade of the verible lint that will avoid this issue entirely.
=> [ci] Revert "Update actions/github-script to v6"

hw/dv/tools/dvsim/vcs.hjson
Required to improve gate-level simulation performance.
=> [dv,vcs] add an option to override debug_region vcs flag

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c
This PR makes the following changes to `chip_sw_sram_ctrl_scrambled_access` test:
-  Fix-up typos ;
- Improve synchronization of the SW with the testbench.
=> [Sram, dv] Improve synchronization of scrambled access test.

hw/ip/otbn/dv/otbnsim/sim/sim.py, hw/ip/otbn/dv/otbnsim/sim/state.py, hw/ip/otbn/dv/otbnsim/sim/wsr.py
No functional change: this is mostly breaking long lines. But it avoids wiggly red lines from flake8 in the editor when trying to do other stuff...
=> [otbn,dv] Fix trivial Python lint bugs in otbnsim

hw/top_earlgrey/dv/chip_rom_tests.hjson, hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv, hw/top_earlgrey/dv/tb/tb.sv, hw/top_earlgrey/dv/tests/chip_base_test.sv
Skipping the ROM backdoor loading is needed to test the final ROM macro which is integrated into the design.
=> [dv] add plusarg to skip ROM backdoor load

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv
Singal sampling routines in the sv forever loop have clock dependency 
based on which signal the routine wants to sample. 
So update to 1ns (fast-enough) to avoid spurious sampling error due to passive_clock change.
=> [chip,dv] update sampling cycle of sram_ctrl sramble sv sequence

hw/dv/sv/key_sideload_agent/key_sideload_driver.sv, hw/dv/sv/key_sideload_agent/key_sideload_if.sv, hw/dv/sv/key_sideload_agent/key_sideload_item.sv
Previously, the `get_and_drive()` task was consuming zero time when the reset was active. This resulted in the key sideload interface endlessly updating the sideload key and the whole DV environment to completely hang. The root cause of this issue was the custom `wait_clks()` implementation of the agent which 1) immediately returned when the reset was active, and 2) was itself called in a forever loop consuming zero time.
To fix this, this commit makes sure every iteration of forever loop inside `get_and_drive()` takes at least one clock cycle. In line with this change, the constraint for the response delay is adjusted to allow for a minimum response delay of zero clock cycles (previously one). The functions for waiting for clocks cycles and/or resets are copied over from the clock and …
=> [dv, key_sideload_agent] Fix DV environment hanging issue under reset

hw/dv/verilator/cpp/dpi_memutil.cc
This causes memutil to mistakenly consider relative path like `./foo` to have extension of `/foo` as opposed to extension-less.
Related: lowRISC/ibex-demo-system#51
@marnovandermaas
=> [dv] Fix extension parsing in memutil

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ec_rst_l_vseq.sv
chip_sw_sysrst_ctrl_ec_rst_l uses fixed 5us clock to sample `ec_rst_l`. 
Since this clock can be drifted +/- 3%, 
constant clock can cause reset period measurement failure.
Replace this sampling clock to real one.
=> [chip,dv] update sampling clock in sysrst_ctrl test

hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv, hw/top_earlgrey/dv/tests/chip_base_test.sv, sw/device/lib/testing/flash_ctrl_testutils.h
sync up between c and sv using flash device can causes misbehavior with real flash model.
Add temporary fix to `chip_sw_sysrst_ctrl_ulp_z3_wakeup` and create a note to flash_ctrl_testutils.h
=> [chip,dv] update test with multiple test phases

sw/device/lib/base/BUILD, sw/device/lib/base/global_mock.h, sw/device/lib/base/global_mock_unittest.cc
This commit changes the implementation of GlobalMock, deferring downcasting `this` to the derived class until the derived class's constructor has returned.
It also adds a regression test that compiles with UBSan.
=> [sw] Fix UB downcast in GlobalMock

sw/device/lib/dif/autogen/dif_adc_ctrl_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_alert_handler_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_aon_timer_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_csrng_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_edn_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_entropy_src_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_flash_ctrl_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_gpio_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_hmac_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_i2c_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_keymgr_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_kmac_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_otbn_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_otp_ctrl_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_pattgen_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_pwrmgr_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_rv_timer_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_sensor_ctrl_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_spi_device_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_spi_host_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_sysrst_ctrl_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_uart_autogen_unittest.cc, sw/device/lib/dif/autogen/dif_usbdev_autogen_unittest.cc, util/make_new_dif/templates/dif_autogen_unittest.cc.tpl
I also regenerated the files in sw/device/lib/dif/autogen/:
util/make_new_dif.py --mode=regen --only=autogen
This commit fixes errors like the following:
```
sw/device/lib/dif/autogen/dif_gpio_autogen_unittest.cc:158:33: warning: left shift count >= width of type [-Wshift-count-overflow]
158 |   const uint32_t irq_mask = (1u << num_irqs) - 1;
```
=> [dif] Fix UB bitshift in autogenerated tests

hw/ip/tlul/generic_dv/env/seq_lib/xbar_random_vseq.sv, hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ec_rst_l_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv, hw/top_earlgrey/dv/tests/chip_base_test.sv, sw/device/lib/testing/flash_ctrl_testutils.h, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c
Following closed source test failures are fixed
- chip_sw_sram_ctrl_scrambled_access_*
- xbar_stress_all*
- chip_sw_sysrst_ctrl_ulp_z3_wakeup
- chip_sw_sysrst_ctrl_ec_rst_l
=> [earlgrey_es,chip,dv] closed source regression fix ver_118

sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/io/jtag.rs, sw/host/opentitanlib/src/test_utils/load_sram_program.rs, sw/host/opentitanlib/src/util/openocd.rs, sw/host/tests/chip/jtag/src/openocd_test.rs
Define all GPRs and more CSRs and use `strum` macro to generate the `name` function.
Split from #18908
=> [opentitanlib] define more GPRs and CSRs

sw/device/silicon_creator/lib/base/chip.h, sw/device/silicon_creator/lib/boot_svc/BUILD, sw/device/silicon_creator/lib/boot_svc/boot_svc_header.h
This PR adds a definition for the common header that will be used by all boot services messages.
See #19130 for details.
=> [sw/silicon_creator] Add boot_svc_header.h

hw/dv/sv/uart_agent/uart_logger.sv, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_uart_tx_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
To enable uarat_logger, we need a sequence to invoke uart agent and enable tx path.
=> [chip,dv] add uart_tx only sequence

hw/dv/sv/sec_cm/prim_count_if.sv, hw/dv/sv/sec_cm/prim_double_lfsr_if.sv, hw/dv/sv/sec_cm/prim_onehot_check_if.sv, hw/dv/sv/sec_cm/prim_sparse_fsm_flop_if.sv, hw/top_earlgrey/dv/env/flash_ctrl_host_gnt_fault_if.sv, hw/top_earlgrey/dv/env/rstmgr_cnsty_fault_if.sv
These interfaces create too much unnecessary info in the `initial` block. 
Adjust verbosity to HIGH to reduce log
=> [chip,dv] adjust verbosity for full chip debug

hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_raw_unlock_vseq.sv
Previous fix (#19074) didn't have enough delay to
complete switching clock. At delay w.r.t aon clock.
=> [chip,dv] rom lc raw unlock fix

apt-requirements.txt, util/site/deploy.sh, util/site/post-build.sh, util/site/site-builder/cloudbuild-deploy-docs.yaml, yum-requirements.txt
This reduces the payload size of these files to approximately 7% of the uncompressed size, which increases the usability of the site on low-bandwidth connections.
I've tested this on [staging.opentitan.org](staging.opentitan.org) and works well. (currently serves the indexes compressed without issue).
=> [util,site] Serve elasticlunr search index files compressed with brotli

sw/device/tests/sim_dv/all_escalation_resets_test.c
0 ping timeout value can causes spurious alert
when alert event takes long enough to expire ping timer. 
Increase ping timeout value to make sure ping timeout happens after expected alert event.
=> [chip,dv] increase ping timeout value for all_escalation_resets_test

hw/top_earlgrey/dv/chip_sim_cfg.hjson
Add a new build_mode requires cov_cfg files associate with the build mode.
=> [chip,dv] add missing cov_cfg_file for a new build_mode

sw/device/lib/dif/dif_spi_host.c, sw/device/lib/dif/dif_spi_host.h, sw/device/lib/dif/dif_spi_host_unittest.cc, sw/device/lib/testing/spi_flash_emulator.c, sw/device/lib/testing/spi_flash_testutils.c, sw/device/lib/testing/spi_flash_testutils.h, sw/device/tests/BUILD, sw/device/tests/sim_dv/spi_passthrough_test.c, sw/device/tests/spi_host_flash_test_impl.c, sw/device/tests/spi_host_flash_test_impl.h, sw/device/tests/spi_host_gigadevice1Gb_flash_test.c, sw/device/tests/spi_host_gigadevice256Mb_flash_test.c, sw/device/tests/spi_host_macronix_flash_test.c, sw/device/tests/spi_host_winbond_flash_test.c
This PR:
- Refactor the DIF spi_host to allow the use of 4 lanes for the opcode section.
- Add a new spi flash test for a gigadevice flash of 1Gb.
=> Spi host flash tests

BLOCKFILE
The M2.5.2 milestone is over and we created the `earlgrey_es` branch. Hence, we lift the RTL embargo on master so that development can continue.
=> [BLOCKFILE] remove RTL blockers on master

sw/device/silicon_creator/lib/boot_data.c, sw/device/silicon_creator/lib/boot_data_functest.c, sw/device/silicon_creator/lib/boot_data_unittest.cc, sw/device/silicon_creator/lib/boot_svc/BUILD, sw/device/silicon_creator/lib/boot_svc/boot_svc_header.c, sw/device/silicon_creator/lib/boot_svc/boot_svc_header.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_header_unittest.cc, sw/device/silicon_creator/lib/drivers/hmac.c, sw/device/silicon_creator/lib/drivers/hmac.h, sw/device/silicon_creator/lib/drivers/hmac_functest.c, sw/device/silicon_creator/lib/drivers/hmac_unittest.cc, sw/device/silicon_creator/lib/drivers/mock_hmac.cc, sw/device/silicon_creator/lib/drivers/mock_hmac.h, sw/device/silicon_creator/lib/sigverify/rsa_verify_functest.c
This PR adds `boot_svc_header_init()` for initializing the header of a boot services message.
See #19130 for details.
=> [sw/silicon_creator] Add boot_svc_header_init()

third_party/go/deps.bzl
When building OT from an ARM-based system, e.g., Apple silicon, bazel fails out with the following error message:
```
rschilling@ubuntu:~/opentitan-integrated$ bazel build //hw:verilator
INFO: Repository go_sdk instantiated at:
/home/rschilling/opentitan-integrated/WORKSPACE:29:8: in <toplevel>
/home/rschilling/opentitan-integrated/third_party/go/deps.bzl:13:20: in go_deps
/home/rschilling/.cache/bazel/_bazel_rschilling/294f71981fe1f7ffbbc1298f58c32d5e/external/io_bazel_rules_go/go/private/sdk.bzl:129:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
/home/rschilling/.cache/bazel/_bazel_rschilling/294f71981fe1f7ffbbc1298f58c32d5e/external/io_bazel_rules_go/go/private/sdk.bzl:116:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_sdk':
Traceback …
```
=> Add go dependencies for ARM64

hw/ip_templates/alert_handler/doc/theory_of_operation.md.tpl, hw/top_earlgrey/ip_autogen/alert_handler/doc/theory_of_operation.md
The theory of operation document referenced a particular ~instance's~ generated core's parameters in a table. Change the table header to not explicitly refer to Earl Grey and populate some of the values from template parameters.
Note: The conversion to Mako template caused lines beginning with `#` to become comments, so I have changed the syntax to use the HTML variant.
=> [alert_handler] Convert theory of operation to template

sw/device/silicon_creator/lib/BUILD, sw/device/silicon_creator/lib/bootstrap.c, sw/device/silicon_creator/lib/bootstrap.h, sw/device/silicon_creator/rom/BUILD, sw/device/silicon_creator/rom/bootstrap.c
This behavior-preserving refactor moves the implementation of ROM bootstrap into a common library for use by ROM and ROM_EXT. This will support the implementation of ROM_EXT Recovery.
Note to reviewers: this is significantly easier to read one commit at a time. I was careful to preserve the original history of rom/bootstrap.c when I moved it to ~reflash.c~ lib/bootstrap.c, but looking at the PR as a whole obscures the actual changes.
Issue #19151
=> [sw/silicon_creator] Refactor ROM bootstrap into a common lib

util/site-dashboard/dashboard.js
Currently the dashboard is unreadable because dark theme defaults to light text color.
=> [site] Fix dashboard in dark theme

site/landing/assets/scss/_boxes.scss, site/landing/assets/scss/_variables.scss
Currently there is no-feedback that these blocks are interactive. Style when hovered to give the user more feedback that they are indeed buttons.
=> [site] Add hover styling to the tiles on the Docs homepage

rules/fusesoc.bzl, util/BUILD, util/fusesoc_build.py
Add a py_binary shim that modifies the PATH environment variable to hold the bazel-provided Python interpreter directory first, so /usr/bin/env will point to it for the shebang method of running Python scripts. Add the entire set of packages from ot_python_deps as deps for that shim, so they're available to any generator fusesoc might call.
=> [tools] Use bazel-provided Python for fusesoc subprocesses

.bazelrc, third_party/crt/repos.bzl
The major change in v0.4.6 is that features from #12553 are now enabled by default. With that change, we no longer need to force-enable those features in .bazelrc. This commit deletes the relevant --features lines from .bazelrc.
The CRT release:
https://github.com/lowRISC/crt/releases/tag/v0.4.6
=> [bazel] Bump CRT dependency to v0.4.6, clean up .bazelrc

hw/top_earlgrey/dv/env/seq_lib/chip_sw_csrng_lc_hw_debug_en_vseq.sv
chip tb cfg.clk_rst_vif.clk can be varied and drifted in closed source env.
Not always good for sampling event. replace this with a constant time step.
=> [chip,dv] change sampling clock for closed source test

hw/top_earlgrey/dv/env/seq_lib/chip_sw_otp_ctrl_vendor_test_csr_access_vseq.sv, sw/device/tests/sim_dv/otp_ctrl_vendor_test_csr_access_test.c
When real vendor test happens in closed source test, it can collide with tlul transactions. 
Add wait event to avoid such collisions.
=> [chip,dv] update otp_ctrl_vendor_test with closed source ip

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
Without this change, the following test fails when CDC is enabled:
```
./util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson \
-i otbn_alu_bignum_mod_err --fixed-seed 123 \
--waves shm --run-only
```
It turns out that the failure is because it takes too long to get URND data from the EDN. Looking at the waves, the timeout arrived when we were partway through the first of three EDN requests.
If we wanted to make the test more robust here, we'd have to wait a fixed time for each EDN request to come up and then allow the test environment an arbitrary time to respond. But I don't expect this to change again, so let's do the simple, silly fix for now.
This fixes one of the failure modes tracked in #19045 ("Timeout waiting for secure wipe, timeout value too short").
=> [otbn,dv] Tweak length of time to wait for reset

util/topgen/strong_random.py
Trying to run this file through a type checker, it noticed that the original code misused the `all()` function, to the extent that I don't believe it could ever have worked. The new code does what I think was intended.
@vrozic: I think you wrote the original version of this code. Would you mind taking a quick look to check that this rewrite is what you'd expect?
=> [topgen] Fix types in test_runs() code

hw/ip/otbn/dv/otbnsim/sim/insn.py, util/design/mubi/prim_mubi.py, util/reggen/access.py, util/reggen/gen_json.py, util/reggen/gen_selfdoc.py, util/reggen/register.py
Fix some mypy errors in the reggen library. It looks like the version of MyPy that we're using in CI at the moment isn't new enough to notice the problems, so we won't really see much change from this commit. However, these changes fix things with 1.0.1 (the latest release), which spat out lots of messages without them.
Getting things happy again is mostly a case of adding some types to guide the tool so that it knows what's going on. There's also a small re-write in `gen_selfdoc.py`: there, the `doc_tbl_head` function used an optional `int` as a way of encoding a bool. This seemed a bit silly (and hard to encode!), so I've switched it to use `True`/`False` instead.
Finally, we fix a type error in `register.py`, where the code was missing some parentheses and testing a function (rather …
=> [reggen] Make reggen library MyPy-clean

sw/device/silicon_creator/lib/base/chip.h, sw/device/silicon_creator/lib/boot_svc/BUILD, sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.c, sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_empty_unittest.cc, sw/device/silicon_creator/lib/boot_svc/mock_boot_svc_header.cc, sw/device/silicon_creator/lib/boot_svc/mock_boot_svc_header.h
This PR adds the empty boot services message that can be used to clear the boot services area in the retention SRAM.
This message type can also be considered a template for the remaining message types.
See #19130 for details.
=> [sw/silicon_creator] Add empty boot services message

python-requirements.txt
The `lxml` package is not a direct dependency of the OT project, rather it is a transitive dependency. Since it is a transitive dependency, it was not pinned to a specific version. As a result, a newer version was pulled down onto our CentOS-based infrastructure that runs the nightly regressions. The newer version was incompatible with CentOS7, and therefore wiped out our nightly regressions. This makes the last known compatible version a direct dependency of the project now to fix the broken nightly regressions.
=> [python] fix package dep that is incompatible with nightly infra

hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, util/topgen.py
Option `--hjson-only` was removed from `topgen.py` long time ago in https://github.com/lowRISC/opentitan/commit/66f7ae29795bec0831b872a7171b0f6921371cb7 but it is still listed in hjson files. This PR removes it from the header template in topgen and updates the autogenerated file.
=> [topgen] Update hjson headers

hw/ip/spi_device/rtl/spi_device_reg_top.sv, util/reggen/reg_top.sv.tpl
This patch fixes cases where read-only and writable fields are mixed in a single register, whereby the hwext register QE would have been tied to 0 previously due to the logical AND of all field QEs.
The patch ignores field QEs that are always 0 when calculating the register QE, except in the case where all fields are RO.
Fixes #19127.
CC @meisnere
=> [regtool] Fix QE assignment bug

hw/ip/prim/README.md
This expands to all the keys that contain 'prim' in `ot-nightly-results.js` (Currently 5)
@GregAC was there any reason not to add this the first time around? Just to double-check. Thanks
=> [doc] Add the block-dashboards to the LR primitives page

hw/ip/aes/dv/env/aes_env_cfg.sv, hw/ip/aes/dv/env/aes_message_item.sv, hw/ip/aes/dv/env/seq_lib/aes_manual_config_err_vseq.sv, hw/ip/aes/dv/tests/aes_config_error_test.sv
This is required for lowRISC/OpenTitan#19025 .
=> [aes, dv] fix aes_manual_config_err sequence

hw/ip/aes/dv/aes_base_sim_cfg.hjson, hw/ip/aes/dv/env/seq_lib/aes_alert_reset_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_reseed_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_stress_vseq.sv
The changes in this PR should be totally uncontroversial as the functionality of the sequences isn't changed. But this PR prepares these sequences for enabling the stress_all(_with_rand_reset) tests.
This is related to #19025.
=> [aes, dv] Prepare test sequences for enabling stress_all(_with_rand_reset) tests

hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_common_vseq.sv, hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv, hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_state_failure_vseq.sv, hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_state_post_trans_vseq.sv, hw/ip/lc_ctrl/dv/tb.sv, hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_kmac_if.sv
Tying this signal off to zero will eliminate the CDC issue. Note that this will functionally not impair the design - the error signal would otherwise only be set to 1 in case the interface FSM is glitched into an invalid state.
See #19200 for more information.
=> [lc_ctrl/eco] Fix ECO issue inside lc_ctrl

sw/device/tests/otp_ctrl_smoketest.c
Last dai program misses `wait for dai finish`.
Add wait for dai_finish before next otp_ctrl transactions.
=> [chip,dv] Add wait for dai_finish

hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
Increase upper bound for cycles to wait in IbexIcacheScrambleKeyRequestAfterFenceI_A.
=> [rtl/rv_core_ibex] Fix RTL assertion for CDC

sw/device/sca/kmac_serial.c, sw/device/sca/sha3_serial.c
Previously, kmac_disable_masking() did not correctly initialize the full KMAC config struct. As a result of using uninitialized memory, it could happen that the endianness when reading the state got changed which completely broke all SHA3 captures.
This commit fixes that by creating a static KMAC config which, for the sake of documentation, initializes all relevant struct variables to the correct value. kmac_disable_masking() then just modifies the variables required to switch off the masking.
=> [sca, sha3, kmac] Fix SHA3 captures by properly initializing KMAC config

sw/host/hsmtool/src/commands/object/show.rs, sw/host/hsmtool/src/util/attribute/attr.rs, sw/host/hsmtool/src/util/attribute/data.rs, sw/host/hsmtool/src/util/attribute/mod.rs
When showing objects, manually redact private key components.
The HSM normally redacts these, however, if you have extractable keys, the show command might dump their contents to the console.  By default, we'll redact these components to avoid accidentally exposing private key material.
=> [hsmtool] Improve attribute redactions

hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_base_vseq.sv, hw/top_earlgrey/dv/tests/chip_base_test.sv
cpu_init is called from chip_sw_base_vseq::body.
If there is a task taking large latency, this can causes to call cpu_init much later 
then reset de-assert and creates false errors. 
Add early cpu init option to avoid these false errors
=> [chip,dv] Add early cpu init option

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ec_rst_l_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_outputs_vseq.sv, sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c
These tests need some additional wait cycles for synchronizers to percolate.
=> [dv,top_level] Fix a couple top-level sysrst_ctrl tests for CDC

hw/ip/usbdev/rtl/usb_consts_pkg.sv, hw/ip/usbdev/rtl/usb_fs_rx.sv
Trigger EOP response when the receiver sees a PRE PID. Because the preamble is not a full packet and does not terminate with an EOP until after the low-speed transmission is complete, stop processing the packet immediately after receiving the PID. The low-speed portion of the packet will trigger error conditions otherwise.
Resolves #19148
=> [usbdev] Truncate RX after receiving a PRE PID

util/regtool.py
Using a simple markdown to html converter on the markdown documentation (like the following) isn't ideal, because wavejson isn't rendered and *unique kebab case* ids aren't automatic added to headings.
```sh
cargo install pulldown-cmark
util/regtool.py -d ./hw/ip/aes/data/aes.hjson | pulldown-cmark  -T > /tmp/aes.html
```
As the html backend is still in the codebase, we may as well as expose it for those who want to use it. This PR adds `--doc-html-old`:
```sh
util/regtool.py --doc-html-old ./hw/ip/aes/data/aes.hjson > /tmp/aes.html
```
=> [reggen] Add access to the old html renderer

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_intg_err_vseq.sv
The first of the two commits is not too important: it just makes a vseq fail more understandably if something goes wrong. The second commit is the core of the change: it ensures that `start_running_otbn` has the behaviour that I think I originally intended, and that the vseqs using it expect! :-)
=> Fix logic in start_running_otbn to get some CDC tests working

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_intg_err_vseq.sv
When CDC is enabled, secure wipe can take a bit longer than otherwise, because the EDN takes longer to send new entropy. Lengthen this wait to give it time to complete.
=> [otbn,dv] Wait longer for secure wipe in otbn_intg_err_vseq

hw/ip/otbn/dv/tracer/rtl/otbn_trace_if.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_alu_bignum_mod_err_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_controller_ispr_rdata_err_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_mac_bignum_acc_err_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_mem_gnt_acc_err_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_pc_ctrl_flow_redun_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_bignum_intg_err_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
These are all minor tweaks that silence Xcelium warnings when building OTBN DV code. There's nothing that will change behaviour, but it makes it a bit easier to read through a compilation log when something else has gone wrong.
=> Minor lint fixes in OTBN DV code

hw/top_earlgrey/dv/chip_sim_cfg.hjson
Test has been timing out with the specified 1ms bus frame; extend timeout until such time as the DPI model can perform multiple control transfers per bus frame.
=> [usbdev_dpi] Extend timeout to allow for 1ms bus frame

sw/device/lib/testing/usb_testutils_controlep.c, sw/device/lib/testing/usb_testutils_controlep.h
Delay configuration setting until acknowledged; test code may then be confident that the control transfer has completed and the host will not fault the configuration whilst top-level test code proceeds to initialize higher-level state.
Support reconnection and reconfiguration; helps with testing, and is required for testing disconnection, bus resets etc.
=> [usb_testutils] Endpoint Zero refinements

.github/workflows/pr_lint_review.yml
Continue #19239 
The first attempt doesn't fix the issue because chipsalliance/verible-linter-action upgrades the downgraded package back up to the broken version.
So also update /etc/apt/preferences.d to prevent these broken versions from being selected.
Tested here: https://github.com/nbdd0121/opentitan/actions/runs/5602237791/jobs/10247206074?pr=1
=> [ci] curl downgrade, attempt 2

hw/top_earlgrey/dv/env/ast_supply_if.sv
Recent PR (https://github.com/lowRISC/opentitan/pull/19198 ) causes compile error in GLS.
Fixed compile error for earlgrey_es.
=> [earlgrey_es,chip,dv] closed source GLS compile error fix

util/design/sparse-fsm-encode.py
This PR fixes the check for if a randomly-generated encoding is the inverse of an existing encoding. The `~` operator in Python treats the inverse as a 2's complement number, so equality is never true. Instead, we can XOR with 1's to invert.
```python
int('1011', 2) == ~int('0100', 2)                  # False
int('1011', 2) ^ ((1 << 4) - 1) == int('0100', 2)  # True
```
Also, this PR instantiates a separate Random object instead of using the global `random` singleton to prevent interference from other libraries.
=> [sparse-fsm-encode] Fix check for complementary encodings

ci/scripts/test-airgapped-build.sh
The airgapped build test was building too many targets which caused CI resources to be exhausted.
=> [ci] reduce targets built in airgapped setup

sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c
The failing tests are chip_sw_pwrmgr_random_sleep_all_wake_ups and chip_sw_pwrmgr_deep_sleep_all_wake_ups. The underying problem is explained in #19234.
=> [dv,top-level] Fix CSR write ordering exposed by CDC instrumentation

ci/scripts/rust-format.sh, quality/BUILD.bazel, rules/quality.bzl, rules/scripts/rustfmt.template.sh
We have already switched Rust building to Bazel, and currently the only place where one needs to have rust toolchain installed is to run `rustfmt`.
=> [bazel] Add `//quality:rustfmt_fix` and switch CI to use `//quality:rustfmt_check`

hw/ip/aes/pre_dv/aes_cipher_core_tb/README.md, hw/ip/aes/pre_dv/aes_cipher_core_tb/aes_cipher_core_tb.core, hw/ip/aes/pre_dv/aes_cipher_core_tb/cpp/aes_cipher_core_tb.cc, hw/ip/aes/pre_dv/aes_cipher_core_tb/rtl/aes_cipher_core_tb.sv
This is mainly useful to perform some basic verification of, e.g., a synthesized version of the AES cipher core and/or to get an understanding of how to interface the core, e.g., for verifying security properties.
This is related to lowRISC/OpenTitan#19091.
=> [aes, pre_dv] Add very basic scratch Verilator testbench for cipher core

sw/device/lib/testing/usb_testutils_controlep.c, sw/device/lib/testing/usb_testutils_simpleserial.c
Fix #19190
Example of broken test: https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=121584&view=logs&j=1a082425-b540-5a45-e7d8-d21f721d187f&t=3583c471-2f95-531c-7145-0be3f8c0aecd
=> [device] make module IDs unique in USB test

hw/data/common_project_cfg.hjson, hw/ip/tlul/generic_dv/xbar_sim_cfg.hjson, util/dvsim/SimCfg.py
This was broken by the new documentation site structure.
This fix works for all blocks except the primitives, as some do not have testplans, and some have testplans which we do not currently render on the site. This can be fixed as a follow-up task.
Note. that the 'testplan_doc_path' key is a slighly hacky way of resolving the testplan path when a sim_cfg is imported by another one.
=> [doc,report] Fix the dvsim report links to the testplans

util/get_workspace_status.sh
This changes fix bug causing generating incorrect
`BUILD_GIT_VERSION` string for unannotated tags.
As result of this changes command `make -C hw topgen_rust_pkg` 
now should generated files with correct version stamp.
To test this change please compare output of command below,
with and without applying this changes.
Command: `util/get_workspace_status.sh`
=> [util]: Fix tag support for get_workspace_status.sh

hw/dv/sv/cip_lib/cip_base_env.sv, hw/dv/sv/tl_agent/tl_reg_adapter.sv
The name of tl_reg_adapter (parameterized class) cannot be captured by gtn macro. 
Replace with plain string based name.
Assign correct agent name to tlul monitor.
=> [tlul,dv] assign proper name for visibility

sw/device/lib/crypto/impl/rsa/BUILD, sw/device/lib/crypto/impl/rsa/rsa_signature.c, sw/device/lib/crypto/impl/rsa/rsa_signature.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/rsa_2048_signature_functest.c
Only PKCS#1 v1.5 padding is implemented for now; some scaffolding for PSS is there, but the actual implementation will be a follow-up.
=> [crypto] Add RSA-2048 signing and a few basic functional tests.

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_intg_err_vseq.sv
This PR has two commits. The first also appears in #19222 (which also needs it). The interesting bit of this PR is the second commit, which fixes an occasional failure in the `otbn_rf_base_intg_err` test when CDC is enabled. Its commit message is:
**[otbn,dv] Wait long enough for RF read in otbn_rf_base_intg_err_vseq**
This vseq wants to start an OTBN run and then, at some time after the
run has started, corrupt the next read of the base register file. Of
course, this needs a bit of a wait: we need to wait until the base
register file is being read. This wait is usually very short (we read
from the RF with most instructions) but is rather longer if we happen
to be stalled reading from RND!
The stall for a RND read is longer when CDC is enabled, and pushed us
over the 2000 cycle max wait. …
=> Otbn rf base intg err

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_zero_state_err_urnd_vseq.sv
The problem is that the design RTL contains assertions like `InitSecWipeNonZeroBaseRegs_A`, which assert that each register has been initialised to a nonzero value during secure wipe. This is reasonable, but isn't true in this test: that's kind of the point!
=> [otbn,dv] Disable RTL assertions in otbn_zero_state_err_urnd test

hw/dv/sv/push_pull_agent/push_pull_agent_cfg.sv, hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_intg_err_vseq.sv, hw/ip/otbn/rtl/otbn_core.sv
This change fixes a failure that you could see when CDC was enabled by running:
```
util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -i otbn_rf_base_intg_err --fixed-seed 123
```
There were actually two problems. The first failure was caused by the fact that we weren't waiting long enough in the vseq for the RTL's status to become Locked. This is because the secure wipe takes longer with CDC and the existing 400 cycle wait wasn't enough. Fixing this isn't too hard: you just have to track the phases of the secure wipe more carefully.
Fixing that turned out not to be enough! We've also got some logic that does a similar wait in `otbn_scoreboard.sv`. Rather than duplicating the "wait for secure wipe" logic yet again, I just bumped the timeout. If this turns out to be fragile, we …
=> [otbn,dv] Wait more carefully for secure wipes, fixing CDC errors

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_ooo_vseq.sv
Update word size / location constraint for non-otf test. (flash_ctrl_invalid_op) 
Update flash_init to the right value after post_start reset.
=> [flash_ctrl,dv] clean up block regression

hw/top_earlgrey/data/top_earlgrey.hjson
This PR:
* Adds explicit commas where Hjson implicitly takes a newline to be a comma.
* Fixes a couple of minor typos in comments.
This PR only covers `top_earlgrey.hjson`.
=> [hjson] Add explicit commas to top_earlgrey.hjson

sw/device/lib/crypto/impl/rsa/rsa_keygen.c, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/rsa_2048_keygen_functest.c
Generate a key and then check that we can verify a signature created with it.
This test also prints out OTBN instruction counts and Ibex cycle counts for RSA keygen, which can be useful for evaluating future performance improvements. :warning: RSA keygen is slow, so this test takes several minutes on an FPGA. :warning:
=> [crypto] Add a functional test for RSA-2048 key generation.

sw/device/lib/crypto/impl/aes_gcm/BUILD, sw/device/lib/crypto/impl/aes_gcm/ghash_unittest.cc
This helps with quick feedback/debugging for the GHASH operation, which is Ibex-only. I found it useful to write this when debugging an issue that came up as I was working on https://github.com/lowRISC/opentitan/issues/18333, and it seemed worth merging.
=> [crypto] Add unit tests for AES-GCM GHASH.

hw/dv/sv/alert_esc_agent/alert_esc_agent_cfg.sv, hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
flash_ctrl_mp_regions test generates recov_err event in the loop. 
If test uses normal alert responder, it can be missed back to back alert 
because responder has ack delay and stable ack period.
Add 'fast rcvr mode' to use minimum value for those parameters.
=> [flash_ctrl,dv] use fast alert responder for back to back error event

azure-pipelines.yml, ci/gcp-upload-bitstream-template.yml, ci/scripts/get-bitstream-fragment-dir.bzl, ci/scripts/get-bitstream-fragment-files-relative.bzl, ci/scripts/make_distribution.sh, ci/scripts/prepare-cached-bitstream.sh, ci/scripts/run-fpga-cw310-tests.sh, hw/bitstream/BUILD, hw/bitstream/vivado/BUILD, rules/bitstreams.bzl, rules/scripts/BUILD, rules/scripts/bitstreams_manifest.example.json, rules/scripts/bitstreams_manifest.schema.json, rules/scripts/bitstreams_workspace.py, rules/scripts/bitstreams_workspace_test.py, util/py/scripts/BUILD, util/py/scripts/bitstream_cache_create.py, util/py/scripts/bitstreams_fragment_from_manifest.py
...and update the schema to invert the hierarchy and group files under designs.
The commits create a notion of "manifest fragments," which are essentially conforming directories with a manifest and the files for a single design. These fragments combine to create a full cache entry, where all desired designs are collected together into a tarball suitable for upload. Bazel targets are made aware of these fragments via the `BitstreamManifestFragmentInfo` provider, which contains all the relevant information to process them.
The cache entry is broken into fragments here to enable using the current CI flow, where bitstreams may be built on independent agents / bazel services and may be passed to downstream jobs as through they were part of a bitstreams cache. In addition, the cache entry to be …
=> [bitstreams] Add rules to generate manifests

hw/ip/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_err_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_ack_consistency_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_host_grant_err_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Kill on-going assertion thread after detecting fatal error to make sure test run to complete.
=> [flash_ctrl,dv] fix phy_host_grant_err test

azure-pipelines.yml
The CI job for chip_earlgrey_cw310_hyperdebug was mistakenly left without the same updates as chip_earlgrey_cw310. Publish the build-bin.tar file already created.
=> [ci] Fix bitstream artifact generation for hyperdebug

hw/top_earlgrey/dv/env/chip_if.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_ctrl_integrity_check_vseq.sv, sw/device/tests/aon_timer_irq_test.c, sw/device/tests/power_virus_systemtest.c
Hi,
This PR is fixing some failures came from regressions in gate-level:
* power-virus & jtag-debug tests : add some undefined paths for GL in the chip_if & small change to the power-virus C test.
* rom_ctrl integrity check test : Add small delay between rom_ctrl_done assertion and the check of rom_ctrl_good to avoid states where the done is asserting in parallel to the deassertion of the good signal.
* aon_timer_irq : increase the overhead value to match the change in the timing between the OS and the CS.
Thanks!
=> [dv/GL] Regression fixes for gate level

hw/bitstream/vivado/BUILD
The bitstreams cache work included an errant change to the release fileset, one that picked out the manifest fragment outputs for the release instead of the ordinary files from the bitstream build. Revert that change, so the release build may continue as it was.
=> [release] Revert hyperdebug release back to ordinary files

ci/gcp-upload-bitstream-template.yml
The bitstream cache creation script requires Python 3.9 for its type hints, but CI doesn't have it natively. Use the bazel-built binary instead of CI's system Python.
Also allow the GCP upload script to fail, so bad uploads do not enter the cache.
=> [ci] Fix Python incompatibility and allow GCP uploads to fail

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv, sw/device/lib/testing/flash_ctrl_testutils.c, sw/device/lib/testing/flash_ctrl_testutils.h, sw/device/tests/sim_dv/sysrst_ctrl_ulp_z3_wakeup_test.c
This test used backdoor overwrites but the mechanism broke when enabling CDC instrumentation: there were many problems with the overwrites, most important they don't flush read buffers, so the test often got stale data. The fix is to flush the read buffers before each attempt to read new data.
=> [top-level,tests] Fix chip_sw_sysrst_ctrl_ulp_z3_wakeup

ci/scripts/test-airgapped-build.sh
This CI job was running out of space again. This a temporary fix until we can figure out why this is causing an issue.
=> [ci] further reduce set of items built by airgapped test job

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ec_rst_l_vseq.sv, sw/device/lib/testing/flash_ctrl_testutils.c, sw/device/lib/testing/flash_ctrl_testutils.h, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c, sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c, sw/device/tests/sim_dv/sysrst_ctrl_outputs_test.c, sw/device/tests/sim_dv/sysrst_ctrl_ulp_z3_wakeup_test.c
This function waits until a flash memory location changes value. It flushes the read buffers before each read to account for SV updates done via backdoor overwrites.
Fix some tests to use this API.
=> [dv,flash_ctrl_testutils] Fix flash_ctrl_testutils_backdoor_wait_update

site/block-diagram/earlgrey.html
In the Earl Grey block diagram the `<h3>` tags were matched with `</h2>` I changed the end tag to be `</h3>`.
=> [site] Match header tags in block diagram

sw/device/silicon_creator/lib/boot_data.c, sw/device/silicon_creator/lib/boot_data.h, sw/device/silicon_creator/lib/boot_data_functest.c, sw/device/silicon_creator/lib/boot_data_unittest.cc, sw/device/silicon_creator/lib/boot_svc/BUILD, sw/device/silicon_creator/lib/boot_svc/boot_svc_primary_bl0_slot.c, sw/device/silicon_creator/lib/boot_svc/boot_svc_primary_bl0_slot.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_primary_bl0_slot_unittest.cc
Adds the message types for the Select Primary BL0 Slot ROM_EXT boot service messages.
=> [sw/silicon_creator] Add Primary BL0 Slot message types

hw/ip/kmac/rtl/kmac_entropy.sv
This is a small follow-up PR to #19248 with two changes:
- Refine an SVA. I found this after investigating a test failure of a full regression.
- Advance the LFSR during reseeding when the Keccak core consumes the randomness. We did already mark the randomness as being consumed before but the LFSR didn't get advanced. This is very minor.
=> [kmac, rtl] Very minor tweaks around LFSR reseeding

doc/security/README.md, hw/ip/aes/README.md
This resolves lowRISC/OpenTitan#17280.
This is related to lowRISC/OpenTitan#16940.
=> [aes, doc] Mention option of implementing GCM with Ibex and bitmanip

hw/top_earlgrey/dv/env/chip_if.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwrmgr_deep_sleep_all_wake_ups_vseq.sv
Add a method in the chip interface for forcing and releasing adc_d_o signal.
Changed uvm_hdl_force with this method in a test vseq.
Because we do not use uvm_hdl_force in gate level environment and we needed a replacement.
=> [CL-adc]-Added a method for forcing adc_d_o signal.

util/tlgen/doc.py
This has been in the file since 2019 but causes our "Check CMDGEN Blocks" CI job to spit out confusing junk in its logs. Fortunately, it wasn't doing anything useful so we can just delete the line!
=> [tlgen] Remove an ancient "error" debug print

sw/device/silicon_creator/lib/base/chip.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_msg.h
Thanks to @milesdai's work in #19286 we can now add an assertion for `CHIP_BOOT_SVC_SIZE_MAX`.
This PR adds an X macro for ease of maintenance -- going forward we should add the new messages to this table.
=> [sw/silicon_creator] Update and add assertions for CHIP_BOOT_SVC_MSG_SIZE_MAX

ci/scripts/check-module-ids.sh, rules/quality.bzl, rules/scripts/BUILD, rules/scripts/modid_check.sh
The output of the module ID check in CI is unreadable because opentitantool prints too many useless messages.
This PR fixes this to only show errors. It also contains a small improvement to remove a temporary file used in a script.
=> Module id check improvements

python-requirements.txt
The `rich` package version was not compatible with the version of Python that is run in the nightly regressions (as these tests are run on CENTOS7 machines due to EDA tool requirements).
=> [python] make packages CENTOS7 compatible

azure-pipelines.yml
The sw_build job was missing many targets, as the build and test commands resolve wildcards very differently, even with --nobuild_tests_only.
=> [ci] Actually build all software in the sw_build job

util/reggen/gen_tock.py
Update the license header emitted into autogenerated files to be in the form acceptable to Tock's license checker.
=> [tock] Update license header in autogenerated files

hw/ip/prim/doc/prim_lfsr.md, hw/ip/prim/rtl/prim_lfsr.sv, util/design/README.md, util/design/get-lfsr-coeffs.py
At the moment prim_lfsr.sv uses two lists of feedback polynomials downloaded from two different sources, one for each LfsrType (GAL_XOR and FIB_XNOR). However, this is not necessary because each polynomial works equally well with either type. Moreover, some polynomials are the same in both lists (e.g. for LfsrDw = 12, 13, 14, 19, 27, 30, 37, 38).
To simplify the primitive, this PR removes the list downloaded from https://users.ece.cmu.edu/~koopman/lfsr/ and makes both lfsr types use the list obtained from 
https://www.xilinx.com/support/documentation/application_notes/xapp052.pdf
=> [prim_lfsr] Remove redundant list of LFSR_COEFF

hw/ip/prim/dv/prim_lfsr/prim_lfsr_tb.sv
Some prim_lfsr tests are currently only working with VCS but not with Xcelium. This commit modifies prim_lfsr_tb.sv to enable `prim_lfsr_gal_smoke`, `prim_lfsr_fib_smoke`, `prim_lfsr_gal_test` and `prim_lfsr_fib_test` to work in Xcelium simulations.
=> [prim lfsr] Replace randomize() calls with $urandom in prim_lfsr_tb

sw/device/lib/crypto/impl/rsa/rsa_keygen.c, sw/device/lib/crypto/impl/rsa/rsa_modexp.c, sw/device/lib/crypto/impl/rsa/rsa_modexp.h, sw/device/lib/crypto/impl/rsa/rsa_signature.c, sw/device/lib/crypto/impl/rsa/rsa_signature.h, sw/device/tests/crypto/rsa_2048_keygen_functest.c, sw/device/tests/crypto/rsa_2048_signature_functest.c
Previously, the RSA signature code had separate `finalize()` functions for each size of signature verification. Now, it will read the mode from OTBN and infer the correct size. This provides more safety against size mismatches and also an interface that better matches the top-level cryptolib API.
This commit also modifies the key generation routine to double-check the mode during `finalize()` as an extra sanity check/countermeasure.
=> [crypto] Modify RSA to infer the size of signatures.

sw/device/silicon_creator/lib/error.h, sw/device/silicon_creator/rom_ext/rom_ext.c
While reviewing #19286 I noticed that we are using the same errors as ROM in rom_ext.c. This PR adds two new enums `kErrorRomExtInterrupt` and `kErrorRomExtBootFailed` for ease of debugging.
=> [sw/silicon_creator] Add kErrorRomExtInterrupt and kErrorRomExtBootFailed

sw/device/silicon_creator/lib/boot_svc/BUILD, sw/device/silicon_creator/lib/boot_svc/boot_svc_min_bl0_sec_ver.c, sw/device/silicon_creator/lib/boot_svc/boot_svc_min_bl0_sec_ver.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_min_bl0_sec_ver_unittest.cc, sw/device/silicon_creator/lib/boot_svc/boot_svc_msg.h
Adds the messages for the [Set Minimum Required BL0 Security Version](https://github.com/lowRISC/opentitan/issues/19156) rom_ext boot service.
This is the first of two PRs, the second will implement the service in rom_ext.
=> [sw/silicon_creator] Add Set Miniumum Security Version service message

sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/app/config/mod.rs, sw/host/opentitanlib/src/app/config/servo_micro.json, sw/host/opentitanlib/src/backend/mod.rs, sw/host/opentitanlib/src/transport/hyperdebug/mod.rs, sw/host/opentitanlib/src/transport/hyperdebug/servo_micro.rs
Add support to perform the rescue operation with the Google servo micro debug device.
Some Chromebooks use a device called "Servo Micro" for gaining access to serial console and GPIO signals of the security chip and other chips inside it. As HyperDebug uses essentially the same USB protocol as Servo Micro, it requires very little effort to allow opentitantool to control a Servo Micro. (Opentitantool already has support for another similar Google debugging device, called C2D2.)
As future Chromebooks will have OpenTitan chips, which can be reached through this Servo Micro, and as opentitantool has some support for the bootstrap protocols of proprietary Google security chips, it will be quite useful to be able to use servo micro through opentitantool.
This PR adds this support.
Example …
=> [opentitantool] Add servo_micro interface support for rescue

hw/ip/flash_ctrl/data/BUILD, hw/ip/otp_ctrl/data/BUILD, hw/ip/rom_ctrl/data/BUILD, hw/top_earlgrey/ip/flash_ctrl/data/autogen/BUILD, rules/autogen.bzl, util/BUILD, util/reggen/gen_tock.py, util/reggen/ip_block.py, util/regtool.py
Some IP blocks have more than one register set.  `regtool` doesn't
understand there may be multiple multiple register blocks and it
generates constants for all of them and overlays their offsets (ie:
there may be multiple registers at offset 0).
1. Allow `regtool` to filter regblocks so that we can generate separate
outputs per register block.
2. Generate only the main reglbock for flash_ctrl, otp_ctrl and
rom_ctrl.
Note: this PR depends on #19341.  You need only review the last commit.
=> [reggen] Generate constants for only the main block

SUMMARY.md, doc/contributing/doc/README.md, doc/contributing/doc/example_ip_block.md, doc/contributing/style_guides/markdown_usage_style.md
Updated the markdown style guide to fit the new purer markdown (commonmark) documentation flow. All the changes have come from discussions I've had when reviewing PRs and setting up new documentation flow.
Updated the content of 'Markdown file format for IP module description' from the style guide and moved into it's own file (`doc/contributing/doc/example_ip_block.md`) .
Created a 'contributing to documentation' page. I will add to this in the future. It currently contains a summary of the documentation set up, as well as an explanation of the file structure and CMDGEN.
=> [doc] Updated markdown style guide and added documentation docs

hw/ip/clkmgr/dv/sva/clkmgr_lost_calib_ctrl_en_sva_if.sv
When the clocks loose calibration (flagged by the AST) the cycle counters in clkmgr get disabled. The delay between enabling counters and disabling them due to loss of calibration needs to go through a prim_reg_cdc on the path to enable it and another one to make the enable value visible to software. The previous number of wait cycles still left room for some failures.
=> [dv/clkmgr] Increase wait cycles in clkmgr_lost_calib_ctrl_en_sva_if

.bazelrc
The combination doesn't really work, mainly because ccache is trying to write to a cache file on a read-only file system. This isn't unreasonable though: the two programs are trying to do the same job!
Passing a "don't actually cache anything" flag like this to ccache seems to be the easiest way to tell things to work under Bazel without requiring the user to uninstall ccache from their computer.
Note that 141f6e3fd is also to do with ccache interaction. But that's specifically for OpenOCD. I *think* that this change probably means that the 141f6e3fd won't be necessary any more, but I haven't actually checked.
=> Disable ccache under Bazel

.github/workflows/pr_lint_review.yml
Switch from posting comments to use check annotation. This should reduce the noise of the lints.
Example:
* no comments in the conversation pane (just shows up as a failing check): https://github.com/nbdd0121/opentitan/pull/3 
* lints reported in the files changed pane: https://github.com/nbdd0121/opentitan/pull/3/files
=> [ci] switch lint report from comment to check annotation

util/design/BUILD, util/design/lib/BUILD, util/design/lib/common.py, util/design/lib/common_test.py, util/design/sparse-fsm-encode-test.py, util/design/sparse-fsm-encode.py
This PR adds unit tests for `sparse-fsm-encode.py` and the `get_hd` function it uses. Additionally, it does a refactoring to make the testing easier. The refactoring should preserve the behavior of this script.
The unit testing uncovered #19244.
I'm not sure if this is an issue we're worried about, but the unit tests also check for non-backwards-compatible changes that would prevent the generated constants from being reproduced. This has already happened before, for instance, in #8665. Commit f2c848c7e1f09018e4cae16d2b30ffd5eca6c3c2 changed the output of the script by not pre-populating the encoding array with the first random value, effectively discarding the first call to random. This is not inherently an issue, but it does means that encodings generated prior to this commit are not …
=> [sparse-fsm-encode] Refactor and add unit tests

sw/host/opentitantool/src/command/gpio.rs
"ignore_case" applies to enum arguments and such, which take a value to be compared against a list of valid values.  This boolean argument is present (without value) or not present, and it seems that putting "ignore_case" on it results in a runtime exception during parsing.
=> [opentitantool] Bool command line arg does not work with "ignore_case"

hw/dv/tools/dvsim/vcs.hjson
The "-deraceclockdata" flag changes the simulation model to always use sampled data values in flops.
=> [tools,vcs] Make flops use the sampled value of data to avoid races

sw/device/lib/ujson/example_roundtrip.c, sw/device/lib/ujson/rust/BUILD, sw/device/lib/ujson/rust/roundtrip_test.rs, sw/device/lib/ujson/ujson.c
Added CRC checks to the roundtrip test. Part of https://github.com/lowRISC/opentitan/issues/17496
Note:
1. There was a bug due to the `status_t` serialisation being handled by `uj->putbuf` directly. The current solution works but it may be nicer to use a dedicated ujson serialisation function:
```c
status_t ujson_serialize_status_t(ujson_t *uj, const status_t *value) {
// The module id is defined to be 3 chars long.
char mod[] = {'"', '\0', '\0', '\0', '"', ','};
int32_t arg;
const char *start;
bool err = status_extract(*value, &start, &arg, &mod[1]);
// strlen of the status code.
const char *end = start;
while (*end)
end++;
TRY(ujson_putbuf(uj, "{\"", 2));
TRY(ujson_putbuf(uj, start, (size_t)(end - start)));
TRY(ujson_putbuf(uj, "\"", 1));
TRY(ujson_putbuf(uj, ":", 1));
if (err) {
// All …
```
=> [ujson] Added crc checks to the roundtrip test

hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_prog_rma_wipe_err_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_rma_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_lcmgr_intg_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_path_intg_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_evict_vseq.sv
Following test regression errors are fixed
- flash_ctrl_rw_evict
- flash_ctrl_intr_rd_slow_flash
- flash_ctrl_invalid_op
- flash_ctrl_rd_path_intg
- flash_ctrl_hw_rma
- flash_ctrl_lcmgr_intg
=> [flash_ctrl,dv] regression cleanup

hw/dv/sv/mem_bkdr_util/mem_bkdr_util__sram.sv, hw/dv/sv/mem_bkdr_util/sram_scrambler_pkg.sv, hw/ip/sram_ctrl/dv/env/sram_ctrl_mem_bkdr_scb.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
The previous fix in #19332 was unfortunately flawed, since ecc errors were checked on the scrambled data, but it should really be done after descrambling it.
This checks for errors after descrambling, and improves the mem backdoor code organization in this area.
Fixes #19268
=> [dv/top-level] Fix sram data integrity error injection

sw/device/silicon_creator/lib/boot_data.c, sw/device/silicon_creator/lib/boot_data.h, sw/device/silicon_creator/lib/boot_data_unittest.cc
Moves the conversion from boot data V1 to V2 into `boot_data_read()`.
=> [sw/silicon_creator] Convert v1 boot data to v2 during read

sw/device/tests/crypto/BUILD, sw/device/tests/crypto/rsa_3072_verify_functest.c
The test did not initialize the entropy complex to auto mode, and it would exhaust the available, finite entropy generated during boot, leading to freezing and timeouts.
Fixes #16805
=> [test] Fix lack of entropy for wycheproof test

doc/guides/getting_started/src/SUMMARY.md
There shouldn't really be url in `SUMMARY.md` files.
One effect is the creation of `doc/guides/getting_started/src/https\:/opentitan.org/book/sw/device/silicon_creator/rom/doc/e2e_tests.html` when the docs are built.
https://github.com/lowRISC/opentitan/pull/17483#discussion_r1140195384
https://github.com/lowRISC/opentitan/pull/17656#discussion_r1146012195
=> [doc] Removed url from getting started `SUMMARY.md`

hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_lcmgr_intg_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_ack_consistency_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_prog_reset_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_wr_path_intg_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Following test failures have been fixed.
- flash_ctrl_rand_ops: update scoreboard memory with bank erase command
- flash_ctrl_intr_wr_slow_flash : increase timeout
- flash_ctrl_prog_reset : increase timeout
- flash_ctrl_lcmgr_intg : create false intg from random data
- flash_ctrl_wr_intg : Add op done between consecutive program operation
- flash_ctrl_phy_ack : Add selective alert check
- flash_ctrl_phy_arb : Add `calculate_expected_data` implementation
=> [flash_ctrl,dv] Regression fix week of 7 Aug 23

rules/quality.bzl, sw/device/lib/base/hardened.h, sw/device/lib/base/macros.h, sw/device/lib/base/memory.c, sw/device/silicon_creator/rom/rom.c
cfrantz@opentitan.org noticed that //quality:clang_tidy_check was failing. It turns out that Clang-Tidy was generating false positives, mostly about potentially uninitialized variables.
Brief timeline:
* In PR #18773, I temporarily removed Clang-Tidy's --warnings-as-errors flag until my work on C warning flags was complete (issue #12553).
* I attempted to fix these false positives in #18774 (never merged) by creating pure C definitions of the HARDENED* macros. That technique may have been workable, but it enabled the compiler to see through the analysis barrier for real builds, which would obviously be a problem.
* In PR #18719, I mistakenly brought back the --warnings-as-errors flag without fixing Clang-Tidy's false positives.
The main fix in this commit is to short-circuit the …
=> [sw] Eliminate false positives from Clang-Tidy

hw/dv/sv/cip_lib/cip_base_scoreboard.sv, hw/dv/sv/sec_cm/prim_onehot_check_if.sv, hw/ip/prim/rtl/prim_subreg_arb.sv
Set coverage option "at_least" besides "weigth" for items that won't be covered so they don't show up as coverage holes.
Disable coverage for unused signals in prim_subreg_arb.
Fixes #19404
=> [dv/cov] Fix coverage handling in some common items

rules/opentitan.bzl, sw/device/silicon_creator/manuf/tests/BUILD
At the moment, opentitan_binary produces a "<name>.elf" target with a platform constraint but it uses cc_binary on which we cannot define a transition. This means that any target that depends on such an ELF file will not trigger a transition and be built with the same platform (unless this rule defines a transition on its attributes). This is problematic for tests that needs to compile a tool with the host toolchain but build some artefact with the platform toolchain, hence the use of platform_target. This is not ideal though because the situation protentially repeats with every binary built by opentitan_binary so it makes more sense for this macro to always produce a target that triggers a transition. This commit specifies and implements that opentitan_binary now create an extra target …
=> [bazel,manuf] Integrate platform transition in opentitan_binary

sw/host/opentitantool/src/command/i2c.rs, sw/host/opentitantool/src/command/spi.rs, sw/host/opentitantool/src/command/tpm.rs
A few subcommands used a `--hexdata` option with the short form `-h`, conflicting with standard `-h` for `--help`.  The tpm.rs file used `-d` as the short form of `--hexdata`, though.
This PR standardizes on `-d` as the short form of `--hexdata`, eliminating the conflict with build in help.  The immediate need for this CL is that somehow, the explicit declarations of long-form only `--help` cases errors about "Required argument: help".  And rather than figuring our how to properly declare `--help` as optional, I think it makes sense to standardize on a short form that does not conflict with `-h`.
=> [opentitantool] Avoid required --help argument

ci/scripts/show-env.sh
Changes to ci/scripts/show-env.sh:
* No longer checking the version of `clang-format` because we only use the Bazel-managed binary.
* No longer failing the script (and thus ci/jobs/quick-lint.sh) when `verible-verilog-lint` is missing. Per the Getting Started guide, it's an optional tool.
=> [ci] Update version checks in ci/scripts/show-env.sh

hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv, hw/ip/otbn/rtl/otbn.sv
The RTL change changes the hierarchical IDs of some assertions so that they all start with a particular scope. Once that is done, we can turn them off with
$assertoff(0, "tb.dut.secure_wipe_assertions");
This is needed to avoid some spurious test failures in the `otbn_ctrl_redun` test.
Although this changes some RTL code (`hw/ip/otbn/rtl/otbn.sv`), it should be completely safe: the only change is to the hierarchical IDs of some assertion statements.
=> [otbn,dv] Wrap some secure wipe assertions in a named block

hw/ip/pwrmgr/dv/env/pwrmgr_if.sv
When simulating with Xcelium, the path for the `$assertoff()` call needs the initial "tb." as well.
=> [pwrmgr,dv] Correct name of disabled assertion

hw/ip/otbn/dv/verilator/otbn_top_sim.sv
In the Verilator-based pre-DV code, we instantiated otbn_core instead of the (bigger) otbn module. This is reasonable, but it means that we have to correctly model the gap between "writing the START command" and "raising the start_i signal".
This got a cycle slower at some point (possibly with 3b58f20120, but I haven't checked carefully), and the timing between the model and the RTL got unstuck. Add the corresponding cycle in the pre-DV wrapper to make everything match again.
=> [otbn,dv] Delay "start" signal for OTBN in pre-DV code by a cycle

sw/device/silicon_creator/lib/boot_svc/boot_svc_min_bl0_sec_ver.c, sw/device/silicon_creator/lib/boot_svc/boot_svc_min_bl0_sec_ver.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_min_bl0_sec_ver_unittest.cc, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/device/silicon_creator/rom_ext/rom_ext_boot_policy.c, sw/device/silicon_creator/rom_ext/rom_ext_boot_policy.h, sw/device/silicon_creator/rom_ext/rom_ext_boot_policy_unittest.cc
Implements the Set minimum required BL0 security version boot service.
This PR is based off https://github.com/lowRISC/opentitan/pull/19348
Resolves https://github.com/lowRISC/opentitan/issues/19156
=> [sw/silicon_creator] Implement set minimum required BL0 security version boot service

sw/device/lib/testing/json/provisioning_data.h, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/individualize.c, sw/device/silicon_creator/manuf/lib/individualize.h, sw/device/silicon_creator/manuf/lib/personalize.c, sw/device/silicon_creator/manuf/lib/personalize.h, sw/device/silicon_creator/manuf/lib/personalize_functest.c, sw/host/tests/manuf/personalize/src/main.rs
This adds functions to the individualization library to provision the TEST_{UNLOCK,EXIT} tokens into the SECRET0 OTP partition.
Updates to the corresponding functest to test this new functionality are coming in a followup.
=> [manuf] add function to provision secret0 OTP partition

SUMMARY.md, sw/host/hsmtool/README.md, sw/host/opentitanlib/README.md, sw/host/opentitansession/README.md, sw/host/opentitantool/README.md, sw/host/tpm2_test_server/README.md
This PR adds just the minimum documentation for OpenTitan's host software.
This will need expanding in the future, but hopefully adding these files will prompt people to add to them and keep them up to date in the future.
Future work:
* If anybody can provide more detailed documentation here, that would be greatly appreciated.
* I couldn't work out exactly what the `cryptotest` library was so have left that out for now.
* I couldn't work out what the `tpm2_test_server` was used for, but have copied its `about` line from the code.
=> [doc] Add basic documentation for host software

BUILD.bazel, hw/BUILD, rules/fusesoc.bzl
Fix up deps and do the fusesoc builds in the sandbox. Since the Python interpreter was switched to the bazel-provided one, it is now possible to use the sandbox. Note that this doesn't make the build *hermetic*, since it still relies on system-provided tools (e.g. vivado, verilator).
=> [bazel] Do fusesoc builds in the sandbox

sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_reset_reqs_test.c
Resubmit #19449 with relevant commit only
pwrmgr_normal_sleep_all_reset_reqs_test.c shows
spurious ping timeout issues.
Update timeout value to 256 ( recommended by design engineer).
=> [chip,dv] Increase ping timeout

WORKSPACE, rules/hooks_setup.bzl
Manufacturing partners have both a secure and non-secure domain they develop test code in that does not get pushed upstream, but makes use of upstream code. This adds a second external Bazel repo for the secure domain test hooks, which are stored in a separate system location than the non-secure domain test code.
=> [bazel] add second `manufacturer_test_hooks` repo for secure domain

hw/ip/clkmgr/dv/env/seq_lib/clkmgr_peri_vseq.sv
Wait some cycles before changing clk_enables CSR again to make sure the side-effects are visible in the outputs. Otherwise the random setting of the clock for the CSR block can occasionally be too fast and the slower clocks won't have time to be disabled in the outputs.
=> [dv/clkmgr] Fix occasional clkmgr_peri test failure

sw/device/tests/BUILD, sw/device/tests/pwrmgr_sleep_disabled_test.c
Test clkmgr_external_clk_src_for_sw_fast_test was ready to go. Test pwrmgr_sleep_disabled_test was failing because the wakeup timer was started too early, and probably fired before everything was configured.
//sw/device/tests:clkmgr_external_clk_src_for_sw_fast_test_fpga_cw310_test_rom (cached) PASSED in 19.5s //sw/device/tests:pwrmgr_sleep_disabled_test_fpga_cw310_test_rom (cached) PASSED in 3.0s
=> [top_level,tests] Allow two more tests to run with CW310

hw/ip/flash_ctrl/dv/env/flash_ctrl_env.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_lcmgr_intg_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_path_intg_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_wr_path_intg_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson, hw/ip/flash_ctrl/dv/tests/flash_ctrl_base_test.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_parallel_lc_esc_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_common_vseq.sv, sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_reset_reqs_test.c
Following PRs' from mater branch
#19415 
#19430 
#19431 
#19450
=> [earlgrey_es,dv] fix closed source regression faillure

sw/host/opentitanlib/src/transport/cw310/mod.rs, sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
This fixes #19467 so JTAG/OpenOCD can be used with hyper310 setup for testing provisioning binaries.
=> [opentitanlib] add jtag capability to hyperdebug transport

sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c
This PR adds a function for checking the expectations stored in `.static_critical` by ROM.
@moidx PLMK if you'd like me to anything else into this function.
=> [sw/silicon_creator] Add rom_ext_check_rom_expectations()

rules/linker.bzl, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/sram_program.ld, sw/host/opentitanlib/src/test_utils/load_sram_program.rs
Continuation of #19075
This:
* Disable segment alignment in SRAM programs
* Switch ELF loader to use segments
=> [manuf] Switch ELF loader to use segments

sw/device/silicon_creator/rom/doc/e2e_tests.md
Add a missing ' to ease copy-n-paste.
=> [rom/doc] Typo fix

rules/quality.bzl, sw/device/lib/dif/dif_clkmgr.c, sw/device/lib/dif/dif_clkmgr_unittest.cc, sw/device/tests/BUILD
Enables ast_clk_outs_test top_level test.
Fixes dif_clkmgr_enable_measure_counts to enable measurements after setting thresholds.
Fixes a commen typo.
=> Three separate simple commits

hw/top_earlgrey/formal/conn_csvs/ast_infra.csv, hw/top_earlgrey/formal/conn_csvs/clkmgr_secure.csv, hw/top_earlgrey/formal/conn_csvs/rstmgr_resets_o.csv
Hi,
This PR is updating the sensor_ctrl name  with suffix "_aon" in the formal CSVs that weren't updated.
Thanks!
=> [dv/formal] Update fomal CSVs with the updated sensor_ctrl path

hw/ip/BUILD
With the sandbox now enabled for fusesoc runs, the CW340 build was failing. It was missing the Ultrascale prim library in the bazel deps.
=> [build] Add missing prim_xilinx_ultrascale to bazel deps

sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/sram_cp_provision_init.c, sw/host/opentitanlib/src/test_utils/load_sram_program.rs, sw/host/tests/manuf/cp_provision_init/src/main.rs
This updates the CP provisioning binary to receive data over the console using the ujson framework, with UART flow control enabled. Additionally, updates to the opentitanlib SRAM program loading test util had to be made to enable writing to the RV_PLIC MMIO region, required for activating UART flow control.
This partially addresses #19453.
=> [manuf] inject provisioning data into CP provisioning binary over console with ujson

sw/device/silicon_owner/tock/kernel/BUILD, sw/device/silicon_owner/tock/kernel/layout.ld, sw/device/silicon_owner/tock/kernel/src/io.rs, sw/device/silicon_owner/tock/kernel/src/main.rs, sw/device/silicon_owner/tock/kernel/src/otbn.rs
Initially, this kernel/board definition is a clone of the upstream
kernel.  Over time, we will customize this kernel to the exact
configuration needed.
This depends on #19442.  You need only review the last commit.
=> [tock] Define a Tock kernel for OpenTitan 

third_party/rust/repos.bzl, util/prep-bazel-airgapped-build.sh
We rely on a forked/patched version of rules_rust to enable airgapped builds. Recently, the forked version's patches were updated, but bugs were introduced, causing airgapped builds (i.e. our nightly regressions to fail). This updates the rules_rust version to fix said bugs.
=> [rules_rust] update rules_rust to fix patch

util/example/tlgen/xbar_main.hjson, util/tlgen.py, util/tlgen/__init__.py, util/tlgen/doc.py, util/tlgen/elaborate.py, util/tlgen/generate.py, util/tlgen/generate_tb.py, util/tlgen/item.py, util/tlgen/lib.py, util/tlgen/validate.py, util/tlgen/xbar.py, util/tlgen/xbar.rtl.sv.tpl
The commits move things around enough that we can add mypy types to the code. Once we're done, we can run `mypy --strict util/tlgen/*.py` and no longer get any error reports.
The original code had lots of Python typing comments (although not machine readable), which made it reasonably easy to figure out what was supposed to do what.
This should hopefully be a good starting point for developing a more strongly-typed equivalent. We could probably move more of the typing logic into Python's type system, which might make it easier to work on.
=> [tlgen] General "tidy up" changes

hw/ip/rv_dm/data/rv_dm_testplan.hjson, hw/ip/rv_dm/dv/env/rv_dm_env.core, hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_not_supported_vseq.sv, hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv, hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test verify that if try to execute abstract command that is not supported will result in cmderr field of abstractcs register set to 2.
=> [RV_DM]cmderr_not_supported_test

hw/top_earlgrey/dv/env/chip_if.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_adc_ctrl_sleep_debug_cable_wakeup_vseq.sv
Changed force_adc_d_o method in chip_if to force `AST_HIER.adc_d_o directly.
Switched uvm_hdl_force with said method in a chip_sw_adc_ctrl_sleep_debug_cable_wakeup_vseq sequence.
=> [chip_if]-fixed force adc_d_o method and added method to test

hw/ip/hmac/data/hmac.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
1. Added list of features to HMAC specification.
2. Moved HMAC chip tests to chip_hmac_testplan.hjson.
3. Added `si_stage: SV3` test cases to cover functionality listed in the list of features.
4. Update pre-silicon test cases with relevant `SV1`, `SV2`, or `SV3` labels.
=> [SiVal] Test plan updates for HMAC

hw/ip/clkmgr/dv/env/clkmgr_env_cov.sv
The CSRs cannot be modified in low power since the CPU is off.
=> [dv/clkmgr] Ignore coverage crosses that are unrealistic

hw/ip/keymgr/data/keymgr.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
1. Added list of features to keymgr specification.
2. Moved keymgr chip tests to chip_keymgr_testplan.hjson.
3. Added `si_stage: SV*` test cases to cover functionality enumerated in the list of features.
4. Updated the pre-silicon test cases with relevant `SV1`, `SV2`, or `SV3` labels.
=> [SiVal] Test plan updates for keymgr

sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/individualize.c, sw/device/silicon_creator/manuf/lib/personalize.c, sw/device/silicon_creator/manuf/lib/util.c, sw/device/silicon_creator/manuf/lib/util.h
The LC token hashing function is used by multiple libraries, and was duplicated in them. This moves the LC token hashing function to a separate library that can be shared between the two.
Additionally, this will enable sharing said library with the CP provisioning binary.
This depends on #19514, only review the last commit.
=> [manuf] move LC token hash function to separate lib

hw/top_earlgrey/data/chip_testplan.hjson, sw/device/silicon_creator/manuf/data/manuf_testplan.hjson
This commit links the silicon creator manufacturing test plan to the chip earlgrey test plan. The manufacturing test cases were also annotated with Silicon Validation (SiVal) `si_stages`, as well as `otp_mutate`, `lc_states`, `features` and `bazel` attributes.
Some of the attributes were left with empty values. Test owners will update these fields in follow up commits.
=> [SiVal] Add manufacturing test plan to Earlgrey

site/book-theme/css/chrome.css, site/book-theme/css/general.css, site/book-theme/index.hbs, site/book-theme/pagetoc.css
Some minor tweaks to the mdbook style to address recent feedback.
1) Make the side fwd/back nav buttons only appear when the window is wider, preventing them from overlapping content on the page.
2) Tweak the background colour of the bottom-of-the-page fwd/back nav buttons to make them more visible.
3) Change the default state of the left-side navigation menu to be visible, to improve the new user experience.
I would appreciate a couple of people building the site locally to verify the changes look okay. Thanks
=> [site] Tweak site nav experience

hw/dv/dpi/usbdpi/usb_transfer.h, hw/dv/dpi/usbdpi/usbdpi.c, hw/dv/dpi/usbdpi/usbdpi.h, hw/dv/dpi/usbdpi/usbdpi.sv, hw/dv/dpi/usbdpi/usbdpi_test.c, hw/dv/dpi/usbdpi/usbdpi_test.h, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/lib/testing/usb_testutils_controlep.h, sw/device/tests/BUILD, sw/device/tests/usbdev_pincfg_test.c
Adds a top-level test that cycles the usbdev through all pin configurations using the DPI model, checking that the device may be enumerated and configured in each configuration.
Verilator top-level simulation is capable of exercising all available configurations. On FPGA and in top-level DV simulation (with a two wire bus and no visibility to the device itself) a restricted subset of configurations is available; all available configurations are exercised.
The DPI changes also introduce a bit more functionality that is required for the full suspend-resume behavior, so the handling of bus resets, in particular, in this PR is tentative and a more complete and accurate model is available to be integrated later.
Commit 1: Tidy ups and restructuring to support later commits. No functional …
=> Usbdev Pin Configuration test

sw/host/opentitanlib/src/backend/mod.rs, sw/host/opentitantool/src/command/bootstrap.rs, sw/host/opentitantool/src/command/gpio.rs, sw/host/opentitantool/src/command/image.rs, sw/host/opentitantool/src/command/load_bitstream.rs, sw/host/opentitantool/src/command/rsa.rs, sw/host/opentitantool/src/command/spi.rs, sw/host/opentitantool/src/command/spx.rs, sw/host/opentitantool/src/command/status_cmd.rs, sw/host/opentitantool/src/command/tpm.rs, sw/host/opentitantool/src/command/update_usr_access.rs, sw/host/opentitantool/src/main.rs, third_party/rust/Cargo.toml, third_party/rust/crates/BUILD.clap-4.2.7.bazel, third_party/rust/crates/BUILD.clap_builder-4.2.7.bazel, third_party/rust/crates/BUILD.clap_derive-4.2.0.bazel
`number_of_values` is renamed to `num_args` and `name` is deprecated in favour of `value_name`. They are still allowed in clap v4 but when the opt-in `deprecated` feature is enabled, the former will cause a warning and the latter is rejected.
=> [opentitantool] migrate deprecated clap attributes

SUMMARY.md, doc/glossary.md
This PR adds a glossary of terms to the documentation. Resolves https://github.com/lowRISC/opentitan/issues/19437.
Many of these entries only state the expansion of an acronym without defining what it means.
Please feel free to suggest changes to explanations or for new entries.
Future PRs:
- Add short explanations of what acronyms actually mean.
- Link to the glossary from terms used around the documentation.
- Consolidate glossaries found in block-level documentation into this page.
=> [doc] Add glossary of terms

sw/device/silicon_creator/manuf/lib/personalize_functest.c, sw/host/opentitanlib/src/test_utils/lc_transition.rs, sw/host/tests/manuf/cp_provision_init/src/main.rs, sw/host/tests/manuf/manuf_cp_device_info_flash_wr/src/main.rs, sw/host/tests/manuf/manuf_cp_test_lock/src/main.rs, sw/host/tests/manuf/manuf_cp_unlock_raw/src/main.rs, sw/host/tests/manuf/manuf_scrap/src/main.rs, sw/host/tests/manuf/personalize/src/main.rs
See #19086
Several manufacturing tests suffer from random JTAG issues because
they try to connect over JTAG while the device is rebooting in a
loop. Since a chip reset kills the JTAG, it can make the test fail
when a reboot occurs during the JTAG session. This is particular
problematic for the trigger_lc_transition() function that performs
an LC transition, a reboot and attempts to connect over JTAG: it
can happen that the initial LC state has CPU execution disabled
but that the target test has execution enabled. When this happens,
and unless a program was bootstrapped that can prevent a reboot
loop, connecting over JTAG is unsafe.
This commit solves this issue by
- make trigger_lc_transition() only optionally reconnect over JTAG,
- carefully documenting for each trigger_lc_transition() …
=> [manuf] Fix JTAG problems in manufacturing tests 

hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- Enable_small_rma had chip level path by mistake.
- Correct the path for block tb.
- Reduce data page size to 3.
- Increase wait ack timeout
- Increase expected alert max_delay : flash_ctrl_derr_detect
=> [flash_ctrl,dv] update path for block tb enable_small_rma

hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_otf_item.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_callback_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/top_earlgrey/dv/env/chip_if.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_adc_ctrl_sleep_debug_cable_wakeup_vseq.sv, sw/device/tests/sim_dv/gpio_test.c
Closed source regression fix
https://github.com/lowRISC/opentitan/pull/19508
https://github.com/lowRISC/opentitan/pull/19511
https://github.com/lowRISC/opentitan/pull/19534
https://github.com/lowRISC/opentitan/pull/19547
=> [earlgrey_es] cherry-pick from master

hw/ip/otbn/dv/rig/rig/configs/safe.yml, hw/ip/otbn/dv/uvm/gen-binaries.py, hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson
The otbn_ctrl_redun test wants to run a well-behaved binary. While the binary is running, the vseq wants to poke something to cause an error. Unfortunately, this doesn't work if the test binary happens to stop really quickly. The "safe mode" is designed to try to avoid this happening.
This is related to the change in #19385 (which makes the test more likely to fail if the binary does something naughty). I think the patches can land in either order, but things will be a bit cleaner after both of them have arrived.
=> [otbn,dv] Add a "safe" mode to RIG; use it in otbn_ctrl_redun test

azure-pipelines.yml, ci/azure-pipelines-nightly.yml, ci/publish-bazel-test-results.yml
The goal of this PR is to improve the usefulness of the GitHub CI reports. At the moment, failing tests are just reported as "bash exited with error 1" and one has to go to the Azure page and scroll the logs to find the problem.
Since bazel test produces JUnit reports, we can ask Azure to publish them and they are automatically displayed by GitHub and it also improves the Azure view. Example on this PR:
- [GitHub check view](https://github.com/lowRISC/opentitan/pull/19409/checks?check_run_id=15814529615)
- [Azure test view](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=123774&view=ms.vss-test-web.build-test-results-tab)
For testing, I have only enabled them on the nightly CI but in fact it is very easy to add them to any bazel test so this could be added to bazel test in …
=> [EXPERIMENT][ci] Publish nightly ROM E2E tests on azure using JUnit

hw/ip/usbdev/doc/programmers_guide.md, hw/ip/usbdev/doc/theory_of_operation.md
Software advisories regarding responsivenes to SETUP packets and handling of notification interrupts.
Cabling requirements for USRUSB on CW310/CW340.
Edit: dropped doc changes to usbdev.hjson because of BLOCKFILE
=> [usbdev/doc] Documentation updates

third_party/hyperdebug/repos.bzl
The recent PR #19482 added functionality to opentitantool to configure which pin should be used as chip select for various SPI devices on the same bus.  This PR pulls in the required support on the HyperDebug firmware side.
=> [opentitantool] Include updated HyperDebug firmware

azure-pipelines.yml, sw/device/silicon_creator/lib/drivers/BUILD, sw/device/silicon_creator/lib/drivers/flash_ctrl.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.h, sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc, sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.cc, sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.h, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/bootstrap.c, sw/device/silicon_creator/rom_ext/bootstrap.h, sw/device/silicon_creator/rom_ext/bootstrap_unittest.cc, util/py/packages/lib/register_usage_report_test.py
This PR adds a new memory protection feature to the flash_ctrl driver.
This is how ROM_EXT bootstrap implements its [promises](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom_ext/bootstrap.h;l=46-51;drc=934678a120ca7d8ef7c8facf4780c80688856979) without explicit bounds checks in software.
Issues #19151, #19438
=> ROM_EXT bootstrap flash memory protection

sw/device/lib/crypto/drivers/entropy.c
This commit adds CSRNG main FSM idle checks before sending any DRBG commands through any of the EDN or CSRNG CSRs. This is done as a workaround to issue #19568.
=> [cryptolib] Add CSRNG main FSM idle checks

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
This test sequence times out (in simulated time) some of the time in our nightlies. In particular, this happens for alert_handler at the moment.
The problem turns out to be that the test iterates over all the CSRs and pokes them in turn. We don't really expect any inter-CSR interactions, so this is just a quick way to get through everything in "one test". Unfortunately, alert_handler has 182 CSRs and this takes a while. In local testing, I think we're taking about 3ms of simulated time per CSR. With 182 CSRs, that's ~546ms, which is more than the 500ms default timeout in uvm-phase.svh!
This patch switches the code to iterate over a shorter list of CSRs. If we have a block with lots of CSRs, we'll need to run the test more times (in parallel!) to get the coverage we expect, but that should …
=> [dv] Iterate over a shorter list of CSRs in shadow reg errors test

sw/device/silicon_owner/tock/kernel/BUILD, sw/device/silicon_owner/tock/tests/BUILD, sw/device/silicon_owner/tock/tests/basic/BUILD, sw/device/silicon_owner/tock/tests/basic/src/basic.rs, sw/device/silicon_owner/tock/tests/defs.bzl, sw/device/silicon_owner/tock/upstream_kernel/BUILD
1. Create a basic test that runs under tock.  Tests that run with the
default `opentitantool` test harness should emit `PASS` or `FAIL` to
indicate their status.
2. Create a build setting that can select between the upstream and
downstream tock kernel.  Defaults to the downstream kernel.
```
bazel test \
--//sw/device/silicon_owner/tock/tests:kernel=<upstream|downstream> \
<label-of-the-test>
```
This PR depends on #19478.  You need only review the last commit.
=> [tock] Create a basic tock test 

SUMMARY.md, doc/getting_started/README.md, doc/getting_started/unofficial/fedora.md
The Fedora `dnf install` command comes from the
[Tock](https://github.com/tock/tock) project documentation.
=> [doc] Add an unofficial setup guide for Fedora

hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv
This fixes an error raised by Xcelium.
=> [edn,dv] Fix type of `mailbox` in `edn_disable_auto_req_mode_vseq`

.github/ISSUE_TEMPLATE/chip-level-test.yml
This commit updates the chip-level-test.yml issue template to include additional instructions for SiVal test cases.
The template title was also updated to include SiVal.
=> [github] Update chip-level issue template for SV

sw/device/lib/crypto/drivers/kmac.c, sw/device/lib/crypto/drivers/kmac.h, sw/device/lib/crypto/impl/hash.c, sw/device/lib/crypto/impl/mac.c
The KMAC driver previously used the crypto_uint8_buf_t types internally, which is different from the other drivers and created complications when I tried to align more things within the cryptolib; this commit changes it to match the other drivers and use separate buffer/length parameters.
Also, the driver previously used byte-reads internally to get the digest. Since I am about to align the digest buffers, there are performance and SCA benefits to swtiching to word-reads. Since we now have word-wise KMAC code from the ROM driver, I updated the cryptolib driver to match (with a memcpy that can be deleted if the output buffer is aligned later).
=> [crypto] Update the KMAC driver in preparation for aligned buffers.

hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/doc/registers.md
Spawned from the thread https://github.com/lowRISC/opentitan/pull/19554#discussion_r1314309770.
The description of `MSG_FIFO` states that when writing bytes/words to it, SW can ignore the word addresses but should correctly provide the least significant 2 bits of the address, so that MSG_FIFO can recognize the position of a byte within word. I think this is incorrect (a test by @jadephilipoom also points to this direction).
What really happens is that, even if SW ignores the least significant 2 bits of the address and directly writes a byte, its alignment is internally corrected by prim_packer primitive inside MSG_FIFO. As prim_packer is receiving input bytes (in order to accumulate them to word, and then release), it only takes the masking bits that come from TL-UL transaction into …
=> [kmac, doc] Update `MSG_FIFO` description

hw/ip/lc_ctrl/data/lc_ctrl.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
1. Added list of features to the lc_ctrl specification.
2. Moved lc_ctrl chip tests to chip_lc_ctrl_testplan.hjson
3. Added `si_stage: SV*` test cases to cover functionality enumerated in the list of features.
4. Updated the pre-silicon test cases with relevant `SV*` labels.
=> [SiVal] Test plan updates for `lc_ctrl`

SUMMARY.md, sw/device/silicon_creator/doc/boot_log.md
Following up on https://github.com/lowRISC/opentitan/pull/19496#issuecomment-1701299182, this PR adds the spec for the boot log to the Markdown documentation.
=> [doc] Add boot log documentation

sw/device/lib/crypto/impl/BUILD, sw/device/lib/crypto/impl/drbg.c, sw/device/lib/crypto/impl/ecc.c, sw/device/lib/crypto/impl/rsa.c, sw/device/lib/crypto/include/drbg.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/drbg_functest.c
- Adds a layer connecting the entropy complex driver to the API
- Adds checks that the entropy complex is in a good state before generating sensitive values on OTBN
- Adds a basic functional test
@moidx , this is the change I mentioned to you yesterday. The KAT test (on FPGA) hangs on `instantiate`, whether I use the top-level interface or call the CSRNG driver directly. It doesn't hang if I insert ~5 print statements before `instantiate`, or run `entropy_complex_check` in a loop 10000 times, which makes me suspect a timing issue.
=> [crypto] Connect CSRNG to the cryptolib API.

hw/dv/tools/dvsim/sim.mk
See #19553 for details. Due to a bazel change between verions 5 and 6, bazel cquery will print fully qualified paths like @//sw/device/...
for the repository instead of just //sw/device/... This breaks the filtering done when copying file and will make dvsim copy way too many files, or even try to copy files that are not there.
This commit fixes the issue by using a custom priting function for the query that removes the @ for path starting with @//.
=> [bazel,dvsim] Prevent dvsim from (trying to) copy irrelevant files

azure-pipelines.yml
The SW Build and Test job is exceeding 3 hours. This PR splits out the OTBN crypto tests into a separate job. This batch of tests includes `//sw/otbn/crypto/tests:rsa_keygen_checkpq_test` that currently takes about 45 minutes.
=> [ci] Break out OTBN crypto tests into their own job

hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv, sw/device/lib/arch/device.h, sw/device/lib/arch/device_fpga_cw305.c, sw/device/lib/arch/device_fpga_cw310.c, sw/device/lib/arch/device_sim_dv.c, sw/device/lib/arch/device_sim_verilator.c, sw/device/lib/testing/test_rom/test_rom.c, sw/device/lib/testing/test_rom/test_rom_start.S
The test ROM now reads the jittery clk enablement field from OTP to perfrom the enablement, same as the ROM. This fixes #19580.
=> [test_rom] align clk jitter enablement between test ROM and ROM

sw/host/opentitanlib/src/app/config/hyperdebug_cw310.json, sw/host/opentitanlib/src/app/config/structs.rs, sw/host/opentitanlib/src/app/mod.rs, sw/host/opentitanlib/src/io/i2c.rs, sw/host/opentitanlib/src/proxy/protocol.rs, sw/host/opentitanlib/src/tpm/driver.rs, sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs, sw/host/opentitanlib/src/transport/ioexpander/sx1503.rs, sw/host/opentitanlib/src/transport/proxy/i2c.rs, sw/host/opentitanlib/src/transport/ti50emulator/i2c.rs, sw/host/opentitantool/src/command/i2c.rs, sw/host/tests/chip/i2c_target/src/main.rs, sw/host/tpm2_test_server/src/main.rs
With this change, OpenTitanTool is able to use I2C addresses from configuration files:
```
"i2c": [
{
"name": "TPM",
"bits_per_sec": 400000,
"address": 0x50,
"alias_of": "I2C1"
}
],
```
This is in addition to being able to specify on command line: `opentitantool i2c --bus=I2C0 --addr=0x50 raw-write --hexdata="1234"`
The above `--addr` flag has become part of the `I2cParams`, meaning that several commands that previously declared their own `addr` field next to a "flattened" `I2cParams` now need only the `I2cParams`.
With this change, the bus/address of I2C behaves substantially similar to bus/chip_select for SPI, in that a "bus alias" can optionally carry additional information about a particular target to be addressed.
=> [opentitantool] Allow configuration of I2C address

hw/ip/kmac/README.md
It wasn't clear whether the previous throughput numbers in the documentation were actually correct and how they were obtained. This commit updates the numbers according to the following thinking:
It always takes 25 clock cycles to load the data and the padding into the Keccak core (1600 bits, 64 bits per cycle) and then either 24 or 96 clock cycles to perform the 24 unmasked or masked Keccak rounds, respectively. This results in 144 (SHA3-224) or 72 bytes (SHA3-512) being processed every 49 (unmasked) or 121 clock cycles (masked).
=> [kmac,doc] Correct performance numbers

sw/host/opentitanlib/src/bootstrap/mod.rs, sw/host/opentitanlib/src/bootstrap/rescue.rs
HyperDebug forwarding of UART data via USB suffers from a condition, that right out of reset it may be that HyperDebug does not forward any UART data until it has received at least one character from USB to be forwarded to the UART.  See issue #19564.
This is not normally an issue for interactive consoles, as the operator would hit enter to see if a prompt appears, or simply start typing a command.
In rare occasions, where one wants to wait for output coming out of the USB link before "typing" anything, the flaw can cause issues, as it did for the legacy serial rescue protocol.
This CL adds a little workaround, by sending a single ^C character into the USB->UART link, while the GSC is held under reset, just to wake up HyperDebug forwarding.
Also, this PR has a tiny bugfix for a panic …
=> [opentitantool] Workaround for HyperDebug quirk

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_path_intg_vseq.sv
Following tests are fixed. See commit message for detail
- flash_ctrl_phy_arb_redun
- flash_ctrl_rd_intg
=> [flash_ctrl,dv] fix closed source regression

hw/dv/dpi/common/tcp_server/tcp_server.c
Given the filename, this code is technically supposed to be C. It uses strdup(), which isn't necessarily defined until C23(!). With standard libraries like glibc, it can be requested by defining a magic __STDC_WANT_LIB_EXT2__ preprocessor variable, so we should probably do that.
With this change,
gcc -std=c99 -c hw/dv/dpi/common/tcp_server/tcp_server.c
runs to completion.
=> [dv,c] Ensure strdup() is defined when compiling tcp_server.c

doc/security/cryptolib/cryptolib_api.md
My previous change (#19613) broke the documentation build. I thought documentation builds actually getting tested in CI, but maybe not; in any case, this fixes it.
=> [doc] Update references in the cryptolib API doc.

sw/host/opentitanlib/src/test_utils/init.rs, sw/host/tests/rom/e2e_openocd_debug_test/src/main.rs
The current threshold (1 second) causes rare failure in CI. Increase it to 2 seconds in this test to reduce flakiness.
The opentitanlib log is changed to print milliseconds instead of just seconds to aid future debugging.
=> [rom_e2e] change `asm_watchdog_bite` test timeout threshold

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_path_intg_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv, sw/device/lib/arch/device.h, sw/device/lib/arch/device_fpga_cw305.c, sw/device/lib/arch/device_fpga_cw310.c, sw/device/lib/arch/device_sim_dv.c, sw/device/lib/arch/device_sim_verilator.c, sw/device/lib/testing/test_rom/test_rom.c, sw/device/lib/testing/test_rom/test_rom_start.S
=> [earlgrey_es] cheery-pick closed source regression fix

hw/dv/sv/jtag_agent/jtag_if.sv
Change the way tck clock is generated so that we won’t get 1ps lose in case tck_period_ps is odd.
This is required for production when tck frequency should be exactly equal to external clock frequency.
=> [jtag,dv] Change the way tck clock is generated

sw/host/hsmtool/BUILD, sw/host/hsmtool/src/commands/mod.rs, sw/host/opentitantool/BUILD, sw/host/opentitantool/src/command/console.rs, sw/host/opentitantool/src/command/gpio.rs, sw/host/opentitantool/src/main.rs, third_party/rust/Cargo.lock, third_party/rust/Cargo.toml, third_party/rust/crates/BUILD.bazel, third_party/rust/crates/defs.bzl, third_party/rust/deps.bzl, util/prep-bazel-airgapped-build.sh
Update the stable compiler version to 1.71 given that out nightly compiler is already newer than that. This gives us the ability to use `std::io::IsTerminal` to replace the crate.
=> [rust] migrate from is-terminal to `std::io::IsTerminal`

ci/scripts/build-docs.sh
The CI command to render documentation omitted an argument, so the CI job always just printed usage advice and exited "successfully", meaning it would miss changes that broke documentation builds.
See https://github.com/lowRISC/opentitan/pull/19633#issuecomment-1711479976
=> [ci] Fix the documentation build job in CI.

sw/device/lib/crypto/drivers/BUILD, sw/device/lib/crypto/drivers/keymgr.c, sw/device/lib/crypto/drivers/keymgr.h, sw/device/lib/crypto/drivers/keymgr_test.c, sw/device/lib/crypto/drivers/kmac.c, sw/device/lib/testing/keymgr_testutils.h
- Adds a cryptolib driver for the key manager.
- The cryptolib never needs to advance the keymgr state, so the driver only has the capability to generate/clear keys
- Adds a test for the basic functionality of the driver
- I'll merge follow-up PRs with functional tests for each sideloaded block that actually use and clear the keys, but since these tests will involve specific details of each block it makes sense to me for them to be separate and live under `sw/device/tests/crypto` instead of with the driver.
=> [crypto] Add a key manager driver and basic tests.

azure-pipelines.yml
This is a followup to #19619 to clean up a few things on the new OTBN crypto test job:
- Reduce the timeout to 60 minutes (the expected completion time is 41 minutes)
- Enable uploading results to the Bazel remote cache
=> [ci] OTBN crypto test job cleanups

hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_raw_unlock_vseq.sv
Add some delay between reset and waiting for lc_ready in chip_sw_lc_raw_unlock_vseq.
Without the delay there are some seeds in which the clocks are slower and the jtag reading of the status register in the lc_ctrl are failing.
=> [dv/rom/lc] Add some delay after reset in lc_raw_unlock_vseq

sw/device/sca/ecc384_serial.c, sw/otbn/crypto/p384_ecdsa_sca.s
Update ecc384_serial.c and p384_ecdsa_sca.s files to be compatible with the latest capture.py file in the ot-sca repo.
This is an WIP PR.
=> [sca/WIP] Update the ecdsa384_sca code

third_party/hyperdebug/repos.bzl
Pack a new precompiled firmware for the HyperDebug device.
This adds support for SPI1, and makes the blue button act as manual reset of the GSC under test.
Also, as slight fix/improvement is to reset all SPI and I2C busses to power-on default speed and chip select settings, on "transport init".
=> [opentitantool] Updated HyperDebug firmware

azure-pipelines.yml
This jobs seems to be causing a "No space left on device" error on the Azure VMs.
=> [ci] move quick lint job to GCP VM from Azure runner

hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
Increase the timeout when waiting for rma index when using enable_small_ram(). It is required when the system clock is slower than 100Mhz.
=> [dv,chip] Increase timeout inside enable_small_rma()

ci/azure-pipelines-nightly.yml
Add hyperdebug tests to the nightly CI. I don't know if they should added to the regular CI or nightlies, I am happy to change that depending on the feedback. I have done nightly run manually to show that it works.
=> [ci] Run hyperdebug tests on the nightly CI

sw/host/opentitanlib/src/app/mod.rs, sw/host/opentitanlib/src/io/spi.rs, sw/host/opentitanlib/src/proxy/handler.rs, sw/host/opentitanlib/src/proxy/protocol.rs, sw/host/opentitanlib/src/tpm/driver.rs, sw/host/opentitanlib/src/transport/chip_whisperer/spi.rs, sw/host/opentitanlib/src/transport/dediprog/spi.rs, sw/host/opentitanlib/src/transport/hyperdebug/spi.rs, sw/host/opentitanlib/src/transport/proxy/spi.rs, sw/host/opentitanlib/src/transport/ti50emulator/spi.rs, sw/host/opentitanlib/src/transport/ultradebug/spi.rs
Strictly speaking, the TPM SPI protocol requires the host to receive while it sends the four-byte request, as the TPM device could send the "ready byte" at the same time as the final byte of the request.
However, the HyperDebug Quad-SPI port does not support simultaneous sending and receiving.
This CL adds ability for Spi trait implementations to advertise whether they support bidirectional transfers, and add workaround code in the TPM logic, which assumes that the TPM device will send the "ready byte" immediately following the fourth and final request byte.
=> [opentitantool] Work around lack of bidirectional SPI

sw/device/silicon_creator/rom/rom_start.S
The fill value of .balign is ignored for .bss. Binutils will warn about
using a non-zero fill value. Clang's integrated assembler won't complain
but it has a debug assertion that will trip in debug builds of the toolchain.
=> Remove erroneous UNIMP fill of .bss section

hw/ip/otbn/dv/otbnsim/sim/wsr.py
Since XOR works on each bit independently, we can do the XOR before rotating the inputs by 45 bits. This way, we only have to rotate one thing (the XOR'd value) and the result is somewhat faster. Standalone otbnsim gets a little bit faster (~2.5%) with this change.
=> [otbn,dv] Rewrite a line more efficiently in wsr.py

hw/ip/otbn/doc/interfaces.md, hw/ip/otbn/dv/model/otbn_core_model.sv, hw/ip/otbn/dv/tracer/rtl/otbn_trace_if.sv, hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv, hw/ip/otbn/dv/uvm/tb.sv, hw/ip/otbn/dv/verilator/otbn_top_sim.sv, hw/ip/otbn/rtl/otbn.sv
This PR cherry-picks the first part of the fixes making OTBN compatible with the LC_CTRL spec. In particular, this PR changes the interpretation of the `lc_escalate_en_i` input signal (remove the detection of invalid values on this signal, consistently use `lc_tx_test_true_loose()`). This is related to https://github.com/lowRISC/opentitan/issues/19050.
The second part of the fix cannot be carried over yet as we first need to modify LC_CTRL itself to have two parallel RMA request interfaces for flash_ctrl and OTBN. See #19136.
=> [otbn] Cherry-pick LC signal handling fixes - Part 1

hw/top_earlgrey/data/chip_testplan.hjson, sw/device/silicon_creator/manuf/data/manuf_testplan.hjson, sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson, util/dvsim/Testplan.py, util/dvsim/testplanner.py, util/mdbook_testplan.py
Testplans are now rendered into a markdown document as oppose to a large HTML table.
These HTML tables were unwieldy when viewed from the site or as plain text. The original `pipe` output was not standard markdown.
New version of the [GPIO Testplan](https://opentitan.org/book/hw/ip/gpio/data/gpio_testplan.html):
Related to https://github.com/lowRISC/opentitan/issues/19078
=> [doc] Testplans are now generated as markdown.

hw/ip/clkmgr/dv/env/seq_lib/clkmgr_regwen_vseq.sv
I don't think this is technically allowed by the standard, and it causes Xcelium to choke on the code. Casting explicitly like this seems to sort things out.
=> [clkmgr,dv] Avoid passing a mubi4_t as a uvm_reg_data_t output arg

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
1. Added list of features to the flash_ctrl specification.
2. Moved flash_ctrl chip tests to chip_flash_ctrl_testplan.hjson
3. Added si_stage: SV* test cases to cover functionality enumerated in the list of features.
4. Updated the pre-silicon test cases with relevant SV* labels.
=> [SiVal] Test plan update for flash_ctrl

azure-pipelines.yml
Update the `azure-pipelines.yml` to refer to the `earlgrey_es` branch.
=> [ci] Build and publish bitstream artifacts on `earlgrey_es`

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/usbdev_pullup_test.c
This PR creates a simple test to check for VBUS presence, assert DP pull up and then check that this raises the DP signal on the USB. This action signals the presence of a Full Speed device to the USB host.
No traffic is performed in this simple test and it completes very quickly.
For those targets which can pull up either DP or DN and thus fully support pin flipping, the test will then repeat this operation on the 'DN' signal for completeness.
The test operates on the CW310 FPGA or in chip simulation and is intended to assist with silicon bring up.
When supervised manually with physical hardware, it can optionally be configured to verify that VBUS is initially low, so a cable may be connected or a hub port powered up manually during the test.
This test requires PR #19566 
The test builds …
=> [tests/usbdev] Create usbdev pull up test

hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
Closed source can generate uncorr data with different mechanism. 
Make a separate function to override in closed source environment.
=> [otp_ctrl,dv] Add virtual to uncorr comp function

doc/contributing/bazel_notes.md, third_party/rust/repos.bzl
This updates rules_rust to make use of a new [patch](https://github.com/lowRISC/rules_rust/commit/545f431ebd1d477ff5a5699665de8b29331c67f2) that was added in the lowRISC fork of rules_rust that enables a workaround for https://github.com/lowRISC/opentitan/issues/12448.
The workaround provides a command line build flag
`--@rules_rust//:extra_rustc_toolchain_dirs=/path/to/somewhere/else` that you can add to your `.bazelrc` file to specify a different location on your system where host toolchain tools may be found.
=> [bazel] update rules_rust to add patch for specifying `ld` location

hw/ip/pwrmgr/dv/sva/pwrmgr_sec_cm_checker_assert.sv
Some tests inject transitions to an invalid state at random, so SVAs that expect specific transitions need to allow for transitions to invalid states.
=> [dv/pwrmgr] Allow transitions to invalid fsm state

util/site/blocks.json, util/site/fetch_block_stats.py
This PR removes the `href` fields from the `blocks.json` block diagram spec file.
This spec file is used to add tooltips to the interactive block diagram on the website.
Some of the `href` fields are now out of date, but were never used by the interactive block diagram code and can be removed.
This JSON specification lists the blocks that will be given tooltips in the website's interactive block diagram.
The [`util/site/fetch_block_stats.py`](https://github.com/lowRISC/opentitan/blob/master/util/site/fetch_block_stats.py) script uses this file to collect information that the [`site/block-diagram/block_diagram.js`](https://github.com/lowRISC/opentitan/blob/master/site/block-diagram/block_diagram.js) script uses to generate tooltips on each block in the diagram.
The URLs listed here are …
=> [site] Remove href field from block diagram json spec

sw/otbn/crypto/p256_base.s
This PR/commit fixes a bug in p256_random_scalar.
To generate a random scalar, randomness is taken from RND. The WDRs which contain the RND bits are then XORed with bits from URND, just in case there's any vulnerability in EDN that lets the attacker recover bits before they reach OTBN.
But one of the three WDRs that contain RND bits isn't XORed with URND. This gets fixed here.
=> [sw/crypto] Fix P-256 Random Scalar Generation

hw/dv/dpi/usbdpi/usbdpi.c
Corrects merge of partial bus reset/disconnect behavior from suspend-resume testing. The merged code was sufficient for Verilator t-l sim but failed with the real USB signals of the ASIC chip sim. It's a 'partial' implementation because the full reset/disconnect behavior is interdependent with the sleep/resume behavior of later tests/PRs-to-be.
Background: although the new usbdev_pincfg_test passed in CI, the merge broke the chip_sw_usbdev_dpi test in the nightly regression because the DPI model was unintentionally holding usbdev in reset with its drivers, which are stronger than the ASIC pull up, so the device could not signal its presence.
With this PR the test now passes again.
=> [usbdev] Fix startup behavior in usb chip sims

sw/host/opentitanlib/src/bootstrap/legacy.rs, sw/host/opentitanlib/src/transport/hyperdebug/gpio.rs, sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
OpenTitanTool now ships with "official" HyperDebug firmware, is able to upgrade the device, and warns if used with non-official firmware.
Given the above, I do not think that we need to keep carrying fallback code meant for cases in which opentitantool is working with older HyperDebug firmware, which does not understand newly added commands.
Also, a small fix to the legacy SPI bootstrap protocol progress bar.  The flash offset was not properly taken into account when using "start address" of the current block as measure of progress.
=> [opentitantool] Remove fallbacks for ancient HyperDebug firmware

.bazelrc, azure-pipelines.yml, rules/quality.bzl, sw/device/lib/ujson/example.h
The goal of this PR is to rework the way module ID are checked to save time.
NOTE: the first commit is #19578 which is necessary for CI to pass
=> [bazel] Rework module ID check aspect

rules/scripts/gdb_test_coordinator.py, sw/host/opentitantool/src/command/console.rs
The automated test systems used at Google will routinely start `opentitantool console` as a sub-process to pipe data back and forth. When such a sub-process is started, it would be ideal that the parent could wait long enough to be able to "see" error output such as "could not open /dev/ttyUSB6: permission denied", or any other error that happens in the setup phase.
This CL makes sure that the "Starting interactive console" message is printed after every bit of initialization has been successful, and switches to printing the aforementioned message on standard error instead of standard out..
Doing so allows the process that starts 'opentitantool console` as a sub process, to monitor stderr of the sub-process until either it closes (and the sub-process then exits with an error code), or …
=> [opentitantool] `opentitantool console` prints status to stderr

sw/host/opentitanlib/src/bootstrap/rescue.rs
At an earlier time, I modified the rescue protocol to round up the size of the range being flashed to a multiple of a page size.  (After being trimmed for trailing words consisting only of FF.)
Prior to this change, the logic for skipping ranges of FFs "in the middle" of the image needed not worry about going past the end of the range to be flashed, as the last word of the range would always be somthing other than pure FFs.
Now it turns out that ranges of FF bytes extending beyond the end of the section of the image to be flashed can cause `addr` to go beyond `max_addr`, this fix makes sure that if all remaning bytes up to `max_addr` are FFs, then then `unwrap_or(0)` will make sure that the logic does not skip anything, (as this has to be due to padding of the final page.)
=> [opentitantool] Yet another fix to legacy Titan rescue protocol

hw/ip/adc_ctrl/data/adc_ctrl.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_adc_ctrl_testplan.hjson
1. Added list of features to the adc_ctrl specification.
2. Moved adc_ctrl chip tests to chip_adc_ctrl_testplan.hjson
3. Added si_stage: SV* test cases to cover functionality enumerated in the list of features.
4. Updated the pre-silicon test cases with relevant SV* labels.
=> [SiVal] Test plan update for adc_ctrl

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_host_grant_err_vseq.sv
This commit already exists in the master branch, this PR will merge it to earlgrey_es branch.
=> [earlgrey_es] Cherry-pick - fix phy_host_gran_err test

azure-pipelines.yml, ci/BUILD, ci/scripts/run-fpga-tests.sh, hw/bitstream/cw340/BUILD, hw/bitstream/hyperdebug/BUILD, hw/bitstream/vivado/BUILD, rules/opentitan.bzl, rules/opentitan_test.bzl, sw/device/lib/arch/BUILD, sw/device/lib/arch/device.h, sw/device/lib/arch/device_fpga_cw340.c, sw/device/tests/BUILD
TODO, this is a work in progrss. I was able to make it work on fred after fixing the tty devices permissions and running
```
bazel test --test_output=streamed --cache_test_results=no //sw/device/tests:example_test_from_flash_cw340_rom_with_fake_keys --test_arg=--uarts=/dev/ttyUSB2,/dev/ttyACM0
```
=> [bazel] Add support for the CW340

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
All error tests using for loop have potential issue with alert agent random response delay.
The issue is while current alert thread waiting for hand shake to finish, another alert comes in or set_exp_alert is called. This will start the next alert thread and overlaped with previous alert thread. Using fast_rcvr knob can reduce the chance but not a complete solution. As this failure, sometimes it is required to explicit guard time before two back to back alert monitoring thread.
=> [flash_ctrl,dv] fix cs reg fail

sw/device/lib/runtime/print.c, sw/device/lib/runtime/print.h
Introduce check for NULL sink function and safely suppress output as per other base_ stdout functions, rather than branching to address zero in chip simulation.
The other base_ functions already included protection against the fact that in DV simulation the base_set_stdout() function has never been invoked. It seems that base_hexdump() and related function were overlooked.
Also noticed a typo.
=> [base_hexdump] Protect base_hexdump calls in DV

sw/device/lib/crypto/drivers/aes.c, sw/device/lib/crypto/drivers/aes.h, sw/device/lib/crypto/drivers/aes_test.c, sw/device/lib/crypto/impl/aes.c, sw/device/lib/crypto/impl/aes_gcm/aes_gcm.c, sw/device/tests/crypto/aes_functest.c
This makes life easier for callers who want to build a streaming AES interface.
=> [crypto] Make AES update the IV when returning.

sw/device/lib/crypto/drivers/hmac.c, sw/device/lib/crypto/impl/ecc/ecdsa_p256.c, sw/device/lib/crypto/impl/rsa/rsa_3072_verify.c, sw/device/silicon_creator/rom/e2e/BUILD, sw/device/silicon_creator/rom/e2e/rom_e2e_self_hash_test.c, sw/device/tests/crypto/sha256_functest.c
The HMAC driver previously returned the SHA-256 digest in little-endian order, which is what it does for ROM. However, for cryptolib, we treat the digest more like a raw data buffer, and for that we want the direct byte stream to adhere to the SHA-256 specification. That means we need to use big-endian order within words.
@timothytrippel I switched the `rom_self_hash_test` to use the `silicon_creator` driver instead, since that's what we actually use at boot anyway. ROM has absolutely everything in little-endian, so I think it's consistent to keep that driver little-endian even though it differs from what cryptolib will now do.
=> [crypto] Fix an endianness mismatch in the HMAC driver.

bazelisk.sh, hw/top_earlgrey/BUILD, rules/opentitan/BUILD, rules/opentitan/cc.bzl, rules/opentitan/defs.bzl, rules/opentitan/exec_env.bzl, rules/opentitan/fpga_cw310.bzl, rules/opentitan/providers.bzl, rules/opentitan/sim_dv.bzl, rules/opentitan/sim_verilator.bzl, rules/opentitan/transform.bzl, rules/opentitan/util.bzl, rules/signing.bzl, signing/examples/BUILD, sw/device/examples/hello_world/BUILD, sw/device/silicon_creator/lib/drivers/BUILD
1. Create rules for describing the target execution environments for
OpenTitan code, including "arch" libraries, linker scripts, signing
keys and test dispatch information.
2. Create a new `opentitan_binary` rule that can build and link C
programs for a set of execution environments.  Emit providers
specific to each environment.
3. Createa new `opentitan_test` rule that can dispatch a test on a
given execution environment.  Like `cc_test`, the opentitan rule
can compile and link the test program before dispatch.
4. Create an `opentitan_test` macro that, given a list of execution
environments, creates a rule per exec_env.
This is still a work in progress.  Draft pull request to collect some early feedback.
=> [bazel] Rewrite binary & test rules 

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv, hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
=> [earlgrey_es] Cherry-pick 

sw/host/opentitanlib/src/app/config/structs.rs, sw/host/opentitanlib/src/app/mod.rs, sw/host/opentitanlib/src/app/spi.rs, sw/host/opentitanlib/src/io/spi.rs, sw/host/opentitanlib/src/proxy/handler.rs, sw/host/opentitanlib/src/proxy/protocol.rs, sw/host/opentitanlib/src/transport/hyperdebug/spi.rs, sw/host/opentitanlib/src/transport/proxy/spi.rs
This change allows all four pins of SPI ports to be controlled from json configuration files.  Depending on backend transport, explicitly specifying pins may not be supported, or may be supported only for some pins (chip select).
This change does not yet add Sam3X driver support.
=> [opentitantool] Allow config control of all spi pins 

hw/top_earlgrey/data/clocks.xdc, hw/top_earlgrey/data/pins_cw310.xdc, hw/top_earlgrey/data/pins_cw310_hyperdebug.xdc
Relieve pressure on hold timing closure by modeling the separate clk_main and clk_io trees and setting them to be asynchronous. Occasional hold time failures would occur through the crossbar during the hyperdebug bitstream build.
Also consolidate the timing constraints into clocks.xdc by moving the USB constraints over.
=> [cw310] Add async paths between main and I/O clocks

hw/dv/sv/sec_cm/prim_onehot_check_if.sv
The prim_onehot_check_if_proxy class can be instantiated when AddrCheck is either on or off. When it is off it should result in no coverage holes for the cp_onehot_addr_fault coverpoint. The previous implementation set option.at_least to zero in this case, which caused a runtime warning. This implementation creates two derived classes from prim_onehot_check_if_proxy, one that is equivalent to the prior class for AddrCheck == 1, and one whose embedded covergroup does not have cp_onehot_addr_fault for AddrCheck == 0.
This removes the option.at_least setting, thus a problematic warning.
=> [prim_onehot,cov] Fix coverage when AddrCheck == 0

doc/security/cryptolib/cryptolib_api.md, sw/device/lib/crypto/impl/hash.c, sw/device/lib/crypto/include/hash.h, sw/device/silicon_creator/manuf/lib/util.c, sw/device/tests/crypto/kmac_functest.c, sw/device/tests/crypto/kmac_set_testvectors.py, sw/device/tests/crypto/kmac_testvectors.h.tpl
Separate the SHAKE and cSHAKE interfaces in the cryptolib.
Since the two take a different set of arguments, we agreed several months ago to separate them in the cryptolib API, but the change hasn't actually happened until now.
=> [crypto] Separate SHAKE/cSHAKE interface.

hw/ip/entropy_src/README.md, hw/ip/entropy_src/doc/theory_of_operation.md
This PR fixes some of the names of registers in the entropy_src documentation.
The main two fixes here are:
1. `CONF.ENABLE` was moved to `MODULE_ENABLE` in 51fde5a9830ab1501b01d953c7651c63727a546d.
2. `REGEN` was renamed to `REGWEN` in ef348c9995b53217479ebda6af8f7501042ecb72.
I have also added some convenience links to registers and fields that weren't linked previously.
=> [doc] Fix registers in entropy_src documentation

sw/device/lib/crypto/drivers/aes.c, sw/device/lib/crypto/impl/aes.c, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/aes_sideload_functest.c
Uses the new key manager driver to sideload AES keys, and adds a basic test that checks for different salts generating different keys and keys being cleared properly after use.
=> [crypto] Add support for sideloaded AES keys, and a test.

hw/ip/i2c/data/i2c.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson, hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
This is an initial version of the I2C silicon validation test plan. It takes inspiration from the counterpart in key manager: https://github.com/lowRISC/opentitan/pull/19521
I tried to create enough tests so that all of I2C's features are covered, but it would probably be good to get the input of more people here. Alternatively, we can merge this as a base version and iterate over it with future PRs.
=> [SiVal] I2C test plan

hw/ip/csrng/rtl/csrng_pkg.sv, hw/ip/edn/data/edn.hjson, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_disable_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv, hw/ip/edn/rtl/edn_reg_pkg.sv
Before this PR no checking of the command interface of the CSRNG block was done.  This PR adds DV checks on the commands issued to the CSRNG block.
This PR resolves #17087
=> [edn/dv] csrng commands check

hw/ip/otbn/dv/otbnsim/sim/wsr.py
Minor cleanups to `wsr.py`, the code that represents WSRs in otbnsim. There shouldn't be any functional change, but the code is a bit easier to understand and it runs (very marginally) faster.
=> [otbn,dv] Cleanups of wsr.py in otbnsim

azure-pipelines.yml, ci/scripts/test-empty-bitstream-cache.sh, rules/scripts/bitstreams_workspace.py, rules/scripts/bitstreams_workspace_test.py
Add a list of known / required designs to the bitstreams workspace generator, and for cache entries that do not contain all the designs, redirect the targets back to the Vivado-built ones.
This eliminates errors that may happen during the analysis phase due to missing referenced targets. Previously, if the bitstreams cache was missing an entry, the targets would not be created in the @bitstreams repo. Now, those targets will always exist, and builds may continue even when the cache entry is incomplete.
=> [bitstreams] Redirect missing targets in the cache

sw/device/lib/dif/dif_spi_host.c, sw/device/lib/dif/dif_spi_host_unittest.cc
This PR put the transaction in the CMD_FIFO before the data is put in the TX_FIFO, this allows transactions lager than the FIFO size, otherwise, the DIF would deadlock during the FIFO feeding.
=> [dif, spi_host] Fix deadlock when the send size is larger than the FIFO

hw/bitstream/BUILD, hw/bitstream/cw340/BUILD, hw/bitstream/hyperdebug/BUILD, hw/bitstream/vivado/BUILD
This is an attempt at simplifying the bitstream targets. It also fixes some obviously wrong splices that look like the result of a bad copy/paste. @a-will
=> [bazel] Reorganize and simplify the bitstream targets

azure-pipelines.yml, ci/scripts/run-fpga-tests.sh, sw/device/tests/BUILD
Note that this requires to build the hyperdebug bitstream which adds a nontrivial load to the CI now we are building three bitstreams (cw310, hyperdebug, cw340).
=> [ci] Run hyperdebug tests in CI

sw/device/lib/crypto/impl/BUILD, sw/device/lib/crypto/impl/mac.c, sw/device/lib/crypto/include/datatypes.h, sw/device/lib/crypto/include/mac.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/hmac_sha256_functest.c, sw/device/tests/crypto/hmac_sha384_functest.c, sw/device/tests/crypto/hmac_sha512_functest.c
We already had  streaming implementations of SHA384 and SHA-512. Since HMAC is a thin layer on top of hashing, it made sense to add support for larger SHA2s to the streaming HMAC interface, in addition to SHA256 (which was already present).
=> [crypto] Add support for HMAC-SHA384 and HMAC-SHA512.

hw/ip/pattgen/data/pattgen.hjson, hw/top_earlgrey/data/chip_testplan.hjson
This PR is based on previous silicon validation test plans. It really only contains one test, but it is simple enough that I don't think it is necessary to split it into separate tests. Happy to make adjustments based on feedback though.
=> [pattgen,SiVal] Silicon validation testplan for pattern generator

sw/device/lib/crypto/impl/BUILD, sw/device/lib/crypto/impl/drbg.c, sw/device/lib/crypto/include/drbg.h, sw/device/lib/testing/BUILD, sw/device/lib/testing/randomness_quality.c, sw/device/lib/testing/randomness_quality.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/drbg_functest.c
A few minor updates to the DRBG interface and testing:
- Changes the DRBG interface to use word buffers for output
- Makes usage of `const` in the DRBG interface a little more consistent
- Adds a library with a basic statistical randomness-quality check
- Adds a DRBG test that uses the non-manual interface and a randomness-quality check
Ideally I'd like to add more tests beyond just the one that's there now, but for now it's better than nothing; for now I just wanted to have some kind of check running in CI on the non-manual DRBG interface.
=> [crypto] Update DRBG interface and improve testing.

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/usbdev_setuprx_test.c
This PR creates a simple test for the reception of a SETUP token packet and associated DATA packet from the USB host as an initial setup in testing the communication with the host.
It checks the properties of the received DATA packet but not the full content, for robustness with different hosts and disparate behaviors.
It forms an interim step between the simpler electrical connectivity tests and the full configuration/communication tests that have characterized usbdev verification to date. The aim is to be of assistance with SiVal bringup.
The test is deliberately simple and self-contained to avoid issues of software dependencies and to assist with any modifications necessary for testing environments.
=> [tests/usbdev] Test SETUP packet reception

.github/CODEOWNERS
I'm spending less time on the CI now, and this helps reduce my email volume.
=> [codeowners] Remove @milesdai from CI codeowners

hw/bitstream/BUILD, hw/bitstream/vivado/BUILD, release/BUILD, release/azure-pipelines-release.yml
This PR addresses an error in the Release pipeline where sometimes the bitstream cache may not initialize properly:
```console
ERROR:root:Cannot find a bitstream close to HEAD
(08:40:06) INFO: Repository bitstreams instantiated at:
/azp/agent/_work/1/s/WORKSPACE:119:16: in <toplevel>
Repository rule bitstreams_repo defined at:
/azp/agent/_work/1/s/rules/bitstreams.bzl:112:34: in <toplevel>
(08:40:06) ERROR: An error occurred during the fetch of repository 'bitstreams':
Traceback (most recent call last):
File "/azp/agent/_work/1/s/rules/bitstreams.bzl", line 85, column 13, in _bitstreams_repo_impl
fail("Bitstream cache not initialized properly.")
Error in fail: Bitstream cache not initialized properly.
(08:40:06) ERROR: /azp/agent/_work/1/s/WORKSPACE:119:16: fetching bitstreams_repo rule …
```
=> [release] Avoid fetching from the bitstream cache when building the release

sw/host/opentitanlib/src/util/usr_access.rs
Bitstreams with headers (.bit files) are not guaranteed to be 4-byte aligned. Scan for the sync word first, then use its offset to get the alignment of command words.
=> [opentitanlib] Align to sync word before scanning bitstream

sw/host/opentitanlib/src/app/mod.rs
With the introduction of LogicalSpiWrapper and LogicalI2cWrapper, the setting of backend interface speed and other properties is done lazily, once the first operation is requested through a particular logical wrapper.  Because of that, there is no need to eagerly get a handle to each SPI and I2C port and set any properties.
This CL skips this step, which anyway had no useful effect.
=> [opentitantool] Wrapper cleanup

azure-pipelines.yml, ci/fpga-template.yml, hw/bitstream/BUILD
Add a manifest fragment target for the cached CW340 bitstream.
Consolidate the various FPGA build scripts into a template. This is largely copied from the other repo, and moving to the template for chip_earlgrey_cw310_hyperdebug and chip_earlgrey_cw340 enables them to use the same logic for using cached bitstreams and skipping Vivado builds.
Exempt more files from triggering bitstream builds when they change, such as hjson files and templates. Because we check in generated RTL, checking for changes to the generated code is sufficient. Checking *only* that code also prunes unrelated changes.
=> [ci] Enable more usage of the bitstream cache

azure-pipelines.yml, ci/azure-pipelines-nightly.yml
This PR fixes the nightlies due to an older version on the CI hypedebug boards.
=> [ci] Check and update the hyperdebug firmware before running tests

hw/ip/edn/rtl/edn_core.sv
There is a discrepancy between the reset values of the EDN MAX_NUM_REQS_BETWEEN_RESEEDS register (32'b0) and the auto request mode counter ('1) that counts the number of generate commands between reseeds.
The scoreboard counts the number of generates between reseeds and compares it to the value in the register. If the number of generates is larger than the value of MAX_NUM_REQS_BETWEEN_RESEEDS an error occurs. The counter value is updated every time a value is written to the register. However, if the value is never updated, in the scoreboard's view the number of allowed generates is 0 and from the counter's view its '1. This leads to the issue that the scoreboard throws an error even though there is nothing wrong.
In this PR I update the default value of the counter to 0. This gets rid of …
=> align reseed cntr resval with MAX_NUM_REQS_BETWEEN_RESEEDS resval

hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv
Adjust the genbits sequence to issue a random sw command while
in auto mode. The sequence now picks one of the auto mode states
during which the sw command will be issued (w/o waiting for the rdy
signal). Furthermore, make the scoreboard smarter to differantiate
between accepted and rejected sw commands. Add more precise reseed/
generade FIFO clearance and some minor fixes. This commit solves
issue https://github.com/lowRISC/opentitan/issues/17087.
=> [edn/dv] Add sequence to check issuing cmd during auto_req_mode

doc/security/cryptolib/cryptolib_api.md, sw/device/lib/crypto/impl/BUILD, sw/device/lib/crypto/impl/key_transport.c, sw/device/lib/crypto/impl/key_transport_unittest.cc, sw/device/lib/crypto/impl/keyblob.c, sw/device/lib/crypto/impl/keyblob.h, sw/device/lib/crypto/include/aes.h, sw/device/lib/crypto/include/key_transport.h, sw/device/lib/crypto/include/mac.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/aes_sideload_functest.c, sw/device/tests/crypto/symmetric_keygen_functest.c
- Adds functions to the key-transport interface that generate symmetric keys or new handles for hardware-backed keys
- Adds unit tests for the hardware-backed key interface, and also uses it in the AES test
- Adds a basic test for symmetric key generation
As part of https://github.com/lowRISC/opentitan/issues/19549, this unifies the interface for generating symmetric keys (as opposed to having an AES keygen, a KMAC keygen, and an HMAC keygen that all do the same thing and fail if the user-set mode is wrong).
=> [crypto] Add symmetric key generation interface to cryptolib.

hw/ip/i2c/data/i2c.hjson, hw/ip/i2c/doc/registers.md, hw/ip/i2c/doc/theory_of_operation.md, hw/ip/i2c/dv/env/i2c_scoreboard.sv, hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv, hw/ip/i2c/rtl/i2c_core.sv, hw/ip/i2c/rtl/i2c_reg_pkg.sv, hw/ip/i2c/rtl/i2c_reg_top.sv, sw/device/lib/dif/dif_i2c.c, sw/device/lib/dif/dif_i2c_unittest.cc
The name READ shadows the uvm_reg_field read() member function in the ral generated package.
This renaming should not affect the real hardware, only the programming model.
=> [rtl,i2c] Rename FDATA READ field to READB

hw/ip/usbdev/data/usbdev.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
Added list of usbdev features.
List usbdev chip-level tests available for SiVal.
Note:
A number of these tests are not yet available, pending merging into the repository but they can be included soon.
For now, tests related to Suspend, Resume, Sleep and Wake are not included in this SiVal test list although they cover important functionality. These tests still require completion.
This PR does however list the features/functionality that they shall cover.
Describes/depends on new tests in PR #19672 and PR #19673.
=> [chip-test] SiVal test plan updates for USBDEV

hw/bitstream/BUILD
Change the bitstream target to match the design name. There was a mismatch between the CI template and the bazel build targets for the cached archives. Go with the CI template.
=> [bitstream] Make cached bitstreams match the design name

hw/top_earlgrey/dv/env/seq_lib/chip_sw_all_escalation_resets_vseq.sv
The SW_FATAL_ERR CSR in rv_core_ibex is affected by a bug. Disable the corresponding escalation in the chip_sw_all_escalation_resets test.
=> [top_level,tests] Disable escalation affected by bug #19774

hw/ip/otbn/dv/uvm/env/otbn_env.core, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_zero_state_err_urnd_vseq.sv
This has 2 simple commits that may fix some otbn failures I see in CI. I cannot guarantee they do since I used VCS to diagnose it, but enabling VCS is good in any case.
Fixes #19815
=> [dv,otbn] Fix otbn unit tests

doc/security/cryptolib/cryptolib_api.md, sw/device/lib/crypto/impl/aes.c, sw/device/lib/crypto/include/aes.h
1. Added the missing crypto_key_security_level enum.
2. Updated the AES-KWP function names as wrap/unwrap instead of encrypt/decrypt, to match NIST spec.
=> [doc] Updates to crypto user guide doc

hw/ip/clkmgr/dv/env/clkmgr_env.core
The clkmgr_pkg and pwrmgr_pkg are obviously missing.
=> [dv/clkmgr] Fix clkmgr_env.core dependencies

sw/device/lib/testing/otp_ctrl_testutils.c, sw/device/lib/testing/otp_ctrl_testutils.h
Adds testutils for reading OTP arrays, which is useful for provisioning code developement.
=> [otp_ctrl] add test util to read OTP array

hw/ip/gpio/data/gpio.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson
1. Added list of features to the gpio specification.
2. Moved adc_ctrl chip tests to chip_gpio_testplan.hjson
3. Added si_stage: SV* test cases to cover functionality enumerated in the list of features.
4. Updated the pre-silicon test cases with relevant SV* labels.
=> [gpio,SiVal] Testplan update for gpio

hw/ip/edn/dv/env/edn_env_pkg.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
Added output FIFO error codes to the err_code_e enum type and to the err_vseq. This means that now errors for the output FIFO are tested in the same way as the errors for the other EDN FIFOs. The H_DataStableWhenValidAndNotReady_A assertion caused the test to fail for the newly added error codes. The assertion was triggered because the FIFO clear in the test sequence causes the host data to be unstable.
Since this is the expected behaviour in this case, the assertion is disabled shortly before the FIFO clear and reenabled right after. This commit closes issue #18223.
=> [edn/dv] Add output FIFO errors to edn_err test

sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/consts.h, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/sram_cp_provision.c, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/sram_cp_provision_functest.c
This tests the CP provisioning binary and fixes #19573.
In the process of writing the test, some bugs were fixed in the provisioning SRAM program.
=> [manuf] complete CP provisioning binary functest

hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson
This follows on from #19765, and only the last commit is unique to this PR. That has the following commit message:
```
This doesn't include SRAM_CTRL.REGWEN or SRAM_CTRL.INTEGRITY.
For the REGWEN side, this feature is provided by some templated code,
so I'm not really convinced that it's worth writing an explicit test
for.
For INTEGRITY, I don't think this feature is easily testable in
hardware without a dedicated lab. That will be covered by the
penetration testing phase, so I'm not sure that it makes sense to list
a sival test for it.
```
=> [sram_ctrl,sival] Describe sival-stage tests

hw/ip/spi_device/data/spi_device.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
Not all 'features' are covered by the current tests, this may be further fixed by either adding new tests or changing the granularity of the features identified.
=> [chip_earlgrey,spi_device,sival] Add new metadata to chip testplan for SiVal

util/py/data/gh_issue_template.hjson, util/py/scripts/create_gh_issues.py
This adds the python script used to automatically create GH issues from a HJSON data file. This is usefull for task management purposes for OpenTitan subprojects.
=> [util] add issue creation script and example HJSON data file

azure-pipelines.yml, sw/device/lib/testing/test_framework/ottf_main.h
Ask me how I ran into this one (it was RSA key generation). Doing the arithmetic to get microseconds here would require importing `math.h` and using `udiv64_slow` and also be annoying to print, so for the large cycle counts I just didn't print the microseconds.
=> [ottf] Allow printing cycle counts that don't fit in uint32_t.

sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson, sw/device/silicon_creator/rom/e2e/BUILD, sw/device/silicon_creator/rom/e2e/hang_test.c
The test does not make sense: it asks the watchdog to shutdown after 2 seconds but the waits only 1 second before returning. Therefore the shutdown nevers happens while waiting and the tests fails. This commit fixes the test by setting the watchdog bite threshold at 1 second and change the test to wait 2 seconds. This way, and with some margin, it will always reset during the wait.
I also change the flash program to display the value of the watchdog count after the loop. The idea is for the test to verify that in certain LC states, the watchdog was actually disabled. Ideally, a further test should be added to verify that in PROD, if we wait only half a second, the value will be printed before the shutdown and show the expected value.
=> [e2e] Fix rom_e2e_shutdown_watchdog

sw/device/lib/base/BUILD, sw/device/lib/base/memory_perftest.c
1. migrates all the test targets in //sw/device/lib/base to use the opentitan_test rule.
2. Relax memory_perftest checks
=> [bazel] Move lib/base to opentitan_test

sw/device/examples/hello_usbdev/BUILD, sw/device/examples/hello_world/BUILD
Switches hellow_usbdev target to use the opentitan_binary target. Also removes unused opentitan_flash_binary rule references from BUILD files.
=> [bazel] Switch examples to opentitan_binary

hw/top_earlgrey/sw/autogen/chip/top_earlgrey.rs, util/topgen/rust.py, util/topgen/templates/toplevel.rs.tpl
* Add generation of compare related traits for enum's in `topgen`.
* Fix missing newline between memory addresses and size in template used to generate `top_earlgrey.rs`
=> [utils,topgen] Add missing trait in topgen rust template

sw/device/tests/crypto/BUILD
This commit migrates all test/crypto test targets to use the opentitan_test rule.
Fixes #19927
=> [bazel] Move test/crypto tests to opentitan_test

azure-pipelines.yml, hw/dv/tools/dvsim/sim.mk, hw/top_earlgrey/BUILD, rules/opentitan/cc.bzl, rules/opentitan/defs.bzl, rules/opentitan/exec_env.bzl, rules/opentitan/fpga_cw310.bzl, rules/opentitan/legacy.bzl, rules/opentitan/openocd.bzl, rules/opentitan/providers.bzl, rules/opentitan/sim_dv.bzl, rules/opentitan/sim_verilator.bzl, rules/opentitan/transform.bzl, sw/device/lib/testing/test_rom/BUILD, sw/device/silicon_creator/manuf/tests/BUILD, sw/device/silicon_creator/rom/BUILD
1. RAM-based binaries need only produce the `.elf` file.
2. Create a `cw310_jtag_params` helper that includes the necessary
dependencies and flags for a JTAG test dispatch via opentitantool.
3. Convert a RAM/JTAG test to the new rules.
Note: this PR depends on #19650, #19697 and #19710.  You need only review the last two commits.
=> [bazel] Add capability to execute jtag/RAM tests 

hw/top_earlgrey/dv/chip_sim_cfg.hjson, third_party/coremark/top_earlgrey/BUILD
1. Converts //third_party/coremark/top_earlgrey/BUILD to the new build rules.
Fixes #19929
=> [bazel] Update the coremark test to use the new rules

hw/top_earlgrey/BUILD, rules/opentitan/cc.bzl, rules/opentitan/defs.bzl, rules/opentitan/exec_env.bzl, rules/opentitan/fpga_cw310.bzl, rules/opentitan/sim_dv.bzl, rules/opentitan/sim_verilator.bzl, rules/opentitan/util.bzl, sw/device/silicon_creator/rom_ext/e2e/BUILD, sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD, sw/device/silicon_creator/rom_ext/e2e/verified_boot/boot_test.c, sw/device/silicon_creator/rom_ext/rom_ext_epmp.c, sw/device/silicon_owner/BUILD
1. Add a `rom_ext` field to the execution environment.
2. When executing a test, if the test requests image assembly, assemble
a flash image for test dispatch.
3. Define an `fpga_cw310_rom_ext` execution environment.
4. Add a simple boot test for the ROM_EXT.
Drawbacks: this only works in a CW310 environment.
- Considering the time it takes to perform signature verifications in simulation, we may not even want to run these types of tests in simulation.
- `opentitantool image assemble` currently doesn't understand VMEM files, so assembling a multi-stage binary for SIM environments will be tedious.
Fixes: #19905 
Addresses: #19589
=> [bazel] Enable build/test for ROM_EXT environments

hw/dv/sv/dv_utils/dv_macros.svh, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
When multiple writes are issued to the same address of flash device, data corruption is exected and detected by checking ecc. However, flash device can only be updated from 1 to 0 (not the other way), 
and multiple writes can make data bits converge to all 0s, which can cause to fail detecting double bit error.
So expected double bit error in the error tests, is updated 
such that it can only be set after tb caculates ecc and confirms it to generate double bit error.
=> [flash_ctrl,dv] update expected double bit error set

hw/top_earlgrey/BUILD, rules/opentitan/cc.bzl, rules/opentitan/defs.bzl, sw/device/silicon_creator/rom/e2e/BUILD, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_owner/bare_metal/BUILD
1. Build the ROM_EXT with the new rules.
2. Rewrite the `bare_metal` examples to use the new rules.
This PR depends on #19949 and #19952.  You need only review the last 2 commits.
Fixes #19930 & #19931.
=> [bazel] Build ROM_EXT with the new rules 

hw/ip/otp_ctrl/data/BUILD, hw/ip/otp_ctrl/data/earlgrey_a0_skus/BUILD, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/tests/BUILD
This adds placeholders for {CREATOR,OWNER}_SW_CFG partitions so they can used to implement the reference provisioning binaries. They will be further updated with SKU-specific values later.
This also removes unused OTP overlays.
=> [manuf] add placeholders for ES OTP *_SW_CFGs

azure-pipelines.yml
It seems that recently, every CI run of "CW310 ROM Tests" times out waiting for hw/bitstream/vivado/build.fpga_cw310_hyperdebug, which it should not be needing.
Alex suggested this as a remedy.
Example problematic run:
https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=130827&view=logs&j=f9206ac2-13eb-5806-2180-615f4d046dc1&t=c1c08aa9-be7b-5018-2cf1-c73aaa1c8058
=> [ci] Avoiding timeout in "CW310 ROM Tests"

hw/ip/spi_host/data/spi_host.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
This is an initial go at creating silicon validation tests for the SPI host block. For now I've listed features and created a separate file, but still need to add additional tests.
Adding @hcallahan-lowrisc for visibility.
=> [spi_host,sival] Silicon validation test for SPI host

rules/opentitan/openocd.bzl, rules/opentitan_test.bzl, sw/device/silicon_creator/manuf/tests/BUILD, sw/device/tests/BUILD, sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/backend/chip_whisperer.rs, sw/host/opentitanlib/src/io/jtag.rs, sw/host/opentitanlib/src/transport/chip_whisperer/mod.rs, sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs, sw/host/opentitanlib/src/transport/hyperdebug/mod.rs, sw/host/opentitanlib/src/util/openocd.rs, third_party/hyperdebug/repos.bzl, third_party/openocd/BUILD
HyperDebug now supports the CMSIS-DAP protocol which OpenOCD already has a transport driver for.  With this change, the HyperDebug backend driver is able to start up OpenOCD with appropriate parameters to have it connect to the same HyperDebug.
=> [opentitantool] Add JTAG support to HyperDebug backend

hw/ip/uart/data/uart.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_uart_testplan.hjson
This comes in several commits. It's a bit difficult to know how many features/tests to define for the UART: it has lots! So I've tried to extract the features that look like they will be important for sival.
I'm very happy to add more! But maybe that would be a sensible thing to do as a followup, so that we can at least land *something* soon.
=> [uart,sival] Add initial sival testplan for uart block

hw/dv/sv/jtag_agent/jtag_agent_cfg.sv, hw/dv/sv/jtag_agent/jtag_driver.sv
[This rv_dm testpoint](https://cs.opensource.google/opentitan/opentitan/+/master:hw/ip/rv_dm/data/rv_dm_testplan.hjson;drc=5d8bab5473d16577c4fc1308c70b297aa4e7c16b;l=158) requires
the jtag driver to retain Run-Test/Idle cycle greater than equal to `dtmcs.idle` (as in  [RISC-V debug spec](https://github.com/riscv/riscv-debug-spec/raw/4e0bb0fc2d843473db2356623792c6b7603b94d4/riscv-debug-release.pdf)).
To achieve minimum value (1cycle), we need a knob to skip default 1 cycle delay of the driver task.
=> [jtag,dv] add min rti duration knob

sw/otbn/crypto/BUILD, sw/otbn/crypto/boot.s, sw/otbn/crypto/p256_base.s, sw/otbn/crypto/p256_verify.s, sw/otbn/crypto/tests/BUILD
This is the product of some discussions between @timothytrippel; this is one single OTBN binary that provides all the crypto services ROM_EXT needs for attestation/secure boot. The purpose is to
- provide a safe way to store the attestation signing key just long enough to sign the next stage's public key without rebooting
- save boot time from wiping/re-loading OTBN programs
The first commit moves some code that signing doesn't use from `p256_base.s` (shared between sign and verify) to `p256_verify.s` so that P-256 signing and RSA-3072 modexp fit together in OTBN's IMEM. No code is changed in that commit, only moved to a different file.
=> [rom_ext] Add a unified boot-time OTBN program.

sw/device/lib/crypto/impl/ecc.c, sw/device/lib/crypto/impl/ecc/ecdsa_p256.c, sw/device/lib/crypto/impl/ecc/ecdsa_p256.h, sw/device/lib/crypto/include/ecc.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/ecdsa_p256_sideload_functest.c, sw/otbn/crypto/p256_ecdsa.s
This adds the infrastructure to support sideloaded ECDSA-P256 keys. The OTBN code already existed (although I did spot a security issue with it and added an issue + TODO).
Contains some small API changes; because of the recent change to move diversification data into the keyblob from the key configuration, I had to make asynchronous ECC keygen routines take full keys instead of just configurations.
=> [crypto] Add support for sideloaded keys in ECDSA P-256.

rules/opentitan/defs.bzl, rules/opentitan/fpga_cw310.bzl, rules/opentitan/openocd.bzl, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/tests/BUILD, sw/device/tests/crypto/BUILD
This PR contains two other changes:
- fix support for overriding the RSA/SPX key and manifest in `opentitan_test`
- fix cw310_jtag_params
- add a test to make sure that all arguments of `opentitan_test` are used
See individual commits for details.
=> [Bazel] convert manuf/lib to the new rules

hw/ip/edn/dv/tests/edn_intr_test.sv
After some investigating the addition to run the interrupt test in boot and auto mode was deemed unnecessary since it is already covered by other tests. Such as edn_err or edn_genbits.
This PR closes issue #18971.
=> [edn/dv] Remove todo comment for intr test

hw/ip/edn/dv/cov/edn_cov_if.sv, hw/ip/edn/dv/env/edn_env_pkg.sv, hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_intr_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv
This PR adds new cover points to the cs_cmds cover group.
Namely acmd, the operational mode and the cmd src registers.
For more information on the added features please see the commit
messages.
This PR closes issue #19855.
=> [edn/dv] Add new coverpoints to cs_cmds cover group

hw/dv/sv/dv_utils/dv_macros.svh, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
=> [earlgrey_es] Cherry-pick

sw/host/opentitanlib/src/app/config/opentitan_cw310.json, sw/host/opentitanlib/src/app/config/opentitan_cw340.json, sw/host/opentitanlib/src/app/mod.rs, sw/host/opentitanlib/src/transport/chip_whisperer/board.rs, sw/host/opentitanlib/src/transport/chip_whisperer/gpio.rs, sw/host/opentitanlib/src/transport/chip_whisperer/spi.rs
This is one more step on the way to moving all pin declarations out of `chip_whisperer/board.rs` and into json configuration files to be parsed by `TransportWrapper`.
=> [opentitantool] Move SPI pin declaration from Rust into json

sw/host/opentitanlib/src/io/jtag.rs, sw/host/opentitanlib/src/util/openocd.rs
When backend transports choose to start openocd as a sub-process, for use as part of the implementation of the `Jtag` trait, the caller needs not care or know which TCP port is being used for communication between the struct implementing `Jtag` and the sub-process.
This CL instructs openocd to choose any available port, and has the helper functions in `openocd.rs` recognize the chosen port among the stderr output of the openocd sub-process, in order to establish connection.
This will ensure that tests or manual invocations of opentitanlib are not adversely affected by an unrelated OpenOCD process already having bound to one of the default ports.
=> [opentitantool] Do not specify OpenOCD ports

sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.h, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/sram_ft_provision.c, sw/device/silicon_creator/manuf/tests/sram_device_info_flash_wr_functest.c
This removes an un-needed function that configures both OTP *SwCfg partitions at once, since there are functions that provision each one individually. This should ease the burden of maintenance on this lib.
=> [manuf] remove un-needed OTP *SwCfg partition config function

hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/chip_smoketests.hjson, sw/device/tests/BUILD
This is a continuation of #20006.
Partially addresses #19926.
=> [bazel] Migrate device/tests to open_test

hw/ip/clkmgr/data/clkmgr.hjson.tpl, hw/ip/rstmgr/data/rstmgr.hjson.tpl, hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson, hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson, hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson, hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson, hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson, sw/device/tests/alert_handler_lpg_clkoff_test.c
This has 3 commits:
- Change fpga_cw310 to cw310 in the bazel test targets
- Update testplans to deal with alert_handler clock and reset enables
- Fix simple issues in alert_handler_lpg_clkoff_test.c
=> [sival,mgr_tests] Update clk/pwr/rstmgr tests

quality/BUILD.bazel
I noticed that recently `bazel run //quality:clang_format_fix` had been taking a really long time, so I dug into why a little bit. Looks like it was going through all the build junk from `build-site` for those who have built the website since cleaning; on my machine this change takes `clang_format_fix` from 4m38s to 7s.
=> [quality] Exclude build-site from clang-format.

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/doc/registers.md, hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv, hw/ip/prim/rtl/prim_subreg_arb.sv, hw/ip/rv_core_ibex/data/rv_core_ibex.hjson, hw/ip/rv_core_ibex/doc/registers.md, hw/ip/rv_core_ibex/rtl/rv_core_ibex_cfg_reg_top.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_all_escalation_resets_vseq.sv, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_core_reg_top.sv
This PR is a port of https://github.com/lowRISC/opentitan-integrated/pull/550 for the discrete OT.
This PR corrects the register behaviour of Mubi RW1S/RW1C registers and uses them instead of RW0C to preserve the API of their instances.
Closes https://github.com/lowRISC/opentitan/issues/19774
=> [hw,prim,rtl] Fix Mubi RW1S/RW1C behaviour and usages

sw/device/lib/dif/dif_flash_ctrl.c, sw/device/lib/dif/dif_flash_ctrl.h, sw/device/tests/BUILD, sw/device/tests/flash_ctrl_ops_test.c
Current bootstrap set default region property from programmed otp value
[as in here](https://github.com/lowRISC/opentitan/blob/2f58b40b9ce2f44b8e1f65cf87043eff97b0ad6c/sw/device/silicon_creator/lib/drivers/flash_ctrl.c#L270-L275)
Adjust region parameter accordingly to match current flash contents wrriten by bootstrap.
=> [chip,sival,flash_ctrl] fix fpga test

doc/security/cryptolib/cryptolib_api.md, sw/device/lib/crypto/impl/hash.c, sw/device/lib/crypto/impl/mac.c, sw/device/lib/crypto/include/hash.h, sw/device/silicon_creator/manuf/lib/util.c, sw/device/tests/crypto/kmac_functest.c, sw/device/tests/crypto/sha256_functest.c, sw/device/tests/crypto/sha384_functest.c, sw/device/tests/crypto/sha512_functest.c
This is a precursor to switching some signature schemes from taking raw messages to taking hash digests as input, and also generally makes some things a little clearer because hash digests now "remember" which hash function they came from.
=> [crypto] Add a specialized buffer type for hash digests.

rules/opentitan/exec_env.bzl, rules/opentitan/fpga_cw310.bzl, rules/opentitan/providers.bzl, rules/opentitan/sim_dv.bzl, rules/opentitan/sim_verilator.bzl
1. Refactor the `_test_dispatch` functions into common code.
2. Create `param` dictionary entries for all files carried by the binary info providers.  This allows a test to pass specific resources built by a binary rule to the test command.  The "default" field is added to the param dictionary without adornments whereas all of the other fields are added to the dictionary with as `name:fieldname` (e.g. `firmware:elf`).
Partially addresses #19908
=> [bazel] Refactor `_test_dispatch` functions

hw/top_earlgrey/BUILD, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/closed_source/BUILD.bazel
This change migrates all closed source hook tests to opentitan_test.
Removed params argument from //hw/top_earlgrey:sim_dv as the "$(location //hw/top_earlgrey/dv:chip_sim_cfg.hjson)" parameter could not be resolved from the @manufacturer_test_hooks// context.
Partially addresses #19797.
=> [bazel] Migrate closed_source to opentitan_test.

hw/dv/sv/csrng_agent/csrng_agent_cov.sv, hw/ip/edn/dv/edn_sim_cfg.hjson, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv
This PR contains multiple commits relating to filling csrng cmd coverage holes.
Please see the individual commit messages for more detailed information.
This PR closes issue #19833.
=> [edn/dv] Fill csrng cmd coverage holes

hw/ip/prim/lint/prim_cipher.vlt, hw/ip/prim/rtl/prim_prince.sv
No functional change (hopefully!), but this works around a warning that is triggered with recent versions of Verilator.
=> [prim_prince] Split an array in the RTL

sw/otbn/crypto/BUILD, sw/otbn/crypto/p256_ecdh.s, sw/otbn/crypto/p256_isoncurve.s, sw/otbn/crypto/p256_verify.s, sw/otbn/crypto/tests/BUILD
Previously, ECDH-P256 didn't actually check that the public key was a valid curve point. Now it does. I had to move `p256_isoncurve` to a new file so that ECDH and ECDSA verify can both use it without increasing the code size of ECDSA sign.
=> [crypto] Add checks to ECDH that ensure the public key is valid.

hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv
Closed source has long reset period (> 1ms).
If `wait_rom_check_done()` is called during the reset period, 
this task pass without checking and causes false failure. 
wait for aon clock to make sure reset is de-asserted.
=> [chip,dv] add reset deassert safeguard

SUMMARY.md, hw/bitstream/README.md, hw/ip/otp_ctrl/data/README.md, sw/device/tests/README.md
This change adds initial documentation for build infrastructure support for OTP and bitstream configurations.
The new documents are cross-referenced in device test documentation.
=> [sival] Add OTP and bitstream docs.

sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/device/silicon_owner/BUILD
1. Test booting owner code in both the A & B slots.  Test booting owner code in A & B via the virtual remap window.
2. Fix an error in the remap window configuration in the rom_ext.
=> [rom_ext_e2e] Implement the boot positions tests

sw/device/silicon_creator/rom/e2e/keymgr/BUILD
=> [bazel] Migrate e2e keymgr_init to new test rules.

sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints/BUILD
=> [bazel] Migrate e2e usage constraints to new test rules.

sw/device/silicon_creator/rom/e2e/sigverify_mod_exp/BUILD, sw/device/silicon_creator/rom/e2e/sigverify_mod_exp/sigverify_mod_exp.c
=> [bazel] Migrate e2e sigverify_mod_exp to new build/test rules.

sw/device/silicon_creator/rom/e2e/shutdown_watchdog/BUILD
=> [bazel] Migrate e2e shutdown_watchdog to new build/test rules.

sw/device/silicon_creator/rom/e2e/BUILD, sw/device/silicon_creator/rom/e2e/shutdown_output/BUILD
=> [bazel] Migrate e2e shutdown_output to new build/test rules.

hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson
Checking the baudrate accuracy in the automatic test would be quite challenging, so I'm proposing in this PR that we change the test plan to check the throughput and let the baudrate to be tested manually using external measurement equipment.
=> [sival, i2c] Remove the speed check from the testplan

sw/device/lib/crypto/impl/ecc.c, sw/device/lib/crypto/impl/ecc/ecdh_p256.c, sw/device/lib/crypto/impl/ecc/ecdh_p256.h, sw/device/lib/crypto/impl/keyblob.c, sw/device/lib/crypto/impl/keyblob.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/aes_sideload_functest.c, sw/device/tests/crypto/ecdh_p256_sideload_functest.c, sw/device/tests/crypto/ecdsa_p256_sideload_functest.c
Threads support for hardware-backed keys up to the cryptolib API, and adds a test. I also slightly adjusted `keyblob.c` so that `keyblob_num_words` gives the correct answer for hardware-backed keys as well as non-hardware-backed ones, since this avoids hardcoded magic numbers in tests.
=> [crypto] Add ECDH-P256 sideloading support.

hw/top_earlgrey/data/ip/chip_rv_timer_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/rv_timer_systick_test.c
This PR:
- Remove the 1ms test from the testplan because it would require a prescale bigger than available.
- Reduce the test tolerance from 5% to 1%, this was empirically tested on the FPGA. 
- Implement the test as described on the testplan.
Relates to #19978
=> [Sival, rv timer] Add the tick configuration test.

hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/flash_ctrl_info_access_lc.c
Current chip_sw_flash_ctrl_lc_rw_en is not transferable to sival.
Create a draft test for sival flash_ctrl_info_access_lc
- split test per lc state
- verified in sim_dv
There will be a subsequent PR with cw310 test artifacts.
=> [chip,sival] flash_ctrl info acess test

sw/device/lib/testing/json/BUILD, sw/device/lib/testing/json/command.h, sw/device/lib/testing/json/mem.c, sw/device/lib/testing/json/mem.h, sw/device/tests/BUILD, sw/device/tests/example_mem_ujcmd.c, sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/test_utils/mem.rs, sw/host/opentitanlib/src/test_utils/mod.rs, sw/host/tests/chip/mem/BUILD, sw/host/tests/chip/mem/src/main.rs
Add memory utility commands for general use. These can be used to peek
and poke the system for debug and/or to replace back door accesses in DV
with frontdoor accesses on silicon.
Add a test that peeks and pokes selected variables on the device side
(using the new ujson commands). In the test, find the addresses of the
variables by looking them up in the ELF.
In a future PR, these could be integrated into OTTF, possibly allowing for dropping into a debugger / inspection mode after returning from `test_main()`.
=> [sw] Add support for memory ujson commands

azure-pipelines.yml, ci/azure-pipelines-nightly.yml, sw/otbn/crypto/tests/BUILD
Adds a "nightly" tag and filters these test out of CI, running them as a nightly pipeline instead.
We previously discussed this option in https://github.com/lowRISC/opentitan/pull/19604; now that I want to add more slow tests in https://github.com/lowRISC/opentitan/pull/20136, I think it's a better option than increasing the timeout. I also added the tag to the two current slowest tests. (FPGA tests should catch most errors anyway, but it's useful to have the OTBN-simulator tests available e.g. to get accurate cycle counts.)
=> [ci] Move slowest OTBN-simulator tests to nightly.

sw/device/lib/testing/test_framework/BUILD, sw/device/lib/testing/test_framework/ujson_ottf_commands.c, sw/device/lib/testing/test_framework/ujson_ottf_commands.h, sw/device/tests/BUILD, sw/device/tests/example_mem_ujcmd.c
Add common ujson command handler to OTTF, which may be used to dispatch the implementing logic for memory access commands.
=> [ottf/ujson] Add common command handler to OTTF

sw/device/silicon_creator/rom/e2e/bootstrap/BUILD
* Fixes https://github.com/lowRISC/opentitan/issues/20091.
=> [bazel] Migrate e2e bootstrap to new build/test rules.

hw/ip/otp_ctrl/data/BUILD, rules/otp.bzl, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/individualize.c, sw/device/silicon_creator/manuf/lib/individualize.h, sw/device/silicon_creator/manuf/lib/individualize_functest.c, sw/device/silicon_creator/manuf/lib/otp_fields.c, sw/device/silicon_creator/manuf/lib/otp_fields.h, sw/device/silicon_creator/manuf/lib/personalize.c, sw/device/silicon_creator/manuf/lib/personalize.h, sw/device/silicon_creator/manuf/lib/personalize_functest.c, sw/host/tests/manuf/personalize/src/main.rs
The SECRET1 provisioning requires access to the CSRNG SW interface. Such access is only granted after the HW_CFG is provisioned during the "individualization" phase. Since the chip is already reset between individualization and personalization, which is required to activate the HW_CFG partition, we move this provisioning operation to the "personalize" phase.
=> [manuf] move SECRET1 provisioning function to `personalize` lib

hw/ip/otp_ctrl/data/earlgrey_a0_skus/BUILD, hw/ip/otp_ctrl/data/otp_ctrl_img.c.tpl, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.h, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg_functest.c, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/ft_personalize.c, sw/host/tests/manuf/individualize_sw_cfg/BUILD, sw/host/tests/manuf/individualize_sw_cfg/src/main.rs
The `individualize_sw_cfg` lib contains functions to provision and lock the CREATOR_SW_CFG and OWNER_SW_CFG OTP partitions. The CREATOR_SW_CFG provisioning needed to be updated to take into consideration ordering dependencies between the provisioning of various OTP partitions. Namely, the FLASH_DATA_DEFAULT_CFG field should only be provisioned after the SECRET1 partition, which can only be provisioned after the HW_CFG partition (since this enables use of the CSRNG SW interface).
To address this, API functions have been added to enable provisioning the FLASH_DATA_DEFAULT_CFG OTP field in isolation from provisioning the rest of the CREATOR_SW_CFG OTP fields.
This partially addresses #19455.
=> [manuf] add flash data config function to `individualize_sw_cfg` lib

util/dvsim/SimCfg.py
Since #20036 the seed is changed to 256-bit, which exceeds what's representable in JSON and causes the Grafana dashboard scraper to fail. This large integer should be represented with a string.
Also, take the opportunity to add build_seed into the JSON report file so we don't have to scrap it from the HTML.
=> [dvsim] fix seed in json report

sw/device/silicon_creator/rom_ext/data/rom_ext_e2e_testplan.hjson
Add tests to cover ROM-to-ROM_EXT handoff behavior and currently implemented boot services requests.
=> [rom_ext_e2e] Add more tests to the test plan

hw/dv/sv/sw_logger_if/sw_logger_if.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv, sw/device/lib/testing/test_framework/status.c, sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c
test_status_set() is often used in DV for synchronization. Announce all such calls via the console, so the majority of these synchronization points become available to SiVal's tester host.
Note that these announcements only occur if OTTF has a console active.
=> [ottf] Announce all test_status_set calls

sw/device/silicon_owner/tock/kernel/src/io.rs, sw/device/silicon_owner/tock/kernel/src/main.rs, sw/device/silicon_owner/tock/tests/basic/BUILD, sw/device/silicon_owner/tock/upstream_kernel/BUILD, third_party/tock/repos.bzl
This PR makes use of the new configuration mechanism introduced in https://github.com/tock/tock/pull/3640 to handle the new cw310 frequencies (changed in #19479). This change fixes the basic Tock test.
I also updated our board definition to work with the changes in https://github.com/tock/tock/pull/3551.
=> Update Tock to latest `master`.

sw/host/opentitanlib/src/test_utils/load_bitstream.rs, sw/host/opentitanlib/src/transport/chip_whisperer/board.rs, sw/host/opentitanlib/src/transport/chip_whisperer/mod.rs, sw/host/opentitanlib/src/transport/common/fpga.rs, sw/host/opentitanlib/src/transport/hyperdebug/mod.rs, sw/host/opentitantool/src/command/load_bitstream.rs
Checking the version of the currently running bitstream relies only on console UART and reset GPIO pin, and need not be coded at the low level of the transport backend implementation.
This PR moves the logic up above the TransportWrapper, allowing the use of aliases from JSON configuration files, rather than Rust traits.
=> [opentitantool] Eliminate POR pin from board.rs

sw/host/opentitanlib/opentitantool_derive/BUILD, sw/host/opentitanlib/opentitantool_derive/src/lib.rs, third_party/rust/Cargo.toml
syn already provides a nice diagnostics utility and there's no need to use extra crates.
Removing proc-macro-error can shrink the dependency closure by a few crates. However, this PR doesn't yet remove proc-macro-error because it's a dependency of the current serde-annotate release. We can get rid of it when bumping serde-annotate.
=> [opentitantool] remove dependency on proc_macro_error

sw/host/opentitanlib/src/transport/common/uart.rs, sw/host/opentitanlib/src/transport/ti50emulator/emu.rs, sw/host/opentitanlib/src/uart/console.rs, sw/host/opentitanlib/src/util/file.rs, sw/host/opentitantool/src/command/gpio.rs
Rust 1.63+ have BorrowedFd, OwnedFd and AsFd trait for IO-safety. We should be using these as much as possible instead of dealing with RawFds directly. (The way nix crate is dealing with raw fds is a bit fishy, many functions interacting with RawFd is marked as safe while they shouldn't. I plan to move from nix to rustix, which implements IO-safety properly, but that'll be a separate PR).
I also identified a place where a `select` call is used instead of this helper function. `select` really shouldn't be used due to its limitations on FD number. The use is converted.
=> [opentitanlib] Make `wait_read_timeout` use std io_safety

ci/azure-pipelines-nightly.yml
The previous implementation was based on the CI OTBN tests and didn't run correctly, see https://github.com/lowRISC/opentitan/pull/20195. I think this will fix it (I used the ROM e2e nightly tests as a template instead). This time I'll manually trigger a nightly run to test it -- I didn't realize that was possible before, sorry for the previous break!
=> [crypto] Fix the nightly OTBN test run.

sw/device/silicon_creator/rom_ext/e2e/handoff/BUILD, sw/device/silicon_creator/rom_ext/e2e/handoff/fault_common.ld, sw/device/silicon_creator/rom_ext/e2e/handoff/fault_slot_a.ld, sw/device/silicon_creator/rom_ext/e2e/handoff/fault_start.S, sw/device/silicon_creator/rom_ext/e2e/handoff/fault_test.c
This is a bare metal test program that does not install its own MTVEC, thus leaving the ROM_EXT vectors in place.  The test program can create several different fault types; the test configurations look for an appropriate `BFV` in the console output.
=> [rom_ext_e2e] Test the fault/shutdown handler

hw/ip/aes/data/aes.hjson, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
This PR adds a list of features to `aes.hjson`, moves AES testplan into a separate file and extends existing tests to cover more features.
=> [aes,SiVal] Add SiVal test plans

hw/top_earlgrey/BUILD, sw/device/tests/BUILD
Introduce the following SiVal emulation targets:
- fpga_cw310_sival
- fpga_cw310_sival_rom_ext
Both targets are based on the real ROM with fake keys configuration, and will eventually be updated to support the code signing strategy adopted by SiVal.
=> [sival] Add CW310 SiVal targets.

sw/device/lib/dif/dif_aes.h
While working with dif_aes, I've noticed a few harmless typos in the comments. Fixing them here
=> Fix a few typos in dif_aes.h

sw/device/lib/crypto/impl/aes_kwp/BUILD, sw/device/lib/crypto/impl/aes_kwp/aes_kwp.c, sw/device/lib/crypto/impl/aes_kwp/aes_kwp.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/aes_kwp_kat_functest.c
This adds an implementation and test for AES-KWP.
Unlike most of the cryptolib API, our top-level interface for AES-KWP is slightly different than the spec; it encrypts entire blinded keys, not bytestreams:
https://github.com/lowRISC/opentitan/blob/1845d62ae788da1bf57a0153c6e53eae5dc1987e/sw/device/lib/crypto/include/aes.h#L310-L312
This means we won't be able to run KAT tests through the API, so it's important to have an internal interface that matches the spec and is suitable for encrypting raw bytestreams.
=> [crypto] Add a core implementation of AES-KWP and basic tests.

sw/device/tests/BUILD
They fail almost systematically in CI.
=> [bazel] Mark hyperdebug openocd tests as broken

sw/device/lib/crypto/include/ecc.h, sw/device/silicon_creator/manuf/lib/personalize.c, sw/device/tests/crypto/ecdh_p256_functest.c, sw/device/tests/crypto/ecdh_p256_sideload_functest.c, sw/device/tests/crypto/ecdsa_p256_functest.c, sw/device/tests/crypto/ecdsa_p256_sideload_functest.c
This is a small cleanup, but it makes instantiating named curves a lot easier. Previously, as you can see in the tests, the caller had to construct a whole dummy domain parameters struct for named curves.
Part of #19549
=> [crypto] Allow NULL for ECC domain parameters.

hw/ip/lc_ctrl/data/lc_ctrl.hjson, hw/ip/lc_ctrl/doc/registers.md
Cherry-picked change.
This is only a SW fix since it does not impact the RTL.
Fixes #20206.
=> [lc_ctrl/sw] Correct ID state enum

hw/top_earlgrey/dv/chip_sim_cfg.hjson
=> [top_earlgrey,sim_cfg] Fix sw image for alert_handler lpg_sleep_mode_alerts

hw/top_earlgrey/data/chip_testplan.hjson
This PR adds the `si_stage: SV2` key and the list of Bazel targets for the smoketest testplan item.
=> [sw] Add SiVal keys to testplan for smoketests

sw/device/silicon_creator/rom_ext/doc/manifest.md
This updates the `timestamp` field's documentation to match its current implementation.
=> [rom_ext] Manifest documentation: indicate `timestamp` is 32-bit aligned.

sw/device/lib/testing/test_framework/BUILD, sw/device/lib/testing/test_framework/ottf_utils.h, sw/device/tests/BUILD, sw/device/tests/example_sival.c, sw/host/tests/chip/example_sival/BUILD, sw/host/tests/chip/example_sival/main.rs
This PR does several things:
- modify the test framework `status` so that it can call a custom abort function
- modify ottf to override the status abort function so it can report status in all case and run the debugger
- implement a ujson debugger that is called when a test passes or failed, this debugger accepts the memory commands
- the debugger also has an `exit` command to exit the loop
- a test can use the `OTTF_DEBUG_UNTIL` macros to call the debugger and wait until a condition is true, for example `OTTF_DEBUG_UNTIL(kPhase != kWaitHost1);`
- there is an example to put everything together, the device having four phases that require host intervention
Run with
```bash
./bazelisk.sh test --test_output=streamed --cache_test_results=no //sw/device/tests:example_sival_fpga_cw310_test_rom …
```
=> OTTF sival library + example

hw/ip_templates/rv_plic/data/rv_plic.hjson.tpl, hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/data/ip/chip_rv_plic_testplan.hjson, hw/top_earlgrey/ip_autogen/rv_plic/data/rv_plic.hjson
There's nothing very exciting here: the main change is moving the entries out of chip_testplan.hjson.
This is equivalent to #19790, but I've split the changes into separate commits, which should make things a bit easier to review.
=> [rv_plic,sival] Add sival testplan entries for rv_plic

bazelisk.sh
* Suppress the error output of `which bazel` if only bazelisk is in path but not bazel.
* Use `${1-}` instead of `$1` so that the script will not fail when no subcommand is provided, but rather forward to bazelisk to print the help message.
=> [bazelisk] various small improvements

azure-pipelines.yml, ci/azure-pipelines-nightly.yml
This PR adds the `BOARD -equals cw310` demand to the Azure pipeline for jobs running in the FPGA pool.
This PR itself is harmless, but makes way for future work that simplifies our CI setup.
Currently, all Azure CI agents in our `FPGA` pool have a CW310 connected and meet this demand.
We have a second pool called `FPGA CW340` with CW340 boards connected (which have the `BOARD -equals cw340` property set).
We would like to merge these two pools into one `FPGA` pool and select the correct board using `demands:`.
This will allow us to make the `FPGA` string an Azure variable which can be changed to `FPGA Staging` when testing hardware without having to open a PR and manually manipulate azure-pipelines.yaml. (The `FPGA Staging` pool is where we put boards that have had a hardware problem like …
=> [ci] Add CW310 demand to FPGA pool requirements

sw/device/silicon_creator/lib/boot_svc/BUILD, sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.c, sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_empty_unittest.cc, sw/device/silicon_creator/lib/error.h, sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD, sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_bad_next_test.c, sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_empty_test.c, sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_next_test.c, sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.c, sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.h, sw/device/silicon_creator/rom_ext/rom_ext.c
1. Fix the ROM_EXT NextBl0Slot behavior.
2. Check a temporary boot to side B.
3. Check that a bad boot slot request produces an error status.
This PR depends on #20207.  You need only review the last two commits.
=> [rom_ext_e2e] Add a tests for NextBl0Slot 

sw/host/opentitanlib/src/proxy/handler.rs, sw/host/opentitanlib/src/proxy/protocol.rs, sw/host/opentitanlib/src/transport/proxy/gpio.rs
The gpio trait has a `set()` method that allows simultaneously setting mode, logic level and weak pull mode.  This both improves performance on HyperDebug (by saving roundtrips of the textual protocol), and eliminates glitches.
For transports that do not natively support this, the trait does provide a default implementation which resolves to one, two or three separate method calls.
It appears that when this was added, I failed to extend the proxy protocol to be able to pass the `set()` method natively, and instead, the operation currently goes through the above fallback to be broken into multiple sub-operations on the client side, which is inefficient.  This CL adds straight-forward code to pass the multi-set operation via the proxy protocol.
=> [opentitantool] Add gpio MultiSet to proxy protocol

sw/device/lib/crypto/impl/BUILD, sw/device/lib/crypto/impl/aes.c, sw/device/lib/crypto/impl/mac.c, sw/device/lib/crypto/include/aes.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/aes_kwp_functest.c, sw/device/tests/crypto/aes_kwp_sideload_functest.c
Follow-up to https://github.com/lowRISC/opentitan/pull/20198; adds the layer that connects the cryptolib API to the internal AES-KWP implementation, and adds some checks that wrapping and then unwrapping a key (with both a sideloaded and non-sideloaded wrapping key) returns the original key.
=> [crypto] Connect AES-KWP to the cryptolib API and add basic tests.

hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson, sw/device/tests/BUILD, sw/device/tests/sram_ctrl_memset_test.c
This test:
1. writes some data to retention SRAM
2. checks it
3. sets the `INIT` bit in the `CTRL` CSR to re-initialize and randomize SRAM
4. tries to read the data back again to ensure it was wiped.
Resolves https://github.com/lowRISC/opentitan/issues/19937
I've written it to only wipe retention SRAM so that we can run the test from executable main SRAM on silicon.
=> [sw] Add sram_ctrl_memset_test

sw/device/tests/BUILD, sw/device/tests/sram_ctrl_smoketest.c
This PR updates the SRAM_CTRL smoketest to write to and read from the owner section of the SRAM, rather than the base address. This prevents overwriting ROM_EXT's usage of the retention SRAM when testing silicon.
=> [sw/sram_ctrl] Use owner section of ret SRAM for smoketest

hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv, sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c
This PR adds an extra sync point between writing the expected data (via backdoor on the testbench side) and checking the actual data against the expected (on the software side).
The current code relies on the testbench running fast enough that it will finish writing the expected data before we get to checking it.
This PR ensures we don't have a race here when this test is ported to silicon where the timing could be closer.
(I've also slipped in a commit here changing an array of length one to a scalar type).
=> [dv] Add extra synchronisation to sram_ctrl_scrambled_access test

sw/device/silicon_creator/rom_ext/data/rom_ext_e2e_testplan.hjson, util/py/scripts/gh_testplan.py
1. Add a script that creates issues from testplan files via the github CLI client.  Additional issue metadata is supplied by the top-level `github_issue_template` object and the per-issue `github` objects. Upon creating an issue, the URL of the issue is written back to the testplan.
2. Run the script on the `rom_ext_e2e_testplan.hjson` file, creating the issues listed in https://github.com/orgs/lowRISC/projects/13/views/58.
=> [rom_ext_e2e] Create issues & update testplan

third_party/hyperdebug/repos.bzl
Use a newer HyperDebug firmware, which has improved ability to capture rapid sequences of changes through the `GpioMonitoring` trait.
Going forward, HyperDebug can record one edge per microsecond, which enables capture of I2C or SPI communication, as long as the clock rate is reduced to around 100kHz.
=> [opentitantool] Improved HyperDebug firmware

sw/device/lib/crypto/impl/ecc.c, sw/device/lib/crypto/impl/rsa.c, sw/device/lib/crypto/include/ecc.h, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/ecdsa_p256_functest.c, sw/device/tests/crypto/ecdsa_p256_sideload_functest.c
Much like #20138, this PR adjusts the cryptolib signature API to use message digests instead of raw messages, which is more flexible for the caller.
Follow-up to #20045
Part of #19549
=> [crypto] Adjust ECDSA to use message digests.

hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
I forgot to add the lc_states label for some tests originally. This PR also adds some notes on why one of the tests can be skipped for SiVal.
=> [entropy_src,SiVal] Add missing lc_states + additional notes

sw/device/tests/power_virus_systemtest.c
This commit adds a small bugfix regarding a csrng command header. For a generate command the maximum generate length is 4095. In the previous powervirus test there was a CSRNG command header with a generate length of 4096.
=> [chip-level/powervirus] Change generate length of csrng command header

hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson, sw/device/lib/testing/BUILD, sw/device/lib/testing/i2c_testutils.c, sw/device/lib/testing/i2c_testutils.h, sw/device/lib/testing/pinmux_testutils.h, sw/device/tests/i2c_target_test.c, sw/device/tests/pmod/i2c_host_accelerometer_test.c, sw/device/tests/pmod/i2c_host_ambient_light_detector_test.c, sw/device/tests/pmod/i2c_host_clock_stretching_test.c, sw/device/tests/pmod/i2c_host_compass_test.c, sw/device/tests/pmod/i2c_host_eeprom_test.c, sw/device/tests/pmod/i2c_host_fram_test.c, sw/device/tests/pmod/i2c_host_gas_sensor_test.c, sw/device/tests/pmod/i2c_host_hdc1080_humidity_temp_test.c, sw/device/tests/pmod/i2c_host_irq_test.c, sw/device/tests/pmod/i2c_host_power_monitor_test.c, sw/device/tests/sim_dv/i2c_device_tx_rx_test.c
The existing test `i2c_host_eeprom_test` already cover the NAK detection test. Therefore, this PR refactor the `i2c_host_eeprom_test` to run with multiple instances of i2c for full compliance with the test description.
Fix https://github.com/lowRISC/opentitan/issues/19839
=> [Sival, i2c] Nak detection

sw/device/silicon_creator/rom/e2e/shutdown_watchdog/BUILD, sw/device/silicon_creator/rom/e2e/shutdown_watchdog/hang_test.c
The problem turned out to be really stupid: LOG_INFO prefixes every message with `I<number>` where `<number>` has 6 digits. For some reason, the BUILD specified one zero too many so the harness failed to match the message.
During debugging, I added a function to regularly print a status which is quite useful to help narrow down problems and might be useful in CI as well so I decided to leave it.
=> [rom/e2e] Fix shutdown watchdog

sw/host/opentitanlib/src/app/config/opentitan.json
When third parties test their software on OpenTitan ASIC development boards, they are probably going to have their .json configuration file, declaring which pins are used for input or output in their code, in order to allow HyperDebug to properly stimulate and verify behavior.
Such a file would probably include `/__builtin__/hyperdebug_cw310.json`, in order to be able to refer to e.g. IOA0 when declaring aliases and pin configurations.
Since IOC5 and IOC8 can be used as GPIO when they are not used as TAP_STRAPn, and since opentitantool does not have a concept of one .json file "overriding" configuration from another .json file, it becomes a problem to declare the two pins as `PushPull` and `level: false` in the built-in `opentitan.json` (which is in turn included from …
=> [opentitantool] Leave IOC5 and IOC8 unconfigured

hw/top_earlgrey/data/ip/chip_edn_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/lib/dif/dif_edn.h, sw/device/lib/testing/edn_testutils.c, sw/device/lib/testing/edn_testutils.h, sw/device/tests/BUILD, sw/device/tests/edn_boot_mode.c
This commit mainly implements the EDN sival boot mode test.
For more detailed information please see the individual commit
messages. Part of this PR is already covered by [this](https://github.com/lowRISC/opentitan/pull/20149) PR.
This PR resolves [#20055](https://github.com/lowRISC/opentitan/issues/20055).
=> [chip-level/sival] Implement sival EDN boot mode test

sw/device/silicon_owner/tock/apps/BUILD, sw/device/silicon_owner/tock/apps/single_app_layout.ld, third_party/tock/repos.bzl, third_party/tock/tockloader_requirements.txt
This updates all the Tock dependencies to latest `master` -- except for `elf2tab`, which was causing `tockloader` to crash. I'll debug that and send an update PR in the future.
`libtock_layout.ld` was relocated to a new crate in https://github.com/tock/libtock-rs/pull/482. I removed the prompt-toolkit and wcwidth dependencies from `tockloader_requirements.txt` -- they seem to have been unnecessary all along.
=> Update our Tock dependencies.

hw/bitstream/BUILD, hw/ip/otp_ctrl/data/BUILD, hw/ip/otp_ctrl/data/earlgrey_a0_skus/generic/BUILD, hw/ip/otp_ctrl/data/earlgrey_a0_skus/sival/BUILD, hw/top_earlgrey/BUILD, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/rom_ext/BUILD, sw/device/tests/BUILD
This commit adds a set of SiVal SKU configurations for prod, prod_end
and dev life cycle stages.
The CW310 SiVal emulation targets were updated to use the prod
personalized configuration to reflect the configuration of device we are
planning to use for silicon validation.
=> [sival] Add SiVal OTP SKU.

sw/device/tests/BUILD
Update the flash_ctrl_info_access_lc_states_personalized test suite to use
the SiVal CW310 targets.
The SiVal targets use the canonical SKU configurations for earlgrey A0. 
Only the last commit is relevant in this PR. The other commits are part of #20257.
=> [sival] Update flash_ctrl info access tests

hw/dv/dpi/gpiodpi/gpiodpi.c, hw/dv/dpi/gpiodpi/gpiodpi.h, hw/dv/dpi/gpiodpi/gpiodpi.sv, hw/dv/dpi/spidpi/spidpi.c, hw/dv/dpi/spidpi/spidpi.h, hw/dv/dpi/spidpi/spidpi.sv, hw/dv/dpi/uartdpi/uartdpi.c, hw/dv/dpi/uartdpi/uartdpi.h, hw/dv/dpi/uartdpi/uartdpi.sv, hw/dv/dpi/usbdpi/usbdpi.h
In order to use these DPI code in the regular sim_dv environment they need to pass more stringent linters and compilers.
The prior versions were only used in the verilator flow.
The first two commits, one for C and the other for SV files, deal with this.
The third commit removes implementation details from the C header files..
=> [top_level,dpi] Fix C and SV code errors

sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/io/jtag.rs, sw/host/opentitanlib/src/transport/chip_whisperer/mod.rs, sw/host/opentitanlib/src/transport/hyperdebug/mod.rs, sw/host/opentitanlib/src/util/openocd.rs, sw/host/tests/rom/e2e_openocd_debug_test/src/main.rs, third_party/rust/Cargo.lock, third_party/rust/Cargo.toml, third_party/rust/crates/BUILD.bazel, third_party/rust/crates/defs.bzl
This is the first PR of a series of OpenOCD-related code cleanup for opentitanlib.
The motivation is to split the monolithic `OpenOcdServer` code into multiple pieces for reuse. The current code is a single struct that handles:
* spawning and communication with openocd process and TCL server
* handling adapter setup
* handling JTAG TAP and target setup
In this PR separates the first out and enables the OpenOCD server handling part to be reused without going through the `Jtag` trait.
=> [opentitanlib] OpenOcd related refactor and cleanup

ci/fpga-template.yml
Temporary solution to lighten some CI load by avoiding bitstream rebuilds when third_party/rust is updated.
=> [ci] add third_party/rust to bitstream exclusion list

sw/device/tests/crypto/cryptotest/BUILD, sw/device/tests/crypto/cryptotest/firmware/BUILD, sw/device/tests/crypto/cryptotest/firmware/aes.c, sw/device/tests/crypto/cryptotest/firmware/aes.h, sw/device/tests/crypto/cryptotest/firmware/firmware.c, sw/device/tests/crypto/cryptotest/json/BUILD, sw/device/tests/crypto/cryptotest/json/aes_commands.c, sw/device/tests/crypto/cryptotest/json/aes_commands.h, sw/device/tests/crypto/cryptotest/json/commands.c, sw/device/tests/crypto/cryptotest/json/commands.h, sw/host/cryptotest/ujson_lib/BUILD, sw/host/cryptotest/ujson_lib/src/aes_commands.rs, sw/host/cryptotest/ujson_lib/src/commands.rs, sw/host/cryptotest/ujson_lib/src/lib.rs, sw/host/tests/crypto/BUILD, sw/host/tests/crypto/aes_nist_kat/BUILD, sw/host/tests/crypto/aes_nist_kat/src/main.rs
This commit adds the cryptotest commands for AES block cipher modes. It also provides an example of how to use these commands to run a test with the NIST KAT testvectors.
There are three components to this code:
1. AES Block Cipher uJSON Commands: the commands are defined under sw/device/tests/crypto/cryptotest/json. There are corresponding rust import stubs located at sw/host/cryptotest/ujson_lib.
2. Cryptotest Device Binary: the cryptotest binary (i.e. the on-device command handler) is located at sw/device/tests/crypto/cryptotest/firmware.
3. AES NIST KAT test program: the host-side test harness is located at sw/host/tests/crypto/aes_nist_kat.
This PR implements the framework described in #19480
=> [cryptotest] Add AES block cipher commands and aes_nist_kat test

hw/ip/usbdev/data/usbdev.hjson, hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
This PR extends the usbdev SiVal test plan to cover the AON/Wake functionality that lies outside of the usbdev IP block itself and was previously not covered by the SiVal block-wise targeting.
It does not attempt to exercise Sleep modes (either Normal or Deep), positing that these will be exercised by the power manager testing, but rather focuses upon the communications between the `usbdev` and the `usbdev_aon_wake` modules. The aim is to test the ability of `usbdev_aon_wake` to respond to significant bus events when it has assumed control of the USB:
- Resume Signaling
- Bus Reset
- Disconnection
A test for the Data Toggle Restore functionality (to be included in prod) is added, along with a test of the CPU-side access to the packet buffer memory, since the memory is anticipated to have …
=> [chip-test/usbdev] Extended SiVal test plan to include aon/wake

hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson, sw/device/tests/pmod/i2c_host_eeprom_test.c
- Rephrasing the test description to be more accurate.
- Adding a step to the `pmod/i2c_host_eeprom_test` that checks the watermarks irqs.
Fix https://github.com/lowRISC/opentitan/issues/19834
=> [Sival, i2c] chip_sw_i2c_host_tx_rx

hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson, sw/device/tests/BUILD, sw/device/tests/sram_ctrl_subword_access_test.c
This test reads and writes many permutations of byte counts and byte offsets to SRAM to check subword reading and writing.
Resolves https://github.com/lowRISC/opentitan/issues/19938.
This was adapted from the SRAM smoketest which reads and writes full words.
(Aside: this is the first device test I've written, so please do point out obvious mistakes etc.)
=> [sw] Add sram_ctrl_subword_access_test

sw/host/opentitanlib/src/dif/lc_ctrl.rs, sw/host/opentitantool/BUILD, sw/host/opentitantool/src/command/lc.rs, sw/host/opentitantool/src/command/mod.rs, sw/host/opentitantool/src/main.rs
[opentitantool] add top-level command to read current LC state
This partially addresses #20211.
Additionally, this updates the lc_ctrl DIF lib to use the (actual) redundant encoding as LC state enum values. Using the actual redundant encoding as the LC state enum values makes checking values on the Rust side easier, and simplifies the code required to implement the top-level opentitantool commands to perform LC reads and the raw unlock operation.
=> [opentitantool] add top-level command to read current LC state

sw/device/silicon_creator/manuf/tests/BUILD
The `manuf_cp_ast_test_execution` test was only being run on the unlocked0 lc state. It now runs on all eight unlocked states.
=> [manuf] sram exec test run on all lc unlocked states

sw/device/silicon_creator/rom/e2e/rom_ext_upgrade_interrupt/BUILD
Fix #20289 
The CI issue appears to be caused by bitstream not cleared after the ROM_EXT upgrade interrupt test. This causes the subsequent test to think that the bitstream does not require reload and fail since manifest version is being rolled back.
=> [test] clear bitstream after rom_ext_upgrade_interrupt

hw/top_earlgrey/data/ip/chip_rom_ctrl_testplan.hjson, sw/device/silicon_creator/rom/e2e/jtag_inject/BUILD
- Migrating the rom_e2e_openocd_debug_test to use the new bazel rules.
- Linking the chip_sw_rom_access to rom_e2e_openocd_debug_test.
Relates to https://github.com/lowRISC/opentitan/issues/19939
=> [chip-test,si-val] chip_sw_rom_access

hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv, sw/device/sca/aes_serial.c, sw/device/sca/kmac_serial.c, sw/device/sca/lib/BUILD, sw/device/sca/lib/sca.c, sw/device/sca/lib/sca.h, sw/device/sca/lib/simple_serial.c, sw/device/sca/sha3_serial.c, util/topgen/templates/chiplevel.sv.tpl
This PR modifies the SCA/FI trigger signal generation on FPGA to also add the option for a fully software-controlled trigger. This is required to prepare the SCA capture setup for the penetration testing of the ES silicon.
This is related to lowRISC/ot-sca#198.
I've successfully tested the CW310 bitstream and the AES binary generated from this PR. What's left to change / align is the CW305 as well as KMAC and OTBN binaries.
=> [top, fpga] Rework SCA/FI trigger signal selection and generation

azure-pipelines.yml
This PR sets the name of the Azure agent pool that we run FPGA jobs on to the `$(fpga_pool)` Azure variable.
The default value for this variable is `FPGA`, so normal runs will be unchanged.
Making the pool name a variable gives us the ability to trigger manual CI pipeline runs with a different value for that variable.
This is useful because we have a second agent pool called `FPGA Staging` where we put FPGAs that we want to check the hardware configuration of. Previously, we would have to open a new pull request changing `FPGA` to `FPGA Staging` to trigger a run on this pool. With this change, we can avoid creating PRs and trigger them through the Azure interface instead.
This PR leaves the CW340 pool alone for now.
=> [ci] Use fpga_pool variable for CI CW310 agent pools

third_party/openocd/repos.bzl, third_party/openocd/terminate_on_parent_death.patch
If a opentitantool or other process invokes `Jtag.connect()` but terminates for any reason before invoking `Jtag.disconnect()`, the current code may leave an orphaned openocd process, which may hold on to USB resources.
The stock OpenOCD code does not seem to have provisions to terminate e.g. when stdin closes.  This CL insteads patches OpenOCD to have it request a SIGHUP from the Linux kernel, whenever its parent terminates for any reason.
=> [opentitantool] Avoid orphaned OpenOCD processes

ci/scripts/run-fpga-tests.sh
Place bitstreams from other jobs in a consistent location, so the BUILD.bazel file and the command line for the action are not needlessly changed for every CI run.
Originally, the git revision would be part of the path name to source files, and this precluded any possibility of getting a hit to the action cache.
=> [ci] Address @bitstreams//BUILD.bazel nullifying action cache

rules/opentitan/cc.bzl, sw/host/opentitanlib/src/image/image.rs, sw/host/opentitantool/src/command/image.rs
SRAM programs don't have manifests, but we currently are still signing them with opentitantool. It happens to work for all tests *by luck*, but @HU90m is having issues when creating new tests.
This PR adds a sanity check so that OT-tool will fail when it is asked to update manifest of a binary that doesn't have one. The bazel rule is changed so SRAM programs are not signed.
=> [opentitantool] add sanity check to manifest updater

SUMMARY.md, doc/security/implementation_guidelines/README.md, doc/security/implementation_guidelines/hardware/README.md, doc/security/implementation_guidelines/reset_vs_non-reset_flops/README.md
In the past, there have been many discussions on the pros and cons of reset vs. non-reset flops for registering security sensitive assets in OpenTitan. While these discussion concluded quite some time ago already, we've never managed to transfer the summary into MarkDown and publish it as part of our documentation. This is what this PR changes.
Other key authors of this document include:
- Tim Chen - @tjaychen
- Ziv Hershman - @zi-v
- Chris Gori - @cdgori
- Scott Johnson - @sjgitty
- Johann Heyszl - @johannheyszl
This resolves lowRISC/OpenTitan#2603.
The MarkDown version of the rationale in this PR is a 1:1 copy of the Google doc previously approved for publication by TC with the following adjustments:
- Minor updates to terminology, e.g., IP block -> hardware block
- Adding a reference …
=> [doc/security] Publish reset vs. non-reset flops rationale

sw/device/lib/base/math.c, sw/device/lib/base/math.h, sw/device/lib/crypto/drivers/BUILD, sw/device/lib/crypto/drivers/entropy.c, sw/device/lib/crypto/impl/BUILD, sw/device/lib/crypto/impl/aes_kwp/BUILD, sw/device/lib/crypto/impl/aes_kwp/aes_kwp.c, sw/device/lib/crypto/impl/drbg.c, sw/device/lib/crypto/impl/keyblob.c
Use it in the crypto library in various places where the divisor is a known nonzero number.
This operation is pretty useful for determining e.g. how many words are needed to store a certain number of bytes. I added it as part of adding the RSA-PSS padding mode, but it's useful in a bunch of other places as well so I gave it its own PR to keep the changes logically separate. As you can see in the diff, it replaces a lot of ad-hoc versions of itself that are either verbose or not overflow-safe (it's kind of one or the other).
=> [crypto] Add a ceil-division operation to `math.h`.

sw/device/sca/aes_serial.c
Added two commands to support WaveRunner batch capture (see ot-sca PR [194](https://github.com/lowRISC/ot-sca/pull/194)).
Also added mask-off switch to seed_lfsr command (masks off if '0'). Note this is only available on FPGA.
The binary has been generated from:
https://github.com/vogelpi/opentitan/tree/ot-sca_2023-07-15_dd8b709_cw310
=> [sca, aes] Add commands for alternative batch capture mode

sw/device/tests/crypto/cryptotest/firmware/BUILD, sw/device/tests/crypto/cryptotest/firmware/firmware.c
The entropy complex starts with a fixed amount of entropy and does not generate more in the default configuration. Initialize the complex in auto mode, so long-running tests don't run out.
Fixes #20277
=> [cryptotest] Make sure to init the entropy complex

hw/ip/otbn/README.md, hw/ip/otbn/data/csr.yml, hw/ip/otbn/data/wsr.yml, hw/ip/otbn/util/Makefile, hw/ip/otbn/util/docs/md_isrs.py, hw/ip/otbn/util/shared/isr.py
No functional change, except that the lists of CSRs/WSRs in the documentation are now auto-generated from a big YAML file.
The plan is to use that YAML file for the other lists that you see mentioned in e.g. otbn/README.md. But I grabbed the initial list from the documentation, so "generating itself" seemed like the obvious first step.
This should be the first step to sorting out issue #3323, which tracks whether the toolchain can support named CSRs and WSRs in OTBN assembly code.
If reviewing this PR:
- You can mostly ignore the .yml files: the contents get used to generate README.md, which is also checked in.
- The script in isr.py is the thing that does the easy job of parsing the yaml.
- The script in md_isrs.py is the thing that converts the parsed yaml into a markdown table.
- …
=> [otbn,doc] Extract list of ISRs into YAML files

azure-pipelines.yml
This PR attempts to cut down total CI length by splitting the "SW build and test" into "build" and "test" jobs to shorten the critical path.
Here's a Gantt chart of a typical CI run before this PR:
You can see that "software build & test" (SWB&T) takes the longest and is a dependency of the three FPGA tests (and a short packaging test).
The FPGA jobs only depend on the software _build_, not the test part. This PR split the build & test job so that the FPGA tests can start just after the build has finished.
=> [ci] Split the 'SW build & test' job into build and test jobs

sw/device/lib/crypto/impl/aes_gcm/ghash.c, sw/device/lib/crypto/impl/aes_gcm/ghash.h, sw/device/lib/crypto/impl/aes_gcm/ghash_unittest.cc
Add a new function to process all available full blocks, but track a partial block. This is helpful for changing AES-GCM to a streaming interface.
https://github.com/lowRISC/opentitan/issues/19549
=> [crypto] Adjust GHASH interface.

sw/device/silicon_creator/lib/attestation.h, sw/device/silicon_creator/lib/otbn_boot_services.c
It is more ergonomical for the certificate templates to have the key represented by its r and s values.
@pamaury I split this up as we discussed last week. Lmk if this is what you were looking for.
=> [silicon_creator] change format of attestation signature

hw/top_earlgrey/data/ip/chip_edn_testplan.hjson, sw/device/tests/entropy_src_edn_reqs_test.c
This PR adds another test to the chip_sw_edn_entropy_reqs test
point in the edn test plan. The added test is a pre existing test
called chip_sw_entropy_src_ast_rng_req_test. This test is added since
chip_sw_entropy_src_edn_reqs_test only tests 7 out of the 8 EDN endpoints.
The endpoint for the AST is now also covered.
This PR resolves #20054
=> [chip-level/sival] Add test to testplan

hw/ip/dma/data/dma.hjson, hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv, hw/ip/dma/lint/dma.waiver, hw/ip/dma/rtl/dma.sv, hw/ip/dma/rtl/dma_reg_pkg.sv, hw/ip/dma/rtl/dma_reg_top.sv
Previously, the FW needs to manually clear the done signal after a transfer, to allow a polling loop to get the fresh data. This PR changes the hardware to automatically clear the done bit on new transfer. This removes the requirement on the FW to clear the DONE bit after a transfer.
Furthermore, it clears also the error and sha2_digest_valid bit when starting a new transfer. 
This PR is pulled over from https://github.com/lowRISC/opentitan-integrated/pull/660
/cc @alees24
=> [hw,dma,rtl] Clear STATUS when starting a new transfer

sw/ip/mbx/dif/dif_mbx.c, sw/ip/mbx/dif/dif_mbx.h, sw/ip/mbx/dif/dif_mbx_unittest.cc, sw/top_darjeeling/sw/dif/BUILD
This PR adds the initial DIF implementation for the mailbox for the host side.
This PR is a copy-over from https://github.com/lowRISC/opentitan-integrated/pull/642 and incorporates the review.
@engdoreis Can you take a look again and approve if its ok?
=> [mbx,dif] Initial implementation of the mailbox DIF

hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv
This commit adds a FIFO reset to prevent the generate FIFO from overflowing in the edn_disable_auto_req_mode test.
This only concerns xcelium.
This PR resolves #20300
=> [edn/test] Add FIFO reset to prevent overflow

sw/device/silicon_creator/lib/BUILD, sw/device/silicon_creator/lib/attestation.h, sw/device/silicon_creator/lib/drivers/flash_ctrl.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.h, sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc, sw/device/silicon_creator/lib/otbn_boot_services.c, sw/device/silicon_creator/lib/otbn_boot_services.h
The current OTBN boot services API requires the user to input the additional DRBG seed manually. Since this seed is provisioned into a flash info page at manufacturing time, this updates the code to automatically load the specified seed from the flash instead. This simplifies the user experience of driving this library.
Additionally, this adds the flash info page that holds such seeds to the list of pages that are to be locked down by the ROM_EXT upon transition to the owner stage.
**Note: this depends on #20328.**
=> [silicon_creator/lib] auto-load attestation keygen seed from flash info

SUMMARY.md, quality/BUILD.bazel, sw/host/ot_certs/BUILD, sw/host/ot_certs/README.md, sw/host/ot_certs/src/lib.rs, sw/host/ot_certs/src/template/hjson.rs, sw/host/ot_certs/src/template/mod.rs, third_party/rust/BUILD, third_party/rust/Cargo.lock, third_party/rust/Cargo.toml, third_party/rust/crates/BUILD.base64-0.21.5.bazel, third_party/rust/crates/BUILD.bazel, third_party/rust/crates/BUILD.chrono-0.4.31.bazel, third_party/rust/crates/BUILD.darling-0.20.3.bazel, third_party/rust/crates/BUILD.darling_core-0.20.3.bazel, third_party/rust/crates/BUILD.darling_macro-0.20.3.bazel, third_party/rust/crates/BUILD.deranged-0.3.8.bazel, third_party/rust/crates/BUILD.fnv-1.0.7.bazel, third_party/rust/crates/BUILD.hashbrown-0.12.3.bazel, third_party/rust/crates/BUILD.ident_case-1.0.1.bazel, third_party/rust/crates/BUILD.indexmap-1.9.3.bazel, third_party/rust/crates/BUILD.indoc-2.0.4.bazel, third_party/rust/crates/BUILD.serde_with-3.4.0.bazel, third_party/rust/crates/BUILD.serde_with_macros-3.4.0.bazel, third_party/rust/crates/defs.bzl
This is the first in a series of PRs that will build up the `ot_certs` crate.
This crate is for reading templates that define the variable and literal values of a certificate that will be installed on an OpenTitan. It will generate:
* Certificates based on a template in X.509 and CWT binary format (with holes where variable data is to be inserted).
* C code for the device to use to fill in the variable values of a certificate with concrete values.
This first PR adds the crate and some code for parsing a template. There is a unit test containing an example template.
The template is written in JSON5/Hjson and specifies various fields needed for an X.509 or CWT certificate. This certificate will live in binary format on the device's flash.
A detailed spec of how these certificates work needs …
=> [ot_certs] Add OT certificate template parser

hw/ip/dma/dv/dma_sim_cfg.hjson, hw/ip/dma/dv/env/dma_env.core, hw/ip/dma/dv/env/dma_scoreboard.sv, hw/ip/dma/dv/env/seq_lib/dma_abort_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_vseq_list.sv, hw/ip/dma/rtl/dma.sv, hw/ip/dma/rtl/dma_pkg.sv
This PR introduces a further DMA vseq to abort DMA transfers randomly.
Deriving from the 'generic' sequence, it can abort DMA transfers having any valid configuration, ie. memory-to-memory and hardware handshaking operations, with or without inline SHA digest calculations.
The vseq uses a parallel thread that executes concurrently with the FW-mimic/transfer control, and a semaphore is therefore introduced to control multithreaded access to the CONTROL register, preventing races in the RAL modifications. The logic in 'set_control' is re-expressed to reduce contention/conflict between the two threads, the scoreboard logic is modified with an awareness that Aborting overrides the starting of chunks/transfers.
It's also important to note that requesting Abort does not guarantee that test …
=> [dv,dma] Randomized Aborting of DMA transfers

hw/ip/dma/rtl/dma.sv
Reset STATUS.busy bit when the CONTROL.go bit is cleared.
The previous expression used a forwards reference to `hw2reg.control.go.de` (blocking assignment in always_comb block), and thus never cleared the busy bit except at IP block reset.
This is important in that recent changes rely upon '...status.busy.q' to ascertain whether the DMA controller is truly idle (ie. between transfers). Firmware will likely also depend upon this status bit indicator.
=> [dma] Fix STATUS.busy reset logic

sw/device/tests/crypto/BUILD, sw/device/tests/crypto/rsa_2048_keygen_functest.c, sw/device/tests/crypto/rsa_3072_keygen_functest.c, sw/device/tests/crypto/rsa_4096_keygen_functest.c
See https://github.com/lowRISC/opentitan/pull/20138#discussion_r1393512869
A previous change to the hash function handling for RSA sign/verify silently broke the keygen tests; this fixes them. Thanks to @a-will for spotting this!
I dug around in the CI scripts and found that, because these tests are marked "long" even on FPGA, they don't actually run at all in either CI or nightly. There's a test timeout filter in `ci/scripts/run-fpga-tests.sh`:
https://github.com/lowRISC/opentitan/blob/93c9a871696b7268f14b04c66ac135ac48323e28/ci/scripts/run-fpga-tests.sh#L53
...and then there's no corresponding nightly rule to run the long ones.
=> [crypto] Fix RSA keygen tests.

hw/top_earlgrey/BUILD, rules/opentitan/defs.bzl, rules/opentitan/openocd.bzl, rules/opentitan/providers.bzl, rules/opentitan/silicon.bzl, sw/device/lib/arch/BUILD, sw/device/lib/arch/device.h, sw/device/lib/arch/device_silicon.c, sw/device/silicon_creator/manuf/tests/BUILD, sw/device/silicon_creator/manuf/tests/sram_empty_functest.c, sw/host/tests/manuf/manuf_sram_program_crc_check/src/main.rs
This adds the exec_env for the silicon platform. Additionally, this adds this exec_env to a manuf test that simply loads and executes an SRAM program. SRAM program can be run with:
```
bazel test --test_output=streamed --cache_test_results=no //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked0_functest_silicon_creator
```
=> [bazel] add exec_env for the silicon platform

hw/ip/edn/data/edn_testplan.hjson, hw/ip/edn/doc/theory_of_operation.md, hw/ip/edn/dv/env/edn_scoreboard.sv
This commit removes some leftovers from when the main_sm_state register used to be called sum_sts.
This PR resolves #18469
=> [edn/doc] Update sum_sts strings to main_sm_state

azure-pipelines.yml
Currently, we set `continueOnError: true` for the HyperDebug test.
That setting allows further jobs in the pipeline to start after this one, even if it has failed. This isn't very useful since the HD tests run at the end of the pipeline anyway.
The flag does prevent us from using the "re-run failed jobs" feature of Azure, though. Azure doesn't seem to think the job failed with `continueOnError: true` set, so we have to force-push to the PR to get it to re-trigger the whole CI pipeline.
Resolves https://github.com/lowRISC/opentitan/issues/17782
=> [ci] Make hyperdebug tests blocking

hw/top_darjeeling/data/chip_testplan.hjson, hw/top_darjeeling/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/otp_ctrl_sw_parts_test.c
Adds a simple test that checks selected SW partitions in OTP_CTRL that have different attributes.
This closes [#599](https://github.com/lowRISC/opentitan-integrated/issues/599).
=> [top_darjeeling, otp_ctrl] Implement SW partition test

hw/ip/mbx/dv/env/mbx_env.sv, hw/ip/mbx/dv/env/mbx_env_cfg.sv, hw/ip/mbx/dv/env/mbx_scoreboard.sv, hw/ip/mbx/dv/env/seq_lib/mbx_base_vseq.sv, hw/ip/mbx/dv/env/seq_lib/mbx_smoke_vseq.sv, hw/ip/mbx/dv/tb.sv
This adds usage of interrupts to the mailbox smoke test referred to here: https://github.com/lowRISC/opentitan-integrated/issues/589
Rather than randomly choose between interrupts/polling instead it waits for the appropriate interrupt then checks the relevant status bit is set
=> Add interrupt usage to mailbox smoke

hw/ip/dma/data/dma.hjson, hw/ip/dma/lint/dma.waiver, hw/ip/dma/rtl/dma.sv, hw/ip/dma/rtl/dma_pkg.sv, hw/ip/dma/rtl/dma_reg_pkg.sv, hw/ip/dma/rtl/dma_reg_top.sv
This PR implements a hardware managed REGWEN, that locks up the configuration registers of the DMA during an operation. When the DMA leaves the `DmaIdle` state, the hardware locks the following registers:
|  Register| Description |
| ------------- | ------------- |
| `SOURCE_ADDRESS_LO` | Locked  |
| `SOURCE_ADDRESS_HI` | Locked  |
| `DESTINATION_ADDRESS_LO` | Locked  |
| `DESTINATION_ADDRESS_HI` | Locked  |
| `ADDRESS_SPACE_ID` | Locked  |
| `ENABLED_MEMORY_RANGE_BASE` | Not locked but captured in the DMA since it already has a REGWEN  |
| `ENABLED_MEMORY_RANGE_LIMIT` | Not locked but captured in the DMA since it already has a REGWEN  |
| `RANGE_VALID` | Not locked but captured in the DMA since it already has a REGWEN  |
| `RANGE_REGWEN` | Not Locked  |
| `CFG_REGWEN` | Register that …
=>  [hw,dma,rtl] Lock configuration registers during an operation

hw/top_earlgrey/dv/chip_rom_tests.hjson, rules/opentitan/cc.bzl, rules/opentitan/defs.bzl, rules/opentitan/keyutils.bzl, sw/device/silicon_creator/rom/e2e/BUILD, sw/device/silicon_creator/rom/e2e/boot_policy_valid/BUILD, sw/device/silicon_creator/rom/e2e/sigverify_always/BUILD, sw/device/tests/closed_source/BUILD.bazel, sw/host/opentitantool/src/command/image.rs
There is a difficult yin this BUILD file that a file needs to be a corrupted. Previously this was easy but with the new rules, this becomes a bit harder. To simplify some test cases, I modified opentitantool to allow the creation of empty files which were previously disallowed (not sure why).
Another aspect that was overlooked is dvsim: the simulator currently expects file names to follow a specific pattern when using the `signed` and key tags. This does not quite match the names produced by the new rules because the old rules could produce several names of the `<something>.<key name>` for several key names. But the new ones can only produce one such name (one for each `opentitan_binary`). For the corrupted empty_test, I got away with using a filegroup for that purpose.
For context, [this …
=> [bazel,new rules] Convert rom/e2e/sigverify_always

hw/ip/pwrmgr/dv/cov/pwrmgr_rom_ctrl_mubi_cov_if.sv, hw/ip/pwrmgr/dv/env/pwrmgr_if.sv, hw/ip/pwrmgr/dv/pwrmgr_sim_cfg.hjson, hw/ip/pwrmgr/dv/sva/pwrmgr_sec_cm_checker_assert.sv
This fixes a few minor issues in the testbench and increases a couple of timeouts so that the pass rate is close to 100%.
The SVA precondition for RstreqChkMainpd_A has been corrected on master, so this patch just aligns the assertion with master.
This closes https://github.com/lowRISC/opentitan-integrated/issues/605.
=> [pwrmgr/dv] Minor fixes to increase pass rate to V2 levels

hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
The changed tests should run in the desired life cycle states for SiVal unaltered.
Note: `chip_sw_rv_core_ibex_icache_scrambled_access` (#20028) won't test anything in SiVal until #20316 is merged.
Covers #20025 #20026 #20027
=> [sival/ibex] added bazel targets to tests that'll run in sival unaltered

hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson, sw/device/lib/testing/rv_core_ibex_testutils.h, sw/device/tests/BUILD, sw/device/tests/rstmgr_cpu_info_test.c
The test `rstmgr_cpu_info_test` was failing with ROM.
See [comment](https://github.com/lowRISC/opentitan/issues/20030#issuecomment-1808126208)
The ROM enables the watchdog to generate a NMI at bark, as this test uses the watchdog bite to reset Ibex after the second fault, the NMI generated was messing with the fault dump.
This commit makes the watchdog to bark even before the first fault, avoiding a NMI in between the faults.
Fix: https://github.com/lowRISC/opentitan/issues/20029
Fix: https://github.com/lowRISC/opentitan/issues/20030
=> [Sival, rv core ibex] Double fault 

third_party/tock/repos.bzl, third_party/tock/tockloader_requirements.txt
This update includes https://github.com/tock/tock/pull/3740 and https://github.com/tock/tock/pull/3743, which fix bugs I've been experiencing.
=> [tock] Update Tock repos to latest master.

sw/device/lib/testing/json/provisioning_data.h, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/individualize.c, sw/device/silicon_creator/manuf/lib/individualize.h, sw/device/silicon_creator/manuf/lib/individualize_functest.c, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/ft_personalize_1.c, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/ft_personalize_2.c, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/sram_ft_individualize.c, sw/host/provisioning/cp_lib/src/lib.rs, sw/host/provisioning/ft_lib/src/lib.rs, sw/host/tests/manuf/provisioning/ft/BUILD, sw/host/tests/manuf/provisioning/ft/src/main.rs
During individualization, the device ID is copied from flash info page 0 to the HwCfg OTP partition. However, the device ID in flash is not checked, and blindly copying it makes it difficult to test both CP and FT stages individually, since to test FT provisioning would require setting up flash info pages before test execution. Moreover, if the device ID is not checked for all 0s, it will cause the keymgr to lock up later during the provisioning flow.
This adds a device ID parameter to the HwCfg individualization function to override the device ID stored in flash (if it is all 0s, i.e., it is missing), or to check against what is already in flash to ensure the provisioning payload is the one expected.
=> [manuf] add device ID parameter to HwCfg individualize function

hw/bitstream/BUILD, hw/ip/otp_ctrl/data/BUILD, hw/ip/otp_ctrl/data/earlgrey_a0_skus/generic/BUILD, hw/ip/otp_ctrl/data/earlgrey_a0_skus/sival/BUILD, rules/otp.bzl, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/personalize_functest.c, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/BUILD, sw/device/silicon_creator/manuf/tests/BUILD, sw/host/tests/manuf/personalize/src/main.rs
This change introduces a list of OTP profiles to be used during Silicon Validation enablement. The current profile definitions ommit OTP permutations that are not planned for end use cases.
=> [sival] Define set of OTP profiles.

sw/device/silicon_creator/rom/e2e/sigverify_always/BUILD
1. The `cw310_params` block now forbids specifying `rom` or `otp` at the same time as `bitstream`.  Use only the `otp` parameter.
2. Eliminate the explicit bitstream splice in favor of the implicit universal splice provided by `cw310_params`.
=> [bazel] Fix `sigverify_always` bitstream splicing

sw/device/tests/BUILD, sw/device/tests/flash_ctrl_rma_test.c, sw/host/tests/chip/flash_ctrl/BUILD, sw/host/tests/chip/flash_ctrl/src/main.rs
Flash ctrl rma entry test
- Test starts from unpersonalized dev state.
- It programs fixed patterns to each info partition and execute otp secret2 partition lock
- After reboot, host triggers rma entry process with rma_unlock token provisioning.
- After rma process is finished in flash device, test does another reboot.
- After reboot, test read back info partition to make sure the data in the info partition are no longer available.
Since it does lc state transition, (dev->rma), it can be run only in fpga target.
=> [flash_ctrl,sival] flash_ctrl post rma data check test

hw/ip/otp_ctrl/data/BUILD, hw/ip/otp_ctrl/data/earlgrey_a0_skus/generic/BUILD, sw/device/tests/BUILD, sw/device/tests/flash_ctrl_rma_test.c, sw/host/tests/chip/flash_ctrl/src/main.rs
The following changes were made:
1. Use `//hw/ip/otp_ctrl/data/earlgrey_a0_skus/sival:otp_img_dev_personalized` to emulate the configuration of a DEV part. DEV parts will be distributed in personalized state.
2. Update `flash_ctrl_rma_test` to skip writing to the creator info page partition. This partition is not available in personalized mode.
3. Force bootstrap before connecting to `rv_dm`. This is to avoid triggering the watchdog during SRAM code execution. The ROM disables the watchdog in bootstrap mode.
4. Update the SiVal `SECRET2` configuration to use a known RMA unlock token.
5. Update exec_env to use `fpga_cw310_sival`. This exec_env is ok to use in this case because the device is in DEV state and code execution is done via SRAM.
=> [sival] Update flash_ctrl_rma_test to use sival infra.

azure-pipelines.yml, ci/jobs/quick-lint.sh, ci/jobs/slow-lint.sh
This step takes ~5 minutes and isn't very quick. All other CI jobs are gated on quick lints, so we do want them to be as fast as possible.
=> [ci] Move documentation build from quick-lints to slow-lints

sw/host/opentitanlib/src/util/openocd.rs, sw/host/tests/rom/e2e_openocd_debug_test/src/main.rs
Currently we don't detect JTAG initialization failure and relies on OpenOCD to fail/abort when we trying to use a broken TAP. Instead we can use the `capture` to get the log during initialization and check for the failure pattern. This improves the reliability when the expected result is failure.
=> [opentitanlib] detect JTAG initialization failure

azure-pipelines.yml, ci/azure-pipelines-nightly.yml, release/azure-pipelines-release.yml, tool_requirements.py
This PR updates the Vivado version we use in CI from 2020.2 to 2021.1.
We're seeing some issues with the CW340 bitstream in 2020.2. CI does have licenses for 2021.1, so perhaps this version will fix the issue.
I have left the minimum Vivado version requirement in [tool_requirements.py](https://github.com/lowRISC/opentitan/blob/master/tool_requirements.py), but perhaps we should keep this up to date with the CI version to ensure some guarantee of support.
**EDIT**: this is now updated.
=> [ci] Update Vivado to 2021.1

sw/device/tests/csrng_edn_concurrency_test.c
This commit changes the comment describing a function that configures the entropy complex and starts both EDNs in auto mode.
This PR resolves #20054.
=> [chip-level/sival] Change comment for configure entropy complex function

WORKSPACE, sw/host/cryptotest/testvectors/data/BUILD, sw/host/cryptotest/testvectors/data/README.md, sw/host/cryptotest/testvectors/data/schemas/BUILD, sw/host/cryptotest/testvectors/data/schemas/ecdsa_sig_ver_schema.json, sw/host/cryptotest/testvectors/parsers/BUILD, sw/host/cryptotest/testvectors/parsers/nist_cavp_ecdsa_parser.py, third_party/nist_cavp_testvectors/BUILD, third_party/nist_cavp_testvectors/BUILD.nist_cavp_common.bazel, third_party/nist_cavp_testvectors/repos.bzl
This PR adds the NIST ECDSA test vectors as a Bazel third-party dependency and adds a parser for them.
=> [cryptotest] Add NIST ECDSA test vectors and parser

hw/ip/dma/dv/env/dma_env_pkg.sv, hw/ip/dma/dv/env/dma_pull_seq.sv, hw/ip/dma/dv/env/dma_scoreboard.sv, hw/ip/dma/dv/env/seq_lib/dma_abort_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_memory_region_lock_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_stress_all_vseq.sv
This PR modifies the DV environment to support interrupt-driven testing/monitoring of the DMA controller, and not just CSR-based polling. It also introduces the ability to generate TL-UL errors to test the error handling and reporting.
**Commit 1:** Trivial tidy ups and removal of unused task. No functional change.
**Commit 2:** Modify scoreboard to have an awareness of the interrupt enable state. Support generation of TL-UL errors.
**Commit 3:** Modify the signaling of test completion, and support either interrupt-driven or CSR-polling on a per-transfer basis.
**Commit 4:** Extend the `dma_stress_all` sequence to embrace the additional testing - interrupts and TL-UL errors - as well as a modified form of the randomized register modification from the `dma_memory_region_lock` sequence. …
=> [dv,dma] Extend DMA DV for interrupt-driven testing and TL-UL error generation

hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson, sw/device/tests/BUILD, sw/device/tests/pmod/BUILD
This PR only links the spi_flash tests to the spi_host_tx_rx test in the testplan.
Fix https://github.com/lowRISC/opentitan/issues/19842
=> [sival, spi_host] chip_sw_spi_host_tx_rx

hw/bitstream/BUILD, hw/top_earlgrey/BUILD, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/BUILD, sw/device/tests/BUILD
Update test targets using sival OTP dependencies to use the new universal bitstream flow. The universal bitstream flow relies on Bazel to maintain a cache of bitstreams built with different `rom` and `otp` images.
=> [sval] Remove prebuilt-sival bitstreams.

hw/top_earlgrey/BUILD, rules/opentitan_test.bzl, sw/device/lib/testing/test_framework/BUILD, sw/device/silicon_creator/rom/e2e/BUILD, sw/device/silicon_creator/rom/e2e/rom_ext_upgrade_interrupt/BUILD, sw/host/opentitanlib/src/app/config/opentitan.json, sw/host/tests/manuf/manuf_cp_yield_test/src/main.rs, sw/host/tests/rom/e2e_bootstrap_disabled/src/main.rs, sw/host/tests/rom/e2e_bootstrap_entry/src/main.rs
Fix up IDs for UART and SPI instances. Some tests were still using "0" as the identifier for UART and SPI devices, but these are not supported across all transports. The correct identifiers are "console" for the UART console and "BOOTSTRAP" for Earl Grey's spi_device IP. The transport will convert these to the correct internal devices that interface with them.
Adjust FPGA flows to perform transport init before FPGA programming. Because the FPGA programming flow interacts with any currently-loaded OpenTitan, the host transport must be set up correctly first.
Ensure TAP straps have default values. The TAP straps should default to setting OT to have no TAP selected. Change the configs to reflect this.
=> [opentitanlib] Fix up instance names and ensure TAP straps have default values

rules/opentitan/openocd.bzl, rules/opentitan/silicon.bzl, sw/device/silicon_creator/manuf/lib/otp_fields.h, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/sram_cp_provision.c, sw/device/silicon_creator/manuf/tests/BUILD
This enables the CP provisioning program to run on the silicon target. The CP provisioning binary is also updated to print the device ID and test unlock tokens provisioned to the console so they can be tracked / saved. This prepares the CP provisioning program to be on silicon targets.
=> [manuf] add silicon exec_env to CP provisioning program

sw/device/silicon_creator/lib/BUILD, sw/device/silicon_creator/lib/attestation.h, sw/device/silicon_creator/lib/attestation_key_diversifiers.c, sw/device/silicon_creator/lib/attestation_key_diversifiers.h, sw/device/silicon_creator/lib/otbn_boot_services.c, sw/device/silicon_creator/lib/otbn_boot_services.h, sw/device/silicon_creator/manuf/lib/flash_info_fields.h, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/ft_personalize_3.c, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/sram_ft_individualize.c, sw/device/silicon_creator/rom/BUILD, sw/host/provisioning/ft_lib/src/lib.rs, sw/host/tests/manuf/provisioning/ft/src/main.rs
This adds a third (and final) personalization binary to advance the keymgr and generate attestation keys / certificates. This code was placed in a separate binary as a short term fix to name collisions between functions in the silicon_creator OTBN driver (used by the `otbn_boot_services` lib that generates the attestation keys), and the cryptolib OTBN driver (used in the `personalization` lib that provisions OTB Secret2 partition and the keymgr flash info pages).
Additionally, this:
1. adds attestation keymgr diversifiers,
2. fix bugs in otbn_boot_services lib that were causing errors when generating the attestation keys.
This partially addresses #19455.
=> [manuf] add final personalization binary to crank the keymgr and gen attestation keys

hw/top_darjeeling/dv/chip_sim_cfg.hjson, sw/device/tests/clkmgr_off_peri_test.c, sw/device/tests/clkmgr_off_trans_impl.c, sw/device/tests/rstmgr_alert_info_test.c
Follwing tests are fixed.
- clkmgr_off_peri_test.c   // It is disabled from chip_sim_cfg due to flash dependency.
- clkmgr_off_trans_impl.c
- rstmgr_alert_info_test.c
=> [chip, darjeeling, clkmgr, rstmgr] clkmgr rstmgr wdog fix

sw/device/tests/sram_ctrl_execution_test.c
sram_ctrl_execution_test was missing a configuration that ensured execution was enabled in sram_ctrl's CSR. When the default OTP settings for tests changed to have EN_SRAM_IFETCH set to mubi true, SRAM execution was no longer enabled simply from being in the RMA state. This fixes the test so it also enables execution in the CSR.
=> [test] Enable SRAM execution in sram_ctrl for its test

hw/ip/dma/dv/env/dma_env_cfg.sv, hw/ip/dma/dv/env/dma_scoreboard.sv, hw/ip/dma/dv/env/dma_seq_item.sv, hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_handshake_smoke_vseq.sv
This PR makes the changes necessary to enable the 'Clear Interrupt' write traffic in all sequences/configurations.
**Commit 1:** No functional change
**Commit 2:** Modify the way that the scoreboard differentiates 'Clear Interrupt' traffic from regular bus traffic
**Commit 3:** Restructure the checking of read/write traffic to avoid crosstalk between 'Clear Interrupt' traffic and regular bus traffic. This is mostly code migration, moving into the 'write data' fork checks that shall not be performed on interrupt-clearing write operations.
**Commit 4:** Dynamically enable/disable interrupts according to whether we're using polling or interrupts to mediate/monitor the transfer.
This commit also removes the DV constraints that prevented interrupts from being cleared previously, now that the …
=> [dv,dma] Bring up of 'Clear Interrupt' traffic

rules/opentitan/fpga_cw310.bzl, rules/opentitan/silicon.bzl, rules/opentitan/sim_dv.bzl, rules/opentitan/sim_verilator.bzl
Restore the ability to apply --test_arg to opentitan_test invocations. This is especially useful for extracting waves from Verilator simulations.
=> [test] Restore ability to add --test_arg

hw/top_earlgrey/BUILD, hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson, sw/device/tests/BUILD, sw/device/tests/doc/sival/README.md, sw/device/tests/sival/BUILD
1. Add `cw310_sival` and `cw310_sival_rom_ext` tags to respective targets in //hw/top_earlgrey. This is to allow filtering test execution by execution environment.
2. Add //sw/device/tests/sival/BUILD to maintain test suites for various SiVal stages.
3. Update a couple of SV1 test cases to enable support for `sival` execution environments.
=> [sival] Add `sv1_test` test_suite.

hw/ip/mbx/data/mbx.hjson, hw/ip/mbx/dv/env/mbx_env_pkg.sv, hw/ip/mbx/dv/tb.sv, hw/ip/mbx/rtl/mbx.sv, hw/ip/mbx/rtl/mbx_core_reg_top.sv, hw/ip/mbx/rtl/mbx_fsm.sv, hw/ip/mbx/rtl/mbx_hostif.sv, hw/ip/mbx/rtl/mbx_imbx.sv, hw/ip/mbx/rtl/mbx_ombx.sv, hw/ip/mbx/rtl/mbx_reg_pkg.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/ip_autogen/rv_plic/data/rv_plic.hjson, hw/top_darjeeling/ip_autogen/rv_plic/data/top_darjeeling_rv_plic.ipconfig.hjson, hw/top_darjeeling/ip_autogen/rv_plic/rtl/rv_plic.sv, hw/top_darjeeling/ip_autogen/rv_plic/rtl/rv_plic_reg_pkg.sv, hw/top_darjeeling/ip_autogen/rv_plic/rtl/rv_plic_reg_top.sv, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_darjeeling/sw/autogen/chip/top_darjeeling.rs, hw/top_darjeeling/sw/autogen/top_darjeeling.c, hw/top_darjeeling/sw/autogen/top_darjeeling.h, sw/device/tests/autogen/top_darjeeling/plic_all_irqs_test.c, sw/ip/mbx/dif/autogen/dif_mbx_autogen.c, sw/ip/mbx/dif/autogen/dif_mbx_autogen.h, sw/ip/mbx/dif/autogen/dif_mbx_autogen_unittest.cc, sw/ip/rv_plic/dif/dif_rv_plic_unittest.cc
This PR implements the error mechanism in case there requester tries to write out of the limit bounds of the mailbox. Compared to the HOST-generated error by Ibex, this error is generated by the mailbox hardware itself. 
* For a better readability, there is a new error state in the FSM. Whenever an error is triggered, the FSM transfers to that state. The error is cleared by the abort mechanism. The requester initiated an abort request, the FSM transfers to the abort state, and finally the HOST acknowledges the abort, such that the mailbox transfers back to idle.
* A hardware generated error triggers a new error interrupt to the host, so it can take any measures that are needed.
Closes https://github.com/lowRISC/opentitan-integrated/issues/443
=> [hw,mbx,rtl] Raise error if SOC writes out-of-bounds

hw/dv/sv/jtag_dmi_agent/jtag_dmi_reg_block.sv, hw/ip/rv_dm/data/rv_dm.hjson, hw/ip/rv_dm/rtl/rv_dm.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/vendor/patches/pulp_riscv_dbg/0001-Fix-lint-errors.patch, hw/vendor/patches/pulp_riscv_dbg/0002-Add-access-error-signal-to-dm_mem.patch, hw/vendor/patches/pulp_riscv_dbg/0003-Use-lowrisc-instead-of-PULP-primitives.patch, hw/vendor/patches/pulp_riscv_dbg/0004-Extend-DMI-address-width.patch, hw/vendor/patches/pulp_riscv_dbg/0005-dm_csrs-Implement-nextdm-register.patch, hw/vendor/pulp_riscv_dbg/src/dm_csrs.sv, hw/vendor/pulp_riscv_dbg/src/dm_top.sv
This also extends the RAL model to model this register (assuming value `0x0`), so the block-level is partially covered.
There is currently however no integration test for this at the top-level.
=> [rv_dm] Implement nextdm register

hw/ip/usbdev/dv/env/usbdev_data_integrity.sv
This request contains the usbdev_data_integrity class of usbdev predictor(reference model). In this class, we will read/write the payload and pid to specific address and endpoint.
=> [usbdev_scoreboard] Predictor (reference model) of usbdev.

hw/top_earlgrey/BUILD, rules/opentitan_test.bzl, sw/device/lib/testing/test_framework/BUILD, sw/device/silicon_creator/rom/e2e/BUILD, sw/device/silicon_creator/rom/e2e/rom_ext_upgrade_interrupt/BUILD, sw/device/silicon_creator/rom/e2e/weak_straps/gpio.bzl, sw/host/opentitantool/src/command/console.rs
Currently if you try to run tests with `bazel run`, you'll end up in a state where the execution doesn't stop and you can't use Ctrl-C to kill it.
It turns out it's due to we use `console` command in OT-tool which, when stdin is TTY, switch it to raw mode and forward stdin to FPGA uart. This is useful for debugging but not what we want for the tests.
So instead, pipe /dev/null to stdin and make `bazel run` consistent with `bazel test` for OT tests.
=> [bazel] make tests runnable with `bazel run`

azure-pipelines.yml
The tests are hitting the 1hr limit, so bump this to 1hr30min.
=> [ci] increase CW310 ROM Test timeout

hw/top_darjeeling/sw/autogen/top_darjeeling_memory.ld, hw/top_earlgrey/sw/autogen/top_earlgrey_memory.ld, sw/device/silicon_creator/rom/e2e/rom_e2e_self_hash_test.c, sw/device/silicon_creator/rom/rom.ld, util/topgen/templates/toplevel_memory.ld.tpl
Add a per-ROM chip_info section dynamically, based on the TOP hjson ROM controllers.
=> [util/topgen] Dynamic chip_info section generation

sw/device/silicon_creator/manuf/tests/BUILD, sw/device/tests/BUILD, sw/device/tests/rv_core_ibex_isa_test.S, sw/device/tests/rv_core_ibex_isa_test.c, sw/host/tests/chip/rv_core_ibex_isa/BUILD, sw/host/tests/chip/rv_core_ibex_isa/src/main.rs
Initial parts of the Ibex ISA smoke test.
Instructions that are not yet checked but will be in a future PR:
- `c.ebreak`
- `ecall`
- `mret`
- `wfi`
*`ebreak` is tested in sram_start and `dret` will never be covered see https://github.com/lowRISC/opentitan/issues/20031#issuecomment-1780850909*
Covers most of https://github.com/lowRISC/opentitan/issues/20031
=> Ibex ISA Smoke Test

hw/ip/mbx/dv/env/mbx_env_cfg.sv, hw/ip/mbx/dv/env/mbx_env_pkg.sv, hw/ip/mbx/dv/env/seq_lib/mbx_base_vseq.sv, hw/ip/mbx/dv/tb.sv
Minor fixes to support use of vcs as an alternative, for additional validation.
Smoke test passes with either vcs or xcelium.
=> [dv,mbx] Changes for vcs support

hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson, sw/device/lib/testing/json/i2c_target.h, sw/device/tests/i2c_target_test.c, sw/host/tests/chip/i2c_target/src/main.rs
Changes the existing i2c_target_test to run against all the i2c instances and links it to the sival test chip_sw_i2c_device_tx_rx.
Fix https://github.com/lowRISC/opentitan/issues/19835
=> [Sival, i2c] chip_sw_i2c_device_tx_rx

sw/device/lib/testing/BUILD, sw/device/lib/testing/uart_testutils.c, sw/device/lib/testing/uart_testutils.h, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/uart_tx_rx_test.c
This PR:
* Adds a testutil function for selecting a pinmux configuration for each UART on each platform.
* Based on the i2c testutils.
* DV maps reflect those used in `uart_tx_rx_test`.
* Hyper310 UARTs are all mapped to the console pins.
* Refactors `uart_tx_rx_test` to use the new testutil instead of direct memory changes.
Tested in dvsim, but the hyper310 configuration will require porting this to sival before it can be tested.
=> [sw] Refactor uart_tx_rx_test to use a pinmux testutil

hw/top_darjeeling/dv/chip_sim_cfg.hjson, sw/device/tests/aon_timer_wdog_bite_reset_test.c, sw/device/tests/sram_ctrl_sleep_sram_ret_contents_test.c
Fix part of #20415 
- aon_timer_wdog_bite_reset_test.
- sram_ctrl_sleep_sram_ret_contents_test : commented out due to flash dependency
=> [chip,darjeeling, aon_timer, sram_ret] wdog reset fix

hw/ip/csrng/dv/env/csrng_scoreboard.sv
No need to go via the names at runtime.
=> [csrng,dv] Simplify RAL access in csrng_scoreboard.sv

doc/security/cryptolib/cryptolib_api.md, sw/device/lib/crypto/impl/ecc.c, sw/device/lib/crypto/include/ecc.h, sw/device/silicon_creator/manuf/lib/personalize.c, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/ecdh_p256_functest.c, sw/device/tests/crypto/ecdh_p256_sideload_functest.c, sw/device/tests/crypto/ecdsa_p256_functest.c, sw/device/tests/crypto/ecdsa_p256_sideload_functest.c
This simplifies the both the internal implementation and the interface for the caller.
=> [crypto] Remove specialized ECC signature/public key structs.

sw/device/tests/BUILD
Update power_virus_systemtest to use the `fpga_cw310_sival_rom_ext` configuration.
Also update the default otp image to `sival:otp_img_prod_personalized` to replicate the sival OTP config in the `fpga_cw310_test_rom` configuration.
=> [sival] Update power_virus_systemtest.

sw/device/lib/testing/spi_device_testutils.c, sw/device/lib/testing/spi_device_testutils.h, sw/device/tests/BUILD, sw/host/opentitanlib/src/spiflash/flash.rs, sw/host/opentitantool/src/command/spi.rs
The default SPI eeprom on the CW310 board is an ISSI25WP016 and it does not support any 4-byte commands.  We do, however, want to support the explict 4-byte opcodes in the passthru implementation and they can be tested in an ad-hoc fashion by connecting a different eeprom to the CW310 board via `USR_SPI0` header `P1`.
1. Fix an error in the spi_passthru_test definition: explicitly load a bitstream so that we make sure we're testing with the expected configuration.
2. Add READ_4B and FAST_READ_4B to the spi device configuration.
3. Support explicit 4-byte opcodes in opentitanlib/tool.  I don't believe the SFDP does a good job of encoding wither or not these opcodes are supported, so they need to be enabled via a command line flag.
=> [spi_passthru] Support READ_4B and FAST_READ_4B

hw/ip/otp_ctrl/data/earlgrey_a0_skus/generic/BUILD, sw/device/lib/testing/json/provisioning_data.h, sw/device/silicon_creator/lib/otbn_boot_services.c, sw/device/silicon_creator/manuf/lib/personalize.c, sw/device/silicon_creator/manuf/lib/personalize.h, sw/device/silicon_creator/manuf/lib/personalize_functest.c, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/ft_personalize_2.c, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/ft_personalize_3.c, sw/host/provisioning/ft_lib/src/lib.rs, sw/host/tests/manuf/personalize/src/main.rs, sw/host/tests/manuf/provisioning/ft/src/main.rs
This updates the certificate personalization flow to write the attestation measurements for the desired ROM_EXT + Owner firmware transport image into the device over the ujson console. These measurements will be written to the SW binding registers prior to cranking the keymgr when generating the various attestation keys.
This partially addresses https://github.com/lowRISC/opentitan/issues/19455.
**Note: this depends on #20394, only review the last two commits.**
=> [manuf/personalize] send attestation TCB measurements to device over console

hw/ip/keymgr_dpe/dv/env/keymgr_dpe_env_pkg.sv, hw/ip/keymgr_dpe/dv/env/keymgr_dpe_if.sv, hw/ip/keymgr_dpe/dv/env/keymgr_dpe_scoreboard.sv, hw/ip/keymgr_dpe/dv/env/seq_lib/keymgr_dpe_base_vseq.sv, hw/ip/keymgr_dpe/dv/env/seq_lib/keymgr_dpe_smoke_vseq.sv, hw/ip/keymgr_dpe/dv/tb.sv
This PR contains commits that fix the scoreboard checkers and base seq checkers for:
Key slot modeling
key_policy modeling
error checking
sw/hw generation
The PR also creates the smoke test for keymgr_dpe_smoke_vseq.sv.
writes to all key-slots
test allow_child
tests retain_parent and non retain_parent
test boot_stage
test max_key_version
With this PR keymgr_dpe will have basic checking enabled and a smoke test with functioning checks.
=> Keymgr dpe dv xfer pr

hw/ip/keymgr_dpe/rtl/keymgr_dpe.sv, hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv
Fixes #20467.
When an advance operation is invalid for various
reasons other than simple key invalidity check,
KMAC msg payload should still be carrying
randomized data.
=> [keymgr_dpe, rtl] Fix invalid data on invalid advance

hw/ip/dma/rtl/dma.sv
Read BE signal was using the write channel for its enable signal
=> [hw,dma,rtl] Fix enable signal for sys_req_.read_be

sw/device/silicon_creator/lib/dbg_print.c, sw/device/silicon_creator/lib/dbg_print.h, sw/device/silicon_creator/rom_ext/doc/si_val.md, sw/device/silicon_creator/rom_ext/e2e/lockdown/BUILD, sw/device/silicon_creator/rom_ext/e2e/lockdown/epmp_rlb_lockdown.c, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/device/silicon_creator/rom_ext/rom_ext_epmp.c, sw/device/silicon_creator/rom_ext/rom_ext_epmp.h
1. Finalize the ePMP configuration for the SiVal ROM_EXT.
- Put the OTP DAI lockout in PMP entry 6.
- Lock all prior ePMP entries to prevent overrding the DAI lockout.
- Clear RLB to prevent further modification of locked ePMP entries.
2. Add a test to make sure RLB is applied.
NOTE: this PR depends on #20362.  You need only review the last commit.
=> [sival, rom_ext] Finalize the ePMP configuration 

util/check_tool_requirements.py
With funny CI environments, the locale might not be set properly, making perl complain. The version check will fail then. I believe it is sufficient to check for the tool version, stderr can be ignored safely, if I am not missing something.
=> [util] Ignore Verilator stderr in version check

hw/ip/dma/rtl/dma.sv
This is a remainder of the locking PR from before.
=> [hw,dma,rtl] Use cached opcode instead of unlocked register value

hw/dv/sv/tl_agent/seq_lib/tl_device_seq.sv
Address race condition discussed in #20417 
In earlgrey, it replies on default initialization but from 
[here](https://github.com/lowRISC/opentitan/commit/db92b366ee79fd2b2cb1fce8f2769ba3e9f24bb7)
it is added on purpose. So I move this to pre_body.
=> [rv_dm,dv] move stop=0 to pre_body

hw/ip/mbx/rtl/mbx.sv, hw/ip/mbx/rtl/mbx_fsm.sv, hw/ip/mbx/rtl/mbx_imbx.sv, hw/ip/mbx/rtl/mbx_ombx.sv, hw/ip/mbx/rtl/mbx_sramrwarb.sv
This PR implements a FW-initiated reset of the Inbound and Outbound data paths in the event of a communications failure within the SoC<->mailbox<->TL-UL chain and improves the Abort handling.
_Mailbox operation is critical to all communication between the SoC and RoT, and use of the asynchronous reset of the IP block is considered infeasible because it is common to many other IP blocks._
The logic is currently reliant upon everything completing as expected (whether successfully or by an error being indicated by the TL-UL device/bus), but is not robust against potential design flaws nor against any reliability issues with the specific physical device. Further, the current Error and Abort handling mechanisms do not have the capacity to reset fully the internal state of the mailbox logic. …
=> [mbx] Improve Abort handling, and recovery from communications failure.

hw/dv/sv/tl_agent/seq_lib/tl_device_seq.sv, hw/ip/rv_dm/dv/env/seq_lib/rv_dm_tap_fsm_vseq.sv
Discovered from darjeeling debug.
- fix rv_dm_fsm_vseq test to use constant scanmode and lc_hw_debug_en value
- Add explicit stop = 0 in case we want to reuse tl_device_sequence in the middle of the body.
=> [rv_dm,dv] fix regression failure

sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/ft_personalize_3.c, sw/host/tests/manuf/provisioning/ft/src/main.rs
This updates the FT personalization binary to set the attestation binding registers to the various FW measurement values.
This partially addresses #19455.
=> [manuf] set attestation binding registers in perso flow

sw/device/lib/crypto/impl/rsa/BUILD, sw/device/lib/crypto/impl/rsa/rsa_padding.c, sw/device/lib/crypto/impl/rsa/rsa_padding.h, sw/device/lib/crypto/impl/rsa/rsa_signature.c, sw/device/lib/crypto/impl/rsa/rsa_signature.h
This change will (a) allow on-host unit tests for padding and (b) simplify the implementation of padding for RSA encryption, since it shares some subroutines with PSS padding.
**No code was changed in this PR, only moved.** One static subroutine (`digest_check`) was added to `rsa_signature.c` to replace a subroutine that had moved to `rsa_padding.c`.
Also adds `OT_WARN_UNUSED_RESULT` macros to `rsa_signature.h`, because I noticed along the way that they were missing.
=> [crypto] Move RSA padding code to its own header.

sw/device/lib/crypto/impl/ecc.c, sw/device/lib/crypto/impl/ecc/ecdsa_p256.c, sw/device/lib/crypto/impl/keyblob.c
Add extra hardening measures where needed for P-256 C code (applies to ECDSA and ECDH). The OTBN code has already been hardened. Includes hardening for the keyblob library as well, which P-256 code depends on.
The OTBN driver itself could still use some extra hardening pass, see https://github.com/lowRISC/opentitan/issues/18333, and the `hardened_memory.h` library itself still relies on `random_order.h`, which is a stub without a properly hardened implementation. However, modulo those more library-wide issues, this should fix the P-256 code.
=> [crypto] Finish ECC top-level hardening.

hw/ip_templates/pwrmgr/data/pwrmgr_testplan.hjson, hw/ip_templates/pwrmgr/dv/env/pwrmgr_env.core, hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv, hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_vseq_list.sv, hw/ip_templates/pwrmgr/dv/pwrmgr_sim_cfg.hjson, hw/top_earlgrey/ip_autogen/pwrmgr/data/pwrmgr_testplan.hjson, hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/pwrmgr_env.core, hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv, hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_vseq_list.sv, hw/top_earlgrey/ip_autogen/pwrmgr/dv/pwrmgr_sim_cfg.hjson
Test the escalation clock timeout feature of pwrmgr. This test fails due to #20516.
Fixes #20158
=> [dv/pwrmgr] Add escalation_timeout test

sw/device/silicon_creator/rom_ext/doc/si_val.md, sw/device/silicon_creator/rom_ext/e2e/lockdown/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/device/silicon_creator/rom_ext/rom_ext_epmp.c, sw/device/silicon_creator/rom_ext/rom_ext_epmp.h
1. Use the ePMP to forbid access to the AST register space from OWNER code.
=> [rom_ext, si_val] Lock out the AST register space

hw/ip/usbdev/dv/env/usbdev_packetiser.sv
This request contains the usbdev_packetiser class of the usbdev predictor (reference model). In this class, we will collect the fields of packets from usb20_item and pack them into their respective arrays.
=> [usbdev_scoreboard] Predictor of usbdev (reference model)

hw/ip/dma/data/dma.hjson, hw/ip/dma/rtl/dma.sv, hw/ip/dma/rtl/dma_reg_pkg.sv, hw/ip/dma/rtl/dma_reg_top.sv
This breaks a dependency on next state and improves the readability. Instead of having a dedicated register, we make the `CFG_REGWEN` to a `hwext` register and use the control state of the FSM to indicate if we enable writing or not.
=> [hw,dma,rtl] Use the FSM state to lock/unlock the register set

hw/top_earlgrey/data/ip/chip_rv_plic_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/autogen/BUILD, sw/device/tests/autogen/plic_all_irqs_test.c, util/topgen/templates/BUILD.tpl, util/topgen/templates/plic_all_irqs_test.c.tpl
Fix #19862
SiVal test binaries have a size limit of 64K which the plic_all_irqs_test is exceeding quite heavily, so I break this test into three.
aon_timer test is disabled non-DV, since it's already covered by aon_timer_irq_test, and the PLIC aspect of it cannot really be tested since SiVal ROM configure the watchdog to generate NMI instead of PLIC IRQ.
=> [sival, rv_plic] port plic_all_irqs_test to SiVal

sw/ip/spi_host/dif/dif_spi_host.c, sw/ip/spi_host/dif/dif_spi_host.h, sw/ip/spi_host/dif/dif_spi_host_unittest.cc
When using the DMA in hardware handshake mode, we need to configure the SPI host first and then let the DMA read or write the FIFOs. This PR splits up the single function that configures the DMA and accesses the FIFOs into two, without changing the API of this DIF.
=> [hw,spi_host,dif] Split the configuration and FIFO read in different functions

util/reggen/fpv_csr.sv.tpl
REGWEN fields may exist in CSRs that are non-HRO, but those registers must not be modified indirectly by CSR testing, so it will be necessary to exclude those registers which may lead to the internal HW state changing and resetting the REGWEN.
(Background: The DMA block has acquired a 'CFG_REGWEN' field that the DMA controller uses to protect its registers during a transfer. This REGWEN-containing register is not 'HRO' since it is the hardware side that sets/clears the REGWEN.)
Provided that the register(s) which can lead to the lock being changed are excluded from CSR write testing (the CONTROL register in the case of DMA), it is then possible to test all of the registers controlled by such a lock rather than exclude all of them too. (In the case of DMA, almost all registers would have …
=> [dv,csr] Support non-HRO REGWEN fields

sw/device/lib/testing/json/provisioning_data.h, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/ft_personalize_3.c, sw/host/tests/manuf/provisioning/ft/src/main.rs
Before, we only generated attestation certs for a specific key ladder stage if the measurements were valid (not all 0s). Now, we always generate all certs, as the certs can be updated later during ROM_EXT execution if a boot stage has been updated. Only the UDS cert will forever remain unchanged for a given chip, as long as the HW has not been compromised.
=> [manuf] always generate all attestation certs during personalization

hw/ip/rv_dm/data/rv_dm.hjson, hw/ip/rv_dm/dv/tb.sv, hw/ip/rv_dm/rtl/rv_dm.sv, hw/ip/rv_dm/rtl/rv_dm_pkg.sv, hw/ip/rv_dm/rv_dm.core, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, hw/top_darjeeling/rtl/autogen/chip_darjeeling_asic.sv, hw/top_darjeeling/rtl/autogen/chip_darjeeling_cw310.sv, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/vendor/patches/pulp_riscv_dbg/0005-dm_csrs-Implement-nextdm-register.patch, hw/vendor/pulp_riscv_dbg/src/dm_csrs.sv, hw/vendor/pulp_riscv_dbg/src/dm_top.sv, hw/vendor/pulp_riscv_dbg/tb/tb_test_env.sv, util/topgen/templates/chiplevel.sv.tpl
Converting the `next_dm` value to a static signal so that it can be assigned using straps/tie-offs in a chiplet setting.
=> [top_darjeeling/rv_dm] Convert next_dm parameter to a static signal

ci/azure-pipelines-nightly.yml, hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson, sw/device/tests/pmod/BUILD
Add the sival exec_env to the CI nigthly BoB tests.
I broke the tests into two steps to optimize the bitstream load.
=> [ci] Add the sival exec_env to the CI nigthly BoB tests

hw/ip/otp_ctrl/data/earlgrey_a0_skus/sival/BUILD, hw/top_earlgrey/BUILD, rules/const.bzl, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/sival/BUILD, sw/device/silicon_creator/rom_ext/sival/signatures/BUILD
1. Move SiVAL ROM_EXT build rules to their own subdirectory.
2. Add rules for building and signing with reak keys.
3. Set CREATOR_SW_CFG_MANUF_STATE to `SiVL` for SiVAL OTP configurations.  Constrain the SiVAL ROM_EXT to run only on devices with that OTP configuration.
=> [rom_ext, sival] Build & Sign configuration for SiVAL ROM_EXT

sw/device/silicon_creator/lib/BUILD, sw/device/silicon_creator/lib/drivers/flash_ctrl.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.h, sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc, sw/device/silicon_creator/lib/drivers/keymgr.c, sw/device/silicon_creator/lib/drivers/keymgr.h, sw/device/silicon_creator/lib/drivers/keymgr_functest.c, sw/device/silicon_creator/lib/drivers/keymgr_unittest.cc, sw/device/silicon_creator/lib/manifest_def.c, sw/device/silicon_creator/lib/otbn_boot_services.c, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c
This adds the attestation keygen flow to the ROM_EXT to partially address #19588. This does not yet add the certificate updating portion yet. That will be done in a follow up. 
**Note: this depends on https://github.com/lowRISC/opentitan/pull/20525.**
=> [rom_ext] add attestation keygen flow

sw/ip/keymgr_dpe/dif/dif_keymgr_dpe.c, sw/ip/keymgr_dpe/dif/dif_keymgr_dpe.h, sw/ip/keymgr_dpe/driver/BUILD, sw/ip/keymgr_dpe/driver/keymgr_dpe.h, sw/ip/keymgr_dpe/test/utils/keymgr_dpe_testutils.c, sw/ip/keymgr_dpe/test/utils/keymgr_dpe_testutils.h, sw/top_darjeeling/sw/device/arch/BUILD, sw/top_darjeeling/sw/device/arch/drivers.c, sw/top_darjeeling/sw/drivers/BUILD, sw/top_darjeeling/sw/test/utils/BUILD
The first keymgr_dpe advance call is used to initialize the key manager and latch the UDS key in one of the destination slots. Software binding, max version and policy registers are not used by hardware during this operation.
This change also updates the `keymgr_dpe_testutils.c` to use the new initialization function.
=> [dif] Add `keymgr_dpe initialize` function.

sw/device/silicon_creator/manuf/lib/personalize_functest.c
The wrong number of words were being read from the attestation key seed flash info page.
=> [manuf] fix bug in personalize_functest

hw/ip/rv_dm/data/rv_dm_testplan.hjson
Title says all. Doesn't violate repo freeze guideline.
=> [rv_dm,dv] fix typo in the testplan

sw/device/tests/BUILD, sw/device/tests/keymgr_dpe_key_derivation_test.c
Based on changes from PR #20539. Adds scaffolding for key manager tests.
=> [top] Add keymgr_dpe_derivation_test

sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/provisioning_inputs.bzl, sw/host/provisioning/cp_lib/src/lib.rs
This fixes #20213 and partially addresses #20212.
=> [manuf] add Si exec_env for provisioning binaries and make harness args mandatory

azure-pipelines.yml
Tests have started exceeding 30 minutes.
=> [ci] Increase sival timeout to 45 mins

sw/host/opentitanlib/src/io/i2c.rs, sw/host/opentitanlib/src/proxy/handler.rs, sw/host/opentitanlib/src/proxy/protocol.rs, sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs, sw/host/opentitanlib/src/transport/hyperdebug/mod.rs, sw/host/opentitanlib/src/transport/hyperdebug/ti50.rs, sw/host/opentitanlib/src/transport/proxy/i2c.rs, sw/host/opentitanlib/src/util/usb.rs, sw/host/opentitantool/src/command/i2c.rs
The HyperDebug debugger is able to act as I2C device as well as I2C host.
This PR adds methods to the `i2c::Bus` trait, as well as sub-commands to opentitantool to allow putting a particular I2C port into "device mode", and then control how the debugger should behave when addressed by the I2C host (which would be the OpenTitan chip).
=> [opentitantool] Support HyperDebug as I2C device

sw/device/tests/crypto/cryptotest/firmware/BUILD, sw/device/tests/crypto/cryptotest/firmware/aes_sca.c, sw/device/tests/crypto/cryptotest/firmware/aes_sca.h, sw/device/tests/crypto/cryptotest/firmware/firmware.c, sw/device/tests/crypto/cryptotest/firmware/prng_sca.c, sw/device/tests/crypto/cryptotest/firmware/prng_sca.h, sw/device/tests/crypto/cryptotest/json/BUILD, sw/device/tests/crypto/cryptotest/json/aes_sca_commands.c, sw/device/tests/crypto/cryptotest/json/aes_sca_commands.h, sw/device/tests/crypto/cryptotest/json/commands.h, sw/device/tests/crypto/cryptotest/json/prng_sca_commands.c, sw/device/tests/crypto/cryptotest/json/prng_sca_commands.h
For the AES SCA penetration test at the silicon, we need to switch from the current simpleserial to the uJSON protocol.
This PR implements the device side command handler. To be compatible to existing tests, the previous simpleserial commands were copied and adapted to the new protocol.
For now, we want to keep the code in `sw/device/tests/crypto/cryptotest`, we might move it to the sca directory in the future.
The host code is located in the ot-sca repository ([PR#218](https://github.com/lowRISC/ot-sca/pull/218)).
=> [sca] Switch AES SCA to uJson

sw/device/tests/rv_core_ibex_icache_invalidate_test.c
The `chip_sw_rv_core_ibex_icache_scrambled_access` test can be run in both a UVM environment with `hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_core_ibex_icache_invalidate_vseq.sv` and on an fpga or in verilator.
The only check that cache invalidations were happening was in the `vseq`.
This commit adds a software check that an invalidation has happened.
Found while looking into https://github.com/lowRISC/opentitan/issues/20028
=> [test, top] ibex icache invalidation now checked in software

hw/top_earlgrey/data/ip/chip_rv_dm_testplan.hjson, sw/device/tests/BUILD, sw/host/opentitanlib/src/app/config/opentitan.json, sw/host/opentitanlib/src/io/jtag.rs, sw/host/opentitanlib/src/util/openocd.rs, sw/host/tests/chip/rv_dm/BUILD, sw/host/tests/chip/rv_dm/src/jtag.rs, sw/host/tests/chip/rv_dm/src/jtag_tap_sel.rs
=> [sival, rv_dm] add sival test for testing RV_DM JTAG

azure-pipelines.yml, hw/top_earlgrey/BUILD, rules/opentitan/defs.bzl, rules/opentitan/fpga_cw310.bzl, rules/opentitan/openocd.bzl, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD, sw/device/silicon_creator/manuf/tests/BUILD, sw/device/silicon_creator/rom/e2e/jtag_inject/BUILD, sw/device/silicon_creator/rom/e2e/rom_e2e_bootstrap_entry/BUILD, sw/device/tests/BUILD, sw/device/tests/pmod/BUILD
Test the sival tests against the hyper310 interface, which reflects the interface used with actual silicon.
Move the SPI flash qualification tests off the fpga_cw310_sival execution environment, since hyper310 does not support that interface. The Pmod board's i2c interfaces should still be supported, so leave those in the fpga_cw310_sival group. Place the SPI tests on a substitute execution environment (fpga_cw310_rom_with_fake_keys).
=> [sival] Move the FPGA sival platforms to hyper310

hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson, hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
Remove manuf_cp* tests since they that code will be run to provision the chips.
=> [sival,clkmgr,pwrmgr] Fix non-existent tests

sw/host/opentitanlib/src/dif/lc_ctrl.rs, sw/host/opentitantool/src/command/lc.rs
Use the name in snake_case from the enum. For example, to read the first hardware revision reg, supply hw_revision0 as the argument.
=> [opentitantool] Add capability to read lc_ctrl regs

hw/ip/tlul/generic_dv/xbar_tests.hjson, hw/ip/tlul/rtl/tlul_socket_1n.sv
This should fix most of the problems that currently cause multiple of [Darjeeling's `xbar_main` tests](https://reports.opentitan.org/integrated/hw/top_darjeeling/ip/xbar_main/dv/autogen/latest/report.html) to fail. Please see the commit messages for details.
=> [darjeeling,dv] Fix `xbar_main` test failures

sw/host/opentitantool/src/command/certificate.rs, sw/host/ot_certs/BUILD, sw/host/ot_certs/src/template/hjson.rs, sw/host/ot_certs/src/template/mod.rs, sw/host/ot_certs/src/x509.rs, sw/host/ot_certs/src/x509/extension.rs, sw/host/ot_certs/src/x509/tests.rs, third_party/rust/Cargo.lock, third_party/rust/Cargo.toml, third_party/rust/crates/BUILD.bazel, third_party/rust/crates/defs.bzl
This add the `certificate parse` command to parse an X509 certificate. It will fully decode the DICE TCB as well.
The result is printed by opentitantool so the output format can be any supported (hjson, json5, etc).
=> [ot_certs] Add a parsing command

sw/host/opentitanlib/src/app/mod.rs, sw/host/opentitanlib/src/proxy/handler.rs, sw/host/opentitanlib/src/proxy/mod.rs, sw/host/opentitanlib/src/proxy/protocol.rs, sw/host/opentitanlib/src/test_utils/init.rs, sw/host/opentitanlib/src/transport/mod.rs, sw/host/opentitanlib/src/transport/proxy/mod.rs, sw/host/opentitantool/src/command/transport.rs, sw/host/tests/manuf/manuf_cp_device_info_flash_wr/src/main.rs, sw/host/tests/manuf/provisioning/ft/src/main.rs
It is desirable to perform the transport initialization with an optional named gpio strap to use when initializing pins. This is especially useful if one wants to perform initialization with the target being held in reset without any glitches on the reset line.
=> [opentitantool] Add ability to "transport init" with strap

hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv
This PR addresses a couple of recent changes to the DV and RTL that introduces a chance  of `dma_abort` sequences from failing.
The Abort request placed by the parallel thread could be cancelled by the main thread initiating the transfer slightly after the abort was requested. This time window was opened by the introduction of code in the main thread to modify the interrupt enables between notification of 'transaction starting' and actually starting the transaction. Additionally, the DMA controller now clears the abort status when starting, so the test would complete normally and thus led to the abort-generating thread reporting a timeout.
The pending abort is now retained in the DV test bench, since the RAL layer does not remember that Abort had been set (SW access is Write Only, and the …
=> [dv,dma] Retain 'abort' bit when modifying the CONTROL register

sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/provisioning_inputs.bzl, sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD, sw/host/tests/manuf/provisioning/cp/BUILD, sw/host/tests/manuf/provisioning/ft/BUILD, third_party/crt/repos.bzl
This PR contains several commits that:
1. adds several FT individualization SRAM binaries per OTP SKU,
2. makes the provisioning test harnesses directly `bazel run`-able,
3. make the FT perso binaries signable with the DEV key on nitrokeys (using the integrated bazel signing flow).
=> [manuf] add data deps to provisioning harnesses

hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson, sw/device/tests/BUILD, sw/device/tests/keymgr_sideload_otbn_test.c
Covers: https://github.com/lowRISC/opentitan/issues/20120
=> [sival/otbn] Added test for `chip_sw_otbn_keymgr`.

hw/ip/dma/dv/env/dma_scoreboard.sv
Check even fixed FIFO src/dest address lies within the DMA-enabled memory range; applies to all accesses except the 'clear interrupt' write traffic.
This closes [#565](https://github.com/lowRISC/opentitan-integrated/issues/565) concerning hardware enforced security, most of which has already been addressed in #20533.
=> [dv,dma] DMA-enabled memory range checks

hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/sram_ctrl_sleep_sram_ret_contents_impl.c, sw/device/tests/sram_ctrl_sleep_sram_ret_contents_impl.h, sw/device/tests/sram_ctrl_sleep_sram_ret_contents_no_scramble_test.c, sw/device/tests/sram_ctrl_sleep_sram_ret_contents_scramble_test.c
Break this test into two, one with additional ram scramble, the other without. This is so it is not necessary to track when scrambing happens in a single test.
Fixes #20582
=> [sival,ret_sram] Fix sram_ctrl_sleep_sram_ret_contents_test

azure-pipelines.yml, sw/device/silicon_creator/manuf/lib/flash_info_fields.c, sw/device/silicon_creator/manuf/lib/flash_info_fields.h, sw/device/silicon_creator/manuf/tests/BUILD, sw/device/silicon_creator/manuf/tests/sram_load_ast_calibration_into_flash.c, sw/host/tests/manuf/manuf_sram_program_load/BUILD, sw/host/tests/manuf/manuf_sram_program_load/src/main.rs
Useful for running SRAM programs during bringup and manufacturing.
Additionally, add a test SRAM program to initialize the AST configuration flash info field.
=> [manuf] add test harness to load and run any SRAM program

hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson, sw/device/lib/testing/test_framework/check.h, sw/device/tests/BUILD, sw/device/tests/spi_device_smoketest.c, sw/host/tests/chip/spi_device_smoketest/BUILD, sw/host/tests/chip/spi_device_smoketest/src/main.rs
This PR clone the existing [DV test](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/sim_dv/spi_tx_rx_test.c;l=1?q=spi_tx_rx_test.c&sq=&ss=opentitan%2Fopentitan) and make changes to communicate with the hyperdebug board.
The tests can be equal because the hyperdebug can do full duplex transactions.
We should in the future adapt the DV implementation to unify the tests though.
Fix https://github.com/lowRISC/opentitan/issues/20438
=> [Sival,  spi dev] Smoke test

rules/signing.bzl, signing/README.md, sw/device/silicon_creator/rom/keys/real/rsa/BUILD, sw/device/silicon_creator/rom_ext/keys/real/BUILD
The `rsa_key` attributes specify a keyset and the label of a key.  It is sometimes desireable to sign with an alternate key.
1. Turn the `keyset` rule into a build setting, allowing the key to be overridden on the bazel command-line.
=> [signing] Allow using alternate keys for signing

hw/ip/dma/rtl/dma.sv
Ensure that failed 'clear interrupt' writes are reported as bus errors, as per regular source/destination accesses.
Diagnostically important from a firmware development perspective, mostly, although it could be important in
production software for recovering from any faults.
@Razer6 - there may be some merit to considering whether all bus errors should be reported identically/indistinguishably to software, or perhaps the 'clear interrupt' writes are fundamentally different from regular source/destination accesses?
(Detected in DV when revising the prediction of DUT interrupts; DV detects and responds to generated bus errors in stress tests.)
=> [dma] Report bus errors from 'clear int' writes

sw/host/opentitanlib/src/dif/lc_ctrl.rs, sw/host/opentitantool/src/command/lc.rs
While the generic transition command already works, it does not check any preconditions.
This adds more argument checking to make sure the requested transition is valid, and a token has been provided if one is required.
=> [ottool] Add more argument checks to transition command 

sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/sram_start_no_ast_init.S, sw/device/silicon_creator/manuf/tests/BUILD, sw/host/tests/manuf/manuf_sram_program_load/src/main.rs
The original sram_init.S was writing to AST regs before the flash page was initialized.
=> [manuf] add sram_init.S for AST calibration flash load

hw/dv/tools/dvsim/vcs.hjson, hw/dv/tools/dvsim/verilator.hjson, hw/dv/tools/dvsim/xcelium.hjson, util/dvsim/Deploy.py, util/dvsim/SimCfg.py
This commit changes the systemverilog seed to 32 bits. It used to be 256 bits. However, systemverilog seeds can only be 32 bits long. This caused the simulations to resort to using a default seed, which in turn caused all the test runs to have the same random values.
This PR resolves #20565
=> [dvsim] Change systemverilog seed to 32 bits

sw/device/tests/crypto/cryptotest/firmware/BUILD, sw/device/tests/crypto/cryptotest/firmware/firmware.c, sw/device/tests/crypto/cryptotest/firmware/ibex_fi.c, sw/device/tests/crypto/cryptotest/firmware/ibex_fi.h, sw/device/tests/crypto/cryptotest/json/BUILD, sw/device/tests/crypto/cryptotest/json/commands.h, sw/device/tests/crypto/cryptotest/json/ibex_fi_commands.c, sw/device/tests/crypto/cryptotest/json/ibex_fi_commands.h
This PR adds first FI command handlers for the first Ibex penetration testto the codebase.
The host code is located in the ot-sca repository
([PR#224](https://github.com/lowRISC/ot-sca/pull/224)).
@milesdai please let me know whether I can keep these fils here or where to move them.
=> [fi] Add Ibex FI command handlers

hw/top_earlgrey/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/signatures/BUILD, sw/device/silicon_creator/rom_ext/sival/BUILD
1. Update the silicon_owner_sival_rom_ext environment to use a BL0 manifest configuration.
2. Add offline signing scaffolding for sival manuf firmware.
=> [sival] Update silicon_owner exec_env manifest.

hw/dv/sv/sec_cm/prim_onehot_check_if.sv
Without this fix, tools like Xcelium warn about calls to sample_cov that don't use the (nonexistent) return value.
=> [prim,cov] Fix type of sample_cov in prim_onehot_check_if

hw/top_earlgrey/dv/chip_sim_cfg.hjson
Title says all.
Increase timeout value for `otbn_ecdsa_op_*` tests.
=> [chip,dv] increase timeout value

hw/ip/dma/dv/env/dma_env_cfg.sv, hw/ip/dma/dv/env/dma_env_pkg.sv, hw/ip/dma/dv/env/dma_scoreboard.sv, hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv, hw/ip/dma/dv/tb/tb.sv
This PR was created to fix the failing 'dma_intr_test' vseqs but during investigation it was found to be necessary to make more extensive changes to the DMA interrupt prediction within the DV environment.
The first commit makes some small changes to assist with the 'intr_test' vseq bring up, but is unable to form reliable predictions of the interrupt signals whilst the sequence is performing CSR traffic because the interrupt signals change immediately in response to the INTR_TEST write cycle starting, but the scoreboard is not notified of the register write until the end of the cycle.
Commit 2 introduces for each interrupt signal a queue of the predicted events and a maximum latency before the event must be observed.
Coupled with checking of all interrupt signals on every clock cycle, but …
=> [dv,dma] Corrections and enhancements to DMA interrupt checking.

util/dvsim/Deploy.py
#20616 causes 
self.svseed = self.seed & 0xFFFFFFFF
TypeError: unsupported operand type(s) for &: 'str' and 'int'
Add explicit cast int to self.seed
=> [dvsim] cast self.seed to 'int'

hw/ip/dma/data/dma_testplan.hjson, hw/ip/dma/dv/env/dma_env_cov.sv, hw/ip/dma/dv/env/dma_scoreboard.sv, hw/ip/dma/dv/env/dma_seq_item.sv, hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_generic_smoke_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_handshake_smoke_vseq.sv, hw/ip/dma/dv/env/seq_lib/dma_memory_smoke_vseq.sv
This PR reworks the DMA's block-level functional coverage plan and completes its implementation with covergroups, thereby resolving https://github.com/lowRISC/opentitan-integrated/issues/137.
I suggest reviewing this PR commit-by-commit.
- The first 9 commits change the previous coverplan and its implementation to make fixes that I think are fairly uncontroversial.
- The 10th (second-to-last) commit reworks the coverplan to bring it up-to-date with the current specification and to cover more of the implementation.
- The 11th (last) commit changes the covergroups to match the reworked coverplan.
The pass rate of tests does not change (i.e., the `dma_abort` test has ca. 80% pass rate, the `dma_intr_test` has ca. 0% pass rate, and the other tests have 100% pass rate).
Coverage results are as …
=> [darjeeling,dma/dv] Rework coverplan and complete its implementation

hw/ip/aes/pre_syn/tcl/yosys_run_synth.tcl, hw/ip/kmac/pre_syn/syn_yosys.sh, hw/ip/kmac/pre_syn/tcl/yosys_run_synth.tcl, hw/ip/otbn/pre_syn/tcl/yosys_run_synth.tcl
This PR contains a couple of relevant fixes to re-enable the Yosys synthesis flow for KMAC and to make the produced netlist more suitable for analysis SCA countermeasures using the [PROLEAD](https://github.com/ChairImpSec/PROLEAD) tool.
This is contributes to the overall penetration testing effort.
=> [aes, kmac, otbn] Fixes for pre_syn Yosys synthesis flows

hw/dv/tools/dvsim/sim.mk
There are many outdated rom e2e tests using `rom_with_real_key` testpoints.
Update make file to be in sync.
=> [chip,dv] update makefile for real_key rom test

hw/ip/otp_ctrl/data/BUILD, hw/ip/otp_ctrl/data/earlgrey_a0_skus/sival_bringup/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD, sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize_3.c, sw/host/tests/manuf/provisioning/cp/src/main.rs
This contains several cleanup to the provisioning firmware to:
1. optimize stack utilization during FT personalization stage 3, and
2. remove the raw unlock operation from the CP stage
=> [manuf] cleanup CP and FT provisioning stages

rules/opentitan/openocd.bzl, rules/opentitan_test.bzl, sw/device/tests/BUILD, sw/host/opentitanlib/src/app/mod.rs, sw/host/opentitanlib/src/backend/chip_whisperer.rs, sw/host/opentitanlib/src/backend/mod.rs, sw/host/opentitanlib/src/transport/chip_whisperer/mod.rs, sw/host/opentitanlib/src/transport/hyperdebug/mod.rs, sw/host/opentitanlib/src/transport/mod.rs
Move handling of the `--openocd_adapter_config=...` argument up from transport driver into `TransportWrapper`, allowing e.g. an Olimex JTAG dongle to be used with any one of the existing transports (including HyperDebug).
=> [opentitantool] Support external JTAG dongles with HyperDebug

sw/device/silicon_creator/manuf/lib/ast_program.c, sw/device/silicon_creator/manuf/tests/sram_load_ast_calibration_into_flash.c
AST calibration values are programmed into, and read out of flash INFO page 0 during provisioning flows. Not waiting for the flash_ctrl to initialize before performing operations can cause reliability issues.
=> [manuf] ensure flash_ctrl is initialized before reading AST values

sw/device/silicon_creator/lib/boot_log.c, sw/device/silicon_creator/lib/boot_log.h, sw/device/silicon_creator/rom_ext/rom_ext.c
The ROM_EXT assumes that the ROM will initialize the boot_log in retention RAM, however, the ROM in the earlgrey_es was cut before the introduction of the boot_log data structure.
1. Detect an uninitialized boot_log in the ROM_EXT and initialize it.
=> [rom_ext] Initialize the boot log in the ROM_EXT

hw/ip/otbn/README.md, hw/ip/otbn/util/docs/md_isrs.py
Blank lines inside HTML tags generate `<pre><code>...</code></pre>` blocks in Markdown. In  the source of the tables in https://opentitan.org/book/hw/ip/otbn/index.html, you can see that many table tags have been escaped
```
<td>
An AIS31-compliant class PTG.3 random number with guaranteed entropy and forward and backward secrecy.
Primarily intended to be used for key generation.
<pre><code>    The number is sourced from the EDN via a single-entry cache.
Reads when the cache is empty will cause OTBN to be stalled until a new random number is fetched from the EDN.
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;0xFC1&lt;/td&gt;
&lt;td&gt;RO&lt;/td&gt;
&lt;td&gt;URND&lt;/td&gt;
&lt;td&gt;
A random number without guaranteed secrecy properties or specific statistical properties.
```
=> [doc] Fix CSR and WSR tables in OTBN README

hw/ip/dma/dv/env/dma_seq_item.sv, hw/ip/dma/rtl/dma.sv
The source and destination addresses of a transfer may have different alignment within the bus word because read steering was necessary to achieve function for 1B/txn and 2B/txn transfers to a FIFO without automatic address incrementing. This change was implemented in [PR #680](https://github.com/lowRISC/opentitan-integrated/pull/680).
The current PR removes the needless check within the DMA and the corresponding constraints within the DV to permit 1-byte and 2-byte transfers to be employed with arbitrary source and destination alignments. Whilst the intended behavior in this case was never explicitly specified, it may be useful to have this functionality available as a contingency, since it is already present and exercised in DV, with the constraints no longer present/required.
Summary: …
=> [dma] Src and dst alignment may differ
