lowRISC/opentitan

- hw/top_earlgrey/BUILD
- rules/opentitan/defs.bzl
- rules/opentitan/sim_verilator.bzl
- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/lib/sigverify/sphincsplus/test/BUILD
This PR depends on #19650.  You need only review the last commit.
> [bazel] Convert most of silicon_creator to the new rules 

- hw/top_earlgrey/ip/ast/lint/ast.waiver
- hw/top_earlgrey/lint/chip_earlgrey_asic.waiver
This fixes the AscentLint escapes from #19535.
> [ast/lint] Fix lint escapes

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/autogen/BUILD
- util/topgen/templates/BUILD.tpl
> [bazel] Migrate tests/autogen to opentitan_test

- sw/device/sca/BUILD
> [bazel] migrate device/sca to opentitan_binary

- sw/device/sca/otbn_vertical/BUILD
> [bazel] Migrate otbn_vertical to opentitan_binary

- doc/contributing/style_guides/markdown_usage_style.md
- hw/ip/pinmux/doc/programmers_guide.md
The two simple commits here fix a couple of pages.
> [doc,typos] Fix a couple of minor issues

- rules/opentitan/fpga_cw310.bzl
- rules/opentitan/sim_dv.bzl
- rules/opentitan/sim_verilator.bzl
- sw/device/lib/testing/test_framework/BUILD
> [bazel] Migrate test_framework to opentitan_test

- sw/otbn/code-snippets/BUILD
- sw/otbn/code-snippets/README.md
- sw/otbn/code-snippets/calc_montgomery_consts.s
Signed-off-by: Juergen Pulkus <Juergen.Pulkus@gmail.com>
> [otbn,sw] Added code snippet for otbn

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/chip_smoketests.hjson
- rules/opentitan/sim_dv.bzl
- sw/device/tests/sim_dv/BUILD
> [bazel] Migrate tests/sim_dv to opentitan_test

- sw/device/lib/testing/test_framework/README.md
This commit contains an update for the code snippet, where a first test setup is shown. This snippet used to reference two libraries that have been renamed or moved to another folder. This commit updates the snippet to now reference the updated paths to the libraries.
> [doc] Update libraries for on-device test setup

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_idle_hint_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test verify that debugger does not need to stay any longer than advertized time indicated in dtmcs register.
@jdonjdon
> [RV_DM]jtag_dtm_idle_hint

- rules/opentitan/defs.bzl
- rules/opentitan/sim_verilator.bzl
- sw/device/silicon_creator/rom/e2e/weak_straps/BUILD
- sw/device/silicon_creator/rom/e2e/weak_straps/gpio.bzl
> [bazel] Migrate weak_straps to opentitan_test

- hw/ip/aon_timer/data/aon_timer.hjson
- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aon_timer_testplan.hjson
Silicon validation for aon_timer block.
> Sival aon timer testplan

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_dm_inactive_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test verify that writing to dm registers other than dmcontrol(exclude it), then read those registers back and it  should give zeros on read.
@jdonjdon  please review it . Thanks
> [RV_DM]jtag_dmi_dm_inactive

- rules/opentitan/defs.bzl
- rules/opentitan/keyutils.bzl
- rules/signing.bzl
- sw/device/silicon_creator/manuf/tests/BUILD
Convert `manuf/tests` to the new rules.
> Bazel convert manuf test

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/chip_smoketests.hjson
- hw/top_englishbreakfast/util/prepare_sw.py
- sw/device/tests/BUILD
> [bazel] Migrate device/tests to open_test

- hw/dv/tools/dvsim/sim.mk
- rules/opentitan/cc.bzl
- rules/opentitan/sim_dv.bzl
- rules/opentitan/sim_verilator.bzl
- sw/device/examples/sram_program/BUILD
- sw/device/silicon_creator/manuf/tests/BUILD
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/tests/BUILD
- sw/device/tests/sram_ctrl_execution_test.c
> [bazel] Migrate examples/sram_program to new build rules

- util/design/gen-otp-img.py
- util/design/lib/LcStEnc.py
- util/design/lib/OtpMemImg.py
- util/design/lib/OtpMemMap.py
- util/design/lib/common.py
- util/dvsim/Deploy.py
- util/dvsim/dvsim.py
- util/topgen.py
- util/topgen/secure_prng.py
> [util] Error out if secure_prng seed is less than 256 bits

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
> [bazel] Migrate device tests to opentitan_test.

- hw/top_earlgrey/dv/chip_rom_tests.hjson
> [dvsim] Migrate keymgr test to opentitan_test.

- sw/device/tests/pmod/BUILD
> [bazel] Migrate pmod tests to opentitan_test.

- sw/device/silicon_creator/rom/e2e/watchdog/BUILD
> [bazel] Migrate e2e watchdog to new test rules.

- sw/device/silicon_creator/rom/e2e/epmp_init/BUILD
> [bazel] Migrate e2e epmp_init to new build/test rules.

- hw/ip/otbn/dv/otbnsim/sim/ext_regs.py
This shouldn't make any difference to behaviour, but it means that the "dirty" flag no longer gets set every instruction. That avoids hunting through some ext_regs and committing them unnecessarily.
A silly test example that I put together for profiling gets about 25% faster, so this should avoid a bit of wasted energy in CI, if nothing else.
> [otbn,dv] Make "dirty" flag more selective in otbnsim ext_regs.py

- sw/device/silicon_creator/rom/e2e/boot_data_recovery/BUILD
> [bazel] Migrate boot_data_recovery to new build/test rules.

- sw/device/silicon_creator/rom/e2e/rom_ext_upgrade_interrupt/BUILD
> [bazel] Migrate e2e rom_ext_upgrade_int to new build/test rules.

- sw/device/silicon_creator/rom/e2e/retention_ram/BUILD
- sw/device/silicon_creator/rom/e2e/rom_e2e_bootstrap_entry/BUILD
- sw/device/silicon_creator/rom/e2e/shutdown_redact/BUILD
* Fixes https://github.com/lowRISC/opentitan/issues/20099.
* Fixes https://github.com/lowRISC/opentitan/issues/20093.
* Fixes https://github.com/lowRISC/opentitan/issues/20089.
> [bazel] Migrate various ROM e2e test cases to new test rules.

- util/ipgen.py
- util/ipgen/__init__.py
- util/ipgen/lib.py
- util/ipgen/renderer.py
Add some try..except code around some file io.
Clean python formatting.
Use more f-strings for readability.
> [util,ipgen] Add some error handling and clean up

- sw/device/tests/BUILD
Add fpga cw310 test for #20084
> [sival,flash_ctrl] Add bazel target for flash_ctrl info access test

- hw/ip/otbn/data/otbn.hjson
- hw/ip/rv_core_ibex/data/rv_core_ibex.hjson
- hw/ip/rv_dm/data/rv_dm.hjson
- hw/ip_templates/alert_handler/data/alert_handler.hjson.tpl
- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.hjson
This PR make some changes to the sival testplan in order to make them consistent
> [Siva, testplans] fixes for consistency

- sw/device/tests/BUILD
- sw/device/tests/flash_ctrl_info_access_lc.c
- Add flash info access with test rom device personalized 
- Add rma lc state info access test with rom_fake_keys
> [sival,flash_ctrl] Add info access test for personalized device

- sw/device/tests/BUILD
- sw/device/tests/flash_ctrl_idle_low_power_test.c
Increase bite threshold for verilator target
> [sival] fix flash_ctrl_idle_low_power_test

- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/lib/testing/clkmgr_testutils.c
- sw/device/tests/BUILD
- sw/device/tests/clkmgr_jitter_frequency_test.c
> [sival,clkmgr] Add test for chip_sw_clkmgr_jitter_cycle_measurements testpoint

- sw/otbn/crypto/p256_verify.s
Fixes https://github.com/lowRISC/opentitan/issues/20299
> [crypto] Remove a redundant load.

- sw/host/opentitantool/src/command/lc.rs
This adds two `life-cycle` subcommands to opentitantool to read the transition count and status CSRs. These commands can be run on the hyper310 platform with:
```
bazel run //sw/host/opentitantool -- --interface=hyper310 life-cycle transition-count --openocd=$(pwd)/bazel-bin/third_party/openocd/build_openocd/bin/openocd
bazel run //sw/host/opentitantool -- --interface=hyper310 life-cycle status --openocd=$(pwd)/bazel-bin/third_party/openocd/build_openocd/bin/openocd
```
> [opentitantool] add more LC commands to read transition count and status CSRs

- hw/top_earlgrey/data/ip/chip_adc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_csrng_testplan.hjson
- hw/top_earlgrey/data/ip/chip_edn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson
- hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson
- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_dm_testplan.hjson
- hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
This PR updates the Sival stages according to the prioritization made by @moidx on the [sheet](https://docs.google.com/spreadsheets/d/1Uw3iNPvXfG-dN-RRnH11qSQOnwNdGl_4TCFIW1atZwA/edit#gid=2045762255).
> [sival] Update testplan 

- hw/README.md
Remove `results` since the sections contain more than just that.
> [doc] Minor tweaks

- hw/top_earlgrey/data/ip/chip_edn_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- sw/device/tests/BUILD
- sw/device/tests/edn_kat.c
This PR adds the EDN KAT. For more detailed information have a look at the individual commit messages.
This PR resolves  #20053
> [chip-level/sival] Add EDN KAT 

- sw/device/tests/rstmgr_cpu_info_test.c
> [chip,rstmgr] fix chip_sw_rstmgr_cpu_info failure

- hw/ip/rv_dm/data/rv_dm.hjson
- hw/ip/rv_dm/doc/registers.md
Document how the CSRs are expected to behave and how the hart and its debug ROM are expected to interact with the debug module.
> [rv_dm/doc] Add some missing CSR documentation

- hw/ip/otp_ctrl/data/earlgrey_a0_skus/sival/BUILD
- sw/device/silicon_creator/manuf/README.md
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/generic/BUILD
- sw/device/tests/doc/sival/devguide.md
1. Document manufacturing stages, including
a. Mapping of manufacturing to life cycle stages
b. Mapping of manufacturing stages to configuring of OTP partitions
2. Update SiVal SKU OTP image targets to use consistent manufacturing state prefixes.
> [sival] Document manufacturing stages

- hw/ip/otbn/util/shared/constants.py
- hw/ip/otbn/util/shared/control_flow.py
- hw/ip/otbn/util/shared/information_flow_analysis.py
- hw/ip/otbn/util/shared/insn_yaml.py
No functional change. Most of this is re-wrapping comments.
> [otbn,python] Tweak code to avoid some flake8 errors

- hw/dv/sv/usb20_agent/usb20_agent.core
- hw/dv/sv/usb20_agent/usb20_agent.sv
- hw/dv/sv/usb20_agent/usb20_agent_cfg.sv
- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/dv/sv/usb20_agent/usb20_block_if.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/ip/usbdev/dv/tb/Clock_Divider.sv
- hw/ip/usbdev/dv/tb/tb.sv
- hw/ip/usbdev/dv/usbdev_sim.core
Add usb20 block level interface.
Modify usb tb.sv to hook up dut using usb20_block_interface. 
Add clock divider module to drive K/J symbols for multiple clock cycles. 
Add usb20 driver to drive token packet.
Add usb20 block interface in usb20_agent.
@jdonjdon  kindly review this. I did this PR again after rebase. Thank
> [usbdev] Add usb20 block level DV Environment

- hw/dv/sv/usb20_agent/usb20_monitor.sv
@jdonjdon usb20_monitor class. Kindly review it.
> [Usbdev] Usb20_Monitor

- sw/device/lib/crypto/impl/aes_gcm/aes_gcm.c
- sw/device/lib/crypto/impl/aes_gcm/aes_gcm.h
Adds a streaming-data mode to AES-GCM, just in the core implementation for now.
Later I'll add API functions for the streaming operations, but this at least changes the core implementation to have a streaming interface.
Part of https://github.com/lowRISC/opentitan/issues/19549, some discussion on that issue
> [crypto] Add streaming mode to the core AES-GCM implementation.

- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/doc/registers.md
This PR makes some small documentation corrections for the CSRNG genbits register.
> [csrng/doc] Correct some minor documentation errors

- hw/dv/sv/usb20_agent/usb20_driver.sv
Add task in usb20_driver class to drive data packet.
@jdonjdon  please review it. Thanks
> [usbdev] usb20_driver

- hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv
Fixes https://github.com/lowRISC/opentitan-integrated/issues/688
In comparison to https://github.com/lowRISC/opentitan-integrated/pull/698, this PR handles two changes:
- If the operation is erase or disabled, do not let ctrl take over the key interface on sideload ctrl side.
- Randomize key output from keymgr_dpe_ctrl more strictly, in the sense that invalid operations present randomized keys.
> [keymgr_dpe, rtl] Fix key switching during erase

- sw/device/silicon_creator/rom/e2e/boot_policy_newer/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_rollback/BUILD
> [bazel] Convert boot_policy_{newer, rollback} to the new rules

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/dv/autogen/xbar_env_pkg__params.sv
- hw/top_darjeeling/dv/autogen/xbar_tgl_excl.cfg
- hw/top_darjeeling/ip/xbar_dbg/data/autogen/xbar_dbg.gen.hjson
- hw/top_darjeeling/ip/xbar_dbg/dv/autogen/xbar_cover.cfg
- hw/top_darjeeling/ip/xbar_dbg/dv/autogen/xbar_env_pkg__params.sv
- hw/top_darjeeling/ip/xbar_dbg/rtl/autogen/tl_dbg_pkg.sv
As discussed with @kwalker27, moving it another time.
> [top_darjeeling] Move JTAG mailbox to 0x1000

- sw/device/tests/pwrmgr_wdog_reset_reqs_test.c
- sw/device/tests/sim_dv/pwrmgr_random_sleep_power_glitch_reset_test.c
> [chip,darjeeling,pwrmgr] pwrmgr wdog reset fix

- hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_lowpower_counter_vseq.sv
This sequence works by setting up some state that works by enabling/disabling an assertion. That's sensible enough, but the assertion that was enabled becomes false if the block gets reset and a new sequence is started. Tweak the vseq so that it also clears the assertion on reset.
This fixes some failures that we're seeing in the `adc_ctrl_stress_all_with_rand_reset` test.
> [adc_ctrl,dv] Fix adc_ctrl_lowpower_counter_vseq if used with resets

- hw/ip/csrng/dv/env/csrng_scoreboard.sv
This PR adds a check for when genbits are read via the genbits register. Now we check whether the genbits_vld flag is high before tracing the genbits. This helps us to avoid tracing genbits that are not valid.
> [csrng/dv] Check whether sw genbits are valid before tracing them

- hw/ip/usbdev/dv/env/usbdev_pkt_manager.sv
This request contains the usbdev_pkt_manager class of usbdev predictor(reference model). In this class, we will collect the fields of different packets,pack them and send them into expected queue.
> [usbdev_scoreboard] Predictor of usbdev (reference model).

- hw/dv/sv/usb20_agent/usb20_item.sv
Changed the sequence of token packet fields as per standard.
@jdonjdon please review this change.
> [usbdev] usb20_item

- hw/ip/usbdev/data/usbdev_testplan.hjson
This is a comprehensive test plan of usbdev.
> [usbdev] pull request for usbdev testplan.

- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
Add a few additional tests for some testpoints.
> [sival,clkmgr,rstmgr] Add bazel tests in testplans

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_common_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_sba_tl_access_vseq_lib.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_stress_all_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
Add stress_all test
Address some random reset failures
> [rv_dm,dv] rv_dm regression cleanup

- doc/contributing/bazel_notes.md
- doc/getting_started/setup_fpga.md
Document bazel linting rules plus some consistency fixes.
> [Doc] Document bazel linting rules

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/asn1.c
- sw/device/silicon_creator/lib/cert/asn1.h
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/error_unittest_util.h
This library is quite low-level and will be used to build X509 certificates for attestation.
> [silicon_creator] Add library to generate ASN1 documents.

- hw/ip/mbx/data/mbx_testplan.hjson
This ensures that all existing tests are mapped to a testpoint.
> [darjeeling,mbx/dv] Create scaffold for testplan

- sw/device/silicon_creator/lib/cert/cdi_0.hjson
- sw/device/silicon_creator/lib/cert/cdi_1.hjson
- sw/device/silicon_creator/lib/cert/example.hjson
- sw/device/silicon_creator/lib/cert/generic.hjson
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/types.rs
Two small changes:
- remove the little endian conversion (see commit for explanation)
- add two more templates for testing
> [ot_certs] Misc

- hw/top_earlgrey/dv/chip_smoketests.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_inject_scramble_seed_vseq.sv
- update img name
- Add newrule
> [chip,dv] earlgrey regression fix

- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/rv_core_ibex_mem_test.c
Covers: https://github.com/lowRISC/opentitan/issues/20033
> [sival/ibex] Ibex Memory Smoke Test

- rules/opentitan/sim_dv.bzl
When dvsim and bazel use different otp image which has different scramble option,
there is a corner case where dvsim can't find vmem file.
Send scr.vmem and vmem to mitigate the issue
> [bzl] sim_dv regression fix

- doc/getting_started/build_sw.md
> [doc] Align bazel version in the docs

- sw/device/silicon_creator/lib/cert/example.hjson
- sw/host/opentitantool/src/command/certificate.rs
- sw/host/ot_certs/BUILD
- sw/host/ot_certs/src/asn1/mod.rs
- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/x509.rs
- sw/host/ot_certs/src/x509/extension.rs
See the commits for description. First 3 commits are from #20596  You can test it using:
```bash
./bazelisk.sh run //sw/host/opentitantool -- certificate generate $PWD/sw/device/silicon_creator/lib/cert/example.hjson $PWD/example.pem
openssl asn1parse -inform DER -in $PWD/example.pem
openssl x509 -in $PWD/example.pem -noout -text
```
> [ot_certs] Add ASN1 X509 generator

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
- sw/device/tests/crypto/cryptotest/firmware/kmac_sca.h
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/kmac_sca_commands.c
- sw/device/tests/crypto/cryptotest/json/kmac_sca_commands.h
This PR translates the existig simpleserial KMAC SCA tests to the uJSON communication framework.
> [sca] KMAC uJSON handler

- sw/host/provisioning/orchestrator/orchestrator.py
- Require database download before running orchestrator.py
> [provisioning] Device Registry patches

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
- sw/device/tests/crypto/cryptotest/firmware/sha3_sca.h
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/sha3_sca_commands.c
- sw/device/tests/crypto/cryptotest/json/sha3_sca_commands.h
This PR translates the existing simpleserial SHA3 SCA tests to the uJSON communication framework.
> [sca] SHA3 uJSON handler

- hw/ip/usbdev/dv/env/usbdev_TransactionManager.sv
- hw/ip/usbdev/dv/env/usbdev_packet_classifier.sv
This request contains the usbdev_TransactionManager class of the usbdev predictor (reference model).In this class the whole flow for the usb predictor is done. It also consist of a modified packet classifier class in which the pid identifier values are changed according to the new usb20_item.
> [usbdev] Predictor of usbdev

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
Update test description as suggested in #15670
cc:@BasitMehmood
> [rv_dm,dv] update test description for jtag_dtm_hard_reset

- util/fpvgen.py
The bugfix is in the first commit, but I think the second commit also makes things a bit easier to follow.
> [util] Fix minor nits in fpvgen Python script

- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
This is an incremental PR add new changes in Driver and Seq_item Class Add drive data packet task in driver class
Add get response from Device task in driver class
Add crc generate task in usb20_item
Add Generate specific payload for control requestes task in usb20_item class
@jdonjdon  please review this
> [Usbdev] usbdev_env

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_hard_reset_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test verify that after perfominmg the operation of hard reset the debug module still responds correctly.
> [RV_DM] rv_dm_jtag_dtm_hard_reset_vseq

- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/hkdf_functest.c
Runs the 3 SHA256 tests from the HKDF RFC.
> [crypto] Add a basic test for HKDF.

- hw/dv/sv/usb20_agent/usb20_agent_cfg.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
This is updated monitor.
@jdonjdon kindly review it. Thanks
> [usbdev]usb20_monitor

- hw/ip_templates/pwrmgr/dv/env/pwrmgr_scoreboard.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/pwrmgr_scoreboard.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv
The number of cycles esc_clk need to stop to trigger a timeout is unpredictable:
- The timeout counter can start at any number from 0 to 7.
- The reqack synchronizer adds some variable number of cycles due to its phase.
Avoid spurious failures by reducing the number of cycles of stoppage when not expecting alerts, and wait reduce the number of cycles to trigger an expected alert.
Also, avoid running the case that fails due to issue #20516.
> [dv,pwrmgr] Fix pwrmgr_escalation_timeout test

- sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest/BUILD
- sw/device/silicon_creator/rom/e2e/empty_test.c
> [bazel] Convert boot_policy_bad_manifest to the new rules

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/asn1.h
- sw/device/silicon_creator/lib/cert/asn1_unittest.cc
- sw/host/ot_certs/src/asn1/der.rs
Add a unitest for the asn1 library.
> [ot_certs] asn1 library unittest

- doc/security/cryptolib/cryptolib_api.md
- sw/device/lib/crypto/impl/aes.c
- sw/device/lib/crypto/impl/aes_gcm/aes_gcm.c
- sw/device/lib/crypto/impl/aes_gcm/aes_gcm.h
- sw/device/lib/crypto/impl/keyblob.c
- sw/device/lib/crypto/impl/keyblob.h
- sw/device/lib/crypto/include/aes.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/aes_gcm_functest.c
- sw/device/tests/crypto/aes_gcm_testutils.c
- sw/device/tests/crypto/aes_gcm_testutils.h
- sw/device/tests/crypto/aes_gcm_timing_test.c
Follow-up to https://github.com/lowRISC/opentitan/pull/20359
See some discussion on the issue above about this change. This was decided a long time ago but I've only now finished pushing through the last changes.
> [crypto] Add streaming mode to the top-level AES-GCM API.

- doc/project_governance/technical_committee.md
Remove no-longer active contributors.
> Update technical committee list.

- sw/device/lib/dif/dif_sensor_ctrl.c
- sw/device/lib/dif/dif_sensor_ctrl.h
- sw/device/lib/dif/dif_sensor_ctrl_unittest.cc
Also fix minor doxygen comment issues.
> [sw,dif_sensor_ctrl] Add support to read alert triggers

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/ecdsa_sig_ver_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/nist_cavp_ecdsa_parser.py
- sw/host/cryptotest/testvectors/parsers/wycheproof_ecdsa_parser.py
This PR adds a parser for the Wycheproof ECDSA test vectors.
CC @RyanTorok
> [cryptotest] Add Wycheproof ECDSA test vectors

- sw/device/silicon_creator/lib/cert/asn1.c
- sw/device/silicon_creator/lib/cert/asn1.h
- sw/device/silicon_creator/lib/cert/asn1_unittest.cc
- sw/device/silicon_creator/lib/cert/generic.hjson
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/host/ot_certs/src/asn1/builder.rs
- sw/host/ot_certs/src/asn1/codegen.rs
- sw/host/ot_certs/src/asn1/der.rs
- sw/host/ot_certs/src/asn1/dice_tcb.rs
- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/codegen.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/src/template/testgen.rs
- sw/host/ot_certs/src/x509/extension.rs
Add support for boolean variables in the template. This is useful for DICE flags that can be set dynamically (such as the debug flag).
> Ot certs booleans

- hw/ip/prim/rtl/prim_sha2.sv
- hw/ip/prim/rtl/prim_sha2_32.sv
- hw/ip/prim/rtl/prim_sha2_pad.sv
This PR makes minor styling fixes and RTL changes to fix 2 AscentLint warnings for HMAC and avoid rules to waive them.
> [prim_sha2,rtl] prim_sha2 minor RTL styling and linting fixes

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_resuming_vseq.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test was failing in regression list so i PR it again.
> Rv dm resuming

- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_stress_all_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
Combine sequences in one test and run as many of them as possible in parallel.
> [RV_DM]rv_dm_stress_all_vseq

- hw/ip/otp_ctrl/data/otp_ctrl_env_pkg.sv.tpl
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_common_vseq.sv
- hw/ip/otp_ctrl/dv/tb.sv
Minor alignments to fix things that were missed during the batch carry-over from integrated_dev.
> [otp_ctrl] Minor alignments

- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/dv/env/usbdev_TransactionManager.sv
- hw/ip/usbdev/dv/env/usbdev_env.sv
- hw/ip/usbdev/dv/env/usbdev_env_pkg.sv
- hw/ip/usbdev/dv/env/usbdev_packetiser.sv
- hw/ip/usbdev/dv/env/usbdev_pkt_manager.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
The Purpose of this PR is to sync the scoreboard with usbdev env so slight changes are done in some classes based on requirement.
> [usbdev] usbdev scoreboard PR

- hw/ip/keymgr_dpe/dv/env/keymgr_dpe_scoreboard.sv
- hw/ip/keymgr_dpe/dv/env/seq_lib/keymgr_dpe_base_vseq.sv
- hw/ip/keymgr_dpe/dv/env/seq_lib/keymgr_dpe_smoke_vseq.sv
This PR adds erase and disable support in the keymgr_dpe dv
> [keymgr_dpe/dv] Verify erase and disable

- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/nist_cavp_hmac_parser.py
This PR adds the test vector parser for the NIST HMAC vectors (https://csrc.nist.gov/Projects/cryptographic-algorithm-validation-program/Message-Authentication#Testing)
> [cryptotest] NIST HMAC test vector parser

- hw/ip_templates/pwrmgr/doc/theory_of_operation.md
- hw/ip_templates/pwrmgr/rtl/pwrmgr_fsm.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/doc/theory_of_operation.md
- hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_fsm.sv
Also fix a typo in fast fsm RTL.
Fixes #20858
> [doc,pwrmgr] Document wakeup signal requirements

- hw/ip/clkmgr/data/clkmgr.sv.tpl
- hw/ip/clkmgr/dv/sva/clkmgr_bind.sv
- hw/ip/prim/rtl/prim_clock_div.sv
- hw/top_darjeeling/ip/clkmgr/rtl/autogen/clkmgr.sv
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
This carries over the changes from `master` in #21100.
> [clkmgr] Minor restructuring to facilitate OCC hookup during DFT insertion

- hw/ip/rv_core_ibex/doc/boot-rom-patching.md
Pending comments from https://github.com/lowRISC/opentitan/pull/21070
> [hw,ibex,doc] Follow-up fixes to the ROM patching spec

- hw/ip/rv_dm/dv/env/rv_dm_if.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_halt_resume_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_hart_unavail_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv
This doesn't really do very much: it just synchronises the seven interface signals with clk.
> [rv_dm,dv] Add a trivial clocking block to rv_dm_if

- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_received_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
THis PR contains sequences of usbdev
> [usbdev] usbdev sequence PR

- hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_otp_reset_vseq.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_base_vseq.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
Fix lint reported by verible.
Fix warnings reported by VCS.
> [lint,flash_ctrl] Fix some warnings and lint

- hw/ip/prim/lint/prim_clock_div.waiver
Related to https://github.com/lowRISC/opentitan/pull/21117, which renamed a few signals.
> [prim_clock_div,lint] Update waiver to cover renamed signals

- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/sival/BUILD
- sw/device/tests/spi_host_irq_test.c
Fix https://github.com/lowRISC/opentitan/issues/19845
> [sival, spi_host] Add test chip_sw_spi_host_events to sival

- hw/ip/usbdev/dv/env/seq_lib/usbdev_av_buffer_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR contains usbdev_av_buffer seq
> [dv,usbdev] usbdev seq PR

- sw/device/tests/BUILD
- sw/device/tests/power_virus_systemtest.c
Instrument the test tasks to be able to run multiple iterations.
> [sival] Add test iterations to power virus test.

- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_setup_trans_ignored_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR adds sequence usbdev_setup_trans-ignored.
> [usbdev] usbdev_setup_transaction sequence

- hw/ip/usbdev/dv/env/usbdev_data_integrity.sv
This PR contains updated usbdev predictor's class (usbdev_data_integrity) with little ammendments.
> [usbdev] usbdev Predictor PR

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv
Added big delay to phy_arb_redun test for some rare cases in which it needed.
> [flash_ctrl/dv] Added big delay to phy_arb_redun test

- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
Adds updates in DV environment to supports Isochronous transaction and also can send SoF packets to device.
> [usbdev] usbdev DV Environment

- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_sent_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR contains usbdev_pkt_sent seq
> [dv,usbdev] usbdev sequence PR

- sw/device/lib/base/macros.h
- sw/device/tests/aon_timer_irq_test.c
- sw/device/tests/otbn_ecdsa_op_irq_test.c
- sw/device/tests/otbn_irq_test.c
- sw/device/tests/otbn_randomness_test.c
- sw/device/tests/pmod/i2c_host_clock_stretching_test.c
- sw/device/tests/pmod/i2c_host_irq_test.c
- sw/device/tests/spi_device_tpm_tx_rx_test.c
- sw/device/tests/spi_host_irq_test.c
- sw/device/tests/sysrst_ctrl_in_irq_test.c
This is a cherry-pick of https://github.com/lowRISC/opentitan/pull/21259 to branch master.
> Backport 21259 to master

- doc/security/specs/device_life_cycle/README.md
- hw/ip/lc_ctrl/doc/theory_of_operation.md
Addresses the doc side of #19679 and #19550
>  [lc_ctrl/doc] Minor doc fix regarding ISO partition access

- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
The goal of this PR is to formalize the tests identified in #20952
Please let me know if you think this captures correctly what the tests should do.
> [entropy_src,testplan] Add testpoints for firmware override mode

- hw/ip/mbx/data/mbx_testplan.hjson
Please see commit messages for details.
> [mbx/dv] Map missing items in test plan

- sw/device/tests/crypto/cryptotest/BUILD
Since #20277 has been closed, there is now no need to split up the AES KAT tests.
> [cryptotest/aes] Consolidate AES KAT tests

- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
- sw/device/lib/dif/dif_entropy_src.c
- sw/device/lib/dif/dif_entropy_src.h
- sw/device/tests/BUILD
- sw/device/tests/entropy_src_fw_observe_many_contiguous.c
Testplan: #21150
Issue: #20952
> [entropy_src,sival] Implement entropy_src_fw_observe_many_contiguous

- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_min_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_stall_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_trans_nak_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_random_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR contains approved sequences:
random length out transaction
minimum length out transaction
maximum length out transaction
out stall
out trans nak
> [Usbdev] Sequences 

- sw/device/sca/sha3_serial.c
- sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
As discussed offline with @vogelpi, this PR moves the arming and disarming of the SCA trigger for SHA3 before and after the process command is issued. This ensures that we only capture the SCA relevant parts for doing power analysis.
> [pentest] Move SHA3 trigger arm&disarm

- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
This is cross-referenced to plic_all_irqs_test_0.
> [sival,alert_handler] Add irq test

- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/spi_device_flash_smoketest.c
- sw/host/tests/chip/spi_device_flash_smoketest/BUILD
- sw/host/tests/chip/spi_device_flash_smoketest/src/main.rs
Fix https://github.com/lowRISC/opentitan/issues/20631
> [sival, spi_dev_flash] Add smoke test and link to test plan

- azure-pipelines.yml
> [ci] Disable CW310 rom job

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
This commit contain changes in #21381 testplan entry.
> [RV_DM]rv_dm_abstractcmd_testentry

- hw/ip/lc_ctrl/data/lc_ctrl.hjson
See #20979 for details.
Fixes #20979.
> [lc_ctrl] Re-certify D2S

- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
Update missing bazel target to the testplan.
> [flash_ctrl, dv] Add more sival target to the testplan

- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This commit contains test sequence and other related files of #21381 testplan entry.
> [RV_DM]rv_dm_abstractcmd_status_vseq

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
The sequence in case 'CompareCtrConsistency' tried to inject errors in
`rom_ctrl_compare.addr_q`. However, it didn't handle injecting errors
when the FSM of `rom_ctrl_compare` was in `state_q=Waiting` correctly.
The case has been split between `CompareCtrConsistencyWaiting` and
`CompareCtrConsistencyDone` and each of them handle error injection in
states `Waiting` and `Done` respectively.
For `CompareCtrConsistencyWaiting` the delay before injecting an error
has also been reduced by a fifth to increase the chances of the FSM in
`Waiting` state.
> [dv] Case 'CompareCtrConsistency' split cases '*Done' & '*Waiting'

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_disable_vseq.sv
Fix flash_ctrl_disable test.
Disable condition is set by multiple places and hasn't been evaluated properly.
Update disable condition.
> [flash_ctrl,dv] update flash_disable condition

- sw/device/lib/crypto/BUILD
- sw/device/lib/crypto/include/BUILD
- sw/device/lib/crypto/include/aes.h
- sw/device/lib/crypto/include/datatypes.h
- sw/device/lib/crypto/include/drbg.h
- sw/device/lib/crypto/include/ecc.h
- sw/device/lib/crypto/include/freestanding/BUILD
- sw/device/lib/crypto/include/freestanding/absl_status.h
- sw/device/lib/crypto/include/freestanding/hardened.h
- sw/device/lib/crypto/include/hash.h
- sw/device/lib/crypto/include/kdf.h
- sw/device/lib/crypto/include/key_transport.h
- sw/device/lib/crypto/include/mac.h
- sw/device/lib/crypto/include/rsa.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/otcrypto_hash_test.c
Cherrypicks the following commits to master:
- 24443194801df5c078d9912dad1d29fa25c3ffec
- 7b17cee780967344bd9d6f7b54a6b6565306ac75
> Cherrypick to master: [cryptolib] Export cryptolib as a stand-alone library

- hw/ip/gpio/doc/theory_of_operation.md
> [gpio,doc] Add clarity for interrupt

- sw/device/silicon_creator/lib/cert/dice.c
Som certificate fields are expected to be big endian formatted in order for the ASN1 to be encoded correctly. This fixes some integer byte arrays that were incorrect, causing certificates not to parse correctly.
> [dice] fix certificate array field endianness

- sw/device/silicon_creator/lib/cert/generic.hjson
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/host/ot_certs/src/asn1/builder.rs
- sw/host/ot_certs/src/asn1/codegen.rs
- sw/host/ot_certs/src/asn1/der.rs
- sw/host/ot_certs/src/asn1/dice_tcb.rs
- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/codegen.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/src/template/testgen.rs
- sw/host/ot_certs/src/x509/extension.rs
This cherry picks #20795 from the main branch (which did not seem to completely cherry pick over to ES Sival branch).
> [certs] cherry-pick #20795

- sw/device/silicon_owner/tock/kernel/src/io.rs
- sw/host/hsmtool/src/commands/rsa/generate.rs
- sw/host/hsmtool/src/commands/rsa/import.rs
- sw/host/opentitanlib/src/util/unknown.rs
- sw/host/opentitantool/src/command/status_cmd.rs
- sw/host/ot_certs/src/codegen.rs
This addresses lints that will be emitted by the `nightly-2024-01-01` toolchain, unblocking a toolchain update.
> [host] Fix upcoming lints.

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
Add call to `stop_transaction_generators` in the common run_mem_partial_access_vseq_sub sequence.
> [dv,otp_ctrl] Fix failure in otp_ctrl_mem_partial_access test

- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/usbdev_aon_wake_disconnect_test.c
- sw/device/tests/usbdev_aon_wake_reset_test.c
- sw/device/tests/usbdev_iso_test.c
- sw/device/tests/usbdev_mixed_test.c
- sw/device/tests/usbdev_pincfg_test.c
- sw/device/tests/usbdev_setuprx_test.c
- sw/device/tests/usbdev_stream_test.c
- sw/host/tests/chip/usb/BUILD
- sw/host/tests/chip/usb/mod.rs
- sw/host/tests/chip/usb/usb.rs
- sw/host/tests/chip/usb/usbdev_aon_wake.rs
First two commits are backports.
Fixes #19972
> [usbdev,sival] Enable silicon for usbdev_aon_wake_reset, implement usbdev_aon_wake_disconnect

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_halted_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_resuming_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_progbuf_busy_vseq.sv
This commit add up the request_halt() task in base_vseq for reusability of this task in other vseqs.
> [RV_DM]rv_dm_base_vseq

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_repeat_reset_wkup_vseq.sv
- sw/device/tests/pwrmgr_random_sleep_all_reset_reqs_test.c
- sw/device/tests/sim_dv/pwrmgr_b2b_sleep_reset_test.c
Also fix minor typos in other pwrmgr top-level test code.
Addresses #21706
> [sival,pwrmgr] Fix pwrmgr_random_sleep_all_reset_reqs_test

- hw/ip/dma/data/dma_testplan.hjson
Please see commit messages for details.
> [dma/dv] Fixes and updates to testplan

- hw/ip/spi_device/data/spi_device_testplan.hjson
Removing generic mode mentions so testplan in in sync with latest RTL changes
> [dv] SPI Device testplan generic mode removal

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This is a few small tidyups to the testplan and the config file. No real change, but it should silence a bunch of annoying warnings from dvsim.
> [usbdev,dv] Tidy up testplan/sim_cfg

- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
This PR contains changes in usbdev monitor, scoreboard, and base sequence according to the updated RTL.
> [usbdev] usbdev updated env

- hw/ip/spi_device/data/spi_device.hjson
> [spi_device] Sign off for D2 and D2S

- hw/ip/usbdev/rtl/usbdev.sv
> [lint,usbdev] Appease Verilator linting

- hw/ip/adc_ctrl/doc/programmers_guide.md
Some tweaks as suggested in https://github.com/lowRISC/opentitan/pull/21796#discussion_r1512198507
> [adc_ctrl/doc] Tweak ADC requirements

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
Updates AES and KMAC with passing silicon tests.
> [sival] Update test plan with passing silicon tests

- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs
- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_in_irq.rs
- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_inputs.rs
- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_outputs.rs
- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_reset.rs
- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ulp_z3_wakeup.rs
> [sysrst_ctrl,sival] Simplify sysrst_ctrl tests

- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_pins_sense_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR contains usbdev test sequence
> [dv,usbdev] usbdev sense seq PR

- hw/ip/usbdev/dv/env/seq_lib/usbdev_av_buffer_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_enable_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_min_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_nak_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_stall_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_trans_nak_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_received_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_sent_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_random_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
The various commits explain the changes in detail. This is part of the work needed to move data out of the base class and into arguments, which should be much easier to reason about.
> [usbdev,dv] Minor cleanups to vseqs and call_data_seq task

- hw/ip/uart/dv/env/seq_lib/uart_intr_vseq.sv
A combination of tweaks to reduce the maximum length of time the uart_intr test takes to run. These seem to reduce max runtime by about half. Improves fail rate slightly by reducing the chance of hitting the timeout set by `+test_timeout_ns`. Did not appear to worsen coverage when tested locally with 50 random tests each for baseline vs. change.
The first change simply limits `num_trans` to a lower maximum. The second change forbids slower baud rates (9600 baud) when performing a long test (`num_trans` > 2).
The third change tweaks some probabilities to reduce the time it takes to empty the RX FIFO when checking the `RxTimeout` interrupt, which could take a long time for large values of `timeout_ctrl.val`.
> [uart] Speed up uart_intr test

- hw/ip/adc_ctrl/doc/theory_of_operation.md
> [adc_ctrl/doc] Minor tweak

- hw/ip/adc_ctrl/rtl/adc_ctrl_intr.sv
This introduces a holding register on the destination side so that the signals are latched first before anding with dst_ack in order to produce control signals. This makes the CDC more conservative and guards against cases where simple AND gates can glitch during transitions.
> [adc_ctrl] Make CDC more conservative

- ci/scripts/run-fpga-tests.sh
- rules/opentitan/cc.bzl
- rules/opentitan/defs.bzl
- rules/opentitan/fpga_cw310.bzl
Backport first commit of #21757 and #21910
> [ci] Backport changes

- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/ecdsa.c
- sw/device/tests/crypto/cryptotest/firmware/ecdsa.h
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/host/cryptotest/testvectors/parsers/wycheproof_ecdsa_parser.py
- sw/host/tests/crypto/ecdsa_kat/src/main.rs
Manual cherry-pick of #20853 to `earlgrey_es_sival`
> [sival/cryptotest] Cherry-pick ECDSA test harness to ES sival branch

- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl
> [otp_ctrl] Sign off version 2.0.0 at D2S

- hw/ip/aon_timer/data/aon_timer.hjson
Major version bump due to change in wake-up timer to become 64-bit.
> [aon_timer] Move to v2.0/D2/V1

- .bazelrc
- sw/device/lib/base/hardened.h
- util/py/scripts/mapfile_to_json.py
1. Add a script to transform the mapfile to json and visualize the space utilization with a `d3.js` treemap.
2. Add a build config to disable hardening and measure the impact of hardening on code size.
> [rom] Measure ROM space utilization

- hw/top_englishbreakfast/util/prepare_sw.py
- sw/host/opentitanlib/bindgen/BUILD
- sw/host/opentitanlib/bindgen/difs.h
Fix English Breakfast build after #21682.
This is a quite hacky approach, but I don't want to implement proper multitop to fix the issue...
> [opentitanlib] fix English Breakfast build

- sw/device/silicon_creator/lib/attestation_key_diversifiers.c
- sw/device/silicon_creator/lib/attestation_key_diversifiers.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_header_unittest.cc
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/drivers/keymgr.c
- sw/device/silicon_creator/lib/drivers/keymgr.h
- sw/device/silicon_creator/lib/drivers/keymgr_functest.c
- sw/device/silicon_creator/lib/drivers/keymgr_unittest.cc
- sw/device/silicon_creator/lib/drivers/otbn.c
- sw/device/silicon_creator/lib/drivers/otbn.h
- sw/device/silicon_creator/lib/drivers/otbn_unittest.cc
- sw/device/silicon_creator/lib/otbn_boot_services.c
- sw/device/silicon_creator/lib/otbn_boot_services.h
- sw/device/silicon_creator/lib/otbn_boot_services_functest.c
- sw/device/silicon_creator/lib/sigverify/mod_exp_otbn.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize_3.c
- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom_ext/doc/si_val.md
- sw/device/silicon_creator/rom_ext/rom_ext.c
This partially addresses #21937.
> [silicon_creator] rename OTBN and keymgr driver functions

- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_stall_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Adds usbdev_in_stall sequence. when the in ep is set to stall then device will respond with stall pid.
> [usbdev] usbdev_in_stall_sequence_PR

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_progbuf_read_write_execute_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This commit contains vseq and other realted files and verify the functioanlity of program buffer.
> [RV_DM]rv_dm_progbuf_read_write_execute_vseq

- hw/ip/usbdev/dv/tb/tb.sv
No functional change: this is just a minor tidy-up.
> [usbdev,dv] Fix indentation in usbdev tb.sv

- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/doc/registers.md
- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
- sw/device/lib/dif/dif_hmac.c
- sw/device/lib/dif/dif_hmac.h
- sw/device/lib/dif/dif_hmac_unittest.cc
- sw/device/lib/testing/hmac_testutils.c
- sw/device/tests/BUILD
- sw/device/tests/hmac_secure_wipe_test.c
- sw/device/tests/sival/BUILD
Fixes [#21467](https://github.com/lowRISC/opentitan/issues/21467).
See commit messages for details.
> [sival] Add hmac_secure_wipe_test

- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/doc/registers.md
- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
- sw/device/lib/dif/dif_hmac.c
- sw/device/lib/dif/dif_hmac.h
- sw/device/lib/dif/dif_hmac_unittest.cc
- sw/device/lib/testing/hmac_testutils.c
- sw/device/tests/BUILD
- sw/device/tests/hmac_secure_wipe_test.c
- sw/device/tests/sival/BUILD
> [sival] hmac_secure_wipe_test

- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
The TB model of flash_mode interrupts isn't complete.
The task which updates a predicted interrupt pending gets killed on CSB=1.
Solution was to move the interrupt pending prediction out of DV_SPINWAIT to avoid thread being killed on CSB assertion.
In addition, There are situations in which the TB wasn't keeping track and clearing interrupt pending state correctly. 
For example, if the TB has interrupts pending before a read to intr_state and there is another interrupt of the same kind from the moment the CSR is read until the moment the CSR is written to clear interrupts, the TB was still believing after the write it had predicted interrupts when it didn't. 
The TB now clears interrupt pending ('intr_trigger_pending') on write to intr_status to avoid any later mismatch.
> Spi device readbuf interrupt tb fix

- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl
> [otp_ctrl] Move to V2S

- hw/ip/spi_device/dv/README.md
This PR takes care of issue #21864
> [dv_doc] spi_device dv doc generic mod and 2P SRAM mentions removal

- hw/ip/usbdev/dv/env/seq_lib/usbdev_enable_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_received_vseq.sv
This commit contains changes that will clear regression failures.
> [usbdev] Usbdev_sequences_changes

- sw/host/opentitanlib/src/transport/common/uart.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
> [ott] Remove UUCP-style locking for serial ports

- hw/ip/spi_device/rtl/spi_passthrough.sv
Add delays to the output-enable when the read pipeline is enabled in passthrough mode, so the drivers are left off for the full dummy cycle period.
@antmarzam discovered I left this out.
> [spi_device] Match OE with the passthrough read pipeline data

- hw/ip/adc_ctrl/data/adc_ctrl.hjson
> [dv,adc_ctrl] Declare V2S

- sw/device/tests/entropy_src_fw_override_test.c
In some situations software seems to work fast enough that it can try to use KMAC before SHA3 is idle after the previous use. Our testutils check for this condition but error out rather than try to recover from it. This change uses a very small timeout since it should become idle very quickly ideally.
The error condition was being observed when #22033 was applied. With this change, the error does not fire.
> [test] Ensure SHA3 is idle before using KMAC

- hw/lint/tools/dvsim/common_lint_cfg.hjson
- util/dvsim/LintParser.py
- util/dvsim/ascentlint-report-parser.py
This should avoid spurious CI failures caused by the kokoro AscentLint instance warning that the licence will expire soon.
> [lint] Demote licence warning in AscentLint parser

- hw/ip/spi_host/rtl/spi_host_fsm.sv
Redux of #21338
This is effectively the same change, but fixes the problem as diagnosed/described [in this comment](https://github.com/lowRISC/opentitan/pull/21338#issuecomment-1984908004).
Closes #14969 (again)
> [spi_host,rtl] Use sd_en_o[0] to only drive sd_o[0] during TX (std_mode)

- SUMMARY.md
- doc/project_governance/project_milestone_definitions.md
Definitions introduced in  https://github.com/lowRISC/opentitan/issues/18750
> [doc] Add Project Milestone Definitions

- hw/ip/usbdev/dv/README.md
> [usbdev,dv,doc] Expand usbdev DV document to reflect current state

- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/ast_clk_rst_inputs.c
Adjust the disablement of EDN module in accordance with the [programmers_guide](https://opentitan.org/book/hw/ip/edn/doc/programmers_guide.html).
> [sw, tests]: Update entropy complex enablement in ast_clk_rst_inputs.c

- hw/top_earlgrey/README.md
This addresses an issue raised in #22243.
> [top_earlgrey,doc] Mention working directory in README

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_stall_priority_over_nak_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR contains stall priority over nak response.
In this sequence we have set the endpoint to both stall and nak.
Stall will take priority and in response we will get the stall pid.
> [usbdev] Stall priority over nak sequence

- hw/ip/spi_host/data/spi_host.hjson
- hw/ip/spi_host/doc/registers.md
> [spi_host] Correct TXFULL description

- hw/ip/spi_host/data/spi_host.hjson
See discussion on issue #21010.
> [spi_host] Downgrade verification_stage to V1

- .github/workflows/pr_lint.yml
This has been done for Ibex repo already: https://github.com/lowRISC/ibex/commit/1c5da195b6d51bc2b96f4d56b3dc4652cb1b6142
> [ci] use pull_request instead of pull_request_target

- ci/scripts/exec-check.sh
This script checks for files with extensions that should not be executable.
> [ci] Simplify exec-check script

- hw/ip/i2c/data/i2c.hjson
See #20971 for signoff analysis.  Closes #20971.
> [i2c] Sign off at D2S

- sw/device/silicon_creator/lib/cert/uds_example_data.json
- sw/host/ot_certs/BUILD
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/tests/example.hjson
- sw/host/ot_certs/tests/example_data.json
- sw/host/ot_certs/tests/generic.hjson
- sw/host/ot_certs/tests/subst_test.rs
Fix a small bug in integer parsing and add an end to end substitution test.
> [ot_certs] Fix substitution bug and add integration test

- hw/ip/aon_timer/data/aon_timer.hjson
See #21030 for signoff analysis.  Closes #21030.
> [aon_timer] Sign off at V2S

- hw/ip/i2c/data/i2c.hjson
> [i2c] V0 -> V1

- hw/ip/spi_host/doc/programmers_guide.md
It is Status-Type in terms of signalling and handling for software. The appropriate section of comportability docs is linked to clarify this point.
> [spi_host,doc] Clarify that the 'spi_event' interrupt is Status-Type

- hw/ip/usbdev/data/usbdev.hjson
See #21005 for signoff notes.  Closes #21005.
> [usbdev] Sign off at V1

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv
The UVM code in the test sequence should not wait before updating the phase memory location via backdoor when transitioning to phase 3, or the update can be too late and the test will fail.
More details: In phase 2 the SV side causes sysrst_ctrl to detect the lid opened, which trigger a wakeup while the CPU is in deep sleep. SV then calls sync_with_sw, which delays updating the phase after the CPU enters test_main, and can cause phase 2 to rerun. Normally this test passes, but the delay can be configured via sim_dv runtime plusargs and set large enough for this to happen, and that is what happens for this failure.
The wait in phase 2 is unnecessary since the chip is asleep and opening the lid causes it to wakeup, so updating the phase can be done anytime before the CPU restarts running …
> [dv,top_level] Fix chip_sw_sysrst_ctrl_ulp_z3_wakeup test

- sw/device/silicon_creator/lib/cert/cdi_0.hjson
- sw/device/silicon_creator/lib/cert/cdi_1.hjson
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/src/x509.rs
- sw/host/ot_certs/tests/example.hjson
- sw/host/ot_certs/tests/example_data.json
- sw/host/ot_certs/tests/generic.hjson
Only review the last commit, the rest is from #22284
Tagging @jwnrt and @nbdd0121 for unsafe review.
> [ot_certs] Add support for validity dates

- hw/ip/rv_dm/data/rv_dm.hjson
See #20972 for the signoff analysis.  Closes #20972.
D2S signoff will come later, see #22356.
> [rv_dm] Sign off at D2

- util/py/scripts/mapfile_to_json.py
The `lld` linker mapfile is in a different format than `gnu-ld`'s mapfile.  Detect the dialect and parse appropriately.
> [util] Fix the `mapfile_to_json` script to work with `lld`

- hw/ip/usbdev/data/usbdev_testplan.hjson
This PR incorporates changes to the description of the usbdev setup_stage sequence to define a more generic behavior.
> [usbdev] Rewrite usbdev setup stage seq description

- util/py/scripts/mapfile_to_json.py
1. Add an option to control the displayed hierarhcy of objects.  Objects can be arranged either by `region` (memory region) or by `file` (ie: object module).
2. Add an option to control the dimensions of the generated HTML treemap.  Set the default to 1920x1080.
> [util] Improve `mapfile_to_json` script

- hw/formal/tools/vcformal/parse-formal-report.py
- hw/ip/clkmgr/util/clkmgr_gen_deprecated.py
- hw/ip/flash_ctrl/util/flash_ctrl_gen.py
- hw/ip/hmac/model/hmac_model.py
- hw/ip/otbn/dv/rig/rig/gens/bad_ispr.py
- hw/ip/pinmux/util/reg_pinmux.py
- hw/syn/tools/dc/at-plot.py
- sw/device/tests/otbn_data/otbn_test_params.py
- util/autogen_testutils.py
- util/design/gen-mubi.py
- util/design/keccak_rc.py
- util/dvsim/verixcdc-report-parser.py
- util/i2csvg.py
- util/i2csvg/convert.py
- util/ipgen/tests/test_render.py
- util/lint_commits.py
- util/topgen/clocks.py
Cherry-pick of second commit from https://github.com/lowRISC/opentitan/pull/20823 (by @vogelpi).
> Fix or waive Python lint errors and warnings

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_setup_stage_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR includes a setup_stage_vseq for usbdev, where we aim to transmit the setup packet by sending control data for the GET_DESCRIPTOR request.
> [usbdev,dv] usbdev setup stage seq

- hw/ip/spi_device/rtl/spi_tpm.sv
This commit fixes a lint error reported by Nuvoton.
> [spi_device] Fix lint error

- .github/workflows/pr_change_check.yml
- .github/workflows/pr_lint.yml
- .github/workflows/pr_lint_review.yml
> [ci] Update GitHub actions to match master

- doc/project_governance/project_milestone_definitions.md
> [doc] Fix typo in project_milestone_definitions.md

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aon_timer_testplan.hjson
- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_csrng_testplan.hjson
- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
- sw/device/tests/BUILD
This is a manual backport of https://github.com/lowRISC/opentitan/pull/22406 to master
> Manual Backport 22406 to master

- hw/top_earlgrey/data/ip/chip_uart_testplan.hjson
- sw/device/lib/testing/test_framework/ottf_console.h
- sw/device/lib/testing/uart_testutils.c
- sw/device/lib/testing/uart_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/uart_parity_test.c
- sw/device/tests/uart_tx_rx_test.c
- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
- sw/host/opentitanlib/src/io/uart.rs
- sw/host/opentitanlib/src/proxy/handler.rs
- sw/host/opentitanlib/src/proxy/protocol.rs
- sw/host/opentitanlib/src/transport/common/uart.rs
- sw/host/opentitanlib/src/transport/hyperdebug/uart.rs
- sw/host/opentitanlib/src/transport/proxy/uart.rs
- sw/host/tests/chip/uart/BUILD
- sw/host/tests/chip/uart/src/uart_parity.rs
- sw/host/tests/chip/uart/src/uart_tx_rx.rs
- third_party/rust/Cargo.lock
- third_party/rust/Cargo.toml
- third_party/rust/crates/BUILD.serialport-4.2.2.bazel
> [cherry-pick] Backport 21845 to earlgrey es sival

- sw/device/tests/BUILD
- sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c
- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/test_utils/gpio_monitor.rs
- sw/host/opentitanlib/src/test_utils/mod.rs
- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs
- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ulp_z3_wakeup.rs
Read the commits for a description. In short:
- fix `ulp_z3_wakeup`
- introduce gpio monitor test util and use it in tests
> [sysrst_ctrl,sival] Various improvements

- azure-pipelines.yml
> [ci] increase SiVal ROM_EXT test timeout

- hw/ip/prim_generic/prim_generic_otp.core
Add missing condition to use the correct ast_pkg.
> [ast] Add dependency in fileset_partner to select correct ast_pkg

- sw/device/tests/penetrationtests/firmware/ibex_fi.c
- sw/device/tests/penetrationtests/json/ibex_fi_commands.h
This commit adds the new alert handler format to the Ibex FI tests.
> [pentest] Add new alert handler to tests

- sw/device/tests/BUILD
- sw/device/tests/entropy_src_csrng_test.c
> Fix entropy src csrng test

- sw/device/tests/BUILD
- sw/device/tests/entropy_src_csrng_test.c
> Backport fix entropy src csrng

- sw/device/silicon_creator/lib/cert/asn1.c
- sw/device/silicon_creator/lib/cert/asn1.h
- sw/device/silicon_creator/lib/cert/asn1_unittest.cc
- sw/device/silicon_creator/lib/cert/cdi_0.hjson
- sw/device/silicon_creator/lib/cert/cdi_1.hjson
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/host/ot_certs/src/asn1/builder.rs
- sw/host/ot_certs/src/asn1/codegen.rs
- sw/host/ot_certs/src/asn1/der.rs
- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/src/x509.rs
- sw/host/ot_certs/src/x509/extension.rs
- sw/host/ot_certs/tests/example.hjson
- sw/host/ot_certs/tests/example_data.json
- sw/host/ot_certs/tests/generic.hjson
#22496: [ot_certs] Add support for pushing boolean and make basic constraints configurable
> [cherry-pick] #22496 to `earlgrey_es_sival` branch

- rules/opentitan/splice.bzl
Fixes #21668, see issue for details
> [bazel] Fix bitstream splicing with skip configuration

- SUMMARY.md
- sw/device/silicon_creator/rom_ext/doc/ownership.md
Convert ownership transfer documentation to markdown.
> [doc] Ownership Transfer

- hw/ip/edn/rtl/edn.sv
The existing code wasn't quite right and actually causes a compilation error when you try to push it through Jasper. For a bit more detail, edn_enable_fo is the "edn enable fanout". This is indexed by entries from FatalErr(=1) to LastEdnEntry-1, and doesn't have anything at index zero. (This is what causes the compilation error)
The bug was introduced by a974108, which removed an "enable_q" signal from edn.sv. Looking at the assertions, I think the property that we're talking about is "some of EDN is enabled". To get what I hope is the intended behaviour, I've used a unary OR to combine together all of the enable signals.
The bug is causing N/A entries in the "nightly" FPV tests, discussed here: https://github.com/lowRISC/opentitan/issues/22385#issuecomment-2058225120.
> [edn,rtl] Fix indices in assertion

- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
> [sival] Add entropy_src_fw_override_test to test plan

- doc/getting_started/setup_fpga.md
This commit adds '--' to two of the commands to make them execute as intended.
> [doc] fpga reproduce fail

- hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/i2c_host_override_test.c
- sw/device/tests/i2c_target_test.c
- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
- sw/host/opentitanlib/src/test_utils/bitbanging/i2c.rs
- sw/host/tests/chip/i2c_host_override/BUILD
- sw/host/tests/chip/i2c_host_override/src/main.rs
- sw/host/tests/chip/i2c_target/src/main.rs
This PR is easier to review each commit separately.
Fix https://github.com/lowRISC/opentitan/issues/19837
> [SiVal, i2c]  Adds the override test

- hw/ip/usbdev/dv/env/usbdev_TransactionManager.sv
- hw/ip/usbdev/dv/env/usbdev_packet_classifier.sv
This PR includes modifications to the usbdev_packet_classifier class, removes unnecessary stuff, and adjusts the usbdev_transaction_manager class to accommodate changes made in the pkt_classifier class
> [usbdev] usbdev predictor amendment

- hw/ip/prim/fpv/tb/prim_count_tb.sv
This was broken by c721c51c133.
> [prim,fpv] Fix port list in prim_count_tb

- hw/ip/edn/dv/sva/edn_assert_if.sv
This fixes broken DV tests run in private CI that was introduced in #22602.
> [edn/dv] fix broken private CI tests

- hw/ip/prim/lint/prim_count.vlt
- hw/ip/prim/lint/prim_count.waiver
- hw/ip/prim/rtl/prim_count.sv
- hw/ip_templates/alert_handler/fpv/vip/alert_handler_esc_timer_assert_fpv.sv
- hw/ip_templates/alert_handler/rtl/alert_handler_esc_timer.sv
- hw/top_earlgrey/ip_autogen/alert_handler/fpv/vip/alert_handler_esc_timer_assert_fpv.sv
- hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_esc_timer.sv
This doesn't get us to 100%, but it should improve things quite a bit. There are detailed comments on the individual commits.
> Improve alert_handler_esc_timer_fpv results a bit

- sw/device/tests/penetrationtests/firmware/ibex_fi.c
- sw/device/tests/penetrationtests/firmware/ibex_sca.c
- sw/device/tests/penetrationtests/firmware/otbn_fi.c
Based on feedback during the SCA & FI penetration testing, this commit changes the following:
- Avoid code optimization for conditional branch test
- Optimize init of different tests
- Performance optimizations
> [pentest] Add tweaks to FI & SCA code

- hw/ip/ascon/data/ascon.hjson
- hw/ip/ascon/doc/registers.md
- hw/ip/ascon/rtl/ascon_reg_top.sv
This fixes the missing regwen field in CTRL_AUX_SHADOWED
> [ascon] fix AUX_CNTRL_SHADDWOED REGWEN

- hw/ip/ascon/ascon.core
- hw/ip/ascon/lint/ascon.vlt
- hw/ip/ascon/lint/ascon.waiver
- hw/ip/ascon/rtl/ascon.sv
- hw/ip/ascon/rtl/ascon_core.sv
- hw/top_earlgrey/lint/top_earlgrey_lint_cfgs.hjson
This PR adds linting to ascon.
Unfortunately, I don't have a local license for AscentLint, so I cannot check it locally before it goes to the CI
> Ascon lint

- sw/device/tests/penetrationtests/firmware/crypto_fi.c
- sw/device/tests/penetrationtests/firmware/ibex_fi.c
The SW build on the earlgrey_es_sival branch seemed to be broken. This should fix.
> [pentest] fix ci/build

- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/x509.rs
- sw/host/ot_certs/tests/example.hjson
- sw/host/ot_certs/tests/example_data.json
- sw/host/ot_certs/tests/generic.hjson
> [ot_certs] Add support for parse subject alternative name

- hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson
- sw/device/lib/testing/json/command.h
- sw/device/lib/testing/json/i2c_target.h
- sw/device/tests/i2c_target_test.c
- sw/host/opentitanlib/src/test_utils/i2c_target.rs
- sw/host/tests/chip/i2c_host_override/src/main.rs
- sw/host/tests/chip/i2c_target/src/main.rs
Fix https://github.com/lowRISC/opentitan/issues/19838
> [Sival, i2c] Adds Clock stretching test

- sw/device/silicon_creator/manuf/lib/flash_info_fields.c
- sw/device/silicon_creator/manuf/lib/flash_info_fields.h
- sw/device/silicon_creator/manuf/lib/personalize.c
> [manuf] provision TPM attestation key seeds in flash info

- hw/ip/pattgen/dv/tb.sv
These are actually all connected to 1 internally, so their behaviour should be pretty trivial! Connect them to variables in tb.sv and add an assertion that says they are high.
> [pattgen,dv] Wire up cio_*_tx_en_o ports

- hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv
- hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
This width wasn't quite right for `u_prim_count_esc_cnt` in the design (and Jasper correctly points out that we can't get to the maximal count value).
We pick a target to ping by incrementing that target's index every time we went around the FSM that drove the pings. Of course, there are only finitely many targets (`N_ESC_SEV` of them) and we wrap at `N_ESC_SEV-1`.
With the current code (before or after this commit), this is done by driving an `esc_cnt_clr` signal. Before we switched to use `prim_count` (in commit b5eb150), the wrapping was implemented directly in this file.
The switch to `prim_count` was reasonable, but instantiated the counter with a width of `PING_CNT_DW`, which is 16, instead of the number of bits needed to represent `N_ESC_SEV-1 = 3`, which is just 2.
> [alert_handler,rtl] Correct width of prim_count instance

- BLOCKFILE
- hw/ip/pinmux/data/pinmux.hjson
- hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
These are currently broken for a couple of silly reasons. Commits 2 and 3 are needed to get the build going again. Commit 1 is orthogonal, but I noticed it was needed while working through things.
> [pinmux,fpv] Fix nightly FPV runs

- sw/host/tests/chip/rv_dm/src/mem_access.rs
The test is randomised and sometimes will try to access the last 32 bytes of the ROM which is not accessible via SBA and fail. Exclude these 32 bytes from the test.
> [sival, rv_dm] fix rv_dm_mem_access flakiness

- third_party/lint/repos.bzl
Cherry-pick of 959d4a3bfaf676671472b9799e0eacd5563ad332
This should fix CI
> [cherry-pick] Backport 22783 to integrated_dev

- hw/ip/csrng/dv/env/csrng_path_if.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
- hw/ip/csrng/dv/sva/csrng_assert_if.sv
This PR contains several independent but rather small fixes to CSRNG DV to get it working again. Without this, some of the CSRNG sequences are completely broken.
> [csrng/dv] Fix up DV

- hw/ip/rv_dm/data/rv_dm.hjson
The analysis supporting this is given in issue #22356.
Closes #22356.
> [rv_dm] Move lifecycle stage to D2S

- hw/ip/spi_device/rtl/spi_device.sv
intercept_en is used to select between the passthrough and internal read paths, but when the fast read pipeline is enabled, this selector needs to follow the data values that it is meant to select. Add intercept_en to the set of signals that pass through the read pipeline, so the correct data can be selected on the cycle in which it is used.
Without this change, transitions from the mailbox to passthrough may cause passthrough data to appear when the last mailbox data should be transmitted.
> [spi_device] Track intercept_en along the read pipeline

- sw/device/silicon_creator/rom_ext/rom_ext.c
> [cherry-pick] #22940 to `earlgrey_es_sival` branch

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/doc/registers.md
- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/keymgr/dv/tb.sv
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv
This resolves https://github.com/lowRISC/opentitan/issues/22877.
For details, please see the individual commit messages.
> [keymgr] Modify PRNG reseeding

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/keymgr/dv/tb.sv
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv
- hw/ip/keymgr_dpe/data/keymgr_dpe.hjson
- hw/ip/keymgr_dpe/dv/env/keymgr_dpe_if.sv
- hw/ip/keymgr_dpe/dv/env/seq_lib/keymgr_dpe_base_vseq.sv
- hw/ip/keymgr_dpe/dv/tb.sv
- hw/ip/keymgr_dpe/rtl/keymgr_dpe.sv
This is a port of #22951 to `integrated_dev`.
> [keymgr,keymgr_dpe] Modify PRNG reseeding

- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/defs.bzl
- sw/device/silicon_creator/rom_ext/proda/BUILD
- sw/device/silicon_creator/rom_ext/prodc/BUILD
- sw/device/silicon_creator/rom_ext/sival/BUILD
This PR depends on #22942.  You need only review the last commit.
> [rom_ext] Set the ROM_EXT version number 

- hw/dv/sv/tl_agent/seq_lib/tl_device_seq.sv
No functional change, but this avoids an Xcelium warning about unusual use of a queue.
> [dv] Tweak tl_device_seq to avoid a runtime warning from Xcelium

- sw/host/provisioning/cp/BUILD
- sw/host/provisioning/ft/BUILD
- sw/host/provisioning/orchestrator/orchestrator.py
- sw/host/provisioning/orchestrator/ot_device.py
This fixes the provisioning orchestrator script and the CP/FT host binary build rules that was triggering errors at run time.
> [manuf] fix provisioning orchistrator

- hw/ip/hmac/dv/env/hmac_env_cov.sv
- hw/ip/hmac/dv/env/hmac_env_pkg.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_common_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_datapath_stress_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
- fix and improve coverage model
- fix couple of minor SCB issues
- rename couple objects to be more relevant
> [hmac/dv] Cleanups and coverage fixes/improvements

- apt-requirements.txt
- sw/device/silicon_creator/manuf/keys/fake/BUILD
- sw/device/silicon_creator/manuf/provisioning_inputs.bzl
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize_4.c
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/ft_lib/BUILD
- sw/host/provisioning/ft_lib/src/lib.rs
This cherry-picks some commits from the master branch that adds checks to the ft_personalize test flow to ensure certificates are verifiable with openssl.
> [cherry-pick] #22978 and #23023 to `earlgrey_es_sival`

- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
- sw/host/provisioning/ft_lib/src/lib.rs
This cleans up the `ft_personalize` binary to consolidate operations into sub-functions, and increase readability. Additionally this fixed an initialization bug in the size of the TPM TBS certificate buffers. Lastly, this updates the certificate hash comparison on the host side to print both hashes if the comparison fails (so that it is easier to see how the host interpretted the bytes, including in the order of said bytes).
> [manuf] cleanup `ft_personalize`

- sw/device/tests/sim_dv/otp_ctrl_lc_signals_test.c
In #22946, keymgr got changed to abort into the Invalid state when the Creator Root Key is not valid during initialization.  The `otp_ctrl_lc_signals_test` was not yet adapted to this behavior; this commit fixes that test.
This should fix issue #23019 (the combination of test and seed mentioned there now passes), although we might want to wait for a nightly regression to confirm.
> [sw/tests] Fix `otp_ctrl_lc_signals_test`

- hw/ip/edn/dv/env/edn_scoreboard.sv
- hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv
This PR fixes some edge cases for edn_disable_auto_req_mode_vseq.
For further information pleas have a look at the commit message.
I ran a full regressions for the edn_disable_auto_req_mode test and a 10% regression on all tests.
All tests passed.
Fixes #20818
> [edn/dv] Fix some edge cases for edn_disable_auto_req_mode_vseq

- hw/ip/csrng/doc/theory_of_operation.md
Please see the commit message.
> [csrng/doc] Correct documentation for invalid acmd

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv
- sw/device/tests/sram_ctrl_scrambled_access_test.c
No material changes from #22989.
> [sival] Backport 22989 to master

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_filesystem_support_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_evict_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_word_sweep_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_filesystem_support_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_evict_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_word_sweep_vseq.sv
Handle program resolution window in flash_ctrl_fs_sup test. Keep fractions even in flash_ctrl_write_word_sweep.
> [dv,flash_ctrl] Fix some test failures

- hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.hjson
- hw/top_earlgrey/ip/sensor_ctrl/doc/registers.md
- hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_top.sv
Part of #23149; see that issue for details.
> [sensor_ctrl] Change reset value of `ALERT_EN` CSRs to MuBiTrue

- azure-pipelines.yml
- ci/scripts/check-countermeasures.sh
- util/reggen/countermeasure.py
- util/reggen/ip_block.py
- util/regtool.py
- util/topgen.py
This has two commits:
- Move the countermeasure checks to topgen.py.
- Trigger the countermeasure check in CI.
Fixes #10071
> [util,reggen] Trigger errors for countermeasures missing in RTL

- sw/device/lib/crypto/drivers/entropy.c
Previously, the main SM state was only checked for the first command word but not for the additional data. Not checking the main SM state before writing the additional data could cause CSRNG to drop additional data provided by software while handling a hardware command. Once the hardware command was handled, the software instance would win arbitration and CSRNG would wait for software to provide the dropped additional data, thereby stalling the entire entropy complex. This would happen for example if a HW instance request would collide with a software request. Since the software command FIFO is only 2 entries deep, it can only be guaranteed to absorb 2 words if the software interface doesn't win arbitration immediately.
This commit contains the ES / CSRNG v.1.0.0 specific version of …
> [cryptolib] Fix CSRNG driver for using the SW command interface of CSRNG

- hw/ip/otbn/dv/smoke/BUILD
- hw/ip/otbn/dv/smoke/smoke_test.s
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- rules/otbn.bzl
- sw/device/tests/BUILD
- sw/device/tests/otbn_isa_test.c
This is a manual cherry-pick of https://github.com/lowRISC/opentitan/pull/21684/:
Git failed to find the hashes, so I pull the pull locally to be able to cherry-pick them.
I also needed to update the licence headers of the new files.
> OTBN ISA Test - Backport 21684 to earlgrey es sival

- rules/opentitan/defs.bzl
- sw/device/tests/BUILD
- sw/device/tests/usbdev_iso_test.c
- sw/device/tests/usbdev_mixed_test.c
- sw/device/tests/usbdev_stream_test.c
- sw/host/tests/chip/usb/usb.rs
- sw/host/tests/chip/usb/usb_harness.rs
- sw/host/tests/chip/usb/usbdev_aon_wake.rs
- sw/host/tests/usbdev/usbdev_stream/stream_test.cc
> Usb harness backport

- hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
The tweaks are described in detail in their respective PRs. Nothing particularly exciting, but they silence a bunch of lint warnings.
> [pinmux,fpv] Various tweaks to avoid lint warnings

- hw/ip/hmac/rtl/hmac.sv
- hw/ip/prim/rtl/prim_sha2.sv
- hw/ip/prim/rtl/prim_sha2_32.sv
- hw/ip/prim/rtl/prim_sha2_pad.sv
This PR contains multiple fixes to `prim_sha2_pad` and `hmac` for the save & restore feature. Please see the commit messages for details.
> [prim_sha2_pad,hmac/rtl] Multiple fixes for save & restore

- hw/ip/prim_generic/rtl/prim_generic_pad_wrapper.sv
- hw/ip/prim_xilinx/rtl/prim_xilinx_pad_wrapper.sv
- hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_pad_wrapper.sv
Based on feedback from silicon teams.
> [prim_pad_wrapper,rtl] Change input enable to active-high

- sw/device/tests/BUILD
- sw/device/tests/usbdev_iso_test.c
- sw/device/tests/usbdev_mixed_test.c
- sw/device/tests/usbdev_stream_test.c
- sw/host/tests/chip/usb/usb.rs
- sw/host/tests/chip/usb/usb_harness.rs
> Fix usb sival backport

- hw/ip/otbn/rtl/otbn_loop_controller.sv
I don't think we need this in for an M2 RCs but worth getting in for M3 so draft PR for now.
Before this fix it was possible for the loop stack to be told to push and pop at the same time. This could put the loop stack in a weird state, however a software error is always triggered so OTBN halts and the stack will be reset before running a new program so practically it's not a problem.
Still I think it's neater to stop that ever happening, hence this change. It also allows us to assert we'll never see a simultaneous push and pop committed.
> [otbn, rtl] Avoid a loop stack commit on simultaneous push/pop

- hw/top_earlgrey/dv/env/seq_lib/chip_padctrl_attributes_vseq.sv
- hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.hjson
- hw/top_earlgrey/ip/sensor_ctrl/doc/registers.md
- hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
- hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_pkg.sv
- hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_top.sv
Based on a request from the silicon team.
> [top_earlgrey,sensor_ctrl] Add pull attributes for manual pads

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- hw/top_earlgrey/data/standalone_sw_testplan.hjson
Update the testplans accordingly with the discussions of the last SiVal meeting.
> Sival update testplans

- sw/device/lib/testing/BUILD
- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/keymgr_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/keymgr_sideload_aes_test.c
- sw/device/tests/keymgr_sideload_kmac_test.c
- sw/device/tests/keymgr_sideload_otbn_test.c
Cherry pick from: https://github.com/lowRISC/opentitan/pull/23298
> [cherry-pick] Manual backport from earlgrey es sival pr 23298

- sw/device/silicon_creator/rom/bootstrap.c
> [rom] Document bootstrap detection

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv
These are mostly commits that add comments, except the last one, which drops an unnecessary wait. Some (rather trivial!) explanation in the commit messages.
> [rv_dm,dv] Tidy-ups in the smoke vseq

- sw/device/silicon_creator/lib/attestation.h
- sw/device/silicon_creator/manuf/lib/flash_info_fields.c
- sw/device/silicon_creator/manuf/lib/flash_info_fields.h
- sw/device/silicon_creator/manuf/lib/personalize.c
> [manuf] add keygen version field to attestation seed page

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/doc/registers.md
This PR adds new testpoints to the testplan for newly-merged I2C features
Currently split into commits with new testpoints per-PR/commit that was merged, just to make reviewing and discussion easier. This will be squashed down before merging.
Changes from:
Closes #22895
> [i2c,testplan] Add testpoints for new features

- sw/host/opentitantool/src/command/rescue.rs
The rescue protocol has a new feature to increase the communication rate above the power-on default, which greatly reduces the time it takes to load a firmware image.
However, if a subsequent command want to e.g. use the serial console after finishing flashing and rebooting, it will operate at its default speed.
This change makes opentitantool also restore the speed setting of HyperDebug, to match that of the OT chip under test.
> [opentitantool] Restore baud rate after rescue

- hw/top_earlgrey/dv/sva/clk_ctrl_and_main_pd_sva_if.sv
- hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv
This change impacts wakeup and power down time.
> [ast] Updating Lc2HcTrCyc, Hc2LcTrCyc according to macro delay

- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- sw/device/tests/BUILD
> Backport flash ctrl lc states

- hw/top_earlgrey/data/chip_testplan.hjson
- sw/device/lib/crypto/data/crypto_testplan.hjson
- sw/device/lib/testing/test_framework/data/ottf_testplan.hjson
Map new tests as discussed on the last SiVal meeting.
> [Sival]  update testplans

- sw/device/silicon_creator/lib/boot_log.h
- sw/device/silicon_creator/rom/e2e/retention_ram/rom_e2e_ret_ram_keep_test.c
- sw/device/silicon_creator/rom/rom.c
Record whether RETRAM was initialized in the boot log.
> [rom] Record whether RETRAM was initialized

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sleep_pin_mio_dio_val_test.c
- sw/host/tests/chip/gpio/BUILD
- sw/host/tests/chip/gpio/src/sleep_pin_mio_dio_val.rs
Manual cherry-pick of #23214 into master
> Port `chip_sw_sleep_pin_mio_dio_val` to SiVal (cherry-pick to master)

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_halt_resume_whereto_vseq.sv
This PR contains two commits, but the first comes from #22962, which should be merged first. The second commit has the following commit message:
This check works by reading from the WHERETO magic address. We expect
to get a jump instruction (jal), but it turns out that there are two
possible destinations: the start of the program buffer and the start
of an abstract command.
Rather than modelling exactly which destination to expect, let's
just weaken the check to ensure we get a jump to one of them.
This fixes a failure mode for the stress sequence where we were
failing because the rv_dm_cmderr_busy_vseq had written something to
the command register before rv_dm_halt_resume_whereto_vseq ran, which
meant we ended up pointing at the abstract command instead of the
program buffer.
> [rv_dm,dv] Slightly weaken check in rv_dm_halt_resume_whereto_vseq

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_common_vseq.sv
This commit fixes the following error message: `Setting the value of field "en" while containing register "sram_ctrl_regs_reg_block.readback" is being accessed may result in loss of desired field value. A race condition between threads concurrently accessing the register model is the likely cause of the problem.`
The reason for this message was that the `sram_readback_en` task was spawned multiple times, causing the error indicated in the message.
Test  pass rate is now at 99.23%:
<details>
<!DOCTYPE html>
<html lang="en">
<body>
<div class="results" style='font-family:"Trebuchet MS", Arial, Helvetica, sans-serif; margin:0 auto; max-width:960px; padding-left:40px; padding-right:40px; padding-top:15px; position:relative; width:80%' width="80%">
<h2 style="padding-bottom:15px; …
> [sram_ctrl/dv] Avoid setting readback enable during access

- sw/device/lib/crypto/drivers/hmac.c
Improves HMAC driver with the following changes, so that we have better coverage on HMAC RTL:
- Instead of writing messages byte at a time, try to write them in words as much as possible.
- Previously, oneshot HMAC/SHA-2 call was internally translated to `init->update->final` calls. With this PR, the oneshot calls do not force unnecessary context switches. They are done in one go as they should be.
- Recently fixed/added Idle status bit of HMAC is now used, instead of waiting `hmac_done` interrupt to fire. Both could be used, but we want to use Idle to make sure that it is working.
- Some code formatting + new functions to avoid duplicating same code in one-shot and streaming calls.
cc: @gdessouky
> [hmac, driver] Improve HMAC driver

- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_setup_stage_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
- Eliminate some redundant functions and unused variables.
- Formatting/style guide changes.
- Added explanatory comments.
Pass rates unaffected. No functional change.
> [dv,usbdev] Tidy up packet classes

- hw/ip/hmac/rtl/hmac.sv
- hw/ip/hmac/rtl/hmac_core.sv
This implements minor fixes to the coding style, e.g., defaults on top, etc. to align with our conventions with no functionality impact. Purely cosmetic :-)
> [hmac,rtl] Coding style fixes

- hw/ip/entropy_src/rtl/entropy_src_core.sv
Previously, these errors would trigger a fatal alert but not cause a local escalation (i.e. lock up the main SM). Since all these errors are structural errors that can't occur e.g. due to how the module currently operates but instead due to FI attacks only, these errors should also cause a local escalation.
This change better aligns ENTROPY_SRC with EDN and CSRNG.
This resolves lowRISC/OpenTitan#19789.
> [entropy_src] Locally escalate upon internal FIFO errors and FSM errors

- hw/ip/csrng/rtl/csrng_core.sv
Previously, these errors would trigger a fatal alert but not cause a local escalation (i.e. lock up the main SM). Since these FSM errors are structural errors that can't occur e.g. due to how the module currently operates but instead due to FI attacks only, these errors should also cause a local escalation.
This change better aligns CSRNG with EDN and ENTROPY_SRC.
This is related to lowRISC/OpenTitan#19789.
> [csrng] Locally escalate upon FSM errors

- hw/ip/otbn/dv/model/otbn_trace_checker.cc
- hw/ip/otbn/dv/model/otbn_trace_entry.cc
- hw/ip/otbn/dv/model/otbn_trace_entry.h
- hw/ip/otbn/dv/tracer/rtl/otbn_tracer.sv
- hw/ip/otbn/dv/uvm/env/otbn_env.core
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_partial_wipe_vseq.sv
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_vseq_list.sv
- hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson
The real test is in the final commit of this PR, but forcing some signals inside the design broke some DV code assumptions about what should happen in a trace. Those are weakened/fixed in the other commits in the PR.
> [otbn,dv] Add a partial wipe test

- hw/ip/spi_host/rtl/spi_host_fsm.sv
Promote CPHA=1 to have its own fully-fledged logic, instead of
incorrectly chaining it to CPHA=0 cases. Leave only the timing of the
read enable with the simple delayed control style.
Also, ensure the state after IdleCSBActive still counts out a full
clkdiv so setup times are met. Previously, the launching state might
only last a single cycle.
Ensure that the data outputs and output-enables are held for the same
value continuously until the next launch edge. Use assertions to verify.
The commit introducing the assertions can be removed. It's merely to show it as an example.
> [spi_host] Fix handling of CPHA=1 and IdleCSBActive

- hw/ip/csrng/rtl/csrng_cmd_stage.sv
The decision whether a command is invalid is taken based on the command header but EDN might continue and send the additional data as well (it might already be in the FIFO). Previously, CSRNG would just pop the invalid command header from the FIFO and leave any additional data in the FIFO which can then erroneously be interpreted as the next command header.
Instead, we have to absorb the full invalid command before we can continue. This commit modifies the design to keep emptying the FIFO until the command interface is idle.
This is related to lowRISC/OpenTitan#23526.
> [csrng] Flush command FIFO after signaling ACK errors

- hw/top_earlgrey/rtl/padring.sv
This resolves lowRISC/OpenTitan#23600.
> [padring] Correct enumeration type for IOB[3:0] muxing

- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv
Adding scan mode controllability according to DFT reports.
> [ast] improving dft readiness

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_common_vseq.sv
These currently cause spurious errors in the `sram_ctrl_sec_cm` test. The problem is that the count in the request fifo gets forced from 0 to 1. This spits out a bogus TL request, and also causes an alert to be raised by the sram adapter.
The alert is good: it's exactly what is supposed to happen. Unfortunately, the request that goes out might be X (because the fifo has never not been empty). Unfortunately, the TL response ends up polluted with X and this lets multiple TL-UL integrity checks within the `sram_ctrl` DV environment fail.
This change disables fault injection on these particular FIFO counters, side-stepping the issue.
Based on lowRISC/opentitan#23627
This change lets the `sram_ctrl_sec_cm` tests pass again:
<details>
<!DOCTYPE html>
<html lang="en">
<body>
<div class="results" …
> [sram_ctrl,dv] Disable FI checks in tlul_adapter req fifos

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
This handles a situation when we don't actually find a time to inject an error (in inject_redun_err). Now we try a couple more times.
> [otbn,dv] Try multiple times in otbn_ctrl_redun_vseq

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_common_vseq.sv
With lowRISC/opentitan#23515, the .Secure(1'b1) parameter was also enabled for the u_tlul_adapter_sram_imem.u_reqfifo and u_tlul_adapter_sram_imem.u_sramreqfifo. Hence, for the same reason as explained in lowRISC/opentitan#23627 we should also exclude FI on these FIFOs.
In addition, lowRISC/opentitan#23627 only excluded the FI tests for the u_rptr. However, the same issue ('X all over the place) could also happen when faulting the u_wptr of the according FIFO. Hence, this commit also excludes FI for the u_wptr.
> [otbn,dv] Disable FI tests also for certain IMEM FIFOs

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv
These currently cause spurious errors in the sram_ctrl_sec_cm test. The problem is that the count in the request fifo gets forced from 0 to 1. This spits out a bogus TL request, and also causes an alert to be raised by the sram adapter.
The alert is good: it's exactly what is supposed to happen. Unfortunately, the request that goes out might be X (because the fifo has never not been empty). Unfortunately, the TL response ends up polluted with X and this lets multiple TL-UL integrity checks within the flash_ctr DV environment fail, e.g. accessing the debug_state after flash is locked.
This change disables fault injection on these particular FIFO counters, side-stepping the issue.
Based on #23627
Closes #23567
> [flash_ctrl/dv] Disable FI checks in tlul_adapter req fifos

- hw/ip/otbn/dv/otbnsim/sim/sim.py
This should behave the same as the code that was there before, except that we no longer disable URND as we enter RMA (but this doesn't matter because we're going to lock anyway).
This makes the case analysis slightly simpler and there's now a comment that explains it clearly.
(This is motivated by me trying to tidy up the model's handling of escalation requests. This needed me to tidy up how the `rma_req` signal got passed around, which needed me to read this reasonably carefully).
> [otbn,dv] Restructure end of wipe round in sim.py

- hw/dv/sv/csr_utils/csr_seq_lib.sv
There shouldn't be any functional change, but the code hopefully becomes much easier to glance at. Since I wanted to make sure I understood it anyway, I thought this would be a chance to make it easier for the next person...
> [dv] Minor cleanups in the bit bash sequence

- hw/ip/keymgr/lint/keymgr.waiver
- hw/ip/kmac/lint/sha3.waiver
- hw/ip/prim/lint/prim.waiver
- hw/ip/prim/lint/prim_fifo.waiver
- hw/ip/prim/lint/prim_secded.waiver
- hw/ip_templates/flash_ctrl/lint/flash_ctrl.waiver
- hw/top_earlgrey/ip_autogen/flash_ctrl/lint/flash_ctrl.waiver
See commit messages for details.
> [lint] Waive uncritical lint errors

- hw/ip/csrng/dv/env/csrng_path_if.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
The error test success rate is barely above 98%.
This PR fixes some failing edge cases and moves the success rate to around 99.8%.
For detailed information about the fixes check out the individual commit messages.
> [csrng/dv] Fix some error test failures

- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/data/hmac_testplan.hjson
- hw/ip/hmac/doc/checklist.md
- hw/ip/hmac/doc/registers.md
- hw/ip/hmac/dv/README.md
Preparation for V2 signoff https://github.com/lowRISC/opentitan/issues/22471.
Here is the document updates.
Please @gdessouky and @ballifatih could take a look at this PR.
Note: I still need to run a regression to confirm some status.
> [hmac/doc] Update docs for V2 signoff

- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_config_pinflip_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Add a minimal sequence to exercise pin flipping, having modified the driver and monitor to support this functionality, along with the other bus configurations.
> [dv,usbdev] Exercise pin flipping

- hw/ip/rv_dm/lint/rv_dm.waiver
Latest tool version flag some more errors but these are all to be expected and it's safe to waive them.
> [rv_dm] Update AscentLint waiver file

- util/dvsim/Regression.py
- util/dvsim/Test.py
- util/dvsim/modes.py
There are some careful notes in the commit messages. This is just meant to be a tidy-up for some of the gnarlier bits of dvsim.
> [dvsim] Simplifications to "mode" handling in dvsim

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_stress_all_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
> This PR builds on the changes from #23116. Only the final 4 commits are new, and will rebased once the first PR is merged in master.
> [hmac,dv] Save & Restore DV cleanups

- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
Expected CRC and checking of actual CRC against the expectation.
Informational reporting of CRC mismatches within the monitor. Scoreboard shall ultimately handle any mismatches.
> [dv,usbdev] Item CRC handling

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_sba_debug_disabled_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
The actual test appears in the final commit, but there are some tidy-ups needed in the previous three. Detailed notes in commit messages.
Fixes #15668.
> [rv_dm,dv] Implement sba_debug_disabled testpoint

- hw/ip/entropy_src/rtl/entropy_src_core.sv
Due to the relocation of the 1-4-bit packer FIFO, the main SM done signal arrived one cycle too early in the single lane mode. This caused the SHA3 process_i signal to go high one cycle too early. This in turn caused the issue that the last word from the precon FIFO is not absorbed properly by SHA3.
This commit fixes this by delaying the main_sm_done signal by 1 cycle in the single lane mode. The ht_error signal has to be delayed by 1 cycle as well to guarantee that the error signal arrives at the same time as the main_sm_done signal.
Resolves #23773
> [entropy_src/rtl] Delay the main_sm_done signal

- hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
- add possibility to use a randomized value of the digest_size in case the command line argument is not passed while calling the test seq. This is necessary as the stress seq cannot pass such argument.
Note: this PR is linked to this issue https://github.com/lowRISC/opentitan/issues/23810
> [hmac,dv] SHA test vec uses arg/rand digest value

- sw/device/silicon_creator/rom/rom.c
1. Double-check the low-power wakeup value.
2. Harden the reset reason double-check logic.
> [rom] Additional hardened checks

- hw/ip/pwm/doc/theory_of_operation.md
- hw/ip/pwm/dv/env/pwm_env_cov.sv
> Pwm clk in doc and fcov fix

- hw/ip/hmac/dv/env/hmac_env_cov.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
This PR is related to this issue https://github.com/lowRISC/opentitan/issues/23245 and is linked with these RTL changes https://github.com/lowRISC/opentitan/issues/23158.
> [hmac,dv] Key swap register test

- sw/device/tests/csrng_edn_concurrency_test.c
Inspecting the waves revealed that the reduced_freq variant of this test sometimes didn't make it across the initial EDN and CSRNG re-config section. The reason is that the RNG inside AST produces raw entropy at a lower rate while the entropy consuming part of AST still consumes a reasonable amount of entropy. As a result, the esfinal FIFO would never fill up and the reconfiguration section would never finish.
To fix this, this commit adds a timeout for the esfinal FIFO: If the FIFO hasn't filled up within 32 ms (under normal conditions this should suffice to fill the FIFO easily), we proceed without a full FIFO.
This fixes lowRISC/OpenTitan#23606.
> [chip-test/sival] Fix csrng_edn_concurrency_reduced_freq

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
No functional change, but it should make the code a little easier to read.
> [dv] Minor tidy-up tweaks to tl_access_sub

- hw/ip/i2c/data/i2c.hjson
> [i2c,dv] Add write-check csr_excl for FMTFIFO/TXFIFO registers

- hw/ip/lc_ctrl/dv/env/lc_ctrl_if.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_base_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv
Detailed notes in commits. This fixes #21268.
> [lc_ctrl,dv] Add more staggering in rma signals

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
This builds upon #23792 but also splits out `pinmux_hw_debug_en_i` configuration. Only the final commit is unique to this PR.
> [rv_dm,dv] Allow pinmux_hw_debug_en_i to be more independent

- hw/ip/entropy_src/rtl/entropy_src_core.sv
If any of the postht, distr or precon FIFOs are non-empty when triggering the conditioner, there is risk of leaving entropy bits tested as part of the current window inside the pipeline instead of absorbing them into the current seed. This would be problematic.
This is related to lowRISC/OpenTitan#21855.
> [entropy_src] Add SVA to ensure FIFOs are empty when triggering SHA

- hw/ip/spi_host/data/spi_host.hjson
This should allow us to close #23490
> [dv + sign-off, spi_host] Bump verif_stage to V2S

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_core_ibex_lockstep_glitch_vseq.sv
This DV only commit extends the `chip_sw_rv_core_ibex_lockstep_glitch` test in such a way that the lockstep enable signal is additionally faulted.
The Ibex lockstep tolerates a fault into the `enable_cmp_q` due to the MuBi encoding and how the lockstep enable RTL is written.
This commit randomly inverts one bit in the MuBi encoded enable signal. The test should behave as before - an alert should be triggered.
Closes #23572.
> [rv_core_ibex,dv] Fault lockstep enable signal

- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- Take the advantage of Save and Restore feature to load a hypothetical context with a large msg_length to test the msg_length_upper register.
- Split the S&R into sub-tasks to make the code a bit easier to read.
Note: code should be slightly change after taking care of this issue https://github.com/lowRISC/opentitan/issues/23562 as the msg_length registers are checked in the vseq but it shouldn't be once the SCB will be able to check the context B.
> [hmac,dv] Test msg_length_upper

- hw/ip/otbn/dv/otbnsim/sim/sim.py
There are some detailed notes in the commit messages, but this is all about trying to get the `otbn_escalate` test to work properly.
> [otbn,dv] Try to improve model's support for RMA requests

- hw/ip/otbn/dv/rig/rig/gens/bad_branch.py
This was supposed to be picking a branch target that would be "bad" for various reasons. In the case that I tweaked, the problem was just that it wasn't a multiple of 4.
This target address is encoded as a 12-bit signed value of 16-bit words, so needs constraining to be within 4k bytes of the current PC.
Fixes #23509.
> [otbn,dv] Fix a bug in random instruction generator

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_jtag_debug_vseq.sv
The bug as introduced by the commit 6611ee4.
Fix #23902
> [dv, rom_e2e] Fix test rom_e2e_jtag_debug_dev

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
Doing so breaks the rv_dm_tap_fsm_rand_reset test because it wants to check all our registers (including late_debug_enable) have their reset values.
> [rv_dm,dv] Don't use late_debug_enable through a CSR if scb disabled

- hw/ip_templates/flash_ctrl/doc/programmers_guide.md
- hw/ip_templates/flash_ctrl/doc/theory_of_operation.md
- hw/top_earlgrey/ip_autogen/flash_ctrl/doc/programmers_guide.md
- hw/top_earlgrey/ip_autogen/flash_ctrl/doc/theory_of_operation.md
Please refer to the commit messages for details.
> [flash/doc] Document controller behavior and address alignment relevant for Earlgrey-PROD 

- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
This PR fixes an edge case for the prediction of the observe FIFO depth. When a new word is being pushed into the observe FIFO while we are in the address phase of reading the observe_fifo_depth register, the prediction will be off by one cycle. The reason for this is that the prediction can't be done while the register is being read, so the prediction has to wait until the register is not busy anymore. This commit adds two additional variables that allow for accurate prediction even in this edge case.
> [entropy_src/dv] Fix edge case for predicting observe FIFO depth

- hw/ip/usbdev/dv/env/seq_lib/usbdev_host_lost_vseq.sv
The `host_lost` bit in usbstat is somewhat superfluous but check it as well as the interrupt signal/status.
> [dv,usbdev] Improve checking in usbdev_host_lost_vseq

- hw/dv/sv/jtag_agent/jtag_monitor.sv
The existing logic didn't actually work if we saw a reset that went away before the next clock edge. If that happened, the monitor would completely miss the reset because we were in the middle of wait_tck().
With this tweaked version, we wait until the first of "reset" and "tck edge", then spot a reset has happened because trst_n is low.
This fixes the `rv_dm_tap_fsm` test for some seeds.
> [jtag,dv] Fix monitor tracking of trst_n

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
Linked to this issue https://github.com/lowRISC/opentitan/issues/23380
> [hmac,dv] Verify idle status register

- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
A few update for GLS simulation.
> [dv,gls] Update signals for gate-level simulation

- hw/dv/sv/csr_utils/csr_utils_pkg.sv
Adding printout to ease tracking csr_spinwait calls. When we get the timeout error we can now see
> [dv, csr_spinwait] debug printout

- hw/ip/aes/dv/env/aes_scoreboard.sv
- hw/ip/aes/dv/env/seq_lib/aes_reseed_vseq.sv
This PR contains a couple of commits to resolve some issues identified in the regression triaging.
This resolves lowRISC/OpenTitan#24052.
> [aes/dv] Fix corner cases in aes_reseed_vseq

- sw/host/opentitanlib/src/image/image.rs
- sw/host/opentitantool/src/command/image.rs
This patch adds code verifying SPX+ signature of OT binary images, when requested. Some refactoring was required to reflect the fact that an image could be signed with either one or two keys.
Tested by successfully running 'opentitantool image manifest verify --spx <rom_ext.bin>'.
> opentitantool: implement spx signature verification

- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv
It seems our DV currently always expects invalid MuBi values in the Flash RMA ack signal to arrive within 3 to 4 clock cycles after sending the request. 3 clock cycles are "spent" for CDC already. Thus, we need to constrain the delay lens for the set_flash_rma_ack() interface to be within 0 to 1 clock cycle.
This resolves lowRISC/OpenTitan#24058.
> [lc_ctrl/dv] Lower max delay for flash_rma_ack in lc_ctrl_sec_mubi test

- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
A bunch of tests are actually failing for simple timeout reason. I took the worst case to compute this new value.
> [kmac,dv] Increase timeouts for some tests

- hw/ip/hmac/dv/hmac_sim_cfg.hjson
- Increase timeouts for some tests still failing some time to time during regression.
> [hmac,dv] Increase timeouts for some tests

- sw/device/tests/spi_host_config_test.c
- sw/host/opentitanlib/src/test_utils/bitbanging/spi.rs
- sw/host/tests/chip/spi_device/src/spi_host_config_test.rs
This PR addresses the comments on this https://github.com/lowRISC/opentitan/pull/23985 PR.
> [Sival, Spi_host] Improve comments on the config test

- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv
When running otf tests with the vendor flash this check isn't valid so in this PR a dependency added in the use_vendor_flash variable.
This PR along with small PR in the foundry is fixing failing seeds of test flash_ctrl_disable.
> [flash/dv] Add dependency in otf_sb when using vendor flash

- hw/dv/sv/jtag_agent/jtag_driver.sv
This task is only being called in a situation where we're enabling tck just afterwards anyway. Simplify things (and avoid it looking like we might disable tck when it's in use) by formalising this.
> [dv,jtag] Simplify tck enable/release in drive_jtag_test_logic_reset

- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_pins_sense_vseq.sv
Extend the sequence to verify more of the pin driving and pin sensing functionality.
> [dv,usbdev] Extend the phy_pins_sense sequence

- hw/ip/rom_ctrl/dv/env/rom_ctrl_env.sv
- hw/ip/rom_ctrl/dv/env/rom_ctrl_env_cfg.sv
Careful notes in the commit messages. Commits 2 and 3 are basically just tidy-ups. Commit 1 should make the test run rather more quickly.
> [rom_ctrl,dv] Tidy-ups in base env cfg

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
In the rv_dm_stress_all test, we might have written to the ndmreset field of dmcontrol in a previous vseq (the smoke vseq). It shouldn't be a problem if that has happened, but we need to clear the pending ndmreset before setting up our own.
> [rv_dm,dv] Clear ndmreset_pending_q at start of ndmreset req vseq

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
This sometimes happens randomly and the RTL doesn't spot the error. But we don't care because the operations are actually equivalent in this situation! Tighten the constraints on the input to avoid forcing the signal like that.
> [otbn,dv] Avoid forcing between add/addc, sub/subb when carry=0

- sw/device/tests/spi_host_config_test.c
- sw/host/opentitanlib/src/test_utils/bitbanging/spi.rs
- sw/host/tests/chip/spi_device/src/spi_host_config_test.rs
This is a backport PR of https://github.com/lowRISC/opentitan/pull/24016
> Backport - [Sival, Spi_host] Improve comments on the config test

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_busy_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_exception_vseq.sv
This should now be a bit quicker and (more importantly) it becomes a bit more obvious what it does.
> [rv_dm,dv] Tidy up cmderr sequence and testpoint

- hw/ip/rv_dm/data/rv_dm_sec_cm_testplan.hjson
Conveniently, these are actually implemented already!
> [rv_dm,dv] Extend description of some sec_cm testpoints

- hw/dv/sv/jtag_agent/jtag_driver.sv
The previous version of this code was assuming that we'd come out of trst_n in FSM state RunTest/IDLE. This *was* the behaviour of the debug module with a previous version of the RTL (which is presumably how this happened). But it's not what is supposed to happen, and it's not what the RTL does any more (since commit 663be282861).
Get things lined up properly.
> [jtag,dv] Correct FSM driving after trst_n

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv
- sw/device/tests/aon_timer_irq_test.c
Flash vseqs - small update for flash control mp region.
aon c code - update timer range to include upper and lower limits.
> [DV] update flash vseq and aon c code file.

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_dmi_failed_op_vseq.sv
This is driven by a coverage hole (where the dap FSM doesn't jump from "Read" or "Write" to "Idle"). I'm not really sure how much this situation could ever matter, but it's not too difficult to exercise so let's just do it.
> [rv_dm,dv] Send and abort a DMI operation

- sw/host/opentitantool/src/command/ecdsa.rs
- sw/host/opentitantool/src/command/spx.rs
Because the OTP creation tool uses python `int` for parsing integers and writing those values into the OTP configuration, some endianness transformations are needed to format key material correctly for OTP configurations.
> [opentitantool] Format `key show` for use in OTP configs

- sw/host/opentitantool/src/command/image.rs
In SPHINCS+ pre-hashed signing mode a properly wrapped hash of the input message is passed to the signer, not the entire message.
Tested on CW310 by enabling SPX signing of the Ti50 image and verifying the image by the ROM_EXT.
> [sphincsplus-rs] fix pre-hashed mode signing

- hw/ip_templates/pwrmgr/data/pwrmgr.hjson.tpl
- hw/ip_templates/pwrmgr/doc/checklist.md
- hw/top_earlgrey/ip_autogen/pwrmgr/data/pwrmgr.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/doc/checklist.md
The justification is added as a comment in #22487.
Fixes #22487
> [doc,pwrmgr] Declare pwrmgr at D3

- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl
- hw/ip/otp_ctrl/doc/checklist.md
See issue #22479 for details. This closes #22479.
> [otp_ctrl] Sign v2.0.0 off at D3

- hw/ip_templates/clkmgr/data/clkmgr.hjson.tpl
- hw/ip_templates/clkmgr/doc/checklist.md
- hw/top_earlgrey/ip_autogen/clkmgr/data/clkmgr.hjson
- hw/top_earlgrey/ip_autogen/clkmgr/doc/checklist.md
The justification is added as a comment in https://github.com/lowRISC/opentitan/issues/22482.
Fixes #22482
> [rtl,clkmgr] Declare clkmgr at D3

- hw/ip_templates/rstmgr/data/rstmgr.hjson.tpl
- hw/ip_templates/rstmgr/doc/checklist.md
- hw/top_earlgrey/ip_autogen/rstmgr/data/rstmgr.hjson
- hw/top_earlgrey/ip_autogen/rstmgr/doc/checklist.md
The justification is added as a comment in https://github.com/lowRISC/opentitan/issues/22481.
Fixes #22481
> [doc,rstmgr] Declare rstmgr at D3

- hw/ip/usbdev/doc/checklist.md
Updated checklist to reflect V2 effort
> [dv,usbdev] Update checklist.md

- hw/dv/sv/jtag_agent/jtag_driver.sv
I came upon the problems that this fixes when I was trying to get a version of the "stress with rand reset" sequence working if it applied resets when things were happening. But I think this change is probably the right thing to do in either situation. Notes on the individual commits.
> [dv,jtag] Improvements in jtag driver

- hw/ip/edn/dv/cov/edn_cov_if.sv
- hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
This is a follow up PR for #24204.
> [edn/dv] Edn cover csrng sts errs

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
If we are under reset, there's no need to check whether alerts are in flight. Return from the task quickly (which avoids us spending ages in post_start).
> [dv] Exit quickly from check_no_fatal_alerts on reset

- hw/dv/sv/dv_base_reg/dv_base_mubi_cov.sv
I strongly suspect that this is working around a VCS tool bug.
> [dv] Manually apply specialisation for mubi32_cov

- hw/ip_templates/pwrmgr/data/pwrmgr_testplan.hjson
- hw/ip_templates/pwrmgr/doc/checklist.md
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/data/pwrmgr_testplan.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/doc/checklist.md
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv
Also mark ALL_TODOS_RESOLVED and a few others in the V3 checklist:
- X_PROP_ANALYSIS_COMPLETED: no issues shown in compilation xprop.log
- FPV_ASSERTIONS_PROVEN_AT_V3, FPV_CODE_COVERAGE_AT_100, and
FPV_COI_COVERAGE_AT_100 do not apply to pwrmgr
- TB_LINT_COMPLETE: no issues shown in dashboards
> [dv,pwrmgr] Remove remaining TODOs

- hw/top_earlgrey/BUILD
- hw/top_earlgrey/dv/env/chip_env_cfg.sv
- rules/opentitan/silicon.bzl
This PR updates earlgrey_1.0.0 with the following PRs that were merged to master:
- #24305
- #24299
These enable a ROM E2E GLS test.
> [earlgrey_1.0.0] cherry pick changes from master to enable ROM E2E GLS test

- hw/ip/rom_ctrl/rtl/rom_ctrl.sv
Detailed notes in commit messages. Fixes #24322.
> [rom_ctrl,dv] Make some assertions terminate, improving coverage

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
This took *ages* to figure out! I think this is the simplest way to see it happen.
> [rv_dm,dv] Hit minor conditional coverage hole for ndmreset signals

- hw/top_earlgrey/dv/env/chip_if.sv
Update some missing signals for gate-level tests.
> [dv, gls] Update ibex PMP signals for gate-level

- hw/dv/sv/jtag_agent/jtag_driver.sv
- hw/top_earlgrey/dv/env/chip_if.sv
- #24261
- #24353
This update only includes changes from CW 33 that have an influence on DV with closed-source models or GLS.
> [earlgrey_1.0.0] Update after CW 33

- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
- sw/device/silicon_creator/manuf/extensions/BUILD.bazel
- sw/device/silicon_creator/manuf/extensions/default_personalize_ext.c
- sw/device/silicon_creator/manuf/extensions/example_personalize_ext.c
Add one more parameter to the hook for accessing flash device state.
> [manuf] Update pre-cert-endorsment perso extension hook

- .github/workflows/private-ci.yml
This commit sends branch name (in case of a push) and the PR title or the latest commit message (in case of a push) to the private CI.
The private CI and then use these information to perform batching and display a more human friendly title in the UI.
> [ci] send more information to the private CI

- .github/workflows/private-ci.yml
> [ci] fix wrong eventName in private CI trigger

- hw/ip/ascon/data/ascon.hjson
- hw/ip/ascon/pre_dv/ascon_tb/README.md
- hw/ip/ascon/pre_dv/ascon_tb/ascon_sim.core
- hw/ip/ascon/pre_dv/ascon_tb/cpp/ascon_tb.cc
- hw/ip/ascon/pre_dv/ascon_tb/rtl/ascon_sim.sv
- hw/ip/ascon/pre_dv/ascon_tb/rtl/ascon_tl_ul_stim.sv
- hw/ip/ascon/pre_dv/ascon_tb/rtl/ascon_tl_ul_stim_pkg.sv
- hw/ip/ascon/rtl/ascon_core.sv
- hw/ip/ascon/rtl/ascon_pkg.sv
- hw/ip/ascon/rtl/ascon_reg_pkg.sv
- hw/ip/ascon/rtl/ascon_reg_top.sv
rebased. This PR adds a basci testbench connected to the TL-UL interface.
Currently a static sequence is sent. The response is also compared to a static sequence. If every response matches, the test is passed. The test is terminated after all messages have been sent/received + a configurable delay to see any post processing.
> [ascon] Basic testbench for TL-UL interface + hwext data register implementation.

- util/dvsim/results_server.py
Use gsutil -m flag to speed up file operations.
> [dvsim] Speed up gsutil operations.

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_self_hash_gls_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/lib/testing/test_framework/ottf_main.c
- sw/device/lib/testing/test_framework/ottf_test_config.h
- sw/device/silicon_creator/rom/e2e/release/BUILD
- sw/device/silicon_creator/rom/e2e/release/rom_e2e_self_hash_test.c
> [earlgrey_1.0.0] Update after CW 34

- sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/BUILD
This enhances the ROM_EXT immutable section tests to also test executing the immutable section with address translation enabled.
> [rom_e2e] enhance ROM_EXT immutable section tests

- sw/device/silicon_creator/lib/drivers/uart.c
- sw/device/silicon_creator/lib/drivers/uart.h
- sw/device/silicon_creator/manuf/lib/flash_info_fields.c
- sw/device/silicon_creator/manuf/lib/flash_info_fields.h
- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/flash_ecc_error_test.c
- sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/BUILD
- sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/immutable_rom_ext_section_test.c
- sw/device/silicon_creator/rom/e2e/release/rom_e2e_self_hash_test.c
- sw/device/silicon_creator/rom/rom.c
- util/design/gen-otp-immutable-rom-ext-json.py
This PR updates `earlgrey_1.0.0` with the following PRs that were merged to master:
- https://github.com/lowRISC/opentitan/pull/24412
- https://github.com/lowRISC/opentitan/pull/24385
- https://github.com/lowRISC/opentitan/issues/24415
- last commit from #24345
> [earlgrey_1.0.0] Update after CW 34 - pt2

- hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv
This should fix an occasional failure in the
rom_ctrl_corrupt_sig_fatal_chk test.
Fixes #24319.
> [rom_ctrl,dv] Avoid an injected FSM error causing a test failure

- hw/ip/usbdev/dv/env/seq_lib/usbdev_av_empty_vseq.sv
Extend the sequence to ensure that a negative transition on the interrupt line is also observed within the sequence.
> [dv,usbdev] Extend av_empty sequence to deassert interrupts

- hw/ip/prim/fpv/vip/prim_fifo_sync_assert_fpv.sv
The old version of these assertions were not quite true, because the under_rst signal (which qualifies wready_o) is only cleared a cycle after we come out of reset. Tweak the assertions to match.
> [prim,fpv] Explicitly delay wready_o assertions by a cycle

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_base_vseq.sv
This PR updates `earlgrey_1.0.0` with the following PRs that were merged to master:
- #24431
> [earlgrey_1.0.0] Update after CW 34 - pt3

- hw/ip/ascon/ascon.core
- hw/ip/ascon/pre_dv/ascon_tb/rtl/ascon_sim.sv
- hw/ip/ascon/pre_dv/ascon_tb/rtl/ascon_tl_ul_stim.sv
- hw/ip/ascon/rtl/ascon.sv
- hw/ip/ascon/rtl/ascon_core.sv
- hw/ip/ascon/rtl/ascon_pkg.sv
- hw/ip/prim/dv/prim_ascon/ascon_model_dpi/ascon_model_dpi.core
- hw/ip/prim/pre_dv/prim_ascon/prim_ascon_duplex_tb/prim_ascon_dublex_tb.core
- hw/ip/prim/pre_dv/prim_ascon/prim_ascon_duplex_tb/rtl/prim_ascon_duplex_tb.sv
- hw/ip/prim/pre_dv/prim_ascon/prim_ascon_round_tb/prim_ascon_round_tb.core
- hw/ip/prim/prim_ascon.core
- hw/ip/prim/rtl/prim_ascon_duplex.sv
This is the first draft of a ascon comportable IP.
It basically instantiates the prim_ascon_duplex module.
There are still a lot of features missing and the TB is very rudimentary.
~~Further this PR is based on (=includes) multiple other PRs:~~
- https://github.com/lowRISC/opentitan/pull/22537
- https://github.com/lowRISC/opentitan/pull/22727
- https://github.com/lowRISC/opentitan/pull/22981 which is based on https://github.com/lowRISC/opentitan/pull/22230
As all needed PRs have been merged, this PR is now ready for reviews.
> Ascon comportable IP: duplex integration

- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
This PR contains two simple commits to fix two issues identified during the TO gap analysis. For details, please refer to the commit messages.
> [kmac/dv] Fix issues identified during TO gap analysis

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_self_hash_gls_vseq.sv
This PR updates `earlgrey_1.0.0` with the following PRs that were merged to master:
- #24445
> [earlgrey_1.0.0] Update after CW 35

- util/lintpy.py
This avoids a DeprecationWarning when running with a recent version of Python.
> [util] Use importlib.metadata in lintpy.py

- hw/ip_templates/flash_ctrl/dv/env/flash_mem_bkdr_util.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_mem_bkdr_util.sv
Hi,
This change is required following the changes of mem_bkdr_util in PR #24447.
> [dv/flash] Adapt flash_mem_bkdr_util to recent changes

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv
Hi,
This PR is fixing some failing seeds of flash_ctrl_invalid_op test when ran in the extending env.
It add the ability for extending env to skip the info2 partition or to skip programming or erasing of RO defined partitions.
The flags used in this PR are disabled by default so it shouldn't affect any existing regressions.
Thanks!
> [dv/flash] Allow invalid_op test to skip special case partitions

- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv
- hw/ip_templates/flash_ctrl/dv/env/flash_mem_bkdr_util.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_ack_consistency_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_evict_vseq.sv
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_mem_bkdr_util.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_invalid_op_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_ack_consistency_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_evict_vseq.sv
- #24406
- #24499
- #24492
- #24486
- #24414
> [earlgrey_1.0.0] Update after CW 36

- sw/device/silicon_creator/lib/drivers/pinmux.c
- sw/device/silicon_creator/lib/drivers/pinmux_unittest.cc
> [rom, rom_ext] Enable pull-up on UART_RX

- sw/device/tests/penetrationtests/firmware/sca/aes_sca.c
- sw/device/tests/penetrationtests/firmware/sca/aes_sca.h
- sw/device/tests/penetrationtests/json/aes_sca_commands.h
This PR consists of two commits:
- Add new AES SCA test
- Cosmetic update of the AES SCA code base to comply with the coding standard
> [pentest] Update and add new AES SCA tests

- hw/ip/prim/fpv/tb/prim_alert_rxtx_bind_fpv.sv
- hw/ip/prim/fpv/vip/prim_alert_rxtx_assert_fpv.sv
See detailed notes in commit messages.
> [prim,fpv] Fix binding for prim_alert_rxtx_fpv

- doc/security/specs/secure_boot/README.md
Elaborate on primary/secondary ROM_EXT boot slot decision by ROM
> Update secure_boot README.md

- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/doc/rescue.md
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/device/silicon_creator/rom_ext/rescue.h
- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/chip/device_id.rs
- sw/host/opentitanlib/src/chip/mod.rs
- sw/host/opentitanlib/src/ownership/rescue.rs
- sw/host/opentitanlib/src/rescue/serial.rs
- sw/host/opentitantool/src/command/rescue.rs
1. Add a mechanism to get OpenTitan's device ID.
2. Add a mechanism to get the contents of the installed owner pages.
3. Add opentitantool commands for the new features.
4. Update rescue documentation.
> [rescue] Extend rescue features

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/otp_ctrl_descrambling_test.c
> [earlgrey_1.0.0,sw/tests] Add OTP descrambling test

- hw/ip/dma/rtl/dma.sv
This PR removes two unused signals that are unused with the memory limit interrupt being removed
> [hw,dma,rtl] Cleanup unused signals

- sw/device/lib/crypto/impl/aes.c
Previously, the hot loop inside otcrypto_aes() would only ever have 2 blocks in flight while the underlying driver function aes_update() as well as the hardware allows up to 3 blocks being in flight:
- Block x-1 can be retrieved from the data output registers by SW.
- Block x   is being processed by HW.
- Block x+1 can already be provided via the data input registers by SW.
Doing this is better for SCA hardening (more concurrency means more background noise) and allows achieving higher throughput.
This is related to lowRISC/OpenTitan#20308.
> [crypto] Let otcrypto_aes() have up to 3 blocks in flight

- SUMMARY.md
- hw/ip/ascon/data/ascon.hjson
- hw/ip/ascon/doc/checklist.md
- hw/ip/ascon/dv/README.md
This adds the checklist for ason to start working on D1
> [ascon] add checklist

- util/dvsim/LauncherFactory.py
- util/dvsim/NcLauncher.py
- util/dvsim/dvsim.py
- util/dvsim/nc_post_cmd.sh
NetworkComputer(NC) now also known as Altair accelerator is a commercial job scheduler tool from Altair/RunTime. Supports launching builds/run using NC for both interactive and non-interactive modes
> Added support for another job scheduler.

- util/get-toolchain.py
just download the archive; don't unpack.
useful when the toolchain is externally managed
in the development environment.
>     [toolchain] add `--download-only` option

- hw/dv/sv/csr_utils/csr_utils_pkg.sv
I broke this task for some pwrmgr tests with commit 5e0f0fe. The problem is that I changed the fork/join_any so that it would complete instantly on a reset and then use "disable fork" to kill the thing that was waiting.
Unfortunately, the thing that got killed might have been in the middle of a csr_rd and killing it doesn't allow the process to clean up properly.
Go back to waiting more carefully but (in a bid to get *some* benefit from the original rewrite) stop a wait between reads more quickly if there is a reset.
> [csr_utils_pkg,dv] Avoid bug on reset in csr_spinwait

- hw/dv/sv/jtag_agent/jtag_if.sv
- hw/ip/otp_ctrl/doc/programmers_guide.md
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_spi_passthrough_vseq.sv
- sw/device/lib/dif/dif_pinmux.c
- sw/device/lib/dif/dif_pinmux.h
- sw/device/lib/testing/BUILD
- sw/device/lib/testing/spi_device_testutils.c
- sw/device/lib/testing/spi_device_testutils.h
- sw/device/lib/testing/spi_host_testutils.c
- sw/device/lib/testing/spi_host_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/power_virus_systemtest.c
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/spi_host_tx_rx_test.c
- sw/device/tests/sim_dv/spi_passthrough_test.c
- #24586
- #24701
- #24577
- #24688
- #24601
> [earlgrey_1.0.0] Update after CW 40

- hw/dv/sv/jtag_agent/jtag_dtm_reg_block.sv
- hw/ip/tlul/adapter_dmi.core
- hw/ip/tlul/generic_dv/env/seq_lib/xbar_base_vseq.sv
- hw/ip/tlul/generic_dv/env/seq_lib/xbar_random_vseq.sv
- hw/ip/tlul/generic_dv/xbar_tests.hjson
- hw/ip/tlul/jtag_dtm.core
- hw/ip/tlul/lint/tlul_adapter_dmi.waiver
- hw/ip/tlul/lint/tlul_jtag_dtm.waiver
- hw/ip/tlul/rtl/tlul_adapter_dmi.sv
- hw/ip/tlul/rtl/tlul_adapter_host.sv
- hw/ip/tlul/rtl/tlul_err_resp.sv
- hw/ip/tlul/rtl/tlul_jtag_dtm.sv
- hw/ip/tlul/rtl/tlul_lc_gate.sv
- hw/ip/tlul/rtl/tlul_socket_1n.sv
- hw/ip/tlul/tlul.core
- hw/ip/uart/dv/env/uart_env.core
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/top_darjeeling/lint/top_darjeeling_lint_cfgs.hjson
This PR syncs all changes from the `tlul` folder to master. The only commit that was left out is https://github.com/lowRISC/opentitan/commit/27a84f007e2d280270c83af31f55edc97ef6c714, which is related to a Darjeeling specific DV config.
> [hw,tlul_*,rtl] Sync TLUL prims to master (integrated_dev to master)

- sw/host/opentitantool/src/command/gpio.rs
Augment the `gpio monitoring` `start` and `read` commands with the ability to also write a vcd file. The `start` and `read` commands do not block or hold the opentitantool interface, so they can be used in conjunction with other opentitantool commands. For example, the `gpio monitoring` `start` and `read` commands can be used with the `tpm i2c` commands to record all of the i2c traffic from hyperdebug and the DUT. The existing `gpio monitoring vcd` command holds the hyperdebug resource until it is finished, so it is currently not possible to sent tpm i2c commands to the DUT using opentitan tool while the `gpio monitoring vcd` is running.
> [opentitantool] Add vcd outfile option to gpio monitor start and read

- hw/ip/uart/data/uart.hjson
- hw/ip/uart/doc/block_diagram.svg
- hw/ip/uart/doc/interfaces.md
- hw/ip/uart/rtl/uart.sv
- hw/ip/uart/rtl/uart_core.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
In this minimal implementation, the UART core asserts iff the TX FIFO fill level is smaller than the configured threshold or the RX FIFO fill level is greater than or equal to the configured threshold, independent of IRQ enablement. The trigger is flopped to avoid CDC issues between different clock domains.
This carries over the changes from the integrated_dev to master. The trigger is not used in Earlgrey.
> [hw,uart,rtl] Implement LSIO trigger (integrated_dev to master)

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
This is a minor tidyup that just fixes some broken links, motivated by some annoying warning messages when I ran dvsim. Much better now :-)
> [chip,dv] Chip testplan tidyup

- hw/top_earlgrey/syn/chip_earlgrey_asic.sdc
- hw/top_earlgrey/syn/ot.sdc_setup.tcl
This PR updates earlgrey_1.0.0 with the following PRs that were merged to master:
- #24221
> [earlgrey_1.0.0] Update after CW 42

- sw/device/lib/dif/BUILD
- sw/device/lib/dif/autogen/dif_mbx_autogen.c
- sw/device/lib/dif/autogen/dif_mbx_autogen.h
- sw/device/lib/dif/autogen/dif_mbx_autogen_unittest.cc
- sw/device/lib/dif/dif_mbx.c
- sw/device/lib/dif/dif_mbx.h
- sw/device/lib/dif/dif_mbx.md
- sw/device/lib/dif/dif_mbx_unittest.cc
- sw/device/lib/testing/BUILD
- sw/device/lib/testing/autogen/isr_testutils.c
- sw/device/lib/testing/autogen/isr_testutils.h
This PR syncs the MBX DIF from `integrated_dev` to `master`. 
This PR depends on https://github.com/lowRISC/opentitan/pull/24437
> [hw,mbx,dif] Sync MBX DIF from integrated_dev to Master 

- hw/top_darjeeling/templates/chiplevel.sv.tpl
- hw/top_darjeeling/templates/toplevel.sv.tpl
This copies over the Darjeeling templates but removes the casing between the different tops.
> [darjeeling] Add Darjeeling chip/toplevel SV template

- sw/device/silicon_creator/rom_ext/defs.bzl
1. Ownership Transfer.
2. Valid DICE chain from CA->UDS->CDI_0->CDI_1.
> [rom_ext] Release ROM_EXT 0.5

- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
- hw/top_earlgrey/rtl/chip_earlgrey_verilator.sv
- hw/top_earlgrey/templates/chiplevel.sv.tpl
Using parameters from package inside ast.
> [ast] using parameters from package inside ast

- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.c
- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty_unittest.cc
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_empty_test.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_min_sec_ver_test.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.h
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_wakeup_test.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
This is a manual cherry-pick of #24247 and some underlying supporting commits to `earlgrey_1.0.0`.
> [Cherry-pick to earlgrey 1.0.0] [rom_ext] Do not process boot_svc request for wakeups

- signing/logs/2024-10-23.md
Note: the release was aborted because a defect was discovered: The
`protect_when_primary` feature does not work as intended.  The defect
will be corrected by https://github.com/lowRISC/opentitan/pull/24879.
> [signing] Publish signing ceremony 2024-10-23

- signing/logs/2024-10-25.md
1. Ceremony documentation.
2. Change owner_key_type to ecdsa.
3. ROM_EXT 0.6 binaries.
> [signing] Publish signing ceremony 2024-10-25

- hw/dv/sv/dv_base_reg/dv_base_reg.sv
Before this change, you could create a mubi-encoded regwen field and the Python code in reggen's access.py would sensibly give it a UVM access value of "RW" (because changing from e.g. Mubi8True to Mubi8False writes some bits and clears other ones).
The lock_lockable_flds method in dv_base_reg.sv hadn't been updated accordingly, and this is supposed to apply the "allow things to be locked" logic.
The change is needed as part of getting the change in #24804 working.
> [dv] Teach dv_base_reg to allow mubi regwen fields

- util/dvsim/LauncherFactory.py
- util/dvsim/LocalLauncher.py
- util/dvsim/LsfLauncher.py
- util/dvsim/NcLauncher.py
- util/dvsim/SgeLauncher.py
- util/dvsim/SlurmLauncher.py
- util/dvsim/dvsim.py
Slurm is an open-source work management tool, similar to IBM LSF. We are slurm internally and extended dvsim with support for that. We factored all the configs out to environment variables to allow a generic use of it.
> [dvsim] Add slurm launcher

- sw/device/silicon_creator/lib/manifest.h
- sw/device/silicon_creator/lib/ownership/datatypes.h
Introduce Integrator Specific Firmware Binding (ISFB) data structures used to implement integrator-device specific binding as well as anti-rollback based on ownership configuration.
Data structures:
1. `manifest_ext_isfb_t`: Integration specific firmware binding manifest extension. Contains anti-rollback strike mask as well as device expecific product expression.
2. `manifest_ext_isfb_erase_t`: ISFB erase policy manifest extension. This extension is used to authorize erasing of the ISFB region. Intended for testing purposes. The implementation will require node-locking for this policy to be effective.
3. `owner_isfb_config`: ISFB owner configuration. Defines the ISFB info flash page configuration as well as its erase policy.
This is part of: …
> [rom_ext] Introduce ISFB data structures.

- .github/workflows/nightly.yml
This PR adds a new nightly Job using GitHub actions, this is meant to be the replacement of the nightly running on azure, but for now it only has the FPGA nightly for SiVal.
> [sival] Add a nightly job on github actions

- hw/ip/aes/doc/theory_of_operation.md
This resolves lowRISC/OpenTitan#24334.
> [aes/doc] Fix a broken reference

- hw/ip/aon_timer/dv/env/aon_timer_env.sv
- hw/ip/aon_timer/dv/env/aon_timer_env_cfg.sv
- hw/ip/aon_timer/dv/env/aon_timer_env_cov.sv
- hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
- hw/ip/aon_timer/dv/env/aon_timer_virtual_sequencer.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_common_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_jump_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_prescaler_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_smoke_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_stress_all_vseq.sv
Moving TB towards declaring functions and constraints as extern to enhance readability
> [aon_timer, dv] Add extern keyword to methods/constraints

- hw/ip/spi_device/dv/env/spi_device_env_pkg.sv
See https://github.com/lowRISC/opentitan/issues/20193#issuecomment-2452097088. This resolves #20193.
> [spi_device/dv] Remove unused variables

- sw/device/tests/BUILD
- sw/device/tests/spi_device_tpm_tx_rx_test.c
This PR updates earlgrey_1.0.0_presilicon with the following PRs that were merged to master:
- https://github.com/lowRISC/opentitan/pull/24928
> [earlgrey_1.0.0_presilicon] Update after CW 44

- sw/device/silicon_creator/rom_ext/doc/ownership.md
Update the ownership transfer documentation.
- Include a diagram of ownership state transitions.
- Add a high-level description of the ownership configuration.
- Describe the uses of the `update_mode`.
- Update struct definitions to reflect the current implementation.
Cherry-pick from: https://github.com/lowRISC/opentitan/pull/24714
> [ownership] Update ownership transfer documentation 

- .github/actions/prepare-env/action.yml
- .github/workflows/ci.yml
- .github/workflows/nightly.yml
> [ci] remove temporary files in prepare-env

- hw/ip/hmac/dv/env/hmac_env.sv
- hw/ip/hmac/dv/env/hmac_env_cfg.sv
- hw/ip/hmac/dv/env/hmac_env_cov.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_back_pressure_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_burst_wr_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_common_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_datapath_stress_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_error_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_long_msg_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_stress_all_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_hmac_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_wipe_secret_vseq.sv
- hw/ip/hmac/dv/tests/hmac_base_test.sv
Edit all the HMAC DV files, to move tasks, functions and constraints and adopt the "extern" SV feature to enhance readability.
> [hmac,dv] Adpot extern method declarations

- hw/ip/hmac/doc/programmers_guide.md
- After this issue #24767 has been raised, and a workaround has been found #24944, the Programmer's Guide should be updated to reflect this.
> [hmac,doc] Update Save and Restore SW guide

- sw/device/lib/crypto/drivers/hmac.c
- Increase the delay before saving the context. This has been changed from 100 to 200 IBEX cycles as issues have been observed in some cases.
- Linked to issue #24767
> [hmac,sw] Fix delay before context save

- hw/top_earlgrey/syn/chip_earlgrey_asic.sdc
This PR updates earlgrey_1.0.0_presilicon with the following PRs that were merged to master:
- #24965
> [earlgrey_1.0.0_presilicon] Update after CW 45 

- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
> [sival,testplans] Update testplans for cpu and alert info tests

- .github/actions/prepare-env/action.yml
- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- azure-pipelines.yml
- ci/bazelisk.sh
- ci/jobs/quick-lint.sh
- ci/scripts/validate_testplans.sh
- hw/lint/sival_testplan_schema.hjson
- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_adc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otp_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rom_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_dm_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- hw/top_earlgrey/data/standalone_sw_testplan.hjson
- util/validate_testplans.py
This PR backport all the GitHub actions updates form master with the objective of enabling the SiVal nighties on the earlgrey_1.0.0 branch.
> [ci] Backport all github actions updates from Master

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/dice_cwt.c
Flesh out the CDI_0/1 generating APIs by the auto-gen CWT templates.
Signed-off-by: Tommy Chiu <tommychiu@google.com>
(cherry picked from commit 1d921f80bfef31e724b64603842a47c4253ca3cb)
> [cherry-pick] manual cherry-pick of #24835 to `earlgrey_1.0.0` branch

- hw/ip/uart/dv/env/seq_lib/uart_intr_vseq.sv
Two tweaks to avoid failures of `uart_intr_vseq`.
When testing RX Timeout does not occur when go close to but not exceeding the timeout, base delays off the last time the timeout was reset rather than a after performing additional CSR reads. Removing the added delay of the CSR reads avoids cases where it is enough to trigger the timeout.
Also, reorder interrupt checking so that pins are checked before CSR reads, seeing as the former are instant and the latter are not. Again, this is to avoid added delay that could allow the timeout to occur due to CSR read delays.
> [uart,dv] Mitigate dly from CSR reads in intr test

- hw/ip/pwm/rtl/pwm_chan.sv
This is equivalent but should be rather easier to read than the trees of ternary operators.
> [pwm,rtl] Make calculation of some _d signals in pwm_chan.sv clearer

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/sram_cp_provision.c
- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
- sw/host/opentitanlib/src/debug/openocd.rs
- sw/host/opentitanlib/src/dif/lc_ctrl.rs
- sw/host/opentitanlib/src/io/jtag.rs
- sw/host/provisioning/cp/BUILD
- sw/host/provisioning/cp/src/main.rs
- sw/host/provisioning/ft/BUILD
- sw/host/provisioning/orchestrator/README.md
- sw/host/provisioning/orchestrator/configs/skus/BUILD
- sw/host/provisioning/orchestrator/configs/skus/sival.hjson
- sw/host/provisioning/orchestrator/data/BUILD
- sw/host/provisioning/orchestrator/data/packages/BUILD
- sw/host/provisioning/orchestrator/data/packages/earlgrey_a1.hjson
- sw/host/provisioning/orchestrator/data/products.hjson
- sw/host/provisioning/orchestrator/src/BUILD
- sw/host/provisioning/orchestrator/src/ca_config.py
- sw/host/provisioning/orchestrator/src/device_id.py
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/src/sku_config.py
- sw/host/provisioning/orchestrator/src/util.py
- sw/host/provisioning/orchestrator/tests/BUILD
- sw/host/provisioning/orchestrator/tests/device_id_test.py
This PR contains:
1. several bug fixes / cosmetic improvements to the CP and FT provisioning flows, and
2. and initial version of the new and improved orchestrator.py provisioning script to support A1 benchtop provisioning flows.
> [provisioning] add initial orchestrator script for benchtop provisioning

- hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_clock_gating_vseq.sv
- hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_random_ramp_vseq.sv
- hw/ip/adc_ctrl/dv/sva/adc_ctrl_bind.sv
- hw/ip/adc_ctrl/dv/sva/adc_ctrl_fsm_sva_if.sv
- hw/ip/adc_ctrl/dv/sva/adc_ctrl_sva.core
- hw/ip/adc_ctrl/dv/sva/adc_ctrl_sva_if.sv
- hw/ip/adc_ctrl/dv/tb.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_adc_ctrl_sleep_debug_cable_wakeup_vseq.sv
- Move SVA related code from tb.sv to adc_ctrl_sva_if.sv.
- Bind adc_ctrl_sva_if for sva only.
- Change module adc_ctrl_fsm_sva to interface adc_ctrl_fsm_sva_if.
- Fix some trivial typos, and remove useless functions.
> [dv,adc_ctrl] Make dv improvements

- sw/device/tests/BUILD
- sw/host/tests/chip/uart/src/uart_baud_rate.rs
Needed a couple of fixes to make it more reliable.
> [sival] Enable UART baud rate test on FPGAs

- util/reggen/fpv_csr.sv.tpl
This PR collects the MuBi REGWEN support from the private integrated repository, since it was not carried across and has been leading to DMA FPV assertions:
Introduce support for REGWEN fields that are specified as MultiBit values.
> [fpv] Support for MuBi REGWEN fields

- util/vendor.py
Update the URLs and filenames following the documentation restructuring.
> [utils/vendor] Update URLs and filenames

- sw/host/provisioning/ft_lib/src/lib.rs
This enhances the E2E perso flow test to verify that UDS cert is not invalid when the ROM_EXT first boots after personalization.
Previously, the test only checked for successful ROM_EXT boot. This change adds a check to ensure that the UDS certificate remains valid during the initial boot.
This address https://github.com/lowRISC/opentitan/issues/25100
> [manuf] Verify ROM_EXT UDS cert after perso

- sw/device/silicon_creator/manuf/base/ft_personalize.c
This adds the check to ensure the `manuf_state_creator` field in the ROM_EXT manifest matches the expected value that will be provisioned into the OTP. The ROM_EXT manifest is located in slot b and is flashed during the second bootstrap. The verification is done before the OTP is provisioned or the bootstrap is disabled, allowing for correction and re-running the personalization flow.
This PR partially addresses #24617
> [manuf] Verify manuf_state_creator consistency between ROM_EXT and OTP

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/sram_cp_provision.c
- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
- sw/host/opentitanlib/src/debug/openocd.rs
- sw/host/opentitanlib/src/dif/lc_ctrl.rs
- sw/host/opentitanlib/src/io/jtag.rs
- sw/host/provisioning/cp/BUILD
- sw/host/provisioning/cp/src/main.rs
- sw/host/provisioning/ft/BUILD
Some bug and cosmetic fixes to the CP/FT provisioning flows were fixed in #25151. This cherry-picks them to the `master` branch.
> [cherry-pick] manual cherry-pick of bug fix commits from #25151

- sw/host/opentitanlib/src/test_utils/bitbanging/i2c.rs
This PR reduces the flakiness seen in tests that use I2C over GPIO bitbanging - namely `i2c_target_test` where this was being used.
Currently, writes to SCL and SDA can be performed within a single GPIO bitbanging sample. This relied on the SDA value being set before the the SCL value, but in reality these changes occur almost simultaneously. Physical characteristics of the FPGA such as e.g. the capacitance on different pins could add delays of a couple of microseconds, causing the SDA variation to appear after the SCL variation. This could cause a valid write (setting SDA high before a rising edge on SCL) to transmit as a 'None' signal, which was causing a lot of flakiness in tests, varying across different FPGAs.
This commit fixes the I2C bitbanging logic to run at half the sampling …
> [i2c, sival] Reduce I2C bitbanging flakiness by separating SDA and SCL pin writes

- sw/device/lib/crypto/data/crypto_testplan.hjson
- sw/device/tests/crypto/rsa_2048_encryption_functest.c
This PR fixes some typos I encountered while reviewing sival testpoints.
> [sival, crypto] Fix some typos

- sw/host/provisioning/orchestrator/src/BUILD
- sw/host/provisioning/orchestrator/src/db.py
- sw/host/provisioning/orchestrator/tests/BUILD
- sw/host/provisioning/orchestrator/tests/db_test.py
Introduce DeviceRecord class to implement a plain ORM interface backed by sqlite.
> [orchestrator] Add database interface.

- .github/workflows/nightly.yml
This is a manual cherry-pick of https://github.com/lowRISC/opentitan/pull/25173
> [Backport, SiVal] Fix branch name when publishing the nightlies report

- .github/workflows/ci.yml
- azure-pipelines.yml
> [ci] Move Verilated Earl Grey tests to GitHub Actions

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sleep_pin_wake_test.c
- sw/host/tests/chip/gpio/BUILD
- sw/host/tests/chip/gpio/src/sleep_pin_wake.rs
This is a manual cherry-pick of https://github.com/lowRISC/opentitan/pull/23472
> Port sleep_pin_wake to SiVal

- hw/ip/lc_ctrl/rtl/lc_ctrl.sv
- hw/ip/prim/lint/prim_ram_1r1w.waiver
- hw/ip/tlul/rtl/tlul_sram_byte.sv
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/ip/ast/rtl/ast.sv
- hw/top_darjeeling/lint/chip_darjeeling_asic.waiver
- hw/top_darjeeling/lint/top_darjeeling.waiver
- hw/top_darjeeling/rtl/autogen/chip_darjeeling_asic.sv
- hw/top_darjeeling/rtl/autogen/chip_darjeeling_cw310.sv
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_darjeeling/templates/chiplevel.sv.tpl
Still needed more, much more....
> [darjeeling,lint] Darjeeling Lint fixes

- sw/device/lib/dif/dif_keymgr.c
- sw/device/lib/dif/dif_keymgr.h
- sw/device/lib/dif/dif_keymgr_unittest.cc
- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/keymgr_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/keymgr_derive_cdi_test.c
- sw/device/tests/keymgr_key_derivation_test.c
- sw/device/tests/penetrationtests/firmware/sca/ibex_sca.c
Cherry-picked commits of #24823 and its bug fixes of #25267.
> Manual backport 24823 to earlgrey 1.0.0

- hw/top_darjeeling/templates/chiplevel.sv.tpl
- hw/top_earlgrey/templates/chiplevel.sv.tpl
This PR removes unused variable definitions from the chip-level template.
> [templates] Remove unused definitions

- hw/top_darjeeling/lint/top_darjeeling.waiver
This PR waives some common errors (similar to Earlgrey).
> [darjeeling,lint] Waive some common errors 

- sw/device/tests/BUILD
This PR:
- Fix the usbdev_aon_wake_reset_test
> [SiVal, usbdev] Fix usbdev tests

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
> [dv,shadow_reg_errors] Test the last shadowed CSR

- sw/host/provisioning/orchestrator/src/BUILD
- sw/host/provisioning/orchestrator/src/db.py
- sw/host/provisioning/orchestrator/src/device_id.py
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/src/sku_config.py
- sw/host/provisioning/orchestrator/tests/db_test.py
- sw/host/provisioning/orchestrator/tests/device_id_test.py
Add database interface to orchestrator.py. The database upsert operation is only executed if the CP and FT stages complete successfully.
> [manuf] Connect db to orchestrator.

- hw/top_darjeeling/templates/toplevel.sv.tpl
- hw/top_earlgrey/templates/toplevel.sv.tpl
- util/topgen/templates/toplevel_pkg.sv.tpl
Separately render the AsyncOn config for outgoing alerts in the top_pkg file instead of referencing the nonexisting alert_handler package.
> [topgen] Render AsyncOn for outgoing alerts

- sw/host/provisioning/orchestrator/src/BUILD
> [manuf] Add db.py to orchestrator deps

- .github/workflows/nightly.yml
- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/cryptotest.bzl
- sw/device/tests/crypto/cryptotest/firmware/BUILD
Manual backport of #25438 to earlgrey_1.0.0
CC: @luismarques this should start running some of the cryptotests in nightly.
> Backport #25438 to earlgrey_1.0.0

- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/uart/console.rs
The serial console library suffers from the need not to consume any additional bytes, if one of the regular expressions matches, for which we have found no better solution than to read a single byte at a time.
At Google, we often use `opentitantool console` and pipe the output into other test scripts (which may do regular expressions).  In such cases, the opentitanlib is not performing any regular expression matching, but it still reading a single byte at a time, and writing each byte using a separate `write()` operating system call.  This is highly inefficient, when the data goes through anonymous pipes, and is often further processed just one or a few bytes at a time by other processes.
This PR modifies the logic in `uart/console.rs` to recognize the case of there not being any regular …
> [opentitantool] Multi-byte read()/write() in serial console

- hw/dv/dpi/jtagdpi/jtagdpi.c
Clients performing a shift operation with data readback will be sending a sequence of commands that toggle TCK, providing the data to shift in, interleaved with read commands to sample the data shifted out. In the current implementation where a single command is processed on each jtagdpi tick, this leads to an uneven TCK duty cycle (i.e. 3 jtagdpi ticks per TCK cycle) whenever data read commands are present.
The JTAG spec dictates that TDO values change on the falling edge of TCK and so should be sampled around the rising edge. The command processing is changed to support a "lookahead" to attempt to pull a read command back to the same jtagdpi tick where a TCK rising edge command is handled. With this lookahead, a client that does (TCK falling edge, TCK rising edge, read TDO) will …
> [dv/dpi] jtagdpi lookahead for 'R' on TCK posedge

- hw/top_darjeeling/ip/sensor_ctrl/sensor_ctrl.core
- hw/top_darjeeling/ip/soc_proxy/soc_proxy.core
Cleanup for upgrade to fusesoc 2.4
> [corefiles] Don't specify files if not needed

- sw/device/silicon_creator/manuf/keys/sival/ca_config.json
- sw/host/provisioning/ft/BUILD
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/ft_lib/src/lib.rs
Some FT provisioning flows do not make use of the extension CA, so we make it an optional argument.
> [manuf] enable extension CA to be optional

- hw/top_darjeeling/lint/top_darjeeling.vbw
- hw/top_darjeeling/physical_pads.core
Ensure they are compliant with fusesoc 2.4
> [corefiles] Fix 2 corefiles for Darjeeling

- .github/workflows/nightly.yml
- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/cryptotest.bzl
Please review by commit for easier comprehension.
> [Sival, Nightly] Add a job to run the slow crypto tests

- hw/ip/hmac/dv/README.md
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
- refers to issue https://github.com/lowRISC/opentitan/issues/24693
- these cleans have been discussed internally and doesn't make sense to keep them all. The remaining ones are linked to an open issue.
> [hmac] Clean some TODO for V3

- sw/device/tests/crypto/cryptotest/cryptotest.bzl
- sw/device/tests/crypto/cryptotest/firmware/BUILD
This is a manual backport of https://github.com/lowRISC/opentitan/pull/24439
> Backport 24439  to earlgrey_1.0.0

- hw/ip/pwm/README.md
- hw/ip/pwm/data/pwm.hjson
- hw/ip/pwm/doc/registers.md
- hw/ip/pwm/doc/theory_of_operation.md
- hw/ip/pwm/dv/README.md
- hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_heartbeat_wrap_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_rand_output_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_smoke_vseq.sv
- sw/device/lib/dif/dif_pwm.c
- sw/device/lib/dif/dif_pwm.h
- sw/device/tests/sleep_pwm_pulses_test.c
This PR collects a number of small, hopefully uncontentious corrections and modifications to the documentation, DIF and DV relating to PWM. These have been identified in the push towards D3.
> [docs,dv,pwm] Docs, DIF and DV corrections for PWM

- .github/actions/publish-bazel-test-results/action.yml
- .github/workflows/nightly.yml
- apt-requirements.txt
This is a manual backport of https://github.com/lowRISC/opentitan/pull/25415
> Backport 25415 to earlgrey 1.0.0

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
Updating the aes_testplan.json file with bazel targets for Aes_interrupt_encryption_Test
Adding @jwnrt as reviewer
> Added bazel target for aes_interrupt_encryption

- hw/ip/prim/rtl/prim_sha2.sv
Related to issue #24767
- Listen to msg_feed_complete when in FifoLoadFromFifo state to move into FifoIdle state.
- And latch digest_on_blk when it happens in FifoLoadFromFifo state.
> [hmac,rtl] Fix hang after stop #24767

- hw/ip/pwm/dv/pwm_sim_cfg.hjson
This should still give a reasonable confidence, but should complete rather faster.
> [pwm,dv] Lower some reseed counts

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_common_vseq.sv
Previously, fault injections on the FIFO counters inside the u_tlul_adapter_sram modules were disabled as 'Xs were seen throughout the entire module.
In lowRISC/opentitan#23659, the FIFO storage was randomized avoiding this behavior. This commit applies the same technique to the sram_ctrl sec_cm test.
> [sram_ctrl,dv] Enable sec_cm FI tests for tlul_adapter_sram FIFOs

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
Enable pipeline stages for timing reasons.
> [darjeeling,ibex] Enable pipelining on Ibex

- hw/ip/rom_ctrl/dv/env/rom_ctrl_env.sv
- hw/ip/rom_ctrl/dv/env/rom_ctrl_env_cfg.sv
- hw/ip/rom_ctrl/dv/env/rom_ctrl_env_cov.sv
- hw/ip/rom_ctrl/dv/env/rom_ctrl_prim_ral_pkg.sv
- hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_common_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_kmac_err_chk_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_smoke_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_stress_all_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_throughput_vseq.sv
Introduced extern method for declaring members of a class for better readibility
> [rom_ctrl, dv] Improvements for V3

- hw/ip/tlul/rtl/tlul_sram_byte.sv
As been shown in the coverage report, the condition removed in this commit cannot be reached. To cover this coverage hole, remove it and add an assertion. A detailed reasoning can be found in the assertion description.
Closes lowRISC/opentitan#25771
> [sram_ctrl,rtl] Removal of unnecessary condition

- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_darjeeling/templates/toplevel.sv.tpl
- hw/top_earlgrey/templates/toplevel.sv.tpl
- util/topgen/templates/toplevel_pkg.sv.tpl
Some issues where found during the integration that where introduced in previous commits. Please look at the individual commits.
> Fix SV templates

- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/dv_base_reg/dv_base_reg.sv
- hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
This PR depends on https://github.com/lowRISC/opentitan/pull/25787
The first commit will disappear after #25787 is merged on master
> Cip base scoreboard intr state check

- hw/ip/pwm/dv/env/pwm_scoreboard.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
Collect coverage for low power mode.
Fix a couple of build warnings (functions enabling tasks).
> [dv,pwm] Low power coverage

- hw/dv/sv/sim_sram/sim_sram.sv
Both modules have missing unused connections, add them
> [sim_sram] Fix connections to TLUL adapter and SRAM

- hw/ip/dma/rtl/dma_pkg.sv
Downstream interface changed, lets adapt that.
> [hw,dma,rtl] Change system port metadata to 3

- hw/ip/otp_ctrl/data/earlgrey_skus/sival/keys/BUILD
- rules/opentitan/keyutils.bzl
- rules/signing.bzl
- sw/device/silicon_creator/lib/ownership/keys/dummy/BUILD
- sw/device/silicon_creator/lib/ownership/keys/fake/BUILD
- sw/device/silicon_creator/lib/ownership/test_owner.c
- sw/device/silicon_creator/rom/e2e/sigverify_spx/BUILD
- sw/device/silicon_creator/rom/keys/fake/ecdsa/BUILD
- sw/device/silicon_creator/rom/keys/fake/otp/BUILD
- sw/device/silicon_creator/rom/keys/fake/spx/BUILD
- sw/device/silicon_creator/rom/keys/real/spx/BUILD
- sw/device/silicon_creator/rom/keys/unauthorized/ecdsa/BUILD
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/opentitantool/src/command/image.rs
- sw/host/opentitantool/src/command/spx.rs
1. Configure fake spx `prod_key_1` to use prehashed mode.
2. Add a test that signs a binary with `prod_key_1` and verifies that
the binary boots.
This PR depends on #25871.  You need only review the last commit.
> [rom] Add a test to check sphincs+ PreHashedSha256 verification 

- hw/ip/spi_host/dv/sva/spi_host_data_stable_sva.sv
Previous SVA check had a race condition. The change simplifies the whole check and has been regressed against VCS and Xcelium
> [spi_host, dv] data stable SVA check fix

- hw/vendor/lowrisc_ibex.lock.hjson
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_id_stage.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_register_file_fpga.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_tracer.sv
To get the latest changes and lint fixes.
> [ibex] Revendor Ibex

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- rename as intr_test is a register name, and this register is WO. This is a follow-up of a previous PR #25903.
> [hmac,dv] Rename intr_test to intr_test_rename

- sw/host/provisioning/ft_lib/src/lib.rs
THe FT individualization firmware is loaded over the RISC-V JTAG TAP into SRAM. After loading the firmware, we now switch back to the LC TAP in case we experience any OTP pogramming errors. This makes it easier to debug the LC state.
> [manuf] switch back to LC TAP after loading individ FW

- hw/top_darjeeling/rtl/top_pkg.sv
To give one bit more space for internal use.
> [darjeeling] User 28 user bits in Darjeeling

- hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
Now the RTL has been fix and resets the internal prescale count the TB removes all the backdoor reads it had to access the internal RTL counter.
> [aon_timer, dv] Update TB to match RTL behavior

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/xbar_main.hjson
- hw/top_darjeeling/ip/xbar_main/data/autogen/xbar_main.gen.hjson
- hw/top_darjeeling/ip/xbar_main/rtl/autogen/xbar_main.sv
This was found while tightening topgen validation.
> [top,darjeeling] Fix typo in xbar_main.hjson

- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/hmac_endianness_test.c
Signed-off-by: Ramesh Prakash <rprakas@google.com>
Add HMAC endian test as per chip_hmac_testplan.hjson
> [sival/hmac] Add Hmac Endian Test

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- util/design/gen-otp-img.py
- util/design/gen-otp-mmap.py
> [tools,otp] Make some arguments required

- util/raclgen/lib.py
This addresses the discussion in #26096 and also relates to #25690.
> [RACL] Add RACL configuration checks

- sw/device/silicon_creator/lib/cert/dice_chain.c
This change relaxes some non-critical hardened checks to save space. Related to #26060
If any of these checks are skipped by glitching, the device would either get the old DICE cert chain unrelated to current identity, corrupted chain that won't verify, or the correct one. Attackers will not have any gain in all these cases.
* Cert signing are still kept hardened as before, ensuring the device won't sign anything unexpected.
* Key ladder stepping
* Key slot cleanup routine to prevent leakage.
* Memory / Index boundary checks for memory safety.
> [sw] Relax non-critical dice chain hardened checks

- hw/dv/sv/tl_agent/tl_host_driver.sv
- hw/dv/sv/tl_agent/tl_monitor.sv
This is actually motivated by wanting to make some changes that generalise the code a bit. But I started by adding some comments that documented how everything works. The clock management, in particular, is quite hairy. Now hopefully it's a bit more obvious how everything works together.
> [tl,dv] Lots of tidy-ups in tl_host_driver.sv

- hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl.sv
Assert that all outputs have known data.
> [hw,soc_dbg_ctrl,rtl] Ensure that all outputs have known data

- hw/ip/mbx/rtl/mbx.sv
Assert that all outputs have known data.
> [hw,mbx,rtl] Ensure that all outputs have known data

- hw/ip/dma/rtl/dma.sv
Assert that all outputs have known data.
> [hw,dma,rtl] Ensure that all outputs have known data

- util/topgen/merge.py
Properly add the incoming interrupts with the correct fields to the top interrupt field.
> [topgen] Correctly amend incoming interrupts

- hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
- Reduce a_valid_delay_max and a_ready_delay_max to 1
- Force wr_mask to always send all bytes
> [hmac,dv] Optimize TLUL trans to reduce sim time

- hw/ip/otp_ctrl/doc/programmers_guide.md
This is manual cherry-pick of #26188 into the `earlgrey_1.0.0` branch.
> Manual backport 26188 to earlgrey 1.0.0

- sw/device/info_sections.ld
- sw/device/lib/runtime/log.h
- sw/device/lib/testing/test_framework/ottf_common.ld
- sw/device/silicon_creator/lib/base/static_critical_boot_measurements.c
- sw/device/silicon_creator/lib/base/static_critical_epmp_state.c
- sw/device/silicon_creator/lib/base/static_critical_sec_mmio.c
- sw/device/silicon_creator/lib/base/static_critical_version.c
- sw/device/silicon_creator/lib/manifest_def.c
- sw/device/silicon_creator/manuf/lib/sram_program.ld
- util/device_sw_utils/extract_sw_logs.py
Includes
* #25596
* #25621
No merge conflicts is encountered during cherry pick.
> Cherry-pick to earlgrey_1.0.0: LLD-related commits #25596 #25621

- hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
- hw/ip/pattgen/dv/env/seq_lib/pattgen_base_vseq.sv
These fixes help run the DV under VCS.
> Pattgen dv

- hw/ip_templates/ac_range_check/data/ac_range_check_testplan.hjson
- hw/top_darjeeling/ip_autogen/ac_range_check/data/ac_range_check_testplan.hjson
This PR will be continuously updated with new tests.
> [hw,ac_range_check,doc] Add initial testplan

- hw/ip/aon_timer/dv/env/aon_timer_intr_timed_regs.sv
It's possible for an interrupt value to be modified via:
- count > threshold
- intr_state/intr_test write
If there's an interrupt due to count > threshold, and by the time it synchronises to the sys clock happens to be a write to intr_state clearing the interrupt, then the intr_state write wins. Due to the above, the TB needs to remove the `count > threshold` prediction out of the timed queue to avoid any false mismatch when an interrupt value is predicted due to both conditions.
> [dv, aon_timer] simultaneous interrupt prediction fix

- SUMMARY.md
- hw/top/README.md
- hw/top/defs.bzl
This adds much needed documentation on the top selection mechanism.
> Document //hw/top

- hw/ip/rom_ctrl/util/scramble_image.py
* SRAM nonce typo fix
* Support nonce widths larger than 64 bits for scrambling SRAM images
> ROM scrambling image script fixes

- sw/device/tests/BUILD
- sw/device/tests/clkmgr_jitter_test.c
> [tests] port clkmgr_jitter_test to devicetables

- sw/host/opentitanlib/src/transport/hyperdebug/dfu.rs
Updating firmware involves resetting HyperDebug to jump into a DFU bootloader, and back to the main firmware.  Previously, we changed opentitantool to allow more than one second for the jump from DFU to main firmware, to allow for various cases in which the USB enumeration could take longer.
Recently, I noticed a case where one second was not enough for jumping from the old firmware to DFU bootloader.  It happened that another USB device misbehaving on the bus seemed to cause the Linux kernel to take longer to get around to recognize the "new" DFU device on the bus. (This misbehaving USB device was OpenTitan, which had abruptbly been put under reset, as HyperDebug prepared to update firmware, and stopped driving the OpenTitan POR signal, leaving it with a 1Mohm pulldown.)
This patch …
> [opentitantool] Make HyperDebug firmware upgrading more robust

- util/dvsim/LocalLauncher.py
- util/dvsim/Scheduler.py
Fix a bug in the reschedule strategy and provide a reschedule count to make it more visible.
> [dvsim] fix bug in busy launcher reschedule strategy

- hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl
- hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv
> [ac_range_check/rtl] Fix clearing of `log_status`

- hw/dv/sv/alert_esc_agent/alert_monitor.sv
- hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv
In alert_monitor we got ping_thread() and alert_thread()
running together in parallel. If alert happened and it
stays for multiple cycles even after completing itself
and meanwhile a ping happens and we are in the middle of
ping handshake then the chances are higher to fail checks
in cip_base_scoreboard. Because maybe ping can timeout
as it didn't receive ack or it is in the middle of its
handshake phases and scoreboard doesn't knows about that
([solved in this PR](https://github.com/lowRISC/opentitan/pull/26138)).
For this particular PR, we wait in the ping_thread for
existing alert completion if it happens before ping. Due
to that won't get ourselves into the ping wait timeout
thread that waits to finish the ping handshake in 32
cycles.
Merge …
> [alert_handler, dv] Ping happened after alert

- util/reggen/ip_block.py
- util/topgen.py
> [security,check_regwen] Add regwen countermeasure check

- hw/ip/pattgen/README.md
This now has a more careful feature list, and describes each behaviour that I could extract from reading the implementation RTL.
> [pattgen,doc] Fill out core documentation

- sw/host/hsmtool/src/util/attribute/attr.rs
The Luna HSM PCKS#11 interface does not mark the CKA_VALUE attribute as AttributeInfo::Sensitive even if the object has the CKA_SENSITIVE attribute set to true. This results in the HSM throwing and error when attempting to read the value in the `AttributeMap::from_object` method.
The solution is to explicitly check the CKA_SENSITIVE value before attempting to read CKA_VALUE.
> [hsmtool] Check sensitive attribute before reading AttributeType::Value

- hw/dv/sv/dv_lib/dv_base_virtual_sequencer.sv
Included new functions to register/load a specialized sequencer to run a sub-sequence into the main virtual sequences.
> [dv][tb][improvement] - dv_base_virtual_sequencer improvement

- hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
Short PR just removing unused variables
> [dv, aon_timer] SCB unused variable cleanup

- hw/ip_templates/ac_range_check/dv/env/ac_range_check_env_cfg.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env_cfg.sv
- Set tl_intg_alert_fields and shadow_update_err_status_fields queues
> [ac_range_check,dv] Add alert registers to env_cfg

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_darjeeling/templates/toplevel.sv.tpl
To keep the existing behavior of Darjeeling.
> [darjeeling] Disable late debug / enable "early" debug

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/template.h
- sw/device/silicon_creator/lib/cert/tpm.c
- sw/host/ot_certs/src/codegen.rs
Manual cherrypick of:
* #26454
> Cherrypick to earlgrey_1.0.0: #26454 [sw,ot_certs] Add X509 setter helper for automatic size assertion

- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/rom_ext/e2e/attestation/BUILD
- sw/device/silicon_creator/rom_ext/e2e/attestation/print_certs.c
- sw/host/opentitanlib/src/image/image.rs
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/tests/attestation/BUILD
- sw/host/tests/attestation/attestation_test.rs
- third_party/rust/Cargo.toml
This PR is a manual cherry-pick of #25076.
Examine the attestation certificates and check the measurements published in the DiceTcbInfo extensions.
Report the DICE measurements in big-endian order.
Check the key IDs reported by the DICE certs.
> Cherry-pick to master: [rom_ext_e2e] Check the attestation certificates 

- util/uvmdvgen/README.md
> [tool,doc] Fix path to uvmdvgen in README file

- hw/ip/aon_timer/dv/README.md
- hw/ip/aon_timer/dv/doc/domains.svg
WIP: there's some missing covergroups/coverpoints not listed
> Aon timer tb docs upgrade

- sw/device/tests/BUILD
- sw/device/tests/sram_ctrl_scrambled_access_test.c
With backdoor access fixed this is now an easy port.
Fix #26235
> [multitop] port sram_ctrl_scrambled_access_test to dt

- hw/dv/dpi/common/tcp_server/tcp_server.c
Don't go into the blocking tcp_buffer_put_byte if the buffer is full.
> [jtagdpi] Fix hanging put byte

- hw/top_darjeeling/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/sleep_pin_mio_dio_val_test.c
- toolchain/BUILD
Fix #26233 
With DT, MIO & DIO handling can also be merged.
> [multitop] port sleep_pin_mio_dio_val_test to darjeeling

- hw/dv/sv/dv_base_reg/dv_base_mem.sv
Since I was looking at this file anyway, I reformatted things to use out-of-block definitions, wrote a documentation comment explaining a magic override and then got rid of an unnecessary copied field.
> [dv] Minor tidy-ups to dv_base_mem.sv

- hw/ip_templates/racl_ctrl/data/racl_ctrl.hjson.tpl
- hw/ip_templates/racl_ctrl/rtl/racl_ctrl.sv.tpl
- hw/top_darjeeling/ip_autogen/racl_ctrl/data/racl_ctrl.hjson
- hw/top_darjeeling/ip_autogen/racl_ctrl/rtl/racl_ctrl_reg_pkg.sv
- util/topgen.py
This PR allows different racl groups to have a different number of racl policies.
> [RACL] Minor fixes for multiple racl groups

- sw/device/lib/testing/clkmgr_testutils.h
Sampling the CLK_HINTS_STATUS register of the clkmgr after writing to CLK_HINTS risks sampling prematurely because of the clock domain crossings that occur.
For Earl Grey the clkmgr register interface operates on a clock that is circa 4 times slower than the software-hintable clocks and this led to test failures of chip_sw_aes_idle for some seeds (clock ratios and phase relationships) in DV simulation.
Introducing even a one microsecond delay before sampling runs the risk of a block such as AES going idle before the sampling occurs, leading to other spurious test failures. A delay of the order of 0.1-0.5 microseconds is required on Earl Grey clocks and this is achieved by introducing a logically-redundant register read, but the result of this read also serves to provide an additional …
> [testutils,clkmgr] Slightly delay sampling of clk_hints_status

- sw/host/provisioning/ft/BUILD
- sw/host/provisioning/orchestrator/README.md
- sw/host/provisioning/orchestrator/configs/skus/BUILD
- sw/host/provisioning/orchestrator/configs/skus/sival.hjson
- sw/host/provisioning/orchestrator/data/BUILD
- sw/host/provisioning/orchestrator/data/packages/BUILD
- sw/host/provisioning/orchestrator/data/packages/earlgrey_a1.hjson
- sw/host/provisioning/orchestrator/data/products.hjson
- sw/host/provisioning/orchestrator/src/BUILD
- sw/host/provisioning/orchestrator/src/ca_config.py
- sw/host/provisioning/orchestrator/src/device_id.py
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/src/sku_config.py
- sw/host/provisioning/orchestrator/src/util.py
- sw/host/provisioning/orchestrator/tests/BUILD
- sw/host/provisioning/orchestrator/tests/device_id_test.py
This is a manual cherry-pick of #25151 from the `earlgrey_1.0.0` to the `master` branch. This PR contains initial provisioning tooling.
> [cherry-pick] manual cherry-pick of #25151 to `master` branch

- hw/Makefile
Refer to #26639 for justification
Fixes #26639
> [hw,Makefile] Stop generating RAL packages

- sw/host/hsmtool/src/commands/ecdsa/export.rs
- sw/host/hsmtool/src/commands/ecdsa/import.rs
- sw/host/hsmtool/src/commands/ecdsa/sign.rs
- sw/host/hsmtool/src/commands/ecdsa/verify.rs
- sw/host/hsmtool/src/commands/rsa/decrypt.rs
- sw/host/hsmtool/src/commands/rsa/encrypt.rs
- sw/host/hsmtool/src/commands/rsa/export.rs
- sw/host/hsmtool/src/commands/rsa/import.rs
- sw/host/hsmtool/src/commands/rsa/sign.rs
- sw/host/hsmtool/src/commands/rsa/verify.rs
- sw/host/hsmtool/src/commands/spx/sign.rs
- sw/host/hsmtool/src/commands/spx/verify.rs
- sw/host/hsmtool/src/util/helper.rs
- sw/host/hsmtool/src/util/key/ecdsa.rs
- sw/host/hsmtool/src/util/key/rsa.rs
Replace them with Rust std equivalent.
> [hsmtool] remove read/write_file helper

- hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
These changes ensure more robust modelling of interrupts for aon_timer and build on top of the alternating VSEQ PR #26465 
Only the last commit is unique to this PR.
> Aon timer suddenly disabling counter scb support

- hw/ip/tlul/rtl/tlul_request_loopback.sv
Follow up from https://github.com/lowRISC/opentitan/pull/26660
> [hw,tlul_request_loopback,rtl] Fix typos in commments

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/cdi_1.hjson
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/dice.h
- sw/device/silicon_creator/lib/cert/dice_chain.c
- sw/device/silicon_creator/lib/cert/dice_chain.h
- sw/device/silicon_creator/lib/cert/dice_cwt.c
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
This is a manual cherrypick of
* #26498
* #26564
> Cherrypick to master: [dice,cwt] Measure Owner SW domain in CDI 1 mode field #26498 #26564

- util/dvsim/dvsim.py
- Add possibility to invoke "-fs" instead of "--fixed-seed" as a command line argument.
> [dvsim] Add -fs option for --fixed-seed

- hw/ip_templates/ac_range_check/dv/env/ac_range_check_scoreboard.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scoreboard.sv
- pass directly the act_tl_filt item as argument of compare_tl_a_chan instead of pushing it through a queue.
> [ac_range_check,dv] Simplify compare_tl_a_chan task

- hw/ip/rom_ctrl/util/gen_vivado_mem_image.py
Although the internal operations of UpdateMEM are a black box, we can surmise from its documentation that it likely has a complexity related to the number of both the data and address values in the generated MEM file, though it is not clear what dominates runtime. The [UpdateMEM documentation](https://docs.amd.com/r/2024.1-English/ug1580-updatemem/Bit-Lane-Definitions-Memory-Device-Usage) does suggest however that UpdateMEM will check for violations in the MEM file, which will scale with address count.
Currently, when generating an UpdateMEM-compatible MEM file for the ROM, we emit an address for each individual ROM word (unlike the OTP, which is one contiguous block). This is despite the fact that, for the majority of widths, the number of characters per word will be such that data is …
> [fpga,rom] Speed up ROM splicing by omitting contiguous addresses

- sw/device/silicon_creator/manuf/base/ft_personalize.c
The `flash_ctrl_info_write()` function requires the data to be word-aligned because the `read32()` used in the function (`flash_ctrl_info_write()` ->  `write()` -> `fifo_write()` -> `read32()`) assumes the `const void* ptr` passed to the function must be word-aligned. However, the `next_cert` pointer may not always be word-aligned since the size of the cert block is not necessarily word-aligned.
This commit addresses the issue by introducing a word-aligned buffer to hold the cert data, ensuring proper alignment for the data.
> [manuf] Align cert data before writing to flash info

- rules/manifest.bzl
- sw/device/silicon_creator/rom_ext/e2e/isfb/BUILD
- sw/host/opentitanlib/src/image/image.rs
- sw/host/opentitanlib/src/image/manifest.rs
- sw/host/opentitanlib/src/image/manifest_def.rs
- sw/host/opentitanlib/src/image/manifest_ext.rs
- sw/host/opentitanlib/src/image/testdata/manifest.hjson
- sw/host/opentitanlib/src/image/testdata/manifest_ext.hjson
- sw/host/opentitantool/src/command/image.rs
This is a manual cherry-pick of #24882 and #25045.
> Cherry-pick to earlgrey_1.0.0: [opentitantool] Add ISFB manifest extensions. 

- hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
- This fix is there to solve issue #26737
> [dv,rtl] Solve build warn from tlul_rsp_intg_gen

- hw/dv/sv/cip_lib/seq_lib/cip_tl_seq_item.sv
- hw/dv/sv/tl_agent/seq_lib/tl_host_base_seq.sv
- hw/dv/sv/tl_agent/tl_agent_cov.sv
- hw/dv/sv/tl_agent/tl_host_driver.sv
- hw/dv/sv/tl_agent/tl_seq_item.sv
These are inspired by another change that I want to make (not in this PR) that groups together these sequence items a bit more. The first step of doing that was to properly document and understand the existing code. This took quite some time!
This PR is the result, and I hope that it makes everything rather clearer.
> [tl,dv] Lots of tidy-ups in tl_seq_item

- hw/ip/aon_timer/dv/aon_timer_sim_cfg.hjson
Increasing the number of tests in the smoke regression aiming to catch issues in the future before they make it to master.
> [dv, aon_timer] Increase number of tests for smoke regression

- hw/dv/sv/alert_esc_agent/alert_esc_agent_cfg.sv
- hw/dv/sv/alert_esc_agent/alert_esc_base_driver.sv
- hw/dv/sv/alert_esc_agent/alert_esc_if.sv
- hw/dv/sv/alert_esc_agent/alert_monitor.sv
- hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv
- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_kmac_err_chk_vseq.sv
This changes are meant to allow robust driving and sampling for alerts and pings.
> Alert ping dv fixes

- hw/ip/aon_timer/README.md
This PR removes a TODO item from the README doc as suggested in issue #22632
> [doc, aon_timer] Removing TODO in README

- hw/ip/aon_timer/aon_timer.core
- hw/ip/aon_timer/lint/aon_timer.waiver
Removes stale lint waiver as suggested in #22632
> [dd, aon_timer] Removing stale lint waiver

- sw/device/tests/BUILD
Add Darjeeling sim_dv as a valid target for a couple of simple tests.
> [aon,icache] Add Darjeeling targets

- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- Need to add processes for some forks with join to have a better control on the spawned processes in case of a reset. This was causing an error for some seeds of hmac_stress_all_with_rand_reset test.
> [hmac,dv] Kill processes in case of reset

- hw/ip_templates/ac_range_check/data/ac_range_check_testplan.hjson
- hw/top_darjeeling/ip_autogen/ac_range_check/data/ac_range_check_testplan.hjson
> [ac_range_check,dv] Add precisons to the testplan

- hw/dv/sv/alert_esc_agent/alert_esc_agent_cfg.sv
- hw/dv/sv/alert_esc_agent/alert_monitor.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
This is still WIP.
This PR aims to sort out ping/alert conflicts not well handled in our models currently.
> Alert and ping fixes

- hw/ip/aon_timer/data/aon_timer.hjson
Still WIP - Do not merge yet. Ready for when V3 issue #22663  is finalised
> [dv, aon_timer] bump verif stage to V3

- hw/dv/sv/alert_esc_agent/alert_esc_agent.sv
- hw/dv/sv/alert_esc_agent/alert_esc_agent_cfg.sv
- hw/dv/sv/alert_esc_agent/alert_esc_agent_cov.sv
- hw/dv/sv/alert_esc_agent/alert_esc_base_driver.sv
- hw/dv/sv/alert_esc_agent/alert_esc_base_monitor.sv
- hw/dv/sv/alert_esc_agent/alert_esc_seq_item.sv
- hw/dv/sv/alert_esc_agent/alert_esc_sequencer.sv
- hw/dv/sv/alert_esc_agent/alert_monitor.sv
- hw/dv/sv/alert_esc_agent/alert_sender_driver.sv
- hw/dv/sv/alert_esc_agent/esc_monitor.sv
- hw/dv/sv/alert_esc_agent/esc_receiver_driver.sv
- hw/dv/sv/alert_esc_agent/esc_sender_driver.sv
- hw/dv/sv/alert_esc_agent/seq_lib/alert_receiver_alert_rsp_seq.sv
- hw/dv/sv/alert_esc_agent/seq_lib/alert_receiver_base_seq.sv
- hw/dv/sv/alert_esc_agent/seq_lib/alert_receiver_ping_seq.sv
- hw/dv/sv/alert_esc_agent/seq_lib/alert_receiver_seq.sv
- hw/dv/sv/alert_esc_agent/seq_lib/alert_sender_base_seq.sv
- hw/dv/sv/alert_esc_agent/seq_lib/alert_sender_ping_rsp_seq.sv
- hw/dv/sv/alert_esc_agent/seq_lib/alert_sender_seq.sv
- hw/dv/sv/alert_esc_agent/seq_lib/esc_receiver_base_seq.sv
- hw/dv/sv/alert_esc_agent/seq_lib/esc_receiver_esc_rsp_seq.sv
Making tasks/functions/constraints `extern` for `alert_esc_agent`
> Extern tasks added to alert agent

- hw/ip/aon_timer/data/aon_timer.hjson
- hw/ip/aon_timer/doc/interfaces.md
- hw/ip/aon_timer/doc/registers.md
- hw/ip/aon_timer/rtl/aon_timer.sv
- hw/ip/aon_timer/rtl/aon_timer_core.sv
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/ip_autogen/pwrmgr/data/top_darjeeling_pwrmgr.ipconfig.hjson
- hw/top_darjeeling/ip_autogen/rstmgr/data/rstmgr.hjson
- hw/top_darjeeling/ip_autogen/rstmgr/data/top_darjeeling_rstmgr.ipconfig.hjson
- hw/top_darjeeling/ip_autogen/rstmgr/doc/registers.md
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/data/top_earlgrey_pwrmgr.ipconfig.hjson
- hw/top_earlgrey/ip_autogen/rstmgr/data/rstmgr.hjson
- hw/top_earlgrey/ip_autogen/rstmgr/data/top_earlgrey_rstmgr.ipconfig.hjson
- hw/top_earlgrey/ip_autogen/rstmgr/doc/registers.md
- hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson
- hw/top_englishbreakfast/ip_autogen/pwrmgr/data/top_englishbreakfast_pwrmgr.ipconfig.hjson
- hw/top_englishbreakfast/ip_autogen/rstmgr/data/rstmgr.hjson
- hw/top_englishbreakfast/ip_autogen/rstmgr/data/top_englishbreakfast_rstmgr.ipconfig.hjson
- hw/top_englishbreakfast/ip_autogen/rstmgr/doc/registers.md
PR created while doing a D3 RTL review of AON_timer.
Closes: https://github.com/lowRISC/opentitan/issues/26902
> [aon_timer] AON Timer minor revisions

- hw/ip/dma/data/dma.hjson
- hw/ip/dma/dma.core
- hw/ip/dma/doc/interfaces.md
- hw/ip/dma/rtl/dma.sv
- hw/ip/dma/rtl/dma_reg_top.sv
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
This PR adds RACL support to the DMA similar to other IPs.
> [hw,dma,rtl] Add RACL support to the DMA regtop

- rules/const.bzl
- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/flash_exc_handler.S
- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/defs.bzl
- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/flash_ecc_error_test.c
- sw/device/silicon_creator/rom/rom.ld
- sw/device/silicon_creator/rom/rom_epmp_test.c
- sw/device/silicon_creator/rom/rom_start.S
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error/BUILD
- sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error/secret_page_setup.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/device/silicon_creator/rom_ext/rom_ext_common.ld
- sw/device/silicon_creator/rom_ext/rom_ext_isrs.c
- sw/device/silicon_creator/rom_ext/rom_ext_isrs.h
- sw/device/silicon_creator/rom_ext/rom_ext_start.S
1. Refactor the flash exception handler used in the ROM to be usable in both the ROM and ROM_EXT.
2. Adapt the `flash_ecc_error_test` to run under either the ROM or ROM_EXT.
3. Put the ROM `flash_ecc_error_test` parameters in a separate `bzl`  file to re-use the parameterization for ROM_EXT tests.
4. Execute the same set of tests under the ROM_EXT.
- Initialize and lock secret partition two.  This is necessary
because without explicit initialization of the flash secret page,
the flash controller will always signal a read error, seeding error
and ECC error.
- Whereas the ROM uses the security version to control which slot
will boot, the ROM_EXT uses `boot_data::primary_slot`.  We control
this setting via `resuce boot-svc`.
- The boot-fault error codes for exceptions are different between …
> [rom_ext] Add the flash exception hander 

- hw/ip_templates/rv_plic/fpv/tb/coverage_waivers.tcl.tpl
- hw/top_darjeeling/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
- hw/top_earlgrey/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
- hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
This is the same code waived in #26613 as dead branch but it still appears as dead statement.
> [rv_plic, fpv] Statement coverage affected by parasitic state

- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
Task `check_alert_triggered` returns a `alert_due_to_ping` flag if the alert sender is handling a ping, so when returning in `check_alerts()` task the flag `expected_alert[alert_name].expected` is not immediately unset.
> [dv, cip_base_scoreboard] Alert check postponed during ping

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
The existing code was probably doing something reasonable, but the explanations were rather confused (claiming that the FSM is linear when it isn't!)
Rewrite things with lots of comments. I suspect the behaviour will be exactly the same, but this should be slightly easier to understand.
Also, avoid the last dut_init call (since we'll do another one when we drop out of the case statement).
> [rom_ctrl,dv] Fix "LocalEscalation" in corrupt_sig_fatal_chk_vseq

- hw/ip/rom_ctrl/dv/env/rom_ctrl_if.sv
- hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
- hw/ip/rom_ctrl/dv/tb.sv
Only the second commit is intended have a functional change (fixing a bug) but the others should make the code a bit easier to read.
> [rom_ctrl,dv] General tidy-ups in rom_ctrl DV code

- hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_status_stall_vseq.sv
- hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
Plus a bit of cleanup for unused variables and a warning from a VSEQ
> [dv, spi_host] Re-implementing command.CSAAT <-> CSB check

- sw/device/silicon_creator/rom_ext/defs.bzl
Update the ROM_EXT version number.
> [rom_ext] Bump version to 0.107

- sw/device/tests/flash_ctrl_idle_low_power_test.c
The test expects the sleep to abort because of the inflight flash transaction. Currently, this is done by calling looking at the reset reason stored in retentation by the ROM. This is incorrect since if the device wrongly enter (shallow) low-power sleep then it would not reset so the ROM will not run and rstmgr will play not role. Instead, the correct way to check this is to ask the pwrmgr's wakeup info and check for the aborted type.
Note that the test by itself was still performing as expected because the aon_timer is configured in a way that if the device ever entered sleep then it would reset due to an watchdog bite and this would cause the test to fail anyway. But it would not catch other types of errors such as the pwrmgr entering sleep and waking up unexpectedly.
> [test,flash_ctrl_idle_low_power_test] Correct check for sleep abort

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
The missing fork risks the possibility that the disable fork will kill some other process that got started.
The fact that this was missing causes the Verissimo lint tool to report an error. Fix it.
> [dv] Add missing isolation fork to cip_base_vseq__shadow_reg_errors

- hw/ip_templates/rv_plic/fpv/tb/coverage_waivers.tcl.tpl
- hw/top_darjeeling/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
- hw/top_earlgrey/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
- hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
This is the same coverage waiver that #26979 added. But this coverage exist for statement as well.
> [rv_plic, fpv] Waiver required for statement coverage

- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_host/rtl/spi_host_window.sv
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
- hw/ip/tlul/rtl/tlul_adapter_racl.sv
- hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv
This PR is a follow-up fix to a [comment](https://github.com/lowRISC/opentitan/pull/26691#discussion_r2060041699) in #26691.
> [hw,rtl,racl] Rename add _i suffix to racl_policy_sel_ranges.

- sw/host/opentitanlib/src/transport/common/uart.rs
**Context**
Rarely, under high CI load, it can happen that a test fails with [SFDP header contains incorrect signature: 0xffffffff](https://github.com/lowRISC/opentitan/actions/runs/14728491203/job/41337073207?pr=27065#step:6:2521).
I have traced back this issue to the following sequence of events:
- a test that changes OTP is run (e.g. `e2e_bootstrap_rma_fpga_cw310_rom_with_fake_keys`)
- a cleanup function runs that [clears the FPGA](https://github.com/lowRISC/opentitan/actions/runs/14728491203/job/41337073207?pr=27065#step:6:2482)
- another test runs and tries to see if the FPGA is loaded with the correct ROM
- due to stale data in the UART device (SAM3x), the host mistankely thinks that the FPGA is loaded and [skips bitstream loading](https://github.com/lowRISC/opentitan/actions/runs/14 …
> [otlib] Improve serial port RX buffer clearing

- .github/workflows/fpga.yml
- .github/workflows/nightly.yml
- sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD
Cherry-pick of #26927 and enable tests added in #26647
> [ci] remove udev workarounds and re-enable DFU tests

- hw/ip/soc_dbg_ctrl/dv/tb.sv
Add this issue ID https://github.com/lowRISC/opentitan/issues/27112 to track the required change
> [soc_dbg_ctrl,dv] Add issue ID to track a TODO

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
The sequence runs without the scoreboard enabled, so the sequence is responsible for updating the RAL. This commit adds a missing update.
The motivation for this was to fix the shadow_reg_errors test for ac_range_check (thanks, @martin-velay, for discovering the problem). Try that out with `util/dvsim/dvsim.py hw/top_darjeeling/ip_autogen/ac_range_check/dv/ac_range_check_sim_cfg.hjson -i ac_range_check_shadow_reg_errors -t xcelium --fi=1`.
> [dv] Predict value after a read of an RC field in shadow_reg_errors

- hw/ip_templates/ac_range_check/dv/env/ac_range_check_env.core.tpl
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_env.sv
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_env_pkg.sv.tpl
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_predictor.sv
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_scoreboard.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env.core
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env_pkg.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_predictor.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scoreboard.sv
- Move some code from the scoreboard into a predictor class included inside the scoreboard.
> [ac_range_check,dv] Create predictor in the SCB

- hw/ip/rv_timer/doc/programmers_guide.md
Document the safe way to modify `mtime` and state explicitly that `mtimecmp` shall be updated after `mtime` in the event that the latter is modified, since the interrupt state is updated only by writes to the `mtimecmp` register and not to `mtime`.
> [rv_timer] Additional notes on the writing of mtime/mtimecmp

- hw/ip/rv_timer/data/rv_timer.hjson
- hw/ip/rv_timer/doc/checklist.md
> [rv_timer] D3 revision and date bumpup

- hw/ip/rv_timer/data/rv_timer.hjson
- hw/ip/rv_timer/doc/checklist.md
> [rv_timer] V3 revision and date bumpup

- hw/ip/dma/doc/programmers_guide.md
Closes https://github.com/lowRISC/opentitan/issues/26947
> [hw,dma,doc] Add DMA programmers guide

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
Introduced with https://github.com/lowRISC/opentitan/pull/27221
> [darjeeling] Re-generate top to fix generated description

- sw/otbn/crypto/p256_shared_key.s
This PR implements the official SCA guidelines for OTBN for `p256_shared_key.s`, as listed in the [Secure Coding for Cryptography section](https://opentitan.org/book/doc/contributing/style_guides/otbn_style_guide.html#secure-coding-for-cryptography) of the OTBN Assembly Style Guide. 
These changes cumulatively amount to +0.2% latency overhead as measured by the OTBN simulator.
Most of the changes are to avoid side-channel leakage by clearing secret share dependent flag values; when two XORs were performed back to back in `arithmetic_to_boolean` on separate words of the same share, I treated it as sufficient to clear flags after both, but this is something that may be worth revisiting (especially since the latency overhead of doing so is very small).
> [sw/crypto] Implement SCA guidelines from OT docs for `p256_shared_key.s`

- sw/device/silicon_creator/rom_ext/defs.bzl
Update the ROM_EXT version number to `0.110`.
> [rom_ext] Bump version number

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/penetrationtests/doc/README.md
- sw/device/tests/penetrationtests/firmware/BUILD
This PR consists of two commits that cleanup the pentest BAZEl build rules.
> [pentest] Cleanup build rules

- hw/ip/hmac/rtl/hmac.sv
- hw/ip/prim/prim_fifo.core
- hw/ip/prim/rtl/prim_fifo_sync.sv
- hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
- hw/ip/prim/rtl/prim_sram_arbiter.sv
- hw/ip/prim_generic/rtl/prim_generic_flash_bank.sv
- hw/ip/spi_device/rtl/spi_tpm.sv
- hw/ip/spi_device/rtl/spid_readsram.sv
- hw/ip/tlul/rtl/tlul_adapter_sram.sv
- hw/ip/tlul/rtl/tlul_sram_byte.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy_rd.sv
- hw/ip_templates/otp_ctrl/rtl/otp_ctrl.sv.tpl
- hw/top_darjeeling/ip_autogen/otp_ctrl/rtl/otp_ctrl.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv
- hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl.sv
- hw/top_englishbreakfast/ip_autogen/flash_ctrl/rtl/flash_phy.sv
- hw/top_englishbreakfast/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv
These two instantiations can never decrement and passing the parameter like this checks this is true.
> [prim,rtl] Pass PossibleActions parameter inside prim_fifo_sync_cnt

- sw/device/lib/dif/dif_csrng_shared.h
- sw/device/lib/dif/dif_rv_core_ibex.h
Triggered by triaging #6242.
Closes #6242.
> [sw] Add @file comments to the remaining dif headers missing them

- sw/device/silicon_creator/rom_ext/defs.bzl
This prepares for the next ROM_EXT build / release.
> [rom_ext] rev version to 0.111

- hw/ip_templates/ac_range_check/data/ac_range_check_testplan.hjson
- hw/ip_templates/ac_range_check/dv/ac_range_check_sim_cfg.hjson.tpl
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_env.core.tpl
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_env_cov.sv
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_misc_io_if.sv
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_predictor.sv
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_scoreboard.sv
- hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_base_vseq.sv
- hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_bypass_vseq.sv
- hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_lock_range_vseq.sv
- hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_vseq_list.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/data/ac_range_check_testplan.hjson
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/ac_range_check_sim_cfg.hjson
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env.core
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env_cov.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_misc_io_if.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_predictor.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scoreboard.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_base_vseq.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_bypass_vseq.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_lock_range_vseq.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_vseq_list.sv
Depends on PR #27226 
Adds functionality to DV for AC_RANGE_CHECK for Bypass and Lock Range Verification
> [ac_range_check,dv] Enabling Bypass and Lock Range Verification

- hw/top_earlgrey/formal/top_earlgrey_fpv_prim_cfgs.hjson
We forgot to change this as part of 8925ae38.
> [fpv] Fix type of after_load in top_earlgrey_fpv_prim_cfgs.hjson

- hw/dv/sv/alert_esc_agent/alert_esc_agent.sv
- hw/dv/sv/alert_esc_agent/alert_esc_base_monitor.sv
- hw/dv/sv/alert_esc_agent/esc_monitor.sv
- hw/dv/sv/dv_lib/dv_base_driver.sv
- hw/dv/sv/dv_lib/dv_base_monitor.sv
- hw/dv/sv/dv_lib/dv_base_test.sv
- hw/dv/sv/dv_lib/dv_base_vseq.sv
- hw/dv/sv/push_pull_agent/push_pull_agent.sv
- hw/dv/sv/push_pull_agent/push_pull_agent_cov.sv
- hw/dv/sv/push_pull_agent/push_pull_monitor.sv
- hw/dv/sv/tl_agent/tl_monitor.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
Adding super. to uvm phases to clean verissimo lint errors R.1204
> Components to call super in phases

- sw/device/lib/testing/test_framework/ottf_console.c
- sw/device/lib/testing/test_framework/ottf_console.h
- sw/device/tests/BUILD
- sw/device/tests/ottf_dual_console_test.c
- sw/host/tests/chip/ottf_dual_console/BUILD
- sw/host/tests/chip/ottf_dual_console/src/main.rs
Follow-up on #27310
Add a test exercising two OTTF console. Only review the last two commits.
> Dual OTTF console test

- hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl_decode.sv
Delay valid/relocked for one cycle to say in sync with the sampled debug category.
At the end, output signals are derived based on the sampled debug category and valid/relocked. The later two signals, though, are one cycle behind the data, which may cause undesired side effects. This PR adds one flop stage on those signals to keep the data and the control signals in sync.
> [hw,soc_dbg_ctrl,rtl] Ensure that valid/relocked have the same amount of FFs as debug category

- sw/device/tests/ottf_dual_console_test.c
- sw/host/tests/chip/ottf_dual_console/BUILD
> [sw,tests] Cleanup various nits in the OTTF dual console test

- hw/dv/sv/kmac_app_agent/kmac_app_agent.sv
> [dv, kmac_app_agent] Call super.run_phase

- hw/ip_templates/ac_range_check/dv/env/ac_range_check_env_cfg.sv
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_scoreboard.sv
- hw/ip_templates/ac_range_check/dv/tests/ac_range_check_base_test.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env_cfg.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scoreboard.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/tests/ac_range_check_base_test.sv
Implementing fix mentioned on issue #27380, via cfg option.
> [ac_range_check,dv] Fix to interrupt CIP test

- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
Fix a typo in a comment and add information in a uvm_info string.
> [dv,flash_ctrl] Make non-functional changes

- sw/device/lib/dif/dif_alert_handler.c
- sw/device/lib/dif/dif_alert_handler.h
- sw/device/lib/testing/BUILD
- sw/device/lib/testing/alert_handler_testutils.c
- sw/device/lib/testing/alert_handler_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/power_virus_systemtest.c
Manual cherry pick of https://github.com/lowRISC/opentitan/pull/26857 as the automatic cherry pick failed.
> Cherry-pick to master: [sival] Add `alert_handler` log utilities.

- sw/device/silicon_creator/rom_ext/imm_section/defs.bzl
This updates the immutable section version number.
> [rom_ext] bump immutable section version to 0.3

- doc/contributing/dv/methodology/README.md
- util/dvsim/README.md
- util/dvsim/doc/testplanner.md
As I went through these pages I found out some minor issues.
> [doc] Fix links and typos for some DV docs

- hw/top_darjeeling/templates/toplevel.sv.tpl
This PR changes the toplevel.sv template to explicitly check for pinmux,alert_handler,ast,rstmgr,gpio to exist before generating code related to these IPs.
It also fixes a small issue where unnecessary signals for outgoing interrupts were generated.
There are no other generated changes when applying this PR as the top_darjeeling.hjson includes all of these IPs. However this should make it easier to reuse this template when some of these IPs are not instantiated.
> [topgen] Make darjeeling template more compatible

- hw/ip/prim/prim_edge_detector.core
- hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl_decode.sv
- hw/ip/soc_dbg_ctrl/soc_dbg_ctrl_decode.core
- hw/top_darjeeling/ip/soc_proxy/soc_proxy.core
- hw/top_darjeeling/lint/top_darjeeling_lint_cfgs.hjson
This factors out some commits from https://github.com/lowRISC/opentitan/pull/27478. Let the easy stuff go in faster.
> [darjeeling,lint] Improve lint for Darjeeling

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/ip/ast/data/ast.hjson
- hw/top_darjeeling/ip/ast/rtl/ast.sv
- hw/top_darjeeling/rtl/autogen/chip_darjeeling_asic.sv
- hw/top_darjeeling/rtl/autogen/chip_darjeeling_cw310.sv
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_darjeeling/templates/chiplevel.sv.tpl
> [darjeeling] Darjeeling has no EDN in AST

- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_core_ibex_lockstep_glitch_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_tap_straps_vseq.sv
Very minor changes, and detailed in commit messages.
> [chip,dv] Fix some warnings when building with Xcelium

- hw/dv/sv/alert_esc_agent/alert_esc_if.sv
- hw/dv/sv/alert_esc_agent/esc_receiver_driver.sv
This simplifies some code, adds documentation comments and adds isolation forks.
> [dv] Tidy-ups in the alert agent

- rules/bitstreams.bzl
(This is an actually meaningful change, but this PR is just a CI test merged to the ci-test branch for testing cherry-picking CI)
> [CI-TEST] do not merge to master

- doc/project_governance/technical_committee.md
Update TC membership as decided by the Governing Board on 2025-07-23.
> [doc] Update TC membership

- util/reggen/multi_register.py
- util/reggen/systemrdl/BUILD
- util/reggen/systemrdl/udp.py
- util/reggen/systemrdl/udp.rdl
- util/reggen/systemrdl_exporter.py
This PR get most of the properties exported to SystemRDL. It also defines some custom properties:
- hwre: Should this be named differently in System RDL?
- shadowed
> [Reggen] Export more properties to SystemRDL

- hw/ip/usbdev/doc/wake_resume.md
Point register links to the registers markdown file in preference to the raw hjson data file.
> [doc,usbdev] Fix up register links

- hw/ip/uart/dv/README.md
A few errors noticed when comparing with the DV files of other IP blocks.
> [dv,uart] Some simple fixes to UART DV documentation

- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
Before locking down write access to configuration CSRs via the SW_REGUPD CSR, we need to make sure there has been enough time for signaling and detecting a recoverable alert (e.g. because of writing invalid MuBis). Upon receiving an alert, the calling task will abort the configuration task thereby preventing the locking. But without sufficient time, DV may lock an invalid configuration which would require resetting the DUT.
This change is required due to 60959f9c17de6c6f5a323cd0421793237dbe8005 which correctly inserted a delay in the function waiting for alert triggers to account for ongoing alert pings.
Without this change, the crucial entropy_src_rng vseq had a failure rate of around 50% which massively impacts functional coverage for the ENTROPY_SRC block.
> [entropy_src/dv] Prevent accidental locking of invalid configurations

- sw/host/provisioning/orchestrator/src/BUILD
- sw/host/provisioning/orchestrator/src/db.py
- sw/host/provisioning/orchestrator/tests/BUILD
- sw/host/provisioning/orchestrator/tests/db_test.py
Backport #25306 ([orchestrator] Add databse interface.)
> Backport 25306 ([orchestrator] Add databse interface.)

- hw/ip_templates/ac_range_check/data/ac_range_check_testplan.hjson
- hw/ip_templates/ac_range_check/doc/checklist.md
- hw/ip_templates/ac_range_check/dv/README.md.tpl
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_dut_cfg.sv
- hw/ip_templates/ac_range_check/dv/env/ac_range_check_misc_io_if.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/data/ac_range_check_testplan.hjson
- hw/top_darjeeling/ip_autogen/ac_range_check/doc/checklist.md
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/README.md
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_dut_cfg.sv
- hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_misc_io_if.sv
Prepare DV docs for V1 and V2 signoff.
Some further work is still required but I suggest to review this as a first stage.
> [ac_range_check,dv & doc] V1 and V2 signoff preparation

- hw/dv/sv/i2c_agent/i2c_driver.sv
In the OpenTitan I2C BFM driver, item_done() is currently called after the fork-join loop. This creates a race condition on reset, where the request (req) may be cleared before item_done() is called.
RUN TIME ERROR : Item_done() called with no outstanding requests. Each call to item_done() must be paired with a previous call to get_next_item().
Move the item_done(req) call inside the fork-join block, immediately after the transaction processing is complete. This ensures item_done() is always paired with a valid get_next_item() call, even if a reset occurs during the forked processing.
This work was done by Raja Aadhithan
> [bfm,i2c,dv] Fix race condition with item_done()

- hw/ip/usbdev/data/usbdev.hjson
- hw/ip/usbdev/rtl/usbdev.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson
Correct the 'Stub' parameter description, and include a few linguistic improvements at the same time.
Describe the 'AlertSkewCycles' parameter.
> [data, usbdev] Documentation fixes

- util/container/Dockerfile
- util/container/README.md
This PR cherry picks 3 commits from the Master branch to earlgrey_1.0.0. These commits update the Dockerfile and make it functional again.
> [util,docker] Dockerfile updates from Master

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/pwrmgr.c
> [sw,silicon_creator] pwrmgr multi-top conversion

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/rnd.c
> [sw,silicon_creator] rnd multi-top conversion

- hw/top_earlgrey/BUILD
- rules/signing.bzl
- rules/tests/BUILD
- signing/examples/BUILD
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/ate/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_big_image/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_newer/BUILD
- sw/device/silicon_creator/rom/e2e/keymgr/BUILD
- sw/device/silicon_creator/rom/e2e/sigverify_key_type/BUILD
- sw/device/silicon_creator/rom/e2e/sigverify_spx/BUILD
- sw/device/silicon_creator/rom/keys/fake/ecdsa/BUILD
- sw/device/silicon_creator/rom/keys/fake/spx/BUILD
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error/BUILD
- sw/device/silicon_creator/rom_ext/e2e/secver/BUILD
- sw/device/silicon_creator/rom_ext/sival/BUILD
Add keysets from rom fake keys to prepare for removal of the key_{ecdsa, spx} keys.
> [rom] Add keysets for rom fake keys

- hw/ip/rv_dm/dv/tb.sv
- hw/ip/tlul/generic_dv/tests/xbar_error_test.sv
- hw/ip/tlul/rtl/tlul_assert.sv
This was originally motivated by my desire to tidy things up (the second commit), but I realised the existing sequences are actually wrong! That is fixed in the first commit.
> [tlul,dv] Tidy-ups and corrections to tlul_assert.sv

- hw/ip/mbx/doc/block_diagram.svg
- hw/ip/mbx/doc/checklist.md
- hw/ip/mbx/doc/theory_of_operation.md
- hw/ip/mbx/dv/README.md
Updates to the checklist and documentation to reflect recent scoreboard and coverage work.
Add IP block diagram.
> [mbx] Further mailbox documentation updates

- hw/ip_templates/otp_ctrl/defs.bzl.tpl
- hw/ip_templates/otp_ctrl/util/BUILD.bazel.tpl
- hw/ip_templates/otp_ctrl/util/dt.py
- hw/ip_templates/otp_ctrl/util/ipconfig.py
- hw/top_darjeeling/ip_autogen/otp_ctrl/defs.bzl
- hw/top_darjeeling/ip_autogen/otp_ctrl/util/BUILD.bazel
- hw/top_darjeeling/ip_autogen/otp_ctrl/util/dt.py
- hw/top_darjeeling/ip_autogen/otp_ctrl/util/ipconfig.py
- hw/top_earlgrey/ip_autogen/otp_ctrl/defs.bzl
- hw/top_earlgrey/ip_autogen/otp_ctrl/util/BUILD.bazel
- hw/top_earlgrey/ip_autogen/otp_ctrl/util/dt.py
- hw/top_earlgrey/ip_autogen/otp_ctrl/util/ipconfig.py
- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/mock_otp.h
- sw/device/silicon_creator/lib/drivers/otp.c
- sw/device/silicon_creator/lib/drivers/otp.h
- sw/device/silicon_creator/lib/drivers/pinmux_unittest.cc
- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/keymgr/rom_e2e_keymgr_init_test.c
- sw/device/silicon_creator/rom_ext/BUILD
- util/topgen/lib.py
* Convert EG base addresses to DT generated ones
* Move readable partitions array to top specific SW folder
Fixes #28071
> [sw,silicon_creator] Multi-top OTP driver

- sw/device/lib/crypto/impl/ecc_p256.c
- sw/device/lib/crypto/impl/ecc_p384.c
We should check the integrity of the public and private key after we have written them into OTBN.
> [crypto] Check ECC key integrity after writing to OTBN

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/otbn.c
> [sw,silicon_creator] OTBN multi-top conversion

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/kmac.c
- sw/device/silicon_creator/lib/drivers/pwrmgr.c
- sw/device/silicon_creator/lib/drivers/pwrmgr.h
- sw/device/silicon_creator/lib/drivers/watchdog.c
- sw/device/silicon_creator/lib/error.h
> [sw,silicon_creator] watchdog and kmac multi-top conversion

- sw/device/lib/crypto/impl/aes.c
- sw/device/lib/crypto/impl/aes_gcm.c
- sw/device/lib/crypto/impl/hkdf.c
- sw/device/lib/crypto/impl/kdf_ctr.c
- sw/device/lib/crypto/impl/key_transport.c
- sw/device/lib/crypto/impl/key_transport_unittest.cc
- sw/device/lib/crypto/impl/kmac.c
- sw/device/lib/crypto/impl/kmac_kdf.c
- sw/device/lib/crypto/include/aes.h
- sw/device/lib/crypto/include/aes_gcm.h
- sw/device/lib/crypto/include/hkdf.h
- sw/device/lib/crypto/include/kdf_ctr.h
- sw/device/lib/crypto/include/key_transport.h
- sw/device/lib/crypto/include/kmac.h
- sw/device/lib/crypto/include/kmac_kdf.h
- sw/device/tests/crypto/cryptotest/firmware/ecdh.c
- sw/device/tests/crypto/hkdf_functest.c
- sw/device/tests/crypto/kdf_hmac_ctr_functest.c
- sw/device/tests/crypto/kdf_kmac_functest.c
- sw/device/tests/crypto/kdf_kmac_sideload_functest.c
- sw/device/tests/penetrationtests/firmware/fi/cryptolib_fi_asym_impl.c
- sw/device/tests/penetrationtests/firmware/sca/cryptolib_sca_asym_impl.c
This is a manual cherry-pick from master to earlgrey_1.0.0 of the following two PRs:
- #27244
- #27265
> Manual cherry-pick to earlgrey_1.0.0: #27244 and #27265

- .github/actions/prepare-env/action.yml
- .github/workflows/ci.yml
- MODULE.bazel
- MODULE.bazel.lock
- third_party/qemu/BUILD
- third_party/qemu/BUILD.qemu_opentitan.bazel
- third_party/qemu/README.md
- third_party/qemu/build_qemu.sh
- third_party/qemu/extensions.bzl
Manual backport of https://github.com/lowRISC/opentitan/pull/28190 from `earlgrey_1.0.0`. No major changes, just things moving around.
Closes https://github.com/lowRISC/opentitan/issues/27898
> [third_party,qemu] Support building QEMU from source incrementally (backport)
