lowRISC/opentitan

- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/host/opentitanlib/src/app/i2c.rs
- sw/host/opentitanlib/src/app/spi.rs
The JSON configuration format allows named aliases of SPI or I2C ports, such that e.g. "TPM" can be an alias for e.g. "SPI1".  The same hardware port can have multiple aliases.  A key point is that each alias can have its own default speed and other settings, and the `TransportWrapper` layer will make sure that before a port alias is used for communication, its settings are applied to the physical transport port.
It seems that a bug had gone un-noticed, because of which the settings were repeatedly applied if the same alias was used in a sequence of transactions.  This could seem to be merely the cause for some slowdown, but Alex discovered that when SPI chip select is to be kept asserted across a series of separate interactions, re-setting the speed and choice of chip select pin will …
> [opentitantool] Fix omission in SPI/I2C alias handling

- hw/ip/dma/data/dma.hjson
- hw/ip/dma/data/dma_testplan.hjson
- hw/ip/dma/doc/theory_of_operation.md
- hw/ip/dma/dv/env/dma_env_cov.sv
- hw/ip/dma/dv/env/dma_scoreboard.sv
- hw/ip/dma/dv/env/dma_seq_item.sv
- hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv
- hw/ip/dma/rtl/dma.sv
- hw/ip/dma/rtl/dma_pkg.sv
- hw/ip/dma/rtl/dma_reg_pkg.sv
- hw/ip/dma/rtl/dma_reg_top.sv
- sw/ip/dma/dif/dif_dma.c
- sw/ip/dma/dif/dif_dma.h
- sw/ip/dma/dif/dif_dma_unittest.cc
This PR aims to rename registers to be more common with other OT IP.
In particular, we now use the following terms:
* INTR for the LSIO triggers/interrupts
* ADDR for address
* SRC for source
* DST for destination
> [hw,dma] Rename registers to be more compatible with other OT IP

- hw/ip/dma/rtl/dma.sv
Memory limit interrupts must be signaled on receipt of the write response, which may occur in two FSM states.
This PR corrects the RTL to include the second state so that interrupts are not omitted. (Found in DV)
> [dma] Fix for signaling of memory buffer (almost) limit interrupt

- hw/formal/tools/dvsim/formal.mk
Piping the command into tee doesn't quite work. For example:
blargl 2>&1 | tee /dev/null
echo $?
will print out 0 because tee passed, even though blargl doesn't exist.
Use the pipefail option to avoid this happening.
> [util,formal] Make sure to fail in Make if a command dies

- util/fpvgen/sv_parse.py
The reason that I looked at this at all is the (trivial) bugfix in the second commit.
To see the bug, run `util/fpvgen.py hw/ip/otbn/rtl/otbn_start_stop_control.sv` and look at the generated testbench: it will have a trailing space which comes up bright pink in Emacs! Clearly worth fixing :-)
While I was at it, I also did a bit of tidyup and deleted some unnecessary lines of code.
> [util,fpvgen] Minor tidyup in parsing

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/aes_sca.c
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/firmware/trigger_sca.c
- sw/device/tests/crypto/cryptotest/firmware/trigger_sca.h
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/aes_sca_commands.h
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/trigger_sca_commands.c
- sw/device/tests/crypto/cryptotest/json/trigger_sca_commands.h
Previously, the trigger source selection was implemented in the AES SCA command handler. However, as other SCA targets (KMAC, SHA3) might want to also change the trigger source, I've moved the handler to a separate command.
> [sca] Move trigger source select to own uJSON command

- hw/ip/mbx/rtl/mbx_fsm.sv
Instead of only using the next state signal of the FSM, we also take into account the current state, to compute the transition edge into the Read and Abort state, that generates the event for the IRQ primitive.
Closes https://github.com/lowRISC/opentitan-integrated/issues/714
> [hw,mbx,rtl] Use the transition to the Read/Abort to generate the IRQ

- sw/host/ot_certs/BUILD
- sw/host/ot_certs/src/asn1/dice_tcb.rs
- sw/host/ot_certs/src/asn1/mod.rs
- sw/host/ot_certs/src/asn1/x509.rs
See the commits for description. First 4 commits are from #20596 and #20600.  You can test it using:
```bash
./bazelisk.sh run //sw/host/opentitantool -- certificate generate $PWD/sw/device/silicon_creator/lib/cert/example.hjson $PWD/example.pem
openssl asn1parse -inform DER -in $PWD/example.pem
openssl x509 -in $PWD/example.pem -noout -text
./bazelisk.sh run //sw/host/opentitantool -- certificate parse $PWD/example.pem
```
> [ot_certs] add ASN1 X509 extensions

- sw/host/opentitanlib/src/app/config/hyperdebug_chipwhisperer.json
- sw/host/opentitanlib/src/app/config/hyperdebug_cw310.json
The "QSPI" SPI interface is mapped to the STM32's OCTOSPI peripheral in the hyperdebug firmware, but it is incapable of performing the TPM protocol. Use SPI1 instead, and add strappings to set pins to high impedance for the unused interface, since they will both be driving the same traces.
> [opentitanlib] Add strappings for hyper310 SPI TPM

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.c
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.h
- sw/device/tests/crypto/cryptotest/firmware/status.h
- sw/device/tests/crypto/cryptotest/json/ibex_fi_commands.h
Adds new FI tests to characterize Ibex:
- ibex.char.mem_op_loop
- ibex.char.reg_op_loop
- ibex.char.unrolled_mem_op_loop
Host code is available at [#259](https://github.com/lowRISC/ot-sca/pull/259).
> [fi] Add Ibex FI characterization tests

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_idle_hint_vseq.sv
This test verify that jtag debugger does not need to stay any longer than advertized idle time indicated in dtmcs register.
@jdonjdon. kindly review it.Thanks
> [RV_DM]JTAG_dtm_idle_hint_vseq

- sw/host/opentitanlib/src/dif/lc_ctrl.rs
- sw/host/opentitantool/src/command/lc.rs
The token was being parsed in the wrong order. Resulting in failed transitions.
> [opentitantool] fix token parsing for LC transition command

- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwrmgr_sensor_ctrl_deep_sleep_wake_up_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/BUILD
- sw/device/tests/pwrmgr_sensor_ctrl_deep_sleep_wake_up.c
This is a sim_dv test that forces sensor_ctrl alert inputs while the chip is in deep sleep. It will fail unless the sensor_ctrl synchronizes incoming alerts with the aon clock. Can be used to verify the fix for #20614.
> [dv,top_level] Add test for sensor_ctrl deep sleep wake up

- sw/device/tests/rv_core_ibex_nmi_irq_test.c
- sw/device/tests/uart_tx_rx_test.c
Fix a comment, remove redundant assignments, and duplicate variable declarations.
> [sival,tests] Fix trivial mistakes

- SUMMARY.md
- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
- sw/device/silicon_creator/rom_ext/README.md
- sw/device/silicon_creator/rom_ext/doc/si_val.md
1. Update the info page lockdown configuration to include the `kFlashCtrlInfoPageFactoryId` page.
2. Updates the ROM_EXT SiVal documentation to include relevant details for this configuration.
> [sival] ROM_EXT SiVal updates.

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/ast.c
- sw/device/silicon_creator/lib/drivers/ast.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/device/silicon_creator/rom_ext/sival/BUILD
Add a mechanism to patch the AST configuration in the rom_ext stage. The data is loaded from the `kFlashCtrlInfoPageFactoryId` info page. The configuration is only applied if the first two words read from flash are not 00s or UINT32_t.
> [rom_ext] Add AST patching to rom_ext.

- .github/workflows/pr_lint_review.yml
The verible github actions look for an Ubuntu-specific tarball in the releases, but these stopped being built. Use the latest release for which that tarball is available.
> [verible-lint] Pin version of verible instead of following latest

- hw/ip/otp_ctrl/doc/interfaces.md
In the past, there have been misunderstandings whether scrambling keys having seed_valid = 0 are safe to be used at all. As it turns out, they are. This PR adds this information to the interfaces section of the otp_ctrl documentation.
This resolves lowRISC/OpenTitan#13201.
> [otp_ctrl,doc] Document scrambling keys being ephemeral if seed_valid=0

- hw/top_earlgrey/BUILD
The cw310_sival_rom_ext configuration was still on the SAM3X bitstream variant. Move it to hyper310 to make all the SiVal I/O available.
> [exec_env] Move cw310_sival_rom_ext to hyper310

- doc/security/cryptolib/cryptolib_api.md
- sw/device/lib/crypto/impl/rsa.c
- sw/device/lib/crypto/include/rsa.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/rsa_2048_keygen_functest.c
- sw/device/tests/crypto/rsa_2048_signature_functest.c
- sw/device/tests/crypto/rsa_3072_keygen_functest.c
- sw/device/tests/crypto/rsa_3072_signature_functest.c
- sw/device/tests/crypto/rsa_4096_keygen_functest.c
- sw/device/tests/crypto/rsa_4096_signature_functest.c
Use normal key and word-buffer structs for RSA keys and signatures instead of specialized multi-level structs. This is more convenient for the caller and also will make it easier to adjust the representation of RSA datatypes under the hood (for example if we wanted to switch to a faster CRT-based RSA, which would represent d differently).
Related: https://github.com/lowRISC/opentitan/pull/20262 was essentially the same change for ECC
> [crypto]  Adjust RSA implementation to remove specialized structs.

- SUMMARY.md
- signing/README.md
- sw/device/tests/doc/sival/README.md
- sw/device/tests/doc/sival/devguide.md
This commit describes how to use the silicon execution environments and adds cross references to other SiVal relevant documentation.
Only review the last commit. Other commits are part of #20694.
> [sival] Document silicon execution environments.

- hw/ip/otp_ctrl/data/earlgrey_a0_skus/prodc/BUILD
- rules/const.bzl
- sw/device/silicon_creator/manuf/provisioning_inputs.bzl
The `prodc` SKU configuration will be used in various integration testing platforms.
> [silicon] Add prodc OTP configuration.

- sw/device/tests/BUILD
- sw/device/tests/doc/sival/README.md
This PR enables tests listed in the SV2 test suite to run using the `silicon_owner_sival_rom_ext` configuration.
> [sival] Add silicon_owner exec env to SV2 test_suite.

- hw/ip/otp_ctrl/data/earlgrey_a0_skus/prodc/BUILD
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/host/opentitanlib/src/app/mod.rs
- sw/host/opentitanlib/src/test_utils/lc.rs
- sw/host/provisioning/orchestrator/orchestrator.py
1. Add `prodc` to provisioning scripts.
2. Update `prodc` OTP config to match the `sival_bringup` configuration.
3. Force `rom_bootstrap` pins before connecting to life-cycle tap during provisioning.
4. Increase the DFT strap apply time to 10ms to account for slower parts.
> Post si SKU updates

- sw/device/lib/crypto/drivers/entropy.c
- sw/device/lib/crypto/drivers/entropy.h
- sw/device/lib/crypto/impl/rsa/BUILD
- sw/device/lib/crypto/impl/rsa/rsa_padding.c
- sw/device/lib/crypto/impl/rsa/rsa_padding.h
- sw/device/lib/crypto/impl/rsa/rsa_signature.c
This padding mode is used for RSA encryption and is defined in IETF RFC 8017.
I couldn't find any tests for OAEP specifically, but I implemented RSA encryption on top of this and got it passing tests. The encryption code and tests will be in a follow-up PR or two for size reasons.
> [crypto] Add OAEP padding for RSA.

- doc/security/cryptolib/cryptolib_api.md
- sw/device/lib/crypto/impl/BUILD
- sw/device/lib/crypto/impl/kdf.c
- sw/device/lib/crypto/impl/keyblob.c
- sw/device/lib/crypto/impl/mac.c
- sw/device/lib/crypto/include/datatypes.h
- sw/device/lib/crypto/include/kdf.h
- sw/device/lib/crypto/include/mac.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/hmac_sha256_functest.c
- sw/device/tests/crypto/hmac_sha384_functest.c
- sw/device/tests/crypto/hmac_sha512_functest.c
HKDF is a common HMAC-based KDF separate from KDF-CTR. This PR implements it on top of the existing HMAC interface.
HKDF wasn't originally part of the cryptolib API because (I think) there was some confusion about whether it was the same thing as KDF-CTR with HMAC as the PRF. It's a bit different, though, and more commonly used, so it seems worth its own entrypoint.
> [crypto] Implement HKDF.

- hw/ip/prim/lint/prim_trivium.vlt
- hw/ip/prim/lint/prim_trivium.waiver
- hw/ip/prim/pre_dv/prim_trivium/README.md
- hw/ip/prim/pre_dv/prim_trivium/cpp/prim_trivium_tb.cc
- hw/ip/prim/pre_dv/prim_trivium/prim_trivium_tb.core
- hw/ip/prim/pre_dv/prim_trivium/rtl/prim_trivium_tb.sv
- hw/ip/prim/prim_trivium.core
- hw/ip/prim/rtl/prim_trivium.sv
- hw/ip/prim/rtl/prim_trivium_pkg.sv
Note this is still a draft PR mainly done for visibility. I don't intend to merge this immediately. I have implemented and verified these two PRNGs (scratch Verilator TB will follow in this PR soon), and also done first SCA experiments when integrating this into our AES core. In terms of SCA hardening, results are similar compared to the existing LFSR-based PRNG. The big advantage of Trivium/Bivium compared to 32-bit LFSRs is that state recovery attacks are infeasible.
This is related to [#19091](https://github.com/lowRISC/opentitan/issues/19091)
This PR adds a new prim module implementing the Trivium [1] and its reduced variant Bivium [2] (more precisely Bivium B) stream cipher primitives. The number of output bits produced per update can flexibly be tuned using the OutputWidth parameter …
> [prim] Add Trivium/Bivium stream cipher primitives

- sw/host/provisioning/orchestrator/ot_device.py
- sw/host/tests/manuf/provisioning/ft/BUILD
The prod-signed FT binaries can still be used to provision dev devices since the prod key is accepted in all LC states. This removes the requirment on having a nitrokey to provision dev devices.
> [manuf] remove deps on non-prod FT bins

- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
[usbdev] usbdev_smoke_vseq
Add smoke sequence test of simple packet transmission in both directions over the USB.
@jdonjdon please review this. This PR is dependent on  [https://github.com/lowRISC/opentitan/pull/20709]
> Usb smoke test

- sw/device/lib/crypto/impl/BUILD
- sw/device/lib/crypto/impl/rsa.c
- sw/device/lib/crypto/impl/rsa/BUILD
- sw/device/lib/crypto/impl/rsa/rsa_encryption.c
- sw/device/lib/crypto/impl/rsa/rsa_encryption.h
- sw/device/lib/crypto/include/datatypes.h
- sw/device/lib/crypto/include/rsa.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/rsa_2048_encryption_functest.c
- Adds RSA encryption/decryption to the cryptolib API
- Adds an internal implementation of RSA encryption (combines the existing modexp and the new OAEP padding)
- Connects the internal implementation to the API
- Adds a basic test
Sorry for the large diff; a lot of it is test data because RSA values are huge.
> [crypto] Implement and test RSA-2048 encryption.

- signing/README.md
Add additional references to google-cloud-cli installation steps, and add more token configuration examples.
> [sival] Update signing configuration doc

- hw/ip/csrng/dv/cov/csrng_cov_if.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
This PR cleans up the code that makes up the fips coverage.
For a more detailed explanation please see the individual commit messages.
Most of this PR is already included in #20475.
> [csrng/dv] Clean up CSRNG fips coverage

- hw/top_earlgrey/data/ip/chip_rv_plic_testplan.hjson
- sw/device/tests/autogen/BUILD
- sw/device/tests/autogen/plic_all_irqs_test.c
- sw/device/tests/sival/BUILD
- util/topgen/templates/BUILD.tpl
- util/topgen/templates/plic_all_irqs_test.c.tpl
- Disable otp_ctrl CSR accesses in Owner boot stage since they are made illegal by rom_ext. This makes plic_all_irqs_test_10 pass, so enable it for silicon_owner_sival_rom_ext.
- The plic_all_irqs_test_10 test was already passing, so it is also enabled for silicon_owner_sival_rom_ext.
- Split the plic_all_irqs_test_0 test in the autogen BUILD file to mark it as broken for silicon_owner_sival_rom_ext.
- Add plic_all_irqs_test_10 and 20 to the sival sv2_tests suite.
> [sival,plic] Fix plic_all_irqs_test_10 and enable for silicon

- hw/ip/lc_ctrl/doc/theory_of_operation.md
- hw/ip/rv_dm/doc/interfaces.md
- Don't mention the reset topology in the lc_ctrl theory of operation doc's description of CPU_EN since lc_cpu_en_o is independent of reset, and rv_core_ibex gets a separate fetch_en input from pwrmgr that determines whether the cpu is effectively enabled.
- Fix the life cycle control description in the rv_dm interfaces doc: all it needs to say is that NDM reset will not reset rv_dm but will reset lc_ctrl. The prior text is inaccurate.
Fixes #20700
> [doc,reset] Fix references to reset behavior

- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/device/silicon_creator/rom_ext/sival/BUILD
Remove SKU restriction from the manifest used to sign the FT provisioning firmware. This is to allow the firmware to be used across all available EarlGrey SKUs.
> [provisioning] Sign ft programs with generic manifest.

- sw/device/tests/BUILD
The fpga_cw310_sival_rom_ext env is already part of EARLGREY_TEST_ENVS.
> [sival,tests] Enable clkmgr_off_otbn_trans_test in silicon

- sw/device/tests/BUILD
This environment is included in EARLGREY_TEST_ENVS.
> [sival,envs] Remove redundant fpga_cw310_sival_rom_ext

- sw/device/tests/keymgr_dpe_key_derivation_test.c
Updated keymgr_dpe key derivation test
> Updated keymgr_dpe key derivation test

- rules/signing.bzl
Automate the offline portion of the signing procedure by providing a JSON file of signing directives.  Rather than having to manually enter a command line per file to sign, one can simply provide the json file to the `exec` command:
```
hsmtool --profile earlgrey_a0 exec signing_directives.json
```
The signing directives file will contain a command specification for each signable input provided to the `srcs` attribute of the `offline_presigning_artifacts` rule.
> [signing] More signing automation

- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aon_timer_testplan.hjson
- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_dm_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_timer_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson
This changes the test plans to comply with the guidelines.
> [sival,testplan] Remove environment suffix from bazel tests

- hw/ip/uart/README.md
Update the Chromium EC documentation URL to point to the correct location.
> [doc] Updated Chromium EC URL

- sw/device/lib/crypto/impl/rsa.c
- sw/device/lib/crypto/impl/rsa/rsa_datatypes.h
- sw/device/lib/crypto/impl/rsa/rsa_keygen.c
- sw/device/lib/crypto/impl/rsa/rsa_keygen.h
- sw/device/lib/crypto/include/rsa.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/rsa_2048_key_from_cofactor_functest.c
- sw/otbn/crypto/div.s
- sw/otbn/crypto/rsa_keygen.s
- sw/otbn/crypto/run_rsa_keygen.s
This came up as a helpful addition for some use cases; bignum division is already part of RSA key generation, so the additional mode doesn't require much more code. This PR implements and tests it for RSA-2048 (3K and 4K will come in a follow-up).
> [crypto] Add a mode to derive RSA keys using a public key and cofactor.

- doc/security/cryptolib/cryptolib_api.md
- sw/device/lib/crypto/impl/key_transport.c
- sw/device/lib/crypto/impl/key_transport_unittest.cc
- sw/device/lib/crypto/include/key_transport.h
- Implements blinded key import/export for symmetric keys.
- Removes unblinded key import/export routines.
I ended up adjusting the API a little bit here because when I gave it some thought, I think that it makes sense for ECC and RSA keys to use algorithm-specific import/export routines than generic ones, especially now that the internal structure of these keys is not exposed via the API. ECC and RSA (the only contexts in which we have unblinded keys) use different masking schemes than symmetric keys that can be very specific to the algorithm in use, so conceptually it makes more sense to me to group the code there. Custom routines already exist for importing RSA private and public keys; we still need to add export functions for RSA and import/export for ECC, which I'm tracking in this …
> [crypto] Implement symmetric blinded key import/export.

- sw/top_darjeeling/sw/device/silicon_creator/irq_asm.S
We do not have an MMIO mapped flash controller, so this access generated a fault.
> [sw/top_darjeeling] Remove flash access disablement from IRQ handler

- third_party/hyperdebug/repos.bzl
Update the version of the pre-built firmware for HyperDebug shipped with opentitantool.  This should resolve problems with HyperDebug acting as I2C device, in particular the previous firmware had issue with switching I2C addresses.
> [opentitantool] HyperDebug firmware with I2C fixes

- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
When OpenOCD issues a fence.i instruction as part of executing a program buffer through the DM the following assertion triggers:
```
[11-28 08:20:01] -I- xmsim: *E,ASRTST (/work/opentitan.integrated/hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv,976): (time 10638803280 PS) Assertion top.u_rv_core_ibex.gen_icache_scramble_asserts.IbexIcacheScrambleKeyRequestAfterFenceI_A has failed (in 11 cycles)
[11-28 08:20:01] -I- UVM_ERROR ../../../opentitan.integrated/hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv(976) @ 10638803280000: reporter [ASSERT FAILED] IbexIcacheScrambleKeyRequestAfterFenceI_A
```
I see upstream has increased this to 14 from 10 - https://github.com/lowRISC/opentitan/commit/4e615dedac018700ebd354920511b779e69e14e3 
We found that 14 wasn’t sufficient, but 20 works reliably.
> [hw,rv_core_ibex,rtl] Increase upper bound for cycles to wait in IbexIcacheScrambleKeyRequestAfterFenceI_A

- hw/ip/aes/pre_sca/prolead/README.md
- hw/ip/aes/pre_sca/prolead/aes_cipher_core_config.set
- hw/ip/aes/pre_sca/prolead/evaluate.sh
- hw/ip/aes/pre_sca/prolead/library.lib
This commit adds a couple of support files and a how to for evaluating the masking employed inside AES together with the instantiated PRNG using the PROLEAD tool.
The library file as well as the PROLEAD config file have been derived from files based on variants in the PROLEAD repository and kindly shared by @AeinRezaeiShahmirzadi.
This is related to lowRISC/OpenTitan#19091.
> [aes, pre_sca] Enable masking evaluation of AES with PROLEAD

- hw/ip/tlul/rtl/tlul_socket_1n.sv
`ASSERT_I` is not disabled during reset or when reset is unknown, so it fails erroneously.  This caused a large number of tests (32 according to the current report) in Darjeelings `xbar_main` regressions to fail.
This commit fixes that problem by changing the assertion to `ASSERT`, which is disabled when reset is not deasserted (thus it's also disabled when reset is unknown).
This is a cherry-picked commit from https://github.com/lowRISC/opentitan/pull/20571, as requested in [this comment](https://github.com/lowRISC/opentitan/pull/20571#issuecomment-1843994716).
> [tlul/rtl] Change `ASSERT_I` to `ASSERT` to fix erroneous assertion failure

- sw/otbn/crypto/montmul.s
- sw/otbn/crypto/tests/rsa_1024_enc_test.s
Implements the same algorithm we used in the specialized RSA-3072 implementation to speed up computation of R^2. This new algorithm uses Montgomery squarings instead of just repeatedly doubling R. This makes the computation of R^2 approximately 10x faster. Since right now we don't store R^2 and recompute it each time, that gives us some nice speedups for RSA verification/encryption:
- RSA-1024 encryption/verification: 4.22x speedup
- RSA-2048 encryption/verification: 4.43x speedup
- RSA-3072 encryption/verification: 4.47x speedup
- RSA-4096 encryption/verification: 4.49x speedup
Speedup for signing is much more modest because the rest of the operation is a lot longer;  I saw 1.07x for RSA-1024 signing/decryption (didn't check the others because the tests take a long time to run, but I …
> [crypto] Speed up computation of R^2 in RSA.

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_intg_err_vseq.sv
There are careful notes in the commit messages. These changes fix some tests that look much healthier on master. (Oh no!) I think the fundamental problem is that the `integrated_dev` branch has different relationships between the EDN clock and the master clock.
Not a problem, but it exposes some incorrect guesses that we made when we did OTBN DV in the first place :-) These commits should tighten things up (and will work equally well on `master`, I hope).
> [otbn,dv] Fix a couple of timing issues

- sw/device/lib/testing/BUILD
- sw/device/lib/testing/otbn_testutils_rsa.c
- sw/device/lib/testing/otbn_testutils_rsa.h
- sw/device/tests/BUILD
- sw/device/tests/otbn_rsa_test.c
- sw/device/tests/power_virus_systemtest.c
Use the same testing library for otbn_rsa_test and power_virus_systemtest. The testing library bypasses everything other than the core OTBN operation, which is helpful for tests that may have other blocks in different configurations than the cryptolib expects (e.g. entropy or HMAC).
The powervirus test is running a different RSA computation now (2K verify with slow constant computation instead of 3K verify with fast and pre-computed constant computation), so the timing of the test might change. The test doesn't run on Verilator, so I can't time it exactly. The RSA computation should get 4x faster after https://github.com/lowRISC/opentitan/pull/19755 is merged.
At some point, it might be a good idea to use something _other_ than RSA modexp for these two tasks, because RSA test data is kind …
> [crypto] Factor out OTBN RSA testing utilities.

- util/site/fetch_block_stats.py
This commit repurposes the `block_level_urls` dictionary which was previously used for badges (I believe) but is now used to look up the report to generate block diagram stats for.
> [site] Fix block diagram stats to before 2023-10-17

- hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/sram_ctrl_execution_test.c
This commit handles the case where SRAM execution cannot be enabled (because it's disabled through OTP, for example) by running the negative case again.
Resolves #19893
> [sram_ctrl,test] Enable sram_ctrl_execution_test in prod locked state

- hw/top_earlgrey/dv/tb/tb.sv
The force can mask some issues when using real silicon.
> [dv,tb] Remove force on simulation sram for patterns

- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
The key nickname was written as `ealrgrey` (L and R transposed).  Correct it to `earlgrey`.
> [cleanup] Fix a typo in the earlgrey key nickname

- hw/ip/mbx/data/mbx.hjson
- sw/ip/mbx/dif/dif_mbx.c
- sw/ip/mbx/dif/dif_mbx_unittest.cc
Modify documentation to specify that the mailbox
limit addresses are inclusive and indicate the final usable DWORD location.
Update DIF address checks accordingly.
> [mbx] Limit addresses are inclusive

- sw/device/lib/crypto/drivers/BUILD
- sw/device/lib/crypto/drivers/aes.c
- sw/device/lib/crypto/drivers/aes_test.c
- sw/device/lib/crypto/drivers/keymgr.c
- sw/device/lib/crypto/drivers/kmac.c
- sw/device/lib/crypto/drivers/otbn.c
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/aes_functest.c
- sw/device/tests/crypto/aes_gcm_functest.c
- sw/device/tests/crypto/aes_gcm_timing_test.c
- sw/device/tests/crypto/aes_kwp_kat_functest.c
- sw/device/tests/crypto/ecdsa_p256_verify_functest.c
- sw/device/tests/crypto/hkdf_functest.c
- sw/device/tests/crypto/hmac_sha256_functest.c
- sw/device/tests/crypto/hmac_sha384_functest.c
- sw/device/tests/crypto/hmac_sha512_functest.c
- sw/device/tests/crypto/kmac_functest.c
- sw/device/tests/crypto/sha256_functest.c
- sw/device/tests/crypto/sha384_functest.c
- sw/device/tests/crypto/sha512_functest.c
After reviewing the documentation of hardware used by the cryptolib, I found that most of them require input from EDN at least for masking. This PR updates all applicable cryptolib drivers to check the state of the entropy complex before running a routine that might consume entropy. Afterwards, I had to add entropy initialization to several crypto tests.
> [crypto] Add entropy complex checks to key drivers.

- sw/device/sca/aes_serial.c
Add command acknowledgement to `aes_serial_batch_alternative_encrypt` function in `aes_serial.c`
> [sca] Acknowledge command for aes_serial_batch_alternative_encrypt

- sw/host/opentitanlib/src/image/image.rs
The manifest check should allow both `manifest.signed_region_end` and `length` to be equal to the length of the binary.
> [opentitantool] Correct manifest checks

- WORKSPACE
- rules/otp.bzl
- third_party/rust/BUILD
- third_party/rust/crates/BUILD.openssl-sys-0.9.95.bazel
- third_party/skylib/BUILD.bazel
- third_party/skylib/repos.bzl
This adds a Bazel string flag build setting to enable specifing an alternative location for OpenSSL (via piping through an augmented PKG_CONFIG_PATH envar to the rust openssl-sys crate build script) so that opentitantool can be built on CentOS7 machines, which have much older native versions of OpenSSL. OpenSSL is required in order to generate OpenTitan attestation certs.
> [bazel] enable specifing alternative OpenSSL paths

- hw/ip/otbn/doc/otbn_intro.md
After https://github.com/lowRISC/opentitan/pull/20701 and https://github.com/lowRISC/opentitan/pull/19755 were merged recently, ECDSA-P256 and RSA got significantly faster. This PR updates the OTBN benchmarks with the new numbers (and also fixes a misplaced backtick I found when I tried to copy the command shown there).
> [crypto] Update benchmarks for ECDSA-P256 and RSA.

- rules/scripts/bitstreams_workspace.py
Fix up argument parsing for --create-symlink so it is treated as a boolean. Also use absolute paths for the substitute manifest, since the relative path required the symlink.
Now a bitstream cache entry can be downloaded without bazel, so long as we nullify some defaults:
```
rules/scripts/bitstreams_workspace.py \
--build-file /dev/null \
--no-create-symlink \
HEAD
```
> [bitstreams] Fix argument parsing for symlink creation

- sw/device/silicon_creator/manuf/tests/BUILD
- sw/device/silicon_creator/rom/e2e/empty_test.c
- sw/device/silicon_creator/rom/e2e/sigverify_key_validity/BUILD
- sw/device/tests/BUILD
Also cleans up some comment references to `opentitan_functest()`.
Fixes: #20098
> [bazel] Convert sigverify_key_validity to the new rules. 

- sw/device/tests/rstmgr_sw_rst_ctrl_test.c
The comment should refer to the 8 bits in the SW_RST_CTRL_N CSR.
> [tests,chip_rstmgr] Fix comments in rstmgr_sw_rst_ctrl_test

- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
The test plan had the wrong name for this test.
> [sival,pwrmgr] Fix test chip_sw_pwrmgr_normal_sleep_por_reset

- sw/device/tests/BUILD
- sw/device/tests/pwrmgr_random_sleep_all_wake_ups.c
- sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c
This test expects sensor_ctrl to have a recoverable error at bit 0, but the AST triggers an additional alert for bit 5. We clear this additional bit and this test is working, but we added a TODO against #20798.
For each wakeup add checks that the CSR in the unit issuing the wakeup is also signalling a wakeup.
> [sival,tests] Fix pwrmgr_random_sleep_all_wake_ups

- hw/ip/spi_device/dv/env/seq_lib/spi_device_stress_all_vseq.sv
We have disabled Generic / Firmware mode for `spi_device` in 02c15bb1728b689a0e670e15e0d520258ce9c2ac.  In that commit, we also disabled the tests that work only in that mode.  However, `spi_device_stress_all_vseq` still runs vseqs from tests that got disabled in the aforementioned commit.
This commit removes those vseqs from `spi_device_stress_all_vseq`.
This should resolve lowRISC/opentitan-integrated#607, though I would wait with closing that issue until we have confirmed its resolution through nightly regression results.
> [spi_device,dv] Remove Generic-mode-only vseqs from `stress_all` test

- hw/ip/dma/doc/registers.md
This adds the register documentation to the collateral. The DMA docs will be updated in a later PR.
> [hw,dma,doc] Add register collateral to the documentation

- hw/ip/aes/README.md
Thanks @m-temp for noticing the ambiguity regarding the key sideload interface.
As a drive by I also adjusted the link to the cryptolib which now as a real page in the documentation :-)
> [aes, doc] Clarify availability of sideload, change cryptolib link

- hw/top_earlgrey/BUILD
- rules/opentitan/defs.bzl
- sw/device/tests/BUILD
This adds an exec environment for the prodc SKU, and adds the exec_env to existing sival SKU test cases.
> [sival] add prodc ROM_EXT exec environment

- azure-pipelines.yml
- bazelisk.sh
- ci/scripts/run-english-breakfast-verilator-tests.sh
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/chip_smoketests.hjson
- hw/top_englishbreakfast/util/prepare_sw.py
- rules/rv.bzl
- sw/device/tests/BUILD
1. Pass the `copt` and `features` values through the OT platform transition.
2. Convert the aes_smoketest to the `opentitan_test` rule.
> [bazel] Pass `copt` and `features` through the OT transition

- hw/top_darjeeling/dv/top_darjeeling_sim_cfgs.hjson
The path used to publish the reports of top-level IPs for Darjeeling is currently wrong, as can be seen in the links of the [summary page][1]:
- ALERT_HANDLER: https://reports.opentitan.org/hw/top_darjeeling/ip_autogen/alert_handler/dv/latest/report.html
- CLKMGR: https://reports.opentitan.org/hw/ip/clkmgr/dv/latest/report.html
- PWRMGR: https://reports.opentitan.org/hw/ip/pwrmgr/dv/latest/report.html
- RSTMGR: https://reports.opentitan.org/hw/ip/rstmgr/dv/latest/report.html
All links miss the `integrated/` prefix after the domain name, so the link for `alert_handler` cannot be found and the links for `clkmgr` and `rstmgr` collide with the results for Earlgrey (`pwrmgr` does not collide because it lives under `hw/top_earlgrey/ip_autogen/pwrmgr` on `master`).
When printing the commands …
> [top_darjeeling,dv] Fix `rel_path` of top-level IPs

- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- sw/device/tests/autogen/BUILD
- sw/device/tests/autogen/alert_test.c
- sw/device/tests/sival/BUILD
- util/topgen/templates/BUILD.tpl
- util/topgen/templates/alert_test.c.tpl
Skip otp_ctrl for rom_ext since otp_ctrl CSR accesses are disabled.
This is because all otp accesses are blocked via ePMP. We expect a
more granular approach to locking OTP access, in issue https://github.com/lowRISC/opentitan/issues/20348.
The code has a TODO for changes once that issue is addressed.
> [sival,alert_test] Enable alert_test for sival_rom_ext

- sw/device/tests/sival/BUILD
Some of these tests don't exist in englishbreakfast since there are less irqs, so the englishbreakfst buid breaks unless they are removed.
Use the plic_all_irqs_test test_suite in sw/device/tests/autogen to run them instead.
> [sival,test_suite] Remove plic_all_irqs tests from suite

- sw/device/tests/autogen/BUILD
- sw/device/tests/autogen/plic_all_irqs_test.c
- util/topgen/templates/BUILD.tpl
- util/topgen/templates/plic_all_irqs_test.c.tpl
Carefully allow these excessive irqs for the correct portion of
the tests, addressing https://github.com/lowRISC/opentitan/issues/20747 so this test passes.
Add a TODO against the issue above so the code is adjusted
depending on how the issue is addressed.
Enable these tests in fpga_cw310_sival_rom_ext.
> [sival,tests] Allow excessive csrng irqs in plic_all_irqs_test

- sw/host/opentitanlib/src/app/i2c.rs
When I added new methods to the I2C trait to support HyperDebug in device mode, I declared default implementation, in order to not have to touch every other backend implementation.
It seems however, that I accidentally forgot about the wrapper layer in `src/app`, which should be able to pass along any request to switch to device mode, for the case the underlying transport supports it.  This PR adds that support.
> [opentitantool] Add missed forwarding to I2C wrappers

- third_party/hyperdebug/repos.bzl
Update the version of the pre-built firmware for HyperDebug shipped with opentitantool.  This should resolve problems with HyperDebug dropping characters if the USB host computer fails to poll for a few milliseconds, while OT is producing data at maximum speed.
Also, bugs in corner cases of GPIO monitoring have been addressed.
> [opentitantool] HyperDebug firmware with bugfixes

- sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_rollback/BUILD
- sw/device/silicon_creator/rom/e2e/defs.bzl
- sw/host/opentitanlib/src/uart/console.rs
- sw/host/tests/chip/rv_dm/src/ndm_reset_req.rs
This is a hack to provide temporary solution to address some of our flaky tests, where `UartConsole::wait_for` over-consumes data.
The hack is currently only applied to serial console. In the long term we should use async instead of all our custom event loop with mio.
Fix #20580
> [opentitanlib] make `uart_read` one character at a time

- BLOCKFILE
Since the `earlgrey_es_sival` branch has now been created, we can go ahead and create remove the RTL blockers on `master` so that so that we can make progress towards Earlgrey-PROD.M2 milestone.
> [rtl] Remove RTL blockers

- azure-pipelines.yml
- bazelisk.sh
- ci/bazelisk.sh
- ci/load-bazel-cache-write-creds.yml
- ci/scripts/check-bazel-banned-rules.sh
- ci/scripts/check-bazel-tags.sh
- ci/scripts/check-licence-headers.sh
- ci/scripts/check-module-ids.sh
- ci/scripts/clang-format.sh
- ci/scripts/get-bitstream-strategy.sh
- ci/scripts/lib/bazel_query.py
- ci/scripts/rust-format.sh
This change lets more jobs _read_ from the cache, and also allows more jobs to _write_ to the cache when running for the `master` branch.
It's being tested in [this Azure run][azure-run] which will write to the cache. A second run will need to be triggered to see if we actually read from the cache.
This change:
1. Switches usage of `./bazelisk.sh` to `ci/bazelisk.sh` in pipelines.
* This script connects Bazel to our GCP bucket containing a Bazel cache.
* This allows CI to read from the cache.
* If the `GCP_BAZEL_CACHE_KEY` variable is set, it also writes to the cache.
2. Adds downloads for the file containing cache write credentials to more jobs.
* This file is stored encrypted in Azure and cannot be downloaded by PRs from forks.
* The location to this file is automatically stored in the …
> [ci] Try to use GCP Bazel cache for more jobs

- hw/ip/keymgr_dpe/dv/env/keymgr_dpe_scoreboard.sv
- hw/ip/keymgr_dpe/dv/env/seq_lib/keymgr_dpe_smoke_vseq.sv
- hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv
Together, these fixes now mean that `keymgr_dpe`'s smoke test passes 100% (even with `-rx 10`, i.e., for 500 reseeds). Please see the commit messages for details.
> [keymgr_dpe] Fix not updating of sideload keys on invalid operation (RTL) and issues in smoke test

- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This test verify that after performing the operation of hard reset the debug module still responds correctly. This test was failing in regression due to this mistake so i modified it.
> [RV_DM] rv_dm_jtag_dtm_hard_reset_vseq

- hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv
- hw/ip/keymgr_dpe/rtl/keymgr_dpe_op_state_ctrl.sv
- hw/ip/keymgr_dpe/rtl/keymgr_dpe_pkg.sv
This fixes the problems with `keymgr_dpe` disabling reported in #20468 (thereby closes that issue) and additionally prevents the wiping of sideload and SW-visible keys during disablement, which is against `keymgr_dpe`'s specification. Please see the commit messages for details.
This supersedes #20471.
> [keymgr_dpe,rtl] Fix disabling

- third_party/python/pip.bzl
When installing python packages using pip, we use a custom script that invokes python directly. By default, python will timestamp bytecode files hence making the builds non-reproducible which is bad for CI. Python also uses a random seed for hash. This commit sets two environment variables when running pip that force python to use a deterministic seed and to use a fixed timestamp instead of the current time.
Note: we should probably get rid of our custom fork of rules python and our custom pip install script. This would be a bigger change that can be done at a later stage.
> [bazel] Make pip wheels install reproducible

- sw/device/silicon_creator/lib/epmp_state.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/doc/si_val.md
- sw/device/silicon_creator/rom_ext/e2e/lockdown/BUILD
- sw/device/silicon_creator/rom_ext/e2e/lockdown/epmp_rlb_lockdown.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/device/silicon_creator/rom_ext/rom_ext_epmp.c
- sw/device/silicon_creator/rom_ext/rom_ext_epmp.h
To provide owner applications with a more flexible memory protection configuration, I have re-arranged the ePMP settings.
Notably:
- The lockouts are moved to regions 0 & 1 to have the highest priority.
- The full FLASH/MMIO/RAM windows have been moved to the end to allow finer grained controls to be applied in the middle entries.
- The ROM_EXT region is moved and unlocked so owners can reclaim the ROM_EXT entries for their own use.
- The owner code regions are left unlocked so owners can select their own preferred arrangement.
We jump to owner code with MML=0, allowing the owner to reconfigure the unlocked entries.  The owner should set MML=1 if they need machine/user mode isolation.
> [rom_ext] Update the ROM_EXT ePMP configuration

- hw/ip/edn/doc/theory_of_operation.md
- hw/ip/edn/dv/env/edn_env_cfg.sv
- hw/ip/edn/dv/env/edn_scoreboard.sv
- hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv
- hw/ip/edn/rtl/edn_main_sm.sv
This PR clears the auto cmd FIFOs after the edn is disabled.
For more precise information check out the individual commit messages.
This PR resolves #19653
> [edn] Clear auto cmd FIFOs after edn disable

- hw/ip/edn/data/edn.hjson
- hw/ip/edn/doc/registers.md
- hw/ip/edn/doc/theory_of_operation.md
- hw/ip/edn/dv/cov/edn_cov_if.sv
- hw/ip/edn/dv/env/edn_scoreboard.sv
- hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv
- hw/ip/edn/rtl/edn_core.sv
- hw/ip/edn/rtl/edn_main_sm.sv
- hw/ip/edn/rtl/edn_pkg.sv
- hw/ip/edn/rtl/edn_reg_top.sv
- sw/device/lib/dif/dif_edn.h
This commit adds a transition from boot to SW mode after the
boot sequence is done and the ctrl.boot_req_mode flag is disabled.
For further information have a look at the individual commit messages.
This PR resolves #19655 
This PR resolves #19037
> [edn] Add transition from boot to SW mode

- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
- sw/device/tests/pwrmgr_sensor_ctrl_deep_sleep_wake_up.c
This has 2 commits in this order:
- Hold the incoming alert from AST until pwrmgr is back in active state in the `chip_sw_pwrmgr_sensor_ctrl_deep_sleep_wake_up` sim_dv test, or the wake_info won't be captured.
- Fix a CDC bug in sensor_ctrl RTL.
Fixes #20614
> [rtl,sensor_ctrl] Fix CDC bug

- hw/ip/prim/pre_dv/prim_trivium/rtl/prim_trivium_tb.sv
- hw/ip/prim/rtl/prim_trivium.sv
- hw/ip/prim/rtl/prim_trivium_pkg.sv
Previously, the lockup protection could only be disabled statically at compile time, which is less suitable in practice as it should only be allowed in very few corner cases.
Factored out of #20852 to unblock some other work.
> [prim_trivium] Allow dynamically disabling the lockup protection

- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv
- hw/ip_templates/pwrmgr/rtl/pwrmgr.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr.sv
The escalation timeout needs to persist until reset. The timeout is detected by clk_i, but the timeout is used to drive a flop clocked by clk_lc. This change adds a synchronizer from clk_i to clk_lc, and a clk_lc flop reset by rst_lc_n. The output of this flop is used to set the fault_status and as a reset request.
Fixes #20516
> [rtl,pwrmgr] Fix escalation timeout persistence

- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/flash_ctrl_clock_freqs_test.c
- sw/device/tests/flash_ctrl_idle_low_power_test.c
- sw/device/tests/flash_ctrl_mem_protection_test.c
- sw/device/tests/flash_ctrl_ops_test.c
- sw/device/tests/flash_ctrl_test.c
- Porting selective tests(see commits below for detail)
- flash_ctrl_test.c
- flash_ctrl_ops_test.c
- flash_ctrl_clock_freqs_test.c
- flash_ctrl_idle_low_power_test.c
- flash_ctrl_mem_protection_test.c
- Update testplan with bazel target
- address issue #12486
> [sival,flash_ctrl] complete flash_ctrl sival

- hw/top_earlgrey/data/pins_cw310_hyperdebug.xdc
Reduce drive strength of IOBs for the USERIOA and USERIOB connectors to 8 mA. The signal quality has not been measured directly, but it seems that there is strong enough coupling over the ribbon cables where simultaneous switching of SPI device I/Os can cause the CSB to be sampled high in the middle of a transaction, leading to spurious failures.
Bringing the drive strength down to 8 mA allowed QSPI passthrough tests to pass on my setup (up to at least 6 MHz). Further experiments may be needed to find the optimal values.
This changes only the CW310 + hyperdebug image.
> [hyper310] Reduce drive strength for USERIOA and USERIOB

- hw/ip/edn/dv/edn_sim_cfg.hjson
- hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv
This commit fixes some failing tests.
For further information check out the individual commit messages.
> [edn/dv] Fix failing tests

- hw/ip/hmac/hmac.core
- hw/ip/hmac/syn/constraints.sdc
- hw/ip/hmac/syn/hmac_syn_cfg.hjson
This PR adds the synthesis configuration files and modifies the core to support test synthesis for area estimates in kGE.
> [hmac,syn] Add cfg and constraints to support HMAC synthesis

- hw/ip/dma/syn/constraints.sdc
- hw/ip/dma/syn/dma_syn_cfg.hjson
This adds the synthesis configuration files to support test synthesis of DMA for area estimates in kGE.
> [dma,syn] Add cfg and constraints to support DMA synthesis

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_halted_vseq.sv
This commit contains some slightly changes in data_type r_data.
> [RV_DM]rv_dm_mem_tl_access_halted_vseq

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
The vseq was a reasonably magic bunch of instructions and it wasn't particularly clear to me what it was supposed to be doing. This commit adds comments about what's going on (and why we expect particular values).
I've also slightly strengthened the test:
- Randomise the arbitrary data instead of hard-coding something.
- Read back abstractdata values and check they change in the expected way.
- Make the timing waits a bit more general.
Note that the wait code was previously broken because it was calling $urandom_range with backwards arguments. The wait would always have been for zero cycles.
> [rv_dm,dv] Add comments to rv_dm_jtag_dmi_debug_disabled_vseq

- signing/README.md
This PR fixes a typo in the signing readme.
> [doc] Fix typo in signing readme

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_uart_tx_rx_vseq.sv
- sw/device/lib/testing/test_framework/ottf_console.c
- sw/device/lib/testing/test_framework/ottf_console.h
- sw/device/lib/testing/uart_testutils.c
- sw/device/lib/testing/uart_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/sival/BUILD
- sw/device/tests/uart_tx_rx_test.c
- sw/host/opentitanlib/src/app/config/hyperdebug_chipwhisperer.json
- sw/host/opentitanlib/src/app/config/opentitan_cw310.json
- sw/host/tests/chip/uart/src/main.rs
This test previously used the SPI device as its OTTF console to avoid having to use a UART (which would have been under test). This PR refactors the test to use one UART0 for the console unless it's under test, in which case we switch to UART1.
To make this work, the `uart_testutils_select_pinmux` function has been simplified to only support two output channels / interfaces: one for the console and another for DUT (device under test). This reflects the two TTYs that are available when using HyperDebug or the chipwhisperer. All of the DV simulations use a separate channel for each of the four UARTs and I didn't want to mess with that, so I've left DV alone.
Now that we can properly use the OTTF console both directions, the `kUartIdx` variable is configured using ujson commands. This …
> [test,uart] Fix uart_tx_rx_test on FPGAs by using another UART as the OTTF console

- hw/top_earlgrey/BUILD
- signing/tokens/BUILD
- signing/tokens/earlgrey_z1_prodc.yaml
- sw/device/examples/teacup_demos/BUILD
- sw/device/examples/teacup_demos/teacup_leds_demo.c
This adds a basic SiVal board LED demo.
Additionally, this fixes the prodc kms signing config.
> [sival] board LED demo

- hw/ip/mbx/dv/env/mbx_env.core
- hw/ip/mbx/dv/env/mbx_seq_item.sv
- hw/ip/mbx/dv/env/seq_lib/mbx_base_vseq.sv
- hw/ip/mbx/dv/env/seq_lib/mbx_imbx_oob_vseq.sv
- hw/ip/mbx/dv/env/seq_lib/mbx_stress_vseq.sv
- hw/ip/mbx/dv/env/seq_lib/mbx_vseq_list.sv
- hw/ip/mbx/dv/mbx_sim_cfg.hjson
> ~Don't merge until after https://github.com/lowRISC/opentitan/pull/20538 has been merged. This PR should remain a draft until that is the case~.
Builds on top of https://github.com/lowRISC/opentitan/pull/20538 ~(this PR for-now contains the changes from that PR, so ignore all but the final commit for reviewing in the meantime. Will be rebased away.)~
Configure the mailbox transaction to exceed the size of the buffer for the request message, then check that the 'Error' condition has been raised come the end of the transaction. This test currently inherits from "mbx_stress", so can still randomly activate stressors (abort, error_req, panic) during each transaction.
Closes lowRISC/opentitan-integrated#573
> [mbx,dv] Add testcase to exercise mailbox inbox oob checks

- hw/ip/rv_dm/rtl/rv_dm_dmi_gate.sv
The assertion is for the same condition as in the `pinmux_strap_sampling` module. However, as opposed to that module, there are some modifications to the `strap_en_i` signal resulting in a local version of it (`strap_en`) and the SVA needs to be formulated for that one instead.
Cherry-picking an urgent commit from https://github.com/lowRISC/opentitan/pull/20889 so it can be merged ahead of time while the other commits of that PR are under review and discussion.
> [rv_dm] Fix an assertion

- hw/top_earlgrey/data/ip/chip_uart_testplan.hjson
The `uart_rx_overflow` and `uart_watermarks` test points are both covered by the existing `uart_tx_rx_test` target.
Resolves #19871 and resolves #19872.
> [sival,uart] Add uart_tx_rx_test as target for two points

- hw/top_darjeeling/rtl/autogen/chip_darjeeling_asic.sv
- hw/top_darjeeling/rtl/autogen/chip_darjeeling_cw310.sv
- util/topgen/templates/chiplevel.sv.tpl
This allows testing the DMA's CTN host port in ASIC simulations and on the FPGA.
> [top_darjeeling] Connect DMA CTN egress port in wrapper

- sw/device/lib/testing/test_framework/ottf_common.ld
- sw/device/tests/dma_inline_hashing.c
This PR changes the second DMA transfer to randomly target the OT-internal or the CTN memory. The second transfer does not use inline hashing, thus we can test all transfer widths, which are selected randomly.
To place an array in the CTN memory, a new `.ctn_data` section was added to the linker script.
This PR build upon the changes from https://github.com/lowRISC/opentitan/pull/20899
> [dma,dv] Randomly select between OT-internal and CTN target memory

- sw/device/lib/testing/test_framework/ottf_common.ld
This was missing on the last PR
> [test] Use ram_ctn memory instead of aliased ottf_flash

- sw/device/examples/teacup_demos/BUILD
- sw/device/examples/teacup_demos/teacup_leds_demo.c
- sw/device/lib/boards/teacup_v1_3_0/BUILD
- sw/device/lib/boards/teacup_v1_3_0/leds.c
- sw/device/lib/boards/teacup_v1_3_0/leds.h
This refactors the SiVal board LED driver code into a separate library that is useable by other code.
> [boards] reorganize LED SiVal board driver code into lib

- sw/device/lib/crypto/impl/rsa.c
- sw/device/lib/crypto/impl/rsa/rsa_encryption.c
- sw/device/lib/crypto/impl/rsa/rsa_encryption.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/rsa_3072_encryption_functest.c
- sw/device/tests/crypto/rsa_4096_encryption_functest.c
The implementation looks pretty much exactly the same as RSA-2K. Most of the code churn is test data because RSA data is large.
> [crypto] Add RSA 3K/4K encryption and basic tests.

- sw/device/tests/pmod/i2c_host_ambient_light_detector_test.c
All zeros are valid values, specially during the night.
Removing this condition from error cases.
> [pmod, i2c] Fix ambient light detector flakiness

- doc/glossary.md
- hw/ip/entropy_src/README.md
- hw/ip/entropy_src/doc/theory_of_operation.md
This PR adds a few more acronym entries to the glossary and fixes some Markdown headings that were set at the wrong level.
* CP and FT: Circuit Probe and Final Test.
* ~~PTRNG: Physical True Random Number Generator.~~
* This acronym does not seem very widely known.
* Instead, I have made its expansion clearer in the entropy_src documentation.
* Is a PTRNG synonymous with a TRNG (True Random Number Generator)? Maybe we should replace.
I would like to give actual descriptions of CP and FT but don't fully understand what they mean. If anybody can help suggest some description text, that would be greatly appreciated!
> [doc] Add entries to glossary

- hw/ip/usbdev/data/usbdev.hjson
- hw/ip/usbdev/doc/interfaces.md
- hw/ip/usbdev/rtl/usbdev.sv
- hw/ip/usbdev/usbdev.core
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/dv/tb/chip_hier_macros.svh
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/chip_earlgrey_verilator.sv
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- hw/top_englishbreakfast/rtl/chip_englishbreakfast_verilator.sv
- util/topgen/templates/chiplevel.sv.tpl
This PR switch the usbdev packet buffer to a Single Port RAM implementation, in place of the current Dual Port RAM.
_Background_
Dual port memories are generally more problematic/expensive and should be avoided where possible. The packet buffer memory in `usbdev` has very little justification for being implemented as a Dual Port RAM. Although it works well on FPGA implementations, it may be unavailable on some process technologies/memory compilers.
_Proposal_
Collisions are very infrequent and we can just delay the TL-UL access when a collision occurs. `usbdev` hardware, even during active transfers, will access the packet buffer memory only every 128 clock cycles (4x oversampling, transfers 32 bits at a time) except at the end of packet reception where two writes may occur closer …
> [usbdev] Single port packet buffer

- hw/ip/keymgr_dpe/doc/theory_of_operation.md
- hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv
Technically it's possible to generate output keys from the root key (i.e., the key with boot stage 0), so it is meaningful to allow SW to set the maximum key version when invoking the advance operation that loads the root key.  Prior to this commit, `keymgr_dpe` would ignore the `MAX_KEY_VER_SHADOWED` CSR for the root key and always set its maximum key version to zero -- that's now fixed.
I ran 10x the seeds of the current `keymgr_dpe_smoke` test with this change and get a nominal pass rate (99.6%) with no errors we haven't seen yet.
@neeraj-rv: as discussed yesterday.
@bobby-rivos: If you can test this without much extra work, could you please do so?
> [keymgr_dpe/rtl] Take max key version into account for root key

- hw/ip/mbx/rtl/mbx_sysif.sv
This PR prevents:
* that the `doe_async_msg_status` gets set
* that the `doe_intr` is raised 
if the asynchronous message feature is not available or enabled.
> [hw,mbx,rtl] Gate the AsyncMsg support with feature strap and enable

- hw/dv/sv/usb20_agent/usb20_block_if.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
This PR makes minimal changes to the recently-introduced usbdev_smoke test to achieve the same behavior whichever simulation tool is used.
Introduce type casts required for strong typing with xcelium.
Use enum types not strings within usdbev_smoke_vseq; attempting to use run-time strings to identify the different enumeration values does not work, and unfortunately does not result in a build error because the strings are treated as open arrays of bytes and subject to bit-streaming casts.
> [dv,usbdev] Type fixes for xcelium testing

- hw/ip/keymgr_dpe/rtl/keymgr_dpe.sv
The logic vector that holds the key is defined as "downto" over the shares, whereas the assignment prior to this commit assigned share 0 to the more significant bits and share 1 to the less significant bits. This is likely not a problem as the shares get XOR'ed (and XOR is commutative) but it is unnecessarily complicated to verify in DV.
> [keymgr_dpe/rtl] Fix assignment of creator root key shares from OTP

- hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv
Boot stage can be at most one less than the number of supported boot stages (`DpeNumBootStages` synthesis parameter) for a successful Advance operation, and boot stage is invalid for all values *greater than* or equal to that maximum.
This inaccuracy in the RTL code did not lead to a problem in the current instantiation, where `DpeNumBootStages = 4` and thus `DpeNumBootStageWidth = 2`, where the width ensures that the value of boot stage cannot be greater than `DpeNumBootStages`.  But this does not hold generally and could cause problems if `DpeNumBootStages` is set to a different value in the future.
> [keymgr_dpe/rtl] Fix `invalid_max_boot_stage`

- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
- sw/host/opentitanlib/src/app/config/mod.rs
The HyperDebug "shield" has a number of MUX'es, buffers and other ICs (current sensors), which can be controlled through some signals in addition to what is used when e.g. simulating OpenTitan on an FPGA.
This PR introduces a new `hyperdebug_teacup.json` file, to be used with `--interface=hyperdebug` (not `hyper310`).  Both this file and existing FPGA-specific files refer to a common `opentitan.json`.
> [opentitantool] Introduce JSON config for teacup shield

- python-requirements.in
- python-requirements.txt
This new release fixes an issue with virtual VLNVs, see https://github.com/lowRISC/fusesoc/pull/5 for more information
> [ci] Update fusesoc dependency to use new lowRISC fork release

- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/flash_ctrl_write_clear_test.c
Adds test to verify 2nd write to clear (all 00s) requirement. The flash
ECC must map a 0 word value to a 0 encoding. This is an use case
requirement.
> [top_earlgrey] Add flash_ctrl_write_clear_test to DV and SiVal environments

- util/tlgen/xbar.dv.sv.tpl
- util/tlgen/xbar.py
This cherry-picks https://github.com/lowRISC/opentitan/commit/7c0e4bd0b64dd15da08d059a6c82f1cb2e6d359f from `integrated_dev` and resolves merge conflicts (the code uses `isinstance(node, <type>)` now instead of a direct comparison).
Fixes https://github.com/lowRISC/opentitan/issues/2337
--------------------------------
This change is necessary for M-to-1 crossbars, in which multiple hosts are connected to a single device.  In that case, `get_s1n_if_exist` would return the device because no `socket_1n` exists between host and device.  For how this function is used, however, we want it to return the `socket_m1` between the multiple hosts and the one device.
Note that this function seems to be used 'only' in DV code (in `xbar.dv.sv.tpl`, which is modified in this commit).  I reran `tlgen` …
> [tlgen/xbar] Generalize `get_s1n_if_exist` to `get_socket_if_exist`

- hw/ip/keymgr_dpe/doc/theory_of_operation.md
The equation previously stated that KDF applied on the child key equals KDF applied on parent key and message, but what it should state is that child key equals KDF applied to parent and message.
> [keymgr_dpe/doc] Fix equation to derive child key

- hw/ip/aes/dv/cov/aes_cov_if.sv
This resolves lowRISC/OpenTitan#20753.
> [aes,dv] Fix aes_ctrl_cg sample function declaration

- rules/manifest.bzl
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
- sw/device/silicon_creator/rom_ext/prodc/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/device/silicon_creator/rom_ext/sival/BUILD
Trying to boot a bad image often results in
`kErrorBootPolicyBadIdentifier` rather than the true error code for the bad image.  This is because the ROM_EXT tries the non-primary slot which is often empty and the "bad identifier" error is appropriate for an empty slot.
1. Determine if the error is "bad identify" for the non-primary slot and prefer the primary slot error message in that case.
2. Link the customer signing keys into the "fake signed" ROM_EXT targets to facilitate creating ROM_EXTs for FPGAs or DEV parts.
> [rom_ext] Improve error reporting for bad images

- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
- sw/device/lib/testing/flash_ctrl_testutils.c
- sw/device/lib/testing/flash_ctrl_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/rstmgr_alert_info_test.c
A minor cleanup of the test to expect an otp_ctrl error if not
in rom_ext. There is still an unexpected flash_ctrl read error
for cw310 upon entry to test_main, so it is pending from rom_ext.
Add utility to log the bits set in flash_ctrl fault status.
The issue https://github.com/lowRISC/opentitan/issues/20589 has an explanation of this test's failures.
> [sival,rstmgr] Adjust rstmgr_alert_info_test

- hw/ip/aes/README.md
- hw/ip/aes/aes.core
- hw/ip/aes/data/aes.hjson
- hw/ip/aes/doc/registers.md
- hw/ip/aes/doc/theory_of_operation.md
- hw/ip/aes/dv/sva/aes_bind.sv
- hw/ip/aes/dv/sva/aes_masking_reseed_if.sv
- hw/ip/aes/pre_sca/prolead/README.md
- hw/ip/aes/pre_sca/prolead/aes_cipher_core_config.set
- hw/ip/aes/pre_syn/syn_yosys.sh
- hw/ip/aes/rtl/aes_cipher_core.sv
- hw/ip/aes/rtl/aes_pkg.sv
- hw/ip/aes/rtl/aes_prng_masking.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/lint/top_earlgrey.waiver
- hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv
- sw/device/lib/testing/aes_testutils.c
While the LFSR-based masking PRNG seems to be able to produce randomness of sufficient quality for the masking implementation in the AES cipher core (as indicated both by our FPGA-based side-channel analysis and by the PROLEAD tool) it may be vulnerable to brute-forcing attacks on the LFSR states.
Therefore, this PR replaces the LFSR-based masking PRNG implementation inside AES with an implementation based on an unrolled Bivium stream cipher primitive as suggested in the paper:
Cassiers, "Randomness Generation for Secure Hardware Masking - Unrolled
Trivium to the Rescue" available at https://eprint.iacr.org/2023/1134
Thanks to bigger individual state chunks - the smallest non-linear feedback shift register (NFSR) has a width of 84 bits - brute-forcing attacks are rendered infeasible. The …
> [aes,rtl] Switch to Bivium-based masking PRNG implementation

- sw/device/silicon_creator/rom/e2e/boot_data_recovery/BUILD
Similar to `boot_policy_rollback` and `boot_policy_bad_manifest`, this also requires tweaks to `exit_failure` message so that it's not matched before `exit_success` message.
This is a fallout of #20592
> [rom/e2e] fix `boot_data_recovery` exit_failure matching

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/base/chip.h
- sw/device/silicon_creator/lib/boot_data.h
- sw/device/silicon_creator/lib/boot_log.c
- sw/device/silicon_creator/lib/boot_log.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_msg.h
- sw/device/silicon_creator/lib/dbg_print.c
- sw/device/silicon_creator/lib/dbg_print.h
- sw/device/silicon_creator/lib/drivers/retention_sram.c
- sw/device/silicon_creator/lib/drivers/retention_sram.h
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/nonce.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
Re-arrange the RET-RAM to be more amenable to future expansions.
1. Expand the boot_log to 128 bytes.  Include the ROM_EXT version number and the nonce value required by owner-authenticated boot_svc commands.
2. Expand the boot_svc message size to 256 bytes.  Many of the future ownership transfer commands will be larger than the current size.
3. Re-order the retention-RAM layout.
- Move the `last_shutdown_reason` immediately after the `reset_reason`.
- Place `boot_log` after `last_shutdown_reason`.
- Place the `boot_svc_msg` at the end of the creator portion of RET-RAM.
This arrangement allows us to add additional items in the middle
reserved portion of the struct and to optionally expand the
boot_svc_msg to a larger size without disrupting the locations of any
of the prior members.
> [rom_ext] Refactor retention RAM layout

- sw/host/opentitanlib/src/transport/hyperdebug/gpio.rs
- sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
- third_party/hyperdebug/repos.bzl
HyperDebug supports logic analyzer functionality, in which it will record events on a given set of gpio pins. 
`opentitantool` can then later be used to retrieve a transcript of every level change with microsecond timestamp.
This has been used by the GSC team to verify the reaction time of firmware under test.  Such testing involve typically a few handfuls of events, which can easily be transmitted via the textual protocol. However, we now plan on using the functionality for cases with 30000 events to be retrieved, which would take many tens of seconds to inefficently transmit via the console (which runs slow enough that the physical UART can keep up).
To improve performance, this CL introduces another Google-specific extension to the binary CMSIS-DAP protocol, for GPIO operations, and …
> [opentitantool] Introduce binary protocol for HyperDebug gpio monitoring

- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
Covers: https://github.com/lowRISC/opentitan/issues/20118, https://github.com/lowRISC/opentitan/issues/20117, https://github.com/lowRISC/opentitan/issues/20116 & https://github.com/lowRISC/opentitan/issues/20115
```
//sw/device/tests:otbn_randomness_test_fpga_cw310_rom_with_fake_keys (cached) PASSED in 19.1s
//sw/device/tests:otbn_randomness_test_fpga_cw310_sival         (cached) PASSED in 19.7s
//sw/device/tests:otbn_randomness_test_fpga_cw310_sival_rom_ext (cached) PASSED in 18.0s
//sw/device/tests:otbn_randomness_test_fpga_cw310_test_rom      (cached) PASSED in 18.7s
//sw/device/tests:otbn_ecdsa_op_irq_test_fpga_cw310_test_rom    (cached) PASSED in 18.9s
//sw/device/tests:otbn_ecdsa_op_irq_test_fpga_cw310_rom_with_fake_keys   PASSED in 19.3s …
```
> [sival/otbn] Added bazel target for testplans covered by randomness.

- sw/device/lib/crypto/BUILD
- sw/device/lib/crypto/otcrypto.h
This will hide the internal structure and allow callers to import only one thing.
> [crypto] Create a unified header file for the cryptolib.

- hw/dv/sv/csr_utils/csr_utils_pkg.sv
This procedure does not have to be a task because it does not control time.  Thus it can be a function, which is easier to use because it can be called from functions and not only from tasks -- and functions are easier to use because they can have a return value.
I ran this change through VCS and Xcelium as part of PR #21061 and did not notice any problems.
> [dv/csr_utils] Change `csr_peek` to function

- hw/ip/clkmgr/data/clkmgr.sv.tpl
- hw/ip/clkmgr/dv/sva/clkmgr_bind.sv
- hw/ip/prim_generic/rtl/prim_generic_clock_div.sv
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
This PR does two things:
1) it moves the tapping point for the divider feedback to *before* the `u_clk_div_buf` so that the output of `u_clk_div_buf` can be used as a hookup point for OCC insertion.
2) it inserts a hookup buffer for on all root clocks feeding into `clkmgr`. note that clock dividers still use the unbuffered root clocks since their output will have separate OCCs inserted on the `u_clk_div_buf` buffer mentioned above.
> [clkmgr] Minor restructuring to facilitate OCC hookup during DFT insertion

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/dv_base_reg/dv_base_reg.sv
- hw/ip/otp_ctrl/data/dif_otp_ctrl.c.tpl
- hw/ip/otp_ctrl/data/dif_otp_ctrl.h.tpl
- hw/ip/otp_ctrl/data/dif_otp_ctrl_unittest.cc.tpl
- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl
- hw/ip/otp_ctrl/data/otp_ctrl_scoreboard.sv.tpl
- hw/ip/otp_ctrl/doc/registers.md
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_core_reg_top.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv
- sw/device/lib/dif/dif_otp_ctrl.c
- sw/device/lib/dif/dif_otp_ctrl.h
- sw/device/lib/dif/dif_otp_ctrl_unittest.cc
So far only the hardware was able to modulate the DAI regwen. 
This updates the implementation so that the DAI can be permanently locked out via SW as well.
Fixes #20348
Note: this is WIP, the DV still needs to be updated for this.
> [otp_ctrl] Make DAI registers software-lockable

- SUMMARY.md
- doc/security/cryptolib/contributing.md
Fixes https://github.com/lowRISC/opentitan/issues/17775
Explains how the cryptolib testing setup works and what the coding conventions are and (especially) how the status codes work.
> [doc] Add cryptolib contribution guidance.

- hw/ip/rv_dm/dv/env/rv_dm_env.core
The TODO was added a long time ago because the environment doesn't actually need the whole of an rv_dm implementation. But the core file on which we depend is just a "grab the vendored rv_dm repository". It's probably not really worth putting in engineering effort to chop it up: I don't think we'll ever want to "vendor just some of the repository".
Drop the TODO message.
> [rv_dm,dv] Remove a TODO in rv_dm_env.core

- .github/workflows/cherrypick.yml
This adds a label-based automatic cherry-picking (backporting) of pull requests. An example could be seen here: https://github.com/nbdd0121/opentitan/pull/7
This requires GitHub actions to be able to create pull requests, so marking as draft until I get confirmation that this option is enabled.
> [ci] automatic cherry-picking of branches

- sw/host/opentitanlib/src/io/console.rs
- sw/host/opentitanlib/src/io/uart.rs
- sw/host/opentitanlib/src/transport/common/uart.rs
- sw/host/opentitanlib/src/uart/console.rs
- sw/host/opentitantool/src/command/console.rs
1. Add serial break support to the opentitanlib Uart trait and serial console.
2. Fix the "Starting interactive console" greeting.
> [opentitanlib] Add serial break support to the console

- hw/ip/otp_ctrl/data/otp_ctrl_img_creator_sw_cfg.hjson
- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/chip_env_cfg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
- hw/top_earlgrey/dv/tests/chip_base_test.sv
This means AST initialization is completely controlled by OTP.
Set CREATOR_SW_CFG_AST_INIT_EN to mubi4 true in
hw/ip/otp_ctrl/data/otp_ctrl_img_creator_sw_cfg.hjson.
Fixes #18974
> [dv,top_earlgrey] Remove dv flag to set OTP ast_init

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/pwrmgr_normal_sleep_por_reset_test.c
- sw/device/tests/pwrmgr_sleep_disabled_test.c
- sw/device/tests/pwrmgr_sleep_wake_5_bug_test.c
- sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c
Create test for wakeup reason 5, expected to fail due to #20798 from sw/device/tests/pwrmgr_random_sleep_all_wake_ups.c.
Skip wakeup reason 5 in pwrmgr_random_sleep_all_wake_ups, with a TODO referring to #20798.
> [sival,pwrmgr] Create dedicated test for wakeup 5

- hw/ip/pinmux/doc/theory_of_operation.md
The goal of this PR is to clarify the fact that the TAP straps are muxed with MIOs and pad attributes apply, even in LC states that continuously sample (such as RMA). This means that one can potentially disable debugging in RMA (intentionally or by mistake) by configuring those pins as output for example. I think this is an important point to keep in mind since debugging in RMA can be valuable, and in fact one could say it's the whole point of the RMA state.
Let me know if you think the text is clear/accurate.
> [pinmux,doc] Clarify that pad attributes apply to tap straps.

- hw/ip/spi_device/data/spi_device.hjson
- hw/ip/spi_device/doc/registers.md
- hw/ip/spi_device/doc/theory_of_operation.md
- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
- hw/ip/spi_device/rtl/spi_cmdparse.sv
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
- hw/ip/spi_device/rtl/spi_device_reg_top.sv
- hw/ip/spi_device/rtl/spi_passthrough.sv
- hw/ip/spi_device/rtl/spid_addr_4b.sv
- hw/ip/spi_device/rtl/spid_csb_sync.sv
- hw/ip/spi_device/rtl/spid_jedec.sv
- hw/ip/spi_device/rtl/spid_upload.sv
- hw/ip/spi_device/spi_device.core
- sw/device/lib/dif/dif_spi_device.c
- sw/device/lib/dif/dif_spi_device_unittest.cc
- sw/device/silicon_creator/lib/drivers/spi_device.c
- sw/device/silicon_creator/lib/drivers/spi_device_unittest.cc
- util/reggen/reg_top.sv.tpl
Add a new edge-to-toggle synchronizer + filter module for SPI to remove
the stringent CSB pulse width requirements that fell out of using
prim_edge_detector to detect CSB de-assertion.
spid_csb_sync produces a pulse in the sys_clk domain when a CSB-clocked
flop produces a value change, compared against the last seen value in
the sys_clk domain. The toggling flop input signal gets filtered based
on (1) whether any SPI clocks were observed and (2) whether the
toggle_en_i signal was asserted for one of those SPI clocks.
In addition to merely providing the notification that a transaction has
completed, this module is also used in the spid_upload module for
qualifying whether an uploaded command was written (for the interrupt
event).
Simplify address mode synchronization by using a common …
> [spi_device] Fix address mode synchronization

- hw/ip/dma/dv/env/dma_env.core
- hw/ip/dma/dv/env/dma_env.sv
- hw/ip/dma/dv/env/dma_env_cfg.sv
- hw/ip/dma/dv/env/dma_env_pkg.sv
- hw/ip/dma/dv/env/dma_if.sv
- hw/ip/dma/dv/env/dma_pull_seq.sv
- hw/ip/dma/dv/env/dma_scoreboard.sv
- hw/ip/dma/dv/env/dma_seq_item.sv
- hw/ip/dma/dv/env/dma_sys_tl_if.sv
- hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv
- hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv
- hw/ip/dma/dv/tb/tb.sv
This PR introduces changes to the DMA block level DV environment to support some testing of the SoC System bus when full testing has been expressly waived. It introduces a simple adapter between DMAC and a TL-UL agent/memory that responds to a 4GiB address window within the 64-bit address space, plus additional constraints to make this usable.
Note that this is based upon understanding of the behavior of the SoC System bus that has to some extent been gleaned from observations of the DMA controller itself, so it should not be regarded as complete. It does, however, offer:
- An increased chance of catching any regressions in the DMA controller logic.
- Testing of 64-bit addressing logic within the DMA controller and the DV environment (SoC System bus is the only bus with a 64-bit address …
> [dv,dma] Introduce an adapter between System bus and TL-UL agent

- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/tests/sival/BUILD
Link `chip_sw_spi_device_flash_mode` to `//sw/device/silicon_creator/rom/e2e:rom_e2e_smoke`.
> [Sival, spi dev] Flash mode test

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_stress_all_vseq.sv
This commit exclude 'rv_dm_common_vseq'from sequence list as it was failing in regression list due to this sequence. As i exclude and run for 50 seeds so it is passing.
> [RV_DM]rv_dm_stress_all_vseq

- hw/ip/keymgr_dpe/dv/env/seq_lib/keymgr_dpe_base_vseq.sv
Makes csr_wr for erase non-blocking. In some cases it seemed that the check for wait_op_done was happening after the operation had actually concluded and the dst slot was erased. Thus a false failure was occuring as for erase operations the sequence ensures that a empty key slot cannot be erased. The csr_wr being blocking was causing this delay in those cases.
> [keymgr_dpe, dv] fix for keymgr_dpe smoke failure

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_path_intg_vseq.sv
A specific file and line number reference is not stable, and it also causes issues with code generation. Update the comments to capture the intent.
> [dv,flash_ctrl] Remove specific file reference in comment

- hw/ip/spi_device/data/spi_device.hjson
- hw/ip/spi_device/doc/registers.md
- hw/ip/spi_device/doc/theory_of_operation.md
- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
- hw/ip/spi_device/lint/spi_device.waiver
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
- hw/ip/spi_device/rtl/spi_device_reg_top.sv
- hw/ip/spi_device/rtl/spid_status.sv
- hw/ip/spi_device/rtl/spid_upload.sv
- sw/device/lib/dif/dif_spi_device.c
- sw/device/silicon_creator/lib/drivers/spi_device.c
- sw/host/tests/chip/spi_passthru/src/main.rs
This PR builds on top of #21119 . Only the last two commits are new.
Previously, the Read Status Register commands behaved differently from
the SPI flash convention, holding a fixed value for every word clocked
out of the same command + rotating through all three registers for each
command. Change the commands to only return the byte targeted by the
specific command, and update the status register value at every byte
beat (8th posedge of SCK).
This brings the SPI device flash behavior in line with the convention,
which is to allow hosts to poll the same register repeatedly and see
updated values as it goes along.
Disable the scoreboard's validation of Read Status commands for now. It
uses csr_rd() to determine the resolved value, but this is impossible.
The source of truth is in the SPI …
> [spi_device] Fix up synchronization of status bits

- hw/ip/spi_device/README.md
- hw/ip/spi_device/data/spi_device.hjson
- hw/ip/spi_device/doc/programmers_guide.md
- hw/ip/spi_device/doc/registers.md
- hw/ip/spi_device/doc/theory_of_operation.md
- hw/ip/spi_device/dv/env/spi_device_env_cov.sv
- hw/ip/spi_device/dv/env/spi_device_env_pkg.sv
- hw/ip/spi_device/rtl/spi_cmdparse.sv
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spi_device_pkg.sv
- hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
- hw/ip/spi_device/rtl/spi_device_reg_top.sv
- hw/ip/spi_device/rtl/spi_p2s.sv
- hw/ip/spi_device/rtl/spi_passthrough.sv
- hw/ip/spi_device/rtl/spi_readcmd.sv
- hw/ip/spi_device/rtl/spid_upload.sv
- sw/device/lib/dif/dif_spi_device.c
- sw/device/lib/dif/dif_spi_device.h
- sw/device/lib/testing/spi_device_testutils.c
- sw/device/lib/testing/spi_device_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/spi_passthru_test.c
- sw/host/tests/chip/spi_passthru/BUILD
- sw/host/tests/chip/spi_passthru/src/main.rs
Add a 2-stage pipeline to break up the combinatorial path for passthrough reads, particularly for quad output reads.
For selected commands in the CMD_INFO tables, this pipeline samples the read data from the downstream SPI flash and latches it in spi_device, then shifts it out to the host 2 cycles later. To use it, the user would read the number of dummy cycles required for the downstream SPI flash, configure the CMD_INFO table for the same number as the downstream SPI flash, then add 2 more cycles and advertise the higher value in an intercepted SFDP read.
On quad output reads, the host thinks there are N+2 dummy cycles (which it learned from the SFDP tables advertised by spi_device), and the downstream SPI device will shift out one additional byte (which will be harmlessly dropped). …
> [spi_device] Add high-speed read pipeline to relax timing requirements

- hw/ip/dma/rtl/dma.sv
- hw/ip/mbx/rtl/mbx_imbx.sv
- hw/ip/mbx/rtl/mbx_ombx.sv
- hw/ip/mbx/rtl/mbx_sramrwarb.sv
This PR removes the direct instanzation of `prim_generic_flop_en` to use the auto-generated wrapper module.
> [hw,dma|mbx,rtl] No instantiation of prim_generic*

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
- sw/device/tests/crypto/cryptotest/json/kmac_sca_commands.h
Currently, the SCA code for KMAC uses features to improve SCA that are only available on the FPGA but not on discrete.
With this PR, the user can transmit a fpga_mode flag (c.f. #[269](https://github.com/lowRISC/ot-sca/pull/269)) allowing to specify which KMAC SCA version to use. For fpga_mode=1, the existing code is  used.
For fpga_mode=0 (i.e., discret chip), the SCA specific `sha3_ujson_absorb` function is replaced by calls to DIF:
- `dif_kmac_mode_kmac_start`
- `dif_kmac_absorb`
Moreover, the SCA specific `kmac_get_digest` function is replaced by:
- ` dif_kmac_squeeze`
By using the KMAC DIF functions, we now comply to the intended usage of KMAC.
Closes #20674
> [sca] Prepare KMAC for pen. tests on discrete

- sw/device/tests/crypto/cryptotest/firmware/trigger_sca.c
- sw/device/tests/crypto/cryptotest/json/trigger_sca_commands.h
This PR fixes a bug in how the trigger select is parsed. The ot-sca framework sends a 0 to select the HW or 1 to select the SW trigger. To parse this bit, we need to  dereference the pointer and read the value.
> [sca] Fix trigger parsing

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
- sw/device/tests/crypto/cryptotest/json/sha3_sca_commands.h
Currently, the SCA code for SHA3 uses features to improve SCA that are only available on the FPGA but not on the discrete chip.
This PR, similar to #20772, changes the sha3_sca code such that the code supports measurements on the FPGA and on the chip.
I've made the following experiments:
`fpga_mode=true` and `masks_off=true`:
`fpga_mode=off` (new mode in this PR) and `masks_off=true`:
As expected, the SCA relevant part is delayed and more noisy but we still can measure leakage. Note that I had to set `kIbexLoadHashMessageSleepCycles = 500` to get first order leakage.
> [sca] Prepare SHA3 for pen. tests

- rules/BUILD
- rules/autogen.bzl
- rules/stamp.bzl
- sw/host/opentitantool/BUILD
- sw/host/opentitantool/src/command/gpio.rs
- sw/host/opentitantool/src/command/version.rs
- util/BUILD
- util/reggen/gen_tock.py
- util/regtool.py
- util/rom_chip_info.py
- util/rom_chip_info_test.py
- util/topgen.py
- util/topgen/rust.py
- util/version_file.py
This PR reworks completely how stamping works in the repository:
- It introduces `stamp.bzl` which is a module to handle stamping. Notably, it allows rules to add `stamp` parameters
that behaves like the usual bazel conversion (0 means no stamping, 1 is always stamping, -1 follows the command line).
- It fixes several python tool and bazel rule to use this module so that they only stamp if required to do so.
- It removes some targets that were always stamping and have now become useless
**What does this change do:**
With this PR, there are two main changes:
- Certain headers generated by reggen (`autogen_hjson_header`, the tock files) do not contain stamping information anymore **by default**. If one requires stamping, see below.
- The topgen code has been updated but it is not called …
> Rework how bazel stamping work in the repository

- hw/ip/prim/lint/prim_sync_cell.waiver
- hw/ip/prim/prim_sync_cell.core
- hw/ip/prim/rtl/prim_flop_2sync.sv
- hw/ip/prim_generic/prim_generic_sync_cell.core
- hw/ip/prim_generic/rtl/prim_generic_sync_cell.sv
- hw/ip/prim_xilinx/prim_xilinx_sync_cell.core
- hw/ip/prim_xilinx/rtl/prim_xilinx_sync_cell.sv
This is an alternative solution to #21139 which is more in line with what has initially been discussed here https://github.com/lowRISC/opentitan/pull/10609.
Specifically, it adds a synchronizer cell primitive that can be used to wrap a 2 flop synchronizer from the standard cell library.
The reason why we're not converting the `prim_flop_2sync` primitive to a technology dependent one is that that module contains additional CDC randomization code for DV which we would like to keep in one place. Having a separate synchronizer cell primitive that is tech dependent allows us to do just that.
> [prim] Add synchronizer cell primitive

- hw/ip/aes/pre_syn/syn_yosys.sh
- hw/ip/kmac/pre_syn/syn_yosys.sh
- hw/ip/otbn/pre_syn/syn_yosys.sh
This package is now referenced in edn_pkg.sv.
> [pre_syn] Include csrng_pkg.sv to re-enable Yosys synthesis

- sw/host/ot_certs/src/asn1/codegen.rs
We do not have an implementation of strlen on devices.
> [ot_certs,codegen] Avoid the use of strlen for string literals.

- hw/ip/prim/rtl/prim_onehot_check.sv
This use of Impl was a workaround that I believe only really affected
some RTL that isn't in the repository(!). Get rid of the workaround:
we might be able to do it more robustly if we see the problem again.
Also add a bit of documentation comment about what's going on with the
assertion the Impl parameter was gating. It took me some time to
understand what it was trying to achieve.
As a bit of background: I only noticed this code at all because its
use of the parameter keyword isn't strictly compliant with the
SystemVerilog spec. I was about to convert it to using localparam,
when I was convinced that the usage never could have worked anyway. So
I thought it made more sense to rip it out!
> [prim] Avoid unnecessary Impl parameter in prim_onehot_check

- util/topgen/validate.py
Apparently this is not used anymore, since the bounds check is not done in the flash_ctrl rtl.
Removing it causes no change in generated code.
> [topgen,flash] Remove unused base_addr from Flash class

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_tap_fsm_vseq.sv
No functional change intended, but it avoids some warning messages from Xcelium.
> [rv_dm,dv] Add some trivial checks to the return value of randomize() calls

- doc/security/cryptolib/cryptolib_api.md
- sw/device/lib/crypto/impl/kdf.c
- sw/device/lib/crypto/include/datatypes.h
- sw/device/lib/crypto/include/kdf.h
NIST SP 800-108r1 defines multiple iteration modes for given PRF \in {KMAC, HMAC, CMAC}. Our current plan is to support:
- counter mode with HMAC
- (no-mode) with KMAC, since KMAC can process produce arbitrary-size outputs
This PR modifies the API so that these two are separate functions. _Label_ and _Context_ inputs are also added to API.
> [cryptolib] KDF API changes

- hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
- hw/top_earlgrey/dv/env/chip_env_cfg.sv
The TODOs were reminding us to verify that the numbers are right. They are! The values are stored in the hartinfo array in rv_dm.sv, which gets initialised with DebugHartInfo (defined a few lines earlier). This has reset values that match the DV code.
> [rv_dm,dv] Remove TODOs when setting reset values in env cfgs

- hw/ip/prim/util/primgen/abstract_prim.sv.tpl
It turns out that the existing code would give something of this form:
module prim_foo #(param1, param2) (arg1, arg2);
parameter prim_pkg::impl_e Impl = `PRIM_DEFAULT_IMPL;
endmodule
Unfortunately, SystemVerilog doesn't actually allow you to declare two lists of parameters like this. The presence of the #(param1, param2) list means that the Impl line gets turned into a localparam.
Annoyingly, JasperGold prints out a warning (presumably to tell the user that something surprising is happening!)
This patch changes the generated code so that everything goes in a formal parameter list. The result should actually be slightly more useful (because the person instantiating the object can pick the implementation), and tools will no longer spit out a warning.
> [primgen] Fix parameters in a primgen template

- hw/ip/edn/rtl/edn_core.sv
Not all recoverable alerts are currently sent to the alert handler. This commit changes this. Now the alert handler is notified for all the recoverable alerts.
This PR fixes a bug I found while working on #15894 
I will make sure the recoverable alerts are tested properly as part of the fix for the upcoming issue above.
> [edn/rtl] Signal all recoverable alerts

- hw/ip/mbx/rtl/mbx.sv
- hw/ip/mbx/rtl/mbx_hostif.sv
- hw/ip/mbx/rtl/mbx_sysif.sv
Previously, acknowledging an abort left all interrupts to the host side being active, as well as the interrupt to the SOC.
This PR utilizes the `hostif_control_abort_clear` signal to clear all pending interrupts to Ibex and clears the interrupt register to the SOC.
Since there is currently no proper DV environment in place, I verified that manually using the existing smoke sequence with the following flow:
1. Start a transfer from the SOC (Generates ready IRQ)
2. Let Host write an error
3. Soc Writes Abort (Generates Abort IRQ)
4. Ibex acknowledges the abort
> [hw,mbx,rtl] Clear interrupts when acknowledging an abort

- hw/ip/spi_device/data/spi_device.hjson
- hw/ip/spi_device/doc/registers.md
- hw/ip/spi_device/doc/theory_of_operation.md
- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
- hw/ip/spi_device/rtl/spi_device_reg_top.sv
- hw/ip/spi_device/rtl/spi_p2s.sv
- hw/ip/spi_device/rtl/spi_passthrough.sv
- sw/device/lib/dif/dif_spi_device.c
- sw/device/lib/dif/dif_spi_device.h
- sw/device/lib/dif/dif_spi_device_unittest.cc
- sw/device/lib/testing/spi_device_testutils.c
- sw/device/lib/testing/test_framework/ottf_console.c
- sw/device/silicon_creator/lib/drivers/spi_device.c
- sw/device/silicon_creator/lib/drivers/spi_device_unittest.cc
- sw/device/tests/rstmgr_sw_rst_ctrl_test.c
spi_device only supports mode 0 now, so eliminate the CSRs for changing modes. The TPM spec requires mode 0, and SPI passthrough is unable to support other modes as well.
Resolves #16339
> [spi_device] Remove all timing mode CSRs

- hw/ip/otbn/rtl/otbn_start_stop_control.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_tx_rx_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_usbdev_dpi_vseq.sv
These warning fixes are really simple:
- Duplicate package import
- Incorrect return type for functions
- Missing checks of return values
> [warnings,otbn,chip_level] Clean up some VCS warnings

- sw/device/tests/crypto/cryptotest/firmware/BUILD
This PR adds a bazel rule allowing to compile a signed binary that can be used for penetration testing.
> [pentest] Add SCA/FI pen. test bazel rule

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/ibex.c
- sw/device/silicon_creator/lib/drivers/ibex.h
- sw/device/silicon_creator/lib/drivers/ibex_host.c
- sw/device/silicon_creator/lib/drivers/pinmux.c
- sw/device/silicon_creator/lib/drivers/pinmux.h
- sw/device/silicon_creator/lib/drivers/uart.c
- sw/device/silicon_creator/lib/drivers/uart.h
- sw/device/silicon_creator/lib/drivers/uart_unittest.cc
1. Add function to get the mcycle timer to `ibex`.
2. Add UART receive functions to the `uart` driver.
3. Add `pinmux` support for UART receieve and reading strapping pins.
> [rom_ext,rescue] Rescue protocol infrastructure

- util/openocd/target/lowrisc-earlgrey-silicon.cfg
The earlgrey chip has the TapID in this file and fixes errors in init.
> [openocd,opentitanlib] Add earlgrey chip tapID

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_resuming_vseq.sv
This commit is just to correct typo in unavailable signal in (#21103).
> [RV_DM]rv_dm_mem_tl_access_resuming_vseq

- hw/ip/kmac/kmac.core
- hw/ip/kmac/pre_dv/kmac_reduced_tb/README.md
- hw/ip/kmac/pre_dv/kmac_reduced_tb/cpp/kmac_reduced_tb.cc
- hw/ip/kmac/pre_dv/kmac_reduced_tb/kmac_reduced_tb.core
- hw/ip/kmac/pre_dv/kmac_reduced_tb/rtl/kmac_reduced_tb.sv
- hw/ip/kmac/pre_syn/tcl/lr_synth_flow_var_setup.tcl
- hw/ip/kmac/pre_syn/tcl/yosys_run_synth.tcl
- hw/ip/kmac/rtl/kmac_reduced.sv
This PR contains two commits:
1. A new RTL module containing just the SHA3 core and the PRNG to enable SCA using e.g. PROLEAD. The main advantages of this module compared to the full KMAC design are:
- All relevant I/Os directly exposed rather through TL-UL interface. This simplifies interfacing with analysis tools. For example, the masked message (the secret to track with the analysis tools) can be provided in one shot rather than in 32-bit words. The unpacking is handled internally.
- Significantly lower circuit area which speeds up analysis.
2. A scratch Verilator testbench for this new kmac_reduced module is added. This helps understanding how to operate and properly interface the kmac_reduced module and thereby working out the configuration file for PROLEAD.
> [kmac,pre_dv] Add kmac_reduced module suitable for SCA including scratch Verilator TB

- hw/ip/kmac/pre_sca/prolead/README.md
- hw/ip/kmac/pre_sca/prolead/evaluate.sh
- hw/ip/kmac/pre_sca/prolead/kmac_reduced_config.set
- hw/ip/kmac/pre_sca/prolead/library.lib
This commit adds a couple of support files and a how to for evaluating the masking employed inside KMAC together with the instantiated PRNG using the PROLEAD tool.
This is related to #20828.
> [kmac, pre_sca] Add PROLEAD setup

- hw/ip/clkmgr/dv/env/clkmgr_scoreboard.sv
This would cause failures for the switch to ipgen, and it is best to fix it in a separate PR.
> [lint,clkmgr] Clean lint for verible

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_resuming_vseq.sv
This typo causes dv smoke test failure.
Not sure how this slipped into the repo.
> [rv_dm,dv] fix typo in seq

- sw/device/lib/crypto/drivers/otbn.c
- sw/device/lib/crypto/drivers/otbn.h
- util/otbn_build.py
This adds code to `otbn_build.py` that computes the checksum and stores it as a symbol in the binary, similar to how we store the start address of the `.data` section. When Ibex loads the binary into OTBN, it now checks that the `LOAD_CHECKSUM` register matches the precomputed value after the app is loaded.
> [crypto] Precompute CRC32 checksums for OTBN apps.

- rules/opentitan/static_library.bzl
- sw/device/lib/crypto/BUILD
Bazel currently does not have a rule which can emit a static library suitable as a release artifact.  Adapt one of the implementations discussed in the bazel community to our needs.
> [bazel] Create a static library link rule

- hw/ip/otp_ctrl/data/otp_ctrl_img_creator_sw_cfg.hjson
- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/chip_env_cfg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
- hw/top_earlgrey/dv/tests/chip_base_test.sv
This reverts commit 114807de2b6955106f80ddc1b02ac3b0f6970ce3 as discussed in the sync today
We will come back to this change and discuss its inclusion after M2 and after the NTIL environment is stable,
> Revert "[dv,top_earlgrey] Remove dv flag to set OTP ast_init"

- sw/device/lib/testing/BUILD
- sw/device/lib/testing/flash_ctrl_testutils.h
- sw/device/lib/testing/ret_sram_testutils.c
- sw/device/lib/testing/ret_sram_testutils.h
This function becomes handy when I debug test over multiple platform.
Add to ret_sram_utils
> [ret_sram, sw] Add is_testrom utils

- hw/ip/entropy_src/README.md
- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/doc/registers.md
- hw/ip/entropy_src/doc/theory_of_operation.md
- hw/ip/entropy_src/rtl/entropy_src_core.sv
- hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
Previously, the documentation and comments in the RTL suggested that the number of bits the conditioner takes to produce a single 384-bit seed would be fixed to 2048 bits. However, this is not true. In a nutshell, the number of bits consumed is equal to the configured health test window size. This commit clarifies this in the documentation as well as in the RTL.
In addition, this commit also documents in the RTL when the SHA3 conditioner block is actually active. So far, this the assumption was the conditioner was only active if explicitly triggered by the main state machine upon finishing checking the next health test window. However, the SHA3 engine is also active whenever 832 bits have been received. This condition is not tracked by the main state machine which is the reason for the CS …
> [entropy_src/doc] Document behavior of SHA3 conditioner engine

- sw/device/silicon_creator/lib/cert/asn1.c
- sw/device/silicon_creator/lib/cert/asn1.h
- sw/device/silicon_creator/lib/cert/asn1_unittest.cc
- sw/host/ot_certs/src/asn1/codegen.rs
- sw/host/ot_certs/src/template/subst.rs
The EC public key uses fixed-size integers so they must be padded. For some reason, the code only padded literals but not variables.
Those random tests should really use a seed but this has lower priority than many other items.
> [ot_certs] Make sure that EC public key creates padded integers

- sw/device/silicon_owner/tock/kernel/BUILD
- sw/device/silicon_owner/tock/kernel/src/io.rs
- sw/device/silicon_owner/tock/kernel/src/main.rs
- sw/device/silicon_owner/tock/kernel/src/pinmux_layout.rs
- third_party/tock/repos.bzl
- third_party/tock/tockloader_requirements.txt
This updates the Tock repository to just before [PR 3748](https://github.com/tock/tock/pull/3748), which updates the Rust toolchain. It updates the other repositories (libtock-rs, elf2tab, and tockloader) to the latest commits.
> [tock] Update our Tock dependencies.

- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/wycheproof_hmac_parser.py
Similar to #21148, this PR adds a test vector parser for HMAC test vectors. This one is for the Wycheproof vectors (https://github.com/google/wycheproof/tree/master/testvectors).
> [cryptotest] Wycheproof HMAC test vector parser

- hw/ip/otp_ctrl/rtl/otp_ctrl_dai.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_buf.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv
Partitions with no integrity should not report any ECC related errors. 
In order to be on the safe side, we filter error responses in that case since they may trigger (unwanted) alerts.
This allows us to disable integrity on the VENDOR_TEST partition in Earlgrey discrete without having to change the internal behavior of the OTP wrapper.
@meisnere @arnonsha with this change, no further changes are required on the closed source side. The only thing that needs to be done is remapping of `ReadRaw -> Read` and `WriteRaw -> Write`.
> [otp_ctrl] Filter ECC errors in partitions with no integrity

- sw/device/lib/crypto/drivers/kmac.c
- sw/device/lib/crypto/drivers/kmac.h
- sw/device/tests/crypto/kmac_gen_single_testvector.py
- sw/device/tests/crypto/testvectors/kmac_hardcoded.hjson
1. As I was testing KDF-KMAC, I encountered a rare bug in `little_endian_encode`. This bug occurs when the customization string is larger than 32 bytes. In this case, the encoded bit-length corresponds to 256.
According to Section 2.3.1 Integer to Byte String Encoding of NIST SP 800-185, `left_encode(x=256)` should be encoded as the byte array `[0x01, 0x01, 0x00]`, however the current implementation encodes this as `[0x01, 0x00, 0x01]`.
The same case applies to `right_encode` as well. I.e. `right_encode(x=256)` should return `[0x01, 0x00, 0x01]`. This side of the bug was circumvented earlier by reversing the order after `little_endian_encode` call. This explains why we did not catch this bug before.
1. This PR also implements a python script to generate arbitrary size KMAC vectors. It …
> [cryptolib, kmac] Fix ordering bug in `little_endian_encode`

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
- hw/dv/sv/csr_utils/csr_utils_pkg.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_flash_init_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_tap_straps_vseq.sv
This follows on from Andreas's https://github.com/lowRISC/opentitan/pull/21104 (applied on the integrated branch) and does some general cleanups that it enables.
Detailed descriptions in the individual commits. There's no big intended change to behaviour.
> [dv] Tweaks to csr_peek to make the code simpler

- BLOCKFILE
At the same time remove restrictions on changes for Earlgrey (on the `integrated_dev` branch).
> [integrated_dev] Restrict RTL changes for Darjeeling and its HW IP blocks

- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/hmac_commands.c
- sw/device/tests/crypto/cryptotest/json/hmac_commands.h
- sw/host/cryptotest/testvectors/data/schemas/BUILD
- sw/host/cryptotest/testvectors/data/schemas/hmac_schema.json
This PR adds the JSON schema file for the HMAC test harness. The schema file specifies the common test vector format output by the test vector parsers in #21148 and #21149.
> [cryptotest] HMAC test vector JSON schema

- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/usbdev_aon_pullup_test.c
This PR creates a simple test of the ability of the USBDEV AON Wake module to maintain the state of the USB pull up; required for successful for suspend/sleep/resume behavior.
The test exercises both DP and DN on supporting targets, and for each signal, the ability of the AON Wake module to hold the USB line in its current state (pull up enabled or disabled) until control of the pull ups is returned to USBDEV. Rather than powering down the USBDEV in this test and then returning it to its previous state, the test simply attempts to alter the pull up state by reprogramming USBDEV whilst the pull ups are under control of the AON Wake module. It then checks that the line state does not reflect the attempted change.
No communication with the host is required, but a physical connection is …
> [usbdev] usbdev_aon_pullup test

- hw/ip/usbdev/rtl/usbdev.sv
Four of the usbdev interrupts are changed to 'Status' interrupt types because they already exhibited that behavior and could not be cleared until the triggering FIFO/register status had been addressed.
Should close #21210, although there's no proper interrupt-related DV testing for USBDEV at present.
> [usbdev] 'Status' interrupt types

- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
Use enum types in place of string types.
String is incorrect and xcelium enforces stricter type checking than vcs with our flow.
> [dv,usbdev] Type fixes

- hw/ip/lc_ctrl/data/lc_ctrl.hjson
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_smoke_vseq.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv
We should always allow transitions into scrap, no matter whether the transition counter is maxed out or not.
In order to prevent any abuse of this unconditional transition path, we max out the counter and program the LC state to SCRAP already in the transition counter increment phase instead of programming the counter state and LC state separately in two phases as all other transitions.
This fixes https://github.com/lowRISC/opentitan/issues/13617.
> [lc_ctrl] Always allow transitions into scrap 

- sw/device/tests/crypto/cryptotest/firmware/BUILD
This PR adds the silicon_owner_prodc_rom_ext target for building the penetration testing binary.
> [pentest] Add prodc target to pentest build script

- hw/ip/otbn/dv/model/otbn_core_model.sv
- hw/ip/otbn/rtl/otbn_controller.sv
- hw/ip/otbn/rtl/otbn_start_stop_control.sv
Now that #21267 changes LC_CTRL to receive multiple RMA ack signals in parallel and the RMA req/ack signals for Flash and OTBN are no longer daisy-chained in Earlgrey, this change can and must be done because:
- A glitch into the RMA req/ack signals can no longer bypass Flash wiping before RMA entry. I.e., the checking of the RMA req signal in OTBN can thus be fully aligned with the LC_CTRL spec.
- The RMA req signal seen by OTBN is no coming from a different clock domain and OTBN will observe staggered transitions. By aligning the signal interpretation in OTBN with the LC_CTRL spec, it can actually handle that.
Note that this is a cherry pick of 388567fbf833f1504fd8d6b374b2ffd87a3c8704 from the `intergrated_dev` branch:
> According to the lc_ctrl spec, all values of non-escalation lc …
> [otbn] Fix interpretation of lc_rma_req signal values

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/sival/BUILD
And remove previous aes_new_smoketest target as it is no longer needed.
> [sival] Add chip_sw_aes_enc bazel target.

- hw/top_earlgrey/data/ip/chip_csrng_testplan.hjson
- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
Add bazel target cross references for some SV2 tests against csrng, hmac and kmac top level test plans.
Fixes https://github.com/lowRISC/opentitan/issues/20440
Fixes https://github.com/lowRISC/opentitan/issues/20443
> [sival] cross-reference SV2 tests

- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/hyperdebug/uart.rs
- third_party/hyperdebug/repos.bzl
HyperDebug uses a non-standard bulk USB protocol for serial ports, and the Linux kernel has only a rudimentary driver, meaning that the usual system calls to set parity and baud rate or generate break conditions, do not work.
This PR adds code to opentitantool to be able to issue the USB control requests directly, instead of going to the Rust serial port library.
Relevant change to Hyperdebug firmware:
https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5241764
> [opentitantool] HyperDebug support for baud rate and break condition

- hw/top_earlgrey/data/clocks_cw341.xdc
Vivado 2021.1 can choose poor placement for the SPI clock path for passthrough, resulting in timing failures at 20 MHz. Relax the SPI timing requirement to 12.5 MHz for now.
Location constraints (or a tool version upgrade) may be the better path forward in the future, but with CW310's SPI constraints still at 20 MHz, it can be the detector for timing issues for passthrough for now.
> [cw340] Relax SPI timing to 12.5 MHz

- sw/device/lib/base/macros.h
- sw/device/tests/aon_timer_irq_test.c
- sw/device/tests/otbn_ecdsa_op_irq_test.c
- sw/device/tests/otbn_irq_test.c
- sw/device/tests/otbn_randomness_test.c
- sw/device/tests/pmod/i2c_host_clock_stretching_test.c
- sw/device/tests/pmod/i2c_host_irq_test.c
- sw/device/tests/spi_device_tpm_tx_rx_test.c
- sw/device/tests/spi_host_irq_test.c
- sw/device/tests/sysrst_ctrl_in_irq_test.c
Centralize the implementation of waiting for IRQ throughout the tests.
> [Test utils ] Macro ATOMIC_WAIT_FOR_IRQ

- sw/host/opentitanlib/src/app/mod.rs
The JSON configuration files allows the declaration of aliases for SPI and I2C ports, and further allows each alias to specify clock speed and chip select (or I2C address) to use by default when that alias is used.
That feature will be used to declare which chip select to use for SPI TPM communication (as the HyperDebug default goes to the OT SPI passthrough chip select).
The TransportWrapper layer has code in `src/app/{spi,i2c}.rs` to keep track of which alias was last used for any given physical SPI/I2C port of the transport, so that the transport is instructed to change speed or other settings only when a new alias is uses, and not when the same alias is used for multiple subsequent operations.  This is a significant optimization, but also affects correctness, since a SPI port may be …
> [opentitantool] Fix for SPI chip select and opentitansession

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/ecdsa_sig_ver_schema.json
- sw/host/cryptotest/testvectors/parsers/nist_cavp_ecdsa_parser.py
- sw/host/cryptotest/testvectors/parsers/wycheproof_ecdsa_parser.py
This PR makes several minor changes to the ECDSA test vector parsing to facilitate testing. The test firmware and drivers are included in #20853.
Changes: 
1. Changed curve type tested for P-256/SHA-256 in wycheproof test vector parser (Koblitz curves (*k1) are currently unsupported, only NIST curves (*r1) are)
2. Included wycheproof test vectors for P-256 for SHA-512, SHA3-256, and SHA3-512
3. Corrected `$id` field in ECDSA test vector JSON schema to display the correct protocol name
4. Added `vendor` and `test_case_id` as new fields in the ECDSA JSON schema to allow better navigation of the test output for debugging
5. Added support for additional hash functions in JSON schema
6. Changed type of `qx`, `qy`, `r`, and `s` values for ECDSA test vectors from integers to hex strings, …
> [cryptotest] Updates to ECDSA test vector parsing

- hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson
- sw/device/tests/BUILD
Update gpio_pinmux_test to new rules for sival target.
Test check with cw310_sival and silicon_owner_sival_rom_ext targets.
> [sival,gpio] update target with new rules

- hw/dv/sv/csrng_agent/csrng_agent_cfg.sv
- hw/dv/sv/csrng_agent/csrng_device_driver.sv
- hw/ip/edn/data/edn.hjson
- hw/ip/edn/doc/registers.md
- hw/ip/edn/dv/cov/edn_cov_if.sv
- hw/ip/edn/dv/env/edn_env_pkg.sv
- hw/ip/edn/dv/env/edn_if.sv
- hw/ip/edn/dv/env/edn_scoreboard.sv
- hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
- hw/ip/edn/dv/tests/edn_alert_test.sv
- hw/ip/edn/dv/tests/edn_base_test.sv
- hw/ip/edn/rtl/edn_core.sv
- hw/ip/edn/rtl/edn_main_sm.sv
- hw/ip/edn/rtl/edn_pkg.sv
- hw/ip/edn/rtl/edn_reg_pkg.sv
- hw/ip/edn/rtl/edn_reg_top.sv
- sw/device/lib/dif/dif_edn.h
This PR adds functionality to the EDN to process status error responses from CSRNG.
For further information please have a look at the individual commit messages.
This resolves [#15894](https://github.com/lowRISC/opentitan/issues/15894)
> [edn/rtl] Process CSRNG status error responses

- hw/top_earlgrey/data/ip/chip_edn_testplan.hjson
This commit just adds the existing EDN sival tests to the respective bazel rules in the chip_edn_testplan.
> [sival/edn] Add EDN tests to bazel testpoint rule

- sw/device/tests/BUILD
- sw/device/tests/usbdev_iso_test.c
- sw/device/tests/usbdev_mixed_test.c
- sw/device/tests/usbdev_pincfg_test.c
- sw/device/tests/usbdev_setuprx_test.c
- sw/device/tests/usbdev_stream_test.c
Minor modifications to support use of kDeviceSilicon as a build target, and BUILD file changes for SiVal.
> [usbdev] Support Si device type in USBDEV tests

- hw/ip/keymgr_dpe/dv/keymgr_dpe_sim_cfg.hjson
- hw/ip/mbx/dv/mbx_sim_cfg.hjson
This PR disables the unimplemented stress tests from their respective IP simulation configuration. This removes them from the full configuration that is inferred when using `dvsim` with `all`, `all_once`, or `nightly` as the test input list.
> [mbx,keymgr_dpe] Disable unimplemented stress tests

- hw/ip/usbdev/dv/env/seq_lib/usbdev_enable_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Adds the sequence usbdev_enable_vseq, which serves as a test for the functionality of the USB device control register field 'enable.' Enabling this field activates the USB device, initiating communication with the device responding with a DP_PULLUP signal. After setting this bit, transmitted a packet, and the device successfully received and responded with an ACK handshake packet.
> [usbdev] usbdev_enable_vseq

- rules/opentitan/static_library.bzl
1. Cause the static library rule to emit a library with the the filename `lib{name}.a`, where `{name}` is the rule's name.
> [bazel] Fix static library link rule

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
Fiddly minor change, but it silences a warning from Xcelium at compile time.
> [rom_ctrl,dv] Use DV_CHECK around some calls to uvm_hdl_read

- third_party/crt/repos.bzl
Updates the CRT from 0.4.8 to 0.4.10, which includes some LLVM fixes.
> Update CRT (LLVM fixes)

- hw/ip/prim/util/primgen.py
Previously, there exist two core files named `prim_xyz.core` defining `lowrisc:prim:xyz` and `lowrisc:prim_abstract:xyz`. 
This PR uniquifies the filename for the second case to match the core  it defines.
> [primgen] Uniquify prim_abstract core file

- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/app/mod.rs
- sw/host/opentitanlib/src/io/gpio.rs
- sw/host/opentitanlib/src/proxy/handler.rs
- sw/host/opentitanlib/src/proxy/protocol.rs
- sw/host/opentitanlib/src/transport/errors.rs
- sw/host/opentitanlib/src/transport/hyperdebug/gpio.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/mod.rs
- sw/host/opentitanlib/src/transport/proxy/gpio.rs
- sw/host/opentitanlib/src/transport/proxy/mod.rs
- sw/host/opentitanlib/src/util/bitbang.rs
- sw/host/opentitanlib/src/util/mod.rs
- sw/host/opentitantool/src/command/gpio.rs
- third_party/hyperdebug/repos.bzl
Some tests need to generate a pulse of a precise duration (when testing e.g. debouncing logic), generate edges on separate GPIOs with a particular delay between the two, or initiate I2C or SPI communication at a precise time after RESET has been released.
For such cases, better precision can be achieved if the HyperDebug EC does the timing, rather than Rust (or go-language) scripts managing the clock, and sending separate USB requests with millisecond latency for each operation.
This PR adds a feature to produce arbitrary waveforms on multiple GPIO pins, it is easy to generate pulses or edges on multiple pins.  For I2C/SPI communication with precise timing, the callers will have to themselves construct the waveform, which will be bit-banged by HyperDebug, (rather than generated using the …
> [opentitantool] Support for bitbanging

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/BUILD
- sw/host/cryptotest/testvectors/data/schemas/hash_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/nist_cavp_hash_parser.py
- third_party/nist_cavp_testvectors/repos.bzl
This PR pulls in the NIST test vectors for SHA2, SHA3, and SHAKE, and includes the associated parser and JSON schema. All algorithms in these three families of hash functions were able to share a single parser and JSON schema.
> [cryptotest] Add NIST test vectors and parser for SHA2/3, SHAKE

- sw/device/lib/crypto/include/mac.h
This PR improves a couple misleading API descriptions in cryptolib:
HMAC: Correct the description to say that the caller must set the tag size to be the size of the output of the hash function they are using, not always 32 bytes.
KMAC: Clarify the key sizes that are supported.
> [crypto] improve API descriptions for HMAC and KMAC

- hw/ip/prim/util/primgen.py
Add a version number to the `prim_abstract` generated core files to have a fully-specified VLNV string.
> [primgen] Use a fully specified VLNV string for prim_abstracts

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
The code in rom_ctrl_corrupt_sig_fatal_chk_vseq.sv was not quite right: it ignored the return value of mubi4_test_invalid, and never actually assigned anything to rand_var.
This change switches things to do what I think was originally intended.
(@msfschaffner: I'm adding you as a reviewer because you touched these lines recently. As far as I can tell, they were silly before you touched them! But I thought you might know some context that I'm missing)
> [rom_ctrl,dv] Tweak randomisation of bad mubi4_t values

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_common_vseq.sv
I suspect that there will be several sequences which could use this change. This is just meant to be an easy framework to implement the same thing for other sequences.
The change in this commit avoids two timeouts:
(1) If you try to start a CSR access right after coming out of reset,
you crash into a timeout in csr_spinwait. This timeout is
default_spinwait_timeout_ns and is configured in csr_utils_pkg.sv
with an initial value of 10ms.
(2) If you wait a little after coming out of reset to avoid *that*
timeout, you crash into a timeout for the run phase (20ms). One
solution would be to increase that timeout but that seems a bit
tricky and I suspect it shows that we're using UVM in a slightly
unconventional way here.
A simpler bodge is to run fewer iterations of the test, so that's
what …
> [rom_ctrl,dv] Start CSR accesses later in passthru_mem_tl_intg_err

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
This avoids a warning from Xcelium. Doing so also means that we don't have to bother with the call to uvm_hdl_check_path, since the uvm_hdl_force call will return 0 if the path is invalid.
> [rom_ctrl,dv] Check returns of uvm_hdl_force/uvm_hdl_release

- azure-pipelines.yml
This PR enables the `earlgrey_es_sival` branch to write bitstreams to the cache.
I'm not sure if this will actually work:
* I haven't tracked where the GCP key is downloaded for this job just yet.
* The bucket it's writing to is still `bucketURI: "gs://opentitan-bitstreams/master"` - will this cause issues?
> [ci] Enable writing to the bitstream cache in sival

- sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
- sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
- sw/device/tests/crypto/cryptotest/json/kmac_sca_commands.h
- sw/device/tests/crypto/cryptotest/json/sha3_sca_commands.h
This PR fixes two bugs that were previously introduced:
- Use data field for fpga_mode & masks_off instead of array. This is related to #20946 
- Revert removal of kmac_reset() in batch mode. This was accidently removed in #20772.
> [pentest] Fix KMAC SCA code

- sw/host/opentitanlib/src/tpm/driver.rs
- sw/host/opentitantool/src/command/i2c.rs
- sw/host/opentitantool/src/command/spi.rs
- sw/host/tests/chip/spi_device_tpm_test/src/main.rs
- sw/host/tpm2_test_server/src/interface.rs
- sw/host/tpm2_test_server/src/main.rs
Google security chips deviate from the TPM standard.  Because the chips are not able to meet the requirements for response/processing time, they employ an additional "ready" signal, generated by the GSC to indicate when it has finished processing the most recent request, and is ready to receive a new request.
This CL adds an optional flag `--gsc_ready` to `opentitantool {spi,i2c} tpm` and to `tpm2_test_server`.  Omitting this flag will result in `opentitantool` use the standard TPM protocol, specifying the flag will make `opentitantool` wait for the Google-specific ready signal at each transaction.
It is worth noting that the existing TPM driver for I2C is not implementing the protocol specified by TCG, but instead a Google-specific protocol, as the first use of I2C by legacy Titan GSC …
> [opentitantool] Add support for Google TPM "ready signal"

- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Adds the USB device test 'usbdev_in_trans,' designed to validate the device functionality for IN transactions. This test also verifies the 'in_sent' register by writing to a specific endpoint's 'in_sent' field. Upon writing, clears the 'in_sent' register when written with a value of one.
> Usbdev in trans vseq

- sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
Add text messages to the numerical codes received from HyperDebug.  The binary protocol is shared with other debugger devices using the same codebase as HyperDebug, which unfortunately prevents us from splitting some of the codes further into more specific cases (such as repeated "not ready" from flash chip, as opposed to other kinds of timeouts.)
Also, increase the timeout for first response packet via USB to 1.1s, because the HyperDebug firmware has 1s timeout when repeatedly trying to poll the "ready bit" on EEPROM/flash devices, and we want to wait to receive a possible "timeout" response from HyperDebug.
> [opentitantool] Better SPI error messages from HyperDebug

- hw/ip/otp_ctrl/rtl/otp_ctrl_dai.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_buf.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv
This fixes an error due to a comparison between different enum types. We can use casting here since the error patterns in question have the same encodings in both enums.
> [otp_ctrl] Fix OTP_CTRL enums

- hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
- hw/ip/kmac/rtl/kmac.sv
- hw/ip/kmac/rtl/kmac_pkg.sv
- hw/ip/otbn/rtl/otbn_start_stop_control.sv
- hw/ip/rom_ctrl/rtl/rom_ctrl.sv
This fixes #20887.
Note that #10071 can only be closed once all autogen'd IPs have been transitioned to IPGen, since the annotation checker does not look in the right RTL locations otherwise. I.e., there are some IPs like `pinmux` which are correctly annotated, but will fail since the top-specific Hjson resides in a different subtree than the associated RTL (which will be fixes once transitioned to IPGen).
> [regtool/rtl] Add missing CM annotations

- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize_3.c
This adds a utility function to compute attestation key IDs that are used in the "serial number" and "subject key ID" fields of attestation certificates. The attestation key ID is derived from an attestation public key using a KMAC KDF operation as described in [NIST SP 800-56C](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr2.pdf#page=39&zoom=100,93,562).
Additionally, this updates the UDS certificate generation flow in the personalization firmware to include the creator pubkey ID field in the TBD certificate generation.
> [ot_certs] add creator pubkey ID (serial number) to UDS certificate

- hw/ip/tlul/README.md
- hw/ip/tlul/rtl/tlul_fifo_async.sv
Use ReqDepth and RspDepth that the submodule 'prim_fifo_async' supports.
Although the submodule includes an assertion to check for validity, the assertion is eliminated on some targets such as Verilator simulations and synthesis.
Also correct a module name in documentation.
> [tlul] Choose valid default depths

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/BUILD
- sw/host/cryptotest/testvectors/data/schemas/ecdh_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/wycheproof_ecdh_parser.py
This PR adds the ECDH wycheproof test vector parser for testing the cryptolib ECDH implementation. Like #20793 did for ECDSA, the JSON outputted by the test vector parser is intended to be used by the Rust driver in #20877 to submit tests to the device.
A few tests had to be manually excluded because `Crypto.Util.asn` failed to reject invalid DER OIDs. More annoyingly, the tests that failed have a different test case ID in the current upstream master wycheproof than in the one currently in `//sw/vendor`, so the comments (but not the logic) in the parser will be outdated if we update the vendored wycheproof or switch to a non-vendored fetch.
> [cryptotest] add wycheproof ecdh test vector parser/schema

- sw/device/lib/crypto/impl/ecc/ecdh_p256.c
- sw/device/lib/crypto/impl/ecc/ecdh_p256.h
- sw/device/lib/crypto/impl/ecc/ecdsa_p256.h
- sw/device/lib/crypto/impl/ecc/p256_common.h
This PR 
- adds the `OT_WARN_UNUSED_RESULT` macro before `status_t` functions of p256 files to protect against a caller forgetting to check and forward the error code.
- puts P-256 ECDH modes in an anonymous enum to match the other files.
- addresses issues which came up in the discussion of https://github.com/lowRISC/opentitan/pull/21067 .
> [cryptolib] Add unused result before status_t functions in P-256 headers

- sw/host/opentitanlib/src/tpm/driver.rs
- sw/host/opentitantool/src/command/i2c.rs
Is seems that PR #21289 introduced a bug that prevents `opentitantool i2c tpm ...` from working at all.
This PR restores the proper use of `Any<>` to allow passing the I2C driver object to the TPM command handler in the way that it expects.
Also, a logic condition was accidentally reversed, making the new `--gsc-ready` flag ineffective for I2C.
> [opentitantool] Fix crippled I2C TPM support

- hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson
- sw/device/lib/testing/sysrst_ctrl_testutils.c
- sw/device/lib/testing/sysrst_ctrl_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/sysrst_ctrl_ec_rst_l_test.c
- sw/device/tests/sysrst_ctrl_in_irq_test.c
- sw/device/tests/sysrst_ctrl_inputs_test.c
- sw/device/tests/sysrst_ctrl_outputs_test.c
- sw/host/tests/chip/sysrst_ctrl/BUILD
- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs
The existing sim_dv test was too DV specific so I created a test from scratch. I intentionally avoid backdoor writes to make it simpler and instead leverage the GPIO monitor functionality. The test goes further than DV and does the optional part of the testplan: make sure the EC reset stretch functionality works.
Fixes #21177, fixes #21178
> [sival] Port sysrst_ctrl_ec_rst_l

- hw/dv/tools/dvsim/vcs.hjson
Parallel merge needs a very powerful machine, and serial merge is fine for many blocks. Leave a comment for how to enable parallel in case someone needs it.
Fixes #21522
> [dv,cov_merge] Do serial coverage merge for vcs

- hw/top_earlgrey/data/ip/chip_uart_testplan.hjson
This PR changes the description (and name) for the UART chip test plan.
The original test description suggests running the test at a random Baud rate on one of the UARTs, but it seems more useful to test all of the Bauds on all of the UART instances.
Is this a change we actually want? It seems that the DV tests are more random-style than exhaustive, so the original description fits for DV more than it does for SiVal.
This PR also connects the test plan to the Bazel target.
> [sival,uart] Update UART sival test plan for baud rate test

- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/firmware/hash.c
- sw/device/tests/crypto/cryptotest/firmware/hash.h
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/hash_commands.c
- sw/device/tests/crypto/cryptotest/json/hash_commands.h
- sw/host/cryptotest/ujson_lib/BUILD
- sw/host/cryptotest/ujson_lib/src/hash_commands.rs
- sw/host/tests/crypto/hash_kat/BUILD
- sw/host/tests/crypto/hash_kat/src/main.rs
This PR adds the test harness for the SHA2/3 and SHAKE hash functions, using the NIST test vectors added in #21261. The test implementation contains a Rust host-side test driver, a device-side firmware handler, and a uJSON API allowing the two to communicate.
The SHA-2 tests test both the oneshot API and the stepwise APIs (init, update, final). At present, SHA-3 and SHAKE only support the oneshot API, so it is the only one tested.
The hash tests take about an hour to run in total, so this will certainly need to go in the nightly CI run eventually.
~Dependent on #21261~
> [cryptotest] Test harness for SHA2/3 and SHAKE

- hw/ip/usbdev/data/usbdev.hjson
- hw/ip/usbdev/doc/registers.md
- hw/ip/usbdev/rtl/usb_fs_nb_in_pe.sv
- hw/ip/usbdev/rtl/usb_fs_nb_out_pe.sv
- hw/ip/usbdev/rtl/usb_fs_nb_pe.sv
- hw/ip/usbdev/rtl/usbdev.sv
- hw/ip/usbdev/rtl/usbdev_reg_pkg.sv
- hw/ip/usbdev/rtl/usbdev_reg_top.sv
- hw/ip/usbdev/rtl/usbdev_usbif.sv
- sw/device/lib/dif/dif_usbdev.c
- sw/device/lib/dif/dif_usbdev.h
- sw/device/lib/dif/dif_usbdev_unittest.cc
This PR proposes register modifications to the usbdev to support resume from Deep Sleep; it addresses #19042 by introducing the ability to read and to restore the Data Toggle bits of all of the IN and OUT endpoints.
~~Comments and guidance are requested on the way that the registers are described, and whether this is apt to cause any issues for our automated CSR tests. Specifically, there's some inelegance in that the register interface contains unnecessary flip flops that mirror the state of the data toggle flops themselves (which are in the packet engines), and the fact that there are register bits at all for the 'mask' bits in the upper half of each register; these 'mask' bits control which of the lower bits cause data toggles to be modified, and which are left unchanged~~.
The …
> [usbdev] Save/restore data toggles for Deep Sleep

- hw/ip/clkmgr/dv/env/seq_lib/clkmgr_peri_vseq.sv
Extend the wait time between updates to CLK_ENABLES csr, or the changes won't be sampled by slower clocks.
> [dv,clkmgr] Fix failure in clkmgr_peri_vseq

- sw/device/tests/otbn_mem_scramble_test.c
The error message should report the number of integrity errors that generated an interrupt but was instead reporting the number of correct memory reads.
> [test, otbn] Fix misleading otbn_mem_scramble_test error message

- hw/dv/dpi/usbdpi/usbdpi.c
Fix SYNC signal generation on SETUP and OUT DATA packets. Non-initial SYNC omitted the first K state and usbdev coped because it responds to the final 6 bits of the SYNC signal rather than requiring detection of the full 8 bits.*
Previous SYNC signal at start of DATA transaction/packet shows [J]KJKJKJKK at the position of the red marker:
Note that the first 'J' is transmitted but since the bus is already in the Idle/J state, there is no transition.
The invalid signal results from advancing the `bit` number even when transitioning from ST_EOP to S_SYNC
The above signals show three distinct packets, separated by the driver output enable on the bottom row. The packets are Start Of Frame (SOF), SETUP and DATA. The invalid SYNC generation occurs on any DATA packet being transmitted by the …
> [usbdpi] Fix SYNC generation

- sw/device/lib/testing/BUILD
- sw/device/lib/testing/usb_logging.c
- sw/device/lib/testing/usb_logging.h
- sw/device/tests/BUILD
- sw/device/tests/usbdev_logging_test.c
Prototype code for logging over USB. This PR details an extension to the usbdev testing code which supports conventional textual logging as if over a UART, but because usbdev operates at 12Mbps it is able to offer much higher throughput and - perhaps more importantly - lower impact CPU performance and latency in servicing other events/devices. The UART offers only 115.2kbaud by contrast. Redirection of stdout is achieved using base_set_stdout() and then LOG_x() etc may be used unmodified.
Also included is a top-level test that exercises a number of concurrent serial streams (presented as ttyUSBx devices on a Linux host), allowing us to model the Google use case of multiple UART streams simultaneously.
Any feedback and suggestions welcome.
UPDATE: Thanks all for the feedback and …
> Initial USB logging code

- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/usbdev_config_host_test.c
This PR creates a simple test of USBDEV detection, identification and configuration by the host/DPI model, indicating that bidirectional communication with the host is working.
Control Transfers from the host are received and processed, identifying the USB device as a single 'simpleserial' device to the host, and a Linux-based host will usually present the device as '/dev/ttyUSBx'.
No further communication with the host occurs during this test and no additional software beyond the driver stack is required on the host side for this test to pass. The test has been checked on the CW310 and in chip simulation.
See [#19966](https://github.com/lowRISC/opentitan/issues/19966)
> [usbdev] usbdev_config_host test

- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
This commit fixes the rng_vseq test which was failing because the ht_threshold_scope was set to an invalid mubi value in the config. Whenever the entropy_src enters an alert state due to the configuration, it reconfigures the DUT in a safe way to run the test. However, for the ht_threshold_scope the same value is kept. The issue here is, that when the initialization fails because of the ht_threshold_scope we still have to set it to a safe value.
> [entropy_src/dv] Fix a failing rng_vseq test

- sw/device/lib/crypto/drivers/kmac.c
- sw/device/lib/crypto/drivers/kmac.h
- sw/device/lib/crypto/impl/mac.c
- sw/device/lib/crypto/include/mac.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/kmac_functest.c
- sw/device/tests/crypto/kmac_sideload_functest.c
- Tweak internal `kmac_kmac_128/256` functions so that key can also be passed with sideload option. Here, I added `hw_backed` field to `kmac_blinded_key_t` struct, which we previously used to represent the key shares internally. When `kmac_kmac_128/256` is invoked with `hw_backed = kHardenedBoolTrue` option, then KMAC control registers are configured to use sideload key instead. Plus, there are also few new checks on the `key` struct.
- Modify `otcrypto_kmac` function that is accessible to the external callers through cryptolib API. In order to support sideload, this function calls keymgr functions to generate the key before KMAC call and clears it after the KMAC operation.
- Added a dedicated functest for KMAC sideloading. This test runs the KMAC operation twice and compares the two …
> [cryptolib, kmac] Add sideload support to KMAC driver

- hw/ip/kmac/pre_dv/kmac_reduced_tb/kmac_reduced_tb.core
- hw/ip/kmac/pre_dv/kmac_reduced_tb/rtl/kmac_reduced_tb.sv
Having such a check is beneficial for simulating actual netlists prior to the analysis using PROLEAD to capture cases where synthesis fails.
> [kmac,pre_dv] Check digests produced by kmac_reduced_tb using DPI model

- sw/device/lib/crypto/drivers/kmac.c
- sw/device/lib/crypto/drivers/kmac.h
- sw/device/lib/crypto/impl/rsa/BUILD
- sw/device/lib/crypto/impl/rsa/rsa_padding.c
Adds support for SHA-3 hash functions for RSA with the PKCS#1 v1.5 padding mode. The argument validation in `sw/device/lib/crypto/impl/rsa.c` already supports them, but the padding implementation did not, resulting in an invalid argument error that was difficult to trace.
Tests for these hashes will be added in a later PR alongside the rest of the RSA tests as part of the ongoing cryptotest effort.
> [crypto] Support SHA-3 hashes in RSA PKCS#1 v1.5 padding mode

- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
This commit links two chip-level entropy_src tests to the bazel tag in the test plan.
Closes #20142
Closes #21391
Closes #20144
> [chip-level/entropy_src] Link bazel tests in testplan

- sw/ip/mbx/dif/dif_mbx.c
- sw/ip/mbx/dif/dif_mbx.h
- sw/ip/mbx/dif/dif_mbx_unittest.cc
Add a DIF function to read out the IPI configuration that is set from the requester side.
> [mbx/dif] DIF function to access IPI configuration

- SUMMARY.md
- sw/device/silicon_creator/lib/dbg_print.c
- sw/device/silicon_creator/lib/dbg_print.h
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/doc/rescue.md
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/device/silicon_creator/rom_ext/rescue.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
Implement the shell of the rescue protocol.
1. Trigger rescue entry via the serial break condition.
2. Support Xmodem-CRC for uploading rescue images or other resources.
3. Support Xmodem-CRC for downloading selected info from the chip.
4. Support requesting the rescue mode via a set of 4-byte identifiers. These include:
- `RESU`: The default rescue mode (ie: upload firmware).
- `BREQ`: Request to upload a boot_svc request message.
- `BRSP`: Request to download the boot_svc response message.
- `BLOG`: Request to download the boot_log data structure.
- `OWNR`: Request to upload an owner block.
- `REBO`: Request to exit rescue mode and reboot.
- Currently, BREQ, BRSP, BLOG and REBO are implemented.
- The RESU command erases and flashes the data in partition A.  The appropriate flash limits …
> [rom_ext, rescue] Implement the rescue protocol

- rules/opentitan/static_library.bzl
- sw/device/lib/crypto/BUILD
Bazel currently does not have a rule which can emit a static library
suitable as a release artifact.  Adapt one of the implementations
discussed in the bazel community to our needs.
> [bazel, cherry-pick] Create a static library link rule 

- hw/ip/entropy_src/doc/programmers_guide.md
This commit adds a small section to the programmers guide where the conditioner bypass in the firmware overide insert mode is explained.
This is a follow up PR to #21369
> [entropy_src/doc] Document how to use fw_ov mode with bypass

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_progbuf_busy_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This commit verify that accessing progbuffer while abstract command is executing causes abstractcs.busy set to 1.
> [RV_DM]rv_dm_progbuf_busy_vseq

- sw/device/lib/dif/autogen/dif_adc_ctrl_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_alert_handler_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_aon_timer_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_csrng_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_edn_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_entropy_src_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_flash_ctrl_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_gpio_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_hmac_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_i2c_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_keymgr_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_kmac_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_otbn_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_otp_ctrl_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_pattgen_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_pwrmgr_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_rv_timer_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_sensor_ctrl_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_spi_device_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_spi_host_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_sysrst_ctrl_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_uart_autogen_unittest.cc
- sw/device/lib/dif/autogen/dif_usbdev_autogen_unittest.cc
- util/make_new_dif/templates/dif_autogen_unittest.cc.tpl
This PR makes a small correction to the template for the auto-generated DIF unit test code, and regenerates the affected files.
- In the auto-generated unit test code, check the returned type of the first interrupt against its actual type; previously it seems all initial interrupts have been of Event type so these tests passed accidentally.
With planned I2C changes, this shall no longer be true.
The code for mapping the hjson key value to the DIF constant mirrors that in `dif_autogen.c.tpl`
> [dif] Fix type checking of first interrupt

- sw/device/silicon_creator/lib/boot_log.c
- sw/device/silicon_creator/lib/boot_log.h
- sw/device/silicon_creator/lib/drivers/retention_sram.h
Re-arrange the retention RAM as discussed in the SW WG meeting on 2024-02-13:
Locate the boot_svc message first, followed by reserved space, followed by the boot_log and last_shutdown_reason. This arrangement allows us to grow the boot_svc message (growing "down" into the reserved space) if needed and to add additional fields at the end (growing "up" into the reserved space).
> [rom, rom_ext] Re-arrange retention RAM

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_kmac_err_chk_vseq.sv
This PR has three commits, but the first two are actually from separate PRs, which should be merged first (#21335 and #21336). The commit message for the last commit (the reason for this PR) is below:
The main change here was in `rom_ctrl_corrupt_sig_fatal_chk_vseq`, where
I've squashed the contents of the `chk_fsm_state` task into the
`check_for_alert` task. This means that we can combine the explicit
calls to the two tasks that appeared in that vseq.
I suspect that the original author intended to do the FSM state check
every time, but the code didn't quite do that. In this commit, I'm
using a `check_fsm_state` argument in order to reproduce the behaviour
that we have.
It turns out that the contents of this task were also inlined in
`rom_ctrl_kmac_err_chk_vseq`. To get rid of the …
> [rom_ctrl,dv] Minor tidy-up in rom_ctrl vseqs

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
- hw/dv/sv/dv_lib/dv_base_env_cfg.sv
Declare the intention to issue a random reset in the near future in order to halt transaction generators. Without this there are occasionally failure for stress_all_with_rand_reset because of timing out waiting for no outstanding accesses, either because the generators have too many pending transactions, or because of a single cycle with no outstanding accesses followed by more accesses.
Fixes #21531
> [dv,random_reset] Enhance handling of random resets

- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/usbdev_aon_wake_reset_test.c
- sw/host/tests/chip/usb/BUILD
- sw/host/tests/chip/usb/mod.rs
- sw/host/tests/chip/usb/usb.rs
- sw/host/tests/chip/usb/usbdev_aon_wake.rs
This test is a bit tricky because it requires to manually suspend the device and issue a reset while in suspended state. On linux, suspended a device is not trivial and requires poking at various sysfs files, and resetting a suspended device is not possible. Instead, the approach used here is to directly talk to the parent hub of the device and issue suspend/reset requests directly. This is a bit risky in that it assumes that linux won't mess with the hub state while we do that but that seems to work. As stated in the tests, we could make this actually safe by manually unbinding the device from the driver first to ensure no intereference but again this requires some sysfs magic and more persmissions.
A side effect of this is that the test requires access not only to the USB device under …
> [usbdev,sival] Implement usbdev_aon_wake_reset

- quality/BUILD.bazel
- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/xmodem.c
- sw/device/silicon_creator/lib/xmodem.h
- sw/device/silicon_creator/lib/xmodem_testlib.h
- sw/host/tests/xmodem/BUILD
- sw/host/tests/xmodem/lrzsz_test.rs
- sw/host/tests/xmodem/xmodem.rs
1. Create an Xmodem-CRC implementation for firmware.
2. Bindgen the C implementation to rust for testing.
3. Test the C implementation against the classic Xmodem implementation supplied by the `lrzsz` programs.
(cherry picked from commit 791b521bf9b779040c82a9b89da8f55897815c10)
> Cherrypick [rom_ext, rescue] Add a firmware Xmodem implementation

- sw/device/silicon_creator/manuf/lib/BUILD
This test has been very flaky recently and is causing PR CI to fail.
https://github.com/lowRISC/opentitan/issues/19086
> [ci] Disable personalize_functest in CI

- azure-pipelines.yml
- ci/azp-private.yml
Currently we have backport branches running CI for a push, but that's already covered by PR CI run, so it's duplicated work. Disabling it.
> [ci] disable CI on backport-* branches

- sw/device/lib/crypto/impl/ecc/ecdh_p256.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p256.c
- sw/otbn/crypto/p256_ecdh.s
- sw/otbn/crypto/p256_ecdsa.s
- sw/otbn/crypto/p256_isoncurve.s
- sw/otbn/crypto/p256_verify.s
- sw/otbn/crypto/p384_verify.s
- sw/otbn/crypto/tests/BUILD
- sw/otbn/crypto/tests/p256_ecdsa_verify_test.exp
- sw/otbn/crypto/tests/p256_ecdsa_verify_test.s
Fixes a bug in P-256 and P-384 found by @RyanTorok via the Wycheproof tests that would have caused the implementation to accept invalid signatures with r=0. Thanks Ryan! :clap: 
Previously, the "fail" jump point for certain paths (e.g. r and s out of range in the signature) copied all-zero values into `x_r` and expected the comparison with `r` to fail. But that doesn't work if `r` is zero; as far as I can tell from a quick sift through the code history, the code originally didn't check the range of `r` and likely expected this to happen on the Ibex side. However, when I went through and implemented the Ibex side, I didn't realize this, and I added the checks for the range of `r` on the OTBN side, jumping to "fail" without inspecting the logic carefully enough and thereby introducing the …
> [crypto] Fix a broken "failure" branch in P-256 and P-384.

- hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson
- sw/device/lib/testing/json/gpio.c
- sw/device/lib/testing/json/gpio.h
- sw/device/tests/BUILD
- sw/device/tests/gpio_intr_test.c
- sw/host/opentitanlib/src/test_utils/gpio.rs
- sw/host/tests/chip/gpio_intr/BUILD
- sw/host/tests/chip/gpio_intr/src/main.rs
This PR includes
- gpio input mode interrupt test
- gpio output mode interrupt test
Since gpio interrupt only depends on its input, for output mode test, pinmux configured s.t. it loopbacks to the gpio input.
For each mode, four tests are included (Rising edge, Falling edge, level high and level low).
> [sival,gpio] gpio interrupt test

- hw/top_earlgrey/BUILD
- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
- sw/host/opentitanlib/src/backend/mod.rs
This PR:
- adds a new `teacup` backend to opentitantool which corresponding to hyperdebug using the `hyperdebug_teacup.json` configuration file
- update the silicon execution to use the teacup interface
> [bazel,silicon] Use `teacup` interface for silicon exec_env

- sw/device/lib/crypto/BUILD
- sw/device/lib/crypto/include/BUILD
- sw/device/lib/crypto/include/aes.h
- sw/device/lib/crypto/include/datatypes.h
- sw/device/lib/crypto/include/drbg.h
- sw/device/lib/crypto/include/ecc.h
- sw/device/lib/crypto/include/freestanding/BUILD
- sw/device/lib/crypto/include/freestanding/absl_status.h
- sw/device/lib/crypto/include/freestanding/hardened.h
- sw/device/lib/crypto/include/hash.h
- sw/device/lib/crypto/include/kdf.h
- sw/device/lib/crypto/include/key_transport.h
- sw/device/lib/crypto/include/mac.h
- sw/device/lib/crypto/include/rsa.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/otcrypto_hash_test.c
1. Rewrite header includes from full paths to basenames.  This will allow the header files to be exported as packagable resource without regard to the file locations within the OT repo.
2. Add freestanding version of the `hardened.h` and `status.h` files. This allows `datatypes.h` to use those definitions once exported out of the OT repo.
3. Add packaging rules to package the cryptolib binary and headers into a tar archive (ie: an exported release artifact).
4. Create a `cc_import` library that uses the output of the static_library rule to create a useful cryptolib resource within the codebase.
> [cryptolib] Export cryptolib as a stand-alone library

- sw/host/opentitanlib/src/transport/common/uart.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
OpenTitanTool creates two locks for serial ports: a `flock` and a UUCP-style `/var/lock/LCK..ttyUSB{n}` file.
From what I can tell, we support UUCP locks for compatability with `minicom` which doesn't use `flock`. This lockfile is left behind very often by OTT, though we're not sure why. On shared machines, OTT is unable to clean up stale locks because `/var/lock/` has a stick bit set which prevents other users deleting files.
We think that the hassle this causes is not worth the compatability with `minicom`. If you use `minicom` and are having trouble with concurrent access, I would recommend other tools that support `flock` such as `picocom`. Please let me know if you do use `minicom` regularly and don't want to lose this support - we can come up with some other solution.
> [ott] Remove UUCP-style locking for serial ports

- hw/top_earlgrey/syn/chip_earlgrey_asic.sdc
Add constraints that are specific to TPM and fast passthrough commands. This might be excessive, but now there are five constraints modes:
- 50 MHz, full-cycle sampling, no passthrough, flash I/O delays
- 25 MHz, half-cycle sampling, no passthrough, flash I/O delays
- 25 MHz, half-cycle sampling, TPM I/O delays
- 25 MHz, full-cycle sampling, all passthrough, flash I/O delays
- 40 MHz, full-cycle sampling, pipelined passthrough only, flash I/O delays
We may be able to consolidate these, but we'll likely want to take a look at the data first.
In addition to the new constraint sets, some generic mode-specific exceptions get removed, and we select IOA7 as the only timed pad for SPI TPM's CSB. _We should confirm that this is the correct chosen pad._
Finally, just a note, but for real …
> [spi_device] Add separate constraints for TPM and fast passthrough

- hw/top_earlgrey/BUILD
- sw/device/silicon_creator/rom_ext/BUILD
~Partially revert #21586 to go back to using the fake keys on the master branch. Allow FPGA tests against ROM_EXT with just the keys in the repo again.~
Change the generic ROM_EXT target to be signed by the fake prod key, so it may be used in the prod life cycle state.
Change the fpga_cw310_sival_rom_ext execution environment to use the generic ROM_EXT with a sival OTP configuration.
This fixes a key mismatch due to earlier changes.
> [fpga_cw310_sival_rom_ext] Use fake-signed tests  on the master branch

- sw/device/tests/crypto/cryptotest/json/ecdsa_commands.h
- sw/host/cryptotest/ujson_lib/BUILD
- sw/host/cryptotest/ujson_lib/src/ecdsa_commands.rs
- sw/host/tests/crypto/ecdsa_kat/BUILD
- sw/host/tests/crypto/ecdsa_kat/src/main.rs
This PR adds the host-side Rust test harness for the ECDSA `Verify` operation tests and the associated uJSON C header file. The device-side firmware will be included in #20853.
~Dependent on #21112 and #21114~
> [cryptotest] Add ECDSA host-side test harness

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/base/chip.h
- sw/device/silicon_creator/lib/boot_data.h
- sw/device/silicon_creator/lib/boot_log.c
- sw/device/silicon_creator/lib/boot_log.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_msg.h
- sw/device/silicon_creator/lib/dbg_print.c
- sw/device/silicon_creator/lib/dbg_print.h
- sw/device/silicon_creator/lib/drivers/retention_sram.c
- sw/device/silicon_creator/lib/drivers/retention_sram.h
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/nonce.h
- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
Re-arrange the retention RAM as discussed in the SW WG meeting on
2024-02-13:
Locate the boot_svc message first, followed by reserved space, followed
by the boot_log and last_shutdown_reason. This arrangement allows us
to grow the boot_svc message (growing "down" into the reserved space)
if needed and to add additional fields at the end (growing "up" into
the reserved space).
Also: name the ASCII code for boot log as `BLOG` instead of `BOLG`.
> [cherrypick, rom, rom_ext] Re-arrange retention RAM

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
Getting my head around this problem took... some time! The exact behaviour of function calls in constraints is described in IEEE 1800, section 18.5.12.
What I was trying to do is definitely invalid, because the constraint looked like
randomize(x) with {is_good(x);}
The constrained randomisation tool doesn't ever look inside functions that it sees. All it can do is to execute the function with some argument. Clearly that isn't going to work in the example above...
I spent a couple of minutes wondering why functions are allowed at all! But this isn't completely crazy, because you might want to do something like this:
randomize(x,y) with { x < 10; y < pow(x, 3); }
This actually works! Assuming that pow is exponentiation, it picks a pair x, y such that x is less than 10 and y is less than …
> [rom_ctrl,dv] Fix constraint for invalid mubis in vseq

- hw/ip/dma/data/dma.hjson
- hw/ip/dma/dv/env/dma_pull_seq.sv
- hw/ip/dma/rtl/dma.sv
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
It was discovered that integrity checks on the TL-UL response were not enabled. This PR adds a new parameter to enable integrity checks for both TL-UL ports
> [hw,dma,rtl] Enable TL-UL integrity checks on response

- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
This test is not needed since all tests will implicitly test POR.
> [sival,pwrmgr] Fix si_stage label for chip_sw_pwrmgr_external_full_reset

- sw/device/tests/crypto/cryptotest/firmware/BUILD
This PR manually cherry-picks PRs #21200 and #21239 from the earlgreay_es_sival branch to master because the automated cherry- picking failed.
Commit messages:
[pentest] Add SCA/FI pen. test bazel rule
This PR adds a bazel rule allowing to compile a signed binary that can be used for penetration testing.
[pentest] Add prodc target to pentest build script
This PR adds the silicon_owner_prodc_rom_ext target for building the penetration testing binary.
> Cherry-pick to master: #21239 and #21200

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/doc/registers.md
- hw/ip/entropy_src/rtl/entropy_src_core.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
- sw/device/lib/dif/dif_entropy_src.c
- sw/device/lib/dif/dif_entropy_src.h
- sw/device/lib/dif/dif_entropy_src_unittest.cc
- sw/device/tests/entropy_src_fw_observe_many_contiguous.c
This PR latches the observe FIFO overflow register signal instead of only pulsing it.
For a more detailed explanation have a look at the individual commit messages.
This PR also contains a commit that changes a mubi4 test true signal from strict to loose.
This is done as a follow up for #21369.
Closes [#21279](https://github.com/lowRISC/opentitan/issues/21279)
> [entropy_src/rtl] Fix observe fifo overflow reg

- SUMMARY.md
- sw/device/silicon_creator/lib/dbg_print.c
- sw/device/silicon_creator/lib/dbg_print.h
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/doc/rescue.md
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/device/silicon_creator/rom_ext/rescue.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
Implement the shell of the rescue protocol.
1. Trigger rescue entry via the serial break condition.
2. Support Xmodem-CRC for uploading rescue images or other resources.
3. Support Xmodem-CRC for downloading selected info from the chip.
4. Support requesting the rescue mode via a set of 4-byte identifiers. These include:
- `RESQ`: The default rescue mode (ie: upload firmware).
- `BREQ`: Request to upload a boot_svc request message.
- `BRSP`: Request to download the boot_svc response message.
- `BLOG`: Request to download the boot_log data structure.
- `OWNR`: Request to upload an owner block.
- `REBO`: Request to exit rescue mode and reboot.
- Currently, BREQ, BRSP, BLOG and REBO are implemented.
- The RESQ command erases and flashes the data in partition A.  The appropriate flash limits …
> Cherrypick to master: [rom_ext, rescue] Implement the rescue protocol shell

- sw/device/lib/crypto/impl/rsa.c
Previously, the RSA OAEP decryption logic incorrectly performed a hardware trap after completing the decryption if the passed buffer for the plaintext is exactly the correct size. This PR fixes this bug. The correctness of this fix has been verified using the wycheproof test vectors.
> [crypto] Fix a broken trap condition in RSA

- sw/device/lib/crypto/impl/rsa/rsa_modexp.c
Previously, RSA `verify` operations returned an invalid argument error when passed a value for the public exponent `e` other than 65537 (`2^16 + 1`), because we currently lack a variable-time implementation to perform the `modexp` operation for other exponents. This PR configures RSA to temporarily use the existing constant-time implementation for other exponents until a variable-time implementation is supported. 
This PR allows us to run the NIST CAVP RSA test vectors, which all use `e != 65537`.
> [crypto/rsa] temporarily use constant-time modexp when e != 0x10001

- sw/host/opentitanlib/src/app/mod.rs
- sw/host/opentitanlib/src/proxy/nonblocking_uart.rs
- sw/host/opentitanlib/src/rescue/xmodem.rs
- sw/host/opentitanlib/src/transport/common/uart.rs
Address compiler lints from `nightly-2024-01-01`. This will enable updating the nightly Rust toolchain.
One of those lints points out that `proxy::nonblocking_uart::UartKey` compares wide pointers including metadata. Instead, UartKey should only consider the address portion of the pointer. This adjust UartKey's Hash and PartialEq implementations to only consider the address portion of the pointer, and adds a test for the Hash implementation.
> [opentitanlib] Address upcoming lints, UartKey comparison fix.

- hw/ip_templates/rv_plic/data/rv_plic_fpv_testplan.hjson.tpl
- hw/top_earlgrey/ip_autogen/rv_plic/data/rv_plic_fpv_testplan.hjson
These two assertions tested edge triggered interrupts, but since the option of edge signalling has been removed a long time ago, these two testplan entries are stale and can be removed.
Fixes #17412
> [rv_plic/fpv] Remove stale testplan entries

- hw/ip/pinmux/doc/programmers_guide.md
This is a short term fix and addresses #18585 and #19425.
Longer term, we should align how top-level documentation is generated, see #12848.
> [topgen] Fix broken pinmux table link

- hw/top_earlgrey/BUILD
- sw/device/silicon_creator/rom_ext/BUILD
Change the generic ROM_EXT target to be signed by the fake prod key, so it may be used in the prod life cycle state.
Change the fpga_cw310_sival_rom_ext execution environment to optionally use the generic ROM_EXT with a sival OTP configuration. A build setting allows it to be built with the real keys, however.
This fixes a key mismatch due to earlier changes.
> [fpga_cw310_sival_rom_ext] Fix key mismatch

- hw/ip/hmac/data/hmac.hjson
With the addition of *save & restore* (PR #21307) and *wider digest and configurable key length* (PR #21604), HMAC will see major changes.  For this reason, this commit gives HMAC a major version bump to 2.0.0 and resets its development stages to L1 (Development), D1 (Functional), V0 (*Initial Work* because the DV environment may not be completely functional for some time), and S0 (*Initial Work* because the DIF may not be completely functional for some time).
The previous version 1.0.0 got assigned a commit ID for future reference even though it had not reached L2, V3, and S3.
> [hmac] Bump version to 2.0.0 and reset development stages

- hw/ip/hmac/README.md
- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/doc/programmers_guide.md
- hw/ip/hmac/doc/registers.md
- hw/ip/hmac/dv/env/hmac_env_cfg.sv
- hw/ip/hmac/dv/env/hmac_env_pkg.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/tests/hmac_base_test.sv
- hw/ip/hmac/rtl/hmac.sv
- hw/ip/hmac/rtl/hmac_core.sv
- hw/ip/hmac/rtl/hmac_reg_pkg.sv
- hw/ip/hmac/rtl/hmac_reg_top.sv
- hw/ip/prim/rtl/prim_sha2.sv
- hw/ip/prim/rtl/prim_sha2_32.sv
- hw/ip/prim/rtl/prim_sha2_pad.sv
This is an initial implementation of save & restore for HMAC (issue #49), which should allow SW to switch between different parallel message streams. In short, SW usage follows a pattern like this:
1. Start processing message stream A by configuring HMAC and then setting the `CMD.hash_start` bit.
2. Write an arbitrary number of message blocks to HMAC's `MSG_FIFO`.
3. Stop HMAC by setting the `CMD.hash_stop` bit and wait for the `hmac_done` interrupt (or poll the interrupt status register).
4. Save the context by reading the `DIGEST_0`..`7` and `MSG_LENGTH_`{`LOWER`,`UPPER`} registers. (The values in the `CFG` register must also be preserved, but that is purely SW-controlled so doesn't need to be read from HW.)
5. Repeat steps 1-4 for message stream B.
6. Restore the context of message …
> [hmac] Initial implementation of save & restore

- util/dvsim/FormalCfg.py
Add support for `result_server` parameter to the `_publish_results()` method.
This fixes issue #21694.
> [dvsim] Add results_server dependency to FormalCfg

- doc/contributing/hw/comportability/README.md
- doc/contributing/hw/comportability/event_intr_type.svg
- doc/contributing/hw/comportability/ot_interrupt_arch.svg
- doc/contributing/hw/comportability/status_intr_type.svg
- hw/ip/prim/rtl/prim_intr_hw.sv
To go along with future interrupt type-alignment tasks, tighten-up the documentation of comportable interrupts, particularly around prim_intr_hw and the distinction between *Status* and *Event* type interrupts.
Add some new block diagrams to support these changes, mirroring the hardware implementations provided by 'prim_intr_hw'. Diagrams were taken from the original RFC which proposed the addition of the **Status**-type interrupt.
Update the existing wavejson waveforms to explicitly include the effects of enabling the output flop (which is the default, and currently the only behaviour used within the codebase).
---
I would particularly appreciate any feedback/suggestion for content in the final paragraph of the section (### CIP Interrupt Types), which (currently, only vaguely) describes …
> [doc] CIP interrupt doc updates

- hw/top_earlgrey/data/ip/chip_rv_plic_testplan.hjson
The test is already enabled for cw310_sival_rom_ext exec env (`bazel test //sw/device/tests:plic_sw_irq_test_fpga_cw310_sival_rom_ext` works). Update the testplan to reflect that.
Fix #19863
> [sival, plic] add plic_sw_irq_test bazel target to testplan

- hw/ip/hmac/lint/hmac.vlt
sha2_pad was removed from hmac with 2290dcc11, because the code now lives in prim_sha2_pad. I suspect we'll want to put in a lint waiver there at some point too, but there's no real advantage to keeping this stale one.
I found this because I was searching through the repository for the various ports of `hmac` when thinking about #21666 (and whether we could "just do it"). Here's a waiver that definitely wouldn't need renaming...
> [hmac,verilator] Remove lint waivers for nonexistent file

- hw/dv/sv/mem_model/mem_model.sv
This spits out quite an impressive ream of text, making --verbosity=medium less useful than it might be.
Looking at the history of the file, I think this message got promoted from UVM_HIGH to UVM_MEDIUM as part of commit 39b2692. I suspect this was a debug print that survived by accident.
Demote it again!
> [dv] Make mem_model's compare_byte function less chatty

- hw/dv/sv/csr_utils/csr_seq_lib.sv
Here, all_csrs is a queue and SystemVerilog doesn't technically allow the part-select that we were using when we created test_csrs.
Fortunately, it does allow access by index, so we can sort of build the subsequence by hand, which is what this commit does.
This avoids the *W,RTSVQR warning from Xcelium.
> [csr_seq_lib] Avoid slicing a queue

- hw/ip/spi_host/rtl/spi_host.sv
- hw/ip/uart/rtl/uart_core.sv
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/ip/soc_proxy/data/soc_proxy.hjson
- hw/top_darjeeling/ip/soc_proxy/rtl/soc_proxy.sv
This PR flops the LSIO triggers at the source IP with their respective peripheral clock and then uses a synchronizer cell at the soc_proxy IP with the fast SoC clock to fix a CDC issue between both domains.
The LSIO trigger of the I2C IP is already flopped.
> [hw,spi_host,i2c,soc_proxy] Fix CDC issue for lsio_triggers

- hw/ip_templates/rv_plic/doc/checklist.md
- hw/ip_templates/rv_plic/rtl/rv_plic.sv.tpl
- hw/top_earlgrey/ip_autogen/rv_plic/doc/checklist.md
- hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic.sv
Looks like filling out the checklist got overlooked in the past. 
This patch amends that and adds a missing SVA for the one standardized bus integrity CM in the design.
The SecCm SVAs all pass:
```  
[16]  rv_plic.FpvSecCmBusIntegrity_A                    proven          N      Infinite    1.546 s      
[17]  rv_plic.FpvSecCmBusIntegrity_A:precondition1      covered         Ht            2    0.082 s      
[18]  rv_plic.FpvSecCmRegWeOnehotCheck_A                proven          Hp     Infinite    3.732 s      
[19]  rv_plic.FpvSecCmRegWeOnehotCheck_A:precondition1  covered         Ht           22    0.085 s   
...
|      name      |  pass_rate  |  stimuli_cov  |  coi_cov  |  prove_cov  |
|:--------------:|:-----------:|:-------------:|:---------:|:-----------:|
| rv_plic_sec_cm |  100.00 % …
```
> [rv_plic] Add SEC_CM assertion and fill out checklist

- hw/ip/spi_device/data/spi_device.hjson
- hw/ip/spi_device/doc/programmers_guide.md
- hw/ip/spi_device/doc/registers.md
- hw/ip/spi_device/doc/theory_of_operation.md
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
- hw/ip/spi_device/rtl/spi_device_reg_top.sv
- hw/ip/spi_device/rtl/spi_readcmd.sv
- hw/ip/spi_device/rtl/spi_tpm.sv
- hw/ip/spi_device/rtl/spid_readbuffer.sv
- hw/ip/spi_device/rtl/spid_status.sv
- sw/device/lib/dif/dif_spi_device.c
- sw/device/lib/dif/dif_spi_device.h
- sw/device/lib/dif/dif_spi_device_unittest.cc
- Remove outdated TODOs / ICEBOXs.
- DIFs only: Add a mechanism to clear outstanding requests to the status registers
- Add a mechanism to reinit the read buffer without needing to reset the entire spi_device IP
- Document the SRAM layout and its relationship to 1r1w memories.
> [spi_device] Clean up TODOs and add a mechanism to reinit the read buffer

- hw/ip/otp_ctrl/data/otp_ctrl_img_owner_sw_cfg.hjson
It seems something messed up for the values. I just re-generated the digest values and got the diff.
Thats the output of the opentitantool:
```
{
partitions: [
{
name: "OWNER_SW_CFG",
items: [
{
name: "OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD",
value: 3837441892
},
{
name: "OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END",
value: 284251105
},
{
name: "OWNER_SW_CFG_ROM_ALERT_DIGEST_DEV",
value: 2316472459
},
{
name: "OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA",
value: 1321476032
}
]
}
]
}
```
> [otp] Fix OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END value

- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otp_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rom_ctrl_testplan.hjson
Add suitable comments explaining the reason some tests are not feasible or needed for sival.
> [sival,testplans] Set si_stage to NA for non-sival tests

- hw/vendor/pulp_riscv_dbg.lock.hjson
- hw/vendor/pulp_riscv_dbg/CHANGELOG.md
- hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom.sv
- hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom_one_scratch.sv
- hw/vendor/pulp_riscv_dbg/debug_rom/gen_rom.py
- hw/vendor/pulp_riscv_dbg/src/dm_mem.sv
- hw/vendor/pulp_riscv_dbg/src/dmi_jtag.sv
This updates `hw/vendor/pulp_riscv_dbg` (i.e., the RISC-V debug module instantiated within `rv_dm`) to the latest upstream commit ahead of the upcoming M2 milestone, thus resolves #21715. The main RTL change that this brings is https://github.com/pulp-platform/riscv-dbg/commit/5024399a48b61527b03e89a532c7530da28e7477, which makes the `addr_q` FFs in the `debug_rom` module resettable. Not a fix to a critical problem for us, but still nice to have. The other RTL change (https://github.com/pulp-platform/riscv-dbg/commit/73260e7fb608041d89771971793af5ba1ee209b8) changes the default value of `dmi_jtag`'s `IdcodeValue` parameter, but this doesn't affect us because we assign it to the value we need when we instantiate it in `rv_dm`.
> [vendor/pulp_riscv_dbg] Update to pulp-platform/riscv-dbg@358f901

- hw/ip/rom_ctrl/dv/rom_ctrl_base_sim_cfg.hjson
Currently it uses the default output path, which does not have the variant in it. This causes the files of ROM_CTRL/32KB run to be overwritten by ROM_CTRL/64KB run silently, and will cause error if parallelism > 3.
Follow what other blocks are doing and specify an output path with variant name in it.
> [dv] fix rom_ctrl dvsim output path

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/cryptotest_util.py
- sw/host/cryptotest/testvectors/parsers/cryptotest_util_test.py
- sw/host/cryptotest/testvectors/parsers/nist_aes_parser.py
- sw/host/cryptotest/testvectors/parsers/nist_cavp_ecdsa_parser.py
- sw/host/cryptotest/testvectors/parsers/nist_cavp_hash_parser.py
- sw/host/cryptotest/testvectors/parsers/nist_cavp_hmac_parser.py
Performs a massive overhaul (and breaking API change) of the `parse_rsp` function in the cryptotest framework's utility library for test vector parsers.
The heterogeneous formatting styles of the test vector files meant that the caller of `parse_rsp` was still having to do a lot of heavy lifting to get the data into the shape they wanted, and some test vectors were impossible to support using the previous version, such as AES-GCM and DRBG, which declare multiple of the same variable in the same test vector. Likewise, this PR is largely a response to the issues that came up during #21617 .
The new API does the following:
- Rather than sort the test vectors into sections based on the headers that looked like `[header]`, the test vectors are instead returned in a single long array. Headers …
> [cryptotest] refactor `parse_rsp` and clean up test vector build script

- sw/device/tests/BUILD
The following tests also seem to be part of issue https://github.com/lowRISC/opentitan/issues/21706:
- //sw/device/tests:pwrmgr_all_reset_reqs_test
- //sw/device/tests:pwrmgr_random_sleep_all_reset_reqs_test
Thus this commit marks them as broken in SiVal ROM_EXT.
This should contribute to fixing the currently failing CI checks on
`master`.
Examples of this test failing in CI:
- https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=143751&view=logs&jobId=6d7ef521-d3a1-575b-de1b-a7342dcf1a8e&j=6d7ef521-d3a1-575b-de1b-a7342dcf1a8e&t=5fbf7d75-9dee-5f42-7084-95893df8eb52
- https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=143812&view=logs&jobId=6d7ef521-d3a1-575b-de1b-a7342dcf1a8e&j=6d7ef521-d3a1-575b-de1b-a7342dcf1a8e&t=5fbf7d75-9dee-5f42-7084-95893df8eb52
> [sw/tests] Mark more tests as broken in SiVal ROM_EXT

- hw/ip_templates/pwrmgr/data/pwrmgr_sec_cm_testplan.hjson
- hw/ip_templates/rstmgr/data/rstmgr_sec_cm_testplan.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/data/pwrmgr_sec_cm_testplan.hjson
- hw/top_earlgrey/ip_autogen/rstmgr/data/rstmgr_sec_cm_testplan.hjson
The old contents were lost in the transition to ipgen. Update the sec_cm_testplan files in ip_templates. These testplans are
top-specific, so they may need to become templates.
> [sec_cm,pwrmgr,rstmgr] Update sec_cm_testplans

- sw/device/lib/testing/alert_handler_testutils.h
- sw/device/tests/aon_timer_wdog_lc_escalate_test.c
- sw/device/tests/pwrmgr_sleep_resets_lib.c
- sw/device/tests/rv_core_ibex_nmi_irq_test.c
- sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c
- sw/device/tests/sim_dv/pwrmgr_random_sleep_power_glitch_reset_test.c
Add a default ping timeout for tests using alert_handler testutils. A number of tests previously used 0 here, but that value risks timeouts, since alert_handler_testutils_configure_all() enables the ping feature unconditionally. Bump that up to the recommended value for earlgrey.
> [alert_handler_testutils] Revise default ping timeout

- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/usbdev_aon_wake_disconnect_test.c
- sw/host/tests/chip/usb/usb.rs
- sw/host/tests/chip/usb/usbdev_aon_wake.rs
Manual backport of #21603 that could not be done automatically due to minor differences in BUILD files.
> Backport usb

- hw/ip_templates/rstmgr/dv/env/rstmgr_env_pkg.sv
- hw/ip_templates/rstmgr/dv/env/rstmgr_scoreboard.sv
- hw/top_earlgrey/ip_autogen/rstmgr/dv/env/rstmgr_env_pkg.sv
- hw/top_earlgrey/ip_autogen/rstmgr/dv/env/rstmgr_scoreboard.sv
There is a handful of registers that are reset on POR only, but the dv_base classes will clear all mirrored values on reset. Rather than changing all that code to handle resets more accurately here we just capture the mirrored values of all such CSRs before reset, and apply them back once reset is handled.
Fixes #18258
> [dv,rstmgr] Handle CSRs reset by POR

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
- hw/dv/sv/csr_utils/csr_utils_pkg.sv
- hw/dv/sv/push_pull_agent/push_pull_agent_cfg.sv
- hw/dv/sv/push_pull_agent/push_pull_monitor.sv
- hw/ip/prim/rtl/prim_fifo_sync.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_bijection_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_executable_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_stress_all_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_throughput_vseq.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_env.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cfg.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
Improve handling of ram initialization: refine the CSR expectations, and
move most processing outside process_tl_access since it is not called for
the CIP common tests; also, ram initialization blocks RAM accesses so
there could be a long time with transactions outstanding, which can cause
random reset timeouts.
Handle re-scramble during test execution, letting the push_pull agent
become active. In case of re-scrambling, invalidate the expected memory
state since it becomes invalid.
Add missing calls to cfg.stop_transaction_generators.
> [dv,sram_ctrl] Fix a few failing tests

- sw/device/lib/dif/dif_entropy_src.c
- sw/device/lib/dif/dif_entropy_src.h
- sw/device/lib/dif/dif_entropy_src_unittest.cc
- sw/device/lib/testing/entropy_testutils.c
- sw/device/lib/testing/entropy_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/entropy_src_fw_observe_many_contiguous.c
- sw/device/tests/entropy_src_fw_override_test.c
- sw/device/tests/entropy_src_fw_ovr_test.c
- sw/device/tests/entropy_src_kat_impl.c
- sw/device/tests/sim_dv/csrng_lc_hw_debug_en_test.c
This PR extends the entropy source firmware override observe fifo test to enable "extract and insert" mode.
1. Adds an interrupt handler for the `es_observe_fifo_ready` interrupt which reads 32 words (the FIFO threshold value) from the observe FIFO and writes it back again.
2. Allows configuring the entropy source with extract and insert mode, enabling that interrupt handler.
3. For each of the "single bit" configurations, checks the entropy source is working by generating a set of random numbers and running AES, KMAC, and HMAC.
> [sival] Add test for the entropy source's firmware extract and insert mode

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/aes_sca.c
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.c
- sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
- sw/device/tests/crypto/cryptotest/firmware/sca_lib.c
- sw/device/tests/crypto/cryptotest/firmware/sca_lib.h
- sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
Instruction caching and dummy instructions could negatively affect the alignment of SCA traces. Hence, this PR adds code to disable the iCache and dummy instructions before starting SCA & FI penetration tests.
The effect of the iCache can be seen in the picture below. Here, I recorded 100 power traces and the corresponding trigger signal when executing NOP instructions.
With the enabled instruction cache (left side), the falling edge of the trigger signal is captured at different points in time. For SCA and FI, this makes the analysis much harder. When disabling the iCache (right side), the falling edge of all 100 triggers are now aligned.
Thanks to @johannheyszl, @moidx, and @a-will for the discussion on this!
> [pentest] Disable iCache and dummy instr.

- sw/otbn/crypto/p256_verify.s
A zero input (such as a point-at-infinity in the conversion to affine coordinates) can cause the variable-time modular inverse algorithm to run forever.
@wettermo I looked at the P384 code and it seems not to be a problem there because we use only the constant-time modular inverse for code size reasons, but let me know if I missed something.
Thanks to @RyanTorok for finding this bug via the wycheproof tests!
> [crypto] Check for zero in P256 modular inverse.

- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.c
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.h
- sw/device/tests/crypto/cryptotest/json/ibex_fi_commands.h
This PR adds new penetration tests targeting the register file (RF) of Ibex:
- ibex_fi_char_register_file: Test whether a fault can manipulate values in the RF
- ibex_fi_char_register_file_read: Test whether a fault during reading the RF can manipulate values. This is related to #20715
> [pentest] Add FI Ibex RF tests

- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_parallel_lc_req_vseq.sv
Consistency and integrity checks performed by `otp_ctrl_smoke` in parallel to LC state transition requests are halted until the LC partition is fully programmed, which might cause the [spinwait on OTP_CTRL.STATUS.CHECK_PENDING](https://github.com/lowRISC/opentitan/blob/master/hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv#L463) to raise false negative timeout due to short duration of the default spinwait timeout, as real OTP PROG operations take much longer in reality then the generic memory array in the OS implementation. Hence, this request scales up the default spinwait timeout duration to solves the issue.
> [dv/otp_ctrl] increased spinwait timeout duration for otp_ctrl_parallel_lc_req_vseq

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv
otf_address is used in mp_regions test.
update constraint in sync with op.addr
> [flash_ctrl,dv] fix constraint for mp_regions test

- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
Local implementation of 'clear_all_interrupts' is no longer required/appropriate because the cip_base_vseq class has been updated.
> [usbdev,i2c] Drop local clear_all_interrupts

- sw/device/lib/testing/i2c_testutils.c
- sw/device/lib/testing/pinmux_testutils.h
- sw/device/tests/sim_dv/i2c_device_tx_rx_test.c
The previous `kI2cPlatformPins` array mapped to pins solely based on the platform.  This works for CW310 (with PMOD and HyperDebug) where I2C is mapped to one pair of pins for all I2C instances.  In DV, however, each I2C instance has its own agent, which is connected to its own pair of (muxed) pins.  Coincidentally, when the I2C instance ID (i.e., 0 to 2) is (incorrectly) used to index the `kI2cPlatformPins` array, that would result in the correct pair of pins for DV.  When pins change for one of the platforms or the number of I2C instances changes, however, this will no longer work.
This commit takes the I2C instance ID into account when mapping to pins. The result is the same as before on the condition that the platform argument to a call of `i2c_testutils_select_pinmux` in …
> [sw/i2c_testutils] Take I2C instance ID into account for pins

- hw/ip/usbdev/data/usbdev.hjson
- hw/ip/usbdev/doc/registers.md
- hw/ip/usbdev/dv/env/seq_lib/usbdev_fifo_rst_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/env/usbdev_env_pkg.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
- hw/ip/usbdev/rtl/usbdev.sv
- hw/ip/usbdev/rtl/usbdev_reg_pkg.sv
- hw/ip/usbdev/rtl/usbdev_reg_top.sv
This PR introduces low-impact software resets for the internal buffer FIFOs, controlled by a new register, as a contingency against unanticipated error conditions, and for future deployments of the USB device where the use of the asynchronous block-level reset is not a viable option. Block-level reset may impact other IP blocks and/or firmware within other chips that contain the USB device, and it may be very time-consuming.
Use of the software resets is only safe when the USB device is not connected to the USB, because packets may be received at any time when the USB is active. Therefore, the pull up should be disabled first. Documentation update to follow in a separate PR, accompanying documentation updates for other recent changes.
The second commit introduces a simple test sequence …
> [usbdev] Software resets for internal buffer FIFOs

- hw/ip/rv_core_ibex/lint/rv_core_ibex.waiver
- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/vendor/lowrisc_ibex.lock.hjson
- hw/vendor/lowrisc_ibex/doc/03_reference/cs_registers.rst
- hw/vendor/lowrisc_ibex/doc/requirements.txt
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/ibex_dv.f
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- hw/vendor/lowrisc_ibex/ibex_top.core
- hw/vendor/lowrisc_ibex/rtl/ibex_core.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_lockstep.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_pkg.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_tracer.sv
5a8a1a99930afbb9efe107ff2c80d482239d7a5f
* [tracer] Fix reporting of load/store data (Adrian Lees)
* Update old `cpuctrl` CSR name in `cs_registers.rst` (Luís Marques)
* [doc] Require sphinx version >= 7.0 (Greg Chadwick)
* [rtl] Harden lockstep enable against FI (Pascal Nasahl)
> Update lowrisc_ibex to lowRISC/ibex@5a8a1a99

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/otbn_boot_services.c
- sw/device/silicon_creator/lib/otbn_boot_services.h
- sw/device/silicon_creator/lib/otbn_boot_services_functest.c
- sw/otbn/crypto/boot.s
- sw/otbn/crypto/p256_sign.s
These tests caught a few bugs and places where comments were needed; the first commits fix bugs and the last commit adds the test code.
Thanks to @ballifatih for finding one bug in the OTBN code, which brought to my attention that we were missing tests for this! Once I started writing them I found more, so it's really good that this came up.
> [boot_services] Add functional tests for the OTBN boot services library.

- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
The vseq names all have a "usbdev_" prefix, but some of the tests were missing that prefix, which will have stopped them from working properly. Put it back.
This change came from a bugfix that was part of #21556. I'm "cherry-picking" the obvious bug fix here to buy some time to review the rest of the PR properly.
> [usbdev,dv] Fix names in usbdev_sim_cfg.hjson

- hw/ip/spi_device/data/spi_device_testplan.hjson
The testplan has been updated to directly mention the new RTL features for V1 sign-off:
- equivalent r/w access when using 1r1w SRAMs as opposed to the 2PSRAM
- Mention of read_pipeline feature as a testpoint
- new covergroup to sample the type of SRAM instantiated
- addition of read_pipeline_mode coverpoint to existing flash_cmd_info_cg
> [dv] Update spi-device testplan for V1 sign-off.

- hw/ip/usbdev/dv/env/seq_lib/usbdev_av_buffer_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_enable_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_nak_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_stall_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_trans_nak_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_received_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_sent_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_random_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_setup_trans_ignored_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
The values are the same at every call site. Get rid of the argument, since it's just confusing!
> [usbdev,dv] Drop some arguments from the call_token_seq task

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_smoke_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_throughput_vseq.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
The older scheme for this detection used csr_spinwait for the duration of init and key request. This only uses csr_spinwait once the request is satisfied, to detect the actual CSR updates. This is just as accurate as the older scheme, and by avoiding csr_spinwait for the full time it simplifies handling of random reset.
> [dv,sram_ctrl] Improve detection of init_done and key_scr_valid

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/BUILD
- sw/host/cryptotest/testvectors/data/schemas/kmac_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/wycheproof_kmac_parser.py
Adds the wycheproof KMAC test vectors to `/sw/vendor/` and adds a python script and JSON schema to parse the test vectors into the format that will be used in the test harness. The parser and JSON schema are only a slight variation of the ones used for HMAC in #21149 and #21151, respectively.
Dependent on #21599
> [cryptotest] add wycheproof KMAC test vectors

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv
This needs to be carried over to ip_autogen since the IPgen transition has not been fully completed yet.
> [flash_ctrl/dv] carry over DV fix to ip_autogen

- hw/ip/adc_ctrl/doc/programmers_guide.md
As mentioned on #18511, the full range of the ADC in Earlgrey is 0.0V - 2.3V. 
This patch updates the programming guidance accordingly.
> [adc_ctrl/doc] Update programming guidance for 0.0V 2.3V full range

- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize_3.c
- sw/host/provisioning/ft_lib/BUILD
- sw/host/provisioning/ft_lib/src/lib.rs
This updates the FT provisioning flow to send the endorsed UDS cert back to the device and writes it to flash. This partially addresses #19455.
> [manuf] send endorsed UDS cert back to the device

- sw/host/opentitanlib/src/io/jtag.rs
This updates the default JTAG speed to 1MHz to descrease test time in CI for tests that make use of JTAG.
> [opentitanlib] update default JTAG speed

- hw/ip/prim/prim_diff_encode.core
- hw/ip/prim/rtl/prim_diff_encode.sv
Add a new primitive to differentially encode an input signal for being used for external alert requests. The output is flopped for being fed to a prim_2sync cell in top_darjeeling
> [hw,prim_diff_encode,rtl] New prim for differential encoding

- hw/ip/uart/data/uart.hjson
- hw/ip/uart/doc/interfaces.md
- hw/ip/uart/doc/registers.md
- hw/ip/uart/dv/env/seq_lib/uart_intr_vseq.sv
- hw/ip/uart/dv/env/uart_scoreboard.sv
- hw/ip/uart/rtl/uart_core.sv
- hw/ip/uart/rtl/uart_reg_top.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- sw/device/lib/dif/autogen/dif_uart_autogen.c
- sw/device/lib/dif/autogen/dif_uart_autogen_unittest.cc
- sw/device/lib/testing/autogen/isr_testutils.c
- sw/device/lib/testing/autogen/isr_testutils.h
- sw/device/lib/testing/test_framework/ottf_console.c
- sw/device/tests/autogen/plic_all_irqs_test.c
- sw/device/tests/uart_tx_rx_test.c
This includes a commit from https://github.com/lowRISC/opentitan/pull/21226 which is a cip_lib change required for all status type interrupts. So need to ensure one of the PRs gets rebased if the other has gone in.
> Uart status interrupts

- hw/ip/usbdev/data/usbdev_testplan.hjson
Additional test points for USBDEV, particularly stress testing and conditions that are impractical or difficult to simulate at top level/FPGA such as random disconnections, bus resets and unexpected/invalid traffic.
These test points are not required for V1, but should go some way towards scoping out the requirements for V2.
Introduce the recently-created FIFO reset test following RTL change in #21791
> [dv,usbdev] Testplan extensions for usbdev

- sw/device/silicon_creator/lib/attestation.h
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/otbn_boot_services.c
- sw/device/silicon_creator/lib/otbn_boot_services.h
- sw/device/silicon_creator/lib/otbn_boot_services_functest.c
- sw/otbn/crypto/BUILD
- sw/otbn/crypto/boot.s
- sw/otbn/crypto/p256_base.s
This required making the P256 code slightly smaller so that sign and verify would fit together on the same binary. Luckily I knew where to find a very slightly faster exponentiation chain for P-256 modular inversion, which I had tried implementing before but hadn't gone to the effort of merging because the speed improvement was so modest. However, the code size improvement is pretty good, so that plus a few more adjustments helped me not only fit everything on the same binary but also shave a cool ~3700 cycles off our top-level ECDSA sign operation. (That's a 0.5% speed improvement, so not all that exciting, but every little bit helps!)
The first three commits are P-256 code size optimizations; the last two are the ones that actually swap over the boot services library to ECDSA.
Should …
> [boot_services] Switch boot services library to use ECDSA verify.

- azure-pipelines.yml
- ci/scripts/run-fpga-tests.sh
This PR reduces the number of ROM tests and favors the Sival environment for tests that exists both in ROM and SiVal.
> [ci] Avoid running ROM tests that have a corresponding sival test

- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
https://github.com/lowRISC/opentitan/pull/21828 added this to the template but did not regenerate the flash_ctrl config. This PR fixes CI.
Generated with `make -k -C hw top`.
> [dv] Add run_timeout_mins to flash_ctrl config

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/dv/env/i2c_env_pkg.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_glitch_vseq.sv
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_fsm.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
This change allows the I2C HW IP module to absorb a max-length SMBus Block Write,
which consists of 1 command code byte, 1 byte defining the number of data bytes in the
block write, up to 255 data bytes, and 1 optional Packet Error Code
(PEC) byte; thus up to 258 bytes in total (from SMBus Specification
version 3.2, section 6.5.7).  Our I2C HW IP module additionally puts the
byte after the Start condition (which contains the address and the R/Wn
bit) and a byte for the Stop condition into the FIFO; thus the total
increases to 260 bytes.
To account for any oversights we may have made in the analysis of the
protocol, we add an extra 8 bytes as margin, thus 268 bytes.
Note that this is larger than required by MCTP, which would be 75 bytes:
- "The size of a transmission unit is defined as the …
> [i2c] Increase depth of ACQ FIFO to 268 bytes 

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/BUILD
- sw/host/cryptotest/testvectors/data/schemas/aes_kw_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/nist_cavp_aes_kw_parser.py
- third_party/nist_cavp_testvectors/repos.bzl
This PR pulls in the NIST testvectors for AES-KW and includes the associated parser along with the JSON schema.
> [cryptotest] Add NIST AES-KW testvector parser

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/BUILD
- sw/host/cryptotest/testvectors/data/schemas/aes_gcm_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/nist_cavp_aes_gcm_parser.py
- third_party/nist_cavp_testvectors/repos.bzl
This PR pulls in the NIST testvectors for AES-GCM, and includes the associated parser and JSON schema.
> [cryptotest] Add NIST AES-GCM testvector parser

- hw/ip/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
Due to the Ipgen migration, we unfortunately have two copies of this file in the tree at the moment. Hence, this change needs to be carried over.
> [flash_ctrl/dv] Carry over timeout increase to legacy DV file

- hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
Extend 'CreatorSwCfgAstInitEn' initialization within the 'initialize_otp_creator_sw_cfg_ast_cfg' function call to have a valid 4-bit MuBi (true/false).
> [dv, chip, env]: Extend 'CreatorSwCfgAstInitEn' initialization

- sw/device/tests/usbdev_pincfg_test.c
With the present SiVal test hardware it is not possible to test pin-flipping fully without a compensatory external flip of the pins.
Change the set of pin configurations to match that tested on the CW310/340 FPGAs.
> [sival,usbdev] Remove test of usbdev pin-flipping from SiVal

- hw/ip/aes/data/aes.hjson
- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
This resolves lowRISC/OpenTitan#21511.
> [sival,aes] Clarify purpose of chip_sw_aes_masking_off test

- hw/top_darjeeling/ip/soc_proxy/rtl/soc_proxy.sv
Use a synchronizer primitive for differentially encoded external alert signals. External alerts don't use the custom alert protocol. Instead, they are just differentially encoded signals, which require a sync cell to pass the clock domain crossing.
I removed the sec anchor cell sincy we now have a flop here anyways.
> [hw,soc_proxy,rtl] Synchronize external alert signals

- sw/device/lib/testing/test_rom/BUILD
- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/base/chip.h
- sw/device/silicon_creator/lib/manifest.h
- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_key.c
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_key.h
This commit adds support for ECDSA public key and signatures to the manifest. Both signature and public key fields were converted to union types to be able to support either RSA or ECDSA.
`kManifestVersionMajor1` is associated with RSA.
`kManifestVersionMajor2` is associated with ECDSA P256.
> [rom] Add ECDSA P256 support to manifest.h

- hw/ip/sram_ctrl/data/sram_ctrl.hjson
- hw/ip/sram_ctrl/doc/registers.md
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
Previously, it was possible to re-request a new key while a memory init was ongoing. This can result in problematic behavior since the init done indication would still be set to true afterwards, which is misleading since part of the array has then been initialized with the a different key.
This patch changes that and ignores key requests that are issued while a memory initialization is pending.
On a similar note, it was possible to re-trigger a memory initialization while one was already ongoing, causing the existing initialization to restart. This is now also changed so that initialization requests are ignored while an initialization is still pending.
> [sram_ctrl] Minor alignment of init and key request behavior

- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_init_fail_vseq.sv
This is trivial, and probably sneaked by @msfschaffner 's fixes to a prior PR.
> [dv,otp_ctrl] Fix formatting

- hw/ip/spi_host/rtl/spi_host_fsm.sv
Change the behaviour as suggested/proposed in https://github.com/lowRISC/opentitan/issues/14969.
The fix suggested [here](https://github.com/lowRISC/opentitan/issues/14969#issuecomment-1501348019) does indeed seem to make logical sense, and after observing the waveforms I can see the expected masking behaviour.
TODO
<details>
<summary>..failures appear to be just spurious, same as nightlies.</summary>
There appears to be a sampling issue on the final bit of the final byte of a segment.
```
UVM_FATAL @ 373563549 ps: (spi_host_scoreboard.sv:155) uvm_test_top.env.scoreboard [uvm_test_top.env.scoreboard] 
WRITE: actual data did not match exp data 
|	 (len 4) 
|	 byte      actual     expected
|	 [0] 			 3 			 3
|	 [1] 			 37 			 37
|	 [2] 			 8a 			 8a
|	 [3] 			 cd 			 cc
```
</details> …
> [spi_host,rtl] Use sd_en_o[0] to only drive sd_o[0] during TX (Standard speed mode)

- hw/ip/otbn/doc/developing_otbn.md
- hw/ip/otbn/doc/programmers_guide.md
This PR fixes a typo in the Develop OTBN section of the OTBN documentation.
> [doc] Fix typo in OTBN

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/BUILD
- sw/host/cryptotest/testvectors/data/schemas/aes_gcm_schema.json
- sw/host/cryptotest/testvectors/data/schemas/aes_kw_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/nist_cavp_aes_gcm_parser.py
- sw/host/cryptotest/testvectors/parsers/nist_cavp_aes_kw_parser.py
- third_party/nist_cavp_testvectors/repos.bzl
Cherry-picks the AES-KW and AES-GCM cryptotest framework test vector parsers to the `earlgrey_es_sival` branch, since the automatic PR generation did not succeed due to a commit ordering issue.
> [sival/cryptotest] Cherry-pick AES test vector parsers to ES sival branch

- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/ecdsa.c
- sw/device/tests/crypto/cryptotest/firmware/ecdsa.h
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/host/cryptotest/testvectors/parsers/wycheproof_ecdsa_parser.py
- sw/host/tests/crypto/ecdsa_kat/src/main.rs
This PR adds the device-side firmware handler and host-side Rust driver for performing the ECDSA cryptotests using the test vectors added in #20793 . 
The tests in this PR require the patch in #21115 in order to pass.
~Dependent on #21113~
> [cryptotest] add device-side test firmware for ECDSA `Verify` operation

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/firmware/otbn/BUILD
- sw/device/tests/crypto/cryptotest/firmware/otbn/otbn_char_hardware_dmem_op_loop.s
- sw/device/tests/crypto/cryptotest/firmware/otbn/otbn_char_hardware_reg_op_loop.s
- sw/device/tests/crypto/cryptotest/firmware/otbn/otbn_char_unrolled_dmem_op_loop.s
- sw/device/tests/crypto/cryptotest/firmware/otbn/otbn_char_unrolled_reg_op_loop.s
- sw/device/tests/crypto/cryptotest/firmware/otbn_fi.c
- sw/device/tests/crypto/cryptotest/firmware/otbn_fi.h
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/otbn_fi_commands.c
- sw/device/tests/crypto/cryptotest/json/otbn_fi_commands.h
This PR adds the following OTBN tests that can be used for FI characterization:
- otbn.fi.char.unrolled.reg.op.loop
- otbn.fi.char.unrolled.dmem.op.loop
- otbn.fi.char.hardware.reg.op.loop
- otbn.fi.char.hardware.dmem.op.loop
The host code is located in lowRISC/ot-sca#327
> [pentest] Add OTBN FI characterization tests

- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
This PR offers improvements to the testing performed by the block level smoke test for the USB device in two commits:
1. Ensure that SETUP, OUT and IN data packets are transmitted and checked at the receiver for a random endpoint, exercising both transmission and reception of packets at both the CSR side and the USB side. Crude initial implementation of full packet decoding to check the contents of IN data packets; further validation is required and in particular the calculation and checking of CRC16. Implement the removal of bit stuffed '0' bits. Introduce workaround for the sampling issues that arise from operating on a clock frequency that matches the bit rate; the DV should preferably be employing an oversampled clock and not stealing access to the USB device driver enable output; …
> [usbdev] Usbdev block level smoke test improvements for V1

- sw/device/sca/aes_serial.c
- sw/device/sca/lib/sca.c
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/aes_sca.c
This PR fixes three bugs in the AES used for SCA in separate commits:
- Set the seed to the correct state
- Set the unused key shares
- Configure entropy complex for SCA measurements
> [pentest] Fix bugs in AES SCA

- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/crypto/ecdsa.rs
- sw/host/opentitanlib/src/crypto/rsa.rs
- sw/host/opentitanlib/src/util/hexdump.rs
- sw/host/opentitanlib/src/util/mod.rs
- sw/host/opentitantool/src/command/ecdsa.rs
- sw/host/opentitantool/src/command/spi.rs
1. Order ECDSA keys and signatures in little-endian order.
2. Add hexdump emit and parse functions (needed in the future for tests that check binary data).
> [opentitanlib] Order ECDSA keys and signature correctly 

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_lc_escalation_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_smoke_vseq.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cfg.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
- Block a few more transaction generators to prevent failure with rand_reset.
- Set the in_init and in_key_req flags in either process_tl_access, or in the req_mem_init and req_key_scr, depending on whether the scoreboard is enabled. Setting it in both was causing retriggering of key requests.
- Avoid request for scramble key by itself in the smoke sequence since it adds no verification value and causes integrity errors.
> [dv,sram_ctrl] Fix a few test failures

- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
It seems that on the Teacup board IOB11 is routed to CN9.21 and IOB12 is routed to CN9.19, the opposite of how there were declared.  As far as I recall, the two signals were swapped at some point during Teacup design review, in order for HyperDebug I2C capabilities to match how ChromeOS intends to use the pins of OpenTitan.
> [opentitantool] Update hyperdebug_teacup.json to match hardware

- rules/opentitan/cc.bzl
- rules/opentitan/defs.bzl
- rules/opentitan/fpga_cw310.bzl
At the moment, some tests manually clear the bitstream *before* the tests but really we ought to be doing the opposite which is to clear the bitstream *after* the test if it touches the OTP. This way, such a test can be safely followed by a "normal" tests.
This commit introduces the notion of a post_test_{harness,cmd} that is run after the normal test_harness (on success and failure). The fpga310 parameters are modified so that they take an extra "clear_bitstream" argument that uses this post test command to clear the bitstream if requested.
This should be combined with #21645
> [bazel] Rework bitstream clearing in tests

- hw/ip/uart/dv/env/seq_lib/uart_intr_vseq.sv
Fix occasional failures of the `uart_intr` test by adding a cycle of delay when checking the `TxWatermark` interrupt with the lowest watermark level.
Also update the uart "Theory of Operation" documentation to reflect the switch to status-type interrupts for these watermark interrupts.
> [uart,dv] Fix uart TX watermark interrupt test

- hw/ip/uart/doc/theory_of_operation.md
Update the uart "Theory of Operation" documentation to reflect the switch to status-type interrupts for these watermark interrupts.
> [uart,doc] uart watermark documentation update

- hw/ip/usbdev/data/usbdev.hjson
- hw/ip/usbdev/doc/registers.md
- hw/ip/usbdev/rtl/usb_fs_nb_in_pe.sv
- hw/ip/usbdev/rtl/usb_fs_nb_pe.sv
- hw/ip/usbdev/rtl/usbdev.sv
- hw/ip/usbdev/rtl/usbdev_reg_pkg.sv
- hw/ip/usbdev/rtl/usbdev_reg_top.sv
- hw/ip/usbdev/rtl/usbdev_usbif.sv
This ~~draft~~ PR relates to a discussion of perfective changes in #19435 (open) and #18942 (closed and subsumed).
There are two distinct cases when we may want to retract IN packets that have been presented for collection by the USB host, and which are still marked as ready for transmission ('rdy' bit set in 'configin'):
- Isochronous IN traffic, when there is new data available (for Isochronous streams the more recent data is more important than older data)
- Loss of ACKnowledgement of the final IN packet within the Data Stage of a Control Transfer; in this case, the missing acknowledgement is to be detected by the lack of a 'pkt_sent' interrupt for the IN Endpoint and the arrival of the zero-length OUT DATA packet that is the Status Stage. (See '8.5.3.3 Error Handling on the Last Data …
> [usbdev] Support the safe retraction of IN packets

- hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otp_ctrl_testplan.hjson
I saw these tests had been ported to sival so have added `bazel: [...]` links in the testplan.
> [lc_ctrl] Add lc_ctrl_otp_hw_cfg_test to testplans

- hw/ip/spi_host/rtl/spi_host_fsm.sv
The original change cause the `chip_sw_spi_host_tx_rx` test to fail and thus causes failing CI checks on `master`.
For now, revert the commit.
A proper fix is being worked on.
See https://github.com/lowRISC/opentitan/pull/21338#issuecomment-1984908004 for details.
> [spi_host,rtl] Revert "[spi_host,rtl] Use sd_en_o[0] to only drive sd_o[0] during TX (std_mode)"

- third_party/nist_cavp_testvectors/repos.bzl
This PR is a follow-up to #21896, which makes the same change for ECDSA. 
Adds the URLs to download the remaining NIST test vectors from the lowRISC-owned GCB as a backup, since `csrc.nist.gov` has experienced recent network issues.
Dependent on #21896
> [cryptotest] Add URLs for GCB-backed mirrors of NIST test vectors

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
Adding names in testplan as these two vseqs has been merged and not added to regression yet.
> [RV_DM] Add seq_names in Test plan

- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
There is no functional change here: we're just listing the sequences alphabetically in usbdev_vseq_list.sv and in usbdev_sim_cfg.hjson. This avoids an annoying situation where every PR is trying to add something at the bottom of the list and thus conflicts.
Now, we can insert a new PR at its point in the alphabetical list and should hopefully have simple merges most of the time.
> [usbdev,dv] Sort sequences (mostly) alphabetically

- sw/device/tests/BUILD
This test has had some flaky behaviour with the UART communication between the FPGA and HyperDebug. I haven't yet debugged the cause, so disabling until it's fixed.
> [sival] Disable uart_tx_rx test in CI

- hw/ip/adc_ctrl/data/adc_ctrl.hjson
- hw/ip/adc_ctrl/doc/interfaces.md
- hw/ip/adc_ctrl/doc/registers.md
- hw/ip/adc_ctrl/dv/env/adc_ctrl_scoreboard.sv
- hw/ip/adc_ctrl/dv/tb.sv
- hw/ip/adc_ctrl/rtl/adc_ctrl.sv
- hw/ip/adc_ctrl/rtl/adc_ctrl_intr.sv
- hw/ip/adc_ctrl/rtl/adc_ctrl_reg_pkg.sv
- hw/ip/adc_ctrl/rtl/adc_ctrl_reg_top.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/sw/autogen/chip/top_earlgrey.rs
- hw/top_earlgrey/sw/autogen/top_earlgrey.c
- hw/top_earlgrey/sw/autogen/top_earlgrey.h
- sw/device/lib/dif/autogen/dif_adc_ctrl_autogen.c
- sw/device/lib/dif/autogen/dif_adc_ctrl_autogen.h
- sw/device/lib/dif/autogen/dif_adc_ctrl_autogen_unittest.cc
- sw/device/lib/testing/autogen/isr_testutils.c
- sw/device/lib/testing/autogen/isr_testutils.h
- sw/device/tests/autogen/plic_all_irqs_test.c
- sw/device/tests/sim_dv/adc_ctrl_sleep_debug_cable_wakeup_test.c
- sw/device/tests/sim_dv/ast_clk_rst_inputs.c
This fixes the `adc_ctrl` portion of #21832
> [adc_ctrl] Change collated IRQ to status type

- hw/dv/sv/i2c_agent/i2c_if.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_perf_vseq.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
- hw/ip/i2c/rtl/i2c_fsm.sv
As titled, basically.
This change caused a lot of breakage in the i2c block level DV, which I have not been able to fully mitigate.
This is primarily around breaking the START/RSTART detection routines in the monitor, which causes the monitor to lose it's lock 
on the bus traffic.
For now, I have weakened the monitor checks for the correct Setup/Holds around these events, which mostly fixes the breakage.
There is still one test that fails systematically with this change, `i2c_host_rx_oversample`.
(On a related note, this test seems to be misnamed, as the testplan description doesn't gel with its implementation IMO. It could be a candidate for removal)
I proposed merging this RTL change with the DV mitigations for now, and removing the broken test from the regression for now. Then to …
> [i2c,rtl] Remove double-counted t_f

- hw/dv/tools/dvsim/tests/stress_all_test.hjson
- hw/dv/tools/dvsim/tests/stress_tests.hjson
- hw/ip/rv_timer/dv/rv_timer_sim_cfg.hjson
A few more instances where the comment uses milliseconds but the value is in whole seconds.
> [dv] Fix more timeout comments with wrong units

- hw/ip/usbdev/data/usbdev_testplan.hjson
- Include some further stress tests for invalid traffic, clock frequency adjustment to match the USB host traffic, and retraction of IN packets (improved Isochronous support).
- Additional tests for aon/wake module. Previously excluded from usbdev block level DV because it lies outside of the usbdev IP block. It should be incorporated into the usbdev TB and DV environment.
> [dv,usbdev] Test plan additions for V1

- sw/device/silicon_creator/rom/boot_policy.c
- sw/device/silicon_creator/rom/boot_policy_unittest.cc
- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
- sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_big_image/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_big_image/resizable_test.c
- sw/host/opentitanlib/src/image/image.rs
- sw/host/tests/rom/e2e_bootstrap_entry/src/main.rs
This fixes #21553.
Note, this simply removes the restriction. Additional changes will be required to truly support dynamic ROM_EXT / Owner slot sizes (if that is deemed desirable in the future).
> [rom] remove 64k ROM_EXT code size restriction

- sw/device/silicon_creator/lib/sigverify/spx_key.h
- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/keys/fake/rsa/BUILD
- sw/device/silicon_creator/rom/keys/fake/spx/BUILD
- sw/device/silicon_creator/rom/keys/fake/spx/sigverify_spx_keys_fake.c
- sw/device/silicon_creator/rom/keys/real/rsa/BUILD
- sw/device/silicon_creator/rom/keys/real/spx/BUILD
- sw/device/silicon_creator/rom/keys/real/spx/sigverify_spx_keys_real.c
- sw/device/silicon_creator/rom/sigverify_key_types.h
- sw/device/silicon_creator/rom/sigverify_keys.c
- sw/device/silicon_creator/rom/sigverify_keys.h
- sw/device/silicon_creator/rom/sigverify_keys_rsa.h
- sw/device/silicon_creator/rom/sigverify_keys_spx.h
1. Move key types into a separate module: We are trying to maintain the same key definitions for SPX+ after the keys are moved to OTP. This change moves key type definitions into a separate module so that they can be reused by a future sigverify otp implementation.
2. Add ECDSA key type to sigverify_key_types.
3. Introduce the `sigverify_spx_config_id_t` type to select between SPX signature parameters.
This change is part of #21204
> [rom-a1] Root Keys in OTP - Refactor ROM key types

- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/sigverify_otp_keys.c
- sw/device/silicon_creator/rom/sigverify_otp_keys.h
The module contains the following functions:
- `sigverify_otp_keys_init()`: Initializes the OTP keys context in SRAM.
- `sigverify_otp_keys_check()`: Verifies the integrity of the OTP keys.
- `sigverify_otp_keys_get()`: Gets a key from the OTP keys array stored
in the SRAM context.
This change is part of https://github.com/lowRISC/opentitan/issues/21204
> [rom-a1] Adds module to load keys from OTP.

- hw/ip/spi_host/data/spi_host.hjson
- hw/ip/spi_host/doc/registers.md
- hw/ip/spi_host/doc/theory_of_operation.md
- hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
- hw/ip/spi_host/rtl/spi_host.sv
- hw/ip/spi_host/rtl/spi_host_core.sv
- hw/ip/spi_host/rtl/spi_host_data_fifos.sv
As the byte_select block greedily fetches TX words from the TX FIFO and is backpressured by the shift_register when outputting bytes, we can consider the byte_select to be effectively an N+1'th stage for the TX FIFO.
To avoid this storage being untracked from the perspective of software, use the byte_valid_o to augment the fifo status signals (tx_qd,txfull,txempty) so that they incorporate this extra word of data.
TODO:
The DV around the `txqd` / `txwm` is quite limited, it would be good to add more robust checking into the scoreboard as a follow up to this change. 
Should close https://github.com/lowRISC/opentitan/issues/17644
> [spi_host,rtl] Factor the byte_sel block into TX FIFO status signals

- hw/dv/sv/common_ifs/clk_rst_if.sv
If you accidentally set the frequency to something negative then you can end up with a period of zero ps and the simulator gets stuck in an infinite loop. This is rather confusing to debug, when the test times out half an hour later. Boo!
Die instantly instead.
> [dv] Add checks to set_freq_*hz

- ci/scripts/run-fpga-tests.sh
Follow-up on #21757 where I forgot to add the manual tag in two places.
When looking at ROM or SiVal tests to determine if they should be run, ignore siblings tests marked as broken OR manual. Otherwise we may end up ignoring a test because of a sibling marked as manual that won't run either!
> [ci] Correctly ignore manual tests when filtering

- hw/ip/uart/dv/env/seq_lib/uart_loopback_vseq.sv
Fix issue caused by a rouge `0` sneaking in to the RX logic and causing a false START when switching from line_loopback to system_loopback without sufficient delay to flush the CDC sync.
> [uart,dv] Fix loopback test when using CDC sync

- sw/device/lib/testing/BUILD
- sw/device/lib/testing/hexstr.c
- sw/device/lib/testing/hexstr.h
- sw/device/lib/testing/hexstr_unittest.cc
- sw/device/lib/ujson/rust/BUILD
- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/nonce.c
- sw/device/silicon_creator/lib/nonce.h
- sw/host/opentitanlib/src/util/unknown.rs
- sw/host/tests/xmodem/BUILD
- sw/vendor/BUILD
Add or correct a number of utility modules to prepare for ownership code.
1. Teach `with_unknown` enums about `clap` (for opentitantool CLIs).
2. Add a build target for `cryptoc` (ECDSA verification until silicon_creator sigverify is ready).
3. Add a library for dealing with hex strings in firmware (for easier expression of test patterns).
4. Improve the `nonce` library (add `new` and `equal` functions).
> [ownership] Miscellaneous preparation

- sw/host/cryptotest/testvectors/data/schemas/aes_gcm_schema.json
- sw/host/cryptotest/testvectors/parsers/nist_cavp_aes_gcm_parser.py
Fix 1:
Currently, there are no FAIL cases in the GCM encryption test vectors. However, for decryption test vectors, if a test vector lacks a Plaintext (PT) field, the result of that particular test vector will be marked as FAIL.
In the initial PR, we accidentally marked the expected result as PASS if
there is no Plaintext (PT) field in the test vector, regardless it's
operation mode.
Fix 2:
In this PR, we include the missing auth tag from the test vectors into
the schema and parser.
> [cryptotest] Fix AES-GCM schema and test vector parser

- rules/opentitan/defs.bzl
- rules/opentitan/keyutils.bzl
- sw/device/silicon_creator/rom/e2e/sigverify_spx/BUILD
- sw/device/silicon_creator/rom/e2e/sigverify_spx/sigverify_spx_test.c
1. Upgrades the `rom_e2e_sigverify_spx` test suite to use the new `opentitan_test` Bazel macro.
2. Add SPX utils to keyutils.bzl
Part of #20090
> [rom e2e] Upgrade sigverify_spx tests

- sw/device/sca/aes_serial.c
- sw/device/sca/kmac_serial.c
- sw/device/sca/lib/sca.c
- sw/device/sca/lib/sca.h
- sw/device/sca/otbn_vertical/ecc256_keygen_serial.c
- sw/device/sca/otbn_vertical/ecc256_modinv_serial.c
- sw/device/sca/sha3_serial.c
- sw/device/tests/crypto/cryptotest/firmware/aes_sca.c
- sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
- sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
- sw/device/tests/crypto/cryptotest/json/aes_sca_commands.h
On the FPGA, the AES block automatically raises the trigger allowing to perform SCA analysis. As this is not available on the chip, this PR extends the AES SCA code to manually handling the trigger.
The arming of the trigger is implemented in the `sca_call_and_sleep_trigger` to keep the trigger window as narrow as possible (this reduces the number of samples needed and helps to easier setup the SCA gear).
The host code is located in lowRISC/ot-sca#329.
> [pentest] Add support for AES SCA measurements on chip

- sw/device/lib/crypto/BUILD
- sw/device/lib/crypto/include/BUILD
- sw/device/lib/crypto/include/datatypes.h
- sw/device/lib/crypto/include/freestanding/BUILD
- sw/device/lib/crypto/include/freestanding/defs.h
- sw/device/lib/crypto/include/freestanding/hardened.h
- sw/device/lib/crypto/include/otcrypto.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/otcrypto_export_test.c
Add a top-level header file that includes all other cryptolib headers.
> [cryptolib] Add a top-level `otcrypto.h` header

- third_party/python/pip.bzl
Some systems were getting permissions errors when trying to install Bazel-managed python packages. This updates the pip configuration and installation process to fix these errors.
> [bazel] fix python package error on debian systems

- hw/ip/otp_ctrl/doc/theory_of_operation.md
- hw/ip/prim/rtl/prim_otp_pkg.sv
- hw/ip/prim_generic/rtl/prim_generic_otp.sv
This a security patch for closing out D2S for OTP_CTRL.
Fixes #21948
> [otp_ctrl] Increase Hamming distance in OTP commands

- rules/autogen.bzl
- util/rom_chip_info.py
- util/rom_chip_info_test.py
**Context**
The ROM contains a `chip_info` structure that records the git hash at the build time. Unfortunately, this also prevents caching in CI and it provides little benefit in general since it does not record if the git hash is clean or not.
**Proposed change**
This PR disables bazel stamping by default so that the ROM chip_info will contain a **fixed** hash by default. The original behaviour can be restore by explicitley building with `--stamp`, e.g. `./bazelisk.sh --stamp ...`. The only instance that I can think of where we want this hash is probably for releases anyway.
> Disable ROM chip info stamping

- sw/device/tests/BUILD
- sw/host/tests/chip/usb/BUILD
- sw/host/tests/chip/usb/usb_harness.rs
On teacup, the VBUS sense buffer is disabled by default so the device cannot detect VBUS. This PR introduces a new test harness that bootstraps the device and enable VBUS sensing.
> [usb,sival] Add a USB test harness for silicon exec_env

- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_min_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_nak_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_stall_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_trans_nak_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_received_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_sent_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_random_length_out_transaction_vseq.sv
It turns out that we almost never need the sequence to have an opinion about num_of_bytes. The only time it matters is when we send an OUT packet to populate a buffer and then try to read the data back out again with an IN packet.
In those situations, we pick up the correct num_of_bytes value for configuring the IN packet by looking at the data packet that we just sent (see usbdev_pkt_sent_vseq for an example).
> [usbdev,dv] Remove num_of_bytes from base vseq

- sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c
The expected ADC filter_status CSR should have the Trans bit set. Notice ADC is only tested in sim_dv, so this doesn't affect sival.
> [dv,top_level] Fix pwrmgr_*_sleep_all_wake_ups tests for sim_dv

- hw/ip_templates/pwrmgr/dv/env/pwrmgr_scoreboard.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/pwrmgr_scoreboard.sv
Calling reset_asserted propagates the reset to the csr package.
> [dv,pwrmgr] Use reset_asserted instead of setting under_reset

- BLOCKFILE
This ensures that you can't add yourself to the COMMITTERS list without authorization
> [ci] Add COMMITTERS to BLOCKFILE

- hw/ip/otbn/dv/smoke/BUILD
- hw/ip/otbn/dv/smoke/smoke_test.s
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- rules/otbn.bzl
- sw/device/tests/BUILD
- sw/device/tests/otbn_isa_test.c
Test re-using the `smoke_test.s` sequence to check the OTBN instructions are working as expected. Loads from the `RND` and `KEY_*` registers have been removed so the sequence is deterministic. These loads are OK to remove because the load instruction is used in the OTBN randomness test, which is also run in SiVAl
Covers: https://github.com/lowRISC/opentitan/issues/20114
> OTBN ISA Test

- sw/device/tests/aon_timer_smoketest.c
In non-TestROM environements, the ROM enables the NMI for the watchdog which is not caught by the test. This commit makes the code handle the NMI in non-testrom.
One could say that with this change, the test becomes quite close to the aon IRQ test but it is still simpler I think.
> [aon_timer,sival] Fix aon_timer_smoketest in silicon

- hw/ip/usbdev/rtl/usb_fs_nb_in_pe.sv
This PR addresses a couple of defects in the IN packet engine:
- Handling of IN token packet reception whilst awaiting the ACK from a previous IN transaction did not check whether the endpoint is active. This aspect of the endpoint configuration is not expected to change whilst the USB device is connected, and the host should not be attempting to retrieve packets from an endpoint that is not being used. The logic should be consistent, however.
- Recent change to maintain IN buffer properties throughout the transaction (#21771) was incomplete; the logic needs qualifying with the two IN transaction states to capture the buffer properties only at the start of an IN transaction. verification effort still pending. Spotted by inspection when implementing event counters.
> [usbdev] Fixes to IN packet engine

- hw/ip/usbdev/data/usbdev_testplan.hjson
This PR contains the addition of the usbdev_phy_pins_sense name to the test plan, so this sequence should be included in the coming regressions.
> [usbdev,dv] add usbdev_phy_pins_sense name in testplan

- hw/dv/sv/usb20_agent/usb20_block_if.sv
- hw/ip/usbdev/dv/tb/tb.sv
The names here look a bit mad (the "_i" signals in the interface get assigned to) and they aren't really doing anything.
Short-circuit the assignment in tb.sv and remove the unused signals.
> [usbdev,dv] Remove usb_d[pn]_i from usb20_block_if

- azure-pipelines.yml
We're not getting much value out of this CI step at the moment because it has been failing for a long time. Disabling until somebody can fix it. Arguably this is sweeping it under the rug and may delay it getting fixed even more, but because we've been ignoring its warnings we could miss other more interesting failures.
See https://github.com/lowRISC/opentitan/issues/21973.
> [ci] Disable experimental bazel tags step

- sw/host/opentitanlib/src/tpm/driver.rs
Some TPM operations, such as generating RSA keypairs can take several minutes (at least on Google's legacy Titan chips).  This PR increases the time that opentitantool is willing to wait for the TPM status register to indicate that a command is done being processed.
> [opentitantool] Increase TPM timeout to match ChromeOS

- hw/ip/kmac/data/kmac.hjson
The SW-visible interface of the KMAC HW IP block has changed when the `fifo_empty` interrupt got its type changed to status (commit 23e491fee6b885a8c45ff5529c50fd486f00393c).  This calls for a major version bump.
Note that also as part of the PRNG reworking in https://github.com/lowRISC/opentitan/pull/21624 the CSRs changed, which is another reason for this major version bump.
This closes #20978.
> [kmac] Bump version to 2.0.0

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_adc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aon_timer_testplan.hjson
- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_edn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson
- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson
- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otp_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rom_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_dm_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_plic_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_timer_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_uart_testplan.hjson
- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
1. Explicitly set sival stage as `NA` for test cases we are not planning to run in SiVal.
2. Reduce the number of test permutations by only running test cases in `PROD` state whenever applicable.
3. Explicitly add missing `lc_states` attribute to test cases having the `si_state` attribute set to a value different than `NA`.
> [sival] Test plan updates

- hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
Increase the upper bound on the number of pending requests upon escalation by one due to CDC for lc_escalation_en_i. This assertion was causing a number of unit test failures.
> [dv,sram_ctrl] Fix failing assertion

- sw/device/info_sections.ld
- sw/device/lib/runtime/log.h
- sw/device/lib/testing/test_framework/ottf_common.ld
- sw/device/silicon_creator/manuf/lib/sram_program.ld
- util/device_sw_utils/extract_sw_logs.py
To make cherry-picking and potential reverts easier, this PR extracts and applies the commits from #21379 that ensure LLD compatibility but doesn't yet enable the use of LLD. The former commit will then just enable LLD.
Thanks to @a-will for his suggestion on how to fix the linker script to make it compatible with LLD while keeping it compatible with the BFD linker.
> Prepare for LLD

- sw/device/lib/runtime/log.c
- sw/device/lib/runtime/log.h
Even though the struct `log` parameter of `base_log_internal_core` is logically constant, we were doing a `memcpy` from flash to the stack. Tweak the code to prevent that.
This saves on code size and cycles. E.g.:
```
text	   data	    bss	    dec	    hex	filename
19882	    132	   8176	  28190	   6e1e	old-test_rom_sim_verilator.elf
19352	    132	   8176	  27660	   6c0c	new-test_rom_sim_verilator.elf
```
> Optimize `base_log_internal_core`

- hw/dv/sv/uart_agent/uart_agent_cfg.sv
- hw/dv/sv/uart_agent/uart_driver.sv
- hw/dv/sv/uart_agent/uart_if.sv
- hw/dv/sv/uart_agent/uart_logger.sv
- hw/dv/sv/uart_agent/uart_monitor.sv
- hw/ip/uart/dv/env/seq_lib/uart_base_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_intr_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_rx_oversample_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_rx_start_bit_filter_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_tx_ovrd_vseq.sv
- hw/ip/uart/dv/env/uart_scoreboard.sv
Fix the incorrect naming and usage of time-related variables. Mostly this stems from the `_ns` suffix of `uart_clk_period_ns`, despite being assigned a `realtime` value rather than an integer number of nanosecond. Correct this by renaming to `uart_clk_period` and adjusting downstream usage as seemed most appropriate.
Also correct some comment typos in the wider uart DV code.
> [uart,dv] Correct uart time unit mishaps & typos

- hw/ip/tlul/lint/tlul_lc_gate.vlt
This fixes the "non-vendored half" of #21716.
> [tlul,lint] Tell Verilator to split a process to avoid an UNOPTFLAT

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_exception_vseq.sv
This commit is to remove rv_dm_progbuf_exception testpoint entry as this functionality is already covered in rv_dm_cmderr_exception vseq. So this testpoint is no longer needed.
> [RV_DM]remove progbuf_exception testpoint entry

- hw/ip/uart/README.md
- hw/ip/uart/data/uart.hjson
- hw/ip/uart/doc/registers.md
- hw/ip/uart/dv/README.md
- hw/ip/uart/dv/env/seq_lib/uart_base_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_fifo_full_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_intr_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_long_xfer_wo_dly_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_loopback_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_perf_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_tx_ovrd_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_tx_rx_vseq.sv
- hw/ip/uart/dv/env/uart_env_cov.sv
- hw/ip/uart/dv/env/uart_env_pkg.sv
- hw/ip/uart/dv/env/uart_scoreboard.sv
- hw/ip/uart/dv/uart_sim_cfg.hjson
- hw/ip/uart/lint/uart.waiver
- hw/ip/uart/rtl/uart_core.sv
- hw/ip/uart/rtl/uart_reg_pkg.sv
- sw/device/lib/dif/dif_uart.c
- sw/device/lib/dif/dif_uart_unittest.cc
The UART FIFOs had been increased from 32B to 128B for Earlgrey ES, predominantly due to the fact that there was a requirement for 128B deep RX FIFOs. Such a requirement does however not exist for the TX FIFO and it can be just 32B deep.
Since the design only supported a homogeneous arrangement, both RX and TX FIFOs had been set to the same depth. This patch reworks that and makes both depths individually configurable.
> [uart] Reduce TX FIFO depth from 128B to 32B

- .bazelrc
This is something that we already wanted to enable, to support LTO, ePIC, etc.
Enabling this now also solves a problem when upgrading the Rust toolchain.
> Use LLD for linking

- sw/device/lib/dif/dif_flash_ctrl.c
- sw/device/lib/dif/dif_flash_ctrl_unittest.cc
Initialize returned objects from objects built by initialization to avoid read-modify-write on potentially uninitialized memory. Without this some tests were getting ECC errors from uninitialized sram. Specifically this addresses failures Nuvoton saw for the chip_sw_pwrmgr_sysrst_ctrl_reset test.
> [dif,flash_ctrl] Avoid reading potentially uninitialized memory

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/ecdh_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/nist_cavp_ecdh_parser.py
- third_party/nist_cavp_testvectors/repos.bzl
This PR adds the parser for the NIST CAVP ECDH test vectors.
~Dependent on #20878~
> [cryptotest] ECDH NIST test vector parser

- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_test_access_vseq.sv
CDC can cause temporary On values when transitioning between arbitrary values. This is not a realistic attack mode since
- Mubi cannot protect against all bits being glitched,
- getting an ON value due to CDC requires the mubi values before and after the CDC transition to have close enough Hamming distance to On, and is as hard or harder than glitching all bits to On.
This avoids infrequent failures in otp_ctrl_test_access.
> [dv,otp_ctrl]  Avoid back-to-back lc_dft_en random values

- hw/top_darjeeling/dv/chip_sim_cfg.hjson
As Darjeeling has a second rom_ctrl, the post-reset sequence takes more time.
With the increased timeouts, all affected tests pass 100% (even with a 5x reseed multiplier).
> [top_darjeeling/dv] Increase timeout of some SW tests

- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/ip/usbdev/dv/env/usbdev_env_cov.sv
Initial set of covergroups and coverpoints for usbdev DV.
Disclaimer: coverage DV is very unfamiliar at this point, and none of the DV code collects samples presently.
> [dv,usbdev] Initial coverage for usbdev

- hw/ip/kmac/data/kmac.hjson
- hw/ip/kmac/doc/theory_of_operation.md
- hw/ip/kmac/pre_dv/kmac_reduced_tb/rtl/kmac_reduced_tb.sv
- hw/ip/kmac/pre_sca/prolead/kmac_reduced_config.set
- hw/ip/kmac/rtl/kmac_entropy.sv
- hw/ip/kmac/rtl/kmac_reg_pkg.sv
- sw/device/lib/dif/dif_kmac.h
- sw/device/lib/dif/dif_kmac_unittest.cc
- sw/device/sca/kmac_serial.c
- sw/device/sca/sha3_serial.c
- sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
- sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
- sw/device/tests/kmac_idle_test.c
- sw/device/tests/kmac_mode_cshake_test.c
- sw/device/tests/kmac_mode_kmac_test.c
- sw/device/tests/kmac_smoketest.c
- sw/device/tests/sim_dv/csrng_lc_hw_debug_en_test.c
To reduce area, this PR switches the stream cipher primitive inside the PRNG of KMAC from Trivium to Bivium. It was found that the security posture of Bivium is sufficient in this application scenario. This should give us back around 10 kGE. 
Please don't merge this yet. The SCA evaluation is currently running and I will update the PR with the results.
> [kmac] Switch PRNG stream cipher primitive from Trivium to Bivium

- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
On top of the RV32I mandatory counters this just leaves the counters for data memory and instruction memory waits. The others are counting different types of instructions being executed so are purely a property of the architectural behaviour of the program so could be found another way (e.g. via simulation) where the wait counters cannot be easily modelled.
This will drop 8 * 32 * 2 (counters are duplicated due to lockstep) = 512 flops out of the design along with associated logic for incrementers and reduce inputs on muxes in the Ibex CSR block.
For reference the details on performance counters in Ibex can be found here: https://ibex-core.readthedocs.io/en/latest/03_reference/performance_counters.html
With this change only events 0-4 from that documentation will have counters.
Before …
> [rv_core_ibex,rtl] Reduce number of performance counters

- hw/ip/i2c/doc/programmers_guide.md
- hw/ip/i2c/doc/theory_of_operation.md
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_rx_oversample_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_perf_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_smoke_vseq.sv
- hw/ip/i2c/rtl/i2c_fsm.sv
Because the spec's data hold time is nominally 0, there are situations where an SDA change may arrive before an SCL change after CDC. This can give the appearance that a controller has sent a Start or Stop symbol, when the next bit was intended to be data, leading to unintended outcomes.
However, Start and Stop symbols have a significant required hold time, a period after the SDA transition when SCL is not allowed to change. Use some of this period to disambiguate data vs. control symbols. Require SCL to be held stable for at least thd_dat for a control symbol to complete decoding.
Note that thd_sta and t_buf must be longer than thd_dat, and thd_dat must be at least 1 cycle. Adjust the randomization of timing parameters in DV so this constraint is properly observed.
> [top_darjeeling,i2c] Reject Start/Stop if SCL changes too soon

- hw/ip/tlul/rtl/tlul_lc_gate.sv
If the sink port takes longer to respond, the internal counter for outstanding transfers would overflow. This PR adds the ability to parametrize the counter for the number of outstanding transactions
> [hw,prim_tlul_gate,rtl] Parametrize the number of outstanding transfers

- hw/ip/aes/pre_dv/aes_cipher_core_tb/rtl/aes_cipher_core_tb.sv
- hw/ip/aes/pre_sca/prolead/aes_cipher_core_config.set
- hw/ip/aes/rtl/aes_cipher_control.sv
- hw/ip/aes/rtl/aes_cipher_core.sv
- hw/ip/aes/rtl/aes_core.sv
- hw/ip/csrng/rtl/csrng_block_encrypt.sv
This PR contains mainly two changes:
1. A new compile-time parameter is added to the AES cipher core to only implement the forward operation of the cipher. Enabling this parameter inside CSRNG allows to completely trim away unused data paths only relevant for the inverse operation. Previously some logic wasn't optimized out due to synthesis optimization barriers placed around the control FSM (synthesis was no longer able to infer that some mux control signals never take on certain values). This allows optimizing away 256 FFs, one 256-bit 2-input mux, one 128-bit 2-input mux and some more inputs on other existing 256-bit and 128-bit muxes.
2. The generation of the PRD signals for register clearing are moved to the outside of the cipher core. This allows connecting the initial state and key …
> [aes, csrng] Reduce area of unmasked AES core inside CSRNG

- hw/ip/csrng/rtl/csrng_state_db.sv
This PR removes two redundant state copies inside the state database:
1. The state selected for software debugging via the INT_STATE_VAL CSR.
2. The state selected for the next command.
The design is modified to directly forward the content of the state database.
These changes allow to save 768 FFs in CSRNG (minus ~5 kGE).
> [csrng] Avoid redundant state copies for debugging and read out in state database

- sw/device/tests/BUILD
- sw/device/tests/pwrmgr_sleep_resets_lib.h
The test fails occasionally while printing the last bit of info the console due to a timeout. Extend the timeout to "moderate" so this failure mode does not continue to occur.
> [tests] Extend timeout of various tests

- sw/device/silicon_creator/lib/manifest.c
- sw/device/silicon_creator/lib/manifest.h
Fix naming bug in manifest extension getters. The extern declaration of the functions were not matching the naming generated by the manifest extension macros.
> [rom] Update manifest extension getters.

- hw/ip/uart/README.md
- hw/ip/uart/data/uart.hjson
- hw/ip/uart/doc/registers.md
- hw/ip/uart/dv/env/uart_scoreboard.sv
- hw/ip/uart/rtl/uart_reg_pkg.sv
- sw/device/lib/dif/dif_uart.c
- sw/device/lib/dif/dif_uart.h
- sw/device/lib/dif/dif_uart_unittest.cc
After more discussion with customers, it became clear that a 64B FIFO size is sufficient.
> [uart] Reduce RX FIFO depth from 128B to 64B

- hw/top_earlgrey/ip/ast/ast.core
- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/vcaon_pgd.sv
- hw/top_earlgrey/ip/ast/rtl/vcc_pgd.sv
- hw/top_earlgrey/ip/ast/rtl/vcmain_pgd.sv
- hw/top_earlgrey/ip/ast/rtl/vio_pgd.sv
This PR should fix #22037
Added some other minor changes:
spaces, rename of wire, rstmgr pgk location
> [ast] fixing always_comb lint errors

- sw/device/tests/crypto/BUILD
This test is broken on the ES due to the impossibility to safely issue a CSRNG command. See #19568. Mark as broken to avoid CI failures.
NOTE: this has been fixed on master.
> [sival,ci] Mark drbg_functest as broken

- hw/top_earlgrey/ip/ast/ast.core
ast is used in the englishbreakfast build, so it must depend on the virtual rstmgr_pkg.
> [ast] Revert dependency on top-specific rstmgr_pkg

- azure-pipelines.yml
- ci/azure-pipelines-nightly.yml
- ci/install-package-dependencies.sh
- doc/getting_started/README.md
- release/azure-pipelines-release.yml
- tool_requirements.py
- util/container/Dockerfile
The version we have been using was quite outdated and did not catch some legacy always @(*) statements that it should have warned about.
This updates to v0.0-3622-g07b310a3, and updates the installation instructions.
We may want to consider holding off merging, though, if this causes any infrastructure issues.
> [veriblelint] Update to v0.0-3622-g07b310a3

- sw/device/silicon_creator/lib/base/static_critical_boot_measurements.c
- sw/device/silicon_creator/lib/base/static_critical_epmp_state.c
- sw/device/silicon_creator/lib/base/static_critical_sec_mmio.c
- sw/device/silicon_creator/lib/manifest_def.c
- third_party/crt/repos.bzl
Update the CRT to a version that includes the LTO feature.
Adds `OT_USED` to variables that would seem unreferenced and thus could be discarded by LTO.
> Prepare for LTO

- sw/host/opentitanlib/src/bootstrap/legacy_rescue.rs
When OTT is used in scripts, the stderr is typically mapped to stdout. If we print something to stderr for every progress iteration, it breaks the progress bar updating in place, and instead each progress bar update will print on a newline instead of replacing itself.
With this change, the progress bar can update in place.
> [opentitantool] Remove eprint during legacy_rescue

- sw/device/lib/crypto/impl/BUILD
- sw/device/lib/crypto/impl/ecc.c
- sw/device/lib/crypto/impl/ecc/BUILD
- sw/device/lib/crypto/impl/ecc/ecdh_p384.c
- sw/device/lib/crypto/impl/ecc/ecdh_p384.h
- sw/device/lib/crypto/impl/ecc/ecdsa_p384.h
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_keygen.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_keygen.h
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_sign.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_sign.h
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_verify.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_verify.h
- sw/device/lib/crypto/impl/ecc/p384_common.c
- sw/device/lib/crypto/impl/ecc/p384_common.h
- sw/device/lib/crypto/impl/ecc/p384_curve_point_valid.c
- sw/device/lib/crypto/impl/ecc/p384_curve_point_valid.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/ecdh_p384_functest.c
- sw/device/tests/crypto/ecdsa_p384_functest.c
- sw/otbn/crypto/p384_ecdh.s
- sw/otbn/crypto/p384_ecdsa_keygen.s
- sw/otbn/crypto/p384_ecdsa_sign.s
- sw/otbn/crypto/p384_ecdsa_verify.s
- sw/otbn/crypto/p384_sign.s
This PR 
- adds Ibex driver code for P-384 ECC on OTBN. 
-> In case of ECDSA the code is split up into individual files for keygen, sign, and verify. This is because each function is a separate OTBN application. But still, everything is put together in a single ecdsa_p384 file, which then is used by the top level ecc driver file.
-> Similar, curve point validation is put into an own driver file, as it also is a separate OTBN application. It is executed before ECDH shared key generation and ECDSA signature verification, to check if the public key is valid (= is a curve point).
- adds the corresponding functests for P-384 ECDH and ECDSA.
- fixes some memory issues in the P-384 top level OTBN binaries, which we discovered during development.
> [cryptolib] Add Ibex drivers for P-384 ECDH and ECDSA on OTBN

- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/firmware/kmac.c
- sw/device/tests/crypto/cryptotest/firmware/kmac.h
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/kmac_commands.c
- sw/device/tests/crypto/cryptotest/json/kmac_commands.h
- sw/host/cryptotest/ujson_lib/BUILD
- sw/host/cryptotest/ujson_lib/src/kmac_commands.rs
- sw/host/cryptotest/ujson_lib/src/lib.rs
- sw/host/tests/crypto/kmac_kat/BUILD
- sw/host/tests/crypto/kmac_kat/src/main.rs
This PR adds the test harness for KMAC. The PR structure is identical to #21181, which serves the same purpose for HMAC.
> [cryptotest] Add KMAC test harness

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
- hw/ip/flash_ctrl/rtl/flash_phy.sv
- hw/ip/flash_ctrl/rtl/flash_phy_core.sv
- hw/ip/flash_ctrl/rtl/flash_phy_pkg.sv
- hw/ip/flash_ctrl/rtl/flash_phy_scramble.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy_core.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy_pkg.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy_scramble.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_hw_sec_otp_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_core.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_pkg.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_scramble.sv
Each bank had its own scrambling module, and since this is not needed from a throughput perspective (we typically only access one bank at a time), the module can be shared to save area.
Note that this change is transparent to DV, although we may want to regenerate UNR after this.
This fixes #3353
> [flash_ctrl] Share flash_scrambling module among banks

- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
If we do not include the signature variables in the UDS cert HJSON description then the `kUdsMaxCertSizeBytes` constant that is automatically generated via the certificate codegen infra does not accound for the signature bytes. If these bytes are not accounted for, then the ujson struct that holds the final endorsed UDS certificate will not allocate an ArrayVec of adequate size on the host side.
> [dice] add signature vars to UDS cert HJSON description

- hw/ip/otbn/data/otbn.hjson
- hw/ip/otbn/doc/registers.md
- hw/ip/otbn/doc/theory_of_operation.md
- hw/ip/otbn/dv/memutil/otbn_memutil.cc
- hw/ip/otbn/dv/tracer/rtl/otbn_trace_if.sv
- hw/ip/otbn/dv/uvm/otbn_model_agent/otbn_model_agent.sv
- hw/ip/otbn/dv/uvm/otbn_model_agent/otbn_model_agent_cfg.sv
- hw/ip/otbn/dv/uvm/tb.sv
- hw/ip/otbn/rtl/otbn_reg_pkg.sv
- hw/ip/otbn/rtl/otbn_reg_top.sv
Only to be merged if we choose to have the imem size increase.
@moidx @jadephilipoom please note with the larger imem size the branch instructions can no longer branch to any other instruction, it's limited to a 4 KiB window either side of the instruction (PC relative addressing). The jump instructions can continue to branch anywhere in imem. Hopefully this doesn't present any issues.
@rswarbrick I've seen some failures in the RIG, I believe due to this line of the `BadBranch` class:
https://github.com/lowRISC/opentitan/blob/53c6c771ed140efeefccf942ce5d875134ff3679/hw/ip/otbn/dv/rig/rig/gens/bad_branch.py#L42
This will no longer work as depending on which PC the bad branch is located at the top or bottom of memory may not be reachable. Could you look at a fix?
> Increase OTBN imem size to 8 KiB

- sw/device/silicon_creator/lib/base/sec_mmio.h
- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/otp.c
- sw/device/silicon_creator/lib/drivers/otp.h
- sw/device/silicon_creator/lib/drivers/otp_unittest.cc
This adds several functions to the OTP silicon_creator driver library to enable reading data from non-memory mapped, readable, partitions. This is required to enable measuring said OTP partitions for attestation key and cert generation purposes.
> [silicon_creator] add OTP DAI read functions to driver lib

- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/json/BUILD
- Update firmware target to support silicon targets
- Enable cryptotest silicon targets
> [cryptotest] Add support for silicon execution environments.

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/doc/entsrc_blk_diag.svg
- hw/ip/entropy_src/doc/programmers_guide.md
- hw/ip/entropy_src/doc/registers.md
- hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
- sw/device/tests/entropy_src_ast_rng_req_test.c
- sw/device/tests/entropy_src_fw_observe_many_contiguous.c
- sw/device/tests/entropy_src_fw_override_test.c
- sw/device/tests/entropy_src_fw_ovr_test.c
- sw/device/tests/sim_dv/ast_clk_rst_inputs.c
Halving the depth of the observe FIFO allows saving 1024 FFs. With a FIFO size of 1 kbit, it is still possible to buffer a full, contiguous 1024-sample window in single-channel mode. For the multi-channel mode, an experiment on the engineering sample showed that Ibex is fast enough in reading out the FIFO to avoid it overflowing during read out.
First block-level tests look good, I am running a full regression now. What also should be done:
- Check the affected TLTs explicitly.
- Check the documentation.
I'll continue this work later tonight.
> [entropy_src] Reduce depth of Observe FIFO

- hw/ip/pinmux/rtl/pinmux_strap_sampling.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- util/topgen/templates/chiplevel.sv.tpl
This hardwires the schmitt trigger enable to 1 for the JTAG Clk/Rst and POR signals for improved signal integrity.
> [top/pinmux] Enable Schmitt trigger for POR and JTAG Clk/Rst

- sw/device/lib/crypto/include/ecc.h
- sw/device/lib/crypto/include/kdf.h
These comments refer to the old method of representing hardware-backed keys (which used a field in the key configuration instead of the keyblob). This was changed in https://github.com/lowRISC/opentitan/pull/19714
Instead, adds guidance that directs callers to `otcrypto_hw_backed_key` for initializing these keys.
Thanks to @vsukhoml for finding this mistake! See https://github.com/lowRISC/opentitan/issues/21936#issuecomment-1989531303
> [crypto] Fix outdated cryptolib docstrings.

- hw/top_earlgrey/ip/ast/rtl/vcaon_pgd.sv
- hw/top_earlgrey/ip/ast/rtl/vcc_pgd.sv
- hw/top_earlgrey/ip/ast/rtl/vcmain_pgd.sv
- hw/top_earlgrey/ip/ast/rtl/vio_pgd.sv
This reverts commit e8bfccf76c80a082870348b4f2acfec2a27b3c17. The change here doesn't work at all (you can't put #(...) delays inside an always_comb).
Undo the change for now: we can try to fix things properly when CI is working again.
> Revert "[ast] fixing always_comb lint"

- hw/ip/spi_device/dv/base_sim_cfg.hjson
Sicne #21812 we have two spi_device variants, which use the same output path, which cause file name
collision when parallelism is increased.
Follow other blocks by adding variant name into the output path. See #21738 as another example.
> [dv] fix spi_device dvsim output path

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/doc/registers.md
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_fsm.sv
- hw/ip/i2c/rtl/i2c_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
This is a change to our I2C target. It essentially adds another timeout control register that can be set in the target that keeps track of how long it has been stretching for and otherwise NACK. The first 6 commits have no functional changes, so you can focus your reviews on the latter 10 commits (some of these have just auto-generated changes which are labelled accordingly).
There are many design parameters here and you can read a more detailed discussion in the issue: https://github.com/lowRISC/opentitan/issues/15227 But here's my take on a few of these:
There are two options here, stretch before the ACK or stretch afterwards. After discussion with @andreaskurth and @a-will we decided to stretch after the ACK to be closer to the current design and to align with I2C high-speed mode.
To …
> [i2c,rtl] NACK after timing out on a stretch

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/doc/registers.md
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
Based on the comment by @andreaskurth: https://github.com/lowRISC/opentitan/pull/21857#discussion_r1530248609
The 32 bits for this counter is a bit overkill. 8 bits should probably be enough since that means the software has missed a whole ACQ FIFO full of contents. Beyond this the value loses most of its meaning. This PR also saturates the counter.
> [i2c,rtl] Reduce NACK count size

- sw/device/silicon_creator/rom_ext/e2e/lockdown/BUILD
The lockdown tests no longer pass after the addition of the OTTF fault printint function.  Adjust the test exit conditions to detect correct execution of the tests.
> [rom_ext] Fix the lockdown tests

- hw/ip/spi_device/data/spi_device_testplan.hjson
This testpoint was written when we only had the two-port implementation. It makes sense in the 1r1w configuration too. Generalise the text a bit so that it is sensible either way.
Fixes #21863.
> [spi_device,dv] Generalise description of mem_cfg testpoint

- hw/dv/tools/xcelium/cov_report.tcl
Switch to using "detachable" HTML coverage reports when using xcelium, as the old format was no longer viewable in web browsers due to Cross-Origin Request Security (CORS) protection.
> [dv, xcelium] Use detachable reports to avoid CORS

- hw/ip/uart/dv/env/seq_lib/uart_base_vseq.sv
Adjust randomisation range of `rxilvl` and `txilvl` to automatically track `RxFifoDepth` and `TxFifoDepth` (assuming the relationship between FIFO depth and the number of levels remains the same).
Should restore `uart_intr` pass rate following recent reduction in RX and TX FIFO sizes.
> [dv, uart] Update RX/TX watermark randomisation

- hw/ip/spi_host/data/spi_host.hjson
- hw/ip/spi_host/doc/interfaces.md
- hw/ip/spi_host/doc/registers.md
- hw/ip/spi_host/rtl/spi_host.sv
- hw/ip/spi_host/rtl/spi_host_reg_top.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- sw/device/lib/dif/autogen/dif_spi_host_autogen.c
- sw/device/lib/testing/autogen/isr_testutils.c
- sw/device/lib/testing/autogen/isr_testutils.h
- sw/device/tests/autogen/plic_all_irqs_test.c
- sw/device/tests/spi_host_irq_test.c
Use prim_intr_hw #(.IntrT("status")) to create the status-type logic, which is
still driven from the 6 individual interrupt sources. Each input now becomes a
level-based signal, allowing removal of the flops which created pulses when the
inputs toggled.
TODO
Closes #21208
> [spi_host,rtl] Change 'spi_event' interrupt to CIP 'Status' type

- hw/top_earlgrey/data/chip_testplan.hjson
- sw/device/tests/sensor_ctrl_alerts.c
Extend sensor_ctrl_alerts.c to test each alert being disabled.
Fixes #21996
> [dv,sensor_ctrl] Add test for alert masking

- hw/ip/usbdev/data/usbdev.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_enable_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_received_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_random_length_out_transaction_vseq.sv
Some recent RTL changes shown below have not been mirrored with DV changes and thus sequences have been failing more often:
- the 'pkt_received' interrupt is now a Status type interrupt and will become deasserted when the RX FIFO entry is read.
- the 'configin' registers must now be excluded from automated CSR testing because there is an interaction among the register bits.
Additionally, since checking of the RX packet properties and content is now available within the base sequence, modify the OUT side sequences to benefit from this more extensive testing.
(Note that whilst the 'recover_orig_data' function is local to each affected sequence for now, rather than shared in the base class, this is because the function should soon be unnecessary. The action of transmitting a data packet …
> [dv,usbdev] Fixes to DV sequences for usbdev

- hw/ip/adc_ctrl/dv/env/adc_ctrl_scoreboard.sv
- hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_base_vseq.sv
- hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_filters_polled_vseq.sv
Clear the cfg.adc_*_ctl testbench variables upon reset. Skip monitor_intr_proc during reset.
> [dv,adc_ctrl] Fix bugs in scoreboard

- hw/top_earlgrey/ip/ast/ast.core
- hw/top_earlgrey/ip/ast/lint/ast.vbl
This waiver is described properly in the code. The reason to bother is that the rule failure is breaking CI at the moment. Eek!
> [lint,verible] Waive Verible's always-comb rule for AST blocks

- hw/ip/aon_timer/doc/programmers_guide.md
The programmer's guide is wrong here: you write 0 to lock the configuration. 1 indicates that writes are enabled.
> Correct the bit documented in the programmer's guide to lock the watchdog configuration

- sw/device/silicon_creator/lib/boot_svc/BUILD
- sw/device/silicon_creator/lib/boot_svc/boot_svc_msg.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_activate.c
- sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_activate.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_activate_unittest.cc
- sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_unlock.c
- sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_unlock.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_unlock_unittest.cc
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/datatypes.h
Add boot_svc command structures for the unlock and activate ownership commands.
> [boot_svc] Add unlock and activate ownership commands]

- sw/device/silicon_creator/manuf/lib/util.c
This fixes a bug in the computation of the OTP {Creator,Owner}SwCfg measurements that are used to lock the partition. The wrong offsets were being used.
> [cherry-pick] portion of #22124 onto `earlgrey_es_sival` branch

- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_aborted_low_power_vseq.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_invalid_vseq.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_wakeup_race_vseq.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_smoke_vseq.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv.tpl
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_aborted_low_power_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_invalid_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_wakeup_race_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_smoke_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_vseq.sv
- Wait for a few slow clock cycles between iterations of pwrmgr_aborted_low_power to avoid consecutive pulses in CDC due to cfg_cdc_sync being too close.
- Move wait_for_csr_to_propagate_to_slow_domain into update_control_csr to avoid missing calling it.
- Fix incorrect check in fast_check_wake_info.
- Change cycles waited before low power transition to slow clock.
> [dv,pwrmgr] Fix failures

- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
This updates the personalization firmware to print is hash over the console. This fixes #19455.
> [manuf] update perso firmware to self report its hash

- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/device/silicon_creator/lib/drivers/hmac.h
- sw/device/silicon_creator/lib/drivers/otp.c
- sw/device/silicon_creator/lib/drivers/otp.h
- sw/device/silicon_creator/lib/drivers/otp_unittest.cc
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
- sw/device/silicon_creator/manuf/lib/util.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
The Earlgrey PROD chip has additional OTP partitions (e.g., for first stage secure boot keys) that contribute to the overall TCB of the device. Hence, this adds their measurements to the UDS cert. This partially addresses #19455.
Note: this depends on #22060, only review the last 4 commits.
> [dice] add measurements of addition PROD OTP partitions to UDS cert

- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/hash.c
- sw/device/tests/crypto/cryptotest/json/hash_commands.h
- sw/device/tests/crypto/testvectors/BUILD
- sw/device/tests/crypto/testvectors/cshake_hardcoded.hjson
- sw/device/tests/crypto/testvectors/hash_hardcoded.hjson
- sw/device/tests/crypto/testvectors/kmac_hardcoded.hjson
- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/hash_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/hjson_hash_parser.py
- sw/host/cryptotest/testvectors/parsers/hjson_kmac_parser.py
- sw/host/tests/crypto/hash_kat/src/main.rs
This PR is a follow-on to #21195 and #21281 
- Split the KMAC and hash hjson test vectors into separate files
- Added parsers for hjson tests for KMAC and hash functions
- Updated test harness for hash functions to support SHA3-224 and cSHAKE
~Dependent on #21193~
> [cryptotest] Add manual tests for KMAC and hash functions

- sw/device/tests/BUILD
> [test] temporarily disable broken `csrng_smoketest`

- third_party/lint/repos.bzl
A bug fix was applied to how the `misc-linters` repository handles Python dependencies in Bazel.
> [lint] update lowRISC `misc-linters`

- sw/device/tests/BUILD
Due to #22152, this test has been failing on the CW310-only platform. Moving to run this only on the hyper310 platform as it is a sival example testcase. Sival test cases should run on an FPGA platform that is compatible between pre- and post-silicon environments.
> [tests] move flaky test to run only on hyper310

- azure-pipelines.yml
Embarrassingly I disabled the wrong step in #21974. This PR re-enables that step and disables the intended one.
> [ci] Disable flaky Bazel tags step

- hw/dv/sv/dv_lib/dv_base_monitor.sv
- hw/dv/sv/flash_phy_prim_agent/flash_phy_prim_monitor.sv
- hw/dv/sv/jtag_agent/jtag_monitor.sv
- hw/dv/sv/jtag_dmi_agent/jtag_dmi_monitor.sv
- hw/dv/sv/jtag_dmi_agent/sba_access_monitor.sv
- hw/dv/sv/jtag_riscv_agent/jtag_riscv_monitor.sv
- hw/dv/sv/key_sideload_agent/key_sideload_monitor.sv
- hw/dv/sv/kmac_app_agent/kmac_app_monitor.sv
- hw/dv/sv/pattgen_agent/pattgen_monitor.sv
- hw/dv/sv/push_pull_agent/push_pull_monitor.sv
- hw/dv/sv/pwm_monitor/pwm_monitor.sv
- hw/dv/sv/rng_agent/rng_monitor.sv
- hw/dv/sv/spi_agent/spi_monitor.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/otbn/dv/uvm/env/otbn_trace_monitor.sv
- hw/ip/otbn/dv/uvm/otbn_model_agent/otbn_model_monitor.sv
- hw/vendor/lowrisc_ibex/dv/uvm/icache/dv/ibex_icache_core_agent/ibex_icache_core_monitor.sv
- hw/vendor/lowrisc_ibex/dv/uvm/icache/dv/ibex_icache_mem_agent/ibex_icache_mem_monitor.sv
- util/uvmdvgen/README.md
- util/uvmdvgen/monitor.sv.tpl
This argument isn't actually used anywhere it's passed. Let's clean it up.
> [dv] Remove phase argument from monitor's collect_trans

- hw/dv/sv/dv_base_reg/dv_base_mubi_cov.sv
The existing type (int) doesn't technically allow the 32-bit mubi types. The problem is that MuBi32True has its top bit set and it's value (0x96969696) isn't representable as a signed 32 bit integer.
> [dv] Fix parameter types in dv_base_mubi_cov.sv

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/firmware/ibex_sca.c
- sw/device/tests/crypto/cryptotest/firmware/ibex_sca.h
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/ibex_sca_commands.c
- sw/device/tests/crypto/cryptotest/json/ibex_sca_commands.h
This commit adds the following penetration tests:
- ibex.sca.register_file_read
- ibex.sca.register_file_write
- ibex.sca.tl_read
- ibex.sca.tl_write
This code is used to check whether data written/read to/from the tegister file or transmitted over TL-UL leaks.
> [pentest] Ibex SCA tests

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.c
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.h
- sw/device/tests/crypto/cryptotest/firmware/status.h
- sw/device/tests/crypto/cryptotest/json/ibex_fi_commands.h
This commit adds the following FI penetrationt test that can be used to characterize Ibex:
- ibex.char.flash_read
- ibex.char.flash_write
- ibex.char.sram_read
- ibex.char.sram_write
- ibex.char.unconditional_branch
- ibex.char.conditional_branch
> [pentest] Add FI Ibex tests

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
No functional change, but VCS complains when compiling the code that was there before, saying that "The SystemVerilog LRM requires a non-empty 'for_initialization'."
I'm not completely convinced that VCS is right! Looking the "Loop statements" section of IEEE 1800, the syntax given is:
for ( [ for_initialization ] ; [ expression ] ; [ for_step ] )
Looking at the "Syntactic description" section near the top of the document, I see that stuff in square brackets denotes an optional item.
But it's nicer not to get warnings from the build step, so it's probably worth matching what VCS expects :-)
> [cip,dv] Fix nitty style problem in cip_base_vseq

- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
Introduces an inter-packet delay task in the base sequence, which will be utilized between packets in all sequence transactions.
> [usbdev,dv] adds inter_pkt_delay() task in usbdev_base_seq

- hw/ip/i2c/data/i2c.hjson
Since i2c was versioned at 1.1.0 (in 0a8d1b27eba), we made multiple changes that change the HW and SW interfaces of this HW IP block in a backward-incompatible way. `git diff 0a8d1b27eba..<this commit>^ -- hw/ip/i2c/data/i2c.hjson` gives a good overview:
```diff
diff --git a/hw/ip/i2c/data/i2c.hjson b/hw/ip/i2c/data/i2c.hjson
index 9e62d5095f..f316e58936 100644
--- a/hw/ip/i2c/data/i2c.hjson
+++ b/hw/ip/i2c/data/i2c.hjson
@@ -40,13 +40,16 @@
// INTERRUPT pins
interrupt_list: [
{ name: "fmt_threshold"
-      desc: "host mode interrupt: raised when the FMT FIFO depth is less than the low threshold."
+      desc: "host mode interrupt: asserted whilst the FMT FIFO level is below the low threshold. This is a level status interrupt."
+      type: "status"
}
{ name: "rx_threshold"
-      desc: …
```
> [i2c] Bump version to 2.0.0, set to D1/V0

- rules/opentitan/keyutils.bzl
- sw/device/silicon_creator/rom/keys/fake/spx/BUILD
- sw/device/silicon_creator/rom/keys/real/spx/BUILD
Introduce the following Bazel rules:
- `key_ecdsa`: Defines an ECDSA object that can be used for sign and verify operations.
- `key_sphincs_plus`: Defines a SPHINCS+ object that can be used for sign and verify operations.
This PR also introduces `key_sphincs_plus` targets for ROM SPX+ keys.
> [bazel] And KeyInfo provider and associated rules.

- python-requirements.in
- python-requirements.txt
Prior to this commit, the FuseSoC version downloaded when running
pip install -r python-requirements.txt
would identify itself as **version `0.4.dev0`** to Pip as well as in `fusesoc --version`.  This is problematic in at least two ways:
1. Because Pip gets told that it downloaded version 0.4, it can prefer to use a locally cached archive (and I've seen it doing that!) that is *really* version 0.4, causing the update to become a NOP even though the user thinks they just updated FuseSoC.
2. Users have no way of distinguishing between versions 0.4 and 0.5 from the command line, which makes debugging issues that got fixed in version 0.5 difficult.
To work around this problem, the PR lowRISC/fusesoc#6 changed `fallback_version`, from which our FuseSoC gets its version, to `0.5.dev0`, and this …
> [python] Fix FuseSoC version

- azure-pipelines.yml
- ci/scripts/run-fpga-tests.sh
- sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD
Those are the tests tagged with `fpga_cw310_rom_ext` which is a different environment from the sival ROM_EXT, and which is used to test the ROM_EXT implementation.
**NOTE:** I have chosen not to limit to `//sw/device/silicon_creator/rom_ext/e2e/...` because there is also a test in `//sw/device/tests/crypto/...`. This can be changed based on feedback.
> [ci] Add a job to run ROM_EXT tests

- hw/ip/usbdev/data/usbdev.hjson
- hw/ip/usbdev/doc/registers.md
- hw/ip/usbdev/rtl/usbdev_reg_pkg.sv
- hw/ip/usbdev/rtl/usbdev_reg_top.sv
Declaring the FIFOs as hwext when they are WO from a software perspective removes the unnecessary flip-flops (and a cycle delay in the provision in the buffer). 'avsetupbuffer' recently mimicked 'avoutbuffer' and thus this apparent oversight was duplicated.
Unless I've missed something this should not change any functionality, and current block level DV tests are unaffected.
> [usbev] Declare Av FIFOs as hwext

- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_av_buffer_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_enable_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_fifo_rst_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_nak_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_received_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_sent_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_random_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_packetiser.sv
- hw/ip/usbdev/dv/env/usbdev_pkt_manager.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
This PR addresses the following issues three separate issues in individual commits:
- IN side sequences were conflicting with the usb20_driver behavior by needlessly trying to clear interrupts whilst the drive is causing interrupts by performing a Bus Reset on the USB. This led to seed-dependent failures.
- Warnings in the vcs build log had become quite numerous; eliminate them to lessen the risk of losing warnings that indicate functional issues.
- Avoid the use of csr_update to write to the FIFOs because this can lead to the csr/uvm logic deciding that update is not required, and thus the write of a buffer number into the FIFO does not occur. When buffer number 0 is chosen this leads to test failures, but that is a perfectly valid buffer number and does/will get selected by …
> [dv,usbdev] Fixes for usbdev DV sequences

- util/topgen/lib.py
- util/topgen/templates/toplevel.sv.tpl
The previous code added a comma after a parameter unless this was the last parameter of the module and this was the last module in the list. This works fine unless the last module in the list doesn't happen to have any parameters.
In that situation, you got something like
...
parameter int unsigned RvCoreIbexDmExceptionAddr =
tl_main_pkg::ADDR_SPACE_RV_DM__MEM + dm::ExceptionAddress[31:0],
parameter bit RvCoreIbexPipeLine = 0,
// parameters for mbx0
// parameters for mbx1
// parameters for mbx2
) (
...
which is a syntax error (the parser sees something like "a, b, )").
Tweak the logic slightly so that we add a comma unless this is the last parameter in the module and this is the last module *with parameters* in the list
The diagnosis and main work was done by Robert Schilling. I just …
> [topgen] Avoid adding a comma after the last parameter in the list

- rules/opentitan/toolchain.bzl
- rules/otp.bzl
- sw/device/silicon_creator/rom/keys/fake/otp/BUILD
- sw/device/silicon_creator/rom/keys/real/otp/BUILD
- util/design/BUILD
- util/design/gen-otp-rot-auth-json.py
This commit adds support for generating the
`ROT_CREATOR_AUTH_CODESIGN_BLOCK_SHA2_256_HASH` digest at build time using a new Bazel `otp_json_rot_keys` rule.
Updated existing key partition definitions to adopt the new rule.
> [otp] Add support for generating the ROT keys digest.

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/doc/registers.md
- hw/ip/i2c/doc/theory_of_operation.md
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_fsm.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
By setting the bit CSR.TARGET_FIFO_CONFIG.TXRST_ON_COND, the block will then automatically reset the TXFIFO (using TXRST) if it observes a STOP/RSTART condition in Target-Mode.
From the commit message:
> This behaviour may be useful to software, as any remaining data in the TXFIFO
> after a Sr/P condition is probably no-longer applicable to the next transfer, so
> will likely have to be cleared out anyway. Keeping this behaviour as a toggle
> allows software to observe the fifo state before resetting it, which may be
> useful to understand how much of the previous transfer completed if that
> information is helpful or relevant.
Reset state is disabled.
Closes #17750
> [i2c,rtl] Add user toggle TXRST_ON_COND

- hw/ip/usbdev/data/usbdev.hjson
- hw/ip/usbdev/doc/registers.md
- hw/ip/usbdev/rtl/usb_fs_nb_in_pe.sv
- hw/ip/usbdev/rtl/usb_fs_nb_out_pe.sv
- hw/ip/usbdev/rtl/usb_fs_nb_pe.sv
- hw/ip/usbdev/rtl/usb_fs_rx.sv
- hw/ip/usbdev/rtl/usbdev.sv
- hw/ip/usbdev/rtl/usbdev_counter.sv
- hw/ip/usbdev/rtl/usbdev_reg_pkg.sv
- hw/ip/usbdev/rtl/usbdev_reg_top.sv
- hw/ip/usbdev/rtl/usbdev_usbif.sv
- hw/ip/usbdev/usbdev.core
Relating to PR #21950 if the ca. 288 flops of the original proposal causes area issues alongside all of the other changes, this PR offers a still more lightweight implementation using ca. 1/3 of those flip-flops at the expense of sacrificing separability.
- Counter widths are reduced to 8 bits as per suggestions in PR #21950; software shall be required to respond more promptly to extend the hardware counters if required.
- Events visible to usbdev hardware only are grouped into categories:
- OUT side events
- IN side events
- Reception error events
- Events within a given category may be enabled/disabled individually but only a second counter collects all enables events within that category.
Associated DV Draft PR #22039 not yet updated.
Resolves #22160.
> [usbdev] Lighter diagnostic and performance counters

- hw/ip/prim/rtl/prim_fifo_sync.sv
- hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
This will make it easier to reuse `prim_fifo_sync_cnt` to build other synchronous FIFO modules (e.g., one that doesn't use FFs as storage). The functionality of `prim_fifo_sync` is not changed by this PR. This PR also improves the documentation/comments around how FIFO pointers are calculated.
> [prim_fifo_sync] Move address and depth calculation to `prim_fifo_sync_cnt`

- hw/dv/sv/mem_bkdr_util/mem_bkdr_util__otp.sv
This bug was introduced when splitting the hw_cfg partition.
Fixes #22200
> [dv,mem_bkdr] Fix digest calculation for hw_cfg0

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_sleep_por_reset_vseq.sv
Increase the reset delay to avoid hang condition during reset waiting (in the closed-source).
> [dv, chip-test]: Extend sysrst reset delay

- hw/ip/uart/data/uart_testplan.hjson
This mirrors most of the other blocks in the design. One consequence is that the testpoint moves to V3, but we probably believe that's a better place for it to live anyway.
> [uart,dv] Import generic testplan for stress_all_with_reset

- hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
- Remove two `unsigned` casts that are no longer needed.
- Remove excessive empty lines before `endmodule`.
> [prim_fifo_sync_cnt] Minor code cleanup

- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/cryptotest.bzl
1. Add cryptotest macro to simplify `opentitan_test` configuration for test targtes.
2. Add `crypto_kat_test_suite` to aid in the setup of SiVal regression of crypto tests.
> [cryptotest] Add cryptotest Bazel macro and crypto kat test suite.

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/keymgr_testutils.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/aes_kwp_sideload_functest.c
- sw/device/tests/crypto/aes_sideload_functest.c
- sw/device/tests/crypto/ecdh_p256_sideload_functest.c
- sw/device/tests/crypto/ecdsa_p256_sideload_functest.c
- sw/device/tests/sival/BUILD
1. Introduce changes to `keymgr_testutils` to support silicon targets.
2. Update cryptolib side load tests to support SiVal targets.
3. Update cryptolib tests to support silicon targets.
4. Integrate cryptolib test suite into the SiVal regression target.
- https://github.com/lowRISC/opentitan/issues/19984
- https://github.com/lowRISC/opentitan/issues/21502
- https://github.com/lowRISC/opentitan/issues/19981
- https://github.com/lowRISC/opentitan/issues/21503
> [sival] Adds keymgr side load  tests based on cryptolib test cases.

- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
Updates the test plan with the following targets:
1. chip_sw_hmac_sha2_stress: //sw/device/tests/crypto/cryptotest:hash_kat https://github.com/lowRISC/opentitan/issues/21464
2. chip_sw_hmac_stress: //sw/device/tests/crypto/cryptotest:hmac_kat https://github.com/lowRISC/opentitan/issues/21464
> [sival] Update hmac sival test targets.

- sw/device/lib/crypto/impl/ecc/ecdh_p256.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p256.c
- sw/otbn/crypto/p256_ecdh.s
- sw/otbn/crypto/p256_ecdsa.s
- sw/otbn/crypto/p256_isoncurve.s
- sw/otbn/crypto/p256_verify.s
- sw/otbn/crypto/p384_verify.s
- sw/otbn/crypto/tests/BUILD
- sw/otbn/crypto/tests/p256_ecdsa_verify_test.exp
- sw/otbn/crypto/tests/p256_ecdsa_verify_test.s
Manual backport of #21115 and #21752 to `earlgrey_es_sival`.
> [crypto/sival] Backport P-256 bug fixes to sival branch

- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
Adds cryptotest targets to KMAC stress chip test points.
* https://github.com/lowRISC/opentitan/issues/21406
* https://github.com/lowRISC/opentitan/issues/21407
* https://github.com/lowRISC/opentitan/issues/21408
* https://github.com/lowRISC/opentitan/issues/21409
> [siva] Add cryptotest targets to chip_kmac_testplan.

- hw/ip/i2c/rtl/i2c_fifos.sv
This is needed to match the SRAM macro.  The minimum depth needed by the RTL is 460 entries (which gets checked by assertions).
This resolves #22234.
CC @meisnere @OTshimeon
> [i2c/rtl] Change depth of RAM for FIFOs to 464 entries

- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/chip/boot_svc.rs
- sw/host/opentitanlib/src/chip/helper.rs
- sw/host/opentitanlib/src/crypto/ecdsa.rs
- sw/host/opentitanlib/src/crypto/mod.rs
- sw/host/opentitanlib/src/crypto/rsa.rs
- sw/host/opentitanlib/src/crypto/spx.rs
- sw/host/opentitanlib/src/util/mod.rs
- sw/host/opentitanlib/src/util/serde.rs
- sw/host/opentitantool/src/command/ecdsa.rs
1. Add a `Raw` struct type for each of the key types that is both serde serializable and convertible to/from binary form.
2. Add `TryFrom` conversions between the native key types and the `Raw` structs.
3. Implement `FromStr` conversions that load the Raw key material from a file.
4. Add a serde helper to allow serde deserialization to use the `FromStr` trait to initialize structs based either on their `FromStr` conversion or a json key-value map.
> [opentitanlib] ECDSA/RSA/SPX raw key helper functions

- sw/device/lib/runtime/print.c
- sw/device/lib/runtime/print.h
- sw/device/silicon_creator/lib/dbg_print.c
- sw/device/silicon_creator/lib/dbg_print.h
- sw/device/silicon_creator/rom_ext/rescue.c
Change the non-standard `%C` specifier to print an uint32_t in "FourCC" style (4 ASCII chars encoded into a uint32_t in little endian order).
Many rescue, boot_svc and ownership identifier words are 32-bit integer constants that are ASCII identifiers.  Adding this specifier makes printing these values much easier.
> [silicon_creator] Improve `dbg_printf`

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/keymgr_testutils.h
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/aes_kwp_sideload_functest.c
- sw/device/tests/crypto/aes_sideload_functest.c
- sw/device/tests/crypto/ecdh_p256_sideload_functest.c
- sw/device/tests/crypto/ecdsa_p256_sideload_functest.c
- sw/device/tests/sival/BUILD
Manual cherry-pick of https://github.com/lowRISC/opentitan/pull/22215
- https://github.com/lowRISC/opentitan/issues/19984
- https://github.com/lowRISC/opentitan/issues/21502
- https://github.com/lowRISC/opentitan/issues/19981
- https://github.com/lowRISC/opentitan/issues/21503
> [cherrypick] Adds keymgr side load tests based on cryptolib test cases.

- util/reggen/ip_block.py
Four HW IP modules have been created on the `integrated_dev` branch, which hasn't been reconverged with `master` yet.  This commit reserves their Comportable IP IDs on `master` to ensure we don't accidentially assign their ID to another new IP, which would make reconvergence more difficult.
> [reggen] Reserve CIP IDs for Integrated IPs

- hw/top_earlgrey/dv/chip_rom_tests.hjson
The ROM E2E self hash test was disabled on FPGA in #17177. The test should also have been disabled in DV. #19199 tracks reenabling the test when the ROM is released for the Earlgrey PROD backend integration.
> [rom_e2e,dv] disable ROM self hash test in DV

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/usbdev_env_cov.sv
This is a pretty mechanical change: it is basically copying the list of covergroups from usbdev_env_cov.sv into usbdev_testplan.hjson. I've taken the long comment above each covergroup and turned it into the description of the covergroup in the testplan.
The only nontrivial change is to a covergroup name (pid_type_end_cg), which had a stray "f".
@alees24: Would you mind glancing over this? I *think* it should be equivalent to the text you wrote, but want to make sure I'm not mangling anything.
Closes #22194.
> [usbdev,dv] Move covergroup descriptions to testplan

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
Increase the wait cycles before reading LC via JTAG to avoid failures in the closed-source.
> [dv, chip, env]: Extend the waiting time before reading LC via JTAG

- sw/device/tests/i2c_target_test.c
- sw/device/tests/spi_passthru_test.c
- sw/host/opentitanlib/src/test_utils/i2c_target.rs
- sw/host/opentitanlib/src/test_utils/spi_passthru.rs
- sw/host/tests/chip/i2c_target/src/main.rs
Since #22101 merged, the `spi_passthru_test` was broken due to ujson CRC's missing between Host-->Device communication. This fixes said test by adding the CRC checks.
> [test,ci] fix broken `spi_passthru_test` in CI by adding UJSON CRC checks

- hw/ip/uart/dv/env/seq_lib/uart_base_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_intr_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_loopback_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_rx_oversample_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_stress_all_vseq.sv
- hw/ip/uart/dv/env/seq_lib/uart_tx_rx_vseq.sv
Get the `uart_stress_all_with_rand_reset` test pass-rate higher by breaking out of sequence loops and increasing polling delays when we want to reset (as indicated by `cfg.stop_transaction_generators()`).
The key to getting the pass rate higher is to avoid the case where `wait_to_issue_reset()` times-out before it sees a large enough gap (defined by `CyclesWithNoAccessesThreshold`) between register accesses. The primary approach to achieving this idleness is to stop the test sequences early by breaking out of loops when they can do so cleanly. The secondary approach taken here is to increase register polling delays, which covers the cases where the test sequence would not reach a clean break point before the reset timeout. Low uart baud rates and sequences with long transactions make this …
> [dv,uart] Aid `uart_stress_all_with_rand_reset`

- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_av_buffer_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_enable_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_received_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_random_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_env_pkg.sv
- hw/ip/usbdev/dv/env/usbdev_packetiser.sv
This PR simplifies the current DV code for the USB device by making the following changes:
- Isolates the vseq code from the internal changes that the usb20_driver makes to sequence items before they are driven onto the USB.
- Removes the unnecessary nibble swapping of the Packet IDentifier values at source and destination, allowing the 'pid_type_e' enumeration to employ the same numerical values as in the USB 2.0 protocol specification.
- Modifies the vseqs to check the received packet buffer contents against the original (randomized) data directly, rather than having to recover the original data after the act of sending it.
> [dv,usbdev] DV simplifications

- .github/workflows/pr_change_check.yml
- .github/workflows/pr_lint_review.yml
Very minor PR which updates the deprecated `actions/checkout@v3` to `@v4` in preparation for Node 16 being removed from the runners.
It also fixes the verible lint action version to v2 as opposed to `main` for some stability.
> [ci] Update GitHub actions

- hw/ip/usbdev/data/usbdev_testplan.hjson
Incorporates the sequence name into the test plan to ensure its inclusion in future regression testing.
> [usbdev,dv] include sequence name in testplan

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_buffer_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/env/usbdev_env_pkg.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR adds a DV test sequence for exercising the packet buffer memory:
- Randomized IN and OUT transactions of random length/content, to randomized buffers and randomized endpoints.
- CSR-side randomized packet buffer reads/writes, ensuring no collision with USB-side access.
- Checking of all data transfers, in both directions and on both CSR and USB sides.
- Aim to induce access collisions (same cycle, don't need to worry about same address); CSR side should be stalled because the packet buffer is implemented using a Single Port RAM now.
- CSR-side access to the packet buffer memory only worked if the scoreboard/UVM was capable of predicting the memory contents; this is not the case when the DUT hardware may write to the packet buffer memory at any moment.
- usbdev_scoreboard is …
> [dv,usbdev] DV sequence for packet buffer memory

- hw/ip/i2c/dv/env/seq_lib/i2c_host_perf_vseq.sv
This is no longer necessary now that #21813 has been merged. However, due to the 'PERFTHRESHOLD = 0.80' fudge-factor in comparing the exp/obs SCL period in this vseq, the check still passed.
This perf check should be made more stringent in the future.
> [i2c,dv] Remove +3 correction for coerced period in host_perf_vseq

- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
Using the tasks now available in the base vseq, present random buffer data for IN packet collection.
Choose different endpoints at each stage of the sequence. Randomize the length of the OUT packet.
Tidy up and clarify the construction of setup packets and the inter-packet delays.
> [dv,usbdev] Smoke test improvements

- hw/ip/usbdev/data/usbdev_testplan.hjson
Drop a few unnecessary tests such as those which relate to Control Transfers above the level of packet transactions.
Clear up the descriptions in a number of tests and clarify the required behavior in some other tests.
Modifications for the altered RTL in places, particularly the separation of the single 'Available Buffer FIFO' into two separate buffer FIFOs for SETUP and OUT packets.
> [dv,usbdev] Test plan refinements

- hw/ip/usbdev/rtl/usb_fs_nb_pe.sv
- hw/ip/usbdev/rtl/usb_fs_rx.sv
- hw/ip/usbdev/rtl/usbdev.sv
- hw/ip/usbdev/rtl/usbdev_linkstate.sv
- hw/ip/usbdev/rtl/usbdev_usbif.sv
This PR proposes two alterations to the receiver side logic of the USB device:
1. As per the assertion in section `8.4.5 Handshake Packets` of the protocol specification, handshake packets that contain additional bits between the valid PID and the EOP shall cause the handshake packet to be ignored. Local modifications to the USBDPI model have demonstrated that an arbitrary number of bits may be introduced between the handshake PID and the EOP, and the handshake will still be accepted at present. Indeed the DPI model is erroneously doing this in a couple of places where it transmits 'USB_PID_ACK' as a complete token packet.
2. As per section `8.7.1 Packet Error Categories` a SOF packet that has a valid PID shall not be ignored completely; instead the presence of a CRC5 error and/or bit …
> [usbdev] Packet receiver refinements

- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/dice.h
- sw/device/silicon_creator/lib/drivers/keymgr.c
- sw/device/silicon_creator/lib/drivers/keymgr.h
- sw/device/silicon_creator/lib/drivers/keymgr_unittest.cc
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
This refactors the keymgr configuration and cranking in the DICE lib / FT person binary to decouple keymgr state operations from attestation key and cert generation. This is preparation for enabling #21583.
> [dice,manuf] refactor keymgr config and cranking in DICE lib

- hw/dv/sv/i2c_agent/i2c_agent.core
- hw/dv/sv/i2c_agent/i2c_agent_pkg.sv
- hw/dv/sv/i2c_agent/i2c_driver.sv
- hw/dv/sv/i2c_agent/i2c_if.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_seq_list.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_target_may_nack_seq.sv
- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/doc/registers.md
- hw/ip/i2c/doc/theory_of_operation.md
- hw/ip/i2c/dv/env/i2c_env.core
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_may_nack_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_fsm.sv
- hw/ip/i2c/rtl/i2c_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
If the I2C bus NAKs any of our transfers when operating as a Controller-Transmitter in Byte-Formatted Programming Mode, the current behaviour is to proceed to the next FDATA entry as normal, disregarding the NAK entirely. The only side-effect of this event is the block raising the 'nak' interrupt (though this can be suppressed by the use of NAKOK in the FDATA entry).
This PR changes the behaviour so the Controller-FSM halts upon generation of the 'nak' interrupt, and proceeds once the interrupt has been acknowledged using the standard 'Event-Type' interrupt acknowledgement (W1C to INTR_STATE).
The next item in the FMTFIFO is not popped until this acknowledgement is received.
If the NAKOK bit is set for a particular Format Indicator and the bus NAKs our byte, the 'nak' interrupt is not …
> [i2c,rtl] Halt controller FSM when unexp. NAK is seen

- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
This PR has two commits: the first is #22292 (which should be merged first); the second builds on this. The commit message for the second commit continues with:
```
This also gives some longer comments explaining the data
formatting (because I found it hard to remember!)
```
> [usbdev,dv] Rename set_payload to something more specific

- hw/dv/sv/spi_agent/spi_agent_cfg.sv
- hw/dv/sv/spi_agent/spi_host_driver.sv
- hw/dv/sv/spi_agent/spi_item.sv
- hw/dv/sv/spi_agent/spi_monitor.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_intercept_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/env/spi_device_env.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
TB has been updated to check for flash_status bits correctness.
SPI-monitor now triggers SV events on each byte sampled on the SPI bus as well as when the CSB is deasserted.
The intercept VSEQ has been updated so reads/writes to flash_status won't occur just sequentially before/after a SPI-txn but also concurrently, as well as sending two flash_status writes in a row (less likely) where the first  writes the upper bits of the flash_status register, and the second would clear the busy/wel bits.
The Scoreboard has been updated to be in sync with the latest  flash_status behaviour changes in the RTL:
- SPI reads to FLASH_STATUS (READ_STATUS#1/2/3 commands ) no longer wrap around the register if the CSB was left "active" after the first byte is returned to the host by the RTL
- Writes to …
> Flash status synchronisation tb fix

- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/data/hmac_testplan.hjson
- hw/ip/hmac/doc/registers.md
- hw/ip/hmac/lint/hmac.vlt
- hw/ip/hmac/rtl/hmac.sv
- hw/ip/hmac/rtl/hmac_core.sv
- hw/ip/prim/rtl/prim_sha2.sv
- hw/ip/prim/rtl/prim_sha2_32.sv
This PR fixes existing coding style issues in the HMAC RTL from earlier to bring it closer to the current coding style guide. It also adds minor styling fixes for the issues raised in the reviews for the wider digest PR https://github.com/lowRISC/opentitan/pull/21604, and fixes the I/O port suffixes in `hmac_core.sv` per the coding style per this issue https://github.com/lowRISC/opentitan/issues/21666.  Once the RTL is finalized and coverage is improved via the extended testplan for the new features, we will need to run the UNR analysis anyway again, and the UNR exclusions list will thus be updated with the changed I/O port names.
> [hmac] Coding style and minor fixes

- hw/ip/spi_host/data/spi_host_testplan.hjson
- Add new testpoint to verify fifo status signals
- This can confirm that #21325 is working as expected.
- Cleanup redundant cp
The other changes for D2(S) were bugfixes or changes that don't require testplan updates.
Closes #22136
Goes towards #21010
> [spi_host,dv] Update testplan based on D2(S) changes

- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env_cov.sv
This includes requirements for test coverage and functional coverage
- Rename old 'perf' testpoints to 'maxperf', to make way for a new point 'host_mode_config_perf' which checks performance matches whatever perf is configured.
- Addition of V2 test descriptions, currently unmapped
Closes #22168 
Goes towards #21006
> [i2c,dv] Update testplan for new features introduced for D2(S)

- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/data/hmac_testplan.hjson
This PR adds testplan items for the recently added features and refers the corresponding tracking issues, then signs HMAC off at D2S and V1, based on the analysis in #20996 and #21031, respectively.
Closes #20996 (D2S signoff issue) and closes #21031 (V1 signoff issue).
> [hmac] Add testplan items for recently added features and sign off at D2S and V1

- hw/dv/sv/mem_bkdr_util/mem_bkdr_util__sram.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_common_vseq.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_mem_bkdr_scb.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv
- sw/device/tests/sim_dv/sram_ctrl_scrambled_access_test.c
Pass the number of bits selecting a tile to various sram backdoor functions. This was incompletely done in the past, which had no impact in the open-source ram configuration since it has a single tile, but causes failures in configurations with multiple tiles.
> [dv,mem_bkdr] Fix handling of multiple tiles in sram

- sw/host/hsmtool/BUILD
- sw/host/opentitanlib/BUILD
- sw/host/opentitantool/BUILD
- third_party/rust/repos.bzl
- v0.0.10 fixed a bug in deserializing enums.
- v0.0.11 re-organizes the serde-annotate project workspace.  The dependency label changes reflect the new structure.
> [rust] Upgrade to serde-annotate v0.0.11

- sw/host/opentitanlib/src/lib.rs
- third_party/rust/deps.bzl
- third_party/tock/repos.bzl
This updates Tock to https://github.com/tock/tock/pull/3748, which updates Tock's Rust toolchain to `2024-01-01`.
> [tock] Update Tock and the nightly Rust toolchain.

- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/crypto/ecdsa.rs
- sw/host/opentitanlib/src/crypto/mod.rs
- sw/host/opentitanlib/src/crypto/rsa.rs
- sw/host/opentitanlib/src/crypto/spx.rs
- sw/host/opentitanlib/src/util/mod.rs
- sw/host/opentitanlib/src/util/serde.rs
- sw/host/opentitantool/src/command/ecdsa.rs
1. Add a `Raw` struct type for each of the key types that is both serde serializable and convertible to/from binary form.
2. Add `TryFrom` conversions between the native key types and the `Raw` structs.
3. Implement `FromStr` conversions that load the Raw key material from a file.
4. Add a serde helper to allow serde deserialization to use the `FromStr` trait to initialize structs based either on their `FromStr` conversion or a json key-value map.
(cherry picked from commit 96f12253f261048c2ce426c35164324caeefac03)
> Cherrypick to master: [opentitanlib] ECDSA/RSA/SPX raw key helper functions

- rules/certificates.bzl
- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
This adds two functions to configure the certificate flash info pages in the silicon_creator (ROM_EXT and personalization) code for full access, and to restrict access to read only upon anding over execution from the ROM_EXT to the owner boot stage. This will enable sharing the flash info page configuration code between the ROM_EXT and personalization code.
> [silicon_creator] add function to config cert flash info pages

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/dice.c
- sw/device/silicon_creator/lib/dice.h
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
Previously, in the `dice` lib, attestation keys and certificates were generated in the same function. This separates key gen into a separate function to enable skipping certificate generation if up-to-date certificates have already been generated, which is a ROM_EXT integration requirement.
Additionally, this optimizes the little to big endian byte order conversions for public keys and signatures by performing the swaps in place, saving on space required for the DICE lib.
> [dice,manuf] decouple dice key and cert generation

- sw/device/tests/pmod/BUILD
Test is currently broken
Re-enablement tracked in https://github.com/lowRISC/opentitan/issues/22347
> [bazel,ci] Temporarily disable i2c_host_eeprom_test in CI

- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_av_buffer_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_nak_trans_vseq.sv
This PR addresses a couple of reliability issues with the current usbdev DV sequences:
- The usb20_monitor suffers the same sampling/aliasing issues as the usb20_driver code when attempting to receive and decode packets on a 12MHz clock, with no ability to adjust the phase of the clock. As an interim workaround this adjusts the sampling to use the positive- or negative-edge of the clock, but a cleaner and more general solution should be implemented at some point to permit testing of frequency- and phase-differences between host and device.
- The unnecessary startup code in the usbdev_nak_trans_vseq and usbdev_av_buffer_vseq conflicted with the current Bus Reset behavior of the usb20_driver, particularly the interrupt clearing because bus resets set interrupt state bits.
> [dv,usbdev] Reliability fixes

- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/doc/checklist.md
For the production tapeout, a couple of API breaking changes are soon being merged which requires a major version bump. Indepentenly, some area optimization changes for M2 negatively impacted the code coverage: branch and expression coverage are now below the 90% bar. Meaning, we should revert the verification stage to V1.
Getting the coverage metrics back up again is tracked in lowRISC/OpenTitan#22354.
> [csrng] Increase version number, revert verification stage to V1

- hw/ip/edn/data/edn.hjson
- hw/ip/edn/doc/checklist.md
Since ES tapeout, a couple of API breaking changes had to be implemented. The DV side was mostly updated in sync but there are two reasons why we cannot meet V2S currently:
- The edn_disable_auto_req_mode test has a pass rate below 90%. See lowRISC/OpenTitan#20818.
- The FSM coverage dropped to around 82%. See lowRISC/OpenTitan#22352.
> [edn] Increase version number, revert verification stage to V1

- sw/device/sca/aes_serial.c
- sw/device/sca/kmac_serial.c
- sw/device/sca/lib/sca.c
- sw/device/sca/lib/sca.h
- sw/device/sca/otbn_vertical/ecc256_keygen_serial.c
- sw/device/sca/otbn_vertical/ecc256_modinv_serial.c
- sw/device/sca/sha3_serial.c
- sw/device/tests/crypto/cryptotest/firmware/aes_sca.c
- sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
- sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
- sw/device/tests/crypto/cryptotest/json/aes_sca_commands.h
This PR manually cherry-picks "Add support for AES SCA measurements on chip" lowRISC/opentitan#21741 from earlgrey_es_sival to master  as the automatic cherry-pick failed due to a merge conflict.
> [pentest] Cherry-pick Add support for AES SCA measurements on chip

- hw/ip/aon_timer/data/aon_timer.hjson
aon_timer only has the standardized `BUS.INTEGRITY` security countermeasure, and it had been signed off at D2S before the bump to version 2.0.0.  Since aon_timer is not a security-focused block and we have not changed its security design since the previous version, we can directly sign it off at D2S again.  See #20995 for the D2 signoff analysis and PR #21908 for the version change, where going to D2S directly has been suggested post merge.
> [aon_timer] Sign off at D2S

- sw/host/hsmtool/BUILD
- sw/host/opentitanlib/BUILD
- sw/host/opentitantool/BUILD
- third_party/rust/repos.bzl
- v0.0.10 fixed a bug in deserializing enums.
- v0.0.11 re-organizes the serde-annotate project workspace.  The dependency label changes reflect the new structure.
(cherry picked from commit 383a9198febad71e8bf5f3814f3ad3ea91002e8f)
> Cherrypick to master: [rust] Upgrade to serde-annotate v0.0.11

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/dice.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
We only want to save the current stage's attestation private key to OTBN DMEM _after_ we have used the previous stage's private key to endorse our current stage's certificate. This was a slight refactoring error in #22303, since previously, we were always overwriting the prior stage's private key in OTBN DMEM before using it.
> [dice] move keysave out of keygen function

- hw/ip/usbdev/data/usbdev_testplan.hjson
This PR incorporates changes to the description of the usbdev stall_trans sequence to drop the generic nature of testpoint.
> [usbdev] Rewrite usbdev stall trans seq description

- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This caused breakage with some of our CI metrics gathering scripts, as by convention all tests start with the blockname.
This shouldn't be an issue, but it turns out there is strange underlying dvsim behaviour where if a testpoint contains no tests, it creates a 'dummy' test output with 0 total runs, but with the same name as the testpoint.
This dummy name clashes the name of the unmapped test in this case.
> [usbdev] Fixup test name with 'usbdev_' prefix

- hw/dv/dpi/usbdpi/usbdpi.c
- hw/dv/sv/usb20_agent/usb20_block_if.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_common_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_dpi_config_host_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/env/usbdev_packetiser.sv
- hw/ip/usbdev/dv/tb/tb.sv
- hw/ip/usbdev/dv/usbdev_sim.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This draft PR integrates the usbdpi model into block level testing for USBDEV with the following aims/advantages:
- usb20_agent may be disconnected and/or deactivated to prevent interference with CSR test, for example.
- Increase coverage within block level DV testing.
- The usbdpi connection is through a tri-stated, bidirectional signaling interface that models the two-wire physical USB with appropriate pull ups, pull downs and active drivers.
- The block level usb20_driver module may at some point drive transactions through all PHY types since it has direct connections to all USBDEV ports.
- usbdpi model is already capable of generating error conditions and invalid traffic.
- Increased opportunity for randomization within usbdpi cf chip-level simulation, because it is obviously much …
> [dv,usbdev] Integration of usbdpi into block level DV environment.

- util/dvsim/Modes.py
- util/dvsim/OneShotCfg.py
- util/dvsim/SimCfg.py
I spent some time looking carefully at this code back in December and it's much more complicated than we need it to be. The commits in this PR are simplifications. There are some other tidy-ups that they enable, but the PR was turning into a bit of a mammoth and I thought this was a sensible place to start!
Most of the commits here are generic tidyups. The only significant change is probably in the code that cleans up how we print `Modes` objects (see the "Strengthen typing ..." commit). This removes use of some generic "object to string" code which the following commit can delete.
> [dvsim] General clean-up in modes.py

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/extclk_sca_fi.c
- sw/device/tests/crypto/cryptotest/firmware/extclk_sca_fi.h
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/extclk_sca_fi_commands.c
- sw/device/tests/crypto/cryptotest/json/extclk_sca_fi_commands.h
This commit adds uJSON command handlers allowing to configure the external clock for the penetration testing.
> [pentest] Configure extclk

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_stall_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR includes the usbdev stall_tran_vseqs sequence, designed to validate the stall functionality of usbdev. Upon setting the out_stall bit for a OUT transaction, the DUT is expected to respond with PidTypeStall.
This builds on #22308. Merge that first, which should just leave the final commit from this PR.
> [usbdev,dv] usbdev stall_trans seq

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/BUILD
- sw/host/cryptotest/testvectors/data/schemas/ed25519_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/wycheproof_ed25519_parser.py
This PR adds a python parser for the [ed25519 wycheproof test vectors](https://github.com/google/wycheproof/blob/master/testvectors_v1/ed25519_test.json).
Unlike [the analogous script](https://github.com/lowRISC/opentitan/pull/20793) for ECDSA, this script does not require any deconstructing of ASN.1 DER sequences, because the ed25519 vectors provide the key in a raw format, and cryptolib accepts ed25519 public keys and signatures in raw binary format, as opposed to an (x, y) curve point. The actual decoding of the point is done internally by cryptolib using the OTBN (see https://github.com/lowRISC/opentitan/pull/14218).
The cryptolib implementation of Ed25519 is currently a TODO, so a test harness using these vectors is currently TBD.
> [cryptotest] ed25519 wycheproof test vector parser

- sw/host/cryptotest/testvectors/parsers/wycheproof_ed25519_parser.py
Fixes the license header in Ed25519 test vector parser to comply with the changes to `//quality:license_check` in #20823.
> [cryptotest] Fix license header in wycheproof ed25519 test vector parser

- sw/host/ot_certs/BUILD
- sw/host/ot_certs/src/asn1/codegen.rs
- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/codegen.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/src/x509.rs
Non-ordered data structures were being iterated over to produce device code that would generate OT attestation certificates. This caused builds on different machines (and on the same machine) of the same code to be different. This switches the non-deterministic data structures for a deterministic equivalent.
> [certs] make OT cert builds deterministic

- doc/getting_started/build_sw.md
- doc/getting_started/setup_fpga.md
- rules/opentitan/defs.bzl
By default, `EARLGREY_TEST_ENVS` used to run tests on both test ROM and regular ROM. This results in a lot of duplicated runs on CI. This commit removes the test ROM from the defaults list, leaving only ROM. If a test has explicitly overridden this default value (and e.g. specified it only runs on test ROM), then it will be unaffected by this change.
The second commit updates documentation: since `uart_smoketest` and other targets no longer include the
`test_rom` environment, it updates the Bazel commands in the documentation to use the ROM targets instead. It also updates a few references to `_rom` targets (which no longer exist afaict, having been replaced by `_rom_with_fake_keys` targets) and clarifies that not all tests will support both test ROM and ROM.
If this works like we hope, …
> [bazel] Change default environments for test targets.

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.c
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.h
- sw/device/tests/crypto/cryptotest/firmware/otbn_fi.c
- sw/device/tests/crypto/cryptotest/firmware/otbn_fi.h
- sw/device/tests/crypto/cryptotest/firmware/sca_lib.c
- sw/device/tests/crypto/cryptotest/firmware/sca_lib.h
- sw/device/tests/crypto/cryptotest/json/ibex_fi_commands.h
- sw/device/tests/crypto/cryptotest/json/otbn_fi_commands.h
This commit configures the alert handler to raise an interrupt that is handled by a custom ISR. This ISR registers the alert and write it back to the ot-sca host for further diagnosis.
The host code is located in https://github.com/lowRISC/ot-sca/pull/339
> [pentest] Configure alert handler for FI

- hw/ip/prim/rtl/prim_packer_fifo.sv
- hw/ip/tlul/rtl/tlul_err.sv
This avoids a warning from Jasper (and, I suspect, some lint tools). The problem is that "1" is a 32-bit value, so "1 << xyz" is also a 32-bit value and the tool warns when we try to put it in something with fewer bits bits.
Explicitly making a "one" that's the right width seems to avoid the warnings and is obviously equivalent.
> [prim,tlul,rtl] Explicitly cast a "1" to specific number of bits

- hw/ip/usbdev/doc/checklist.md
This follows several(!) V1 review meetings. The last was on March 28,
2024. The changes are as follows:
DV_DOC_DRAFT_COMPLETED:
The draft document is now in place. There's some more work to do in order to finish a DV document, but there's a solid draft.
TESTPLAN_COMPLETED:
There is a complete testplan in place, which has been reviewed and signed off.
TB_GEN_AUTOMATED:
We don't have TB generation for usbdev (past the usual automated CSR tests).
SIM_SMOKE_TEST_PASSING:
The smoke test passes with all seeds in nightly tests.
SIM_CSR_MEM_TEST_SUITE_PASSING:
Most CSR tests pass with all seeds in nightly tests. The usbdev_csr_bit_bash test is an exception, but still has a 40% pass rate.
FPV_MAIN_ASSERTIONS_PROVEN:
This block does not have FPV testing.
SIM_ALT_TOOL_SETUP:
Tested with both VCS and …
> [usbdev] Mark V1 items done in checklist.md

- hw/ip/kmac/rtl/keccak_2share.sv
These parameters were added in 233ea81e5a9 and were supposed to be a lint fix themselves. JasperGold complains about defining a "parameter" when there is also a formal parameter declaration list and points out that it will be magically turned into a localparam.
Do the transformation manually and silence the warning.
> [kmac] Fix silly lint warning in keccak_2share.sv

- ci/scripts/run-fpga-tests.sh
This PR prints the SAM3X firmware version before running FPGA tests. This is useful even for hyperdebug tests as we still program the bitstream etc through the SAM3X.
> [ci] Print SAM3X firmware version for FPGA jobs

- hw/ip/otbn/data/otbn.hjson
This will represent the version of OTBN going into PROD. We've just had a V1 review meeting (which was, honestly, a bit of a formality), but we think there will be some proper work to do before we can claim to be back at the V2 stage.
> [otbn,dv] Drop verification stage to V1

- util/reggen/fpv_csr.sv.tpl
These were found by looking at Verisium warnings that come out of running a Jasper proof. The proof still fails with the same percentages, but these changes silence some warnings and (I think) fix some genuine bugs.
> [reggen,fpv] Fix up some bugs in indices in reggen's FPV code

- hw/ip/prim/rtl/prim_assert_standard_macros.svh
Jasper just emits a warning if it sees a final block (and ignores the contents). Don't emit the final block if we're targeting Jasper, which avoids the warning.
> [prim,dv] Tweak ASSERT_FINAL to be a no-op if FPV enabled

- util/reggen/fpv_csr.sv.tpl
The previous change was mostly right, except for an off-by-one which didn't get triggered with the HRO register count I was testing with. If num_hro_regs = N, they will have indices 0, 1, ..., N-1. Then we'll throw in an extra index for non-HRO registers, with value N.
To represent an arbitrary one of these indices, we need $clog2(N) bits. My code was wrong and used $clog2(N+1) (because there are N+1 entries in the array).
It turns out that I was testing with a value of N where those two calculations give the same result. But it doesn't work with N=3 (the situation I have now).
Note in the PR: The previous (wrong) code was in PR #22408
> [reggen,fpv] Fix array sizes in fpv_csr.sv.tpl... again!

- sw/otbn/crypto/p256_verify.s
Fixes the failing wycheproof ECDSA tests in #22322.
When computing the recovered x coordinate, we get a value that's reduced modulo p (the coordinate field modulus) and we then need to reduce this value modulo n (the curve order). This operation is almost always a no-op, since p and n are very close together; there's roughly a 2^-130 probability of hitting this range by chance. However, the code implementing the reduction was *always* a no-op. Essentially, by using `bn.subm` instead of `bn.addm` here, the code was conditionally *adding* the modulus n if `w19 - 0` underflowed, which it never would. Instead, we need `bn.addm`, which will conditionally *subtract* the modulus n if `w19 + 0` is greater than n.
> [crypto] Fix a bug in ECDSA-P256.

- azure-pipelines.yml
- hw/top_earlgrey/BUILD
- rules/opentitan/defs.bzl
- sw/device/tests/BUILD
- sw/host/opentitanlib/src/app/config/hyperdebug_cw340.json
This PR adds `cw340_test_rom` and `cw340_rom_with_fake_keys` execution environments. The `cw340_rom_with_fake_keys` one is tested through `uart_smoketest` in CI. They're both using the `hyper340` transport.
Unlike the CW310, CW340 boards can only be in either the HyperDebug or SAM3X configurations at any given time.
Our CI currently only has a board in the HyperDebug configuration. Adding exec_envs for the SAM3X configuration would be simple enough but would not get tested in CI.
> [bazel] Add some cw340 exec_envs

- hw/ip/usbdev/dv/env/seq_lib/usbdev_dpi_config_host_vseq.sv
Open PR overlapped the update to the copyright header.
> [dv,usbdev] Copyright message update

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aon_timer_testplan.hjson
- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_csrng_testplan.hjson
- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otbn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
- sw/device/tests/BUILD
This PR adds bazel targets to the testplans which are already running on the nightlies but not linked.
> Sival update testplans

- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv
I don't think the types in this constraint made sense (and VCS warns when asked to compile it). Change to types that actually match.
> [lc_ctrl,dv] Fix constraint in lc_ctrl_errors_vseq

- hw/ip/usbdev/rtl/usb_fs_nb_in_pe.sv
Time out in the event of a missing handshake response from the host was tardy. Must time out after 16-18 bit intervals (7.1.19.1) and the calculation anticipated a longer delay in the receipt of 'rx_pkt_start_i' signaling.
This PR reduces the time out to 17 bit intervals plus the 1.5 bit intervals for the SOP be seen within the IN packet engine.
Fixes #22437, from observations in simulation.
> [usbdev] Reduce timeout interval

- sw/device/tests/BUILD
This PR fixes a merge skew caused by the renaming of `new_cw310_params` to `cw310_params`.
Relevant PRs: #21845 #22078
> [sw] Fix params for parity test

- hw/dv/sv/usb20_agent/usb20_agent.core
- hw/dv/sv/usb20_agent/usb20_agent.sv
- hw/dv/sv/usb20_agent/usb20_agent_cfg.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_dpi_config_host_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/env/usbdev_env.sv
- hw/ip/usbdev/dv/env/usbdev_env_cfg.sv
- hw/ip/usbdev/dv/tb/tb.sv
Before this change, usb20_if.sv appeared in two cores: usb20_usbdpi and usb20_agent. This causes silly warnings from EDA tools like VCS which point out that we have a spare copy of the file.
Avoid the duplication and leave a comment that explains what's going on.
> [usbdev,dv] Avoid duplicate file when building usbdev tests

- hw/ip/usbdev/dv/env/seq_lib/usbdev_dpi_config_host_vseq.sv
Technically, the code that was there before isn't valid SystemVerilog (because you're not allowed to put an "import" line into the top-level of a class).
We only actually need to do this import in the configuration_wait task. Make the code conformant to the spec.
> [usbdev,dv] Move package import into task

- hw/ip/i2c/dv/env/seq_lib/i2c_glitch_vseq.sv
- hw/ip/i2c/dv/tb/tb.sv
- hw/ip/i2c/i2c.core
- hw/ip/i2c/rtl/i2c_controller_fsm.sv
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_target_fsm.sv
Split the target and controller FSMs both to simplify the code for better maintainability / readability and to lay the groundwork for multi-controller support. Note that there will likely be some increase in area for duplicated structures here, but it turns out that much of the state was already independent.
Also fix a bug where the controller-mode stretch counter would continue counting cycles even when the target had already released SCL.
> [i2c] Split the target and controller FSMs

- hw/ip/usbdev/data/usbdev_testplan.hjson
Adds in_iso sequence name in tesplan for regression run.
> [usbdev,dv] adds usbdev_in_iso_seq name in testplan

- sw/device/sca/aes_serial.c
- sw/device/sca/lib/sca.c
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/aes_sca.c
This PR manually cherry-picks "Fix bugs in AES SCA" #21784 as the automatic cherry-pick failed due to a merge conflict.
> [pentest] Cherry-pick Fix bugs in AES SCA

- hw/ip/tlul/rtl/tlul_adapter_host.sv
No functional change, but this silences some lint warnings which were treating a "1" literal as a 32-bit number, so e.g. "source_q + 1" was also being expanded to 32 bits.
> [tlul,rtl] Explicitly cast +1 widths in tlul_adapter_host.sv

- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_av_buffer_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_enable_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_iso_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_rand_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_stall_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_nak_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_stall_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_trans_nak_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pending_in_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_received_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_pkt_sent_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_random_length_out_transaction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_stall_priority_over_nak_vseq.sv
This task didn't actually do anything interesting! It was actually just checking that the supplied usb20_item had the PID that was provided. There were lots of other lines as well, but these had no effect.
Probably better to ditch the extra noise.
> [usbdev,dv] Get rid of get_out_response_from_device

- hw/ip/prim/lint/prim_count.waiver
- hw/ip/prim/rtl/prim_count.sv
- hw/top_earlgrey/formal/top_earlgrey_fpv_prim_cfgs.hjson
The counters in prim_count have a magic delta signal (fpv_force), which can be used to make them jump around. This causes all manner of problems in FPV tests for other blocks that happen to include prim_count.
Tighten the ifndef line so that fpv_force is only allowed to be nonzero when we're doing FPV for prim_count on its own. This way, the outputs of the prim_count instances won't randomly jump around in blocks that want to use them.
Honestly, I suspect that the fpv_force signal isn't sufficiently constrained to be useful even in that situation. But that's probably an issue for a different commit!
This change will fix a bunch of failures in e.g. `entropy_src` SEC_CM FPV testing. I'm not sure whether it gets us to 100%, but I was seeing instant counterexamples before, and now it doesn't …
> [prim,fpv] Only allow unconstrained counters in prim_count FPV

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.S
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.c
- sw/device/tests/crypto/cryptotest/firmware/ibex_fi.h
- sw/device/tests/crypto/cryptotest/firmware/ibex_sca.c
- sw/device/tests/crypto/cryptotest/firmware/ibex_sca.h
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/ibex_fi_commands.h
- sw/device/tests/crypto/cryptotest/json/ibex_sca_commands.c
- sw/device/tests/crypto/cryptotest/json/ibex_sca_commands.h
This commit manually cherry picks lowRISC/opentitan#22269 as the automatic cherry pick failed.
This commit adds the following SCA and FI penetration tests:
- ibex.fi.address_translation
- ibex.fi.address_translation_config
- ibex.fi.char.csr_write
- ibex.fi.char.csr_read
- ibex.sca.key_sideloading
The host code is located in lowRISC/ot-sca#350
Signed-off-by: Pascal Nasahl <nasahlpa@lowrisc.org>
(cherry picked from commit ea26e1a140df386be9d1cc116e856c990939a03e)
> [pentest] Manual Cherry Pick of "Add Ibex FI & SCA tests"

- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/dice.h
- sw/device/silicon_creator/lib/drivers/keymgr.c
- sw/device/silicon_creator/lib/drivers/keymgr.h
- sw/device/silicon_creator/lib/drivers/keymgr_unittest.cc
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize_3.c
Some manual modifications were made to the cherry-picked commits to adapt them to the `earlgrey_es_sival` branch where the perso flow is still split into three separate binaries.
>  [cherry-pick] #22250 to `earlgrey_es_sival` branch 

- sw/device/silicon_creator/lib/cert/asn1.c
- sw/device/silicon_creator/lib/cert/asn1.h
- sw/device/silicon_creator/lib/cert/asn1_unittest.cc
- sw/device/silicon_creator/lib/cert/cdi_0.hjson
- sw/device/silicon_creator/lib/cert/cdi_1.hjson
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/host/ot_certs/src/asn1/builder.rs
- sw/host/ot_certs/src/asn1/codegen.rs
- sw/host/ot_certs/src/asn1/der.rs
- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/src/x509.rs
- sw/host/ot_certs/src/x509/extension.rs
- sw/host/ot_certs/tests/example.hjson
- sw/host/ot_certs/tests/example_data.json
- sw/host/ot_certs/tests/generic.hjson
The first commit modifies `push_boolean` to accept a variable, this wasn't the case before because it was not needed. The second commit uses this new feature to make basic constraints configurable. This is also a good test for the new feature.
> [ot_certs] Add support for pushing boolean and make basic constraints configurable

- sw/device/tests/BUILD
This PR re-enables the `uart_tx_rx` test on FPGAs and silicon.
The test was disabled due to flakiness in the UARTs which has hopefully gone away now.
> [ci] Enable uart_tx_rx test in CI

- hw/ip/prim/rtl/prim_pulse_sync.sv
- hw/ip/prim/rtl/prim_reg_cdc.sv
- hw/ip/prim/rtl/prim_reg_cdc_arb.sv
- hw/ip/prim/rtl/prim_sync_reqack.sv
Clarify behavior when a single domain is reset; the auto-generated register logic appears to be robust against the spurious pulses generated by the use of 'prim_pulse_sync' and 'prim_sync_reqack' (NRZ mode) during a single-domain reset, provided that there is no in-progress transaction (register read/write from SW).
Correct a couple of typographical errors.
It is perhaps worth also noting that the `SrcAckBusyChk_A` assertion will fire if the source domain is reset after an odd number of SW accesses to the CDC register, which could perhaps be prevented by changes either to the logic (now is perhaps not the time given the chip-wide impact) or the use of more-involved assertion checking that attends to reset behavior.
> [dv,prim] Clarification of reset behavior

- hw/ip/pinmux/data/pinmux.hjson
- hw/ip/pinmux/data/pinmux.hjson.tpl
- hw/ip/pinmux/doc/registers.md
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
It previously copied the pull_en description, which is incorrect. I consulted with hweng on what a correct description would be.
Cc: @moidx @msfschaffner
> [pinmux/doc]: Fix the description for the keeper_en register

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/otbn_boot_services.c
- sw/device/silicon_creator/lib/otbn_boot_services.h
- sw/device/silicon_creator/lib/otbn_boot_services_functest.c
- sw/otbn/crypto/boot.s
- sw/otbn/crypto/p256_sign.s
This is a manual cherry-pick of #21717 ([boot_services] Add functional tests for the OTBN boot services library) to the `earlgrey_es_sival` branch.
This was manually cherry-picked since a slight modification needed to be made to a file's license header after recent changes to the lint checks run on said branch (CI in #22503 had failed).
> [cherry-pick] #21717 to earlgrey_es_sival

- hw/top_earlgrey/sw/autogen/top_earlgrey_memory.ld
- sw/device/silicon_creator/lib/base/boot_measurements.h
- sw/device/silicon_creator/lib/base/static_critical_version.h
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- util/topgen/templates/toplevel_memory.ld.tpl
This partially addresses #21583 and #19588 by cranking the keymgr and generating attestation keys in the ROM_EXT.
> [rom_ext] add attestation keygen to ROM_EXT

- sw/host/ot_certs/BUILD
- sw/host/ot_certs/src/asn1/codegen.rs
- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/codegen.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/src/x509.rs
#22392: [certs] make OT cert builds deterministic
Non-ordered data structures were being iterated over to produce device code that would generate OT attestation certificates. This caused builds on different machines (and on the same machine) of the same code to be different. This switches the non-deterministic data structures for a deterministic equivalent.
Signed-off-by: Tim Trippel <ttrippel@google.com>
(cherry picked from commit 39cf48bb91e55740fd0d0b8179ac903e5654d41b)
> [cherry-pick] #22392  from `earlgrey_es_sival` branch

- sw/host/opentitanlib/src/app/config/h1dx_devboard_c2d2.json
- sw/host/opentitanlib/src/transport/hyperdebug/uart.rs
The C2D2 debugger is used by ChromeOS for communicating with the security chip among other things.  It offers basically only access to the RESET signal and the two UART lines.  This is enough to perform rescue firmware updating, or other operations.
It turns out that the default configuration file for C2D2 had not been updated with proper RESET strapping, and also instead declared empty strappings, which is confusing as it leads to silent errors.
This change properly declares the RESET strapping, and removes the ROM_BOOTSTRAP strapping (as C2D2 does not have wires to enter bootstrap mode.)
> [opentitantool] Improvements to C2D2 debugger support

- sw/device/tests/BUILD
Backport of #22261 to `earlgrey_es_sival`. The manual backport was needed because a new silicon execution environment was added.
> [cherry-pick] Backport 22261 to earlgrey_es_sival

- sw/device/tests/BUILD
- sw/device/tests/csrng_edn_concurrency_test.c
The problem is that recoverable alert (`ACMD_FLAG0_FIELD_ALERT`) is triggered *before* the test, but the test does not clear it before starting. This is problem triggered in the ROM_EXT or the ROM, and it happens on both master and es_sival.
> [csrng,sival] Fix `csrng_edn_concurrency`

- hw/ip/entropy_src/rtl/entropy_src_core.sv
These signals come from:
- u_prim_fifo_sync_distr (the distribution FIFO)
- u_prim_fifo_sync_esrng (the RNG bus input FIFO)
- u_prim_fifo_sync_observe
- u_prim_fifo_sync_esfinal
when one sees an internal error. We want any of these errors to be transformed into a fatal alert.
> [entropy_src,rtl] Factor sfifo errors into fatal alert

- sw/device/silicon_owner/tock/apps/single_app_layout.ld
- sw/device/silicon_owner/tock/kernel/layout.ld
- sw/device/silicon_owner/tock/kernel/src/main.rs
- sw/device/silicon_owner/tock/upstream_kernel/layout.ld
- third_party/tock/repos.bzl
This updates Tock past the [PMP rewrite](https://github.com/tock/tock/pull/3597), which should help with running Tock on ES hardware.
> [tock] Update the Tock kernel.

- sw/device/lib/crypto/drivers/entropy.c
When asked to enable the TRNG input (disable_trng_input = false), the code would incorrectly set `flag0` in the command to 0 instead of `kMultiBitBool4False` which triggers an alert.
Fixes #22524
> [cryptolib,entropy] Fix `csrng_send_app_cmd`

- sw/device/tests/penetrationtests/firmware/BUILD
- sw/device/tests/penetrationtests/firmware/ibex_fi.c
- sw/device/tests/penetrationtests/firmware/otbn_fi.c
- sw/device/tests/penetrationtests/firmware/sca_lib.c
- sw/device/tests/penetrationtests/firmware/sca_lib.h
- sw/device/tests/penetrationtests/json/ibex_fi_commands.h
- sw/device/tests/penetrationtests/json/otbn_fi_commands.h
This commit adds additional alerts to the alert handler configuration and fixes a bug in the configuration of the alert handler. Previously random alerts were triggered, now, only the alerts are reported that were triggered by a FI attack.
> [pentest] Configure additional alerts for FI

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/boot_data.c
- sw/device/silicon_creator/lib/boot_log.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/boot_test.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/opentitanlib/src/rescue/serial.rs
- sw/host/opentitantool/BUILD
- sw/host/opentitantool/src/command/mod.rs
- sw/host/opentitantool/src/command/ownership.rs
- sw/host/opentitantool/src/command/rescue.rs
- sw/host/opentitantool/src/main.rs
1. Initialize ownership during ROM_EXT init.
2. Process the OwnershipUnlock message in boot services.
3. Update the serial rescue implementation to encode and send the
ownership unlock command.
4. Add a top-level `ownership` command for creating the ownership unlock
command.
5. Add a rescue command to send the ownership unlock command.
6. Add a test for the OwnershipUnlock command.
> [rom_ext] Initialize ownership 

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/doc/registers.md
- hw/ip/i2c/doc/theory_of_operation.md
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_glitch_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_hrst_vseq.sv
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_pkg.sv
- hw/ip/i2c/rtl/i2c_target_fsm.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_i2c_device_tx_rx_vseq.sv
- sw/device/lib/dif/dif_i2c.h
- sw/device/lib/testing/i2c_testutils.c
Change recording of Start symbols to always accompany the address data,
instead of recording a separate R.Start, then Start+address. This helps
maintain certain availability invariants needed for reliable stretching
and NACK handling.
Note that a controller that chooses to do a Repeated Start and address a
*different* target is an unusual case, and it leads to a situation where
the transfer closing symbol won't appear until the Stop or a later
Repeated Start that *does* address this target. While this transaction
style is not explicitly forbidden in the I2C specification, it is not
typically supported in the wild. In any case, software should be able to
resolve this case, and a closing symbol will eventually appear.
Fix up the DV transaction generation to match the expected behavior. …
> [i2c] Clean up target mode transaction boundaries and NACK handling

- util/dvsim/LintParser.py
The code in extract_messages tries to avoid getting multiple hits at a single location. The idea is that you might have two different buckets that both match a particular string. For example, suppose we have buckets with the following patterns:
"This.*not.*bad"
"This.*bad"
If the log that we're parsing contains "This is not bad", we want to find a single hit (we probably want the one for the first pattern).
The code tries to do this by storing a partial map to compute "The first pattern in the list that matches the string starting at the given location".
This should work nicely! But I had messed up the Python side of things and used m.pos instead of m.start. The pos field gives the pos argument that got passed to find() (zero here) and the result is that we find exactly one result, …
> [dvsim,lint] Fix bug in duplicate detection in lint parser

- hw/ip/lc_ctrl/dv/cov/lc_ctrl_cov.core
- hw/ip/lc_ctrl/dv/cov/lc_ctrl_cov_bind.sv
- hw/ip/lc_ctrl/dv/cov/lc_tx_cov_array_if.sv
The existing binding expected a single object of type lc_tx_t, but the thing that it was sampling changed type with commit fa447d0cdc9: it is now NumRmaAckSigs different lc_tx_t objects.
VCS correctly complains at build time about the width mismatch. I couldn't easily see how to name the instances sensibly and "bind things in a loop", so I've used a simple approach where the generate module inside the thing that gets bound.
> [lc_ctrl,dv] Fix width of coverage binding

- hw/ip/prim/rtl/prim_assert_sec_cm.svh
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
No big change, but this makes the code a bit easier to follow. (It took me a while to understand!). Proper comments on each different commit.
The only bug fix is in the second commit ("[sram_ctrl,fpv] Fix incorrect assertion") where the assertion wasn't strong enough (and I only noticed because I was going through the code trying to understand everything).
> [fpv] Minor tidy-ups to SecCm FPV code

- hw/ip_templates/rv_plic/rtl/rv_plic.sv.tpl
- hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic.sv
This was... surprisingly tricky to get right! There's a long comment above the assertion that explains how to read it.
Once merged, this should hopefully fix the TOP_EARLGREY_IP_FPV Formal FPV regression (current results [here](https://reports.opentitan.org/hw/top_earlgrey/formal/ip/summary/latest/report.html))
> [rv_plic,fpv] Fix failing FpvSecCmBusIntegrity_A assertion

- hw/ip_templates/rv_plic/fpv/vip/rv_plic_assert_fpv.sv.tpl
- hw/top_earlgrey/ip_autogen/rv_plic/fpv/vip/rv_plic_assert_fpv.sv
No functional change really, but it silences some warnings that come out of Jasper at build time (because the type of the index is a 32-bit variable and it reasonably worries that this might mean we're going to to an out-of-bounds access).
> [rv_plic,fpv] Fix index widths

- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_kmac_if.sv
Previously, the two shares of the masked values forwarded to KMAC and the sideload ports would be equal when not used. This is non-ideal as the effective value observed on the sideload ports and by KMAC becomes then 0 which may potentially be exploited.
This resolves lowRISC/OpenTitan#8120.
> [keymgr] Use non-deterministic decoy values for KMAC and sideload ports

- hw/vendor/lint/pulp_riscv_dbg.vlt
The first commit is #21736: merge that first, but review the second commit here.
**For the second commit, the message is:**
This should waive the final lint warnings that come from Verilator
when building rv_dm. To see the current status, run:
```
util/dvsim/dvsim.py hw/top_earlgrey/lint/top_earlgrey_lint_cfgs.hjson \
--tool verilator --select-cfgs=rv_dm
```
Before this change, you got the following warnings:
%Warning-WIDTHTRUNC: ../src/pulp-platform_riscv-dbg_0.1_0/pulp_riscv_dbg/src/dm_mem.sv:87:41: Operator VAR 'RomBaseAddr' expects 12 bits on the Initial value, but Initial value's VARREF 'HaltAddress' generates 64 bits.
: ... note: In instance 'rv_dm.u_dm_top.i_dm_mem'
87 |   localparam logic [DbgAddressBits-1:0] RomBaseAddr   = dm::HaltAddress;
| …
> [rv_dm,lint] Waive remaining Verilator lint warnings

- sw/device/tests/crypto/cryptotest/BUILD
- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/ecdsa_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/cryptotest_util.py
- sw/host/cryptotest/testvectors/parsers/random_ecdsa_generator.py
- sw/host/tests/crypto/ecdsa_kat/src/main.rs
Adds a generator for random ECDSA tests. Per the crypto testplan, the randomness is sourced using a seed generated using python's internal randomness source. This seed is printed to `stderr` to allow for reproducible results in CI.
This PR also includes a few small changes to the ECDSA test harness to allow the random tests to work properly. The changes have been regression-tested against the existing test vectors.
~Dependent on #21713~
> [cryptotest] Add generator for random ECDSA test vectors

- sw/device/tests/crypto/cryptotest/BUILD
- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/data/schemas/ecdsa_schema.json
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/cryptotest_util.py
- sw/host/cryptotest/testvectors/parsers/random_ecdsa_generator.py
- sw/host/cryptotest/testvectors/parsers/wycheproof_rsa_parser.py
- sw/host/tests/crypto/ecdsa_kat/src/main.rs
This PR adds a parser for the wycheproof RSA test vectors. This PR uses the tests from `testvectors_v1` in wycheproof.
~Dependent on #21590 and #21599~
> [cryptotest] Add RSA wycheproof test vectors

- signing/tokens/BUILD
- sw/device/examples/hello_world/BUILD
1. Rename the `cloud_kms` token label to `cloud_kms_sival` and deprecate the old name.
2. Fix the `hello_world` demo to build as a sival ROM_EXT target.
This partially addresses #22428.
> [bazel] Rename the cloud_kms token label

- rules/autogen.bzl
Context: closed source OTP and FLASH use the `alias` feature to generate the wrapper (SHIM) registers. DIF SW code relies on these regiserts to successfully build, but current implementation of `autogen_hjson_c_header` does not allow execution of `regtool` with `alias`.
Suggestion:
This PR introduces an optional `alias` attribute to `//rules/autogen:autogen_hjson_c_header` rule and its implementation `_hjson_c_header`.
> [rules/autogen] added option for 'alias' in autogen_hjson_c_header

- rules/opentitan.bzl
- sw/device/silicon_creator/rom/e2e/shutdown_alert/BUILD
* Fixes https://github.com/lowRISC/opentitan/issues/20106
* Also removes unused `get_key_structs_for_lc_state`
> A1 e2e update shutdown alert test

- azure-pipelines.yml
Successful runs are taking ~40 minutes and sometimes we're getting timed out at 45 seemingly depending on the load of the CI runner.
> [ci] Increase CW310 SiVal non-ROM_EXT test timeout to 75m

- sw/host/ot_certs/BUILD
- sw/host/ot_certs/src/asn1/dice_tcb.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/src/x509.rs
- sw/host/ot_certs/src/x509/extension.rs
- sw/host/ot_certs/tests/dice_tcb_info.rs
This PR makes a few changes:
- mark DICE TCB info extension as **CRITICAL**, as recommended per the spec @timothytrippel 
- shuffle around some code so that the DICE TCB Info generation and parsing can be used on their own
- add a unit test to exercise the DICE TCB info specifically, without using any of the X509 stuff
> [ot_certs] Add a DICE TCB info unit test and mark extension as critical

- hw/ip/flash_ctrl/rtl/flash_phy_rd.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy_rd.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv
This commit fixes a bug in the read pipeline where the data and the mask storage FIFO could get out of sync in case of the mask computation running behind the actual Flash read (e.g. due to back pressure in the shared scrambling logic).
To avoid the FIFOs getting out of sync, the design now tracks whether for reads that don't require descrambling, a mask was still computed. This can happen if for scramble enabled locations that are being erased. In case a mask computation has been started, the FIFOs are now only popped if both the data and the mask FIFO contain a valid entry (i.e. the mask computation for the data to be popped has finished).
This resolves lowRISC/OpenTitan#22443
> [flash_ctrl] Pop read pipeline FIFOs for data and mask in sync

- hw/dv/sv/sim_sram/sim_sram.sv
- hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl
- hw/ip/flash_ctrl/rtl/flash_ctrl.sv
- hw/ip/hmac/rtl/hmac.sv
- hw/ip/kmac/rtl/kmac.sv
- hw/ip/kmac/rtl/kmac_staterd.sv
- hw/ip/otbn/rtl/otbn.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
- hw/ip/rom_ctrl/rtl/rom_ctrl.sv
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_host/rtl/spi_host_window.sv
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
- hw/ip/tlul/rtl/tlul_adapter_sram.sv
- hw/ip/tlul/rtl/tlul_sram_byte.sv
- hw/ip/usbdev/rtl/usbdev.sv
- hw/ip_templates/flash_ctrl/rtl/flash_ctrl.sv.tpl
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl.sv
I plan to put together a hacky block synthesis for sram_ctrl so I can check I've eliminated all of the feedthroughs that were causing issues. Will work on that tomorrow.
Contributes to resolving #22462.
> [sram_ctrl/rtl] Timing fixes

- azure-pipelines.yml
- hw/top_earlgrey/BUILD
- rules/opentitan/defs.bzl
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/tests/BUILD
This PR adds three new execution environments:
* `fpga_cw340_rom_ext`
* `fpga_cw340_sival`
* `fpga_cw340_sival_rom_ext`
The `uart_smoketest` is given all CW340 environments for testing purposes. The plan is to later add some select CW340 environments to the `EARLGREY_TEST_ENVS` variable used by most tests.
This PR also adds a CI job for the `cw340_sival_rom_ext` execution environment which currently will only execute `uart_smoketest`. In the future we may want another CI job for `cw340_sival` but that isn't necessary right now.
> [bazel,ci] Add `rom_ext`, `sival`, and `sival_rom_ext` exec envs for CW340

- sw/device/tests/BUILD
- sw/device/tests/uart_baud_rate_test.c
- sw/host/tests/chip/uart/src/uart_baud_rate.rs
This test was disabled in CI due to problems with the HyperDebug which appear to be fixed now.
This PR also removes the two highest Baud rates (1MBd and 1.5MBd) since they're too high for us to test. Previously they were only enabled in Silicon (where the clock was thought to run fast enough) but it seems it's either not fast enough or HyperDebug doesn't go that fast.
Open question: should I change the test plan to only require the lower Baud rates? @rswarbrick is this an acceptible change to the test?
> [sival] Re-enable UART Baud test and disable high Bauds

- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
I missed this when adding the test originally.
> [sival] Add entropy_src_fw_override_test to test plan

- hw/ip/rv_dm/dv/tb.sv
No functional change, except that we drop an unnecessary trailing '*' sign in a couple of the paths. But it took me a few minutes to work out what was using each of these connections! So I've left a couple of comments that should make it a bit more obvious.
I've also re-ordered the lines to group related interfaces a bit.
> [rv_dm,dv] Slightly tidy up interface connections in tb.sv

- hw/dv/sv/jtag_dmi_agent/jtag_dmi_monitor.sv
- hw/dv/sv/jtag_dmi_agent/jtag_dmi_reg_frontdoor.sv
This fixes issue #21517. The first two three commits have no functional change, but make the code a bit easier to read.
Following that is a change to the frontdoor sequence. This tweak ensures that we send an extra JTAG transaction just after doing a DMI request. Doing so ensures that we get truthful tracking of DmiOpInProgress afterwards.
Finally, there's a change to the monitor to avoid it believing that the DUT has suddenly become busy without being asked to do an operation (which is *very* confusing to debug!)
> [jtag_dmi_reg] Correctly handle a confusing situation where TCK is much faster than the main clock

- sw/device/tests/penetrationtests/firmware/ibex_fi.c
- sw/device/tests/penetrationtests/firmware/ibex_fi.h
- sw/device/tests/penetrationtests/json/ibex_fi_commands.h
This commit adds the ibex.fi.char.sram_write_static FI test to the codebase. The aim of this test is to fault one of the 64 consecutive SW instructions used to write a static value into SRAM. The host code is located in lowRISC/ot-sca#359
> [pentest] Add SRAM Write Static test

- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/extclk_sca_fi.c
- sw/device/tests/crypto/cryptotest/firmware/extclk_sca_fi.h
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/extclk_sca_fi_commands.c
- sw/device/tests/crypto/cryptotest/json/extclk_sca_fi_commands.h
This commit manually cherry picks PR lowRISC/opentitan#22310 and lowRISC/opentitan#22416 as the automatic cherry pick failed.
> [pentest] Cherry-pick Configure extclk

- sw/device/tests/penetrationtests/firmware/BUILD
- sw/device/tests/penetrationtests/firmware/aes_sca.c
- sw/device/tests/penetrationtests/firmware/hmac_sca.c
- sw/device/tests/penetrationtests/firmware/ibex_fi.c
- sw/device/tests/penetrationtests/firmware/ibex_sca.c
- sw/device/tests/penetrationtests/firmware/kmac_sca.c
- sw/device/tests/penetrationtests/firmware/otbn_fi.c
- sw/device/tests/penetrationtests/firmware/sca_lib.c
- sw/device/tests/penetrationtests/firmware/sca_lib.h
- sw/device/tests/penetrationtests/firmware/sha3_sca.c
- sw/device/tests/penetrationtests/json/BUILD
- sw/device/tests/penetrationtests/json/sca_lib_commands.c
- sw/device/tests/penetrationtests/json/sca_lib_commands.h
This commit extends the init function of the SCA and FI tests to read out the DEVICE_ID register in the life cycle controller. This can be used by the host to categorize test results.
> [pentest] Return device ID to host

- sw/device/tests/penetrationtests/firmware/BUILD
- sw/device/tests/penetrationtests/firmware/crypto_fi.c
- sw/device/tests/penetrationtests/firmware/crypto_fi.h
- sw/device/tests/penetrationtests/firmware/firmware.c
- sw/device/tests/penetrationtests/json/BUILD
- sw/device/tests/penetrationtests/json/commands.h
- sw/device/tests/penetrationtests/json/crypto_fi_commands.c
- sw/device/tests/penetrationtests/json/crypto_fi_commands.h
This commit adds the following fault injection tests for AES and KMAC: 
- crypto_fi_aes_key
- crypto_fi_aes_plaintext
- crypto_fi_aes_encrypt
- crypto_fi_aes_ciphertext
- crypto_fi_kmac_key
- crypto_fi_kmac_absorb
- crypto_fi_kmac_squeeze
> [pentest] AES and KMAC FI tests

- sw/device/tests/penetrationtests/firmware/extclk_sca_fi.c
This commit fixes the external clock speed selection configuration. Accidentally, a MUBI value was passed instead of a boolean to select the slow or high speed clock.
> [pentest] Fix extclk speed config

- sw/device/lib/testing/pinmux_testutils.c
- sw/device/tests/BUILD
- sw/host/tests/chip/gpio/src/main.rs
- sw/host/tests/chip/gpio_intr/src/main.rs
The current test failure is caused by:
* "teacup" interface not being recongised by test harness.
* Slight difference in pin availability compared to hyper310.
> [sival] fix GPIO tests on silicon

- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv
Inject arbitration faults randomly choosing any of the four redundant arbiters, and randomly grounding any of the two copies. Disable the assertions that are clearly violated by the fault.
Addresses #22443
> [dv,flash_ctrl] Tighten flash_ctrl_phy_arb_redun test

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/cert.c
- sw/device/silicon_creator/lib/cert/cert.h
- sw/device/silicon_creator/lib/cert/cert_unittest.cc
- sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.cc
- sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.h
- sw/device/silicon_creator/lib/error.h
This adds a cert library in the silicon_creator dir that contains helper functions and structs for managing OpenTitan certificates. Specifically a function is added to check if a cert's serial number matches what is expected. This function will be used to determine whether CDI0/1 certs need to be updated in the ROM_EXT (if the ROM_EXT or OWNER firmware is ever updated).
> [cert] add cert lib with util functions / structs

- hw/ip/prim/rtl/prim_count.sv
The correctness assertion is unchanged (because (A |-> B) && (B |-> A) is true if (A == B) when A and B are expressions). The change here is in the generated cover properties.
The correctness property means that we are proving there's only one cover point that is needed (let's make it "err_o" for brevity). But we will only see this happen when the counters get forced. Fortunately, we have a way of doing that (see the fpv_force variable). Only generate the cover property in that situation.
If you are a reviewer, you might reasonably wonder whether the `PrimCountFpv` situation works properly. So did I! It turns out that this has failed to compile since a change in September. I'm going to get that tidied up now.
> [prim,fpv] Rephrase prim_count error assertions
