lowRISC/opentitan

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
With this bug, the code failed on every execution when it tried to access the (nonexistent) abstractcmd[10].
@BasitMehmood: This is causing the failing nightly. It looks like you never actually ran the code. I didn't notice the mistake when reviewing #21543.
> [rv_dm,dv] Fix typo in rv_dm_abstractcmd_status_vseq

- hw/ip/prim/rtl/prim_arbiter_ppc.sv
A minor cleanup that avoids some tool warnings. Fortunately, it turns out that we had a width parameter floating around already so it was really easy to use!
> [prim,fpv] Fix width of FPV variable in prim_arbiter_ppc.sv

- hw/ip/lc_ctrl/dv/lc_ctrl_base_sim_cfg.hjson
- hw/ip/rom_ctrl/dv/rom_ctrl_base_sim_cfg.hjson
Without this change, there is a problem where we have two different variants of each block that are both getting built for nightly tests and both variants write results to the same place. This fix nicks the equivalent code from the aes block (which has to solve the same problem).
Fixes #22122.
> [rom_ctrl,lc_ctrl,dv] Specialise scratch_path/rel_path for variants

- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/testvectors/parsers/BUILD
- sw/host/cryptotest/testvectors/parsers/cryptotest_util.py
- sw/host/cryptotest/testvectors/parsers/hjson_rsa_parser.py
The second in the series of RSA test PRs. This PR adds a parser to integrate the existing RSA manual test vectors in `/sw/device/tests/crypto/testvectors/` with the cryptotest framework. 
During writing of this PR, I noticed that the C header templates the manual tests previously used before the current cryptotest framework was developed call into a different RSA-3072 verify API than the normal `otcrypto_rsa_verify` API, and the former calls into a dedicated OTBN routine, which will need to be separately tested within the test harness.
~Dependent on #21590~
> [cryptotest] Add parser for RSA manual hjson tests

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/cert.c
- sw/device/silicon_creator/lib/cert/cert.h
- sw/device/silicon_creator/lib/cert/cert_unittest.cc
- sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.cc
- sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.h
- sw/device/silicon_creator/lib/error.h
cherry-pick #22627: [cert] add cert lib with util functions / structs
This adds a cert library in the silicon_creator dir that contains helper functions and structs for managing OpenTitan certificates. Specifically a function is added to check if a cert's serial number matches what is expected. This function will be used to determine whether CDI0/1 certs need to be updated in the ROM_EXT (if the ROM_EXT or OWNER firmware is ever updated).
> [cherry-pick] manual cherry-pick of #22627 to `earlgrey_es_sival` branch

- sw/device/silicon_creator/rom/keys/fake/ecdsa/dev_key_0_ecdsa_p256.h
- sw/device/silicon_creator/rom/keys/fake/ecdsa/prod_key_0_ecdsa_p256.h
- sw/device/silicon_creator/rom/keys/fake/ecdsa/prod_key_1_ecdsa_p256.h
- sw/device/silicon_creator/rom/keys/fake/ecdsa/test_key_0_ecdsa_p256.h
- sw/device/silicon_creator/rom/keys/fake/otp/BUILD
Adds ECDSA keys to fake auth partition. Also adds header version of the public keys to simplify auditing of key values.
This change is part of https://github.com/lowRISC/opentitan/issues/21204.
> [rom] Add ECDSA fake keys to OTP auth partition.

- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_key.c
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_key.h
- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/sigverify_keys_ecdsa_p256.c
- sw/device/silicon_creator/rom/sigverify_keys_ecdsa_p256.h
This module is used to lookup keys in the ROT AUTH partition.
This change also updates the function name of `sigverify_ecdsa_key_id_get()` to `sigverify_ecdsa_p256_key_id_get()` to make it consistent with the module name.
This change is part of https://github.com/lowRISC/opentitan/issues/21204.
> [rom] Add sigverify_keys_ecdsa_p256 module

- rules/opentitan/cc.bzl
- rules/signing.bzl
1. The `sign_binary` function was overriding the selected ecdsa key with an empty rsa object. This was due to a missing rsa attribute empty check.
2. The `_build_binary` function in cc.bzl had an unconditional rsa key check which would fail when an ecdsa was selected.
This change is part of https://github.com/lowRISC/opentitan/issues/21204.
> [bazel] Fix ECDSA signing issues.

- sw/device/lib/crypto/drivers/entropy.c
This reduces the reseed interval for EDN0 and 1 which was causing OTBN program execution to appear to hang in the `ft_personalize` binary during an attestation key generation operation.
Specifically, when working on #22714, I noticed that OTBN execution would hang during the UDS attestation (ECC P256) key generation. It would not error out, rather it would just hang, causing `//sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup:ft_provision_fpga_cw310_sival` to timeout eventually. (After attaching a JTAG/OpenOCD/GDB setup, I was able to determine the location of the hang.)
A few things we noticed were:
1. [moving the loading of the OTBN Boot Services program to before the entropy complex was reconfigured for keymgr operations](https://github.com/lowRISC/opentitan/pull/22714/com …
> [entropy] reduce reseed interval in cryptolib

- hw/ip/tlul/rtl/tlul_adapter_sram.sv
The existing assertion was actually false because the response from the SRAM might have been unknown. Thank you, Jasper, for leading me to this!
> [tlul,rtl] Weaken "known" assertion in tlul_adapter_sram.sv

- hw/ip/prim/rtl/prim_count.sv
This PR has three commits, but only the last one is unique to this PR. The other two come from #22560 which should be merged first. The commit unique to this PR is:
*[prim,fpv] Correct assertions for commit_i input*
The ClrFwd_A assertion says "When a clear is requested, it should take
effect". But this isn't quite true because commit_i might be false,
which would mean the clear operation wouldn't take effect in cnt_q.
Strengthen the assumption to "When a clear is requested and we really
mean it ..."
Similarly for SetFwd_A.
> [prim,fpv] Correct assertions for commit_i input

- sw/device/tests/BUILD
I've seen this test failing in multiple PRs now that don't touch any of I2C. I think it's most likely broken.
Examples of where it failed CI:
- https://github.com/lowRISC/opentitan/pull/22599
- https://github.com/lowRISC/opentitan/pull/22588
- https://github.com/lowRISC/opentitan/pull/22621
> [sival] Mark `i2c_target_test_fpga_cw310_sival` as broken

- sw/device/tests/penetrationtests/firmware/ibex_fi.c
- sw/device/tests/penetrationtests/firmware/otbn_fi.c
- sw/device/tests/penetrationtests/firmware/sca_lib.c
- sw/device/tests/penetrationtests/firmware/sca_lib.h
- sw/device/tests/penetrationtests/json/ibex_fi_commands.h
- sw/device/tests/penetrationtests/json/otbn_fi_commands.h
As for the pen. testing evaluating an array instead of individual variables for the triggered alerts is easier, this commit switches the format of how the alerts are returned to the host.
> [pentest] Return alerts as array

- rules/opentitan/defs.bzl
- rules/opentitan/fpga_cw310.bzl
- rules/opentitan/silicon.bzl
- rules/opentitan/sim_dv.bzl
- rules/opentitan/sim_verilator.bzl
- sw/device/tests/BUILD
- sw/device/tests/entropy_src_edn_reqs_test.c
The first commit enables `opentitan_test` to take per-exec-env defines.
The second commit fixes the test, the test has two problems in SiVal:
- the SiVal ROM_EXT blocks direct access to the OTP registers so the
OTP test triggers an exception. Disable this test in SiVal as it
simply cannot be done.
- the SiVal ROM_EXT cranks the key manage to the owner state whereas
the ROM does not touch the key manager. Change the test to expect
a different state in SiVal.
> Fix entropy src edn reqs

- hw/ip/edn/dv/env/edn_scoreboard.sv
The sw_cmd_reg_rdy also goes high after the last additional data word and low again after receiving the ACK from CSRNG. Previously, the scoreboard expected this bit not to go high again after the last additional data word causing around 20 - 40% of edn_disable_auto_req_mode tests to fail.
> [edn/dv] Correct prediction of sw_cmd_reg_rdy for auto mode Instantiate

- rules/opentitan/cc.bzl
- rules/signing.bzl
1. The `sign_binary` function was overriding the selected ecdsa key with an empty rsa object. This was due to a missing rsa attribute empty check.
2. The `_build_binary` function in cc.bzl had an unconditional rsa key check which would fail when an ecdsa was selected.
(cherry picked from commit f3e4604ea129ff6d2bbfeae80ad1ed37a6b61601)
Original PR: https://github.com/lowRISC/opentitan/pull/22742
> cherry-pick manual: [bazel] Fix signing issues.

- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_verify.c
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_verify.h
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_verify_functest.c
Introduce `sigverify_p256_verify()` function. The function uses the otbn_boot_services OTBN kernel to provide signature verification of the next code partition. The signature comparison method is adapted from the sigverify RSA implementation.
The magic constant generated by `sigverify_ecdsa_p256_verify()` is the same value generated by `sigverify_rsa_verify()`. This is so that we can migrate from RSA --> ECDSA via incremental changes.
This change is part of [#21204](https://github.com/lowRISC/opentitan/issues/21204).
> [rom] sigverify ECDSA P256

- sw/device/lib/crypto/drivers/entropy.c
This PR removes the wait for idle in csrng_send_app_cmd().
For further information check out the commit message.
This PR depends on #22114.
Fixes [#19568](https://github.com/lowRISC/opentitan/issues/19568).
> [crypto-lib/csrng] Remove wait for idle in csrng_send_app_cmd

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/doc/registers.md
- hw/ip/i2c/rtl/i2c_controller_fsm.sv
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
- hw/ip/i2c/rtl/i2c_target_fsm.sv
Reduce counter sizes to only the widths needed to support Standard mode at a 1 GHz core clock.
In the FPGA implementation, this saves 44 flops (~4%) and over 100 LUTs (~6.6%). The granularity of the FPGA area is large, so the size of the savings can be misleading, but compared to what we had prior to the FSM split, this brings us to +29 flops, -59 LUTs for the whole chain of commits.
This builds on #22551. Only the last commit is new.
> [i2c] Reduce counter sizes to save area

- sw/host/tests/chip/i2c_host_override/src/main.rs
- sw/host/tests/chip/i2c_target/src/main.rs
This PR fix the i2c_override test and improve the i2c_repreated_start test by changing how the hyperdebug pins are configured.
> [Sival, i2c] Fix i2c tests

- sw/device/tests/BUILD
This reverts commit 2cfed61d65eb9a7e0055af6fcfcff5697d28361c.
The Bazel target was removed because it was assumed to only be there for CW340 use, but it was also used by some DVSIM tests.
Re-adding until we work out how DVSIM can use the `opentitan_test` version.
See https://github.com/lowRISC/opentitan/issues/22733
> [bazel] Revert "Remove opentitan_functest UART smoketest"

- third_party/lint/repos.bzl
This updates the lowRISC misc-linters dependency that was causing a CI breakage.
> [bazel] update lowRISC misc-linters

- sw/device/tests/BUILD
- sw/device/tests/pwrmgr_all_reset_reqs_test.c
The test was `pwrmgr_all_reset_reqs_test_fpga_cw310_sival_rom_ext` was flaky because occasionally an unexpected reset (0x40 = `kDifRstmgrResetInfoEscalation`) would occur and mess up with the test.
This PR moves the alert handler configuration to phase 3 of the test.
> [Sival, pwrmgr] Fix flakyness on Silicon

- sw/device/silicon_owner/tock/kernel/src/main.rs
- sw/host/tests/chip/i2c_target/src/smbus_arp.rs
- sw/host/tests/chip/rv_dm/src/control_status.rs
- sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs
This patch is a result of running
$ touch sw/device/silicon_owner/tock/kernel/src/tests.rs $ basel run //quality:rustfmt_fix
$ rm sw/device/silicon_owner/tock/kernel/src/tests.rs
The first line is necessary to address the issue where rustfmt fails to process sw/device/silicon_owner/tock/kernel/src/main.rs due to the missing test module.
> fix rust format violations.

- sw/device/silicon_creator/rom/e2e/sigverify_key_type/BUILD
> [bazel] Update `rom/e2e/sigverify_key_type` to the new rules

- rules/opentitan/defs.bzl
- rules/opentitan/keyutils.bzl
1. Update opentitan_test macro to support ecdsa_keys.
2. Add `ecdsa_key_for_lc_state()` to keyutils.bzl. This is helpful in providing a mechanism to generate a key set dependency for opentitan_test and opentitan_binary targets.
> [bazel] Add support for ecdsa keys to opentitan_test.

- sw/device/silicon_creator/lib/ownership/ecdsa_functest.c
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block_unittest.cc
The symbol `kBootDataSlot...` got replaced by `kBootSlot...`.
> [ownership] Fix merge skew

- sw/device/silicon_owner/tock/kernel/src/main.rs
This makes it possible to run rustfmt acroll the entire tree.
> tock: comment out nonexisting test module reference

- hw/ip/uart/doc/theory_of_operation.md
"If the baud rate is (too low), care should be taken when the system clock frequency is (too high)." - It currently says "when the clock frequency is **under** X MHz"; should say "over".
I also changed the rounding of frequency values in that paragraph (after doing the math to make sure it's right) so that they're rounded down instead of up, which makes more sense after this change (otherwise, it would imply that 31.7 MHz is safe for 1200 baud since it's <32, but it's not - max safe frequency is 31.45).
> doc/theory_of_operation.md: "under" should be "over"

- hw/ip/ascon/rtl/ascon_core.sv
The Ascon hardware block is very much work in progress. Unfortunately, lint warnings and errors inside Ascon cause the whole AscentLint CI job to fail.
> [ascon] Fix AscentLint warning

- sw/device/tests/penetrationtests/firmware/BUILD
We don't want to run this test automatically as part of CI. Tag it as `manual`, to address that issue.
> Tag `chip_pen_test` as a manually-triggered test

- hw/ip/tlul/README.md
The example in the timing diagram shows several device responses. One of these responses has the d_error signal set. On that cycle, d_source is I5 but the caption talks about an error on the I4 response. Fix the caption.
Fixes #22817.
> [tlul,doc] Fix typo in timing diagram caption

- hw/formal/tools/dvsim/common_fpv_cfg.hjson
- hw/formal/tools/jaspergold/fpv.tcl
- hw/ip_templates/alert_handler/fpv/tb/esc_after_load.tcl.tpl
- hw/ip_templates/alert_handler/fpv/tb/ping_after_load.tcl
- hw/top_earlgrey/formal/top_earlgrey_fpv_prim_cfgs.hjson
- hw/top_earlgrey/ip_autogen/alert_handler/fpv/tb/esc_after_load.tcl
- hw/top_earlgrey/ip_autogen/alert_handler/fpv/tb/ping_after_load.tcl
There are careful comments in the respective commits' commit messages (and in the code they add: most of which is comments to explain it!).
The second group of cover properties that is waived in the final commit actually points to some unnecessary RTL(!). I'll file a separate PR to reflect that.
> [fpv,alert_handler] Carefully waive some coverage requirements in prim FPV

- hw/ip/prim/lint/prim_count.vlt
- hw/ip/prim/lint/prim_count.waiver
- hw/ip/prim/prim_count.core
- hw/ip/prim/rtl/prim_count.sv
- hw/ip/prim/rtl/prim_count_pkg.sv
- hw/ip_templates/alert_handler/rtl/alert_handler_esc_timer.sv
- hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv
- hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_esc_timer.sv
- hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
This is all about avoiding some vacuous assertions that are reported in prim FPV tests. The first commit generalises a `DecrNeverTrue` parameter that I added recently and allows a user to specify exactly which actions are possible in the given instance.
The second commit uses the new `PossibleActions` parameter in the alert_handler's ping timer, where we have two different instances of `prim_count` which are used in two different ways.
The end result should be to improve the "pass rate" in the nightly prim FPV tests.
> [fpv,prim] Generalise FPV parameter that constrains what actions a prim_count is asked for

- hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv
- hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
The FSM in the ping timer uses a prim_count to count down from a timeout value (ping_timeout_cyc_i) to zero. It then avoids telling the prim_count module to decrement further.
But the prim_count saturates at zero already, so that check isn't actually needed.
(Spotted by debugging why an FPV property about decrementing when equal to zero was unreachable)
Note that the FPV property in question has its coverage property waived in PR #22797. If both PRs land, the second one to land should be amended to drop the waiver.
> [alert_handler,rtl] Slightly simplify decrementing counter

- hw/ip_templates/alert_handler/fpv/tb/ping_after_load.tcl
- hw/top_earlgrey/ip_autogen/alert_handler/fpv/tb/ping_after_load.tcl
These were added in 4668da7 but the waivers were needed because of something fixed in the design by cd303a4. Remove the waivers accordingly.
(I meant to squash the change that drops these waivers into the second commit above, but forgot. That PR is #22798)
> [fpv,alert_handler] Remove two unnecessary cover waivers

- hw/top_earlgrey/BUILD
- sw/device/silicon_creator/rom/e2e/BUILD
- sw/device/silicon_creator/rom/e2e/weak_straps/gpio.bzl
Migrates all //sw/device/silicon_creator/rom/e2e:* to opentitan_test rules.
Update e2e/weak_straps to remove dependency to rom/e2e:* targets.
Add sim_verilator_rom_with_fake_keys execution environment.
Fixes: https://github.com/lowRISC/opentitan/issues/19923
> [bazel] Migrate rom/e2e:* targets to opentitan_test

- sw/device/tests/BUILD
These tests check that JTAG is not accessible, so can be run on PROD LC state.
> [sival, rv_dm] Enable lc_disabled tests for silicon

- hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson
- sw/device/lib/testing/json/command.h
- sw/device/lib/testing/json/i2c_target.h
- sw/device/tests/i2c_target_test.c
- sw/host/opentitanlib/src/test_utils/i2c_target.rs
- sw/host/tests/chip/i2c_target/src/main.rs
This is a manual backport PR of #22701 to master.
The automatic backport failed because the master branch has new CRC functions for ujson.
> Backport 22701 to master

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
This change was done for hw/ip/flash_ctrl only, so it must be done in hw/ip_templates/flash_ctrl as well.
Part of #8440
> [dv,flash_ctrl] Port missing fix from ip/flash_ctrl/dv

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_rom_tests.hjson
- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/e2e/bootstrap/BUILD
- sw/device/silicon_creator/rom/e2e/jtag_inject/BUILD
- sw/device/silicon_creator/rom/e2e/release/BUILD
- sw/device/tests/BUILD
1. Remove unused `opentitan_functest` references from BUILD files.
2. Remove `uart_smoketest_signed` as this is equivalent to the `rom_e2e_smoketest`.
> [bazel] Remove opentitantest references from build files

- doc/contributing/bazel_notes.md
- doc/getting_started/build_sw.md
- doc/getting_started/setup_fpga.md
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/verilator/verilator_sim_cfg.hjson
- sw/device/lib/testing/test_rom/BUILD
- sw/device/silicon_owner/tock/tests/basic/src/basic.rs
Remove `opentitan_functest` references from Markdown and comments in source code.
The same was done for `opentitan_{flash,rom}_binary` references.
Removed some Bazel commands that are no longer valid with `opentitan_test`.
> [doc] Remove opentitan_functest references.

- hw/ip_templates/clkmgr/dv/sva/clkmgr_bind.sv
- hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_bind.sv
The SVAs for peripheral clock gating need to use inputs synchronized to the clock they control, or they will be unrealistic. It is possible that the gating controls will change too quick and a pulse will be missed, causing assertion failures. In reality this is a corner case since the expectation is that gating controls will change infrequently.
> [dv,clkmgr] Used synchronized sw enables in SVA

- hw/ip/csrng/rtl/csrng_core.sv
Previously the cmd sts signal was checked to be 1'b1 but now it is more than one bit. Now we check if it is NE zero by comparing to CMD_STS_SUCCESS.
> [csrng/rtl] Fix lint error

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_jtag_inject_vseq.sv
- sw/device/examples/sram_program/sram_program.c
- sw/device/examples/sram_program/sram_program.ld
- sw/device/silicon_creator/manuf/lib/sram_start.S
- sw/device/silicon_creator/manuf/lib/sram_start_no_ast_init.S
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/sram_cp_provision.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/sram_cp_provision_functest.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/sram_ft_individualize.c
- sw/device/silicon_creator/manuf/tests/sram_device_info_flash_wr_functest.c
- sw/device/silicon_creator/manuf/tests/sram_empty_functest.c
- sw/device/silicon_creator/manuf/tests/sram_exec_test.c
- sw/device/tests/flash_ctrl_rma_test.c
- sw/device/tests/rv_core_ibex_epmp_test.S
- sw/device/tests/rv_core_ibex_epmp_test.c
- sw/device/tests/rv_core_ibex_isa_test.S
- sw/device/tests/rv_core_ibex_mem_test.c
- sw/host/opentitanlib/src/test_utils/load_sram_program.rs
- sw/host/tests/chip/rv_core_ibex_isa/src/main.rs
- sw/host/tests/manuf/manuf_cp_device_info_flash_wr/src/main.rs
- sw/host/tests/manuf/manuf_sram_program_crc_check/src/main.rs
This makes it easier to use the a test as both sram main and a normal test.
The rv_core_ibex_isa_test currently uses a0 for returning error code, which I have changed it to a1 so that a0 is used as `bool test_main` return code.
This is a preparatory PR to run some rv_core_ibex SRAM program tests as normal tests when LC state is PROD.
> [sram_program] Rename `sram_main` to `test_main`

- sw/device/tests/BUILD
- sw/device/tests/pmod/BUILD
Add the Silicon exec_env to test so they can run on the nightlies.
> [Sival]  Add the Silicon exec_env to test

- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/lib/personalize_functest.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/host/opentitanlib/src/test_utils/lc.rs
- sw/host/tests/manuf/personalize_functest/src/main.rs
This makes several reliability improvements to the perso functest and reactivates it in CI. This fixes #19086.
> [manuf] improve reliability of `personalize_functest`  and reactivate in CI

- sw/device/tests/chip_power_idle_load.c
~~The first commit (cherr-picked from #22579) enables opentitan_test to take per-exec-env defines.~~ (now committed)
The second commit fixes the test, by disabling OTP access in SiVal ROM_EXT environments.
> Fix chip_power_idle_load for SiVal ROM_EXT environment

- hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
- hw/ip/csrng/rtl/csrng_cmd_stage.sv
The ready signal of the genbits FIFO is not considered when pushing the FIFO which may raise concerns. However, by inspecting the command stage FSM, one can see that the FSM only ever triggers the generation of more bits if the genbits FIFO is empty.
This commit documents these findings in the RTL and adds some SVAs to check that 1) the FSM indeed only ever enters the stage where it requests more bits after finding an empty FIFO and 2) that the genbits FIFO is only ever pushed in the in the FSM states where this can be expected.
This resolves lowRISC/OpenTitan#16563.
> [csrng] Add SVAs to check for unexpected pushes to the genbits FIFO

- hw/ip/mbx/data/mbx.hjson
- hw/ip/mbx/rtl/mbx_reg_pkg.sv
- hw/ip/mbx/rtl/mbx_soc_reg_top.sv
A mailbox con either be a PCIe mailbox or a FW mailbox. In case of the PCIe setting, the SOC reagisters 0x0 and 0x4 implement the capability header functionality, but this is done outside of the mbx RTL. PCIe mailboxes do not use the SOC_INTR_DATA/ADDR registers. FW-based mailboxes on the other hand only use the SOC_INTR_DATA/ADDR registers but no capability headers. Previously, it was decided to alias both registers as they are used orthogonally. However, this deceission was revised.
This PR moves the SOC_INTR_DATA/ADDR registers to the end of the SOC register interface to not alias with any capability header registers for PCIe mailboxes
> [hw,mbx,rtl] Move SOC_INTR_ADDR/DATA registers to the end

- sw/device/tests/power_virus_systemtest.c
Reduce the number of power_virus test iterations for silicon targets. This is to make the test run within 5 minutes at a standard core frequency.
> [test] Reduce number of power_virus test iterations.

- sw/device/silicon_creator/rom/rom.c
- sw/device/tests/BUILD
This PR changes the ROM to write the retention SRAM version on every boot, not just after initialization. The version is expected by the ROM_EXT to boot, but is cleared by scrambling.
An alternative would be for the `ROM_EXT` to assume that unknown version indicate scrambling and re-populate the retention sram.
This change fixes the `sram_ctrl_sleep_sram_ret_contents_scramble_test` which ensures we can wake up from deep sleep after scrambling.
---
The previous version of this PR disabled this part of the test:
> Deep sleep requires a reset to wake up again. Resetting runs through the ROM_EXT. The ROM_EXT will not boot if the retention SRAM is scrambled.
> We therefore cannot test this part under those conditions, so I have disabled it.
> [rom] Always set ret sram version on boot

- doc/contributing/style_guides/otbn_style_guide.md
This text is from an OpenTitan-domain [doc](https://docs.google.com/document/d/1kX2fr5lH9xzYcpu2ycsac4JZ2j8L0Vl_0UNmoN3-UlY/edit) that @abdullahvarici wrote a while back, but it seems useful to have on the public documentation website as well.
> [doc] Add SCA guidelines for OTBN from COCO-Alma work.

- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
- sw/device/tests/BUILD
This PR:
* Adds the `pwrmgr_smoketest` as satisfying the `external_full_reset` test point.
* Supposedly any device test will do here, so I've just picked one.
* Removes the `broken` tag from `pwrmgr_random_sleep_all_reset_reqs_test`.
* This test passed 100/100 runs I did so I don't think it's flaky any  more.
* Probably fixed by https://github.com/lowRISC/opentitan/pull/22730
* Adds the sival execution environments to the `pwrmgr_normal_sleep_all_reset_reqs_test`.
* Like above, this passed 100/100 times when I ran it on a CW310.
> [sival] Fix pwrmgr testplan for sival

- hw/ip/hmac/README.md
- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/doc/registers.md
- hw/ip/hmac/lint/hmac.vlt
- hw/ip/hmac/lint/hmac.waiver
- hw/ip/hmac/rtl/hmac.sv
- hw/ip/hmac/rtl/hmac_core.sv
- hw/ip/prim/rtl/prim_sha2.sv
- hw/ip/prim/rtl/prim_sha2_32.sv
- sw/device/tests/hmac_secure_wipe_test.c
This PR fixes the secure wiping feature in `prim_sha2` engine such that internal variables are overwritten with the WIPE_SECRET value rather than XORed. This change makes it more secure and also consistent with how the secret key is wiped in HMAC. This change has ~~no impact on DV, given its current state (value overwritten to variables is not checked atm)~~ no impact on block-level DV - `hmac_smoke` and `hmac_wipe_secret` pass. A TLT has been updated in this PR to correspond with this change.
Once merged, this would close #22555.
> [prim_sha2/hmac,rtl/dv] HMAC/SHA-2 secure wiping fix

- sw/device/silicon_creator/lib/boot_data.h
- sw/device/silicon_creator/lib/boot_log.h
- sw/device/silicon_creator/lib/drivers/ibex.c
- sw/device/silicon_creator/lib/drivers/ibex.h
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/boot_test.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
1. Add an `ownership_transfers` member which will report the total number of ownership transfers the chip has had.
2. Use the remap window to detect in which flash slot the ROM_EXT is running.
3. Test all variations of owner slots and ROM_EXT slots.
> [rom_ext] Improve `boot_log` reporting

- hw/ip/edn/doc/registers.md
Commit 903b319 accidentally replaced EDN's registers.md with that of CSRNG. This commit switches back.
> [edn/doc] Switch back to EDN's registers.md

- hw/ip/rv_dm/rtl/rv_dm.sv
This comment is supposed to be explaining that we're using a mubi value for the late debug signal. It was not quite in the right place: move it to fix that.
> [rv_dm,rtl] Fix location of SEC_CM comment

- hw/ip_templates/clkmgr/dv/clkmgr_sim_cfg.hjson
- hw/ip_templates/clkmgr/dv/cov/clkmgr_tgl_excl.cfg.tpl
- hw/ip_templates/pwrmgr/dv/cov/pwrmgr_tgl_excl.cfg
- hw/ip_templates/pwrmgr/dv/pwrmgr_sim_cfg.hjson
- hw/ip_templates/rstmgr/dv/cov/rstmgr_tgl_excl.cfg.tpl
- hw/ip_templates/rstmgr/dv/rstmgr_sim_cfg.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/ip_autogen/clkmgr/dv/clkmgr_sim_cfg.hjson
- hw/top_earlgrey/ip_autogen/clkmgr/dv/cov/clkmgr_tgl_excl.cfg
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/cov/pwrmgr_tgl_excl.cfg
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/pwrmgr_sim_cfg.hjson
- hw/top_earlgrey/ip_autogen/rstmgr/dv/cov/rstmgr_tgl_excl.cfg
- hw/top_earlgrey/ip_autogen/rstmgr/dv/rstmgr_sim_cfg.hjson
- Generate the exclusions for clkmgr and rstmgr from templates. This is easier to maintain since the information comes from the hjson files.
- Create exclusion for pwrmgr with a single item.
- Use `module_name` directive for exclusion since it makes it possible to use the same config at block and full chip level.
- Add these exclusions to each block environment as well.
- Add these exclusions to full chip.
Fixes #16640
> [dv,cov] Improve config for toggle coverage exclusions

- sw/device/silicon_creator/lib/drivers/ibex.c
- sw/device/silicon_creator/lib/drivers/ibex_unittest.cc
1. The address translation windows do not properly mask off low bits in hardware.  Mask them off in software before programming.
2. The address translation windows must be power-of-two aligned with respect to the window size.  Forcibly align the remap address.
This partially addresses #22884.
> [rom, rom_ext] Fix address translation

- third_party/coremark/top_earlgrey/BUILD
Add silicon_owner execution environments to the coremark_test target.
> [sival] Enable //third_party/coremark/top_earlgrey:coremark_test.

- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/keymgr_testutils.h
- sw/device/tests/keymgr_sideload_aes_test.c
1. Add `keymgr_testutils_max_key_version_get()` to determine the maximum key version allowable by the current keymgr state.
2. Add `keeymgr_testutils_string_get()` to return a string format version of the current keymgr state.
1. Implement keymgr initialization via `keymgr_testutils_try_startup()` for silicon targets. The initialization will aim to advance the state `OwnerRootKey` which is the expected initial state for silicon_owner execution environments.
2. Check the max_key_version and adjust the key generation parameters accordingly. In silicon_owner execution environments, the max key version is set by the rom_ext.
3. Update log messages to print the current keymgr state instead of using hard-coded strings.
> [sival] keymgr test updates

- sw/device/tests/BUILD
- sw/device/tests/sram_ctrl_sleep_sram_ret_contents_impl.c
The retention SRAM contains a "version" field which the ROM_EXT expects to be valid in order to boot. The ES version of the ROM does not set this field on every boot. Since the version is invalid after a wipe / scrambling of the retention SRAM, this test was failing due to boot errors.
This is fixed in the production ROM, but we've had to work around it for ES.
The scrambling version of this test:
1. Changes the scrambling key from the default.
2. Writes a pattern to retention SRAM and goes into a normal sleep. After waking up, we check that the pattern reads back the same.
3. Goes into deep sleep and resets using the AON timer.
4. With this kind of reset, the ROM should restore the scrambling key we changed to. We check this by reading back the pattern again.
5. Resets "normally" using …
> [sival,sram_ctrl] Fix sram_ctrl_sleep_contents_ret test

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- util/topgen/c_test.py
- util/topgen/merge.py
- util/topgen/validate.py
There might be multiple rv_dm instances in the system. Therefore, use the module property to determine there is no DIF for rv_dm modules rather than the name
> [topgen] Support for multiple rv_dm instances

- sw/device/sca/aes_serial.c
- sw/device/tests/aes_masking_off_test.c
- sw/device/tests/crypto/cryptotest/firmware/aes_sca.c
The input masks are now taken from the PRNG buffer stage. This means after loading the magic seed into the PRNG and having the PRNG output the all-zero vector, the buffer stage needs to be updated as well. This can be achieved by triggering via a clearing operation of the data output registers.
This resolves lowRISC/OpenTitan#22917.
> [aes/sw] Load all-zero vector into PRNG buffer stage for masking off

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/rstmgr_alert_info_test.c
Fixes https://github.com/lowRISC/opentitan/issues/20589
The Root cause was that the ROM_EXT locks up the OTP registers with the ePMP, any attempt to write to them would generate an exception.
Therefore, we can't test the OTP alert when the test runs after the ROM_EXT.
> [Sival, rstmgr] Fix rstmgr_alert_info_test on ROM_EXT

- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/doc/registers.md
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/rtl/csrng_cmd_stage.sv
- hw/ip/csrng/rtl/csrng_core.sv
- hw/ip/csrng/rtl/csrng_ctr_drbg_cmd.sv
- hw/ip/csrng/rtl/csrng_pkg.sv
- hw/ip/csrng/rtl/csrng_reg_pkg.sv
- hw/ip/csrng/rtl/csrng_reg_top.sv
- hw/ip/edn/data/edn.hjson
- hw/ip/edn/doc/registers.md
- hw/ip/edn/rtl/edn_reg_pkg.sv
- hw/ip/edn/rtl/edn_reg_top.sv
- sw/device/lib/crypto/drivers/entropy_kat.c
- sw/device/lib/dif/dif_csrng.h
- sw/device/lib/dif/dif_csrng_unittest.cc
- sw/device/lib/testing/aes_testutils.c
- sw/device/lib/testing/csrng_testutils.c
Please see the commit messages for info.
Resolves [#16499](https://github.com/lowRISC/opentitan/issues/16499)
I still need to do some cleanup and debug the last part of the alert test vseq.
There seems to be an issue in DV where the wait for an acknowledgement doesn't behave as 
expected.
I also need to rebase.
The first commit can be ignored since it is already merged.
> [csrng/rtl] add reseed intervall sts err

- sw/device/silicon_creator/rom_ext/rom_ext.c
This temporarily disables DICE certificate updating in the ROM_EXT to unblock CI. A more permanent fix to #22921 will be rolled out shortly.
> [rom_ext] temporarily disable cert updating

- sw/device/lib/crypto/drivers/entropy.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
This change aims to mitigate some of the side effects caused by lowRISC/opentitan#22877.
1. Increase the reseed interval in EDN0 to reduce the number of requests going to entropy_src.
2. Increase the reseed interval in keymgr to reduce the number of requests going to edn0.
Both configuration values will be updated later on based on recommendations derived from penetration testing and pre-silicon evaluation.
> [rom_ext] Relax EDN0 configuration.

- hw/ip/kmac/data/kmac.hjson
- hw/ip/kmac/doc/programmers_guide.md
- hw/ip/kmac/doc/registers.md
- hw/ip/kmac/doc/theory_of_operation.md
- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_key_error_vseq.sv
- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
- hw/ip/kmac/lint/kmac.waiver
- hw/ip/kmac/rtl/kmac.sv
- hw/ip/kmac/rtl/kmac_app.sv
- hw/ip/kmac/rtl/kmac_core.sv
- hw/ip/kmac/rtl/kmac_errchk.sv
- hw/ip/kmac/rtl/kmac_reg_pkg.sv
- hw/ip/kmac/rtl/kmac_reg_top.sv
- sw/device/lib/crypto/drivers/kmac.c
- sw/device/lib/crypto/drivers/kmac.h
- sw/device/lib/dif/dif_kmac.c
- sw/device/lib/dif/dif_kmac.h
- sw/device/lib/dif/dif_kmac_unittest.cc
- sw/device/lib/testing/kmac_testutils.c
- sw/device/lib/testing/kmac_testutils.h
- sw/device/silicon_creator/lib/drivers/kmac.c
- sw/device/tests/keymgr_sideload_kmac_test.c
- sw/device/tests/kmac_entropy_test.c
The KMAC HW IP block features an option to load keys from Key Manager
via a HW key sideload interface.  Prior to this commit, KMAC would:
- when used via the SW application interface: *not check at all* if the
sideload key is valid (issue https://github.com/lowRISC/opentitan/issues/10704, https://github.com/lowRISC/opentitan/issues/16855);
- when used via a HW application interface: check if the sideload key is
valid *only for a single cycle* when the application interface gets
configured (state `StAppCfg` in `kmac_app`).
This could lead to cases where KMAC would use an invalid sideload key. This PR fixes that by raising an error in these cases.
To enable that, this PR moves the `err_processed` bit from the `CFG_SHADOWED` CSR to the `CMD` CSR, and this PR fixes three problems with KMAC's …
> [kmac] Abort when sideload key is invalid during operation

- sw/device/silicon_creator/lib/sigverify/sphincsplus/address.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/address.h
- sw/device/silicon_creator/lib/sigverify/sphincsplus/address_unittest.cc
- sw/device/silicon_creator/lib/sigverify/sphincsplus/params.h
This change does not affect the sphincsplus-shake-128s parameter set we use, since the key pair field is less than two bytes for all of the parameter sets that were submitted to the NIST competition. However, some choices of parameters need a larger field, so for maximum flexibility it makes sense to adjust. This change does not have any significant effect on performance, since these copies/writes are not on the hot path (checked this locally as well).
Corresponds to commit 7ec789a from the SPHINCS+ reference implementation (PR 60):
https://github.com/sphincs/sphincsplus/commit/7ec789ace6874d875f4bb84cb61b81155398167e
One difference between this PR and the commit above is that the check for `SPX_D==1` in `hash_shake.c` doesn't appear here; that's because we actually already had it! I …
> [rom] Change the size of the key pair field in SPHINCS+ addresses.

- hw/ip/otbn/rtl/otbn_alu_bignum.sv
- hw/ip/otbn/rtl/otbn_controller.sv
- hw/ip/otbn/rtl/otbn_core.sv
- hw/ip/otbn/rtl/otbn_mac_bignum.sv
- hw/ip/otbn/rtl/otbn_rf_base.sv
- hw/ip/otbn/rtl/otbn_start_stop_control.sv
This commit adds a little bit of security hardening around signals used for zeroing parts of the OTBN state during secure wipe. To this end, the secure_wipe_running_o signal is registered inside the start stop controller (to get distinct driving cells) and the critical signals are compared against the secure_wipe_running signal at the point of consumption.
This resolves lowRISC/OpenTitan#12061.
> [otbn] Detect unexpected partial "secure" wipes

- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/vendor/lowrisc_ibex.lock.hjson
- hw/vendor/lowrisc_ibex/dv/cosim/spike_cosim.cc
- hw/vendor/lowrisc_ibex/dv/cosim/spike_cosim.h
- hw/vendor/lowrisc_ibex/dv/riscv_compliance/ibex_riscv_compliance.core
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/Makefile
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/riscv_dv_extension/ibex_asm_program_gen.sv
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/riscv_dv_extension/ibex_directed_instr_lib.sv
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/scripts/collect_results.py
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/scripts/compile_tb.py
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/scripts/merge_cov.py
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/scripts/report_lib/util.py
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/scripts/run_rtl.py
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/yaml/rtl_simulation.yaml
- hw/vendor/lowrisc_ibex/dv/uvm/icache/dv/fcov/ibex_icache_fcov_if.sv
- hw/vendor/lowrisc_ibex/dv/verilator/simple_system_cosim/ibex_simple_system_cosim.core
- hw/vendor/lowrisc_ibex/rtl/ibex_core.f
- hw/vendor/lowrisc_ibex/rtl/ibex_counter.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_top.sv
- hw/vendor/lowrisc_ibex/util/Makefile
This PR mainly reduced the number of PRINCE rounds for ICache scrambling to improve the timing. From a security perspective, this is acceptable. The scrambling of the other memory primitives (OTBN IMEM, DMEM, ROM etc.) is not touched.
To enable this change, Ibex needs to be re-vendored.
This is related to #22462.
> [rv_core_ibex] Re-vendor Ibex and reduce number of PRINCE rounds for ICache scrambling

- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
This PR:
1. Fixes the `lc_state` for `chip_sw_rstmgr_sys_reset_info` since its testplan specifies it cannot run in `PROD`.
2. Fixes the bazel targets for `pwrmgr_random_sleep_all_reset_reqs` which were wrong.
> [sival,rstmgr] Fix testplan entries for rstmgr

- hw/ip_templates/alert_handler/dv/env/seq_lib/alert_handler_common_vseq.sv
- hw/top_earlgrey/ip_autogen/alert_handler/dv/env/seq_lib/alert_handler_common_vseq.sv
This assertion was moved from an FPV file to the design itself in commit a4ad7a84c9b. The assertion is true (it's even provable!) in an FPV setting, but isn't true if you start forcing variables. Disable it for FI tests accordingly.
Fixes #22854.
> [alert_handler,dv] Disable an assertion that breaks for FI tests

- rules/manifest.bzl
- rules/opentitan/cc.bzl
- rules/signing.bzl
- sw/device/silicon_creator/lib/manifest.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/defs.bzl
- sw/device/silicon_creator/rom_ext/proda/BUILD
- sw/device/silicon_creator/rom_ext/prodc/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/device/silicon_creator/rom_ext/sival/BUILD
- sw/host/opentitanlib/src/image/manifest.rs
- sw/host/opentitanlib/src/image/manifest_ext.rs
- sw/host/opentitanlib/src/image/testdata/manifest_ext.hjson
- sw/host/opentitantool/src/command/image.rs
1. When the security version of the just-booted ROM_EXT is greater than the ROM_EXT minimum security version in boot data, move the value forward.
2. Provide a mechanism in the manifest to prevent moving foward even though the version is newer.  This is to release test ROM_EXTs without running afoul of #22941.
This should NOT be cherry-picked to master.  We will fix this on master by adjusting the selection criteria as discussed in #22941.
> [rom_ext] Advance the security version in boot_data

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/doc/registers.md
- hw/ip/i2c/doc/theory_of_operation.md
- hw/ip/i2c/dv/env/seq_lib/i2c_glitch_vseq.sv
- hw/ip/i2c/i2c.core
- hw/ip/i2c/rtl/i2c_bus_monitor.sv
- hw/ip/i2c/rtl/i2c_controller_fsm.sv
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
- hw/ip/i2c/rtl/i2c_target_fsm.sv
- sw/device/lib/dif/dif_i2c.c
- sw/device/lib/dif/dif_i2c.h
- sw/device/lib/dif/dif_i2c_unittest.cc
- sw/device/tests/i2c_target_smbus_arp_test.c
- sw/device/tests/pmod/i2c_host_clock_stretching_test.c
- util/reggen/gen_cheader.py
Prepare for multi-controller functionality by creating a bus monitor that tracks transaction boundaries, detects Start and Stop symbols, and provides clock timeout functions. Move "bus free" detection to the bus monitor, and block the controller FSM from beginning transmissions unless the bus monitor gives the OK.
Add an optional SMBus bus timeout, which checks if SCL is held low for too long, and make it mux with the target stretch timeout, since it doesn't make much sense for them to both be active. In the general bus timeout case, it doesn't matter which entity is pulling SCL low. In the target stretch timeout case, the controller's contribution to SCL low time is ignored.
Add a control bit for selecting between single-controller and multi-controller monitoring mode. For the …
> [i2c] Consolidate transaction boundary tracking in a bus monitor

- hw/ip/keymgr/doc/theory_of_operation.md
- hw/ip/keymgr/dv/env/keymgr_env_pkg.sv
- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_sideload_protect_vseq.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/keymgr_testutils.h
- sw/device/tests/entropy_src_edn_reqs_test.c
Prior to this PR, keymgr could be initialized and would open itself
to operations even if the Creator Root Key shares provided by OTP in the
`root_key_i` input were invalid (although keymgr did write all-zeros and
all-ones instead of the input from OTP into its key shares if that was
the case).  However, the specification dictates that kemygr must signal
an invalid operation, though it did not specify the next state.
This PR fixes the problem by letting keymgr raise an *invalid
operation* error in this case and then transition to the terminal
Invalid state (going through a wipe state to clear any secrets with
entropy).  The rationale for this implementation is that the Creator
Root Key is meant to be static after reset, so SW doesn't have to be
able to retry the initialization.  Letting …
> [keymgr] Abort into Invalid when Creator Root Key is not valid during initialization

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/dice.c
- sw/device/silicon_creator/lib/dice.h
- sw/device/silicon_creator/lib/drivers/keymgr.c
- sw/device/silicon_creator/lib/drivers/keymgr.h
- sw/device/silicon_creator/lib/drivers/keymgr_unittest.cc
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/otbn_boot_services.c
- sw/device/silicon_creator/lib/otbn_boot_services.h
- sw/device/silicon_creator/lib/otbn_boot_services_functest.c
- sw/device/silicon_creator/manuf/lib/personalize_functest.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize_3.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/opentitanlib/src/test_utils/lc.rs
- sw/host/tests/manuf/personalize_functest/src/main.rs
See #22837 and #22810  for details.
This was split off from #22907 due to CI issues.
> [cherry-pick] #22837 and #22810 to `earlgrey_es_sival` branch

- hw/top_earlgrey/BUILD
- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/spi_passthru_test.c
- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
This PR fixes the spi_passthru on silicon and link it to the sival testplan
> [sival, spi] Passthru

- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom/rom_start.S
When waking from sleep, the watchdog IP will not have been reset, so it is not necessary to re-configure it.  In fact, if watchdog REGWEN has been used to disable writes to its registers, attempting to do so can generate an exception causing chip reset, which will reset not only the watchdog, but other IP blocks that the owner code wanted retained across the period of sleep.
> [rom] Avoid touching watchdog config on wake from sleep

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/silicon_creator/rom/e2e/BUILD
1. Configure the sim_dv rom_e2e_somke test to use the opentitan_test target used in FPGA execution enviornments.
2. Update the //sw/device/silicon_creator/rom/e2e:rom_e2e_smoke target to always perform signing, independent of the execution environment. This is so that we can use the regular `sim_dv` target at build time to avoid having to refactor the dvsim makefile.
3. Increase the runtime of the rom_e2e_smoke test as it now takes longer due to the new signing configuration.
This is part of https://github.com/lowRISC/opentitan/issues/22697.
> [dv] Enable rom_e2e_smoke test

- hw/ip/prim/rtl/prim_clock_gp_mux2.sv
Happened to see this bit of code that looks like a typo.
Not sure about SystemVerilog, but in C this loop would never terminate. Better safe than sorry.
> [prim] Fix typo'd loop increment

- sw/device/silicon_creator/rom_ext/rom_ext.c
During bring-up and debug, having the ROM_EXT print fault information is very helpful.
> [rom_ext] Print fault info in the exception handler

- sw/host/opentitanlib/src/transport/errors.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/hyperdebug/uart.rs
- sw/host/opentitanlib/src/util/usb.rs
- third_party/hyperdebug/repos.bzl
Rather than repeatedly reading until timeout, use a new USB control request to make HyperDebug drop any UART data buffered in its memory.
We still need to repeatedly read, though, since data could also be buffered in the host operating system or libraries.
Also this PR contains a few more cleanups and improvements to the HyperDebug backend driver.
Includes below HyperDebug firmware change and others:
https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5468408
> [opentitantool] Better way of clearing HyperDebug UART buffers

- hw/ip/prim/prim_diff_decode.core
- hw/ip/prim/rtl/prim_diff_decode.sv
The differential `diff_pi` and `diff_ni` should not have equal values; otherwise a signal integrity issue exists.  Such issues can be detected with an XNOR.  Prior to this commit, this was implemented with behavioral RTL code, which could allow some synthesis tools to perform undesired optimizations for the complementary differential signals.
This PR changes the implementation to a `prim_xnor2` instance, so that synthesis tools cannot change that logic.
I ran all TLTs that have `alert` in their name (`util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_{alert_test,alert_handler_{escalation,ping_timeout,reverse_ping_in_deep_sleep,lpg_sleep_mode_alerts,lpg_sleep_mode_pings,lpg_clkoff,lpg_reset_toggle,entropy},sensor_ctrl_alert,pwrmgr_sleep_sensor_ctrl_alert_wakeup,flash_cras …
> [prim_diff_decode] Use `prim_xnor2` to detect integrity issue

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/cert.c
- sw/device/silicon_creator/lib/cert/cert.h
- sw/device/silicon_creator/lib/cert/cert_unittest.cc
- sw/device/silicon_creator/lib/dice.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
This fixes #22921, including errors in the byte ordering of certificate serial numbers, and how they are checked during ROM_EXT execution to detemine if the certificate needs to be updated.
Additionally, this adds some unit tests to test corner cases in the certificate serial number validity checking mechanism.
> [rom_ext] fix certificate validity check

- rules/opentitan/defs.bzl
- rules/opentitan/fpga_cw310.bzl
- rules/opentitan/silicon.bzl
- rules/opentitan/sim_dv.bzl
- rules/opentitan/sim_verilator.bzl
- sw/device/tests/BUILD
- sw/device/tests/entropy_src_edn_reqs_test.c
Manual backport of #22579 due to a minor conflict in the BUILD file.
> Backport fix entropy src edn req

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/doc/registers.md
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
- hw/ip/i2c/rtl/i2c_target_fsm.sv
- sw/device/lib/dif/dif_i2c.c
- sw/device/lib/dif/dif_i2c.h
- sw/device/lib/dif/dif_i2c_unittest.cc
- sw/device/tests/i2c_target_smbus_arp_test.c
Change target FSM's stretch timeout to count across an entire transaction, for SMBus support.
Add a CSR to report fault events that occurred during a read, and gate
the next read (stretch clock at the first bit) until the event latch is
cleared. This is for reads to this IP's target module.
The gate helps prevent stale data from emerging from the FIFO.
Also roll in some of the functionality the TXRST_ON_COND CSR was meant
to provide, and make this a catch-all gate for releasing the TX FIFO on
a read instead. The prior mechanism had some corner cases that produced
races with software, such as software being able to inadvertently write
a new (yet stale) byte of data after the clear yet before being notified
that the command completed. The separate gating CSR helps avoid such
races by not …
> [i2c] Add target FSM responses to timeouts and read commands

- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/doc/registers.md
- hw/ip/csrng/doc/theory_of_operation.md
- hw/ip/csrng/dv/env/csrng_env_pkg.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
- hw/ip/csrng/rtl/csrng_cmd_stage.sv
- hw/ip/csrng/rtl/csrng_core.sv
- hw/ip/csrng/rtl/csrng_main_sm.sv
- hw/ip/csrng/rtl/csrng_reg_pkg.sv
- hw/ip/csrng/rtl/csrng_reg_top.sv
- sw/device/lib/dif/dif_csrng.h
Please see the commit message for a description.
I ran a regression with 0.1 multiplier and a few more tests than usual are failing (~5 more than expected).
I didn't have time to debug all of them but I think this PR is ready to at least be looked at.
depends on #22883
> [csrng/rtl] csrng move cmd checks into the cmd stage

- hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_disable_auto_req_mode_vseq.sv
This PR fixes the deadlock issue in edn_disable_auto_req_mode mentioned in [#20818](https://github.com/lowRISC/opentitan/issues/20818).
Please see the commit message for a detailed explanation of the issue at hand.
> [edn/dv] Fix the deadlock in edn_disable_auto_req_mode

- sw/device/lib/base/macros.h
- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/lib/cert/tpm_cik.hjson
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/device/silicon_creator/lib/dice.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
This cleans up the DICE/TPM certificate sizes and fixes a small bug in the TPM CIK certificate's subject country string. This is in preparation for combining the DICE certs into a single flash info page.
> [manuf] cleanup cert sizes and fix slight bug

- apt-requirements.txt
- sw/device/silicon_creator/manuf/keys/fake/BUILD
- sw/device/silicon_creator/manuf/provisioning_inputs.bzl
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/ft_lib/BUILD
- sw/host/provisioning/ft_lib/src/lib.rs
This patch adds generated x509 certificate validation using the 'openssl verify...' command.
The CA certificate file name is currently hardcoded to point the the fake CA prepared earlier.
Unit test included in this patch succeeds:
$ bazel test  //sw/host/provisioning/ft_lib:openssl_verify
> [provisioning] add x509 chain validation

- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
This PR makes the teacup config for SPI TPM exactly the same as the CW310.
Testing:
```
bazel test  --//signing:token=//signing/tokens:cloud_kms_sival \
//sw/device/tests:spi_device_tpm_tx_rx_test_silicon_owner_sival_rom_ext
```
> [Sival, spi] Fix TPM test on teacup boad.

- sw/device/silicon_creator/rom_ext/rom_ext.c
If a DICE certificate must be updated, the entire page must be erased before writing, since flash bits can only transition from 1 --> 0.
> [rom_ext] fix cert update

- sw/device/tests/pmod/i2c_host_clock_stretching_test.c
It seems that reading entropy via rv_core_ibex is slower o silicon than on the FPGA.
@vogelpi
> [Sival, i2c] Fix clock stretching on Silicon

- hw/ip/prim/rtl/prim_esc_receiver.sv
This waives some cover properties in the prim_count that is instantiated with some "action" inputs hard coded to zero.
> [prim,fpv] Use PossibleActions param in prim_esc_receiver

- hw/ip/prim/rtl/prim_esc_receiver.sv
The code in prim_esc_receiver tells the instantiated prim_count to increment the counter unless the value is '1. But prim_count is already designed to saturate, so there's no need to condition incr_en_i like this.
Found by an unreachable cover property when running FPV tests.
> [prim,rtl] Avoid unnecessary check in prim_esc_receiver.sv

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_data_toggle_restore_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Add a test sequence for the additional Data Toggle restore functionality.
This sequence first performs some basic tests using the CSR interface and then brings up the USB connection and tests their interaction with the USB traffic.
Note that the data toggles may safely be changed between packets in the DV environment because the USB traffic is controlled. For active endpoints on a live system they must be modified only under very specific conditions such as halt or reset.
> [dv,usbdev] Data toggle restore sequence

- sw/host/provisioning/cp/BUILD
- sw/host/provisioning/ft/BUILD
- sw/host/provisioning/orchestrator/orchestrator.py
- sw/host/provisioning/orchestrator/ot_device.py
This fixes the provisioning orchestrator script and the CP/FT host binary build rules that was triggering errors at run time.
Signed-off-by: Tim Trippel <ttrippel@google.com>
(cherry picked from commit 2db5df6c7cf9a466c19e743d164f6174655e67ec)
> [cherry-pick] #23012: fix provisioning orchistrator

- hw/top_earlgrey/data/ip/chip_adc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aon_timer_testplan.hjson
- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_csrng_testplan.hjson
- hw/top_earlgrey/data/ip/chip_edn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson
- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson
- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otp_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rom_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_timer_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_uart_testplan.hjson
- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
Remove the suffix  `chip_` from ip_block name on testplans for consistency
> [sival] Refactor testplans for consistency

- rules/signing.bzl
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/defs.bzl
- sw/device/silicon_creator/rom_ext/prodc/BUILD
- sw/device/silicon_creator/rom_ext/sival/BUILD
This is a manual cherry-pick of #22949 and #23009 to master.
1. Corrects a bug in `dict` handling when signing.
2. Applies a version number to the per-product ROM_EXT manifests.
> Cherry-pick to master: [rom_ext] Set the ROM_EXT version number

- sw/device/lib/dif/dif_alert_handler.c
- sw/device/lib/dif/dif_alert_handler.h
A state indicating an fsm error was added about 3 years ago, but apparently the dif code was not updated, and the code would flag an error if it ever hits that state. This state indicates some tampering.
> [dif,alert_handler] Fix dif_alert_handler_get_class_state

- quality/BUILD.bazel
- sw/device/silicon_owner/tock/tests/uart/BUILD
- sw/device/silicon_owner/tock/tests/uart/src/main.rs
- sw/host/tests/tock/uart/BUILD
- sw/host/tests/tock/uart/src/main.rs
This test the ability of a Tock app to perform console writes and reads over the UART. It is an integration tests that tests the Console syscall driver, the UART virtualizer, and the UART peripheral driver.
> [tock] Add Tock UART tests.

- sw/device/tests/BUILD
These tests are all working in ROM_EXT on master and earlgrey_es_sival now that we've fixed the underlying keymgr issue. For details, see
https://github.com/lowRISC/opentitan/issues/22819#issuecomment-2095648654
This is related to lowRISC/OpenTitan#21706 and lowRISC/OpenTitan#22140.
> [sival] Mark fixed entropy complex tests as unbroken in ROM_EXT

- hw/ip/rv_dm/dv/env/rv_dm_env.sv
- hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
- hw/ip/rv_dm/dv/tb.sv
This PR depends on #22591 (no real impact, but they are touching related lines and rebasing is annoying!). The second commit is the only one that's special to this PR and can reviewed on its own. The other PR should be merged first.
The commit that's unique to this PR just makes an extra clock/reset interface to drive the signals and wires it up to the block.
> [rv_dm,dv] Connect rst_lc_ni in tb.sv

- hw/top_earlgrey/data/chip_conn_testplan.hjson
- hw/top_earlgrey/data/ip/chip_csrng_testplan.hjson
- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
This is a backport PR of https://github.com/lowRISC/opentitan/pull/23015
There was a conflict on the file `chip_entropy_src_testplan.hjson`
> Backport [sival] Mark test that can't run on silicon as NA

- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/lib/testing/BUILD
- sw/device/lib/testing/usb_logging.c
- sw/device/lib/testing/usb_logging.h
- sw/device/tests/BUILD
- sw/device/tests/usbdev_aon_pullup_test.c
- sw/device/tests/usbdev_config_host_test.c
- sw/device/tests/usbdev_logging_test.c
Manual backport for several usbdev commits, replaces #21671 that was closed
> Cherry pick usb

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
The test was moved from sw/device/tests/sim_dv to sw/device/tests and the hjson hasn't been updated.
> [dv] fix chip_sw_flash_ctrl_write_clear bazel target

- sw/device/tests/BUILD
- sw/device/tests/sram_ctrl_execution_test.c
This test was failing in `ROM_EXT` environments because the ROM_EXT sets the `MMWP` bit in ePMP.
This changes the behaviour for unconfigured ePMP regions from them being ignored (everything allowed) to blocked (everything disallowed).
The test was removing configurations including seemingly for the region that the test was running out of flash from. This caused Ibex to just stop in the middle of the test.
This PR changes this part of the test to change to configuration of the actual region we care about and leave the others alone.
> [sival,sram_ctrl] Fix SRAM execution test in ROM_EXT environments

- hw/top_earlgrey/BUILD
- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/spi_passthru_test.c
- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
This is a backport PR of https://github.com/lowRISC/opentitan/pull/21348#issuecomment-2094051293 to master.
There was a conflict on the bazel BUILD file.
> Backport [sival, spi] Passthru

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv
- sw/device/tests/sram_ctrl_scrambled_access_test.c
Previously the code preserved both the `pattern` and `backdoor` fields when we scramble main SRAM. The `pattern` field is the one that we expect to be scrambled and trigger ECC errors. In DV-sim environments the `backdoor` field is magically corrected so that it's scrambled with the new key and thus doesn't trigger ECC errors.
This of course does not (and cannot) happen outside of DV sim, so the number of ECC errors was doubled.
Fixed by changing the layout of `scramble_test_frame` so that we can skip copying the `backdoor` field outside of DV-sim.
If this description makes no sense, let me know and I'll try fix up the explanation better.
> [sival,sram_ctrl] Fix scrambled_access ECC error counts

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
The pass rate for this vseq is not brilliant. These commits make it somewhat better (but definitely still not 100%). Before the changes, the pass rate was roughly 75%. With them, I've just run 50 seeds and got a pass rate of 94%.
A full fix for this test will be a bit fiddly. For example, the operation it chooses might be "Inject an error when OTBN is writing to a flag register". But that's going to be difficult if the randomly generated binary doesn't actually write to a flag register...
I suspect that a "full" solution will involve generating a known-good binary and then running two binaries back-to-back: a random one, followed by the binary that we know does all the operations we might want to interrupt. But that's definitely more difficult than just tweaking some wait times, so let's …
> [otbn,dv] Improve error rate in `otbn_ctrl_redun_vseq`

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
The wait_lc_status() task does a DMI read over JTAG to figure out the current state of lc_ctrl. This requires pinmux to route the JTAG signals to LC_CTRL and things get rather confused if we run this task before the routing has happened.
In normal use, the JTAG driver will send an IR command to switch address to the DMI address. Then it will send a DR command to do the DMI read/write. On the next DMI command, it can avoid the silly extra IR command because it knows we're already pointing at the DMI address.
Of course, this doesn't work if the JTAG signals got squashed. In that case, it will not know that IR hasn't changed, so it will send repeated DR commands expecting to see a particular lc_ctrl status come out. But that won't happen because we're not actually looking at the DMI register …
> [chip,dv] Wait for JTAG connection in chip_sw_base_vseq

- hw/dv/sv/csr_utils/csr_seq_lib.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This PR has two commits. The first just makes some debug prints a bit more helpful. The second (the point of the PR) has the following commit message:
This test is sometimes timing out. The reason is that I tweaked the
DMI driver to deal more gracefully with JTAG frequencies much higher
than the clock frequency. The (usually overly careful) code we ended
up with is a bit slower and we take more than 50ns to run through the
whole list with some seeds.
Double the time available. The simulation that was timing out still
runs in only 3m20s on my laptop so I'm not really concerned about
total time.
> [rv_dm,dv] Double timeout for rv_dm_jtag_dmi_csr_bit_bash

- hw/ip_templates/flash_ctrl/dv/env/flash_otf_item.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_otf_item.sv
These checks can never fail because region has a type that can never be null. Xcelium then fails to compile the code, pointing out that the types don't make sense.
Remove the dead code.
> [flash_ctrl,dv] Remove bogus checks from flash_otf_item.sv

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv
These macros are used to construct paths for asserton/assertoff macros that were added in f541c61. I believe that a prefix was missing from the name (and Xcelium rejects the code at compile time).
> [flash_ctrl,dv] Correct macro names in flash_ctrl_phy_arb_redun_vseq

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_idle_hint_vseq.sv
This seems less complicated than the code that was there before, which had compiled the various DMI operations into their underlying JTAG writes without comments. Undoing this means I'm getting steadily better with a hex calculator...
There shouldn't be any functional change here, except that we're now using the DMI frontdoor driver, which is probably a bit more robust than what was there before.
Rather confusingly, this is somewhat reverting the change that landed in this file as fde2e0c. That change had an identical commit message to the previous change to the file and there wasn't really a proper discussion on the pull request (#20349). I'm not entirely sure why Basit thought that change was required, but I propose to undo things and revisit it if necessary.
This test should get the …
> [rv_dm,dv] Rewrite dtm_idle_hint_vseq to use DMI helpers

- sw/host/tests/rom/e2e_bootstrap_rma/src/main.rs
There was an assert checking that the LC controller's status was `INITIALIZED`. This failed if the status was `INITIALIZED | READY`.
Changed to use the `wait_for_status` function which allows unions and also has retries built in.
> [test] Make e2e_bootstrap_rma test more resilient

- hw/dv/sv/jtag_agent/jtag_driver.sv
- hw/dv/sv/jtag_agent/jtag_if.sv
- hw/dv/sv/jtag_agent/jtag_item.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_tap_fsm_vseq.sv
The main impetus for this came from trying to sort out an rv_dm test which was failing because of incorrect use of a clocking block (see "Remove use of HOST_CB clocking block"), but I spent a while looking at the rather complicated code and trying to tidy it up a bit.
The commit described above should be the only one that changes behaviour (and it changes it for the better!). The others should all be tidyups that make the code clearer without changing behaviour.
> [jtag,dv] Lots of tidyups in jtag_driver.sv

- hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/sram_ctrl_lc_escalation_test.c
- sw/host/tests/chip/sram_ctrl/BUILD
- sw/host/tests/chip/sram_ctrl/src/sram_ctrl_lc_escalation.rs
This test:
1. Reads and writes to main and retention SRAMs from ibex and through the debug module.
2. Triggers a lifecycle controller bus integrity error alert which is configured to escalate to locking the SRAMs.
3. Tries to read and write the SRAMs through the debug module again which should fail.
4. Resets the chip.
5. Tries to read and write the SRAMs again which should pass.
We can't check that the SRAMs lock up from within ibex because ibex also locks up at the same escalation level.
Instead, I have moved the test from the PROD to RMA lifecycle state and tried to access the SRAMs through the debug module.
There's a chance for a false positive with this test where actually the debug module (or something else) locks up / breaks during the escalation and not the SRAMs. I can't think of …
> [sival] Add `sram_ctrl_lc_escalation` test

- sw/device/lib/crypto/impl/ecc/ecdh_p384.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_keygen.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_sign.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_sign.h
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_verify.c
- sw/device/lib/crypto/impl/ecc/p384_curve_point_valid.c
- sw/device/lib/crypto/impl/ecc/p384_curve_point_valid.h
- sw/device/sca/ecc384_serial.c
- sw/otbn/crypto/p384_base_mult.s
- sw/otbn/crypto/p384_curve_point_valid.s
- sw/otbn/crypto/p384_ecdh.s
- sw/otbn/crypto/p384_ecdsa_keygen.s
- sw/otbn/crypto/p384_ecdsa_sca.s
- sw/otbn/crypto/p384_ecdsa_sign.s
- sw/otbn/crypto/p384_ecdsa_verify.s
- sw/otbn/crypto/p384_internal_mult.s
- sw/otbn/crypto/p384_isoncurve.s
- sw/otbn/crypto/p384_keygen.s
- sw/otbn/crypto/p384_scalar_mult.s
- sw/otbn/crypto/p384_sign.s
- sw/otbn/crypto/p384_verify.s
- sw/otbn/crypto/tests/p384_base_mult_test.s
- sw/otbn/crypto/tests/p384_curve_point_valid_test.s
- sw/otbn/crypto/tests/p384_ecdh_shared_key_test.s
- sw/otbn/crypto/tests/p384_ecdsa_sign_test.s
- sw/otbn/crypto/tests/p384_ecdsa_verify_test.s
- sw/otbn/crypto/tests/p384_isoncurve_test.s
- sw/otbn/crypto/tests/p384_keygen_test.s
- sw/otbn/crypto/tests/p384_scalar_mult_test.s
This PR removes `dptr_<x>` variables and adapts the code to function without it.
Previously, to reference a value in the data memory, the memory address of the value was stored in addition to the actual value. 
However, this is not absolutely necessary to reference values in the data memory. It is also possible to do this without extra pointer variables. 
This means that instead of storing the pointer (i.e. the memory address of the value) in the data memory, the pointer is only used in registers without writing it to the data memory. 
This reduces the number of instructions required in the code and therefore saves instruction and data memory.
> [crypto] Change P-384 Pointer Handling

- hw/dv/sv/csrng_agent/csrng_monitor.sv
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_alert_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
This PR adds some basic DV for the recently added status response changes.
For further information check out the individual commit messages.
This PR depends on #22906.
I ran 10% of a full regression multiple times and around 9 tests fail consistently.
None of them are alert tests, but some of the tests that fail don't fail before my changes.
I would have to do some further debugging to get back to the baseline number of failures.
However, I decided to create this PR anyways such that I can move on to some more urgent tasks.
> [csrng/dv] Add DV for the command status responses

- hw/ip/spi_host/rtl/spi_host_command_queue.sv
Eliminate First Word Fallthrough for the command queue. It was concatenating the bus-write-to-CSR path with the SPI-command-to-I/O-port path, creating an unnecessarily long path for timing.
> [spi_host] Disable FWFT for the command queue

- sw/device/lib/testing/BUILD
- sw/device/lib/testing/spi_host_testutils.c
- sw/device/lib/testing/spi_host_testutils.h
- sw/device/tests/pmod/spi_host_gigadevice1Gb_flash_test.c
- sw/device/tests/pmod/spi_host_gigadevice256Mb_flash_test.c
- sw/device/tests/pmod/spi_host_macronix_flash_test.c
- sw/device/tests/pmod/spi_host_micron512Mb_flash_test.c
- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
This commit fixes the PMOD tests on teacup board.
The teacup board has the SPI_HOST1 sd0 and sd1 pins inverted, so this PR adds a different mapping to work around this problem.
> [Sival, spi host] Fix PMOD pin mapping for teacup board.

- sw/device/tests/pmod/i2c_host_fram_test.c
This is possible due to some RTL fixes on i2c block, tracked in #18958
> [sival, i2c] Rise the expected performance of the i2c host

- sw/host/sphincsplus/BUILD
- sw/host/sphincsplus/lib.rs
- third_party/sphincsplus/BUILD.sphincsplus.bazel
- third_party/sphincsplus/repos.bzl
Follow-up to #22953 
Background: the existing SPHNICS+ crate that `opentitantool` relies on does not support the `consistent_basew` update to the algorithm in the newest NIST draft standard that is planned for earlgrey prod.
This issue was discussed in the Software WG, and the consensus was that we would develop our own SPHINCS+ crate that imports the correct version of the SPHINCS+ C code.
This PR adds a bazel toolchain to fetch the correct branch of the SPHINCS+ repository (which unfortunately does not have a release, so we fall back to using the `bare_repository` bazel rule). From there, `rules_rust` provides some nice tooling to import the Rust library generated by the `bindgen` tool into our code.
> [deps/crypto] add skeleton code for self-hosted SPHINCS+ library

- hw/ip/rv_dm/dv/env/rv_dm_if.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/tb.sv
This builds on top of #22594 (which should be reviewed and merged first). Only the final commit is unique to this PR. Its commit message is:
*[rv_dm,dv] Expose new ports in rv_dm_if*
This change shouldn't cause any change to behaviour, but it's
connecting up the ports separately in tb.sv so that they can be
controlled by vseqs.
The logic that wires everything together (and the TODO comment) have
now been moved to the base vseq.
> [rv_dm,dv] Expose new ports in rv_dm_if

- hw/ip/edn/dv/env/seq_lib/edn_err_vseq.sv
- hw/ip/edn/rtl/edn_core.sv
- hw/ip/edn/rtl/edn_main_sm.sv
This PR contains two commits that help improving FSM coverage:
1. [[edn/rtl] Make Error main SM state terminal again](https://github.com/lowRISC/opentitan/commit/3d8c6e0e34f2d6fc77f0db4ab6dc616558d45fe9): This is actually a security-relevant bug fix. Previously, the hardware could be made to leave the terminal error state upon receiving an error status signal from CSRNG.
2. [[edn/dv] Fix FSM coverage hole](https://github.com/lowRISC/opentitan/commit/6021c33c18e6061c54381595539358c21b7de62d): There were some systematic coverage holes in the err_test of EDN DV. This commit fixes those.
A third commit has been appended to fix Verilator lint warnings and errors.
> [edn] Improve FSM coverage

- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv
Previously, keymgr would keep updating and reseeding the PRNG forever once entering the StCtrlDisabled or StCtrlInvalid state. This is not ideal from an entropy and power consumption viewpoint.
This commit changes the design to - once one of the two states is entered - to keep updating the PRNG (which also triggers the reseed operation) until two more PRNG reseed operation have happened.
This resolves lowRISC/OpenTitan#22997.
FYI, once in the Invalid or Disabled state and after having stopped PRNG update requests inside the main controller, it's still possible that the PRNG is advanced and that reseed operations are started. E.g. if there are still some handshakes on the KMAC app interface or on the sideload ports (see figure below). However, once in the Disabled state, those are not …
> [keymgr] Don't update and reseed PRNG in Disabled/Invalid state forever

- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/sival/BUILD
The current SRAM program can be executed in prod as a normal test.
The same program can be used for both cases with #22834.
> [sival, rv_core_ibex] test rv_core_ibex_isa_test in prod

- hw/top_earlgrey/data/chip_testplan.hjson
- sw/device/tests/BUILD
- sw/host/tests/chip/rv_dm/src/jtag_tap_sel.rs
This test now tests PROD states and check in RMA state the tap is continuously sampled. This makes it cover chip_sw_tap_strap_sampling test.
> [sival, rv_dm] improve jtag_tap_sel to support multiple lc states

- sw/device/tests/BUILD
This test was missing its test harness in the silicon env.
Also added the rest of the `EARLGREY_TEST_ENVS` since it seems to work in `fpga_cw310_sival_rom_ext` now and unmarking as broken.
Semi-related: https://github.com/lowRISC/opentitan/issues/23051 - the test seems to be broken in DV. Maybe the UVM harness is out of date.
> [sival,pwrmgr] Add test harness for pwrmgr_deep_sleep_all_reset_reqs

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv
keymgr_key_derivation TLT is running 30+ mins. The issue is the typo in the assertion name I think @andreaskurth.
```
/workspaces/repo> ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_keymgr_key_derivation --fixed-seed 1 --waves fsdb
INFO: [dvsim] [proj_root]: /workspaces/repo
INFO: [SimCfg] [scratch_path]: [chip] [/workspaces/repo/scratch/keymgr_reorg_cnsts/chip_earlgrey_asic-sim-vcs]
ERROR: [Regression] Test "chip_plic_all_irqs" added to regression "xcelium_ci_0" not found!
ERROR: [Regression] Test "chip_sw_aes_force_prng_reseed" added to regression "V2" not found!
ERROR: [Regression] Test "chip_plic_all_irqs" added to regression "V2" not found!
ERROR: [Regression] Test "chip_sw_aes_prng_reseed" added to regression "V2" not found!
ERROR: [Regression] Test …
```
> [keymgr, dv] Fix a typo in keymgr seq

- hw/dv/sv/usb20_agent/usb20_agent_cfg.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_bitstuff_err_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_disconnected_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_endpoint_access_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_in_err_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_suspend_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_out_iso_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_config_eop_single_bit_handling_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_rx_crc_err_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR collects all of the changes in the following PRs from the original authors (@MubashirSaleem775, @Saad22386) and modifies them where necessary for inclusion in the current DV environment in the push towards the V2 milestone.
- #21928 - Out iso - Modify comment - modified comments and dropped broken bus state check
- #22376 - rx_crc_err - integrated with modifications to reduce code replication
- #22379 - usbdev_disconnected - small modifications and integrated
- #22422 - integrated with minor updates
- #22442 - usbdev_endpoint_access - simple sequence, integrated with minor fixups
- #22461 - usbdev_link_suspend - integrated with changes for readability
- #22725 - usbdev_bitstuff_err - integrated with a couple of functional fixes and extended significantly to guarantee that a bit …
> USBDEV DV changes and additional sequences

- .bazelrc
- sw/device/silicon_creator/manuf/keys/fake/BUILD
- sw/device/silicon_creator/manuf/keys/fake/gen_fake_ca.sh
- sw/device/silicon_creator/manuf/provisioning_inputs.bzl
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/ft_lib/BUILD
- sw/host/provisioning/ft_lib/src/lib.rs
the first patch of the two patchsets of this PR was submitted as a separate PR (https://github.com/lowRISC/opentitan/pull/23066)  and will be updated here if the review of 23066 calls for modifications.
The second patch implements support of two modes of certificate signing, either using a local private key (test mode), or a key stored in Google Cloud KMS (ckms). Signing mode is picked based on which key parameter is passed to the signing utility.
Testing of both modes is supported, by default local key mode is used, adding `--define  cert_signer=cloud_kms` to test invocation will trigger testing the Cloud KMS based signign.
> Certificate signing with Google Cloud KMS

- quality/BUILD.bazel
- sw/host/sphincsplus/BUILD
- sw/host/sphincsplus/lib.rs
Builds on the bindgen library from https://github.com/lowRISC/opentitan/pull/23049 to create more Rust-friendly wrappers for the C functions and a few quick tests.
Next steps: integrate this wrapper with the host-side SPHINCS+ code under `opentitanlib`, remove the `pqcrypto` dependency, and finally unblock https://github.com/lowRISC/opentitan/pull/22953
> [host] Write Rust library wrapper for SPHINCS+ implementation.

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
This was using the lc_hw_debug_en signal (which controls whether the debugger actually does anything), but we should have been using the pinmux_hw_debug_en, which controls whether DMI access is enabled.
This fixes the rv_dm_jtag_dmi_debug_disabled test, which was failing because... DMI wasn't disabled! Oops :-)
> [rv_dm,dv] Drive correct enable signal in dmi_disabled vseq

- sw/device/silicon_creator/lib/attestation.h
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/otbn_boot_services.c
- sw/device/silicon_creator/lib/otbn_boot_services.h
- sw/device/silicon_creator/lib/otbn_boot_services_functest.c
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/ecdsa.c
- sw/device/silicon_creator/lib/ownership/ecdsa.h
- sw/device/silicon_creator/lib/ownership/ecdsa_functest.c
- sw/device/silicon_creator/lib/sigverify/rsa_verify.c
- sw/device/silicon_creator/lib/sigverify/rsa_verify.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/otbn/crypto/BUILD
- sw/otbn/crypto/boot.s
- sw/otbn/crypto/p256_base.s
Since we are planning to do away with RSA signatures in favor of ECDSA signatures, we can use Ibex for RSA verification until we fully eliminate the use of RSA.  This important temporary measure allows us to bring the full ECDSA OTBN program into the ROM_EXT and use it for ECDSA verification of ownership transfer operations.
1. Switch RSA sigverify of the owner application firmware over to Ibex-based verification.
2. Cherry-pick jadephilipoom's OTBN P-256 implementation.
3. Use the OTBN implementation for ownership-related verification, thus eliminating CryptoC and saving 12K of flash space.
> [rom_ext] Use Ibex for RSA sigverify

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
This fixes failures for the occasional seed in the rv_dm_jtag_dmi_debug_disabled test. Those failures also cause lots of failures in the rv_dm_stress_all test, which it also fixes.
> [rv_dm,dv] Add missing waits to rv_dm_jtag_dmi_debug_disabled_vseq

- util/dvsim/LocalLauncher.py
- util/dvsim/SgeLauncher.py
Delete the redefinitions in the two subclasses of Launcher.py to ensure the attribute max_odirs given by args of DVSim been correctly passed to clean_odirs() function.
Related to https://github.com/lowRISC/opentitan/issues/23093#issuecomment-2110826639
> Launcher Modification

- hw/dv/sv/jtag_agent/jtag_driver.sv
No functional change, but this should make it a bit more obvious that these aren't control knobs to twiddle.
This is to follow up on a comment that @hcallahan-lowrisc left when reviewing #23002.
Only the final commit is really part of this PR, but the lines conflict with changes from #23081, so I'm pushing it after the relevant commits from that PR and that should be merged here. Only the last commit needs reviewing in this PR.
> [jtag,dv] Mark driver internal state variables as protected

- sw/device/tests/BUILD
These tests were missing a harness to enable vbus sensing which caused the test to fail.
> [usbdev,sival] Fix config_host and aon_pullup on silicon

- sw/device/silicon_creator/lib/boot_log.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
1. Add `min_sec_ver` fields to the `boot_log` structure.
2. Initialize the minimum security versions to the values contained in the `boot_data` structure.
> [rom_ext] Communicate minimum security version in the boot_log

- sw/device/lib/runtime/pmp.c
- sw/device/lib/runtime/pmp.h
- sw/device/tests/BUILD
- sw/device/tests/pmp_smoketest_napot.c
- sw/device/tests/pmp_smoketest_tor.c
Instead of unlocking all address space by unsetting all PMP registers, these tests only need 1 or 2 spare PMP regions. Choose regions 6/7 for this purpose. A test is added to ensure that these regions are not configured.
> [sival] fix pmp_smoketest_{napot, tor} tests in rom_ext

- sw/device/lib/crypto/drivers/entropy.c
This PR contains two commits, the really relevant one changes the entropy driver of cryptolib to also poll the CSRNG command ready bit for additional data. Previously, the command register ready bit was only polled for the additional data when writing commands to the SW register of EDN.
When writing commands to CSRNG instead, not polling the command ready bit could cause CSRNG to drop additional data provided by software while handling a hardware command. Once the hardware command was handled, the software instance would win arbitration and CSRNG would wait for software to provide the dropped additional data, thereby stalling the entire entropy complex. This would happen for example if a HW instance request would collide with a software request. Since the software command FIFO is only 2 …
> [cryptolib] Fix CSRNG driver

- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/device/silicon_creator/lib/dice.c
This measurement is not relevant to the overall identity of the device. Moreover, the device ID (which is part of the HW_CFG partition) is already mixed into the keyladder.
This reduces the UDS cert size as well.
> [manuf] remove HW_CFG measurement from UDS cert

- signing/README.md
- signing/tokens/BUILD
- sw/device/tests/doc/sival/README.md
Remove the `cloud_kms` token label; use `cloud_kms_sival`.
Fixes: #22428
> [signing] Remove the legacy `cloud_kms` token

- sw/device/silicon_creator/rom/BUILD
Fix a dependency error that was preventing the `clang-tidy` quality check from running.
> [sigverify] Fix dependency error

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/chip_env_cfg.sv
- sw/device/silicon_creator/rom/e2e/BUILD
1. Update Bazel rules to provide targets with the `sim_dv` suffix, which is expected by dvsim.
2. Update chip_env_cfg.sv to support handling of ECDSA labels for signed binaries.
3. Update chip_rom_tests.hjson to work with the new `opentitan_test` and `opentitan_binary` rules.
Fixes: https://github.com/lowRISC/opentitan/issues/22919
Fixes: https://github.com/lowRISC/opentitan/issues/22697
> [dv] Enable ROM e2e test cases for A1

- hw/ip/prim/fpv/vip/prim_fifo_sync_assert_fpv.sv
- hw/ip/prim/rtl/prim_fifo_sync.sv
These shouldn't cause any change in behaviour, but it's nice to silence some of the cruft from the tool (Jasper) as it reads the code.
> [prim,fpv] Fix a couple of silly warnings in prim_fifo_sync

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- sw/device/silicon_creator/rom/e2e/keymgr/BUILD
1. Update keymgr init test to generate signed binaries for all execution environments. Remove opentitan_binary targets as these are no longer compatible with dvsim.
2. Update keymgr init targets in chip_rom_tests.hjson to support opentitan_test artifacts.
> [bazel/dv] Fix rom e2e keymgr tests.

- hw/ip/rv_core_ibex/rtl/rv_core_addr_trans.sv
Previously to this change software had to set the lower bits of the mapping address to 0 otherwise the address translation would produce an incorrect result.
Same fix as https://github.com/lowRISC/opentitan/pull/23178 but on integrated branch
> [rtl,rv_core_ibex] Mask off lower bits of mapping address

- rules/opentitan/defs.bzl
- sw/device/tests/BUILD
- sw/device/tests/usbdev_iso_test.c
- sw/device/tests/usbdev_mixed_test.c
- sw/device/tests/usbdev_stream_test.c
- sw/host/tests/chip/usb/BUILD
- sw/host/tests/chip/usb/usb.rs
- sw/host/tests/chip/usb/usb_harness.rs
- sw/host/tests/chip/usb/usbdev_aon_wake.rs
- sw/host/tests/usbdev/usbdev_stream/stream_test.cc
This PR builds on #22409, it cherry picks the USB harness from the sival branch and extends it so it can run the C++ host streaming code and monitor for success.
At the moment, I had to reduce the number of bytes sent in those tests because they are way too long (5min for each test). @alees24 is that fine or should we find a way to make this configurable? I think for CI it should be sufficient to aim for maybe a 30s test?
Still TODO:
> [usbdev,sival] Enable streaming test

- sw/device/tests/BUILD
Manual backport of #23128
Replaces #23154
> usb aon pullup and host config backport Backport 23128 to master

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/keymgr.c
- sw/device/silicon_creator/lib/drivers/keymgr.h
- sw/device/silicon_creator/lib/drivers/kmac.c
- sw/device/silicon_creator/lib/drivers/kmac.h
- sw/device/silicon_creator/lib/drivers/kmac_functest.c
- sw/device/silicon_creator/lib/error.h
1. Add KMAC256 functionality to the silicon_creator driver.
2. Add NIST test vectors to the functest to ensure the kmac functions produce correct results.
3. Add the capability to select a hardware destination to the `keymgr` driver.
> [rom_ext] Add KMAC256 operations using software and hardware keys

- sw/host/opentitanlib/src/app/config/h1dx_devboard_c2d2.json
Add the ROM_BOOTSTRAP strapping which allows the `bootstrap -p legacy-rescue` operation to work.
Add more information to UART which allows the C2D2 to perform a UART break condition
> [opentitantool] Improvements for C2D2 debugger support

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/keymgr.c
- sw/device/silicon_creator/lib/drivers/keymgr.h
- sw/device/silicon_creator/lib/drivers/kmac.c
- sw/device/silicon_creator/lib/drivers/kmac.h
- sw/device/silicon_creator/lib/drivers/kmac_functest.c
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/mock_ownership_key.cc
- sw/device/silicon_creator/lib/ownership/mock_ownership_key.h
- sw/device/silicon_creator/lib/ownership/ownership_key.c
- sw/device/silicon_creator/lib/ownership/ownership_key.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
In order to bind the owner configuration block to the chip, we seal accepted owner blocks with a keyed KMAC over the contents of the owner block.
1. Add functions to create and check KMAC based seals.
2. Split the attestation keygen function into three functions: one for each of silicon, creator and owner.
3. Call the silicon and creator functions immediately after rom_ext startup.
4. Call the owner function when preparing to boot the owner stage.
Note: This PR depends on #23162; you need only review the last two commits.
> [ownership] Add KMAC-based sealing functions

- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/ecdsa.c
- sw/device/silicon_creator/lib/ownership/ecdsa.h
- sw/device/silicon_creator/lib/ownership/ecdsa_functest.c
- sw/device/silicon_creator/lib/sigverify/rsa_verify.c
- sw/device/silicon_creator/lib/sigverify/rsa_verify.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
This is a manual cherry-pick of #23064 to master.
Since we are planning to do away with RSA signatures in favor of ECDSA signatures, we can use Ibex for RSA verification until we fully eliminate the use of RSA. This important temporary measure allows us to bring the full ECDSA OTBN program into the ROM_EXT and use it for ECDSA verification of ownership transfer operations.
Switch RSA sigverify of the owner application firmware over to Ibex-based verification.
Cherry-pick jadephilipoom's OTBN P-256 implementation.
Use the OTBN implementation for ownership-related verification, thus eliminating CryptoC and saving 12K of flash space.
> Cherry-pick to master: [rom_ext] Use Ibex for RSA sigverify

- hw/top_earlgrey/dv/env/chip_common_pkg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_sigverify_always_a_bad_b_bad_vseq.sv
Update the expected ROM error to `ROM_BFV_BAD_ECDSA_SIGNATURE`.
Fixes: https://github.com/lowRISC/opentitan/issues/22919
> [dv] Fix e2e sigverify_always tests.

- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_data_toggle_restore_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_in_trans_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_setup_trans_ignored_vseq.sv
- hw/ip/usbdev/dv/tb/tb.sv
- hw/ip/usbdev/dv/usbdev_sim.core
This is based on PR #23061 with all but the first two commits being identical at this time, because it requires the usb20_driver changes that supports 'no response' from the DUT, reported as a 'time out.'
The two commits unique to this PR:
1. Instantiate and use the external differential receiver, a la OpenTitan ASIC implementation.
2. Fix the test sequence 'usbdev_setup_trans_ignored' which was previously doing nothing useful, as well as tidying the 'usbdev_in_trans' sequence and introducing some further tasks in the base functions, to be used throughout the remaining sequences in future changes.
The PHY configuration is presently not varied, but the configuration is presented in the same USBDEV register, and the bits being available paves the way for satisfying further test points.
> [dv,usbdev] External diff rcvr at block level, and fix setup_trans_ignored

- hw/ip/otp_ctrl/data/otp_ctrl_base_vseq.sv.tpl
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_otp_ctrl_vendor_test_ecc_error_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/otp_ctrl_vendor_test_ecc_error_test.c
Add a top level test that injects singe and double bit errors in the VENDOR_TEST partition, expecting no error to occur reading the otp_ctrl `STATUS` csr.
Fixes #21265
> [dv,otp_ctrl] Check ECC errors in VENDOR_TEST partition

- hw/ip/hmac/doc/programmers_guide.md
Preivously, it was suggested that KEY registers should be copied by SW as it saves the context. However KEY registers are swaccess=wo type, which means reading them returns 0. Therefore SW *must* keep a copy of the key itself, without relying on this register.
> [hmac, doc] Update HMAC context saving guide

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
Some top-level tests depend on Xcelium to run correctly and have all checks active.  As top-level tests for Earlgrey run in VCS by default, all tests in the `nightly` regression set also run in VCS.  This commit creates a new `xcelium_nightly` regression set so that specific tests can be run in Xcelium during nightly regressions.
> [top_earlgrey/dv] Create regression set for nightly Xcelium runs

- sw/device/silicon_creator/lib/sigverify/rsa_verify.c
- sw/device/silicon_creator/lib/sigverify/rsa_verify.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
On the `master` branch, the ROM loads the OTBN application; the ROM_EXT does not need to.
Fixes #23222.
> [rom_ext] Skip extra OTBN initialization 

- sw/device/tests/BUILD
- sw/device/tests/keymgr_sideload_aes_test.c
Update the test case to call `keymgr_initialize_sival()` only if `kBootStage == kBootStageOwner`. Tested change on silicon and cw310 sival execution environments.
> [sival] Fix keymgr_sideload_aes_test

- check_tool_requirements.core
Newer versions of FuseSoC (at least 2.4) fails to export files that start with ./ in the filename.
> Make check_tool_requirements compatible with newer FuseSoC

- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/sival/BUILD
Cherry-pick of #22876. This also include @HU90m's testplan changes which were not backported.
> Cherry-pick to earlgrey_es_sival: [sival, rv_core_ibex] test rv_core_ibex_isa_test in prod 

- util/fpvgen/fusesoc.core.tpl
Weirdly, I don't think the previous code ever worked! Grepping for dut_name in 9292494f0c5 (where the code was added) doesn't find any other hits.
Fixes #23232.
> [tool,fpvgen] Fix variable in fusesoc.core.tpl

- hw/ip/hmac/README.md
- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/doc/programmers_guide.md
- hw/ip/hmac/doc/registers.md
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- hw/ip/hmac/rtl/hmac.sv
- hw/ip/prim/rtl/prim_sha2.sv
This PR implements scoreboard checks for the new HMAC digest sizes and key lengths for normal operation and whenever secure wiping is triggered.  For ease of DV checks and consistency across configuration changes where previous digests remain held in CSRs until HMAC starts a new operation, this PR also removes the clearing of redundant digest values for the smaller digest sizes in the RTL. It also updates the documentation to clarify that SW should only read the relevant digest CSRs for the digest size configured - @ballifatih (only read digests 0..7 for SHA-2 256 and digests 0..11 for SHA-2 384, i.e., do not assume the redundant digest values in these sizes will be all-zero.)
This should also fix the failing hmac_wipe_secret test (https://github.com/lowRISC/opentitan/issues/23053) and …
> [hmac,dv/rtl] Implement DV checks for new digest sizes/key lengths

- rules/const.bzl
- sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
- sw/device/silicon_creator/rom/e2e/sigverify_key_validity/BUILD
- sw/device/silicon_creator/rom/e2e/sigverify_spx/BUILD
1. Update tests to cover keys in `REVOKED` and `BLANK` states.
2. Add coverage for SPX+ keys, by enabling `sigverify_spx` in mission states. Expect SPX+ disabled in `TEST_UNLOCKED` states.
This is part of: https://github.com/lowRISC/opentitan/issues/21551
> [rom/e2e] Update key_validity tests.

- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/device/silicon_creator/lib/dice.c
This measurement is not relevant to the overall identity of the device. This reduces the UDS cert size as well.
> [manuf] remove HW_CFG1 measurement from UDS cert

- sw/device/silicon_creator/lib/cert/tpm_ek.hjson
This updates the TPM EK cert's subject country field to match the CIK and CEK certs.
> [manuf] fix TPM EK cert subject country

- sw/device/lib/arch/device.h
- sw/device/lib/arch/device_fpga_cw305.c
- sw/device/lib/arch/device_fpga_cw310.c
- sw/device/lib/arch/device_fpga_cw340.c
- sw/device/lib/arch/device_silicon.c
- sw/device/lib/arch/device_sim_dv.c
- sw/device/lib/arch/device_sim_verilator.c
- sw/device/silicon_creator/rom_ext/doc/rescue.md
- sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/device/silicon_creator/rom_ext/rescue.h
- sw/host/opentitanlib/src/rescue/serial.rs
- sw/host/opentitantool/src/command/rescue.rs
Allow the rescue protocol to negotiate a speed faster than the standard 115200 bps.  The faster rates are the "extended standard" rates of 230400, 460800 and 921600 bps.
This addresses #22943.
This PR depends on #23205; you need only review the last 2 commits.
> [rescue] Support faster UART speeds 

- sw/device/silicon_creator/lib/epmp_state.h
- sw/device/silicon_creator/rom_ext/doc/si_val.md
- sw/device/silicon_creator/rom_ext/rom_ext.c
Per discussion in the tape-out sync meeting on 2024-04-22, relax the ePMP settings:
Unlock the configuration of ePMP entries 12, 14 and 15, allowing the owner to reconfigure as needed.
As detailed in the [ePMP Proposal](file:///home/cfrantz/Downloads/Smepmp.pdf) (see section 2.2), this change will allow for CPU execution over the entire flash region, the MMIO region and main RAM because we're currently operating with MMWP=1 and MML=0.  We prevent RAM execution at the SRAM controller.
> [rom_ext] Relax ePMP settings.

- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/rom.c
The rom was incorrectly determining the value to place into the `rom_ext_slot` of the boot log.
> [rom] Report the correct boot log `rom_ext_slot`

- sw/device/lib/arch/device.h
- sw/device/lib/arch/device_fpga_cw305.c
- sw/device/lib/arch/device_fpga_cw310.c
- sw/device/lib/arch/device_fpga_cw340.c
- sw/device/lib/arch/device_silicon.c
- sw/device/lib/arch/device_sim_dv.c
- sw/device/lib/arch/device_sim_verilator.c
- sw/device/silicon_creator/rom_ext/doc/rescue.md
- sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/device/silicon_creator/rom_ext/rescue.h
- sw/host/opentitanlib/src/rescue/serial.rs
- sw/host/opentitantool/src/command/rescue.rs
1. Support rescue uploads to slot B.
2. Add a `WAIT` command that prevents automatic reboot after upload actions.
3. Allow the rescue protocol to negotiate a speed faster than the standard 115200 bps.  The faster rates are the "extended standard" rates of 230400, 460800, 921600, 1.3M and 1.5M bps.
4. Configure the rescue limit to 474K as a convenience for the `prodc` customer.  Future configuration of this limit will be enabled by ownership transfer.
> Cherry-pick to earlgrey_es_sival: [rescue] Support Slot B, rescue limits and faster rates

- hw/ip/csrng/rtl/csrng_ctr_drbg_gen.sv
This commit changes the check for the CMD_STS_INVALID_GEN_CMD error status response. Since GEN commands are renamed to GENB and finally to GENU we should check whether the acked command is GENU instead of GEN in csrng_ctr_drbg_gen.sv.
Resolves [#23131](https://github.com/lowRISC/opentitan/issues/23131)
> [csrng/rtl] Check for GENU instead of GEN for CMD_STS_INVALID_GEN_CMD

- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/rv_core_ibex_mem_test.c
- sw/device/tests/sival/BUILD
Changes made:
* ROM check is skipped because it's locked by ROM_EXT.
* Since ROM_EXT locks address translation, the MMIO test location is
switched to a rv_timer register instead.
* ROM_EXT locks down its own flash pages, so the page being tested is moved
from page 0 to an accessible page. The default property config is also
changed to a specific data region.
> [sival, rv_core_ibex] make rv_core_ibex_mem_test work on silicon

- sw/device/tests/BUILD
- sw/host/tests/chip/pwrmgr/src/sleep_all_resets.rs
- sw/host/tests/chip/pwrmgr/src/sleep_all_wakeups.rs
- sw/host/tests/chip/pwrmgr/src/sleep_por.rs
Even though the test plan says not to run `pwrmgr_normal_sleep_all_wake_ups` (and deep variant) and to prefer the random version, it is current in a weird state where it is enabled but does not specify a test harness which causes it to fail.
> Fix pwrmgr sival

- hw/ip/hmac/rtl/hmac.sv
- hw/ip/hmac/rtl/hmac_core.sv
Prior to this commit, `hmac_core` and thus the entire `hmac` module would not raise the `idle_o` output when it got told to stop (#23036). This is problematic because then HMAC cannot be clock-gated during context switch (save & restore feature).  Clock gating would only work when a message stream is fully processed (after the *process* command).
This commit fixes the problem by keeping track of idleness inside `hmac_core`.  In addition to the conditions that existed before, this tracker goes to idle when a *stop* command is received and the current message block is completely processed.
This fixes #23036.
> [hmac/rtl] Fix idle_o when told to stop

- sw/device/tests/pwrmgr_deep_sleep_all_wake_ups.c
- sw/device/tests/pwrmgr_normal_sleep_all_wake_ups.c
Wakeup source 5 is already disabled in the randomized version.
*DO NOT CHERRY-PICK TO mater*
> [pwrmgr,sival] Disable wakeup source 5 in normal tests

- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/dv/sv/usb20_agent/usb20_block_if.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_aon_wake_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_in_err_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_setup_stage_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_smoke_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/env/usbdev_env_cfg.sv
- hw/ip/usbdev/dv/tb/tb.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR introduces a single sequence that addresses the following test points:
- usbdev_aon_wake_resume
- usbdev_aon_wake_reset
- usbdev_aon_wake_disconnect
These are checking that the `usbdev_aon_wake` module responds to the appropriate newly-introduced USB bus events from the usb20_driver, and that it issues a 'wake request' in response. The request would ordinarily be received by power management hardware and cause the SoC to resume from Normal/Deep Sleep.
The PR also makes some minimal modifications to `usb20_monitor` to correct its decoding and handling of valid packet data on the USB, since that was found to be leading to failures in the new tests (as well as a number of the existing sequences). It does not attempt to fix up the monitor behavior for invalid traffic such as that …
> [dv,usdbev] usbdev_aon_wake sequences

- hw/ip/pattgen/data/pattgen.hjson
- hw/ip/pattgen/doc/programmers_guide.md
- hw/ip/pattgen/doc/registers.md
- hw/ip/pattgen/dv/env/pattgen_channel_cfg.sv
- hw/ip/pattgen/dv/env/pattgen_env.core
- hw/ip/pattgen/dv/env/seq_lib/pattgen_base_vseq.sv
- hw/ip/pattgen/dv/env/seq_lib/pattgen_inactive_level_vseq.sv
- hw/ip/pattgen/dv/env/seq_lib/pattgen_vseq_list.sv
- hw/ip/pattgen/dv/pattgen_sim_cfg.hjson
- hw/ip/pattgen/rtl/pattgen_chan.sv
- hw/ip/pattgen/rtl/pattgen_core.sv
- hw/ip/pattgen/rtl/pattgen_ctrl_pkg.sv
- hw/ip/pattgen/rtl/pattgen_reg_pkg.sv
- hw/ip/pattgen/rtl/pattgen_reg_top.sv
This feature allows to define the level that `pcl` and `pda` take when pattgen is not actively sending data  bits (i.e., when pattgen is disabled or all data bits have been sent).
The feature is not yet supported in the scoreboard, so the scoreboard gets disabled for the test that exercises this feature.  This limitation is tracked in a linked issue.  A manual inspection of waves showed that the main use case works as intended, though:
(see https://github.com/lowRISC/opentitan/issues/21924#issuecomment-2120534793 for details)
All existing tests retain their checks, coverage, and pass rate; i.e., when this feature is not used (`inactive_level_p`{`cl`,`da`}` = 0`), pattgen's behavior does not change.
This resolves #21924.
> [pattgen] Add inactive level feature

- sw/device/tests/rv_core_ibex_address_translation_test.c
Previously this test tests for ibus translation only despite setting up both ibus and dbus translation. This PR adds a dbus check.
> [sival, rv_core_ibex] check for dbus address translation

- sw/device/tests/BUILD
- sw/device/tests/usbdev_iso_test.c
- sw/device/tests/usbdev_mixed_test.c
- sw/device/tests/usbdev_stream_test.c
- sw/host/tests/chip/usb/usb.rs
- sw/host/tests/chip/usb/usb_harness.rs
The main purpose of this PR is to fix the test harness that I broke by mistake in https://github.com/lowRISC/opentitan/commit/52714dcdce25352e48537c8dc7c9063ee7b261fc
The issue is that in certain test, the harness is needed to enable VBUS sensing but no USB device will actually appear on the bus so the harness must not wait for it. I took this opportunity to do some further cleanup/improvements.
The reason this failure was not caught by CI is that certain tests do not require the harness on the CW310 so it was not used and therefore the CI didn't break. This PR changes that to run the harness (even when almost useless) even on the CW310.
> [usb,sival] Various improvements and fixes

- sw/device/silicon_creator/rom/e2e/sigverify_key_type/BUILD
- sw/device/silicon_creator/rom/e2e/sigverify_key_type/key_type.bzl
Update sigverify_key_test to include coverage of SPX keys.
This change introduces the key_type.bzl module which is used to generate test exit success and failure signatures.
Fixes: https://github.com/lowRISC/opentitan/issues/21551
> [rom/e2e] Update sigverify_key_test

- hw/ip/pwm/data/pwm_testplan.hjson
- hw/ip/pwm/dv/env/pwm_env_cov.sv
`regwen_cg` and `overwrite_conf_cg` don't make sense (anymore), so this PR removes them from the testplan. Please see commit messages for details.
This resolves #17369.
> [pwm/dv] Remove unfit covergroups

- hw/formal/tools/jaspergold/parse-formal-report.py
- util/dvsim/FormalCfg.py
Looking at documentation for the current version of Jasper, and also for Jasper version 2021.12, the reported numbers are not called stimuli/coi/proof any more. Tweak to match the names used in recent versions.
The most recent nightly run gave the following result:
This makes rather more sense if the "green column" is stimuli coverage (which essentially checks whether all the inputs of all the modules in the design can be 0/1).
> [fpv] Tweak report headers to match Jasper version

- third_party/openocd/reset_on_dmi_op_error.patch
Now that the issue with JTAG has been identified and fixed, we can partially revert #18051. This commit removes the "stuck-at-one" detection and only keeps two DMI resets on error paths that are missing in OpenOCD. We will try to upstream this patch.
> [third_party] Partially revert patch on OpenOCD

- sw/device/silicon_creator/lib/cert/tpm_ek.hjson
- sw/device/silicon_creator/lib/dice.c
- sw/host/provisioning/ft/BUILD
- sw/host/provisioning/orchestrator/orchestrator.py
- sw/host/provisioning/orchestrator/ot_device.py
This contains several bug fixes to the Earlgrey ES provisioning flow including:
1. making the flow re-entrant,
2. enabling provisioning with either PROD or DEV signed perso binaries (depending on the target mission mode LC state), and
3. enabling the CA key ID to be a parameter of the script.
This includes a fix from the master branch: #23261
CC: @benjbender
> [manuf] bug fixes for provisioning orchestrator 

- hw/ip/hmac/dv/env/hmac_env_cov.sv
- hw/ip/hmac/dv/env/hmac_env_pkg.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- hw/ip/hmac/rtl/hmac.sv
This PR will only have 2 commits to review once this PR https://github.com/lowRISC/opentitan/pull/23108 is merged. This introduces changes in the HMAC DV to enable `do_read_check` that was commented out https://github.com/lowRISC/opentitan/issues/22578 and achieve synchronization with how the FIFO is  verified vs the CSRs being read and compared **but only for SHA-2 256**.  I have disabled `do_read_check` in the meantime to keep the constraints unreleased on the digest sizes and key lengths, until I fix the synchronization issues for 384/512. With this PR, the block test `hmac_error` and `hmac_stress_all` still fail, but have been root-caused and will be fixed in upcoming PRs.
> [hmac,dv/rtl] Fix HMAC DV scoreboard synchronization

- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env.core
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_reset_acq_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_reset_tx_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_watermarks_acq_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_watermarks_tx_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_hrst_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_runtime_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_smoke_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
This PR adds two new directed testcases for the I2C target-mode watermark interrupts added in #21621.
See the commit message + vseq header comment for more details about each test.
Some test machinery changes and cleanups have been done to support these new testcases, which comprises the first 4 commits. The final two commits add each testcase.
Best reviewed commit-by-commit.
Goes towards #23077
> [i2c,dv] I2C target mode fifo watermark tests

- sw/device/lib/dif/dif_csrng_shared.c
- sw/device/lib/dif/dif_csrng_unittest.cc
- sw/device/lib/testing/BUILD
- sw/device/lib/testing/csrng_testutils.c
- sw/device/lib/testing/csrng_testutils.h
- sw/device/lib/testing/entropy_testutils.c
- sw/device/lib/testing/entropy_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/csrng_edn_concurrency_test.c
This PR contains a couple of commits to tighten the csrng_edn_concurrency test to stress the entropy complex more heavily (see #22753). Also, the PR carries over a fix from the cryptolib to the dif library to avoid hangs as a result of SW commands being missed / dropped by CSRNG due to handling HW commands.
I recommend reviewing the commit individually.
> [chip-level/sival] Tighten csrng_edn_concurrency test

- sw/device/lib/crypto/drivers/hmac.c
- sw/device/lib/crypto/drivers/hmac.h
- sw/device/lib/crypto/impl/hash.c
- sw/device/lib/crypto/impl/rsa/rsa_3072_verify.c
- sw/device/tests/crypto/ecdsa_p256_verify_functest.c
- sw/device/tests/crypto/sha256_functest.c
As outline in #22731, the plan is to move SHA-2/HMAC implementations to HMAC HWIP. This PR only brings the "bottom" part of the implementation (which is the HMAC driver), and I plan to make another PR for the "top" part (which is the code that connects HMAC driver to cryptolib API).
Therefore this "bottom" part includes addition of streaming calls to the HMAC driver. I have tested the driver for all 6 functionality, but this PR only connects SHA-256 function to cryptolib, because I want to keep "top" part simple in this PR.
There is also tracker for planned changes in https://github.com/lowRISC/opentitan/issues/23191.
> [cryptolib, hmac] Update HMAC driver

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- hw/ip/hmac/rtl/hmac.sv
This PR depends on PRs https://github.com/lowRISC/opentitan/pull/23108 and https://github.com/lowRISC/opentitan/pull/23220 to get merged. It implements fixes in HMAC RTL and DV scoreboard for digest loading (based on @ballifatih's PR https://github.com/lowRISC/opentitan/pull/23197) besides additional changes to fix issues with secret wiping and error handling (prioritizing `SwInvalidConfig` in case of simultaneous errors) across different digest sizes. 
This also implements a potential fix for https://github.com/lowRISC/opentitan/issues/23181 but needs to be tested - would you test this @ballifatih and let me know if this sorts this out?
> [hmac,rtl/dv] Fix digest loading/error wiping and error handling

- hw/top_earlgrey/padring.core
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
- hw/top_earlgrey/rtl/padring.sv
- util/topgen/templates/chiplevel.sv.tpl
In packages with reduced pin count, not all pads can be bonded out.  The
direct-mapped pads have to be bonded out, but Quad SPI may not always be
required.  For use cases where IOB[0:3] are not bonded out but
SPI_HOST_D{2,3} and SPI_DEV_D{2,3} are bonded out but are not used
(because Quad SPI is not used), this commit adds muxes that allow using
those Quad SPI ports via IOB[0:3].
The mux selectors are currently tied off (to the direct connection);
they will be wired up as part of https://github.com/lowRISC/opentitan/issues/23280.
> [top_earlgrey,padring] Implement muxing for IOB[0:3]

- hw/ip/spi_device/dv/env/spi_device_env_cov.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
Spi_device CFG covergroup updated and sampled regardless of the mode since tx/rx_order affect all modes.
Mailbox_en bit has been added as well.
> [dv] Spi_device CFG register Covergroup fix.

- hw/ip/spi_device/lint/spi_device.waiver
- hw/ip/spi_device/lint/spi_tpm.waiver
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spi_passthrough.sv
- hw/ip/spi_device/rtl/spi_readcmd.sv
- hw/ip/spi_device/rtl/spi_tpm.sv
- hw/ip/spi_device/rtl/spid_jedec.sv
- hw/ip/spi_device/rtl/spid_status.sv
For flops that latch on the falling edge of SCK, an unsafe reset timing can occur if SCK is permitted to toggle while CSB toggles. SPI NOR flash datasheets typically only specify setup and hold requirements around the rising edge of SCK, so these flops are not protected (at least without OT-specific requirements on the datasheet).
Add a synchronizing flop that releases the CSB reset on the rising edge of SCK, and create a separate reset network for the outclk domain to fix the RDC issue.
> [spi_device] Add CSB reset sync for outclk domain

- hw/ip/aon_timer/dv/env/aon_timer_env_cov.sv
- hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_jump_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_prescaler_vseq.sv
This PR adds new covergroups for wkup, bark and bite metrics, including the sampling in the SCB. 
Also rewrites existing VSEQ constraints to allow for a wide range of values for the threshold and count vectors.
> Aon timer coverage and minor scb fix

- sw/device/lib/testing/BUILD
- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/keymgr_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/keymgr_sideload_aes_test.c
- sw/device/tests/keymgr_sideload_kmac_test.c
- sw/device/tests/keymgr_sideload_otbn_test.c
This change fixes the following tests:
- keymgr_sideload_kmac_test
- keymgr_sideload_otbn_test
It also refactors the following test to reuse common keymgr infrastructure:
- keymgr_sideload_aes_test
> [test] Fix keymgr_sideload test cases.

- hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- sw/device/tests/autogen/plic_all_irqs_test.c
- util/reggen/interrupt.py
- util/reggen/reg_block.py
- util/topgen/c_test.py
- util/topgen/merge.py
- util/topgen/templates/plic_all_irqs_test.c.tpl
Cherry-picks a single commit in #21226 which seems to fix the rv_plic sival tests on silicon.
> Cherrypick to earlgrey_es_sival: [topgen] Add field to specify status IRQ default behavior

- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_min_sec_ver_test.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
1. Verify the manifests of both slots to determine a maximum `min_sec_ver`.  We prevent advancing the `min_sec_ver` beyond the value associated with any valid firmware in flash.
2. Test the `MinBl0SecVer` request by advancing the minimum security version forward.  Attempt to go beyond the maximum allowed value and confirm that the request is rejected.  Attempt to go backwards and confirm that the request is rejected.
This addresses #23259.
> [rom_ext_e2e] Test the `MinBl0SecVer` request

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv
- sw/device/lib/testing/keymgr_testutils.c
The default timeout was too short; see the added comment for details.
This resolves #23050, and it resolves #23084.
> [top_earlgrey/dv] Fix timeout in `chip_sw_keymgr_key_derivation_vseq`

- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/BUILD
- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/flash_ecc_error_test.c
This adds ROM E2E two test cases that corrupt the ROM_EXT manifest identifier in both slots A and B to prepare for the development of a ROM load access fault exception handler to address #21353. Note this just contains the test cases to tease out the flash ECC corruption error cases, but does not yet provide a solution for handling such in the ROM. A solution to handling the ECC error corruption (i.e., continue attempting to boot the next stage) will be developed in a follow up PR.
> [rom,e2e] add tests for flash ECC error handling during boot

- rules/signing.bzl
- signing/README.md
- signing/examples/BUILD
- signing/examples/signatures/BUILD
Update the offline signing demo to work with ECDSA keys. Update the documentation to note that RSA signing examples only work with in the `earlgrey_es_sival` branch.
> [signing] Update offline signing demo.

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/csrng_edn_concurrency_test.c
This PR contains three more commits to optimize the `csrng_edn_concurrency` test to focus on the CSRNG and EDN interaction (and reducing wait times for ENTROPY_SRC during the test loop) and it increases the number of seeds we run in the nightlies as proposed #22753 .
> [chip-test/sival] Optimize csrng_edn_concurrency test and run more seeds in nightlies

- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/doc/registers.md
- hw/ip/hmac/dv/env/hmac_env_pkg.sv
- hw/ip/hmac/rtl/hmac.sv
- hw/ip/hmac/rtl/hmac_reg_pkg.sv
- hw/ip/hmac/rtl/hmac_reg_top.sv
This PR adds the `key_swap` field to the HMAC `CFG` CSR per this issue https://github.com/lowRISC/opentitan/issues/23158 and exposes the HMAC idle status via the `STATUS` CSR per this issue https://github.com/lowRISC/opentitan/issues/22916. Both changes would need to be covered by DV in M5 @martin-velay.
This PR depends on previous PRs; once they are merged, it will only be the last commit c5e80715a4e1c7b0dcdcb48bb44d56dfea1584f2.
> [hmac,regs/rtl] Add key_swap field and expose Idle status to SW

- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv
I am having some issues with my environment and I need to runt this through CI.
It basically tries to address to #22565 by:
* Not introducing extra seeds that incur extra area.
* Cleaner diversifications for Keymgr calls, so that we can claim no message collisions for different use cases.
> [keymgr, rtl] Reorganize keymgr advance payloads 

- hw/ip/i2c/rtl/i2c_fifos.sv
- hw/ip/otbn/dv/verilator/otbn_top_sim.sv
- hw/ip/otbn/rtl/otbn.sv
- hw/ip/prim/rtl/prim_ram_1p_adv.sv
- hw/ip/prim/rtl/prim_ram_1p_scr.sv
- hw/ip/prim_generic/rtl/prim_generic_otp.sv
- hw/ip/sram_ctrl/data/sram_ctrl.hjson
- hw/ip/sram_ctrl/doc/registers.md
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
- hw/ip/sram_ctrl/rtl/sram_ctrl_reg_pkg.sv
- hw/ip/sram_ctrl/rtl/sram_ctrl_regs_reg_top.sv
- hw/ip/usbdev/rtl/usbdev.sv
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/ibex_dv.f
- hw/vendor/lowrisc_ibex/dv/uvm/icache/dv/tb/tb.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_top.sv
- hw/vendor/patches/lowrisc_ibex/dv/0002-dv-Add-error-ports-to-ram.patch
- hw/vendor/patches/lowrisc_ibex/rtl/0002-rtl-Add-error-ports-to-ram.patch
This commit encodes all flopped 1-bit control signals into multi bit signals in the `prim_ram_1p_scr` and `prim_ram_1p_adv` module. When an encoding error is detected, a major alert is triggered within Ibex.
> [rtl] MuBi encoding of iCache memory ctrl signals

- sw/device/tests/BUILD
This test can fail because the harness waits for the USB device but the C side will only keep the USB device until the kernel sends a configuration request. Thus if the test harness is not quick enough, it might never detect the USB device.
> [usbdev,sival] Make config_host test more reliable

- hw/top_earlgrey/data/ip/chip_uart_testplan.hjson
This test was renamed but its reference in the testplan was not.
> [sival] Fix Bazel target for UART parity test

- sw/device/tests/BUILD
ROM_EXT blocks OTP programming to prevent accidental chip scrapping. This means that this test is not runnable in silicon owner stage.
This is purely a Bazel change and contains no functional changes.
> [sival] otp_ctrl_smoketest cannot run after rom_ext

- sw/device/lib/crypto/drivers/entropy.c
The cryptolib avoid use of the general-purpose `status_t` creating macros like `OK_STATUS()` or `INVALID_ARGUMENT()` which call `status_create()`.  Instead, cryptolib defines its own status types that are compatible with `status_t` but do not invoke `status_create`.
A couple of the general-pupose invocations snuck in.  Eliminate them in favor of `OTCRYPTO_...` definitions.
> [cryptolib] Eliminate `status_create` symbol use

- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- sw/device/tests/BUILD
- small fix to `flash_ctrl_info_access_lc_*` bazel
- mark `flash_ctrl_info_access_lc_*` as not runnable at the owner stage (see commit)
This PR uses the testplan `boot_stage` attribute introduced in #22898. #22898 should be merged before this PR?
> Clarify flash ctrl info access

- sw/device/lib/crypto/drivers/entropy.c
This is a manual cherry-pick of #23211 to `earlgrey_es_sival`.
> [cryptolib] Eliminate status_create symbol use

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/rnd.c
The ROM_EXT locks out OTP access, and the rnd32 function attempts to read a field in OTP, which was causing a load access fault when executed at the owner stage. This updates the rnd32 function to only read from OTP if it is executed at the ROM or ROM_EXT boot stages.
> [silicon_creator] make rnd32 work at owner stage

- sw/device/silicon_creator/manuf/provisioning_inputs.bzl
- sw/host/provisioning/ft/BUILD
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/orchestrator/orchestrator.py
- sw/host/provisioning/orchestrator/ot_device.py
This updates the provisioning orchestrator script to use a cloud KMS CA endorsement key or a local key file (as is the currently supported behavior).
> [manuf] enable orchestrator script use a cloud KMS CA endorsement key

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
Due to rom_ext locking down a bunch of stuff, some tests cannot be run in silicon owner stage. This is orthogonal to the lifecycle states, so adding a new field to testplan to indicate this.
The idea is that the new `boot_stages` field is used to indicate which boot stages the test can run in. For example,
```
boot_stages: ["rom_ext"]
```
limits the test to rom_ext stage, where
```
boot_stages: ["silicon_owner"]
```
limits the test to silicon owner stage. I suppose for tests that use SRAM injection they can have `"rom"` as boot stage since they run before ROM is executed.
When nothing is specified the test should be treated as having
```
boot_stages: ["rom_ext", "silicon_owner"]
```
> [sival] add field to testplan to indicate required boot stages

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
This seems to fix the `otbn_sw_errs_fatal_chk` vseq, which was previously passing at near 90%. (Just below when I started, or this wouldn't have been my first target!)
Careful notes in commit messages.
> [otbn,dv] Improve stack corruption vseq

- hw/dv/sv/jtag_agent/jtag_driver.sv
This fixes some silliness that crops up when the jtag driver ends up out of sync with the edges of TCK. We could probably make it more robust, but this should be the simplest tweak that gets everything working more predictably.
Note: this PR looks bigger than it is! The first commit is from PR #23081. Only these three commits are unique to this PR:
- c318b028bc `[jtag,dv] Handle trst_n at start of time in jtag_driver.sv`
- 0c5a40cc13 `[jtag,dv] Sync up with TCK before calling drive_jtag_req`
- a52617fd0b `[jtag,dv] Add a check about synchronisation in jtag driver`
> [jtag,dv] Improve driver sync with TCK

- sw/device/lib/dif/dif_clkmgr.c
The backslash in the comment causes a warning. Add some ellipsis to avoid that. (Other alternatives such as using two backslashes or adding whitespace after the backslash did not seem to work).
> [sw][nfc] Fix multi-line comment warning

- hw/ip/prim/rtl/prim_assert_standard_macros.svh
No functional change: the warning message from Jasper was saying that the $isunknown(__rst) was being treated as "0", which is the behaviour we're making explicit.
But now we don't get a warning message, which makes genuine problems a little more obvious.
> [prim,fpv] Avoid warning message from Jasper with ASSERT_AT_RESET

- sw/device/silicon_creator/rom_ext/rom_ext.c
- OTP lockout will be configured directly in the otp_ctrl.
- AST lockout is not required as `Earlgrey.PROD` will configure AST in the ROM and/or ROM_EXT with data provisioned at manufacturing time.
> [rom_ext] Remove AST and OTP lockout regions from ePMP.

- hw/ip/kmac/rtl/kmac_pkg.sv
- hw/ip/prim/rtl/prim_sha2_pkg.sv
The linter flags an error when `conv_data` gets declared and initialized in one statement.  Splitting this into two statements removes the lint error.  This shouldn't make any functional difference inside a function, but it gets the file lint-clean without the need for a waiver.
> [kmac,prim_sha2/rtl] Fix lint error in endian conversion functions

- sw/host/opentitanlib/src/io/gpio.rs
- sw/host/opentitanlib/src/proxy/handler.rs
- sw/host/opentitanlib/src/proxy/protocol.rs
- sw/host/opentitanlib/src/transport/hyperdebug/gpio.rs
- sw/host/opentitanlib/src/transport/proxy/gpio.rs
- sw/host/opentitanlib/src/util/bitbang.rs
- sw/host/opentitantool/src/command/gpio.rs
- sw/host/tests/chip/i2c_host_override/src/main.rs
- sw/host/tests/chip/i2c_target/src/main.rs
- third_party/hyperdebug/repos.bzl
This PR enhances the existing FTDI-inspired bitbanging supported by HyperDebug.  In particular, it adds means of specifying that generation of the waveform should be put on "pause" at a certain point, until a certain logic level is seen on particular pins.
This feature allows generating I2C waveforms, while allowing the I2C device to stretch the clock.  Or generating an edge on a GPIO pin at a very precise time after OT has toggled some other pin, in order for a test case to attempt to trigger a race condition.
The command below will flash the blue LED on HyperDebug half a second after the user presses the blue button.  The new `await(1x)` directive means to pause until a high level on the first pin (and any level on the second pin) is seen.  (The initial zero on the waveform output …
> [opentitantool] Advanced bitbanging

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_common_vseq.sv
If the JTAG clock runs much faster than the system clock then things can get a bit out of sync for DMI accesses. This is tracked in an issue in the pulp-dbg module that we vendor.
Tightening the constraint slightly like this should avoid the issue that led to the problem in the first place (where the system clock was at 25MHz and the JTAG tck ran at about 100MHz).
The pulp-dbg issue is https://github.com/pulp-platform/riscv-dbg/issues/163.
> [rv_dm,dv] Avoid a fast JTAG clock

- hw/dv/sv/jtag_dmi_agent/jtag_dmi_monitor.sv
- hw/dv/sv/jtag_dmi_agent/jtag_dmi_reg_frontdoor.sv
I strongly suspect that I misunderstood what was going on when I added this code, and it just makes things more complicated. The failures that I was "working around" were probably due to bugs in the jtag driver, which I believe I have now fixed.
> [rv_dm,dv] Revert "double request" logic in DMI driver and monitor

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
This is a small tweak that gets things to line up for some seeds in the FSM smoke sequence.
> [rv_dm,dv] Add a slight wait when enabling debug in rv_dm_base_vseq

- hw/ip/rv_dm/dv/tb.sv
This won't have much effect on the enable/disable events, but it *does* change the timing because the decision about whether to connect some of the signals goes through a prim_lc_sync or a prim_clock_mux2, which injects a few extra cycles of delay.
Rather than trying to guess the exact timing, let's cheat and tell the jtag monitor to use the version that's actually making it through to the internals of the block.
> [rv_dm,dv] Connect mon_jtag_if to internal signals

- hw/ip/otp_ctrl/data/otp_ctrl_scoreboard.sv.tpl
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
For non-integrity partitions (s.a. VENDOR_TEST), the OTP scoreboard backdoor reads the OTP in raw form (doesn't apply ECC corrections) and compares with actual data returned on the DAI interface. However, in case `MacroEccUncorrErr` is injected, the IP might try and correct the errors, and the result on the DAI won't match the actual raw data in that particular address.
This issue causes two failures:
1. [Memory comparison](https://github.com/lowRISC/opentitan/blob/master/hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv#L612C1-L616C44). This has been mitigated in CS.
2. [Register comparison for `OTP_CTRL.DIRECT_ACCESS_RDATA_*`](https://github.com/lowRISC/opentitan/blob/master/hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv#L1119-L1130). This is a bit trickier to override in CS, hence this PR is …
> [dv/otp_ctrl] dont compare direct_access_rdata_* on on non-integrity partitions

- hw/top_earlgrey/ip/ast/rtl/adc.sv
- hw/top_earlgrey/ip/ast/rtl/aon_clk.sv
- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/ast_alert.sv
- hw/top_earlgrey/ip/ast/rtl/ast_bhv_pkg.sv
- hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv
- hw/top_earlgrey/ip/ast/rtl/ast_dft.sv
- hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv
- hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv
- hw/top_earlgrey/ip/ast/rtl/io_clk.sv
- hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv
- hw/top_earlgrey/ip/ast/rtl/rng.sv
- hw/top_earlgrey/ip/ast/rtl/sys_clk.sv
- hw/top_earlgrey/ip/ast/rtl/usb_clk.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
- util/topgen/templates/chiplevel.sv.tpl
[ast] adding spi or iob mux as part of #23201
Adding #23125 changes as it wasn't approved the first time for some reason.
> [ast] adding spi or iob mux

- sw/device/silicon_creator/lib/attestation.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
- sw/device/silicon_creator/lib/otbn_boot_services.c
- sw/device/silicon_creator/manuf/lib/flash_info_fields.c
- sw/device/silicon_creator/manuf/lib/flash_info_fields.h
- sw/device/silicon_creator/manuf/lib/personalize.c
- sw/device/silicon_creator/rom_ext/defs.bzl
This cherry picks two fixes to the earlgrey_es_sival branch:
1. a ROM_EXT fix to enable reading the attestation seed flash info page at the owner stage (to enable TPM/CDI_1 keygen there as was originally intended), and
2. the addition of a keygen version field to the attestation key seed INFO page
> [cherry-pick] #23401 and #23403 to `earlgrey_es_sival` branch

- sw/device/lib/testing/pinmux_testutils.c
- sw/device/silicon_creator/rom/e2e/weak_straps/BUILD
- sw/device/silicon_creator/rom/e2e/weak_straps/sw_straps_test.c
- sw/host/tests/rom/sw_strap_value/src/main.rs
1. Add some propagation delays to `pinmux_testutils`.
2. Add some debug output to the `sw_straps` test program and test harness.
3. Add support for the teacup board's `SW_STRAPn_WEAK` pins to allow testing of weak values through high-value (1 Mohm) resistors.
Partially addresses #21630.
> [sival] Verify all strap combinations

- sw/host/provisioning/orchestrator/ot_device.py
This fixes the provisioning orchestrator script to enable using either:
1. a local key, or
2. a cloud KMS key for endorsing certificates during personalization. Which key is used is based on which parameter is passed to the orchestrator.py script. If the `--ca_key_ckms_id` parameter is passed, the cloud KMS key will be used. Similarly, if the `--ca_key_der_file` parameter is passed, the local key will be used.
> [manuf] enable local or KMS cert endorsement key

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_common_vseq.sv
There are some notes in the individual commits, but the motivation was that I had to squint a bit to work out what the code was doing, and realised that it could be somewhat simpler.
> [dv] Minor cleanups in `run_seq_with_rand_reset_vseq`

- .bazelrc
- sw/host/opentitanlib/bindgen/BUILD
- sw/host/opentitanlib/src/util/status.rs
- sw/host/tests/xmodem/xmodem.rs
This lint requires a `// SAFETY: ...` comment above `unsafe { ... }` blocks which explain why the unsafe code is safe.
See https://rust-lang.github.io/rust-clippy/master/index.html#/undocumented_unsafe_blocks for more details.
Most of our code is already clean for this lint, but I've added two commits which fix or add these annotations.
The `status.rs` file just needed the comments to match the format `clippy` expects.
The `xmodem.rs` test file needed `SAFETY` comments writing which hopefully I've gotten right.
> [sw] Enable `clippy::undocumented_unsafe_blocks` lint

- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
- sw/device/silicon_creator/lib/otbn_boot_services.c
This fixes a bug in the ROM_EXT to enable read access (while removing write and erase access) to the attestation seed INFO page so that CDI_1 and TPM attestation keys can be generated at the Owner stage, as was originally intended.
> [rom_ext] enable read access to attestation seed pages

- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/mod.rs
- sw/host/opentitantool/src/command/transport.rs
HyperDebug by default does JTAG on five particular pins.  However, as it is all bit-banging with no true hardware support, it is able to use almost any combination of pins.
This PR introduces a transport-specific command to "move" the JTAG functionality to a different set of pins.
Usage:
`opentitantool --interface=hyperdebug transport set-jtag-pins <TCLK> <TMS> <TDI> <TDO> <TRSTn>`
> [opentitantool] Allow changing which pins to use for JTAG

- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_bus_rand_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_usb_traffic_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR adds sequences to:
- check back-to-back streaming of packets to single/multiple endpoints (streaming_test)
- check operations under maximum USB utilization (max_usb_traffic)
- generate randomized bus stimuli such as Suspend-Resume Signaling, Bus Resets and VBUS Disconnects during traffic; to check that the DUT is recoverable.
- the PR also addresses some faults and inadequacies of the USB driver
1. detect and check the SE0/EOP signaling, and additionally the Idle bit interval after the SE0 bits.
2. prevent collision between reception of DUT traffic and transmission of host packets
3. calculate and check the CRC16 on IN DATA packets
> [dv,usbdev] Max traffic, streaming and randomized bus stimuli

- hw/dv/sv/jtag_dmi_agent/jtag_rv_debugger.sv
If the JTAG clock is reasonably slow, multiplying by 100_000 overflows a 32-bit value. In the test I was running, I had tck_period_ps = 258310. After it had overflowed, we were actually just waiting ~250 TCK cycles, which wasn't enough to avoid a timeout.
Cast up to a bigger type to avoid the overflow.
> [dv,jtag] Fix overflow in timeout calculation

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_common_vseq.sv
The impact of this change can be seen in e.g. rv_dm_tap_fsm_vseq. With the original 10,000 cycle wait, the back-to-back DMI operations took too long and we never managed to inject the reset.
(I should say: this doesn't actually get the test passing! But I think that's a separate issue, which I will try to address in a separate PR)
> [rv_dm,dv] Increase the wait time for injecting resets

- hw/bitstream/README.md
- hw/ip/otp_ctrl/data/earlgrey_a0_skus/sival/BUILD
- hw/ip/otp_ctrl/data/earlgrey_a0_skus/sival_bringup/BUILD
- hw/top_earlgrey/BUILD
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/device/silicon_creator/manuf/tests/BUILD
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/tests/BUILD
- sw/device/tests/doc/sival/devguide.md
Enable SLH-DSA (SPX+) for test targets using the following execution environments:
- `//hw/top_earlgrey:fpga_cw310_sival`
- `//hw/top_earlgrey:fpga_cw310_sival_rom_ext`
> [test] Enable SLH-DSA on fpga_cw310_sival.

- hw/ip/hmac/rtl/hmac_core.sv
This implements RTL changes to the HMAC FSM to handle context switching (transitions to `StDone` to wait on hash result, and then `StIdle` from where every context ought to start/continue) and aligns triggering of idle and done. With this change, the SAR smoke test passes on @martin-velay's SAR DV branch (https://github.com/lowRISC/opentitan/pull/23116) which tests out SAR across 2 contexts (HMAC + same digest size 256). 
This hasn't been tested out thoroughly, and I think other issues will come up as DV proceeds. I'm also running a block-level regression at my end. @ballifatih this should close this issue https://github.com/lowRISC/opentitan/issues/23352, but I wouldn't be surprised if something else comes up next.
> [hmac,rtl] HMAC FSM fixes for SAR

- hw/ip/hmac/dv/env/hmac_env_pkg.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- hw/ip/prim/rtl/prim_sha2.sv
- hw/ip/prim/rtl/prim_sha2_32.sv
- hw/ip/prim/rtl/prim_sha2_pkg.sv
This synchronizes the scoreboard checks for digest sizes 384 and 512, and once merged would close https://github.com/lowRISC/opentitan/issues/22578. This also implements a minor RTL fix with the loading from the message FIFO for SHA-2 384/512; this has no impact on functionality and digests computation, but aligns reading the words from the FIFO (and thus depth and status throughout) with what would be expected. This also implements additional DV fixes for the error handling checks when simultaneous errors are triggered.
> [hmac,rtl/dv] DV synchronization and error handling fixes

- sw/device/silicon_creator/lib/base/sec_mmio.c
- sw/device/silicon_creator/lib/boot_data.c
- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/lifecycle.c
- sw/device/silicon_creator/lib/drivers/otbn.c
- sw/device/silicon_creator/lib/drivers/otp.c
- sw/device/silicon_creator/lib/sigverify/spx_verify.c
- sw/device/silicon_creator/rom/sigverify_otp_keys.c
Fix #22925 to refactor the hardened size_t wrap-around tests.
The hardened checks test against the `SIZE_MAX` instead of `UINT32_MAX`, which works both on-device and off-device while preserving the size semantics.
Change all applicable lines that match both “CHECK” and “UINT32_MAX”.
> [rom] Assert size_t wrap-around with SIZE_MAX

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_sba_tl_access_vseq_lib.sv
Many of these tests were timing out, for rather silly reasons. A local example run had num_times=2 and num_trans=25 and this took about 150ms, the time limit that we impose on the uvm phase. That works out as roughly 3ms per transaction.
Rather than bumping the timeout to be bigger, knock the maximums down in these constraints. I don't believe that a longer-running test will show any new types of behaviours, so we can always increase the reseed count (and run the tests in parallel!) if we're not covering enough of the state space.
> [rv_dm,dv] Constrain iteration counts in sba tl_access vseq

- azure-pipelines.yml
- ci/scripts/check_dv_sw_images.py
- ci/scripts/check_dv_sw_images.sh
The goal of this script is to check that all sw_images specified in DV sim_cfg hjson files are valid bazel targets. This avoid DV tests getting out of sync with bazel BUILD files.
Note that this is just a first pass because it only checks that the bazel targets exists but a more thorough check would be to check that the actual output files of the bazel target contain the expected files (e.g. flash image, otp image).
> [ci] Add DV sim_cfg sw_images linter

- hw/top_earlgrey/BUILD
Part of https://github.com/lowRISC/opentitan/issues/23388.
> [test] Enable SLH-DSA on fpga_cw340_sival.

- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
Add the following test cases:
1. `chip_sw_hmac_all_configurations`: Include coverage for 384 and 512 modes of operation.
2. `chip_sw_hmac_stream_mode`: Include coverage for context save and restore across multiple modes of operation.
> [top-level] Update HMAC top level test plan.

- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/alert_handler_ping_ok_test.c
Ensure the pinging mechanism does not trigger any alert handler NMI interrupts as a result of synchronization issues between ping senders and receivers.
This is part of https://github.com/lowRISC/opentitan/issues/22954. 
This test will be added to the GLS test plan.
> [dv/top] Add alert_handler ping_ok test.

- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
Firstly, remove the test_timeout_ns override from the hjson file. We actually increase the timeout to 150ms in the rv_dm base vseq, and we don't want to lower it again!
Secondly, divide the CSRs into smaller chunks and run more seeds. The test coverage should still be reasonable, but we will hopefully no longer time out.
This is a better-thought-out version of #23434, which was trying to do the same thing.
> [rv_dm,dv] Avoid timeouts in the rv_dm_jtag_dmi_csr_bit_bash test

- hw/dv/sv/tl_agent/seq_lib/tl_device_seq.sv
This condition came about because the pre_start task for tl_device_seq clears a flag, which doesn't work if we set the flag just before starting the sequence.
That clearing behaviour came from commit 17d386c879a, which doesn't really explain why it's needed. Maybe we can drop that behaviour entirely, but there's an easy work around just in case it's necessary. This commit does that workaround.
> [dv] Fix a race condition in tl_device_seq

- .github/workflows/cherrypick.yml
Fixes #23447
This change causes the `Manually CherryPick` label to be added to a PR if its automated cherry picking fails. This makes it easier to find and fix failed backports.
> [ci] Apply "Manually CherryPick" label when backporting fails

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
This is currently broken (my fault!), causing the `otbn_multi_err` test to fail in nightly checks.
The first commit fixes the breakage and the tidy-up meant that I could drop a load of other code from the base vseq. This is the second commit.
Fixes #23461.
> [otbn,dv] Fix wait_for_run_completion in otbn_base_vseq

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_abstractcmd_status_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_busy_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_exception_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_halt_resume_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_not_supported_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_common_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_dataaddr_rw_access_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_halt_resume_whereto_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_hart_unavail_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_dm_inactive_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_hard_reset_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_idle_hint_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_halted_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_resuming_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_progbuf_busy_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_progbuf_read_write_execute_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_rom_read_access_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_sba_tl_access_vseq_lib.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_tap_fsm_vseq.sv
Rather than explicitly setting it to MuBi4False in each vseq, let's move the constraint to the base class. This fixes things for the stress sequence which didn't have the individual copied constraint, and hopefully makes the code a bit clearer.
> [rv_dm,dv] Tidy up how we disable scan mode

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_dm_inactive_vseq.sv
This isn't really meant to make big changes, but the vseq becomes a bit less magical (fewer magic hex constants), and it's a bit more obvious what it's doing. Descriptions in the commit messages (the last one is the main commit).
> [rv_dm,dv] Improve the rv_dm_jtag_dmi_dm_inactive vseq

- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- sw/device/tests/BUILD
- sw/device/tests/rv_dm_delayed_enable.c
- sw/host/tests/chip/rv_dm/BUILD
- sw/host/tests/chip/rv_dm/src/csr_rw.rs
1. Add OTP image with `RV_DM` late debug feature enabled.
2. Introduce test case on FPGA.
3. Update selected test cases to run in `cw340` FPGA.
This is part of https://github.com/lowRISC/opentitan/issues/21965
> [test] Add `rv_dm` late enable test 

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
When a key request is triggered by the DV environment, we shouldn't update the readback CSR as this triggers the error described in lowRISC/opentitan#23445.
More specifically, writing the readback CSR over the RAL interface issues a TL-UL message to the register interface of the `sram_ctrl` module. However, when `cfg.in_key_req=1`, the `sram_ctrl_scoreboard` checks that no TL-UL transaction is on the bus.
By waiting until `cfg.in_key_req=0` we avoid this error message.
After this change:
Closes #23445.
> [sram_ctrl/dv] Avoid updating readback CSR on key_req

- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_sec_cm_ctrl_config_regwen_vseq.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_vseq.sv
- hw/ip_templates/pwrmgr/rtl/pwrmgr.sv
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_sec_cm_ctrl_config_regwen_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr.sv
- sw/device/tests/BUILD
- sw/device/tests/pwrmgr_lowpower_cancel_test.c
To avoid race conditions with WFI and locking the CONTROL CSR prematurely, wait until the transition out of FastPwrStateActive that begins low power entry before locking the CONTROL CSR.
This allows software to clear CONTROL.LOW_POWER_HINT if an early interrupt caused the "core_sleep" pulse to be too short for pwrmgr to capture. Then, subsequent WFI instructions may still choose between full power and a low power mode.
When software wakes up, it must attempt to clear CONTROL.LOW_POWER_HINT, then busy-poll until it reads its value as 0. If pwrmgr triggered low power entry, the CPU will poll until pwrmgr completes the low power sequence. If pwrmgr did not trigger low power entry, the CPU's write will succeed, and the read will immediately return 0.
Also add a test that causes Ibex to decode …
> [pwrmgr] Don't lock CONTROL until observing core_sleep

- hw/ip/spi_device/dv/env/spi_device_env_cov.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
The TB (SCB) now carries out addr_mode checks for both the pending bit and the addr_4b_en field.
Some FCOV has been added to check that if there's been a addr_mode TL-UL write, the value would be invalidated if the next flash_command clashes against the written value (EN/EX4B commands)
> [dv, spi_device] addr_mode DV changes + FCOV

- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/hmac_functest.c
- sw/device/tests/crypto/hmac_multistream_functest.c
Reorganize SHA-2/HMAC tests into two:
- One shot calls -> hmac_functest
- Multistream (a.k.a. interleaving streaming) test -> hmac_multistream_functest
also update the test plan and add the second test as TLT, so that it runs on nightlies.
> [earlgrey, hmac] Add TLT for SHA-2/HMAC multistream

- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/tests/csrng_base_test.sv
At some point we should probably add some coverage for the new registers. I can do so once I'm back.
Rarely there are still some failures I wasn't able to investigate yet. When I ran a 10% regression I found 1 failure due to the added DV in the csrng_cmds test.
This is the DV for #23324
> [csrng/dv] Add DV for the force fips bit functionality

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_config_regwen_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_config_regwen_vseq.sv
Fix constraints contradiction.
See constraint ctrl_num_c in file flash_ctrl_otf_base_vseq line 95 (at 6/05/2024).
if (rand_op.partition == FlashPartData) ctrl_num == ctrl_data_num;
> [flash/dv] Fix constraint error in flash_ctrl_config_regwen test

- hw/top_earlgrey/data/ip/chip_rv_dm_testplan.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_rv_dm_lc_disabled_vseq.sv
Update the `chip_rv_dm_lc_disabled` test point to include coverage for the `rv_dm` late debug enablement feature.
Modify the chip_rv_dm_lc_disabled_vseq.sv to include randomized tests for the late debug enablement feature as well as fixed coverage for the DEV life cycle state to exercise this feature.
Fixes: https://github.com/lowRISC/opentitan/issues/21965
> [dv/tlt] Add rv_dm late debug enable test.

- hw/dv/sv/csrng_agent/csrng_agent_cfg.sv
- hw/dv/sv/csrng_agent/csrng_device_driver.sv
- hw/ip/edn/dv/env/edn_if.sv
- hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
- hw/ip/edn/dv/tests/edn_base_test.sv
- hw/ip/edn/rtl/edn_core.sv
- hw/ip/edn/rtl/edn_main_sm.sv
This PR is related to [#22352](https://github.com/lowRISC/opentitan/issues/22352)
I wasn't able to confirm with the coverage yet if this fills the FSM coverage hole since I was working on debugging.
Through this PR I was able to find some potential minor issues.
Some might not even be issues but are still worthy of discussion.
These include:
- HW_CMD_STS only shows boot/auto mode after the INS command (For auto mode this probably makes sense since INS is SW controlled).
- After reenabling EDN the HW_CMD_STS still shows the last command before EDN was disabled.
- Two assertoffs I added need to be checked if they can be added or if there is a bug.
Furthermore, the alert test does not have a check for SW_MODE since the probability of having both auto mode and boot mode disabled in the CTRL …
> [edn/dv] Add transition to reject entropy state to alert test

- sw/device/lib/base/BUILD
- sw/device/lib/testing/test_framework/BUILD
- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/lib/sigverify/sphincsplus/test/BUILD
- sw/device/tests/BUILD
- sw/device/tests/autogen/BUILD
- sw/device/tests/pmod/BUILD
- util/topgen/templates/BUILD.tpl
This PR updates as many `opentitan_test`s as possible to use `EARLGREY_TEST_ENVS` and `EARLGREY_SILICON_OWNER_ROM_EXT_ENVS`.
* If a test isn't designed for an environment, we remove it with `dicts.omit`.
* If a test is supposed to work but is broken on an environment, we tag `broken`.
I have tried my best not to _remove_ any environments from tests, only add them.
@engdoreis and I discussed some tests in `//sw/device/tests` that do not need to run on `fpga_cw310_test_rom` so removed that environment from those tests.
> [bazel] Refactor device test execution environment assignments

- sw/host/opentitanlib/src/app/config/mod.rs
It appears that `hyperdebug_teacup_default.json` got left out of the list of built-in config files.
> [opentitantool] Fix config files bug

- sw/device/silicon_creator/rom/rom.ld
We have been padding the `.crt` section out to consume the whole of `epmp_reset_rx_size` (the size of the initial EPMP executable region coming out of reset).
Reclaim this unused space for ROM code.
> [rom] Reclaim 662 bytes of unused space

- hw/ip/otbn/rtl/otbn.sv
- hw/ip/rom_ctrl/rtl/rom_ctrl.sv
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
- hw/ip/tlul/rtl/tlul_adapter_sram.sv
- hw/ip_templates/flash_ctrl/rtl/flash_ctrl.sv.tpl
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl.sv
This commit enables the .Secure() option of the prim_fifo_sync FIFOs inside the tlul_adapter_sram used by the flash_ctrl module.
On an error, the intg_error_o signal will be flagged.
> [flash_ctrl/rtl] Enable SecFifoPtr for TL-UL FIFOs

- hw/ip_templates/flash_ctrl/rtl/flash_phy_rd.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv
This commit enhances the data integrity protection inside the flash_phy_rd module by generating and appending the integrity tag before muxing the corresponding word using word_sel.
> [flash_ctrl/rtl] Enhance data intg in flash_phy_rd

- hw/dv/tools/dvsim/sim.mk
- rules/opentitan/cc.bzl
- sw/device/lib/testing/test_rom/BUILD
- sw/device/silicon_creator/rom/BUILD
1. Add `opentitan_binary` ROM targets with the expected suffix: i.e. `mask_rom_sim_dv`, `mask_rom_sim_verilator`.
2. Update Bazel cc.bzl to export `elf` files in `opentitan_binary` builds.
3. Update sim.mk to query Bazel output files from the `files` group if the target kind is not `opentitan_test`. This works because the ROMs are built using `opentitan_binary` targets.
> [dv] Fix ROM e2e JTAG tests.

- hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv
Please propagate it to the prim_ram_*p_pkg::ram_*p_cfg_t on chip top level.
> [ast] adding memory test port controllability

- hw/ip/hmac/rtl/hmac_core.sv
Should clear following linting errors:
```
E   PARAM_NOT_USED:   hmac_core.sv:59           Localparam 'BlockSizeBSBSHA256' not used in module 'hmac_core'                           New
E   PARAM_NOT_USED:   hmac_core.sv:61           Localparam 'BlockSizeBSBSHA512' not used in module 'hmac_core'                           New
```
> [hmac/lint] Remove unused localparam

- hw/top_earlgrey/dv/chip_rom_tests.hjson
Increase the timeout. ECDSA sigverify takes longer compared to the previous RSA implementation.
> [dv/tlt] Fix rom_e2e_static_critical

- hw/ip/spi_device/rtl/spi_cmdparse.sv
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spid_status.sv
Block uploads, WREN, WRDI, EN4B, and EX4B when the busy bit is set. The state of the device should not change until the busy bit is cleared.
This may be especially important to avoid the payload buffer changing its contents while software is processing a command.
Fixes #21700
> [spi_device] Block flash write commands when busy

- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/lc_ctrl/dv/cov/lc_ctrl_volatile_unlock_disabled_unr_exclude.el
- hw/ip/lc_ctrl/dv/cov/lc_ctrl_volatile_unlock_enabled_unr_exclude.el
- hw/ip/otbn/otbn.core
- hw/ip/otbn/otbn_pkg.core
- hw/ip/prim/pre_dv/prim_flop_2sync/tb.sv
- hw/ip/prim_generic/prim_generic_flop_2sync.core
- hw/ip/prim_generic/rtl/prim_generic_flop_2sync.sv
- hw/ip/uart/dv/env/seq_lib/uart_noise_filter_vseq.sv
- hw/top_earlgrey/data/clocks.xdc
- hw/top_earlgrey/data/clocks_cw341.xdc
- hw/top_englishbreakfast/data/clocks.xdc
This allows for technology/library-specific implementations of `prim_flop_2sync`.  The generic implementation is based on two back-to-back `prim_flop`s, which is identical to how `prim_flop_2sync` was implemented before.
This PR doesn't add FPGA-specific implementations; this will be tracked in an issue and might get implemented later.
> [prim/rtl] Allow for tech-specific impls of `prim_flop_2sync`

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
Increase timeout to solve test failure.
Fixes: https://github.com/lowRISC/opentitan/issues/23325
> [dv/tlt] Fix Coremark test.

- hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv
- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
This signal is not really synchronous with anything else: an escalation request can come at any time. Collect very basic coverage of whether it is Off, On or undefined (treated as On).
The "bad" bin for this covergroup is true whenever an unknown value is sent on the lc_escalate_en_i. We expect this to be treated as an escalation request (because of the lc_tx_test_true_loose call in otbn_core_model.sv), so completing coverage for this covergroup will check that we do indeed treat unknown values on lc_escalate_en_i as good escalation requests.
This should satisfy the first item in #23460.
> [otbn,dv] Collect coverage from lc_escalate_en_i signal

- hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv
- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
The point of this is to check that we're handling invalid RMA request values correctly (by ignoring them). Invalid values land in the "bad" bin for the covergroup and completing coverage for the covergroup will ensure that we have genuinely seen this invalid value.
The code in otbn_core_model.sv will ignore that request (using lc_tx_test_true_strict to check it), so the test will fail if the RTL acts on the request.
This should satisfy the second item in #23460.
> [otbn,dv] Collect coverage for RMA requests

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_flash_ctrl_lc_rw_en_vseq.sv
- sw/device/tests/sim_dv/flash_ctrl_lc_rw_en_test.c
The test had issues with handling of the keymgr configuration. The DIF was throwing an error when trying to advance the state of the keymgr when the device is in unprovisioned state.
The test was refactored to make it easier to maintain in the future.
> [dv/tlt] Fix flash_ctrl_lc_rw_en_test.

- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/doc/registers.md
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
- hw/ip/csrng/rtl/csrng_core.sv
- hw/ip/csrng/rtl/csrng_reg_pkg.sv
- hw/ip/csrng/rtl/csrng_reg_top.sv
- hw/ip/csrng/rtl/csrng_state_db.sv
As discussed here: https://github.com/lowRISC/opentitan/issues/21141#issuecomment-2082289550
> [csrng] Make reseed counters always readable, allow locking down internal state access per instance

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
We've recently observed some timeouts for this test in the nighlies. This commit thus speeds up the AST power-up time to reduce the test time per seed similar to the non-reduced frequency variant.
> [chip-test/sival] Modify config for csrng_edn_concurrency_reduced_freq

- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/spi_device_sleep_test.c
- sw/host/tests/chip/spi_device/BUILD
- sw/host/tests/chip/spi_device/src/spi_device_sleep_test.rs
This PR adds the test
```
name: chip_sw_spi_device_output_when_disabled_or_sleeping
desc: '''Verify spi_device output values when spi_device is disabled or the chip is sleeping.
SW needs to be able to set the SPI output value when spi_device is disabled or the
chip is sleeping, to either all-zeros or all-ones, depending on integration
requirements.  The following scenarios have to be verified:
After power-on reset:
- SW to configure pinmux retention logic so that the chip pins connected to
spi_device outputs are (a) always zero or (b) always one (SW needs to be able to
choose between a and b).
- DV environment to check that SPI outputs match configuration by SW.
Going to sleep:
- SW to disable spi_device, wait until CSb is high, configure pinmux retention logic
as it would after POR, and …
```
> [Sival, Spi device] Sleep test

- hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
- hw/ip/spi_host/dv/tb.sv
There's some description in commit messages. This is about trying to avoid warnings coming out when building spi_host DV code with VCS (or, I suspect, Xcelium).
> [spi_host,dv] Fix some typing problems in spi_host DV code

- doc/contributing/hw/comportability/README.md
- hw/ip/tlul/rtl/tlul_adapter_sram.sv
- hw/ip_templates/flash_ctrl/rtl/flash_ctrl.sv.tpl
- hw/ip_templates/flash_ctrl/rtl/flash_phy.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy_core.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy_rd.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_core.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv
- util/reggen/countermeasure.py
This commit adds the data XOR address infection mechanism. The goal of this countermeasure is to detect faults on read addresses targeting the flash controller.
On a host flash read, the address used for accessing the data is XORed inside the flash_phy_rd module to the fetched data.
The address then is removed in the u_tl_adapter_eflash where the core has a TL-UL interface to the flash memory. Here, the buffered address from the incoming TL-UL read request is taken.
When a FI attack manipulates an address, data would be fetched from the wrong address in the flash memory. But inside the flash_phy_rd module, this manipulated address is XORed to the data. Now, when removing the address by using the original address, and there is a difference from a FI, the data would be faulty and the …
> [flash_ctrl/rtl] Host data XOR address infection

- sw/host/tests/chip/flash_ctrl/src/main.rs
- sw/host/tests/chip/gpio/src/main.rs
- sw/host/tests/chip/gpio_intr/src/main.rs
- sw/host/tests/chip/i2c_host_override/src/main.rs
- sw/host/tests/chip/i2c_target/src/main.rs
- sw/host/tests/chip/mem/src/main.rs
- sw/host/tests/chip/spi_device/src/spi_passthru.rs
- sw/host/tests/crypto/aes_nist_kat/src/main.rs
- sw/host/tests/crypto/drbg_kat/src/main.rs
- sw/host/tests/crypto/ecdh_kat/src/main.rs
- sw/host/tests/crypto/ecdsa_kat/src/main.rs
- sw/host/tests/crypto/hash_kat/src/main.rs
- sw/host/tests/crypto/hmac_kat/src/main.rs
- sw/host/tests/crypto/kmac_kat/src/main.rs
These rust harnesses enable control flow on a UART object but then
immediately drop it and gets it again in each test function. Since
the UART object is reference counted, it will be destroyed in-between
tests and the control flow setting will be lost. The easiest fix is to
create the object once and pass it around.
> [sw/host] Fix UART usage regarding control flow

- hw/ip/prim/rtl/prim_ram_1p_pkg.sv
- hw/ip/prim/rtl/prim_ram_2p_pkg.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
- util/topgen/templates/chiplevel.sv.tpl
This adds a memory test port and connects it to the AST interface added in PR #23531.
> [top_earlgrey,prim_ram_*_pkg] Connect memory test port

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_jtag_inject_vseq.sv
The OTP images used in ROM e2e test cases set `EN_SRAM_IFETCH` to `True` inside the `HW_CFG1` partition. The `sram_ctrl` checks the otp value to determine to use the fetch enable signal provided by `lc_ctrl` versus the `sram_ctrl` `exec` register value.
This change enables SRAM execution by setting the `sram_ctrl` exec register. The `chip_sw_sram_ctrl_execution_main` test cases checks all the other OTP versus SRAM register permutations.
> [dv/tlt] Fix ROM JTAG injection tests.

- hw/ip/otbn/data/otbn_testplan.hjson
These match the post-ES features discovered when analysing #22077. Implementing these tests is tracked as #23460.
> [otbn,dv] Add post-ES sec_cm feature tests to testplan

- hw/ip/csrng/dv/env/csrng_scoreboard.sv
This got accidentally modified with commit 3b47465d33e980e728ce96168cab07093efcf6ee. See also lowRISC/OpenTitan#23349.
> [csrng/dv] Correct prediction of FIPS/CC compliance flag for UNI cmd

- hw/dv/sv/usb20_agent/usb20_agent_cfg.sv
- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/dv/sv/usb20_agent/usb20_block_if.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_data_toggle_restore_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_enable_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_pins_sense_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- hw/ip/usbdev/dv/tb/tb.sv
This PR mostly extends the usb20_monitor to support other bus configurations and non-packet signaling on the USB, and to detect and indicate the presence of errors in the received packets. The driver is also simplified slightly to leave only the 'mechanism' within the driver and leave the sequence to determine what activity shall be generated ('policy').
- Correct the collection of packet traffic to validate the End Of Packet.
- Generalize the collection of symbols from the USB so that the other bus configuration may readily be tested later.
- Implement the detection of invalid SYNC signals, invalid EOP and bit stuffing errors; flag these in the item that we will forward to the scoreboard.
- This also means that the agent is now using true tri-stated USB signaling.
- Support the detection …
> [dv,usbdev] Monitor improvements and error detection

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/hmac.c
- sw/device/silicon_creator/lib/drivers/hmac.h
- sw/device/silicon_creator/lib/drivers/hmac_functest.c
- sw/device/silicon_creator/lib/drivers/hmac_unittest.cc
To ease implementation of SLH-DSA (#23144), it is convenient to collect SHA256 digests in big-endian order.
> [silicon_creator, hmac] Permit big- and little-endian results

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_outputs_vseq.sv
The device software was updated the name of one of the injected variables from `kTestPhase` to `kTestPhaseDV`. This change aligns the implementation in the DV side.
> [dv/tlt] Fix sysrst_ctrl_outputs test.

- sw/host/tests/chip/spi_device/src/spi_passthru.rs
test_write_status was missing the busy bit check, as there is no SpiFlash helper method for WriteStatus1.
> [test] Fix up spi_passthru test to check WIP

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
1. Increase chip_sw_csrng_edn_concurrency_reduced_freq timeout: This is to account for the more aggressive entropy complex configuration introduced in earlier changes.
2. Increase chip_sw_uart_tx_rx_bootstrap timeout to take twice as long. A follow PR will reduce this time once we get an idea of how much time is needed to run this test.
> [dv/tlt] Increase timeouts for `chip_sw_csrng_edn_concurrency_reduced_freq` and `chip_sw_uart_tx_rx_bootstrap` tests.

- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spi_device_pkg.sv
- hw/ip/spi_device/rtl/spid_status.sv
The newer out_clk-synchronized resets were missing direct connectivity for scan reset, as was the CSR-connected reset to the prim_fifo_async used for flash status register updates moving from SW to the SPI clock domain. Add the requisite muxes to patch that up.
> [spi_device] Mux in missing scan_rst_ni connectivity

- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
- hw/ip/tlul/rtl/tlul_sram_byte.sv
This commit changes back the PRIM_FLOP_SPARSE_FSM to an ordinary flop.
> [sram_ctrl/rtl] Use flop instead of prim_sparse_flop

- hw/top_earlgrey/data/ip/chip_rom_ctrl_testplan.hjson
- sw/device/silicon_creator/rom/e2e/jtag_inject/BUILD
We don't have JTAG access in `PROD`. Make the lifecycle states for these tests properly reflect that, instead of "passing when it fails" as was done before for `PROD` and `PROD_END` states.
> Fix `chip_sw_rom_access` / `openocd_debug_test_otp_*` LC states

- hw/vendor/patches/pulp_riscv_dbg/0003-Use-lowrisc-instead-of-PULP-primitives.patch
- hw/vendor/pulp_riscv_dbg/src/dmi_cdc.sv
Convert the JTAG combined resets to have a synchronous assertion timing in the core clock domain, placing them on the D input of the first flop of the prim_flop_2sync, instead of the reset inputs of both flops. This removes the asynchronous reset assertion that may cause RDC issues, and it restores scan reset as the only reset for those 2 flops when in scan mode.
Note that prim_fifo_async_simple guarantees that a prior transaction in flight will at least maintain its data values, since the holding register is *not* reset. This mechanism does not guarantee that the request will be squashed, but it *does* guarantee that the request will not be malformed by the reset. In addition, if the JTAG reset is held for long enough (i.e. >= the round-trip delay), the response for any previously …
> [rv_dm] Fix RDC and DFT issue with resets

- hw/ip/edn/dv/edn_sim_cfg.hjson
- hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
- hw/ip/edn/rtl/edn_core.sv
Previously, EDN could immediately de-assert the valid upon getting an ACK error thereby violating the valid/ready handshake protocol between EDN and CSRNG.
> [edn] Hold csrng_req_valid until valid/ready handshake completes

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__sec_cm_fi.svh
- hw/dv/sv/sec_cm/sec_cm_base_if_proxy.sv
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_common_vseq.sv
See the second commit message for a careful description of what this is doing. Fixes #23578.
After writing this, it occurred to me that another approach might have been to write zeros to the backing memory for the FIFOs in question (rather than 'X). This would have fixed the FSM lock-up behaviour that we were seeing. If this "disable the buggy check" approach feels unsafe, we could always follow up with that more principled approach, but it's probably worth merging this version to fix the failing nightly in the meantime.
Note: There's currently a "TODO(???)" comment, which is supposed to track a specific PR discussing the thing we're working around. Don't merge this without linking it up properly.
For proof that this genuinely fixes the linked issue:
```
rupert@halibut /s/l/opentitan …
```
> [otbn,dv] Disable an FI test which causes (spurious) DV failures

- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR just collects a few uncontentious tidy ups and introduces constructors for use in subsequent code and to simplify/tidy the existing code in time. Presently objects are created and subsequently populated, which results in a lot of error-prone replication of code.
> [dv,usbdev] Tidy up test plan and usb20_item handling

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/power_virus_systemtest.c
1. Add fast sim and rng_srate +plusargs to speed up simulation time. This may be removed by the backend integrator as needed.
2. Increase SW timeout.
3. Update entropy complex configuration to force more operations.
> [dv/tlt] Fix power virus test.

- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/BUILD
The flash ECC tests are broken due to an oversight in the way the exception is handled.
Addresses #21353.
> [rom_e2e] Disable broken flash ECC tests

- hw/dv/sv/push_pull_agent/push_pull_monitor.sv
cfg.agent_type is of type push_pull_agent_e and we want to print out its name rather than its integer value, so need to add a ".name()".
> [dv] Fix typo in prints in push_pull_monitor

- hw/ip/otbn/dv/model/otbn_trace_entry.h
This header uses uint32_t and builds with recent versions of GCC and Verilator don't get that included transitively, causing a build failure. Fix the silly bug.
> [otbn,dv] Add missing include to otbn_trace_entry.h

- hw/dv/sv/i2c_agent/i2c_agent.core
- hw/dv/sv/i2c_agent/i2c_agent_cfg.sv
- hw/dv/sv/i2c_agent/i2c_agent_pkg.sv
- hw/dv/sv/i2c_agent/i2c_driver.sv
- hw/dv/sv/i2c_agent/i2c_item.sv
- hw/dv/sv/i2c_agent/i2c_monitor.sv
- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env.core
- hw/ip/i2c/dv/env/i2c_env.sv
- hw/ip/i2c/dv/env/i2c_env_cfg.sv
- hw/ip/i2c/dv/env/i2c_env_pkg.sv
- hw/ip/i2c/dv/env/i2c_reference_model.sv
- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/i2c/dv/env/i2c_seq_cfg.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_mode_toggle_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_reset_acq_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_reset_tx_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_hrst_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_stress_all_vseq.sv
This PR cleans up the architecture of the I2C scoreboard to create a clean break between comparison (scoreboard) and modelling (reference model / predictor). This change is a precursor to further DV, which builds upon the new infrastructure to model more behaviour in the refModel and less in the vseqs. The I2C DV environment in it's current form is difficult to work on, and this change should go a long way towards improving it.
This is a big PR, and is therefore difficult to judge based on the diff only. I have regressed it locally, and only seen a difference to the "i2c_target_hrst_vseq" test, which is currently passing approx 30% of the time. This vseq is quite unpleasant in the way it interacts with the agent/scoreboard, and is very brittle to change, while mainly targeting an increase …
> [i2c,dv] I2C scoreboard rearchitect

- sw/device/silicon_creator/lib/drivers/alert.h
Make sure `alert_ping_enable` is either:
- Not called from ROM
- Controllable with an OTP configuration
Addresses #23393.
> [rom] Document `alert_ping_enable`

- hw/top_earlgrey/BUILD
- rules/opentitan/silicon.bzl
- sw/device/silicon_creator/rom/BUILD
1. Give the silicon target the capability to emit a ROM target.
2. Add `silicon_creator` as a exec_env for the ROM.
Fixes: #23641
> [rom] Build for the silicon_creator target

- sw/device/tests/chip_power_idle_load.c
Disables alert_handler outgoing alert pings, since they cause the ping response to be confused for an outgoing alert. This workaround can be removed when #23644 is fixed.
Fixes #23570
> [dv,top_level] Fix chip_sw_power_idle_load

- hw/top_earlgrey/sw/autogen/top_earlgrey_memory.ld
- sw/device/lib/testing/test_framework/ottf_start.S
- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/BUILD
- sw/device/silicon_creator/rom/rom_isrs.S
- sw/device/silicon_creator/rom/rom_start.S
- sw/device/silicon_creator/rom_ext/e2e/handoff/fault_start.S
- sw/device/silicon_creator/rom_ext/rom_ext_start.S
- sw/device/silicon_owner/bare_metal/bare_metal_start.S
- util/topgen/templates/toplevel_memory.ld.tpl
1. Store all registers in the exception frame to permit the
fault handler to update the value of the faulting load.
2. Re-arrange the exception logic to check mstatus and the flash
controller fault status first.
3. Decode the faulting instruction.  If the instruction is a load,
extract the destination register.  Load all-ones into the
destination register before returning from the exception.
Note: this is an alternative approach to #23634
Addresses #21353
> [rom] Rewrite the flash exception handler 

- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom/rom.h
- sw/device/silicon_creator/rom/rom_isrs.S
- sw/device/silicon_creator/rom/rom_isrs.c
- sw/device/silicon_creator/rom/rom_isrs.h
1. Move the C-based ISR functions to their own module to better control the link order.
> [rom] Relocate exception handlers to their own section

- hw/ip/otp_ctrl/data/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/prodc/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/data/otp_ctrl_mmap.hjson
- hw/ip/otp_ctrl/doc/otp_ctrl_mmap.md
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv
- sw/device/silicon_creator/rom/e2e/sram/BUILD
- sw/device/silicon_creator/rom/e2e/sram/sram_readback_test.c
- sw/device/silicon_creator/rom/rom_start.S
1. Configure the SRAM readback feature as specified by OTP.
2. Supply default configurations with readback disabled.
3. Add tests to check the enabled case.
Addresses #23495.
> [rom] Configure the SRAM readback feature 

- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
The aon_timer module is a regular IP block, so it should not be marked as `attr: "templated"`, since that causes a failure in the countermeasures check.
Fixes #23649
> [hjson,englishbreakfast] Do not declare aon_timer as templated

- hw/dv/sv/i2c_agent/i2c_agent_cfg.sv
- hw/dv/sv/i2c_agent/i2c_monitor.sv
- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env.core
- hw/ip/i2c/dv/env/seq_lib/i2c_host_perf_precise_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
> ~~This PR builds on changes from #23528 and #23192, which should be merged first. Only the final 2 commits are new.~~
This PR adds a new test to more-precisely measure the I2C performance in DUT-Controller mode. This removes the fudge-factor from the existing host_perf_test. This test is mapped to the "host_mode_config_perf" TestPoint, and may be used as a basis for further expanding future coverage crosses against performance / timing configuration.
An additional commit maps a previously-unmapped testpoint to an existing test.
Goes towards #23077
> [i2c,dv] I2C precise perf test

- hw/ip/csrng/dv/env/seq_lib/csrng_err_vseq.sv
For each error there is a corresponding error test signal. In the error test sequence not all of these error test signals were expected to cause a fatal error even though they do in the normal case. This commit adds for each fatal error, the corresponding err_test to the list of fatal errors.
> [csrng/dv] Add the right err_test codes to fatal errors

- hw/ip/csrng/rtl/csrng_core.sv
The main SM error test signal is currently the only test signal where the actual error would be fatal but the test signal is not. This commit make adds the err_code_test_bit for the main SM error to fatal_loc_events to make the main SM error test fatal.
> [csrng/rtl] Make the main SM error test signal fatal

- sw/device/silicon_creator/lib/manifest.h
- sw/device/silicon_creator/lib/manifest_unittest.cc
Fix #22923 to reject unaligned manifest extensions.
The `manifest_check` function will now return `kErrorManifestBadExtension` if the given manifest has an unaligned extension offset.
> [rom] Reject unaligned manifest extensions

- azure-pipelines.yml
- hw/ip_templates/clkmgr/data/BUILD
- hw/ip_templates/flash_ctrl/data/BUILD
- hw/ip_templates/pwrmgr/data/BUILD
- hw/ip_templates/rstmgr/data/BUILD
- sw/device/silicon_creator/rom/data/rom_manual_testplan.hjson
- util/py/packages/lib/register_usage_report.py
- util/py/scripts/audit_sec_mmio_calls.py
1. Remove invalid autogen header targets from `ip_template` folders. These targets were not working due to invalid dependencies. Removing these invalid targets help simplify build target queries, which are used in the `sec_mmio` auditing script. 
2. Fix the `audit_sec_mmio_calls.py` script. The script was failing due missing updates to required bazel target queries.
3. Update the ROM manual test plan to include the following targets:
a. `rom_manual_sec_mmio_audit`
b. `rom_manual_stack_utilization`
c. `rom_manual_alert_handler_ping_disabled`
Fixes: https://github.com/lowRISC/opentitan/issues/19288
Part of: https://github.com/lowRISC/opentitan/issues/23393
Part of: https://github.com/lowRISC/opentitan/issues/14707
> [rom] Fix sec_mmio audit script and update ROM manual test plan

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_common_vseq.sv
This was... more difficult than I expected! The real point of the changes is the last commit of the PR. The other commits are to make everything work.
I'm pleased to say that (with this change) I've just run 24 seeds for the `otbn_sec_cm` sequence. After 50 minutes(!), 19 of them had passed, and the others are still running. So I'm reasonably confident that this works properly.
Update (crikey, that takes a while!): It works!
```
Stage  |                    Name                    | Tests       |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  |
|:-------:|:------------------------------------------:|:------------|:-----------------:|:----------------:|:---------:|:-------:|:-----------:|
|   V2S   |                tl_intg_err                 | otbn_sec_cm | …
```
> [otbn,dv] Get the otbn_sec_cm test working again without needing do disable FI

- hw/ip/otbn/data/otbn.hjson
This has been reviewed by Pirmin Vogel and Greg Chadwick (in issue #22077) and the V2 stage can now be claimed.
> [otbn,dv] Increase verification_stage to V2

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
The previous timeout was 1ms, which I chose pretty arbitrarily. It turns out that this isn't long enough for some runs in the otbn_multi vseq.
Increase to 10ms, which is still short enough that a failure should only take a couple of minutes.
This commit also tweaks the timeout error message. When I originally wrote it, it only applied to status polling timeouts. Before pushing the PR, I generalised things to cope with interrupts too, but forgot to fix the error message. Now done!
Fixes #23418.
> [otbn,dv] Increase run timeout by a factor of 10 to 10ms

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/doc/programmers_guide.md
- hw/ip/entropy_src/doc/registers.md
- hw/ip/entropy_src/doc/theory_of_operation.md
While prepping the V2S sign-off issue and going through open issues, I noted that I still had prepared some commits earlier to fix an open doc issue.
> [entropy_src/doc] Fix some documentation issues

- hw/ip/csrng/dv/csrng_sim_cfg.hjson
- hw/ip/hmac/dv/hmac_sim_cfg.hjson
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This is a V3 test and quite a few IP blocks for which we are primarily targeting V2S (AES, CSRNG, HMAC, I2C, KMAC, RV_DM, USBDEV) have a very low pass rate for this test right now.
To save DV resources, this commit reduces the number of seeds for this test for blocks not targeting V3 right now.
> [dv] Reduce number of seeds for stress_all_with_rand_reset tests

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/attestation.h
- sw/device/silicon_creator/lib/dice.c
- sw/device/silicon_creator/lib/dice.h
- sw/device/silicon_creator/lib/manifest.h
- sw/device/silicon_creator/lib/otbn_boot_services.c
- sw/device/silicon_creator/lib/otbn_boot_services.h
- sw/device/silicon_creator/lib/otbn_boot_services_functest.c
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/ecdsa.c
- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_key.c
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_key.h
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_verify.c
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_verify.h
- sw/device/silicon_creator/lib/sigverify/ecdsa_p256_verify_functest.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom/sigverify_key_types.h
- sw/device/silicon_creator/rom/sigverify_keys_ecdsa_p256.c
- sw/device/silicon_creator/rom/sigverify_keys_ecdsa_p256.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
Align secure boot and attestation implementations to use the same ECDSA types.
Part of https://github.com/lowRISC/opentitan/issues/22134.
> [rom] Refactor ECDSA pub key and signature structs.

- hw/ip/tlul/rtl/tlul_adapter_sram.sv
This commit fixes a couple lint warnings and errors flagged by multiple tools (AscentLint, Verilator, Verible). It's better to just fix them instead of writing multiple waivers.
> [tlul] Fix lint warnings and errors

- hw/ip/prim/lint/prim_flop_2sync.waiver
- hw/ip/prim_generic/lint/prim_generic_flop_2sync.waiver
- hw/ip/prim_generic/prim_generic_flop_2sync.core
The prim_flop_2sync primitive is now generated via primgen, meaning some additional lint waiver rules are needed.
> [lint] Waive lint warnings and errors in prim_[generic_]_flop_2sync

- hw/ip/rv_dm/dv/tb.sv
No functional change, since we're not really testing this behaviour. But it avoids a warning from the EDA tool at build time.
> [rv_dm,dv] Tie off next_dm_addr_i in tb.sv

- hw/ip_templates/flash_ctrl/rtl/flash_ctrl_erase.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy_core.sv
- hw/ip_templates/flash_ctrl/rtl/flash_phy_rd.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_erase.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_core.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv
This PR contains two commits to fix some uncritical lint errors (could also be waived) and some which are rather critical. We better don't rely on tools doing the right thing for those.
> [flash_ctrl] Fix lint errors and warnings

- hw/ip/hmac/rtl/hmac.sv
This adds checking `reg_hash_stop` in the `ValidHashProcessAssert` assertion for completeness to make sure that `hash_process || reg_hash_stop `are toggled with `hash_start_or_continue`.
Block-level tests at the moment without SAR will not complain of this change. @ballifatih can you plz confirm this works the same at your end with your TLT (though this is a very last priority atm)?
> [hmac,dv] Minor DV assertion fix

- hw/ip/otbn/dv/otbnsim/sim/sim.py
- hw/ip/otbn/dv/otbnsim/sim/state.py
This isn't completely working, because of the bug that I tried to fix in (the incorrect) PR #23587. With that incorrect fix working around the problem I was seeing there, I stumbled into some other issues, which this PR fixes properly.
- When we've taken an RMA request, we go down a path where we use the `stop` function to cancel any instructions that happen to be in flight. We want that behaviour, but we don't want the function to also forget about the RMA request. The first commit tidies that up.
- On an RMA request that happens before we run any operations, we don't want OTBN to actually do a secure wipe. In the design, the logic is that there's nothing that needs wiping anyway! The second commit makes the model use the same logic.
- When we take an RMA request, we need the STATUS …
> [otbn,dv] Partially fix RMA request handling

- hw/ip/hmac/rtl/hmac.sv
The `index` signal did not get assigned a default value in the corresponding always_comb block which may cause the inference of a latch.
> [hmac] Avoid inference of latch

- hw/ip_templates/flash_ctrl/dv/README.md.tpl
- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_evict_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_word_sweep_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/README.md
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_rw_evict_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_word_sweep_vseq.sv
The addresses to be programmed cannot repeat to avoid integrity errors.
Fix doc or comment typos in a separate independent commit.
Fixes #23681
> [dv,flash_ctrl] Avoid double writes in flash_ctrl_rw_evict_vseq

- hw/ip/rv_core_ibex/data/rv_core_ibex.hjson
Latest sign-off identified some small holes in testing around recently introduced security features (#23542) so moving back to V2 until tests are written to cover these.
> [rv_core_ibex] Move back to V2

- sw/device/silicon_creator/lib/sigverify/sigverify_tests/BUILD
- sw/device/silicon_creator/lib/sigverify/sigverify_tests/sigverify_cryptotest.c
Add `sigverify_cryptotest` target to test `sigverify_ecdsa` with cryptotest vectors. This change adds testing with
//sw/host/cryptotest/testvectors/data:wycheproof_ecdsa_p256_sha256.json.
Fixes: https://github.com/lowRISC/opentitan/issues/21548
> [rom] Integrate wycheproof_ecdsa_p256_sha256 tests.

- hw/ip/spi_device/lint/spi_device.waiver
After discussing with @a-will offline, we've concluded that lint errors flagged by the latest version of AscentLint for the updated spi_device version can all be waived.
> [spi_device] Waive lint errors raised by new AscentLint version

- hw/ip/otp_ctrl/data/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/prodc/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- rules/const.bzl
- sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error/BUILD
- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom/rom_isrs.S
Since the flash ECC exception handler is a complex bit of low-level
code, mitigate risk by enabling or disabling the handler via OTP.
1. Enable the handler in the default OTP configurations.
2. Test at exception entry whether or not we want to handle ECC errors.
3. Add a test that confirms that when flash ECC exception handling is
disabled, an ECC error results in a classic Load Access Fault.
> [rom] Make the flash exception handler OTP controlled 

- hw/ip/usbdev/rtl/usb_fs_tx.sv
Correct the handling of link reset to prevent it from inverting the output signals and to avoid leaving the signals inverted between the bus reset and the first transmission. Behavior should be unaltered on physical devices provided that the driver enable is honored.
Background: unexpected transitions of DP/DN were observed in block-level simulation relating to Bus Reset.
> [usbdev] Tidy DP/DN output state when undriven

- hw/ip/otp_ctrl/data/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/prodc/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- hw/ip/otp_ctrl/data/otp_ctrl_img_owner_sw_cfg.hjson
- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/ibex.c
- sw/device/silicon_creator/lib/drivers/ibex.h
- sw/device/silicon_creator/lib/drivers/ibex_host.c
- sw/device/silicon_creator/lib/drivers/pwrmgr.c
- sw/device/silicon_creator/lib/drivers/pwrmgr.h
- sw/device/silicon_creator/lib/drivers/sensor_ctrl.c
- sw/device/silicon_creator/lib/drivers/sensor_ctrl.h
- sw/device/silicon_creator/lib/drivers/sensor_ctrl_unittest.cc
- sw/device/silicon_creator/lib/drivers/watchdog.c
- sw/device/silicon_creator/lib/drivers/watchdog_unittest.cc
- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/rom.c
Add a sensor_ctrl driver to configure the peripheral from OTP.
Configure sensor_ctrl during ROM bootup.
Addresses: #23150, #21871.
> Rom sensor ctrl

- sw/device/lib/arch/BUILD
- sw/device/lib/arch/device.h
- sw/device/lib/arch/device_fpga_cw305.c
- sw/device/lib/arch/device_fpga_cw310.c
- sw/device/lib/arch/device_fpga_cw340.c
- sw/device/lib/arch/device_silicon.c
- sw/device/lib/arch/device_sim_dv.c
- sw/device/lib/arch/device_sim_verilator.c
- sw/device/silicon_creator/lib/drivers/uart.c
- sw/device/silicon_creator/lib/drivers/uart.h
- sw/device/silicon_creator/lib/drivers/uart_unittest.cc
- sw/device/silicon_creator/lib/shutdown.c
- sw/device/silicon_creator/rom/rom.c
- sw/device/tests/BUILD
- sw/host/tests/rom/e2e_openocd_debug_test/src/debug_test.rs
1. Print `OpenTitan:<lifecycle_hw_rev>` and `GIT:<git revision>` at startup.
2. The UART FIFO size was reduced from 128 to 32 for the TX FIFO, but the shutdown function assumed a 128 byte FIFO.
3. Because of the smaller FIFO, we cannot emit all of the fault info into the FIFO in one shot.  Move the UART wait function into shutdown_print.
> [rom] Print a banner at startup 

- sw/device/lib/testing/test_rom/BUILD
- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/bootstrap.c
- sw/device/silicon_creator/lib/shutdown.c
- sw/device/silicon_creator/lib/stack_utilization.c
- sw/device/silicon_creator/lib/stack_utilization.h
- sw/device/silicon_creator/lib/stack_utilization_asm.h
- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom/rom_start.S
- sw/host/opentitanlib/src/bootstrap/mod.rs
- sw/host/opentitantool/src/command/mod.rs
1. Add infrastructure to measure stack utilization.  The code is gated behind the preprocessor symbol `STACK_UTILIZATION_CHECK`.
2. Enhance bootstrap to skip the post-bootstrap reset step, allowing the stack utilization to be printed.
3. Add a manual test to measure stack utilization in various circumstances:
- Bootstrap
- A good image in slot A
- A good image in slot B
- A bad image in slot A
- Empty flash
Addresses #14707.
> [rom] Stack usage report

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_usb_traffic_vseq.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Ensure that minimum and maximmum inter-packet delays are exercised by introducing the ability to set these delays explicitly on existing sequences rather than have them randomized.
> [dv,usbdev] Testing of inter-packet delays

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_av_buffer_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_device_address_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_disable_endpoint_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_resume_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_suspend_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_config_tx_osc_test_mode_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_spray_packets_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR adds test sequences to cover the following test points:
- link_resume
- phy_config_tx_osc_test_mode
- device_address
- disable_endpoint
It also updates av_buffer_seq following the division into the Available Buffer FIFO into two separated FIFOs for OUT and SETUP packets. It now exercises the Av SETUP FIFO too.
~~This PR is now based on #23671~~
> [dv,usbdev] Additional test sequences

- hw/ip/otbn/data/otbn.hjson
This follows the discussion on issue #22077.
Fixes #22077.
> [otbn] Mark verification stage as V2S

- sw/device/silicon_creator/lib/drivers/hmac.c
- sw/device/silicon_creator/lib/drivers/hmac.h
- sw/device/silicon_creator/lib/drivers/hmac_functest.c
Add functions for truncated digests and word-aligned input.
This is helpful for SHA2-based SPHINCS+, particularly the word-aligned version of update. Without it, the average of 10 runs is `1739904` cycles, but with the word-aligned update it's `1476997` cycles, so I think the small amount of code size here is worthwhile.
> [rom] Extend HMAC driver.

- hw/ip/otp_ctrl/data/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/prodc/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- sw/device/lib/testing/test_framework/BUILD
- sw/device/lib/testing/test_framework/ottf_main.c
- sw/device/lib/testing/test_framework/ottf_test_config.h
- sw/device/silicon_creator/rom/e2e/reset_reason/BUILD
- sw/device/silicon_creator/rom/e2e/reset_reason/reset_reasons_test.c
- sw/device/silicon_creator/rom/rom.c
1. Add an OTP to control preserving the reset reason in rstmgr (default configuration: clear it).
2. Do not clear the reset reason if instructed to preserve it by OTP.
3. Add a test for the reset-reason-preserving OTP configuration.
Addresses #21355.
> [rom] Maybe don't clear the reset reason

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_setup_priority_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR adds a single sequence in the final commit:
- usbdev_setup_priority checks that the final slot of the RX FIFO accepts only SETUP packets and that OUT packets are NAKed. This is important in keeping the USBDEV always responsive to Control Transfers even under heavy traffic and/or high software latency.
~~_This PR is based upon and includes #23669 because it uses some common code, but **only the final commit is relevant.**_~~
> [dv,usbdev] Usbdev setup priority sequence

- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/provisioning_inputs.bzl
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
This updates the CP and FT E2E tests to reactivate them in CI (removing the "broken" label). These were temporarily disabled as #22823 was investigated.
Additionally, the FT flow was fixed (a recent PR #23391 enabled SPX+ signing, but a valid key was not specified here).
> [manuf] reactivate CP and FT provisioning flows in CI

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_prog_reset_vseq.sv
- hw/ip_templates/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_prog_reset_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
flash_ctrl_prog_reset allow in some cases to wait for states that aren't reachable and the timeout used to wait for the test to finish gracefully is in some cases not long enough, so this PR is increase it.
> [flash/dv] Increase timeout for flash_ctrl_prog_reset

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
This fixes some rare failures in test flash_ctrl_fs_sup caused by a possible overflow of the randomized operation by randomizing an address and number of words that exceeding the info partition size.
> [flash/dv] Fix flash_ctrl_base_otf_vseq address overflow

- hw/ip/otbn/dv/model/iss_wrapper.cc
- hw/ip/otbn/dv/model/iss_wrapper.h
- hw/ip/otbn/dv/model/otbn_core_model.sv
- hw/ip/otbn/dv/model/otbn_model.cc
- hw/ip/otbn/dv/model/otbn_model.h
- hw/ip/otbn/dv/model/otbn_model_dpi.h
- hw/ip/otbn/dv/model/otbn_model_dpi.svh
- hw/ip/otbn/dv/otbnsim/sim/constants.py
- hw/ip/otbn/dv/otbnsim/sim/ext_regs.py
- hw/ip/otbn/dv/otbnsim/sim/sim.py
- hw/ip/otbn/dv/otbnsim/sim/state.py
- hw/ip/otbn/dv/otbnsim/stepped.py
- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
This is still not beautiful, but the pass rate for the `otbn_escalate` test goes from 80% (last night's run) to `87.5%` (running 24 seeds) and the code now has comments that explain why it thinks it is doing the right thing.
There are careful comments on the individual commits. Clearly, this still isn't quite working right (and there's even a TODO message about an ugly workaround in the simulator), but this is much closer to where we want to be.
> [otbn,dv] Tidy up RMA handling

- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
The dout value here comes from pulp code in dmi_jtag_tap.sv (see the always_comb block that drives tdo_mux) and we'll almost get the BYPASS behaviour, but not quite. Since the correct behaviour of rv_dm doesn't really include an opinion about what happens here, let's ignore it.
> [rv_dm,dv] Remove check from scoreboard about unmapped DTM reads

- hw/ip/pinmux/lint/pinmux.waiver
- hw/top_earlgrey/lint/padring.waiver
- hw/top_earlgrey/lint/top_earlgrey.waiver
This PR contains the last AscentLint waiver updates for Earlgrey. Once this PR is merged together with either https://github.com/lowRISC/opentitan/pull/23718 or https://github.com/lowRISC/opentitan/pull/23716, Earlgrey is lint clean.
> [top, pinmux] Update AscentLint waivers

- hw/ip/prim/rtl/prim_rom_pkg.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
- util/topgen/templates/chiplevel.sv.tpl
This is a follow-up of lowRISC/OpenTitan#23547.
This PR supersedes #23716.
> [top, rom_ctrl] Add missing TEST port for ROM macro

- hw/ip/usbdev/data/usbdev.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_config_tx_osc_test_mode_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
This PR just addresses a couple of regressions in the block level DV tests following a change to the usb20_driver module to disable its drivers and let the bus float to the Idle state, rather than actively driving the bus to Idle.
- usbdev_phy_config_tx_osc_test_mode requires the DUT connected to take the USB out of a link reset state and permit the test mode oscillator to drive the bus.
- CSR test was failing because changing the PHY configuration was producing visible input changes to the packet reception logic,  causing it to raise errors. This modified the event counters, causing unexpected register changes in the CSR test(s) (_same_csr_outstanding).
> [dv,usbdev] Fix up tri-state related block level tests

- hw/ip/prim/lint/prim.waiver
- hw/ip/prim/lint/prim_gf_mult.waiver
- hw/ip/prim/prim_gf_mult.core
prim_gf_mult is a primitive with it's own core file. Having the waiver rules inside the shared prim.waiver file may cause Flow warnings.
> [prim/lint] Move AscentLint waiver rules for prim_gf_mult into own file

- sw/device/silicon_creator/lib/sigverify/sphincsplus/BUILD
- sw/device/silicon_creator/lib/sigverify/sphincsplus/params.h
- sw/device/silicon_creator/lib/sigverify/sphincsplus/sha2.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/sha2.h
- sw/device/silicon_creator/lib/sigverify/sphincsplus/test/BUILD
- sw/device/silicon_creator/lib/sigverify/sphincsplus/test/mgf1_test.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/test/thash_test.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/thash_sha2_simple.c
Part of https://github.com/lowRISC/opentitan/issues/23144
These are preliminary steps for SHA2-based SPHINCS+; essentially the changes I can make without actually flipping the switch on the whole implementation. I've added an MGF1 implementation and a SHA2 version of the SPHINCS+ `thash` operation, and tests for both that I created using a known-good third-party implementation.
As a side change, I also added `test_rom` targets for all SPHINCS+ subcomponent tests. I found this useful for debugging, especially since it might be helpful to test SPHINCS+ subcomponents on commits/targets where there are issues with the ROM boot flow.
> [rom] Implement and test MGF1 and SHA2-based thash.

- hw/ip/hmac/dv/env/hmac_env_cov.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_long_msg_vseq.sv
- replace auto bins by ranges as auto bins were giving coverage mostly on index 0, as this is calculated per seed. Now changed into ranges.
- add sampling of cfg anytime hash_start/hash_continue are triggered to also sample error cases.
- tweak a bit long messages to target more what this test intent is.
> [hmac,dv] Improve slightly fcov

- hw/ip/rv_dm/dv/tests/rv_dm_base_test.sv
The logic was reasonable but I hadn't noticed that we might run two iterations, so everything was out by a factor of two. Oops!
> [rv_dm,dv] Correct timeout estimate in rv_dm_base_test

- hw/ip/otbn/dv/model/otbn_model.cc
No functional change, but this avoids a lint warning from the C++ compiler (and I was looking at the log because I've got a genuine local bug as well)
> [otbn,dv] Add unconditional return to otbn_model::step()

- hw/dv/sv/i2c_agent/i2c_agent.core
- hw/dv/sv/i2c_agent/i2c_agent_cfg.sv
- hw/dv/sv/i2c_agent/i2c_monitor.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_controller_base_seq.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_seq_list.sv
- hw/ip/i2c/dv/env/i2c_reference_model.sv
- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_reset_acq_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_reset_tx_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_watermarks_acq_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_fifo_watermarks_tx_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_runtime_base_vseq.sv
This PR is a precursor for #23192, split out to hopefully make reviewing a bit easier.
This changeset includes the less interesting stuff, cleanups and utility code to prepare for adding the new testcases in the coming PR. Hopefully each commit is comprehensible on its own. Probably the most interesting and weighty commit is the first, which adds new functionality to the I2C Agent to allow it to run NACK-aware sequences which can, for example, terminate with a stop condition when they observe a Target-driven NACK on the bus.
> [i2c,dv] I2C cleanups for nack generation tests

- hw/dv/sv/csr_utils/csr_seq_lib.sv
- hw/dv/sv/csr_utils/csr_utils_pkg.sv
Add a counter ("register 3 of 10") and lower the verbosity of the "skipping" messages: practically speaking, these messages rather overwhelms the other one when verbosity is medium.
> [dv] Improve debug prints from register aliasing sequence

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_word_sweep_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_word_sweep_vseq.sv
Write to the locations that will be read to avoid errors and to have non trivial data values. This fixes some occasional failures.
> [dv,flash_ctrl] Initialize data for flash_ctrl_read_word_sweep

- hw/ip/otbn/dv/smoke/run_smoke.sh
We're doing a build using fusesoc, which uses Verilator as the backend. The compilation takes quite a while and I realised that I was essentially compiling a big load of C++ with one thread. Oops! This makes things a bit snappier.
> [otbn,dv] Add -j$(nproc) to --make_options in run_smoke.sh

- hw/ip/edn/data/edn.hjson
This resolves lowRISC/OpenTitan#22468.
> [edn] Move EDN version 2.0.0 verification_stage to V2S

- hw/top_earlgrey/BUILD
- rules/tock.bzl
- sw/device/silicon_owner/tock/apps/hello/BUILD
- sw/device/silicon_owner/tock/kernel/BUILD
- sw/device/silicon_owner/tock/kernel/layout.ld
- sw/device/silicon_owner/tock/kernel/src/main.rs
- sw/device/silicon_owner/tock/tests/basic/BUILD
- sw/device/silicon_owner/tock/tests/uart/BUILD
- third_party/tock/repos.bzl
This makes several changes:
1. Update Tock to the merge commit for PR 4034 (which makes its ePMP setup compatible with the ROM_EXT).
2. tock_image uses opentitantool to assemble the final Tock image, because tockloader was hardcoded to assume Tock is at address 0x20000000.
3. tock_image now produces a signed image.
4. The kernel linker script sets separate symbols for "start of flash" and "start of the Tock image", as required by the new ePMP setup logic.
5. The kernel linker script now fills in all the required manifest fields.
6. Removes TicKV from the Tock kernel as well as the flash controller reconfiguration, as they are not working on silicon. TicKV is unlikely to suit our needs.
7. Changes the Tock chip config to one that matches silicon.
> [tock] Enable Tock in ROM_EXT environments.

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
Without doing this, things get rather confused if the scanmode happens to be true. The problem is that the jtag driver has to model the current FSM state, and it ends up counting a different clock from the one in the design. This is rather confusing!
The proper long-term fix is probably to make the jtag driver able to consume its TCK passively when configured to do so.
> [rv_dm,dv] Temporarily avoid scanmode in rv_dm_base_vseq

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_data_toggle_clear_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Add a test sequence for exercising the data toggle clear functionality which was subsumed into the data toggle save/restore behavior of the new registers.
Data Toggle clearing is still the most common use case for these registers, since clearing the data toggle bit is essential for handling Bus Resets and some Control Transfers to endpoint zero, and is important in some protocols.
The more general save/restore functionality is for implementing resume from Deep Sleep.
> [dv,usbdev] Data toggle clear sequence

- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_aon_wake_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_device_address_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_disable_endpoint_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_out_err_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_usb_traffic_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_rx_crc_err_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_setup_priority_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_spray_packets_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR addresses a number of uncovered test points with a single sequence `usbdev_link_out_err` that iterates through the possible causes of a 'link out error' interrupt.
It additionally improves the existing 'usbdev_rx_crc_err' sequence to meet the test plan description, which is refined for correctness.
This PR is built on #23725 because that is still suffering from unrelated CI failures, but only the **last 3 commits are relevant to this PR** and the earlier commits are unmodified and already reviewed.
> [dv,usbdev] OUT side sequences

- rules/tock.bzl
- sw/device/silicon_owner/tock/apps/hello/BUILD
- sw/device/silicon_owner/tock/kernel/BUILD
- sw/device/silicon_owner/tock/kernel/src/main.rs
- sw/device/silicon_owner/tock/tests/BUILD
- sw/device/silicon_owner/tock/tests/basic/BUILD
- sw/device/silicon_owner/tock/tests/uart/BUILD
This builds two Tock kernels: one for the cw310 and one for silicon. Each test app is built once, then combined with both kernels to produce two test images. The `opentitan_test` rule is configured to run image corresponding to its exec environment.
I manually tested this works on silicon.
> [tock] Run Tock tests on both the cw310 and silicon.

- hw/ip/otp_ctrl/data/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/prodc/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- hw/ip/otp_ctrl/data/otp_ctrl_mmap.hjson
- sw/device/silicon_creator/lib/drivers/retention_sram.c
- sw/device/silicon_creator/lib/drivers/retention_sram.h
- sw/device/silicon_creator/rom/e2e/sram/BUILD
- sw/device/silicon_creator/rom/e2e/sram/sram_readback_test.c
- sw/device/silicon_creator/rom/rom.c
1. Use the READBACK_EN OTP word to control both the main SRAM and RET-RAM readback enables.
Addresses #23495
> [rom] Enable SRAM readback for RET-RAM

- azure-pipelines.yml
- rules/opentitan/defs.bzl
- rules/opentitan/exec_env.bzl
- rules/opentitan/fpga.bzl
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/device/silicon_creator/manuf/tests/BUILD
Enable running the CP and FT reference provisioning flows on the CW340 FPGA platform (in addition to the existing flows running on the CW310 FPGA platform).
Fixes: #22971
> [manuf] Add CW340 exec_env to CP/FT provisioning tests

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_wr_path_intg_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_wr_path_intg_vseq.sv
Increase the timeout for the alert in the flash_ctrl_wr_intg, to make sure it will be enough for the slower extending enivronments.
> [flash/dv] Increase alert timeout in wr_intg test

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv
Failing to do this caused confusion in the stress_all test if the following vseq assumed we weren't in the middle of the ndmreset sequence.
> [rv_dm,dv] Clean up ndmreset value at end of smoke vseq

- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_config_rand_bus_type_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
There are three bus configuration options, leading to eight possible types of bus. Ensure that all are tested.
Modify the usb20_driver/monitor to be aware of pin-flipping when the TX side is using D/SE0 because this does invert the sense of the 'd' signal, since it is effectively driving DN now.
> [dv,usbdev] Exercise all bus configurations

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_halted_vseq.sv
This happens because we run a DMI stress sequence which happens to set the ndmreset signal and follow it up with `rv_dm_mem_tl_access_halted_vseq`. The latter sequence times out because the TL connection is gated by ndmreset.
The first commit here fixes the problem by setting the signal back to zero. The second commit adds a check in the `request_halt` task (the one that was timing out) to die immediately and informatively if this happens again.
> [rv_dm,dv] Avoid failures in stress sequence from ndmreset signal

- hw/dv/sv/jtag_agent/jtag_agent_cfg.sv
- hw/dv/sv/jtag_agent/jtag_driver.sv
- hw/dv/sv/jtag_dmi_agent/jtag_dmi_reg_frontdoor.sv
This handles a rather confusing situation in the DMI frontdoor. The problem is that a DMI request has to travel from dmi_jtag to dm_top (involving a CDC from TCK to the main clock) and then back again (involving a CDC from the main clock back to TCK).
If we stop sending JTAG operations in that time, the CDC doesn't actually get anywhere. The wait is jtag_agent_cfg_h.vif.wait_tck(10), which ends up waiting based on elapsed time rather than clock edges.
The result is that when we send another JTAG operation to find out the result of the operation, the "busy" status only makes it through the CDC *after* the JTAG operation has finished and reported that the dm is idle.
Things then get rather confused when the "busy" status appears, which the agent interprets as a mysterious operation that has …
> [jtag,dv] Keep TCK running a short time after a transaction

- sw/device/lib/dif/dif_kmac.c
- sw/device/lib/dif/dif_kmac.h
- sw/device/lib/dif/dif_kmac_unittest.cc
- sw/device/lib/testing/kmac_testutils.c
- sw/device/lib/testing/kmac_testutils.h
- sw/device/tests/entropy_src_fw_override_test.c
- sw/device/tests/keymgr_sideload_kmac_test.c
- sw/device/tests/kmac_entropy_test.c
- sw/device/tests/kmac_idle_test.c
- sw/device/tests/kmac_mode_cshake_test.c
- sw/device/tests/kmac_mode_kmac_test.c
- sw/device/tests/kmac_smoketest.c
- sw/device/tests/sim_dv/csrng_lc_hw_debug_en_test.c
Related to #17759.
The key change in this PR is the test `sw/device/tests/keymgr_sideload_kmac_test.c`, so I find that to be the most review-worthy change of this PR.
- Extend `keymgr_sideload_kmac` test so that:'
- For KMAC op with sideloaded key, check that the capacity reads as 0.
- For SW-keyed KMAC op, check that the capacity does not read as 0. This test **does not** check that this capacity value is correct. I think that is not very important to check its correctness, because we do check the correct digest.
- Further changes required in DIF/testutils to enable above change:
- Update `dif_kmac_squeeze` so that it can also return `capacity` buffer.
- Update `kmac_testutils_kmac` so that it also accepts `capacity` buffer.
- Fix these function references in other tests.
> [kmac, dv] Test if KMAC correctly zeroizes the capacity

- hw/dv/sv/dv_utils/dv_macros.svh
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_ctrl_program_error_vseq.sv
- hw/top_earlgrey/dv/tb/tb.sv
- sw/device/tests/sim_dv/lc_ctrl_program_error.c
Inject an error by tampering with the state field in an otherwise valid lc program request. If a bit needs to be cleared the otp will flag an error and won't perform the update. The previous approach was flawed.
Fixes #23631
> [dv,chip_level] Fix chip_sw_lc_ctrl_program_error

- hw/dv/sv/alert_esc_agent/alert_esc_if.sv
- sw/device/tests/chip_power_idle_load.c
Outgoing alerts can be in response to a ping request or real alerts. Make changes in alert_esc_if to detect ping responses so the cip infrastructure can avoid spurious alerts.
Change the chip_power_load test to re-enable pings.
Fixes #23644
> [d,alert_ping] Detect ping responses

- sw/device/silicon_creator/lib/drivers/hmac.c
- sw/device/silicon_creator/lib/drivers/hmac.h
- sw/device/silicon_creator/lib/drivers/hmac_functest.c
- sw/device/silicon_creator/lib/drivers/mock_hmac.cc
- sw/device/silicon_creator/lib/drivers/mock_hmac.h
- sw/device/silicon_creator/lib/sigverify/sphincsplus/context.h
- sw/device/silicon_creator/lib/sigverify/sphincsplus/hash_sha2.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/sha2.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/test/BUILD
- sw/device/silicon_creator/lib/sigverify/sphincsplus/test/mgf1_test.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/thash_sha2_simple.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/wots.c
Accelerates SPHINCS+ computations by changing the HMAC driver:
1. Separate out `init()` into `configure()` and `start()` so that the code can start a new hash operation of the same type without reconfiguring the hardware.
2. Separate `process()` from `final()` so that we can perform unrelated computations in between letting HMAC know the input is done and actually reading the digest, while HMAC is processing.
3. Use the new save/restore feature of the HMAC block to cache the state of the most performance-relevant computation after ingesting the first message block (the reference implementation also does this; I just didn't include it in #23732 because I wasn't sure we would want to commit to the code size tradeoff).
In terms of performance (average of 10 valid runs from `kat0`) and code …
> [rom] Speed up SPHINCS+ computations.

- hw/ip/rv_dm/data/rv_dm_sec_cm_testplan.hjson
This is implemented by a generic test (in
cip_base_vseq__tl_errors.svh) and the only work needed for rv_dm is to name it in the testplan. Do so.
> [rv_dm,dv] Connect up sec_cm_bus_integrity testpoint

- hw/ip/rv_dm/data/rv_dm_sec_cm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_debug_disabled_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
- hw/ip/rv_dm/dv/sva/rv_dm_bind.sv
- hw/ip/rv_dm/dv/sva/rv_dm_enable_checker.sv
- hw/ip/rv_dm/dv/sva/rv_dm_sva.core
This builds on #23766, which is the first 4 commits. Only the final 3 commits are unique to this PR.
The first two commits are about strengthening the scoreboard slightly so that it can check the properties we want to test in the testpoint. The final commit implements most of the testpoint, falling back to rv_dm_sba_debug_disabled (which was implemented in commit 4) for one of the properties we want to assert.
> [rv_dm,dv] Implement sec_cm_lc_hw_debug_en_intersig_mubi testpoint

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_not_supported_vseq.sv
The first commit tidies up the testpoint slightly. The second implements it, replacing a rather nonsensical mess that was there before.
> [rv_dm,dv] Properly implement the rv_dm_cmderr_not_supported_vseq test

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
The testpoint description can be improved slightly (first two commits). Then the implementation needs re-doing, so that it gives us some confidence! That's the third commit.
> [rv_dm,dv] Tidy up implementation of the ndmreset_req vseq

- sw/host/opentitanlib/src/io/gpio.rs
- sw/host/opentitanlib/src/proxy/handler.rs
- sw/host/opentitanlib/src/proxy/protocol.rs
- sw/host/opentitanlib/src/transport/hyperdebug/gpio.rs
- sw/host/opentitanlib/src/transport/proxy/gpio.rs
- sw/host/opentitanlib/src/util/bitbang.rs
- sw/host/opentitantool/src/command/gpio.rs
- third_party/hyperdebug/repos.bzl
HyperDebug has fast DACs, meaning that we can have them generate arbitrary waveforms on the analog output pins.
This is useful for verifying that the OpenTitan ADC filters have been configured as intended, by simulating e.g. USB-PD negotiation going on "on top of" the steady state CC voltage levels.
This feature builds on the existing support for streaming binary data for bit-banging, and handling it on HyperDebug via a timer interrupt.
Current HyperDebug firmware supports short bursts of up to 2000 samples at up to 1Msps, or streamed generation of arbitrary lengths at up to around 80ksps.  (If necessary, HyperDebug firmware could be modified to allocate larger buffers, such that more than 2000 samples could be emitted at the maximum speed.)
Example commands below.
Fast USB-PD-like …
> [opentitantool] Arbitrary waveform generation via HyperDebug

- hw/ip/rv_dm/dv/sva/rv_dm_enable_checker.sv
The assertion referenced a non-existent port and was missing the direction suffix. Fix that up.
Fixes a typo from #23788
> [rv_dm,dv] Fix port name typo in rv_dm_enable_checker

- hw/ip/pinmux/rtl/pinmux.sv
- hw/ip/pinmux/rtl/pinmux_pkg.sv
- hw/ip/prim/rtl/prim_pad_wrapper_pkg.sv
- hw/top_earlgrey/chip_earlgrey_cw310.core
- hw/top_earlgrey/chip_earlgrey_cw310_hyperdebug.core
- hw/top_earlgrey/chip_earlgrey_cw340.core
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
- hw/top_earlgrey/rtl/chip_earlgrey_verilator.sv
- hw/top_earlgrey/rtl/scan_role_pkg.sv
- hw/top_englishbreakfast/rtl/chip_englishbreakfast_verilator.sv
- util/topgen/templates/chiplevel.sv.tpl
Add a ScanClock role to the scan_role_e enum, then add the scan roles of all pinmux-connected DIOs and MIOs to the pinmux. Filter any DIO or MIO with the ScanClock role from connecting to the wakeup detector flops when scanmode is active.
Use SPI_DEV_CLK as the scan clock.
> [pinmux,top_earlgrey] Add ScanClock role to SPI_DEV_CLK and filter from flop inputs during DFT

- hw/ip/usbdev/rtl/usb_fs_nb_out_pe.sv
The OUT packet engine was missing a signal to internal blocks about what happened to the just-received packet if it sent a STALL to the host. Fix this so the internal blocks correctly reset counters and free up resources given to the rejected packet.
Fixes #23806
> [usbdev] Also reject OUT packet internally when STALLing

- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_mp_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_fetch_code_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv
- hw/ip_templates/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_mp_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_fetch_code_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/flash_ctrl_base_sim_cfg.hjson
This PR is making the op_readonly_on_info in the flash_ctrl env to be controllable by plusargs.
> [flash/dv] Make the info_ro to be controlled by plusarg

- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_low_speed_traffic_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_usb_traffic_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR addresses the 'low_speed_traffic' test point by introducing the ability to generate low speed traffic on the USB.
Low speed traffic is propagated in the downstream direction by hubs when operating in a full/low-speed environment, so the DUT must be robust against the presence of such traffic. USBDEV has already been modified to prevent the reporting of spurious 'bit stuffing errors' when subjected to low speed traffic.
This PR also reduces the duration of the stress sequences because they take a long time to complete in the presence of other randomized bus events/stimuli.
For context the pertinent section of the USB 2.0 Protocol Specification is `8.6.5 Low-speed Transactions.`
> [dv,usbdev] Low speed traffic sequence

- hw/ip/usbdev/rtl/usbdev_usbif.sv
In the event that a link reset occurs at the end of receiving an OUT packet of 62 or more bytes, the same fault as observed with the OUT STALL behavior would occur, causing reception failure of the first packet post-reset.
Related to issue #23806 and the RTL change in #23807, but this additional change is from inspection/reasoning rather than (yet) being demonstrated in DV.
> [usbdev] Link reset must clear packet reception state.

- sw/device/silicon_creator/rom/rom.c
1. Remove the GIT revision.  The OpenTitan creator-product-revision ID uniquely identifies a product and its ROM version; the GIT revision is redundant.  This cuts the time spent emitting the banner from 4ms to 2ms.
2. Do not print the banner when waking from sleep.
> [rom] Adjust the ROM bootup banner

- sw/device/lib/dif/dif_i2c.c
- sw/device/lib/testing/i2c_testutils.c
- sw/device/lib/testing/i2c_testutils.h
- sw/device/tests/pmod/BUILD
- sw/device/tests/pmod/i2c_host_fram_test.c
- sw/device/tests/pmod/i2c_host_irq_test.c
The PR fixes the following tests:
- `i2c_host_eeprom_test`
- `i2c_host_hdc1080_humidity_temp_test`
- `i2c_host_gas_sensor_test`
- `i2c_host_irq_test`
This is done by updating the `i2c_testutils_wait_transaction_finish` to handle halt events correctly. The test `i2c_host_irq_test` was completely broken since it didn't compile and required a small change (see commit).
TODO:
> Fix i2c testutils

- hw/dv/sv/jtag_agent/jtag_driver.sv
There were two bugs in my code!
- The drive_jtag_test_logic_reset function didn't release TCK once the task was finished.
- If a request had the reset_tap_fsm bit set then drive_jtag_req would acquire TCK before calling drive_jtag_test_logic_reset.
Thes bugs were causing the rv_dm_tap_fsm test to fail. Fix them!
> [jtag,dv] Fix tck acquire/release in jtag_driver.sv

- hw/dv/sv/spi_agent/spi_agent_cfg.sv
- hw/dv/sv/spi_agent/spi_item.sv
- hw/dv/sv/spi_agent/spi_monitor.sv
- hw/ip/spi_device/dv/base_sim_cfg.hjson
- hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_flash_all_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_flash_mode_ignore_cmds_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
- hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv
- hw/ip/spi_device/dv/env/spi_device_env.core
- hw/ip/spi_device/dv/env/spi_device_env_cfg.sv
- hw/ip/spi_device/dv/env/spi_device_env_cov.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
en/ex4b wren/wrdis and upload commands are ignored if busy bit is set 
FCOV has been added to know when a command is ignored due to flash status busy bit being set
> [spi_device, dv] disallow certain commands if busy

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- index has to include 11 in mode SHA2_384
> [hmac,dv] SCB digest_idx issue in SHA2_384

- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_common_vseq.sv
The main change here is the second commit, with the following message:
The logic for whether debug is enabled in the dut looks like:
```
if ((otp_dis_rv_dm_late_debug_i is mubi true) ||
(the late_debug_enable register is mubi true)) {
enabled = lc_hw_debug_en_i;
} else {
enabled = lc_dft_en_i;
}
```
Before this commit, we always set `otp_dis_rv_dm_late_debug_i` to true. This commit makes it possible to depend on the register because `otp_dis_rv_dm_late_debug_i` doesn't have the "true" value.
We still aren't handling the situation where neither is a mubi true value, but that will come in a following commit.
> [rv_dm,dv] Support "late enable through register" mechanism

- hw/ip/pinmux/lint/pinmux.waiver
The corresponding mux got recently added to filter the scan clock from the wakeup detector inputs. For details, see
be4459d2b2480b4184e797458637cbf27128d020.
> [pinmux] Waive AscentLint error

- sw/device/silicon_creator/lib/drivers/uart.c
- sw/device/silicon_creator/lib/drivers/uart.h
- sw/device/silicon_creator/lib/shutdown.c
- sw/device/silicon_creator/lib/stack_utilization.c
1. The ROM banner takes about 2 ms to be sent from the UART at 115200 bps.  Rather than wait for it to complete transmission, emit the characters into the UART FIFO and proceed with boot.  Hashing the FLASH contents and performing signature verification typically will take an additional 2.4 + 4.2 ms.  There is no need to delay boot waiting for the UART.
2. Fix the ROM's terminal states to wait for UART output to complete.
> [rom] Make the banner message non-blocking

- .bazelrc
This sets the default flags for `cquery` to `--output=files`.  This is a convenience for finding the outputs of a given target with:
```
bazel cquery <some-label>
```
> [bazel] Add default flags for cquery

- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- When wipe_secret test is triggered from stress test and if the last
triggered wipe secret type is WipeSecretBeforeStart and HMAC is
enabled then rd_digest is not exercised thus wipe_secret_triggered
is not pulled back to 0.
> [hmac,dv] Fix rare issue with wipe_secret

- hw/ip/entropy_src/dv/cov/entropy_src_cov_if.sv
- hw/ip/entropy_src/dv/env/entropy_src_dut_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
This PR raises the group coverage to ~85%. Could be even more potentially.
For more information please have a look at the individual commit messages.
I had to leave in the first commit which contains an RTL fix (#23775) because without it a lot of the tests are failing (>10%).
This PR could potentially also be related to #18797.
This PR is related to [#21888](https://github.com/lowRISC/opentitan/issues/21888)
> [entropy_src/dv] Improve the group coverage

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_setup_priority_over_stall_response_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Ensure that transmission of SETUP to a STALLed endpoint clears the STALL condition. This is important in clearing protocol stall and permitting Control Transfers to the endpoint to continue.
This relates to issue #23806 and RTL changes in #23807 and #23812.
> [dv,usbdev] Setup priority over STALL response vseq

- sw/device/lib/base/BUILD
- sw/device/lib/base/hardened.h
- sw/device/lib/base/hardened_functest.c
Change the hardened check to evaluate both the requested condition and its opposite.  Land on an illegal instruction if either of the tests evaluates incorrectly.
> [rom] Improve hardened checks

- hw/top_earlgrey/dv/env/chip_common_pkg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_shutdown_exception_c_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_shutdown_output_vseq.sv
A new ROM UART banner was added to print chip version information to the UART. This broke some DV E2E test cases that did not expect such information to be printed.
Note: this depends on #23802.
> [rom_e2e,dv] fix ROM E2E DV test cases due to new ROM banner

- sw/host/opentitantool/src/command/spx.rs
A clean up fix modifying the help text for `opentitantool spx sign` command.
> [opentitantool]: clarify spx sign help message

- hw/ip/hmac/dv/env/hmac_env_cov.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- sample reg CFG from seq as cannot be done from the SCB, otherwise the sha2/key_invalid are never seen
- sample properly msg_length: the divide by 8 was not needed as we got a number of bits and that's what we need to sample actually
- add a check on error even when no error is supposed to be triggered
> [hmac,dv] Improve feature coverage

- hw/ip/hmac/dv/hmac_sim_cfg.hjson
Regression failed for some seeds due to timeout for SHA2-512 test only:
```
`UVM_FATAL (uvm_phase.svh:1512) [PH_TIMEOUT] Explicit timeout of * ps hit, indicating a probable testbench issue` has 1 failures:
* Test hmac_test_sha512_vectors has 1 failures.
* 3.hmac_test_sha512_vectors.108683676871538303991718868438741530266571739654349379393166068314816946587950\
Line 132586, in log /home/dev/src/scratch/cov_test/hmac-sim-vcs/3.hmac_test_sha512_vectors/latest/run.log
UVM_FATAL @ 1000000000000 ps: (uvm_phase.svh:1512) [PH_TIMEOUT] Explicit timeout of 1000000000000 ps hit, indicating a probable testbench issue
UVM_INFO @ 1000000000000 ps: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
--- UVM Report catcher Summary ---
```
> [hmac,dv] Increase SHA2 test vector timeout

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
Diagnosing this took me ages! In this situation (with err_type = 1), the vseq works forking into two processes. One injects an error on every stack write. The other waits until it sees a read from the stack, which should trigger an alert, and then tells the model to go into a locked state.
Once the latter process finishes, we can release our forced signals and wait until the RTL and the model raise an alert at the same time. At this point, we use "disable fork"
The first process waited for reads from the stack using the wait_for_flag() task which, in turn, used wait_for_run_completion() to detect the end of a run (at which point, we weren't going to see the flag change, so should stop early).
Unfortunately, wait_for_run_completion would sometimes wait for the end of the run by polling the …
> [otbn,dv] Avoid killing during TL read in otbn_stack_addr_integ_chk

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- Verify FIFO empty interrupt register to tackle issue #21815
- Add checks on interrupt pins when test mode is triggered via the dedicated register INTR_TEST
> [hmac,dv] FIFO empty interrupt and test mode pins

- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
This undoes a minor DV change in https://github.com/lowRISC/opentitan/pull/23817 intended to address rare issues where wipe_secret_triggered is not pulled back to 0. This conflicts with another change that was on master that was meant to do the same, so the digest prediction fails at some points. We can either just merge this fix or unmerge that other PR. 
I am still running `stress_all` and `stress_all_with_rand_reset` at my end locally to make sure though.
> [hmac,dv] Fix secret wiping issues

- hw/ip/hmac/dv/env/seq_lib/hmac_stress_all_vseq.sv
- hw/ip/hmac/dv/hmac_sim_cfg.hjson
- reduce reseeding for HMAC SHA-2/HMAC vectors tests as the randomization space is quite narrow
- remove these tests from the stress test as it doesn't bring anything
- related to this issue #23844
> [hmac,dv] Optimize regression duration

- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
This extends the timeout on outstanding accesses when issuing reset for `hmac_stress_all_with_rand_reset` to prevent the test timing out for messages/vectors where there is always outstanding accesses. This change, along with PR https://github.com/lowRISC/opentitan/pull/23848 which excludes the long HMAC/SHA-2 test vectors from this sequence, this should close https://github.com/lowRISC/opentitan/issues/23559.
This reduces to 1 commit 37cdc5fe4bc2a0d3675424be0ae11a1bbfdf541c once a previous PR gets merged.
> [hmac,dv] Extend timeout on outstanding accesses for reset test

- sw/device/silicon_creator/rom/e2e/shutdown_watchdog/BUILD
- sw/host/opentitanlib/src/transport/common/uart.rs
- sw/host/opentitanlib/src/transport/verilator/transport.rs
1. Recognize the ROM banner in the watchdog shutdown tests.
2. Be permissive about UART baudrates in tests that communicate via a pseudo-uart.
> [rom] Miscellaneous test fixups

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_sigverify_always_a_bad_b_bad_vseq.sv
This updates the ROM E2E `sigverify_always` test to check for the correct UART message, since the ROM prints a banner message since #23521 merged.
> [rom,e2e,dv] fix UART message check

- hw/ip_templates/flash_ctrl/data/flash_ctrl.hjson.tpl
- hw/top_earlgrey/ip_autogen/flash_ctrl/data/flash_ctrl.hjson
The V2S signoff for Earlgrey-PROD happened some time ago already (see lowRISC/OpenTitan#21012). This commit just updates the hjson to reflect this.
This resolves lowRISC/OpenTitan#22470.
> [flash_ctrl] Increase verification_stage to V2S

- hw/ip/i2c/dv/env/seq_lib/i2c_target_tx_stretch_ctrl_vseq.sv
The base agent sequence is unable to meaningfully drive anything, so we need to override to a sequence which can do meaningful Controller-Mode transfers.
This fixes the "	i2c_target_tx_stretch_ctrl" test, which is currently 0% passing.
> [i2c,dv] Override agent sequence for target_tx_stretch_ctrl test

- hw/dv/sv/jtag_agent/jtag_dtm_reg_block.sv
The existing code already excluded the "op" field of the register, but we actually get other mismatches as well because the "address" and "data" fields have values based on the last DMI operation. Exclude the whole register.
> [rv_dm,dv] Widen exclusion for dmi register in jtag_dtm_reg_block

- hw/ip/i2c/data/i2c.hjson
Both of these registers are sw:"rw1c"/hw:"hrw".
Fixes #22761
> [i2c,dv] Add csr test exclusions for CSR.{target,controller}_event

- hw/ip/hmac/dv/env/hmac_env_cov.sv
- message length is expressed in bits but actually, the register granularity is in byte. The coverage bins have to be reviewed in consequence.
> [hmac,dv] Fix msg_length coverage

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_idle_hint_vseq.sv
Writing a command leaves things in an untidy state for following sequences: we've either started a command and need to finish it, or we've generated an error because of the invalid command and need to clear the error.
This testpoint is about doing back-to-back DMI accesses, so there's no real need to think about abstract commands at all. Don't!
> [rv_dm,dv] Avoid writing to command in rv_dm_jtag_dtm_idle_hint_vseq

- hw/dv/sv/usb20_agent/usb20_block_if.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_freq_phase_delta_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_stream_len_max_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/env/usbdev_env.sv
- hw/ip/usbdev/dv/env/usbdev_env_cfg.sv
- hw/ip/usbdev/dv/env/usbdev_osc_tuning_if.sv
- hw/ip/usbdev/dv/tb/tb.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR adds frequency and phase delta testing in two commits:
_Commit 1:_
Adds a sequence for streaming max length packets, taking into consideration USB bit stuffing. Employing maximum length packets is critical in ensuring that the DUT continues to sample the USB signals correctly throughout the packet.
_Commit 2:_
Adds a sequence that employs the 'max length streaming' sequence to operate the DUT and host at different frequencies and phase relationships and check that all data is transferred correctly as expected, without any reliance upon retrying.
- Bus framing is performed by the host, ensuring that the SOF packets form a reliable heart beat signal every 1ms, according to the host clock frequency.
- Traffic may be sent to the DUT during each bus frame, away from the SOF packets, …
> [dv,usbdev] Frequency and phase delta sequence

- hw/ip/spi_device/data/spi_device.hjson
This should allow us to close spi-device sign-offs:
- #22473 
- #23489
> [dv + sign-off, spi_device] Bump up verif_stage to V2S

- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv
- hw/ip_templates/flash_ctrl/dv/env/flash_otf_item.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_word_sweep_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_otf_scoreboard.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_otf_item.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_word_sweep_vseq.sv
- Improve tracking of words with error injection so only one error of any kind is injected per word.
- Improve initialization of data in flash_ctrl_read_word_sweep. There is still room for improvements.
Addresses #22879
> [dv,flash_ctrl] Fix some block level failures

- sw/device/lib/testing/usb_testutils_controlep.c
- sw/device/lib/testing/usb_testutils_controlep.h
- sw/device/lib/testing/usb_testutils_diags.h
- sw/device/tests/usbdev_iso_test.c
- sw/device/tests/usbdev_mixed_test.c
- sw/device/tests/usbdev_pincfg_test.c
- sw/device/tests/usbdev_stream_test.c
- sw/device/tests/usbdev_test.c
Time out much more promptly in simulation if the configuration is not set by the DPI host; if a change breaks connectivity or communications, regression tests should not continue idling until the test is aborted.
This PR uses this timeout functionality in place of the previous indefinite loop for each of the existing tests.
Include a couple of helpful prompts for the user when these tests are run on the FPGA. (Do not issue the prompt in simulation, because logging over UART can induce test failures because of the CPU time consumed.)
> [tests/usbdev] Introduce usbdev test timeouts

- hw/ip/pinmux/fpv/pinmux_fpv.core
- hw/ip/pinmux/fpv/tb/pinmux_tb.sv
- hw/top_earlgrey/ip/pinmux/fpv/pinmux_chip_fpv.core
- hw/top_earlgrey/ip/pinmux/fpv/tb/pinmux_tb.sv
The target_cfg_t gained a couple of fields with commit be4459d2b24 and Jasper (quite reasonably) fails if its input script doesn't match.
This fixes things up in hw/ip/pinmux/fpv/tb and also hw/top_earlgrey/ip/pinmux/fpv/tb/pinmux_tb.sv.
(This is kind of required because the nightly FPV runs are currently N/A for pinmux, due to the compilation failure)
> [pinmux,fpv] Fix PinmuxTargetCfg initialiser in pinmux_tb.sv

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
UVM sequences get randomized before calling pre_start, so these
repeated calls to DV_CHECK_MEMBER_RANDOMIZE_FATAL are a bit pointless.
I tested that by implementing pre_randomize like this and looking at
the logs:
function void pre_randomize();
$display("pre_randomize()");
super.pre_randomize();
endfunction
The pre_randomize call comes out once before pre_start and then once
for each call we were doing to DV_CHECK_MEMBER_RANDOMIZE_FATAL.
> [rv_dm,dv] Get rid of unnecessary re-randomisation in base vseq

- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
- hw/ip/rv_dm/dv/sva/rv_dm_bind.sv
- hw/ip/rv_dm/dv/sva/rv_dm_enable_checker.sv
Both were using lc_hw_debug_en_i to figure out whether debug was enabled. That's correct if late debug enable is true, but is wrong if it is false. Teach them to use the right control.
The background to this change is that I'm trying to generalise the DV virtual sequences so that we sometimes don't use late debug enable. After doing so, these checks fail very quickly! This fixes the checks.
> [rv_dm,dv] Teach SVA and scoreboard about late debug enable

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_stress_all_vseq.sv
This just shows which vseq we're running (and gives a hint about how far we've got through the test).
> [rv_dm,dv] Add debug print to rv_dm_stress_all_vseq

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_raw_unlock_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_volatile_raw_unlock_vseq.sv
This fixes the ROM raw unlock test by simply adding a `override_test_status_and_finish(.passed(1));` invocation to the end of sequence body, since there is no need to wait for a flash image to boot to confirm the chip has transitioned from raw to test_unlocked0 LC states.
Additionally, this adds some console prints to the sequence to aid in debugging in the future.
> [dv] fix rom_raw_unlock test

- hw/dv/sv/csrng_agent/csrng_item.sv
- hw/dv/sv/csrng_agent/csrng_monitor.sv
- hw/ip/csrng/dv/env/csrng_env_pkg.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
This PR adds checks for the SW and HW command status signals to the scoreboard.
The error vseq still doesn't use the new checks in the scoreboard since the scoreboard is disabled.
However, I don't think it's a good use of our resources to change this right now.
This resolves [#22219](https://github.com/lowRISC/opentitan/issues/22219)
> [csrng/dv] Add checks for the cmd sts signal to the scoreboard

- hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_smoke_vseq.sv
* aon_timer TB now randomizes wdog_ctrl.pause_in_sleep in aon_timer_smoke_vseq
* aon_timer SCB now stops WDOG counting in sleep mode when pause_in_sleep is set
I have run a local regression and the passing rate seems the same as the nightly regression. And the failures (2/102) have the same failing signature as the nightly one [(report from 11/06/2024)](https://reports.opentitan.org/hw/ip/aon_timer/dv/2024.06.12_04.38.22/report.html):
```
UVM_ERROR @ 23395289269 ps: (cip_base_vseq.sv:473) [uvm_test_top.env.virtual_sequencer.aon_timer_common_vseq] Check failed exp_val == act_val (0 [0x0] vs 1 [0x1]) when reading the intr CSRaon_timer_reg_block.intr_state
```
I merged the coverage from the local regression (with tweaks to Xcelium coverage config file, [since toggle coverage is only enabled …
> [dv, aon_timer] Stimulus for wdog_ctrl.pause_in_sleep

- hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_error_cmd_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_event_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_overflow_underflow_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv
- hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
- hw/ip/spi_host/dv/env/spi_transaction_item.sv
The TB was barely using the factory to create objects. In addition there were a few places where a seq_item was created to them be overriden by popping an item from a queue.
> [dv, spi_host] Using the factory to create objects

- hw/ip/uart/dv/env/seq_lib/uart_noise_filter_vseq.sv
This commit fixes a string line break that was causing the `uart_noise_filter` test to fail.
Closes lowRISC/opentitan#23639
> [uart,dv] Fix string line break

- hw/ip/entropy_src/dv/env/entropy_src_env.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
- hw/ip/entropy_src/rtl/entropy_src_core.sv
This PR contains a couple of fixes mostly relevant for the max rate test. I recommend reviewing the commits individually.
The first two commits just fix failing tests whereas the third commit changes the behavior of the DV environment which triggers Observe FIFO overflows. The DV environment can handle these overflows correctly but it may have an impact on coverage. I am currently running a full regression with coverage.
This PR is the last missing item for and resolves #21855.
> [entropy_src] Max rate test fixes

- sw/device/tests/rv_dm_access_after_wakeup.c
The C code kept waiting for `kSoftwareBarrier` to become 1, which the DV code did set via a backdoor memory write but was not visible to SW. This caused a timeout on the DV side (the spinwait on "Entering normal sleep.").
Qualifying `kSoftwareBarrier` with `const` in the C code puts the variable into flash instead of SRAM, which fixes the problem: the value updated from DV is now visible to SW.
> [sw/tests] Fix `rv_dm_access_after_wakeup` in DV

- sw/device/lib/dif/BUILD
- sw/device/lib/dif/dif_adc_ctrl.c
- sw/device/lib/dif/dif_adc_ctrl.h
- sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c
See #23303 for explanation. In short, the ADC `FILTER_STATUS` register may a take a while to update after wake up due to the hardware writes going through the CDC. This PR fixes this issues by adding a new DIF method to wait long enough for any CDC update to finish and then uses this method in the problematic tests.
Fixes #23303
> Fix pwrmgr_sleep_all_wake_ups

- hw/top_earlgrey/doc/design/README.md
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- third_party/coremark/print_coremark_per_mhz.patch
- third_party/coremark/repos.bzl
This resolves lowRISC/OpenTitan#14330.
The first commit makes the test print out the CoreMark/MHz number which is what most people actually care about:
```
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 6193300
Total time (secs): 12
Iterations/Sec   : 1
Iterations       : 12
CoreMark/MHz     : 1.93
Compiler version : GCClowRISC Clang 16.0.2 (https://github.com/lowRISC/llvm-project.git d213f6b2e0bcc561930538ef47b3b5cc900b5b17)
Compiler flags   : Please put compiler flags here (e.g. -o3)
Memory location  : STACK
seedcrc          : 0xe9f5
[0]crclist       : 0xe714
[0]crcmatrix     : 0x1fd7
[0]crcstate      : 0x8e3a
[0]crcfinal      : 0x755b
Correct operation validated. See README.md for run and reporting rules.
PASS!
```
> [coremark] Increase CoreMark timeout, report CoreMark/MHz, update performance doc

- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
This happens if you see these events when you don't have coverage enabled. And, of course, I didn't test the code that collects coverage when I'd disabled coverage. And we run nightly tests with coverage enabled too. D'oh!
> [otbn,dv] Avoid null pointer dereference in otbn_scoreboard

- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
- hw/ip/otbn/dv/uvm/sva/otbn_idle_checker.sv
- hw/ip/otbn/dv/uvm/tb.sv
This is to allow RMA operations, as found with the `otbn_escalate` test.
Commits 1 and 3 are working around the behaviour reported in #23903 (and leave TODO notes pointing back at it). Commit 2 fixes a genuine DV bug (we wrote the environment before RMA requests were in the design)
> [otbn,dv] Weaken some checks in DV code to allow RMA operations

- hw/ip/kmac/dv/env/seq_lib/kmac_common_vseq.sv
PR lowRISC/opentitan#22794 moved the `err_processed` field from the `CFG_SHADOWED` shadow register to the `CMD` register.
However, the `shadow_reg_wr` function was not adapted. This function assumes that writing to the `CFG_SHADOWED` reg clears the update error field. As this now can only be done with the `CMD` register, this is not true anymore. Hence, this commit removes this assumption.
Closes lowRISC/opentitan#23083.
> [kmac,dv] Remove `err_processed` from shadow reg DV logic

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_dm_access_after_wakeup_vseq.sv
- sw/device/tests/rv_dm_access_after_wakeup.c
- sw/host/tests/chip/rv_dm/src/access_after_wakeup.rs
In #23924, this test got a fix for DV, which unfortunately consistently broke the test on FPGA.  The reason is that `kSoftwareBarrier` got moved to flash, which is read-only for Ibex (enforced by PMP) and thus cannot be updated by OTTF in FPGA tests.
This commit fixes the problem by splitting the software barrier variable into one in flash, which is only used when this test is executed in DV, and one in RAM, which is used when this test is executed outside DV.
> [sw/tests] Fix `rv_dm_access_after_wakeup` on FPGA

- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/doc/checklist.md
This resolves lowRISC/OpenTitan#22467.
> [csrng] Move CSRNG version 2.0.0 verification_stage to V2S

- hw/ip_templates/pwrmgr/doc/programmers_guide.md
- hw/top_earlgrey/ip_autogen/pwrmgr/doc/programmers_guide.md
Clarify that interrupt sources should be masked if they are not desired to contribute to a fall-through exit (or resumption of execution during a wait-for-interrupt exception).
CC @jettr 
Resolves https://github.com/lowRISC/opentitan/issues/23351
> [pwrmgr,doc] Clarify how interrupts should be masked for low power

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_raw_unlock_vseq.sv
Prior to this PR, `chip_sw_lc_raw_unlock_vseq` would try to read a CSR via JTAG without checking if SBA is non-busy.  The `rom_raw_unlock` test failed (for some seeds) because the SBA was indeed busy, which caused an `sbbusyerror` that never got cleared.
With this, the pass rate of `rom_raw_unlock` is 100% (tested with `-rx 10`).
> [top_earlgrey/dv] Fix `rom_raw_unlock` test

- hw/ip/rv_core_ibex/data/rv_core_ibex.hjson
This resolves lowRISC/OpenTitan#23542.
> [rv_core_ibex] Move Ibex verification_stage to V2S

- hw/ip/hmac/data/hmac_testplan.hjson
All vseqs based on `hmac_base_vseq` enable the FIFO empty status interrupt, and the scoreboard checks this interrupt (since #23749), so this testpoint gets covered by all tests based on `hmac_base_vseq`.
> [hmac/dv] Map tests to `fifo_empty_status_interrupt` testpoint

- sw/device/tests/BUILD
- sw/device/tests/spi_device_sleep_test.c
- sw/host/tests/chip/spi_device/src/spi_device_sleep_test.rs
This PR makes the spi_sleep test more robust by using gpios to sync between the device and the host.
Fix https://github.com/lowRISC/opentitan/issues/20635
> [sival, spi_dev] Refactor sleep test to wake up with gpio

- sw/device/silicon_creator/rom/e2e/release/rom_e2e_self_hash_test.c
- sw/otbn/crypto/p256_verify.s
This is a simple, lightweight hardening measure against fault-injection attacks on the loop control flow in OTBN, just in case the hardware hardening measures don't hold up as well as we'd like.
The OTBN ECDSA-P256 verification program returns two results: an "OK" value that's either `kHardenedBoolTrue` or `kHardenedBoolFalse`, and the recovered "r" value that should be equal to "r" from the signature if the signature was valid. Ibex needs to check both values.
The new counter basically just piggybacks on the existing "OK" value; instead of directly writing `kHardenedBoolTrue` into the "OK" buffer, we load the constant `kHardenedBoolTrue ^ 256` and then XOR it with a counter that gets incremented on every loop iteration. If the counter says 256 iterations, we get the right value, but if …
> [crypto] Add a counter to the main loop of ECDSA-P256 verify.

- hw/top_earlgrey/dv/env/chip_env_cfg.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_padctrl_attributes_vseq.sv
Add the following updates to **chip_padctrl_attributes_vseq**:
- Pull delay after configuring the pad pull attributes.
- "pad_in_dis_val": As the value of the pad_in differs between open source and closed source when the input is disabled, with the current configuration we are failing when the pad’s input is disabled.
> [dv, chip]: Add pull delay and pad_in_dis_val

- hw/ip/spi_host/dv/env/spi_segment_item.sv
spi_host tests are still too long for some seeds and that still needs work, but this sorts out the randomisation failure from the nightly regression
This resolves #23938
> [dv, spi_host] Randomization Failure fix

- hw/ip/otbn/dv/otbnsim/sim/sim.py
- hw/ip/otbn/dv/otbnsim/sim/state.py
- hw/ip/otbn/dv/otbnsim/stepped.py
These changes massively improve the pass rate of the `otbn_escalate` test. The first commit tracks whether we're in the middle of a secure wipe (rather than waiting for the next seed) and the second commit uses that flag to figure out when we're getting an unexpected URND ack.
The final commit is just a code cleanup which I noticed because I was touching equivalent code. But it collides with the other two commits and I thought it made the most sense to "tailgate" them.
> [otbn,dv] Improve RMA handling in model

- WORKSPACE
- rules/hooks_setup.bzl
- sw/device/silicon_creator/manuf/customization/BUILD.bazel
- sw/device/silicon_creator/manuf/customization/README.md
- sw/device/silicon_creator/manuf/customization/WORKSPACE.bazel
- sw/device/silicon_creator/manuf/customization/default_personalize_ext.c
- sw/device/silicon_creator/manuf/customization/example_personalize_ext.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
- sw/host/provisioning/ft_lib/src/lib.rs
This partially addresses #23426 by enabling SKU-owners to define their own personalization firmware extensions in separate code repositories. Additionally, this provides an example personalization firmware extension.
> [manuf] add perso extensions feature

- hw/ip/otbn/dv/otbnsim/sim/sim.py
This was caused by 597247f7614b6dcd661041a161fff19523c87b17 (and causes CI failures)
> [otbn,lint] Fix silly Python lint error

- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env.core
- hw/ip/i2c/dv/env/i2c_env_cfg.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_smbus_maxlen_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
> Note. ~~This test depends on changes from #23911, which as been squashed into the first commit. Changes from this commit should be ignored while reviewing, as it will be rebased away when that PR is merged.~~
This directed test aims to check the I2C block can absorb a max-length SMBus message
without software intervention mid-message (e.g. to drain the ACQFIFO, or handle interrupts).
- Stimulate a max-length transfer (Block-Write of 255 bytes)
- Disable all interrupt/polling based handlers
- Wait for the command-complete interrupt to signal the end of the transfer
- Readback the transfer and check it was received correctly (done via scoreboard)
A new V2 testpoint is added to track this test against.
Closes #22252 
In the future, it might be desirable to confirm the intended behaviour …
> [i2c,dv] I2C SMBus maxlen directed test

- hw/dv/sv/i2c_agent/i2c_agent.sv
- hw/dv/sv/i2c_agent/i2c_agent_pkg.sv
- hw/dv/sv/i2c_agent/i2c_item.sv
- hw/dv/sv/i2c_agent/i2c_monitor.sv
- hw/dv/sv/i2c_agent/i2c_sequencer.sv
> For reviewing purposes, ignore the first commit. It is part of #23911, and will be rebased away when that PR is merged.
This change adds more granular transaction tracking into the i2c_item type. A new `.state` field is added, which is updated by the i2c_monitor as a transfer progresses.
This more-granular measurement allows:
1) For the agent's reactive sequences to monitor in-progress transfers directly, and to drive at the appropriate points.
2) For the I2C predictor/ref_model to make more accurate predictions about inputs to the system mid-transfer. Currently we make no use of this, but it will be built upon to start modelling DUT features more precisely.
> [i2c,dv] Capture progress of transfer into i2c_item.state field

- hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_fw_ov_contiguous_vseq.sv
This commit adds some checks for the CSRs relevant for the
firmware override mode. For further information check out the 
individual commit messages and the added comments.
There is still some work to be done here.
I need to:
- add coverage for the fill state or come up with a clever way to check if the behavior for reading from the observe FIFO is as intended.
- Debug failing test sequences.
**Update** by @vogelpi: we've decided to split the work for #18837 into two parts. This PR covers the first part around the extract part / observe FIFO (FW_OV_RD_DATA) while a follow-up PR will cover the insert part (FW_OV_WR_DATA).
~~This resolves #18837~~
> [entropy_src/dv] Verify firmware override CSRs

- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/device/tests/crypto/cryptotest/firmware/sphincsplus.c
- sw/device/tests/crypto/cryptotest/firmware/sphincsplus.h
- sw/device/tests/crypto/cryptotest/json/BUILD
- sw/device/tests/crypto/cryptotest/json/commands.h
- sw/device/tests/crypto/cryptotest/json/sphincsplus_commands.c
- sw/device/tests/crypto/cryptotest/json/sphincsplus_commands.h
- sw/host/cryptotest/testvectors/data/BUILD
- sw/host/cryptotest/ujson_lib/BUILD
- sw/host/cryptotest/ujson_lib/src/lib.rs
- sw/host/cryptotest/ujson_lib/src/sphincsplus_commands.rs
- sw/host/tests/crypto/sphincsplus_kat/BUILD
- sw/host/tests/crypto/sphincsplus_kat/src/main.rs
- third_party/sphincsplus/repos.bzl
This PR is a follow-up to #21680. Adds a test harness for SPHINCS+ verify operation tests w/ SHAKE-256 in the style of the test harnesses for the algorithms in cryptolib. Structurally, the test harness has a lot in common with the ECDSA harness in #21113 and #20853, except that there is no elliptic curve parameter.
[Resolved] The dependency on #22953 exists because this PR switches the test vectors to use the `consistent-basew` version of SPHINCS+.
~Dependent on #21680~
~Dependent on #22953~
> [cryptotest] Test harness for SPHINCS+ verify operation w/ SHA-2

- hw/dv/sv/jtag_dmi_agent/sba_access_monitor.sv
- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
These commits are both changes to the DV environment to make it possible to actually write the test. Fortunately, it works after that :-)
Fixes #23900.
> [rv_dm,dv] Properly fix sba_debug_disabled testpoint

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
I messed this up with a recent refactor and the constraint ended up overriding the (correct) pinmux_hw_debug_en_c constraint in the base class with a no-op constraint in the derived class.
Fortunately, the fix is trivial: delete the bogus override.
> [rv_dm,dv] Correctly set pinmux_hw_debug_en_i in rv_dm_ndmreset_req

- hw/dv/sv/i2c_agent/i2c_agent.sv
- hw/dv/sv/i2c_agent/i2c_agent_pkg.sv
- hw/dv/sv/i2c_agent/i2c_item.sv
- hw/dv/sv/i2c_agent/i2c_monitor.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_base_seq.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_device_response_seq.sv
- hw/dv/sv/i2c_agent/seq_lib/i2c_target_may_nack_seq.sv
> ~~The first two commits in this PR are squashes of other PRs, on which we are dependent. They should both be ignored for reviewing purposes, and will be rebased away when they land.~~
> Without these two commits : 313 insertions(+), 126 deletions(-)
Fixup the i2c_agent's target-mode sequences to use the new transfer-level TLM items from the i2c_monitor (functionality added in #23955). This removes the strange partial-item messages that were passed from monitor to seqr via the 'req_analysis_port', which was inflexible and used the existing i2c_item for yet another alternate purpose. With this change, the sequences can pickup the 'in-progress' transfer item from the monitor, and observe the state of the transaction as it progresses via the `i2c_item.state` field.
The base_seq has been …
> [i2c,dv] I2C agent sequences rework for transfer-level items

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- sw/device/silicon_creator/rom/e2e/release/BUILD
This changes the ROM self hash test to run in the PROD LC state and increases the timeout.
> [rom_e2e,dv] fix ROM self hash test in DV

- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
This was occasionally a problem in the otbn_partial_wipe test, where we could see a start request which (correctly) got ignored because the model was locking itself instead.
> [otbn,dv] Explicitly drop pending start request if we lock

- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_device_timeout_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_iso_retraction_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_usb_traffic_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_config_rand_bus_type_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR adds two sequences for the remaining test points:
- IN packet retraction, for Isochronous IN traffic primarily.
- Device timeout; checks that the device recovers from missing host handshake, corruption to/loss of DATA packet and delayed host handshake; USB 2.0 protocol specification stipulates the time window within which the device must timeout and become receptive to subsequent transactions, as part of the recovery mechanism.
Note that the first of these sequences relies upon RTL changes and is not yet expected to pass on the current RTL; the RTL change is yet to be soak-tested and ratified, but this is a refinement to the behavior of a feature not presently requested or required.
> [dv,usbdev] Sequences for testing IN retraction and device timeouts

- hw/ip/otbn/dv/otbnsim/sim/insn.py
- hw/ip/otbn/dv/otbnsim/sim/sim.py
- hw/ip/otbn/dv/otbnsim/sim/standalonesim.py
- hw/ip/otbn/dv/otbnsim/sim/state.py
- hw/ip/otbn/dv/otbnsim/stepped.py
- hw/ip/otbn/dv/otbnsim/test/stats_test.py
These changes are to get the `otbn_escalate` test working properly: there was a rather "bodged" model of how secure wipe should work and it didn't match the RTL (or make sense!)
The important change is the penultimate one, which splits the "wiping" state into two pieces. This means that we correctly track "waiting for seed" before "performing the wipe", which could end up being tracked backwards in some situations before.
But this doubles the number of "wiping" states and (many years ago) I unwisely differentiated between WIPING_GOOD and WIPING_BAD to distinguish whether we expected to lock when the wipe was complete. Rather than adding *two* more states, I've merged those two states back together (in the "Merge WIPING_GOOD, WIPING_BAD" commit) so the net change is zero!
Fixes #20835 …
> [otbn,dv] Refactor FSM states in otbn simulator

- BLOCKFILE
As discussed in the meeting yesterday, we should start to block accidental ROM changes. @timothytrippel @cfrantz , it's probably fine to activate the blocker once the final ROM release tag has been created.
The ROM self hash test itself is run in CI. It fails unless the golden ROM hashes are updated in sync with potential ROM changes. Thus, it's sufficient to block changes to the ROM self hash test and the golden hashes to prevent accidental ROM changes.
> [BLOCKFILE] Block changes to ROM self hash test incl. golden ROM hashes

- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/env/i2c_env.sv
- hw/ip/i2c/dv/env/i2c_reference_model.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_may_nack_vseq.sv
> ~~The first two commits in this PR are squashes of other in-flight PRs, which we depend on here. Ignore for reviewing purposes~~.
Build on the changes in #23911 to start modelling and correctly-predicting transfers with a Target that may NACK our bytes.
The modelling in place in this PR is very rudimentary, and cannot yet make predictions when mid-transfer stimulus is applied, such as software clearing fifo state during NACK events which cause the DUT to halt. This modelling will be further fleshed-out in the future.
Map the test "i2c_host_may_nack" to the TP:host_mode_halt_on_nak.
The description and documentation of the "i2c_reference_model.sv" should be significantly fleshed-out in the future, as it will greatly increase in apparent complexity as we amend it to model and predict more …
> [i2c,dv] I2C Controller-Mode NACK modelling, mapping TP:host_mode_halt_on_nak

- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_err_vseq.sv
This PR adds the new hardened FIFO errors to the error test sequence.
This resolves [#22326](https://github.com/lowRISC/opentitan/issues/22326)
While writing the code for this commit I discovered that the hardened counter errors don't cause the error state bits for FIFO state errors to go high. We might want to discuss whether this is intended or not.
Other than that the test results look good.
I also added coverage for the newly covered errors. However I counted them as state errors, so depending on what we decide here I need to change that.
> [entropy_src/dv] Test hardened FIFO errors

- hw/ip/otbn/dv/model/otbn_core_model.sv
- hw/ip/otbn/dv/otbnsim/sim/sim.py
I added them when developing things recently and didn't notice that I'd left them in place. Oops! Take them out again.
> [otbn,dv] Remove some stray debug prints

- hw/ip/otbn/dv/otbnsim/sim/sim.py
I'd put this logic into the PRE_WIPE state but hadn't noticed that the RMA might appear when we are in the middle of a round of wiping. Match it in the WIPING state as well.
> [otbn,dv] Wipe INSN_CNT on an RMA that comes in when we're wiping

- ci/install-package-dependencies.sh
This was used to build Verilator which we now download from a bucket.
We're getting this old GCC from a separate repository which is currently having network issues. Removing this dependency saves time and makes CI less fragile.
> [ci] Remove gcc-9 from packages in CI

- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
This PR adds prediction for the FW_OV_RD_FIFO_FULL CSR to the scoreboard.
Some clean up for the observe FIFO read prediction is also included.
For further information check the individual commit messages.
Resolves [#18837](https://github.com/lowRISC/opentitan/issues/18837)
> [entropy_src/dv] Predict FW_OV_RD_FIFO_FULL

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/doc/registers.md
This PR documents what happens when the fw_ov_rd_data register is read when the observe FIFO is empty.
> [entropy_src/doc] Document the fw_ov_rd_data read when empty behavior

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/doc/checklist.md
This resolves lowRISC/OpenTitan#22469.
> [entropy_src] Move ENTROPY_SRC version 2.0.0 verification_stage to V2S

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_dmi_failed_op_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_idle_hint_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This was reasonably fiddly because causing the failure requires back-to-back JTAG writes to the dmi register, and the race window isn't very wide.
Fixes #17034.
> [rv_dm,dv] Implement jtag_dmi_failed_op testpoint

- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_regwen_vseq.sv
- hw/ip/csrng/dv/tests/csrng_base_test.sv
This PR contains a couple of commits to verify some CSRs added close to RTL freeze:
1. INT_STATE_READ_ENABLE[_REGWEN] CSRs, see #23827
2. RESEED_COUNTER CSRs, see #23826
For details, please refer to the commit messages.
> [csrng/dv] Check RESEED_COUNTER and INT_STATE_READ_ENABLE

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_debug_disabled_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_sba_debug_disabled_vseq.sv
This PR looks a bit massive, but it actually builds on some existing PRs.
- #23750: This contains commits 1,2
- #23792: This contains commits 3,4
- #23793: This contains commit 5
The remaining commits are:
- [rv_dm,dv] Explicitly control lc_dft_en_i
- [rv_dm,dv] Configure scanmode as a bit instead of a mubi4_t
- [rv_dm,dv] Config lc_hw_debug_en as a bit, not a 4-bit variable
- [rv_dm,dv] Get rid of unnecessary re-randomisation in base vseq
They have detailed commit messages, but the overriding aim is to simplify the way the underlying `rv_dm_base_vseq` controls the enable/disable of debug features.
> [rv_dm,dv] Tidy up randomisation of "enable signals" in base vseq

- hw/top_earlgrey/data/chip_testplan.hjson
Delete testpoint because the functionality that it describes does not exist. There is no such CSR/signal.
> [dv,chip] Delete legacy USBDEV-related test

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
This PR looks reasonably large because it depends on #23799. Once that has been merged, there are two remaining commits:
- *[rv_dm,dv] Make DMI bringup in base vseq depend on pinmux connection*
- *[rv_dm,dv] Use the "right enable" in \*_jtag_dmi_debug_disabled_vseq*
The first commit is a tidyup in the base vseq (which I noticed when trying to fix the vseq for the second commit). The second commit is the main point of this PR. Its commit message is as follows:
*[rv_dm,dv] Use the "right enable" in \*_jtag_dmi_debug_disabled_vseq*
The code here was a bit broken and I clearly hadn't previously
understood the difference between "pinmux enabled" and "debug
enabled".
The *whole point* of this test is supposed to be that DMI transactions
get blocked when pinmux is not enabled. After the changes …
> [rv_dm,dv] Use the "right enable" in *_jtag_dmi_debug_disabled_vseq

- hw/ip/aes/data/aes.hjson
- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/otbn/data/otbn.hjson
- hw/ip/pattgen/data/pattgen.hjson
- hw/ip/pinmux/data/pinmux.hjson.tpl
- hw/ip/rom_ctrl/data/rom_ctrl.hjson
- hw/ip/rv_core_ibex/data/rv_core_ibex.hjson
- hw/ip/rv_dm/data/rv_dm.hjson
- hw/ip/spi_host/data/spi_host.hjson
- hw/ip/usbdev/data/usbdev.hjson
- hw/ip_templates/alert_handler/data/alert_handler.hjson.tpl
- hw/ip_templates/clkmgr/data/clkmgr.hjson.tpl
- hw/ip_templates/pwrmgr/data/pwrmgr.hjson.tpl
- hw/ip_templates/rv_plic/data/rv_plic.hjson.tpl
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.hjson
- hw/top_earlgrey/ip_autogen/clkmgr/data/clkmgr.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/data/pwrmgr.hjson
- hw/top_earlgrey/ip_autogen/rv_plic/data/rv_plic.hjson
The algorithm to determine the HW IP block version numbers is described in issue #22222.  This resolves #22222.
> [hw] Align HW IP block versions for Earlgrey-PROD

- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/spi_host_config_test.c
- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/test_utils/bitbanging/i2c.rs
- sw/host/opentitanlib/src/test_utils/bitbanging/mod.rs
- sw/host/opentitanlib/src/test_utils/bitbanging/spi.rs
- sw/host/tests/chip/i2c_target/src/main.rs
- sw/host/tests/chip/spi_device/BUILD
- sw/host/tests/chip/spi_device/src/spi_host_config_test.rs
1. Send four packets from the host to the device, each one with a different configuration for cpol and cpha.
2. The device should receive the packets and be able to decode them with the appropriated configuration.
Fix https://github.com/lowRISC/opentitan/issues/19036
Fix https://github.com/lowRISC/opentitan/issues/19844
> [Sival, Spi host]  Config test CPOL and CPHA

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_ast_clk_rst_inputs_vseq.sv
- sw/device/tests/sim_dv/ast_clk_rst_inputs.c
This test previously configured the ENTROPY_SRC in Firmware Override: Extract and Insert mode and erroneously enabled the routing of entropy to firmware (ENTROPY_DATA register). Also the entropy source was reconfigured multiple times during the test.
This commit modifies the test to 1) use the Firmware Override: Observe mode in which entropy is observable from the Observe FIFO but also continues to flow through the pipeline to CSRNG and the EDNs, and 2) to not re-configure the entropy source but just drain the observe FIFO to restart the entropy re-collection.
In addition, the default_spinwait_timeout_ns value in the vseq is updated together with the run_timeout_mins to avoid random timeouts. Also a check that the observe FIFO is empty when we come out of deep sleep is removed. This check …
> [chip-test,sival] Optimize ENTROPY_SRC config for ast_clk_rst_inputs

- hw/ip/i2c/data/i2c_testplan.hjson
This test is currently broken, and the feature is unused by any test software, and only has a cursory mention in the programmers guide. It's purpose was to detect invalid bus driving by the I2C-Controller, when a STOP condition was received at an earlier point that expected during a READ transfer. This is valid I2C bus behaviour, but likely an unexpected early-termination of a transfer.
In short, I believe the logic to generate this IRQ is no longer functional due to the addition of the multi-controller arbitration logic. A comment was made to this effect in the code at the time.
https://github.com/lowRISC/opentitan/blob/44d2f94d7b73b6bdcc85e1bac190bd00e243c160/hw/ip/i2c/rtl/i2c_core.sv#L487-L489
I tried to fix this test as part of #23987, at which point I realized it was unfixable as …
> [i2v,dv] Move TP:target_error_intr / i2c_target_unexp_stop to V3

- hw/dv/sv/i2c_agent/i2c_agent_cfg.sv
- hw/dv/sv/i2c_agent/i2c_driver.sv
- hw/dv/sv/i2c_agent/i2c_monitor.sv
- hw/ip/i2c/dv/env/i2c_env_cfg.sv
- hw/ip/i2c/dv/env/i2c_reference_model.sv
- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_fifo_full_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_host_mode_toggle_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_hrst_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_perf_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_smoke_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_target_stress_all_vseq.sv
This is a bunch of smaller fixes, and cleanups that happened along the way, to get the overall I2C block-level regression back up to V2(S) levels.
Review commit-by-commit, see commit messages for more details about each failure. Most of these failures just came about from previous DV changes to model I2C transfers properly, but some are stragglers due to previous RTL changes.
The final commit removes the `i2c_target_ack_stop_vseq` from the target_stress_all test, as I believe this test is no longer functional due to a small RTL bug. See #24010 for more details.
--- 
`./util/dvsim/dvsim.py hw/ip/i2c/dv/i2c_sim_cfg.hjson -i all_once --tool vcs --reseed 10 --cov`
> [i2c,dv] I2C regression fixes

- hw/ip/i2c/data/i2c.hjson
This moves the I2C HWIP block to V2S, as described in the signoff review issue #22108.
> Note. there are a few in-flight PRs (#23987, #24010) that need to be merged before this one. When they are merged, the lightweight signoff criteria bullets in the signoff issue [comment here](https://github.com/lowRISC/opentitan/issues/22108#issuecomment-2152850795) will be updated to reflect the latest status, particularly related to regression pass rates and coverage numbers.
As detailed in the signoff issue, this is a verification signoff limited to a certain scope of features. 
Signoff review issue : #22108.
V2S checklist : [#22108_checklist_comment](https://github.com/lowRISC/opentitan/issues/22108#issuecomment-2152850795)
V2S qualifying criteria : …
> [i2c,dv] Move I2C to hardware development stage V2(S)

- hw/top_earlgrey/formal/conn_csvs/ast_mem_cfg.csv
- hw/top_earlgrey/formal/conn_csvs/lc_ctrl_broadcast.csv
This commit re-aligns the top-level connectivity specs with the RTL updates since Eargrey ES. These are:
- Update SPI_DEVICE and USBDEV memory paths for memory test port connections from AST.
- Update lc_rma_req/ack signals between LC_CTRL, FLASH_CTRL, OTBN. There are now dedicated connections and we no longer daisy chain things.
> [top_earlgrey, conn] Update top-level connectivity specs

- hw/top_earlgrey/formal/chip_conn_cfg.hjson
- hw/top_earlgrey/formal/conn_csvs/alert_handler_esc.csv
The escalation sender and receiver pairs need to connect to the same clock and reset signals, or they can malfunction.
This adds a connectivity configuration for these tests, but it is expected to fail due to the mis-connection of pwrmgr rst_ni described in #23888.
Fixes #14887
> [conn,alert_esc] Check escalation sender/receiver connectivity

- hw/dv/dpi/usbdpi/usbdpi.c
Shorten the length of the EOP SE0 signaling to the correct 2 bit intervals on SETUP and OUT DATA packets.
USBDEV has always coped with the incorrect SE0 duration but because of the extra traffic checking in the block level testing, the usb20_monitor was flagging up the SETUP/OUT DATA packets as invalid.
> [dv,usbdev] Fix length of DATA packet EOP

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
- hw/ip/rv_dm/dv/tb.sv
This is part of what is tracked in #22048, which wanted to make sure we were testing the new behaviour that we have added to rv_dm to make it track ndm resets properly.
The first commit is a "wiring tidyup" which makes sure that the signals are being driven properly. I'm not sure it was strictly needed, but this avoids some X's propagating through the design. The second commit strengthens the vseq and tries to check that the feature works properly.
> [rv_dm,dv] Extend ndmreset test to check the reset pins are corrected properly

- hw/ip/usbdev/dv/README.md
- hw/ip/usbdev/dv/doc/tb.svg
This PR updates the DV documentation for USBDEV to reflect the changes to the DV environment:
- Inclusion of the additional support modules and interfaces within the testbench.
- Addition of covergroups for the collection of functional coverage.
- Modifications to the `usbdev_scoreboard` class to perform the checking of register traffic and USB packet responses against expectations produced by a functional model of USBDEV.
- Inclusion of the functional model that predicts the desired response of the DUT to any USB stimulus such as packet transfers and bus-level events including suspend-resume signaling, bus resets and connections/disconnections.
Thanks to Elliot Baptist <elliot.baptist@lowrisc.org> for creating the block diagram.
> [dv,usbdev] Update USBDEV DV documentation

- hw/dv/sv/jtag_agent/jtag_agent_cfg.sv
- hw/dv/sv/jtag_agent/jtag_monitor.sv
- hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
- hw/vendor/patches/pulp_riscv_dbg/0008-dmi_jtag_tap-fix-tap_state_q.patch
- hw/vendor/pulp_riscv_dbg/src/dmi_jtag_tap.sv
This fixes upstream issue pulp-platform/riscv-dbg#165 by applying upstream PR pulp-platform/riscv-dbg#169.  The change gets applied in a patch to avoid re-vendoring, which would be inconvenient at the current time.
This also reverts commit bd76d9282f14aad8ddb9ec276948320df59535e3 "[jtag,dv] Allow the jtag monitor to "reset" to a different TAP state" and commit 3b41400f100577e17ab66f18b16677880dc47445 "[rv_dm,dv] Teach environment about TAP's reset FSM state", which together replicated this problem in our DV code.
This fixes #24019.
> [hw/pulp_riscv_dbg] Fix reset value of `tap_state_q`

- hw/vendor/lowrisc_ibex.lock.hjson
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/env/core_ibex_dut_probe_if.sv
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_core.sv
96a1c02ba03400a8b0d69f08b97004adc436dfb7
* [dv] Increase iterations and instructions in riscv_rf_intg_test (Greg Chadwick)
* [dv] Alter riscv_rf_intg_test to cover more scenarios (Greg Chadwick)
* [rtl] Fix logic for generating ECC related alerts (Greg Chadwick)
> Update lowrisc_ibex to lowRISC/ibex@96a1c02b

- hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv
The `chip_csr_mem_rw_with_rand_reset` has been constantly failing in the nightly regression since early Feb when we've implemented changes in `cip_base_vseq.sv` and `csr_seq_lib.sv`. I am not quite sure why the test has been passing before but all the failures I've seen are due to timeouts inside the sequence. More precisely, the sequence first checks all 2612 CSRs and these checks are done back to back without opening a window for the test to perform a reset. For this to happen, the test expects a window without any outstanding CSR accesses. By default, the test waits for up to 10000 clock cycles until getting such a window without outstanding CSR accesses. Obviously, 10000 clock cycles are not fast enough for write-read-checking 2612 CSRs and that's why the test has had a 100% fail rate …
> [chip-test] Fix chip_csr_mem_rw_with_rand_reset test

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_hartsel_warl_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This is the extra check discussed in #22048. The second commit adds the check, but it didn't work at first! This turned out to be a silly DV bug, fixed in the first commit.
> [rv_dm,dv] Add WARL check for hartsel

- hw/top_earlgrey/formal/conn_csvs/ast_infra.csv
For Earlgrey-PROD, we've added the possibility to disable the inputs of pads to save idle power. The feature is controlled by pinmux and after reset, all pad inputs must be enabled. This commit adds the corresponding conditions to the connectivity specification.
> [top_earlgrey, conn] Reflect pad input disable in connectivity specs

- sw/device/silicon_creator/lib/drivers/hmac.c
- sw/device/silicon_creator/lib/drivers/hmac.h
- sw/device/silicon_creator/lib/drivers/hmac_functest.c
- sw/device/silicon_creator/lib/drivers/hmac_unittest.cc
- sw/device/silicon_creator/lib/sigverify/sphincsplus/hash_sha2.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/sha2.c
- sw/device/silicon_creator/lib/sigverify/sphincsplus/thash_sha2_simple.c
- sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/ft_personalize.c
- sw/device/silicon_creator/rom/e2e/release/rom_e2e_self_hash_test.c
- sw/device/silicon_creator/rom/rom.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
This updates the HMAC silicon_creator driver to separate out the `hmac_sha256_process()` call from the `hmac_sha256_final...()` calls to avoid sending multiple process commands to the hardware, and thus triggering an SVA in sim (see #23954). While the consensus in #24022 was that the hardware can handle multiple `process` commands, this path is less tested. Hence, we make this update to minimize risk in the ROM code that drives the HMAC SHA2 engine.
This updates the ROM, and fixes #23954. A new rom release candidate will tagged after this merges.
> [silicon_creator,hmac] ensure `process` cmd is only invoked once

- hw/dv/sv/jtag_agent/jtag_driver.sv
Using the DV_WAIT macro causes a failure if the signal doesn't go high again in time. The driver shouldn't really be checking for things like this: it should just wait until we come out of reset.
> [dv,jtag] Don't constrain wait for trst_n to be de-asserted

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
It turns out this sometimes was too tight in
rv_dm_tap_fsm_rand_reset. (And if the DV_WAIT timed out, we wouldn't run the DV_CHECK_FATAL anyway). Make the code simpler, and stop it failing for silly reasons.
> [rv_dm,dv] Remove upper bound from trst_n wait

- hw/ip/rv_dm/dv/sva/rv_dm_enable_checker.sv
These signals mostly need some response before they drop (e.g. the a_valid signal, which won't drop without a_ready). If one is asserted and then debug stops being enabled before we get a response, it's ok. The thing that isn't allowed is for one of those signals to *become* asserted when debug is not enabled.
> [rv_dm,dv] Weaken enable checker to allow "left over" items

- sw/device/lib/testing/json/provisioning_data.h
- sw/host/provisioning/cert_lib/BUILD
- sw/host/provisioning/cert_lib/src/lib.rs
- sw/host/provisioning/ft_lib/src/lib.rs
This moves the FT certificate utility functions to a separate library to facilitate building different provisioning test programs for different SKUs. This partially addresses #23426.
> [manuf] move FT cert operations to lib     

- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
Some automated CSR tests may actually trigger encryption operations without reading the result. Previously, this could cause the post_body() task to timeout. As the scoreboard is anyway disabled for these tests, meaning the produced finish_message variable isn't read, we can simply skip the detection of the final message end.
This resolves lowRISC/OpenTitan#23475.
> [aes/dv] Only detect the final message end if the scoreboard is enabled

- hw/ip/csrng/dv/env/csrng_scoreboard.sv
Previously, we would erroneously exit the task when handling a disable while waiting for entropy. After this point, the scoreboard would no longer perform any checks on the command FIFO, no longer update the internal state, and no longer compare the generated bits of the corresponding app. This is bad in two ways: either it can go completely unnoticed or lead to failing checks when comparing internal states between the scoreboard and the DUT using check_internal_state().
Luckily, the fix is easy. We can just replace the `return` keyword by a `continue` to drop the current item of the queue and start over in case of a disable.
> [csrng/dv] Don't exit process_csrng_cmd_fifo() task upon disable

- sw/host/tests/chip/gpio/src/sleep_pin_retention.rs
- sw/host/tests/chip/spi_device/src/spi_host_config_test.rs
A noop change, the result of executing
bazel run //quality:rustfmt_fix'
> fix format to keep rustfmt happy

- hw/ip/otbn/util/shared/BUILD
- hw/ip/otbn/util/shared/testgen.py
- rules/otbn.bzl
- sw/otbn/crypto/tests/generated/BUILD
- sw/otbn/crypto/tests/generated/mul_test.s
- sw/otbn/crypto/tests/generated/mul_testgen.py
This is a slight expansion of the existing OTBN test infrastructure that allows us to generate test data based on a known-good implementation. This PR includes both the infrastructure and an example that tests our bignum `mul` implementation against test data that generates some numbers and then multiplies them in Python.
Since Bazel doesn't allow _actually_ random generation of numbers at build time, I included a "seed" argument that gets passed through from the `BUILD` file to seed the pseudorandom test-data generation. The test data for the first test (seed = 0) will always be the same on every build, and so will the test data for the second test, etc, as long as the test-generation script is the same. But they will be different from each other, so by repeating the target 10 times like …
> [otbn,bazel] Add a way to generate random-ish tests for OTBN.

- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_spi_device_pinmux_sleep_retention_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/tests/BUILD
- sw/device/tests/spi_device_sleep_test.c
Lots of firing assertions have been popping up due to Xs. These have been bypassed by disconnecting interfering signals accordingly.  
The test now checks :
1. the pinmux (spi-dev) outputs are set to 1 when sleeping
2. the pinmux (spi-dev) outputs are set to 0 when sleeping
3. The core wakes up when driving a spi txn (toggling the CSB line)
A screenshot of the waves:
One can see how the core goes to sleep after setting `IOA8=1` and wakes up when deasserting for steps 1 and 2. 
Also for step 3) the core wakes up after the CSB line is set low (although just toggling it would be enough).
> [tlt, dv] spi_device/pinmux sleep/retention test

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
- hw/dv/sv/dv_base_reg/dv_base_reg.sv
- hw/ip/rv_dm/data/rv_dm.hjson
- util/reggen/README.md
- util/reggen/reg_block.py
- util/reggen/register.py
- util/reggen/uvm_reg_base.sv.tpl
This is really for `rv_dm` (see the last commit). But the idea is that we've currently got some code in `cip_base_vseq__tl_errors.svh` that tries to generate bad writes by sending an invalid mask value. The `stress_all_with_rand_reset` sequence is supposed to be checking that those writes won't have any effect.
Unfortunately, they *do* have an effect for some registers in `rv_dm`. I don't *think* this behaviour is disallowed by the TileLink spec, so the correct response is probably to avoid depending on the writes being squashed.
> [dv] Add "writes_ignore_errors" flag

- hw/dv/sv/dv_lib/dv_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
This was wrong twice in the same direction. The first commit tidies up a factor of 1000 in the rv_dm code, then the second commit tidies up another factor of up to 10 in the base dv code.
> [rv_dm,dv] Tidy up reset length calculation

- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
I think this is a (very minor) bug in the riscv-dbg RTL. Reported upstream at https://github.com/pulp-platform/riscv-dbg/issues/170.
> [rv_dm,dv] Weaken IDCODE check

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_dm_inactive_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_stress_all_vseq.sv
These are small changes. The first one handles a situation where we've issued a CSR read which has stopped early because we are in reset (and obviously won't have seen the right value).
The other two concentrate on stopping the sequence if we wish to issue a reset. Honestly, I think the correct behaviour will be for the base classes to issue the resets unconditionally and for the IP classes to handle this. But that's a much bigger change and these are minimal tweaks to make the vseq work at all with the current structure.
> [rv_dm,dv] Minor tweaks to rv_dm dv code to work with stress_all_with_rand_reset

- sw/device/lib/base/macros.h
- sw/device/lib/runtime/ibex.h
- sw/device/lib/runtime/log.h
- sw/device/lib/testing/alert_handler_testutils.c
- sw/device/lib/testing/aon_timer_testutils.c
- sw/device/tests/aon_timer_irq_test.c
- sw/device/tests/sim_dv/otp_ctrl_lc_signals_test.c
- sw/device/tests/sram_ctrl_subword_access_test.c
When an argument (to be formatted via format specifiers in a given string) is passed to the `LOG` function either directly or indirectly, this value is then later read from the `va_list` using the `va_arg(va_list ap, type)` function. In the case of DV logging via the C->SV backdoor (bypasses UART, speeding up DV simulation) this is always read as a `uint32_t`. In the case of core logging (on Ibex), this is either `uint32_t`, `size_t`, `uintptr_t` or `status_t` (a struct storing an `int32_t`).
As a result, when a 64 bit integer is passed into some debug logging functionality without appropriate explicit casting, no implicit casting is performed as may be expected, and instead the 64 bit integer argument is read as a 32 bit width argument.
As per N1570 7.16.1.1 paragraph 2: 
> ... if type …
> [sw, lib] Add compile-time check for log arg size to prevent undefined behaviour in logging 

- hw/dv/sv/csr_utils/csr_utils_pkg.sv
If we are trying to read a CSR and are in reset, the operation isn't going to work. This change makes it so that we exit immediately (setting the status to UVM_NOT_OK) rather than blocking indefinitely.
> [dv] Add a quick exit in csr_rd_sub when in reset

- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
Similar as https://github.com/lowRISC/opentitan/pull/24083, this issue came up after the merge of this PR during the regression triage meeting.
- As observed for some other tests: they are going into timeout with 200ms, the worst case seen is running the 126th message when failing over 200. Which leads me to increase the timeout to more than the double to have margin.
> [kmac,dv] Increase timeout

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_ctrl_scrap_vseq.sv
This PR solves a problem in CS where external clock transition request might complete in the middle of booter operations, where the booter will read values from the OTP and write them to AST registers upon startup. 
Changes:
- Waiting for the boot process to end (`sync_with_sw`) before changing to external clock and performing a LC state transition
- Waiting for`LC_CTRL.STATUS.EXT_CLOCK_SWITCHED == 1` in order to be sure the external clock is switched and stable
> [dv/chip] fixed chip_sw_lc_ctrl_scrap_vseq

- hw/dv/sv/usb20_agent/usb20_agent_pkg.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
This PR fixes decoding of packets in the `usb20_monitor` and tidies up object creation via the UVM factory.
It then simplifies the collection of DATA packets and then ensures that monitor listens to d/se0 only when the DUT is transmitting, because those lines are driven only by the DUT and not `usb20_driver` so the monitor was not seeing all of the traffic.
> [dv,usbdev] Monitor fixes

- hw/top_earlgrey/data/ip/chip_rv_dm_testplan.hjson
- sw/host/opentitanlib/src/debug/dmi.rs
- sw/host/tests/chip/rv_dm/src/control_status.rs
- sw/host/tests/chip/rv_dm/src/ndm_reset_req.rs
Fix #22044
For the WARL `hartsel`:
* The existing code already tests the WARL behaviour, update the testplan to match.
* The hartsel mask retrieval code is moved to a dedicated function for clarity.
For the anyhavereset:
* Replace OpenOCD reset command with explicit manipulation of `ndmreset` in dmcontrol
* Check `anyhavereset` stays low before releasing ndmreset
* Check that it goes have after releasing `ndmreset`
* Note that it's not feasible to observe the period between `ndmreset` release and `anyhavereset` going high, because JTAG is too slow compared to reset.
> [rv_dm, sival] test WARL hartsel and anyhavereset

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_power_virus_vseq.sv
- sw/device/tests/power_virus_systemtest.c
Bad i2c_agent timing parameters have been causing the power_virus test to fail. This commit fixes this, by using the algorithm in `chip_sw_i2c_host_tx_rx_vseq.sv` to create a derived timing configuration for the agent.
In the future, we shouldn't be handcrafting a set of timing parameters like this. Hopefully this sort of calculation will be centralized into a library of-sorts. That future improvement is already tracked in #23920.
Tested locally with the following command, which passes. This is what is run by the nightly regression.
```
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_power_virus --tool vcs --fi 1
```
> [dv,tlt,i2c] Fixup i2c_agent timing parameters in power_virus test

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_spi_device_pinmux_sleep_retention_vseq.sv
The CSB pulse needs to be long enough (at least a whole AON clock cycle) in order to be detected by pinmux and waking up the chip. 128 and over are sizes which suffice the pulse duration needed.
> [tlt, dv] spi_device/pinmux retention fix

- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- util/topgen/templates/chiplevel.sv.tpl
As requested by the PD team.
This resolves lowRISC/OpenTitan#24132.
> [chip_earlgrey_asic] Enable pull-up setting for power-on reset

- hw/ip/prim/rtl/prim_count.sv
This is related to lowRISC/OpenTitan#24119.
> [prim_count] Register err_o to avoid potential CDC issues downstream

- doc/getting_started/setup_fpga.md
- hw/ip/otp_ctrl/data/earlgrey_skus/prodc/BUILD
This adds a personalized prodc OTP image with SPX+ sigverify enabled for the purposes of splicing the latest cached bitstreams with this OTP image for validating owner firmware payloads.
Additionally this adds instructions to the website to explain how to use the `universal_splice` Bazel target to splice custom bitstreams.
> [otp,doc] add prodc OTP image with SPX+ enabled

- hw/ip/prim/dv/prim_esc/tb/prim_esc_tb.sv
- hw/ip/prim/fpv/vip/prim_esc_rxtx_assert_fpv.sv
- hw/ip/prim/rtl/prim_esc_receiver.sv
This is related to lowRISC/OpenTitan#24119.
Note, this is most likely needed on top of flopping the error output of the prim_count instances (#24125) as there is some further combinatorial logic on the counter error output in the escalation receiver. For example, we also check the output value of the counter and AND all bits together. To be safe, we should also latch the escalation request output as done in this PR. Otherwise, you can e.g. get a false escalation request if the counter switches from say 4'b1000 to 4'b0111.
> [prim_esc_receiver] Register esc_req_o to avoid potential CDC issues

- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
For circa 10% of seeds the link state prediction lagged the observation and reporting of Resume Signaling by the DUT (an artefact of the fact that usb20_monitor is sampling on a fixed clock even throughout the Suspend Signaling).
> [dv,usbdev] Fix usbdev_rand_suspends sequence

- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
This doesn't actually add any testing, but it avoids a quick error path when a stress test tries to write the late_debug_enable_regwen register.
Eventually, we should probably check that the register *does* something useful. This change is much simpler than that: it just stops the random write from causing the test to fail for a silly reason.
> [rv_dm,dv] Add late_debug_enable_regwen to scoreboard list of regs

- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/rv_core_ibex_mem_test.c
- sw/device/tests/sival/BUILD
This is cherry-pick of #23254 to master, needed because in master `<IP>_regs` is renamed to `<IP>_c_regs`.
> Cherry-pick to master: [sival, rv_core_ibex] make rv_core_ibex_mem_test work on silicon

- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_test_vectors_kmac_vseq.sv
Linked to this issue #22341
I am not sure it works well yet. I have only checked it for one test, and it seems good from what I've seen.
This check is not modeling the FIFO level, instead it is using the FIFO empty/full from the DUT through a backdoor access. Then it does a prediction on the FIFO empty interrupt as described in the [KMAC register doc](https://opentitan.org/book/hw/ip/kmac/doc/registers.html#intr_state--fifo_empty).
> [kmac,dv] Check FIFO empty interrupt

- hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
There can't be multiple requests outstanding (because this is fundamentally driven by a single chain of DMI accesses). Drop max_outstanding_req accordingly, which avoids tl_agent_cov trying to collect coverage for lots of requests outstanding.
> [rv_dm,dv] Set max_outstanding_req for the SBA TL agent

- hw/ip/rv_dm/dv/cov/rv_dm_cov_excl.el
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_halt_resume_whereto_vseq.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
These are minor tweaks in `rv_dm_halt_resume_whereto_vseq` to try to improve condition coverage numbers.
It feels a little bit silly to go much further, because the conditions and branches in `dm_mem` are all about deciding what instruction to manufacture for the core to execute. I don't think it would make much sense to put more effort into seeing lots of those instructions, only to ignore the values that come out (since `rv_dm` testing doesn't really care about what instructions get generated by the debug module).
A sensible approach might be to waive a large tract of the relevant conditional coverage and note that we're not really trying to test the internals of the pulp debug module. But that's definitely a problem for a different PR.
> [rv_dm,dv] Improve the coverage we get from reading WhereTo address

- BLOCKFILE
For some reason, we did not have `chip_earlgrey_asic.sv` in the BLOCKFILE nor the template used to generate it. Including the template is not needed as this also impacts the FPGA chip-level files. But we should at least include the generated ASIC file.
> [BLOCKFILE] Add top_earlgrey.sv and chip_earlgrey_asic.sv files

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_dataaddr_rw_access_vseq.sv
This test is pretty trivial: it's just supposed to be checking that values written over TL to a certain pair of registers are visible over DMI.
This rewrite makes the code a bit easier to read. The behaviour is still the same.
> [rv_dm,dv] Rewrite and simplify rv_dm_dataaddr_rw_access_vseq

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
This fixes an ENUMERR build failure when build with Xcelium.
> [rom_ctrl,dv] Explicitly cast the return value of get_invalid_mubi4

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
This is a sequence of "tidy-up" commits (with detailed commit messages) which I made because I had a rather confusing time on Friday trying to understand how all of this is supposed to work. No big functional change (except minor cleanups) but there are now documentation comments and it should be slightly easier to read.
> [dv] Tidy-up in tl_errors_vseq_sub

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
This was originally added in a0f850982d2 and used in rv_dm_cmderr_busy_vseq. I rewrote that vseq in 85f9684 (tidying things up and adding comments about what it did) but didn't realise that the task was left hanging.
Remove it.
> [rv_dm,dv] Remove unused read_chk task

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_hart_unavail_vseq.sv
No functional change, but it should be a bit simpler to read what's going on.
> [rv_dm,dv] Rewrite rv_dm_hart_unavail_vseq to make it easier to read

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_halted_vseq.sv
This isn't really needed for the testpoint and I don't believe it strengthens our confidence in the design. Drop the repetition.
> [rv_dm,dv] Avoid repetition in rv_dm_mem_tl_access_halted_vseq

- hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/entropy_src_fw_override_test.c
This commit extends the entropy_src_fw_override_test to also test whether the entropy can be inserted with a significant delay after reading from the observe FIFO. Another extension is for testing whether the entropy_src can be reenabled without reenabling the rest of the entropy complex.
I tested it on FPGA and the test passes.
`bazel test //sw/device/tests:entropy_src_fw_override_test_fpga_cw310_sival_rom_ext --test_output=streamed --nocache_test_results`
I'm not sure what qualifies as a "significant" delay. I just did 128 micro seconds. For 100Mhz this should be ~12800 cycles.
That should probably be enough but it's still worth discussing.
Resolves [#22705](https://github.com/lowRISC/opentitan/issues/22705)
> [chip-level/sw] Extend the entropy_src_fw_override_test

- hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_smoke_vseq.sv
- hw/ip/rom_ctrl/dv/rom_ctrl_base_sim_cfg.hjson
This was driven by me trying to fix (very sporadic) smoke test failures. Annoyingly, they still happen very sporadically after this change, but the test has got rather quicker and is slightly easier to read.
> [rom_ctrl,dv] Minor tidy-ups in smoke vseq

- hw/ip/otbn/dv/otbnsim/sim/sim.py
This was a cycle too late if we got an escalation request when were were in the middle of a secure wipe. The reason is that we checked lock_after_wipe in the _delayed_insn_cnt_zero function just before setting the flag.
The fix is to set the flag *before* checking it...
> [otbn,dv] Correct timing for when INSN_CNT gets zeroed in model

- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
This decouples the flash info certificate page configuration functions from the specific certificate pages to enable configuring different personalization flows for different SKUs, where different SKUs may have a different number of certificates. This partially addresses #23426.
> [silicon_creator,flash_ctrl] decouple cert page configs

- hw/ip/usbdev/dv/env/seq_lib/usbdev_data_toggle_restore_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_rx_full_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_bfm.sv
- hw/ip/usbdev/dv/env/usbdev_env_cfg.sv
- hw/ip/usbdev/dv/env/usbdev_env_cov.sv
This PR addresses a couple of small oversights in the coverage collection and extends two sequences to provide more extensive testing.
In changing the sequence `usbdev_data_toggle_restore` a subtle discrepancy between the functional model and the DUT was also discovered; the DUT routinely collects packet data into the buffer memory before deciding whether or not the packet can be accepted. This is because of the serial nature of the USB transmission and the absence of any internal storage beyond a few flip-flops and the packet buffer memory itself.
> [dv,usbdev] Coverage improvements

- rules/opentitan/keyutils.bzl
- rules/signing.bzl
Support ECDSA signing with `hsmtool`.
Currently, in order to create an ECDSA signature with hsmtool, you must have keys defined in a `keyset`.  Longer-term, we should eliminate `keyset`s in favor of the `KeyInfo` provider introduced in #22155. This change enables signing with an ECDSA keyset to test hsmtool signing flows with the ROM.
> [signing] Support ECDSA signing with hsmtool

- sw/host/hsmtool/src/commands/ecdsa/sign.rs
- sw/host/hsmtool/src/commands/ecdsa/verify.rs
OpenTitan's ECDSA implementation expects the R and S components of an ECDSA signature to be in little-endian order.
1. Reverse the R and S components individually rather than reversing the entire signature.
> [hsmtool] Fix endianness reversal for ECDSA

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_spi_device_pinmux_sleep_retention_vseq.sv
Changed software log printed string in DV_WAIT from "SYNC: Awaked" to "PASS!"
If this DV_WAIT happens after the desired "SYNC: Awaked" is printed the test will fail on timeout.
"PASS!" is the last printed line to the software C log, I choose this line because the desired "SYNC: Awaked" happens almost at the end of the C code.
> [DV/SPI] updated sleep retention vseq to avoid race condition

- hw/ip/usbdev/dv/env/seq_lib/usbdev_phy_config_tx_osc_test_mode_vseq.sv
- hw/ip/usbdev/dv/env/timed_reg.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
This PR just implements a few initial minor changes to improve the coverage results:
- Disabling the tx oscillator test mode was not being performed at sequence end, so that state transition was never observed.
- Low Speed traffic would have been collected as per Full Speed traffic, when in reality all Low Speed packets have a PREamble PID and shall be ignored entirely by the device. This is just because the usb20_monitor is actually capable of decoding Low Speed traffic.
> [dv,usbdev] Initial minor changes to improve coverage results

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/keymgr_functest.c
This enhances the keymgr functest to ensure the SW binding registers stay locked until the keymgr is cranked from
Reset-->Init-->CreatorRootKey, where it is unlocked, and that the values locked in the binding registers stays once craked from Reset-->Init, as this is the behavior the ROM expects.
> [test] enhance keymgr functest

- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
This is to remove the cyclic referenced between Hyperdebug Transport Targets and the Inner struct, allowing for Targets to be dropped if they and the Transport object both go out of scope.
This is useful for creating another Transport object after the previous one has been dropped. Otherwise the target objects stay alive forever preventing equivalents from being created the next time a Transport object is created.
> Pull shared objects out of Hyperdebug Transport Inner member

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_device_address_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_disable_endpoint_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_endpoint_types_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_spray_packets_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_bfm.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR modifies the sequence `usbdev_spray_packets` to support Isochronous transfer types and the `set_nak_out` functionality, and then derives a simple, largely-unconstrained sequence `usbdev_endpoint_types` to ensure that all permutations of the configuration bits may be observed in coverage, and each endpoint configuration may see each of the possible token packets.
- Add support for sending PRE token packets (Low Speed traffic).
- Ensure that Isochronous configuration bits are appropriately qualified in the sequence and in the functional model; it is possible to 'misconfigure' an endpoint for _both_ Isochronous traffic and Control Transfers (SETUP packets), so ensure that the behavior is consistent throughout.
~~**This PR is built on 24183 and only the final commit is relevant to …
> [dv,usbdev] Endpoint types sequence

- hw/top_earlgrey/dv/env/chip_if.sv
Add an option to skip the external pull up from test bench on POR pad.
This following https://github.com/lowRISC/opentitan/pull/24124 that adds and internal pull up.
> [dv] Add plusarg to enable to skip external pull-up on POR pad

- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/entropy_src/dv/tests/entropy_src_fw_ov_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_rng_test.sv
This PR randomizes the duration of the simulation and sets the default for the mean time between failures to -1 to turn them off. The time between failures is already randomized for the rng_test and the fw_ov test.
Resolves [#18836](https://github.com/lowRISC/opentitan/issues/18836)
The values below the TODO comment are already random for certain tests.
@andreaskurth please tell me if I am misunderstanding something here.
> [entropy_src/dv] Randomize the simulation duration

- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_bus_rand_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_low_speed_traffic_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_non_iso_usb_traffic_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_max_usb_traffic_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_streaming_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Generalize the `usbdev_max_usb_traffic` sequence to support Isochronous transfers/endpoints too.
Introduce a derived sequence that constrains the testing to the much more common non-Isochronous traffic (Iso transfers are rarely used on the USB in practice).
_This PR requires the changes to `usbdev_bfm.sv` in #24185_ so that must be merged first otherwise there will be some test failures when Isochronous transfers are selected oweing to a discrepancy between the model and the DUT.
> [dv,usbdev] Support Iso transfers in max_usb_traffic

- hw/top_earlgrey/dv/env/ast_supply_if.sv
Adding \`timeunit and \`timeprecision to allow proper execution of '#1ps' inside 'GLITCH_VCMAIN_POK'.
Otherwise #1ps might be executed as 0 in certain cases.
> [dv,ast] Add timeunit for correct execution of delays in AST IF

- hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv
- hw/ip/spi_host/dv/env/spi_host_env_pkg.sv
- hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
RTL doesn't support 3-byte enable writes to TXFIFO, and the task packing the VSEQ data wasn't taking that into account.
That was causing an ACCESSINVAL error to be raised and never cleared which was locking up the simulation and causing timeouts.
This PR is meant to take care of test-triage tickets: #24170 and #24050 
In addition, I realised the RTL doesn't report a TL-UL bus error when a bus doesn't proceed (i.e. because the mask is wrong).
The ticket is [here](https://github.com/lowRISC/opentitan/issues/24178)
> [spi_host, dv] Timeout fixes

- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_suspend_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_bfm.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Some of the link transitions were previously not observed because (i) the driver/sequences typically do not model the USB by periodically sending the SOF packets when the bus is Idle. (ii) the Powered link state is transient and difficult to observe because the DP/DN both low state before VBUS connection acts as a Bus Reset. It therefore tends to transition quickly to ActiveNoSOF. Update the BFM to reflect the Powered -> PoweredSuspended transition.
Randomization is now required for the `usbdev_rx_full` sequence to be useful, since its scope has been extended.
> [dv,usbdev] Improve testing of suspend transitions

- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/lib/cert/cert.h
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/host/provisioning/cert_lib/src/lib.rs
- sw/host/provisioning/ft_lib/src/lib.rs
This updates the personalization flow to export/import certificates as continuous blobs to enable easily adding additional certificates in extensions for various SKUs.
This partially addresses #23426.
> [manuf] export/import certs as a single blob during perso

- hw/ip/hmac/README.md
- hw/ip/hmac/doc/programmers_guide.md
- hw/ip/hmac/doc/theory_of_operation.md
This implements minor fixes to the HMAC documentation: minor wording edits and alignment with changes to the IP and its SW usage.
This should close https://github.com/lowRISC/opentitan/issues/23455 once merged.
> [hmac,doc] Align documentation with HW changes

- hw/ip/usbdev/dv/env/seq_lib/usbdev_aon_wake_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_resume_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_suspend_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_bfm.sv
Modifications to `usbdev_link_suspend_vseq` induced failures in the derived sequences because it now exercises more functionality and tidies up after itself, disconnecting from the USB. Restructure the sequence so that the derived sequences once again function.
Extend the behavior of `usbdev_link_resume_vseq` to check both resuming when active and resuming from Deep Sleep (since `usbdev_link_suspend_vseq` now offers that), and also improve the interrupt-related checking.
> [dv,usbdev] Fix and extend suspend-related tests

- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
The sequence `usbdev_resume_link_active` was recently modified and does now use randomization to control timing and state transitions.
> [dv,usbdev] usbdev_resume_link_active uses randomization

- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_smoke_vseq.sv
This PR fixes an issue that arises for the stress all test whenever a ht failure occurs during the smoke vseq. If a HT failure happens the sequence infinitely waits for the DUT to produce a seed even though it will never be produced.
Now the vseq doesn't expect a seed if we get a HT failure.
> [entropy_src/dv] Fix timeout failure for stress all test

- hw/ip/entropy_src/rtl/entropy_src_core.sv
This commit adds an assertion for rng_fips_o.
rng_fips_o should only request high quality entropy if mubi_rng_fips is equal to Mubi4True.
Closes [#18842](https://github.com/lowRISC/opentitan/issues/18842)
> [entropy_src/dv] Add assertion for rng_fips_o

- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/doc/registers.md
- hw/ip/csrng/doc/theory_of_operation.md
As discussed in #24193 this is the PR to adapt the documentation.
> [csrng/doc] Adapt the command status response documentation

- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
Some tests were failing because the scoreboard was expecting an alert after disabling the DUT. This PR adds a variable that when set leads the scoreboard to ignore any outstanding alerts.
Closes [#18797](https://github.com/lowRISC/opentitan/issues/18797)
> [entropy_src/dv] Ignore outstanding alerts after disablement

- hw/ip/edn/dv/cov/edn_cov_if.sv
- hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_common_vseq.sv
For further information check out the individual commits.
I didn't add multiple requests per endpoint, since lowering the req signal would be a protocol violation.
Furthermore, I could add a more in depth coverage which checks if entropy requests happen in each main SM state.
However, to do this I think I would have to create a proper interface for the endpoint req/res signals, which would be more work.
@vogelpi should we create an issue for this?
Resolves [#19027](https://github.com/lowRISC/opentitan/issues/19027)
> [edn/dv] Add EDN endpoint requests while EDN is in error state

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_legacy_base_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_legacy_base_vseq.sv
Hi,
This PR added back the recently removed exclude_info2 condition to flash_ctrl_legacy_base_vseq.
This condition is required because info2 has special use in the extending environment in which it can't be tested in those tests, so the flag added to allow running those tests without using info2 partition.
Thanks!
> [flash/dv] Add back the exclude_info2 condition to legacy_base_vseq

- sw/device/lib/testing/json/command.h
- sw/device/lib/testing/json/pinmux_config.c
- sw/device/lib/testing/json/pinmux_config.h
- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/bindgen/BUILD
- sw/host/opentitanlib/src/dif/mod.rs
- sw/host/opentitanlib/src/dif/pinmux.rs
- sw/host/opentitanlib/src/test_utils/pinmux_config.rs
- sw/host/tests/chip/gpio/src/main.rs
- sw/host/tests/chip/gpio_intr/src/main.rs
This PR adds support for `opentitanlib` to configure the pad attributes of the device under test and extends the `gpio_pinmux` test to check inverted pads.
Only MIOs are tested. The DIOs could in theory be tested but it might be a bit harder.
> [sival] Test inverted pads with GPIO

- hw/ip/dma/rtl/dma.sv
Previously, the error code is written when entering the error state AND while being in there. Since the error code value is only availble in the transition into the error state, and further update overwrites the error code again with zero.
This change ensures that the error code only gets update in the transition into the error state, where the correct value is available
> [hw,dma,rtl] Only set error code when entering the error state

- sw/host/opentitanlib/opentitantool_derive/src/lib.rs
- sw/host/opentitanlib/src/app/command.rs
- sw/host/opentitanlib/src/app/mod.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/mod.rs
- sw/host/opentitansession/src/main.rs
- sw/host/opentitantool/src/command/console.rs
- sw/host/opentitantool/src/main.rs
Introduce means for users of opentitanlib to declare that for a period, no other users will be simultaneously accessing the same debugger device, allowing the driver to keep USB handles open across multiple operations.
The primary motivation for this is an observation that the repeated opening and closing of the `/dev/ttyUSBn` HyperDebug console in conjuction with other activity on the USB bus may trigger what could be a bug in the Linux USB driver stack.  Even absent concerns for such a bug, this change reduces the time taken by `transport init` from 0.4s to 0.1s for a set of Google configuration files, which could become significant, when running many small test cases in a row.
In this first iteration, `opentitansession` is made to claim exclusive use of the USB backend all the time, …
> [opentitantool] Avoid repeated opening/closing

- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_link_suspend_vseq.sv
This PR introduces randomized VBUS disconnection and reconnection to the sequence `usbdev_link_suspend` and its derived sequences to increase the coverage of FSM transitions in the `usbdev_linkstate` module of the DUT.
It also fixes a subtle fault in the Resume Signaling from the monitor to the scoreboard which for some clock frequencies and sampling phases could arrive too late to predict the change in the `usbstat.link_state` field. The result was a test failure for a very small number of seeds; this was observed with one simulator when running a larger number of seeds to check for regressions in the altered sequences.
> [dv,usbdev] Introduce VBUS disconnect/reconnect to `usbdev_link_suspend`

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_progbuf_read_write_execute_vseq.sv
Not much of a functional change, except that I've made it so that now we write all the multiregisters before reading them all back (to make sure that they aren't all backed by a single register).
I've also added comments to make it as clear as possible what's going on.
> [rv_dm,dv] Expand the rv_dm_progbuf_read_write_execute test

- hw/ip/usbdev/dv/env/seq_lib/usbdev_bitstuff_err_vseq.sv
This PR addresses a single failing seed observed on a recent regression run.
The sequence `usbdev_bitstuff_err` could inject bit stuffing violations from which the current RTL does not properly recover and the DUT instead tries to interpret the remainder of the OUT token packet as a separate packet, leading to a `rx_pid_err` assertion too.
Instead, ensure that only known, recoverable bit stuffing violations are exercised with the current RTL, pending a more robust recovery mechanism in a later revision. Changing the RTL was deferred as a risk mitigation; bit stuffing violations are not expected in practice.
It has now passed with 500 random seeds.
> [dv,usbdev] Fix failure in `usbdev_bitstuff_err` sequence

- util/dvsim/Regression.py
- util/dvsim/modes.py
The existing python code was using a string to tell the base class how to look up sub-modes for an instance of a given derived class. This was a bit complicated!
There are actually only two places where this does anything anyway, so duplicate them and get rid of the string magic.
> [util] Get rid of "type" field in Modes

- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_word_sweep_vseq.sv
- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_word_sweep_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_read_word_sweep_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_write_word_sweep_vseq.sv
This has 4 commits. The first is a fix for two test sequences, the remaining changes are
code simplifications and formatting changes.
> [dv,flash_ctrl] Fix word sweep tests

- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
- sw/device/silicon_creator/manuf/extensions/BUILD.bazel
- sw/device/silicon_creator/manuf/extensions/cfg.bzl
- sw/device/silicon_creator/manuf/extensions/default_ft_ext_lib.rs
- sw/device/silicon_creator/manuf/extensions/default_personalize_ext.c
- sw/device/silicon_creator/manuf/extensions/example_ft_ext_lib.rs
- sw/device/silicon_creator/manuf/extensions/example_personalize_ext.c
- sw/host/provisioning/ft_lib/BUILD
- sw/host/provisioning/ft_lib/src/lib.rs
This adds both:
1. a post-cert-endorsment perso extension hook to the perso firmware, and
2. a provisioning extension hook to the host side FT provisioning test harness,
that enables SKU owners to inject additional assets into the device that originate on the host side. This expands on the existing FT provisioning test harness that only enabled endorsing certificates the device had originally sent the host.
CC: @tommychiu-github
>  [manuf] add more personalization extension hooks

- sw/device/lib/dif/dif_sensor_ctrl.c
- sw/device/lib/dif/dif_sensor_ctrl_unittest.cc
The `sensor_ctrl` DIF currently uses the following range check to determine if a supplied alert event is valid: https://github.com/lowRISC/opentitan/blob/51852781d790a158784169effa7b785ba689612f/sw/device/lib/dif/dif_sensor_ctrl.c#L22
However, the actual values of `event_idx` that are intended to be valid are those between `0` and `SENSOR_CTRL_PARAM_NUM_ALERT_EVENTS - 1` inclusive.
This introduces a bug where an `event_idx` of `event_idx == SENSOR_CTRL_PARAM_NUM_ALERT_EVENTS` can be given, resulting in a valid bitfield read (returns `kDifOk`) despite the fact that reading this bit is not defined.
This bug was not caught by the existing `dif_sensor_ctrl_unittest.cc` because it also makes this error, initialising an out-of-bounds index arg as follows: …
> [dif,sensor_ctrl] Fix incorrect AST event validity range check

- hw/top_earlgrey/ip/sensor_ctrl/doc/checklist.md
sensor_ctrl's RTL changed since it had previously been signed off at D3.  This renews the D3 signoff, thus closes #22651.
This PR is currently a draft until the lint waiver has been reviewed by the TC and the SW-visible changes by the SW team.
> [sensor_ctrl] Renew D3 signoff

- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
This demonstrates nicely that I didn't properly understand JTAG when I wrote it. I understand a bit more now and the structure with TDI flowing into a shift register before flowing back out of TDO is literally given in the spec. Oops.
> [rv_dm,dv] Remove bogus TODO note from me

- hw/top_earlgrey/data/ip/chip_rom_ctrl_testplan.hjson
This was called out in https://github.com/lowRISC/opentitan/pull/22604 to satisfy both tests, so adding the `bazel` label here. There was also discussion of merging the testpoints in the two plans into one, but for now I'm just going to assign the test to both.
> [sival] Assign `kmac_app_rom_test` to `rom_ctrl_digest` test

- hw/ip_templates/alert_handler/doc/checklist.md
- hw/top_earlgrey/ip_autogen/alert_handler/doc/checklist.md
alert_handler's RTL changed since it had previously been signed off at D3.  This renews the D3 signoff, thus closes #22477.
> [alert_handler] Renew D3 signoff

- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
As of lowRISC/OpenTitan#23942, the FIFO empty status-type interrupt is predicted and verified which unfortunately negatively impacts the simulation performance in some cases. Most tests are not notably impacted but for some rather long running tests, the maximum observed job runtime increased by up to 50%. As a result, we started seeing timeouts for some of these tests in the nightly regressions after merging the FIFO empty interrupt verification PR.
Therefore, this commit increases the timeout for those long running tests where we observed timeouts.
This resolves lowRISC/OpenTitan#24225.
> [kmac/dv] Extend timeout values for long running tests

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/sw/autogen/chip/top_darjeeling.rs
- hw/top_darjeeling/sw/autogen/chip/top_darjeeling_memory.rs
- hw/top_darjeeling/sw/autogen/top_darjeeling.h
- hw/top_darjeeling/sw/autogen/top_darjeeling_memory.h
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- util/topgen/c.py
- util/topgen/lib.py
- util/topgen/rust.py
- util/topgen/templates/toplevel.h.tpl
- util/topgen/templates/toplevel.rs.tpl
- util/topgen/templates/toplevel_memory.h.tpl
- util/topgen/templates/toplevel_memory.rs.tpl
- util/topgen/validate.py
Remove hardcoded devices and interfaces for MMIO region filtering by adding two new optional module attributes cpu_visible and cpu_not_visible.
By unifying the implementation of the C and Rust generator, an inconsistency between the two implementations was uncovered. Ideally, `TopGenC` and `TopGenRust` will be refactored with a common base class to remove as much of the code duplication. I'm not sure though if that is the right PR to fix that.
This fixes #14345
> [topgen] Generically filter for MMIO region visible devices

- hw/dv/sv/csr_utils/csr_utils_pkg.sv
This reverts commit b400b907d0891418ad4e12e05e6213e68a01391c.
The change there sort of made sense: if there's a reset when we're doing a CSR operation, it's probably more defensible to return with a silly answer than to block indefinitely. Unfortunately, this doesn't quite work with the pwrmgr DV code, which seems to set the under_reset flag well before it causes a reset (and the code doesn't seem to clear it again either).
Thinking harder about the problem, I think the correct behaviour should probably be that the driver/monitor are in charge of responding quickly when they see a reset on the interface in question. Revert the (badly thought out) initial change from me in the meantime.
Fixes #24214.
> Revert "[dv] Add a quick exit in csr_rd_sub when in reset"

- hw/dv/sv/csrng_agent/csrng_agent_cov.sv
- hw/ip/csrng/dv/cov/csrng_cov_if.sv
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
- hw/ip/edn/dv/cov/edn_cov_if.sv
This PR changes the interrupt vseq to properly trigger the command error status responses instead of forcing the signals.
One thing we might need to discuss is that we run into issues where if a command with clen > 0 fails we don't absorb the whole command. This might be completely fine but still worth discussing.
Resolves #22869
> [csrng/dv] Properly trigger the status error responses

- hw/ip/edn/dv/env/seq_lib/edn_common_vseq.sv
With https://github.com/lowRISC/opentitan/pull/24125, we added a register to the error output of all prim_count instances. This adds an additional delay until errors become actually visible via CSRs (e.g. main_sm_state, err_code). This commit adds a corresponding wait statement to take this into account.
This resolves https://github.com/lowRISC/opentitan/issues/24226.
> [edn/dv] Allow flopped error output of prim_count to propagate to CSRs

- hw/dv/sv/usb20_agent/usb20_agent_cfg.sv
- hw/dv/sv/usb20_agent/usb20_driver.sv
- hw/dv/sv/usb20_agent/usb20_item.sv
- hw/dv/sv/usb20_agent/usb20_monitor.sv
- hw/ip/usbdev/data/usbdev_testplan.hjson
- hw/ip/usbdev/dv/env/seq_lib/usbdev_base_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_tx_rx_disruption_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_vseq_list.sv
- hw/ip/usbdev/dv/env/timed_reg.sv
- hw/ip/usbdev/dv/env/usbdev_bfm.sv
- hw/ip/usbdev/dv/env/usbdev_env.core
- hw/ip/usbdev/dv/env/usbdev_env_cfg.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- hw/ip/usbdev/dv/env/usbdev_timed_regs.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR adds a sequence that subjects the DUT to USB Bus Resets or IP block resets during the transmission or reception of packet data. Although the relevant logic in the module `usb_fs_tx.sv` is very simple the fact that bus resets were disjoint with packet transmission meant that a number of state transitions were not observed in coverage collection.
The sequence additionally uses the IP block reset and then reconfigures the DUT to ensure that it is possible to resume communication by receiving and transmitting packets. This is less of a concern than the idea that an inopportunely-timed USB Bus Reset might break packet reception/transmission logic or the OUT/IN packet engine state machines.
~~**The first commit belongs to PR #24206**~~
> [dv,usbdev] Sequence to disrupt packet tx/rx with USB Bus Reset or IP block reset

- sw/device/silicon_creator/lib/boot_log.c
- sw/device/silicon_creator/lib/boot_log.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
The function `boot_log_check_or_init` is meant to initialize the `boot_log` structure if it hasn't already been initialized.  This is meant to initialize the boot_log if the ROM doesn't (it doesn't on the earlgrey_es chip), however, it will also skip initialization if the boot_log is already initialized from a prior boot.
Initialize only portions of the boot_log that will be constant across boots.  Defer setting the `rom_ext_slot` to `rom_ext_start` and set it to the current boot slot on every boot.
Fixes: #23869
> [rom_ext] Set the boot slot on every boot

- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.c
- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty_unittest.cc
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_empty_test.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_min_sec_ver_test.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.h
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_wakeup_test.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
The ROM_EXT should not process `boot_svc` requests for low-power exit
cases as resuming from sleep is not expected to change the state of the
chip.
Fixes: #24235
> [rom_ext] Do not process boot_svc request for wakeups 

- hw/ip/usbdev/dv/env/seq_lib/usbdev_iso_retraction_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_bfm.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
This PR slightly delays the response to IN token packets within the device model, since the DUT does not respond immediately and there is a risk of CSR traffic introducing a discrepancy between the model and the DUT.
The timed-delay model is very simple at present but may later be extended to support other timed events such as detecting the absence of the host or violations of inter-packet delays.
The lack of temporal modeling was causing failures within the sequences `usbdev_iso_retraction` which heavily exercises CSR traffic and USB collection of Isochronous IN packets.
The PR also addresses the failure of that sequence to tidy up upon termination, which occasionally caused a failure in the interrupt clearing in `cip_base_vseq`. With this PR the sequence `usbdev_iso_retraction` has now …
> [dv,usbdev] Delayed response to IN token packets in model

- hw/ip/lc_ctrl/data/lc_ctrl.hjson
- hw/ip/lc_ctrl/doc/checklist.md
This resolves lowRISC/OpenTitan#22480.
For now let's leave this as draft. The TC needs to review the updated lint waiver.
> [lc_ctrl] Move LC_CTRL version 2.0.0 design_stage to D3

- hw/ip/usbdev/dv/env/seq_lib/usbdev_low_speed_traffic_vseq.sv
- hw/ip/usbdev/dv/env/seq_lib/usbdev_spray_packets_vseq.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
The PRE special PID (used to shield Full Speed devices from Low Speed traffic) shall be seen by all endpoint types, and it shall produce no response/change in any.
Modify the existing sequences to ensure that all types of transactions may be sent as Low Speed traffic (with PREamble) to all types of endpoints, increasing testing and satisfying coverage points.
Low speed traffic sequence now derives directly from the max_usb_traffic sequence to ensure that Isochronous endpoints are also subjected to LS traffic.
There was also a failure to collect coverage for `data_tog_endp_cg` on handshake packets.
> [dv,usbdev] Ensure all endpoint types see PRE.

- sw/device/tests/penetrationtests/firmware/fi/BUILD
- sw/device/tests/penetrationtests/firmware/fi/ibex_fi.c
- sw/device/tests/penetrationtests/firmware/fi/ibex_fi.h
- sw/device/tests/penetrationtests/firmware/fi/otbn_fi.c
- sw/device/tests/penetrationtests/firmware/fi/otbn_fi.h
- sw/device/tests/penetrationtests/firmware/firmware.c
- sw/device/tests/penetrationtests/firmware/firmware_fi.c
- sw/device/tests/penetrationtests/firmware/firmware_sca.c
- sw/device/tests/penetrationtests/firmware/lib/BUILD
- sw/device/tests/penetrationtests/firmware/lib/extclk_sca_fi.c
- sw/device/tests/penetrationtests/firmware/lib/sca_lib.c
- sw/device/tests/penetrationtests/firmware/lib/sca_lib.h
- sw/device/tests/penetrationtests/firmware/sca/aes_sca.c
- sw/device/tests/penetrationtests/firmware/sca/ibex_sca.c
- sw/device/tests/penetrationtests/firmware/sca/kmac_sca.c
- sw/device/tests/penetrationtests/firmware/sca/prng_sca.c
- sw/device/tests/penetrationtests/firmware/sca/sha3_sca.c
- sw/device/tests/penetrationtests/firmware/sca/trigger_sca.c
- sw/device/tests/penetrationtests/json/BUILD
- sw/device/tests/penetrationtests/json/extclk_sca_fi_commands.h
- sw/device/tests/penetrationtests/json/ibex_fi_commands.h
- sw/device/tests/penetrationtests/json/otbn_fi_commands.h
- sw/device/tests/penetrationtests/json/sca_lib_commands.c
- sw/device/tests/penetrationtests/json/sca_lib_commands.h
This PR consists of several commits that update and use the new SCA lib that is utilized by the penetration testing framework. This PR moves code from my fork used in the testing to the upstream project.
New functionalities include:
- Returning the device ID. This allows the tester to differentiate between different chips/fpga used in the setup
- Configure and return the triggered alerts for FI tests
Moreover, this PR consists of the following cosmetical changes:
- Move function description from source file into header file to comply with the coding standard
- Remove 0 from OK_STATUS(0) as this is unnecessary
- Rename cryptotest to penetrationtest
> [sw/pentest] Update SCA library

- hw/ip/usbdev/dv/cov/usbdev_manual_excl.el
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Manually add explicit coverage exclusions for transitions and branches that cannot be reached because of the dynamic behavior of the USB/DUT, eg. transmission and reception being impossible simultaneously on a shared, bidirectional bus.
> [dv,usbdev] Add coverage exclusions for dynamic USB behavior

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
This is needed for getting the timing to match properly when forcing a write address. The path from the error signal to clearing the instruction count goes through state_q in the controller, so it takes an extra cycle to take effect.
> [otbn,dv] Correct timing after injecting one type of error

- .github/workflows/private-ci.yml
This adds GitHub action based private CI for:
* AscentLint (replacing kokoro)
* Xcelium/VCS (replacing Azure pipeline-based private CI)
Both AZP and GitHub CI would still be side-by-side for a while before we decide to turn one off.
See https://github.com/lowRISC/ibex/blob/master/.github/workflows/private-ci.yml for a working example.
> [ci] add GitHub actions private CI

- ci/azure-pipelines-nightly.yml
This is contributing to nightly failures due to its timeout being too short. The tests it runs are already covered by regular CI run on every pull request, so this is redundant.
> [ci] Disable hyperdebug job in nightlies

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
This is a bound on the time we'll wait before we try to inject a reset in the middle of a stress sequence. 10 million cycles is... quite a long time!
This cuts it down to 100k cycles, which is still surely long enough to get to an interesting point in the state space of the device.
But rather more quickly.
> [dv] Chop reset delay by a factor of 100 in cip_base_vseq

- hw/ip/rv_dm/data/rv_dm_testplan.hjson
This is already tested by the two tests that implement the SBA testpoint. I don't believe that repeating the implementation here will gain us any confidence.
> [rv_dm,dv] Remove the "good prefix" of sba_debug_disabled testpoint

- doc/rust_for_c_devs.md
- sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs
`repr(packed)` only guarantees no internal padding, not that the fields will not be reordered. See https://github.com/rust-lang/rust/pull/125360/
> [rust] use explicit `repr(C, packed)` instead of just `repr(packed)`

- hw/dv/sv/jtag_dmi_agent/jtag_dmi_reg_frontdoor.sv
This ensures that a DMI operation that is in flight will be aborted (rather than hanging) if a reset gets asserted.
> [dv,jtag] Teach jtag_dmi_reg_frontdoor to handle resets

- hw/ip/kmac/dv/env/seq_lib/kmac_test_vectors_base_vseq.sv
- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
Previously, these tests were testing up to three complete test vector sets per test run, which could take several hours per run. And for each of these tests, we were running 50 seeds in the nightlies per default.
As these tests don't contribute much to the test coverage, this commit reduces the number of seeds per test. In addition, only one test vector set is tested per test run to reduce the time spent per run.
This is a follow-up of lowRISC/OpenTitan#24233. This resolves lowRISC/OpenTitan#24225.
> [kmac/dv] Reduce test time spent on testing NIST test vectors

- hw/dv/sv/cip_lib/cip_base_env_cfg.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
This is intentionally opt-in and won't have any effect unless an IP block configures can_reset_with_csr_accesses=1.
> [dv] Define a more robust "resetting procedure" for vseqs
