- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sec_wipe_err_vseq.sv
No functional change, but this should hopefully make the structure a little more obvious.
> [otbn,dv] Factor out tasks in otbn_sec_wipe_err_vseq.sv

- hw/dv/sv/jtag_agent/jtag_monitor.sv
- hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_busy_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_not_supported_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_halt_resume_whereto_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_hart_unavail_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_hard_reset_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_idle_hint_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_halted_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_resuming_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_stress_all_vseq.sv
This is tied in with changes I'm making locally to allow a reset to happen more easily in the middle of a run (for the stress_all_with_rand_reset testpoint). When the base vseq is configured to allow these resets to occur, the changes in this PR are needed to avoid things falling apart.
This PR has quite a few commits (sorry!). All of them are new except for the first one, which is from #24138 (which I hadn't been chasing reviews for: oops).
> [rv_dm,dv] Make lots of changes to vseqs to allow reset during a run

- hw/dv/sv/cip_lib/README.md
Cindy's example (that she added in 2019) got bumped to the wrong place by commit cf42ab6f8ba in 4 months later... which we didn't notice. Oops! Put it back.
> [dv,doc] Fix layout in cip_lib/README.md

- hw/dv/sv/tl_agent/tl_reg_adapter.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_debug_disabled_vseq.sv
This was sitting in rather the wrong place: bus2reg shouldn't really be doing scoreboard checks. It was also failing for some rv_dm vseqs, which sent TL transactions when debug is disabled, which means they all get error responses.
This commit also removes the line that turns off this check in rv_dm_debug_disabled_vseq (because the check isn't there any more to be turned off)
> [tl,dv] Remove d_error check from bus2reg in reg adapter

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
The first commit is from #24265, which should be merged first. The second commit's message is below.
I'm splitting the commits like this because I *think* the combination is correct (and needed), but the first commit is *definitely* safe. Splitting like this means that things are a bit easier to debug if something goes wrong.
**[rv_dm,dv] Drop a wait from dut_shutdown**
I think the logic behind this was that a vseq might have started some operations and we want to wait for them to run to completion. I don't believe that there *are* any such operations in rv_dm's sequences and this just made the code more complicated. Drop it.
> [rv_dm,dv] Drop a wait from dut_shutdown

- hw/top_earlgrey/dv/env/chip_env_cfg.sv
Hi,
This PR changes the condition order in the **resolve_sw_image_path** method in the **chip_env_cfg** file to check for **silicon_creator** before checking for **new_rules**.
This required specifically for tests that defined with both **new_rules** and **silicon creator** like the following test, in which the flash image created with **_silicon_creator** as its suffix.
https://github.com/lowRISC/opentitan/blob/13e9917aca2db743554ec8f3e9a55128c115c78c/hw/top_earlgrey/dv/chip_rom_tests.hjson#L805-L810
This PR comes with PR #24284
> [dv/chip] change condition order in resolve_sw_image_paths

- hw/top_earlgrey/BUILD
- rules/opentitan/silicon.bzl
This updates silicon exec_env to build VMEM images. This enables running specific tests in GLS with the images compiled for silicon platforms.
> [bazel,silicon] build VMEM files for flash images

- .bazelrc
When test suites are specified in `bazel test` (e.g. `//sw/device/tests/uart_smoketest` or `//sw/device/tests/...`), Bazel will build all the targets in that suite even if some are filtered out (e.g. with `--test_tag_filters=verilator`).
This flag causes Bazel to only build the tests that will be run.
This prevents having to build Verilator sims or FPGA bitstreams when they aren't needed.
https://bazel.build/docs/user-manual#build-tests-only
> [bazel] Enable --build_tests_only globally

- rules/certificates.bzl
This adds the full bazel label to the `asn1` device lib dep when generating certificates to enable provisioning extension repos to make use of the upstream Bazel targets.
> [bazel] add full bazel label to dep

- hw/ip/rv_dm/dv/env/rv_dm_env.core
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_scanmode_vseq.sv
- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
This is a (trivial) test to make sure that JTAG works as expected in scanmode.
Fixes #23763 (and should cover some conditions that we weren't seeing otherwise)
> [rv_dm,dv] Add a scanmode sequence

- hw/ip/rom_ctrl/dv/env/rom_ctrl_env_cfg.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
The important change is the second one (which should fix a bunch of failures in the stress_all_with_rand_reset sequence), but it needs the (reasonably trivial) first commit as well.
> [rom_ctrl,dv] Make it possible to inject resets more easily

- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_if.sv
The check_invalid bin in the coverpoint is not hit, but it doesn't really matter. The pwrmgr_data_invalid signal means that the pwrmgr_data_o.good mubi signal that we are generating has an invalid encoding. This can never happen without an injected fault.
We also don't care about whether this signal is valid or not: it is not actually read by any code in the IP block, so it doesn’t really matter if an injected fault causes it to become invalid.
Fixes #17501.
> [rom_ctrl,dv] Remove irrelevant coverpoint from rom_ctrl_tlul_cg

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
Practically speaking, we wouldn't expect differences to be local like this. But causing this to happen should allow us to hit a conditional coverage item in the compare module (where matches_q should remain false after a mismatch even if a later word matches).
Fixes #24321.
> [rom_ctrl,dv] Allow words in the expected digest to not all be wrong

- hw/ip/prim/rtl/prim_assert.sv
The assertion is supposed to start and say that we don't come back to a state until reset. Unfortunately, the implementation was disabling the property when reset happened, which meant that the assertion never finished, so it got marked as incomplete in the coverage.
Change the call to `ASSERT() so that it doesn't kill the property any more, relying on the fact that the property will terminate on its own once we go into reset.
This is associated with #24322, but I'm not marking the PR as fixing that issue because the "rom_ctrl assertions terminating" is addressed by a different PR.
> [dv] Allow assertions from ASSERT_FPV_LINEAR_FSM to complete

- hw/ip/otbn/rtl/otbn.sv
The NotBusyAndDone_A assertion wasn't quite correct. We can make it fail by injecting a fatal error when the core is in the middle of its initial wipe. If that happens, we don't bother doing a proper locking procedure (there's nothing important to wipe!) and the "busy_execute_d" signal stays high, but "locking" goes high.
These assertions were added by me (oops) last May and I don't think they really make much sense anyway. Drop the one that isn't true.
> [otbn,dv] Weaken an assertion about tracking busy/locking state

- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.c
- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_empty_unittest.cc
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_empty_test.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_min_sec_ver_test.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.h
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_wakeup_test.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
The ROM_EXT should not process boot_svc requests for low-power exit
cases as resuming from sleep is not expected to change the state of the
chip.
This is a manual cherry-pick of #24247.
This PR depends on #23311.
> Cherry-pick to master: [rom_ext] Do not process boot_svc request for wakeups

- hw/dv/tools/dvsim/vcs.hjson
- hw/ip_templates/pwrmgr/dv/cov/pwrmgr_tgl_excl.cfg
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/cov/pwrmgr_tgl_excl.cfg
This fixes two sources of warnings:
- Change global VCS flags: remove an unnecessary flag and one that is unused and causes a warning due to a conflict with coverage features
- Fix silly typo causing compilation warning
> [dv,vcs,pwrmgr] Fix compilation warnings

- sw/device/lib/crypto/impl/ecc/ecdh_p256.c
- sw/device/lib/crypto/impl/ecc/ecdh_p384.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p256.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_keygen.c
- sw/device/lib/crypto/impl/ecc/ecdsa_p384_sign.c
- sw/device/lib/crypto/impl/rsa/rsa_keygen.c
- sw/device/lib/crypto/impl/rsa/rsa_modexp.c
- sw/otbn/crypto/p256_ecdh.s
- sw/otbn/crypto/p256_ecdsa.s
- sw/otbn/crypto/p384_ecdh.s
- sw/otbn/crypto/p384_ecdsa_keygen.s
- sw/otbn/crypto/p384_ecdsa_sign.s
- sw/otbn/crypto/run_rsa_keygen.s
- sw/otbn/crypto/run_rsa_modexp.s
Small adjustment to the cryptolib OTBN routines that allows them to read mode constants directly from the OTBN binary, so that these do not have to be manually adjusted when they change. This is a minor cleanup I'd been planning on for a while, and had the impetus to fix because of a discussion in https://github.com/lowRISC/opentitan/issues/24277
> [crypto] Read mode constants from OTBN binaries.

- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
In the nightly regression we've been observing some test timeouts for kmac_long_msg_and_output which is most likely related to lowRISC/OpenTitan#24225.
After recuding the test time spent on testing NIST test vectors in lowRISC/OpenTitan#24279, the timeouts for
kmac_test_vectors_shake_128/256 can safely be reduced again.
> [kmac/dv] Adjust some test timeouts

- ci/scripts/test-airgapped-build.sh
Usually bash sub-scripts inherit these flags from their parent shell, but that doesn't seem to be happening when run via `ip` and `sudo`.
We're seeing cases where the `cquery` fails due to OOM and generates no tests, but then the `build` succeeds because it only has to build the hard-coced `mask_rom` target. This success was used as the exit code for the whole script.
Adding `-e` and `-x` flags ensures the sub-script uses the same flags as the parent script.
> [ci] Fix false-positive Bazel airgapped build test

- rules/fusesoc.bzl
Make the fusesoc cache dir be in the bazel tree, so fusesoc doesn't attempt to create directories outside, such as ~/.cache/fusesoc. That action can cause build failures, since fusesoc is sandboxed.
Fixes #23696
> [rules] Specify fusesoc cache dir to be in the bazel tree

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_stress_all_vseq.sv
Currently, some of the sram_ctrl_stress_all fail with a DataKnown_A assertion.
The reason for this failure is that the sram_ctrl_stress_all test, depending on the seed, immediately triggers a reset before the first test is started. However, this reset before the first test interferes with the hardware-based memory initialization feature.
More specifically, this reset currently happens when the last write of the mem init is issued, i.e., the write gets not finished. Hence, the memory at the last address is uninitialized, triggering the DataKnown_A assertions.
To circumvent this issue, this commit adds a wait_clks(2) before the reset.
> [sram_ctrl,dv] Wait with reset after mem_init

- hw/ip_templates/rstmgr/dv/env/rstmgr_env_pkg.sv
- hw/top_earlgrey/ip_autogen/rstmgr/dv/env/rstmgr_env_pkg.sv
All leafs must be listed or the corresponding countermeasure won't be listed. After this fix the full rstmgr regression is still at 100% passing.
|                            Name                            |  Passing  |  Total  |  Pass Rate  |  Coverage  |
|:----------------------------------------------------------:|:---------:|:-------:|:-----------:|:----------:|
| [RSTMGR](../../../ip_autogen/rstmgr/dv/latest/report.html) |    620    |   620   |  100.00 %   |  99.68 %   |
Fixes #24370
> [dv,rstmgr] Update rstmgr_leaf_rst instances

- third_party/openocd/repos.bzl
Sourceforge often has reliability issues which cause our CI to fail. Switch to debian source mirror as the primary URL to download it.
Debian only mirrors the bz2 compressed version, so the SHA is changed.
> [third_party] switch OpenOCD to debian mirror

- hw/top_earlgrey/dv/chip_rom_tests.hjson
- hw/top_earlgrey/dv/env/chip_env.core
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_base_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_self_hash_gls_vseq.sv
- hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
- sw/device/lib/testing/test_framework/ottf_main.c
- sw/device/lib/testing/test_framework/ottf_test_config.h
- sw/device/silicon_creator/rom/e2e/release/BUILD
- sw/device/silicon_creator/rom/e2e/release/rom_e2e_self_hash_test.c
The final ROM image is built for the "silicon" device, and as such does not write to the DV_SIM_WINDOW to signal a test pass. This adds a DV vseq that will signal test pass once the UART prints the expected ROM hash.
> [dv] add vseq to check ROM hash in GLS

- hw/vendor/lowrisc_ibex.lock.hjson
- hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv
38c070939183cc10940b66c8e9e04eeca6b65470
* [rtl] Remove ECC related data_rdata_i -> instr_X_o feedthroughs (Greg Chadwick)
This is related to #24404.
> Update lowrisc_ibex to lowRISC/ibex@38c07093

- sw/device/silicon_creator/rom_ext/e2e/handoff/fault_common.ld
This symbol is expected by the code and the test fails to compile without it. This was not caught by the CI because it apparently does not run in CI.
> [rom_ext/e2e] Define _manifest_address_translation in linker script

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/personalize_ext.h
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
- sw/device/silicon_creator/manuf/extensions/BUILD.bazel
- sw/device/silicon_creator/manuf/extensions/default_personalize_ext.c
- sw/device/silicon_creator/manuf/extensions/example_personalize_ext.c
Declare interface functions in a .h file so that they can be validated at compile time and move all passed in parameters into the respective structures. Not all extesnions use all interface parameters, keeping paramters in structures will allow to add new interface parameters without modifying extensions which do not use the new parameters.
Tested by running various personalization end to end tests both local and with extensions.
> [personalization_ext] Improve personalization extensions API

- hw/vendor/lowrisc_ibex.lock.hjson
- hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv
38c070939183cc10940b66c8e9e04eeca6b65470
* [rtl] Remove ECC related data_rdata_i -> instr_X_o feedthroughs
(Greg Chadwick)
This is a cherry pick of commit 59525819177bfb1108da7743d9dac7167dcc4888
to branch earlgrey_1.0.0.
~NOTE: This PR will be updated once the PR into master (#24403 ) has been merged.~ This has now been done.
> [earlgrey_1.0.0] Ibex timing fix

- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
- hw/ip/entropy_src/rtl/entropy_src_core.sv
This commit changes a couple of assertions to not falsely trigger during max rate tests.
Closes [#24103](https://github.com/lowRISC/opentitan/issues/24103)
> [entropy_src/dv] fix entropy drop assertions

- sw/host/opentitanlib/src/test_utils/gpio.rs
- sw/host/opentitanlib/src/test_utils/i2c_target.rs
- sw/host/opentitanlib/src/test_utils/mem.rs
- sw/host/opentitanlib/src/test_utils/pinmux_config.rs
- sw/host/opentitanlib/src/test_utils/rpc.rs
- sw/host/opentitanlib/src/test_utils/spi_passthru.rs
- sw/host/provisioning/cp_lib/src/lib.rs
- sw/host/provisioning/ft_lib/src/lib.rs
- sw/host/tests/chip/i2c_target/src/main.rs
- sw/host/tests/crypto/aes_nist_kat/src/main.rs
- sw/host/tests/crypto/drbg_kat/src/main.rs
- sw/host/tests/crypto/ecdh_kat/src/main.rs
- sw/host/tests/crypto/ecdsa_kat/src/main.rs
- sw/host/tests/crypto/hash_kat/src/main.rs
- sw/host/tests/crypto/hmac_kat/src/main.rs
- sw/host/tests/crypto/kmac_kat/src/main.rs
- sw/host/tests/crypto/sphincsplus_kat/src/main.rs
- sw/host/tests/manuf/cp_provision_functest/src/main.rs
- sw/host/tests/manuf/personalize_functest/src/main.rs
- sw/host/tests/rom/e2e_chip_specific_startup/src/main.rs
- sw/host/tests/rom/sw_strap_value/src/main.rs
This PR has a commit that refactors the RPC module to support additional console devices, e.g. the SPI device console.
This PR aims to support a future OTTF SPI  device console (#21726)
> [opentitanlib] Refactor RPC module to enable supporting future console interfaces (e.g., SPI)

- .github/workflows/rerun.yml
This allow members with triage access but not commit access to apply a "CI:Rerun" label on pull request to trigger rerun of workflow.
This would trigger both public and prviate CI workflows.
> [ci] add a label to rerun workflows

- .github/workflows/private-ci.yml
- .github/workflows/rerun.yml
This is the integrated_dev branch version of #24367
> [ci] add GitHub-based private CI

- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block.h
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/test_owner.c
- sw/device/silicon_creator/lib/xmodem.c
- sw/device/silicon_creator/lib/xmodem.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/device/silicon_creator/rom_ext/rescue.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/opentitanlib/src/ownership/rescue.rs
1. Configure SRAM execution as specified in the owner configuration.
2. Configure rescue according to the owner configuration.
2a. Set bounds on the firmware rescue region in flash.
2b. Disallow rescue modes not allowed by the configuration.
2c. Disallow boot_svc commands not allowed by the configuration.
3. Correct an endian issue with the rescue-mode FourCC codes.  Rescue-modes are expressed in big-endian order, whereas all other FourCC codes are expressed in little-endian order (the reason is that rescue-modes should be thought of more as 4-byte strings than identifier words).
> [ownership] Initialize SRAM & rescue according to the owner configuration

- sw/device/silicon_creator/manuf/lib/flash_info_fields.c
- sw/device/silicon_creator/manuf/lib/flash_info_fields.h
Some SKU owners may desire to obtain characterization data during manufacturing. This allocates a field in flash info page 0 for this to be written to.
> [manuf] add flash info field for writing characterization data

- sw/device/silicon_creator/lib/drivers/uart.c
- sw/device/silicon_creator/lib/drivers/uart.h
- sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/BUILD
- sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/immutable_rom_ext_section_test.c
- sw/device/silicon_creator/rom/e2e/release/rom_e2e_self_hash_test.c
- sw/device/silicon_creator/rom/rom.c
- util/design/gen-otp-immutable-rom-ext-json.py
The original ROM_EXT immutable section configuration did not account for the address translation adjustments to the immutable section entry point. This meant that if address translation was enabled, the immutable section entry point would never get moved to the virtual address space, which gets marked RX. The physical address space of the current slot would only be marked R, and when jumping to the entry point an exception would occur. This slipped through b/c our tooling always calculated the correct offset to the immutable section base on symbols in the ELF, but meant that the same offset could not be used across different ROM_EXT slot locations (which is important since the immutable section offset is stored in fuses). This fixes that error and enhances the tests to ensure the same …
> [rom] fix ROM_EXT immutable section to work with address translation

- sw/device/lib/testing/test_framework/ottf_console.c
- sw/device/lib/testing/test_framework/ottf_console.h
- sw/device/tests/spi_device_ottf_console_test.c
- sw/host/opentitanlib/src/console/spi.rs
- sw/host/tests/chip/spi_device_ottf_console/src/main.rs
This PR has three commits that:
1. Update the opentitanlib SPI console module to support TX direction
2. Add support for reading data from the Host via the OTTF SPI device console
3. Test the OTTF spi_device console in TX direction.
Workflow:
1. Device Ready Signal: Device initiates communication by sending a sync message to Host, signaling its readiness to receive data and its active wait state for an upload command.
2. Host Initiates Upload: Host responds by issuing an upload command. Following this, Host actively polls the status register, waiting for the BUSY bit to be cleared.
3. Device Data Processing: Upon receiving the upload command, Device reads data from the payload buffer. After processing, it clears the BUSY bit and enters a busy wait state, anticipating the next upload …
> [ottf,opentitanlib,test] Impl spi device ottf tx console

- hw/ip/usbdev/dv/cov/usbdev_manual_excl.el
- hw/ip/usbdev/dv/env/usbdev_bfm.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
This PR makes a couple of small changes to improve the coverage results:
- handshake packets were not being collected appropriately for contributing to the functional coverage results.
- manual exclusions are introduce for the line coverage to match the FSM transitions that had already been manually excluded as unreachable. Condition coverage exclusions are added for invalid FIFO operations that we _do not expect to see_.
The third commit simply increases the number of seeds used for one of the stress sequences because otherwise the pass rate will fluctuate between 80% and 100% if a single seed fails.
> [dv,usbdev] Changes to improve coverage

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_base_vseq.sv
Hi,
This change is required for the GL in which the DV_WAIT default timeout is not long enough.
Done here as we done in the chip_sw_rom_e2e_self_hash_gls_vseq in the previous PR #24339:
https://github.com/lowRISC/opentitan/blob/cf32d0f1190b72144c52ffe1b226b4fe37eb3988/hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_self_hash_gls_vseq.sv#L17-L22
> [dv/chip/rom] Update the timeout of DV_WAIT

- hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
Rather strangely, these were originally correct but became wrong with commit 1ebc7a9de3d (which was made as the author brought up an FPV environment). Make them right again.
> [prim,fpv] Fix delays in assertions of prim_fifo_async_sram_adapter

- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
This PR has a commit that fixes out-of-bounds memory access in `ast_cfg_data`.
The device started hanging after I tried to make some modifications on `sram_ft_individualize` to switch the device console from Uart to SPI interface (#24420). Further investigation revealed that the root cause was an out-of-bounds memory access in the original code, which had not previously caused any issues though.
> [manuf] Fix out-of-bounds memory access in ast_cfg_data

- azure-pipelines.yml
- ci/scripts/run-fpga-tests.sh
- rules/opentitan/defs.bzl
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
- sw/device/silicon_creator/rom_ext/e2e/handoff/BUILD
- sw/device/silicon_creator/rom_ext/e2e/lockdown/BUILD
- sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
- sw/device/silicon_creator/rom_ext/rescue.c
Use the `fpga_hyper310_rom_ext` environment for ROM_EXT end-to-end tests.
The hyperdebug serial ports support serial break out of the box, whereas
the CW310 serial ports require special SAM3x firmware to support serial
break.
> [rom_ext_e2e] Update CI to run ROM_EXT tests on hyper310 

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/cert.c
- sw/device/silicon_creator/lib/cert/cert.h
- sw/device/silicon_creator/lib/otbn_boot_services.c
- sw/device/silicon_creator/lib/otbn_boot_services.h
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
This moves the `cert_ecc_p256_keygen()` function from the `cert` lib to the `otbn_boot_services` lib to simplify on-host unit testing of the `cert` lib. The `otbn_boot_services` lib is only tested on-device at the moment due to the dependencies on specific OpenTitan hardware that is difficult to mock. In refactoring this, the cert_unittest is now fixed.
> [cert] move cert keygen function to otbn_boot_services lib

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.h
- sw/device/silicon_creator/manuf/extensions/BUILD.bazel
- sw/device/silicon_creator/manuf/lib/flash_info_fields.c
- sw/device/silicon_creator/manuf/lib/flash_info_fields.h
- sw/host/provisioning/ft_lib/src/lib.rs
- sw/host/provisioning/perso_tlv_lib/src/lib.rs
This patch adds the dev seed hash to the set of objects generated by the device and transferred to the host during personalization.
In fact dev seed hash is a SKU specific object, its processing should be used to SKU specific code on both device and host, along with TPM certificates produced by the cros SKU, this is left as a future enhancement.
> [personalisation] dev seed hash generation and transfer

- hw/dv/sv/mem_bkdr_util/mem_bkdr_util.sv
- hw/dv/sv/mem_bkdr_util/mem_bkdr_util__sram.sv
- hw/dv/sv/mem_bkdr_util/sram_scrambler_pkg.sv
- hw/ip/prim/doc/prim_ram_1p_scr.md
- hw/ip/sram_ctrl/data/sram_ctrl.hjson
- hw/ip/sram_ctrl/dv/sram_ctrl_main_sim_cfg.hjson
- hw/ip/sram_ctrl/dv/sram_ctrl_ret_sim_cfg.hjson
- hw/ip/sram_ctrl/dv/tb.sv
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/dv/tb/tb.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
This PR contains multiple commits to reduce the number of PRINCE half rounds for the main SRAM scrambling from 3 back to 2 as used for Earlgrey ES. This is done to reduce timing pressure.
The scrambling parameters of the other scrambled memory primitives (retention SRAM, ROM, OTBN IMEM & DMEM) are not touched by this PR.
This PR supersedes #24376 as it also includes the required tooling changes. #24376 is intentionally left untouched to allow comparing the RTL changes as #24376 has already been absorbed by the PD team last week, i.e., we must not change the RTL beyond #24376.
For reference, the PRs where we increased the number of scrambling rounds in the past are:
- https://github.com/lowRISC/opentitan/pull/22425
- https://github.com/lowRISC/opentitan/pull/22948
> [top_earlgrey] Reduce number of PRINCE half rounds for main SRAM scrambling

- sw/device/tests/crypto/cryptotest/cryptotest.bzl
- sw/device/tests/crypto/cryptotest/firmware/BUILD
Add support for the CW340 target to Bazel rules for cryptotest.
Fixes #24418.
> [bazel] Support CW340 FPGA target

- hw/dv/sv/mem_bkdr_util/mem_bkdr_util.sv
- hw/dv/sv/mem_bkdr_util/mem_bkdr_util__sram.sv
- hw/dv/sv/mem_bkdr_util/sram_scrambler_pkg.sv
- hw/ip/prim/doc/prim_ram_1p_scr.md
- hw/ip/sram_ctrl/data/sram_ctrl.hjson
- hw/ip/sram_ctrl/dv/sram_ctrl_main_sim_cfg.hjson
- hw/ip/sram_ctrl/dv/sram_ctrl_ret_sim_cfg.hjson
- hw/ip/sram_ctrl/dv/tb.sv
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/dv/tb/tb.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
This PR contains multiple commits to reduce the number of PRINCE half rounds for the main SRAM scrambling from 3 back to 2 as used for Earlgrey ES. This is done to reduce timing pressure.
The scrambling parameters of the other scrambled memory primitives (retention SRAM, ROM, OTBN IMEM & DMEM) are not touched by this PR.
Note that this PR is currently WIP. It will most likely not pass CI yet as I need to also update the tooling to support backdoor loading of memories using different numbers of scrambling rounds. But this PR is sufficient to allow the PD team kicking off another synthesis run. The RTL changes are okay and I pushed this through lint which hasn't flagged any warnings / errors.
For reference, the PRs where we increased the number of scrambling rounds in the past are:
- …
>  [top_earlgrey] Reduce number of PRINCE half rounds for main SRAM scrambling

- sw/device/silicon_creator/rom_ext/data/rom_ext_e2e_testplan.hjson
- util/py/scripts/gh_testplan.py
1. Update the ownership transfer testplan with GitHub issue URLs.
2. Update the issue creator script to ensure the URLs are UTF-8.
> [rom_ext] Update ownership transfer testplan

- sw/device/silicon_creator/lib/cert/cdi_0.hjson
- sw/device/silicon_creator/lib/cert/cdi_1.hjson
- sw/device/silicon_creator/lib/cert/tpm_ek.hjson
- sw/device/silicon_creator/lib/cert/uds.hjson
- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/subst.rs
- sw/host/ot_certs/src/x509.rs
- sw/host/ot_certs/src/x509/extension.rs
- sw/host/ot_certs/tests/example.hjson
- sw/host/ot_certs/tests/example_data.json
- sw/host/ot_certs/tests/generic.hjson
This allows certificate templates to specify whether they want a key usage extension at all, and if they do what the key usages are. I only added support for the 3 usages that seem the most
> [ot_certs] Add support for custom key usage

- sw/device/tests/penetrationtests/firmware/BUILD
- sw/device/tests/penetrationtests/firmware/fi/BUILD
- sw/device/tests/penetrationtests/firmware/fi/crypto_fi.c
- sw/device/tests/penetrationtests/firmware/fi/crypto_fi.h
- sw/device/tests/penetrationtests/firmware/firmware.c
- sw/device/tests/penetrationtests/firmware/firmware_fi.c
- sw/device/tests/penetrationtests/json/BUILD
- sw/device/tests/penetrationtests/json/commands.h
- sw/device/tests/penetrationtests/json/crypto_fi_commands.c
- sw/device/tests/penetrationtests/json/crypto_fi_commands.h
This commit pulls over the following tests from the pentest branch of nasahlpa/opentitan that has been used for the penetration testing:
- AES FI
- KMAC FI
- Shadow Register access FI
- Shadow Register read FI
> [pentest] Add Crypto FI tests

- sw/device/tests/penetrationtests/firmware/BUILD
- sw/device/tests/penetrationtests/firmware/fi/BUILD
- sw/device/tests/penetrationtests/firmware/fi/lc_ctrl_fi.c
- sw/device/tests/penetrationtests/firmware/fi/lc_ctrl_fi.h
- sw/device/tests/penetrationtests/firmware/firmware.c
- sw/device/tests/penetrationtests/firmware/firmware_fi.c
- sw/device/tests/penetrationtests/json/BUILD
- sw/device/tests/penetrationtests/json/commands.h
- sw/device/tests/penetrationtests/json/lc_ctrl_fi_commands.c
- sw/device/tests/penetrationtests/json/lc_ctrl_fi_commands.h
This commit pulls over the lc_ctrl.runtime_corruption FI test from the pentest branch of nasahlpa/opentitan that has been used for the penetration testing.
> [pentest] Add LC_CTRL FI tests

- sw/device/tests/penetrationtests/firmware/BUILD
- sw/device/tests/penetrationtests/firmware/firmware.c
- sw/device/tests/penetrationtests/firmware/firmware_sca.c
- sw/device/tests/penetrationtests/firmware/sca/BUILD
- sw/device/tests/penetrationtests/firmware/sca/hmac_sca.c
- sw/device/tests/penetrationtests/firmware/sca/hmac_sca.h
- sw/device/tests/penetrationtests/json/BUILD
- sw/device/tests/penetrationtests/json/commands.h
- sw/device/tests/penetrationtests/json/hmac_sca_commands.c
- sw/device/tests/penetrationtests/json/hmac_sca_commands.h
This commit pulls over the HMAC SCA tests from the pentest branch of nasahlpa/opentitan that has been used for the penetration testing.
> [pentest] Add HMAC SCA tests

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_self_hash_gls_vseq.sv
A new ROM was released after #24417 was merged, however the expected hash was not updated in the vseq used for the GLS test. This updates the expected hash to match that in the `.c` file counterpart.
> [dv,rom_e2e] update expected ROM hash in GLS self hash test

- sw/host/opentitanlib/src/image/image.rs
In case of SPX signing using the PrehashedSha256 domain the image payload needs to be hashed both before signing and before validating the signature.
The validation path was not hashing the image which was causing signature validation failures.
Tested by verifying pure and hashed SPX signing cases.
Change-Id: I055d2c5717b7280d9e5a11a93e54815ad9a707cd
> [opentitantool]: fix hashed SPX signature verification

- rules/opentitan/defs.bzl
- sw/device/silicon_creator/lib/ownership/keys/dummy/BUILD
- sw/device/silicon_creator/lib/ownership/keys/fake/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/defs.bzl
- sw/host/opentitanlib/src/chip/rom_error.rs
- sw/host/tests/ownership/BUILD
- sw/host/tests/ownership/transfer_lib.rs
- sw/host/tests/ownership/transfer_test.rs
The tests added by this change are all simple variations on
the ownership transfer test added in #24419.  They involve verifying the
different modes and error conditions (e.g. using the wrong key).
Adds the following tests:
- `bad_unlock_test`; Fixes #24466
- `bad_activate_test`; Fixes #24467
- `bad_owner_block_test`; Fixes #24468
- `bad_app_key_test`; Fixes #24469
- `transfer_endorsed_test`; Fixes #24470
- `bad_endorsee_test`; Fixes #24471
- `locked_update_test`; Fixes #24472
- `bad_locked_update_test` & `bad_locked_update_no_exec_test`; Fixes #24473
Note: This PR# depends on #24419; you need only review the last commit.
> [rom_ext_e2e] More ownership transfer tests 

- quality/BUILD.bazel
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/flash_contents.c
- sw/host/opentitanlib/src/ownership/mod.rs
- sw/host/tests/ownership/BUILD
- sw/host/tests/ownership/rescue_limit_test.rs
- sw/host/tests/ownership/rescue_permission_test.rs
- sw/host/tests/ownership/transfer_lib.rs
Test the configuration options of the rescue protocol.
The `transfer_lib` is enhanced to allow for pre-set variations of the ownership config through the `OwnerConfigKind` enum.  The rust-based test harnesses are near-clones of the `transfer_test` harness, however, they allow for certain expected errors during the transfer process (such as a `Cancel` during the rescue upload) and test for specific conditions after owner activation.
`rescue_limit_test`: Fixes #24474.
`rescue_permission_test`: Fixes #24475.
> [rom_ext_e2e] Ownership rescue configuration tests

- azure-pipelines.yml
- ci/scripts/check-unrunnable-tests.sh
- ci/scripts/incompatible_targets.cquery
We have discovered that some unittest have become unrunnable because we added my mistake dependencies that are marked as only compatible with the OT platforms. This means that those unittests are then skipped when running all tests using //...
This commit adds a lint to make sure that all tests are compatible with the host platform.
**NOTE:** I have currently marked this lint as a warning only because we still have 6 tests that are broken at the moment.
This partially addresses #24446
> [ci] Add a lint to check for unrunnable tests

- sw/device/lib/runtime/print.c
- sw/device/lib/runtime/print.h
- sw/device/lib/testing/test_framework/ottf_console.c
- sw/device/lib/testing/test_framework/ottf_console.h
- sw/device/lib/testing/test_framework/ujson_ottf.c
- sw/device/tests/BUILD
- sw/device/tests/spi_device_ottf_console_test.c
- sw/device/tests/spi_device_ujson_console_test.c
- sw/host/opentitanlib/src/test_utils/mem.rs
- sw/host/tests/chip/spi_device_ottf_console/src/main.rs
- sw/host/tests/chip/spi_device_ujson_console_test/BUILD
- sw/host/tests/chip/spi_device_ujson_console_test/src/main.rs
This PR has four commits that:
1. Refactor ujson ottf console and implement `getc` for SPI device.
2. Test the new `getc` implementation.
3. Refactor mem module to support the new SPI device console
4. Add an example test for spi_device ujson ottf console.
This fixes #21726.
> [base,ottf,test] Refactor ujson ottf console to support spi_device console

- hw/ip/spi_host/rtl/spi_host_fsm.sv
This partially reverts commit 7eb53da738a770a4cc00153eb7179a2c2d9bdda9, which introduced a glitch on the `sd_en_o` output of `spi_host_fsm`. The reversal is partial in order to minimize the netlist diff.  The `drive_posedge` signal as well as the four `sd_en_ff_q` flops are now unused.
This is *not* a cherry pick of a commit on `master`, where the glitch is planned to be fixed with a full reversal of the commit mentioned above (in PR #24500).
Relevant block- and top-level tests are currently running; I'll post the results here once they're done.
Full block-level regression doesn't show any new failures:
```
|  Stage  |                   Name                    | Tests                               |  Max Job Runtime  |  Simulated Time  |  Passing  |  Total  |  Pass Rate  | …
```
> [earlgrey_1.0.0,spi_host/rtl] Fix `sd_en_o` of `spi_host_fsm`

- hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_ack_consistency_vseq.sv
- hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_ack_consistency_vseq.sv
Hi,
This small PR is increasing the delay for the fatal_err timeout in the flash_ctrl_phy_ack_consistency test because it seems to be insufficient in some seeds for the extending environment.
> [dv/flash] Increase fatal_err delay in flash_ctrl_phy_ack_consistency

- sw/device/lib/runtime/print_unittest.cc
The `printf` unit testing was missing tests for the custom debug formatting specifier `kFourCC`, which is used for formatting Four Character Codes. This specifier prints a `uint32_t` as four ASCII characters encoded in little endian order. Existing print unit tests did not check this specifier, and so this commit introduces three additional small unit tests to check that the implementation is working as intended.
This has been tested by running the following command:
```sh
./bazelisk.sh test -t- --test_output=streamed //sw/device/lib/runtime:print_unittest
```
which still passes after the changes as expected.
> [sw,lib] Add unit test for debug printing four character codes

- bazelisk.sh
This PR resolves #23990.
After building a software target using `./bazelisk.sh build`, sometimes an `opentitan_test` would be built in multiple configurations, causing Bazel's `cquery` to return the same file multiple times in its output, as a result of us using `--output=starlark` for starlark postprocessing instead of the newer `--output=files`.
Some scripts, such as [`ci/scripts/target-location.sh`](https://github.com/lowRISC/opentitan/blob/39211701b5d2d8af1d52ab243b5b079bec36535f/ci/scripts/target-location.sh#L33C1-L37C36), rely on the fact that outquery will return a unique result. This ensures that these scripts will not break if a test target is built, by ensuring that output files are unique and non-duplicated.
To test, run the following commands:
```sh
./bazelisk.sh build …
```
> [bazel] Ensure output files of outquery are unique

- sw/host/tests/chip/spi_device_ujson_console_test/src/main.rs
It was spotted that `spi_device_ujson_console_test` may take longer than 30s to finish on cw310 in the CI pipeline. This PR modifies the timeout of  the test to 60s to avoid the test being timeout.
> [test] adjust the timeout of ujson_console test

- sw/device/lib/dif/dif_i2c.c
- sw/device/lib/dif/dif_i2c.h
- sw/device/lib/dif/dif_i2c_unittest.cc
The i2c block requires a minimum value (for the current setup, at least 4 cycles) for the SCL high and low time in order for clock stretching to function. This functionality was previously added to the DIF (see #23772), and so this PR updates the relevant unit tests to also check for these conditional cases. Modified input clock periods are used that have been calculated to execute minimum boundary branch cases, and a static assertion before the test ensures that these calculated values will not fall out of sync if the minimum high/low time does change.
This has been tested by running the following command:
```sh
./bazelisk.sh test -t- --test_output=streamed //sw/device/lib/dif:i2c_unittest
```
which still passes after the changes as expected.
> [i2c,dif] Test i2c dif SCL high and low time cycle bounds on clock stretching

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_resuming_vseq.sv
This vseq is mostly careful to follow the form:
Do a TL transaction
Stop if we are in reset (since the transaction was aborted)
Check the result
But I missed an instance! Put it in.
> [rv_dm,dv] Handle reset at surprising time in resuming vseq

- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
- sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.cc
- sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.h
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block.h
- sw/device/silicon_creator/lib/ownership/owner_block_unittest.cc
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership.h
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/flash_regions.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/tests/ownership/BUILD
- sw/host/tests/ownership/flash_permission_test.rs
- sw/host/tests/ownership/transfer_lib.rs
Perform flash lockdown of owner flash regions.
`flash_permission_test`: Fixes: #24476
Adds a test harness that verifies the flash configuration state of data
regions.
> [rom_ext_e2e] Test owner flash configuration 

- hw/ip/sysrst_ctrl/doc/theory_of_operation.md
The documentation is incorrect: since the default logic value of the pin with no override is 0, the only way to release the pin is to use an override to 1, and NOT to disable the override.
Addresses #24480 since we cannot change the RTL at this point.
> [sysrst_ctrl,doc] Fix documentation of the flash_wp_l pin

- python-requirements.in
- python-requirements.txt
- tool_requirements.py
- util/check_tool_requirements.py
- util/lintpy.py
- util/reggen/params.py
This builds on #24512 (the first commit in the PR) and removes some compatibility code that I put into the tooling to support older Python versions. Detailed notes in commit messages.
> Remove some support for Python <= 3.7

- sw/device/lib/testing/test_framework/ottf_console.c
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/sram_cp_provision.c
- sw/device/silicon_creator/manuf/base/sram_cp_provision_functest.c
- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
- sw/host/opentitanlib/src/console/spi.rs
- sw/host/provisioning/cp/src/main.rs
- sw/host/provisioning/cp_lib/src/lib.rs
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/ft_lib/src/lib.rs
- sw/host/tests/manuf/cp_provision_functest/src/main.rs
This PR  has two commits that:
1. Add host-device resync mechnisam for SPI device RX console to enhance robustness against device resets during provisioning
2. Switch provisioning flow to use spi console 
This fixes #24420.
Note: this depends on #24530. Only review the last 2 commits.
> [manuf] Update CP and FT provisioning tests to utilize SPI device console

- hw/dv/tools/vcs/cover.cfg
- hw/dv/tools/vcs/cover_reg_top.cfg
- hw/ip/rv_dm/dv/cov/cover.cfg
- hw/ip/rv_dm/dv/cov/cover_reg_top.cfg
- hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
- Stop collecting non-assertion coverage from the tlul_assert block (since that seems a bit pointless).
- Mirror this change in cover_reg_top.cfg
- Refactor stuff in the rv_dm specialisations of the two files because they are supposed to *extend* the base versions rather than reimplementing them.
- The resulting rv_dm version of cover.cfg ends up empty (which causes VCS to segfault!). Remove it.
> [dv,vcs] Tidy up how coverage is collected in assertion modules

- hw/ip/i2c/data/i2c.hjson
Writes can affect hardware in a way that causes interrupts (sda/scl_interference) to re-assert continuously, preventing the end-of-test clear_interrupts routine from completing.
> [i2c,dv] Add csr write excl to OVERRIDE csr

- hw/ip/otp_ctrl/data/otp_ctrl_img.c.tpl
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.h
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg_functest.c
This separates the provisioning of the ROM_BOOTSTRAP_DIS OWNER_SW_CFG OTP field from the provisioning and locking of the remainder of the OWNER_SW_CFG OTP partition, since this field needs to be provisioned after all bootstrap operations in the personalization flow have been completed.
This addresses #24189
> [manuf] split OWNER_SW_CFG OTP provisioning into several sub-steps

- sw/host/hsmtool/BUILD
- sw/host/hsmtool/src/commands/ecdsa/sign.rs
- sw/host/hsmtool/src/commands/ecdsa/verify.rs
- sw/host/hsmtool/src/error.rs
- sw/host/hsmtool/src/util/key/ecdsa.rs
- third_party/rust/Cargo.lock
- third_party/rust/Cargo.toml
- third_party/rust/crates/BUILD.bazel
- third_party/rust/crates/defs.bzl
OpenTitan's ECDSA implementation expects the R and S components of an
ECDSA signature to be in little-endian order.
1. Reverse the R and S components individually rather than reversing the entire signature.
2. Following the PKCS#11 specifications, the CKA_EC_POINT should be the DER-encoding of ANSI X9.62 ECPoint value.
These cherry-picks are from #23962 and #23905.
> Cherry-pick from `master`: hsmtool fixes

- WORKSPACE
- third_party/open-dice/BUILD
- third_party/open-dice/BUILD.open-dice.bazel
- third_party/open-dice/repos.bzl
We'll need the cbor_reader and cbor_writer implementations from the open-dice repository, for the CWT CBOR DICE implementation in the ROM_EXT.
Test: bazel build @@open-dice//:cbor_reader_writer
> [third_party] Add open-dice dependency

- doc/getting_started/setup_fpga.md
This updates the jumper table to correctly reference J23/J25 for the SPI device and J12/J13 for the JTAG connection on the CW340 base board.
The image of blue socket-to-socket jumpers on cw340 board is attached for the reference
> [doc] update cw340 jumper table references

- .github/workflows/ci.yml
- azure-pipelines.yml
- ci/scripts/test-airgapped-build.sh
This PR adds a GitHub Actions equivalent to the airgapped build job. It does not remove the Azure job (yet).
The airgapped build is now using 95% of the disk space for public Azure runners (10GiB):
* Azure won't give us more. We would have to move it to a self-hosted Azure runner.
* GitHub Actions free runners provide 14GiB which should be enough for now.
* We can pay for more if needed without having to self-host.
This should unblock the ability to test signing binaries (with fake keys) in the airgapped build test. We know how to grant permission for GitHub Actions CI jobs to access Google Cloud signing services. We haven't done it before in Azure.
We would like to move CI over to GitHub Actions eventually. The airgapped build is independent of all other jobs, making it a good candidate …
> [ci] Add GitHub Actions version of airgapped build

- sw/device/tests/penetrationtests/firmware/BUILD
- sw/device/tests/penetrationtests/firmware/fi/rng_fi.c
- sw/device/tests/penetrationtests/firmware/firmware.c
- sw/device/tests/penetrationtests/firmware/firmware_sca.c
- sw/device/tests/penetrationtests/firmware/sca/BUILD
- sw/device/tests/penetrationtests/firmware/sca/edn_sca.c
- sw/device/tests/penetrationtests/firmware/sca/edn_sca.h
- sw/device/tests/penetrationtests/json/BUILD
- sw/device/tests/penetrationtests/json/commands.h
- sw/device/tests/penetrationtests/json/edn_sca_commands.c
- sw/device/tests/penetrationtests/json/edn_sca_commands.h
This commit pulls over the EDN SCA tests from nasahlpa/opentitan that have been used in the pentesting:
- edn.sca.bus_data
- edn.sca.bus_data_batch_fvsr
- edn.sca.bus_data_batch_random
These tests can be used to analyze the SCA security of the EDN.
> [pentest] Add EDN SCA tests

- hw/ip/prim/rtl/prim_count.sv
The err_d signal is flopped into err_q, which appears as err_o. The existing assertion (that err_d went high) was correct, but didn't check the err_q/err_o part. This eventually translated into a coverage hole where no property had a CoI that included the "err_q <= err_d" line.
Change things so that we use err_o instead. This feels a little "less internal" anyway, which is nice, and also includes the register stage.
> [prim,fpv] Strengthen CntErrReported_A assertion in prim_count.sv

- hw/ip/prim/rtl/prim_fifo_sync.sv
This doesn't change the meaning, but it means that we now use ASSERT_KNOWN_IF instead of explicitly talking about $isunknown. Doing so will allow FPV runs (that don't support $isunknown) to avoid needing to report unprocessed code.
Note that this won't make any difference without #24454.
> [prim,fpv] Tweak DataKnown_A assertion in prim_fifo_sync.sv

- hw/ip/rom_ctrl/util/mem.py
- hw/ip/rom_ctrl/util/scramble_image.py
- util/design/secded_gen.py
As ROMs get bigger, scrambled memory collision checker in `mem.py` becomes slower.
On my local machine using this revised implementation, scrambling the second rom only takes 1.75 seconds vs. 7.68 seconds with the previous implementation (> 4x speed up).
I've tested collisions detections forcing several of them and checking the collision report remains the same:
```diff
diff --git a/hw/ip/rom_ctrl/util/scramble_image.py b/hw/ip/rom_ctrl/util/scramble_image.py
index c3e1cd0d63..6d70c2144e 100755
--- a/hw/ip/rom_ctrl/util/scramble_image.py
+++ b/hw/ip/rom_ctrl/util/scramble_image.py
@@ -493,6 +493,8 @@ def main() -> int:
scr_mem.add_ecc32()
assert scr_mem.width == 39
+    scr_mem.chunks[0].words[4] = scr_mem.chunks[0].words[78] = scr_mem.chunks[0].words[453]
+    scr_mem.chunks[0].words[12] …
```
> [rom_ctrl,util] Rework memory collision check

- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block_unittest.cc
- sw/device/silicon_creator/lib/ownership/ownership_activate.c
- sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc
- sw/device/silicon_creator/lib/ownership/test_owner.c
- sw/host/opentitanlib/src/ownership/owner.rs
1. Rename `version` to `struct_version`.
2. Verify the struct_version when parsing the owner block.
3. A correct parse is a pre-condition for activation.
> [ownership] Rename `version` to `struct_version`

- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership_activate.c
- sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc
- sw/device/silicon_creator/lib/ownership/ownership_unlock.c
- sw/device/silicon_creator/lib/ownership/ownership_unlock_unittest.cc
- sw/device/silicon_creator/rom_ext/data/rom_ext_e2e_testplan.hjson
- sw/device/silicon_creator/rom_ext/doc/ownership.md
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/host/opentitanlib/src/chip/boot_log.rs
- sw/host/tests/ownership/transfer_test.rs
The name `LockedUpdate` is confusing because it is an unlocked chip state.  This state is to allow the chip to accept an owner configuration update that must be from the self-same owner.
> [ownership] Rename `LockedUpdate` to `UnlockedSelf`

- sw/host/opentitanlib/src/image/manifest_def.rs
- sw/host/opentitantool/src/command/image.rs
It was observed that repetitive invoking 'opentitiantool image manifest update ...' passing an --spx_key and same manifest input file which included SPX key and signature extensions repetitively is causing addition of the SPX key and SPX signature space every time opentitantool is invoked.
This patch fixes the problem.
All opentitantool and opentitanlib tests pass, and running the same invocation does not cause additions of the SPX key and signature spaces any more.
> [opentitantool] do not create duplicate extension entries

- .github/actions/install-deps/action.yml
- .github/workflows/ci.yml
In Azure, we use these quick lints as a filter before we run the rest of the pipeline. We need this job running in parallel in GitHub Actions to start porting things over.
* I've dropped the "Determine build type" step as we don't need this right now and it's not a lint anyway.
* I also dropped the "Confirm no `.bazelrc-site`" step since it's already in `.gitignore` and this check seems superfluous.
* Otherwise, no changes.
This PR also ports the `ci/install-dependencies.{sh,yml}` files from Azure to GitHub (with some duplication). I'd still like to extract the Verilator and Verible versions to some external file. Same for the Python version ideally.
> [ci] Add `quick_lint` job to GitHub Actions CI workflow

- .github/actions/install-deps/action.yml
Add apt-get update to the `install-deps` CI step to ensure the dependency resolution is based on the latest remote apt package index rather than the cached one baked into the ubuntu container running the job.
> [ci] add apt-get update

- hw/dv/sv/jtag_agent/jtag_if.sv
The current configured frequency of 50MHz is too fast and might not be supported by silicin.
> [dv,jtag] Change JTAG clock frequency to 24MHz

- hw/ip/prim/rtl/prim_assert.sv
- hw/ip/prim/rtl/prim_assert_standard_macros.svh
Unknown signals aren't really supported by Jasper, which drops the assertion accordingly. Unfortunately, this shows up as a coverage hole (for a rather silly reason). Get rid of the assertion entirely if we are in this context (the signal is not X because the tool doesn't allow that to happen...)
> [prim,fpv] Get rid of ASSERT_KNOWN in an FPV context

- hw/ip/prim/fpv/tb/prim_alert_rxtx_fatal_bind_fpv.sv
The statement that was previously there didn't actually bind the assertions into anything. This was only noticed because of low formal coverage numbers.
> [prim,fpv] Fix the bind statement in prim_alert_rxtx_fatal_bind_fpv

- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_claim_transition_if_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_smoke_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_volatile_unlock_smoke_vseq.sv
I think this predates the infrastructure that's now in `lc_ctrl_errors_vseq.sv`. When that was merged, the stuff in the smoke sequence seems to have been disabled but left in place unused. Remove it.
> [flash_ctrl,dv] Drop some unused stuff from the smoke sequence

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_halt_resume_whereto_vseq.sv
This silences a build warning from Xcelium (because $urandom_range expects a (32 bit) int argument.
> [rv_dm,dv] Fix constant width in vseq

- hw/ip/otbn/dv/otbnsim/sim/sim.py
- hw/ip/otbn/dv/otbnsim/sim/state.py
There are two paths by which this can happen in the RTL (the insn_cnt_clear_int_o signal from otbn_start_stop_control and the way that otbn_controller can go into a locked state). These have slightly different timings!
Make sure to model them correctly.
This fixes failures in `otbn_escalate`. Last night had 5 failures in 60 runs, four of which were caused by this sort of mismatch. I've just run some seeds locally and I see this mismatch cause failures in 2 runs of 100, so the "pass rate" for this check goes from 93% to 98%, which should hopefully be worth it.
> [otbn,dv] Correct the timing for when we zero insn_cnt in model

- sw/device/tests/penetrationtests/README.md
In this commit, instructions how to build the pen. testing framework for the FPGA or the chip are added.
> [pentest/doc] Add building instructions

- hw/ip/otp_ctrl/doc/programmers_guide.md
This error may not be generated if the underlying OTP macro can actually perform the write operation by applying means to enable writes on existing data.
> [otp_ctrl/doc] Clarify documentation around MacroWriteBlankError

- hw/top_englishbreakfast/data/pins_cw305.xdc
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- hw/top_englishbreakfast/data/xbar_peri.hjson
- sw/device/lib/testing/pinmux_testutils.c
- sw/device/lib/testing/test_framework/ottf_console.c
- sw/device/sca/lib/sca.c
- util/topgen/templates/chiplevel.sv.tpl
For penetration testing, we've been using a second UART on the CW310 and the silicon platform such that the host can directly communicate with the target using the uJSON protocol instead of looping this communication through the simpleserial channel with the scope (available on Husky only anyways).
This commit now adds a second UART to the English Breakfast top level such that we can re-align the capture setups again. Ultimately, this will allow removing the simpleserial-based communication which will quite notably simplify code maintenance in the future.
For reference, see also https://github.com/lowRISC/ot-sca/issues/235.
> [top_englishbreakfast] Add second UART

- sw/host/hsmtool/src/commands/ecdsa/sign.rs
- sw/host/hsmtool/src/commands/ecdsa/verify.rs
- sw/host/hsmtool/src/commands/rsa/sign.rs
- sw/host/hsmtool/src/commands/rsa/verify.rs
- sw/host/hsmtool/src/util/helper.rs
- sw/host/hsmtool/src/util/signing.rs
To facilitate signing of ownership-related requests (e.g. signing the owner config and the unlock/activate commands), give hsmtool the ability to act on slices of the input.
1. Add the capability to sign and verify over a slice of the input file.
2. Add the capability to update the input file in place.
Example: Sign an owner config.
- The `format` is a plain-text slice from bytes 0..0x7a0 of the input file.
- The signature should be updated in place at bytes 0x7a0..0x7e0 of the input file.
```
hsmtool -t token -u user -p 123456 \
ecdsa sign --label owner_key \
--format slice:0..0x7a0 \
--update-in-place 0x7a0..0x7e0 \
owner_config.bin
```
Example: Verify the previously signed owner config.
```
hsmtool -t token -u user -p 123456 \
ecdsa verify --label owner_key \
--format slice:0..0x7a0 \ …
```
> [hsmtool] Support sign/verify over input slices

- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership_activate.c
- sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc
- sw/device/silicon_creator/lib/ownership/test_owner.c
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/defs.bzl
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/tests/ownership/flash_permission_test.rs
- sw/host/tests/ownership/rescue_limit_test.rs
- sw/host/tests/ownership/rescue_permission_test.rs
- sw/host/tests/ownership/transfer_lib.rs
- sw/host/tests/ownership/transfer_test.rs
1. Add a `config_version` field to permit monotonically increasing updates of the ownership configuration.
2. Add a `min_security_version_bl0` field to allow the owner to reset the minimum security version with a new ownership configuration.
3. Refactor the `test_owner_init` function into `sku_creator_owner_init` to allow versioned updates of built-in ownership configs.
4. Add tests for `min_security_version_bl0` and the built-in self update behavior.
> [ownership] Add config version and secver reset fields

- sw/host/opentitanlib/src/image/manifest_def.rs
- sw/host/opentitanlib/src/util/file.rs
- sw/host/opentitantool/src/command/bootstrap.rs
- sw/host/opentitantool/src/command/image.rs
When 'opentitiantool image manifest update ...' fails due to any input or output file name mistyped, or any of the input files does not exist, the error message is the same:
Error: No such file or directory (os error 2)
Which does not help much the operator. This patch adds some code which will print the name of the file causing the error.
Tested by invoking 'image manifest update' with incorrectly specified various input files. In case of the wrong SPX key file name the file name is printed twice, since the code is trying to read the file first trying to retrieve a private key, and then if unsuccessful - one more time trying to retrieve the public key.
This double print could be eliminated by proper return error processing, but is left as is at this time.
> [opentitantool] improve user experience

- hw/ip/pinmux/data/pinmux.hjson
- hw/ip/pinmux/data/pinmux.hjson.tpl
- hw/ip/pinmux/doc/registers.md
- hw/ip/pinmux/lint/pinmux.waiver
- hw/ip/pinmux/rtl/pinmux.sv
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
TAP strap 0 is sampled after reset (and only once for life cycle states
that are not TEST_UNLOCKED* or RMA).  To ensure it gets sampled as 0
unless driven to 1 from an external source (and specifically that it
gets sampled as 0 when left floating / not connected), this enables the
pull-down of the pad at reset.
This resolves issue #24576 on `master`.
> [top_earlgrey,pinmux] Enable pull-down for TAP strap 0 at reset

- hw/dv/sv/alert_esc_agent/alert_esc_if.sv
- hw/dv/sv/jtag_agent/jtag_if.sv
- hw/ip/pinmux/data/pinmux.hjson
- hw/ip/pinmux/data/pinmux.hjson.tpl
- hw/ip/pinmux/doc/registers.md
- hw/ip/pinmux/lint/pinmux.waiver
- hw/ip/pinmux/rtl/pinmux.sv
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
> [earlgrey_1.0.0] Update

- hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv
- util/reggen/reg_top.sv.tpl
This is an ECO on the `earlgrey_1.0.0` branch that adds a deglitcher on the `err_storage` output signal for the shadowed measurement control registers related **only to the MAIN clock domain**.  For the IO_DIV4 clock domain, this deglitcher is not required (because the register and the alert sender are clocked with the IO_DIV4 clock), and the other clock domains (IO, IO_DIV2, and USB) are less critical and out of scope of this ECO.
On the `master` branch, a separate PR will add a deglitcher on the registers for all clock domains (even IO_DIV4, for simplicity).
> [clkmgr] Deglitch shadow storage error for MAIN clock domain

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/keymgr.c
- sw/device/silicon_creator/lib/drivers/keymgr.h
- sw/device/silicon_creator/lib/drivers/kmac.c
- sw/device/silicon_creator/lib/drivers/kmac.h
- sw/device/silicon_creator/lib/drivers/kmac_functest.c
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/mock_ownership_key.cc
- sw/device/silicon_creator/lib/ownership/mock_ownership_key.h
- sw/device/silicon_creator/lib/ownership/ownership_key.c
- sw/device/silicon_creator/lib/ownership/ownership_key.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
This is a manual cherry-pick of  #23162 and #23183 to `earlgrey_es_sival`.
> Cherry-pick to earlgrey_es_sival: [rom_ext] Add KMAC256 operations using software and hardware keys

- util/design/lib/LcStEnc.py
- util/design/lib/OtpMemImg.py
- util/design/lib/OtpMemMap.py
- util/design/lib/common.py
- util/topgen.py
- util/topgen/secure_prng.py
This routine wasn't currently affecting the logic, but would have weakened certain seeds that happened to have low values. Ideally this should all be refactored to use byte strings so it's clearer what range the value is sampled from, but for now just removing the harmful logic should suffice.
> [util] Remove expand_seed routine.

- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block.h
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership_activate.c
- sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc
- sw/device/silicon_creator/lib/ownership/test_owner.c
[ownership] Use KMAC to seal the owner block to the chip 
1. Use KMAC to generate a chip-unique seal for an owner block.
Note: this PR depends on #23209.  You need only review the last commit.
> Owner page seal

- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/lib/ast_program_functest.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg_functest.c
This updates the individualization firmware to erase the AST configuration data from flash info after committing it to OTP.
This fixes #24526.
> [manuf] erase AST config data from flash after use

- sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_activate.h
- sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_unlock.h
- sw/device/silicon_creator/lib/drivers/lifecycle.c
- sw/device/silicon_creator/lib/drivers/lifecycle.h
- sw/device/silicon_creator/lib/drivers/mock_lifecycle.cc
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/ownership_activate.c
- sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc
- sw/device/silicon_creator/lib/ownership/ownership_unlock.c
- sw/device/silicon_creator/lib/ownership/ownership_unlock_unittest.cc
- sw/device/silicon_creator/lib/xmodem.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
- sw/host/opentitanlib/src/chip/boot_svc.rs
- sw/host/opentitanlib/src/chip/device_id.rs
- sw/host/opentitanlib/src/chip/helper.rs
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/opentitanlib/src/ownership/rescue.rs
- sw/host/opentitanlib/src/rescue/serial.rs
- sw/host/tests/ownership/flash_permission_test.rs
- sw/host/tests/ownership/rescue_limit_test.rs
- sw/host/tests/ownership/rescue_permission_test.rs
- sw/host/tests/ownership/transfer_lib.rs
- sw/host/tests/ownership/transfer_test.rs
1. Include the Device Identification Number (DIN) subfield of the full 256-bit device ID into the ownership unlock and activate commands.
2. Update the Rust versions of the unlock/activate requests to include the DIN.
3. Update unittests.
4. Update the rescue mode-change function to wait for the requested `mode` event to confirm entry into the requested mode.
5. Update ownership transfer tests.
> [ownership] Require the device ID for ownership unlock/activate

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/rom/e2e/weak_straps/BUILD
- sw/device/tests/BUILD
- sw/device/tests/autogen/BUILD
- sw/device/tests/crypto/BUILD
- sw/device/tests/pmod/BUILD
- sw/device/tests/spi_host_irq_test.c
- third_party/coremark/top_earlgrey/BUILD
- util/topgen/templates/BUILD.tpl
This PR partially addresses issues #24182 and #24184.
All Verilator test targets were run using public CI overnight in preparation for the addition of a weekly/nightly Verilator job in PR #24145. Of the 390 targets (at the time of testing), 14 explicitly failed and 67 timed out (when using `--test_timeout=2400,2400,3600,-1`). This PR accordingly:
- Marks all 67 timed-out tests as "manual", as they take at least 40 (and many > 60) minutes to complete when run on our public CI infrastructure and as such are too long to run in any sort of regular CI. The confirmation of whether these tests truly take a long time or should be marked broken and/or fixed is tracked by #24184. All of these tags are documented with the reason for their inclusion, mentioning whether the timeout used was 40 or 60 …
> [verilator, tests] Fix and tag failing & timed-out Verilator test targets

- ci/jobs/quick-lint.sh
- ci/scripts/exec-check.sh
- util/sh/scripts/run-shellcheck.sh
After the building of the site / landing page was moved to a separate repository, there is still an existing reference to the old `./ci/scripts/build-site.sh` script in `./ci/jobs/quick-lint.sh`, which causes the quick lint job to error near the end, This PR removes that reference from the job.
This commit also excludes the `build-site` directory from the CI executable file and shell check scripts, as current building of the docs via mdbook creates many executable files and shell scripts which do not pass linting standards (but are temporary, and local).
I've tested that this still works by simply running `./ci/jobs/quick_lint.sh`.
> [ci] Update quick-lint & CI scripts after site move

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/otp_ctrl_descrambling_test.c
This adds a top-level test for the descrambling functionality/datapath of `otp_ctrl`.  All checks are done in SW; there's no need for any checks on the DV side.  The test works by reading out all three SECRET OTP partitions from SW (which is possible before they get locked) and confirm that the descrambled value that SW reads from OTP equals the expected value that is stored in the OTP image (the OTP image itself is scrambled).
> [sw/tests] Add OTP descrambling test

- hw/ip/spi_host/rtl/spi_host_fsm.sv
This reverts commit 7eb53da738a770a4cc00153eb7179a2c2d9bdda9, which introduced a glitch on the `sd_en_o` output of `spi_host_fsm`.
This is **not an ECO** -- the ECO on the `earlgrey_1.0.0` branch is in PR #24501. This PR makes the long-term fix to `master`.
This resolves #24631.
TODO
> [spi_host/rtl] Fix `sd_en_o` of `spi_host_fsm`

- hw/ip/aes/dv/env/aes_env_cfg.sv
- hw/ip/aes/dv/env/aes_env_pkg.sv
- hw/ip/aes/dv/env/aes_message_item.sv
- hw/ip/aes/dv/env/aes_seq_item.sv
- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/tests/aes_alert_reset_test.sv
- hw/ip/aes/dv/tests/aes_b2b_test.sv
- hw/ip/aes/dv/tests/aes_base_test.sv
- hw/ip/aes/dv/tests/aes_clear_test.sv
- hw/ip/aes/dv/tests/aes_config_error_test.sv
- hw/ip/aes/dv/tests/aes_fi_test.sv
- hw/ip/aes/dv/tests/aes_manual_config_err_test.sv
- hw/ip/aes/dv/tests/aes_reseed_test.sv
- hw/ip/aes/dv/tests/aes_sideload_test.sv
- hw/ip/aes/dv/tests/aes_smoke_test.sv
- hw/ip/aes/dv/tests/aes_stress_test.sv
This PR contains a couple of commits to enable closing a small coverage hole.
The main commit is the last one. It properly randomizes the operation values. Previously, the operation field of the main control register was only written with valid one-hot encoded values but not with invalid values leading to a small DV coverage hole.
This resolves https://github.com/lowRISC/opentitan/issues/20941.
> [aes/dv] Randomly drive invalid AES operation values

- hw/top_earlgrey/formal/top_earlgrey_fpv_prim_cfgs.hjson
The existing code was wrong, and it was my fault: I had thought that the Jasper "-define" argument would turn into a pre-processor define. But it doesn't! It actually defines a TCL variable that (in our case) is visible in fpv.tcl.
Fortunately, the hjson/tcl machinery has a "defines" key, which common_formal_cfg.hjson translates into an FPV_DEFINES environment variable, which then gets picked up by fpv.tcl and passed in to the JasperGold "analyze" command.
This commit switches to using that.
> [fpv,prim] Fix PrimCountFpv define in prim_count tests

- hw/ip/ascon/data/ascon.hjson
- hw/ip/ascon/doc/registers.md
- hw/ip/ascon/pre_dv/ascon_tb/rtl/ascon_tl_ul_stim.sv
- hw/ip/ascon/rtl/ascon.sv
- hw/ip/ascon/rtl/ascon_core.sv
- hw/ip/ascon/rtl/ascon_pkg.sv
- hw/ip/ascon/rtl/ascon_reg_pkg.sv
- hw/ip/ascon/rtl/ascon_reg_top.sv
- hw/ip/prim/pre_dv/prim_ascon/prim_ascon_duplex_tb/rtl/prim_ascon_duplex_tb.sv
- hw/ip/prim/rtl/prim_ascon_duplex.sv
- hw/ip/prim/rtl/prim_ascon_pkg.sv
This PR implements the following tasks from https://github.com/lowRISC/opentitan/issues/22452
> [ascon_core] add ctrl/status information

- hw/ip/rv_dm/data/rv_dm.hjson
This follows the discussion in issue #22472, where we are now convinced that rv_dm is at the required stage.
Closes #22472.
> [rv_dm] Assert development stage V2S

- hw/ip/prim/rtl/prim_lfsr.sv
This initialisation isn't really needed because the array will come up as 'x and the SboxPermutationCheck_A assertion below would fail if the end result wasn't '1.
The existing code also causes a reported coverage hole in the FPV flow, which notes that assigning sbox_perm_test to zero has no effect.
Obviously, this is a little silly: it's inside ifndef SYNTHESIS so coverage doesn't really matter! But waiving this sort of coverage hole more generally might be tricky and this particular case can just be "fixed".
> [prim,fpv] Remove initialisation before a test

- hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv
This PR fixes the `rom_ctrl_kmac_err_chk_fix` test failure.
rom_ctrl_scoreboard happens to fails the [pwrmgr_complete](https://github.com/lowRISC/opentitan/blob/ec74fd4b3fff1d9764cf1956c9f75057c00660e7/hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv#L254C1-L254C74) check a cycle earlier when the rom_ctrl_fsm is not in a done state. rom_ctrl_fsm was still processing through its post-reset flow and state registers after virtual sequence ends.
The fix here ensures that the run_phase doesn't complete until the [pwrmgr_complete](https://github.com/lowRISC/opentitan/blob/ec74fd4b3fff1d9764cf1956c9f75057c00660e7/hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv#L254C1-L254C74)  has happened.
> [rom_ctrl,dv] Fixed rom_ctrl_kmac_err_chk_fix failure

- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_excl.el
Similar to this [PR](https://github.com/lowRISC/opentitan/pull/24606#issue-2536684988)
> [rom_ctrl,dv] Excluded continuous assignment blocks from line coverage

- sw/host/opentitanlib/src/transport/hyperdebug/dfu.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
Firmware upgrading of HyperDebug requires entering and leaving "DFU mode", each of which involves resetting connection with the USB device.
Previous code waited one second for the device to reset after upgrading concluded, before attempting to restablish USB connection with the newly flashed firmware.  This turns out to be insufficient on some machines.
This patch will wait up to five seconds, checking twice a second if the device is available, and terminating early if it is.
> [opentitantool] Improvement to HyperDebug firmware upgrade

- azure-pipelines.yml
This has been running in GitHub Actions cleanly for a couple of weeks.
The Azure version is running up on the disk space limit and taking longer than the GitHub version.
> [ci] Remove airgapped build from Azure CI

- .github/workflows/ci.yml
- azure-pipelines.yml
- ci/jobs/quick-lint.sh
- ci/scripts/validate_testplans.sh
- hw/lint/sival_testplan_schema.hjson
- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/data/ip/chip_adc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_otp_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rom_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
- hw/top_earlgrey/data/ip/chip_rv_dm_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- hw/top_earlgrey/data/standalone_sw_testplan.hjson
- util/validate_testplans.py
This PR is an updated version of a previous PR by @engdoreis found at https://github.com/lowRISC/opentitan/pull/20265, with merge conflicts resolved and with support for the `bazel` property of a testplan to be conditionally missing if the `si_stage` property is set to `NA`, as discussed [here](https://github.com/lowRISC/opentitan/pull/20265#discussion_r1541901278). That PR can be closed when this is merged. 
A JSON schema is used with the relevant python library to lint the testplans appropriately. This can be run using the below commands to verify that all testplans pass the linting.
```bash
./util/lint_testplan.py --schema hw/lint/sival_testplan_schema.json --dir hw/top_earlgrey/data/
```
```bash
./util/lint_testplan.py --schema hw/lint/sival_testplan_schema.json --dir …
```
> [ci, sival] Create a linter for the testplans

- hw/ip/tlul/rtl/tlul_sram_byte.sv
Currently, only a readback error check is reported when the `error_i` signal is not raised. However, as this signal is also raised when there is no activity on the TL-UL bus, we might miss some readback failures.
This commit modifies the error reporting logic to also report the readback mismatch when the error signal is raised.
Closes #24698.
> [tlul,rtl] Modify readback check error reporting logic

- hw/dv/sv/jtag_agent/jtag_if.sv
Fix the code to match to the comments (24MHz for GLS, 50MHz for RTL).
Reverting the frequencies in [#24580](https://github.com/lowRISC/opentitan/pull/24580) so it will be correct.
> [dv,jtag] Change JTAG clock frequency to 24MHz for GLS

- hw/ip/tlul/rtl/tlul_sram_byte.sv
Currently, only a readback error check is reported when the `error_i` signal is not raised. However, as this signal is also raised when there is no activity on the TL-UL bus, we might miss some readback failures.
This commit modifies the error reporting logic to also report the readback mismatch when the error signal is raised.
Closes #24698.
This is a cherry pick of PR  #24679 to branch earlgrey_1.0.0.
> [tlul/rtl] Modify readback check error reporting logic

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
This is spurred by a hole in conditional coverage where the following condition doesn't see the state where reset_req_en is not asserted.
```
assign ndmreset_ack = ndmreset_pending_q &&
lc_rst_pending_q &&
!ndmreset_req &&
!lc_rst_asserted &&
reset_req_en;
```
Thinking about it, we'd expect that to happen! So make it happen.
> [rv_dm,dv] Improve modelling of system bringup in ndmreset sequence

- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
1. Measure the owner configuration and combine that measurement with the
BL0 measurement to diversify the attestation ladder.
2. Apply the diversifier from the app verification key to the sealing
ladder iff the ownership state is LockedOwner.
Addresses: lowRISC#21583 (adds owner firmware measurement to CDI_1 cert)
Addresses: lowRISC#19596 (add owner configuration block measurement to CDI_1 cert)
> [rom_ext,ownership] Diversify keymgr on owner measurements 

- hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv
This is to fill a coverage hole, where the rom_intg_error signal is never seen going high in the coverage.
The signal *does* go high in the rv_dm_tl_intg_err test, but that test uses the "cover_reg_top" build_mode (in tl_access_tests.hjson). This build mode is intentionally configured not to collect coverage for anything but the TL-focused modules. This is done for VCS in cover_reg_top.cfg. The point is that if the block doesn't have a model against which we're checking, then the register tests might trigger weird behaviour that they don't notice. Therefore we shouldn't be tracking coverage of the non-TL-related signals for these tests, because they might not be testing the blocks that they exercise.
In the very specific case of TL integrity errors, it doesn't really matter: the only …
> [rv_dm,dv] Add a task that injects TL errors to the smoke sequence

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/cbor.h
- sw/device/silicon_creator/lib/cert/dice_cwt.c
- sw/device/silicon_creator/manuf/base/BUILD
To support mutliple DICE implementation (X.509 with ASN.1, and CWT with CBOR), it'll require to refactor current dice lib implementation.
1. Add a `dice_cwt` lib (implementation details to be added later)
2. Levaraging the third_party `open_dice` library to generate UDS_Pub structure
> [dice] Refactor the `dice` library to support multiple implementations

- util/dvsim/NcLauncher.py
skip checking job_runtime_secs against timeout_mins when timeout_mins is None
> fix job status poll logic when timeout is not specified

- sw/device/lib/testing/BUILD
- sw/device/lib/testing/spi_device_testutils.c
- sw/device/lib/testing/spi_device_testutils.h
- sw/device/lib/testing/spi_host_testutils.c
- sw/device/lib/testing/spi_host_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/power_virus_systemtest.c
- sw/device/tests/sim_dv/BUILD
- sw/device/tests/sim_dv/spi_host_tx_rx_test.c
- sw/device/tests/sim_dv/spi_passthrough_test.c
SPI pads should use strong drive strength and fast slew rate.
> [dv,spi] Set strong drive strength and fast slew rate for SPI pads

- sw/device/lib/dif/dif_pinmux.c
- sw/device/lib/dif/dif_pinmux.h
The MIO|DIO_PAD_ATTR registers are specified as WARL meaning certain bits written by software may get discarded by the hardware. For example the supported number of drive strength bits can depend on the hardware platform (simulation, FPGA, silicon).
Without this commit, the DIF treated these registers as RW: After writing pad attributes, it would perform a read back and error out in case of mismatches.
This is related to lowRISC/OpenTitan#24577.
---
The pinmux spec is probably a bit ambiguous with respect to the WARL/RW behavior of these registers:
I think the main issue is that the regtool does not support WARL inherently. But the registers are really WARL, depending on the hardware/simulation platform and pad implementation, a different number of drive strength bits can be accepted …
> [pinmux/dif] Allow WARL behavior for pad attribute registers

- hw/ip/prim/fpv/tb/prim_alert_rxtx_async_bind_fpv.sv
- hw/ip/prim/fpv/tb/prim_alert_rxtx_async_fatal_bind_fpv.sv
- hw/ip/prim/fpv/vip/prim_alert_rxtx_async_assert_fpv.sv
These tests weren't actually doing anything because we were binding them into a nonexistent module (found by looking at formal coverage).
Fix that and fix most of the broken properties. Annoyingly, `AlertCheck0_A` still doesn't quite work. This property is supposed to be putting an upper bound on the time between someone asking the alert sender to do something and the alert receiver registering that it has happened. I suspect this just needs a small tweak (since the non-async version is working fine!). But it seems a bit fiddly and I'm hoping someone who understands this primitive better than me can help...
I think this change is worth taking either way because it enables a load of testing that we weren't previously running. And most of it passes!
> [prim,fpv] Tweak the prim_alert_rxtx_async tests

- hw/dv/tools/vcs/cover.cfg
- hw/dv/tools/vcs/cover_reg_top.cfg
No functional change but this took me a while to understand! I think the "use in reg_top" comment in cover.cfg was copied from cover_reg_top.cfg (where it made slightly more sense).
> [dv,vcs] Tidy up the comments where we disable coverage in a prim

- .github/actions/install-deps/action.yml
- .github/workflows/ci.yml
- azure-pipelines.yml
- ci/.bazelrc
- ci/scripts/build-docs.sh
- ci/scripts/check-countermeasures.sh
- ci/scripts/check-generated.sh
- ci/scripts/check-vendoring.sh
- ci/scripts/check_bazel_target_names.py
- ci/scripts/check_bazel_test_suites.py
- ci/scripts/verible-lint.sh
This PR also includes a fix to the `install-deps` action for Verilator and Verible permissions.
It moves the "countermeasure implementation" check for `englishbreakfast` into the in-depth lint job for consistency.
> [ci] Move in-depth lint to GitHub Actions

- hw/ip/sram_ctrl/dv/README.md
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_lc_escalation_vseq.sv
- hw/ip/sram_ctrl/dv/sram_ctrl_exec_64kB_sim_cfg.hjson
- hw/ip/sram_ctrl/dv/sram_ctrl_main_sim_cfg.hjson
- hw/ip/sram_ctrl/dv/sram_ctrl_ret_sim_cfg.hjson
- hw/ip/sram_ctrl/dv/tb.sv
- hw/ip/sram_ctrl/dv/tests/sram_ctrl_base_test.sv
Only adds a clarification comment related to word addresses and SRAM configs used by Darjeeling.
> [hw,sram_ctrl,rtl] Sync sram_ctrl to master (integrated_dev to master)

- sw/device/silicon_creator/rom_ext/doc/ownership.md
Update the ownership transfer documentation.
- Include a diagram of ownership state transitions.
- Add a high-level description of the ownership configuration.
- Describe the uses of the `update_mode`.
- Update struct definitions to reflect the current implementation.
> [ownership] Update ownership transfer documentation

- sw/device/lib/crypto/impl/aes.c
Previously, the hot loop inside otcrypto_aes() would only ever have 2 blocks in flight while the underlying driver function aes_update() as well as the hardware allows up to 3 blocks being in flight:
- Block x-1 can be retrieved from the data output registers by SW.
- Block x   is being processed by HW.
- Block x+1 can already be provided via the data input registers by SW.
Doing this is better for SCA hardening (more concurrency means more background noise) and allows achieving higher throughput.
This is related to lowRISC/OpenTitan#20308.
This is a cherry pick of commit 8f0f5003a4f7b0df446c718a71fc84b7bbc75476 to branch earlgrey_es_sival.
> [crypto] Let otcrypto_aes() have up to 3 blocks in flight

- hw/top_earlgrey/BUILD
1. Correct a copy/paste error in the paths to proda key materials.
Addresses: #24641
> [rom_ext] Migrate ProdA users to ECDSA

- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership.h
- sw/device/silicon_creator/lib/ownership/ownership_unlock.c
- sw/device/silicon_creator/lib/ownership/ownership_unlock_unittest.cc
- sw/device/silicon_creator/lib/ownership/test_owner.c
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/defs.bzl
- sw/device/silicon_creator/rom_ext/e2e/ownership/flash_regions.c
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/boot_test.c
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/tests/ownership/BUILD
- sw/host/tests/ownership/flash_permission_test.rs
- sw/host/tests/ownership/newversion_test.rs
- sw/host/tests/ownership/transfer_lib.rs
The ownership `update_mode` allows the owner to attenuate the power of the unlock key:
- UpdateMode::Open - The unlock key has full unlock power.
- UpdateMode::Self - The unlock key can only unlock the device for updates to the self-same owner.
- UpdateMode::NewVersion - The device cannot unlock, but can accept a signed update from the self-same owner.
1. Add an `unlock_mode` field to the owner config and the associated UpdateMode constants.
2. Based on the UpdateMode, allow or deny the unlock command.
3. When in the NewVersion mode, check for updates during locked owner initialization.
4. Implement owner page lockdown based on the ownership state and update mode.
5. Test that updates are accepted in NewVersion mode.  Test that the permissions are set appropriately on the owner pages. …
> [ownership] Add an `update_mode` to the configuration

- util/py/scripts/mapfile_to_json.py
1. Display the size of an object if known.
2. Correctly test for a zero-length symbol list.
3. Display the address of objects without a name.
> [util] Enhance the `mapfile_to_json` script

- third_party/crt/repos.bzl
Bumps the CRT to the latest version. Here are the relevant CRT release items:
* Bump toolchain to release 20240923-1 by @luismarques in https://github.com/lowRISC/crt/pull/38
* Add `lto` feature to the `feature_set` `common` by @luismarques in https://github.com/lowRISC/crt/pull/36
* [features] Add LTO feature by @luismarques in https://github.com/lowRISC/crt/pull/25
* Add -Wtype-limits feature by @jwnrt in https://github.com/lowRISC/crt/pull/34
> Bump CRT to v0.4.13

- sw/host/hsmtool/src/commands/ecdsa/sign.rs
- sw/host/hsmtool/src/commands/ecdsa/verify.rs
- sw/host/hsmtool/src/commands/rsa/sign.rs
- sw/host/hsmtool/src/commands/rsa/verify.rs
- sw/host/hsmtool/src/util/signing.rs
When a sign or verify requests `little-endian`, the input should only be reversed if it is already a Sha256 hash.  We assume a pre-hashed input comes from opentitantool, which writes out its hash digests in little-endian order.
> [hsmtool] Refactor input endianness handling

- hw/top_darjeeling/dv/top_darjeeling_sim_cfgs.hjson
- hw/top_darjeeling/lint/top_darjeeling_dv_lint_cfgs.hjson
- hw/top_darjeeling/lint/top_darjeeling_fpga_lint_cfgs.hjson
- hw/top_darjeeling/lint/top_darjeeling_fpv_lint_cfgs.hjson
- hw/top_darjeeling/lint/top_darjeeling_lint_cfgs.hjson
This PR adds the block level lint and sim configuration for the Darjeeling top. It only adds the IPs that are used in Darjeeling, ignoring other IPs that are used in Earlgrey.
The PR enables the DMA, MBX, KeymgrDPE, soc_proxy IP.
> [top_darjeeling,lint,sim] Add lint and sim cfg for Darjeeling

- hw/ip/rom_ctrl/dv/env/rom_ctrl_env_cfg.sv
The conditional coverage was uncovered on [L157](https://github.com/KinzaQamar/opentitan/blob/6e5b27f59be08e442daf27791f085f77c9695896/hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv#L157) for kmax_err_i being 1. This is due to the scenario an unaligned transitions b/w fsm state (ReadingHigh), kmac_done_i, counter_done and kmac_err_i. All should be synced and raised on the exact clock edge. kmac_err_i was unsynced and raised to 1 when the state was RomAhead.
The fix tweaks the rsp_delay in rom_ctrl_env_cfg.sv just to get the precision in the delay and that kmac_err_i should be raised for the particular scenario when state is ReadingHigh and both kmac_done_i and counter_done are set.
> [rom_ctrl, dv] Fixed rom_ctrl checker fsm conditional coverage

- hw/dv/sv/mem_bkdr_scb/mem_bkdr_scb.sv
- hw/ip/sram_ctrl/data/sram_ctrl_sec_cm_testplan.hjson
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_readback_err_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_vseq_list.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_env.core
- hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cfg.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
- hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
This commit provides a new sec_cm_readback test that tests the SRAM readback FI countermeasure. In the test, a fault is injected during one of the read/write SRAM requests. The test checks, whether the expected alert fires.
Closes #23322.
> [sram_ctrl,dv] Add sec_cm_mem_readback test

- sw/device/silicon_creator/lib/ownership/testdata/basic_owner.json5
- sw/host/opentitanlib/src/ownership/application_key.rs
- sw/host/opentitanlib/src/ownership/flash.rs
- sw/host/opentitanlib/src/ownership/flash_info.rs
- sw/host/opentitanlib/src/ownership/misc.rs
- sw/host/opentitanlib/src/ownership/mod.rs
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/opentitanlib/src/ownership/rescue.rs
- sw/host/opentitantool/src/command/ownership.rs
The ownership structs are TLV structs and the TLV headers and other
reserved fields are often irrelevant to the human-readable json
representation of the ownership config.
1. Add a flag to control serialization of headers and reserved fields.  By default, do not serialize them.
2. Handle a missing ownership seal in json.
3. Provide lower-case enum aliases for ownership configs.
> [opentitantool] Add a debug flag to ownership serialization 

- hw/ip/mbx/rtl/mbx_sramrwarb.sv
The error signal is only valid if the valid signal from the TLUL host is asserted. This explicitly gates the error signal with the corresponding valid signal in order to not introduce a change to the TLUL host adapter.
> [hw,mbx,rtl] Gate TLUL error with valid signal

- hw/ip/rv_dm/dv/env/rv_dm_env.core
When the core file originally got a dependency on the IP itself (in 1f3a0e5f53b), the tests were only actually depending on the debug module package. But that's not true any more! In particular, rv_dm_env_pkg now depends on rv_dm_reg_pkg (since commit 840a2455268).
Depend on hw:ip:rv_dm to make this explicit (rather than depending on the ordering fusesoc happens to choose, which doesn't necessarily get what we need).
> [rv_dm,dv] Slightly broaden dependency in rv_dm_env.core

- azure-pipelines.yml
The documentation build is currently broken on the `earlgrey_es_sival` branch.  The aparent cause is a missing DV report from the reports bucket.
Addresses: #24772
> [docs] Disable documentation rendering (`earlgrey_es_sival`)

- .github/actions/install-deps/action.yml
The binaries were compiled with the `v4.210` component of the path, so we have to leave this in.
> [ci] Fix verilator installation path

- .github/actions/install-deps/action.yml
The GitHub-provided setup-python action does not create portable binaries (https://github.com/actions/setup-python/issues/871) and can cause failure for bitstream cache. Instead, ask uv to manage our dependencies.
> [ci] use uv to manage Python and pip dependencies

- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_primary_test.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
A number of `boot_log` fields are copies of fields in `boot_data`. Since boot services can update `boot_data`, we need to initialize those `boot_log` entries after boot services completes.
Fixes: 24768
> [rom_ext] Initialize boot_log after boot_svc

- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
1. Claim 2 pages as CreatorReserved.  These pages are to be used in the future for creator features or some other as-yet unanticipated need.
2. Arrange for the OwnerReserved pages to be arranged equally between the banks.
3. Update OwnerReserved page indicies in perso.
> [flash_crtl] Re-arrange the INFO page layout

- quality/BUILD.bazel
- util/sh/scripts/run-shellcheck.sh
This PR:
* Fixes shellcheck errors in the `run-shellcheck.sh` script.
* Fixes the path to the `shellcheck` binary when run under Bazel.
* The current method uses a hard-coded path in `external/` which is fragile.
* This path is incorrect under bzlmod.
* Use the more robust `$(location ...)` method via an env var instead.
> [bazel] Fix shellcheck lints and path to binary

- sw/device/silicon_creator/rom_ext/e2e/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/defs.bzl
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/tests/ownership/transfer_lib.rs
Include the `usage_constraint` field from ApplicationKeys into the overall constraint requirement.
> [ownership] Include ApplicationKey constraints

- hw/top_earlgrey/BUILD
The sival key is not part of the prodc keyset.
> Fix rsa signing for silicon_owner_prod<c/a>_rom_ext

- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership_activate.c
- sw/device/silicon_creator/lib/ownership/ownership_activate.h
- sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc
- sw/device/silicon_creator/lib/ownership/test_owner.c
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/proda/proda_owner.c
- sw/device/silicon_creator/rom_ext/prodc/prodc_owner.c
- sw/device/silicon_creator/rom_ext/sival/sival_owner.c
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/tests/ownership/newversion_test.rs
Allow the owenrship block to specify that it is locked to a specific device ID.
1. Add `lock_constraints` and `device_id` fields to the owner config.
2. Use the device_id from the lifecycle controller in the cryptographic verification of the owner config.
3. Add tests to verify node locking.
Addresses: #24657
> [ownership] Add node-locked owner configs 

- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
I noticed that running `//sw/device/examples/teacup_demos:teacup_leds_demo` on a HyperTeacup rev 1.5.0 board doesn't work as-is (the board's LEDs don't light up at all). This PR fixes the issue, although I'm not sure whether this is the best solution and would appreciate feedback from folks more familiar with the board design and this part of the codebase. 
Explanation:
The latest rev of the HyperTeacup board (v1.5.0) connects the active-low shutdown pin of the LED driver to HyperDebug pin CN10.15. The board pulls this pin low with a resistor, so the HyperDebug needs to actively drive it high to enable the LED driver. (See signal `LED_DRV_SD_L` on pages 5 and 7 of the [schematic](https://github.com/lowRISC/opentitan-hyperdebug-shield/blob/main/drawings/hyp_ot_evt_v150_042624.pdf)). 
This …
> [opentitanlib] Activate LED driver on HyperTeacup 1.5

- hw/top_earlgrey/syn/chip_earlgrey_asic.sdc
- hw/top_earlgrey/syn/ot.sdc_setup.tcl
Please review the two files, confirm them and use it for future sdc edits.
chip_earlgrey_asic.ot.sdc replaces the previous chip_earlgrey_asic.sdc
> [sdc] update sdc after PD review

- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/mock_ownership_key.cc
- sw/device/silicon_creator/lib/ownership/mock_ownership_key.h
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership_activate.c
- sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc
- sw/device/silicon_creator/lib/ownership/ownership_key.c
- sw/device/silicon_creator/lib/ownership/ownership_key.h
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/boot_test.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/tests/ownership/transfer_test.rs
1. Rewrite the OwnerSecret page when performing an ownership transfer.
2. Test that the sealing derivation changes in each state along the transfer (e.g. CurrentOwner -> Unlocked -> NextOwner).
Addresses: #24667
> [ownership] Update owner entropy upon transfer

- hw/ip/spi_host/data/spi_host.hjson
- hw/ip/spi_host/doc/interfaces.md
- hw/ip/spi_host/rtl/spi_host.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
In this minimal implementation, SPI Host asserts `lsio_trigger_o` iff the TX FIFO fill level is smaller than the configured watermark or the RX FIFO fill level is greater than or equal to the configured watermark, independent of IRQ enablement.
> [hw,spi_host,rtl] Implement LSIO trigger (integrated_dev to master)

- hw/ip_templates/rv_plic/rtl/rv_plic.sv.tpl
- hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic.sv
This provides `ASSERT definition that is otherwise missing
> Add missing include to rv_plic template file

- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block.h
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership_unlock.c
- sw/device/silicon_creator/lib/ownership/ownership_unlock_unittest.cc
- sw/device/silicon_creator/rom_ext/doc/rescue.md
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/host/opentitanlib/src/ownership/owner.rs
1. The `SelfVersion` update mode permits either an ownership unlock to `UnlockedSelf` or a new-version update from the current owner.
2. Adjust rescue security: Always allow the `REBO`, `WAIT` and `BAUD` commands.
> [ownership] Add a SelfVersion update_mode 

- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/kmac_endianess_test.c
This commit adds a chip level test to test the endianess feature of KMAC. This includes the message as well as the state register.
The following configurations are covered:
- Little endian message, little endian digest.
- Little endian message, big endian digest.
- Big endian message, little endian digest.
- Big endian message, big endian digest.
Currently, only the KMAC mode is covered. However, as the big/ little endian feature should be independent of the underlying mode, this should be sufficient.
> [sival,kmac] Add kmac_endianess test

- hw/ip/otbn/dv/otbnsim/sim/sim.py
This fixes a problem problem that was visible in the otbn_escalate test. It is caused by the design bug that is tracked in issue #23903. The one cycle glitch wouldn't be a big deal but we might be really unlucky and read the register at just the wrong time!
The change in sim.py changes otbnsim to correctly model the design's behaviour, with a whopping great TODO message that explains how to undo the change again.
**However** tracking down whether this fixes everything found that this doesn't *completely* fix the `otbn_escalate` test, which still occasionally fails! Delving into the problem carefully, you find that the model's status signal (represented as `status_q` in `otbn_core_model.sv`) normally changes at the same time as the register top's `status_qs` signal. This is reasonably …
> [otbn,dv] Model a glitch on the STATUS register

- rules/otp.bzl
This commit enables installing opentitantool to find and link to its library dependencies like libftdi, libusb, libudev that are installed in
user's work area. This is particularly useful when the user's compute
enironment does not have these libraries preinstalled as part of the system and the user doesn't have root permissions to install these libraries using syatem package managers. While the custom paths to the headers and shared libs needed for building the opentitantool can be specified by setting the PKG_CONFIG_PATH environment variable through the bazel build action_env property in site specific .bazelrc-site file, these paths are not available in the bazel sandbox that runs the opentitantool to generate the otp json.
for example, bazel build …
> [dv, bazel] : run opentitantool with shared libs outside system lib path

- hw/ip/pinmux/data/pinmux.hjson.tpl
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_pkg.sv
- util/topgen.py
The attr_dw topgen parameter for pinmux generation is unused, since it is used to initialize the unused SV parameter AttrDw. Also, the value used to initialize it was wrong anyway.
> [pinmux,gen] Remove unused generator parameter

- sw/device/lib/base/macros.h
- third_party/hyperdebug/repos.bzl
- third_party/openocd/repos.bzl
- third_party/python/pip.bzl
- third_party/rust/BUILD
- third_party/rust/crates/BUILD.openssl-sys-0.9.102.bazel
- third_party/rust/crates/defs.bzl
- third_party/rust/deps.bzl
- third_party/sphincsplus/repos.bzl
This change enables this repo (`lowrisc_opentitan`) to be brought in as an external Bazel dependency in another Bazel project for the purpose of building opentitanlib as an external dependency in another Bazel project. This will be used by the `opentitan_provisioning` repo to build a provisioning testbed based on FPGA provisioning flows.
> [bazel,otlib] enable otlib to be built as external dep

- sw/device/silicon_creator/rom_ext/e2e/attestation/BUILD
- sw/device/silicon_creator/rom_ext/e2e/attestation/print_certs.c
- sw/host/opentitanlib/src/image/image.rs
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/tests/attestation/BUILD
- sw/host/tests/attestation/attestation_test.rs
- third_party/rust/Cargo.toml
- third_party/rust/crates/defs.bzl
Examine the attestation certificates and check the measurements published in the DiceTcbInfo extensions.
> [rom_ext_e2e] Check the attestation certificates 

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/dice.h
- sw/device/silicon_creator/lib/cert/dice_cwt.c
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.h
This PR has two commits that:
1. Move the calculation of OTP measurement from `dice_uds_tbs_cert_build` to `ft_personalize`
2. Modify the perso flow to complete the provisioning of the `CreatorSwCfg` and `OwnerSwCfg` OTP partitions at the end of the process.
- Sets the expected values for fields in the OTP that are not provisioned until the final stages of personalization.
- Compare the OTP measurement used during certificate generation with the value stored in the OTP.
This PR addresses #24610 partially.
> [manuf] Finalize {Creator,Owner}SwCfg at end of perso flow 

- hw/ip/otp_ctrl/data/otp_ctrl_img.c.tpl
- rules/const.bzl
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.h
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg_functest.c
This PR has two commits that:
1. Separate the provisioning of the MANUF_STATE OTP field from the rest of the CREATOR_SW_CFG partition and provision it at the end of perso firmware.
2. Bind the personalization firmware with the `PERSO_INITIAL` manufacturing state.
- Define `PERSO_INITIAL` creator manufacturing state.
- Create a new `manifest_perso` with `Initial` manufacturing state binding.
This PR addresses #24610 partially.
Note: this depends on #24783. Only review the last 2 commits.
> [manuf] Bind perso firmware with PERSO_INITIAL MANUF_STATE

- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/kmac_kmac_key_sideload_test.c
This commit adds the chip_sw_kmac_kmac_key_sideload test. In this test, a sideloaded key is used in KMAC. The output is stored in retention SRAM, a reset is performed, and it is checked whether the same KMAC output is generated.
> [sival,kmac] chip_sw_kmac_kmac_key_sideload

- sw/device/silicon_creator/lib/dice.c
- sw/host/tests/attestation/BUILD
- sw/host/tests/attestation/attestation_test.rs
1. Report the DICE measurements in big-endian order.
2. Check the key IDs reported by the DICE certs.
> [rom_ext, attestation] Fix DICE measurements

- util/topgen/templates/toplevel_pkg.sv.tpl
There was a hard coded reference to Earlgrey in the `toplevel_pkg` template. Remove that and fetch that information from the provided parameters.
> [topgen,template] Don't hardcode Earlgrey in toplevel_pkg

- hw/top_earlgrey/data/ip/chip_otp_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson
- hw/top_earlgrey/data/ip/chip_uart_testplan.hjson
These targets have different names to what's in the testplans.
> [sival] Fix bazel target spellings

- sw/device/silicon_creator/lib/base/util.c
- sw/device/silicon_creator/lib/base/util.h
- sw/device/silicon_creator/lib/cert/cbor.h
- third_party/open-dice/Add-a-local-strlen-implementation.patch
- third_party/open-dice/repos.bzl
It requires some more cbor wrappers to generate different type of data. Add
1. A patch to open-dice library for strlen()
2. A binary to hex-string convertor
3. Wrappers of cbor_writer to perform API status check
> [dice,cwt] Add more utilities for CWT implementation

- sw/host/opentitanlib/src/proxy/handler.rs
- sw/host/opentitanlib/src/proxy/protocol.rs
- sw/host/opentitanlib/src/transport/proxy/gpio.rs
Add a few method needed to propagate calls to `Gpio::analog_write()` and `Gpio::analog_read()` via the proxy protocol.  This appears to have been an oversight at the time when the analog functionality was added, which has gone undetected the feature was needed by Google now.
> [opentitantool] Support gpio analog-write via proxy

- hw/ip/otp_ctrl/data/earlgrey_skus/prodc/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- hw/ip/otp_ctrl/data/otp_ctrl_img.c.tpl
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.h
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg_functest.c
- util/design/gen-otp-immutable-rom-ext-json.py
This PR has two commits that:
1. Update ROM_EXT immutable section OTP gen tooling
- Consider `_rom_ext_start_address` when determining the manifest start address to support the common rom_ext binary
- Updates the OTP  JSON file with data from an immutable ROM_EXT section only if the immutable ROM_EXT is enabled.
2. Delay IMMUTABLE_ROM_EXT_EN provisioning to end of personalization
- Separate the provisioning of the IMMUTABLE_ROM_EXT_EN OTP field from the rest of the CREATOR_SW_CFG partition
- Use the ROM_EXT immutable section OTP gen tool by default when building personalization binary
This PR addresses #24610 partially.
Note: this depends on #24783 and #24789. Only review the last 2 commits.
> [bazel,otp,manuf] Support immutable ROM_EXT enabling during personalization 

- hw/ip/otp_ctrl/data/earlgrey_skus/prodc/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/device/silicon_creator/manuf/lib/BUILD
This removes several duplicate and unused OTP image and overlay definitions across the prodc and sival SKUs. Note, most image definitions removed were those from the prodc SKU as they are not used during sival. Only the prodc *_SW_CFG definitions should exist as those could *potentially* be different and are used to generate a different individualization binary for provisioning.
> [otp_img] cleanup OTP images used across SKUs

- sw/device/tests/BUILD
- sw/device/tests/aes_interrupt_encryption_test.c
@moidx  Checking in aes_interrupt_encryption_test.c code and modified the BUILD to include this test.
> [sival/aes] Add AES Interrupt Encryption tests

- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership.h
- sw/device/silicon_creator/lib/ownership/testdata/basic_owner.json5
- sw/device/silicon_creator/rom_ext/data/rom_ext_e2e_testplan.hjson
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/prodc/prodc_owner.json5
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/opentitanlib/src/chip/boot_svc.rs
- sw/host/opentitanlib/src/chip/mod.rs
- sw/host/opentitanlib/src/ownership/flash.rs
- sw/host/opentitanlib/src/ownership/flash_info.rs
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/tests/ownership/flash_permission_test.rs
- sw/host/tests/ownership/transfer_lib.rs
1. Rename `protect_when_primary` to `protect_when_active`, as this feature
is supposed to protect flash pages in whichever side is the active side
regardless of which side is the primary side.
2. When this feature was named `protect_when_primary`, I did the
seemingly correct thing and protected the slot that was the primary
boot slot.  This is, in fact, not what this feature should actually
do; it _should_ protect the active slot.
3. Update the test to verify the behavior of the feature in both slots.
> [ownership] Fix protect_when_active behavior 

- sw/device/silicon_creator/rom_ext/defs.bzl
Features:
- Ownership Transfer.
- Valid DICE chain from CA->UDS->CDI_0->CDI_1.
Bug fixes:
- `protect_when_primary` is renamed to `protect_when_active` and protects whichever slot is the active slot.
> [rom_ext] Advance version to ROM_EXT 0.6

- hw/ip/otp_ctrl/data/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/prodc/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- hw/ip/otp_ctrl/data/otp_ctrl_img.c.tpl
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.h
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg_functest.c
- sw/device/silicon_creator/manuf/lib/util.c
- sw/device/silicon_creator/manuf/tests/BUILD
- sw/host/provisioning/ft/BUILD
- sw/host/tests/manuf/individualize_sw_cfg_functest/src/main.rs
- util/design/lib/OtpMemImg.py
This updates the FT individualization provisioning stage to provision the first stage secure boot keys into the ROT_CREATOR_AUTH* partitions.
Doing so required updating the OTP C file constants generation to allow generating a C file that contains the secure boot key constants that are to be provisioned into OTP during individualization.
Additionally, this fixes a bug in the generation of the perso firmware that was always using the sival SKU OTP SW_CFG constants for the fields that cannot be provisioned during individualization. Now, a separate personalization binary is generated for each SKU.
Lastly, this simplifies how FT binary generation is done. Specifically, FT individualization and personalization binaries are generated based on a SKU. A SKU can be defined as a combination of the …
> [manuf,otp] provision secure boot keys during individualization

- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_next_test.c
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_primary_test.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
The `primary_bl0_slot` can be reported incorrectly when a `SetNextBl0` command is issued.
1. Initialize `boot_log->primary_bl0_slot` before boot services so that a temporary override doesn't get reported as the new primary.
2. Update the "set next bl0" test to verify that the primary_bl0_slot didn't change.
> [rom_ext] Fix reporting of `primary_bl0_slot`

- sw/device/silicon_creator/rom_ext/defs.bzl
Features:
- Ownership Transfer.
- Valid DICE chain from CA->UDS->CDI_0->CDI_1.
Bug fixes:
- `protect_when_primary` is renamed to `protect_when_active` and protects whichever slot is the active slot.
- Report the `primary_bl0_slot` correctly after a `SetNextBl0` command.
> [rom_ext] Advance version to ROM_EXT 0.7

- hw/ip_templates/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_shadow_attack_vseq.sv
- hw/ip_templates/rstmgr/dv/env/seq_lib/rstmgr_sec_cm_scan_intersig_mubi_vseq.sv
- hw/top_earlgrey/ip_autogen/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_shadow_attack_vseq.sv
- hw/top_earlgrey/ip_autogen/rstmgr/dv/env/seq_lib/rstmgr_sec_cm_scan_intersig_mubi_vseq.sv
This PR adds two changes to make the rstmgr simulation compatible with xcelium:
1. It removes the `@edge` and replaces it with a combination of `@posedge` and `@negedge`
2. Because of strong typing rules it's possible to directly read via `uvm_hdl_read` into a `prim_mubi_pkg::mubi4_t`. Read into a `logic` and cast the result to `prim_mubi_pkg::mubi4_t`
> [hw,rstmgr,dv] Use Xcelium compatible syntax

- hw/ip/dma/dv/doc/tb.svg
- hw/ip/dma/dv/tb/tb.sv
- hw/ip/dma/rtl/dma.sv
- util/reggen/fpv_csr.sv.tpl
This PR adds two fixes needed after merging the DMA to master:
1. It changes the SHA mode `None` to `SHA_None`, which was changed in the related upstream package
2. It removes the devmode interface, which was removed from the upstream register tooling.
> [hw,dma] DMA fixes after merge to master

- hw/ip/keymgr_dpe/dv/README.md
- hw/ip/keymgr_dpe/dv/tb.sv
- hw/ip/mbx/dv/env/mbx_env_cfg.sv
- hw/ip/mbx/rtl/mbx_hostif.sv
- hw/ip/mbx/rtl/mbx_sysif.sv
- hw/ip_templates/rstmgr/dv/README.md.tpl
- hw/top_earlgrey/ip_autogen/rstmgr/dv/README.md
The `devmode` interface on the reg_tops was removed on master. This PR removes all references to that from the `keymgr_dpe`, `mbx`, and `rstmgr` IPs.
> [keymgr_dpe,mbx,rstmgr]  Remove references to obsolete devmode interface

- util/dvsim/NcLauncher.py
The timeout_mins specified in the test list json file or on dvsim command
line is intended to be a timeout on the wall time elapsed after the job
has started running.It is not intended to count in the time spent in waiting for a compute node and/or a license to become available. Despite best efforts to specify license resource strings, the availability of a compute node doesn't always guarantee the availability of a license as this scheme only works when all jobs from all projects running on the cluster adhere to this license requesting scheme which sadly can't be enforced in a fool proof manner.
In the proposed scheme, the file size as a proxy to determine if the job has really started running. While this is not one hundred percent accurate, it prevents false timeouts on jobs/tests that …
> [dv, dvsim] Add job queue/lic wait timeout in addition to run timeout

- azure-pipelines.yml
- ci/scripts/run-fpga-tests.sh
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
- sw/device/silicon_creator/rom_ext/e2e/handoff/BUILD
- sw/device/silicon_creator/rom_ext/e2e/lockdown/BUILD
- sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
- sw/device/silicon_creator/rom_ext/rescue.c
This is a manual cherry-pick of #24430,
Use the fpga_hyper310_rom_ext environment for ROM_EXT end-to-end tests.
The hyperdebug serial ports support serial break out of the box, whereas
the CW310 serial ports require special SAM3x firmware to support serial
break.
> Cherry-pick to earlgrey_1.0.0: [rom_ext_e2e] Update CI to run ROM_EXT tests on hyper310

- sw/host/opentitanlib/src/image/manifest.rs
- sw/host/opentitanlib/src/image/manifest_ext.rs
- sw/host/opentitanlib/src/image/testdata/manifest_ext.hjson
Add opentitantool image manifest support for Integrator Specfic Firmware Binding (ISFB) extensions.
The following manifest extensions were added:
1. isfb: Integration specific firmware binding manifest extension. Contains anti-rollback strike mask as well as device expecific product expression.
2. isfb_erase_policy: This extension is used to authorize erasing of the ISFB region. Intended for testing purposes. The implementation will require node-locking for this policy to be effective.
This change does not integrate the extensions into the build system. This will be done in a separate commit.
This is part of: https://github.com/lowRISC/opentitan/issues/24666
> [opentitantool] Add ISFB manifest extensions.

- hw/dv/sv/tl_agent/dv/tb/tb.sv
- hw/dv/sv/tl_agent/dv/tl_agent_sim_cfg.hjson
The code successfully removes the `covg_disable_cg` flag for xcelium. 
However, the test still fails for xcelium with:
```
UVM_WARNING @ 0 ps: reporter [BDTYP] Cannot create a component of type 'tl_agent_base_test' because it is not registered with the factory.
UVM_FATAL @ 0 ps: reporter [INVTST] Requested test from command line +UVM_TESTNAME=tl_agent_base_test not found.
UVM_INFO /tools/eda/cadence/xcelium/23.09-s004/tools/methodology/UVM/CDNS-1.2/sv/src/base/uvm_report_catcher.svh(705) @ 0 ps: reporter [UVM/REPORT/CATCHER]
--- UVM Report catcher Summary ---
````
@rswarbrick As an UVM expert, could you help me on that one?
> [tl_agent,dv] Disable covg_disable_cg for xcelium

- rules/opentitan/ci.bzl
This swaps the priority of CW310 and CW340 jobs. If a test can run on the CW340 then it will, else it will fall back to the CW310.
This is required so that we can check tests as they're moved over to running on the CW340s.
> [ci] Prioritise CW340 jobs in CI over CW310

- sw/device/tests/BUILD
- sw/device/tests/spi_device_tpm_tx_rx_test.c
SPI device pads should use strong drive strength and fast slew rate.
> [SPI,dv] Set strong drive strength and fast slew rate for SPI device

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/rom_ext/sival/BUILD
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/ft_lib/src/lib.rs
This enables loading a combined image containing the personalization firmware in slot a and ROM_EXT in slot b during personalization flow. This also enhances the opentitan bootstrap test utils to support loading different binaries. 
This PR addresses https://github.com/lowRISC/opentitan/issues/24610 partially.
> [manuf] load the assembled image during perso

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/device/silicon_creator/rom_ext/prodc/BUILD
- sw/host/provisioning/ft/src/main.rs
This updates the SKU configuration to enable selection of the transport image that is loaded in flash slot B during personalization.
This fixes #17394.
> [manuf] move transport image selection to SKU config

- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/host/opentitantool/src/command/certificate.rs
- sw/host/ot_certs/BUILD
- sw/host/ot_certs/src/lib.rs
- sw/host/provisioning/cert_lib/BUILD
- sw/host/provisioning/cert_lib/src/lib.rs
- sw/host/provisioning/ft_lib/src/lib.rs
This updates the perso flow to verify the entire DICE certificate chain using OpenSSL on the host side. This fixes #24954.
> [manuf] update perso flow to validate the DICE chain with OpenSSL on the host

- sw/device/silicon_creator/manuf/base/BUILD
This decreases the test timeout for the FT provisioning flow from "long" to "moderate" so that it is always run in CI. Currently CI only runs "short" and "moderate" tests due to resource constraints.
> [manuf] decrease FT provisioning flow test timeout

- hw/ip/prim/rtl/prim_pulse_sync.sv
This is needed to be able to analyze `prim_pulse_sync.sv` on its own (i.e., together with the modules it hierarchically instantiates but without assuming any non-dependencies have been analyzed before it).
> [prim_pulse_sync] Add missing `include "prim_assert.sv"`

- sw/device/lib/crypto/drivers/BUILD
- sw/device/lib/crypto/drivers/hmac.c
- Implement a workaround in C cryptolib as HW is hanged
after a stop in certain conditions.
- Refer to issue https://github.com/lowRISC/opentitan/issues/24767
> [hmac,sw] Workaround to avoid hang - Stop CMD is not triggered

- util/cmdgen.py
Commands may contain paths, which are relative to the root of the repository.  In order to make command invocation independent of the current working directory, we set `cwd` of `subprocess.run` to the root of the repository.
This supersedes PR #24986.
> [util/cmdgen.py] Ensure working directory is repo root

- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
The AND within the if is not supported in xcelium. Factor this out into a dedicated signal.
> [hw,keymgr,dv] Fix unsupported AND within an if

- .github/actions/install-deps/action.yml
- .github/workflows/ci.yml
- azure-pipelines.yml
This PR cherry-pick the minimum number de commits necessary for having the file `.github/actions/install-deps/action.yml` backported across into the `earlgrey_1.0.0` branch.
We need this change for the SiVal nightly job, which will run from master, but it will checkout the `earlgrey_1.0.0` branch.
> [ci,SiVal] Backport github actions to earlgrey_1.0.0

- .github/actions/prepare-env/action.yml
- .github/workflows/ci.yml
- ci/bazelisk.sh
This should not be merged yet until we have configured bucket permission so that workload identity federation can write to the cache properly.
> [ci] configure Bazel cache for GitHub actions

- ci/scripts/check-generated.sh
- doc/contributing/doc/README.md
- hw/Makefile
Change ci/scripts/check-generated.sh to run both top and cmdgen when checking for the topgen generated artifacts. This is to support template md files having no text between the BEGIN and END markers so they can handle multi-top.
Add a separate "cmdgen" target in the hw/Makefile and describe that in the README.md for contributing to documentation.
Fixes #24991
> [ci,check-generated] Handle empty text in CMDGEN

- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
The old `hmac_kat` and `hash_kat` cryptotest targets had been split up. This PR updates these targets in the HMAC and KMAC testplans.
One thing to note is that looking at cSHAKE, it only has four test cases that are defined in `sw/device/tests/kmac_mode_cshake_test.c`. We don't have any large set of NIST KAT test vectors since I don't think they ever released any. We do have two examples that NIST has provided that we manually extracted from a PDF. They are currently in `sw/device/tests/crypto/testvectors/cshake_hardcoded.hjson` but are not used anywhere. Do we want to include these two hardcoded tests?
More broadly, do we want to include the hardcoded tests under `sw/device/tests/crypto/testvectors` for other algorithms as well as part of the sival tests? As best as I can tell, several …
> [sival] Replace nonexistent bazel targets in HMAC and KMAC testplans

- hw/cdc/tools/dvsim/meridiancdc.hjson
- hw/cdc/tools/meridiancdc/run-cdc.tcl
- hw/top_earlgrey/cdc/chip_earlgrey_asic_cdc_cfg.hjson
- hw/top_earlgrey/cdc/user_configuration.tcl
This file allows to configure the CDC tool after constraints have been evaluated and additional user intents specified.  The file is currently empty; it will be populated in later PRs.
> [cdc,top_earlgrey] Add user configuration file

- sw/device/lib/testing/otp_ctrl_testutils.c
- sw/device/lib/testing/otp_ctrl_testutils.h
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.h
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg_functest.c
This PR has 3 commits that
1. Extend write-before-check  the following RoT partitions:
- `kDifOtpCtrlPartitionRotCreatorAuthCodesign`
- `kDifOtpCtrlPartitionRotCreatorAuthState`
2. Ensure the OTP measurements used during certificate generation match the final OTP values both before and after the OTP partitions are locked.
3. Refactor the OTP field configuration process by consolidating several individual functions into a single, unified function.
- The following functions have been removed:
- `manuf_individualize_device_flash_data_default_cfg()`
- `manuf_individualize_device_creator_manuf_state_cfg()`
- `manuf_individualize_device_immutable_rom_ext_en_cfg()`
- `manuf_individualize_device_rom_bootstrap_dis_cfg()`
- These functionalities are now handled by the …
> [manuf] Improve re-entrancy of the FT provisioning flow

- hw/top_earlgrey/syn/chip_earlgrey_asic.sdc
Some of the constraints in the SDC file were not fully clear and this commit adds comments to provide relevant background information.
This is a follow-up of lowRISC/OpenTitan#24221.
> [sdc] Add clarifying comments to SDC file

- util/dvsim/Deploy.py
- util/dvsim/FlowCfg.py
- util/dvsim/SimCfg.py
- util/dvsim/modes.py
These comparisons trigger flake8 warnings if you have a PR that touches any of these files. Get rid of them.
> [dvsim] Avoid some type comparisons in dvsim code

- hw/ip/pwm/dv/env/seq_lib/pwm_stress_all_vseq.sv
Fixing the number of sequences that is run to 5 (instead of uniformly choosing from [5, 8]) will slightly reduce the average number of iterations (from 6.5 to 5). The plus side is that it will avoid very long runs (which occasionally time out because they take more than 10s). We'll still get a reasonable number of "back-to-back" sequences (since 5 is much more than 1!).
The total amount run will drop slightly. To avoid that, we could up the reseed count for this test to 6.5/5*50 = 65, but I'm reasonably convinced that the number for this vseq come from a default, so I don't believe there's any need to worry about it.
> [pwm,dv] Cap number of sequences in pwm_stress_all_vseq

- util/dvsim/SlurmLauncher.py
Incorporate post-merge feedback from @matutem to improve the error handling and make try/catch block only deal with IO.
> [dvsim] Improve error handling on slurm launcher

- sw/device/lib/dif/dif_keymgr.c
- sw/device/lib/dif/dif_keymgr.h
- sw/device/lib/dif/dif_keymgr_unittest.cc
- sw/device/lib/testing/keymgr_testutils.c
- sw/device/lib/testing/keymgr_testutils.h
- sw/device/tests/BUILD
- sw/device/tests/keymgr_derive_cdi_test.c
- sw/device/tests/keymgr_key_derivation_test.c
- sw/device/tests/penetrationtests/firmware/sca/ibex_sca.c
This PR comprises two commits that ultimately lead to the implementation of `chip_sw_keymgr_derive_sealing` and `chip_sw_keymgr_derive_attestation`:
- Commit 1: The keymgr IP supports both the sealing and attestation CDI flows,
which is controlled by the `CDI_SEL` field in the `CONTROL_SHADOWED`
register. So far, this field was hardcoded to the sealing type in the
keymgr DIF. This commit parametrizes the field, making it possible to
also invoke the attestation flow through the DIF. In particular, the
commit comprises the following changes:
- A new `dif_keymgr_cdi_type_t` enumeration type.
- A new `dif_keymgr_identity_seed_params_t` struct such that the CDI
flow can be chosen for the identity derivations.
- A new `cdi_type` field in `dif_keymgr_versioned_key_params_t` to
chose the CDI flow …
> [sival, keymgr] chip_sw_keymgr_derive_{sealing,attestation}

- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.h
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
Currently, during ft_perso, the host writes the raw endorsed X.509 certificates (in ASN.1 DER format) to flash_info pages. When it needs to access them later on, the certificate length is calculated by parsing the ASN.1 header (1 or 2 bytes). This design works for X509 but not CWT-CBOR since there's no such information in some CBOR types (map, array specifically). This updates the perso flow to write the certificates to the info page wrapped in the perso LTV object header. Additionally, this refactors the `perso_tlv_data` code to use `rom_error_t` where applicable so it can be shared with the ROM_EXT, which also must parse and potentially update CDI_0/1 DICE certificates.
Fixes #24942.
Test: //sw/device/silicon_creator/manuf/base:ft_provision_cw340
This is a refactor of #24951 that …
> [manuf,rom_ext] write certs to flash in perso LTV object format

- hw/dv/tools/common.tcl
- hw/dv/tools/dvsim/common_modes.hjson
- hw/dv/tools/dvsim/common_sim_cfg.hjson
- hw/dv/tools/dvsim/vcs.hjson
- hw/dv/tools/dvsim/xcelium.hjson
- hw/dv/tools/sim.tcl
- util/dvsim/Deploy.py
- util/dvsim/FlowCfg.py
- util/dvsim/LocalLauncher.py
- util/dvsim/SimCfg.py
- util/dvsim/dvsim.py
Add a GUI debug mode for Xcelium. Turn on debug features:
- breakpoints
- live data
- transaction recording
And run simulation up until the end of the UVM elaboration phase to have access to the dynamic objects.
This mode is available through the dvsim command line arguments: `--gui-debug` or `-gd`
> [dv] Add GUI debug mode for Xcelium

- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
Manual cherry-pick of https://github.com/lowRISC/opentitan/pull/24637. 
The first commit from #24637 was not required since boot measurements are already stored in a static critical section in `earlgrey_1.0.0`.
> [ownership] Manual cherry-pick of #24637

- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.h
- sw/device/silicon_creator/manuf/base/personalize_ext.h
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
The DICE UDS certificate is endorsed offline at manufacturing time, and injected into a flash info page on the chip. It must remain stable for the lifetime of a chip.
Previously, the CDI_0 and CDI_1 DICE certificates were also written to the same flash info page. However, the ROM_EXT can update these certificates in the event that the ROM_EXT or Owner FW is ever updated (as this triggers a CDI0/1 key pair change). To update these certificates, the ROM_EXT buffered all certificates in RAM, erased the flash info page, and re-wrote it with the udpated certificates.
If there is a power outage during the certificate update, after the flash page was erased but before the certificates had been written back, there could be a moment when the UDS certificate was lost.
To prevent this from …
> [manuf,rom_ext] move UDS cert to separate info page

- hw/ip/dma/rtl/dma.sv
The instantiation of `prim_sha2_32` changed in master. New inputs/outputs were added. This PR updates the instantiation within the DMA.
> [hw,dma,rtl] Update instantiation of prim_sha2_32

- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- sw/device/silicon_creator/lib/otbn_boot_services_functest.c
Also:
- remove one reference to a KMAC crypto test that doesn't actually cover the test point
- make a small adjustment to the boot services test so that it covers all key manager stages
- adjust the attestation test point to not generate SW output (we would never need to do this for the attestation CDI, so I'm not sure it makes sense to include it -- if there's a reason I'm happy to add it back)
I went through the test plan (at the suggestion of @matutem) to see if any crypto tests I know of might cover the test points. I found one that's mostly covered by some attestation tests, but mostly the points covered by crypto tests were already noted. I adjusted the attestation tests to more thoroughly cover the test point, as well (by going through the same steps in one additional key manager …
> [sival] Add a few crypto/boot services test refs to testplan.

- sw/device/lib/crypto/drivers/hmac.c
- Add HMAC idle polling to be sure that the HW is ready after the temporary workaround for context switching.
- To complete https://github.com/lowRISC/opentitan/pull/24944 as already merged.
- This was missing and has been caught after updating the programmer's guide (see https://github.com/lowRISC/opentitan/pull/24966)
> [hmac,sw] Poll HMAC IDLE state

- .github/actions/prepare-env/action.yml
- .github/workflows/nightly.yml
This PR publishes the test results produced by bazel in a gcp bucket for the Nightly job for now.
The results will be consumed by scripts which will feed the Grafana database and the SiVal spreadsheet.
> [ci, SiVal] Publish bazel result to a gcp bucket

- sw/device/silicon_creator/manuf/base/ft_personalize.c
A SHA256 measurement of the owner FW and owner configuration block had not been completed before using the measurement.
> [perso] fix bug in SHA256 measurement computation

- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.h
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
This cherry-picks #24992 to `earlgrey_1.0.0` branch to change how certs are written to flash info pages.
> [cherry-pick] manually cherry-pick of #24992 to `earlgrey_1.0.0` branch

- sw/device/silicon_creator/lib/base/util.c
- sw/device/silicon_creator/lib/base/util.h
- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/cbor.h
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/dice_cwt.c
- sw/device/silicon_creator/lib/cert/dice_keys.c
- sw/device/silicon_creator/lib/cert/dice_keys.h
Some DICE key creation constants and utilities are invoked by several modules.
Refactor them for a better code reuse.
> [dice] Refactor some dice related constants and APIs

- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.h
- sw/device/silicon_creator/manuf/base/personalize_ext.h
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
This cherry-picks https://github.com/lowRISC/opentitan/pull/25029 to `earlgrey_1.0.0` branch to move UDS DICE cert to its own flash info page.
> [cherry-pick] manually cherry-pick of #25029 to `earlgrey_1.0.0` branch

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/device/silicon_creator/rom_ext/e2e/defs.bzl
- sw/device/silicon_owner/bare_metal/BUILD
This separations makes it easier to prepare transport images for devices being provisioned.
With this change, SKU owners can now place a bazel label in the [EARLGREY_SKUS configuration dict](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl;l=21?q=provisioning_inputs.bzl&ss=opentitan%2Fopentitan) for which ROM_EXT target they want to bootstrap into slot B to boot after perso runs, and similarly they can place a bazel label in the same configuration dict for which owner FW target they want to bootstrap in owner slot B to be booted by the ROM_EXT after perso runs.
> [perso] separate transport image into ROM_EXT and OWNER fw

- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/kmac_error_conditions_test.c
This adds the new `kmac_error_conditions_test` test that is defined in the `chip_sw_kmac_error_conditions` chip level test.
> [sival,kmac] Add kmac_error_conditions_test

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/dice.h
- sw/device/silicon_creator/lib/cert/dice_cwt.c
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
In order to have a better diff for code review, those changes are kept in rom_ext.c for now,
and we’ll move them to `silicon_creator/lib/cert/` in a follow-up PR.
---
This PR contains several bugfixes and refactoring of the DICE-related logics in rom_ext.
* Global variables are encapsulated in `dice_cert_t` and related code are encapsulated in `dice_chain_*` functions for moving.
* Includes more boundary checks on the cert buffer in RAM to avoid overflow.
* TLV object is parsed at where it will be consumed to handle parsing errors correctly.
* Stale TLV objects will be cleared if parsing fails.
* Certificate checking function are moved to dice library to handle different formats.
* TLV name will also be checked when validating the cert.
* Invalidate the remaining buffer before encoding …
> [rom_ext] encapsulate dice logics for moving to silicon_creator lib

- sw/device/silicon_creator/lib/cert/cert.h
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/dice.h
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/ft_personalize.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.h
- sw/device/silicon_creator/manuf/base/personalize_ext.h
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/provisioning/ft_lib/src/lib.rs
- sw/host/provisioning/perso_tlv_lib/src/lib.rs
In this implementation,
- Add one more object type "kPersoObjectTypeCwtCert" to reflects the CWT implementation
- Update "struct personalize_extension_pre_endorse{}" to pass more OTP measurments to the perso_ext for uds_build_tbs()
- Update the personalize_endorse_certificates() logic, to parse the payload based on DICE chain type
Bug: 356532759
Bug: #24943 
Test: //sw/device/silicon_creator/manuf/base:ft_provision_cw340
> [dice,cwt] Endorse and store all 4 DICE CWT/X509 certificates

- hw/ip/kmac/dv/env/kmac_env_cov.sv
- hw/ip/kmac/rtl/kmac_pkg.sv
- sw/device/lib/dif/dif_kmac.h
- sw/device/lib/dif/dif_kmac_unittest.cc
The `ErrShadowRegUpdate` code is never used in the RTL. Instead, according to the documentation, on a shadow register update error, a recoverable alert shall be triggered - this recoverable alert then is signaled in the STATUS register and not in the error code register.
Hence, this commit removes this error code as well as the corresponding SW code (`kDifErrorShadowRegisterUpdate`).
> [kmac, rtl/dv/sw] Remove unused error code

- hw/ip/pwm/dv/README.md
- hw/ip/pwm/dv/env/pwm_env.sv
- hw/ip/pwm/dv/env/pwm_env_cfg.sv
- hw/ip/pwm/dv/env/pwm_env_pkg.sv
- hw/ip/pwm/dv/env/pwm_scoreboard.sv
- hw/ip/pwm/dv/env/pwm_seq_cfg.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_perf_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_rand_output_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_smoke_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_stress_all_vseq.sv
This builds on #24929, which should be merged first. Only the last 5 commits are unique to this PR:
- a379082dec [pwm,dv] Remove set_reg_en from pwm_base_vseq
- ebc2609c82 [pwm,dv] Remove duration_cycles from the vseqs
- 870fb50c98 [pwm,dv] Remove get_pwm_mode and pwm_mode_e from pwm_env_pkg
- 40b73b899d [pwm,dv] Rewrite pwm_env_cfg using out-of-block declarations
- d267b5ca87 [pwm,dv] Rewrite pwm_scoreboard using out-of-block declarations
> [pwm,dv] Remove lots of dead code from the environment and do some tidying

- hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_common_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_perf_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_rand_output_vseq.sv
This is not the entire DV code (because the list of commits was getting rather long!), but changes a reasonable tranche. There are five commits:
- [pwm,dv] Change rand_pwm_blink to return the randomised value
- [pwm,dv] Use out-of-block declarations in pwm_base_vseq
- [pwm,dv] Use out-of-block declarations in pwm_common_vseq
- [pwm,dv] Correctly set duty_cycle / blink in pwm_perf_vseq
- [pwm,dv] Use out-of-block declarations in pwm_perf_vseq
> [pwm,dv] Use out-of-block declarations in some of the DV code

- rules/manifest.bzl
- sw/device/silicon_creator/rom_ext/e2e/isfb/BUILD
- sw/host/opentitanlib/src/image/image.rs
- sw/host/opentitanlib/src/image/manifest_def.rs
- sw/host/opentitanlib/src/image/manifest_ext.rs
- sw/host/opentitanlib/src/image/testdata/manifest.hjson
- sw/host/opentitanlib/src/image/testdata/manifest_ext.hjson
- sw/host/opentitantool/src/command/image.rs
Update `opentitanlib` and `opentitantool` to support manifest extension configuration parameters in the main manifest JSON file.
1. Discontinue support for the `--manifest_ext` flag in the image manifest update command. Most extensions are manipulated directly by the command, and other extension parameters are now included in the main manifest JSON configuration file.
2. Update `ManifestExtEntrySpec` to add an attribute to determine if a given manifest extension should be signed. The OpenTitan specifications defines whether a extension should be signed or not. Capturing this information in `opentitanlib` makes the implementation less prone to user configuration errors.
3. Make `ManifestExtEntrySpec` serialization use named attributes to make the configuration easier to read.
4. Remove …
> [manifest tools] Add extension params to manifest json file.

- hw/ip/dma/data/dma.hjson
- hw/ip/dma/doc/registers.md
- hw/ip/dma/dv/env/dma_env_cov.sv
- hw/ip/dma/dv/env/dma_env_pkg.sv
- hw/ip/dma/dv/env/dma_scoreboard.sv
- hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv
- hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv
- hw/ip/dma/rtl/dma.sv
- hw/ip/dma/rtl/dma_reg_pkg.sv
- hw/ip/dma/rtl/dma_reg_top.sv
- sw/device/lib/dif/autogen/dif_dma_autogen.c
- sw/device/lib/dif/autogen/dif_dma_autogen_unittest.cc
- sw/device/lib/dif/dif_dma.h
- sw/device/lib/dif/dif_dma_unittest.cc
- sw/device/lib/testing/autogen/isr_testutils.c
- sw/device/lib/testing/autogen/isr_testutils.h
This PR adds a new STATUS.chunk_done bit to the status register to determine the cause when the DMA stopped an operation. In multi-chunk mem2mem transfers, where each chunk is transferred with a separate SW-go, `chunk_done` goes high when finishing every chunk, except the last chunk, where `done` goes high. The `done` interrupt fires for every chunk for now.
> [hw,dma,rtl] Add STATUS.chunk_done bit

- hw/ip/pwm/data/pwm_testplan.hjson
- hw/ip/pwm/dv/env/pwm_env.core
- hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_heartbeat_wrap_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_vseq_list.sv
- hw/ip/pwm/dv/pwm_sim_cfg.hjson
This covers a code coverage hole, where we didn't see the second ternary on this line being true:
assign duty_cycle_htbt = !dc_wrap_q ? dc_htbt_q : pos_htbt ? 16'hffff : '0;
The code is trying to saturate the updated `dc_htbt_q` value to `[0, ffff]`. Underflowing zero isn't too hard, but we never saw the behaviour when we overflowed `ffff`.
(This PR builds on #25056, which should be merged first. Once that has been merged, this PR only contains the last commit, whose commit message appears above)
> [pwm,dv] Add a pwm_heartbeat_wrap test to see heartbeat wrapping

- hw/ip/prim/rtl/prim_util_memload.svh
Put memory path printing into a synthesis exclusion block to avoid synthesis tools complaining about it and ignoring it anyway.
> Exclude mem init dynamic `if` from synthesis

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
GitHub action is moving latest to 24.04 and 20.04 may be deprecated soon. The Ubuntu 20.04 OS itself will also reach EOL early next year.
> [ci] move GitHub runner to Ubuntu 22.04

- sw/host/tests/chip/spi_device/src/spi_host_config_test.rs
Cherry-picking #23398 based on a very old green CI run introduced a build issue, in that one more test case had been introduced into the branch, which required a slight adaptation.
> [tests] Adapt one test broken by cherry-pick #23398

- hw/ip/kmac/data/kmac.hjson
- hw/ip/kmac/doc/interfaces.md
- hw/ip/kmac/dv/README.md
- hw/ip/kmac/dv/env/kmac_env.sv
- hw/ip/kmac/dv/env/kmac_env_cfg.sv
- hw/ip/kmac/dv/env/kmac_env_cov.sv
- hw/ip/kmac/dv/env/kmac_env_pkg.sv
- hw/ip/kmac/dv/env/kmac_if.sv
- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/kmac/dv/env/kmac_virtual_sequencer.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_app_with_partial_data_vseq.sv
- hw/ip/kmac/dv/tb.sv
- hw/ip/kmac/lint/kmac.waiver
- hw/ip/kmac/rtl/kmac.sv
- hw/ip/kmac/rtl/kmac_app.sv
- hw/ip/kmac/rtl/kmac_pkg.sv
- hw/top_darjeeling/templates/toplevel.sv.tpl
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/templates/toplevel.sv.tpl
- util/reggen/gen_cfg_md.py
- util/reggen/inter_signal.py
- util/reggen/ip_block.py
- util/reggen/params.py
- util/topgen.py
- util/topgen/intermodule.py
- util/topgen/merge.py
This PR adds support for parametrized inter-module signals. Previously, when an inter-module signal depended on a parameter, you needed to specify the `width` value twice. Once for the parameter and once when the value is used for the width of the inter-module signal. 
This PR fixes that and adds support for parameters being used for the width of an inter-module signal. When you want to do that, you need to expose the parameter. If `local` is set, the parameter will be created as localparam in the top-level file, and the interconnection uses that parameter. If `local` is `false`, a top-level parameter is created, but also a local parameter within the `reg_pkg` of the IP.
The PR is separated into 2 parts:
1. The infrastructure implemetnation
2. Using that feature for the KMAC `NumAppIntf` …
> [topgen] Support for parametrized inter-module signals

- hw/ip/pwm/rtl/pwm_chan.sv
This is equivalent logic but avoids a coverage hole where the simulator complains that we don't hit blink_en_i=1 and htbt_en_i=0 in the second check. This doesn't happen because we don't actually get to the second check in that case.
> [pwm,rtl] Recode a 3-way selector to avoid a coverage hole

- hw/ip/uart/dv/env/uart_scoreboard.sv
Add a wait cycle between updates to the TX watermark/empty interrupts. This represents the single cycle that the interrupts may flip for between a TX item being added by the register interface and *almost* immediately popped off by the transmission logic.
> [uart,dv] Tweak modelling of TX FIFO interrupts

- hw/ip/rom_ctrl/data/rom_ctrl_testplan.hjson
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_common_vseq.sv
- hw/ip/rom_ctrl/dv/rom_ctrl_base_sim_cfg.hjson
The nightly regression coverage dashboard thrown an uncovered conditional coverage hole on L138 and L131 in tlul_adapter_sram. To resolve the issue rom_ctrl_sec_cm test has been used. 
This PR fixes two kind of vulnerabilities.
1) The test rom_ctrl_sec_sm wasn't collecting the coverage for the wires that were uncovered by the report. Fixing this was straight forward to add the proxy binds in rom_ctrl_base_sim_cfg.hjson that were injecting faults to different blocks inside rom_ctrl and add the sec_cm_count test_plan in rom_ctrl_testplan.hjson. 
2) As the test inject faults to different blocks of rom_ctrl(FSM, SRAM, ...), the testbench should know what to do next if something bad has happened. For this particular coverage hole, the proxy_if was prim_count that pokes cnt_q in prim_count.sv …
> [rom_ctrl, dv] Uncovered conditional coverage for tlul_adapter_sram

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/dice_cwt.c
Add some helper functions and a CDI_* builder manually.
Some of the changes in the builder will be replaced by a following RP on opentitantool > codegen feature.
> [dice,cwt] Add CWT implementation

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/perso_tlv_data.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.h
- sw/device/silicon_creator/manuf/base/tpm_personalize_ext.c
Eliminate a dependency in `//sw/device/lib/runtime:log` and `//sw/device/lib/base:status`, as these two deps are not wanted in rom or rom_ext code.
> [rom_ext] Eliminate unwanted dependencies

- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership.h
- sw/device/silicon_creator/lib/ownership/testdata/basic_owner.json5
- sw/device/silicon_creator/rom_ext/data/rom_ext_e2e_testplan.hjson
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/opentitanlib/src/chip/boot_svc.rs
- sw/host/opentitanlib/src/chip/mod.rs
- sw/host/opentitanlib/src/ownership/flash.rs
- sw/host/opentitanlib/src/ownership/flash_info.rs
- sw/host/opentitanlib/src/ownership/owner.rs
- sw/host/tests/ownership/flash_permission_test.rs
- sw/host/tests/ownership/transfer_lib.rs
This is a manual cherry-pick of #24879.
1. When this feature was named `protect_when_primary`, I did the
seemingly correct thing and protected the slot that was the primary
boot slot.  This is, in fact, not what this feature should actually
do; it _should_ protect the active slot.
2. Update the test to verify the behavior of the feature in both slots.
> Cherry-pick to earlgrey_1.0.0: [ownership] Fix protect_when_active behavior

- hw/ip_templates/pinmux/data/pinmux.tpldesc.hjson
- util/ipgen/renderer.py
This PR fixes 2 comments from previous PRs:
* On the pwrmgr, it defines a typed variable
* On the pinmux, a boolean parameter is used in the template description
> [pwrmgr,pinmux] Cleanup comments from previous PRs

- sw/device/tests/BUILD
- sw/device/tests/i2c_target_test.c
- sw/host/opentitanlib/src/test_utils/i2c_target.rs
The I2C target test was failing because the ujson `I2cTestConfig` command added for clock stretching (#22816) when backported from `earlgrey_es_sival` did not have a CRC added to it (#22277), causing the de-serialization to fail. This was not noticed as the test was marked broken at the time due to an unrelated issue (#22729). This commit adds this CRC, adds an additional CRC to the configuration payload itself, and marks the test as no longer being broken. 
This has been tested locally to pass on a CW310 using: `./bazelisk.sh test -t- --test_output=streamed --runs_per_test 10 //sw/device/tests:i2c_target_test_fpga_cw310_sival`.
> [sival,i2c] Fix and re-enable I2C target test by adding config ujson CRC

- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/ft_lib/src/lib.rs
The raw RMA token is input into the FT provisioning test harness, where the harness itself computes the digest before sending the digest to the device. Additionally the token is 128-bits, not 64.
> [manuf] update RMA token input name

- sw/device/silicon_creator/rom_ext/rom_ext.c
The DICE UDS cert was moved to a different cert page than the CDI_* certs but the page configuration was not setup properly. This fixes it. Thansk to @vbendeb for finding this.
> [rom_ext] setup scrambling and ECC on factory certs page

- util/device_sw_utils/extract_sw_logs.py
This PR addresses #20139.
As described there, there is currently no implementation of the custom formatting specifier `%r` in the C to System Verilog DV logging backdoor, which means that such logs end up producing irrelevant and useless error messages on DV test benches. 
I spent a while investigating the best way to fix this - custom System Verilog logic for performing the formatting could be introduced. However, while investigating this, it was found that `%r` was not the only broken formatting specifier, which is now tracked by a larger issue #24522.
As mentioned there, any relevant fix will likely require a large change to the way that the DV logging is performed, such as the introduction of a logging DPI to maintain consistency with non-DV logging. As such, it was opted to take a …
> [sw,dv] Add support for basic `status_t` (%r) logging in DV tests

- sw/device/tests/BUILD
- sw/device/tests/entropy_src_fw_observe_many_contiguous.c
- sw/device/tests/entropy_src_fw_override_test.c
This PR partially addresses #24184 (specifically, it addresses the two tests found to fail if given long enough to run in Verilator).
Entropy is generated much more slowly in Verilator, and as a result, two tests were timing-out (and if given long enough, failing) when run in Verilator. These are `sw/device/tests:entropy_src_fw_observe_many_contiguous_test_sim_verilator`, and `sw/device/tests:entropy_src_fw_override_test_sim_verilator`. This PR conditionally lowers the test requirements for the Verilator simulation environment to allow these tests to pass on Verilator.
For `fw_observe_many_contiguous_test`, the number of entropy samples to be observed is reduced from 1024 to just 8, as the full 1024 would take around 13-15 hours. For `fw_override_test`, the entropy consumers have been …
> [entropy_src,verilator] Reduce entropy tests requirements on Verilator to fix failing test targets

- hw/ip/rom_ctrl/dv/cov/cover_reg_top.cfg
- hw/ip/rom_ctrl/dv/rom_ctrl_base_sim_cfg.hjson
The coverage collection for tlul_adapter_sram for rom_ctrl_tl_intg_err test was disabled. The rom_ctrl_tl_intg_err test covers the intg_err signal in tlul_adapter_sram in rom_ctrl.
To let the nightly regression dashboard reporting intg_err as 1/0 being covered for the conditional statements present in rom_ctrl tlul_adapter_sram, this PR added a cover_reg_top.cfg file and overrides it in rom_ctrl_base_sim_cfg.hjson.
> [rom_ctrl, dv] Coverage Collection for tlul_adapter_sram

- rules/opentitan/cc.bzl
- sw/device/silicon_creator/manuf/base/BUILD
This adds a rule (`opentitan_binary_assemble`) to assemble a flash image from several opentitan_binary images. This is usefule when building firmware images during provisioning.
> [bazel] add rule to assemble several binaries

- rules/opentitan/cc.bzl
- sw/device/silicon_creator/manuf/base/BUILD
This adds a rule (`opentitan_binary_assemble`) to assemble a flash image from several opentitan_binary images. This is useful when building firmware images during provisioning.
> [cherry-pick] manual cherry-pick of #25130 to `earlgrey_1.0.0`

- rules/const.bzl
- rules/opentitan/toolchain.bzl
- util/design/gen-otp-immutable-rom-ext-json.py
This enhances the ROM_EXT immutable section OTP tooling to embed the first three bytes of immutable ROM_EXT hash into the `MANUF_STATE` field in the `CREATOR_SW_CFG` OTP partition.
This partially addresses #24610
During boot, if the immutable ROM extension feature is enabled, ROM verifies the IM_EXT hash against the OTP value. Any mismatch results in an immediate ROM shutdown, safeguarding the device's integrity. However, this check occurs after ROM_EXT signature verification, and there's no fallback to another slot if the hash is invalid.
To mitigate this limitation, we use the first three bytes of `CREATOR_SW_CFG_MANUF_STATE` to represent the first three bytes of IM_EXT's hash. If the IM_EXT feature is disabled, "000000" is used instead. This allows us to invalidate the ROM_EXT's …
> [otp] Embed the first three bytes of imt_ex hash into MANUF_STATE

- hw/ip/dma/data/dma.hjson
- hw/ip/dma/doc/registers.md
- hw/ip/dma/dv/env/dma_env_pkg.sv
- hw/ip/dma/dv/env/dma_scoreboard.sv
- hw/ip/dma/dv/env/dma_seq_item.sv
- hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv
- hw/ip/dma/dv/env/seq_lib/dma_generic_vseq.sv
- hw/ip/dma/dv/tb/tb.sv
- hw/ip/dma/rtl/dma.sv
- hw/ip/dma/rtl/dma_reg_pkg.sv
- hw/ip/dma/rtl/dma_reg_top.sv
- sw/device/lib/dif/autogen/dif_dma_autogen.c
- sw/device/lib/dif/autogen/dif_dma_autogen.h
- sw/device/lib/dif/autogen/dif_dma_autogen_unittest.cc
This PR adds a new chunk_done interrupt. This interrupt is raised for chunked mem2mem transfers when a single chunk is transferred and the SW needs to start the transfer of a new chunk. When transferring the last chunk, only the `done` interrupt is raised.
This PR is based upon https://github.com/lowRISC/opentitan/pull/24108
> [hw,dma] Add a chunk_done interrupt

- sw/device/tests/pmod/BUILD
This will enable this test to run on the SiVal nightlies.
> [SiVal, spi_host] Update execution environment of macronix test

- sw/device/silicon_creator/rom_ext/e2e/dice_chain/BUILD
- sw/device/silicon_creator/rom_ext/e2e/dice_chain/no_refresh_test.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
There's one rebase conflict resolved incorrectly in #24980. It tries to load the CDI certs from the Factory page which is only for UDS cert. So the CDI certificate is always not found, making the rom_ext refreshing the cert chain on every boot.
* Specify flash pages explicitly, so each certificate's handler is independent without relying on previous states.
* Add the UDS certificate error message back so we can do e2e test with perso.
* An new e2e test is added to ensure we skip unnecessary update correctly.
> [rom_ext,dice] Fix incorrect dice page id

- sw/host/ot_certs/src/asn1/x509.rs
- sw/host/ot_certs/src/template/mod.rs
- sw/host/ot_certs/src/template/testgen.rs
- sw/host/ot_certs/src/x509.rs
- sw/host/ot_certs/src/x509/extension.rs
- sw/host/ot_certs/tests/parse_test.rs
The primary goal of this PR is to fix some flakiness in the `ot_certs` parse test. See the commit for an explanation.
The short summary is that OpenSSL has an undocumented quirk: if the basic key usage is empty (and possibly in other circumstances?), it silently pretend that the certificate has no authority or subject key identifier. It is not clear whether this is intentional or a side-effect of a bug but the result is the same: a seemingly valid (but stupid) certificate will generate an error when parse with ot_certs. When we generate random certificates for parsing test, we can sometimes create some with no key usage set which triggers this behaviour.
To solve this, I have switch to manually parsing of the auth key id and subj key id. This is very easy and we already parse most …
> [ot_certs] Various fixes

- hw/ip/pwm/dv/pwm_sim_cfg.hjson
I think the initial commit of this code included a run mode as default (presumably when getting it working in the first place), which wasn't stripped out. Strip it out.
> [pwm,dv] Avoid running as UVM_HIGH by default

- hw/ip/pwm/dv/pwm_sim_cfg.hjson
This builds upon #25054 and the only unique commit is the second. The message for that commit is:
> The default timeout is 0.2 seconds and at a 5MHz clock, we're not *quite* finished in time.
> [pwm,dv] Set a sensible timeout for slowest clocks

- hw/ip/pwm/dv/env/seq_lib/pwm_rand_output_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_smoke_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_stress_all_vseq.sv
This builds on top of #25056 (which should be merged first). Once that has been merged, there are only the following three commits:
- b1d4a6e906 [pwm,dv] Use out-of-block declarations in pwm_rand_output_vseq
- cad204d17c [pwm,dv] Use out-of-block declarations in pwm_smoke_vseq
- 40e83cf8c5 [pwm,dv] Use out-of-block definitions in pwm_stress_all_vseq
and this converts all of the PWM DV code to use out-of-block declarations.
> [pwm,dv] Use out-of-block declarations in the rest of the DV code

- hw/ip/keymgr_dpe/data/keymgr_dpe.hjson
- hw/ip/keymgr_dpe/dv/env/keymgr_dpe_env_cfg.sv
- hw/ip/keymgr_dpe/dv/env/keymgr_dpe_env_pkg.sv
- hw/ip/keymgr_dpe/dv/env/keymgr_dpe_if.sv
- hw/ip/keymgr_dpe/dv/env/keymgr_dpe_scoreboard.sv
- hw/ip/keymgr_dpe/dv/tb.sv
- hw/ip/keymgr_dpe/keymgr_dpe.core
- hw/ip/keymgr_dpe/rtl/keymgr_dpe.sv
The flash seed input pulls in the flash_ctrl_pkg, which is ip-gened. Darjeeling, who is the only user of keymgr_dpe by now, does not have a flash_ctrl and so it does not use the flash seed input. To remove the dependency of flash_ctrl, remove the flash seed input from keymgr_dpe
> [hw,keymgr_dpe,rtl] Remove flash seed input as not used currently

- hw/ip/pwm/dv/env/pwm_env_pkg.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_perf_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_rand_output_vseq.sv
This builds on top of #25057 (converting things to use out-of-block declarations), which should be merged first. Once that has been merged, there are the following commits:
- 2df2c0dca9 [pwm,dv] Simplify how we override reg_param in pwm_perf_vseq
- 17c8223356 [pwm,dv] Remove empty constraint in pwm_rand_output_vseq
- 4514d379c3 [pwm,dv] Drop RsvParam from param_reg_t
- 99dcd29a64 [pwm,dv] Fix units in pwm_rand_output_vseq
> [pwm,dv] Improvements in rand_output_vseq

- hw/top_earlgrey/data/chip_testplan.hjson
- sw/device/lib/crypto/data/crypto_testplan.hjson
These tests must pass for silicon validation, so we should include them in the testplan for Earl Grey.
> [sival] Include cryptolib tests in earlgrey sival testplan

- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- rules/const.bzl
- rules/manifest.bzl
- rules/opentitan/cc.bzl
- rules/opentitan/exec_env.bzl
- rules/opentitan/toolchain.bzl
- sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/BUILD
- sw/device/silicon_creator/rom_ext/sival/BUILD
- util/design/BUILD
- util/design/gen-otp-immutable-rom-ext-json.py
- util/design/lib/BUILD
- util/design/lib/ImmutableSectionProcessor.py
- util/design/update-manifest-json.py
This commit decouples the `CREATOR_SW_CFG_MANUF_STATE` OTP field from the SKU.
Previously, the `CREATOR_SW_CFG_MANUF_STATE` field was used to identify the SKU. However, we now leverage Device ID for SKU identification, eliminating the need to use `CREATOR_SW_CFG_MANUF_STATE` for this purpose. We can now embed the first four bytes of the immutable ROM_EXT hash into the `CREATOR_SW_CFG_MANUF_STATE` field.
The following changes were made to implement this decoupling:
- The `CREATOR_SW_CFG_MANUF_STATE` field in the `otp_ctrl` data structure is now set to a fixed value, `CONST.MANUF_STATE.PERSONALIZED`.
- The `MANUF_STATE` enum in the `const.bzl` file has been updated to remove the `SIVAL` value and add a `PERSONALIZED` value.
- The `update_creator_manuf_state_data` function in the …
> [otp] decouple CREATOR_SW_CFG_MANUF_STATE from SKU

- rules/signing.bzl
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/keys/fake/BUILD
- sw/device/silicon_creator/lib/ownership/keys/fake/app_dev_spx.h
- sw/device/silicon_creator/lib/ownership/keys/fake/app_dev_spx.pem
- sw/device/silicon_creator/lib/ownership/keys/fake/app_dev_spx.pub.pem
- sw/device/silicon_creator/lib/ownership/keys/fake/app_prod_spx.h
- sw/device/silicon_creator/lib/ownership/keys/fake/app_prod_spx.pem
- sw/device/silicon_creator/lib/ownership/keys/fake/app_prod_spx.pub.pem
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block.h
- sw/device/silicon_creator/lib/ownership/test_owner.c
- sw/device/silicon_creator/lib/sigverify/spx_verify.c
- sw/device/silicon_creator/lib/sigverify/spx_verify.h
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/opentitanlib/src/ownership/misc.rs
1. Add fake SPX+ keys to the test_owner configuration.
2. Use key_ids to distinguish between plain and hybrid keys (hybrid
key_ids are the xor of the individual key_ids).
3. Detect the SPX manifest extensions and update the search key_id
accordingly.
4. Verify hybrid signatures by checking both ECDSA and SPX signatures.
Note: this PR depends on #25080.
> [rom_ext] Add SPX+ verification for owner firmware 

- .github/workflows/ci.yml
- azure-pipelines.yml
Moves both the `sw_build` and `sw_test` jobs from Azure into one `sw_build_test` job in GitHub Actions.
There's a small improvement in execution time here for a cold build. I'll check the time when the results are cached once this merges.
> [ci] Port software build job from Azure to GitHub

- .github/workflows/bitstream.yml
The job itself doesn't take much time, but it needs time to wait for license to become available.
> [ci] increase GitHub bitstream job timeout

- ci/verify-fpga-jobs.yml
Without this, Azure automatically checks out the repo at the time this job runs, not necessarily at the same commit as the previous FPGA jobs.
This can lead to a test not existing when the FPGA tests ran, but now existing when this verify job runs. The verify job then complains that you didn't run that test.
> [ci] Add checkout step to verify-fpga job

- .github/actions/prepare-env/action.yml
- .github/workflows/bitstream.yml
- .github/workflows/ci.yml
- .github/workflows/nightly.yml
It appears that Bazel cache performance suffers when using WIF. This is likely a bug in Bazel (or google-auth-library java) since both the ID token and the exchanged access token can be cached. I suppose when WIF is in use there're excessive amount of access token exchange happening which slows down all Google bucket accessese.
As a workaround, go back to use service account JSON instead of WIF.
> [ci] use service accounts instead of workload identity federation

- sw/device/tests/uart_baud_rate_test.c
Thanks to https://github.com/lowRISC/opentitan/pull/23379 we can now test high baud rates (1MBd, 1.5Mbd) so we enable this on silicon targets.
It's still disabled on the FPGA which cannot clock high enough to test these.
Thanks to @AlexJones0 for the help debugging.
> [sival] Enable high UART baud rates on silicon

- hw/ip/otp_ctrl/data/earlgrey_skus/emulation/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
The provisioning firmware contains hardcoded settings for the HWCFG1 partition, and uses data generated at manufacturing time to calculate the DEVICE_ID. As a result, most of the otp image targets and hardware partition settings in the sival SKU, are not derived from the OTP build targets.
This change removes unused tardgets to simplify the build / provisioning maintenance. pre-silicon and post-silicon simulation and emulation environments should use the emulation SKU instead.
> [sival] Remove unused OTP targets from sival SKU.

- sw/host/provisioning/cp/BUILD
- sw/host/provisioning/ft/BUILD
- sw/host/provisioning/orchestrator/src/device_id.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/tests/device_id_test.py
This contains two commits that address review feedback in #25151 and #25152. Specifically, this:
1. removes the CRC32 field from the device ID and marks it as reserved, and
2. removes `testonly` flag from CP/FT host bins.
> [provisioning] remove crc32 from device ID and testonly flags from CP/FT harnesses

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/lib/cert/dice.h
- sw/device/silicon_creator/lib/cert/dice_cwt.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.c
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/e2e/dice_chain/BUILD
- sw/device/silicon_creator/rom_ext/e2e/dice_chain/no_refresh_test.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
This cherry pick includes a bug fix to the ROM_EXT that ensures the DICE CDI_1 private is left in OTBN DMEM when the owner firmware is booted. Additionally, this adds a ROM_EXT E2E test to ensure the DICE certs are valid after an update.
> [cherry-pick] manually cherry-pick of #24980 and #25136 onto `earlgrey_1.0.0` branch

- hw/Makefile
- util/autogen_testutils.py
- util/check_dif_statuses.py
- util/dashboard/gen_dashboard_entry.py
- util/ipgen/README.md
- util/ipgen/lib.py
- util/ipgen/renderer.py
- util/make_new_dif.py
- util/make_new_dif/ip.py
- util/topgen.py
- util/topgen/c_test.py
- util/topgen/lib.py
- util/topgen/merge.py
- util/topgen/validate.py
This has 4 commits with no breakages in between:
- Add cmdgen to "all" target in hw/Makefile
- Move type hints from comments to variable declarations in util/topgen.py
- Remove support for templated ips in topgen
- Improve ipgen docs, exception handling, and make minor implifications
Some are part of #8440
> [util,topgen] Remove support for templated ips

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/epmp.c
- sw/device/silicon_creator/lib/drivers/epmp.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
Immutable rom_ext also needs the epmp lib for reconfiguration.
Since the library code is general and not specific to rom_ext, let's move it to driver lib.
This PR only rename symbols, there's no change to the functionalities.
This partially addresses #24368.
> [rom_ext] Move the rom_ext epmp lib to drivers

- sw/device/silicon_creator/imm_rom_ext/BUILD
- sw/device/silicon_creator/imm_rom_ext/imm_rom_ext.c
- sw/device/silicon_creator/imm_rom_ext/imm_rom_ext.h
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/device/silicon_creator/rom_ext/rom_ext_common.ld
- sw/device/silicon_creator/rom_ext/rom_ext_start.S
To minimize the divergence between SKUs that with and without immutable rom_ext feature enabled in ROM, we propose always linking the section to rom_ext, and call it first if it isn’t called by ROM.
With this change, the boot flows will be always (almost) the same, while the OTP flag `IMMUTABLE_ROM_EXT_EN` basically only controls whether the immutability is enforced by ROM.
SKUs without the immutability enforced enable should still link with the trunk/master imm_rom_ext section, but without the EN bit set in their OTP configuration.
This partially addresses #24368.
A placeholder is added to avoid breaking current tests, and should be replaced by a proper target after #25043 is merged.
> [rom_ext] Call immutable section first at startup

- hw/vendor/lowrisc_ibex.lock.hjson
- hw/vendor/lowrisc_ibex/doc/03_reference/images/blockdiagram.svg
- hw/vendor/lowrisc_ibex/rtl/ibex_register_file_fpga.sv
84232a5bfa8b020cd05718b2ae21d8584c942df8
* [rtl] Fix zero value in FPGA RF (Pascal Nasahl)
* Block diagram: make feature text readable (Marno van der Maas)
* Block diagram: fixes and improved looks (Marno van der Maas)
> Update lowrisc_ibex to lowRISC/ibex@84232a5b

- hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/kmac_entropy_test.c
Map `kmac_entropy_test` to `chip_sw_kmac_entropy` and include more execution targets.
> [sival,kmac] Add chip_sw_kmac_entropy test

- .github/workflows/nightly.yml
-  The branch name should be the one where the tests run.
> [SiVal] Fix branch name when publishing the  nightlies resport

- hw/ip/otp_ctrl/data/earlgrey_skus/emulation/BUILD
- hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD
- rules/const.bzl
- rules/manifest.bzl
- rules/opentitan/cc.bzl
- rules/opentitan/exec_env.bzl
- rules/opentitan/toolchain.bzl
- sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/BUILD
- sw/device/silicon_creator/rom_ext/sival/BUILD
- util/design/BUILD
- util/design/gen-otp-immutable-rom-ext-json.py
- util/design/lib/BUILD
- util/design/lib/ImmutableSectionProcessor.py
- util/design/update-manifest-json.py
This cherry-picks several commits to `earlgrey_1.0.0` that prevent the personalization firmware from executing again once a device has been successfully personalized.
> [cherry-pick] manual cherry-pick of #24948, #25087, and #25106 to `earlgrey_1.0.0`

- hw/ip/rom_ctrl/dv/env/rom_ctrl_env_cfg.sv
- hw/ip_templates/pwrmgr/data/pwrmgr.hjson.tpl
- hw/ip_templates/pwrmgr/data/pwrmgr.tpldesc.hjson
- hw/ip_templates/pwrmgr/dv/cov/pwrmgr_cov_bind.sv.tpl
- hw/ip_templates/pwrmgr/dv/env/pwrmgr_if.sv
- hw/ip_templates/pwrmgr/dv/env/pwrmgr_scoreboard.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_disable_rom_integrity_check_vseq.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_repeat_wakeup_reset_vseq.sv
- hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv.tpl
- hw/ip_templates/pwrmgr/dv/tb.sv.tpl
- hw/ip_templates/pwrmgr/rtl/pwrmgr.sv.tpl
- hw/ip_templates/pwrmgr/rtl/pwrmgr_cdc.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/dv/env/chip_if.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/data/pwrmgr.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/data/top_earlgrey_pwrmgr.ipconfig.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/cov/pwrmgr_cov_bind.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/pwrmgr_if.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/pwrmgr_scoreboard.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_disable_rom_integrity_check_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_repeat_wakeup_reset_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_cdc.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_reg_pkg.sv
- util/topgen.py
Darjeeling has 2 rom_ctrls. Template the rom_ctrl input to support more than 1 rom_ctrl input.
This pulls over work from the integrated_dev branch.
> [hw,pwrmgr,rtl] Support more than 1 rom_ctrl input

- sw/device/tests/keymgr_derive_cdi_test.c
- sw/device/tests/keymgr_key_derivation_test.c
This PR is composed of two commits fixing two bugs in the keymgr derivation tests:
1. Fix [chip_sw_keymgr_key_derivation](https://github.com/lowRISC/opentitan/commit/fdda4294ec6a7084880d613128d0edb258b0dee7): `chip_sw_keymgr_key_derivation_vseq` provides backdoor support required in the `chip_sw_keymgr_key_derivation` software test. However, the test would trigger an assertion failure when run in DV. The cause of this is a missing space character in the log message that is used as a checkpoint in the sequence.
2. Fix [chip_sw_keymgr_derive_{sealing,attestation}](https://github.com/lowRISC/opentitan/commit/b93e9d1d354605f4bf3b635c5436bf5e51b41afc): The `chip_sw_keymgr_derive_{sealing,attestation}` test would fail on FPGAs with masking disabled due to faulty logic that checks whether …
> [sival, keymgr] Fix failing key manager sival tests

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/aes_force_prng_reseed_test.c
- sw/device/tests/aes_prng_reseed_test.c
[sival/aes] Add aes_prng_reseed,aes_prng_force_reseed
This commit introduces the AES PRNG reseed test (chip_sw_aes_prng_reseed)
and (chip_sw_aes_force_prng_reseed) and AES FORCE PRNG reseed, to handle the
reseed process by disabling entrpy complex and triggering PRNG reseed
accordingly to test the actual behavior of the AES module's PRNG reseeding in
ECB mode.
- Updated the test plan descriptions in `chip_aes_testplan.hjson` to match
the implemented tests. Added missing test feature.
- Resoloved latest code suggestions provided in PR #24574 and updated
code with suggestions from other thread (using TRY and remove .c suffix
in bazel tag).
- Single commit for a cleaner history.
- Resolve multiple commits.
See: hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
Closes Issue #24857
Closes Issue …
> [sival/aes]  Introduce aes_force_prng_reseed_test and aes_prng_reseed_test 

- hw/top_earlgrey/data/chip_testplan.hjson
This testplan was missing from `top_earlgrey`'s imports.
> [sival] Add ibex testplan to top_earlgrey plan

- hw/ip/pwm/dv/cov/cover.ccf
- hw/ip/pwm/dv/cov/toggle.exclude
- hw/ip/pwm/dv/pwm_sim_cfg.hjson
Honestly, this isn't really a pwm-specific change so we'll probably want to move it eventually. Before this change, he reported toggle coverage misses bits 56:43 of data_i in tb.dut.u_reg.u_chk.u_chk. This instance is made with:
prim_secded_inv_64_57_dec u_chk (
.data_i({tl_i.a_user.cmd_intg, H2DCmdMaxWidth'(cmd)}),
.data_o(),
.syndrome_o(),
.err_o(err)
);
where cmd is 43 bits wide and H2DCmdMaxWidth is 57. As such, bits 56:43 are constant.
> [pwm,dv] Exclude impossible toggle coverage in u_reg.u_chk

- sw/device/silicon_creator/rom_ext/rom_ext.c
An extra `dbg_print_epmp` call got added to the ROM_EXT.  Remove it.
> [rom_ext] Eliminate extra debug print

- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block_unittest.cc
- sw/host/tests/ownership/flash_permission_test.rs
The INFO page layout has changed between the ES and PROD chips.  Update the lockdown and ownership functions relating to INFO configuration. Update the `flash_permission_test` to verify the configuration.
> [rom_ext] Update INFO page lockdown for `earlgrey_a1`

- hw/top_earlgrey/BUILD
- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/cbor.h
- sw/device/silicon_creator/lib/cert/dice_cwt.c
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/device/silicon_creator/rom/e2e/address_translation/BUILD
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/defs.bzl
- sw/device/silicon_creator/rom_ext/e2e/dice_chain/BUILD
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/device/silicon_creator/rom_ext/sival/BUILD
- sw/host/provisioning/ft_lib/src/lib.rs
This updates the ROM_EXT build configuration to build multiple ROM_EXTs that support each DICE cert format: X.509 and CWT. Additionally, this updates the `dice_cwt` lib to implement the `dice_cert_check_valid()` function for checking if a DICE CWT is valid or not.
> [rom_ext,dice] build ROM_EXT with DICE CWT cert format support

- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/ast.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
The original implementation was intended to be used during early silicon integration. Since then, the provisioning infrastructure and info flash memory map has changed and this funcitonality is no longer compatible.
> [rom_ext] Remove AST patch functionality.

- rules/opentitan/cc.bzl
- rules/opentitan/exec_env.bzl
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/device/silicon_creator/manuf/base/signatures/BUILD
1. Set up offline signing rules for perso binaries.
2. Feed the correct binaries to the test flows based on the SKU.
> [perso] Set up signing and testing 

- hw/ip/hmac/README.md
- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/doc/registers.md
- hw/ip/hmac/doc/theory_of_operation.md
- The HMAC supports arbitrary key lengths. Add precision on how to use it.
> [hmac,doc] Update for arbitrary key length

- sw/device/tests/penetrationtests/firmware/sca/BUILD
- sw/device/tests/penetrationtests/firmware/sca/otbn_sca.c
- sw/device/tests/penetrationtests/firmware/sca/otbn_sca.h
- sw/device/tests/penetrationtests/json/otbn_sca_commands.h
This commit adds the otbn.sca.rsa512_decrypt penetration test. The user needs to provide the mod, exp, and message which then gets decrypted using the rsa OTBN app. The result is transmitted back to the host. SCA measurements can be conducted during the trigger window.
> [pentest] Add RSA512 decryption SCA test

- hw/top_earlgrey/data/chip_testplan.hjson
OTBN tests are required for Earl Grey's silicon validation, so they should be imported by Earl Grey's testplan.
> [sival] Import OTBN testplan for Earl Grey

- hw/top_darjeeling/lint/padring.waiver
This file was missing. Together with that and the FUSESOC_IGNORE move you can lint Darjeeling.
> [darjeeling] Add missing padring.waiver

- third_party/openocd/calloc_transpose.patch
- third_party/openocd/repos.bzl
We configure GCC to treat all warnings as errors and newer versions warn when calloc args are tranposed. This adds a patch that fixes the issue.
> [openocd] fix openocd build on new versions of GCC

- sw/device/silicon_creator/rom_ext/rom_ext.c
Initialize ownership at the UDS stage so that the ownership seal is bound to the hardware rather than any mutable code.
> [rom_ext] Initialize ownership in UDS

- .github/workflows/ci.yml
It is missing the service account json secret input.
> [ci] fix verilated earlgrey job on push

- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/host/tests/ownership/flash_permission_test.rs
- sw/host/tests/ownership/transfer_lib.rs
1. Fix incorrect INFO page `cfg` and `cfg_wen` register calculations.
2. Add an INFO page to the various `with-flash` configurations in the ownership transfer tests.
> [ownership] Compute correct flash INFO page addresses

- ci/fpga-job.yml
- ci/verify-fpga-jobs.yml
Note: Do not merge this change directly into the `master` or any branches with active hardware or ROM development.
This change disables ROM e2e cases from CI as the branch does not support RTL or ROM changes.
Coverage for software under //sw/device/silicon_created/... is achieved by:
- unittests
- functests
- rom_ext e2e
> [ci] Remove ROM e2e test cases from earlgrey_1.0.0

- hw/top_earlgrey/data/chip_testplan.hjson
This test checks various muxing configurations, plus one attribute (invert), which fulfils most of the testpoints here. More attributes can be added later if necessary.
> [sival] Assign `gpio_pinmux_test` to two points

- sw/device/tests/uart_baud_rate_test.c
The FPGA cannot clock high enough for 1MBd or 1.5MBd, but silicon can.
This change enables a wider range of baud rates and changes how the 1MBd and 1.5MBd are restricted to be better for multitop.
Backport of #23605
> [test] Improve reliability of UART baud rate test

- sw/device/tests/BUILD
These previously only had CW340 environments, but they work fine on the CW310 as well. This allows us to run them easier in our nightlies.
> [sival] Enable CW310 exec env on rv_dm tests

- sw/device/silicon_creator/rom/e2e/defs.bzl
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/host/provisioning/ft_lib/src/lib.rs
- sw/host/tests/ownership/transfer_test.rs
1. Change the startup banner to just "ROM_EXT:<version>".
2. Prefix all ROM_EXT messages with a subject (e.g. error, info, verify, etc).
3. Eliminate the ePMP printout.
4. Update tests.
> [rom_ext] Clean up ROM_EXT prints

- hw/BUILD
- hw/bitstream/vivado/BUILD
- hw/top/BUILD
- hw/top/defs.bzl
- hw/top_darjeeling/ip/ast/BUILD
- hw/top_darjeeling/ip/ast/data/BUILD
- hw/top_darjeeling/ip/sensor_ctrl/BUILD
- hw/top_darjeeling/ip/sensor_ctrl/data/BUILD
- hw/top_darjeeling/ip_autogen/clkmgr/BUILD
- hw/top_darjeeling/ip_autogen/pinmux/BUILD
- hw/top_darjeeling/ip_autogen/pwrmgr/BUILD
- hw/top_darjeeling/ip_autogen/rstmgr/BUILD
- hw/top_darjeeling/sw/autogen/top_darjeeling.c
- hw/top_darjeeling/sw/autogen/top_darjeeling.h
- hw/top_earlgrey/sw/cw310/BUILD
- sw/device/lib/dif/autogen/BUILD
- sw/device/lib/testing/BUILD
- sw/device/lib/testing/autogen/BUILD
- sw/device/lib/testing/rand_testutils.c
- sw/device/silicon_creator/lib/cert/BUILD
Test to see how much is broken after force rebasing on master with darjeeling
> [multitop_dev] Test PR

- hw/dv/sv/i2c_agent/i2c_monitor.sv
The default type (bit) causes VCS to emit a warning about the fact we call the function without looking at the return value. Tell VCS that there isn't one!
> [i2c,dv] Add missing "void" type to a function in i2c_monitor

- hw/top_darjeeling/templates/toplevel.sv.tpl
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/templates/toplevel.sv.tpl
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- util/topgen/lib.py
- util/topgen/merge.py
- util/topgen/resets.py
- util/topgen/validate.py
Tops may specify resets that are completely managed externally, i.e., with a dedicated reset manager in the uncore environment of an integrated OpenTitan. Feeding that reset to the internal reset manager is not necessary and just adds complexity in the configuration.
To address this, this PR introduces support for unmanaged external resets, allowing them to operate independently from the internal reset manager. To define an unmanaged reset, simply add an entry to the top-level unmanaged_resets list. Once defined, these resets can be used like any other reset for IP instantiation and crossbar mapping.
Additionally, when routing IP alerts to the alert manager, the alert manager requires a reset status signal to know if the reset for the alert’s IP is currently active. For unmanaged external …
> [topgen] Support for unmanaged external resets

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/asn1.c
- sw/device/silicon_creator/lib/cert/asn1.h
- sw/device/silicon_creator/lib/cert/asn1_unittest.cc
- sw/host/ot_certs/src/asn1/codegen.rs
Our ROM_EXT is close to the limit,
and future changes (e.g. immutable rom_ext) will likely introduce 10~20k more bytes.
This refactor moves the error propagation to the end of asn1 builder (`asn1_finish`), reducing a huge amount of branches to save firmware size.
This patch reduced
* 1864 bytes from the ROM_EXT. (46180 to 44316)
* 3040 bytes from FT_perso. (92164 to 89124)
This PR partially address #24558.
---
More specifically, we added an internal error tracking variable `state->error`. When any operation results in error. The variable will be set, and all future operations will be no-op. This patch comes with the cost that we will execute many no-ops before the error is propagated. However, since the device shouldn’t trigger any of these errors during normal conditions, this cost seems …
> [dice,x509] Reduce X509 template library code size

- sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
The latest rev of the HyperTeacup board (v1.5.0) connects the active-low shutdown pin of the LED driver to HyperDebug pin CN10.15. The board pulls this pin low by default, so the HyperDebug needs to actively drive it high to enable the LED driver.
This commit updates opentitanlib's HyperTeacup configuration to drive this pin high by default, ensuring that the driver is always active.
CN10.15 is not connected on HyperTeacup rev 1.3.0, so this change should be backwards compatible with older boards.
Signed-off-by: Noah Moroze <noah@opentitan.org>
(cherry picked from commit cb5bf502a94ef3a7969aa6b43dfbfee92d377854)
> Backport 24794 to earlgrey_es_sival

- sw/device/silicon_creator/lib/BUILD
- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/lib/sigverify/sphincsplus/test/BUILD
- sw/device/tests/BUILD
- sw/device/tests/autogen/BUILD
- third_party/riscv-compliance/defs.bzl
- util/topgen/templates/BUILD.tpl
This PR addresses some discrepancies between the Bazel build targets and the results that are being collected by our nightly runs. Several tests are marked as being broken in the SiVal ROM EXT execution environment, but have been passing consistently over 30+ nightly runs - this suggests the underlying issue may be resolved without marking the test as no longer being broken.
See the commit messages for more details. Every test re-enabled has been verified to pass for 5 iterations in a row on a local FPGA.
> [sival] Re-enable broken SiVal ROM EXT tests that pass consistently

- hw/dv/dpi/common/tcp_server/tcp_server.c
This is pull over from https://github.com/lowRISC/opentitan/pull/23889 to `master`:
Two small patches to the tcp_server code, used by other transactors such as jtagdpi and dmidpi. These improve the usability of the transactors in a shared, remote environment such as an emulator.
Without this change, an interrupted select() call is treated as a connection error and the client is dropped. This makes connections very unstable.
> [dv/dpi] tcpserver single connection and retry select on EINTR

- sw/device/tests/pmod/BUILD
Adds a SiVal ROM EXT environment local to the PMOD tests that overrides the `hyper310` bitstream and interface to use the `cw310` versions, so that the relevant pins required for PMOD are accessible during the test, and the test can be run in a ROM EXT environment with the local SiVal changes (e.g. OTP changes). This should work with the existing nightly runner as it uses the same `fpga_cw310_sival_rom_ext` tag, despite being a private exec env.
> [sival,bazel] Add SiVal ROM EXT exec env without hyper310 for use in PMOD tests

- hw/dv/sv/tl_agent/tl_agent_cov.sv
The cp_mask field expects to see a value of '1 (i.e. all byte lanes are enabled). Bizarrely, a full-width read doesn't match the coverpoint bin for some reason, yielding a hole in the cross at the bottom of the covergroup.
Calculate the "replicated ones" explicitly, which seems to solve the problem.
> [tl,dv] Avoid silly hole in tl_a_chan_cov_cg

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
- hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
This is a manual backport of https://github.com/lowRISC/opentitan/pull/24735
> Backport 24735 to earlgrey 1.0.0

- hw/top_earlgrey/data/ip/chip_rv_dm_testplan.hjson
This Bazel test is parametrised by its LC state, not the RV_DM states like other tests (e.g. `rv_dm_mem_`).
> [sival] Fix rv_dm_jtag bazel entries

- sw/host/provisioning/orchestrator/README.md
- sw/host/provisioning/orchestrator/configs/skus/sival.hjson
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/tests/device_id_test.py
The RMA token is autogenerated by the FT test harness; it is a random number. Additionally, this removes inputs to CP flow required from the refactor in #25388.
> [provisioning] remove RMA token from orchestrator inputs

- util/reggen/uvm_reg_base.sv.tpl
The ral_pkg files are all auto-generated and depending on the name and exact instantiation of shadow registers (potentially `hwext`), may contain pretty long path names. To avoid veriblelint flagging warnings about this (it feels silly as the files are auto-generated anyway), this commit adds a suitable inline waiver specifically for shadow registers paths.
> [regtool] Add inline veriblelint waivers for line-length rule in ral_pkg

- hw/dv/dpi/jtagdpi/jtagdpi.c
- hw/dv/dpi/jtagdpi/jtagdpi.h
- hw/dv/dpi/jtagdpi/jtagdpi.sv
See the commit log messages, but the functionality is (1) override the `LISTEN_PORT` parameter and (2) assert `srst_n` from start of sim.
> [dv/dpi] jtagdpi supports 2 new plusargs

- hw/ip/sram_ctrl/data/sram_ctrl_testplan.hjson
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_throughput_vseq.sv
- hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
When the readback feature is enabled, reads and writes take longer. This commit adapts the cycle prediction to account for that delay.
Closes lowRISC/opentitan#23321
> [sram_ctrl,dv] Adapt throughput tests for readback feature

- hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
This commit adds the `chip_sw_keymgr_derive_{sealing, attestation}` tests to the keymgr testplan.
> [sival, keymgr] Align testplan with the new tests

- hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv
This was "tightened up" in commit b1095ff, which actually broke things! The problem is that I was imagining the "continue" would continue in the surrounding "forever" loop. But it doesn't! It just skips an iteration of the "repeat" loop inside.
Make the logic a bit more explicit and correctly handle the case where we go into reset with the clock paused.
(@KinzaQamar: Thanks for finding and diagnosing this bug)
> [alert,dv] Fix logic in alert_receiver_driver

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/templates/chiplevel.sv.tpl
Some tooling changes on the generated files are not yet reflected such as external alerts on so on. Re-generate it as a separate PR to avoid having that diff on a new feature PR.
> [darjeeling] Regenerate Darjeeling after tooling changes

- hw/ip/prim/fpv/tb/prim_fifo_sync_bind_fpv.sv
- hw/ip/prim/fpv/tb/prim_fifo_sync_tb.sv
- hw/ip/prim/fpv/vip/prim_fifo_sync_assert_fpv.sv
- hw/ip/prim/rtl/prim_fifo_sync.sv
This output doesn't really do anything in the FPV world (because it detects error injection which we don't model), but wiring it up in a trivial way avoids a warning in Jasper.
To avoid merge conflicts, this PR builds on #25464, which contains the first two commits. The only commit that is unique to this PR is the last commit.
> [prim_fifo_sync,fpv] Add checks for the full_o output

- hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv
When debugging my error and fixing it in #25272, I tidied the code up a bit, using out-of-block definitions and documenting how things worked a little more carefully. This builds on that PR (which contains the first commit) and shouldn't change behaviour, but should make the code a bit easier to reason about.
> [alert,dv] Tidyups in the alert receiver driver

- hw/ip/rv_core_ibex/data/rv_core_ibex.hjson
- hw/ip/rv_core_ibex/doc/interfaces.md
- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/ip/rv_core_ibex/rtl/rv_core_ibex_pkg.sv
- hw/ip/rv_core_ibex/rv_core_ibex.core
- hw/ip_templates/pwrmgr/data/pwrmgr.hjson.tpl
- hw/ip_templates/pwrmgr/dv/env/pwrmgr_if.sv
- hw/ip_templates/pwrmgr/pwrmgr.core.tpl
- hw/ip_templates/pwrmgr/rtl/pwrmgr.sv.tpl
- hw/ip_templates/pwrmgr/rtl/pwrmgr_pkg.sv.tpl
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/ip_autogen/pwrmgr/data/pwrmgr.hjson
- hw/top_darjeeling/ip_autogen/pwrmgr/doc/interfaces.md
- hw/top_darjeeling/ip_autogen/pwrmgr/dv/env/pwrmgr_if.sv
- hw/top_darjeeling/ip_autogen/pwrmgr/pwrmgr.core
- hw/top_darjeeling/ip_autogen/pwrmgr/rtl/pwrmgr.sv
- hw/top_darjeeling/ip_autogen/pwrmgr/rtl/pwrmgr_pkg.sv
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/data/pwrmgr.hjson
- hw/top_earlgrey/ip_autogen/pwrmgr/doc/interfaces.md
- hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/pwrmgr_if.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/pwrmgr.core
- hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr.sv
- hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_pkg.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
Some IPs depend on the power manager package to define their IO interfaces, for example the rv_core_ibex or flash control. However, some tops do not have a power manager, and therefore also not the ipgen'ed power manager package. This causes a dependency error.
To solve that problem, we put out common type definitions to a common `pwrmgr_common_pkg`, which is not part of ipgen. Thus, also tops that don't have a pwrmgr, can reference these definitions.
> [hw,pwrmgr_common_pkg,rtl] Move common interface definitions out of ipgen

- util/topgen/templates/toplevel_pkg.sv.tpl
Previously, the number of alert modules was used to determine the number of outgoing alerts. That's wrong. If a device has more than one alert, the number of alert modules and the actual number of alerts diverge.
This PR fixes that and uses the correct number.
> [topgen] Use the number of alerts and not alert modules

- .github/workflows/nightly.yml
- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/cryptotest.bzl
- sw/device/tests/crypto/cryptotest/firmware/BUILD
This PR adds the `fpga_cw310_sival_rom_ext` execution environment to the cryptotests.
This will cause the nightly CI runs to pick up these tests; however, because some of these tests are very slow (i.e. > 30 min), this PR also adds a `skip_in_nightly_ci` bazel tag that allows excluding certain tests.
Currently, only three of the KAT tests repeatably run in under 5 minutes (HMAC-SHA256 is a bit close), so the rest of the tests are being excluded at the moment.
```console
//sw/device/tests/crypto/cryptotest:cshake_kat_fpga_cw310_sival_rom_ext (cached) PASSED in 21.6s
//sw/device/tests/crypto/cryptotest:kmac_kat_fpga_cw310_sival_rom_ext (cached) PASSED in 146.3s
//sw/device/tests/crypto/cryptotest:ecdh_kat_fpga_cw310_sival_rom_ext    PASSED in 248.5s …
```
> [sival] Enable `fpga_cw310_sival_rom_ext` exec env on cryptotests

- sw/host/provisioning/orchestrator/src/db.py
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
This PR fixes some small issues in orchestrator.py, and adds a `--cp-only` flag for convenience.
> [manuf] orchestrator.py tweaks

- sw/host/opentitanlib/src/console/spi.rs
SPI flash mode on hyperdebug defaults to 3 byte mode, and if we try to init to 3b mode if we are not in 4b mode the transaction hangs. This is a temporary fix until this can be root caused.
> [opentitanlib] remove 3b mode init of SPI console

- sw/device/tests/BUILD
This commit adds the CW310 and CW340 SiVal execution environments to the kmac_app_rom_test.
> [kmac, sival] Add sival exec environment to kmac_app_rom_test

- third_party/rust/patches/rules_rust.extra_rustc_toolchain_dirs.patch
- third_party/rust/repos.bzl
From the original commit:
Add build setting to enable specifying other tool locations
On some systems, the CC toolchain discovered by bazel uses a different path for the linker than where the linker (that is specified by the `-fuse-ld=` flag) actually lives on the system.
The issue stems from rules_rust deciding to pass `-fuse-ld=lld` a link arg, rather than just using what was detected by the CC toolchain. This results in the linker not being found, as reported by
https://github.com/lowRISC/opentitan/issues/12448
This is a workaround that enables telling rules_rust where other linker directories might be on your system. It is used by passing `--@rules_rust//:extra_rustc_toolchain_dirs=/path/to/somewhere/else` to `bazel ...` invocations.
> [bazel] Add `rules_rust` `extra_rustc_toolchain_dirs` patch

- sw/host/opentitanlib/src/app/spi.rs
- sw/host/opentitanlib/src/io/spi.rs
- sw/host/opentitanlib/src/io/uart.rs
- sw/host/opentitanlib/src/proxy/handler.rs
- sw/host/opentitanlib/src/proxy/protocol.rs
- sw/host/opentitanlib/src/transport/common/uart.rs
- sw/host/opentitanlib/src/transport/dediprog/spi.rs
- sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
- sw/host/opentitanlib/src/transport/hyperdebug/uart.rs
- sw/host/opentitanlib/src/transport/proxy/spi.rs
- sw/host/opentitanlib/src/transport/proxy/uart.rs
- sw/host/opentitantool/BUILD
- sw/host/opentitantool/src/command/mod.rs
- sw/host/opentitantool/src/command/spi.rs
- sw/host/opentitantool/src/command/uart.rs
- sw/host/opentitantool/src/main.rs
Add two new commands to `opentitantool`: `spi flashrom-arg` and `uart os-device`, which can be used for heling external programs access HyperDebug (or some other backend devices) without going through `opentitanlib`, while still using the `usb-serial` and port aliases from our configuration files to identify the debugger and port.
```
$ opentitantool --conf ... --usb-serial 2042355F3236 spi --bus=BOOTSTRAP flashrom-args
{
programmer: "raiden_debug_spi:serial=2042355F3236,target=2"
}
$ opentitantool --conf ... --usb-serial 2042355F3236 uart --uart=EC os-device
{
path: "/dev/ttyUSB6"
}
```
> [opentitantool] Convenience for external programs

- hw/Makefile
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
Because the Darjeeling target would modify some auto-generated tests, that are not yet in multitop-sw, the Makefile target must be placeed before Earlgrey, which writes back the correct tests
> [top] Enable Darjeeling in the hw Makefile

- hw/top_earlgrey/BUILD
- rules/signing.bzl
- signing/BUILD
Implement signing of owner-stage payloads with owner keys.  By default, we select key zero in the owner's keyset.  The default owner's keyset is the SiVAL owner's keyset.  Both the owner
keyset and the selected key can be chosen with commandline parameters:
```
bazel build //sw/device/tests:aes_smoketest_silicon_owner_sival_rom_ext \
--//signing:token=//signing/tokens:<owner_token> \
--//signing:appkey=//sw/device/silicon_creator/rom_ext/sival/keys:keyset \
--//sw/device/silicon_creator/rom_ext/sival/keys:keyset=sv00-app-key-prod-0
```
> [signing] Implement owner-stage signing

- sw/device/silicon_creator/manuf/base/BUILD
Commit fd9ba9d261e23647cca2285248014526dab8f4b1 dropped some test coverage, since the conditional unintentionally removes the default test tags if it evaluates to False.
This commit fixes the issue and should fix the "Verify FPGA jobs" CI workflow.
> [manuf] Fix missing test tags for FT FPGA tests

- sw/host/provisioning/orchestrator/src/device_id.py
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
This PR tweaks the DIN handling in the device ID to create a `None` default and makes the CP confirmation message clearer. I also tossed in a few other small fixes/cleanups while I was in there. 
@timothytrippel LMK if this looks like what you had in mind!
> [manuf] Clean up device ID confirmation message

- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/firmware/ecdh.c
- sw/device/tests/crypto/cryptotest/firmware/ecdsa.c
These were initially excluded because we didn't support P-384 in cryptolib yet, but now that P-384 support is present we should test it. Note that there were some tests with SHA-256 in the original test suite that was commented out, but I removed them: since cryptolib doesn't let you use a hash function with collision resistance weaker than the curve security level these will always fail.
Verified locally that the ECDH and ECDSA targets pass on FPGA.
Follow-up after noticing it was missing while making some changes, see https://github.com/lowRISC/opentitan/pull/25391
> [cryptotest] Add P-384 targets to cryptotest.

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_jtag_inject_vseq.sv
These lines are assertions to check that two different enumerations match. But VCS (at least) warns about the comparison, presumably because comparing different enum types is usually a mistake.
Explicitly cast one side to bits on each side to tell the tool that we're doing it on purpose!
> [chip,dv] Make a cast explicit in chip_sw_rom_e2e_jtag_inject_vseq

- .github/workflows/nightly.yml
- sw/device/tests/BUILD
- sw/host/opentitanlib/src/app/config/hyperdebug_cw340.json
This PR move the tpm test to run on the CW340 and create a job to run all the SiVal cw340 tests.
> [SiVal] Enable spi_host_tpm test for SiVal  nightly

- hw/ip/prim/rtl/prim_reg_cdc.sv
This is trying to remove a coverage item that was a hole for some blocks that I was (wrongly) trying to waive with #25088. I hope this solution will be cleaner.
If DstWrReq is false then the src_update signal cannot be true. This is because it is driven by the src_update_o port on a prim_reg_cdc_arb instance. If DstWrReq is false then the instance wires src_update_o to zero (in the gen_passthru generate block).
This rewrite will behave equivalently in the same way as before but will no longer generate any conditional coverage terms that depend on src_update if DstWrReq is false.
> [prim,rtl] Rephrase a term in prim_reg_cdc.sv

- .github/workflows/nightly.yml
- sw/device/tests/BUILD
- sw/host/opentitanlib/src/app/config/hyperdebug_cw340.json
This is a manual cherry pick of https://github.com/lowRISC/opentitan/pull/25520
> Backport 25520 to earlgrey 1.0.0

- hw/ip/hmac/rtl/hmac.sv
- hw/ip/hmac/rtl/hmac_core.sv
This PR contains two commits that
1. resolve two Verilator `WIDTH` warnings.
2. remove an obsolete TODO.
> [hmac, rtl] Resolve lint warnings and TODOs for the V3 signoff

- sw/host/opentitanlib/src/app/i2c.rs
- sw/host/opentitanlib/src/app/mod.rs
- sw/host/opentitanlib/src/app/spi.rs
- sw/host/opentitanlib/src/io/i2c.rs
- sw/host/opentitanlib/src/io/spi.rs
- sw/host/opentitanlib/src/proxy/handler.rs
- sw/host/opentitanlib/src/proxy/protocol.rs
- sw/host/opentitanlib/src/tpm/driver.rs
- sw/host/opentitanlib/src/transport/chip_whisperer/spi.rs
- sw/host/opentitanlib/src/transport/dediprog/spi.rs
- sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
- sw/host/opentitanlib/src/transport/proxy/i2c.rs
- sw/host/opentitanlib/src/transport/proxy/spi.rs
- sw/host/opentitanlib/src/transport/ti50emulator/i2c.rs
- sw/host/opentitanlib/src/transport/ti50emulator/spi.rs
- sw/host/opentitanlib/src/transport/ultradebug/spi.rs
- sw/host/opentitantool/src/command/i2c.rs
- sw/host/opentitantool/src/command/spi.rs
- sw/host/tests/chip/spi_device/src/spi_device_tpm_test.rs
- sw/host/tpm2_test_server/src/main.rs
Adapt TPM driver layer to use advanced transport features, if available.  These features allows asking the backend transport to perform a full TPM register read or write in a single USB roundtrip, including e.g. polling the SPI bus to know when the device is ready for the data transfer.
This change speeds up TPM communication between 2x and 4x when HyperDebug is used to communicate with GSC chips.
> [opentitantool] Advanced TPM primitives in transport

- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
- hw/top_earlgrey/templates/chiplevel.sv.tpl
As the `SecureIbex` configuration is the one we use for the Earl Grey ASIC, we also should enable it for the FPGA boards.
Due to resource constraints, this is only possible for the CW340 but not the CW310.
**Report for CW340 with SecureIbex enabled:**
Resource utilization stays still well below 70%:
And timing is met:
**Report for CW340 with SecureIbex disabled:**
Closes lowRISC/opentitan#25137
> [rv_core_ibex, top_earlgrey] Enable SecureIbex for CW340

- rules/opentitan/cc.bzl
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/binaries/BUILD
1. Make exec_env_filegroup return a DefaultInfo provider so it may be consumed by other filegroup/packaging rules.
2. Remove `perso_bins` filegroup in favor of `ft_personalize_sival`.
> [bazel] Clean up `exec_env_filegroup`

- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/image/manifest_def.rs
- sw/host/opentitanlib/src/util/known_keys.rs
- sw/host/opentitanlib/src/util/mod.rs
Quality-of-life improvement: When using `opentitantool image manifest show` to display the manifest of an image, emit a comment with the name of the public key.
> [opentitantool] Add a comment to the public key

- apt-requirements.txt
- sw/host/provisioning/orchestrator/tests/BUILD
- sw/host/provisioning/orchestrator/tests/e2e.sh
- sw/host/provisioning/orchestrator/tests/transition.bzl
The orchestrator.py script is intended to be deployed and run as a zip file in an offline environment. This CI check performs and e2e test that the zip file executes correctly.
> [manuf,ci] Add an E2E test of the provisioning orchestrator

- sw/device/silicon_creator/manuf/base/ft_personalize.c
Initialize the sealing key ladder with the same constants used by the ROM_EXT.
> [perso] Initialize the sealing ladder

- hw/top_earlgrey/BUILD
- sw/device/silicon_owner/bare_metal/BUILD
Use the appropriate keys and ROM_EXT when building owner code under the cw310 and cw340 exec_envs.
> [signing] Setup owner signing for FPGA environments

- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_excl.el
There were bunch of statements in tlul_adapter_sram that needs to get excluded as the cases were non-occuring (refer rom_ctrl_cov_excl.el).
Moreover, there is a removal of an item (reqfifo_rvalid) in the design of tlul_adapter_sam.sv to cover a conditional coverage case as the item implies another item inside the conditional coverage.
> [rom_ctrl, dv] tlul_adapter_sram conditional coverage

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/device/silicon_creator/manuf/extensions/cfg.bzl
- sw/host/provisioning/orchestrator/configs/skus/emulation.hjson
- sw/host/provisioning/orchestrator/configs/skus/sival.hjson
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/src/sku_config.py
Additional config fields make it easier to specify various paths for downstream perso bins. Addionally, individualization ELF paths should be based on OTP names not SKU names.
> [orchestrator] add config fields for perso_bin and otp

- sw/device/tests/BUILD
- sw/device/tests/sram_ctrl_scrambled_access_test.c
With PR https://github.com/lowRISC/opentitan/pull/25146, now, tests that rely on the SecureIbex parameter can now be executed on CW340. This PR consists of two commits enabling the CW340 exec. environment for such tests.
> [sival] Enable CW340 exec. environment for ECC tests

- sw/device/tests/BUILD
This PR fixes spi_passthru_test on silicon.
> [sival, spi] Add missing argument for passthru test harness on silicon

- sw/device/tests/BUILD
- sw/host/tests/chip/usb/usbdev_smoketest.rs
This PR configures host harnesses for the usbdev tests that were missing this config. These changes get these tests working on A1 silicon.
> [usb, sival] Fix usbdev sival tests on silicon

- sw/device/silicon_creator/lib/sigverify/sigverify_tests/sigverify_cryptotest.c
- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/firmware/BUILD
- sw/device/tests/crypto/cryptotest/firmware/firmware.c
- sw/host/tests/crypto/aes_nist_kat/src/main.rs
- sw/host/tests/crypto/drbg_kat/src/main.rs
- sw/host/tests/crypto/ecdh_kat/src/main.rs
- sw/host/tests/crypto/ecdsa_kat/src/main.rs
- sw/host/tests/crypto/hash_kat/src/main.rs
- sw/host/tests/crypto/hmac_kat/src/main.rs
- sw/host/tests/crypto/kmac_kat/src/main.rs
- sw/host/tests/crypto/sphincsplus_kat/src/main.rs
Switch the cryptotest KAT tests to use the SPI console for increased communication performance. This leads to 5-10x speedups across the cryptotests and makes them feasible to run in CI.
Based on some local testing, re-enabling these tests in CI should add about an extra 20 minutes to the nightly CI. The remaining KAT tests each take about 500-700s each.
```console
//sw/device/tests/crypto/cryptotest:aes_kat_fpga_cw310_sival_rom_ext     PASSED in 536.2s
//sw/device/tests/crypto/cryptotest:cshake_kat_fpga_cw310_sival_rom_ext  PASSED in 3.7s
//sw/device/tests/crypto/cryptotest:drbg_kat_fpga_cw310_sival_rom_ext    PASSED in 36.6s
//sw/device/tests/crypto/cryptotest:ecdh_kat_fpga_cw310_sival_rom_ext    PASSED in 35.8s
//sw/device/tests/crypto/cryptotest:ecdsa_kat_fpga_cw310_sival_rom_ext …
```
> [cryptotest] Switch cryptotests over to the SPI console

- .github/actions/publish-bazel-test-results/action.yml
- .github/workflows/nightly.yml
- apt-requirements.txt
The GCP bucket upload behaviour is opt-in and currently only used in nightly flow.
To track FPGA being used hostname is added to the JUnit XML.
> [ci] allow publish-bazel-test-results to publish to buckets and include hostname

- third_party/hyperdebug/repos.bzl
This update includes several improvements:
* New SPI/I2C features to perform TPM operations in a single USB roundtrip.
* Vastly improve efficiency of UART data forwarded via USB.
* Fix to bit-banging, which could previously incorrectly complain about "ongoing operation", if the most recent bit-banging had ended less than one clock-tick ago.  (This clock could be arbitrarily slow.  The problem showed up when bit-banging simulated key presses with a 20ms clock, and the next operation was attempted initiated less than 20ms after the previous one had applied its last sample.)
* ADC calibration did not entirely adhere to STM32 timing requirements, resulting in occasional crash during "reinit" (transport init).
Relevant CLs:
87399ae831 board/hyperdebug: Reduce USB fragmentation in CMSIS-DAP …
> [opentitantool] Include updated firmware for HyperDebug

- hw/ip/prim/lint/prim.waiver
This came from b4919e58, the initial commit to prim.waiver in 2020. As far as I can tell, it didn't even apply to the prim_sram_arbiter.sv in the initial commit in the repository (there was only one rsp_error* signal, but this was an output port which just matched the sram_rerror input port).
> [prim,lint] Remove waiver for prim_sram_arbiter.sv

- hw/ip/prim/lint/prim_subreg.waiver
The linter would warn about an input port that wasn't used, but this input port is now passed along to prim_subreg_arb (which has been the case since 7b2a5c3690c), so the lint warning will no longer come up.
> [prim,lint] Remove waiver for prim_subreg.sv

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
This ensures that AST is initialized in FT individualize firmware.
CC: @benjbender
> [manuf] ensure AST is initialized in FT individualize

- hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
This write is always overridden by a write in the next if/else statement (and causes a hole in reported FPV statement coverage).
> [prim,rtl] Remove dead code in prim_fifo_async_sram_adapter

- bazelisk.sh
- util/prep-bazel-airgapped-build.sh
This will fix master CI.
Required for bzlmod support. Older versions do not recognise `MODULE.bazel` as the root of the repo when searching for `.bazelversion`.
> [bazel] Update bazelisk to 1.24.1

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/aes_force_prng_reseed_test.c
- sw/device/tests/aes_prng_reseed_test.c
Manually created backport PR from PR #24574 to branch earlgrey_1.0.0.
> Cherry-pick to earlgrey 1.0.0: [sival/aes] Add aes_force_prng_reseed_test and aes_prng_reseed_test

- .github/workflows/nightly.yml
- sw/device/tests/crypto/cryptotest/BUILD
- sw/device/tests/crypto/cryptotest/cryptotest.bzl
This is a manual backport of https://github.com/lowRISC/opentitan/pull/25556
> Backport 25556 to earlgrey 1.0.0

- hw/ip/hmac/data/hmac_testplan.hjson
- hw/ip/hmac/dv/env/hmac_env.core
- hw/ip/hmac/dv/env/seq_lib/hmac_stress_reset_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_vseq_list.sv
- hw/ip/hmac/dv/hmac_sim_cfg.hjson
- New sequence to try to cover all the FSM transitions with random resets along with long message test.
> [hmac,dv] Add new test to cover FSM transitions

- hw/ip/prim/lint/prim_fifo.waiver
- hw/ip/prim/rtl/prim_fifo_async.sv
The first can never match (because the subtraction was changed from -3 to -2 in 7cbebc2e690 in June 2021).
The second *has* never matched: I think the variable in question has been called unused_decval_msb since the initial commit in the repository.
I think the third matched some width arithmetic that was done on pointer values until commit 64272d832be replaced the inline logic with a prim_fifo_sync_cnt instance. (The waiver came from an initial bunch of waivers in 2020 and the comment doesn't make sense: it looks like it was accidentally copied from the previous waiver)
> [prim,lint] Remove dead waivers for prim_fifo_*sync.sv

- hw/top_earlgrey/dv/env/seq_lib/chip_common_vseq.sv
Incorrect inclusion of "+" at the start of the plusarg name string in a `$value$plusargs` call.
> [chip,dv] Fix $plusarg string

- hw/ip/pwm/rtl/pwm_chan.sv
- hw/ip/pwm/rtl/pwm_core.sv
This PR addresses a number of issues found within the PWM RTL as part of the D3 review process. Since the changes have ended up becoming pretty extensive, the PR is structured as a number of commits. Each of these, except perhaps the final one, should be easy to understand in isolation since it is either (i) small and self-contained or (ii) not a functional change.
Since the last involves significant changes to the blink mode and particularly heartbeat logic it is more involved.
Please see the commit messages for a breakdown of what each commit does.
Issues with the current PWM implementation:
- phase counter configuration is accepted immediately; software could probably tolerate either immediate or deferred acceptance, but this PR changes the RTL to match the specification/documentation, …
> [pwm] RTL modifications for specification compliance and predictable behavior

- hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
With the introduction of the SRAM readback mode (c.f., lowRISC/opentitan#23212) memory requests can be delayed. The SRAM DV tests are adapted such that the readback feature can be disabled or enabled anytime during a test.
The sram_ctrl_passthru_mem_tl_intg_err failed occasionally because the integrity alert was expected to arrive without any delay. This commit increases the max_delay parameter for the expected alert to take the readback mode delay as well as a potential enabling or disabling of the feature into account.
> [sram_ctrl,dv] Increase fatal_error timeout

- hw/ip/rom_ctrl/dv/cov/cover_reg_top.cfg
tlul_adapter_sram contains fifos (prim_fifo_sync) and we are'nt required to collect assertion coverage. This will reduce the percentage of assert coverage being uncovered for the adapter.
> [rom_ctrl, dv] Removed the option of assert coverage collection

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_common_vseq.sv
This code was added by cc0abbfe3e3 and I think it was assuming that we only ever run this after reset (when the FIFO will be empty). It turns out that this isn't quite true and there is a window where we can write rubbish to the FIFO when it isn't empty, causing a sporadic failure in rom_ctrl_stress_all_with_rand_reset.
> [rom_ctrl,dv] Fix how we splat fifo contents in common vseq

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_readback_err_vseq.sv
When injecting a fault into write transaction 0, we previously were writing 0 to memory. However, as the memory seems to be initialized with 0, the readback returned the init value 0. Hence, the readback check was not failing as expected.
> [sram_ctrl,dv] Fix readback_err test for write iteration 0

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_mubi_enc_err_vseq.sv
Occasionally, some TLUL integrity checks fired for the sram_ctrl_mubi_enc_err. This is expected as this test is a fault injection error test. Disable the according check to let the test pass.
> [sram_ctrl,dv] Disable intg. checks for FI test

- bazelisk.sh
- util/container/Dockerfile
This container pre-downloads Bazelisk for some reason, and the version does not match what we're downloading in `bazelisk.sh`.
This old version is broken. Updating will fix the website build.
> [ci] Update Bazelisk version in dev container to v1.24.1

- hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/aes_stall_test.c
This commit introduces the AES stall test (chip_sw_stall_test) to
verify the stall bit getting asserted when scenario of back pressure
is created.
- Intial Checkin: sw/device/tests/aes_stall_test.c
- Updated File: sw/device/tests/BUILD
- Updated File: hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
- Implemented changes as per review comments from engdoreis and nasahlpa
- Re-opening accidently closed PR#25082 did not work
- Attempt to create new PR
> [sival/aes] Introduce AES Stall Status Bit test

- sw/device/info_sections.ld
- sw/device/lib/runtime/log.h
- sw/device/lib/testing/test_framework/ottf_common.ld
- sw/device/silicon_creator/lib/base/static_critical_boot_measurements.c
- sw/device/silicon_creator/lib/base/static_critical_epmp_state.c
- sw/device/silicon_creator/lib/base/static_critical_sec_mmio.c
- sw/device/silicon_creator/lib/manifest_def.c
- sw/device/silicon_creator/manuf/lib/sram_program.ld
- util/device_sw_utils/extract_sw_logs.py
This PR cherry-picks several commits for preparing LTO on ROM_EXT to reduce firmware size.
Includes:
https://github.com/lowRISC/opentitan/pull/22008
* d4ba5d405ea015ebd1ddf0905ddfcf658ac254ae
* ef73fd81c24adb0ba3399acbcfd1f7d0497ab6ee
* 6f63d6bae02fbb401affd3c510403756e0f6174c
* 42e5bc0ac897e069391950b53111bcde3f0c7a72
https://github.com/lowRISC/opentitan/pull/22052
* 13c8e1da6726b63a75d18ee247a921a006edf1df
* (2eaf0b347de2482ac8daf2575803fa72f22c4691 is skipped since master already uses a newer CRT)
> [rom_ext] Explicitly mark static critical vars as used

- hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
This test is quite long and sometimes the default test timeout was not enough, letting the test fail in regression runs. Hence, this commit doubles the test timeout, letting previously failing tests pass again.
> [sram_ctrl,dv] Increase sram_ctrl_bijection test timeout

- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
- sw/device/silicon_creator/manuf/lib/individualize.c
- sw/host/opentitanlib/src/test_utils/lc.rs
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/orchestrator/src/device_id.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/tests/device_id_test.py
The CP device ID is extracted from flash during CP and passed to FT. If the CP step is skipped, e.g., if the device is already in test_locked*, then host will not know what the CP device ID is.
This updates the provisioning flow to extract the CP device ID from flash again during FT and pass it back to the host, making the flow reentrant.
Note, this depends on #25608; only review the last two commits.
> [provisioning] enable reentrant provisioning flow

- hw/ip/hmac/data/hmac.hjson
This version bump encompasses the RTL changes with minor functional
impact as part of the D3 sign-off. Since milestone 2.0.0 was taped
out, the purpose of this version bump is to document that what has
been taped out and signed-off for tape out is different.
> [hmac] Bump version to 2.0.1

- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- This delay is linked to an issue seen on FPGA #24767 and should be solved by RTL change from PR #24771.
> [hmac,dv] Add a delay before issuing stop command

- util/dvsim/LocalLauncher.py
- GUI_DEBUG mode addition is creating an issue when tests are going into timeout. Because Deploy.py is managing GUI_DEBUG mode through GUI mode, but in LocalLauncher.py we were trying to access gui_debug attribute which doesn't exists.
> [dv] Fix DVSim after GUI_DEBUG addition

- util/topgen/secure_prng.py
The original statement contained an interpolated string without the string interpolation token 'f'
> Fixed typo in print statement

- sw/device/silicon_creator/lib/base/static_critical_version.c
The previous PR (#25596) missed this file.
Marking it as used prevents optimizations such as LTO from stripping the value.
We'll be ready to enable LTO on ROM_EXT with this PR and https://github.com/lowRISC/crt/pull/40.
> [rom_ext] Mark static critical version as used

- bazelisk.sh
The `bazelisk.sh` script will try to use a real Bazel from the `PATH` if it can find it, but doesn't check its version against `.bazelversion`.
This change checks the version and falls back to downloading `bazelisk` if it doesn't match.
> [bazel] Check Bazel version when found in PATH

- doc/contributing/doc/README.md
- doc/contributing/hw/design.md
When generating top and top-dependent IPs it is necessary to run cmdgen.
Add a mention of this in doc/contributing/doc/README.md and
doc/contributing/hw/design.md.
> [doc,design] Mention the need to run cmdgen

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/templates/toplevel.sv.tpl
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/templates/toplevel.sv.tpl
- util/topgen.py
- util/topgen/lib.py
- util/topgen/merge.py
- util/topgen/validate.py
This PR adds support for incoming interrupts. The approach is analog to incoming alerts. You define an HJSON, which is included in the PLIC instantiation in the top-level HJSON. Out of this, the tooling creates incoming interrupt inputs and routes them to the collective interrupt vector. The number of interrupts is extended with the number of external interrupts. Regarding SW collateral, the external interrupts are included in all mappings. They map to an unknown device, which is reasonable, as the interrupt is coming from external.
> [topgen] Support for incoming interrupts

- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/doc/registers.md
- a bug has been found via PR #25554, but this has been considered as a specification bug. This PR fixes this issue. Now the specification says that DIGEST and MSG_LENGTH registers can be updated only when HMAC is in IDLE state (instead of when SHA core is disabled).
- linked to https://github.com/lowRISC/opentitan/issues/24363
> [hmac,doc] S&R reg changes when IDLE

- hw/dv/dpi/jtagdpi/jtagdpi.c
- hw/dv/dpi/jtagdpi/jtagdpi.sv
- hw/top_earlgrey/dv/verilator/chip_sim_tb.sv
- hw/top_englishbreakfast/rtl/chip_englishbreakfast_verilator.sv
To avoid starting up a server when not needed, and spending time making the jtagdpi_tick call unnecessarily, an "active" input port is added. This is similar to what's done in gpiodpi already.
> [dv/dpi] add an active port to jtagdpi

- rules/opentitan/defs.bzl
- sw/device/silicon_creator/manuf/extensions/README.md
- sw/device/silicon_creator/manuf/extensions/cfg.bzl
This change adds the ability to run silicon validaton targets on downstream product configurations of Earl Grey, leveraging the @provisioning_ext local repo extensions.
> [sival] Add support for downstream execution envs.

- sw/device/silicon_creator/lib/drivers/rnd.c
https://opentitan.org/book/hw/ip/rv_core_ibex/doc/registers.html#rnd_status
According to the register doc, the `RND_DATA_VALID` is only one bit at bit 0.
Testing against full 32-bits might make us exit the waiting loop before the data actually becomes ready.
> [sw,rnd] Fix polling loop for RND_DATA_VALID

- rules/manifest.bzl
- rules/opentitan/cc.bzl
This PR modifies the output file name of the updated manifest  to include the execution environment name, ensuring unique output file names for each ELF file and resolving the conflicting actions.
The `update_manifest` function was previously using the same output file name for different ELF files, resulting in conflicting actions when multiple environments are set in `exec_env`.
> [bazel] resolve conflicting actions in `update_manifest`

- .github/workflows/ci.yml
The CW305 uses an Artix-7 FPGA which does not require an enterprise Vivado license to synthesise for. We limit the number of machines on the `-bitstream` label to match our number of licenses, however CW305s are taking up these spots unnecessarily.
This commit moves them to the `-vivado` machines which have access to Vivado Standard edition only.
> [ci] Move CW305 bitstream build to machine without license

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/tl_agent/seq_lib/tl_host_seq.sv
When we start a sequence to perform a CSR access, we wrap it in a DV_SPINWAIT with a timeout of e.g. tl_access_timeout_ns. This is a good idea! If the TL bus dies, we'd like the test to time out and fail.
But we might call e.g. csr_rd many times in parallel. If we do so, we'll end up enqueuing many copies of tl_seq. These each take some time to run and a very wide queue will cause the DV_SPINWAIT above to time out. This is a bit silly. There's no problem with the hardware: we're just doing a load of stuff, which takes a long time.
To avoid the problem, we set up an extra level of queueing. Getting through the first queue allows us access to the sequencer and causes the timer to be started.
> [dv] Avoid timing out if we call tl_access_sub lots in parallel

- hw/dv/sv/common_ifs/clk_rst_if.sv
The existing code would always leave at least one process lying around when it ran wait_clks_or_rst. Avoid doing that.
> [dv] Be more careful not to leave orphan processes in clk_rst_if

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
Practically speaking, this doesn't really matter (because it only ever gets called with the default value), but it seems worth tidying up.
> [rom_ctrl,dv] Correct argument to dut_init in rom_ctrl_base_vseq

- hw/dv/sv/cip_lib/cip_base_pkg.sv
~~add the option "goal" to 0 to exclude a coverpoint from the coverage calculation as VCS seems to ignore the weight option to 0 for some reason.~~
explicit has_mem_byte_access_err, has_wo_mem, has_ro_mem values as no default has been set, which can lead to different behaviour with different simulators I guess.
~~related to issue https://github.com/lowRISC/opentitan/issues/23594~~
> [cip,dv] Explicit some fcov flags init val.

- sw/host/opentitantool/src/command/lc.rs
Add `opentitantool` argument to skip reset on `LcStateRead`. This is useful when debugging device alerts  as the device will report escalation state as a result of an escalation. Since the escalation status is not persisted across resets, we need to be able to connect to LC_TAP to read without performing a reset. This is only possible in lc states that support continuous PINMUX_TAP polling.
> [sival] Add option to skip reset on lc state read.

- third_party/hyperdebug/repos.bzl
A single bugfix to recently introduced feature to optionally have SPI or I2C TPM operations recognize Google's "TPM ready" signal.
a3d721e81c board/hyperdebug: Corrections to TPM "GSC ready" logic
> [opentitantool] HyperDebug firmware fix

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
In the sram_dv_increase_timeout_reset test, we are waiting to issue a reset when no outstanding TL-UL are in the fly. This wait timed out in some of the tests. Increasing the wait timer lets the test pass.
> [sram_ctrl,dv] Increase wait_cycles for rand_reset tests

- sw/device/lib/dif/autogen/dif_adc_ctrl_autogen.c
- sw/device/lib/dif/autogen/dif_alert_handler_autogen.c
- sw/device/lib/dif/autogen/dif_aon_timer_autogen.c
- sw/device/lib/dif/autogen/dif_csrng_autogen.c
- sw/device/lib/dif/autogen/dif_dma_autogen.c
- sw/device/lib/dif/autogen/dif_edn_autogen.c
- sw/device/lib/dif/autogen/dif_entropy_src_autogen.c
- sw/device/lib/dif/autogen/dif_flash_ctrl_autogen.c
- sw/device/lib/dif/autogen/dif_gpio_autogen.c
- sw/device/lib/dif/autogen/dif_hmac_autogen.c
- sw/device/lib/dif/autogen/dif_i2c_autogen.c
- sw/device/lib/dif/autogen/dif_keymgr_autogen.c
- sw/device/lib/dif/autogen/dif_keymgr_dpe_autogen.c
- sw/device/lib/dif/autogen/dif_kmac_autogen.c
- sw/device/lib/dif/autogen/dif_mbx_autogen.c
- sw/device/lib/dif/autogen/dif_otbn_autogen.c
- sw/device/lib/dif/autogen/dif_otp_ctrl_autogen.c
- sw/device/lib/dif/autogen/dif_pattgen_autogen.c
- sw/device/lib/dif/autogen/dif_pwrmgr_autogen.c
- sw/device/lib/dif/autogen/dif_rv_timer_autogen.c
- sw/device/lib/dif/autogen/dif_sensor_ctrl_autogen.c
- sw/device/lib/dif/autogen/dif_spi_device_autogen.c
- sw/device/lib/dif/autogen/dif_spi_host_autogen.c
- sw/device/lib/dif/autogen/dif_sysrst_ctrl_autogen.c
- sw/device/lib/dif/autogen/dif_uart_autogen.c
- sw/device/lib/dif/autogen/dif_usbdev_autogen.c
- util/make_new_dif/templates/dif_autogen.c.tpl
The functino performs an incorrect check on the irq number. In particular, this number could be negative or above max_irq+1. If this happens, the function will perform an out-of-bound array access.
One particular instance where this could happen is in the isr testutils where it can be called with an incorrect argument.
> [dif] Fix dif_<ip>_irq_get_type to handle bad arguments

- hw/cdc/tools/meridiancdc/run-cdc.tcl
Without the `-scenario` argument, `report_policy` only reports checks for the current scenario, which is the ENV file at this point in the script.  By adding `sdc`, also SDC setup check results get reported.
> [meridiancdc] Include SDC results in setup checks report

- hw/ip/tlul/lint/tlul_request_loopback.vlt
- hw/ip/tlul/lint/tlul_request_loopback.waiver
- hw/ip/tlul/request_loopback.core
- hw/ip/tlul/rtl/tlul_request_loopback.sv
- hw/ip/tlul/tlul.core
- hw/ip_templates/ac_range_check/README.md
- hw/ip_templates/ac_range_check/data/ac_range_check.hjson.tpl
- hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl
This PR implements the range check logic of the AC range checks. If there is a failing request, the request is squashed.
> [hw,ac_range_check] Implement range check logic

- sw/device/tests/BUILD
- sw/device/tests/entropy_src_bypass_mode_health_test.c
This test implements the entropy source test,
"chip_sw_entropy_src_bypass_mode_health_tests" scenario as described in the OpenTitan testplan.
- ENTROPY_SRC provides one initial seed in boot-time / bypass mode.
- Signals a recoverable alert if the total failure counter hits the threshold in boot-time / bypass mode.
- Checks and prints status registers for debug
See: /hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
> [sival/entropy_src] Add entropy_src_bypass_mode_health_test

- hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/alert_handler_escalation_test.c
- sw/device/tests/sim_dv/BUILD
This PR generalizes the existing `alert_handler_escalation_test` to all simulation targets to cover the
`chip_sw_alert_handler_escalation` testplan item (as specified in `hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson`).
> [alert, sival] chip_sw_alert_handler_escalation

- hw/ip/pattgen/doc/programmers_guide.md
- hw/ip/pattgen/doc/theory_of_operation.md
Update the design details, and particularly the signal names, to match the implementation better. This should aid in reading and understanding the RTL. Include the `inactive_level_pcl|pda signals` which were previously omitted from the design details. Assorted linguistic corrections and refinements.
> [doc,pattgen] Documentation refinements

- sw/device/silicon_creator/imm_rom_ext/BUILD
- sw/device/silicon_creator/imm_rom_ext/defs.bzl
- sw/device/silicon_creator/imm_rom_ext/hello_world.c
- sw/device/silicon_creator/imm_rom_ext/hello_world.h
- sw/device/silicon_creator/imm_rom_ext/hello_world.ld
- sw/device/silicon_creator/imm_rom_ext/hello_world_start.S
- sw/device/silicon_creator/imm_rom_ext/utils.bzl
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
* Add minimized C code, startup asm and linker script for a standalone IM_EXT build target.
* Add a bazel rule `imm_rom_ext_section`, which will transform binaries into object files and turn it to a target that can be directly used as deps of ROM_EXT's bazel targets.
* Reuse the rule `opentitan_binary` to build IM_EXT and add a attribute to skip the signing stage to the rule. The manifest given as None will turn into the default manifest and keep the signing operation so we need to skip it explicitly.
* Add a map for all IM_EXT target that can be used and make the ROM_EXT targets iterate the map to generate multiple targets.
* Update the ROM_EXT to use in e2e verified boot test.
---
This PR partially addresses https://github.com/lowRISC/opentitan/issues/24368.
The first commit is included …
> Add hello world imm rom ext

- hw/ip/hmac/doc/programmers_guide.md
- sw/device/lib/crypto/drivers/BUILD
- sw/device/lib/crypto/drivers/hmac.c
In line with the RTL fix in #24771 for the hash stop hang bug described in #24767, this commit reverts four commits that implemented a software workaround for the issue and only keeps the idle polling timeout implementation from #24944. This workaround and its corresponding documentation is now obsolete.
Reverted commits:
- e869152 #25070
- 2b072c4 #25012
- 7f32449 #24966
- f591bea #24944
> [hmac, sw] Revert hash stop hang workaround

- sw/device/tests/crypto/BUILD
This allows these tests to run on SiVal nightlies.
> [SiVal] Add the cw340 exec_env to crypto tests

- sw/device/silicon_creator/manuf/tests/BUILD
- sw/host/opentitanlib/bindgen/BUILD
- sw/host/opentitanlib/bindgen/difs.h
- sw/host/opentitanlib/src/test_utils/load_sram_program.rs
Previously, we were relying on HW_CFG1 partition not being programmed yet for SRAM execution to be enabled in TEST_UNLOCKED* states. However, this limits the re-entrancy of the FT individualize program, where HW_CFG1 is programmed but the individualize program needs to be re-tried again.
> [opentitanlib] set EXEC CSR in sram_ctrl when SRAM program is loaded

- sw/host/provisioning/orchestrator/README.md
- sw/host/provisioning/orchestrator/src/BUILD
- sw/host/provisioning/orchestrator/src/ca_config.py
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/src/sku_config.py
- sw/host/provisioning/orchestrator/src/util.py
- sw/host/provisioning/orchestrator/tests/BUILD
- sw/host/provisioning/orchestrator/tests/e2e.sh
- sw/host/provisioning/orchestrator/tests/util_test.py
This PR updates the provisioning orchestrator to use the `runfiles` library from rules_python to resolve paths to Bazel runfiles. This simplifies the instructions for running the packaged orchestrator. The previous instructions had a few small issues that caused some trouble.
Some hackery was required to preserve the scheme used previously for referring to the main repo vs external repos. We could remove this logic if openocd was the only external reference, but I have a hunch this may be required for supporting provisioning extensions.
> [manuf] Clean up runfile path handling in orchestrator

- hw/ip/i2c/data/i2c_testplan.hjson
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
These were showing up as errors because host_sanity and V2 were expecting there to be a i2c_host_rx_oversample test, but this has been commented out pending #21887. This commit just comments those out with the same TODO issue linked.
> [i2c,dv] Fully remove rx oversample test

- hw/ip/rom_ctrl/dv/cov/cover_reg_top.cfg
We are not required to collect assertion coverage for prim_fifo_sync instantiated in tlul_adapter_sram. Commit 0372c1f removed the assert coverage for these modules but still got assertion coverage holes reported by VCS.
> [rom_ctrl, dv] Assertion coverage collection for tlul_adapter_sram

- MODULE.bazel.lock
- third_party/rust/rust.MODULE.bazel
This is the URL we used before switching to bzlmod. `toolchains_llvm` also automatically picks up this exact toolchain for Ubuntu, however it also detects OS version which would fail for NixOS.
Pinning the URL and hash would make it work for NixOS dev environment setup used in lowRISC.
> [bazel, rust] pin LLVM toolchain URL and hash

- MODULE.bazel
Due to semantic version resolution, we're actually getting `bazel_skylib` version 1.7.1 due to a dependency asking for it.
Update the version listed in `MODULE.bazel` to match so the warning is supressed.
> [bazel] Correct `bazel_skylib` version in `MODULE.bazel`

- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/sku_config.py
The extension CA was made optional in #25545 in the host benchtop provisioning FT harness. However, it was not propagated to the orchestrator script. This updates the orchestrator script to also make the extension CA optional, as some SKUs do not require extensions.
> [provisioning] make extension CA config optional

- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/ft_lib/src/lib.rs
Certain SKUs require personalization success validation which extends beyond confirming that the ROM_EXT in slot B has started.
Let's allow the user to specify a string which when issued on the chip console indicates perso success.
This will require longer timeouts after post perso reboot.
Tested the following:
- when onwer string is not provided . success and failure due UDS cert problems are reported as before
- when owner string is provided . failure due UDS cert problems is still reported . success when fw string is detected is reported . in case fw string is not detected timeout results in an error
> [provisioning]: allow the owner to specify perso success condition

- hw/dv/sv/alert_esc_agent/alert_esc_agent.sv
I was trying to be clever when I wrote a771270fab3, and set the ping sequence to run with a lower priority than the alert response sequence. But this doesn't work with the default fifo arbitration...
> [alert,dv] Use priorities in alert agent arbitration

- hw/dv/sv/jtag_agent/jtag_driver.sv
This was very chatty and meant that rv_dm tests with -vm weren't very
easy to interpret. Drop the messages to UVM_HIGH accordingly.
(The PR looks bigger than it really is, because it depends on #23097. Once that is merged, this is just the last commit)
> [jtag,dv] Demote some driver messages to UVM_HIGH

- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_excl.el
t is impossible to see !tl_i_int.a_valid & !error_internal. When a_valid is false, it is seen
in u_err inside tlul_adapter_sram.sv. This will make a_config_allowed inside u_err false as it
depends on addr_sz_chk, mask_chk and fulldata_chk. All of them are false if a_valid is false.
This means that the first term inside err_o definition in u_err is false which raised err_o.
Next, err_o become visible to error_det as tlul_error inside tlul_adapter_sram and it will
be true if tlul_error is true. error_det will then be seen as error_i to u_sram_byte inside
tlul_adapter_sram.
Since EnableIntg parameter is 0 for rom_ctrl, error_i comes out as error_o from u_sram_byte.
Then error_o would be seen as error_internal to tlul_adapter_sram and the conditional statement
is not able to cover 00 case for …
>  [rom_ctrl, dv] Exclusion of non-occuring cases for tlul_adapter_sram 

- sw/host/provisioning/orchestrator/src/ot_dut.py
The extension CA is sometimes unused by SKUs. It should not be required by the orchestrator.
> [orchestrator] enable empty EXT CA

- hw/ip/dma/doc/registers.md
- hw/ip/keymgr/doc/registers.md
- hw/ip/kmac/doc/registers.md
- hw/ip/lc_ctrl/doc/registers.md
- hw/ip/otp_ctrl/doc/registers.md
- hw/ip/pwm/doc/registers.md
- hw/ip/rv_core_ibex/doc/registers.md
- hw/ip/sysrst_ctrl/doc/registers.md
- hw/top_darjeeling/ip_autogen/pinmux/doc/registers.md
- hw/top_darjeeling/ip_autogen/rstmgr/doc/registers.md
- hw/top_earlgrey/ip/sensor_ctrl/doc/registers.md
- hw/top_earlgrey/ip_autogen/flash_ctrl/doc/registers.md
- hw/top_earlgrey/ip_autogen/pinmux/doc/registers.md
- hw/top_earlgrey/ip_autogen/rstmgr/doc/registers.md
- util/reggen/gen_md.py
The Markdown documentation generator from b1e7742d911 accidentally missed it for multi-registers.
Most of this commit is auto-generated. The only hand-rolled bit is the change to util/reggen/gen_md.py
Fixes #25688.
> [reggen] Describe REGWEN properly for multi-registers

- sw/device/silicon_creator/manuf/data/manuf_testplan.hjson
- sw/device/silicon_creator/manuf/tests/BUILD
These are the most obvious links based on the name.
Adding the CW340 exec_env will make these tests to be executed in the SiVal nightly job.
The remaining manufacture tests will be linked in a separated PR.
> [SiVal] Map manufacture tests to the testplans

- .github/workflows/ci.yml
- sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
- sw/device/silicon_creator/rom_ext/e2e/handoff/BUILD
- sw/device/silicon_creator/rom_ext/e2e/lockdown/BUILD
- sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD
- sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
- sw/device/silicon_creator/rom_ext/rescue.c
- sw/device/silicon_owner/bare_metal/BUILD
- sw/device/tests/BUILD
This is a manual cherry-pick of #24430,
Use the fpga_hyper310_rom_ext environment for ROM_EXT end-to-end tests.
The hyperdebug serial ports support serial break out of the box, whereas
the CW310 serial ports require special SAM3x firmware to support serial
break.
> Cherry-pick to master: [rom_ext_e2e] Update CI to run ROM_EXT tests on hyper310

- sw/otbn/crypto/modexp.s
See https://github.com/lowRISC/opentitan/pull/25300 for context; this is an updated version of that hardening change based on the [coding guidelines](https://opentitan.org/book/doc/contributing/style_guides/otbn_style_guide.html?highlight=bn.sel#handling-secret-shares) from COCO-Alma.
Add some SCA hardening measures to the modexp subroutine that selects either the squared or squared-and-multiplied result in square-and-multiply-always modular exponentiation.
Although the rest of the code is not hardened, the hardening for RSA will likely preserve this subroutine, so hardening it is still useful.
> [crypto] Harden RSA modexp subroutine.

- sw/host/hsmtool/src/commands/spx/export.rs
- sw/host/hsmtool/src/commands/spx/generate.rs
- sw/host/hsmtool/src/commands/spx/import.rs
- sw/host/hsmtool/src/commands/spx/list.rs
- sw/host/hsmtool/src/commands/spx/sign.rs
- sw/host/hsmtool/src/commands/spx/verify.rs
- sw/host/hsmtool/src/error.rs
- sw/host/hsmtool/src/module.rs
1. It is legal for SPX key entities to be missing a PKCS#11 `id`.
2. Rename the `acorn` field to `spx`, as it represents a generic interface to SPX functions rather than a specific implementation.
> [hsmtool] SPX cleanups

- hw/ip/prim/rtl/prim_sha2_pad.sv
This commit removes some conditional FSM states transition that were deemed undesirable in `prim_sha2_pad`, see #23936. It made it possible to cancel an ongoing padding operation, which is disallowed by the HMAC module. As a side-effect, the removal plugs some existing FSM transition coverage holes in `prim_sha2_pad` whose manual exclusions can be removed as well.
This change makes it impossible to transition into the `StFifoReceive` state from either `StPad80`, `StPad00`, `StLenHi` or `StLenLo` by asserting the `hash_go` signal.
> [hmac, rtl] Do not skip padding after a hash stop command

- hw/ip/prim/lint/prim_rom_adv.waiver
- hw/ip/prim/prim_rom_adv.core
- hw/ip/prim/rtl/prim_rom_adv.sv
- hw/ip/prim_generic/rtl/prim_generic_rom.sv
Tech specifc ROM macros might have a reset input. Add them to the prim.
> [hw,prim_rom,rtl] Add reset input to prim_rom

- ci/scripts/BUILD
- ci/scripts/run-fpga-tests.sh
- ci/scripts/run_test.sh
The log are quite long and GitHub provides a feature where the output group can split lines into groups. This is achieved by using the --run_under command of bazel test. This allows to run a script that then invokes the test runner. This only thing this script does is print the grouping commands.
> [ci] Create GitHub groups in log outputs for FPGA tests

- hw/ip/pwm/rtl/pwm_chan.sv
Heartbeat direction reversal was premature in the event of passing the target duty cycle (non-wrapping case). The heartbeat direction shall only be changed at the end of the 'X'+1 pulse cycles for the current duty cycle.
This was found using the improved DV which is ongoing; the current DV environment overlooked this deviation from the specification.
> [pwm] Correction to heartbeat mode

- hw/ip/rv_core_ibex/data/rv_core_ibex.hjson
- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/vendor/lowrisc_ibex.lock.hjson
- hw/vendor/lowrisc_ibex/doc/02_user/integration.rst
- hw/vendor/lowrisc_ibex/doc/03_reference/debug.rst
- hw/vendor/lowrisc_ibex/doc/03_reference/pmp.rst
- hw/vendor/lowrisc_ibex/dv/riscv_compliance/rtl/ibex_riscv_compliance.sv
- hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
- hw/vendor/lowrisc_ibex/dv/verilator/pcount/cpp/ibex_pcounts.cc
- hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_core.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_lockstep.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_pmp.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_top.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_top_tracing.sv
This PR updates Ibex to https://github.com/lowRISC/ibex/commit/a05d4d82 to include a recent RTL change that allows all accesses to the Debug Module in debug mode (https://github.com/lowRISC/ibex/pull/2232), and it bumps the minor version of `rv_core_ibex` to 2.1.0 to reflect the SW-visible backward-compatible change.
> [rv_core_ibex] Update Ibex to allow all accesses to Debug Module in debug mode

- hw/ip/spi_host/data/spi_host.hjson
- hw/ip/spi_host/doc/registers.md
- hw/ip/spi_host/dv/README.md
- hw/ip/spi_host/dv/env/spi_host_env_pkg.sv
- hw/ip/spi_host/rtl/spi_host_cmd_pkg.sv
- hw/ip/spi_host/rtl/spi_host_fsm.sv
- hw/ip/spi_host/rtl/spi_host_reg_pkg.sv
- hw/ip/spi_host/rtl/spi_host_reg_top.sv
Currently, the SPI host only supports a 9-bit command length, meaning an SPI transaction can only transfer 512b. This is especially problematic for integrated devices, where large FW blobs (>5MB) need to be fetched from the external SPI flash. When used in conjunction with the DMA (hardware-handshake mode), only a few chunks can be transferred before re-programing the SPI host and DMA.
To overcome this problem, we extend the command length to 20
Bit. This allows a more flexible use case and allows the system to read large FW blobs with a single SPI and DMA configuration.
/cc @rivos-eblot
> [hw,spi_host,rtl] Increase command length register to 20 bit

- util/reggen/params.py
- util/topgen/intermodule.py
- util/topgen/merge.py
Otherwise, the same parameter of a difference instance would be overwritten.
This fixes the issue in https://github.com/lowRISC/opentitan/pull/25625#discussion_r1882240404, where the same parameter was used in multiple parametrized port definitions.
> [topgen] Deepcopy parameter when mangeling

- hw/ip/prim/doc/prim_keccak.md
- hw/ip/prim/rtl/prim_keccak.sv
The unhardened prim_keccak primitive is not actually used in the design. It's purpose is serve as an FPV example.
> [prim/doc] Add pointer to hardened Keccak implementation in prim_keccak

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/tests/BUILD
- sw/device/tests/otp_ctrl_rot_auth_config_test.c
This test exercises the ROT AUTH programming sequence performed during FT stages. The ROT AUTH partitions are used to store the ROM (e.g. root keys) of the Earl Grey top level.
Note: This is WIP. I will update the PR once I get test results.
> [dv] Add ROT_AUTH configuration test.

- hw/ip/spi_host/data/spi_host.hjson
- hw/ip/spi_host/doc/registers.md
- hw/ip/spi_host/dv/README.md
- hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_overflow_underflow_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_performance_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_smoke_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_speed_vseq.sv
- hw/ip/spi_host/dv/env/seq_lib/spi_host_upper_range_clkdiv_vseq.sv
- hw/ip/spi_host/dv/env/spi_host_env_cov.sv
- hw/ip/spi_host/dv/env/spi_host_env_pkg.sv
- hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
- hw/ip/spi_host/dv/sva/spi_host_bind.sv
- hw/ip/spi_host/dv/sva/spi_host_data_stable_sva.sv
- hw/ip/spi_host/rtl/spi_host.sv
- hw/ip/spi_host/rtl/spi_host_reg_pkg.sv
- hw/ip/spi_host/rtl/spi_host_reg_top.sv
- sw/device/lib/dif/dif_spi_host.c
- sw/device/lib/dif/dif_spi_host_unittest.cc
With a single configopts register, the register layout does not change when the user changes the `NumCS` parameter. Firmware, however needs to set up the config register ahead of a new transfer, but only when switching to a different device.
> [hw,spi_host,rtl] Remove configopts multi register

- hw/dv/sv/sim_sram/sim_sram.sv
- hw/ip/prim/lint/prim_ram_1p_adv.waiver
- hw/ip/prim/rtl/prim_ram_1p_adv.sv
- hw/ip/prim_generic/lint/prim_generic_flash.waiver
- hw/ip/prim_generic/lint/prim_generic_ram_1p.waiver
- hw/ip/prim_generic/rtl/prim_generic_flash_bank.sv
- hw/ip/prim_generic/rtl/prim_generic_ram_1p.sv
- hw/ip/prim_xilinx/rtl/prim_xilinx_ram_1p.sv
- hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_ram_1p.sv
- hw/vendor/lowrisc_ibex/dv/uvm/icache/dv/prim_badbit/prim_badbit_ram_1p.sv
- hw/vendor/lowrisc_ibex/rtl/ibex_top.sv
- hw/vendor/patches/lowrisc_ibex/dv/0003-PATCH-Add-rst-to-prim_ram_1p.patch
- hw/vendor/patches/lowrisc_ibex/rtl/0004-PATCH-Add-rst-to-prim_ram_1p.patch
A reset input is reasonable as the underlying macro might need a reset signal for internal flops.
> [hw,prim_ram_1p,rtl] Add reset input to prim_ram_1p

- hw/dv/sv/pwm_monitor/pwm_if.sv
- hw/dv/sv/pwm_monitor/pwm_item.sv
- hw/dv/sv/pwm_monitor/pwm_monitor.sv
- hw/dv/sv/pwm_monitor/pwm_monitor_cfg.sv
- hw/ip/pwm/dv/README.md
- hw/ip/pwm/dv/env/pwm_env_cfg.sv
- hw/ip/pwm/dv/env/pwm_env_pkg.sv
- hw/ip/pwm/dv/env/pwm_scoreboard.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_heartbeat_wrap_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_perf_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_rand_output_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_smoke_vseq.sv
- hw/ip/pwm/dv/tb.sv
This PR offers extensive improvements to the amount of verification performed by the existing DV environment.
Unfortunately the majority of the sequence items were being silently ignored previously as a result of a couple of clear faults in the DV environment (incorrect clock, ignoring items that had a 'period' mismatch, and a 'settle time' whenever the blink phase changed).
The DV also made no attempt to monitor disabled channels, pulse cycles with no change in the output (duty cycle of zero), or the phase delay of outputs. The low power mode testing was also deficient.
This PR improves the DV and achieves a near 100% pass rate; there is an issue with 'pwm_alert_test' at present, and some sequences will fail on account of the initial pulse cycle being hard to predict because of the CDC …
> [dv,pwm] DV improvements for PWM

- hw/ip/sram_ctrl/dv/cov/sram_ctrl_cov_excl.el
As the FSM within the tlul_sram_byte was modified, the exclusions are not matching anymore. This commit excludes two uncovered branches that cannot be reached as (1) the read latency of the prim_ram is always 1 and (2) it always can accept a new read/write operation.
> [sram_ctrl,dv] Update tlul_sram_byte exclusions

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
After resetting, we should wait a bit before starting the new test to make sure that the tl_agent message queue really is emptied. If we are not doing this, we might see the following error:
```
./util/dvsim/dvsim.py hw/ip/sram_ctrl/dv/sram_ctrl_main_sim_cfg.hjson \
-i sram_ctrl_passthru_mem_tl_intg_err -t vcs --fixed-seed \
41020402185315011969996404882728929238760707320232330314609988937493640571488
UVM_ERROR @ 2116319532 ps: uvm_test_top.env.m_tl_agent_sram_ctrl_regs_reg_block
sequencer [uvm_test_top.env.m_tl_agent_sram_ctrl_regs_reg_block.sequencer] get_
next_item/try_next_item called twice without item_done or get in between
```
> [sram_ctrl,dv] Add post apply reset delay

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
This allows to route differnt config parameters to different RAM instances.
> [hw,darjeeling,rtl] Separate the RAM cfg ports

- sw/device/lib/dif/dif_sram_ctrl.h
With lowRISC/opentitan#21850, key requests that are issued during a memory init are ignored by the hardware. This has not yet been reflected in the dif_sram_ctrl_request_new_key and dif_sram_ctrl_wipe function description.
> [dif, sram_ctrl] Update wipe and key request description

- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
No need to use an overwritable `parameter` when it is essentially just a local parameter.
> [hw,sram_ctrl,rtl] Use localparam for local parameters

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- this PR should fix this issue https://github.com/lowRISC/opentitan/issues/24690
- Move the IDLE pin check from the base sequence to the SCB as it makes more sense to perform check there.
> [hmac,dv] Move IDLE check from vseq to scb

- hw/top_darjeeling/rtl/top_pkg.sv
Lets change it. This is used to accommodate the RACL and CTN ID information.
> [top,darjeeling] Darjeelling uses 27 user bits

- hw/ip/prim_generic/prim_generic_ram_1p.core
- hw/ip/prim_generic/prim_generic_ram_1r1w.core
- hw/ip/prim_generic/prim_generic_ram_2p.core
- hw/ip/prim_xilinx/prim_xilinx_ram_1p.core
For generic usages, i.e.g, when using a ram_pkg in spi_device or in i2c, we rely on the fusesoc resolving skills. Once the virtual cors PR is merged, this gets explicitly set in the top-level core file.
> [prim_generic] Depend on the tech ram_pkg within the tech lib

- hw/ip/spi_host/data/spi_host.hjson
- hw/ip/spi_host/dv/env/spi_host_env_cfg_pkg.core
- hw/ip/spi_host/dv/env/spi_host_env_cfg_pkg.sv
- hw/ip/spi_host/dv/env/spi_host_env_pkg.sv
- hw/ip/spi_host/dv/sva/spi_host_bind.sv
- hw/ip/spi_host/dv/sva/spi_host_data_stable_sva.sv
- hw/ip/spi_host/dv/sva/spi_host_sva.core
- hw/ip/spi_host/dv/tb.sv
- hw/ip/spi_host/rtl/spi_host.sv
- hw/ip/spi_host/rtl/spi_host_cmd_pkg.sv
- hw/ip/spi_host/rtl/spi_host_command_queue.sv
- hw/ip/spi_host/rtl/spi_host_core.sv
- hw/ip/spi_host/rtl/spi_host_fsm.sv
- hw/ip/spi_host/rtl/spi_host_reg_pkg.sv
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
This moves the NumCS param from the reg_top_pkg to an instance level parameter. This allows instances to overwrite the parameter.
> [hw,spi_host,rtl] Make NumCS an exposed  parameter

- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_excl.el
The signals that are excluded are tied to constants and thus landed as toggle coverage holes.
> [rom_ctrl, dv] Exclusion of toggle coverages

- sw/host/opentitantool/BUILD
- sw/host/opentitantool/src/command/bfv.rs
- sw/host/opentitantool/src/command/mod.rs
- sw/host/opentitantool/src/main.rs
- util/BUILD
- util/bfv_decoder.c
Given the hex value reported in the `BFV: xxxxxxxx` entry of the crash log print the symbolic name of the error.
Usage example:
> bazel run //util:fw_error_decode -- 50540d 0c4f5705 123
...
0050540d: kErrorPersoTlvInternal
0c4f5705: kErrorOwnershipKeyNotFound
00000123: unknown error code
> util: tool for parsing BFV codes

- sw/device/tests/BUILD
- sw/device/tests/alert_handler_lpg_sleep_mode_pings.c
* FPGA support is extended to the CW340.
* DV timings are corrected to match the DV.
* Silicon support is added.
* Unknown environments are now handled explicitly.
Note that I can't currently test this on the FPGA due to the flash splicing problem.
> Fix `alert_handler_lpg_sleep_mode_ping` tests for silicon (and other envs)

- util/reggen/README.md
Whether an error is typically returned depends on whether the requested address can be represented with the internally available address bits or not. This commit clarifies this with the help of an example.
This got reported by Amisha Srivastava from University of Texas at Dallas.
> [reggen/doc] Clarify when accesses to unmapped addresses return errors

- hw/ip/hmac/data/hmac.hjson
- hw/ip/hmac/doc/registers.md
- hw/ip/hmac/rtl/hmac.sv
- hw/ip/prim/rtl/prim_sha2.sv
- related to issue https://github.com/lowRISC/opentitan/issues/23563
- update spec to be aligned with the RTL
- add assertions to check the effect of wipe secret operation
> [hmac] Wipe secret assertions and spec update

- sw/device/lib/crypto/drivers/kmac.c
- sw/device/lib/crypto/drivers/kmac.h
- sw/device/lib/crypto/impl/kdf.c
- sw/device/lib/crypto/impl/mac.c
- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/kdf_kmac_functest.c
- sw/device/tests/crypto/kdf_set_testvectors.py
- sw/device/tests/crypto/kdf_testvectors.h.tpl
Previously, the KMAC driver always unmasked the shares of the digest returned by the KMAC block. This is OK for hash functions like SHA-3, but problematic for KMAC-KDF where the output is key material. The implementation also did not modify the second half of the keyblob buffer in KMAC-KDF, which would actually cause correctness issues if those values were not initialized to zero.
This commit refactors the KMAC driver to allow returning the digest in masked form, and adjusts KMAC-KDF to use this new capability.
While I was messing with this code anyway, I also made a small tweak to the way that KMAC-KDF test vectors are formed; the previous setup defined the expected output as a full blinded key struct with most of the fields uninitialized, but this is unnecessary and confusing in my …
> [crypto] Fix the KMAC-KDF implementation to return the output in shares.

- hw/ip/entropy_src/rtl/entropy_src.sv
We currently don't use the stubbing anywhere in the codebase but some lint tools tend to flag issues despite the corresponding parameter being disabled.
This resolves lowRISC/OpenTitan#24231.
> [entropy_src/rtl] Fix reg reference and default value for stubbed impl

- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
- sw/device/lib/dif/dif_usbdev.c
- sw/device/lib/dif/dif_usbdev.h
- sw/device/lib/testing/usb_testutils.c
- sw/device/lib/testing/usb_testutils.h
- sw/device/lib/testing/usb_testutils_controlep.c
- sw/device/lib/testing/usb_testutils_streams.c
- sw/device/lib/testing/usb_testutils_streams.h
- sw/device/tests/BUILD
- sw/device/tests/usbdev_deep_disconnect_test.c
- sw/device/tests/usbdev_deep_reset_test.c
- sw/device/tests/usbdev_deep_resume_test.c
- sw/device/tests/usbdev_sleep_disconnect_test.c
- sw/device/tests/usbdev_sleep_reset_test.c
- sw/device/tests/usbdev_sleep_resume_test.c
- sw/device/tests/usbdev_suspend.c
- sw/device/tests/usbdev_suspend.h
- sw/device/tests/usbdev_suspend_full_test.c
- sw/device/tests/usbdev_suspend_resume_test.c
- sw/host/tests/chip/usb/BUILD
- sw/host/tests/chip/usb/usb.rs
- sw/host/tests/chip/usb/usbdev_suspend.rs
- sw/host/tests/usbdev/usbdev_stream/usb_device.cc
- sw/host/tests/usbdev/usbdev_stream/usb_device.h
This PR is based on the PR: https://github.com/lowRISC/opentitan/pull/23200
> [SiVal, usbdev] Suspend and Resume test.

- third_party/rust/Cargo.lock
- third_party/rust/Cargo.toml
- third_party/rust/patches/mdbook-landing-page-links.patch
This PR updates the rust dependencies found in `third_party/rust` to solve determinism and security issues. Primarily due to the usage of outdated versions of `mdbook` (due to patching) and the unused `rust-crypto` crate, we had a lot of transitive dependencies with security advisories / vulnerabilities. There is also a separate commit for directly pulling in updates to the `rustix` and `object` crates which had build determinism issues (see commit message).
It might be nice to do a more general `cargo update`, but I'm conservatively updating only what is necessary for now as I was running into build issues in CI that presumably need fixes.
See the commit messages for more details.
> [deps,bazel] Rust dependency updates for build determinism & `cargo audit`

- hw/ip_templates/pinmux/rtl/pinmux.sv.tpl
- hw/top_darjeeling/ip_autogen/pinmux/rtl/pinmux.sv
These signals are only available when enabling strap sampling. If not, gate the assertions.
> [hw,pinmux,rtl] Also gate assertions to signals related to strap sampling

- hw/dv/sv/dv_base_reg/dv_base_reg.sv
- hw/dv/sv/dv_base_reg/dv_base_reg_field.sv
The base scoreboard ignores register reads checks unless the prediction flag is set. The fields that are predicted in a given register can be then accessed via a mask in dv_base_reg
> [dv, base_reg] Adding a prediction flag to field and mask to reg

- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- when a reset a is happening, the HMAC DV env is not really robust. Some tasks are still ongoing and would require to be killed. A temporary fix has been proposed to skip the msg_length check when a Save and Restore task is ongoing when a reset is triggered. A better approach will be put in place later when a proper reset agent will be used.
> [hmac,dv] Skip msg_length check when reset

- site/book-theme/css/chrome.css
- site/book-theme/css/general.css
- site/book-theme/css/variables.css
- site/book-theme/index.hbs
This should make the mdBook rendering work in accordance with the changes from `mdBook` version 0.4.34 -> 0.4.43, fixing e.g. the broken sidebar links or sidebar collapse visibility.
These files were created by running the following command to get our diffs from the file's first introduction, e.g. for `index.hbs`:
```
git diff b84b6e2feba718bce3cf29c29bc58a78325bb868 site/book-theme/index.hbs
```
and then applying the same diffs (where applicable) to the latest 0.4.43 `index.hb` (etc.) file from the `mdBook` crate.
I've tested this by building the documentation locally and clicking around for a while and it seems to fix the issues that were introduced by the latest `mdBook` update.
> [docs,deps] Update mdBook site theme files to latest versions

- sw/host/opentitantool/BUILD
- sw/host/opentitantool/src/command/bfv.rs
- sw/host/opentitantool/src/command/mod.rs
- sw/host/opentitantool/src/main.rs
- util/BUILD
- util/bfv_decoder.c
Given the hex value reported in the `BFV: xxxxxxxx` entry of the crash log, print the symbolic name of the error.
Usage example:
> bazel run //sw/host/opentitantool:opentitantool -- --rcfile-= bfv 50540d 0c4f5705 123
...
0050540d: kErrorPersoTlvInternal
0c4f5705: kErrorOwnershipKeyNotFound
00000123: unknown error code
Signed-off-by: Vadim Bendebury <vbendeb@chromium.org>
(cherry picked from commit ee783ac25c3da454c859e2c3c181bb2227f8b947)
> opentitantool: option for parsing BFV codes

- sw/device/silicon_creator/imm_rom_ext/BUILD
- sw/device/silicon_creator/imm_rom_ext/imm_rom_ext.c
- sw/device/silicon_creator/imm_rom_ext/imm_rom_ext_epmp.c
- sw/device/silicon_creator/imm_rom_ext/imm_rom_ext_epmp.h
- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/drivers/epmp.c
- sw/device/silicon_creator/lib/drivers/epmp.h
- sw/device/silicon_creator/lib/drivers/epmp_unittest.cc
- sw/device/silicon_creator/rom_ext/rom_ext.c
The immutable ROM_EXT data segment is also covered in ROM_EXT code region due to ROM limitation,
This PR let immutable ROM_EXT reconfigure ePMP first to remove executable permission on the data segment.
We propose to use the following new ePMP layout before jumping to the mutable ROM_EXT:
```
*    0: ROM      ----- ----
*    1: ROM        TOR LX-R
*    2: ROM      NAPOT L--R
*    3: -------  ----- ----
*    4: -------  ----- ----
*    5: -------  ----- ----
*    6: IM_EXT   ----- ----
*    7: IM_EXT     TOR LX-R
*    8: MU_EXT   ----- ----
*    9: MU_EXT     TOR LX-R
*   10: VIRTUAL  NAPOT L--R
*   11: STACK      NA4 L---
*   12: RvDM     NAPOT LXWR
*   13: FLASH    NAPOT L--R
*   14: MMIO     NAPOT L-WR
*   15: RAM      NAPOT L-WR
```
MU_EXT stands for mutable part of rom_ext text …
> [imm_rom_ext] Add immutable ROM_EXT ePMP reconfiguration

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
rom_ctrl coverage report contains a hole occurred in rom_ctrl_mux.sv by a conditional statement (alert_d = sel_invalid | sel_reverted | sel_q_reverted) as 001 not covered.
This PR fixes corrupt_sig_fatal_vseq to force sel_bus_qq in rom_ctrl_mux to an invalid value to get sel_q_reverted = 1. Then to make sure that we inject something bad to sel_bus_qq before ROM check finishes, the fix adds force_early variable.
Lastly, changed the name err_point to inject_after_done for better readibility.
> [rom_ctrl, dv] Conditional coverage hole of rom_ctrl_mux

- hw/dv/sv/pwm_monitor/pwm_monitor.sv
- hw/ip/pwm/data/pwm_testplan.hjson
- hw/ip/pwm/dv/env/pwm_env.core
- hw/ip/pwm/dv/env/pwm_scoreboard.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_perf_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_phase_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_vseq_list.sv
- hw/ip/pwm/dv/pwm_sim_cfg.hjson
This PR introduces a sequence to drive the PWM outputs in a known phase relationship, with three of the signals driven at 120-degree offsets and the second group of three driven as their anti-phase counterparts using the `invert` functionality.
The above capture shows channels 0-2 being driven with phases of 0,120 and 240, and then channels 3-5 being their respective complements. It shows the point of transition from duty cycle A (1/4) to duty cycle B (3/4) and how the channels switch configuration only at the point at which it is safe to change the duty cycle, given their configured phase delays.
Note: **Only the final commit is relevant,** this is built on PR #25815.
> [dv,pwm] Phase relationship test sequence

- hw/ip/pwm/data/pwm_testplan.hjson
- hw/ip/pwm/dv/env/pwm_env.core
- hw/ip/pwm/dv/env/pwm_scoreboard.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_regwen_vseq.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_vseq_list.sv
- hw/ip/pwm/dv/pwm_sim_cfg.hjson
Introduce a test that attempts to modify the PWM configuration after the outputs have been set operating and the REGWEN bit has been cleared.
Model the REGWEN functionality in the scoreboard.
Tidy the reset handling within the scoreboard as required to support this sequence, since clearing the REGWEN shall only be achievable by a reset of the DUT. Normal shutdown via the configuration registers is not possible.
**Only the final commit is relevant to this PR,** but it is presently based on PR #25815 which should be reviewed and merged first.
> [dv,pwm] Test protection of configuration registers

- hw/ip/rv_dm/rtl/rv_dm.sv
This fixes the hierarchy path of the protected FSM registers for the RV DM LC gate
> [hw,rv_dm] Fix assertion path for FSM error trigger

- hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
The test descriptions mention internal signals that aren't exposed to Software, so, this will be covered by closed source tests in SiVal.
> [SiVal, usbdev] Mark sof test as NA for SiVal

- site/book-theme/css/chrome.css
This PR updates a couple of small properties in our custom CSS files to ensure that content is rendering properly after updating mdBook to 0.4.43, which made some changes to how mdBook is rendered.
This has been tested by locally building the site and rendering/using the sidebar visibility toggle button and the sidebar resize handle.
> [docs] Minor documentation CSS fixes for mdBook 0.4.43

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- linked to issue #24691
- where the interrupt state for fifo_empty field from the RAL against the RTL were not matching. This was the case when all the empty conditions were filled but at the same time a full is coming. It was just a matter of changing the condition order in the TB.
- fix also FIFO depth status by allowing +1 of tolerance as this is not super critical to be cycle accurate.
> [hmac,dv] Fix fifo_empty interrupt

- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
Explicitly add the unconnected ports to avoid compilation warnings.
> [hw,rv_core_ibex,rtl] Add unconnected ports of the RVFI interface

- hw/top_darjeeling/chip_darjeeling_asic.core
- hw/top_earlgrey/chip_earlgrey_asic.core
- hw/top_earlgrey/chip_earlgrey_cw310.core
- hw/top_earlgrey/chip_earlgrey_cw310_hyperdebug.core
- hw/top_earlgrey/chip_earlgrey_cw340.core
- hw/top_earlgrey/chip_earlgrey_verilator.core
- hw/top_earlgrey/top_earlgrey.core
- hw/top_englishbreakfast/chip_englishbreakfast_cw305.core
This define is superseeded by passing the PMP reset values using parameters to the core.
> [corefiles] Remove IBEX_CUSTOM_PMP_RESET_VALUES parameter

- .github/workflows/ci.yml
- ci/scripts/check-lock-files.sh
This script regenerates the Bazel, Cargo, and Python lock files and checks for a diff.
> [ci] Check lock files in CI

- SUMMARY.md
- third_party/README.md
Has a soft dependency on #25832 since it mentions the `./ci/scripts/check-lock-files.sh` script.
> [doc] Add documentation for external dependencies

- MODULE.bazel
- rules/otp.bzl
- third_party/foreign_cc/BUILD
- third_party/foreign_cc/foreign_cc.MODULE.bazel
- third_party/foreign_cc/patches/BUILD
- third_party/foreign_cc/patches/rules_foreign_cc.remove_log_output.patch
- util/design/gen-otp-img.py
- util/design/lib/OtpMemImg.py
This PR includes three commits, which, in addition to the crate updates from e7868c7c892b7ef459b1aceb90433ddbea0f53bb in #25795, should help improve the determinism of our builds and as such should improve the cache hit rate for Bazel builds, reducing build times. See more details in the commit messages.
> [bazel] Improve build determinism

- ci/scripts/check-generated.sh
Lock files are now separately checked in `check-lock-files.sh` so this is redundant.
> [ci] Remove python-requirements.txt check from check-generated.sh

- hw/top_darjeeling/templates/toplevel.sv.tpl
- hw/top_earlgrey/templates/toplevel.sv.tpl
- util/topgen.py
- util/topgen/merge.py
- util/topgen/validate.py
This PR fixes the rendering of the LPG map in the alert handler for incoming alerts. The LPG's are independent for every incoming alert group where their index is only relative within the alert group. Previously, the LPGs index offset was added after every alert, which is wrong. This only needs to be done after dealing with all alerts of one alert group and when switing to the next alert group.
> [topgen] Fix LPG Map for incoming alerts

- hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson
- hw/top_englishbreakfast/ip_autogen/rstmgr/data/rstmgr.hjson
- hw/top_englishbreakfast/ip_autogen/rstmgr/doc/interfaces.md
- hw/top_englishbreakfast/ip_autogen/rstmgr/dv/README.md
- hw/top_englishbreakfast/ip_autogen/rstmgr/dv/env/rstmgr_env_pkg.sv
- hw/top_englishbreakfast/ip_autogen/rstmgr/dv/env/rstmgr_if.sv
- hw/top_englishbreakfast/ip_autogen/rstmgr/dv/env/seq_lib/rstmgr_sw_rst_reset_race_vseq.sv
- hw/top_englishbreakfast/ip_autogen/rstmgr/rtl/rstmgr.sv
- hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv
alert_pkg changed to alert_handler_pkg after the CI run for the PR that added englishbreakfast's files.
> [englishbreakfast] Redo topgen to fix merge skew

- .bazelrc
- .github/workflows/nightly.yml
- rules/opentitan/defs.bzl
- rules/opentitan/fpga.bzl
- rules/opentitan/silicon.bzl
- rules/opentitan/sim_dv.bzl
- rules/opentitan/sim_verilator.bzl
In combination with the build determinism fixes from #25842, this PR aims to reduce CI runtime and FPGA runner utilisation by enabling the ability for FPGA and Verilator tests to be remotely cached. See the commit messages for more details on the individual changes.
Importantly, these changes will now mean that 
- FPGA/Verilator tests will run in a sandboxed environment, and 
- FPGA/Verilator tests will make use of remotely cached results where they exist, and the test previously passed, and the test itself has not changed / been rebuilt. 
Our CI bitstreams should have access to a remote cache which is written to by merge jobs, meaning that when a PR is merged, its successful FPGA/Verilator runs will be cached and can be re-used by subsequent PRs which do not modify the bitstream, testing …
> [ci,bazel] Enable remote caching of FPGA & Verilator test results

- hw/ip_templates/alert_handler/rtl/alert_handler_lpg_ctrl.sv.tpl
- hw/top_darjeeling/ip_autogen/alert_handler/rtl/alert_handler_lpg_ctrl.sv
- hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_lpg_ctrl.sv
If there is only 1 LPG, no need to read the unused one. The one LPGs is associated to all alerts.
> [hw,alert_handler,rtl] Only read unused LPGs when there are more than 1

- rules/signing.bzl
- signing/tokens/BUILD
- sw/host/sphincsplus/variants.rs
- third_party/hsm/BUILD.opensc.bazel
- third_party/hsm/repos.bzl
1. Enhance the signing rules to use the spx signing commands added to hsmtool.
2. Change the PKCS#11 provider from sc-hsm-embedded to opensc.
- sc-hsm-embedded supports RSA3072 and ECDSA P256 signatures, but does not support CKO_DATA objects.
- opensc supports ECDSA P256 signatures and CKO_DATA objects, but does not support RSA3072 signatures.
We no longer use RSA3072 signatures for signing code; we _can_ use
CKO_DATA objects to hold SPX keys for signing.
3. Use the formal NIST names for SPHINCS+ algorithms when saving or serializing keys.  Accept the older names as aliases.
- SLA-DSA-SHAKE-128s
- SLA-DSA-SHA2-128s
> [signing] Support SPX signing with `hsmtool`

- hw/ip_templates/rv_plic/rv_plic.core.tpl
- hw/ip_templates/rv_plic/rv_plic_component.core.tpl
The `module_instance_name ` was missing in some VLNVs from the latest changes.
> [hw,rv_plic,rtl] Fix uniquified instance name in VLNVs

- rules/opentitan/transform.bzl
It's not clear why sandboxing was disabled here but it seems unnecessary.
> [bazel] Disable sandboxing for disassembly actions

- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
This adds detailed log prints to each OTP write that happens during provisioning to enable easier triaging bugs.
> [manuf] add debug prints to OTP provisioning process

- hw/ip/dma/rtl/dma.sv
Feed back errors from the system port interface back to the DMA.
> [hw,dma,rtl] Feed back sysif errors back to the DMA FSM

- sw/device/tests/BUILD
Signed-off-by: Ramesh Prakash <rprakas@google.com>
Updated bazel target to include silicon tests for aes_interrupt_encryption tests
> Updated bazel target to include silicon test

- sw/host/opentitantool/src/command/rescue.rs
Add a default true flag `opentitantool rescue firmware --erase_other_slot true"` This can be used to control whether the content of the slot not being newly programmed should be left in place, or erased.  The latter ensures that the newly "rescued" firmware is the one to boot, and is the default, opposite of the previous behavior.
> [opentitantool] Rescue erases other slot by default

- sw/device/silicon_creator/lib/ownership/keys/dummy/BUILD
- sw/device/silicon_creator/lib/ownership/keys/fake/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/defs.bzl
- sw/host/opentitanlib/src/chip/rom_error.rs
- sw/host/tests/ownership/BUILD
- sw/host/tests/ownership/transfer_lib.rs
- sw/host/tests/ownership/transfer_test.rs
This is  a manual cherry-pick of #24479 to master.
The tests added by this change are all simple variations on the ownership transfer test added in #24419.  They involve verifying the different modes and error conditions (e.g. using the wrong key).
Adds the following tests:
- `bad_unlock_test`; Fixes #24466
- `bad_activate_test`; Fixes #24467
- `bad_owner_block_test`; Fixes #24468
- `bad_app_key_test`; Fixes #24469
- `transfer_endorsed_test`; Fixes #24470
- `bad_endorsee_test`; Fixes #24471
- `locked_update_test`; Fixes #24472
- `bad_locked_update_test` & `bad_locked_update_no_exec_test`; Fixes #24473
(cherry picked from commit 4d520bd7efa5399f54cafe756bcc08e58d20b23e)
> Cherry-pick to master: [rom_ext_e2e] More ownership transfer tests

- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/lib/flash_info_fields.h
- sw/device/silicon_creator/manuf/lib/individualize.c
- sw/device/silicon_creator/manuf/lib/individualize_functest.c
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/orchestrator/src/device_id.py
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/tests/BUILD
- sw/host/provisioning/orchestrator/tests/e2e.sh
- sw/host/provisioning/orchestrator/tests/e2e_multistage.sh
This fixes two bugs in the orchestrator.py script:
1. a bug in the computation and construction of the Device ID when parts are provisioned from a TestLocked* stage, i.e., if part has already previously run through CP and then runs through FT at a later stage. In this scenario, the there is no CP device ID returned to the Host (since CP stage is not run), so FT must trust what already exists in flash, and the final device ID is read out by the host over JTAG at the end of provisioning,
2. a device record was upserted into the registry database regardless if it already existed in the database, without flashing any warnings.
Additionally, this enhances the E2E testing of the orchestrator.py script catch these corner cases.
> [orchestrator] fix bugs in orchestrator.py script

- .github/workflows/ci.yml
This was using an older `ubuntu-20.04` runner. Update to using `ubuntu-22.04` as `ubuntu-20.04` will begin deprecation on 2025-02-01 and be fully deprecated by 2025-04-01.
> [ci] Bump verilator test runner to `ubuntu-22.04`

- hw/dv/sv/mem_bkdr_util/mem_bkdr_util__otp.sv
This fixes the build again (currently broken!), leaving a TODO note to make sure it gets wired up properly for other top-levels.
@Razer6 fyi. Issue #25883 tracks needing a "proper" fix.
Fix #25860
> [mem_bkdr_util] Temporarily fix build for an otp_ctrl parameter

- sw/host/hsmtool/BUILD
- sw/host/hsmtool/src/util/attribute/attr.rs
- sw/host/opentitanlib/src/transport/common/uart.rs
- sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
- sw/host/ot_certs/src/cwt.rs
- sw/host/ot_certs/src/template/subst.rs
- third_party/rust/.cargo/audit.toml
- third_party/rust/Cargo.lock
- third_party/rust/Cargo.toml
- third_party/rust/patches/cryptoki-vendor-defined-mechanism-type.patch
Most updates are compatible, some caveats:
* crytoki: patch needs updating
* indexmap: deprecation of API
* secrecy: doesn't appear to be used, so removed
* clap: version pinned due to newer 1.74 MSRV
The update removed `mach` crate so remove the entry from audit.toml. RSA crate has an advisory but we don't use the vulnerable API.
> [rust] update Rust dependencies

- hw/ip/hmac/dv/env/seq_lib/hmac_stress_reset_vseq.sv
- The stress_reset test is currently failing when a reset is happening when the Save and Restore is in a particular state. This should be removed later when the reset will be handled properly in the env.
- Increase the time before reset to let the test doing something relevant and let some checks to happen.
> [hmac,dv] Disable S&R for stress reset and increase delay before reset

- hw/ip/hmac/dv/env/seq_lib/hmac_long_msg_vseq.sv
- this test was taking too long to run and can cause a timeout, the max number or transactions has been divided by 2.
> [hmac,dv] Reduce long_msg test duration

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- Reset expected intr_test signal to 0 when a reset is triggered, as this was obviously causing the SCB comparison to fail.
> [hmac,dv] Reset intr_test signal

- hw/ip/hmac/rtl/hmac.sv
- The usage of ~fifo_wready to assess fifo_full state was leading to have `fifo_full_seen_d` set high during a reset. This fifo_full output from the block prim_fifo_sync has been added later and is the correct signal to use.
- Fortunately this is not a bug as `fifo_full_seen_d` signal is only used by `fifo_empty_gate` which is also depending on `msg_allowed`. In order to see `fifo_empty_gate` going low, we should have both `msg_allowed` and `fifo_full_seen_d` set to 1. But `fifo_full_seen_d` is going low when `msg_allowed` is going high. As `msg_allowed` is going high when `hash_start | hash_continue` is detected, but `fifo_full_seen_d` will go low when `reg_hash_start` or `reg_hash_continue` will be detected. See the screenshot to understand better.
- But using the proper signal and …
> [hmac,rtl] Use fifo_full instead of fifo_wready

- rules/rv.bzl
- sw/device/silicon_creator/lib/sigverify/sphincsplus/utils.c
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/device/silicon_creator/rom_ext/sival/BUILD
- sw/device/tests/BUILD
This change enables Oz optimization for rom_ext to reduce code size (43084B -> 41868B).
Since some targets can't be built with LLD, this commit introduces a new attribute, `with_features`, to the `opentitan_binary` rule to allow specifying additional features for the target.
LTO is also ready to be enabled for those targets, but we found no size improvement (41868B off v.s. 41896B on), so we keep it off at the moment.
> [rom_ext] Enable Oz to reduce firmware size

- hw/ip/aon_timer/data/aon_timer.hjson
- hw/ip/aon_timer/doc/registers.md
- hw/ip/aon_timer/rtl/aon_timer_core.sv
- hw/ip/aon_timer/rtl/aon_timer_reg_pkg.sv
- hw/ip/aon_timer/rtl/aon_timer_reg_top.sv
The AON timer core has an internal counter `prescale_count_q` which is not reset upon each write to wkup_ctrl.
This causes issues if the WKUP timer is re-configured to a lower prescaler value than it was before, and the `prescale_count_q` variable is greater than the new prescaler value, forcing the `prescale_count_q` counter to overflow itself causing a non-spec compliant behavior.
In order to mitigate the above, the internal `prescale_count_q` is reset after wkup_ctrl write. Thus, the aon timer is forced to count from scratch the new intended prescaler value.
Docs PR is #25904
> [rtl, aon_timer] Reset core.prescale_count on wkup_ctrl write

- hw/ip/adc_ctrl/rtl/adc_ctrl_reg_top.sv
- hw/ip/aon_timer/rtl/aon_timer_reg_top.sv
- hw/ip/pwm/rtl/pwm_reg_top.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_reg_top.sv
- hw/ip/tlul/rtl/tlul_adapter_reg.sv
- hw/ip/usbdev/rtl/usbdev_reg_top.sv
- hw/top_darjeeling/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv
- hw/top_darjeeling/ip_autogen/pinmux/rtl/pinmux_reg_top.sv
- hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv
- hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_reg_top.sv
- hw/top_englishbreakfast/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv
- hw/top_englishbreakfast/ip_autogen/pinmux/rtl/pinmux_reg_top.sv
- util/reggen/reg_top.sv.tpl
This creates a combinational path between the input and output TLUL port. This can be pretty long and impacts the synthesis in high-frequency designs.
Originally, the busy_i signal was gated with a_vali for cases where reg_tops have different clock domains. There, the busy input is a function from the request... At the moment, this causes assertions to fail, e.g., the `AReadyKnown` assertion in the PWM. This is an IP that uses 2 clock domains.
> [hw,tlul_adapter_reg,rtl] Do not gate a_ready with a_valid

- sw/device/tests/crypto/BUILD
- sw/device/tests/crypto/kdf_kmac_sideload_functest.c
- sw/device/tests/crypto/kmac_sideload_functest.c
This commit fixes the two `kmac_sideload_functest` tests that were failing due to a misconfigured key version parameter. Some ROMs set the max key version in the keymgr to 0, which causes sideloading to abort if any other version value is being programmed. Note that the proper functioning of valid/invalid keymgr version numbers is part of the `chip_sw_keymgr_derive_{sealing, attestation}` tests.
This bug has been mentioned as part of #21706.
> [kmac, sival] Keymgr-state-agnostic `kmac_sideload_functest`

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_common_vseq.sv
There was some reported assertion coverage hole for rom_ctrl. All the assertions were basically related and they haven't seen the execution of them on a particular event. They should happen when we run a rom_ctrl_sec_cm test and inject errors in rom_ctrl's adapter fifos. Based on that an alert should fire, which was true. However, when we inject anything bad to the fifos, it fails some assertions in rom_ctrl and rom_tlul_assert_device. So, instead of turning all the assertions off for rom_ctrl (in rom_ctrl_commom_vseq), we just turn the affected assertions off. This resolves the assertion hole for rom_ctrl
> [rom_ctrl, dv] Assertion coverage for rom_ctrl

- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_excl.el
- hw/ip/tlul/rtl/tlul_adapter_sram.sv
This is the value that gets supplied as a user field that provides data integrity. If we are responding with an error response, we need to make sure we send integrity bits that correspond.
The logic that was previously here detected this condition with
(vld_rd_rsp && reqfifo_rdata.error)
but that is wrong because it shouldn't depend on vld_rd_rsp. Imagine we send a TL write with a TL error. When we read the response, the d_error flag will be high (because u_reqfifo contains the faulty TL write) and d_data will be error_blanking_data. But the integrity bits will be SecdedInv3932ZeroEcc because vld_rd_rsp is false (we haven't seen a TL read at all!)
This is also possible to trigger by using only reads. Suppose we send an TL read with a TL error and then, a few cycles later, read the TL …
> [tlul,rtl] Correct the calculation of data_intg in tlul_adapter_sram

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- fifo_full_detected was going low and high without any change on the FIFO level. This was causing the SCB to generate a fifo_empty_intr when it was not expected.
> [hmac,dv] Fix SCB fifo_full_detected signal

- hw/ip_templates/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv
- hw/top_darjeeling/ip_autogen/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv
- hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv
Put back the fix in otp_ctrl_mem_bkdr_util_pkg tadded in #25884.
otp_ctrl_mem_bkdr_util_pkg needs to be a template since it depends on the partitions. Until that is done this fix will do.
> [dv,mem_bkdr_util] Temporarily fix otp_ctrl mem_bkdr functions

- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- reinitialize the Save and Restore skip context flag each time the HMAC is in reset.
> [hmac,dv] Reset S&R skip context

- hw/dv/sv/dv_utils/dv_macros.svh
- hw/ip/hmac/dv/env/hmac_env_cfg.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_smoke_vseq.sv
- This PR is a temporary fix to allow the reset to complete without waiting for complete CSR accesses. This is done by setting the flag can_reset_with_csr_accesses to 1 in the env_cfg file. Ideally, this should go away once the a better reset approach will be in place via a reset agent.
- The approach here is to try to exit ASAP from all the tasks to skip the CSR accesses.
> [hmac,dv] Allow reset w/o CSR accesses complete

- hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl_decode.sv
- hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl_pkg.sv
- hw/ip/soc_dbg_ctrl/soc_dbg_ctrl_decode.core
This PR just fixes some issues that showed up during integration:
* Add all dependencies to the decode module that is used out-of-tree
* Explicitly convert the logic from flops back to the MUBI types to avoid linting errors
* Provide a default valid CAT 3 policy used for DV
> [hw,soc_dbg_ctrl,rtl] Fix dependencies, improve type robustness, default values

- toolchain/BUILD
This change ensures optimization level flags are exclusive, resolving ambiguity caused by the previous implementation where it expects the last flag overwrote the optimization level.
Verified with `--subcommands` that Oz is the only one -O flag when building rom exts, while other tests are built with Os.
> [toolchain] Make Os and Oz mutually exclusive.

- hw/ip_templates/pwrmgr/rtl/pwrmgr.sv.tpl
- hw/top_darjeeling/ip_autogen/pwrmgr/rtl/pwrmgr.sv
... to generate the light reset request.
> [hw,pwrmgr,rtl] Make the SoC see what the slow FSM sees

- sw/host/opentitanlib/src/transport/hyperdebug/dfu.rs
This reverts commit 7a0134a9b4d5620435b9750683083662acc7d6ab, such that opentitantool no longer requires the `--force` switch in order to downgrade firmware with `opentitantool transport update-firmware`. Instead, opentitantool will be back to the original behavior of overwriting firmware in any case when the version number does not match exactly.
The original reason for not downgrading was that our branches had diverged, such that they had different firmware versions, resulting in CI machines constantly upgrading/downgrading as CI runs from different branches were scheduled.
PR #25917, however introduced a faulty HyperDebug firmware with never version number, which is now on a number of CI machines, and will not be downgraded automatically, with the result that "innocent" other PRs will …
> Revert "[opentitantool] Refuse downgrading HyperDebug firmware"

- quality/BUILD.bazel
- rules/quality.bzl
- sw/host/opentitanlib/src/image/manifest.rs
- sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs
- sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
#25912 introduced some unformatted Rust files but due to broken Bazel rules they reuse previous results from cache and did not actually check in the CI.
This PR fixes those files and also fix the Bazel rules so they're no longer cached.
> [rust] fix broken CI due to unformatted files

- hw/ip_templates/alert_handler/rtl/alert_handler.sv.tpl
- hw/top_darjeeling/ip_autogen/alert_handler/rtl/alert_handler.sv
- hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler.sv
We use a stiching tool to automatically connect ports outside of the OpenTitan bounding box. This tool relies on the fact having the full-scope struct type available in the port list rather than an already imported type. This PR adds the full-scope port type to the alert and escalation interface of the alert handler, which we also use outside of OpenTitan.
> [hw,alert_handler,rtl] Use full-scope package definition in toplevel

- sw/device/sca/aes_serial.c
- sw/device/tests/penetrationtests/firmware/sca/aes_sca.c
- sw/device/tests/penetrationtests/firmware/sca/aes_sca.h
This PR consists of three different commits:
- The first two commits tidy up the code base and prepare it for the third commit
- The third commit makes sure that we correctly (i.e., after a `dif_aes_start`()) do a reseed.
Before this commit, turning off the masks for AES gave us the following TVLA figure:
As shown in the figure, leakage is only detected in the first AES rounds. However, with masking disabled, we expect leakage in all rounds.
With these changes, the masking off now works again:
> [pentest] Fix masking off for AES-SCA

- sw/host/opentitanlib/BUILD
- sw/host/opentitanlib/src/otp/alert_handler.rs
- third_party/rust/Cargo.lock
- third_party/rust/Cargo.toml
This dependency hasn't been updated for a while, and given it's use is limited, just drop it.
This gets rid of 5 packages, and I think the readability/maintainability is not adversely affected.
> [opentitanlib] get rid of bitvec dependency

- hw/ip/prim_generic/rtl/prim_generic_otp.sv
- hw/ip_templates/otp_ctrl/rtl/otp_ctrl.sv
- hw/top_darjeeling/ip_autogen/otp_ctrl/rtl/otp_ctrl.sv
- hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl.sv
This parametrization allows the usage of prim_otp with different DFT config and response ports. One usage is for example when using macro tiling within the prim instance and have different instances with different configuration in the design. By passing the port type as a parameter we don't need to pull in all the tiling related parameters into the design.
> [hw,otp_ctrl,rtl] Parametrize the DFT config and response port

- hw/ip/tlul/rtl/tlul_adapter_sram.sv
When DataXorAddr is true, there are two fifos that hold SRAM requests (u_sramreqfifo and u_sramreqaddrfifo). These will always push and pop in sync (using the same signals in fact!).
As such, checking both wready signals is unnecessary. Drop one, avoiding an impossible conditional coverage item.
> [tlul,rtl] Avoid an unnecessary wready signal in tlul_adapter_sram

- hw/ip/pwm/dv/pwm_sim_cfg.hjson
PWM has no interrupt-related registers so drop `intr_test` because it does nothing useful.
> [dv,pwm] PWM block has no interrupts

- hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- hw/top_englishbreakfast/dv/autogen/rstmgr_tgl_excl.cfg
- hw/top_englishbreakfast/rtl/autogen/chip_englishbreakfast_cw305.sv
- hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv
- hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast_pkg.sv
- hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast_rnd_cnst_pkg.sv
- hw/top_englishbreakfast/rtl/autogen/top_racl_pkg.sv
Previously, we were still using a shorter seed and topgen/secure_prng.py kept complaining about this. We don't really care for English Breakfast as this is never going to be taped out anyway that constantly seeing the warning is kind of annoying.
Just in case someone cares: the number added now has been generated with randomness from /dev/random using the following command:
od -vAn -N32 -tuL < /dev/random
This gives a random 32-byte number in the form of 4 64-bit unsigned integers which can then be shifted and added together.
> [englishbreakfast] Switch to 256-bit seed for compile-time random consts

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_kmac_err_chk_vseq.sv
- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_stress_all_vseq.sv
There are several commits in this PR, with detailed individual commit messages. The original motivation was actually a hole in toggle coverage, but this has ended up tidying up a couple of other items
> [rom_ctrl,dv] Stress sequence tidyup

- doc/getting_started/README.md
- sw/device/silicon_creator/rom/doc/e2e_tests.md
- util/container/Dockerfile
- util/container/README.md
Getting this fixed so people don't have new Ubuntu 20.04 installations anymore.
We'll need to deprecate the support of Ubuntu 20.04 before it goes EOL this April.
> [doc,docker] update util/container to Ubuntu 22.04 and stop mentioning 20.04

- .bazelrc
- .github/actions/prepare-env/action.yml
- rules/fusesoc.bzl
- rules/nonhermetic.bzl
- rules/opentitan/splice.bzl
- signing/tokens/BUILD
* `HOME` is no longer used (except by hsmtool to find Google Cloud credentials)
* `XILINX_HLS` environment variable is removed (we don't use HLS anyway)
* Only relevant part of `PATH` is used, not the full path (this allows us to remove the CI hack)
* `updatemem` is now sandboxed
> [bazel,hw] improve hermeticity of bitstream builds

- sw/device/silicon_creator/manuf/base/BUILD
This enables building the individualization binaries for the sim_dv exec_env to stand up ATE test flows.
> [manuf] build individualization binaries for sim_dv

- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
This ensures all OTP consistency and integrity checks are disabled during FT individualization.
> [manuf] disable OTP checks during FT individualize

- hw/ip_templates/clkmgr/data/clkmgr.tpldesc.hjson
- hw/ip_templates/flash_ctrl/data/flash_ctrl.tpldesc.hjson
- hw/ip_templates/otp_ctrl/data/otp_ctrl.tpldesc.hjson
- hw/ip_templates/pinmux/data/pinmux.tpldesc.hjson
- hw/ip_templates/pwrmgr/data/pwrmgr.tpldesc.hjson
- hw/ip_templates/rstmgr/data/rstmgr.tpldesc.hjson
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/ip_autogen/rv_plic/data/top_darjeeling_rv_plic.ipconfig.hjson
- hw/top_darjeeling/templates/toplevel.sv.tpl
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip_autogen/rv_plic/data/top_earlgrey_rv_plic.ipconfig.hjson
- hw/top_earlgrey/templates/toplevel.sv.tpl
- hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- hw/top_englishbreakfast/ip_autogen/rv_plic/data/top_englishbreakfast_rv_plic.ipconfig.hjson
- util/topgen.py
- util/topgen/lib.py
- util/topgen/validate.py
This PR adds basic support to render and instantiate uniquified IPs from ipgen. The change is done in the following way:
1. It is assumed that all ipgen IP templates support the `module_instance_name` parameter. This is not true for all IPs there. Though this parameter was added to all `*.tpldesc` files, even it is not used.
2. In topgen, when you instantiate an ipgen'ed (`attr: "ipen"`), you specify three different fields:
1. `template_type`: This is the basic template type that is used to render the IP from.
2. `type`: This is the uniquified type.
3. `name`: This is the actual instance name used in the top-level SystemVerilog file.
Let's make an example: To render a uniquified `rv_plic` you would set the following parameters in the HJSON:
```hjson
{
template_type: "rv_plic"
type: …
```
> [topgen] Add support for instantiating uniquified ipgen IPs

- util/topgen/lib.py
Otherwise, we would end up in conflicts when adding incoming alerts from other domains, which have the same module and alert name.
> [topgen] Properly uniquify the incoming alert names

- hw/ip_templates/rstmgr/data/rstmgr.tpldesc.hjson
- util/topgen.py
- util/topgen/lib.py
This PR is a follow-up from https://github.com/lowRISC/opentitan/pull/25966 and post-merge fixes 2 review comments:
1. Properly use the rstmgr default in their module instance name template
2. Merge `find_module` and `find_module_by_type` by adding a new parameter `use_base_template_type`
> [topgen] Uniquification folllow-up

- hw/ip_templates/ac_range_check/ac_range_check.core.tpl
- hw/ip_templates/ac_range_check/data/ac_range_check.hjson.tpl
- hw/ip_templates/ac_range_check/data/ac_range_check.tpldesc.hjson
- hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl
- util/topgen.py
This PR adds RACL checks to the AC ranges. Now that RACL is (partly) merged, we can enable the RACL checks first.
RACL error logging is not yet fully implemented as it depends on determining the failing range.
> [hw,ac_range_check,rtl] Add RACL checks to the AC Range Checks

- hw/ip_templates/clkmgr/data/clkmgr.hjson.tpl
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/dv/autogen/tb__xbar_connect.sv
- hw/top_darjeeling/ip_autogen/clkmgr/data/clkmgr.hjson
- hw/top_darjeeling/ip_autogen/clkmgr/data/top_darjeeling_clkmgr.ipconfig.hjson
- hw/top_darjeeling/ip_autogen/clkmgr/doc/registers.md
- hw/top_darjeeling/ip_autogen/clkmgr/rtl/clkmgr.sv
- hw/top_darjeeling/ip_autogen/clkmgr/rtl/clkmgr_reg_pkg.sv
- hw/top_darjeeling/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv
This PR changes the Darjeeling clocks to:
* main: 1 GHz
* IO: 1 GHz
* USB (Not used): 1 GHz
* AON: 62.5 MHz
From IO, `clkmgr` derives a 500 MHz and 250 MHz Clock.
The `clkmgr` needed a tweak in the template. To measure the clock frequency, the clkmgr has some measurement circuitry. These regs are preloaded with defaults to (freq / f_aon) +- 10. For the 250 MHz IO_DIV4 clock, this ratio becomes 4 - 10, which is negative. This change ensures the lower value is clipped at 0.
> [Darjeeling] Configure Darjeeling clocks

- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_excl.el
Merge this PR first as a dependency of [25869](https://github.com/lowRISC/opentitan/pull/25869)
> [rom_ctrl, dv] Exclusion of a case where sramreqfifo_wready is false

- rules/opentitan.bzl
- sw/device/silicon_creator/rom/sigverify_otp_keys.c
Make the DEV key valid in TEST and RMA. Because of the limited number of key slots in OTP, we allow the DEV key to be valid in DEV, TEST and RMA. This will allow a single set of keys (e.g. 3xPROD + 1xDEV) to be viable for devices provisioned to PROD and DEV mission mode states while still allowing the use of the DEV key for TEST and RMA states.
> [rom] Make the DEV key valid in TEST and RMA

- sw/device/silicon_creator/rom/BUILD
- sw/device/silicon_creator/rom/keys/fake/spx/BUILD
- sw/device/silicon_creator/rom/rom.c
The hmac peripheral produces the SHA256 hash in reversed byte order. We need to byte-reverse the hash to put it into natural byte order before passing it to the `spx_verify` function.
> [rom] Correct the hash order for SPX verify

- sw/device/silicon_creator/lib/drivers/otp.c
- sw/device/silicon_creator/lib/drivers/otp.h
- sw/device/silicon_creator/rom/e2e/keymgr/BUILD
- sw/device/silicon_creator/rom/e2e/keymgr/rom_e2e_keymgr_init_test.c
- sw/device/silicon_creator/rom/rom.c
This fixes a bug in the ROM that computes OTP measurements to populate the keymgr attestation binding CSRs, if the OTP fuse (`OWNER_SW_CFG_ROM_KEYMGR_OTP_MEAS_EN`) to request this is set. Additionally, this fixes the corresponding ROM E2E test as well, and enhances its robustness.
> [rom] fix bug in ROM that computes OTP measurements

- sw/device/lib/testing/otp_ctrl_testutils.c
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/sku_config.py
- sw/host/provisioning/orchestrator/tests/BUILD
- sw/host/provisioning/orchestrator/tests/e2e.sh
- sw/host/provisioning/orchestrator/tests/e2e_option_flags.sh
This PR contains several orchestrator.py script and provisioning enhancements, including:
1. enabling the overriding of the package ID via the orchestrator.py CLI,
2. removal of duplicate test behavior; specifically, the "enable-alerts" and "use-ext-clk" flags of the orchestrator.py script we being tested in several E2E tests instead of just one,
3. the multistage orchestrator.py E2E test was re-enabled, and
4. the OTP programming timeout was increased to 10ms
> [manuf] several orchestrator and provisioning enhancements

- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_excl.el
- hw/ip/tlul/rtl/tlul_adapter_sram.sv
** The assertion in tlul_adapter_sram was missing a _A suffix.
** The exclusion for some conditions in rom_ctrl_cov_excl.el
didn't work as after some RTL changes their condition
numbers got changed.
> [rom_ctrl, cleanups] Minor convention changes

- hw/ip/tlul/rtl/tlul_adapter_sram.sv
Having two FIFOs with pointers that are kept in lock-step is a little silly. Turn them into a single wider FIFO.
Note that the two FIFOs had compatible parameters. The address FIFO had OutputZeroIfEmpty set to 1, which is the default value (so u_sramreqfifo got it too). Request it explicitly in case the default changes in future.
> [tlul,rtl] Merge u_sramreqfifo and u_sramreqaddrfifo

- hw/dv/sv/mem_bkdr_util/mem_bkdr_util.sv
This PR adds optional tiling support for the memory backdoor utility. Previous, untiled access is still supported.
> [membkdr] Add RAM tiling to membkdr utility

- hw/ip/tlul/rtl/tlul_adapter_sram.sv
This seemed sensible when I originally ported the code to use the shared fifo, but it turns out not to be needed. And Pirmin (quite reasonably) pointed out that the name is rather confusing. Forget about it!
(I mis-clicked when merging #25951. This PR tidies up again...)
> [tlul,rtl] Drop unused typedef from tlul_adapter_sram

- hw/ip/i2c/rtl/i2c.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
- hw/ip/mbx/rtl/mbx.sv
- hw/ip/pwm/rtl/pwm.sv
- hw/ip/pwm/rtl/pwm_reg_top.sv
- hw/ip/spi_host/rtl/spi_host.sv
- hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv
- hw/ip/uart/rtl/uart.sv
- hw/ip/uart/rtl/uart_reg_top.sv
- hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl
- hw/ip_templates/alert_handler/rtl/alert_handler.sv.tpl
- hw/ip_templates/racl_ctrl/rtl/racl_ctrl.sv.tpl
- hw/ip_templates/rv_plic/rtl/rv_plic.sv.tpl
- hw/top_darjeeling/ip/soc_proxy/rtl/soc_proxy.sv
- util/reggen/reg_top.sv.tpl
This adds ASSERT_KNOWN assertions to many outputs of the newly introduced signals.
It also uncovered a bug. The RACL error may be `'x` because the internal address hit depends on the incoming TLUL address, which might be `'x` at some cases. To fix this, the `a_valid` signal is factored in to the RACL error computation.
> [assert] Add ASSERT_KNOWN asserts to multiple new outputs

- hw/ip/hmac/rtl/hmac_core.sv
- hw/ip/prim/rtl/prim_sha2.sv
- hw/ip/prim/rtl/prim_sha2_pad.sv
In light of the V3 signoff, this commits adapts certain RTL parts that induced uncoverable coverage holes. There are two types of changes:
1. Removal of dangling else branches that are impossible to cover.
2. Removal of uncoverable FSM default state assignments.
Both changes have no functional impact and are only cosmetic in nature in order to attain the demanded coverage thresholds. See #24692, for a detailed discussion of these changes.
> [hmac, rtl] Increase coverage through minor RTL restructure

- hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
Confusingly, the default priority (-1) seems to mostly work. Unfortunately, this *doesn't* work properly with the rom_ctrl_stress_all_with_rand_reset sequence for some seeds for particular iterations of the stressed sequence.
In this situation, we end up with an item from a call to mirror() from the end of one iteration racing against some other register item from the start of the next one. Because there is more than once item, the sequencer tries to decide which one to grant... and explodes because they have a negative priority.
The error message is rather confusing:
UVM_FATAL @ 2122662017 ps: uvm_test_top.env.m_tl_agent_rom_ctrl_regs_reg_block.sequencer [SEQDEFPRI] Sequence m_tl_host_base_seq has illegal priority: -1
and the point is that if a sequence item has a priority of -1, this …
> [rom_ctrl,dv] Pass the .prior argument for some mirror calls

- sw/device/silicon_creator/rom_ext/defs.bzl
Update the ROM_EXT minor version to `102`.  I'm using the offset 100 as a starting point to distinguish A1 development ROM_EXTs from ES development ROM_EXTs.
> [rom_ext] Update the ROM_EXT minor version

- hw/ip/csrng/README.md
Previously, this section:
- was referring to a derivation function which our implementation doesn't use,
- mentioned and undefined CSRNG_MAX_GENERATE constant,
- mentioned the support of a prediction resistance flag for generate calls (only relevant for instantiate and reseed commands)
- mentioned the update routine only in the context of generate commands (it's used by any single command call and can be called explicitly).
> [csrng/doc] Clarify description section of README.md

- rules/const.bzl
- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/BUILD
- sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/immutable_rom_ext_section_test.c
- sw/device/silicon_creator/rom/rom.c
1. Add tests that check if a valid signed ROM_EXT with an invalid immutable section can boot.  The correct behavior is that the ROM should determine that the immutable section is invalid and try the other slot.
2. Refactor immutable section verification into a separate function.
3. When booting, examine the immutable section and fail the boot with an error if the immutable section is invalid.  If the failure occurs in the primary slot, the ROM should attempt to boot the secondary slot.
> [rom] Examine the immutable section and skip if invalid 

- hw/ip/prim/lint/prim_ram_1r1w.waiver
- hw/ip/prim/lint/prim_ram_1r1w_async_adv.waiver
- hw/ip/prim/prim_ram_1r1w_async_adv.core
- hw/ip/prim_generic/lint/prim_generic_ram_1r1w.waiver
- hw/ip/spi_device/lint/spi_device.waiver
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/lint/top_darjeeling.waiver
- hw/top_darjeeling/lint/top_darjeeling_lint_cfgs.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_darjeeling/templates/toplevel.sv.tpl
This PR waives some expected lint errors.
> [Darjeeling] Lint fixes to top-level 

- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
- sw/device/silicon_creator/manuf/lib/BUILD
- sw/device/silicon_creator/manuf/tests/BUILD
- sw/device/tests/BUILD
- sw/host/provisioning/orchestrator/configs/skus/emulation.hjson
- sw/host/provisioning/orchestrator/configs/skus/emulation_dice_cwt.hjson
- sw/host/provisioning/orchestrator/configs/skus/emulation_tpm.hjson
- sw/host/provisioning/orchestrator/configs/skus/sival.hjson
- sw/host/provisioning/orchestrator/src/device_id.py
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/sku_config.py
- sw/host/provisioning/orchestrator/tests/device_id_test.py
- sw/host/provisioning/orchestrator/tests/e2e.sh
- sw/host/provisioning/orchestrator/tests/e2e_multistage.sh
- sw/host/provisioning/orchestrator/tests/e2e_option_flags.sh
This updates the SKU specific portion of the device ID to add the following subfields:
1. AST config version
2. OTP ID
3. OTP version
4. SKU specific version
> [orchestrator] refactor SKU specific portion of device ID

- ci/fpga-job.yml
- ci/verify-fpga-jobs.yml
These renanble the ROM E2E tests on the `earlgrey_1.0.0` branch (thus reverting #25302), to prepare for a ROM release.
> [ci] re-enable ROM E2E tests on `earlgrey_1.0.0`

- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/data/top_darjeeling.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
Downstream, the DFT signals for both ROM ctrls are different. Let's add separate top-level inputs for that and let the AST connect to both in the uncore environment.
> [hw,darjeeling,rtl] Separate ROM ctrl cfg inputs

- hw/ip/prim/rtl/prim_subreg_shadow.sv
Shadowed subregs lacked support for Multibit values. This PR feeds the multibit parameter down to all prims that are used within this one. 
The reason why this is needed now is that `soc_dbg_ctrl` uses shadowed mubi registers.
> [hw,prim_subreg_shadow,rtl] Add Mubi Support to prim_subreg_shadow

- hw/ip_templates/clkmgr/rtl/clkmgr.sv.tpl
- hw/top_darjeeling/ip_autogen/clkmgr/rtl/clkmgr.sv
- hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr.sv
- hw/top_englishbreakfast/ip_autogen/clkmgr/rtl/clkmgr.sv
Darjeeling has different clock ratios. This causes the registers to have a different size than the counter of the measurement circuit. That happens because the threshold value is exactly a power of two, which requires one bit more.
Change the width of the counter do be able to hold the maximum value.
> [hw,clkmgr,rtl] Properly size the measurement counter

- hw/ip/tlul/adapter_reg_racl.core
- hw/ip/tlul/adapter_sram_racl.core
- hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv
- hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv
- hw/ip/tlul/rtl/tlul_request_loopback.sv
This PR adds a RACL protected SRAM adapter. This works by acting like a shim around the existing TLUL SRAM adapter. In case of a RACL error, the error is responded via the TLUL loopback adapter. Currently, only a single RACL policy is supported, but this will be extended in the future.
This RACL protected SRAM adapter will be used in SPI host and device as well as in the SRAM Control.
The same approach is implemented for the Reg adapter. This circumvents dealing with any flop latencies in the adapter explicitly, since RACL is check for the TLUL request goes into the TLUL adapter.
> [hw,tlul_adapter_sram,rtl] Add support for RACL protected SRAM Adapter

- sw/device/lib/testing/test_rom/test_rom_start.S
- sw/device/silicon_creator/rom/rom_start.S
The ROM e2e plan captures the expected behavior of the clock jitter enable flow:
> `CREATOR_SW_CFG_JITTER_EN`: `kMultiBitBool4False` disables, all other values
>  enables. `CREATOR_SW_CFG_AST_INIT_EN` must also be `kMultiBitBool4True` to enable.
This change refactors the code in `rom_start.S` and `test_rom_start.S` to explicitly reduce any value different than MubiFalse to MubiTrue. The implementation relies on the register to be reset to MubiFalse by default.
> [rom] Update clkmgr jitter enable to match ROM specification.

- sw/host/provisioning/orchestrator/src/device_id.py
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
Confirmation requirement should only be required when the `--non-interactive` mode CLI arg is NOT passed. This updates the script behavior to disble the confirmation requirement when said flag is passed and a host/device device ID mismatch occurs, which typically happens on parts that have had CP run, and later FT run, as opposed to running both stages back to back.
Additionally, this updates the DIN of blind assembly parts to all FF to provide a DIN for parts for which wafer information is missing.
> [orchestrator] fix confirmation requirement bug and enable classifying blind assembly parts

- sw/device/lib/testing/otp_ctrl_testutils.c
- sw/device/lib/testing/otp_ctrl_testutils.h
- sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
This adds weak hook functions to OTP sub operations to enable tests, and provisioning firmware, to insert debug functionality before and after functions.
> [manuf] add weak OTP operations hooks

- .bazelrc
It still refered to the old 'crt' repository instead of pointing to the new toolchain.
> [bazelrc] Fix 'riscv32' config

- util/topgen/templates/toplevel_racl_pkg.sv.tpl
This commit adds the racl roles as paramters to the top_racl_pkg.
These will be used later in a follow-up PR.
Example output:
```
/**
* RACL Roles
*/
parameter role_t RACL_ROLE_ROT   = 4'h0;
parameter role_t RACL_ROLE_ROLE1 = 4'h1;
parameter role_t RACL_ROLE_SOC   = 4'h2;
```
> [RACL] Render RACL Roles in top_racl_pkg

- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block.h
- sw/device/silicon_creator/lib/ownership/owner_block_unittest.cc
- sw/device/silicon_creator/lib/ownership/ownership.c
- sw/device/silicon_creator/lib/ownership/ownership.h
- sw/device/silicon_creator/lib/ownership/ownership_activate.c
- sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD
- sw/device/silicon_creator/rom_ext/e2e/ownership/flash_regions.c
- sw/device/silicon_creator/rom_ext/rom_ext.c
- sw/device/tests/flash_ctrl_idle_low_power_test.c
- sw/device/tests/flash_ctrl_write_clear_test.c
- sw/device/tests/rv_core_ibex_mem_test.c
- sw/host/tests/ownership/flash_permission_test.rs
- sw/host/tests/ownership/transfer_lib.rs
Ownership flash lockdown was protecting and locking all regions in the same slot that booted the owner code.  However, the ROM_EXT and owner code don't have to boot from the same side of the flash.
1. Disallow ownership configurations that have flash regions that overlap with the ROM_EXT region.  It is an error to upload such a configuration, but if one already exists in the chip, the owner-specified ROM_EXT regions are ignored in favor of the self-protection.
2. Always protect the ROM_EXT by using flash regions 0 and 1.
3. Update the tests.
This is a cherry-pick & rewrite of #25892 for earlgrey_a1.
Fixes #25435.
> [rom_ext] Make the ROM_EXT protect itself in flash

- sw/host/opentitantool/src/command/rescue.rs
I believe I have seen cases where the slot not being flashed during rescue still booted afterwards, meaning that the previous code flashing a zero-length image to the other slot may be ineffective.  This PR changes the default behavior to flashing an 4kB image consisting entirely of 0xFF to the other slot, in order to make sure that the header of any previous image is overwritten and invalidated.
> [opentitantool] Erase header of other slot during rescue

- .github/workflows/ci.yml
This is a manual cherry-pick of #26012.
> [ci] Rename the ROM_EXT hyper310 workflow

- sw/device/silicon_creator/lib/otbn_boot_services.h
This removes a duplicate function prototype for the `otbn_boot_attestation_keygen()` that is unneeded.
> [silicon_creator] remove duplicate function prototype

- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
- sw/device/silicon_creator/manuf/lib/individualize.c
Some configuration settings are only toggled on specific platforms during individualization. This ensures SimDv and Silicon platforms are treated the same.
> [manuf] treat SimDv and Silicon platforms the same

- sw/device/tests/crypto/cryptotest/cryptotest.bzl
This allows the Bazel hook infrastructure to support additional silicon SKUs.
> [sival] Use `EARLGREY_SILICON_OWNER_ROM_EXT_ENVS` in cryptotests.

- hw/ip_templates/clkmgr/data/clkmgr.hjson.tpl
- hw/ip_templates/clkmgr/doc/registers.md.tpl
- hw/ip_templates/clkmgr/dv/env/clkmgr_scoreboard.sv
- hw/ip_templates/clkmgr/dv/env/seq_lib/clkmgr_smoke_vseq.sv
- hw/top_earlgrey/ip_autogen/clkmgr/data/clkmgr.hjson
- hw/top_earlgrey/ip_autogen/clkmgr/doc/registers.md
- hw/top_earlgrey/ip_autogen/clkmgr/dv/env/clkmgr_scoreboard.sv
- hw/top_earlgrey/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_smoke_vseq.sv
- hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv
- sw/device/lib/dif/dif_clkmgr.c
- sw/device/lib/dif/dif_clkmgr.h
- sw/device/lib/dif/dif_clkmgr_unittest.cc
- util/reggen/fpv_csr.sv.tpl
- util/reggen/reg_top.sv.tpl
This PR aligns RTL, block-level DV, DIF and doc to the modified behavior of the jitter_enable CSR. The corresponding ROM change is #26027.
> [clkmgr] Align behavior of jitter_enable CSR

- hw/ip/prim/rtl/prim_reg_cdc_arb.sv
`end else if (dst_req_i && !dst_req_q && busy) begin` is equivalent to
`end else if (dst_req_i && busy) begin`.
In order to guarantee the above happens an assertion has been added checking:
`dst_req_i |-> !dst_req_q`
The reasoning for the simplification is:
In prim_reg_cdc, we expect to see a request that comes from the SW
as a signal on the src domain (either src_we_i or src_re_i).
This gets synchronised to the destination clock by
u_src_to_dst_req.
This then appears to the arbiter as dst_req_i.
If there is another request in flight (probably an update from HW),
the SW request get stored in the dst_req_q register.
The stored request gets cleared on the first posedge of the dst
clock after the previous request is complete, because it causes
dst_lat_d to be high.
To see dst_req_i && …
> [rtl, prim_reg_cdc_arb] Conditional coverage simplification

- hw/top_darjeeling/lint/top_darjeeling_lint_cfgs.hjson
Some IPs changed.  Update the Lint config
> [darjeeling,lint] Fix lint config for Darjeeling

- sw/device/silicon_creator/manuf/lib/sram_start.S
This changes solves an issue that caused larger programs to return the following linker error:
```
relocation truncated to fit: R_RISCV_GPREL_I against symbol `_stack_end' defined in .sram_start
```
Using the `norelax` option avoids the use of compressed instructions which was causing the `_stack_end` address calculation error.
Patch submitted by cfrantz@google.com.
> [sram-exec] Avoid using compressed instructions when loading sp.

- rules/bitstreams.bzl
- rules/scripts/bitstreams_workspace.py
- rules/scripts/bitstreams_workspace_test.py
- util/prep-bazel-airgapped-build.sh
Bitstream schemas can change on the main branch so we want to fetch the earlgrey_1.0.0 bitstreams in particular.
> [bazel,airgapped] fetch earlgrey_1.0.0 bitstreams

- sw/device/tests/crypto/BUILD
Update crypto functional tests to use the `CRYPTO_EXEC_ENVS` map of execution environments to enable support for external SKUs.
> [sival] Update crypto test exe_envs

- hw/ip/keymgr/rtl/keymgr_kmac_if.sv
- hw/ip/keymgr_dpe/dv/env/keymgr_dpe_if.sv
- hw/ip/keymgr_dpe/dv/env/keymgr_dpe_scoreboard.sv
- hw/ip/keymgr_dpe/rtl/keymgr_dpe.sv
- hw/ip/keymgr_dpe/rtl/keymgr_dpe_pkg.sv
This PR fixes the bug reported in #25994. It consists of three commits the first two being
preparatory bug fixes:
1. The `keymgr_dpe` DV was not compiling due to a spurious artifact.
2. All DV tests were failing because of wrongly ordered DPE policy bits.
3. The actual bugfix for #25994.
> [keymgr, keymgr_dpe, rtl] keymgr_dpe correct KMAC input

- hw/ip/i2c/rtl/i2c.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
- hw/ip/mbx/rtl/mbx.sv
- hw/ip/mbx/rtl/mbx_soc_reg_top.sv
- hw/ip/pwm/rtl/pwm.sv
- hw/ip/pwm/rtl/pwm_reg_top.sv
- hw/ip/spi_host/rtl/spi_host.sv
- hw/ip/spi_host/rtl/spi_host_reg_top.sv
- hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv
- hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv
- hw/ip/uart/rtl/uart.sv
- hw/ip/uart/rtl/uart_reg_top.sv
- hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl
- hw/ip_templates/alert_handler/rtl/alert_handler.sv.tpl
- hw/ip_templates/rv_plic/rtl/rv_plic.sv.tpl
- util/reggen/reg_top.sv.tpl
This PR is a follow up to the review in https://github.com/lowRISC/opentitan/pull/26004#pullrequestreview-2579395912:
It adds:
1. Proper qualification of the read and write request with the necessary TLUL signals for the reg and sram adapter
2. Properly qualify the error log computation in the reg_top with the access control signal coming from the reg_adapter.
> [racl] Follow-up fixes to TLUL adapter and reg_top

- hw/ip/rv_core_ibex/data/rv_core_ibex.hjson
- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/ip/rv_dm/data/rv_dm.hjson
- hw/ip/rv_dm/rtl/rv_dm.sv
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson
- hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv
RACL uses the TLUL user bits to inject the role and CTN UID. To make these bits generically configurable, we need to expose them to the top-level interface. There, if RACL is used, they can be assigned to the right RACL roles. 
In this PR, we expose the user bits of the Ibex and RV DM host.
> [racl] Expose TLUL User bits to the top-level

- hw/ip/prim/rtl/prim_reg_cdc_arb.sv
Removing unused upper bit of state_q/d signals
> [dd, prim_reg_cdc_arb] state signal width reduction

- sw/device/silicon_creator/lib/drivers/flash_ctrl.c
- sw/device/silicon_creator/lib/drivers/flash_ctrl.h
- sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/owner_block.c
The hardening in the function `flash_ctrl_data_region_protect` resulted in 1304 bytes of RV32 machine code.  This relaxed version results in 250 bytes of RV32 machine code.
> [flash_ctrl] Relax the hardening in `flash_ctrl_data_region_protect`

- hw/ip/aon_timer/rtl/aon_timer.sv
The condition originally looked like:
```
assign intr_test_qe           = reg2hw.intr_test.wkup_timer_expired.qe |
reg2hw.intr_test.wdog_timer_bark
```
Which causes a conditional coverage hole due to both Qe signals being connected to the same signal in aon_timer_reg_top. In order to avoid waving the hole, the RTL has been ammended, and an assertion has been added to ensure things work as expected in case the RTL (register top) changes in the future
> [rtl, aon_timer] Simpler condition to aid coverage closure

- hw/ip_templates/pinmux/data/pinmux.hjson.tpl
- hw/ip_templates/pinmux/rtl/pinmux.sv.tpl
- hw/top_darjeeling/ip_autogen/pinmux/data/pinmux.hjson
- hw/top_darjeeling/ip_autogen/pinmux/doc/registers.md
- hw/top_darjeeling/ip_autogen/pinmux/rtl/pinmux.sv
- hw/top_darjeeling/ip_autogen/pinmux/rtl/pinmux_reg_pkg.sv
- hw/top_darjeeling/ip_autogen/pinmux/rtl/pinmux_reg_top.sv
Depending on the pin config of the pinmux, some signals of the MUX might be unused (It is aligned to the largest DIO size). Read the unused signals to avoid linting errors.
> [hw,pinmux,lint] Read unused signals to avoid lint errors

- sw/host/opentitanlib/src/crypto/ecdsa.rs
When processing ECDSA signatures consider the input file to be either a raw signature, with 32 bytes R and S values in little endian format concatenated into a single 64 bytes blob, or an ASN.1 encoded ECDSA signature, which is a sequence of two big endian big number values, which could be anywhere from one to 33 bytes long.
In case input is in ASN .1 format Convert the values into little endian and truncate/expand as necessary to generated the internal representation of R and S of exactly 32 bytes each.
Tested by attaching the Crypto4a HSM produced ECDSA signature to an owner binary image and verifying the signature, both using opentitantool.
> opentitanlib: accept ECDSA signatures as ASN.1 blobs

- hw/ip_templates/clkmgr/dv/env/seq_lib/clkmgr_regwen_vseq.sv
- hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
- hw/top_earlgrey/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_regwen_vseq.sv
- sw/device/lib/dif/dif_clkmgr.c
- sw/device/lib/dif/dif_clkmgr.h
- sw/device/lib/dif/dif_clkmgr_unittest.cc
- sw/device/tests/BUILD
- sw/device/tests/clkmgr_jitter_frequency_test.c
- sw/device/tests/clkmgr_jitter_test.c
- sw/device/tests/flash_ctrl_clock_freqs_test.c
- sw/device/tests/sim_dv/ast_clk_rst_inputs.c
Fix clkmgr jitter enable tests to match the change that any write to jitter enable will set it to mubi-true.
> [tests,clkmgr_jitter] Fix jitter tests to track RTL changes

- sw/host/tests/chip/pwm_smoketest/src/main.rs
Make the host to wait for the ottf to print the "running" message before start the test.
> [pwm] Fix flakiness on smoketest

- hw/ip/gpio/data/gpio.hjson
- hw/ip/gpio/doc/interfaces.md
- hw/ip/gpio/rtl/gpio.sv
- hw/ip/gpio/rtl/gpio_reg_top.sv
- hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
- hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson
- hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv
This PR adds RACL support to the GPIO IP, similar to other IPs.
> [hw,gpio,rtl] Add support for RACL

- hw/ip/aon_timer/rtl/aon_timer.sv
This was suggested by @vogelpi in the discussion of PR #25811 and I accidentally merged that change (as 8d05977) before the lint fix got added.
Put it in late...
> [aon_timer,rtl,lint] Add an unused_ signal to avoid a lint error

- hw/ip_templates/racl_ctrl/doc/interfaces.md.tpl
- hw/ip_templates/racl_ctrl/doc/registers.md.tpl
Use the uniquified path when generating the register and interface description.
> [hw,racl_ctrl,doc] Uniquify hjson path when calling regtool

- hw/ip/prim/rtl/prim_reg_cdc_arb.sv
The acknoledgement can't be set unless the request is set. The condition has been simplified to only check for the acknoledgment.
In addition, the new assertion checks if the ack is set, the request must be set
> [dd, prim] Simplyfing condition to ease coverage closure

- hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
- sw/device/tests/BUILD
- sw/device/tests/hmac_error_conditions_test.c
Signed-off-by: Ramesh Prakash <rprakas@google.com>
Add HMAC error condition test as per chip_hmac_testplan.hjson
> [sival/hmac] Add Hmac error conditions Test

- hw/top_earlgrey/data/otp/sival_skus/BUILD
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/sival/BUILD
See #26060 for the rationale and plan for re-enabling SPX signatures.
> [rom_ext, sival] Temporarily disable SPX signing of ROM_EXT

- MODULE.bazel.lock
- third_party/hyperdebug/extensions.bzl
Support 48Mhz clock generation, and bugfixes
Add ability to change HyperDebug core clock frequency.  Choosing 96 MHz will allow any PWM capable pin to produce a 48 MHz clock suitable for driving a NuvoTitan chip.  (CN10.31 is the only pin that can output 96 MHz.)
Also included are a few bugfixes to HyperDebug polling the "GSC ready" signal when passing through TPM operations.
Relevant CLs:
d090a07063 chip/stm32: Avoid stuck UART to USB forwarding
b3c959b5c5 board/hyperdebug: Avoid clobbering CCR_CFGR register
765b8a9d2b chip/stm32: Wait for core voltage to stabilize on STM32L4/5
6e9f274d2c board/hyperdebug: Improve GSC ready pulse detection
843d7ee9a6 board/hyperdebug: Expect GSC ready pulse after transaction
1b9f351528 board/hyperdebug: Properly set system timer tick rate
3962928140 …
> [opentitantool] Ship updated firmware for HyperDebug

- WORKSPACE
- ci/scripts/test-airgapped-build.sh
- hw/dv/tools/dvsim/sim.mk
- pyproject.toml
- python-requirements.txt
- third_party/google/no-hash-python-packages.patch
- third_party/google/repos.bzl
- third_party/python/airgapped-wheels-cache.patch
- third_party/python/pip.bzl
- third_party/python/repos.bzl
- third_party/python/requirements.bzl
- util/prep-bazel-airgapped-build.sh
This re-adds the ability to generate an external Bazel repository that contains all Python wheels for used as dependencies for this project. This capability was originally added to workaround a rules_python shortcoming that prevented Python wheels from being downloaded and cached through the bazel third party dependency caching mechanism (specifically, the repository cache). This issue caused airgapped builds to fail. This issue was believed to solved in newer versions of rules_python, so this wheel caching mechanism we removed in #24361.
However, after further testing, we found that newer rules_python version suffer the same issue, i.e., the default to downloading Python wheels through Python, rather than the bazel download/caching mechanism, as shown here: …
> [bazel,python] re-enable building of airgapped python wheels repo

- sw/device/lib/ujson/ujson.c
- sw/device/lib/ujson/ujson_test.cc
- sw/device/silicon_creator/lib/cert/dice.c
- sw/device/silicon_creator/manuf/base/perso_tlv_data.c
This PR has three commits that:
1. Fixes a potential integer overflow in `ujson_parse_integer` by using an unsigned integer for parsing and adding a check before converting back to a signed integer.
2. Adds buffer size checks in `perso_tlv_data.c` to prevent potential memory corruption vulnerabilities.
3. Removes the unused cert_size output parameter in `dice_cert_check_valid`
> [ujson,perso_tlv,dice] Fix potential signed integer flow, and add buffer checks

- hw/ip/tlul/rtl/tlul_request_loopback.sv
Explicitly cast the output of a flop to the actual type to avoid liniting errors.
> [hw,tlul_loopback,lint] Explicitly typecast for flopped opcode

- sw/host/sphincsplus/BUILD
- sw/host/sphincsplus/key.rs
Some HSMs distribute SPX pub keys as PEM encoded ANS.1 objects. The approach so far has been to manually extract the 32 byte key material from the object. This patch adds parsing code for processing the ANS.1 key files.
The supported algorithm is slh-dsa-sha2-128s-with-sha256, its OID is defined in
https://csrc.nist.gov/projects/computer-security-objects-register/algorithm-registration#heading1725030685275_13
Tested on an opentitatn owner's firmware by passing to --spx-key first the raw SPX key and then the HSM generated PEM file, and observing the unchanged contents of the resulting image.
Signed-off-by: Vadim Bendebury <vbendeb@chromium.org>
(cherry picked from commit fb326fc736e955f3a6f2d8db44de03c430b9b9b1)
> sphincsplus: accept PUB key as PEM encoded ASN.1 objects

- hw/dv/sv/mem_bkdr_util/sram_bkdr_util.sv
Drop the upper bits. Furthermore, add the tiling parameter to the sram bkdr utility.
> [membkdr] Fix return with of read32 and add tiling params to sram util

- rules/opentitan/cc.bzl
- rules/rv.bzl
- sw/device/silicon_creator/imm_rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/BUILD
- sw/device/silicon_creator/rom_ext/sival/BUILD
The `extra_bazel_features` attribute was added #25840 as an attribute to `rv_rule` to transitively add features to the rule. However this is too general because when applied to opentitan_binary, it will change the features not only for the rule, but all its dependencies such as exec_env, tools,  etc which may have unintended effects.
This commit keeps essentially the same logic but instead of applying it to `rv_rule`, it is now only an attribute of `opentitan_binary` and `opentitan_test` and it transitions only features for the `deps`. This attribute is also renamed to `transitive_features`. The rationale for the rename is that every bazel rule has an implicit `features` argument but it only applies to the target, not its dependencies. This attribute does the same but also applies …
> [rules] Rename and change semantic of `extra_bazel_features`

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/cbor.h
This dependency is only used to log an error message which is already covered by a specific error code anyway. Also since `log` only compiles on OT, it prevents the unittests from being runnable on host.
> [silicon_creator] Remove cbor dependency on log

- hw/ip/hmac/dv/env/hmac_env_cfg.sv
- hw/ip/hmac/dv/env/hmac_env_cov.sv
- hw/ip/hmac/dv/env/hmac_env_pkg.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_test_vectors_sha_vseq.sv
- hw/ip/hmac/dv/hmac_sim_cfg.hjson
- Split the NIST test vectors into shorter tests to avoid timeout issues. Linked to issue #23980.
- And move the NIST test vector checking from the sequence to the scoreboard to be more reusable (and UVM compliant). This addresses part of the issue #23288.
- Now, the seq is picking random vectors from the test vector file according to the desired configuartion. And the scoreboard is trying to find if one of the digest is matching. If yes, then the test is considered as passed and the coverage is collected. The NIST will be considred as covered if all of the vectors have been exercised.
> [hmac,dv] Split NIST test vectors to avoid timeout

- .github/workflows/ci.yml
- MODULE.bazel
- MODULE.bazel.lock
- hw/top_earlgrey/BUILD
- rules/opentitan/cc.bzl
- rules/opentitan/defs.bzl
- rules/opentitan/providers.bzl
- rules/opentitan/qemu.bzl
- rules/scripts/BUILD
- rules/scripts/qemu_pass.py
- sw/device/lib/arch/BUILD
- sw/device/lib/arch/device.h
- sw/device/lib/arch/device_sim_qemu.c
- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/rom/BUILD
- sw/device/tests/BUILD
- sw/device/tests/rom_exit_immediately.S
- third_party/qemu/BUILD
- third_party/qemu/BUILD.qemu_opentitan.bazel
- third_party/qemu/extensions.bzl
This PR adds a `sim_qemu_rom_with_fake_keys` execution environment and CI job.
QEMU comes from the in-development Earl Grey branch of our fork: https://github.com/lowRISC/qemu/tree/dev/ot-earlgrey-1.0.0-updates
In the future when Earl Grey and Darjeeling coexist in the same QEMU binary, this execution environment should support both tops in Bazel.
The exec env currently runs `qemu-system-riscv32` directly. A future PR will add QEMU support to `opentitantool`. Until then, the exec env does not support tests that require custom harnesses and the test won't quit when `FAIL!` is printed, it will have to timeout.
`qemu_params` supports the `icount: <int>` and `globals: { <key>: <val> }` parameters for changing the Ibex clock scaling factor and global parameter values respectively.
QEMU …
> [bazel] Add QEMU execution environment

- sw/device/silicon_creator/lib/manifest.h
- sw/device/silicon_creator/lib/ownership/datatypes.h
Introduce Integrator Specific Firmware Binding (ISFB) data structures used to implement integrator-device specific binding as well as anti-rollback based on ownership configuration.
Data structures:
1. `manifest_ext_isfb_t`: Integration specific firmware binding manifest extension. Contains anti-rollback strike mask as well as device expecific product expression.
2. `manifest_ext_isfb_erase_t`: ISFB erase policy manifest extension. This extension is used to authorize erasing of the ISFB region. Intended for testing purposes. The implementation will require node-locking for this policy to be effective.
3. `owner_isfb_config`: ISFB owner configuration. Defines the ISFB info flash page configuration as well as its erase policy.
(cherry …
> Cherry-pick to earlgrey_1.0.0: [rom_ext] Introduce ISFB data structures.

- hw/ip_templates/otp_ctrl/dv/env/otp_ctrl_env.core.tpl
- hw/ip_templates/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv
- hw/top_darjeeling/ip_autogen/otp_ctrl/dv/env/otp_ctrl_env.core
- hw/top_darjeeling/ip_autogen/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv
- hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_ctrl_env.core
- hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv
Use mem_bkdr_util_pkg for top-level only:
- The block level DV code doesn't use this package, so don't add it as a block-level dependency.
- Moreover, the code depends on SKU-specific OTP fields which are only available in the top-level DV environment, so it won't compile at block level.
Fixes #25883
> [mem_bkdr_util,otp_ctrl] Restore the use of EnCsrngSwAppReadSize

- util/dtgen/helper.py
- util/topgen/lib.py
The code is trying to find the module of external interrupts which of course does not exists. Instead, map those to the 'unknown' peripheral.
> [topgen,dtgen] Fix handling of external interrupts

- .github/workflows/ci.yml
- WORKSPACE
- hw/top_earlgrey/BUILD
- rules/opentitan/cc.bzl
- rules/opentitan/defs.bzl
- rules/opentitan/providers.bzl
- rules/opentitan/qemu.bzl
- rules/scripts/BUILD
- rules/scripts/qemu_pass.py
- sw/device/lib/arch/BUILD
- sw/device/lib/arch/device.h
- sw/device/lib/arch/device_sim_qemu.c
- sw/device/silicon_creator/lib/drivers/BUILD
- sw/device/silicon_creator/lib/sigverify/BUILD
- sw/device/silicon_creator/rom/BUILD
- sw/device/tests/BUILD
- sw/device/tests/rom_exit_immediately.S
- third_party/qemu/BUILD
- third_party/qemu/BUILD.qemu_opentitan.bazel
- third_party/qemu/repos.bzl
Backport of #25909
Mostly the same but with `WORKSPACE` instead of `MODULE.bazel` and with some paths (e.g. to `otp_ctrl`) fixed. No material differences.
> [bazel] Add QEMU execution environment to `earlgrey_1.0.0`

- sw/device/silicon_creator/lib/cert/BUILD
- sw/device/silicon_creator/lib/cert/dice_chain.c
- sw/device/silicon_creator/lib/cert/dice_chain.h
- sw/device/silicon_creator/lib/ownership/BUILD
- sw/device/silicon_creator/lib/ownership/datatypes.h
- sw/device/silicon_creator/lib/ownership/owner_block.c
- sw/device/silicon_creator/lib/ownership/owner_block.h
- sw/device/silicon_creator/rom_ext/rom_ext.c
Note: this is manual cherry-pick from #25007 
1. Measure the owner configuration and combine that measurement with the BL0 measurement to diversify the attestation ladder.
2. Apply the diversifier from the app verification key to the sealing ladder iff the ownership state is LockedOwner.
Addresses: #21583 (adds owner firmware measurement to CDI_1 cert)
Addresses: #19596 (add owner configuration block measurement to CDI_1 cert)
(cherry picked from commit 6c4a600e7d272787c8ff0cf65f3c403ec91f9e77) 
(cherry picked from commit ff6e7d4c176203099f0e214b59c992a9cf44f74e)
> Cherry-pick to master: [rom_ext,ownership] Diversify `keymgr` on owner measurements

- rules/scripts/qemu_pass.py
These canonical paths are different between Bazel 6, 7, and 8. The `rules_python` runfiles library will perform repository mappings before using this path, so we can use `qemu_opentitan` instead of the canonical name.
> [bazel] Fix runfile path to QEMU binary

- util/topgen/merge.py
This results in having the same reset being routed to both the primary and shadowed reset. This is ok, as unmanaged external resets are coming from a dedicated external reset, which is already behind a glitch filter.
> [topgen] Mark external unmanaged resets as non-shadow

- hw/top_darjeeling/lint/top_darjeeling.waiver
top_darjeeling.sv is auto-generated and adhering to the line length limit is not always feasible for auto-generated files. In particular when dealing with uniquified and parameterized input/ouput ports and signal names.
Automatically wrapping those lines would hinder readability and so would coming up with shorter signal/parameter names (which is especially challenging given the auto-generation / unification aspects here).
> [lint] Waive LINE_LENGTH AscentLint warnings in top_darjeeling.sv

- hw/ip_templates/racl_ctrl/data/racl_ctrl.hjson.tpl
- hw/top_darjeeling/ip_autogen/racl_ctrl/data/racl_ctrl.hjson
- hw/top_darjeeling/ip_autogen/racl_ctrl/doc/registers.md
This is a minor fix that only changes the generated documentation for `racl_ctrl`.
> [RACL] Fix hjson/md generation for racl_ctrl

- sw/device/lib/testing/json/provisioning_data.h
- sw/device/silicon_creator/manuf/base/BUILD
- sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
- sw/device/silicon_creator/manuf/lib/ast_program.c
- sw/device/silicon_creator/manuf/lib/flash_info_fields.c
- sw/device/silicon_creator/manuf/lib/flash_info_fields.h
- sw/host/provisioning/ft/src/main.rs
- sw/host/provisioning/orchestrator/src/orchestrator.py
- sw/host/provisioning/orchestrator/src/ot_dut.py
- sw/host/provisioning/orchestrator/tests/BUILD
- sw/host/provisioning/orchestrator/tests/e2e_option_flags.sh
This updates the individualization firmware to enable patching a single AST config CSR based on an address and value stored in flash info page 0. This is activated by a CLI arg `--patch-ast` passed to the orchestrator script.
> [manuf] enable patching a single AST config CSR
