lowRISC/opentitan

sw/host/tests/ownership/flash_permission_test.rs
The problems were highlighted when running pre-submission check on an unrelated patch.
=> flash_permission_test: fix lint errors

rules/linker.bzl
The compilation context created by `ld_library` was incorrectly using the full file name (e.g. sw/device/file.ld) as the include path instead of the directory name (e.g. sw/device).
=> [rules] Fix linker rule to correct set the includes path

hw/ip/gpio/dv/env/gpio_env_cfg.sv, hw/ip/gpio/dv/env/seq_lib/gpio_dout_din_regs_random_rw_vseq.sv, hw/ip/gpio/dv/env/seq_lib/gpio_intr_rand_pgm_vseq.sv, hw/ip/gpio/dv/env/seq_lib/gpio_rand_intr_trigger_vseq.sv, hw/ip/gpio/dv/env/seq_lib/gpio_random_dout_din_vseq.sv, hw/ip/gpio/dv/env/seq_lib/gpio_random_long_reg_writes_reg_reads_vseq.sv, hw/ip/gpio/dv/env/seq_lib/gpio_smoke_vseq.sv
New fix for the stress_all_gpio testcase with random reset. Basically included new if(reset) checks into the sequences to skip the flow when a reset comes, and replaced the wait_clks task to wait_clks_or_rst. This makes the gpio test pass with a reasonable number of seeds. It's a temporally fix until we have the reset agent on place.
=> Fix the gpio_stress_all with random reset 

sw/device/silicon_creator/manuf/base/BUILD, sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg_functest.c, sw/device/silicon_creator/manuf/lib/util.c
We update the individualization firmware to purposely exclude the AST configuration data field of the CreatorSwCfg partition from the same partition's digest calculation because this could be different per chip and we do not want to it to be part of the foundation for the UDS keys if the `OWNER_SW_CFG_ROM_KEYMGR_OTP_MEAS_EN` switch is set to enabled.
If the `OWNER_SW_CFG_ROM_KEYMGR_OTP_MEAS_EN` field is intended to be set for a given SKU, during personalization we need to be able to inject the expected OTP SW partition measurement (which is computed as `sha256(CreatorSwCfg digest || OwnerSwCfg digest || root key hash)` into the manifest of the perso image so that the same CreatorRootKey keymgr attestation binding value computed in the field by the ROM is the same as the one used during …
=> [manuf] update individualization to exclude AST data from OTP digest

sw/host/provisioning/ft_lib/src/lib.rs
In case the perso code generats dev seeds verify that the Owner's image started in the end of the process can reproduce the seeds.
Tested on CW310 FPGA by running perso with an updated Cros image. Also verified that all the rest of the SKUs pass the provisioning test.
=> [manuf] add post perso dev seed validation

util/dtgen/dt_ip.c.tpl, util/dtgen/dt_ip.h.tpl
Due to a rebase error, those functions were not added in the initial merge of the DT.
=> [dtgen] Add missing clock related functions

util/topgen.py
AC ranges do not use the top-level cfg anymore.
Instead the number of ranges is defined on a per instance basis.
=> [topgen] Don't gate ac_range_check generation by topcfg

hw/ip/uart/dv/env/uart_env_cov.sv, hw/ip_templates/rstmgr/dv/rstmgr_cnsty_chk/tb.sv, hw/top_darjeeling/ip_autogen/rstmgr/dv/rstmgr_cnsty_chk/tb.sv, hw/top_earlgrey/ip_autogen/rstmgr/dv/rstmgr_cnsty_chk/tb.sv, hw/top_englishbreakfast/ip_autogen/rstmgr/dv/rstmgr_cnsty_chk/tb.sv
There are detailed notes in the commits, but I *think* this fixes every example where we do the problem.
As such, this fixes #26001.
=> [dv] Avoid imports into class scope

hw/ip_templates/ac_range_check/data/ac_range_check.hjson.tpl, hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl, hw/top_darjeeling/ip_autogen/ac_range_check/data/ac_range_check.hjson, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv
A few fixes for `ac_range_check` from t-l simulation bring up.
Use strict SystemVerilog typing in assignments; otherwise the assignments are faulted by xcelium.
Introduce assertion that prim_count errors become alerts.
Add alert names for the shadowed control register; otherwise cip_base_env_cfg complains.
=> [rtl,ac_range_check] SystemVerilog type and assertion fixes

hw/ip/hmac/dv/hmac_sim_cfg.hjson
- fcov had 2 holes, reseed has to be slightly increased to cover them.
=> [hmac,dv] Ajust reseed for SHA384/512 for fcov

sw/device/silicon_creator/manuf/base/sram_ft_individualize.c, sw/device/silicon_creator/manuf/lib/ast_program.c, sw/device/silicon_creator/manuf/lib/ast_program_functest.c
All value will be copied to OTP and subsequently loaded into the CSRs by the ROM.
=> [manuf,ast] do not copy all AST values to CSRs during SRAM load

hw/ip/hmac/dv/env/hmac_env.core, hw/ip/hmac/dv/env/seq_lib/hmac_directed_vseq.sv, hw/ip/hmac/dv/env/seq_lib/hmac_vseq_list.sv, hw/ip/hmac/dv/hmac_sim_cfg.hjson
- FSM transition StLenHi->StIdle is missing, a directed test is required. This test is waiting until this state is detected and disable SHA core (sha_en=0). This has the effect of moving the FSM back to StIdle state.
=> [hmac,dv] Directed test to cover FSM trans hole

hw/dv/sv/alert_esc_agent/alert_esc_agent_cfg.sv, hw/dv/sv/alert_esc_agent/alert_monitor.sv, hw/dv/sv/cip_lib/cip_base_scoreboard.sv
When ping happens we go to ping handshake phases and
meanwhile if alert happens we can't proceed with
alert handshake phases until ping finishes. But in
cip_base_scb, if a fatal alert happens then the task
check_alert_triggered() waits for 6 cycles to get the
alert in the middle of alert handshake.
This PR tweaks check_alert_triggered() to watch ping
handshakes in both of the phases and once the handshakes
finishes then wait for 6 cycles to get the alert in the
middle of alert handshake.
=> [alert_handler, dv] Alert happened after ping

sw/device/lib/testing/BUILD, sw/device/lib/testing/aes_testutils.c, sw/device/tests/BUILD, sw/device/tests/aes_entropy_test.c, sw/device/tests/aes_smoketest.c
Fix #26208
Fix #26209
Fix #26210
=> [multitop] port aes_smoketest to multitop

sw/device/silicon_creator/imm_rom_ext/imm_rom_ext.c, sw/device/silicon_creator/lib/cert/dice_chain.c, sw/device/silicon_creator/lib/dbg_print.c, sw/device/silicon_creator/lib/dbg_print.h, sw/device/silicon_creator/lib/dbg_print_unittest.cc, sw/device/silicon_creator/lib/otbn_boot_services.c
Since immutable rom_ext only prints string literals, this commit replaced the `dbg_printf` by a simplified `dbg_puts` version. It saves about 480 Bytes.
=> [sw] Simplify dbg_printf in immutable rom ext

hw/ip/hmac/dv/env/seq_lib/hmac_stress_all_vseq.sv, hw/ip/hmac/dv/hmac_sim_cfg.hjson
- Increase number of seeds for stress_all_with_rand_reset tests as it was reduced by this PR #23664, but now we are targeting V3.
- Reduce transactions range for stress_all tests to reduce regression duration.
=> [hmac,dv] Adjust stress_all parameters

hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, util/topgen.py, util/topgen/merge.py, util/topgen/validate.py
To allow topgen to be called from different paths.
=> [topgen] All RACL configs are relative to the project root

hw/top_darjeeling/lint/top_darjeeling_lint_cfgs.hjson
This temporarily excludes the few blocks that have currently known lint problems from the overall Darjeeling configuration, so that we can activate the overall Darjeeling lint CI check.  The excluded blocks will be fixed and re-enabled in lint shortly (#26245)
=> [top_darjeeling,lint] Temporarily exclude blocks with problems

hw/ip/tlul/rtl/tlul_adapter_sram.sv
This code (from 7d6d53d11f2) was hard to read! It's not doing anything very clever, so let's rewrite it in a way that's easier to parse.
=> [tlul,rtl] Rewrite definition of wr_attr_error

hw/ip_templates/ac_range_check/data/ac_range_check.hjson.tpl, hw/top_darjeeling/ip_autogen/alert_handler/data/top_darjeeling_alert_handler.ipconfig.hjson, hw/top_earlgrey/ip_autogen/alert_handler/data/top_earlgrey_alert_handler.ipconfig.hjson, util/topgen.py, util/topgen/lib.py, util/topgen/merge.py, util/topgen/validate.py
This has two commits:
- Fix problems in uniquification:
- The feature was not triggered by any top so it was not tested
- Minor simplification in the validate code:
- Use dictionaries instead of arrays of ips, so avoids the need for
indices
=> [tools,topgen] Fix uniquification and simplify validate

sw/device/tests/penetrationtests/firmware/BUILD
Introduce `PENTEST_EXEC_ENVS` to align the execution environment configuration of existing penetration tests. Include `EARLGREY_SILICON_OWNER_ROM_EXT_ENVS` to add support for silicon targets, including `sival` as well as SKUs injected using the provisioning extensions infrastructure.
=> [pentest] Add SiliconOwner exec envs.

sw/device/tests/BUILD, sw/device/tests/kmac_app_rom_test.c, sw/device/tests/kmac_mode_cshake_test.c, sw/device/tests/kmac_mode_kmac_test.c
Fix #26216
Fix #26218
Fix #26219
Fix #26220
This PR ports 3 KMAC tests to use the devicetables API so that they no longer depend on Earlgrey-specific constants. All three tests remain passing on Earlgrey on FPGA (`fpga_cw310_rom_with_fake_keys`), and will compile for Darjeeling using e.g.
```sh
bazel build //sw/device/tests:kmac_app_rom_test_sim_dv --//hw/top=darjeeling 
```
It might be worth updating `kmac_app_rom_test` in the future so that each exec_env provides a way to get the hashfile of its ROM, so the information here is not hard-coded. But that is out of scope for this PR.
Edit: I've also now tested chip_sw_kmac_mode_kmac_jitter_en is passing on Earlgrey via DVsim so I'm marking this as closing that issue as well.
=> [sw,multitop] port kmac_{app_rom,mode_cshake,mode_kmac}_test to devicetables

sw/device/tests/BUILD, sw/device/tests/rv_core_ibex_address_translation_test.c
Fix #26229
This PR ports the `rv_core_ibex_address_translation_test` to use the devicetables API so that it no longer depends on Earlgrey-specific constants. The test remains passing on Earlgrey on FPGA (`fpga_cw310_rom_with_fake_keys`), and will compile for Darjeeling via
```sh
bazel build //sw/device/tests:rv_core_ibex_address_translation_test_sim_dv --//hw/top=darjeeling
```
=> [sw] Port rv_core_ibex_address_translation_test to devicetables

hw/ip/spi_device/rtl/spi_device.sv, hw/ip/spi_host/rtl/spi_host_window.sv, hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_common_vseq.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_readback_err_vseq.sv, hw/ip/sram_ctrl/rtl/sram_ctrl.sv, hw/ip/sram_ctrl/rtl/sram_ctrl_ram_reg_top.sv, hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/racl/all_rd_wr_mapping.hjson, hw/top_darjeeling/data/racl/soc_rot_mapping.hjson, hw/top_darjeeling/rtl/autogen/top_racl_pkg.sv, hw/top_darjeeling/templates/toplevel.sv.tpl, hw/top_earlgrey/rtl/autogen/top_racl_pkg.sv, hw/top_earlgrey/templates/toplevel.sv.tpl, hw/top_englishbreakfast/rtl/autogen/top_racl_pkg.sv, util/raclgen.py, util/raclgen/lib.py, util/topgen/merge.py, util/topgen/templates/toplevel_racl_pkg.sv.tpl
This PR adds racl support for the `ram` tlul interface of `sram_ctrl`. (RACL for its `regs` interface was addded in #26047)
However, for this it was necessary to add so-called RACL ranges.
Due to this new type, the format of the racl mapping hjson files changes.
Furthermore, this PR also allows non-`*` mappings now (as mentioned in #25986).
I could not reasonably split the changes in `raclgen/lib.py` into separate commits. I hope this is still okay.
~~Note: This PR is based on #26096 and should not be merged before #26096.
I will rebase this PR and drop the first commit when that happens.~~
=> [RACL] Add support for ranges and enable racl for sram_ctrl

sw/device/tests/penetrationtests/firmware/sca/BUILD, sw/device/tests/penetrationtests/firmware/sca/otbn/BUILD, sw/device/tests/penetrationtests/firmware/sca/otbn/otbn_insn_carry_flag.s, sw/device/tests/penetrationtests/firmware/sca/otbn_sca.c, sw/device/tests/penetrationtests/firmware/sca/otbn_sca.h, sw/device/tests/penetrationtests/json/otbn_sca_commands.h
This PR adds the following new OTBN SCA tests to the penetration testing framework:
- otbn.sca.insn.carry_flag
- otbn.sca.ecdsa256.sign
- otbn.sca.ecdsa256.sign_batch
- otbn.sca.ecdsa256.sign_fvsr_batch
=> [pentest] Add OTBN SCA tests

sw/device/tests/penetrationtests/firmware/sca/edn_sca.c, sw/device/tests/penetrationtests/firmware/sca/edn_sca.h, sw/device/tests/penetrationtests/json/edn_sca_commands.h
This commit updates the EDN SCA tests to use asm instead of C code such that the SCA target is more accurate.
=> [pentest] Update EDN SCA tests

hw/ip/hmac/dv/cov/hmac_cov_excl.el
- the PR #26163 was adding 4 assertions to the exclusion list which have been removed by the PR #25696. This commit adds them back.
=> [hmac,dv] Add assertions excl back from PR #26163

sw/device/tests/power_virus_systemtest.c
The current power virus implementation writes to the i2c device but has no logic enabled to flush the registers. This causes the test to hang on the second iteration when running in silicon. This change disables i2c writes if the target is `kDeviceSilicon`.
=> [sival] Disable writing to I2C in powervirus test.

hw/top_darjeeling/BUILD, hw/top_darjeeling/sw/BUILD, hw/top_darjeeling/sw/dt/BUILD, hw/top_darjeeling/sw/dt/sim_dv.c, hw/top_earlgrey/BUILD, hw/top_earlgrey/sw/dt/BUILD, hw/top_earlgrey/sw/dt/sim_qemu.c, sw/device/tests/BUILD, sw/device/tests/rv_timer_smoketest.c
Fix #26232
This PR ports the `rv_timer_smoketest` to use the devicetables API so that it no longer depends on Earlgrey-specific constants. The test remains passing on Earlgrey on FPGA (`fpga_cw310_rom_with_fake_keys`), and will compile for Darjeeling via
```sh
bazel build //sw/device/tests:rv_timer_smoketest_sim_dv --//hw/top=darjeeling
```
See the commit message for more details. Includes a couple of commits (slightly modified) from #26158 to get better support for clock speeds in multitop tests.
=> [sw,multitop] port rv_timer_smoketest to dt & add missing dt clocks

sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/rom_ctrl_integrity_check_test.c
Fix #26224
This PR ports the `rom_ctrl_integrity_check_test` to use the devicetables API so that it no longer depends on Earlgrey-specific constants. The test remains passing on Earlgrey in the `sim_dv` environment, and will compile for Darjeeling via
```sh
bazel build //sw/device/tests/sim_dv:rom_ctrl_integrity_check_test_sim_dv --//hw/top=darjeeling
```
As with `kmac_app_rom_test`, because Darjeeling has two ROM partitions, it isn't entirely clear to me whether this test will actually be functional when ported to Darjeeling, or whether it will need some extra handling conditional on Darjeeling; for now, this PR aims to complete the work to port this test to devicetables and get it compiling independent of the Earlgrey top at least. Perhaps this test should check *all* available ROMs …
=> [sw] Port rom_ctrl_integrity_check_test to devicetables

doc/getting_started/setup_fpga.md
At least two people have been understandably confused by error message `Error: Firmware programming failed: Unable to establish connection after flashing.  Possibly bad image.` when using opentitantool to flash HyperDebug firmware for the first time.  The cause being that with the jumper wire left in place, the board will not boot into the firmware just flashed, but instead boot into the DFU bootloaded again.
Adding an explicit step in the instructions calling for removing the jumper wire _before_ running opentitantool should hopefully avoid this.
=> [doc] Better explain HyperDebug flashing

util/tlgen/xbar.pkg.sv.tpl, util/tlgen/xbar.rtl.sv.tpl
This PR
* fixes a typo/copy-paste error in xbar.rtl.sv.tpl
* and allows for multiple addr_ranges for all devices.
The latter is a new feature that allows e.g., to map parts of the address space of one subsystem into another subsystem's address space.
E.g., if one subsystem has a large range with a hole in the middle, it may be split into two ranges and something else can be mapped into that hole.
=> [tools,tlgen] Allow multiple address ranges in tlgen templates

BLOCKFILE
otp_ctrl is now an ipgen block and the hjson within top_earlgrey needs protecting.
=> [top_earlgrey] Blockfile updates

sw/device/tests/BUILD, sw/device/tests/csrng_kat_test.c, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/lc_ctrl_scrap_test.c
Fix #26214
Fix #26221
These 2 tests are pretty simple to port.
I check for exact 1 instance instead of at least 1 since they should all be singleton IPs.
=> [multitop, tests] port lc_ctrl_scrap_test & csrng_kat_test to darjeeling

sw/device/lib/dif/dif_pinmux.c, sw/device/lib/testing/pinmux_testutils.c, util/dtgen/dt_api.c.tpl, util/dtgen/dt_api.h.tpl, util/dtgen/helper.py
At the moment the peripheral I/Os of type DIO include information about the PAD register to use to configure them. However they do not provide any information about the corresponding `dt_pad_t` which can be valuable in some context. Add this information to the DT.
=> [dtgen] Add pad information for DIOs

util/topgen/merge.py
Otherwise an idle signal is inserted that is left unconnected.
=> [topgen] Don't do clkmgr idle connect if no clkmgr exists

hw/ip_templates/clkmgr/data/clkmgr.hjson.tpl, hw/ip_templates/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip_templates/clkmgr/dv/env/seq_lib/clkmgr_frequency_vseq.sv, hw/ip_templates/clkmgr/dv/env/seq_lib/clkmgr_regwen_vseq.sv, hw/top_darjeeling/ip_autogen/clkmgr/data/clkmgr.hjson, hw/top_darjeeling/ip_autogen/clkmgr/doc/registers.md, hw/top_darjeeling/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/top_darjeeling/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_frequency_vseq.sv, hw/top_darjeeling/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_regwen_vseq.sv, hw/top_darjeeling/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv, hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson, hw/top_earlgrey/ip_autogen/clkmgr/data/clkmgr.hjson, hw/top_earlgrey/ip_autogen/clkmgr/doc/registers.md, hw/top_earlgrey/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/top_earlgrey/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_frequency_vseq.sv, hw/top_earlgrey/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_regwen_vseq.sv, hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv, hw/top_englishbreakfast/ip_autogen/clkmgr/data/clkmgr.hjson, hw/top_englishbreakfast/ip_autogen/clkmgr/doc/registers.md, hw/top_englishbreakfast/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/top_englishbreakfast/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_frequency_vseq.sv, hw/top_englishbreakfast/ip_autogen/clkmgr/dv/env/seq_lib/clkmgr_regwen_vseq.sv, hw/top_englishbreakfast/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv, sw/device/lib/dif/dif_clkmgr.c, sw/device/lib/dif/dif_clkmgr.h, sw/device/lib/dif/dif_clkmgr_unittest.cc, sw/device/lib/testing/clkmgr_testutils.c, sw/device/tests/BUILD, sw/device/tests/clkmgr_jitter_frequency_test.c, sw/device/tests/clkmgr_jitter_test.c
This has two commits:
- Fix the clkmgr hjson file to connect jitter_regwen to jitter_enable
- Enhance unit an top level tests for this feature
- Add dif support for this as required
- Fix clkmgr_frequency block level test to disable an assertion that is intentionally violated
Fixes #26258
=> [rtl,clkmgr] Fix missing jitter regwen

util/topgen/validate.py
To fix dealing with unmanaged external resets.
=> [topgen] Use reset net instead of signal for validation

util/topgen/merge.py
The interrupt name for incoming IRQs would grow for multiple invocations due to in-place edits. `add_module_prefix_to_signal` for the normal interrupts does a `deepcopy` internally.
=> [topgen] No inplace edits, it's not indepodent for multiple passes

util/topgen.py
Incoming alerts would mistakenly assume that LPGs exist already for the internal alerts.
=> [topgen] Only add LPG if there is already a LPG defined

sw/host/opentitanlib/src/app/i2c.rs, sw/host/opentitanlib/src/tpm/driver.rs, sw/host/opentitanlib/src/transport/hyperdebug/spi.rs, sw/host/opentitanlib/src/util/bitbang.rs
- Removed leftover debug logging from opentitanlib/src/app/i2c.rs .
- Reordered the proprietary `GscReady` for I2C transactions, to more accurately reflect what HyperDebug does.
- Increased maximum TPM FIFO transfer burst size from 32 to 64 bytes.
- Fixed bitbang pauses to allow 1% tolerance either way.
=> [opentitantool] Several small fixes

hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson, sw/device/tests/BUILD, sw/device/tests/hmac_endianness_test.c
Add HMAC endian test as per chip_hmac_testplan.hjson Incorporated suggested changes from PR feedback
Signed-off-by: Ramesh Prakash <rprakas@google.com>
(cherry picked from commit 4999941)
=> [sival/hmac] Add Hmac Endian Test

hw/ip_templates/racl_ctrl/README.md, hw/ip_templates/racl_ctrl/doc/racl_configuration.md.tpl, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/racl/racl.hjson, hw/top_darjeeling/ip_autogen/racl_ctrl/README.md, hw/top_darjeeling/ip_autogen/racl_ctrl/data/top_darjeeling_racl_ctrl.ipconfig.hjson, hw/top_darjeeling/ip_autogen/racl_ctrl/doc/racl_configuration.md, util/raclgen.py, util/raclgen/lib.py, util/reggen/BUILD, util/topgen/BUILD
This commit adds initial documentation for RACL and describes the racl configuration files in the form of inline examples.
Furthermore, it generates a `racl_configuration.md` file which documents the current RACL configuration for each module instance and interface.
I don't have a strong opinion on how to format the RACL config information in the generated tables. We can still discuss and changes this!
=> [RACL] Add documentation and example config

hw/top/defs.bzl, sw/device/lib/dif/dif_pwrmgr.c, sw/device/lib/dif/dif_pwrmgr.h, sw/device/lib/dif/dif_rstmgr.c, sw/device/lib/dif/dif_rstmgr.h, sw/device/lib/testing/BUILD, sw/device/lib/testing/aon_timer_testutils.c, sw/device/tests/BUILD, sw/device/tests/rstmgr_cpu_info_test.c, third_party/rust/patches/rules_rust.bindgen_defines.patch, third_party/rust/rust.MODULE.bazel
Fix #26226
This PR ports the `rstmgr_cpu_info_test` to use the devicetables API so that it no longer depends on Earlgrey-specific constants. The test remains passing on Earlgrey on FPGA (in `fpga_cw310_rom_with_fake_keys`) and will compile for Darjeeling via
```sh
bazel build --build_tests_only //sw/device/tests:rstmgr_cpu_info_test_sim_dv --//hw/top=darjeeling
```
As part of porting this test, the pwrmgr and rstmgr difs have been updated to support both Earglrey and Darjeeling's IP. This caused issues in bindgen when opentitanlib was compiled due an issue with upstream rules_rust where `rust_bindgen_library` does not understand defines set on `cc_libraries`. This is patched until support is merged [upstream](https://github.com/bazelbuild/rules_rust/pull/3271). It also fixes the …
=> [sw,dif] Port rstmgr_cpu_info_test to DT & update pwrmgr/rstmgr difs for DJ

hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
To avoid wrongly updating an intr_state bit on intr_test write the TB predicts each field separetely depending on which bits were set on the intr_test write.
This avoids the mismatch that could happen if the TB was going to predict an intr_state field due to count > threshold and has set intr_status_exp but not yet predicted the value by the time an intr_test occurs.
=> [dv, aon_timer] Split intr_state prediction on intr_test write

doc/security/cryptolib/cryptolib_api.md, sw/device/lib/crypto/impl/ecc.c, sw/device/lib/crypto/include/datatypes.h, sw/device/lib/crypto/include/ecc.h, sw/device/tests/crypto/cryptotest/firmware/ecdh.c, sw/device/tests/crypto/cryptotest/firmware/ecdsa.c, sw/device/tests/crypto/ecdh_p256_functest.c, sw/device/tests/crypto/ecdh_p256_sideload_functest.c, sw/device/tests/crypto/ecdh_p384_functest.c, sw/device/tests/crypto/ecdh_p384_sideload_functest.c, sw/device/tests/crypto/ecdsa_p256_functest.c, sw/device/tests/crypto/ecdsa_p256_sideload_functest.c, sw/device/tests/crypto/ecdsa_p384_functest.c, sw/device/tests/crypto/ecdsa_p384_sideload_functest.c
This change is part of a larger separation of the two curves' operations, so that we can remove the complicated curve specification parameters and save some code size on hardened switch statements and linker efficiency.
While I was here, I also edited some of the documentation comments to be more consistent and readable.
Part of https://github.com/lowRISC/opentitan/pull/26322
=> [crypto] Separate P-256 and P-384 key generation.

hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_excl.el
The excluded line is a continuous assignment. If the right hand side happens to be constant then it will never be marked as executing (and we don't care!)
I wrongly suggested that we should have an assertion saying that it *was* constant. But that's wrong, and was removed by a920ad246c. Tweak the text to avoid things being confusing next time.
This is a follow-up after #26310.
=> [rom_ctrl,dv] Slightly tweak an exclusion annotation

hw/ip/dma/data/dma.hjson, hw/ip/dma/doc/registers.md
Very tiny PR. The other quote was showing in documentation, but our generators managed to ignore it.
=> [dma] Fix misquoted field name

.github/workflows/ci.yml, third_party/rust/BUILD
An effort to remove `continue-on-error` since nobody actually checks them.
=> [ci] fix bazel target name warnings and turn it into hard error

doc/security/cryptolib/cryptolib_api.md, sw/device/lib/crypto/impl/ecc.c, sw/device/lib/crypto/include/ecc.h, sw/device/tests/crypto/cryptotest/firmware/ecdsa.c, sw/device/tests/crypto/ecdsa_p256_functest.c, sw/device/tests/crypto/ecdsa_p256_sideload_functest.c, sw/device/tests/crypto/ecdsa_p384_functest.c, sw/device/tests/crypto/ecdsa_p384_sideload_functest.c
Part of a larger change to separate the curves' operations so that we can remove the complicated curve specification parameters and save some code size on hardened switch statements and linker efficiency.
While I was here, I also edited some of the documentation comments to be more consistent and readable.
Part of https://github.com/lowRISC/opentitan/pull/26322
=> [crypto] Separate P-256 and P-384 sign/verify operations.

sw/device/lib/arch/BUILD, sw/device/lib/arch/device.h, sw/device/lib/arch/device_fpga_cw305.c, sw/device/lib/arch/device_fpga_cw310.c, sw/device/lib/arch/device_fpga_cw340.c, sw/device/lib/arch/device_silicon.c, sw/device/lib/arch/device_sim_dv.c, sw/device/lib/arch/device_sim_qemu.c, sw/device/lib/arch/device_sim_verilator.c, sw/device/lib/runtime/log.c, sw/device/lib/runtime/log.h, sw/device/lib/testing/test_framework/check.h, sw/device/lib/testing/test_framework/status.c, sw/device/lib/testing/test_framework/status.h, sw/device/silicon_creator/lib/epmp_test_unlock.c
By using the DT API for the Ibex core, we can make them work for all tops.
=> [sw,device] Make device definitions scale across tops

pyproject.toml
There are some warnings when running ruff format due to conflicting rules. This PR sets the ignore list as recommended. The behavior is not expected to change, but rather make the current behavior explicit and prevent the warning messages.
```
✦ ❯ ruff format
warning: `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible. Ignoring `one-blank-line-before-class`.
warning: `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible. Ignoring `multi-line-summary-second-line`.
warning: The following rules may cause conflicts when used with the formatter: `COM812`, `ISC001`. To avoid unexpected behavior, we recommend disabling these rules, either by removing them from the `select` or `extend-select` configuration, …
```
=> [python] add ignore for conflicting rules

hw/ip/soc_dbg_ctrl/data/soc_dbg_ctrl.hjson, hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl.sv
This removes the offenses for `soc_dbg_ctrl` from https://github.com/lowRISC/opentitan/issues/26362
=> [hw,soc_dbg_ctrl,doc] Properly define SEC_CM countermeasures

hw/ip/sram_ctrl/rtl/sram_ctrl.sv
PR lowRISC/opentitan#23292 introduced MuBi encoding for the prim_ram_1p_scr module. However, adding the corresponding countermeasure label PRIM_RAM.CTRL.MUBI was forgotten.
=> [sram_ctrl,cm] Add CM label to prim_ram

hw/ip/prim/prim_flop_no_rst.core, hw/ip/prim_generic/prim_generic_flop_no_rst.core, hw/ip/prim_generic/rtl/prim_generic_flop_no_rst.sv
From the physical perspective its better to reduce the load on the reset network. This PR adds a new prim for a flop without reset It can be used where data is transmitted alongside some control signal. The control signals would use flops with reset and always have a known value, but the data is using a flop without a reset. Then, the data is only used for example when the valid control signal indicates that there is actually valid data available.
=> [prim] Add flop without reset

sw/device/tests/BUILD, sw/device/tests/plic_sw_irq_test.c
Fix #26205
This PR ports the `plic_sw_irq_test` to use the devicetables API. The test remains passing on Earlgrey in the `fpga_cw310_rom_with_fake_keys` environment, and will compile for Darjeeling via
```sh
bazel build //sw/device/tests:plic_sw_irq_test --//hw/top=darjeeling
```
I have also successfully run this test on Darjeeling DV using the latest WIP branch.
=> [sw,multitop] Port `plic_sw_irq_test` to devicetables

sw/device/lib/dif/dif_clkmgr.c, sw/device/lib/dif/dif_clkmgr.h, sw/device/tests/BUILD, sw/device/tests/kmac_idle_test.c
Fix #26217
This PR ports the `kmac_idle_test` to use the devicetables API so that it no longer depends on Earlgrey-specific constants. The test remains passing on Earlgrey in the `fpga_cw310_rom_with_fake_keys` environment, and will compile for Darjeeling via
```sh
bazel build //sw/device/tests:kmac_idle_test --//hw/top=darjeeling
```
As part of porting this test, the clkmgr DIF has been updated using conditional compilation to match the changes made by Darjeeling's clkmgr. This test also still requires the use of a top-specific constant for the main KMAC hintable clock, since this information is not yet exposed through a clkmgr DT extension (see #26248)
=> [multitop,clkmgr] Port clkmgr DIF to support DJ & port `kmac_idle_test` to DT

util/vendor.py
Sometimes a mapping has a "from" and "to" field that is actually a file instead of a whole directory. Example of this can be found here: https://github.com/lowRISC/sonata-system/blob/06102a66aebdda1d42966b049409d8ddaa6cd53a/vendor/lowrisc_ip.vendor.hjson#L15 When also adding a patch directory this runs into a problem because git apply gets supplied the "to" field as a directory without checking whether it is a file. This commit fixes that by checking if it is a file before passing it along as the base directory.
=> [util/vendor] Allow patches to files

ci/lint/ruff.toml, util/uvmdvgen.py, util/uvmdvgen/__init__.py
Without this, `importlib.resources` was not able to find the package it was in.
=> [python] Move uvmdvgen out of its own package

sw/device/lib/dif/dif_spi_host.c, sw/device/lib/dif/dif_spi_host.h, sw/device/lib/dif/dif_spi_host_unittest.cc, sw/device/lib/testing/BUILD, sw/device/lib/testing/dma_testutils.c, sw/device/lib/testing/dma_testutils.h, sw/device/tests/BUILD, sw/device/tests/dma_abort.c, sw/device/tests/dma_inline_hashing.c
I've cherry picked the commits but dropped the changes to DV as that's not currently working for DJ on `master`.
I've only made the minimal changes required to get this compiling, I haven't yet ported the tests to device-tables.
=> [dma] Port DMA tests from `integrated_dev` branch

.github/workflows/ci.yml
Fix #26339
As discussed in lowRISC/opentitan#26339, when the check-countermeasures script fails, the Lint (slow) job continues without flagging this error. We should let the job failing when this check fails.
=> [ci] Remove continue-on-error for check-countermeasures check

hw/ip/gpio/rtl/gpio_reg_top.sv, hw/ip/i2c/rtl/i2c_reg_top.sv, hw/ip/mbx/rtl/mbx_soc_reg_top.sv, hw/ip/spi_device/rtl/spi_device_reg_top.sv, hw/ip/uart/rtl/uart_reg_top.sv, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check_reg_top.sv, hw/top_darjeeling/ip_autogen/racl_ctrl/rtl/racl_ctrl_reg_top.sv, util/reggen/reg_top.sv.tpl
This PR fixes a small issue in `reg_top.sv.tpl`:
With the introduction of RACL the `_re` and `_we` signals in `reg_enable_gen` were changed from `addr_hit` to `wr_addr_hit`, which depends on `racl_addr_hit_write`. However, `_we` should use `racl_addr_hit_read` instead.
=> [racl,reggen] reg_top.sv.tpl Fix _re signals in reg_enable_gen

hw/ip/gpio/data/gpio.hjson, hw/ip/gpio/doc/interfaces.md, hw/ip/gpio/doc/registers.md, hw/ip/gpio/doc/theory_of_operation.md, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson
Documentation adjustments for GPIO Straps feature.
=> Gpio straps doc

hw/ip/gpio/rtl/gpio.sv
[gpio,rtl] Remove overly strong assumption
The "always" part of this assumption (and assertion) is false if there is a reset. It also doesn't really give an assumption that constrains the input behaviour, so we should just drop it.
=> [gpio,rtl] Remove overly strong assumption

hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv.tpl, hw/top_darjeeling/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv, hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
Caught this with Verilator linting -- esc_ping_en is a N_ESC_SEV-wide (currently 4) one-hot signal that is shifted by esc_cnt (which goes up to 3). As a-will observes in https://github.com/lowRISC/opentitan/pull/22568#discussion_r1962486432, the too-narrow cast didn't cause a problem because the LHS causes us to widen again to N_ESC_SEV anyway.
=> [alert_handler,rtl] Fix esc_ping_en widening cast

sw/device/silicon_creator/imm_rom_ext/imm_rom_ext_epmp.c, sw/device/silicon_creator/lib/drivers/BUILD, sw/device/silicon_creator/lib/drivers/lifecycle.c, sw/device/silicon_creator/lib/drivers/lifecycle.h, sw/device/silicon_creator/lib/drivers/lifecycle_unittest.cc
The commit simplifies the existing check in immutable ROM_EXT, which determines whether to enable the RvDM ePMP region based on the lifecycle state (prod / non-prod). The simplified check only tests for PROD and PROD-END states to reduce space cost by eliminating TEST-UNLOCK states checks.
One potential downside is that invalid LCS states will be treated as non-prod, leading to the RvDM region being enabled. However, this is mitigated by the fact that debugging requires JTAG, which verifies LCS in hardware. Additionally, invalid LCS will be detected later in the mutable ROM_EXT stage when reading the lifecycle.
=> [sw] Simplify lifecycle checks in immutable rom ext

sw/device/silicon_creator/lib/cert/dice_chain.c, sw/device/silicon_creator/lib/cert/dice_cwt.c, sw/host/provisioning/ft_lib/src/lib.rs
This method eliminates all the CBOR parser code and reduces the rom_ext size by ~1.2KB (48888 -> 47640 Bytes).
---
During the boot process, the rom_ext will check if the CDI certificate serial number matches the cached one, and skip signing if matched.
As this check is exclusively used for cache refresh, an incorrect result doesn't compromise security, but only affects boot time. Therefore, there is no need to harden the check.
The CWT certificate check was simplified by directly comparing the certificate public key or ID to their expected offset.
=> [sw,dice] Simplify CWT cert id checker

MODULE.bazel.lock, rules/opentitan/qemu.bzl, third_party/qemu/extensions.bzl
The bus for the Earl Grey `eflash` has changed from 1 to 2. Updating QEMU here in OpenTitan will make upstream development slightly easier.
=> [bazel] Bump OT QEMU to v9.2.0-2025-02-05

sw/device/tests/kmac_endianess_test.c
The use of unaligned pointers leads to DIf to write the content byte by byte and therefore the swap is not applied.
Issue identified in #26354 by @luismarques
=> [sw,kmac_endianess] Make sure to use word-aligned message

hw/ip/dma/data/dma.hjson, hw/ip/dma/doc/registers.md, hw/ip/dma/rtl/dma.sv, hw/ip/dma/rtl/dma_pkg.sv, hw/ip/dma/rtl/dma_reg_pkg.sv, hw/ip/dma/rtl/dma_reg_top.sv
A similar feature exists on HMAC. Let's also add this to the DMA to make the SW life easier.
=> [hw,dma,rtl] Ability to swap the endianness of 32-byte digest words

sw/device/tests/entropy_src_kat_impl.c
Several loops increase the counter even on failures. This can result in the code pulling/pushing less elements than the FIFO size and causing the test to fail. Issue identified in #26354
=> [sw,entropy_src_kat] Fix several errors in the code

sw/device/silicon_creator/imm_rom_ext/BUILD, sw/device/silicon_creator/imm_rom_ext/defs.bzl, sw/device/silicon_creator/imm_rom_ext/e2e/boot_message/BUILD, sw/device/silicon_creator/imm_rom_ext/imm_rom_ext.c, sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
This commit adds a boot message that indicates whether the immutable rom_ext section is invoked by ROM (hash enforced) or by the fallback in ROM_EXT (hash unenforced).
This message can help identify the device mode for both manual and automated testing.
=> [sw,imm_rom_ext] Print hash enforcement status in boot message

sw/device/silicon_creator/lib/cert/BUILD, sw/device/silicon_creator/lib/cert/cbor.c, sw/device/silicon_creator/lib/cert/cbor.h, sw/device/silicon_creator/lib/cert/dice_cwt.c, sw/host/ot_certs/src/cwt.rs, third_party/open-dice/BUILD.open-dice.bazel
As part of the code size reduction process in CWT, this PR aims to provide a custom-made CBOR writer library for dice cert generation.
The core idea of this CBOR writer library is that we don't check if the destination buffer is large enough in every function call.
Instead, we require users to query the output size without writing to the actual buffer first.
If it doesn't exceed, then they run the process again to output to the target buffer.
For the codegen generated functions, we already calculate the size on our own, and thus we ignore the return values.
=> [cwt,dice,ot_certs] remove crate `cbor_reader_writer` from dice cert generation

sw/device/silicon_creator/lib/cert/BUILD, sw/device/silicon_creator/lib/cert/dice_chain.c
The dice_chain library currently determines the certificate buffer size based on x509 codegen constants, which is not suitable for the CWT variant.
This commit eliminates the dependency on x509 codegen constants and instead chooses the largest buffer size (i.e. Flash page size).
=> [sw,dice] Remove direct deps from dice_chain lib to x509 template

sw/device/tests/penetrationtests/firmware/BUILD
PR #26261 added the SiliconOwner exec environments to the pentesting framework. This commit adds this env to chip_pen_test_fi_otbn as well.
=> [pentest] Add missing exec environment

hw/top_darjeeling/templates/toplevel.sv.tpl, hw/top_earlgrey/templates/toplevel.sv.tpl, util/raclgen.py, util/topgen.py, util/topgen/templates/toplevel_racl.tpl, util/topgen/templates/toplevel_racl_pkg.sv.tpl, util/topgen/templates/toplevel_racl_pkg_parameters.tpl
This PR:
* deduplicates all of the RACL templates and consolidates them into two separate files
* allows including template files within other templates
* updates lowrisc_misc_linters to the latest version to allow for comments within .tpl files (which are needed for the license checker)
=> [RACL] Deduplicate RACL templates

hw/ip/aon_timer/data/aon_timer_testplan.hjson, hw/ip/aon_timer/dv/aon_timer_sim_cfg.hjson, hw/ip/aon_timer/dv/env/aon_timer_env.core, hw/ip/aon_timer/dv/env/aon_timer_env_cfg.sv, hw/ip/aon_timer/dv/env/aon_timer_env_cov.sv, hw/ip/aon_timer/dv/env/aon_timer_env_pkg.sv, hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_custom_intr_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_jump_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_prescaler_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_smoke_max_thold_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_smoke_min_thold_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_smoke_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_stress_all_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_vseq_list.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_wkup_count_cdc_hi_vseq.sv
This PR tackles the Functional coverage gap to reach to 100%. 
A few more constrained tests have been added for easier coverage closure (min/max threshold and intr_test).
Some of the covergroups have been fixed since not all bins were populated due to incorrect range values. 
Mid-TL_UL transaction reset have been added as well.
Running a regression with these improvements plus the remaining RTL exclusions from PR #26165 brings CCOV over ~99%.  
FCOV should already be at 100% for a single regression run (`-rx 1`). 
There's a couple of missing items for `tb.dut.u_reg.u_wkup_count_hi_cdc` and its arbiter below which I'm still working on generating stimulus for.
The goal is also to diminish the regression length to allow for faster sign-off and less simulation cycles
=> Aon timer fcov fixes

hw/ip_templates/racl_ctrl/lint/racl_ctrl.waiver.tpl, hw/top_darjeeling/ip_autogen/racl_ctrl/lint/racl_ctrl.waiver
Depending on the RACL policy names lines that are too long may be generated. This PR waives such lines for ascent lint.
=> [racl_ctrl] Waive auto generated long lines

hw/ip/pattgen/dv/env/pattgen_env_cfg.sv, hw/ip/pattgen/dv/env/pattgen_env_pkg.sv, hw/ip/pattgen/dv/env/pattgen_seq_cfg.sv, hw/ip/pattgen/dv/env/seq_lib/pattgen_base_vseq.sv, hw/ip/pattgen/dv/env/seq_lib/pattgen_cnt_rollover_vseq.sv, hw/ip/pattgen/dv/env/seq_lib/pattgen_error_vseq.sv, hw/ip/pattgen/dv/env/seq_lib/pattgen_perf_vseq.sv, hw/ip/pattgen/dv/env/seq_lib/pattgen_stress_all_vseq.sv
There a detailed notes in the commits, but a big chunk of this work is in `pattgen_base_vseq` (which was quite long, so had several possible cleanups).
=> [pattgen,dv] General code tidy-up

hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_darjeeling/rtl/autogen/top_racl_pkg.sv, hw/top_earlgrey/rtl/autogen/top_racl_pkg.sv, hw/top_englishbreakfast/rtl/autogen/top_racl_pkg.sv, util/raclgen/lib.py, util/topgen/templates/top_racl_pkg.sv.tpl, util/topgen/templates/toplevel_racl.tpl
Having this config in a parameter makes it easier for out-of-tree integration and to keep the behaviour in sync
=> [racl] Create a parameter defining the error response

hw/ip/pattgen/dv/env/pattgen_scoreboard.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv
These aren't actually used in the pattgen or sysrst_ctrl DV environments.
=> [dv] Remove unused intr_exp_at_addr_phase variables

sw/device/silicon_creator/lib/base/BUILD, sw/device/silicon_creator/lib/base/static_dice.ld, sw/device/silicon_creator/lib/base/static_dice_cdi_0.h, sw/device/silicon_creator/lib/cert/dice_chain.c
The previous PR #26409 transferred the public key ID to mutable ROM_EXT to validate the certificate. This is sufficient for the x509 variant, but not for the CWT variant, which uses public key contents to validate the UDS COSE Key. The manual e2e provisioning test `//sw/host/provisioning/orchestrator/tests:e2e_emulation_dice_cwt_cw340_test` can catch this error.
This commit fixes the test by putting the public key contents into the static dice region with the public key ID.
=> [sw,imm_rom_ext] Transfer DICE public keys to mutable ROM_EXT

sw/device/lib/dif/dif_clkmgr.h, sw/device/lib/dif/dif_clkmgr_unittest.cc, sw/device/lib/testing/clkmgr_testutils.c, sw/device/tests/BUILD, sw/device/tests/aes_idle_test.c, sw/device/tests/otbn_randomness_test.c
Fix #26211
Fix #26222
Darjeeling has no external clock so use of the `external_clk` parameter of `clkmgr_testutils_enable_clock_counts_with_expected_thresholds` will cause a check failure on darjeeling.
This API isn't used by the ported tests (otbn_randomness_test, aes_idle_test); they use clkmgr for another API.
=> [sw,multitop] port clkmgr_testutils and dependant tests to multi-top

sw/device/silicon_creator/imm_rom_ext/defs.bzl, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD
The immutable ROM_EXT section is compiled into every ROM_EXT. The immutability is only enforced by the ROM if an OTP flag is set. This removes a duplicate ROM_EXT build target that is no longer needed.
=> [rom_ext] remove duplicate ROM_EXT target

sw/device/silicon_creator/lib/ownership/ownership.c
After cherry-picking the immutable ROM_EXT changes to the earlgrey_1.0.0 branch, the call to ownership_seal is now performed in the immutable ROM_EXT.
=> [ownership] remove call to ownership_seal_init in ownership_init

sw/device/silicon_creator/lib/cert/BUILD, sw/device/silicon_creator/lib/cert/dice.c, sw/device/silicon_creator/lib/cert/template.h, sw/device/silicon_creator/lib/cert/tpm.c, sw/host/ot_certs/src/codegen.rs
Previously, variable size assertions were manually implemented, which is prone to errors. This commit introduces a setter helper designed to automatically generate these size assertions, improving readability and reducing potential inconsistencies.
=> [sw,ot_certs] Add X509 setter helper for automatic size assertions

sw/device/silicon_creator/imm_rom_ext/BUILD, sw/device/silicon_creator/imm_rom_ext/imm_rom_ext.c, sw/device/silicon_creator/lib/BUILD, sw/device/silicon_creator/lib/cert/dice_chain.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.h, sw/device/silicon_creator/lib/otbn_boot_services.c, sw/device/silicon_creator/rom_ext/rom_ext.c
The attestation seed page contains CSPRNG generated seeds, which will be mixed to the derived seed for generating the keypair. It is crucial that the page should not be tampered by less secure boot stages, which could lead to key leakage.
To prevent seed tampering, we lockdown the page to readonly at the IMM_ROM_EXT stage which owns the first key ladder state (UDS).
=> [sw,dice] Lockdown the attestation seed page to readonly

sw/device/silicon_creator/lib/cert/BUILD, sw/device/silicon_creator/lib/cert/dice_cwt.c, sw/host/ot_certs/src/cwt.rs
CWT templating libs are generating by the ot_certs lib component of opentitantool. Using ordered containers like HashMap causes the code generated to be non-reproducible across builds which impacts:
1. build reproducibility across offline signed binaries
2. inability to use the immutable ROM_EXT with CWT DICE cert format.
This fixes the CWT codegen ot_certs library to produce reproducible code.
=> [ot_certs] use IndexMap instead of HashMap when generating CWT code

sw/device/silicon_creator/lib/cert/dice_cwt.c
There are a few cases where the DICE needs to generate an identifier for use in certificates. To ensure these identifiers are deterministic and require no additional DICE inputs, the identifiers are derived from the associated public key. The identifiers are 20 octets so they fit in the RFC 5280 serialNumber field constraints and the X520SerialNumber type when hex encoded.
Ref: https://pigweed.googlesource.com/open-dice/+/HEAD/docs/specification.md#deriving-identifiers
=> [dice,cwt] Update the Issuer/Subject name size

hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_darjeeling/rtl/autogen/top_darjeeling_racl_pkg.sv, hw/top_darjeeling/rtl/autogen/top_racl_pkg.sv, util/raclgen/lib.py, util/topgen/templates/top_racl_pkg.sv.tpl, util/topgen/templates/toplevel_racl.tpl, util/topgen/templates/toplevel_racl_pkg.sv.tpl, util/topgen/templates/toplevel_racl_pkg_parameters.tpl
This commit:
* Renders the policy selectors (indices) for all policies.
* Uses the rendered policy selectors in the policy selection vectors.
* Moves the relevant information to an inline comment.
* Renames policy selection vectors from `POLICY_SEL_` to `POLICY_SEL_VEC_` to avoid naming conflicts between the policy selectors and the policy selection vectors.
The goal of this PR is to remove magic values in the selection vectors and make debugging easier by providing all the relevant information as an inline comment within the policy selection vectors.
Furthermore, this allows using the rendered policy selectors to index into the policy vector, which may be used by external IPs.
=> [RACL] Render policy selectors

hw/ip/gpio/data/gpio_testplan.hjson, hw/ip/gpio/dv/env/gpio_env.core, hw/ip/gpio/dv/env/gpio_env.sv, hw/ip/gpio/dv/env/gpio_env_cfg.sv, hw/ip/gpio/dv/env/gpio_env_pkg.sv, hw/ip/gpio/dv/env/gpio_scoreboard.sv, hw/ip/gpio/dv/env/seq_lib/gpio_base_vseq.sv, hw/ip/gpio/dv/env/seq_lib/gpio_rand_straps_vseq.sv, hw/ip/gpio/dv/env/seq_lib/gpio_vseq_list.sv, hw/ip/gpio/dv/gpio_sim.core, hw/ip/gpio/dv/gpio_sim_cfg.hjson, hw/ip/gpio/dv/interfaces/gpio_if.core, hw/ip/gpio/dv/interfaces/gpio_straps_if.sv, hw/ip/gpio/dv/tb/tb.sv, hw/ip/gpio/dv/tests/gpio_base_test.sv
New sequence to verify the straps feature and some additional description of the behaviour of this feature in the register document.
=> GPIO straps verif

hw/ip/tlul/rtl/tlul_adapter_dmi.sv, hw/ip/tlul/rtl/tlul_adapter_reg.sv, hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
The existing behaviour of the tlul_rsp_intg_gen was to add rsp/data integrity bits if their generation was enabled and pass through the input integrity bits if not.
In some instantiations (in tlul_adapter_reg and tlul_adapter_dmi), these bits are actually always zero. One consequence is missing coverage in DV simulations. The problem is that e.g. the rsp_intg signal is driven with a continuous assignment:
assign rsp_intg = tl_i.d_user.rsp_intg;
But the right hand side is zero, so constant and the assignment is not marked as covered.
This commit adds a UserInIsZero parameter. If this is true then we know the input d_user signal is zero and thus can wire the variable directly to zero.
This removes the cover point but will not change RTL behaviour at all.
=> [tlul,rtl] Explicitly zero some integrity bits from tlul_adapter_reg

sw/device/silicon_creator/lib/drivers/otbn.c, sw/device/silicon_creator/lib/drivers/otbn.h, sw/device/silicon_creator/lib/otbn_boot_services.c, sw/device/silicon_creator/lib/otbn_boot_services.h, sw/device/silicon_creator/lib/sigverify/ecdsa_p256_verify.c, sw/device/silicon_creator/lib/sigverify/ecdsa_p256_verify.h, sw/device/silicon_creator/rom_ext/rom_ext.c
1. Split ECDSA sigverify into start and finish operations so Ibex can perform SPX verification while OTBN is verifying the P256 signature.
2. Update the ROM_EXT to use the split P256 operations.
By running the ECDSA and SPX operations in parallel, the 4.2ms ECDSA verification time is subsumed into the ~9ms SPX verification time.
=> [rom_ext] Perform ECDSA ans SPX verification in parallel 

hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl_decode.sv
Re-lock is active high, correctly decode that to a logic.
=> [hw,soc_dbg_ctrl,rtl] Debug relock to Mubi::True

hw/ip/prim_xilinx/rtl/prim_xilinx_ram_1p.sv
This avoids elaboration errors from more stricter tools.
=> [hw,prim_xilinx_ram_1p] Explicitly cast MemInitFile to string

hw/ip/aon_timer/README.md
When the AON timer's wakeup counter was changed from 32 bits to 64 bits, the docs were mostly updated (in the theory of operation / registers / programmer's guide), but the index README page was missed - specifically the list of features. This is the first thing most people will read about the IP, so it should probably be accurate.
=> [aon_timer,doc] Remove 32-bit wakeup timer reference in the docs

SUMMARY.md
Update `SUMMARY.md` file to let the `ac_range_check` IP documents getting generated as HTML and be visible online [here](https://opentitan.org/book/hw/ip/index.html)
=> [doc] Update SUMMARY for Darjeeling AC Range Check

sw/device/tests/uart_tx_rx_test.c
Improve the chip-level DV UART test program in two ways:
- Add `volatile` to the type of the TX/RX data arrays that can be overwritten by the DV vseq.
- Fix some typos while in the neighbourhood.
=> [dv,chip] Add volatility & spelling to UART test

rules/manifest.bzl, rules/opentitan/cc.bzl, rules/opentitan/exec_env.bzl, rules/opentitan/toolchain.bzl, sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section/BUILD, util/design/BUILD, util/design/gen-otp-immutable-rom-ext-json.py
This PR removes the functionality of fusion immutable ROM_EXT hash into the `CREATOR_SW_CFG_MANUF_STATE` OTP field   from the OTP tooling and the manifest update tool.
With the fallback mechanism implemented in #25984, ROM can now attempt the alternative ROM_EXT slot if the immutable ROM_EXT hash is invalid. Consequently, the fusion of this hash into the  `CREATOR_SW_CFG_MANUF_STATE` OTP field and the binding of ROM_EXT to `creator_manuf_state` are no longer needed. 
This partially reverts #24948, #25106, and #25566.
=> [bazel,otp] remove im_ext hash fusion into MANUF_STATE

hw/ip/gpio/dv/env/seq_lib/gpio_stress_all_vseq.sv
Included the new straps testcase into the gpio_stress_all list of tests, to have more iterations and randomisation cases. 
Merge the PR #25868 first.
=> Gpio straps stress all

sw/device/silicon_creator/lib/drivers/flash_ctrl.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.h, sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc, sw/device/silicon_creator/lib/error.h, sw/device/silicon_creator/lib/ownership/BUILD, sw/device/silicon_creator/lib/ownership/datatypes.h, sw/device/silicon_creator/lib/ownership/ownership.c, sw/device/silicon_creator/lib/ownership/ownership.h, sw/device/silicon_creator/lib/ownership/ownership_unlock.c, sw/device/silicon_creator/lib/ownership/ownership_unlock_unittest.cc, sw/device/silicon_creator/lib/ownership/test_owner.c, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD, sw/device/silicon_creator/rom_ext/e2e/ownership/defs.bzl, sw/device/silicon_creator/rom_ext/e2e/ownership/flash_regions.c, sw/device/silicon_creator/rom_ext/e2e/verified_boot/boot_test.c, sw/device/silicon_creator/rom_ext/rescue.c, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/host/opentitanlib/src/ownership/owner.rs, sw/host/tests/ownership/BUILD, sw/host/tests/ownership/flash_permission_test.rs, sw/host/tests/ownership/newversion_test.rs, sw/host/tests/ownership/transfer_lib.rs
This is a manual cherry-pick of #25017.
The ownership `update_mode` allows the owner to attenuate the power of the unlock key:
- UpdateMode::Open - The unlock key has full unlock power.
- UpdateMode::Self - The unlock key can only unlock the device for updates to the self-same owner.
- UpdateMode::NewVersion - The device cannot unlock, but can accept a signed update from the self-same owner.
1. Add an `unlock_mode` field to the owner config and the associated UpdateMode constants.
2. Based on the UpdateMode, allow or deny the unlock command.
3. When in the NewVersion mode, check for updates during locked owner initialization.
4. Implement owner page lockdown based on the ownership state and update mode. 5a. Test that updates are accepted in NewVersion mode. 5b. Test that the permissions …
=> Cherry-pick to master: [ownership] Add an `update_mode` to the configuration

sw/device/lib/testing/json/provisioning_data.h, sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/host/provisioning/ft/src/main.rs, sw/host/provisioning/orchestrator/src/ot_dut.py
During personalization, CDI_0 and CDI_1 are generated based on ROM_EXT and Owner FW measurments that were manually passed in over the UJSON consoled. However, they were unused, as CDI_0 and CDI_1 are automatically updated by the ROM_EXT when the transport image is first booted. Therefore, these inputs were un-needed and unused. Thus, this PR removes theses inputs to minimize the UJSON console inputs from the ATE during perso.
=> [manuf] remove unused UJSON measurment inputs

sw/device/lib/testing/flash_ctrl_testutils.c, sw/device/lib/testing/flash_ctrl_testutils.h, sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c, sw/device/tests/sram_ctrl_scrambled_access_test.c, sw/device/tests/sysrst_ctrl_outputs_test.c, sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c
The backdoor wait mechanism was updated to not rely on flash_ctrl anymore, so the init is no longer needed.
=> [testutils] remove flash_ctrl_testutils_backdoor_init

hw/ip/aon_timer/data/aon_timer_testplan.hjson, hw/ip/aon_timer/dv/aon_timer_sim_cfg.hjson, hw/ip/aon_timer/dv/env/aon_timer_env.core, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_alternating_enable_on_off_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_vseq_list.sv
The goal of these changes is to ensure the TB can keep up predicting interrupts when the counters are disable shortly before/after they reach the threshold.
=> Aon timer alternating on off vseq

sw/device/silicon_creator/lib/boot_svc/boot_svc_header.c, sw/device/silicon_creator/lib/boot_svc/boot_svc_header_unittest.cc, sw/device/silicon_creator/lib/boot_svc/boot_svc_min_bl0_sec_ver.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_next_boot_bl0_slot.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_activate.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_unlock.h
Check that the boot_svc message length is valid before computing the digest.
=> [boot_svc] Check the bootsvc message length 

hw/ip/prim/prim_leading_one_ppc.core, hw/ip/prim/rtl/prim_arbiter_ppc.sv, hw/ip/prim/rtl/prim_leading_one_ppc.sv, hw/ip_templates/ac_range_check/ac_range_check.core.tpl, hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl, hw/top_darjeeling/ip_autogen/ac_range_check/ac_range_check.core, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv
This computes the denied index (the leading 1 in the deny mask) to identify the range that corresponds to the denied request. The index is logged to the status log register.
Resolves https://github.com/lowRISC/opentitan/issues/25456
=> [hw,ac_ranges,rtl] Compute denied range index using PPC

sw/device/tests/penetrationtests/firmware/sca/BUILD, sw/device/tests/penetrationtests/firmware/sca/aes_sca.c, sw/device/tests/penetrationtests/firmware/sca/kmac_sca.c, sw/device/tests/penetrationtests/firmware/sca/sha3_sca.c, sw/device/tests/penetrationtests/json/aes_sca_commands.h, sw/device/tests/penetrationtests/json/commands.h
Before this commit, the number of encryptions for the batch mode was received, e.g., for AES, using the aes_sca_data_t data structure, which is a 16*uint8_t array. As this is unecessary, replace it with just a single uint32.
=> [pentest] Read single int instead of array for num_enc

.github/workflows/ci.yml, sw/device/lib/testing/test_framework/ottf_common.ld
The LTO PR broke Darjeeling builds due to a linking error. This was not caught in CI due a stupid error in the CI job.
=> Emergency Darjeeling fix

hw/dv/sv/tl_agent/tl_host_driver.sv
This was my fault and I triggered the problem with commit [09af19f](https://github.com/lowRISC/opentitan/commit/09af19f7801964fc28262d9075459d6061949135). What I hadn't realised was how the flow worked when reset got asserted. Before my previous change:
- Suppose we're in the middle of send_a_request_body
- The reset is asserted and the DV_SPINWAIT_EXIT macro exits.
- We then go around the loop again, skipping the first wait.
- Then we set req_abort=1
- The next wait doesn't do anything (because we're in reset)
- We get back to the top of the loop, which exits because req_abort is true.
This is a bit mad! It would probably make more sense to drop out on the third bullet above, and that's what this commit does.
The reason my previous change broke things is that it switched the last …
=> [tl,dv] Fix infinite loop in tl_host_driver

hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson, sw/device/tests/BUILD, sw/device/tests/kmac_entropy_stress_test.c
Adds a test for the `chip_sw_kmac_entropy_stress` test point. This test configures the KMAC entropy mode in various ways and runs 5000 KMAC operations through the block. It checks for no errors and that the hash counter increments as expected.
Using the earlgrey_es_sival branch because that was the device used for development.
=> [sival/kmac] Add KMAC entropy stress test

sw/host/provisioning/orchestrator/tests/BUILD
The missing parenthesis clears all the tags, which makes the test be skipped regardless of the offline flag. The test should only be skipped if offline.
=> [sw,e2e] Fix provisioning e2e test CI tags

sw/device/tests/BUILD, sw/device/tests/mbx_smoketest.c
This PR ports the test software only, none of the DV. I've converted most of it to DT except for the size of the Mbox SRAM which I don't think is available yet.
=> [mbx] Port `mbx_smoketest` from `integrated_dev`

hw/dv/sv/tl_agent/tl_seq_item.sv
- declare do_compare method which will be automatically called by the uvm_object compare() method. This implementation is comparing all the fields of the sequence item.
=> [tlul,dv] Add do_compare function to tl_agent

hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
This builds on #26436. Once that is merged, only the second commit is in this PR. It switches to using out-of-block definitions in the scoreboard and adds careful documentation comments to explain what things are. No change to the code.
=> Pattgen out of block scoreboard

sw/device/lib/testing/flash_ctrl_testutils.c, sw/device/lib/testing/flash_ctrl_testutils.h, sw/device/lib/testing/test_framework/ottf_utils.h, sw/device/lib/testing/test_framework/status.c, sw/device/tests/BUILD, sw/device/tests/pattgen_ios_test.c, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c, sw/device/tests/sram_ctrl_scrambled_access_test.c, sw/device/tests/sysrst_ctrl_outputs_test.c, sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c
This introduce `OTTF_BACKDOOR_READ` macro which (hopefully) does everything correctly.
I converted all `flash_ctrl_testutils_backdoor_wait_update` users to use this. Marking as draft because there're much more backdoor users...
=> [ottf] introduce OTTF_BACKDOOR_READ macro

hw/top_darjeeling/dv/chip_sim_cfg.hjson, hw/top_darjeeling/dv/env/seq_lib/chip_sw_mbx_smoke_vseq.sv, hw/top_darjeeling/dv/env/seq_lib/chip_sw_soc_proxy_external_alerts_vseq.sv, hw/top_darjeeling/dv/env/seq_lib/chip_sw_soc_proxy_external_wakeup_vseq.sv, hw/top_darjeeling/dv/env/seq_lib/chip_sw_soc_proxy_gpio_vseq.sv, hw/top_darjeeling/dv/env/seq_lib/chip_sw_soc_proxy_smoke_vseq.sv
This PR provides some simple fixes to the DV side of `chip_sw_mbx_smoketest` allowing it to pass. The creation of orphaned soc_control and soc_status registers led to UVM warnings on the master branch, resulting in a test failure even after the software component had reported successful completion.
Clean up a few build warnings at the same time, in an effort to keep the build log clean so that we can spot any real problems; these are just probe/release calls that do not require the state of the affected signal.
=> [dv,chip] DV fixes for chip_sw_mbx_smoketest

sw/device/silicon_creator/lib/BUILD, sw/device/silicon_creator/lib/cert/dice_chain.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.h, sw/device/silicon_creator/lib/otbn_boot_services.c, sw/device/silicon_creator/rom_ext/imm_section/BUILD, sw/device/silicon_creator/rom_ext/imm_section/imm_section.c, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/host/tests/attestation/attestation_test.rs
This is an manual cherry-pick of #26456 to branch earlgrey_1.0.0.
Note that the otp commit is skipped since it's deprecated by #26532.
commit skipped: [sw] Add missing otp driver deps to imm_rom_ext
=> Cherry-pick to earlgrey_1.0.0: [sw,dice] Lockdown the attestation seed page to readonly

hw/dv/sv/dv_lib/dv_base_sequencer.sv
Just a small check to avoid null pointers if someone tries to create new agents and other components and forget to instantiate the configuration object.
=> [dv][fix] Minor fix in the dv_base_sequencer.sv

sw/device/lib/testing/BUILD, sw/device/lib/testing/ret_sram_testutils.c, sw/device/lib/testing/ret_sram_testutils.h, sw/device/tests/BUILD, sw/device/tests/alert_handler_lpg_clkoff_test.c, sw/device/tests/alert_handler_lpg_reset_toggle.c, sw/device/tests/alert_handler_lpg_sleep_mode_pings.c, sw/device/tests/clkmgr_off_peri_test.c, sw/device/tests/keymgr_derive_cdi_test.c, sw/device/tests/kmac_kmac_key_sideload_test.c, sw/device/tests/pwrmgr_all_reset_reqs_test.c, sw/device/tests/pwrmgr_deep_sleep_all_reset_reqs_test.c, sw/device/tests/pwrmgr_deep_sleep_all_wake_ups.c, sw/device/tests/pwrmgr_normal_sleep_all_reset_reqs_test.c, sw/device/tests/pwrmgr_random_sleep_all_reset_reqs_test.c, sw/device/tests/pwrmgr_random_sleep_all_wake_ups.c, sw/device/tests/rstmgr_alert_info_test.c, sw/device/tests/sensor_ctrl_alerts_test.c, sw/device/tests/sim_dv/alert_handler_lpg_sleep_mode_alerts.c, sw/device/tests/sim_dv/all_escalation_resets_test.c, sw/device/tests/sim_dv/data_integrity_escalation_reset_test.c, sw/device/tests/sim_dv/lc_ctrl_program_error.c, util/dtgen/dt_api.h.tpl
I've stolen two commits from here: https://github.com/lowRISC/opentitan/pull/26418
=> [rstmgr] Port `rstmgr_alert_info_test` to DT

hw/ip/prim/rtl/prim_assert.sv
I tweaked this assertion in commit b5b4087 (to allow a formal tool to see the assertion run to completion) but there is a chip-level test (`chip_sw_pwrmgr_sleep_power_glitch_reset`) which fails this assertion (with or without my change).
The test resets the block (which causes the FSM state to go back to its initial value) but the `until` operator doesn't complete, because:
- The property gets sampled on every posedge of `__clk` (this is because of the definition of `` `ASSERT``)
- In the failing test, we go into reset (putting the FSM back to its initial state) and then come out of reset.
- We then sample the property again. But it was never sampled when we were in reset so the `until` doesn't complete.
This commit tweaks the `until` so that it waits until the ```__name``_cond``` signal …
=> [prim,dv] Fix a failure mode for ASSERT_FPV_LINEAR_FSM

hw/ip/pattgen/rtl/pattgen_chan.sv
Motivated by reading the code while trying to review #26319 and interpret the vague testpoint description. This change clarifies the implementation of a pattgen channel to better match up with the spec documentation.
No functional change. The first two commits are minor RTL refactors, while the third extends the documentation comments throughout the new changes.
The documentation describes a FSM which does not exist in a canonical form within the module, but is practically implemented using the 'active' signal. Add a documentation comment to the code explaining this. I guess an alternative would be to change the RTL, but I wanted to keep the changes minimal for this changeset.
=> [pattgen,rtl] pattgen_chan cleanup

hw/ip/i2c/dv/sva/i2c_protocol_cov.sv
Made the covergroups names consistent and also add a label to the end of the i2c_protocol_cov_cg.
=> [i2c,dv] Covergroup naming consistency

hw/ip_templates/pwrmgr/util/dt.py, hw/ip_templates/rstmgr/defs.bzl.tpl, hw/ip_templates/rstmgr/util/BUILD.bazel.tpl, hw/ip_templates/rstmgr/util/dt.py, hw/ip_templates/rstmgr/util/ipconfig.py, hw/top_darjeeling/ip_autogen/pwrmgr/util/dt.py, hw/top_darjeeling/ip_autogen/rstmgr/defs.bzl, hw/top_darjeeling/ip_autogen/rstmgr/util/BUILD.bazel, hw/top_darjeeling/ip_autogen/rstmgr/util/dt.py, hw/top_darjeeling/ip_autogen/rstmgr/util/ipconfig.py, hw/top_earlgrey/ip_autogen/pwrmgr/util/dt.py, hw/top_earlgrey/ip_autogen/rstmgr/defs.bzl, hw/top_earlgrey/ip_autogen/rstmgr/util/BUILD.bazel, hw/top_earlgrey/ip_autogen/rstmgr/util/dt.py, hw/top_earlgrey/ip_autogen/rstmgr/util/ipconfig.py, hw/top_englishbreakfast/ip_autogen/pwrmgr/util/dt.py, hw/top_englishbreakfast/ip_autogen/rstmgr/defs.bzl, hw/top_englishbreakfast/ip_autogen/rstmgr/util/BUILD.bazel, hw/top_englishbreakfast/ip_autogen/rstmgr/util/dt.py, hw/top_englishbreakfast/ip_autogen/rstmgr/util/ipconfig.py, util/dtgen/dt_api.h.tpl, util/dtgen/dt_ip.c.tpl, util/dtgen/dt_ip.h.tpl, util/dtgen/helper.py
The intiial commits are from #26248. This PR adds information about the resets and provides a `rstmgr` extension.
**Additions to the DT**
The first requirement to expose the necessary information is that the list of resets for each IP needs to be exposed. This is done by creating a new list of reset nodes in `dt_api.h`:
```c
/**
* List of resets.
*
* Resets are guaranteed to be numbered consecutively from 0.
*/
typedef enum dt_reset {
kDtResetUnknown = 0, /**< Unknown reset */
kDtResetPorAon = 1, /**<  */
kDtResetLcSrc = 2, /**<  */
kDtResetSysSrc = 3, /**<  */
kDtResetPor = 4, /**<  */
kDtResetPorIo = 5, /**<  */
kDtResetPorIoDiv2 = 6, /**<  */
kDtResetPorIoDiv4 = 7, /**<  */
kDtResetPorUsb = 8, /**<  */
kDtResetLc = 9, /**<  */
kDtResetLcAon = 10, /**<  */
kDtResetLcIo = 11, /**<  */ …
```
=> [dtgen] Add rstmgr extension

hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson, sw/device/tests/BUILD, sw/device/tests/kmac_entropy_stress_test.c
Just two small modifications to `dif_kmac_sqeeze` and `dif_kmac_get_error` account for some changes to the kmac DIFs from the earlgrey_es_sival branch.
(cherry picked from commit 0336c6c81774b94c5c45f85737e81f60e977fd45)
=> Cherry-pick to master: [sival/kmac] Add KMAC entropy stress test

hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson, sw/device/tests/BUILD, sw/device/tests/kmac_entropy_stress_test.c
Just two small modifications to dif_kmac_sqeeze and dif_kmac_get_error account for some changes to the kmac DIFs from the earlgrey_es_sival branch.
(cherry picked from commit 0336c6c81774b94c5c45f85737e81f60e977fd45)
=> Cherry-pick to earlgrey_1.0.0: [sival/kmac] Add KMAC entropy stress test

sw/device/tests/BUILD, sw/device/tests/hmac_enc_test.c
Fix #26215
This PR ports the `hmac_enc_test` to use the devicetables API so that it no longer depends on Earlgrey-specific constants. The test remains passing on Earlgrey on FPGA (`fpga_cw310_rom_with_fake_keys`), and will compile for Darjeeling via
```sh
bazel build //sw/device/tests:hmac_enc_test_sim_dv --//hw/top=darjeeling
```
See the commit message for more details about replacing the `isr_testutils` API call.
=> [sw,multitop] port hmac_enc_test to devicetables

sw/device/silicon_creator/manuf/base/ft_personalize.c
Some SKUs build factory installed certs based on PROD diversifier. Since ROM_EXT and Owner FW cannot update these keys/certs on the next boot, perso must set them to PROD.
=> [perso] setup keymgr OwnerKey stage with PROD binding

hw/ip/prim_xilinx/rtl/prim_xilinx_ram_1p.sv
Different tool, different errors. Life is sad.
Let's remove the string, it's not in the parameter anyways.
=> [hw,prim_xilinx_ram_1p,rtl] Don't use string, the tools don't like it

util/dtgen/helper.py
I noticed that there is a discrepancy in the handling of non-muxed pads between the DT and the headers: the non-muxed pads in `pinmux.ios` are in facts all the DIOs from the perspective of the pinmux.
=> [dtgen] Fix handling of DIO pads

hw/vendor/lowrisc_ibex.lock.hjson, hw/vendor/lowrisc_ibex/doc/03_reference/verification.rst, hw/vendor/lowrisc_ibex/dv/cosim/cosim.h, hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv, hw/vendor/lowrisc_ibex/rtl/ibex_core.sv, hw/vendor/lowrisc_ibex/rtl/ibex_decoder.sv, hw/vendor/lowrisc_ibex/rtl/ibex_id_stage.sv, hw/vendor/lowrisc_ibex/rtl/ibex_register_file_fpga.sv
6e466c1504b61333d1b2ba85c69bff94b65e9284
* Verification should be done with ibex_cosim branch (Marno van der Maas)
* [cosim] Update comment on `set_mip` in Cosim interface (Greg Chadwick)
* [rtl] Remove low utility assertions (Greg Chadwick)
* [rtl] Flush pipe on all CSR modifications (Greg Chadwick)
* [rtl] Read csr_addr direct from instruction (Greg Chadwick)
* [ibex_core] Fix assertion when SecureIbex is false (Rupert Swarbrick)
* [ibex_register_file_fpga] Drop two confusing comments (Rupert Swarbrick)
=> Update lowrisc_ibex to lowRISC/ibex@6e466c15

sw/device/silicon_creator/rom_ext/imm_section/imm_section.c, sw/host/tests/attestation/attestation_test.rs
* #26533
The cherrypick PR #26533 introduces some fixes when cherrypick to earlgrey_1.0.0. This PR ports these differences back to master, including:
* Fix pubkey id hashing in attestation e2e test
* Set attestation seed flash scrambling/ecc before lockdown
=> Cherrypick #26533 diff to master: [sw,dice] Lockdown the attestation seed page to readonly

sw/device/lib/dif/dif_rstmgr.c, sw/device/lib/dif/dif_rstmgr.h, sw/device/tests/BUILD, sw/device/tests/rstmgr_sw_rst_ctrl_test.c
Fix #26228
This PR ports the `rstmgr_sw_rst_ctrl_test` to use the devicetables API so that it no longer depends on Earlgrey-specific constants. The test remains passing on Earlgrey in an FPGA (`fpga_cw310_rom_with_fake_keys`) environment, and will compile for Darjeeling via
```sh
bazel build --build_tests_only //sw/device/tests:rstmgr_sw_rst_ctrl_test_sim_dv --//hw/top=darjeeling
```
This PR is marked as a draft because it currently requires hardcoding the rstmgr SW Reset Requests per top. Once support for retrieving this information is added (via a devicetables IP extension), this PR will be accordingly updated and marked as ready.
=> [sw,multitop] Port `rstmgr_sw_rst_ctrl_test` to devicetables

sw/device/silicon_creator/manuf/base/BUILD, sw/device/silicon_creator/manuf/base/sram_ft_individualize.c, sw/host/opentitanlib/src/test_utils/rpc.rs, sw/host/provisioning/ft/BUILD, sw/host/provisioning/ft/src/main.rs, sw/host/provisioning/ft_lib/src/lib.rs, sw/host/provisioning/orchestrator/src/orchestrator.py, sw/host/provisioning/orchestrator/src/ot_dut.py, sw/host/provisioning/orchestrator/tests/e2e.sh, sw/host/provisioning/orchestrator/tests/e2e_option_flags.sh, sw/host/provisioning/ujson_lib/BUILD, sw/host/provisioning/ujson_lib/src/lib.rs, sw/host/tests/crypto/aes_nist_kat/src/main.rs
To facilitate bringup of manufacturing flows in DV and on ATE, this adds a flag `--log-ujson-payloads` to the E2E FT provisioning flow to print the UJSON payloads (from Host-->Device) as hexstrings to the console. This can be demonstrated by running:
```sh
bazel test --test_output=streamed --test_arg="--log-ujson-payloads" \
//sw/host/provisioning/orchestrator/tests:e2e_emulation_tpm_hyper310_test
```
CC: @benjbender
=> [manuf] add ability to log UJSON payloads to console

sw/device/silicon_creator/rom_ext/defs.bzl
ROM_EXT binaries were recently rereleased/resigned (in #26570). This rev's the version number for the next release.
=> [rom_ext] rev ROM_EXT version number

hw/ip/prim/rtl/prim_mubi_pkg.sv, util/design/data/prim_mubi_pkg.sv.tpl
- this function is similar to mubix_test_true_strict, but takes a logic as input instead of a mubix_t type.
=> [prim] Add mubix_logic_test_true_strict function

sw/host/provisioning/orchestrator/data/products.hjson
A1 and A2 share the same product ID.
=> [orchestrator] add A2 product ID to database

sw/device/silicon_creator/manuf/base/BUILD
This updates the perso FW offline signing rule to enable different SKU configs to share signature Bazel target locations.
=> [manuf,signing] enable SKU configs to share signature dirs

hw/dv/sv/tl_agent/seq_lib/tl_device_seq.sv
The sequence gained a parameter in c50fecfbb3e and the call to uvm_object_param_utils wasn't updated.
=> [dv] Fix call to uvm_object_param_utils in tl_device_seq

hw/ip/aon_timer/aon_timer.core, hw/ip/aon_timer/data/aon_timer.hjson, hw/ip/aon_timer/doc/interfaces.md, hw/ip/aon_timer/rtl/aon_timer.sv, hw/ip/aon_timer/rtl/aon_timer_reg_top.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv
This PR adds RACL support to the AON timer. RACL is disabled for this IP in both Darjeeling, Earlgrey, and Englishbreaksfast.
=> [hw,aon_timer,rtl] Add RACL support to AON timer

hw/ip/dma/dv/env/dma_seq_item.sv, hw/ip/dma/dv/env/dma_sys_tl_if.sv, hw/ip/dma/dv/env/seq_lib/dma_abort_vseq.sv, hw/ip/hmac/dv/cryptoc_dpi/hmac.c, hw/ip/hmac/dv/cryptoc_dpi/hmac_wrap.c
Fix up warnings in xcelium build of the DMA DV environment. This also addresses use of the non-LITE SHA functions from a 'LITE' context, which was functionally broken but the functions that do not explicitly specify the digest size appear not to be used now.
=> [dv,dma] Fix build warnings

sw/host/opentitanlib/src/io/uart.rs, sw/host/opentitanlib/src/rescue/mod.rs, sw/host/opentitanlib/src/rescue/serial.rs, sw/host/opentitanlib/src/rescue/xmodem.rs, sw/host/opentitantool/src/command/rescue.rs, sw/host/opentitantool/src/main.rs, sw/host/tests/ownership/flash_permission_test.rs, sw/host/tests/ownership/newversion_test.rs, sw/host/tests/ownership/rescue_limit_test.rs, sw/host/tests/ownership/rescue_permission_test.rs, sw/host/tests/ownership/transfer_lib.rs, sw/host/tests/ownership/transfer_test.rs, third_party/rust/Cargo.lock, third_party/rust/Cargo.toml, third_party/rust/crates/BUILD.bazel, third_party/rust/crates/BUILD.libusb1-sys-0.7.0.bazel, third_party/rust/crates/BUILD.rusb-0.9.4.bazel, third_party/rust/crates/defs.bzl
1. Refactor rescue into a trait.
2. Refactor rescue protocol creation.
3. Update the `rusb` crate.
=> [opentitanlib] Refactor rescue protocol creation

.github/workflows/ci.yml, hw/dv/tools/dvsim/sim.mk, hw/top_darjeeling/dv/tb/tb.sv, hw/top_darjeeling/rtl/autogen/chip_darjeeling_asic.sv, hw/top_darjeeling/rtl/autogen/chip_darjeeling_cw310.sv, hw/top_darjeeling/templates/chiplevel.sv.tpl, rules/opentitan/defs.bzl, sw/device/lib/dif/dif_pinmux.h, sw/device/lib/testing/pinmux_testutils.c, sw/device/lib/testing/pinmux_testutils.h, sw/device/lib/testing/test_framework/ottf_ld_top_config.ld, sw/device/lib/testing/test_rom/BUILD, sw/device/lib/testing/test_rom/test_rom.c, sw/device/lib/testing/test_rom/test_rom.ld, sw/device/lib/testing/test_rom/test_rom_start.S, sw/device/silicon_creator/lib/drivers/retention_sram.h, sw/device/tests/BUILD, sw/device/tests/rstmgr_alert_info_test.c
This PR recreates the SW fixes identified by @alees24 in #26088 in a way that is compatible with all tops. The only missing part is the issue with the VMEM file created for EG which is not compatible with DJ DV. See #26573. 
This is mostly a SW fix but it also contains a HW change to undo the hack that @alees24 had to apply to workaround the issue with the SW being linked at the wrong address.
=> Software + DV fixes for Darjeeling DV

hw/ip/pattgen/dv/env/seq_lib/pattgen_base_vseq.sv
I added this by accident when merging some tasks and Xcelium quite reasonably points out that it's a non-void function that's being called without looking at the return value.
Oops! Delete it. The code that comes from this is in update_size_for_channel.
=> [pattgen,dv] Get rid of dead code in pattgen_base_vseq

hw/ip_templates/rv_plic/rtl/rv_plic_gateway.sv.tpl, hw/top_darjeeling/ip_autogen/rv_plic/rtl/rv_plic_gateway.sv, hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_gateway.sv, hw/top_englishbreakfast/ip_autogen/rv_plic/rtl/rv_plic_gateway.sv
This behaviour is unchanged, but I think it's rather easier to read. The idea is that "set[i]" should be true if src_q[i] is true unless le_i[i] is true (so we're edge triggered) and src_q[i] is true (so le_i[i] was already true last cycle).
=> [rv_plic,rtl] Avoid an unnecessary ternary in a loop

sw/device/silicon_creator/lib/ownership/ownership.c, sw/device/silicon_creator/lib/ownership/ownership.h, sw/device/silicon_creator/lib/ownership/testdata/basic_owner.json5, sw/device/silicon_creator/rom_ext/data/rom_ext_e2e_testplan.hjson, sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/host/opentitanlib/src/chip/boot_svc.rs, sw/host/opentitanlib/src/chip/mod.rs, sw/host/opentitanlib/src/ownership/flash.rs, sw/host/opentitanlib/src/ownership/flash_info.rs, sw/host/opentitanlib/src/ownership/owner.rs, sw/host/tests/ownership/flash_permission_test.rs, sw/host/tests/ownership/transfer_lib.rs
This is a manual cherry-pick of #25097.
=> Cherry-pick to master: [ownership] Fix protect_when_active behavior

bazelisk.sh, hw/ip/otbn/dv/uvm/get-toolchain-paths.sh, rules/certificates.bzl, rules/host.bzl, rules/host_cpu.bzl, rules/quality.bzl, sw/host/opentitanlib/src/util/status.rs, third_party/crt/repos.bzl, third_party/rust/BUILD, third_party/rust/deps.bzl, third_party/rust/repos.bzl, util/prep-bazel-airgapped-build.sh
This allows both compiling opentitantool and images for the sival chips on hosts with ARM architecture. Before merging this we should adjust the release paths for crt, lowrisc toolchains and safe ftdi.
=> Add support for aarch64

hw/dv/sv/key_sideload_agent/key_sideload_agent.sv, hw/dv/sv/key_sideload_agent/key_sideload_agent_cov.sv, hw/dv/sv/key_sideload_agent/key_sideload_driver.sv, hw/dv/sv/key_sideload_agent/key_sideload_monitor.sv
A parameterised type needs this instead of just uvm_component_utils. Noticed by Verissimo and it's a pretty trivial fix.
=> [dv] Correctly use uvm_component_param_utils in key_sideload_agent

hw/ip/rv_dm/rtl/rv_dm_dmi_gate.sv
When no strap enable overwrite is possible (SecVolatileRawUnlockEn=0), the ordinary strap enable mechanism is still genuine. Don't assert that away.
=> [hw,rv_dm,rtl] Strap enable is genuinely used to ungate the DM

hw/dv/sv/cip_lib/seq_lib/cip_tl_host_single_seq.sv
- instr_type was never found enabled when running the sequence cip_tl_host_single_seq, this enables to see the EXECUTE command types on the bus on the top of READ and WRITE possibilities.
- this field is always set to MuBi4False by default but can be overriden by the user with an inline constraint when randomizing this sequence.
=> [tlul,dv] Randomize instr_type to see EXECUTE type

sw/device/silicon_creator/lib/cert/cert.c, sw/device/silicon_creator/rom_ext/rom_ext.c
We want to avoid having a `.data` section in ROM and ROM_EXT code.
1. By initializing the `lc_state` global variable, we add to a `.data` section.  Since this value is initialized very early in `rom_ext_init`, we don't need a explicit initializer.
2. The dice cert serial number check was using a staticly initialized data item to keep the ASN.1 prefix around.  Manually initializing this prefix in code requires fewer bytes than the static initializer and doesn't require the initializer to be in `.data` or `.rodata`.
=> Eliminate ROM_EXT `.data` sections

sw/device/tests/gpio_smoketest.c
The inputs were being sampled too soon in `test_gpio_write` on the expectation that the outputs would all be visible at the GPIO inputs almost immediately, and that all inputs would change simultaneously. Even in DV simulation that is not the case because the CDC modeling introduces single-cycle latency on a random subset of the input signals.
Introduce a single microsecond delay which, for all practical clock frequencies, will ensure that the inputs have stabilized by the time they are sampled.
=> [gpio] Delay sampling of GPIO inputs to accommodate synchronizers

hw/top_darjeeling/ip_autogen/ac_range_check/data/top_darjeeling_ac_range_check.ipconfig.hjson, hw/top_darjeeling/ip_autogen/alert_handler/data/top_darjeeling_alert_handler.ipconfig.hjson, hw/top_darjeeling/ip_autogen/clkmgr/data/top_darjeeling_clkmgr.ipconfig.hjson, hw/top_darjeeling/ip_autogen/gpio/data/top_darjeeling_gpio.ipconfig.hjson, hw/top_darjeeling/ip_autogen/otp_ctrl/data/top_darjeeling_otp_ctrl.ipconfig.hjson, hw/top_darjeeling/ip_autogen/pinmux/data/top_darjeeling_pinmux.ipconfig.hjson, hw/top_darjeeling/ip_autogen/pwrmgr/data/top_darjeeling_pwrmgr.ipconfig.hjson, hw/top_darjeeling/ip_autogen/racl_ctrl/data/top_darjeeling_racl_ctrl.ipconfig.hjson, hw/top_darjeeling/ip_autogen/rstmgr/data/top_darjeeling_rstmgr.ipconfig.hjson, hw/top_darjeeling/ip_autogen/rv_plic/data/top_darjeeling_rv_plic.ipconfig.hjson, hw/top_earlgrey/ip_autogen/alert_handler/data/top_earlgrey_alert_handler.ipconfig.hjson, hw/top_earlgrey/ip_autogen/clkmgr/data/top_earlgrey_clkmgr.ipconfig.hjson, hw/top_earlgrey/ip_autogen/flash_ctrl/data/top_earlgrey_flash_ctrl.ipconfig.hjson, hw/top_earlgrey/ip_autogen/gpio/data/top_earlgrey_gpio.ipconfig.hjson, hw/top_earlgrey/ip_autogen/otp_ctrl/data/top_earlgrey_otp_ctrl.ipconfig.hjson, hw/top_earlgrey/ip_autogen/pinmux/data/top_earlgrey_pinmux.ipconfig.hjson, hw/top_earlgrey/ip_autogen/pwrmgr/data/top_earlgrey_pwrmgr.ipconfig.hjson, hw/top_earlgrey/ip_autogen/rstmgr/data/top_earlgrey_rstmgr.ipconfig.hjson, hw/top_earlgrey/ip_autogen/rv_plic/data/top_earlgrey_rv_plic.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/clkmgr/data/top_englishbreakfast_clkmgr.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/flash_ctrl/data/top_englishbreakfast_flash_ctrl.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/gpio/data/top_englishbreakfast_gpio.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/pinmux/data/top_englishbreakfast_pinmux.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/pwrmgr/data/top_englishbreakfast_pwrmgr.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/rstmgr/data/top_englishbreakfast_rstmgr.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/rv_plic/data/top_englishbreakfast_rv_plic.ipconfig.hjson, util/topgen.py
The GPIO was probably missed in https://github.com/lowRISC/opentitan/pull/26541 (it was added to ipgen in between). Lets add that to the list of uniquified IPs.
=> [topgen] Add GPIO to the list of uniquified ipgen IPs

util/ipgen/renderer.py
When rendering an out-of-tree IP with ipgen, the uniquified_modules might not be defined in the IP description. Return an empty dict when this is not defined to not error out.
=> [ipgen] Return empty dict when uniquified_modules not defined

sw/host/hsmtool/src/commands/ecdsa/export.rs, sw/host/hsmtool/src/commands/ecdsa/import.rs, sw/host/hsmtool/src/commands/rsa/export.rs, sw/host/hsmtool/src/commands/rsa/import.rs, sw/host/hsmtool/src/util/wrap.rs, sw/host/provisioning/orchestrator/README.md
The HSM used in provisioning infrastructure uses a custom mechanism identifier (`CKM_AES_KWP = (CKM_VENDOR_DEFINED + 0x171)`) even though the implementation follows the RFC 3394 and 5649 specifations.
The `CKM_AES_KWP` implemented by Thales is also equivalent to the KWP algorithm specified by NIST SP 800-38F.
This change adds a custom `Wrap::VendorThalesAesKwp` mechanism to `hsmtool` to be able to wrap/unwrap private keys with `AES_KWP`.
=> [hsmtool] Add vendor specific AES_KWP mechanism

hw/dv/sv/dv_utils/dv_macros.svh
- Fix DV_WAIT_TIMEOUT macro to report error when set (before it was not reporting anything!)
- Add REPORT_FATAL_ argument to some macros to allow to log uvm_error instead or uvm_fatal
=> [dv_utils] Fix and improvements

hw/dv/sv/tl_agent/tl_agent_pkg.sv
- create 2 functions in the package to extract the MSB and LSB bit positions of the instr_type field from tl_a_user.
=> [tlul,dv] Add func to return intr_type bit pos

rules/opentitan/cc.bzl, rules/opentitan/exec_env.bzl, rules/opentitan/providers.bzl, rules/opentitan/sim_dv.bzl
This is a semi-hack to enable Darjeeling DV: when building the sim_dv firmware image, create both a 32-bit and 64-bit VMEM so that the DV env can pickup whichever it likes. This requires a small change to how files are exposed (see commit).
=> Final software fixes for Darjeeling DV 

sw/host/hsmtool/src/util/attribute/attr.rs
Besides `CKA_VALUE` There are aother attributes that may be sensitive and should not be accessed if `CKA_SENSITIVE` is set to true.
This change adds the `AttributeMap::sensitive_attrs` static function to get a manually compiled list of sensitive attributes.
The `AttributeMap:from_object` method was refactored to properly handle potentially sensitive fields.
=> [hsmtool] Generalize handling of sensitive attributes in attrs.rs.

sw/device/silicon_creator/manuf/base/sram_ft_individualize.c, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
This removes noisy console prints during FT individualization binary execution. This is to optimize test execution in ATE environment.
Note: this depends on #26648, only review the last commit.
=> [manuf] remove noisy console prints during individualize

sw/device/silicon_creator/lib/boot_data_functest.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.h, sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc, sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.h, sw/device/silicon_creator/lib/ownership/ownership_key.c
Use bitfields to lay out the flash permissions and configuration structures exactly as the registers in the flash_ctrl driver.  By using this arrangemnt, we can save 470 bytes over all calls for flash configuration.
=> [flash_ctrl] Optimize the perms/config structs

sw/device/lib/dif/dif_pwrmgr.c, sw/device/lib/dif/dif_pwrmgr.h, sw/device/silicon_creator/rom/e2e/retention_ram/BUILD, sw/device/silicon_creator/rom/e2e/retention_ram/rom_e2e_ret_ram_keep_test.c, sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_wakeup_test.c, sw/device/tests/BUILD, sw/device/tests/alert_handler_lpg_sleep_mode_pings.c, sw/device/tests/alert_handler_reverse_ping_in_deep_sleep_test.c, sw/device/tests/i2c_target_test.c, sw/device/tests/pwrmgr_sleep_disabled_test.c, sw/device/tests/pwrmgr_smoketest.c, sw/device/tests/rv_dm_access_after_wakeup.c, util/make_new_dif/templates/dif_autogen.c.tpl, util/make_new_dif/templates/dif_autogen.h.tpl
This PR continues the work of #26389 to get rid of all usage of hardcoded wakeup constants (e.g. `kDifPwrmgrWakeupRequestSourceFive`). This requires to go through tests one and by one and use the new DIF function to get the wakeup bitmap. At the same time, port (partially or totally) the tests to DT.
Uses #26279 and part of  #26389
=> [multitop] Port various tests to pwrmgr multitop

sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/chip/boot_svc.rs, sw/host/opentitanlib/src/chip/helper.rs, sw/host/opentitanlib/src/crypto/ecdsa.rs, sw/host/opentitanlib/src/crypto/spx.rs, sw/host/opentitanlib/src/ownership/misc.rs, sw/host/opentitanlib/src/ownership/mod.rs, sw/host/opentitanlib/src/ownership/owner.rs, sw/host/opentitanlib/src/ownership/signature.rs, sw/host/opentitantool/src/command/ownership.rs, sw/host/opentitantool/src/command/rescue.rs, sw/host/tests/ownership/transfer_lib.rs
1. Create a DetachedSignature structure that can hold large signature entities.  Include a `command` word that identifies which entity this signature is for (e.g. ownership-unlock, ownership-activate, or ownership configuration) and a nonce that can be used to match the signature with the current command.
2. Update the signing helper functions to accept an algorithm type and both ECDSA and SPX keys.  Sign with the key appropriate to the algorithm type.
3. Plumb the return-type changes through to the opentitantool commands and ownership transfer testlib.
=> [opentitanlib] Prepare detached signatures for ownership

hw/top_darjeeling/dv/env/seq_lib/chip_sw_gpio_vseq.sv, sw/device/tests/sim_dv/BUILD, sw/device/tests/sim_dv/gpio_test.c
Modifications to bring up `chip_sw_gpio` on Darjeeling T-L. Introduce a delay between writing outputs and reading them back to support different clock frequencies, clock domain crossings, and randomized CDC delays.
Update: required a small modification to the DV sequence to accommodate the DIO pins of Darjeeling.
=> [gpio,darjeeling] Fixes for gpio_test on Darjeeling

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv, hw/dv/sv/cip_lib/seq_lib/cip_tl_host_single_seq.sv, hw/ip/rv_dm/dv/env/seq_lib/rv_dm_buffered_enable_vseq.sv
- The PR #26631 introduced randomizable instr_type variable. But this change was not compatible with the task tl_access_sub, neither with the rv_dm_buffered_enable_vseq sequence. THey have been updatated to fit with this new way.
- And the field instr_type declaration has to be changed from mubi4_t to a bit vector as some sequences require to have this variable being randomized with some erroneous values.
=> [tlul,dv] Fix seq calling cip_tl_host_single_seq

hw/ip_templates/ac_range_check/dv/env/ac_range_check_dut_cfg.sv, hw/ip_templates/ac_range_check/dv/env/ac_range_check_env_pkg.sv.tpl, hw/ip_templates/ac_range_check/dv/env/ac_range_check_scoreboard.sv, hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_base_vseq.sv, hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_common_vseq.sv, hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv, hw/ip_templates/ac_range_check/dv/tests/ac_range_check_base_test.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_dut_cfg.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env_pkg.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scoreboard.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_base_vseq.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_common_vseq.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/tests/ac_range_check_base_test.sv
**Main changes**
- Add prediction and comparison to the scoreboard
- Create constrained random sequences to cover most of the range check registers capabilities
**Still remaining**
According to the smoke test definition from the testplan [ac_range_check_smoke](https://opentitan.org/book/hw/top_darjeeling/ip_autogen/ac_range_check/data/ac_range_check_testplan.html#ac_range_check_smoke):
- Now most of the `RANGE_*` registers are configured randomly (with constraints), except the `log_denied_access` field from `RANGE_PERM` reg.
- Another points to mention: 
- TL transaction `mask` is always set to 4'hF.
- TLUL errors are not checked.
=> [ac_range_check,dv] Sequence and scoreboard for smoke test

hw/ip_templates/clkmgr/defs.bzl.tpl, hw/ip_templates/clkmgr/util/BUILD.bazel.tpl, hw/ip_templates/clkmgr/util/dt.py, hw/ip_templates/clkmgr/util/ipconfig.py, hw/top_darjeeling/ip_autogen/clkmgr/defs.bzl, hw/top_darjeeling/ip_autogen/clkmgr/util/BUILD.bazel, hw/top_darjeeling/ip_autogen/clkmgr/util/dt.py, hw/top_darjeeling/ip_autogen/clkmgr/util/ipconfig.py, hw/top_earlgrey/ip_autogen/clkmgr/defs.bzl, hw/top_earlgrey/ip_autogen/clkmgr/util/BUILD.bazel, hw/top_earlgrey/ip_autogen/clkmgr/util/dt.py, hw/top_earlgrey/ip_autogen/clkmgr/util/ipconfig.py, hw/top_englishbreakfast/ip_autogen/clkmgr/defs.bzl, hw/top_englishbreakfast/ip_autogen/clkmgr/util/BUILD.bazel, hw/top_englishbreakfast/ip_autogen/clkmgr/util/dt.py, hw/top_englishbreakfast/ip_autogen/clkmgr/util/ipconfig.py, sw/device/lib/dif/dif_clkmgr.c, sw/device/lib/dif/dif_clkmgr.h, sw/device/tests/kmac_idle_test.c
This extension provides the list of gateable and hintable clocks.
**Design of the clkmgr extension**
An important information needed to operate the clkmgr is the list of software gateable and hintable clocks. With the DT information, exposing the information is easy:
- it is possible to query the number of software gateable/hintable clocks,
- it is possible to query for clock which module instance it controls.
The API looks like this:
```c
/**
* Get the number of software gateable clocks.
*
* @param dt Instance of clkmgr.
* @return Number of gateable clocks.
*/
size_t dt_clkmgr_sw_clock_count(dt_clkmgr_t dt);
/**
* Get the instance ID of a gateable clock.
*
* The wakeup sources are ordered as they appear in the registers.
*
* @param dt Instance of clkmgr.
* @param idx Index of the …
```
=> [clkmgr] Add DT extension

util/dtgen/dt_ip.h.tpl, util/dtgen/helper.py, util/reggen/BUILD, util/reggen/feature.py, util/reggen/ip_block.py
These can be used to enable/disable code when two tops have the same IP but with different features and helps avoid hard-coding top names.
None of our current tests need this, but I think it will be useful if e.g. AES gains GCM or I2C gains multi-host.
Maybe `keymgr` and `keymgr_dpe` could share more code and use a `DPE` feature? I'm not sure how similar they are.
`#define`s were chosen over function(s) to avoid having to `#include` unsupported testutils.
Example output:
```c
/**
* List of supported hardware features.
*/
#define OPENTITAN_UART_HAS_PARITY 1
#define OPENTITAN_UART_HAS_LINE_LOOPBACK 1
#define OPENTITAN_UART_HAS_SYSTEM_LOOPBACK 1
#define OPENTITAN_UART_HAS_BAUD_RATE_CONTROL 1
#define OPENTITAN_UART_HAS_LINE_BREAK 1
#define OPENTITAN_UART_HAS_FIFO_INTERRUPTS 1
```
=> [dt] Expose IP hardware features in DT headers

hw/ip/prim_generic/prim_generic_otp.core, hw/ip_templates/otp_ctrl/otp_ctrl_prim_reg_top.core.tpl, hw/top_darjeeling/ip_autogen/otp_ctrl/otp_ctrl_prim_reg_top.core, hw/top_earlgrey/ip_autogen/otp_ctrl/otp_ctrl_prim_reg_top.core
This moves the generic to top-specific dependency down to prim_generic_otp core, which is an area that will need changes anyway.
=> [fusesoc,otp_ctrl] Change otp_ctrl_prim_reg_top core to template

hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv, hw/ip/tlul/rtl/tlul_request_loopback.sv
If the RAZWI response and the ordinary response of the TLUL port need to be served at the same time, one is currently dropped. Fix this by introducing a FIFO on the RAZWI response, which read port is set to 0 when an SRAM response is served.
Imagine SRAM control is fed with valid read requests. There are multiple outstanding requests in flight. Then, there is an invalid access, i.e, a ACL violation, which request ist looped back. If that happens at the same cycle an outstanding response is served, one is dropped, which causes a TLUL hang.
=> [hw,tlul_request_loopback,rtl] Avoid dropping responses by enqueuing the RAZWI response

sw/device/lib/testing/test_rom/test_rom_start.S
Darjeeling AST model still requires initialization because otherwise the oscillator clocks will not stabilize and test timings will be much more variable/unpredictable, leading to failures.
=> [test_rom] Initialilze AST on Darjeeling

sw/device/silicon_creator/lib/error.h, sw/device/silicon_creator/lib/ownership/owner_block.c, sw/device/silicon_creator/lib/ownership/owner_verify.c, sw/device/silicon_creator/lib/rescue/rescue_xmodem.c, sw/device/silicon_creator/lib/rescue/xmodem.c, sw/device/silicon_creator/lib/rescue/xmodem.h, sw/host/tests/xmodem/xmodem.rs
1. A loop variable of type `size_t` was being passed to `launder32` which accepts `uint32_t`.
2. There was a potential out-of-bounds access when receiving an xmodem frame.  Check that the buffer has enough space to receive the next frame.
=> [ownership, rescue] Fix errors

hw/top_darjeeling/dv/env/seq_lib/chip_sw_uart_rand_baudrate_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_uart_rand_baudrate_vseq.sv, sw/device/lib/testing/test_framework/ottf_utils.h, sw/device/tests/uart_tx_rx_test.c
This PR fixes the following failing Earl Grey DV top-level tests:
- chip_sw_uart_tx_rx_alt_clk_freq
- chip_sw_uart_tx_rx_alt_clk_freq_low_speed
- chip_sw_uart_rand_baudrate
The `sim_dv` targets expect to be able to override the clock frequency and target baud rate of the UART peripheral under test in order to cover a wider range of sampling ratios and phases (= NCO values).
Explicitly widen the parameters to 64 bits before using the streaming operators because otherwise one simulator replicates the MS byte whilst another zeroes the additional bytes. This is done in both the Earl Grey and Darjeeling test environments but presently the software has not been ported to Darjeeling.
=> [uart] Fix uart_tx_rx_alt_clk/rand_baudrate in DV sim

hw/top_darjeeling/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD
Update some of the configuration files for both Earl Grey and Darjeeling to reflect altered test locations.
Make `example_...` tests build for Darjeeling by adding it as a valid target.
=> [dv] A few build fixes for sim_dv targets

hw/dv/sv/dv_utils/dv_macros.svh
This was inspired by a lint warning from Verissimo about the fact that we weren't looking at the result of try_get(). But we can structure things a bit differently, solving the problem and simplifying the code too. Do that!
=> [dv] Simplify DV_EOT_PRINT_TLM_FIFO_CONTENTS macro

hw/top_darjeeling/rtl/autogen/top_racl_pkg.sv, hw/top_earlgrey/rtl/autogen/top_racl_pkg.sv, hw/top_englishbreakfast/rtl/autogen/top_racl_pkg.sv, util/topgen/templates/top_racl_pkg.sv.tpl
Since SystemVerilog structs go from msb to lsb, this layout didn't match the register definitions. We *could* teach everything to do the reversal, but it's confusing for a reader. Switch things round now.
=> [racl_ctrl,rtl] Re-order racl_policy_t to match the register

hw/ip_templates/ac_range_check/dv/ac_range_check_sim_cfg.hjson.tpl, hw/top_darjeeling/ip_autogen/ac_range_check/dv/ac_range_check_sim_cfg.hjson
Fixes the weekly Darjeeling regression after #26645 and #26688.
This didn't use the correct Python fstring format required to properly format in `module_instance_name`: Mako was escaping the format in the string by default, which was leading to errors in regressions where the ac_range_check sim_cfg HJSON could not be parsed by dvsim due to the unsubstituted `{module_instance_name}` appearing as an unknown, unexpanded wildcard.
=> [acrc,dv] Fix Mako formatting in sim_cfg HJSON template

sw/device/silicon_creator/manuf/base/flash_info_permissions.h, sw/device/silicon_creator/manuf/base/sram_cp_provision_functest.c
Early in manufacturing, the ATE cannot write to flash info page 0 with ECC enabled. This removes ECC from this page.
=> [manuf] remove ECC from flash info page 0

hw/ip/spi_device/rtl/spi_device.sv, hw/ip/spi_host/rtl/spi_host_window.sv, hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/doc/interfaces.md, hw/ip/sram_ctrl/rtl/sram_ctrl.sv, hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_darjeeling/rtl/autogen/top_racl_pkg.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/lint/top_earlgrey.waiver, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_earlgrey/rtl/autogen/top_racl_pkg.sv, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/lint/top_englishbreakfast.vbl, hw/top_englishbreakfast/lint/top_englishbreakfast.waiver, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv, hw/top_englishbreakfast/rtl/autogen/top_racl_pkg.sv, hw/top_englishbreakfast/top_englishbreakfast.core, util/raclgen/lib.py, util/topgen/templates/top_racl_pkg.sv.tpl, util/topgen/templates/toplevel_racl_pkg_parameters.tpl
This PR makes RACL ranges more flexible by using signals instead of parameters for the ranges and removing the power-of-two constraint.
Since RACL is still disabled for sram_ctrl (on darjeeling, earlgrey, englishbreakfast) it has no effects.
=> [RACL] Allow non-napot and non-parameter racl ranges

hw/ip/prim/prim_alert_to_diff.core, hw/ip/prim/prim_diff_encode.core, hw/ip/prim/prim_diff_to_alert.core, hw/ip/prim/rtl/prim_alert_to_diff.sv, hw/ip/prim/rtl/prim_diff_encode.sv, hw/ip/prim/rtl/prim_diff_to_alert.sv
A similar module was already in the integrated_dev branch. This adds additional buffers to avoid optimization.
This PR also adds two prims to convert the alert of an IP to a differentially encoded signal and then back to an alert. This is helpful, when you use an IP out-of-tree, in a different design unit, and do not want to distribute clock/rst meta information along the system.
Decoding the differentially encoded signal intentionally does not use prim_diff_decode. Instead, it treats any signal togelling as an alert.
=> [hw,prim_diff_encode,rtl] Add primitive to differentially encode a signal

hw/ip_templates/rv_plic/fpv/tb/coverage_waivers.tcl.tpl, hw/top_darjeeling/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_earlgrey/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
This PR:
1) Adds waivers for the undetectable statement coverage.
2) Removes the chunk of code in coverage_waivers.tcl which is no longer required. [#26559](https://github.com/lowRISC/opentitan/pull/26559)
=> Undetectable statement coverage and exclusion of a non-required waiver and supporting assertion

util/ipgen/README.md
The syntax highlighting in Emacs looked awry :-)
=> [ipgen,doc] Add a missing back-tick in README.md

hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv, hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv
We don't need to wait for the device to decide squashing the request. We can do that without knowing that. This breaks a combinational loop where in the user of the adapter has a dependency on req_o on the gnt_i signal.
=> [hw,tlul_adapter_*_racl,rtl] Don't factor a_ready in squash decission

sw/device/lib/base/macros.h, sw/device/silicon_creator/lib/drivers/BUILD, sw/device/silicon_creator/lib/drivers/pinmux.c, sw/device/silicon_creator/lib/drivers/pinmux.h, sw/device/silicon_creator/lib/drivers/stdusb.c, sw/device/silicon_creator/lib/drivers/stdusb.h, sw/device/silicon_creator/lib/drivers/usb.c, sw/device/silicon_creator/lib/drivers/usb.h, sw/device/silicon_creator/lib/drivers/usb_functest.c, sw/device/silicon_creator/lib/error.h, sw/device/tests/kmac_entropy_stress_test.c, sw/host/tests/chip/usb/BUILD, sw/host/tests/chip/usb/silicon_creator_harness.rs
Create a small USB driver meant to be used in silicon_creator code.
1. Implement a basic no-interrupts driver for the OpenTitan USB
peripheral.  The driver manages the USB peripheral buffers, endpoint
transfers and SETUPDATA on the control endpoint.  Higher level
protocols register a callback function with the endpoints.
2. Implement a standard USB control endpoint handler.  This handler
should be called in response to any SETUPDATA requests on endpoint
zero.
3. Add a basic test to check device enumeration and configuration and
data transfers.
=> [silicon_creator] Add a small USB driver 

sw/device/tests/usbdev_setuprx_test.c
The DPI model spends slightly over one bus frame in the Bus Reset state after detecting a device connection. This is now 1ms since the duration of the bus frame was originally shortened artificially to reduce simulation times. It was subsequently extended to model the real USB.
With a 1ms timeout the test `usbdev_setuprx` has been observed to fail sometimes because the software gives up just as the transmission of the first SOF packet commences. Increase the timeout to 1.5 USB bus frames.
=> [usbdev] DPI model spends a little over 1ms in Bus Reset

hw/ip/lc_ctrl/data/lc_ctrl.hjson, hw/ip/lc_ctrl/lc_ctrl.core, hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/ip_templates/alert_handler/data/alert_handler.hjson.tpl, hw/ip_templates/alert_handler/data/alert_handler.tpldesc.hjson, hw/ip_templates/alert_handler/rtl/alert_handler.sv.tpl, hw/ip_templates/rv_core_ibex/data/rv_core_ibex.hjson.tpl, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, hw/top_darjeeling/ip_autogen/alert_handler/data/alert_handler.hjson, hw/top_darjeeling/ip_autogen/alert_handler/data/top_darjeeling_alert_handler.ipconfig.hjson, hw/top_darjeeling/ip_autogen/alert_handler/rtl/alert_handler.sv, hw/top_darjeeling/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.hjson, hw/top_earlgrey/ip_autogen/alert_handler/data/top_earlgrey_alert_handler.ipconfig.hjson, hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler.sv, hw/top_earlgrey/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv, util/topgen.py
All ips that instantiate prim_esc_receiver need to get a couple parameters from alert_handler. Pass them to these ips via regular parameter overrides.
Reggen only allows local params to determine CSR sizes. This means we need to create both a regular and a local parameter in alert_handler set to the same value.
=> [ipgen,alert_handler] Expose esc_prim_receiver parameters

hw/ip/prim/rtl/prim_ram_1p_scr.sv, hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/doc/interfaces.md, hw/ip/sram_ctrl/doc/theory_of_operation.md, hw/ip/sram_ctrl/rtl/sram_ctrl.sv, hw/ip/sram_ctrl/rtl/sram_ctrl_pkg.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv
This PR adds the ability to correct single-bit errors using the ECC on the data. Double bit errors are only detected.
When there is a single bit error, it is corrected and logged via the new error log, which can be connected to a RAS error log for example. Double errors are passed to the requester but also logged to the error log. The error correction happens via a new piped ECC stage, which increases the latency of the sram_ctrl adapter.
In DJ and EG, this feature is not not used. The error log is tied off.
=> [hw,sram_ctrl,rtl] Ability to correct single-bit errors and log error

hw/ip/aon_timer/data/aon_timer.hjson, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/ip_autogen/pwrmgr/data/top_darjeeling_pwrmgr.ipconfig.hjson, hw/top_darjeeling/ip_autogen/rstmgr/data/rstmgr.hjson, hw/top_darjeeling/ip_autogen/rstmgr/data/top_darjeeling_rstmgr.ipconfig.hjson, hw/top_darjeeling/ip_autogen/rstmgr/doc/registers.md, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/ip_autogen/pwrmgr/data/top_earlgrey_pwrmgr.ipconfig.hjson, hw/top_earlgrey/ip_autogen/rstmgr/data/rstmgr.hjson, hw/top_earlgrey/ip_autogen/rstmgr/data/top_earlgrey_rstmgr.ipconfig.hjson, hw/top_earlgrey/ip_autogen/rstmgr/doc/registers.md, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/ip_autogen/pwrmgr/data/top_englishbreakfast_pwrmgr.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/rstmgr/data/rstmgr.hjson, hw/top_englishbreakfast/ip_autogen/rstmgr/data/top_englishbreakfast_rstmgr.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/rstmgr/doc/registers.md
No RTL change, but the changes propagates through topgen to several hjson files and register documentation.
=> [hw,aon_timer] Fix typo in documentation

sw/host/opentitanlib/src/dif/lc_ctrl.rs
Without this, it's impossible to know the list of valid values when trying to read a register via `life-cycle read-reg` which makes the command read hard to use.
There are probably other instances of this in opentitanlib.
=> [opentitanlib] Derive clap::ValueEnum for LcCtrlReg

sw/device/silicon_creator/rom_ext/e2e/handoff/BUILD, sw/device/silicon_creator/rom_ext/e2e/handoff/epmp_print.c, sw/device/silicon_creator/rom_ext/imm_section/imm_section_epmp.c
Traditionally, we placed the RvDm region in ePMP entry 13 and the memory-mapped flash in region 12.
This was reversed because it would allow for one more ToR region when RvDM is not in use, however downstream customers applications may depend on a specific ePMP configuration when their firmware starts.
The customer is free to re-arrange ePMP as they wish, so a configuration with an extra ToR entry is still possible as long as the customer programs the proper ePMP arragement.
=> [rom_ext] Order the ePMP as expected by customers

rules/otp.bzl
This is to be able to maintained an ordered list of alert parameters matching the layout of the alert_handler configuration. Otherwise buildifier will want to sort the parameters if set via `kwargs`.
=> [bazel/otp] Add ordered_params to ot_alert_classification.

sw/host/opentitanlib/src/tpm/driver.rs
When transmitting large TPM commands, the AP is supposed to inspect the "burstCount" field of the TPM STS register, in order to determine how many bytes the TPM can accept in a single SPI/I2C transfer.
Our code was first hard-coded to 32 bytes, later changed to 64 bytes.  Neither suited every legacy TPM implementation at Google.
In order to be able to handle various TPM implementation, this patch makes the code use whatever is advertised in burstCount.  (It does not re-inspect the STS register between each block of bytes, assuming instead that the TPM has a fixed-size buffer.)
=> [opentitanlib] Respect TPM burstCount

sw/device/silicon_creator/manuf/base/sram_ft_individualize.c
This was checking the AST patch address regardless if it was set or not.
=> [individualize] only check AST patch if it is set

sw/device/lib/base/status.c, sw/device/lib/runtime/print.c, sw/device/lib/runtime/print_unittest.cc
1. Fix potential `filename` out of bound access.  Although it's rarely to have filename's length be less than three, we don't have this kind of check.
2. Fix status serialization/deserialization inconsistency. Although it's rarely to have the module identifier contains "\\" character, we still want to serialize the module identifier properly in this case.
=> [ujson] Fix module identifier serialization

hw/ip/otp_ctrl/data/otp_ctrl_img.c.tpl, sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.h
Enabling scrambling and ECC for the boot data info pages during individualization was causing perso bootstrap to fail.
This is because ROM attempts to read the boot data before it has been initialized, causing integrity errors.
The solution is to skip boot data during individualization and apply it during perso, which is when the boot data is written for the first time.
=> [manuf] Initialize boot data cfg OTP during perso.

.github/workflows/cherrypick.yml
The note will look like this:
> [!IMPORTANT]
> This automated pull request cannot trigger CI tests itself.
>
> Please add the `CI:Rerun` label to trigger them manually before merging.
=> [ci] Add note about triggering CI for backports

hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv
This fixes #26588 as well as the value stored in the `log_status.deny_range_index` CSR field.
=> [ac_range_check/rtl] Fix permission checking and deny index

hw/ip_templates/racl_ctrl/data/racl_ctrl.hjson.tpl, hw/ip_templates/racl_ctrl/rtl/racl_ctrl.sv.tpl, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/ip_autogen/racl_ctrl/data/racl_ctrl.hjson, hw/top_darjeeling/ip_autogen/racl_ctrl/doc/interfaces.md, hw/top_darjeeling/ip_autogen/racl_ctrl/doc/registers.md, hw/top_darjeeling/ip_autogen/racl_ctrl/rtl/racl_ctrl.sv, hw/top_darjeeling/ip_autogen/racl_ctrl/rtl/racl_ctrl_reg_pkg.sv, hw/top_darjeeling/ip_autogen/racl_ctrl/rtl/racl_ctrl_reg_top.sv, hw/top_darjeeling/ip_autogen/rv_plic/data/rv_plic.hjson, hw/top_darjeeling/ip_autogen/rv_plic/data/top_darjeeling_rv_plic.ipconfig.hjson, hw/top_darjeeling/ip_autogen/rv_plic/rtl/rv_plic.sv, hw/top_darjeeling/ip_autogen/rv_plic/rtl/rv_plic_reg_pkg.sv, hw/top_darjeeling/ip_autogen/rv_plic/rtl/rv_plic_reg_top.sv, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_darjeeling/sw/autogen/chip/top_darjeeling.rs, hw/top_darjeeling/sw/autogen/top_darjeeling.c, hw/top_darjeeling/sw/autogen/top_darjeeling.h, util/make_new_dif/templates/dif_autogen.c.tpl
This PR adds interrupts to racl_ctrl.
The documentation will follow in a later PR (after #26592 is merged) but is tracked in #26720 in the meanwhile.
This PR allows notifying e.g. the ibex core when a RACL error occurred via an interrupt. It is disabled by default but can enabled via software. Interrupts are necessary because the device maintaining the RACL policies also wants to monitor for RACL errors that were triggered by other devices. Interrupts allow to do this more efficiently without having to continuously poll the racl_ctrl registers.
=> [racl_ctrl] Add interrupt to racl_ctrl

sw/device/lib/crypto/drivers/entropy.c, sw/device/silicon_creator/lib/base/sec_mmio.c, sw/device/silicon_creator/lib/drivers/otbn.c
1. In `sec_mmio` and `otbn`, some variables of type `size_t` were being passed to `launder32` which accepts `uint32_t`.
2. In `entropy`, the `config->alert_threshold` is `uint16_t` type. It will be promoted to `int32_t` by the `~` operator. However, `bitfield_field32_write` accepts `uint32_t` type. This commit converts the `config->alert_threshold` to `uint32_t` first.
=> [rom_ext] Fix type errors of drivers used in the immutable section.

hw/ip_templates/pwm/data/pwm.hjson.tpl
The available number of outputs need to be templatized with the ipgen parameter. No change for Earlgrey, since the default is 6 anyways.
=> [hw,pwm,rtl] Fix PWM hjson template

sw/device/silicon_creator/rom/e2e/BUILD, sw/device/tests/BUILD, sw/device/tests/csrng_smoketest.c, sw/device/tests/hmac_enc_idle_test.c, sw/device/tests/hmac_smoketest.c, sw/device/tests/kmac_smoketest.c, sw/device/tests/otbn_smoketest.c, sw/device/tests/otp_ctrl_smoketest.c
This PR just updates a number of the very simple smoke tests of internal blocks to work on Darjeeling as well as Earl Grey, using DT.
HMAC smoketest is ported first, and then the other tests follow on accordingly, making changes in the same manner, so hopefully only the first two commits really need any appreciable attention.
Modifications have been tested in both Earl Grey and Darjeeling top-level DV simulations.
=> [darjeeling] Port a number of the simple smoketests to Darjeeling DV

sw/device/tests/BUILD, sw/device/tests/sram_ctrl_smoketest.c
Port the sram_ctrl_smoketest to use DT and perform bring up on Darjeeling.
Generalize the code to support a variable number of SRAM Controller instances. kDtSramCtrlMain still needs to be treated as special to avoid corrupting the main SRAM content.
Overlap the testing of the individual SRAM Controller instances to increase the chance of catching an interactions/crosstalk.
Test thus now exercises the mailbox SRAM controller on Darjeeling.
=> [sram_ctrl] Update sram_ctrl_smoketest for Darjeeling using DT

hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv
Limit the range_base/limit constraints to only some ranges. This has the effect of revealing the RTL bug raised in issue #26588 and fixed in PR #26589.
=> [ac_range_check,dv] Fix smoke to reveal RTL bug

sw/device/silicon_creator/lib/drivers/epmp.c, sw/device/silicon_creator/lib/drivers/epmp.h
The `pmpaddr` should not be UINT32_MAX as the input for decoding napot.
1. Add a HARDENED_CHECK_NE for `pmpaddr`, as `1u << 32` is an undefined behavior.
2. Mitigate the signed integer conversion by replacing `1` to `1u`.
=> [epmp] Check the PMP address for NAPOT decode.

hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv, hw/ip/lc_ctrl/dv/tb.sv
Support a variable number of assertion checkers on the RmaAck signals within lc_ctrl.
=> [lc_ctrl] Darjeeling has just one RmaAck signal

hw/ip/tlul/adapter_racl.core, hw/ip/tlul/lint/tlul_adapter_racl.vlt, hw/ip/tlul/lint/tlul_adapter_racl.waiver, hw/ip/tlul/rtl/tlul_adapter_racl.sv, hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv, hw/top_earlgrey/lint/top_earlgrey.waiver
This PR:
- Fixes a typo in a waiver file as a follow-up from #26691
- Factors out the RACL logic from `tlul_adapter_sram_racl` into its own `tlul_adapter_racl` which acts as a generic TLUL adapter and allows it to be used outside of the context of sram.
=> [RACL] Factor out RACL range check logic from tlul_adapter_sram_racl

hw/top_darjeeling/dv/chip_sim_cfg.hjson, hw/top_darjeeling/dv/top_darjeeling_sim_cfgs.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson
See #26733 which tracks either fixing or selecting another set of smoke tests for Darjeeling.
This will allow us to enable Darjeeling DV CI for pull requests, though it will only run the three tests shown here for now.
=> [dv] Exclude currently failing tests from Darjeeling smoke set

sw/device/silicon_creator/manuf/base/BUILD, sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/host/provisioning/ft_lib/src/lib.rs
The OTP configuration may instruct the ROM to turn on the Watchdog and preserve the reset reason in the `rstmgr`. This change makes implements the following:
1. Unconditionally disable the watchdog in ft_personalize. This is to avoid having to pet the watchdog during long running operations (e.g. TBS certificate round trip).
2. Clear the reset reason in the `rstmgr`. This is to avoid accumulation of reset events during the perso flow.
=> [perso] Disable WD and clear reset status.

hw/dv/sv/jtag_agent/jtag_driver.sv, hw/ip/rv_dm/dv/env/rv_dm_if.sv, hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv, hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv, hw/ip/rv_dm/dv/tb.sv
When using the DMI interface we must not wait on the monitor because it does not see the internal JTAG signaling, and we must be sure to enable the straps because otherwise the internal DMI gate will block the DMI traffic from reaching the debug logic.
=> [rv_dm] Fix rv_dm_smoke when using the DMI interface

hw/top_darjeeling/dv/top_darjeeling_sim_cfgs.hjson
The OTP config was disabled by mistake. The LC_CTRL tests should work since https://github.com/lowRISC/opentitan/pull/26778.
The others should also not really have been disabled, but their smoke regressions fail CI so I'll need to disable that tomorrow before they can re-enabled.
=> [dv] Re-enable Darjeeling configs

sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c, sw/host/provisioning/ft_lib/src/lib.rs
Changes:
1. Include `OTP_CTRL_PARAM_CREATOR_SW_CFG_FLASH_INFO_BOOT_DATA_CFG_OFFSET`
in `manuf_individualize_device_partition_expected_read()`. This is
required now that the boot data info page configuration is committed
into OTP in the later stages of personalization.
2. Remove logging message to simplify tester integration. The message was
initially added for debugging purposes, but it is no longer needed.
=> [perso] Update CREATOR SW OTP digest calculation and remove reset logging message.

hw/top_darjeeling/dv/chip_sim_cfg.hjson
Modify the sw test image location for some tests that have been ported to DT but have not been operational on Darjeeling as a result of this oversight in the configuration file.
Some tests are no longer dvsim-only targets, so update their filenames.
Darjeeling does not have a sensor_ctrl module, so remove those tests which still make reference to it.
=> [darjeeling] Update config files for some overlooked tests

sw/device/silicon_creator/lib/drivers/flash_ctrl.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.h, sw/device/silicon_creator/manuf/base/ft_personalize.c
This fixes a bug in the boot-data flash info page configuration. We need to read the configuration of the boot-data flash info page from OTP before configuring the page, not the default data page configuration as there are two different sets of configuration settings.
=> [perso] fix bug in boot data flash info page config

hw/ip/aon_timer/dv/tb.sv
Adding missing RACL signals to get rid of a warning due to missing ports otherwise.
=> [dv, aon_timer] Adding RACL signals to tb.sv

sw/device/tests/BUILD, sw/device/tests/clkmgr_smoketest.c, sw/device/tests/rstmgr_smoketest.c
Two of the remaining smoke tests that are very simple are ported to DT and thus brought up on Darjeeling.
=> [clkmgr,rstmgr] Port a couple more simple smoke tests to Darjeeling

hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv
- Not enough granted transactions were seen and causing the scoreboard to fail. Now allow 2/3 of the transactions; instead of 1/2 when the range is allowed.
=> [ac_range_check,dv] Grant more transactions

hw/ip/aon_timer/doc/theory_of_operation.md
Mentioning RACL ports as suggested in issue #22632
=> [doc, aon_timer] Mention of RACL ports in theory of operation

sw/device/silicon_creator/lib/rescue/BUILD, sw/device/silicon_creator/lib/rescue/dfu.c, sw/device/silicon_creator/lib/rescue/dfu.h, sw/device/silicon_creator/lib/rescue/dfu_state_table.c, sw/device/silicon_creator/lib/rescue/rescue_usb.c
Implement the DFU state machine and control endpoint to manage transfer of data in and out of the chip.
USB AltSettings are used to permit the rescue protocol to communicate with different ROM_EXT services (e.g. boot-log, boot-services, device-id, etc).
This PR depends on #26622 and #26637.
=> [rescue] Implement the DFU protocol for rescue 

sw/device/tests/BUILD, sw/device/tests/aon_timer_smoketest.c, sw/device/tests/rv_plic_smoketest.c
Port `rv_plic_smoketest` and `aon_timer_smoketest` to DT and thus Darjeeling.
Note that rv_plic_smoketest will pass only in the presence of #26814 which prevents X propagation into the UART on Darjeeling.
=> [darjeeling] PLIC and AON Timer smoketests

sw/device/lib/testing/pinmux_testutils.c
Darjeeling as Dedicated I/O pin for the UartRx input and it is driven directly by the TB/DV. Asserting the pull up leads to X propagation into the UART and failure of any test that enables reception of UART data.
=> [uart] Do not assert pull up on Darjeeling UartRx input

hw/top_darjeeling/dv/chip_sim_cfg.hjson, sw/device/tests/BUILD, sw/device/tests/kmac_entropy_test.c, sw/device/tests/otbn_mem_scramble_test.c
Ported `kmac_entropy_test` and `otbn_mem_scramble_test` to DT and thus Darjeeling.
Drop from the Darjeeling chip configuration those tests which rely upon the presence of an entropy source IP block; Darjeeling does not include one a la Earl Grey so these tests are not relevant.
=> [darjeeling] Bring up a few more top-level SW tests

sw/device/lib/testing/aes_testutils.c, sw/device/lib/testing/aes_testutils.h, sw/device/sca/aes_serial.c, sw/device/tests/BUILD, sw/device/tests/aes_masking_off_test.c, sw/device/tests/penetrationtests/firmware/sca/aes_sca.c
Port the aes_masking_off_test and associated testutils functions to Darjeeling using DT.
Minimally update both aes_sca and aes_serial to avoid introducing additional bit rot, but leave them as Earl Grey only for now.
=> [aes] Port aes_masking_off_test to Darjeeling using DT

sw/device/tests/penetrationtests/firmware/fi/crypto_fi.c, sw/device/tests/penetrationtests/firmware/fi/ibex_fi.c, sw/device/tests/penetrationtests/firmware/fi/lc_ctrl_fi.c, sw/device/tests/penetrationtests/firmware/fi/otbn_fi.c, sw/device/tests/penetrationtests/firmware/fi/otp_fi.c, sw/device/tests/penetrationtests/firmware/fi/rng_fi.c, sw/device/tests/penetrationtests/firmware/fi/rom_fi.c, sw/device/tests/penetrationtests/firmware/lib/BUILD, sw/device/tests/penetrationtests/firmware/lib/pentest_lib.c, sw/device/tests/penetrationtests/firmware/lib/pentest_lib.h, sw/device/tests/penetrationtests/firmware/sca/aes_sca.c, sw/device/tests/penetrationtests/firmware/sca/edn_sca.c, sw/device/tests/penetrationtests/firmware/sca/hmac_sca.c, sw/device/tests/penetrationtests/firmware/sca/ibex_sca.c, sw/device/tests/penetrationtests/firmware/sca/kmac_sca.c, sw/device/tests/penetrationtests/firmware/sca/otbn_sca.c, sw/device/tests/penetrationtests/firmware/sca/sha3_sca.c, sw/device/tests/penetrationtests/json/crypto_fi_commands.h, sw/device/tests/penetrationtests/json/ibex_fi_commands.h, sw/device/tests/penetrationtests/json/lc_ctrl_fi_commands.h, sw/device/tests/penetrationtests/json/otbn_fi_commands.h, sw/device/tests/penetrationtests/json/otp_fi_commands.h, sw/device/tests/penetrationtests/json/pentest_lib_commands.h, sw/device/tests/penetrationtests/json/rng_fi_commands.h, sw/device/tests/penetrationtests/json/rom_fi_commands.h
This PR consists of two commits:
- Allow enabling / disabling the SRAM readback feature as well as the jittery clock
- Read out and report the fatal / recoverable alerts from the AST
=> [pentest] Allow enabling countermeasures and report AST alerts

sw/host/hsmtool/acorn/acorn.rs, sw/host/opentitanlib/opentitantool_derive/src/lib.rs, sw/host/opentitanlib/src/transport/dediprog/spi.rs, sw/host/opentitanlib/src/transport/hyperdebug/spi.rs, sw/host/opentitantool/src/command/bfv.rs, sw/host/ot_certs/src/asn1/builder.rs, sw/host/ot_certs/src/asn1/codegen.rs, sw/host/ot_certs/src/asn1/der.rs, sw/host/ot_certs/src/asn1/x509.rs, sw/host/ot_certs/src/codegen.rs, sw/host/tests/chip/pattgen/pattgen_ios.rs, sw/host/tests/chip/rv_dm/src/csr_rw.rs, sw/host/tests/chip/rv_dm/src/mem_access.rs, sw/host/tests/xmodem/xmodem.rs, third_party/rust/rust.MODULE.bazel
This includes all fixes necessary to move to Rust 2024:
* `gen` becomes a reserved keyword
* `unsafe` is now required even the function is `unsafe`
* `ref` can no longer be added if the scrutinee is already ref
* `no_mangle` and `extern` now require `unsafe`
Some changes that require no fixing:
* if-let drop order changes; I've reviewed all sites and they seem fine (they're all false positives, see https://github.com/rust-lang/rust/issues/137376)
* expr in macro accepts more expressions, our use of them are all fine.
* tail expression drop order changes; I've reviewed all sites and they seem fine.
=> [rust] move to edition 2024

hw/top_darjeeling/dv/top_darjeeling_sim_cfgs.hjson
I'm told these tests are working now
=> [dv] Re-enable RV_DM config for Darjeeling

hw/ip_templates/ac_range_check/data/ac_range_check.hjson.tpl, hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/ip_autogen/ac_range_check/data/ac_range_check.hjson, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
Expose the option of the underlying loopback primitive to make the design more configurable for other use cases.
=> [hw,ac_range_check,rtl] Make error response paramtrizable

hw/ip/mbx/data/mbx.hjson, hw/ip/mbx/rtl/mbx.sv, hw/ip/mbx/rtl/mbx_core_reg_top.sv, hw/ip/mbx/rtl/mbx_hostif.sv, hw/ip/mbx/rtl/mbx_sysif.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, hw/top_darjeeling/ip_autogen/racl_ctrl/data/racl_ctrl.hjson, hw/top_darjeeling/ip_autogen/racl_ctrl/data/top_darjeeling_racl_ctrl.ipconfig.hjson, hw/top_darjeeling/ip_autogen/racl_ctrl/doc/racl_configuration.md, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_darjeeling/rtl/autogen/top_darjeeling_racl_pkg.sv, util/topgen.py
This PR is a follow-up to #26004.
- This commit extends topgen such that a single IP can have RACL
enabled on multiple interfaces.
- It also adds RACL for mbx's device interface 'core'. Previously,
only mbx's 'soc' interface had RACL support.
- Finally, it enables RACL for all mbx instances in top_darjeeling.
Two of them were left disabled by accident.
=> [mbx,racl,topgen] Add RACL support for both device interfaces of mbx

.github/workflows/cherrypick.yml
Manual backport of https://github.com/lowRISC/opentitan/pull/26768
=> [ci] Add note about triggering CI for backports (`earlgrey_1.0.0`)

sw/device/silicon_creator/lib/rescue/BUILD, sw/device/silicon_creator/lib/rescue/rescue.c, sw/device/silicon_creator/lib/rescue/rescue.h, sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD, sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_enter_rescue_test.c, sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.h, sw/device/silicon_creator/rom_ext/rom_ext.c
Allow the owner application to request entry into rescue mode on the next boot.  This will enable applications to implement the app-state portion of the DFU state machine and request DFU mode to process firmware updates.
1. Add a handler for boot_svc `EnterRescue` command.
2. Add tests.
=> [boot_svc, rescue] Allow app-requested rescue

hw/dv/sv/dv_lib/dv_base_monitor.sv
The parameterisation has been wrong since I added some parameters to the class in 2021(!). Fix it.
=> [dv] Fix uvm_component_param_utils call in dv_base_monitor

sw/device/silicon_creator/manuf/base/BUILD, sw/device/silicon_creator/manuf/base/sram_ft_individualize.c, sw/host/opentitanlib/src/test_utils/load_sram_program.rs, sw/host/provisioning/ft/src/main.rs, sw/host/provisioning/ft_lib/BUILD, sw/host/provisioning/ft_lib/src/lib.rs
The OTTF console initialization requires a host--device handshake when using the SPI transport. This causes issues with ATE integration. This removes the OTTF console initialization, and all remaining `LOG_INFO()`s from the individualization firmware.
Additionally, this makes the FT test harness more flexible to enable performing a test exit operation from any TestUnlocked state.
=> [individualize] remove OTTF console init and all prints

hw/ip_templates/ac_range_check/README.md, hw/top_darjeeling/ip_autogen/ac_range_check/README.md
- This is linked to this issue: #26572. The paragraph related to the priority of matching in case of conflicting permissions, have been clarified.
=> [ac_range_check,doc] Spec clarification

hw/ip/prim_generic/rtl/prim_otp_cfg_pkg.sv, hw/top_darjeeling/rtl/autogen/chip_darjeeling_asic.sv, hw/top_darjeeling/rtl/autogen/chip_darjeeling_cw310.sv, hw/top_darjeeling/templates/chiplevel.sv.tpl
There was no driver on otp_cfg, although since that's a DFT input it has not led to simulation failures.
The only other chip-level Z/X signals are all a product of DIO/MIO signals being undriven and are harmless provided that the pinmux (for MIOs) or output enables (DIOs) are set appropriately before the signals are used.
Specifically, MIOs (excepting 0 which is the TAP strap input) are left floating (Z) when unused, and the SPI interfaces are undriven in the cast of DUT SPI Host 0 output and connected to X in the case of DUT SPI Device 0 input.
=> [darjeeling] Fix undriven input port

hw/ip/tlul/rtl/tlul_err.sv
Removed the unneccessary chunk of zero assignment code. The reason being that jasper concludes the default zero assignment code as undetectable because the zero assignment to the affected signals happening in two ways:
1) By default
2) If something unexpected happens (in an else or default case)
=> [rv_plic, fpv] Removed the chunk of zero assignment

hw/ip_templates/rv_plic/fpv/tb/rv_plic_bind_fpv.sv.tpl, hw/ip_templates/rv_plic/fpv/vip/rv_plic_assert_fpv.sv.tpl, hw/top_darjeeling/ip_autogen/rv_plic/fpv/tb/rv_plic_bind_fpv.sv, hw/top_darjeeling/ip_autogen/rv_plic/fpv/vip/rv_plic_assert_fpv.sv, hw/top_earlgrey/ip_autogen/rv_plic/fpv/tb/rv_plic_bind_fpv.sv, hw/top_earlgrey/ip_autogen/rv_plic/fpv/vip/rv_plic_assert_fpv.sv, hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/tb/rv_plic_bind_fpv.sv, hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/vip/rv_plic_assert_fpv.sv
The intention was to get rid of undetectable coverage. u_rsp_intg_gen in rv_plic_reg_top that generates both data and rsp intg through some prim_secded_inv_xx_xx_enc. All the continuous assignments to data_o for the generation of integrity bits were marked as undetectable by jasper.
The assertions added in this PR simply says that if I have a response coming from the device, then it must have correct integrity bits.
=> [rv_plic, fpv] Assertions added for rsp and data intg

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
Updating the existing check in `check_fatal_alert_nonblocking` to consider the extra two clock cycles introduced by the sampling delay at the VIF
This PR is meant to fix the AES failures found in the [nightly darjeeling run](https://nightly.reports.lowrisc.org/opentitan_nightly_darjeeling/2025_03_31/hw/ip/aes_unmasked/dv/latest/report.html)
=> [dv, cip_base_vseq] alert check fix on `check_fatal_alert_nonblocking`

sw/device/silicon_creator/lib/drivers/hmac.c, sw/device/silicon_creator/lib/drivers/hmac.h, sw/device/silicon_creator/lib/drivers/hmac_functest.c
This adds a function to the silicon_creator HMAC driver lib to compute an HMAC-SHA256 keyed digest. This is required to implement the WAS authentication flow during personalization required by #22274.
=> [silicon_creator,hmac] add HMAC-SHA256 driver function

sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs
It appears that since its inception, the I2C driver has had a bug in handling USB response spanning more than one 64-byte packet.  (This will happen when more than 59 bytes are received via I2C, as the tunneling protocol adds a 5-byte header in the USB response.)
Recent changes to the TPM driver in opentitanlib stopped it from limiting TPM I2C transfers to 32 bytes, and that revealed this old bug.
=> [opentitanlib] Fix for HyperDebug I2C driver

util/topgen/validate.py
This key is superseded by using an ipgen_param in the top-level instantiation.
=> [topgen] Remove ac_range_check key from top validate

hw/ip/hmac/dv/hmac_sim_cfg.hjson
- A regression was showing few ccov holes, and I've noticed from a previous regression results that these holes were actually covered by hmac_stress_all or by hmac_stress_all_with_rand_reset tests.
=> [hmac,dv] Add more seeds to ensure CCov

sw/device/silicon_creator/lib/bootstrap.c, sw/device/silicon_creator/lib/drivers/BUILD, sw/device/silicon_creator/lib/drivers/mock_spi_device.cc, sw/device/silicon_creator/lib/drivers/mock_spi_device.h, sw/device/silicon_creator/lib/drivers/spi_device.c, sw/device/silicon_creator/lib/drivers/spi_device.h, sw/device/silicon_creator/lib/drivers/spi_device_bfpt.h, sw/device/silicon_creator/lib/drivers/spi_device_unittest.cc, sw/device/silicon_creator/lib/rescue/BUILD, sw/device/silicon_creator/lib/rescue/dfu.h, sw/device/silicon_creator/lib/rescue/rescue_spi.c, sw/device/silicon_creator/lib/rescue/sfdp.c, sw/device/silicon_creator/lib/rescue/sfdp.h, sw/device/silicon_creator/rom/bootstrap_unittest.cc
1. Use the `spi_device` driver to configure the SPI peripheral.  Turn on
the mailbox and spi egress buffer to facilitate send and recv of
command packets (mailbox) and data packets (egress buffer).
2. Initialize an SFPD table that communicates the SPI-DFU capability in
a parameter table.
3. Process SPI opcodes captured by the SPI device to implement the DFU
protocol.
This PR depends on #26622, #26638 and #26647.  You need only review the last 2 commits.
=> [rescue] Implement the DFU protocol over SPI 

rules/opentitan/silicon.bzl, sw/device/silicon_creator/manuf/lib/ast_program.c, sw/device/silicon_creator/manuf/lib/individualize_sw_cfg.c
Additionally, add a rule to generate unscrambled VMEM SRAM binary files for testing SRAM injection in DV.
=> [ate] remove ECC from AST programming

sw/device/lib/crypto/drivers/entropy.c
The `EDN_CTRL` register uses multi-bit (MUBI) fields to configure the mode of operation. Setting the fields to any value different than `TRUE (0x6)` or `FALSE (0x9)` will result in a recoverable alert.
This change explicitly sets all the fields in the register to expected values to avoid triggering recoverable alerts.
The `EDN_RECOV_ALERT_STS_REG` is also cleared before enabling the block to avoid starting with previous invalid conditions.
=> [cryptolib] Explicitly enable EDN

hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv
Previously only the flow control signals (valid and ready) were asserted to be known on the TL-UL and RACL Error ports.  This commit expands the assertion to check whether the other fields of those ports are known if the module signals that they are valid.
=> [ac_range_check] Expand `ASSERT_KNOWN` checks

sw/device/lib/dif/dif_alert_handler.c, sw/device/lib/dif/dif_alert_handler.h, sw/device/lib/testing/BUILD, sw/device/lib/testing/alert_handler_testutils.c, sw/device/lib/testing/alert_handler_testutils.h, sw/device/tests/BUILD, sw/device/tests/power_virus_systemtest.c
The following utilities are introduced to facilitate triaging of issues in silicon:
1. `alert_handler_testutils_status_log`: Log any alert counts accumulated across any of the alert handler classes.
2. `alert_handler_testutils_dump_log`: Log any alerts and alert handler class counters captured in the reset manager crash dump.
3. `alert_handler_testutils_dump_enable`: Enable crash dump for any enabled alert handler classes.
=> [sival] Add `alert_handler` log utilities.

hw/ip_templates/ac_range_check/dv/env/ac_range_check_env.core.tpl, hw/ip_templates/ac_range_check/dv/env/ac_range_check_env_pkg.sv.tpl, hw/ip_templates/ac_range_check/dv/env/ac_range_check_scb_item.sv, hw/ip_templates/ac_range_check/dv/env/ac_range_check_scoreboard.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env.core, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env_pkg.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scb_item.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scoreboard.sv
- This PR addresses this issue #26848. It replaces a struct containing a counter and a tl_seq_item. It's cleaner to move it into a dynamic object to allow more flexibility. This will also be needed by the predictor as TLM port doesn't accept struct types.
=> [ac_range_check,dv] Move struct into class wrapper

rules/files.bzl, rules/scripts/copy_files.template.sh, sw/device/silicon_creator/manuf/base/binaries/BUILD, sw/device/silicon_creator/rom_ext/sival/binaries/BUILD
During the signing ceremony, after re-attaching signatures, it is necessary to copy the signed binaries from the `bazel-out` directory to their desired location within the project.  This copying is tedious and error prone.
To ease toil, provide a rule which can copy the files produced by the post_signing_attach rule to their desired destination.
```
bazel run //sw/device/silicon_creator/rom_ext/sival:copy_signed
```
=> [signing] Improve automation

sw/device/silicon_creator/manuf/base/BUILD, sw/device/silicon_creator/manuf/base/flash_info_permissions.h, sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/device/silicon_creator/manuf/base/perso_tlv_data.h, sw/device/silicon_creator/manuf/base/sram_cp_provision.c, sw/host/provisioning/ft/src/main.rs, sw/host/provisioning/ft_lib/BUILD, sw/host/provisioning/ft_lib/src/lib.rs, sw/host/provisioning/orchestrator/src/ot_dut.py, sw/host/provisioning/perso_tlv_lib/src/lib.rs, third_party/rust/Cargo.lock, third_party/rust/Cargo.toml, third_party/rust/crates/BUILD.bazel, third_party/rust/crates/defs.bzl
This fixes #22274 by updating the perso firmware and FT test harness to compute and validate an HMAC-SHA256 over the TBS certs.
=> [perso] implement WAS / TBS HMAC binding

hw/ip/rom_ctrl/doc/theory_of_operation.md
The text was documenting the original design (which padded up from 39 bits to 64 bits), but this changed in 2022 with commit 5d4d4e5 and started only padding up to 40 bits, which is rather more efficient.
Update the document to match.
=> [rom_ctrl,doc] Correct a padding width

hw/ip_templates/rv_core_ibex/data/rv_core_ibex.hjson.tpl, hw/ip_templates/rv_core_ibex/data/rv_core_ibex.tpldesc.hjson, hw/ip_templates/rv_core_ibex/rtl/rv_core_ibex.sv.tpl, hw/ip_templates/rv_core_ibex/rv_core_ibex.core.tpl, hw/top_darjeeling/ip_autogen/rv_core_ibex/data/top_darjeeling_rv_core_ibex.ipconfig.hjson, hw/top_earlgrey/ip_autogen/rv_core_ibex/data/top_earlgrey_rv_core_ibex.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/rv_core_ibex/data/top_englishbreakfast_rv_core_ibex.ipconfig.hjson, util/topgen.py
This PR adds an optional RACL support to the rv_core_ibex IP. The enablement is gated via an ipgen parameter to not add the logic (even though it is disabled) to rendered IPs that don't use it.
=> [hw,rv_core_ibex,rtl] Add optional RACL support to RV Core Ibex

doc/contributing/bazel_notes.md
Experiment shows that build speed is significantly improved by using `--disk_cache`.
=> [doc] explain that --disk_cache is also needed for top switching

sw/device/silicon_creator/lib/ownership/BUILD, sw/device/silicon_creator/lib/ownership/test_owner.c, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD, sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/io/spi.rs, sw/host/opentitanlib/src/ownership/rescue.rs, sw/host/opentitanlib/src/rescue/dfu.rs, sw/host/opentitanlib/src/rescue/mod.rs, sw/host/opentitanlib/src/rescue/spidfu.rs, sw/host/opentitanlib/src/spiflash/sfdp.rs
1. Detect the SPI-DFU capability with an SFDP extension.
2. Implement USB-like control transactions over SPI using the SPI mailbox and SPI egress buffers.
3. Add spi-dfu to to the rescue e2e tests.
This PR depends on #26622, #26638, #26647 and #26669.  You need only review the last 2 commits.
=> [rescue] Implement a SPI-DFU client 

sw/device/silicon_creator/manuf/base/ft_personalize.c
This updates the perso flow to add GPIO test start / done indicator pins to aid ATE flows.
=> [perso] add GPIO test start / done ATE indicators

util/raclgen/lib.py
Previously racl mappings allowed either `*` mappings or non-`*` mappings.
But especially for out of tree modules, it can be beneficial to allow mixing both types.
This PR changes raclgen, such that it's possible to specify policies to some specific registers/windows while also allowing to set all other registers/windows (that are not explicitly named) to another policy using the `*` mapping.
This behavior was previously under specified and will be added to the documentation after #26592 is merged. In the meantime this change is tracked in #26720.
=> [RACL, raclgen] Allow mixing * and non-* in racl mappings

sw/device/silicon_creator/lib/cert/cdi_1.hjson, sw/device/silicon_creator/lib/cert/dice.c, sw/device/silicon_creator/lib/cert/dice.h, sw/device/silicon_creator/lib/cert/dice_chain.c, sw/device/silicon_creator/lib/cert/dice_chain.h, sw/device/silicon_creator/lib/cert/dice_cwt.c, sw/device/silicon_creator/lib/ownership/mock_ownership_key.cc, sw/device/silicon_creator/lib/ownership/mock_ownership_key.h, sw/device/silicon_creator/lib/ownership/ownership_activate.c, sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc, sw/device/silicon_creator/lib/ownership/ownership_key.c, sw/device/silicon_creator/lib/ownership/ownership_key.h, sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/host/tests/attestation/attestation_test.rs
1. Add a `fw_ids` member that contains the ownership history information.  The ownership history is a hash chain of all owner_keys: `owner_history = HASH(owner_history || owner_key)`.
2. Initialize the owner_history hash in `sku_creator_owner_init`. The beginning of the hash chain is just `HASH(owner_key)`.
3. Check the owner_history element in the attestation test.
A follow-up PR will add tests to check the owner_history after an ownership transfer.
=> [rom_ext] Communicate owner history via the CDI_1 certificate

hw/top_darjeeling/dv/chip_sim_cfg.hjson
These tests are not yet thought to be reliable and we don't want to block on them in CI.
CC @alees24 who told me these tests weren't useful to have copied over from Earlgrey.
=> [dv] Disable certain chip-level tests for Darjeeling

sw/device/lib/dif/dif_alert_handler.c
The `enable` argument was not taken into account to enable/disable a particular alert. This chaanges fixes that issue.
=> [dif] Fix configure alert function.

hw/ip/kmac/rtl/kmac_msgfifo.sv
This isn't technically allowed by the 1800 spec and causes a lint error from the Verissimo tool.
Fortunately it's easy to fix! Do so.
=> [kmac,rtl] Avoid a procedural assignment to a port

hw/dv/sv/alert_esc_agent/alert_esc_if.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
Doing so causes Xcelium to generate an (initially mystifying) error message:
```
xmelab: *E,DISVIF (...._vseq.sv,111|48):
Disallowed virtual interface hierarchical reference object type at 'PingSt'.
```
This took me a while to understand, but the point is that the vseq was using e.g. alert_vif.PingSt. What is the type of that expression? Well, it's state_e, but the enum is defined inside the interface (and that enum isn't technically part of the "port list" of the interface).
At least, that's what I *think* is going on. There's a discussion of (I think) the same question at
https://stackoverflow.com/questions/54627223/
=> [alert,dv] Avoid using state_q and PingSt from alert_esc_if directly

rules/files.bzl, rules/scripts/copy_files.template.sh
Update the file copying rule to operate in the root of the opentitan repo and be able to copy files into an externally attached repo (e.g. the provisioning skus repo).
=> [signing] Fix file copy automation

sw/device/tests/power_virus_systemtest.c
`csrng` raises a recoverable alert after receiving an our of order command. The test was previously issuing the instantiated command on an already instantiated instance.
=> [sival] Fix csrng alert in power virus test.

hw/dv/sv/scoreboard/scoreboard.sv
Honestly, I'm rather unconvinced by this class in
general ("scoreboard" as a class name?!). This is a trivial change though, triggered by a warning from Verissimo that we were passing the wrong type to the macro.
=> [dv] Correct params for uvm_component_param_utils in scoreboard.sv

hw/ip/rom_ctrl/dv/rom_ctrl_base_sim_cfg.hjson
This won't negatively affect the coverage numbers (or, more importantly, the confidence that the tests give us). But it cuts the time to less than half.
=> [rom_ctrl,dv] Dramatically shorten regressions

sw/host/provisioning/orchestrator/configs/skus/emulation.hjson, sw/host/provisioning/orchestrator/configs/skus/emulation_dice_cwt.hjson, sw/host/provisioning/orchestrator/configs/skus/emulation_tpm.hjson, sw/host/provisioning/orchestrator/configs/skus/sival.hjson, sw/host/provisioning/orchestrator/data/packages/earlgrey_a2.hjson, sw/host/provisioning/orchestrator/data/products.hjson, sw/host/provisioning/orchestrator/src/BUILD, sw/host/provisioning/orchestrator/src/sku_config.py, sw/host/provisioning/orchestrator/tests/device_id_test.py
This updates all orchestrator configs to use the updated A2 product ID in the device ID.
=> [orchestrator] switch all SKUs to A2 product ID

sw/host/opentitantool/src/command/ownership.rs
Validate ECDSA signature of a full 2K binary owner's configuration blob.
The first 1952 bytes are considered the TBS section, the public key location is fixed inside the blob. The embedded key is used to verify the signature unless the key is supplied in a separate file.
TEST=read configuration from a live chip, converted it to binary and
successfully verified the blob signature using both embedded and
external keys. Also verified that a signature verification
failure is reported if a wrong pub key file is passed in.
=> ownership: add validating of ECDSA owner's signature

sw/device/lib/crypto/drivers/BUILD, sw/device/lib/crypto/drivers/ibex.c, sw/device/lib/crypto/drivers/ibex.h, sw/device/lib/crypto/drivers/ibex_test.c
This PR adds a new ibex driver to cryptolib for gathering randomness from the RND_DATA CSR.
For further information check the individual commits.
=> [sw/cryptolib] Add new ibex driver functions

sw/device/silicon_creator/lib/drivers/epmp.c, sw/device/silicon_creator/lib/drivers/epmp.h, sw/device/silicon_creator/lib/drivers/keymgr.c, sw/device/silicon_creator/lib/drivers/keymgr.h, sw/device/silicon_creator/lib/drivers/keymgr_functest.c, sw/device/silicon_creator/lib/ownership/ownership_key.c, sw/device/silicon_creator/lib/ownership/ownership_key.h, sw/device/silicon_creator/rom_ext/rom_ext.c
Lockdown the chip before entering rescue mode.
- Forbid SRAM execution.
- Disable keymgr and clear sideload keys.
- Lock out OTP memory-mapped access.
- Lock the ePMP.
- Lock out access to flash INFO pages
=> [rescue, rom_ext] Lockdown before entering rescue

sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/host/provisioning/ft_lib/src/lib.rs
This updates the perso flow to remove the UJSON CRC from the RMA token hash payload to facilitate development of ATE flows.
=> [perso] remove UJSON CRC when sending RMA token

sw/device/tests/rstmgr_alert_info_test.c
The exception for non-owner code is no longer required.
Fix https://github.com/lowRISC/ot-earlgrey-a1/issues/15
=> [Sival, rstmgr] Fix test rstmgr_alert_info_test

hw/ip/prim/dv/prim_alert/prim_alert_sim_cfg.hjson, hw/top_darjeeling/dv/top_darjeeling_sim_cfgs.hjson
This PR addresses two points:
1. The clkmgr smoke test is now okay for inclusion in Darjeeling CI / nightly runs.
2. Darjeeling nightly regression may now be run with xcelium.
=> [darjeeling] Update configuration files

sw/device/lib/runtime/BUILD, sw/device/lib/runtime/print.c, sw/device/lib/runtime/print.h, sw/device/lib/testing/test_framework/BUILD, sw/device/lib/testing/test_framework/ottf_console.c, sw/device/lib/testing/test_framework/ottf_test_config.h, sw/device/tests/BUILD, sw/device/tests/ottf_console_with_gpio_tx_indicator_test.c, sw/host/opentitanlib/src/console/spi.rs, sw/host/opentitanlib/src/io/console.rs, sw/host/provisioning/cp/src/main.rs, sw/host/provisioning/ft/src/main.rs, sw/host/tests/chip/ottf_console_with_gpio_tx_indicator/BUILD, sw/host/tests/chip/ottf_console_with_gpio_tx_indicator/src/main.rs, sw/host/tests/chip/spi_device_ottf_console/src/main.rs, sw/host/tests/chip/spi_device_ujson_console_test/src/main.rs, sw/host/tests/crypto/aes_nist_kat/src/main.rs, sw/host/tests/crypto/drbg_kat/src/main.rs, sw/host/tests/crypto/ecdh_kat/src/main.rs, sw/host/tests/crypto/ecdsa_kat/src/main.rs, sw/host/tests/crypto/hash_kat/src/main.rs, sw/host/tests/crypto/hmac_kat/src/main.rs, sw/host/tests/crypto/kmac_kat/src/main.rs, sw/host/tests/crypto/sphincsplus_kat/src/main.rs, sw/host/tests/manuf/cp_provision_functest/src/main.rs
This PR has two commits that enables the use of a GPIO TX-ready indicator pin in conjunction with the SPI console to eliminate the need for the host to constantly poll the SPI egress buffer for data.
The first commit adds an TX-ready indicator GPIO pin to the SpiConsoleDevice in opentitanlib that can alternatively be sampled by the SpiConsoleDevice to determine when the host should attempt to read out data from the device.
The second commit updates the OTTF console to enable the device to drive this TX-ready GPIO indicator pin when data is added to the egress buffer.
Both of these commits will enable capturing waveforms of the SPI console during the personalization flow to develop ATE test patterns. See the below waveform captured during the newly added test. See how the host only clocks …
=> [ottf_console] enable use of GPIO TX indicator pin with SPI console to prevent host polling

sw/device/lib/ujson/ujson.c, sw/device/lib/ujson/ujson_test.cc
This PR fixes the potential unsigned underflow/overflow in the ujson parsing functions.
1. The subtraction `c - '\t' < 5` in `is_space()` might underflow, this commit updates the implementation to `'\t' + 5`.
2. The `value` in `ujson_parse_interger()` might overflow, this commits adds a check before the assignment.
=> [ujson] Fix potential unsigned underflow/overflow.

sw/device/tests/BUILD, sw/device/tests/flash_ctrl_clock_freqs_test.c, sw/device/tests/flash_ctrl_ops_test.c, sw/device/tests/flash_ctrl_test.c
Currently it always use region 0 and first page of bank 1, but both of them are occupied by ROM_EXT. Simply switch to region 2 and page 0x20 when running in owner stage would make the test to work on owner stage.
Existing checks for silicon is wrong -- it should be checking for boot stages instead. These are replaced too.
=> [sival] use different region and page in owner stage for flash tests

.github/workflows/fpga.yml, .github/workflows/nightly.yml
With https://github.com/lowRISC/container-hotplug/pull/13, containers in our CI infrastructure can now observe udev events properly, therefore the workarounds around stale USB devices can be removed.
=> [ci] remove udev workarounds

sw/device/lib/testing/json/provisioning_data.h, sw/device/silicon_creator/manuf/base/BUILD, sw/device/silicon_creator/manuf/base/sram_ft_individualize.c, sw/host/provisioning/ft/src/main.rs, sw/host/provisioning/ft_lib/src/lib.rs, sw/host/provisioning/orchestrator/src/device_id.py, sw/host/provisioning/orchestrator/src/ot_dut.py, sw/host/provisioning/orchestrator/tests/BUILD, sw/host/provisioning/orchestrator/tests/e2e_option_flags.sh
This partially reverts #26648 by adding back the injection of the FT device ID during individualization. This is necessary as the orchestrator.py script provides command line switches for orriding the package ID an AST config version fields of the FT (SKU-specific) portion of the device ID. Since these fields can be overridden at runtime, they cannot be precompiled into the FT individualization binary. Thus, data must be transmitted from the host to the device over UJSON during individualization.
To support ATE flows that would like to avoid sending UJSON messages for performances reasons, we also support building individualization binaries where the FT device ID is compiled into the binary. However, these are no used with the orchestrator, which provides the ability to override the …
=> [manuf] send FT device ID from host to device

util/dttool.py, util/ipgen.py, util/regtool.py, util/topgen.py
Addresses #26754, with hat tip to @matutem and @milesdai for their guidance. I changed the log format in tools I run into most frequently, but there are other util/ scripts that call `logging.basicConfig()`, such as tlgen.py, otbn_build.py, and generate_compilation_db.py. Should these be changed, too?
=> [util] Add filename and line numbers to logging messages

sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD, sw/host/opentitantool/src/command/image.rs
1. Make opentitantool examine all extensions to set the signed region bounds.
1. Test that firmware boots with an ISFB extension present.  Note that the ISFB extension is not evaluated by this test -- we're only checking that the ROM_EXT will boot firmware with such an extension.
=> [rom_ext_e2e] Test firmware boot with an ISFB present

hw/top_darjeeling/dv/env/seq_lib/chip_sw_base_vseq.sv, hw/top_darjeeling/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv, sw/device/tests/sram_ctrl_scrambled_access_test.c
This bring up the test `chip_sw_sram_ctrl_scrambed_access` (and should improve/fix related tests) on Darjeeling:
- The Darjeeling vseq is updated to match the latest software test; in particular the synchronization mechanism has been modified extensively since the integrated_dev branch was forked.
- The sampling frequencies are adjusted to operate with the real Darjeeling clock frequencies.
- OTP control request indexes are modified, because there are a different number of request/response channels in Darjeeling.
- Sampling of the `light_reset_req` signal must be performed more frequently because it is asserted only very briefly in response to a sw reset request.
=> [sram_ctrl] Bring up of sram_ctrl_scrambled_access in Darjeeling DV

hw/ip/aes/dv/env/seq_lib/aes_alert_reset_vseq.sv
AES expects fatal alerts, and setting the flag `expect_fatal_alerts` skips the check in `check_no_fatal_alerts` for the cases where there is a fatal (periodic) alerts.
=> [dv, aes] enable flag `expect_fatal_alerts`

hw/ip_templates/rv_plic/fpv/tb/coverage_waivers.tcl.tpl, hw/top_darjeeling/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_earlgrey/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
Since the interrupts are level triggered, we don't use scr_q register in rv_plic_gateway. So, even if this logic is broken, nobody (in the assertions world) cares.
=> [rv_plic, fpv] Interrupts are level triggered

.github/workflows/ci.yml
Manual cherry-pick of #25882
The Ubuntu 20.04 runner is now completed disabled by GitHub, so we need this to fix CI.
=> Cherry-pick to earlgrey_1.0.0: [ci] Bump verilator test runner to ubuntu-22.04

hw/dv/sv/cip_lib/cip_base_env_cfg.sv, hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv, hw/ip/rom_ctrl/dv/env/rom_ctrl_env_cfg.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
This PR is meant to remove the rom_ctrl warnings which said the arguments in the `tl_access*` task don't match the ones in the parent class.
There's no need to override the method now, instead rom_ctrl_env_cfg overrides the `tl_access_timeout_ns` to the desired value.
The warnings were:
```
Warning-[MDVMO] Multiple default values in method override
../src/lowrisc_dv_rom_ctrl_env_0.1/seq_lib/rom_ctrl_base_vseq.sv, 28
rom_ctrl_env_pkg, "rom_ctrl_env_pkg_rom_ctrl_base_vseq_11_0::tl_access"
The class method argument 'tl_access_timeout_ns' has different default 
values specified at the base 
("../src/lowrisc_dv_cip_lib_0/seq_lib/cip_base_vseq.sv", 178) and the 
current definition.
VCS resolves default arguments of functions at compile time so the current 
one will be used regardless of virtual …
```
=> Remove rom ctrl base vseq warnings

sw/host/opentitantool/src/command/lc.rs
This change adds a flag (`--use_external_clk`) to the the life cycle transition and raw_unlock commands. The default is set to `false` to rely on the internal DUT clock.
=> [ottool] Add ext_clk flag to lc transition/raw_unlock commands.

hw/ip/spi_device/data/spi_device.hjson, hw/ip/spi_device/doc/registers.md
Update the FLASH_STATUS description to show how the updates occur on byte boundaries, whereas the passthrough gate still updates only on CSB deassertion.
=> [spi_device] Clarify FLASH_STATUS behavior

sw/device/silicon_creator/lib/ownership/test_owner.c, sw/device/silicon_creator/lib/rescue/rescue.c, sw/device/silicon_creator/lib/rescue/rescue.h, sw/device/silicon_creator/lib/rescue/rescue_xmodem.c, sw/device/silicon_creator/rom_ext/defs.bzl, sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD, sw/host/opentitantool/src/command/rescue.rs
1. Add a `no-op` mode to rescue so that the xmodem protocol is functional if the owner disables the `RescueFirwmare` command.
2. Make the `no-op` mode the default if `RescueFirmware` is absent from the allowed commands list.
3. Test that the rescue protocol is functional when the `RescueFirmware` mode is not in the list of allowed commands.
=> [rescue, rom_ext_e2e] Test rescue with a restricted command set

sw/device/silicon_creator/rom_ext/imm_section/imm_section_version_def.c
We cannot record clean/modified status because this affects build reproducibility during ROM_EXT signing.
During a signing ceremony:
- First we generate pre-signing artifacts, typically in a clean codebase.
- Next, we take hashes of the pre-signing artifacts offline and sign them with our signing infrastructure.
- Finally, we bring the offline signatures back to the codebase and land them in an appropriate `signatures` subdirectory.  This modifies the codebase, which then causes a change in the build_status value, which causes bazel to rebuild pre-signing artifacts, which invalidates the signatures.
=> [imm_section] Do not record the codebase clean/modified status

sw/host/opentitanlib/src/app/config/hyperdebug_chipwhisperer.json, sw/host/opentitanlib/src/app/config/hyperdebug_cw340.json, sw/host/provisioning/ft/src/main.rs
PR #27011 updated the default configuration of IOA2 to prevent provisioning flows accidentally entering SPI rescue. This applies the fix to both hyper310 and hyper340 boards.
Additionally, this decreases the default FT timeout to reduce CI times.
=> [opentitanlib,manuf] apply #27011 to hyper310 and decrease FT timeout

sw/device/lib/ujson/ujson.c, sw/device/lib/ujson/ujson_test.cc
This PR is a manual cherrypick of #26610.
- #26610
=> Cherrypick to earlgrey_1.0.0: [ujson] Fix potential unsigned underflow/overflow.

sw/device/tests/kmac_error_conditions_test.c
Actually check for test result rather than just ignoring them.
=> [test, kmac] add missing `CHECK_STATUS_OK` for kmac error test

sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.cc, sw/device/silicon_creator/lib/drivers/mock_flash_ctrl.h, sw/device/silicon_creator/lib/ownership/owner_block.c, sw/device/silicon_creator/lib/ownership/owner_block.h, sw/device/silicon_creator/lib/ownership/owner_block_unittest.cc, sw/device/silicon_creator/lib/ownership/ownership.c, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/host/tests/ownership/flash_permission_test.rs
The owner-level INFO pages have a `lock` bit in their configuration that
specifies that their configuration should be locked by the ROM_EXT
before booting the owner firmware.
1. Add a function to lock the so-configured INFO pages.
2. Perform the lockdown before booting owner firmware and before entering rescue mode.
3. Add tests.
=> [ownership] Lock owner INFO pages 

hw/ip/otp_ctrl/data/earlgrey_skus/sival/BUILD, hw/top_earlgrey/dv/chip_rom_tests.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_ft_perso_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, sw/device/silicon_creator/manuf/base/binaries/BUILD
This adds the perso simulation configuration to enable ATE itegration of the personalization flow.
=> [dv] add perso sim configuration

hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
This is completely equivalent, but a bit shorter. The Verissimo lint tool also raises an error for the more verbose version. Use the shorter one.
=> [rom_ctrl,dv] Use foreach in a vseq

hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv
This PR adds the ability to log an RACL violation as part of a denied access, which was previously missing in the implementation.
Closes #25454
=> [hw,ac_range,rtl] Log RACL hit on denied accesses

hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv
Only log a failed access when the range that denied the access actually has its logging functionality enabled. Indexing into the log mask must be done in the right order. Don't create a reversed mask from the beginning.
This PR closes #25456.
=> [hw,ac_range,rtl] Only log if per-range log bit is enabled

hw/dv/sv/dv_utils/dv_report_catcher.sv
It turns out that foreach doesn't iterate over multi-dimensional arrays like that. Apparently, we tested with tools that do what we wanted, but the Verissimo tool correctly points out that the standard doesn't require it to work.
Switch to a form that is allowed.
=> [dv] Correct foreach syntax in dv_report_catcher

SUMMARY.md, book.toml
When set, this option automatically creates missing pages. This can be annoying if people accidently put fragments or URLs in the SUMMARY.md, which mdBook interprets as a missing page.
=> [doc] Disable mdBook's create-missing

hw/ip/prim/rtl/prim_subreg_arb.sv
The SystemVerilog spec doesn't technically allow this because the stuff in this test is a constant expression ("constant_expression" in section A8.3 of the spec). But this doesn't allow an "inside_expression", unlike a normal expression.
How annoying! Expand the check to be explicit.
This was found by the Verissimo linting tool (thanks, guys!)
=> [prim,rtl] Avoid using inside in a constant expression

hw/ip/pattgen/dv/env/seq_lib/pattgen_perf_vseq.sv
This gets rid of a build warning (one field is a 10 bit variable and the other is 6 bits; the original author had just got the two ranges backwards).
=> [pattgen,dv] Fix constraint in pattgen_perf_vseq

sw/device/lib/testing/test_framework/ottf_console.c, sw/device/silicon_creator/manuf/base/BUILD, sw/device/silicon_creator/manuf/base/sram_ft_individualize.c, sw/host/opentitanlib/src/console/spi.rs, sw/host/provisioning/ft/src/main.rs, sw/host/provisioning/ft_lib/src/lib.rs
This contains two commits that:
1. updates the individualization firmware to use the SPI console GPIO TX-indicator pin to reduce the amount of traffic on the SPI console to simplify ATE integrations, and
2. remove SRAM execution done print.
Regarding the second item/commit, when SRAM programs complete execution they set the stack pointer to a magic value. We can detect this magic value instead of requiring the host to wait until a message is printed over the console. This eliminate more unneeded traffic on the SPI console.
Note this depends on #26982, only review the last two commits.
=> [individualize] use SPI console GPIO TX-indicator pin and remove done indication print

sw/otbn/crypto/ed25519.s, sw/otbn/crypto/field25519.s, sw/otbn/crypto/tests/ed25519_ext_add_test.s, sw/otbn/crypto/tests/field25519_test.s, sw/otbn/crypto/x25519.s
This change speeds up Ed25519 and X25519 by about 30%. The core algorithm is the same, but by using OTBN's particular interface slightly more cleverly and combining the multiply with the reduce, we can save quite a few instructions, ending up with only 24 instructions per multiply and 22 per square.
I proved both the multiply and square algorithms correct in Coq here against a simplified OTBN model, just for my peace of mind:
https://gist.github.com/jadephilipoom/41bb78778ddffdcd3f9e17ae5be26c73
=> [crypto] Speed up multiplication and squaring mod 2^255 - 19.

sw/host/opentitanlib/src/app/config/hyperdebug_chipwhisperer.json, sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
Configure IOA2 as a push-pull output with a default level of logic-low. Currently, we use IOA2 as a trigger for SPI rescue in some configurations.  This change prevents errant triggering of SPI resuce and regularizes the configuration across hyperdebug configurations.
=> [opentitanlib] Configure IOA2 for testing

sw/device/silicon_creator/lib/drivers/rstmgr.c, sw/device/silicon_creator/lib/drivers/rstmgr.h, sw/device/silicon_creator/lib/rescue/dfu.c, sw/device/silicon_creator/lib/rescue/rescue_spi.c, sw/device/silicon_creator/lib/rescue/rescue_xmodem.c, sw/device/silicon_creator/rom_ext/e2e/BUILD, sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c
1. Clear power-on-reset in self-requested reboots.
2. Test that the ROM_EXT preserves any boot_svc message sent to itself (e.g. power-on-reset is cleared so that the ROM won't re-scramble RET-RAM).
=> [rom_ext] Clear power-on-reset in self-requested reboots

hw/ip_templates/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv.tpl, hw/top_darjeeling/dv/env/seq_lib/chip_sw_csrng_lc_hw_debug_en_vseq.sv, hw/top_darjeeling/dv/env/seq_lib/chip_sw_lc_ctrl_transition_vseq.sv, hw/top_darjeeling/dv/env/seq_lib/chip_sw_sram_ctrl_execution_main_vseq.sv, hw/top_darjeeling/ip_autogen/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_flash_init_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_flash_rma_unlocked_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_ctrl_transition_vseq.sv, hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv
Generate this code to handle the differences between tops. Change top-level tests to accomodate the changes. Most work happens in darjeeling since the previous interface was simply not right.
Fixes #26288
=> [ipgen,otp_ctrl] Generate the otp_ctrl_mem_bkdr_util code

hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/doc/interfaces.md, hw/ip/sram_ctrl/rtl/sram_ctrl.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_darjeeling/templates/toplevel.sv.tpl, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_earlgrey/templates/toplevel.sv.tpl, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv, util/raclgen.py, util/reggen/bus_interfaces.py, util/topgen/templates/toplevel_racl_parameters.tpl, util/topgen/templates/toplevel_racl_pkg.sv.tpl, util/topgen/templates/toplevel_racl_pkg_parameters.tpl, util/topgen/templates/toplevel_racl_signals.tpl
A previous commit changed RACL ranges from a parameter to a signal, however the topgen templates were not updated.
This commit fixes RACL ranges up such that they are working again with topgen:
* RACL range support was added to bus_interfaces.py such that the template can know which interface uses RACL ranges.
* The parameter RaclPolicySelRangesRamNum was removed from the ip hjson and its name aligned with what the template previously generated. The template now also generates the necessary default value if RACL ranges are disabled.
* toplevel_racl.tpl was split into two files to allow generating the necessary parameters and signals: toplevel_racl_parameters.tpl and toplevel_racl_signals.tpl
* The toplevel_racl_pg.sv.tpl has been updated to only emit RACL range parameters for interfaces …
=> [RACL] Fix up RACL ranges support

hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, util/topgen.py
The otp_ctrl interface to export the flash_keys is only needed if the otp secret1 partition holds flash_ctrl keys. Darjeeling has no flash and has no keys in otp.
Detect this examining the content of the otp rather than using an ipgen_param.  This assumes the flash keys are in the secret1 partition, and are named "flash*key_seed" (case doesn't matter). If in some future otp mmap the location of these keys changes we can revisit this detection.
Addresses #26553
Fixes #26931
=> [topgen,otp_flash_keys] Deduce if flash_keys are needed in otp_ctrl

hw/ip_templates/rv_core_ibex/data/rv_core_ibex.hjson.tpl, hw/ip_templates/rv_core_ibex/rtl/rv_core_ibex.sv.tpl, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_darjeeling/ip_autogen/rv_core_ibex/rtl/rv_core_ibex.sv, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex.sv, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_englishbreakfast/ip_autogen/rv_core_ibex/rtl/rv_core_ibex.sv, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv, hw/vendor/lowrisc_ibex.lock.hjson, hw/vendor/lowrisc_ibex/doc/03_reference/cs_registers.rst, hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml, hw/vendor/lowrisc_ibex/dv/verilator/simple_system_cosim/ibex_simple_system_cosim.core, hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv, hw/vendor/lowrisc_ibex/rtl/ibex_core.sv, hw/vendor/lowrisc_ibex/rtl/ibex_cs_registers.sv, hw/vendor/lowrisc_ibex/rtl/ibex_decoder.sv, hw/vendor/lowrisc_ibex/rtl/ibex_lockstep.sv, hw/vendor/lowrisc_ibex/rtl/ibex_pkg.sv, hw/vendor/lowrisc_ibex/rtl/ibex_top.sv, hw/vendor/patches/lowrisc_ibex/rtl/0001-PATCH-Change-RAM-DFT-signals.patch
This PR re-vendors Ibex and then adds support for passing the new Ibex parameters for mvendorid/mimpid  from the top. The current parameter selection (0/0) is the same as the current behavior. Integrators may set that to a different value.
=> [rv_core_ibex, ibex, rtl] Re-vendor Ibex and pass mvendorid/mimpid to Ibex

sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/e2e/BUILD, sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c
1. Detect if we're executing in a low-power-wakeup state.  Do not execute boot_svc or rescue entry when waking from low power.
2. Upon entering rescue, disable the watchdog timer.
3. Update the inactivity timeout test to use the watchdog-enabled OTP configuration.
=> [rom_ext] Disable the watchdog when entering rescue

sw/device/lib/runtime/print.c, sw/device/lib/runtime/print.h, sw/device/lib/testing/test_framework/ottf_console.c, sw/device/lib/testing/test_framework/ottf_console.h, sw/device/lib/testing/test_framework/ottf_test_config.h, sw/device/lib/testing/test_framework/ujson_ottf.c, sw/device/lib/testing/test_framework/ujson_ottf.h, sw/device/lib/ujson/example_roundtrip.c, sw/device/lib/ujson/test_helpers.h, sw/device/lib/ujson/ujson.c, sw/device/lib/ujson/ujson.h, sw/device/silicon_creator/manuf/base/BUILD, sw/device/tests/BUILD, sw/device/tests/ottf_console_with_gpio_tx_indicator_test.c, sw/host/opentitanlib/src/uart/console.rs, sw/host/tests/chip/ottf_console_with_gpio_tx_indicator/BUILD, sw/host/tests/chip/ottf_console_with_gpio_tx_indicator/src/main.rs
When using the spi_device transport for the OTTF console, a header is attached to every data payload before writing the data payload to the spi_device flash buffer (to be later read out by the host). This creates a large overhead (12-bytes) when the data payload is small (e.g., only a single character).
Moreover, the way the UJSON message transmit macros are implemented, results in writing several small strings, or even single characters, to the printf (console) sink function. This created an unncessarily large number of SPI console frames when sending the `perso_blob_t` UJSON struct to the host.
This commit adds a SW buffering mechanism to the OTTF SPI console to collect all small strings / single character writes into a single large SPI console transaction. This greatly improves the …
=> [ottf_console] buffer SPI console data in SW

sw/host/provisioning/ft_lib/src/lib.rs
The FT test harness can check the console output from owner firmware (transport) images loaded during personalization, and booted after personalization completes. However, the console output checked should be specified in the orchestrator HJSON configuration file, not hardcoded into the test harness.
=> [ft] remove SKU-specific owner FW boot message checks

sw/host/opentitantool/src/command/ownership.rs
This introduces a new `ownership digest` subcommand to `opentitantool`. This command allows users to compute the SHA256 digest of an owner block binary, excluding the signature and seal bytes.
=> [opentitantool] Add `ownership digest` command

sw/host/opentitanlib/src/ownership/misc.rs, sw/host/opentitanlib/src/ownership/mod.rs, sw/host/opentitanlib/src/ownership/signature.rs, sw/host/opentitantool/src/command/ownership.rs
This introduces a new `ownership detached-signature` subcommand to `opentitantool`. This command allows users to generate a detached signature binary from the existing raw signature files
=> [opentitantool] Add `ownership detached-signature` command

hw/ip/adc_ctrl/dv/env/adc_ctrl_env_cfg.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv, hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_erase_suspend_vseq.sv, hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_mp_vseq.sv, hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv, hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_fetch_code_vseq.sv, hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_full_mem_access_vseq.sv, hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_mid_op_rst_vseq.sv, hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv, hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_base_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_erase_suspend_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_mp_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_fetch_code_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_full_mem_access_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_mid_op_rst_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_base_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_erase_suspend_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_mp_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_error_prog_type_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_fetch_code_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_full_mem_access_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_mid_op_rst_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_mp_regions_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_otf_base_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_base_vseq.sv
The changes in PR #26908 don't quite do what we want. Before that PR, we had code like
```
foreach (foo[a]) {
foreach (foo[a][b]) {
...
}
}
```
Some lint tools warn that the inner foreach loop is badly formed, and I think they might be correct. The IEEE 1800 spec doesn't seem to allow this syntax. The start of section 12.7.3 (about the foreach loop) says:
> The foreach-loop construct specifies iteration over the elements of
> an array. Its argument is an identifier that designates any type of
> array followed by a comma-separated list of loop variables enclosed
> in square brackets.
This doesn't match the syntax for the inner loop in the example because "foo[a]" is not an identifier.
The changes in the PR converted that example to something like
```
foreach (foo[a]) {
foreach (foo[a, b]) …
```
=> [dv] Iterate more carefully with foreach loops

hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
The branch appeared as undetectable with a jasper description saying "implicit else". Tidying up the branch into the precondition part of the assertion would make it more clean and get rid of the undetectable coverage complain.
=> [rv_plic, fpv] Tidying up the branch condition into assertion

hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_smoke_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_spien_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_status_stall_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_upper_range_clkdiv_vseq.sv, hw/ip/spi_host/dv/env/spi_host_env.sv, hw/ip/spi_host/dv/env/spi_host_env_cfg.sv, hw/ip/spi_host/dv/env/spi_host_env_pkg.sv, hw/ip/spi_host/dv/env/spi_host_scoreboard.sv, hw/ip/spi_host/dv/env/spi_host_seq_cfg.sv, hw/ip/spi_host/dv/spi_host_fsm_if.sv, hw/ip/spi_host/dv/spi_host_sim.core, hw/ip/spi_host/dv/tb.sv
Split the clk-divider high values to be tested in a different config which sets  a `define and decrements the pres-scaler in 16-units to quicken up simulation.
Tweaked TB knobs to reduce test duration in general.
Extra checks in VSEQs to avoid timeouts in corner case situations
=> Spi host timeout fixes and clkdiv testing

hw/ip/rv_timer/dv/env/rv_timer_env.core, hw/ip/rv_timer/rv_timer.core, hw/ip/rv_timer/rv_timer_reg_pkg.core
This will allow the TB to derive DV parameters from the templated rv_timer_reg_pkg.sv instead of having hardcoded values
=> Rv timer new reg pkg

sw/device/lib/runtime/print.c, sw/host/opentitanlib/src/console/spi.rs, sw/host/tests/chip/ottf_console_with_gpio_tx_indicator/src/main.rs
This optimizes the TX-ready GPIO feature by only writing one frame at a time to the SPI flash buffer and monitoring the chip-select state for when the device is free to overwrite the data in the buffer (i.e., the host has read out the data). This eliminates the need to add delays between TX-ready GPIO toggling.
=> [ottf_console] optimize TX-ready GPIO feature

sw/device/tests/BUILD, sw/device/tests/example_test_from_rom.c
This test had the Darjeeling execution environment added but was still using Earlgrey constants.
=> [test] Port `example_test_from_rom` to DT

hw/ip/rom_ctrl/dv/tb/rom_ctrl_compare_if.sv
I hadn't realised that "force" behaves like a continuous assignment, so my previous code was essentially doing:
assign foo = ~foo;
This gives you an infinite loop in the simulator. D'oh...
=> [rom_ctrl,dv] Fix forcing in rom_ctrl_compare_if

hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
Adjusted the testplan to include the new FIPS-mode health tests for the entropy source. Adjusted the testplan to include the new BYPASS-mode health tests for the entropy source.
As per advice from vogelpi in #27064
=> [ip/chip_entropy_src] Update chip_entropy_src_testplan.hjson

sw/device/lib/base/BUILD, sw/device/lib/base/ibex.c, sw/device/lib/base/ibex_test.c
When this library was moved from the cryptolib to the base libraries, it wasn't ported to multitop. This change is necessary for #26753
=> [sw/base] Make the ibex library top-independent

sw/device/lib/base/ibex.c, sw/device/lib/base/ibex.h, sw/device/lib/base/ibex_test.c
Fixing a few things I noticed about the new Ibex driver when I attempted to use it.
1. **Always wait for entropy to become valid before reading the register.** Skipping this could lead to repeated "random" values!
2. Add warnings to function documentation about initializing the entropy complex before calling functions that could hang.
3. The Ibex driver has no need to return status values, since it can't return errors. We can save some code-size-heavy `TRY` macros and some complexity by skipping the indirection.
On further inspection, it looks like this code was likely copied from `sw/device/lib/dif/div_rv_code_ibex.{c,h}` and then only lightly modified. As a more general caution, DIFs serve a very different purpose than security-critical base or cryptography libraries; they expose all …
=> [base] Make Ibex driver return values directly, and wait for valid.

hw/ip/soc_dbg_ctrl/data/soc_dbg_ctrl.hjson, hw/ip/soc_dbg_ctrl/doc/registers.md, hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl_core_reg_top.sv, hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl_jtag_reg_top.sv, hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl_reg_pkg.sv
- Reset of the DEBUG_POLICY_CATEGORY registers was initialized to 0x0 but it should be 0x50 (= `DbgCategoryLocked`).
=> [soc_dbg_ctrl] Fix register reset value

hw/ip/soc_dbg_ctrl/dv/sva/soc_dbg_ctrl_bind.sv
- Fix typo for soc_dbg_ctrl_jtag_csr_assert_fpv binding module
=> [soc_dbg_ctrl,dv] Fix JTAG CSR assert

sw/device/lib/dif/dif_pwrmgr.h, sw/device/lib/dif/dif_pwrmgr_unittest.cc, sw/device/tests/clkmgr_off_peri_test.c, sw/device/tests/pwrmgr_sleep_resets_lib.c, sw/device/tests/rstmgr_alert_info_test.c, sw/device/tests/rstmgr_cpu_info_test.c, sw/device/tests/sim_dv/pwrmgr_random_sleep_power_glitch_reset_test.c, sw/device/tests/sim_dv/pwrmgr_sysrst_ctrl_test.c, sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c, sw/device/tests/soc_proxy_smoketest.c, sw/device/tests/sram_ctrl_sleep_sram_ret_contents_impl.c
The goal of this PR is to remove this from the DIF headers:
```c
typedef enum dif_pwrmgr_reset_request_source {
kDifPwrmgrResetRequestSourceOne = (1u << 0),
kDifPwrmgrResetRequestSourceTwo = (1u << 1),
} dif_pwrmgr_reset_request_source_t;
```
Instead, the reset request sources can be queried via the DT.
Remaining issue:
=> Remove all hardcoded reset requests constants

sw/device/silicon_creator/manuf/base/sram_ft_individualize.c, sw/device/silicon_creator/manuf/lib/flash_info_fields.c, sw/device/silicon_creator/manuf/lib/flash_info_fields.h, sw/device/silicon_creator/manuf/lib/individualize.c, sw/device/silicon_creator/manuf/lib/individualize.h, sw/device/silicon_creator/manuf/lib/individualize_functest.c, sw/host/provisioning/orchestrator/configs/skus/emulation.hjson, sw/host/provisioning/orchestrator/configs/skus/emulation_dice_cwt.hjson, sw/host/provisioning/orchestrator/configs/skus/emulation_tpm.hjson, sw/host/provisioning/orchestrator/configs/skus/sival.hjson, sw/host/provisioning/orchestrator/src/device_id.py, sw/host/provisioning/orchestrator/src/devid_header_gen.py, sw/host/provisioning/orchestrator/src/orchestrator.py, sw/host/provisioning/orchestrator/src/ot_dut.py, sw/host/provisioning/orchestrator/src/sku_config.py, sw/host/provisioning/orchestrator/tests/e2e.sh, sw/host/provisioning/orchestrator/tests/e2e_multistage.sh, sw/host/provisioning/orchestrator/tests/e2e_option_flags.sh
Previously, the AST config version field was provided by the host during the FT individualization step. However, since the AST values are programmed to flash info page 0 during the CP stage, the AST configuration version is also known then. Therefore we add a field to flash info page 0 to store this field and overwrite this portion of the FT device ID during individualization before the device ID is written to OTP.
Additionally, since this field will be programmed during the CP calibration step, not provided during FT, there is no longer a need for this CLI switch within the orchestrator. Hence it is removed.
=> [individualize,orchestrator] add AST config version to flash info field

hw/ip/aes/dv/env/seq_lib/aes_wake_up_vseq.sv
Sysytem Verilog LRM doesn't allow direct assigning logic type variables to bit one.  Although some tools extend standard (print warnings) in general this code causes compilation errors. To avoid this the type of "init_key" array elements could be probably changed to bit.
=> [aes,dv] Change the type of init_key variable - logic to bit assignments are not allowed in SV

hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
From SV LRM:
```
6.16.3 Getc()
function byte getc(int i);
— str.getc(i) returns the ASCII code of the ith character in str.
— If i < 0 or i >= str.len(), then str.getc(i) returns 0.
```
Thus the type cast should be used to assign it to string variable.
=> [aes,dv] Add a cast for the byte type return of getc() function to string variable assignment

hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
The SystemVerilog LRM doesn't allow to use a  "+" operator for string literals concatenation. It should be replaced with correct form of concatenation expression (using {} brackets).
=> [entropy_src, dv] Fix incorrect string concatenation

hw/dv/sv/tl_agent/tl_monitor.sv
The motivation was to stop it from seeing A- or D-channel transactions when reset has actually been asserted.
(These don't normally happen, but I had a bug in a UVM driver that caused them. The monitor should probably ignore them though!)
=> [tl,dv] Clean up how tl_monitor tracks resets

hw/ip/soc_dbg_ctrl/data/soc_dbg_ctrl.hjson
- Add excl:CsrNonInitTests tag property to some of the registers for which the internal HW logic is special and cannot be automatically checked with our test suite.
=> [soc_dbg_ctrl,dv] Exclude regs from CSR tests

hw/ip/rv_timer/README.md
Specify the design is configurable but current implementation only wires up one timer for one hart.
=> [doc, rv_timer] Doc clarification

sw/device/lib/ujson/ujson.c, sw/device/lib/ujson/ujson_test.cc
This change implements parsed for quoted integers. The implementation authored by cfrantz@google.com.
JSON messages generated by protobuf libraries will use quoted strings for `uint64` types. See for example:
```json
{
"wafer_auth_secret": [
2790285947,
1491553456,
2694274708,
1137231153,
1404344500,
190480117,
3248928340,
4233979174
],
"test_unlock_token_hash": [
"18123448053906926503",
"14479932172051545263"
],
"test_exit_token_hash":[
"895855566562726762",
"1749132506438826860"
]
}
```
The change provided in this patch allows the device to parse the payload above. Before this change, the ujson module would return a parsing integer error.
=> [ujson] Add support for quoted integers.

rules/manifest.bzl, sw/device/silicon_creator/lib/manifest.c, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/defs.bzl, sw/device/silicon_creator/rom_ext/e2e/secver/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/device/silicon_creator/rom_ext/sival/BUILD
1. Make the ROM_EXT detect the `secver_write` extension in the manifest. If present and the manifest security version is greater than the current boot_data minimum security version, update the value and write boot_data.
2. Add a string flag to the build system that allows the `secver_write` value to be set at build time.
3. Add a test which sequences firmware through a series of ROM_EXTs which advance the security version.  Confirm each update and confirm that an older ROM_EXT will no longer execute.
=> [rom_ext] Advance the security version if requested

hw/ip/aes/dv/env/seq_lib/aes_wake_up_vseq.sv
There is no functional change here. The commit was motivated by a Verible check (because of long lines), but I'm also rejigging things slightly to use out-of-block definitions and avoid unnecessary class variables.
=> [aes,dv] Reformat aes_wake_up_vseq

hw/ip_templates/otp_ctrl/rtl/otp_ctrl_macro_pkg.sv.tpl
If the OTP depth is not a power of 2, we need to always round up to get the number of address bits. The previously used `round` function can round down or up, depending on the value, which is wrong. We need to always round up to get the last bit.
Because the upstream OTP maps have all a depth value that is a power of two, this change does not trigger any RTL change but only a template change.
=> [hw,otp_ctrl,rtl] Use math.ceil to determine the required address bits

sw/device/tests/BUILD, sw/device/tests/clkmgr_off_aes_trans_test.c, sw/device/tests/clkmgr_off_hmac_trans_test.c, sw/device/tests/clkmgr_off_kmac_trans_test.c, sw/device/tests/clkmgr_off_otbn_trans_test.c, sw/device/tests/clkmgr_off_trans_impl.c, sw/device/tests/clkmgr_off_trans_impl.h
Port of these tests to DT and they still function on Earl Grey. Darjeeling tests will not yet complete successfully within the expected time frame because the clocks still need to be set appropriately in _both_ DV/HW and software.
The test presently still exercises only the first instance of each type of IP block but has been modified with a view to supporting multiple instances later. No extant top has multiple instances at present.
=> [darjeeling] Bring up clkmgr_off_ tests

hw/top_earlgrey/dv/chip_manuf_ate_tests.hjson, hw/top_earlgrey/dv/chip_rom_tests.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_ate_bootstrap_flash_erase_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
This contains two commits that:
1. consolidates all manufacturing ATE bringup tests to a separate dvsim configuration file, and
2. adds a simple ATE DV test that puts the DUT in bootstrap mode and then drives the correct SPI sequence to erase all of flash, which is the first part of performing a bootstrap operation.
=> [dv,ate] add ATE test to perform bootstrap erase

util/container/Dockerfile
The "build Docker containers" GitHub action generates warnings otherwise.
=> [util] Avoid "ENV NAME value" and use "ENV NAME=value" instead

hw/ip_templates/rv_plic/fpv/tb/coverage_waivers.tcl.tpl, hw/top_darjeeling/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_earlgrey/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
Since rv_plic registers has no regwen type, the mubi(4-16)_and_hi calls inside the unique case block are unused and appeared as dead branches and statements inside prim_mubi_pkg for mubi(4-16)_and.
=> [rv_plic, fpv] Unused code block because of NoRegwen type

hw/ip/usbdev/dv/tb/tb.sv
Xcelium 23.09.s002 throws the warning about the port not connected.
=> [usbdev, Xcelium] Unconnected output port ram_cfg_rsp_o

hw/ip_templates/gpio/dv/tb/tb.sv.tpl, hw/top_darjeeling/ip_autogen/gpio/dv/tb/tb.sv, hw/top_earlgrey/ip_autogen/gpio/dv/tb/tb.sv, hw/top_englishbreakfast/ip_autogen/gpio/dv/tb/tb.sv
Xcelium 23.09.s002 throws the warning about the racl ports being unconnected.
=> [gpio, Xcelium] Unconnected racl ports

hw/ip/uart/dv/env/uart_scoreboard.sv, hw/ip/uart/dv/tb/tb.sv
- Xcelium 23.09.s002 throws the warning about the ports being unconnected.
- Unexpected semicolon after endtask
=> [Uart, Xcelium] Xcelium 23.09.s002 warnings

hw/ip/rom_ctrl/dv/tb/rom_ctrl_compare_if.sv
The previous logic was wrong because good_val has to be a static variable, which means that the initializer that was part of the variable definition only runs once.
(Well, that was silly! And it's kind of embarrassing how many times I had to run the code to figure out what was going on!)
=> [rom_ctrl,dv] Correctly force u_compare.state_d

hw/dv/sv/dv_base_reg/dv_base_reg.sv
This code was trying to ensure that the semaphore had exactly one token in it. Knowing that it would only ever have at most one token, the code worked by trying to get that token if there was one and then putting a new token in.
Casting the result of the try_get() function to void causes a lint error from Verissimo. And there's a simpler way to get the same behaviour: just make a new semaphore!
This would be a problem if anything took a reference to the old semaphore (leaving a "dangling pointer") but a quick grep shows that this doesn't happen.
=> [dv] Simplify use of dv_base_reg::atomic_en_shadow_wr

util/reggen/multi_register.py, util/reggen/reg_block.py
Honestly, this is slightly overengineered (the only place we can generate this exception catches it and throws it away!). But I thought it might make sense to store the information properly in case we care in the future.
Fixes #26545.
=> [reggen] Allow a multireg with count <= 0

hw/ip/soc_dbg_ctrl/dv/env/seq_lib/soc_dbg_ctrl_base_vseq.sv, hw/ip/soc_dbg_ctrl/dv/env/soc_dbg_ctrl_env.sv, hw/ip/soc_dbg_ctrl/dv/env/soc_dbg_ctrl_env_cfg.sv, hw/ip/soc_dbg_ctrl/dv/env/soc_dbg_ctrl_env_pkg.sv, hw/ip/soc_dbg_ctrl/dv/env/soc_dbg_ctrl_misc_io_if.sv, hw/ip/soc_dbg_ctrl/dv/soc_dbg_ctrl_sim.core, hw/ip/soc_dbg_ctrl/dv/tb.sv
Create an interface to handle miscellaneous signals without any attached UVM agent.
This PR resolves #27112.
=> [soc_dbg_ctrl,dv] Add VIF to drive misc IOs

sw/host/opentitanlib/src/proxy/handler.rs, sw/host/opentitanlib/src/proxy/protocol.rs, sw/host/opentitanlib/src/transport/proxy/uart.rs
It apperars that when adding a new method to the Uart trait for controlling break condition.  I forgot to add a corresponding new message to the proxy protocol.  With this patch, it becomes possible to use UART break (e.g. rescue protocol) via opentitansession.
=> [opentitanlib] Support UART break via proxy

hw/dv/tools/dvsim/sim.mk
When a filegroup is used to point to a SW image in a dvsim config file, and the filegroup lives in an external bazel repo, i.e., @manufacturer_test_hooks//..., excuting a `bazel cquery ...` operation on it to obtain the file paths will yield a partial path relative to the `bazel info output_base` path. We need to account for this in the sim.mk file when copying over Bazel build SW images to the dvsim run dir.
=> [dv] enable copying filegroup targest to run dir

hw/top_earlgrey/dv/chip_manuf_ate_tests.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_ate_bootstrap_one_frame_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, sw/device/silicon_creator/manuf/tests/BUILD
This adds a DV test that performs two basic bootstrap operations:
1. SPI flash erase, and
2. a single page program.
This is to facilitate bootstrap operation bringup in ATE environments. This fixes #27150.
=> [dv,ate] add test to bootstrap a single flash data page

hw/ip/soc_dbg_ctrl/dv/env/soc_dbg_ctrl_scoreboard.sv, hw/ip/soc_dbg_ctrl/rtl/soc_dbg_ctrl.sv
This PR fixes the assignment from the 'status' register on the core interface to the 'jtag_status' register on the JTAG interface, since the two packed structures involved have their sub-fields declared in opposing orders.
The structure assignment was fragile and it is considered preferable to assign the fields individually to defend against further changes.
A minor tweak is also made to the scoreboard in the DV environment to help keep the 'smoke' regression more usable for catching build issues/regressions until such time as it is further developed.
=> [soc_dbg_ctrl] Correct wiring fault in jtag_status register

hw/formal/tools/jaspergold/fpv.tcl, hw/ip_templates/rv_plic/fpv/tb/coverage_waivers.tcl.tpl, hw/top_darjeeling/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_earlgrey/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
This PR uses a mechanism to inject fault in the state register
of alert FSM. This mechanism is to create a stopat at state_q
so that jasper drives any possible value. When it does, we cover
the stimuli coverage for a default case in prim_alert_sender.
To cover the checker coverage, an assertion is added. This
assertion and stopat is created in a separate isolated task so
that none of our proved assertions fails when we are doing FI
in FPV.
=> [rv_plic, fpv] FI through stopat to generate stimuli coverage

rules/opentitan/cc.bzl, sw/device/silicon_creator/manuf/tests/BUILD
The personalization binary is combined with the transport image into a multislot binary payload that is bootstrapped during personalization. This updates `opentitan_binary_assemble` rule to build VMEM files for opentitantool-assembled multislot image so they can be loaded in DV to bringup ATE flows for manufacturing. This fixes #25977.
=> [bazel] enable building VMEM image for multislot bins

hw/top_earlgrey/dv/chip_manuf_ate_tests.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_ate_bootstrap_disjoint_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, rules/opentitan/cc.bzl, sw/device/silicon_creator/manuf/tests/BUILD
This adds a test that bootstraps a multislot flash image, skipping page programs of all 0xFF bytes to mimic how opentitantool implements bootsrap. This fixes #27151.
Note: this depends on #27215; only review the last commit.
=> [dv] add test to bootstrap a multislot flash image

sw/host/opentitanlib/src/io/uart.rs
This is required to develop a wrapper lib for provisioning that directly instantiates this struct with params.
=> [opentitanlib] make UartParams public

MODULE.bazel, sw/device/silicon_creator/lib/cfi.h, sw/device/silicon_creator/rom/BUILD, sw/device/silicon_creator/rom/doc/rom_customization.md, sw/device/silicon_creator/rom/hooks/BUILD.bazel, sw/device/silicon_creator/rom/hooks/MODULE.bazel, sw/device/silicon_creator/rom/hooks/README.md, sw/device/silicon_creator/rom/hooks/default_rom_hooks.c, sw/device/silicon_creator/rom/hooks/dummy_rom_hooks.c, sw/device/silicon_creator/rom/rom.c, sw/device/silicon_creator/rom/rom.h, sw/device/silicon_creator/rom/rom_state.c, sw/device/silicon_creator/rom/rom_state.h
This PR implements an initial framework for allowing vendors to customize OpenTitan ROMs with external , potentially closed-source hooks. See #25633 for more details on the problem statement and the proposed solution. 
This pull request is made of six commits:
1. `[sw,silicon_creator,rom] Add a ROM state API` is the main ROM vendor hooks implementation. It provides a set of C macros for defining ROM states and binding them with a run callback implementation. It also provides a simple API for walking through all defined states.
2. `[sw,silicon_creator,rom] Add dummy ROM state hooks` expands the `hooks_setup` bazel rules for supporting external ROM hooks repository. It also provides a dummy example of such a repository, with basic documentation on how to replicate that setup to actually …
=> RFC: Initial ROM vendor hooks implementation

hw/ip_templates/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv.tpl, hw/top_darjeeling/ip_autogen/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv, hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- The PR #27001 has introcudced a typo in the SCB when refering to the OTP macro RAL, which was obviously causing errors in simulation.
=> [otp_ctrl,dv] Fix SCB typo for OTP macro RAL

sw/device/silicon_creator/lib/ownership/ownership.c, sw/device/silicon_creator/lib/ownership/test_owner.c, sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/device/silicon_creator/rom_ext/sival/sival_owner.c
Erase all owner-reserved INFO pages during personalization to ensure that they're all known to be in the erased state.
=> [perso] Erase all owner-reserved INFO pages

sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/crypto/ecdsa.rs, sw/host/opentitanlib/util/BUILD, sw/host/opentitanlib/util/src/lib.rs, sw/host/opentitantool/src/command/image.rs, sw/host/opentitantool/src/command/spx.rs, sw/host/sphincsplus/BUILD, sw/host/sphincsplus/lib.rs, sw/host/sphincsplus/signature.rs
This PR includes 2 commits:
1. Introduces the ability to parse ECDSA signatures from PEM-encoded files and a new utility function handles deviations from strict RFC 7468 PEM formatting,
2.  Introduces the ability to parse SPX+ signatures from PEM-encoded files and a new `SpxSignature` struct to 
encapsulate raw SPX+ signature.
=> [opentitanlib] Support ECDSA and SPX+ pem signature

rules/signing.bzl, sw/device/silicon_creator/lib/error.h, sw/device/silicon_creator/lib/ownership/datatypes.h, sw/device/silicon_creator/lib/ownership/keys/fake/BUILD, sw/device/silicon_creator/lib/ownership/keys/fake/app_dev_spx.h, sw/device/silicon_creator/lib/ownership/keys/fake/app_dev_spx.pem, sw/device/silicon_creator/lib/ownership/keys/fake/app_dev_spx.pub.pem, sw/device/silicon_creator/lib/ownership/keys/fake/app_prod_spx.h, sw/device/silicon_creator/lib/ownership/keys/fake/app_prod_spx.pem, sw/device/silicon_creator/lib/ownership/keys/fake/app_prod_spx.pub.pem, sw/device/silicon_creator/lib/ownership/owner_block.c, sw/device/silicon_creator/lib/ownership/owner_block.h, sw/device/silicon_creator/lib/ownership/test_owner.c, sw/device/silicon_creator/lib/sigverify/spx_verify.c, sw/device/silicon_creator/lib/sigverify/spx_verify.h, sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/host/opentitanlib/src/ownership/misc.rs
This is a manual cherry-pick of #25083 
1. Add fake SPX+ keys to the test_owner configuration.
2. Use key_ids to distinguish between plain and hybrid keys (hybrid
key_ids are the xor of the individual key_ids).
3. Detect the SPX manifest extensions and update the search key_id
accordingly.
4. Verify hybrid signatures by checking both ECDSA and SPX signatures.
=> Cherry-pick to master: [rom_ext] Add SPX+ verification for owner firmware

sw/host/opentitanlib/src/console/spi.rs, sw/host/provisioning/cp/src/main.rs, sw/host/provisioning/ft/src/main.rs, sw/host/tests/chip/ottf_console_with_gpio_tx_indicator/src/main.rs, sw/host/tests/chip/spi_device_ottf_console/src/main.rs, sw/host/tests/chip/spi_device_ujson_console_test/src/main.rs, sw/host/tests/crypto/aes_nist_kat/src/main.rs, sw/host/tests/crypto/drbg_kat/src/main.rs, sw/host/tests/crypto/ecdh_kat/src/main.rs, sw/host/tests/crypto/ecdsa_kat/src/main.rs, sw/host/tests/crypto/hash_kat/src/main.rs, sw/host/tests/crypto/hmac_kat/src/main.rs, sw/host/tests/crypto/kmac_kat/src/main.rs, sw/host/tests/crypto/sphincsplus_kat/src/main.rs, sw/host/tests/manuf/cp_provision_functest/src/main.rs
When opentitanlib is invoked via an external C/C++ wrapper library, the SpiConsoleDevice object is reinstantiated repeatedly to comply with Rust's ownership rules (and satisfy the borrow checker). On each reinstantiation of the SpiConsoleDevice struct, the next expected frame number is reset to 0. This causes the SpiConsoleDevice to ignore a valid frame when used through an external wrapper library, as is the case with the OtlibWrapper used in the opentitan-provisioning repo. This was causing CI issues in
https://github.com/lowRISC/opentitan-provisioning/pull/165.
As such, this provides a mechanism for users of the SpiConsoleDevice to ignore the frame number, which frankly  is not necessary when the SpiConsoleDevice is used alongside the TX-indicator GPIO feature. This feature does not …
=> [opentitanlib] add option to ignore SPI console frame numbers

sw/device/lib/base/BUILD, sw/device/lib/crypto/impl/BUILD, sw/device/lib/crypto/impl/hkdf.c, sw/device/lib/crypto/impl/integrity.c, sw/device/lib/crypto/impl/keyblob_unittest.cc, sw/device/lib/crypto/include/datatypes.h, sw/device/tests/crypto/cryptotest/firmware/BUILD, sw/device/tests/crypto/cryptotest/firmware/ecdh.c
Uses a CRC32 checksum to provide a lightweight integrity check on keys. The basic setup for this already existed, this commit just:
- fills in the stub
- corrects a few places that didn't write the checksum
- changes a couple fields in the key structs from `size_t` to `uint32_t`
The last item is so that we have consistency across platforms in how large the field is and can use `crc_add32` safely for host-side tests as well as device-side ones.
=> [crypto] Implement key integrity checksums.

doc/contributing/style_guides/otbn_style_guide.md
This is a small change to update out-of-date info in the OTBN Assembly Style Guide re: side channel protections--the `bn.mulqacc.so` instruction as currently documented in OT does set flags, and there is code that relies on `bn.mulqacc.so` setting flags for correctness (e.g. `mod_mul_256x256` in `p256_base.s`).
=> [doc] Update otbn_style_guide.md to correct out-of-date info about bn.mulqacc flags

hw/ip/rom_ctrl/rtl/rom_ctrl.sv
Fix a couple of assertions in the RTL (so that they become true!). There are detailed notes in the commit messages.
No change to the design.
=> [rom_ctrl,rtl] Fix some false assertions

hw/ip/prim/rtl/prim_assert_sec_cm.svh, hw/ip/rom_ctrl/rtl/rom_ctrl.sv
This is inspired by trying to do FPV for a block and the pesky Jasper tool pointing out that the assertions that say something will trigger an alert aren't actually true. The problem is that they are defined in terms of the `alert_tx_o` signal and the alert interface is stateful so a falsifier can just get it into a state where the alert doesn't come out!
Rather than making the assertion say something about the state of that interface, the first commit in this PR makes it possible to talk in terms of what we're passing *to* the alert system.
The second commit in the PR tweaks the top-level of `rom_ctrl` to use this weaker (and true!) assertion instead.
=> [rtl,fpv] Tweak some assertions so they might be true

hw/formal/tools/jaspergold/conn.tcl
This commit adds a stopat on the power-on reset input pin to exclude the internal pull-up logic from the connectivity analysis. This resolves lowRISC/OpenTitan#25567.
=> [top_earlgrey, conn] Exclude pull-up logic enabled on POR_N by default

hw/top_earlgrey/dv/chip_manuf_ate_tests.hjson, hw/top_earlgrey/dv/env/seq_lib/chip_sw_ate_bootstrap_disjoint_vseq.sv
The test was timing out and there was also a logic error in the code that verifies the contents of flash after a bootstrap operation.
=> [dv] fix disjoint bootstrap test

sw/device/lib/testing/json/provisioning_data.c, sw/device/silicon_creator/manuf/tests/BUILD, sw/device/silicon_creator/manuf/tests/ujson_msg_size_functest.c, sw/host/tests/manuf/manuf_ujson_msg_size/BUILD, sw/host/tests/manuf/manuf_ujson_msg_size/src/main.rs
This adds a test to print the max UJSON payload sizes for a subset of the payloads transmitted during personalization.
=> [test] add test to print UJSON payload max sizes

sw/device/lib/crypto/impl/keyblob.c, sw/device/lib/crypto/impl/keyblob.h, sw/device/lib/crypto/impl/keyblob_unittest.cc
Use the newly filled-in `random_order` primitive to harden the loop, and get randomness with `hardened_memshred` rather than an argument.
=> [crypto] Adjust keyblob remask routine.

sw/device/lib/base/hardened_memory.c
Follow-up from @pqcfox 's review on #27242 : https://github.com/lowRISC/opentitan/pull/27242#discussion_r2096310740
Adds a word-offset of 1 to the index of the second decoy in `hardened_memcpy` so that we have more possible source/d
destination pairs. Otherwise, there would only be 4 possible unique pairs; 4 word-sized increments after `decoy[3] = decoy[7]` would be `decoy[7] = decoy[3]`. Adding an offset results in 8 unique pairs for minimal overhead.
This doesn't really have an effect on `hardened_memeq` since all the decoys have to be equal there, but I changed it there anyway just to keep the pattern consistent.
=> [base] Increase the period of decoy pairs in `hardened_memory.c`.

sw/device/lib/crypto/impl/hkdf.c, sw/device/lib/crypto/impl/kdf_ctr.c, sw/device/lib/crypto/impl/key_transport.c, sw/device/lib/crypto/impl/key_transport_unittest.cc, sw/device/lib/crypto/impl/kmac_kdf.c, sw/device/lib/crypto/include/hkdf.h, sw/device/lib/crypto/include/kdf_ctr.h, sw/device/lib/crypto/include/key_transport.h, sw/device/lib/crypto/include/kmac_kdf.h, sw/device/tests/crypto/cryptotest/firmware/ecdh.c, sw/device/tests/crypto/hkdf_functest.c, sw/device/tests/crypto/kdf_hmac_ctr_functest.c, sw/device/tests/crypto/kdf_kmac_functest.c, sw/device/tests/crypto/kdf_kmac_sideload_functest.c
Most of the cryptolib already accepted keys by reference, not value, but the KDFs and export function didn't for some reason (likely simple carelessness on my part). This would make it difficult to re-mask the key and update the checksum, so this PR brings those trailing functions in line with their friends and passes the key by reference.
Groundwork for https://github.com/lowRISC/opentitan/issues/27243
=> [crypto] Always pass keys by reference.

sw/device/lib/testing/test_framework/ujson_ottf.h, sw/device/silicon_creator/manuf/tests/ujson_msg_size_functest.c, sw/host/opentitanlib/src/test_utils/gpio.rs, sw/host/opentitanlib/src/test_utils/i2c_target.rs, sw/host/opentitanlib/src/test_utils/mem.rs, sw/host/opentitanlib/src/test_utils/pinmux_config.rs, sw/host/opentitanlib/src/test_utils/rpc.rs, sw/host/opentitanlib/src/test_utils/spi_passthru.rs, sw/host/provisioning/cp_lib/src/lib.rs, sw/host/provisioning/ft_lib/src/lib.rs, sw/host/tests/chip/i2c_target/src/main.rs, sw/host/tests/chip/ottf_console_with_gpio_tx_indicator/src/main.rs, sw/host/tests/chip/spi_device_ujson_console_test/src/main.rs, sw/host/tests/crypto/aes_nist_kat/src/main.rs, sw/host/tests/crypto/drbg_kat/src/main.rs, sw/host/tests/crypto/ecdh_kat/src/main.rs, sw/host/tests/crypto/ecdsa_kat/src/main.rs, sw/host/tests/crypto/hash_kat/src/main.rs, sw/host/tests/crypto/hmac_kat/src/main.rs, sw/host/tests/crypto/kmac_kat/src/main.rs, sw/host/tests/crypto/sphincsplus_kat/src/main.rs, sw/host/tests/manuf/manuf_ujson_msg_size/src/main.rs, sw/host/tests/rescue/rescue_test.rs, sw/host/tests/rom/e2e_chip_specific_startup/src/main.rs, sw/host/tests/rom/sw_strap_value/src/main.rs
In manufacturing ATE environments, constant sized UJSON strings are preferred. CRCs are variable in length. Therefore, we enable setting the CRC to a fixed value of 0 and skipping the check on the host side.
Note: this depends on #27255, only review the last commit.
=> [ujson] enable skipping CRC sent with UJSON payloads

.github/workflows/cherrypick.yml
Adding the label is not enough to trigger CI, the PR must be closed and re-opened.
=> [ci] Correct cherry-pick CI trigger information

sw/device/lib/testing/json/provisioning_data.c, sw/device/lib/testing/json/provisioning_data.h, sw/device/lib/testing/test_framework/ujson_ottf.h, sw/device/lib/ujson/ujson.c, sw/device/lib/ujson/ujson.h, sw/device/lib/ujson/ujson_derive.h, sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/device/silicon_creator/manuf/tests/BUILD, sw/device/silicon_creator/manuf/tests/ujson_msg_padding_functest.c, sw/host/opentitanlib/src/test_utils/rpc.rs, sw/host/provisioning/ft_lib/src/lib.rs, sw/host/provisioning/ujson_lib/src/lib.rs, sw/host/tests/manuf/manuf_ujson_msg_padding/BUILD, sw/host/tests/manuf/manuf_ujson_msg_padding/src/main.rs
To facilitate bringup of the personalization flow in an ATE environment fixed sized UJSON messages are required. This updates the personalization flow to pad all UJSON messages between the host and device with whitespace before each message's trailing "}" character to ensure fixed size data transmissions.
Note: this depends on #27262; only review the last commit.
=> [personalize] pad UJSON messages to fixed sizes

sw/device/silicon_creator/manuf/base/BUILD, sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
This is a temporary work-around.  #27275 tracks the proper refactoring of the manufacturing build/sign rules.
=> [manuf] Disqualify staging targets for offline signing

sw/device/tests/crypto/BUILD, sw/device/tests/crypto/otcrypto_export_size.c, sw/device/tests/crypto/otcrypto_interface.c, sw/device/tests/crypto/otcrypto_interface.h
Developed with help from @cfrantz 
Create a struct to hold all the cryptolib algorithms, and a thin `main` function that uses it. Requires LTO to be turned off so that the whole struct is preserved. This is useful for measuring the size of the cryptolib itself when built for on-device targets.
Part of https://github.com/lowRISC/opentitan/pull/26322
=> [crypto] Create a test target to measure post-link cryptolib size.

sw/device/lib/crypto/impl/ecc/p384.c, sw/otbn/crypto/run_p384.s
This means the binary doesn't store a bunch of zeroes for no reason. Saves over 400 bytes of space. Found this in passing while working on https://github.com/lowRISC/opentitan/pull/27249
Requires setting padding on some of the buffers, since otherwise OTBN will lock in response to reading uninitialized memory.
=> [crypto] Change P-384 data to use .bss.

hw/ip/rom_ctrl/rtl/rom_ctrl_counter.sv, hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv
I spent some time understanding the design today and found it a bit hard. This comments should hopefully make it clearer.
Although the commits touch RTL, they are just comments: there is no functional change.
=> [rom_ctrl,rtl] Add some documentation comments in rom_ctrl

sw/host/hsmtool/acorn/acorn.rs, sw/host/hsmtool/acorn/spx.rs, sw/host/hsmtool/src/commands/spx/generate.rs, sw/host/hsmtool/src/commands/spx/import.rs, sw/host/hsmtool/src/commands/spx/list.rs, sw/host/hsmtool/src/extra/spxef.rs, sw/host/hsmtool/src/extra/spxkms.rs
CloudKMS is addedsupport for SLH-DSA signatures using the prehashed domain.  Add support for keygen, sign and verify with prehashing.
1. Check the domain during keygen.  CloudKMS encodes both the algorithm and domain into their notion of algorithm, so you must provide the domain at keygen time.
2. Check that the `domain` given for sign and verify matches the domain for which the key was generated.
=> [hsmtool] Add support for prehashing in CloudKMS

sw/device/lib/crypto/impl/ecc/p256.c, sw/device/lib/crypto/impl/ecc/p384.c, sw/device/tests/otbn_ecdsa_op_irq_test.c, sw/otbn/crypto/run_p256.s, sw/otbn/crypto/run_p384.s
Resolves #19875 
This was planned anyway but actually ends up being a helpful step to do before the ECC part of https://github.com/lowRISC/opentitan/issues/27243, because now we have an easy place to apply re-masking (at the same time the keys are moved).
=> [crypto] Store P-256 and P-384 keys in the scratchpad.

sw/device/tests/penetrationtests/firmware/fi/crypto_fi.c, sw/device/tests/penetrationtests/firmware/fi/ibex_fi.c, sw/device/tests/penetrationtests/firmware/fi/lc_ctrl_fi.c, sw/device/tests/penetrationtests/firmware/fi/otbn_fi.c, sw/device/tests/penetrationtests/firmware/fi/otp_fi.c, sw/device/tests/penetrationtests/firmware/fi/rng_fi.c, sw/device/tests/penetrationtests/firmware/fi/rom_fi.c, sw/device/tests/penetrationtests/firmware/lib/BUILD, sw/device/tests/penetrationtests/firmware/lib/pentest_lib.c, sw/device/tests/penetrationtests/firmware/lib/pentest_lib.h, sw/device/tests/penetrationtests/firmware/sca/aes_sca.c, sw/device/tests/penetrationtests/firmware/sca/edn_sca.c, sw/device/tests/penetrationtests/firmware/sca/hmac_sca.c, sw/device/tests/penetrationtests/firmware/sca/ibex_sca.c, sw/device/tests/penetrationtests/firmware/sca/kmac_sca.c, sw/device/tests/penetrationtests/firmware/sca/otbn_sca.c, sw/device/tests/penetrationtests/firmware/sca/sha3_sca.c, sw/device/tests/penetrationtests/json/crypto_fi_commands.h, sw/device/tests/penetrationtests/json/ibex_fi_commands.h, sw/device/tests/penetrationtests/json/lc_ctrl_fi_commands.h, sw/device/tests/penetrationtests/json/otbn_fi_commands.h, sw/device/tests/penetrationtests/json/otp_fi_commands.h, sw/device/tests/penetrationtests/json/pentest_lib_commands.h, sw/device/tests/penetrationtests/json/rng_fi_commands.h, sw/device/tests/penetrationtests/json/rom_fi_commands.h
This commit pulls over the following two commits from the master branch:
- 6381c7f6dd2f426b6ebe3712be0dd8cf0129b2f0: Read AST alerts and report them to the host
- e4cccb7: Allow configuring iCache and dummy instruction enable / disable
Moreover, commit 2eca32bc881e506d304a4bd8021bf765257ffd96 is changed such that it works with A1 and A2.
=> [pentest] Test configuration and reporting

util/raclgen.py
... Instead of relying on a fixed module name.
=> [raclgen] Use topgen.find_module to determine if racl_ctrl is present

hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
This fixes the warning: 
```
A variable of type string is supplied to (%d).
```
=> [hw,dv_base_reg_block,dv] Fix Xcelium 24.09 warning of passing a string arg

hw/ip/prim/rtl/prim_subreg.sv
It is documented that .qe only asserts on SW writes. In particular, the [docs](https://opentitan.org/book/util/reggen/index.html#register-definitions-per-type) say:
qe | output | Output register enable, scalar, true when bus interface writes to subreg
-- | -- | --
The current RTL, however, asserts this signal for both writes from software, but also from hardware.
This PR changes the behavior ot only assert the signal for SW writes.
=> [hw,prim_subreg,rtl] Assert qe only on SW writes

sw/device/tests/penetrationtests/firmware/fi/ibex_fi.c, sw/device/tests/penetrationtests/firmware/fi/rom_fi.h
This PR provides a couple of fixes for SRAM, FLASH, and ROM FI tests in three different commits:
- Check if the flash region we are trying to configure is locked. Abort with an error.
- Add rom_fi function header that was missing.
- Init the SRAM for the test
=> [pentest] Small fixes for FI tests

.github/workflows/pr_change_check.yml
The GitHub API refuses to give the list of changed files when there are too many of them.
This PR uses Git directly to get this list.
Note that the *master* branch version of this CI check is running on this PR, not the updated one.
=> [ci] Allow BLOCKFILE checker to handle many files

hw/ip/rom_ctrl/rtl/rom_ctrl_compare.sv
The previous version didn't get turned from an enum value to the underlying bits, which means that it generated a lint error from AscentLint (oops).
=> [rom_ctrl,rtl] Fix parameter value in prim_count instantiation

hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv
It's now clearer that we're saying "we don't use the top bits, and we have an assertion that says they were zero anyway".
=> [rom_ctrl,rtl] Avoid repetition in the code

hw/dv/sv/jtag_riscv_agent/jtag_riscv_driver.sv
We're deriving from uvm_driver, which is derived from uvm_component and needs the corresponding "utils" macro.
This was prompted by a lint warning from Verissimo.
=> [jtag,dv] Fix uvm_component_utils macro in jtag_riscv_driver

hw/dv/sv/cip_lib/cip_base_scoreboard.sv, hw/dv/sv/tl_agent/tl_seq_item.sv, hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv, hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
This has got dramatically simpler since #26724 was merged (and I clearly hadn't noticed I'd almost filed the same thing twice). Rebased, it has just one commit, with the following commit message:
> [tl,dv] Simplify tl_seq_item::is_ok
>
> This was inspired by a lint warning from Verissimo about casting the return of the function to void. That was done because the function had a side-effect and could generate an error.
>
> But there aren't many call sites (two!), so we can easily move that behaviour to the call site, and this allows us to simplify/shorten things as well.
>
> (The diffstat on the commit doesn't look so great, but that's because we have three templated copies of the +5/-1 change in flash_ctrl_scoreboard.sv)
=> [tl,dv] Lots of cleanups (and some documentation) in `tl_seq_item.sv`

hw/ip_templates/ac_range_check/data/ac_range_check.hjson.tpl, hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/ip_autogen/ac_range_check/data/ac_range_check.hjson, hw/top_darjeeling/ip_autogen/ac_range_check/doc/interfaces.md, hw/top_darjeeling/ip_autogen/ac_range_check/doc/registers.md, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv, hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check_reg_top.sv
This PR refactors the AC range interrupt handling and improves the combined clear and increment operation.
1.  **Interrupt Type:** Changes the AC range interrupt from an event-triggered to a status-based interrupt. This simplifies the logic as the counter's status directly dictates the interrupt condition.
2.  **Combined Clear/Increment:** Updates the clear and increment handling to use the `SET`-interface of the `prim_counter`. This ensures both actions are incorporated simultaneously.
* A clear without an increment now loads 0.
* A simultaneous clear and increment now loads 1.
=> [hw,ac_range_check,rtl] Switch to status interrupt and better clear behavior

hw/dv/sv/alert_esc_agent/alert_esc_if.sv, hw/dv/sv/alert_esc_agent/alert_monitor.sv, hw/dv/sv/alert_esc_agent/esc_monitor.sv, hw/dv/sv/csr_utils/csr_utils_pkg.sv, hw/dv/sv/dv_base_reg/csr_excl_item.sv, hw/dv/sv/dv_base_reg/dv_base_mem.sv, hw/dv/sv/dv_base_reg/dv_base_reg_pkg.sv, hw/dv/sv/dv_lib/dv_base_env_cfg.sv, hw/dv/sv/dv_utils/dv_utils_pkg.sv, hw/dv/sv/sec_cm/prim_count_if.sv, hw/dv/sv/sec_cm/prim_double_lfsr_if.sv, hw/dv/sv/sec_cm/prim_onehot_check_if.sv, hw/dv/sv/sec_cm/prim_singleton_fifo_if.sv, hw/dv/sv/sec_cm/prim_sparse_fsm_flop_if.sv, hw/dv/sv/sec_cm/sec_cm_pkg.sv, hw/dv/sv/tl_agent/tl_agent_pkg.sv, hw/dv/sv/tl_agent/tl_monitor.sv, hw/dv/sv/tl_agent/tl_reg_adapter.sv
This was originally inspired by looking at some messages from the Verissimo linter but (working through a bunch of them) I found quite a few places things could be simpler and more informative. This PR is the result!
=> [dv] Tweak how we pass the "id" argument to some uvm_info/uvm_error calls

util/dtgen/helper.py, util/i2csvg.py, util/reggen/gen_cheader.py, util/reggen/html_helpers.py, util/topgen/secure_prng.py
The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
This small PR resolves it.
=> [util] Modernize logger interface

hw/check_tool_requirements.core
A simple fix that was raised during the new Fusesoc integration.
=> [corefiles] Apply user file type to python files

sw/host/opentitanlib/src/app/config/hyperdebug_teacup_bga69.json, sw/host/opentitanlib/src/app/config/mod.rs, sw/host/opentitanlib/src/backend/mod.rs
Add a configuration for hyperdebug with the BGA69 Teacup shield.
=> [opentitantool] Support the teacup BGA69 board

sw/otbn/crypto/p384_scalar_mult.s, sw/otbn/crypto/p384_sign.s
This is the third of a handful of PRs to make the P-384 implementation compliant with the SCA guidelines as listed in the OpenTitan OTBN Style Guide docs.
This PR just addresses `p384_{sign,scalar_mult}.s`. Following PRs will address the remainder of the P-384 implementation.
Care has been taken to mirror the SCA adjustments as implemented for P-256 wherever the implementations closely align.
=> [crypto] Modify p384_{sign,scalar_mult}.s to comply with OTBN SCA guidelines in docs

sw/device/silicon_creator/manuf/base/BUILD
The personalization firmware emulates a ROM_EXT. To ensure it always boots first. We set its version to the max value.
=> [perso] set perso manifest version to the max

hw/ip/lc_ctrl/doc/theory_of_operation.md, hw/ip/lc_ctrl/dv/README.md, hw/ip_templates/otp_ctrl/doc/interfaces.md.tpl, hw/ip_templates/otp_ctrl/doc/theory_of_operation.md, hw/top_darjeeling/ip_autogen/otp_ctrl/doc/interfaces.md, hw/top_darjeeling/ip_autogen/otp_ctrl/doc/theory_of_operation.md, hw/top_earlgrey/ip_autogen/otp_ctrl/doc/interfaces.md, hw/top_earlgrey/ip_autogen/otp_ctrl/doc/theory_of_operation.md
One commit is fixing broken links.
The other commit is content tweaks for clarity.
=> [doc] otp_ctrl & lc_ctrl doc tweaks

sw/device/silicon_creator/manuf/lib/individualize.c, sw/host/provisioning/orchestrator/src/device_id.py
This updates the DIN to be set to all 1s for FPGA emulated devices to enable test owner firmware images to bind to this invalid device ID.
=> [manuf] set DIN to all 1s for FPGA devices

hw/ip/prim_generic/rtl/prim_flash.sv, hw/ip_templates/flash_ctrl/rtl/flash_ctrl.sv.tpl, hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/rtl/flash_ctrl.sv
This allows to get rid of `prim_pkg` in RTL code.
=> [flash] Move assertion from `flash_ctrl` to `prim_flash`

hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_common_vseq.sv
The path previously referred to a generate case in which the FIFO would have more than one entry, but `u_rspfifo` has as many entries as the value of the `Outstanding` parameter of `tlul_adapter_sram`, which is not set for the `u_to_rd_fifo` instance in `flash_ctrl`, hence the default is 1 entry.  This caused the `flash_ctrl_sec_cm` test to fail.
This commit fixes the path to be correct for the singleton FIFO.  The `flash_ctrl_sec_cm` test passes again.
=> [flash_ctrl/dv] Fix path used in FI tests

hw/top_earlgrey/chip_earlgrey_asic.core, hw/top_earlgrey/top_earlgrey.core
1. Removed default lowrisc:prim:prim_legacy_pkg from to file to enable partner integration.
2. Renamed prim_generic to prim_tech as it is technology related.
3. Added support for partner otp_macro.
=> [prim] removing default prim_generic to enable partner integration

sw/device/silicon_creator/lib/cert/dice_chain.c
Fix incorrect key ID values that cause CDI_0 to be unnecessarily re-signed by the imm_section.
Also, we simplify the check in rom_ext, since the imm_section verifies if the CDI_0 cache matches.
With this change, the no_refresh e2e test can catch the bug if CDI_0 is signed again by imm_section.
=> [rom_ext] Fix incorrect key ID values that cause CDI_0 to be re-signed

.bazelignore, MODULE.bazel, ci/scripts/check-bazel-banned-rules.sh, ci/scripts/test-airgapped-build.sh, util/prep-bazel-airgapped-build.sh
This PR backports a commit from https://github.com/lowRISC/opentitan/pull/26092 which ensures the Bazel cache outside of the airgap directory is cleaned before running the test.
Requires a change to how we override `misc-linters` since Git downloads aren't cached properly by Bazel at the moment.
=> [bazel] Ensure Bazel cache is clean before airgap test

sw/device/tests/penetrationtests/firmware/fi/BUILD, sw/device/tests/penetrationtests/firmware/fi/otp_fi.c, sw/device/tests/penetrationtests/json/otp_fi_commands.h, sw/host/penetrationtests/testvectors/data/fi_otp.json, sw/host/tests/penetrationtests/fi_otp/src/main.rs
This commit fixes a couple of bugs in the OtpFi tests. Moreover, the test response is adapted such that it is indicated whether there was a mismatch between the partition dump before and after the FI trigger window.
=> [pentest] Fix and refactor OtpFi tests

hw/ip_templates/clkmgr/util/dt.py, hw/ip_templates/gpio/data/gpio.tpldesc.hjson, hw/ip_templates/gpio/defs.bzl.tpl, hw/ip_templates/pwm/data/pwm.tpldesc.hjson, hw/ip_templates/pwm/defs.bzl.tpl, hw/ip_templates/pwrmgr/util/dt.py, hw/ip_templates/rstmgr/util/dt.py, hw/top_darjeeling/ip_autogen/clkmgr/util/dt.py, hw/top_darjeeling/ip_autogen/gpio/data/top_darjeeling_gpio.ipconfig.hjson, hw/top_darjeeling/ip_autogen/gpio/defs.bzl, hw/top_darjeeling/ip_autogen/pwrmgr/util/dt.py, hw/top_darjeeling/ip_autogen/rstmgr/util/dt.py, hw/top_earlgrey/ip_autogen/clkmgr/util/dt.py, hw/top_earlgrey/ip_autogen/gpio/data/top_earlgrey_gpio.ipconfig.hjson, hw/top_earlgrey/ip_autogen/gpio/defs.bzl, hw/top_earlgrey/ip_autogen/pwm/data/top_earlgrey_pwm.ipconfig.hjson, hw/top_earlgrey/ip_autogen/pwm/defs.bzl, hw/top_earlgrey/ip_autogen/pwrmgr/util/dt.py, hw/top_earlgrey/ip_autogen/rstmgr/util/dt.py, hw/top_englishbreakfast/ip_autogen/clkmgr/util/dt.py, hw/top_englishbreakfast/ip_autogen/gpio/data/top_englishbreakfast_gpio.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/gpio/defs.bzl, hw/top_englishbreakfast/ip_autogen/pwrmgr/util/dt.py, hw/top_englishbreakfast/ip_autogen/rstmgr/util/dt.py, util/BUILD, util/dtgen/BUILD, util/dtgen/helper.py, util/dtgen/ipgen_ext.py, util/dttool.py, util/ipgen/lib.py
This PR adds basic support for exposing some ipgen parameters through dtgen automatically. At the high level, what we are trying to achieve is the following:
- we add some information to the `tpldesc` of an IP, e.g.
```javascript
{
template_param_list: [
...
{
name: "num_inp_period_counters"
desc: "number of input period counters"
type: "int"
default: 0
// NEW
dtgen:
{
type: "uint8"
name: "input_period_counter_count"
}
}
]
}
```
and `dtgen` automatically adds the following API to `dt_gpio.h`:
```c
/**
* Get the number of input period counters.
*
* @param dt Instance of gpio.
* @return number of input period counters.
*/
uint8_t dt_gpio_input_period_counter_count(dt_gpio_t dt);
```
**Changes to `topgen`***
The first necessary change is to make topgen take the `dtgen` dictionary in …
=> Expose ipgen parameter to dtgen

hw/top_earlgrey/chip_earlgrey_asic.core
[prim] removing prim_legacy from partner file list
With the above change, partner side compiles successfully :)
=> [prim] removing prim_legacy from partner file list

sw/host/hsmtool/src/util/wrap.rs
The HSM used in provisioning infrastructure uses a custom mechanism identifier (CKM_AES_KW = (CKM_VENDOR_DEFINED + 0x170)) even though the implementation follows the RFC 3394 specification. The CKM_AES_KW implemented by Thales is also equivalent to the KW algorithm specified by NIST SP 800-38F.
This change adds a custom Wrap::VendorThalesAesKw mechanism to hsmtool to be able to wrap/unwrap private keys with AES_KW. This is similar to #26565.
=> [hsmtool] Add vendor specific AES_KW mechanism

third_party/rust/patches/rules_rust.experimental.patch, third_party/rust/patches/rules_rust.transition.patch, third_party/rust/repos.bzl
The opentitan-provisioning loads this repo as a bazel dependency to build opentitanlib. Minor updates to rules rust in this repo broke builds downstream. This should fix them.
=> [bazel] fix/add patches to enable downstream builds

hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/rtl/sram_ctrl.sv, hw/ip/sram_ctrl/rtl/sram_ctrl_pkg.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling_rnd_cnst_pkg.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast_rnd_cnst_pkg.sv
Previously, this LFSR just used a width of 32 which - depending on how the module is used - may not be ideal. This commit thus increases the width of this LFSR to 64 bits, while the output width, i.e., the number of bits used per cycle, remains at 32 bits. To seed the additional 32 state bits, the previously unused upper 32 bits of the nonce obtained from OTP_CTRL are used.
This is related to https://github.com/lowRISC/opentitan/issues/27381.
=> [sram_ctrl] Increase width of LFSR used for initialization to 64 bits 

sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/host/opentitanlib/src/test_utils/rpc.rs, sw/host/provisioning/ft_lib/src/lib.rs
This updates the perso firmware, and benchtop provisioning flow, to send a CRC with the RMA unlock token hash as this is the only asset provisioned during the entire provisioning flow that is not also tested during the flow.
=> [perso] send CRC with the RMA unlock token hash UJSON payload

sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/device/silicon_creator/manuf/base/perso_tlv_data.h, sw/host/provisioning/ft_lib/src/lib.rs, sw/host/provisioning/perso_tlv_lib/src/lib.rs
Prior to this change, the personalization firmware (self) hash was logged to the console as text. This updates the flow to push it into the perso TLV structure (i.e., perso blob) so it can be sent to the provisioning registry.
=> [perso] log perso firmware has in the perso blob

sw/device/silicon_creator/manuf/base/BUILD
This sets the perso firmware version to an integer that represents the following format for a given release candidate:
\<year\>\<month\>\<day\>\<release candidate\>.
The perso firmware version will no longer be match the ROM_EXT version.
=> [perso] start versioning perso firmware

sw/device/tests/crypto/BUILD, sw/device/tests/crypto/kdf_kmac_sideload_functest.c
The `kdf_kmac_sideload_functest` computes two blinded keys using KDF with sideloaded keys from the keymgr, but directly compares the output blinded keyblobs, which will each contain two masked keyshares. KMAC masking is disabled on CW310 due to FPGA limitations, but in other execution environments we would not expect the two keyblobs to be the same as a result of KMAC masking.
To fix this, correct the test logic to export and unmask both derived blinded keys, and directly compare the contents of the unmasked keys instead. This should allow the test to pass in environments that have KMAC masking enabled. I've also created issue #27463 to track the ability to run KMAC tests on CW340, to prevent similar issues appearing in the future.
CC @moidx
=> [sival, kdf] Compare derived keys in kdf_kmac_sideload_functest

hw/ip/kmac/doc/programmers_guide.md
This PR makes the doc less confusing.
Currently it sounds like there might be HW context switching.
=> [kmac/doc] Clarify context switch doesn't exist for both hw and sw

hw/top_earlgrey/data/top_earlgrey.hjson
This line already exists above. Remove the duplicated entry.
=> [top_earlgrey] Remove duplicated entropy_src intersignal

hw/top_earlgrey/lint/top_earlgrey_lint_cfgs.hjson
Pre-ipgen, these flags where used to select different files but it's not used anymore in the codebase.
=> [top_earlgrey] Remove outdated overrides in lint config

sw/device/silicon_creator/lib/rescue/rescue.c, sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD
The reboot mode is always allowed in `rescue_validate_mode`. However, the rescue protocol will still crash with `kErrorRescueBadMode` when the reboot command is not allowed.
This commit fixes this issue by moving those special commands before the `owner_rescue_command_allowed` checks.
=> [rom_ext,rescue] Fix allowlist for reboot mode

sw/device/silicon_creator/lib/rescue/rescue.c, sw/device/silicon_creator/lib/rescue/rescue_xmodem.c, sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
When rescue mode is initiated by OwnerSW via the boot service, the UART RX is not active. This prevents it from receiving commands after displaying "RESQ".
=> [rom_ext,rescue] Fix rescue rx when triggered by boot svc

sw/device/silicon_creator/lib/BUILD, sw/device/silicon_creator/lib/boot_svc/BUILD, sw/device/silicon_creator/lib/dbg_print.c, sw/device/silicon_creator/lib/mock_manifest.cc, sw/device/silicon_creator/lib/mock_manifest.h, sw/device/silicon_creator/lib/ownership/BUILD, sw/device/silicon_creator/lib/ownership/isfb.c, sw/device/silicon_creator/lib/ownership/mock_owner_verify.cc, sw/device/silicon_creator/lib/ownership/mock_owner_verify.h, sw/device/silicon_creator/lib/ownership/owner_verify.h, sw/device/silicon_creator/lib/rescue/BUILD, sw/device/silicon_creator/lib/rescue/rescue_null.c, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/device/silicon_creator/rom_ext/rom_ext_boot_services.c, sw/device/silicon_creator/rom_ext/rom_ext_boot_services.h, sw/device/silicon_creator/rom_ext/rom_ext_boot_services_unittest.cc, sw/device/silicon_creator/rom_ext/rom_ext_verify.c, sw/device/silicon_creator/rom_ext/rom_ext_verify.h
These changes refactor the `handle_boot_svc` method and several related methods out of `rom_ext.c` into separate libraries - `rom_ext_boot_services.c` and `rom_ext_verify.c`. This enables standalone unit tests to be written for boot services (and shortly, fuzzing for boot services).
Unit tests were added for each action handled in `handle_boot_svc`. Mocks and conditional compilation were added where necessary to support on-host tests for `rom_ext`.
=> [rom_ext] Boot services refactor and unit tests

hw/ip/tlul/rtl/tlul_adapter_sram.sv
We only used the "op" field to store a single bit, for whether an access was a read or write. Narrow things to match.
=> [rtl] Make the reqfifo narrower in tlul_adapter_sram

sw/device/silicon_creator/lib/ownership/owner_block.c
This commit changes to normal comparison to eliminate the corner case.
---
We used XOR for the comparison hardening, but didn't realize that might flip false to true. Luckily, the allowed values checked before calling the function makes the flip impossible.
Specifically, flipping from false to true requires xor 0xed to the last byte, while the allowed enums can only produce [0x00, 0x03, 0x18, 0x1b].
=> [ownership] Fix key algo comparison hardening

util/sh/scripts/gen-python-requirements.sh
It appears that UV can pick up locally installed Python versions when running `uv pip compile` and not honour current environment Python version and pyproject.toml. Pin to a specific version to avoid surprises when people need to repin on their environment.
=> [python] pin Python version in gen-python-requirements.sh

sw/device/silicon_creator/lib/drivers/BUILD, sw/device/silicon_creator/lib/drivers/hmac_functest.c, sw/device/silicon_creator/lib/drivers/kmac_functest.c
feat:  Add a test that can hash256 unaligned inputs
As defined by the HMAC/KMAC specs, the hashing algorithm should be able to reproduce a digest that is identical to an aligned/unaligned input. 
Test:
Device under test: cw340 w/ HyperDebugger
CMD: bazel test --test_output=streamed --cache_test_results=no //sw/device/silicon_creator/lib/drivers:kmac_functest_fpga_cw340_rom_with_fake_keys
tested git hash: 81e4bb698ffd45469fe10a70086a6f49074fc97b
KMAC
[test.log](https://github.com/user-attachments/files/20892449/test.log)
HMAC
[test.log](https://github.com/user-attachments/files/20892480/test.log)
=> [lib][drivers] Inital draft for change

hw/ip/entropy_src/data/entropy_src.hjson, hw/ip/entropy_src/doc/registers.md, hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv, hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
This register implements an IP revision register which is unused in the current design. Remove that as part of the IP upgrade.
=> [hw,entropy_src,rtl] Remove unused REV register

sw/device/silicon_creator/manuf/base/ft_personalize.c
num_objs will be updated during personalize_endorse_certificates() which leads to personalize_extension_post_cert_endorse() gets incorrect value.
=> [manuf] Restore the num_objs for perso_blob_from_host

hw/dv/sv/mem_bkdr_util/mem_bkdr_util.sv, hw/ip/sram_ctrl/dv/env/sram_ctrl_bkdr_util.sv
DFT might have a different path generation for the hierarchy. Provide a way to overwrite the tile suffix string.
=> [membkdr_util] Support for custom tile suffix

sw/device/silicon_creator/manuf/base/BUILD
This bumps the perso version to prepare for the next signing operation.
=> [perso] rev perso version

hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, hw/top_darjeeling/sw/autogen/top_darjeeling.h, hw/top_darjeeling/templates/toplevel.sv.tpl, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_earlgrey/sw/autogen/top_earlgrey.h, hw/top_earlgrey/templates/toplevel.sv.tpl, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/data/top_englishbreakfast.hjson, hw/top_englishbreakfast/sw/autogen/top_englishbreakfast.h, util/topgen.py, util/topgen/c_test.py, util/topgen/lib.py, util/topgen/merge.py, util/topgen/templates/BUILD.tpl, util/topgen/templates/plic_all_irqs_test.c.tpl, util/topgen/templates/toplevel.c.tpl, util/topgen/templates/toplevel.h.tpl, util/topgen/templates/toplevel.rs.tpl, util/topgen/templates/toplevel_interrupt_assignments.tpl, util/topgen/templates/toplevel_interrupts.tpl, util/topgen/validate.py
Currently, each IP block's HJSON defines some number of interrupts in its interrupt_list, and these are all implicitly connected to the top's rv_plic instance, if present.
With an eye towards more flexible interrupt topologies, with potentially multiple interrupt controllers, this PR makes interrupt controller connections explicit by having each toplevel module define a `plic` key defining where its interrupts should go, e.g.
```
...
{ name: "csrng",
type: "csrng",
clock_srcs: {clk_i: "main"},
clock_group: "secure",
reset_connections: {rst_ni: "lc"},
+     plic: "rv_plic",
base_addr: {
hart: "0x21150000",
},
},
...
```
For brevity, there's support for a toplevel default interrupt controller:
```
...
num_cores: "1",
// Interrupt handler information for the design
interrupts: {
// Any …
```
=> [topgen,rv_plic] Explicitly specify interrupt controller connections

hw/ip/otp_macro/data/otp_macro.hjson, hw/ip/otp_macro/otp_macro.core, hw/ip/otp_macro/rtl/otp_macro.sv, hw/ip/otp_macro/rtl/otp_macro_prim_reg_top.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
This PR adds RACL support to the underlying OTP macro instance. In the upstream, RACL is not used on this IP and tied-off.
=> [hw,otp_macro,rtl] Add RACL support

util/reggen/access.py, util/reggen/field.py, util/reggen/gen_systemrdl.py
Maps all the reggen properties that can be directly mapped to SystemRDL properties in register fields.
Custom properties and Register properties will in an follow-up PR.
=> [reggen] Add non-custom properties fields of the Systemrdl exporter

util/dvsim/utils.py
Here old is a Path object. The old comparison old != 'summary' always evaluates to True because a Path object is never equal to the string 'summary'. Therefore the directory named summary would still be deleted. The updated check uses old.name != 'summary', which compares the directory’s name to the string, so a directory called summary is correctly skipped.
=> [utils] Fixes utils.py for missed .name

sw/device/lib/dif/BUILD, sw/device/lib/dif/dif_soc_dbg_ctrl.c, sw/device/lib/dif/dif_soc_dbg_ctrl.h
This PR creates an initial DIF implementation, providing the debug category values to the software. The values must be kept in sync with the hardware implementation. Unfortunately, there is no way to sync those values from HW to SW at the moment.
=> [hw,soc_dbg_ctrl,dif] Add soc_dbg_ctrl DIF with debug category enum

hw/ip_templates/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_darjeeling/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_earlgrey/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl, hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/tb/coverage_waivers.tcl
The FPV for alerts is already been done separately. It would makes sense to migrate the coverage closure work done for alerts while doing FPV on rv_plic to the alert FPV world.
=> [rv_plic, fpv] Removed alert related FPV 

sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl
This disables signing of emulation perso images, which are signed on the fly by Bazel using fake keys.
=> [bazel] disable signing emulation perso images

sw/device/tests/BUILD
The silicon environment on this test was missing the host test harness.
=> [sival] Add missing harness to spi_host_config_test

hw/ip/otbn/dv/otbnsim/sim/stats.py, hw/ip/otbn/dv/otbnsim/standalone.py, hw/ip/otbn/util/otbn_as.py, util/otbn_build.py
This pull request integrates the OTBN simulator with Bazel's code coverage tool.
To generate a coverage report, execute the following commands:
```shell
./bazelisk.sh coverage --combined_report=lcov //sw/otbn/crypto/tests/...
genhtml -o /tmp/$USER/coverage bazel-out/_coverage/_coverage_report.dat
```
=> [otbn,cov] Add bazel coverage support to OTBN simulator tests

hw/dv/sv/mem_bkdr_util/mem_bkdr_util.core, hw/dv/sv/mem_bkdr_util/mem_bkdr_util.sv, hw/dv/sv/mem_bkdr_util/mem_bkdr_util_pkg.sv, hw/dv/sv/mem_bkdr_util/mem_bkdr_util_row_adapter.sv, hw/ip/rom_ctrl/dv/env/rom_ctrl_bkdr_util.sv, hw/ip/sram_ctrl/dv/env/sram_ctrl_bkdr_util.sv, hw/ip_templates/flash_ctrl/dv/env/flash_ctrl_bkdr_util.sv, hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_bkdr_util.sv, hw/top_englishbreakfast/ip_autogen/flash_ctrl/dv/env/flash_ctrl_bkdr_util.sv
This PR adds a custom row adapter that is being used by the memory backdoor util to access and manipulate rows of data. Integrators might are using SRAM primitives with a different internal organization than `Width x Depth`. They can provide a custom row adapter to the memory backdoor utility to for the needs of their memory prims.
=> [membkdr] Provide a tile adapter to access internal rows

hw/dv/sv/alert_esc_agent/alert_monitor.sv
These are all minor linting tweaks to avoid silly warnings.
=> [dv] Tweaks to alert_monitor.sv to use clocking blocks

hw/ip_templates/ac_range_check/data/ac_range_check.tpldesc.hjson, hw/ip_templates/rv_core_ibex/data/rv_core_ibex.tpldesc.hjson, hw/ip_templates/rv_plic/data/rv_plic.tpldesc.hjson, hw/top_darjeeling/ip_autogen/ac_range_check/data/top_darjeeling_ac_range_check.ipconfig.hjson, hw/top_darjeeling/ip_autogen/rv_core_ibex/data/top_darjeeling_rv_core_ibex.ipconfig.hjson, hw/top_darjeeling/ip_autogen/rv_plic/data/top_darjeeling_rv_plic.ipconfig.hjson, hw/top_earlgrey/ip_autogen/rv_core_ibex/data/top_earlgrey_rv_core_ibex.ipconfig.hjson, hw/top_earlgrey/ip_autogen/rv_plic/data/top_earlgrey_rv_plic.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/rv_core_ibex/data/top_englishbreakfast_rv_core_ibex.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/rv_plic/data/top_englishbreakfast_rv_plic.ipconfig.hjson
This PR exposes simpler parameters via the new ipgen dtgen interface. This allows multi-top compatible SW to query this parameter and generate a more generic driver or DIF.
=> [dtgen] Expose more ipgen params via dtgen

hw/ip/prim/dv/prim_alert/prim_alert_sim_cfg.hjson, hw/ip/prim/dv/prim_alert/tb/prim_alert_tb.sv
This PR is a follow-up to https://github.com/lowRISC/opentitan/pull/27536 to add the variable skew cycle configuration to the prim alert testbench. The change adds the option to switch between 1 cycle skew (default) and 3, which is the config in Darjeeling at the moment. It is only enabled for the async fatal case.
=> [hw,prim_alert,dv] Add 3 cycles clock skew to the testbench config

hw/ip_templates/rv_core_ibex/data/rv_core_ibex.hjson.tpl, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_earlgrey/templates/toplevel.sv.tpl, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/data/top_englishbreakfast.hjson, hw/top_englishbreakfast/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv
AFAICT lc_ctrl's only connection to Ibex is lc_cpu_en, but there's assertions and a CM that need to be gated out, so it's not as simple as an SV parameter. To use this, set ipgen_param.LcCtrl to "false" to disable lc_ctrl's fetch enable signal (and also remove the `lc_cpu_en` inter-module signal).
=> [rv_core_ibex] Use a default lc_ctrl_pkg::On for lc_cpu_en

sw/device/tests/flash_ctrl_clock_freqs_test.c
Happened to notice this as I was looking through the test. Harmless, but also not doing what was intended.
Only a single word of the test data is actually being written to in each iteration, because the incorrect loop variable `i` is being used instead of the inner loop variable `j`. Fix this so that the full 16 words of test data is being randomized.
=> [flash_ctrl, tests] Fix incorrect loop variable for test data

hw/dv/dpi/uartdpi/uartdpi.c, hw/dv/dpi/usbdpi/usb_monitor.c
With the toolchain I was just trying to use for a compilation (GCC 14.2.1; glibc 2.40), these two files failed to build because we didn't have the relevant feature test macro defined. Define it...
=> [dpi] Define _DEFAULT_SOURCE in two files to get BSD functions

.github/workflows/fpga.yml
We're currently not keeping the HyperDebugs up to date on the CW340s.
=> [ci] Update HyperDebug firmware for CW340s

hw/dv/sv/tl_agent/seq_lib/tl_device_seq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_rng_seq.sv, hw/ip/hmac/dv/env/seq_lib/hmac_error_vseq.sv, hw/ip/hmac/dv/env/seq_lib/hmac_stress_reset_vseq.sv, hw/ip/hmac/dv/env/seq_lib/hmac_wipe_secret_vseq.sv
This is discouraged by some style guides (because it isn't guaranteed to run before body!). Avoid it, and implement this by overriding body() instead.
=> [dv] Avoid implementing the pre_body task

hw/ip_templates/ac_range_check/BUILD.tpl, hw/ip_templates/ac_range_check/data/BUILD.tpl, hw/ip_templates/alert_handler/BUILD.tpl, hw/ip_templates/alert_handler/data/BUILD.tpl, hw/ip_templates/gpio/BUILD.tpl, hw/ip_templates/gpio/data/BUILD.tpl, hw/ip_templates/pwm/BUILD.tpl, hw/ip_templates/pwm/data/BUILD.tpl, hw/ip_templates/racl_ctrl/BUILD.tpl, hw/ip_templates/racl_ctrl/data/BUILD.tpl, hw/ip_templates/rv_core_ibex/BUILD.tpl, hw/ip_templates/rv_core_ibex/data/BUILD.tpl, hw/ip_templates/rv_plic/BUILD.tpl, hw/ip_templates/rv_plic/data/BUILD.tpl, hw/top_darjeeling/ip_autogen/ac_range_check/data/BUILD, hw/top_darjeeling/ip_autogen/racl_ctrl/data/BUILD
Some BUILD files of ipgen IPs didn't fully respect the module instance name, which can be different depending on the ipgen configuration. Properly factor the module instance name into the BUILD files.
=> [ipgen,bazel] Correct BUILD files for ipgen IPs

rules/bitstreams.bzl
Surprisingly, it seems that Bazel does not automatically watch the label attributes of the repository rule and it will not refetch it even when they change. Although this runs contrary to what we expect and this requires more investigation, this commit provides at least a workaround.
More precisely, I managed to reproduce the issue as follows:
- checkout master, and make sure that the bitstream is up-to-date by running
```bash
./bazelisk build @bitstreams//...
```
- edit `rules/scripts/bitstreams_workspace.py`, for example by making a change that prevents the file from even compiling
- run
```bash
./bazelisk build @bitstreams//...
./bazelisk fetch --configure
```
and observe that the bitstream rule is not evaluated, even though both commands should invalidate it.
- run
```bash
./bazelisk …
```
=> [rules,bitstreams] Explicitely watch files

sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_unlock.c, sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_unlock.h, sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_unlock_unittest.cc, sw/device/silicon_creator/lib/ownership/owner_block.c, sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc, sw/device/silicon_creator/lib/ownership/ownership_unlock.c, sw/device/silicon_creator/lib/ownership/ownership_unlock_unittest.cc, sw/device/silicon_creator/rom_ext/doc/ownership.md, sw/device/silicon_creator/rom_ext/rom_ext_boot_services_unittest.cc, sw/host/opentitanlib/src/chip/boot_svc.rs, sw/host/opentitanlib/src/chip/helper.rs
This PR fixes an issue in endorsed ownership transfers, where attackers could downgrade an endorsed SPX+ECDSA transfer to ECDSA-only after ECDSA is broken.
The fix involves endorsing the key algorithm with the public key, ensuring transfers only complete with the designated algorithm.
=> [ownership] Check key alg during endorsed transfer

.github/workflows/fpga.yml, .github/workflows/nightly.yml, ci/scripts/run-fpga-tests.sh, sw/device/tests/pmod/BUILD
The FPGA jobs in nightly are reworked to use our reusable workflows.
* Every FPGA Bazel test is now executed.
* Bitstreams are built if needed.
* The Bazel cache is now available.
Normal CI only runs one version of each FPGA test. We run all execution environments of each test in nightlies to prevent regressions. Building bitstreams as-needed here lets (eventually) disable the non-HyperDebug bitstream build in regular CI, reducing load.
Example nightly run: https://github.com/lowRISC/opentitan/actions/runs/16312373557
=> [ci] Rework nightly FPGA jobs

sw/device/silicon_creator/lib/rescue/rescue_usb.c
Format the USB-DFU rescue's `iSerial` serial number as a 64-bit hex integer.  This is the same representation as the device identification number in `//sw/host/opentitanlib/src/chip/device_id.rs`.
=> [rescue] Format the serial number correctly

hw/formal/tools/jaspergold/fpv.tcl, hw/formal/tools/jaspergold/jaspergold.hjson, hw/formal/tools/jaspergold/synthesis_optimized.tcl, hw/ip_templates/rv_plic/fpv/tb/coverage.tcl, hw/top_darjeeling/ip_autogen/rv_plic/fpv/tb/coverage.tcl, hw/top_earlgrey/ip_autogen/rv_plic/fpv/tb/coverage.tcl, hw/top_englishbreakfast/ip_autogen/rv_plic/fpv/tb/coverage.tcl
The cover items that are optimized in synthesis are
undetectable/deadcode in the stimuli coverage and
out of COI in the checker. They will remain
uncovered even if we try to cover them by writing
related assertions.
=> [fpv] Added synthesis_optimized script

sw/device/lib/testing/test_framework/BUILD, sw/device/lib/testing/test_framework/ottf_alerts.c, sw/device/lib/testing/test_framework/ottf_alerts.h, sw/device/lib/testing/test_framework/ottf_isrs.c, sw/device/lib/testing/test_framework/ottf_main.c, sw/device/lib/testing/test_framework/ottf_test_config.h, sw/device/silicon_creator/rom/e2e/chip_specific_startup/chip_specific_startup.c, sw/device/silicon_creator/rom/e2e/shutdown_alert/rom_e2e_alert_config_test.c, sw/device/silicon_creator/rom/e2e/shutdown_alert/rom_e2e_shutdown_alert_config_test.c, sw/device/tests/chip_power_sleep_load_test.c
Allows tests to configure that OTTF should catch and fail the test if any alerts trigger. I've made it opt-in for now.
Tests may set `.catch_alerts` in `OTTF_DEFINE_TEST_CONFIG` to cause OTTF to configure all alerts as enabled in class D. OTTF will catch class D interrupst and fail the test.
---
You can test this by forcing an alert, for example in `uart_smoketest`:
```diff
--- a/sw/device/tests/uart_smoketest.c
+++ b/sw/device/tests/uart_smoketest.c
@@ -14,12 +14,17 @@
static const uint8_t kSendData[] = "Smoke test!";
OTTF_DEFINE_TEST_CONFIG(.enable_concurrency = false,
.console.test_may_clobber = true, );
bool test_main(void) {
dif_uart_t uart;
CHECK_DIF_OK(dif_uart_init(
mmio_region_from_addr(TOP_EARLGREY_UART0_BASE_ADDR), &uart));
+
+  LOG_INFO("Forcing alert...");
+ …
```
=> [ottf] Add OTTF option to configure and catch alerts

sw/device/tests/penetrationtests/BUILD, sw/device/tests/penetrationtests/pentest.bzl
This commit puts the tests for the pentest framework into CI by setting the timeout to moderate instead to long.
=> [pentest] Add tests to CI

sw/device/silicon_creator/lib/ownership/owner_block_unittest.cc
This change adds test cases to cover error branches for invalid arguments, including unaligned size and out-of-bounds arguments.
=> [cov] Add more owner_block unit tests to improve the code coverage

hw/ip_templates/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv.tpl, hw/ip_templates/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv.tpl, hw/ip_templates/otp_ctrl/dv/env/seq_lib/otp_ctrl_common_vseq.sv.tpl, hw/top_darjeeling/ip_autogen/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv, hw/top_darjeeling/ip_autogen/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv, hw/top_darjeeling/ip_autogen/otp_ctrl/dv/env/seq_lib/otp_ctrl_common_vseq.sv, hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv, hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv, hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/seq_lib/otp_ctrl_common_vseq.sv
Allow scoreboard to wait some cycles for an expected timeout to become an outgoing alert to account for flops on the path.
The otp_macro fsm errors are flagged as bus integrity errors, which sounds wrong and perhaps should be fixed to be flagged as fatal_prim_otp_alert. For now I changed the order of checks in task check_sec_cm_fi_resp, in otp_ctrl_common_vseq.sv.tpl.
Templetize function sec_cm_fi_ctrl_svas since the buffered partitions depend on per-top config. The function was also incorrect for earlgrey.
=> [dv,otp_ctrl] Fix some unit test failures

sw/device/silicon_creator/lib/rescue/dfu.c, sw/device/silicon_creator/lib/rescue/dfu.h
Rework the `validate_mode` function to set flags in the DFU context that represent whether a DFU `DnLoad` or `UpLoad` operation is allowed. Report an error in the download/upload handler when an unsupported operation is attempted.
=> [rescue] Report errors for disallowed configurations

sw/device/silicon_creator/lib/drivers/otbn.c, sw/device/silicon_creator/lib/drivers/otbn.h, sw/device/silicon_creator/rom_ext/imm_section/BUILD, sw/device/silicon_creator/rom_ext/imm_section/imm_section.c
There is an error in the OTBN boot services program loaded by the ROM that can affect the random share values.  This bug is caused by a simple transposition of operands in the `p256_base` source code.
Since the OTBN program is stored in ROM and loaded into OTBN by the ROM, we patch it in the immutable section before we use that portion of the program.
DO NOT cherrypick this change to the `master` branch.
=> [otbn] Patch an error in the OTBN boot services program

sw/device/tests/rv_core_ibex_address_translation_test.S, sw/device/tests/rv_core_ibex_address_translation_test.c
Add one more character to a `.string` in a `.text` section to ensure it has an even number of characters (counting the null) and thus keep the code aligned to 2 bytes (RVC).
This works around a [linker bug](https://github.com/llvm/llvm-project/issues/147771). If the code is misaligned, debug builds of LLD will trip on an assertion.
=> [sw] Ensure string in .text section doesn't misalign code

doc/contributing/hw/comportability/README.md
It seems we forgot to update the occurrence in the text when updating the guidance and the actual example header also displayed further down in the same doc.
=> [doc] Align copyright message in doc with actual header

sw/device/tests/crypto/otcrypto_interface.h
crypto_interface.c is needed to determine the size of cryptolib.
Some parts of the function handle struct were outdated.
This PR updates the function handles such that the file can compile.
=> [crypto,sw] Update struct for otcrypto_interface to compile

sw/device/lib/ujson/ujson.c
The function `ujson_putbuf` has the type `sink_func_ptr` except that it returns a `status_t` instead of a `size_t`. Although those are the same at an ABI level, at the C level they are different types. More recent versions of Clang warn about casting betwen such incompatible types. This commit fixes such a casting warning by introducing a wrapper function `ujson_putbuf_sink` with the appropriate `sink_func_ptr` type.
=> [sw] Fix cast of `ujson_putbuf` to `sink_func_ptr`

sw/device/silicon_creator/rom_ext/e2e/handoff/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c
In the ES chip, we cleared Rule Locking Bypass (RLB) to make locked entries permanent because we needed to lock out access to a couple of peripheral regions.
In the A1/A2 chips, we want to give the owner full control over the ePMP.  It is the owner's responsibility to configure the MSECCFG register, which includes the RLB, MMWP and MML configuration bits.
=> [rom_ext] Do not clear `RLB` in the ROM_EXT

sw/device/tests/usbdev_deep_disconnect_test.c, sw/device/tests/usbdev_deep_reset_test.c
Unblock failing CI ~~as the tests likely cause some alerts that are not disabled / handled properly~~. Though these don't lead to direct failures as a result of the alert capturing mechanism, this leads to failures in the tests themselves and as such cause CI failures on any PRs.
A more appropriate long-term fix would be to determine what is happening in the interaction between the test and the alert-catching mechanism, but for now we make the simplest fix to unblock `earlgrey_1.0.0` CI.
*Edit*: From a glance, I don't think the alert catching mechanism is responsible for the failures, but instead these usbdev tests were already flaky and that the additional OTTF logic pushed the flakiness towards frequent failures. I suspect the core of the issue lies in some assumptions in the usbdev …
=> [ottf,usbdev] Disable OTTF alert catching on deep USB tests

hw/ip/dma/data/dma.hjson, hw/ip/dma/data/dma_sec_cm_testplan.hjson, hw/ip/dma/doc/interfaces.md, hw/ip/dma/doc/registers.md, hw/ip/dma/rtl/dma.sv, hw/ip/dma/rtl/dma_pkg.sv, sw/device/lib/dif/dif_dma.c
Modify the FSM state to be sparsely-encoded as per the lingering comment.
Assorted minor linguistic corrections and clarifications.
@Razer6 I presume the intention was always to change the FSM state variable as per the comment but it just had not happened; I welcome any feedback, please.
=> [dma] Sparsely-encoded FSM state

util/testplantool/README.md, util/testplantool/cli.py, util/testplantool/testplanlib/lib.py
Based on SiVal stage
```sh
bazel run util/testplantool -- export-testsuite \
$(pwd)/hw/top_earlgrey/data/chip_testplan.hjson $(pwd)/sw/device/tests/sival/BUILD
```
Based on `lc_state`
```sh
mkdir -p sw/device/tests/lc_state
bazel run util/testplantool -- export-testsuite -g "lc_state" \
$(pwd)/hw/top_earlgrey/data/chip_testplan.hjson $(pwd)/sw/device/tests/lc_state/BUILD
```
=> [Testplantool] Add option to group bazel test suite by lc_state

sw/device/lib/base/BUILD, sw/device/lib/base/freestanding/BUILD, sw/device/lib/base/freestanding/string.h, third_party/lowrisc/BUILD.lowrisc_rv32imcb_toolchain.bazel, toolchain/BUILD
Remove the use of headers provided by Newlib and GCC. Instead, use a freestanding environment provided by a combination of Clang + OpenTitan.
Also, don't link again nosys, as we aren't linking agaist Newlib, nor do we want to.
=> Use freestanding environment

sw/device/silicon_creator/lib/boot_svc/boot_svc_ownership_activate.h, sw/device/silicon_creator/lib/ownership/ownership_activate.c, sw/device/silicon_creator/lib/ownership/ownership_activate_unittest.cc
Correctly handle the `rimary_bl0_slot` field in the ownership activate command: use the value if it is one of the legal values and ignore otherwise.
=> [ownership] Handle `primary_bl0_slot` in ownership activate

.github/workflows/cherrypick.yml
This modifies the cherry-pick workflow to use a lowRISC-managed GitHub token minter to generate an access token with ability to create pull_requests as the "lowrisc-ci" app.
This allows GitHub action to trigger and bypass the restriction that actions performed by GitHub actions cannot itself trigger another GitHub actions (as a recursion prevention measure), and therefore allows CI to run on cherry-picked pull requests.
A test PR created by this action can be seen here: https://github.com/lowRISC/opentitan/pull/27724, with checks triggered at https://github.com/lowRISC/opentitan/pull/27724/checks.
=> [ci] use GitHub app token to create pull request

sw/device/lib/testing/test_framework/ottf_utils.h
The function `ottf_backdoor_flush_read_buffers` is only used by the macro `OTTF_BACKDOOR_READ`, but that macro isn't always used. That causes warnings about the function being unused in some translation units. Marking the function as `inline` fixes that issue.
=> [sw][ottf] Fix warning about unused `ottf_backdoor_flush_read_buffers`

sw/device/silicon_creator/rom_ext/rom_ext_boot_services_unittest.cc
The C++ standard only guarantees the initialization of the first member of a union, which in this case only covers the header of the boot service message. This behavior, when compiled with Clang, leads to test failures.
This change explicitly sets DIN to ensure the value matches the lifecycle device ID.
=> [rom_ext] set DIN explicitly in the rom_ext_boot_services_unittest

sw/device/tests/spi_device_flash_smoketest.c
Remove the function as it's unused and causes an unused function warning.
=> [sival, spi_device] Remove unused `configure_jedec_id` function

hw/ip/rom_ctrl/data/rom_ctrl.hjson, hw/ip/rom_ctrl/rtl/rom_ctrl.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv
This injects a clock edge between data coming out of the ROM and data going into KMAC to be hashed. Inserting the delay is pretty trivial: we just use a prim_fifo_sync.
There *is* an area vs. efficiency question. Because there is no pass-through, a prim_fifo_sync with depth 1 will have half throughput, because it has to alternate between taking an item and passing it on. Although, there's the bandwidth to do both on the same cycle, breaking the combinatorial path means that we can't pass the KMAC block's "ready" signal all the way back to the ROM.
This works perfectly well, but takes twice as long as you might hope.
A lazy workaround is to use Depth = 2. This is a little silly, because it uses twice as much area as necessary. But it's very easy from a coding perspective!
=> [rom_ctrl,rtl] Add a flop between rom_ctrl and kmac

hw/top_earlgrey/BUILD, hw/top_earlgrey/data/otp/sival_skus/BUILD, sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl, sw/device/silicon_creator/manuf/lib/BUILD, sw/device/silicon_creator/rom_ext/sival/BUILD
This is a partial backport of #25195. Indeed #25195 does two things:
- update the key material of ealgrey_1.0.0 from the ES to A1
- change a few FPGA targets from sival to emulation images
This PR only backports the second type of changes.
=> Backport [earlgrey,sival] Convert a few more target to emulation images

hw/ip/dma/doc/programmers_guide.md, hw/ip/dma/dv/README.md, hw/ip/dma/dv/sva/dma_bind.sv, hw/ip/dma/dv/tb/tb.sv
This PR extends the documentation in the programmer's guide as well as making the DV README.md much more complete. Additionally it connects a `tlul_assert` to the remaining bus (SoC System) because this appears to have been overlooked following the introduction of the SoC SYS <-> TL-UL adapter interface.
=> [doc,dma] Extensions to DMA documentation

sw/device/lib/testing/test_framework/ottf_console.c, sw/device/lib/testing/test_framework/ottf_isrs.c, sw/device/lib/testing/test_framework/ottf_isrs.h, sw/device/lib/testing/test_framework/ottf_main.c
Partial backport of https://github.com/lowRISC/opentitan/pull/26279 without multitop changes.
I'd like to use this improved IRQ handling mechanism which doesn't interfere with flow control for alert handling. I have tweaked the commits slightly to pass a `peripheral` to the ISR instead of a multitop `devid`.
=> [ottf] Backport improved IRQ handling

hw/top_earlgrey/dv/env/seq_lib/chip_sw_all_escalation_resets_vseq.sv
PR [#27001](https://github.com/lowRISC/opentitan/pull/27001) moved prim_otp out of otp_ctrl
This PR resolves the failure with tests like
** chip_sw_all_escalation_resets
** chip_sw_alert_handler_lpg_sleep_mode_alerts
and many more that fails on finding the path to
*otp_ctrl.u_otp.*u_state_regs
=> [chip, dv] Removed the entry for prim_otp

hw/ip/otbn/util/check_const_time.py, rules/otbn.bzl
If we want to add FI checks to consttime routines, the consttime tests will fail. This PR allows us to ignore certain subroutines during consttime tests.
=> [util,sw] Add argument for consttime test to ignore subroutines

sw/device/examples/teacup_demos/teacup_leds_and_screen_demo.c, sw/device/examples/teacup_demos/teacup_leds_demo.c, sw/device/lib/testing/i2c_testutils.c, sw/device/lib/testing/i2c_testutils.h, sw/device/tests/i2c_target_smbus_arp_test.c, sw/device/tests/i2c_target_test.c, sw/device/tests/pmod/i2c_host_accelerometer_test.c, sw/device/tests/pmod/i2c_host_ambient_light_detector_test.c, sw/device/tests/pmod/i2c_host_clock_stretching_test.c, sw/device/tests/pmod/i2c_host_compass_test.c, sw/device/tests/pmod/i2c_host_eeprom_test.c, sw/device/tests/pmod/i2c_host_fram_test.c, sw/device/tests/pmod/i2c_host_gas_sensor_test.c, sw/device/tests/pmod/i2c_host_hdc1080_humidity_temp_test.c, sw/device/tests/pmod/i2c_host_irq_test.c, sw/device/tests/pmod/i2c_host_power_monitor_test.c
See the commit messages for more details.
In silicon environments, set much tighter thresholds on the expected speeds in the `i2c_host_fram_test`. To enable this to work despite the test utilities to compute I2C timing configurations, lower SDA rise and fall times (based on physical characteristics) must be provided, and so the existing test utilities are modified to allow for this.
=> [i2c, sival] Tighten `i2c_host_fram_test` test thresholds

.github/workflows/ci.yml
With this change and merge queue enabled, PRs will only be merged to target branch once the bitstream is built and cached. This prevent RTL changes from causing all subsequent CI jobs to rebuild bitstream after merging and before bitstreams are built and cached.
This also has the advantage of reducing the likelihood of merge skews, if we move jobs from push to merge_group event. These are future possibilities, for now the merge queue is only gated on bitstream being built.
Implementation-wise, GitHub uses a single check name to gate both PR and merge queue, so I've created two dynamically named jobs to allow the PR to be gated only on `quick_lint` while the merge queue will be gate on bitstream being built and cached.
=> [ci] support merge queues

sw/host/tests/usbdev/usbdev_stream/usbdev_iso.cc
In the code
```c
size_t num_bytes = DataAvailable(&data);
assert(num_bytes >= len);
```
the variable `num_bytes` is only used when assertions are enabled. That causes an unused variable warning in release builds. This patch fixes that warning.
=> [host,usbdev] Fix variable `num_bytes` unused in release builds

.github/workflows/ci.yml, .github/workflows/private-ci.yml
The merge groups are pushed to `gh-readonly-queue/<branch>/<hash>` which is not matched by `gh-readonly-queue/*`, two stars are needed here as it's a glob.
=> [ci] fix duplicated work on merge queues

hw/ip/dma/data/dma_testplan.hjson, hw/ip/dma/dv/env/dma_scoreboard.sv, hw/ip/dma/dv/env/dma_sys_tl_if.sv, hw/ip/dma/rtl/dma.sv
This PR improves the handling of TL-UL errors:
- map the dma_memory|handshake_tl_error testpoints.
- catch any TL-UL transaction that occurs after a bus error has occurred.
- propagate TL-UL errors back to SoC System bus now that they do occur and RTL handles them.
=> [dma] Improvements to handling of TL-UL errors

hw/ip_templates/rv_core_ibex/data/rv_core_ibex.hjson.tpl, hw/ip_templates/rv_core_ibex/rtl/rv_core_ibex.sv.tpl, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, hw/top_darjeeling/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_darjeeling/ip_autogen/rv_core_ibex/rtl/rv_core_ibex.sv, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex.sv, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/ip_autogen/rv_core_ibex/data/rv_core_ibex.hjson, hw/top_englishbreakfast/ip_autogen/rv_core_ibex/rtl/rv_core_ibex.sv, hw/top_englishbreakfast/rtl/autogen/top_englishbreakfast.sv
Add an optional pipeline stage in the address request path between the Ibex core and the address translation to break a long path between the instruction fetch FSM and the TLUL request. Given that the number of address translation regions is parametrizable and the Darjeeling uses 32 vs 2 in Earlgrey, this is a considerable long path.
To cut that, this PR adds a pipeline stage in between. If Ibex' instruction cache works properly, there should not be much impact on the real performance. The stage is only enabled for Darjeeling.
=> [hw,rv_core_ibex,rtl] Add optional pipe in instruction request path

sw/otbn/crypto/p256_base.s
Avoid potential horizontal SCA issue in P256 scalar multiplication based on code review. Avoid that source and dest of one case in BN.SEL uses the same value by preseting with randomness.
Runtime overhead +3*320 instructions = very low.
Codesize overhead +3 instruction = very low.
=> [crypto] P256 scalar multiplication code-review for SCA hardening

sw/device/lib/runtime/print.c, sw/device/lib/runtime/print.h, sw/device/lib/testing/test_framework/ottf_console.c, sw/device/lib/testing/test_framework/ottf_console.h, sw/device/lib/testing/test_framework/ottf_test_config.h, sw/device/lib/testing/test_framework/ujson_ottf.c, sw/device/lib/testing/test_framework/ujson_ottf.h, sw/device/lib/ujson/example_roundtrip.c, sw/device/lib/ujson/test_helpers.h, sw/device/lib/ujson/ujson.c, sw/device/lib/ujson/ujson.h, sw/device/silicon_creator/manuf/base/BUILD, sw/device/tests/BUILD, sw/device/tests/ottf_console_with_gpio_tx_indicator_test.c, sw/host/opentitanlib/src/uart/console.rs, sw/host/tests/chip/ottf_console_with_gpio_tx_indicator/BUILD, sw/host/tests/chip/ottf_console_with_gpio_tx_indicator/src/main.rs
Backport  #27063 and one commit of #26983
Follow up to #27623
NOTE: after hours of debugging, I figured out that `kPayloadSize` was hardcoded to the wrong value due to master/earlgrey_1.0.0 differences which was causing some silent corruption. I changed the code to use `ARRAYSIZE` of the struct field.
=> OTTF console backports

hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, hw/top_darjeeling/ip_autogen/ac_range_check/data/top_darjeeling_ac_range_check.ipconfig.hjson, hw/top_darjeeling/ip_autogen/rv_core_ibex/data/top_darjeeling_rv_core_ibex.ipconfig.hjson, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_earlgrey/ip_autogen/gpio/data/top_earlgrey_gpio.ipconfig.hjson, hw/top_earlgrey/ip_autogen/rv_core_ibex/data/top_earlgrey_rv_core_ibex.ipconfig.hjson, hw/top_englishbreakfast/data/autogen/top_englishbreakfast.gen.hjson, hw/top_englishbreakfast/data/top_englishbreakfast.hjson, hw/top_englishbreakfast/ip_autogen/gpio/data/top_englishbreakfast_gpio.ipconfig.hjson, hw/top_englishbreakfast/ip_autogen/rv_core_ibex/data/top_englishbreakfast_rv_core_ibex.ipconfig.hjson, util/topgen.py, util/topgen/validate.py
This allows the user to arbitrarily set ipgen params on ipgen IPs. These parameters are passed through to the ipgen renderings This allows integrators to easily define custom ipgen parameters and get them used without changes in topgen.
=> [topgen] Pass through ipgen params to the ipgen config

sw/device/lib/crypto/impl/ecc/p256.c, sw/device/lib/crypto/impl/ecc/p384.c
This commit adds instruction count checks to ECC functions that run in constant time. This helps protect against fault injection.
=> [cryptolib,sw] Add instruction count checks to ECC functions

util/ipgen/lib.py
When `dtgen` support was added to the ipconfig, only the constructor was updated but not the code loading from a file. Since topgen directly calls the constructor, this was not caught in CI but it throws an error if running ipgen directly, e.g.
```
util/ipgen.py generate -C hw/ip_templates/ac_range_check -o hw/top_darjeeling/ip_autogen/ac_range_check -c hw/top_darjeeling/ip_autogen/ac_range_check/data/top_darjeeling_ac_range_check.ipconfig.hjson -f
```
=> [ipgen] Fix loading of ipconfig from a file

sw/otbn/crypto/p256_base.s, sw/otbn/crypto/p384_keygen.s, sw/otbn/crypto/tests/boot_key_endorse_valid.hjson
This commit fixes a bug where the most significant 64 bits were constantly set to 0 instead to the actual seed.
Thanks Yi-Hsuan Deng for spotting this!
=> [crypto] Fix shift in p256_random_scalar share generation 

.bazelrc, rules/opentitan/defs.bzl, rules/opentitan/fpga.bzl, rules/opentitan/silicon.bzl, rules/opentitan/sim_dv.bzl, rules/opentitan/sim_verilator.bzl
Backport of https://github.com/lowRISC/opentitan/pull/25845/
In combination with the build determinism fixes from #25842, this PR aims to reduce CI runtime and FPGA runner utilisation by enabling the ability for FPGA and Verilator tests to be remotely cached. See the commit messages for more details on the individual changes.
Importantly, these changes will now mean that 
- FPGA/Verilator tests will run in a sandboxed environment, and 
- FPGA/Verilator tests will make use of remotely cached results where they exist, and the test previously passed, and the test itself has not changed / been rebuilt. 
Our CI bitstreams should have access to a remote cache which is written to by merge jobs, meaning that when a PR is merged, its successful FPGA/Verilator runs will be cached and can be re-used …
=> [ci,bazel] Enable remote caching of FPGA & Verilator test results (backport)

hw/top_earlgrey/BUILD, sw/device/silicon_creator/lib/cert/BUILD, sw/device/silicon_creator/lib/cert/dice_chain.c, sw/device/silicon_creator/lib/cert/dice_cwt.c, sw/device/silicon_creator/lib/error.h, sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl, sw/device/silicon_creator/rom/e2e/address_translation/BUILD, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/defs.bzl, sw/device/silicon_creator/rom_ext/e2e/dice_chain/BUILD, sw/device/silicon_creator/rom_ext/e2e/verified_boot/BUILD, sw/device/silicon_creator/rom_ext/imm_section/BUILD, sw/device/silicon_creator/rom_ext/imm_section/e2e/exec_env/BUILD, sw/device/silicon_creator/rom_ext/sival/BUILD, sw/host/provisioning/ft_lib/src/lib.rs
Backport #25281 ([rom_ext,dice] build ROM_EXT with DICE CWT cert format support), + a bits of #26185 and #26295, and finally [one commit](https://github.com/lowRISC/opentitan/pull/26169/commits/dd0aa270c260eaa53fd5295f2f1eea1433218a93) of #26169 to avoid breaking the CI.
Conflict note: due to #26185 being applied after #25281 on earlgrey_1.0.0 but already applied on master in #25069, the changes to `rom_ext.c` were manually applied to `dice_chain.c` instead.
Conflict note: in the earlgrey_1.0.0 branch, the immutable section work was done later, but it's already (partially) merged back to master. Therefore I added a few changes so that hopefully the code compiles and will not cause too many conflicts down the line when backporting.
Conflict note: in the earlgrey_1.0.0 branch, there is both …
=> Backport #25281 ([rom_ext,dice] build ROM_EXT with DICE CWT cert format support)

hw/ip/prim/rtl/prim_util_pkg.sv
The minimum supported version is now 21.09, so this workaround can be safely removed.
=> [prim] remove $clog2 workaroud for Xcelium < 19.10

hw/ip_templates/ac_range_check/dv/ac_range_check_sim_cfg.hjson.tpl, hw/ip_templates/ac_range_check/dv/env/ac_range_check_env.core.tpl, hw/ip_templates/ac_range_check/dv/env/ac_range_check_env_cov.sv, hw/ip_templates/ac_range_check/dv/env/ac_range_check_predictor.sv, hw/ip_templates/ac_range_check/dv/env/ac_range_check_scoreboard.sv, hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_base_vseq.sv, hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_lock_range_vseq.sv, hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_high_threshold_vseq.sv, hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv, hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_vseq_list.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/ac_range_check_sim_cfg.hjson, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env.core, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env_cov.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_predictor.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scoreboard.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_base_vseq.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_lock_range_vseq.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_high_threshold_vseq.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv, hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_vseq_list.sv
This commit includes covergroups for logging registers as well as introducing logging in the smoke sequence.
=> [ac_range_check,dv] Included logging support in testbench

sw/device/lib/crypto/impl/ecc/p256.c, sw/device/lib/crypto/impl/ecc/p384.c
After two PRs were merged at the same time the instruction time check didn't check for the correct value any more. This commit fixes that issue.
=> [sw,crypto] Fix instruction count FI check

hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling_rnd_cnst_pkg.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv, util/design/lib/LcStEnc.py, util/design/lib/OtpMemImg.py, util/design/lib/OtpMemMap.py, util/design/lib/common.py, util/topgen.py, util/topgen/merge.py, util/topgen/secure_prng.py, util/topgen/secure_prng_test.py
Previously, there was a rather single singleton implementation where only a single PRNG lived in the design at once. Re-seeding the PRNG caused all subsequent PRNG invocations to use that seed. That meant, once the otp map reseeded the PRNG, all topgen calls to the PRNG used the otp map seed.
This PR fixes that by introducing a factory that allows creating multiple PRNGs with different namespaces. Now, the otp map and also otp image generation can create their own PRNG instance without interfering with the topgen PRNG.
cc @matutem
=> [topgen] Add PrngFactory for PRNGs with different seeds

sw/device/silicon_creator/rom_ext/sival/BUILD
Backport #25305 ([rom_ext] Correct the sival presigning rule)
Depends on #27714
=> Backport 25305 ([rom_ext] Correct the sival presigning rule)

SUMMARY.md, hw/ip_templates/clkmgr/defs.bzl.tpl, hw/ip_templates/clkmgr/util/BUILD.bazel.tpl, hw/ip_templates/clkmgr/util/dt.py, hw/ip_templates/clkmgr/util/ipconfig.py, hw/top/BUILD, hw/top/README.md, hw/top/doc/top_desc.md, hw/top/top_desc.md, hw/top_darjeeling/ip_autogen/clkmgr/defs.bzl, hw/top_darjeeling/ip_autogen/clkmgr/util/BUILD.bazel, hw/top_darjeeling/ip_autogen/clkmgr/util/dt.py, hw/top_darjeeling/ip_autogen/clkmgr/util/ipconfig.py, hw/top_earlgrey/ip_autogen/clkmgr/defs.bzl, hw/top_earlgrey/ip_autogen/clkmgr/util/BUILD.bazel, hw/top_earlgrey/ip_autogen/clkmgr/util/dt.py, hw/top_earlgrey/ip_autogen/clkmgr/util/ipconfig.py, hw/top_englishbreakfast/ip_autogen/clkmgr/defs.bzl, hw/top_englishbreakfast/ip_autogen/clkmgr/util/BUILD.bazel, hw/top_englishbreakfast/ip_autogen/clkmgr/util/dt.py, hw/top_englishbreakfast/ip_autogen/clkmgr/util/ipconfig.py, rules/autogen.bzl, util/dtgen/dt_ip.h.tpl, util/dtgen/helper.py
Currently the `clkmgr` DT does not expose any information about the measurable clocks which therefore need quite a bit of top-specific code. The PR exposes this information in a top-independent way.
The following information is necessary in order to operate a clock measurement:
- which clock is touches (e.g. IO, main, USB, ...)
- offset of the `ctrl_en` register (e.g. `CLKMGR_IO_MEAS_CTRL_EN_REG_OFFSET`) and
- bitfield of the `EN` field (though it's the same for all, this is a bit cleaner)
- offset of the `ctrl_shadowed` register (e.g. `CLKMGR_IO_MEAS_CTRL_SHADOWED_REG_OFFSET `) and
- bitfield of the `LO` field (different for each clock)
- bitfield of the `HI` field (same)
Concretely, this is exposed as follows in the C API:
```c
/**
* Description of a measurable clock.
*
*/
typedef …
```
=> [dt] Add clkmgr measurable clock information

sw/otbn/crypto/tests/BUILD, sw/otbn/crypto/tests/p256_keygen_valid.hjson
Related to:
* #27685
The added test ensure the shift issue is fixed correctly that two shares are both 320-byte long.
=> [otbn,cov] Add p256 key generation sim test

sw/device/silicon_owner/bare_metal/BUILD, sw/device/silicon_owner/bare_metal/bare_metal_common.ld, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/otcrypto_export_size.c, sw/device/tests/crypto/otcrypto_interface.c, sw/device/tests/crypto/otcrypto_interface.h, util/py/scripts/mapfile_to_json.py
Thanks to @cfrantz for this fix!
This PR contains necessary updates to allow for building the map file of the whole crypto lib and then use the map file to hjson python script to create a visual representation of the map file for easier analysis of the memory usage.
To generate the map file and the HTML use the following commands:
`bazel build  //sw/device/tests/crypto:otcrypto_export_size`
`./util/py/scripts/mapfile_to_json.py -v -a file --regions eflash bazel-bin/sw/device/tests/crypto/otcrypto_export_size_fpga_cw310_rom_ext.map`
The second command will open the html straight away. You can also create an HTML file and open it later by removing the `-v` option and adding `-html <path to file>`
=> [crypto/sw] Enable cryptolib map file analysis

hw/ip/dma/data/dma.hjson, hw/ip/dma/dma_pkg.core, hw/ip/dma/rtl/dma.sv, hw/ip/dma/rtl/dma_pkg.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv
Since RACL is now within OpenTitan, derive the RACL role sizes from there instead of having a second, hard-coded parameter for the size of a RACL role.
=> [hw,dma,rtl] Use top_racl_pkg to derive RACL role size

util/topgen/merge.py
Use `find_module` and then query the name instead of using a local function to determine the name of a module.
=> [topgen] Remove duplicated function, instead use existing lib function

hw/ip_templates/rv_plic/data/rv_plic.hjson.tpl, util/topgen.py, util/topgen/lib.py, util/topgen/merge.py
This PR addresses some small issues issues found when playing with topgen. The context is trying to remove assumptions about names in topgen. For this experiment, I tried renaming the rv_plic to another name, and also give it a nonstandard "type name". This fails because for ipgen IP, topgen currently enforces that name==type (which can be different from the template_type however). This still caught some errors however. To reproducing things, here is the diff I was playing with:
```diff
iff --git i/hw/top_darjeeling/data/top_darjeeling.hjson w/hw/top_darjeeling/data/top_darjeeling.hjson
index 95093ee276..c49187efdd 100644
--- i/hw/top_darjeeling/data/top_darjeeling.hjson
+++ w/hw/top_darjeeling/data/top_darjeeling.hjson
@@ -200,7 +200,7 @@
interrupts: {
// Any module with interrupts that …
```
=> [topgen] Various small fixes

rules/scripts/sival_signature_test.template.sh, rules/signing.bzl, rules/tests/BUILD, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/sival/binaries/BUILD
feat: Adding a signature verify test to check signed binaries
The intent is to have a way to verify a signed binary is good. One case is checking they are good before committing them into CI
test: run bazel test and verify no error found
=> [rom_ext] adding sig test rule with script

hw/ip/keymgr/rtl/keymgr_pkg.sv
Some of the default seeds (anyway overwritten using top-specific, secret netlist constants) were not yet generated using our own tooling. This commit simply regenerates them using our tooling.
=> [keymgr] Regenerate default seeds using util/design/gen-lfsr-seed.py

hw/ip/adc_ctrl/dv/env/adc_ctrl_env_cov.sv
Verissimo complains:
The class 'adc_ctrl_env_pkg::adc_ctrl_env_cov' constructor's argument 'name' default value is not an empty string!
We create the class object through the create call which creates the object as well as register it to UVM factory. So, leaving the name argument empty inside the constructor will not affect any functionality.
=> [adc_ctrl, verissimo][UVM69] UVM new() functions

hw/ip/mbx/data/mbx.hjson, hw/ip/mbx/doc/registers.md
Since reading WDATA is defined to return a value or zero rather than raise a TL-UL error in response, define it as a `rw` window; otherwise the csr/mem testing will fail on this memory window.
~~@Razer6 - is this appropriate for the SoC side? There is CIP code that tries to read from windows that are declared 'write only' and it expects a TL-UL error in response, so an alternative to marking it as 'rw' would be to loop back the '_re' signal to the 'error_i' on the tlul_adapter_reg, but the RTL annotates the return of zero as read data.~~ Thanks.
=> [mbx] Declare WDATA as a rw register

hw/ip/dma/dv/dma_sim_cfg.hjson, hw/ip/dma/dv/env/dma_env_cfg.sv, hw/ip/dma/dv/env/dma_pull_seq.sv, hw/ip/dma/dv/env/dma_scoreboard.sv, hw/ip/dma/dv/env/dma_seq_item.sv, hw/ip/dma/dv/env/dma_sys_tl_if.sv, hw/ip/dma/dv/env/seq_lib/dma_base_vseq.sv
Support finer granularity in the choice of the 4GiB address window into which the TL-UL memory is mapped. Instead of being 4GiB-aligned it is now 4B-aligned. This just provides more robust checking of the addressing arithmetic within the DUT.
Introduce separate 4GiB windows with different base addresses for the source and destination traffic.
Since the DMA controller itself can only perform transfers of less than 4GiB, now that the adapter supports separated read and writes transfers we can lose the 'waiving' of full verification.
=> [dv,dma] Improve SoC System bus testing

hw/Makefile
otp_ctrl is now ipgen'ed, it's register generation is done using topgen. Reggen does not have a dependency on that anymore, so remove that constraint from the Makefile.
=> [makefile] No OTP map dependency for reggen

sw/device/silicon_creator/manuf/base/provisioning_inputs.bzl, sw/host/provisioning/orchestrator/README.md, sw/host/provisioning/orchestrator/configs/skus/BUILD, sw/host/provisioning/orchestrator/configs/skus/emulation.hjson, sw/host/provisioning/orchestrator/src/BUILD, sw/host/provisioning/orchestrator/src/orchestrator.py, sw/host/provisioning/orchestrator/src/ot_dut.py
Backport #25407 ([manuf] Build stand-alone orchestrator package).
Depends on #27878.
I haven't actually tested the instructions but I suspect that with bzlmod being enabled on the master branch (and not in earlgrey_1.0.0 at the time), it's quite likely that it would break down due to runfiles.
Conflict note: to avoid further conflict, I left the `sival` configuration in the provisioning inputs more or less unchanged. But since we don't check in earlgrey_1.0.0 material in master, I had to leave it commented. This configuration is not usable in master anyway and this will have to be rethough after we are doing backporting.
=> Backport 25407 ([manuf] Build stand-alone orchestrator package)

sw/host/opentitanlib/BUILD, sw/host/opentitanlib/src/io/gpio.rs, sw/host/opentitanlib/src/test_utils/gpio_monitor.rs, sw/host/opentitanlib/src/util/mod.rs, sw/host/opentitanlib/src/util/vcd.rs, sw/host/opentitantool/src/command/gpio.rs, sw/host/tests/chip/pattgen/pattgen_ios.rs
Context: This is the 4th of a series of PRs (see #27612, #27613, #27614) to better integrate bitbanging utilities with opentitanlib, with a goal of recording waves that can be replayed during provisioning.
This PR introduces new utilities to dump GPIO samples to a VCD file format, and to parse VCDs back into GPIO samples. Supported is added for both uniform (discrete) samples that are returned by the `gpio_bitbanging` transport interface, as well as edge-represented waveforms as returned by the `gpio_monitoring` interface. This extends the `GpioMonitor` utility introduced in #22329 (replacing it to use this interface).
Support for parsing VCD samples is only currently extended to support enough functionality so that we can load back the dumped VCDs, with the intent that more features can …
=> [opentitanlib, testutils] Add utilities for dumping/parsing VCDs from GPIO samples

sw/host/provisioning/orchestrator/README.md, sw/host/provisioning/orchestrator/configs/skus/sival.hjson, sw/host/provisioning/orchestrator/src/orchestrator.py, sw/host/provisioning/orchestrator/src/ot_dut.py, sw/host/provisioning/orchestrator/tests/device_id_test.py
**DO NOT MERGE before https://github.com/lowRISC/opentitan/pull/27881,**
Backport [provisioning] remove RMA token from orchestrator inputs #25433
([provisioning] remove RMA token from orchestrator inputs)
=> Backport 25433 [provisioning] remove RMA token from orchestrator inputs

sw/device/silicon_creator/lib/drivers/BUILD, sw/device/silicon_creator/lib/drivers/lifecycle.c, sw/device/silicon_creator/lib/drivers/lifecycle.h, sw/device/silicon_creator/manuf/base/ft_personalize.c, sw/device/silicon_creator/rom_ext/e2e/handoff/BUILD, sw/device/silicon_creator/rom_ext/rom_ext.c, sw/host/opentitanlib/src/test_utils/lc_transition.rs, sw/host/tests/rom_ext/device_status/BUILD, sw/host/tests/rom_ext/device_status/src/main.rs
In order to more easily track boot stages during manufacturing, write status and version information into the `TRANSITION_TOKEN` registers in the lifecycle controller.  These registers may be accessed both from firmware and via JTAG, allowing an easy status readout during the manufacturing process.
1. Add helpers and definitions to the lifecycle controller driver.
2. Write status and version information when the ROM_EXT starts.
3. Write status and version information when ft_personalize starts.
4. Add a test that verifies the ROM_EXT values can be read via JTAG.
=> [rom_ext,manuf] Write boot status to the transition token registers

hw/ip/mbx/doc/checklist.md
The checklist.md file has been lagging a long way behind the current D/V status of the block. Modify those fields in D1, D2(S), V1 and V2 that are uncontentious, without yet performing formal sign-off. (Status reflects #27969 and #27970)
=> [doc,mbx] Update checklist.md to reflect status

util/topgen.py, util/topgen/templates/toplevel_pkg.sv.tpl
This makes it such that some of the non-addr-space-specific templates are not rendered for each address space.
And second, previously in toplevel_pkg.sv.tpl the `peripheral_e` enum and the AST macros were gated by `if has_pinmux`. I have replaced this with a `if addr_space_suffix == ""`. While this is not ideal, at least it's more correct than before.
There's no change in any of the generated files.
This change comes from a larger future PR where I'm trying to figure out the best way to decouple address-space-specific headers from toplevel headers and where I'm trying to remove special handling of the "hart" address space. I'll raise an issue to discuss this once I know more about this.
=> [topgen,template] Various topgen.py fixes

util/design/gen-otp-img.py
The Bazel rule propagates a `--stamp` flag, not a `-stamp` flag.
=> [util] fix bug in OTP image generation script

rules/scripts/qemu_pass.py
Replace the `subprocess.run` in the `qemu_pass.py` script with an equivalent manual Popen implementation to allow streaming the received test output line by line, as we can do in other test environments.
I tested this with
```
./bazelisk.sh test --test_output=streamed //sw/device/lib/base:memory_perftest_sim_qemu_rom_with_fake_keys
./bazelisk.sh test //sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat1_sim_qemu_rom_with_fake_keys -t- --test_output=streamed
```
=> [bazel,qemu] Stream QEMU stdout logs during test execution

hw/ip/dma/dv/env/dma_env_cfg.sv, hw/ip/dma/dv/env/dma_scoreboard.sv
The DUT supports read/write traffic from/to combinational devices (e.g. ROM/RAM connected directly to the TL-UL), which assert `d_valid` in the same cycle that a transaction is accepted ('a_valid & a_ready').
Modify the DV environment to enable combinational responses. This requires us to synchronize the notifications of A channel and D channel activity within the scoreboard, which we now do with minimal change to the current structure of the scoreboard; collect both the A channel and the D channel items before dispatching them into the existing checking logic.
(Requires #27973 for tests to pass.)
=> [dv,dma] Exercise combinational responses

.github/workflows/ci.yml, ci/jobs/slow-lint.sh, ci/scripts/verible-lint.sh
This PR refactors the `verible-lint.sh` script to be top-aware, allowing it to work with other tops instead of being hardcoded to `earlgrey`. 
The `verible-lint.sh` script (as many others) was hardcoded to use `top_earlgrey` for all lint configurations, making it impossible to use with other tops like Darjeeling or Englishbreakast. This created a maintenance burden and limited the script's usefulness in multi-top scenarios.
The script interface was modified to accept a second parameter for the top name, replacing hardcoded `earlgrey` paths with dynamic construction using `${top}` substitution. There is no explicit top validation to allow the script to work also with downstream tops. An implicit top validation is performed by checking if the lint config file exists. All existing CI jobs …
=> [lint] Make the verible lint step top aware

sw/host/provisioning/orchestrator/src/db.py, sw/host/provisioning/orchestrator/src/device_id.py, sw/host/provisioning/orchestrator/src/orchestrator.py, sw/host/provisioning/orchestrator/src/ot_dut.py, sw/host/provisioning/orchestrator/src/util.py, sw/host/provisioning/orchestrator/tests/BUILD, sw/host/provisioning/orchestrator/tests/device_id_test.py
Backport #25488 and #25493. Depends on #27953.
Also contains commit [bed096d](https://github.com/lowRISC/opentitan/commit/bed096d3b9cdf9e6d78a93116e22480a5c92666b) from #25502 to fix the device ID test
=> Backport 25488 and 25493  ([manuf] orchestrator.py tweaks, [provisioning] the DIN fields should be parsed as BCD values)

rules/scripts/sival_signature_test.template.sh
When given the ecdsa and/or spx key, the script appends on the amount of files RATHER THAN appending if the keys are provided.
=> [testing] Fix signature_test when used with multiple keys

hw/ip_templates/racl_ctrl/data/racl_ctrl.hjson.tpl, hw/ip_templates/racl_ctrl/doc/programmers_guide.md, hw/ip_templates/racl_ctrl/rtl/racl_ctrl.sv.tpl, hw/top_darjeeling/ip_autogen/racl_ctrl/data/racl_ctrl.hjson, hw/top_darjeeling/ip_autogen/racl_ctrl/doc/programmers_guide.md, hw/top_darjeeling/ip_autogen/racl_ctrl/doc/registers.md, hw/top_darjeeling/ip_autogen/racl_ctrl/rtl/racl_ctrl.sv, hw/top_darjeeling/ip_autogen/racl_ctrl/rtl/racl_ctrl_reg_pkg.sv, hw/top_darjeeling/ip_autogen/racl_ctrl/rtl/racl_ctrl_reg_top.sv
This PR changes the error_log_address register to not store the lowest 2 bits of the address. These 2 bits are always zero since TLUL requests are always 4-byte-aligned.
=> [racl_ctrl] Don't store lowest 2 bits in error_log_address register

sw/device/lib/crypto/impl/ecc/p256.c, sw/otbn/crypto/p256_base.s, sw/otbn/crypto/p256_shared_key.s, sw/otbn/crypto/tests/BUILD, sw/otbn/crypto/tests/p256_scalar_reblind_test.exp, sw/otbn/crypto/tests/p256_scalar_reblind_test.s
This commit adds blinding for the secret scalar d each time before a scalar multiplication is performed. This is done as a SCA countermeasure.
Related to #27648.
=> [sw,crypto] Scalar blinding of p256 keys

hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv, hw/ip/entropy_src/rtl/entropy_src_core.sv
This PR 1) fixes an RTL bug in Darjeeling which could lead to bucket test failures getting ignored and 2) fixes the prediction of the bucket test related registers for Darjeeling. The prediction of the `BUCKET_HI_WATERMARKS` and the `BUCKET_TOTAL_FAILS` registers as well as the `ALERT_FAIL_COUNTS.BUCKET_FAIL_COUNT` were all wrong before.
This is related to #27471.
=> [entropy_src] Fix bucket test failure aggregation and prediction for Darjeeling variant

sw/device/silicon_creator/manuf/base/perso_tlv_data.c
This PR re-enables previously disabled `obj_type` checks, to prevent `perso_tlv_get_cert_obj` from returning `kErrorOk` with an invalid `obj_type`.
=> Enable perso_tlv obj_type check

MODULE.bazel, MODULE.bazel.lock
Move dependencies and overrides to the top and keep them sorted.
=> [bazel] Reorganise MODULE.bazel file

.bazelrc, doc/contributing/style_guides/c_cpp_coding_style.md, hw/dv/tools/dvsim/vcs.hjson, hw/ip/aes/pre_dv/aes_cipher_core_tb/aes_cipher_core_tb.core, hw/ip/aes/pre_dv/aes_sbox_tb/aes_sbox_tb.core, hw/ip/aes/pre_dv/aes_wrap_tb/aes_wrap_tb.core, hw/ip/ascon/pre_dv/ascon_tb/ascon_sim.core, hw/ip/kmac/pre_dv/kmac_reduced_tb/kmac_reduced_tb.core, hw/ip/otbn/dv/verilator/otbn_top_sim.core, hw/ip/prim/pre_dv/prim_ascon/prim_ascon_duplex_tb/prim_ascon_dublex_tb.core, hw/ip/prim/pre_dv/prim_ascon/prim_ascon_round_tb/prim_ascon_round_tb.core, hw/ip/prim/pre_dv/prim_crc32/prim_crc32_sim.core, hw/ip/prim/pre_dv/prim_sync_reqack/prim_sync_reqack_tb.core, hw/ip/prim/pre_dv/prim_trivium/prim_trivium_tb.core, hw/top_darjeeling/ip/ast/ast.core, hw/top_earlgrey/dv/verilator/chip_sim.core, hw/top_earlgrey/ip/ast/ast.core, hw/top_englishbreakfast/chip_englishbreakfast_verilator.core, hw/top_englishbreakfast/ip/ast/ast.core, sw/host/tests/usbdev/usbdev_stream/build.sh, sw/host/tests/usbdev/usbdev_stream/build_standalone.sh
The first three commits are cherry-picked from https://github.com/lowRISC/opentitan/pull/27530/.
The last commit updates master-branch only related C++11 references to C++17.
=> [c++,hw,sw] Enable project wide C++17 Support

hw/ip/entropy_src/data/entropy_src.hjson, hw/ip/entropy_src/dv/entropy_src_rng16bits_sim_cfg.hjson, hw/ip/entropy_src/dv/entropy_src_rng4bits_sim_cfg.hjson, hw/ip/entropy_src/dv/tb/tb.sv, hw/ip/entropy_src/rtl/entropy_src.sv, hw/ip/entropy_src/rtl/entropy_src_core.sv, hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/top_darjeeling.hjson, hw/top_darjeeling/rtl/autogen/top_darjeeling.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
As discussed today @Razer6 . This also reduces the depth of the distribution FIFO.
=> [entropy_src] Add parameter to disable the CS AES halt request interface, disable it for Darjeeling

sw/device/silicon_creator/lib/ownership/test_owner.c, sw/device/silicon_creator/rom_ext/defs.bzl, sw/device/silicon_creator/rom_ext/e2e/handoff/BUILD, sw/device/silicon_creator/rom_ext/e2e/handoff/sram_exec_test.c
This change adds an end-to-end test for SRAM execution mode owner config switches.
The test verifies that the SRAM execution mode can be enabled, disabled, and disabled+locked.
=> [sw,e2e] Add SRAM execution owner config testcases

hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv, hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv, hw/ip/entropy_src/dv/env/entropy_src_path_if.sv, hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_rng_seq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_err_vseq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv, hw/ip/entropy_src/rtl/entropy_src_core.sv, util/design/gen-rng-health-thresholds.py
This PR contains two main changes:
1) an RTL change to take the max bin count value of all Bucket test instances (rather than summing the max bin counts of the individual instances up as before), 
2) a DV and tooling change to correct the threshold computation. Previously, most health tests continuously failed in the rng and the rng_max_rate tests which is bad for coverage.
=> [entropy_src] Fix bucket test result aggregation for Darjeeling, correct threshold computation

hw/dv/dpi/gpiodpi/gpiodpi.sv
Assignments on variables (reg/logic) are just initialization. Assignments wires are continuous assignment (assign).
=> [gpiodpi] fix activation and the effective clock generation

sw/device/lib/crypto/impl/ecc/p256.c, sw/otbn/crypto/p256_sign.s
This commit adds mask refreshing before the secret scalar is used for the p256 sign algorithm.
=> [sw,cryptolib] Add mask refreshing for ECC p256 sign

hw/ip/csrng/dv/sva/csrng_assert_if.sv
`dv/sva/csrng_assert_if.sv` contains a list of FSM-related SVAs that need to be turned off before running tests in which FSMs are forced to invalid encodings/states. These paths were relative to the DUT, not to the test environment, which resulted in these asserts not being found when requested to be disabled (and re-enabled after the test).
This caused a sizable number of tests to fail (`csrng_intr` and `csrng_err`); with this fix, the [pass rate](https://nightly.reports.lowrisc.org/opentitan_weekly_earlgrey/2025_06_22/hw/ip/csrng/dv/report.html) increases from ~95% to ~99%.
=> [csrng/dv] Fix DV paths to FSM-related asserts

util/design/README.md
This argument to `gen-otp-img.py` is required.
=> [gen-otp-img,doc] Add `--mmap-def` argument missing in example

rules/opentitan/qemu.bzl
Adds a `qemu_args` to `qemu_params` that allows specifying arguments to be passed directly to QEMU.
I missed this the first time around.
=> [bazel] Allow extra args to be passed to QEMU

hw/ip_templates/pinmux/rtl/pinmux.sv.tpl, hw/top_darjeeling/ip_autogen/pinmux/rtl/pinmux.sv, hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux.sv, hw/top_englishbreakfast/ip_autogen/pinmux/rtl/pinmux.sv
This is analogous to the change we made in e.g. rom_ctrl (commit 0f7e1226574), where we change the assertion to actually be true.
In both cases, the original version of the assertion wasn't strictly true because the alert receiver could stall the communication from the alert sender, meaning that the alert_p signal would never go high.
Since we verify the alert system separately, this commit simplifies things by just checking that we *ask* the alert system to do something.
=> [pinmux,rtl] Tweak the FpvSecCmBusIntegrity_A assertion

hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson, hw/top_darjeeling/data/autogen/top_darjeeling.secrets.testing.gen.hjson, hw/top_darjeeling/data/otp/otp_ctrl_mmap.hjson, hw/top_darjeeling/ip_autogen/otp_ctrl/data/top_darjeeling_otp_ctrl.ipconfig.hjson, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/autogen/top_earlgrey.secrets.testing.gen.hjson, hw/top_earlgrey/data/otp/otp_ctrl_mmap.hjson, hw/top_earlgrey/ip_autogen/otp_ctrl/data/top_earlgrey_otp_ctrl.ipconfig.hjson, util/design/lib/OtpMemImg.py
Add the Darjeeling partitions to the SW skips for generating the C header and make it more generic to support more HWCFG/SECRET partitions.
=> [OtpMemImg] Don't hard-code partitions for alignment and SW header skip

hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv, hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv, hw/ip/entropy_src/rtl/entropy_src_adaptp_ht.sv, hw/ip/entropy_src/rtl/entropy_src_markov_ht.sv, hw/ip/prim/rtl/prim_sum_tree.sv
See commit messages for details. This is especially relevant for the Darjeeling configuration of the ENTROPY_SRC where these counters can overflow otherwise.
=> [prim]  Add parameter to control saturation behavior of prim_sum_tree and model that behavior in ENTROPY_SRC

hw/ip/i2c/doc/programmers_guide.md
Supersedes https://github.com/lowRISC/opentitan/pull/19542. I co-authored the commit from @aadhithan-rv to add the sign-off.
=> [hw,i2c,docs] Fix incorrect computation of the SCL period

hw/ip/racl_ctrl/dv/env/racl_ctrl_env_cfg.sv, hw/ip/racl_ctrl/dv/racl_ctrl_tests.hjson, hw/ip_templates/racl_ctrl/dv/tb.sv.tpl, hw/top_darjeeling/ip_autogen/racl_ctrl/dv/tb.sv
This depends on #27218 and #27393. Once those two PRs are merged, only the final commit remains. Its commit message is:
```
[racl_ctrl,dv] Connect up an interrupt interface in tb
This gets registered as "intr_vif" in uvm_config_db. That gets picked
up by cip_base_env and then stored as cip_base_env_cfg.intr_vif in the
environment's config object.
Setting the num_interrupts field to 1 in that config object means that
the CIP base code will know about the existence of the interrupt (and
will automatically generate sequences to poke the associated intr_test
register).
Finally, we add intr_test.hjson to the configurations imported by
racl_ctrl_tests. This contains racl_ctrl_intr_test, which implements
the intr_test testpoint in intr_test_testplan (imported by
racl_ctrl_testplan).
```
=> [racl_ctrl,dv] Connect up an interrupt interface for racl_ctrl DV

hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv, hw/top_earlgrey/templates/chiplevel.sv.tpl
We are running into LUT utilization limits on the CW310.  Disabling masking on the CW310 helps by reducing LUT usage.
=> [top_earlgrey,cw310] Disable AES masking

sw/device/silicon_creator/rom_ext/e2e/dice_chain/BUILD, sw/device/silicon_creator/rom_ext/e2e/dice_chain/debug_mode_test.c
This change introduces a new end-to-end test for the DICE chain to verify the correct measurement of the debug mode.
The test reads the DICE attestation data from flash, parses the CDI_1 certificate, and extracts the debug mode information. It then compares this extracted debug mode with an expected value.
This ensures that the debug mode state is accurately reflected in the DICE measurements, which is critical for secure boot and attestation.
=> [sw,e2e] Add testcase for OwnerSw DICE debug mode measurements

sw/device/silicon_creator/rom/e2e/clkmgr/BUILD, sw/device/silicon_creator/rom/e2e/clkmgr/jitter_test.c, sw/device/silicon_creator/rom/e2e/rstmgr/BUILD, sw/device/silicon_creator/rom/e2e/rstmgr/alert_info_test.c, sw/device/silicon_creator/rom/e2e/rstmgr/cpu_info_test.c
This PR adds ROM e2e tests for the clkmgr & rstmgr OTP switch to increase coverage for those branches. The tests check those registers are configured correctly by ROM.
---
Errata #27498: On Earlgrey, a typo in ROM sets an incorrect register when the CPU debug info OTP switch is enabled. The `exit_success` is temporarily set to the failure string for the Earlgrey branch to keep the test happy.
=> [sw,e2e] Add testcases for clkmgr & rstmgr ROM OTP switches

sw/device/lib/crypto/drivers/aes.c
This PR contains two commits that harden setting the AES config against FI.
=> [crypto] Harden setting AES config

sw/device/silicon_creator/lib/cert/BUILD, sw/device/silicon_creator/lib/cert/dice_cwt_functest.c
This change adds a new functional test `dice_cwt_functest` to cover corner cases related to certificate body sizes and magic bytes for the DICE CWT parser, which increases the test coverage to those error branches.
=> [sw,test] Add corner tests for dice cwt parser

rules/bitstreams.bzl, rules/scripts/bitstreams_workspace.py
This makes use of the repository_ctx's ability to watch file changes to detect changes within .git when the git HEAD moves from a hash to another or one branch to another.
=> [bazel] automatic reconfigure bitstream cache when git hash changes

sw/device/silicon_creator/manuf/base/BUILD, sw/device/silicon_creator/manuf/base/perso_tlv_data.h, sw/device/silicon_creator/manuf/base/perso_tlv_data_unittest.cc
This commit adds the unit test for the perso_tlv_data library. The unit test verifies the correctness of the TLV encoding/decoding of several corner cases.
=> [cov] add perso_tlv_data unit test

hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv.tpl, hw/top_darjeeling/rtl/autogen/testing/lc_ctrl_state_pkg.sv, hw/top_earlgrey/rtl/autogen/testing/lc_ctrl_state_pkg.sv, util/topgen.py
That way we can re-enable the check-countermeasures CI check for lc_ctrl since all labels are within the lc_ctrl folder.
=> [hw,lc_ctrl,sec] Move SEC_CM label from state package to lc_ctrl

hw/ip/keymgr_dpe/dv/env/keymgr_dpe_scoreboard.sv, hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv
This fixes a Todo lying around. Initialize the slot with randomness and also during an erase operation.
=> [hw,keymgr_dpe,rtl] Initialize slots with randomness (and during erase)

hw/ip/keymgr_dpe/data/keymgr_dpe.hjson, hw/ip/keymgr_dpe/doc/registers.md, hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv, hw/ip/keymgr_dpe/rtl/keymgr_dpe_op_state_ctrl.sv, hw/ip/keymgr_dpe/rtl/keymgr_dpe_pkg.sv
The `keymgr_dpe` currently only supports a single DICE tree, as the root key is loaded exclusively at initialization. This prevents the creation of new, independent security domains at runtime.
This PR adds a new load command to the `keymgr_dpe`. This command makes it possible to load a new root key into a specified key slot at any point after initialization. This effectively enables the creation of a second (or subsequent) DICE tree, allowing for dynamic key management and derivation in separate contexts.
=> [hw,keymgr_dpe,rtl] Ability to load a root key into a slot

hw/ip/keymgr_dpe/data/keymgr_dpe.hjson, hw/ip/keymgr_dpe/doc/registers.md, hw/ip/keymgr_dpe/rtl/keymgr_dpe_pkg.sv, hw/ip/keymgr_dpe/rtl/keymgr_dpe_reg_pkg.sv, hw/ip/keymgr_dpe/rtl/keymgr_dpe_reg_top.sv
This is to allow more key slots to be active at the same time. Possibly in the future to hold more than one tree.
=> [hw,keymgr_dpe,rtl] Support 8 key slots

hw/ip_templates/otp_ctrl/rtl/otp_ctrl_dai.sv, hw/top_darjeeling/ip_autogen/otp_ctrl/rtl/otp_ctrl_dai.sv, hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_dai.sv
Before this commit, DAI writes to the zeroization marker field were rejected for buffered partitions with a HW digest and for unbuffered partitions.  While this effectively applies to all OTP partitions configured upstream (for both Darjeeling and Earlgrey) already, it is cleaner to just *always* reject DAI writes to the zeroization marker field.
=> [otp_ctrl/rtl] Unconditionally reject DAI writes to zeroization marker

sw/device/lib/crypto/drivers/BUILD, sw/device/silicon_creator/lib/drivers/BUILD, sw/device/silicon_creator/rom/e2e/BUILD, sw/device/silicon_creator/rom/e2e/keymgr/BUILD, sw/device/tests/BUILD, sw/device/tests/crypto/BUILD
This will help enable development with CI testing on QEMU for these features, targeting the `earlgrey_1.0.0` release.
The tests that have the fatal reset property disabled intentionally use the rstmgr, so we need to tell QEMU not to exit early when there is a reset signal.
=> [qemu, bazel] Add QEMU environment & make resets non-fatal for some tests

sw/host/cryptotest/testvectors/data/schemas/ecdsa_schema.json
This duplicate field was introduced at commit 73fc849dae1a82547d90476603077e2ef6521d57.
=> [cryptotest] Remove duplicate ECDSA schema field

sw/device/silicon_creator/rom/e2e/keymgr/BUILD, sw/device/tests/BUILD
When I added the QEMU environment to the tests in https://github.com/lowRISC/opentitan/pull/28138 I missed the OTP overrides that were required in the test parameters (only present on FPGA currently) - add these so that we actually exercise the test functionality, rather than testing in the RMA state.
=> [bazel,qemu] Fix missing OTP override on some QEMU tests

hw/top_darjeeling/formal/chip_conn_cfg.hjson
The `top_chip` variable was introduced in [this commit](https://github.com/lowRISC/opentitan/tree/dc06a181e1686f44847b9a8040398bef69b56b9e), but it is not set. This leads dvsim to fail on the specific config.
To align this file with Earl Grey, we hardcode the path here instead of setting a variable that must be constant.
=> [top_darjeeling/formal] Fix config

sw/device/silicon_owner/bare_metal/BUILD
Partial backport of #25540. I did not include the changes to support the appkey since it is not relevant to master.
=> Partial backport of 25540 ([signing] Setup owner signing for FPGA environments)

sw/device/lib/crypto/drivers/BUILD, sw/device/lib/crypto/drivers/otbn.c, sw/device/lib/crypto/drivers/otbn.h
The `otbn_dmem_write` function is a security-sensitive function as it writes secrets from Ibex into OTBN. This PR hardens this function by:
- Randomize the write order to mitigate SCA
- Check if the loop correctly executed to mitigate FI
- Read back and compare the checksum to the expected checksum to mitigate FI
=> [crypto] Harden `otbn_dmem_write` against SCA & FI

sw/device/lib/crypto/impl/BUILD, sw/device/lib/crypto/impl/status.h, sw/device/lib/crypto/impl/status_functest.c
The HARDENED_TRY macro currently only does a redundant branch in case the status is ok, but misses a redundant branch for the error limb.
Adapt the macro such that it performs a redundant branch on each case. In order to save code size, a new configuration is used.
The assembly has the following pattern:
j function
addi a0, a0, -1849 // This is done to branch on zero to save code size, and to force the compiler to work with a0 (not to compile away some of the checks)
beqz a0, continue_branch
addi a0, a0, 1849
bltz a0, return_branch
unimp
...
continue_branch:
beqz a0, rest_of_the_code
unimp
Finally, running //sw/device/tests/crypto:otcrypto_export_size, code size goes from ~84k to ~83k.
=> [HARDENED_TRY] Harden HARDENED_TRY

sw/device/lib/crypto/drivers/hmac.c
Some functions in the HMAC driver are security-sensitve. Use `HARDENED_TRY()` to check the return value of those functions.
=> [crypto] Check return value of HMAC functions

hw/top_darjeeling/top_darjeeling.core
Darjeeling does not instantiate those IPs, no need to have them in the core file and add more files than needed.
=> [hw,darjeeling,corefile] Remove adc_ctrl/sysctrl from fusesoc deps

sw/device/lib/crypto/impl/aes_gcm/BUILD, sw/device/lib/crypto/impl/aes_gcm/aes_gcm.c, sw/device/lib/crypto/impl/aes_gcm/ghash.c, sw/device/lib/crypto/impl/aes_gcm/ghash.h, sw/device/lib/crypto/impl/aes_gcm/ghash_unittest.cc, sw/device/lib/crypto/include/aes_gcm.h
This commit hardens the GHASH function against SCA. The masking scheme follows the approach highlighted in lowRISC/opentitan#27258.
In summary, this masking schemes processes the shares of the hash subkey H = H0 + H1 and the encrypted intial counter block S = S0 + S1 independently.
**Code Size and Performance Analysis**
Runtime: 142933 to 178564 cycles (25+%) for the first AES-GCM testvector.
Code size: from 83,051B to 83,885B (+1%)
**SCA Measurements**
Unfortunately the executing time of AES-GCM is too long to record power traces using the CW setup. Hence, instead, I focused on measuring the multiplication inside the [ghash_process_block(](https://github.com/lowRISC/opentitan/blob/3479cd5ee544e82e6eb8f7b042db42c3472de8e6/sw/device/lib/crypto/impl/aes_gcm/ghash.c#L242)) function:
state = …
=> [crypto] AES-GCM SCA hardening

.github/workflows/ci.yml, sw/device/tests/qemu/BUILD, sw/device/tests/qemu/i2c_qemu_test.c
This creates a test for the EG 1.0.0 I2C device in QEMU (See https://github.com/lowRISC/qemu/pull/162).
The test is in its own `qemu/` sub-directory as this test is QEMU-specific - it does not use pinmuxing as this is unsupported in QEMU.
The test writes and reads from a DS1338 RTC+NVRAM to test host functionality, and the QEMU i2c-echo device is used to test host and target functionality. These are attached to each I2C bus at QEMU startup.
=> Create I2C QEMU test

rules/opentitan/keyutils.bzl, sw/device/silicon_creator/rom/keys/unauthorized/ecdsa/BUILD, sw/device/silicon_creator/rom/keys/unauthorized/spx/BUILD
- Remove `key_{ecdsa,spx} and filegroup rules for the "unauthorized" keys.
- Remove any references to the now-deleted rules.  Reference the "unauthorized" keyset instead.
=> [rom] Remove key_{ecdsa,spx} and filegroup rules

sw/host/opentitantool/src/command/ecdsa.rs
The `opentitantool ecdsa verify` command previously only supported raw 64-byte binary signature files.
This change updates the command to use the
`EcdsaRawSignature::read_from_file` helper function. This function can automatically detect and parse raw binary, ASN.1 DER, and PEM encoded signature files.
=> [opentitantool] Add support for DER/PEM signatures in `ecdsa verify`

sw/device/examples/sram_program/sram_program.ld, sw/device/silicon_creator/manuf/lib/sram_program.ld
The bss section of the SRAM provisioning program silently overflowed into the allocated stack region. This PR partially cherrypicked the KEEP fixes from #26354 to fix it:
* `[sw,sram_program] Don't KEEP() all sections`  commit from:
* #26354
This PR also adds a check to detect when the bss section overlaps with the stack.
---
Result of `//sw/device/silicon_creator/manuf/base/sram_ft_individualize_sival_fpga_hyper310_rom_with_fake_keys.elf`:
Before: (bss ends at 0x1001e294, while stack starts at 0x1001c000)
```
[ 6] .bss              NOBITS          1001b998 019a98 002900 00  WA  0   0  4
```
After:
```
[ 6] .bss              NOBITS          1000d21c 00b31c 0009b0 00  WA  0   0  4
```
=> [sw,sram_program] Add stack region overlapping check

sw/device/lib/crypto/drivers/BUILD, sw/device/lib/crypto/drivers/aes.c
The cryptolib uses hard-coded drivers, which only work for Earlgrey. This PR moves the aes driver to the generic DT-API.
=> [cryptolib] Move aes driver to DT

sw/device/lib/crypto/drivers/BUILD, sw/device/lib/crypto/drivers/keymgr.c
The cryptolib uses hard-coded drivers, which only work for Earlgrey. This PR moves the keymgr driver to the generic DT-API.
=> [cryptolib] Move keymgr driver to DT

sw/device/lib/crypto/drivers/BUILD, sw/device/lib/crypto/drivers/entropy_kat.c
The cryptolib uses hard-coded drivers, which only work for Earlgrey. This PR moves the entropy_kat driver to the generic DT-API.
=> [cryptolib] Move entropy_kat driver to DT

sw/device/lib/crypto/drivers/BUILD, sw/device/lib/crypto/drivers/hmac.c
The cryptolib uses hard-coded drivers, which only work for Earlgrey. This PR moves the hmac driver to the generic DT-API.
=> [cryptolib] Move hmac driver to DT

hw/ip_templates/otp_ctrl/data/otp_ctrl.hjson.tpl, hw/top_darjeeling/ip_autogen/otp_ctrl/data/otp_ctrl.hjson, hw/top_darjeeling/ip_autogen/otp_ctrl/doc/registers.md, hw/top_earlgrey/ip_autogen/otp_ctrl/data/otp_ctrl.hjson, hw/top_earlgrey/ip_autogen/otp_ctrl/doc/registers.md
The previous description `Software must write this digest value` made it sound like the exact value from this register was supposed to be used for locking a partition. But that's not correct and also not possible since the value would be `0` before the partition is locked, which means that the partition wont get locked.
=> [otp_ctrl] Clarify *_DIGEST register description.

hw/ip/rv_timer/dv/env/seq_lib/rv_timer_base_vseq.sv, hw/ip/rv_timer/dv/env/seq_lib/rv_timer_random_vseq.sv
With the previous version, we had something of this form:
```
fork
for (...) begin
fork
something_or_other();
join_none
end
wait fork;
join
```
This means the "wait fork" ends up starting in parallel with the thing that was supposed to start sub-processes. This was all rather confusing when I ran things with Xcelium because we end up with the "wait fork" completing immediately, but then the something_or_other process starting afterwards (no longer being waited for). This gets followed by a "disable fork", leaving a process being killed when it is trying to get a sequencer, causing a failure a cycle later.
I think the author probably intended something like this:
```
begin
for (...) begin
fork
something_or_other();
join_none
end
wait fork;
end
```
(where the outer begin/end is necessary to …
=> [rv_timer,dv] Fix subtly broken fork/join tree

sw/device/lib/crypto/drivers/BUILD, sw/device/lib/crypto/drivers/kmac.c
The cryptolib uses hard-coded drivers, which only work for Earlgrey. This PR moves the kmac driver to the generic DT-API.
=> [cryptolib] Move kmac driver to DT

sw/device/lib/crypto/impl/rsa.c, sw/device/lib/crypto/impl/rsa/rsa_datatypes.h, sw/device/lib/crypto/impl/rsa/rsa_encryption.c, sw/device/lib/crypto/impl/rsa/rsa_keygen.c, sw/device/lib/crypto/impl/rsa/rsa_modexp.c, sw/device/lib/crypto/impl/rsa/rsa_modexp.h, sw/device/lib/crypto/impl/rsa/rsa_signature.c, sw/device/lib/crypto/include/rsa.h, sw/device/tests/crypto/otcrypto_interface.h, sw/device/tests/crypto/rsa_2048_encryption_functest.c, sw/device/tests/crypto/rsa_2048_key_from_cofactor_functest.c, sw/device/tests/crypto/rsa_2048_keygen_functest.c, sw/device/tests/crypto/rsa_2048_signature_functest.c, sw/device/tests/crypto/rsa_3072_encryption_functest.c, sw/device/tests/crypto/rsa_3072_keygen_functest.c, sw/device/tests/crypto/rsa_3072_signature_functest.c, sw/device/tests/crypto/rsa_4096_encryption_functest.c, sw/device/tests/crypto/rsa_4096_keygen_functest.c, sw/device/tests/crypto/rsa_4096_signature_functest.c, sw/device/tests/penetrationtests/firmware/fi/cryptolib_fi_asym_impl.c, sw/device/tests/penetrationtests/firmware/sca/cryptolib_sca_asym.c, sw/device/tests/penetrationtests/firmware/sca/cryptolib_sca_asym_impl.c, sw/device/tests/penetrationtests/firmware/sca/cryptolib_sca_asym_impl.h
F4=2^16+1 is the de-facto standard public-key exponent for all standardized RSA encryption/signature schemes. The cryptolib supported a haphazard implementation for arbitrary exponents that reverted back to F4 in many places. This commit removes all the residuals with regards to arbitrary values.
=> [crypto/rsa] Fix public-key exponent to F4

hw/ip/entropy_src/dv/env/entropy_src_env.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
Previously, this function erroneously used the interrupt threshold to determine the number of words to read. This is not suitable for testing higher entropy rates (the Observe FIFO always overflows). This PR changes the function as follows:
1. The current FIFO depth is used to determine the number of words to read (for coverage, the threshold is still used but with low probability only).
2. Once the previously determined number of words have been read, the routine again checks the depth and continues reading. This is what also firmware would be doing.
In addition, the PR also tunes the TL-UL timing for the max rate test and the Darjeeling configuration.
With this PR, the pass rates for the two different ENTROPY_SRC configurations get very close. This resolves lowRISC/OpenTitan#27471.
=> [entropy_src/dv] Improve do_entropy_data_read() for testing higher rates

sw/device/tests/BUILD, sw/device/tests/aes_force_prng_reseed_test.c, sw/device/tests/aes_interrupt_encryption_test.c, sw/device/tests/aes_prng_reseed_test.c, sw/device/tests/aes_stall_test.c
This PR moves all remaining AES tests to the DT API and enables them for Darjeeling.
=> [sw,test] Move all AES tests to DT

sw/device/tests/BUILD, sw/device/tests/kmac_endianess_test.c, sw/device/tests/kmac_entropy_stress_test.c, sw/device/tests/kmac_error_conditions_test.c, sw/device/tests/kmac_kmac_key_sideload_test.c
This PR moves all remaining kmac tests to the DT API and enables them for Darjeeling.
=> [sw,test] Move all KMAC tests to DT

hw/ip/prim/rtl/prim_sha2.sv
Assert is used within the file but the include is missing.
=> [hw,prim_sha2,rtl] Add missing includes of prim_assert.h

hw/ip/rom_ctrl/util/scramble_image.py, hw/top/BUILD, rules/autogen.bzl, rules/opentitan/exec_env.bzl, rules/opentitan/fpga.bzl, rules/opentitan/silicon.bzl, rules/opentitan/sim_dv.bzl, rules/opentitan/sim_verilator.bzl, rules/opentitan/transform.bzl
This PR replaces #28231 and does a few things:
- it adds the top hjson to the exec_env
- it then uses that to pass the hjson to the ROM scrambling script
- it fixes the scrambling script to correctly read parameters from the files
- finally it lets the scrambling script handle the case where scrambling is disabled (only english breakfast uses that at the moment).
=> [scrambling] Allow the scrambling script to handle SecDisableScrambling

sw/host/sphincsplus/key.rs
The SPHINCS+ key generation and signing functions expect a 32-byte message when the `PreHashedSha256` domain parameter is used. Enforce this length constraint with an assertion.
=> [sw,signing] Enforce hash length for pre-hashed SHA256

sw/host/opentitanlib/src/image/image.rs
This change adds a new check to ensure that the image assembly process does not result in overlapping firmware being written into the same region to catch oversized firmware.
=> [sw,opentitantool] Add overlap check during image assembly

MODULE.bazel.lock
This was changed by the recent updates to Rust dependencies but the lockfile was not checked in.
=> [bazel] Update bzlmod lockfile

rules/scripts/modid_check.sh
Without this flag, OTT will pick up your local ~/.config/opentitan flags and if those include an `--interface` it will try to connect and fail if that's not found.
This causes problems if you have, for example, `--interface cw310` in your config and don't have one connected when using the script.
=> [bazel] Disable OTT config file in modid check

sw/device/silicon_creator/rom/e2e/clkmgr/BUILD, sw/device/silicon_creator/rom/e2e/clkmgr/jitter_test.c, sw/device/silicon_creator/rom/e2e/rstmgr/BUILD, sw/device/silicon_creator/rom/e2e/rstmgr/alert_info_test.c, sw/device/silicon_creator/rom/e2e/rstmgr/cpu_info_test.c, sw/device/silicon_creator/rom/rom_start.S
This PR resolves #27498 on the `master` branch:
* #27498
The first two commits are cherry-picked from #28058, with extra multi-top fixes.
The final commit resolves the bug and activates the previously cherry-picked test.
=> [sw,rom] Fix CPU debug info OTP configuration in ROM

.bazelrc, MODULE.bazel.lock, rules/actions.bzl, rules/coverage/BUILD, rules/opentitan/cc.bzl, sw/device/BUILD, sw/device/lib/base/BUILD, third_party/lowrisc/BUILD.lowrisc_rv32imcb_toolchain.bazel, third_party/lowrisc/extensions.bzl, toolchain/BUILD
This is manual cherry pick the toolchain update to master.
The only conflict resolved is lines around cc_tool_map load, which isn't exist on earlgrey_1.0.0.
```
load("@rules_cc//cc/toolchains:tool_map.bzl", "cc_tool_map")
```
---
ROM / ROM_EXT is the same before and after this change.
```bash
$ ./bazelisk.sh build //sw/device/silicon_creator/rom_ext:rom_ext_dice_x509_slot_virtual && \
sha256sum bazel-bin/sw/device/silicon_creator/rom_ext/rom_ext_dice_x509_slot_virtual_silicon_creator.bin
619e07265c7697ac48c7cbdcf05a59cfa8fd1a6c78d0634bdb3ae496b682ab42  bazel-bin/sw/device/silicon_creator/rom_ext/rom_ext_dice_x509_slot_virtual_silicon_creator.bin
$ ./bazelisk.sh build //sw/device/silicon_creator/rom:mask_rom && \
sha256sum bazel-bin/sw/device/silicon_creator/rom/instrumented_mask_rom_silico …
```
=> Cherry-pick to master: [toolchain,cov] Upgrade lowrisc clang version and add coverage flags #28250

.github/workflows/ci.yml, .github/workflows/fpga.yml, ci/scripts/run-fpga-tests.sh, sw/device/silicon_creator/rom_ext/e2e/ownership/BUILD, sw/device/tests/BUILD, sw/device/tests/crypto/BUILD, sw/device/tests/crypto/cryptotest/BUILD
This PR changes CI to filtering FPGA tests on the `slow_test` tag rather than timeouts.
This allows us to run longer tests in nightlies and also ensures that the pattern file uploaded as an artifact accurately lists the tests being run and isn't being filtered further.
=> [ci] Enable slow cryptotests in nightlies

sw/device/lib/crypto/drivers/aes.c, sw/device/lib/crypto/drivers/aes.h, sw/device/lib/crypto/drivers/entropy.c, sw/device/lib/crypto/drivers/hmac.c, sw/device/lib/crypto/drivers/keymgr.c, sw/device/lib/crypto/impl/aes.c, sw/device/lib/crypto/impl/aes_gcm/aes_gcm.c
Reread the CTRL and CTRL_AUX registers from the AES once it is done with its operation.
Move HMAC's verification of the CFG registers to the end of the computation.
Reread the CTRL register from the CSRNG after generating data.
Reread the CONTROL register from the key manager when generating a key.
This is to stop potential fault attacks on the security critical registers.
=> [crypto] CTRL regs hardening: AES, HMAC, KeyMngr, CSRNG

sw/device/lib/base/crc32.h, sw/device/lib/crypto/drivers/aes.c, sw/device/lib/crypto/drivers/hmac.c, sw/device/lib/crypto/impl/aes_gcm/BUILD, sw/device/lib/crypto/impl/aes_gcm/ghash.c, sw/device/lib/crypto/impl/aes_gcm/ghash.h, sw/device/lib/crypto/impl/aes_gcm/ghash_unittest.cc, sw/device/lib/crypto/impl/ecc/BUILD, sw/device/lib/crypto/impl/ecc/p256.c, sw/device/lib/crypto/impl/ecc/p256.h, sw/device/lib/crypto/impl/ecc/p384.c, sw/device/lib/crypto/impl/ecc/p384.h, sw/device/lib/crypto/impl/ecc_p256.c, sw/device/lib/crypto/impl/ecc_p384.c, sw/device/lib/crypto/include/aes_gcm.h, sw/device/tests/penetrationtests/firmware/fi/cryptolib_fi_asym_impl.c, sw/device/tests/penetrationtests/firmware/sca/cryptolib_sca_asym_impl.c
General check whether checksums were missing in security critical structures in the cryptolib for fault protection.
In general:
- ECC keys do not have checksums
- GCM's H does not have a checksum
=> [crypto] Checksums in key structures

hw/top_earlgrey/BUILD, rules/opentitan/defs.bzl, rules/opentitan/qemu.bzl, sw/device/lib/crypto/drivers/BUILD, sw/device/lib/testing/test_rom/BUILD, sw/device/silicon_creator/lib/drivers/BUILD, sw/device/silicon_creator/rom_ext/BUILD, sw/device/silicon_creator/rom_ext/imm_section/defs.bzl, sw/device/tests/BUILD
This PR adds initial support for SiVal ROM_EXT tests running in QEMU. It makes use of the latest release QEMU binaries that are pinned in OpenTitan already, so no overriding is needed.
One notable limitation is a result of QEMU's `flashgen.py` script which generates a QEMU flash backend image for emulation, which can only take two binaries and places restrictions on what these binaries can be and where they can be stored (essentially, ROM_EXT at 0x0 and some firmware at 0x10000). This also does not properly support using multiple banks at the moment, as this use case is not adequately supported in QEMU.
This can be tested by running most existing tests that pass in the `sim_qemu_rom_with_fake_keys` environment and the `fpga_cw310_sival_rom_ext` environment. I've run a local regression …
=> [bazel,qemu] Add initial support for `sival_rom_ext` for `sim_qemu` environments.

sw/device/lib/crypto/impl/ecc/p384.c, sw/otbn/crypto/p384_sign.s
This PR adds remasking of the secret key scalar each time
the sign routine is executed. This is added as a countermeasure
against SCA.
Based on #28043
=> [sw,cryptolib] p384 remasking

sw/device/silicon_creator/rom_ext/e2e/handoff/BUILD, sw/device/silicon_creator/rom_ext/e2e/handoff/fault_start.S
The `OWNER_SW` is not intended to return control to the `ROM_EXT`; if it does, the `ROM_EXT` should report an error.
This commit introduces a new fault test, `return_boot_failed`, which simulates the `OWNER_SW` returning to `ROM_EXT` (e.g., via a `ret` instruction) to verify that `ROM_EXT` correctly handles this unexpected scenario.
This test can make sure the `ROM_EXT` handles this error situation correctly.
=> [sw,e2e] Add fault test for OWNER_SW returning to ROM_EXT

sw/device/silicon_creator/lib/ownership/test_owner.c, sw/device/silicon_creator/rom_ext/defs.bzl, sw/device/silicon_creator/rom_ext/e2e/rescue/BUILD, sw/host/tests/rescue/BUILD, sw/host/tests/rescue/dfu_rescue_error_handling.rs
This PR includes 4 commits that
- Add a test to validate SPI DFU state machine transitions with both valid and invalid requests.
- Add a test to ensure correct error handling and unsupported SPI DFU requests.
- Add a test to verify robustness against invalid flash transactions during SPI DFU rescue mode.
- Add a test to verify that the USB DFU implementation correctly rejects download requests where the data chunk size exceeds the allowed maximum.
=> [rescue,dfu,test] Add dfu error handle tests

sw/device/silicon_creator/lib/drivers/ibex.c, sw/device/silicon_creator/lib/drivers/ibex.h, sw/device/silicon_creator/lib/drivers/ibex_unittest.cc, sw/device/silicon_creator/rom/rom.c, sw/device/silicon_creator/rom_ext/rom_ext.c
Generalize the address translation API to support the number slots defined by the hardware top.
Extend the API with helpers to get those number of slots and verify a slot translation configuration.
Fixed #28369
Co-developed-by: Loic Lefort <loic@rivosinc.com>
=> [sw,silicon_creator] Generalize the ibex driver API

sw/device/tests/BUILD
This test is expected to fail so we need to look for a specific message. Previously only the FPGA was configured to look for it.
=> [test] Add pass/fail silicon param for ottf alert catch test

hw/top_earlgrey/chip_earlgrey_cw310.core, hw/top_earlgrey/chip_earlgrey_cw310_hyperdebug.core, hw/top_earlgrey/chip_earlgrey_cw340.core, hw/top_earlgrey/dv/verilator/chip_sim.core, hw/top_englishbreakfast/chip_englishbreakfast_cw305.core, hw/top_englishbreakfast/chip_englishbreakfast_verilator.core, hw/top_englishbreakfast/top_englishbreakfast.core
PRIM_DEFAULT_IMPL is only used in TB code now. Remove those fusesoc parameters from all RTL cores.
=> [corefiles] Remove PRIM_DEFAULT_IMPL from tops's corefiles

hw/top_darjeeling/BUILD
Move doc_files target before sim_dv targets, this make the BUILD file easier to compare with Earlgrey one.
=> [hw,darjeeling] Move doc_files target

rules/opentitan/sim_verilator.bzl
For Darjeeling exec_env, the "flash" is actually a RAM. This commit forces generation of the proper VMEM for Darjeeling RAM.
=> [rules,verilator] Add support for loading Darjeeling CTN RAM

sw/device/lib/base/hardened_memory.c, sw/device/lib/crypto/drivers/otbn.c
As `random_order_len()` simply returns the number of iterations, directly use the length argument of the function we are in.
Although the compiler anyways does this optimization, this change makes reading the code easier.
=> [crypto] Simplify `hardened_memory` and `otbn_dmem_write` functions

hw/ip/otp_ctrl/data/earlgrey_skus/sival/keys/BUILD, rules/opentitan/keyutils.bzl, rules/signing.bzl, sw/device/silicon_creator/rom_ext/sival/keys/BUILD
Since all key definitions have migrated to keyset, we can remove the
starlark rules definitions for key_{ecdsa,sphincsplus} as well as their
associated providers.
=> [signing] Remove the key_{ecdsa, sphincsplus} rules

sw/device/tests/penetrationtests/firmware/BUILD, sw/device/tests/penetrationtests/pentest.bzl
The fpga_cw340_rom_ext targets include an RMA lifecycle test target for the CW340 FPGA which allows for GDB testing.
=> [pentest] Add fpga_cw340_rom_ext targets for pentest

toolchain/BUILD
This flag is implicitly added when the toolchain is in "RISCVToolChain" mode (distinct from Baremetal mode) [^1] which is enabled if `crt0.o` is included in the toolchain [^2].
This may change in future builds of the toolchain, so we want to make this flag explicit now.
The hash of the ROM and ROM_EXT ELFs are unchanged with this commit, so I think there are no functional changes.
[^1]: https://github.com/llvm/llvm-project/blob/185b81e034ba60081023b6e59504dfffb560f3e3/clang/lib/Driver/ToolChains/RISCVToolchain.cpp#L166
[^2]: https://github.com/llvm/llvm-project/blob/e9f3be63d3928b24f3667d8aaadfbee9d325015f/clang/lib/Driver/ToolChains/BareMetal.cpp#L151
=> [bazel] Enable `--discard-locals` explicitly for linker

sw/device/lib/crypto/impl/ecc/p384.c, sw/otbn/crypto/p384_isoncurve.s, sw/otbn/crypto/p384_isoncurve_proj.s
The error reported in case of the is on curve check should only be an input error when the initial public key check is executed. After the initial check, the is on curve check would only return an error in case of an FI attack. In that case we should not report the error as a user error.
=> [sw,cryptolib] Only return input errors on user errors
