- sw/otbn/code-snippets/modexp.S
Document modexp otbn assembly code
This finishes #2908
> [otbn] document/comment modexp otbn assembly lib

- apt-requirements.txt
- doc/ug/install_instructions/index.md
- tool_requirements.py
- util/build_docs.py
- util/container/Dockerfile
- util/container/README.md
Before, we didn't explicitly list our system requirements in a 
distribution-agnostic way. Instead, we provided a list of packages and a 
reference distribution (Ubuntu 16.04). Users of other distributions then 
had to either try, or manully cross-check if their setup works as expected.
With this change the documentation describes better what packages are 
required, and which version is required. This commit is meant to be a 
clarification without changing the status quo.
Notes:
* The list of package dependencies and their versions isn't bullet-proof,
as packages can change behavior even in-between minor
versions (if they use semantic versioning at all). The only way to be
sure that a distribution works is testing it. We currently do all our
tests on Ubuntu 16.04, hence we call this the …
> [doc] Clarify our system and software requirements

- hw/ip/otp_ctrl/data/otp_ctrl.prj.hjson
> [otp_ctrl] Move into L1 stage

- hw/ip/otp_ctrl/rtl/otp_ctrl_scrmbl.sv
- hw/ip/prim/doc/prim_present.md
- hw/ip/prim/dv/prim_present/tb/prim_present_tb.sv
- hw/ip/prim/lint/prim.waiver
- hw/ip/prim/rtl/prim_cipher_pkg.sv
- hw/ip/prim/rtl/prim_present.sv
> [prim_present/otp_ctrl] Add round index state IOs to primitive

- hw/ip/kmac/doc/checklist.md
This commit is to add checklist for KMAC HWIP.
> [kmac] Checklist (D0/V0)

- hw/ip/aes/rtl/aes_core.sv
@msfschaffner could you please cross-check that this indeed fixes the error in AscentLint?
> [aes] Fix lint error

- hw/ip/prim/util/sparse-fsm-encode.py
Added some more error and help messages for user guidance.
Also, the script disallows all-zero and all-one encodings now.
> [sparse-fsm-encode] Expand error and help messages

- hw/ip/prim/util/sparse-fsm-encode.py
This adds support for generating C enums to the sparse encoder script.
We intend to use this when hardening the software we're writing in C,
including in particular the Mask ROM.
The script has not been improved much, as the intention is this is run
once for a specific enum, and the result is copied into a C file and
modified, rather than the script producing a perfect enum when run.
> [util] Add C Enum Support to sparse-fsm-encode.py

- hw/ip/otbn/rtl/otbn_alu_bignum.sv
> [otbn] Write flags on logical operations

- azure-pipelines.yml
- ci/install-package-dependencies.yml
- ci/run-riscv-compliance.yml
- doc/ug/install_instructions/index.md
- site/docs/builder.Dockerfile
- tool_requirements.py
- util/container/Dockerfile
- util/container/README.md
Require at least Ubuntu 18.04, or another distribution which provides components which are similar to the ones in Ubuntu 18.04.
Fixes #3664
> Use Ubuntu 18.04

- doc/rm/device_interface_functions.md
- doc/security/specs/attestation/_index.md
- doc/security/specs/device_life_cycle/_index.md
- doc/security/specs/identities_and_root_keys/_index.md
Signed-off-by: Scott Johnson <scottdj@google.com>
I noticed a few non-ASCII characters as I was doing another PR, created this one to clean up just in case.
> [doc] cleanup non-ASCII

- hw/ip/entropy_src/doc/_index.md
- hw/ip/entropy_src/entropy_src.core
- hw/ip/entropy_src/rtl/entropy_src.sv
- hw/ip/entropy_src/rtl/entropy_src_ack_sm.sv
- hw/ip/entropy_src/rtl/entropy_src_adaptp_ht.sv
- hw/ip/entropy_src/rtl/entropy_src_bucket_ht.sv
- hw/ip/entropy_src/rtl/entropy_src_core.sv
- hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
- hw/ip/entropy_src/rtl/entropy_src_markov_ht.sv
- hw/ip/entropy_src/rtl/entropy_src_repcnt_ht.sv
- hw/ip/entropy_src/rtl/entropy_src_watermark_reg.sv
- hw/ip/prim/rtl/prim_packer_fifo.sv
There is an rtl fix to allow the sanity test to run.
There are lint and style changes added in several files.
The request/ack state machine was added to insure proper bus timing.
> [entropy_src/rtl] fix for dv sanity test

- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_sanity_vseq.sv
- hw/ip/entropy_src/dv/tb/tb.sv
Removed dependencies on PR #3764 (entropy_src rtl changes)
> Dv sanity fixes

- sw/device/lib/dif/dif_alert_handler.c
- sw/device/lib/dif/dif_alert_handler.h
Unit tests coming soon, ~~probably as part of this PR.~~
> [dif] Implement DIFs for alert_handler

- hw/ip/otp_ctrl/dv/env/otp_ctrl_env.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cfg.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_sanity_vseq.sv
- hw/ip/otp_ctrl/dv/tb.sv
This PR supports OTP sanity sequence. This PR covers all the sequence
for DAI interface.
There will be a following PR that supports exercising all interfaces
within OTP.
> [dv/otp_ctrl] initial commit for OTP sanity sequence

- hw/ip/prim/rtl/prim_assert.sv
> [prim_assert] Fixed non-UVM part of `ASSERT_ERROR

- sw/device/tests/dif/dif_rstmgr_unittest.cc
- sw/device/tests/dif/meson.build
[sw, dif_rstmgr] Add DIF Reset Manager unittests
Related to #3454 .
> [sw, dif_rstmgr] Add DIF Reset Manager unittests

- hw/ip/otbn/dv/model/otbn_core_model.sv
VCS correctly complains if you compare a chandle with zero or assign
zero to it (this should use null instead). It looks like Verilator is
doing the wrong thing, so I've filed an upstream issue here: [1].
More confusingly, VCS also complains if you call a method on a string
parameter. I'm not sure whether that's implied by the spec, but
there's an easy solution here: I just want to know whether a string is
empty, so can compare with "" rather than checking that its length is
zero.
[1] https://github.com/verilator/verilator/issues/2602
Note that we need to do some more splitting up of the memutil code before we can actually build this with VCS. I've got that work locally, but this change is independent, so I'm pushing it up first.
> [otbn] Make otbn_core_model compilable with VCS

- sw/device/lib/dif/dif_alert_handler.c
- sw/device/lib/dif/dif_alert_handler.h
- sw/device/tests/dif/dif_alert_handler_unittest.cc
- sw/device/tests/dif/meson.build
Still pending >16 alert support, I suspect that will be its own PR.
> [dif] Add tests for dif_alert_handler.h

- hw/dv/sv/push_pull_agent/push_pull_device_driver.sv
- hw/dv/sv/push_pull_agent/push_pull_host_driver.sv
- hw/dv/sv/push_pull_agent/push_pull_if.sv
Created push_pull_if data_int field
> Pp agent fix2

- hw/ip/otp_ctrl/dv/env/otp_ctrl_env.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cfg.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_virtual_sequencer.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_sanity_vseq.sv
- hw/ip/otp_ctrl/dv/tb.sv
This PR adds the two other key interfaces - flash and otbn using push
pull agents
> [dv/otp-ctrl] add flash and otbn using push-pull agents

- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_reg_top.sv
- hw/ip/prim_generic/prim_generic_otp.core
- hw/ip/prim_generic/rtl/prim_generic_otp.sv
> [prim_otp] Add TL-UL regfile for testing (sim only)

- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/rtl/otp_ctrl_reg_top.sv
> [otp_ctrl] protect SW_CFG lock regs with DIRECT_ACCESS_REGWEN

- hw/ip/entropy_src/dv/env/entropy_src_env.core
- hw/ip/entropy_src/dv/env/entropy_src_env.sv
- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
- hw/ip/entropy_src/dv/tb/tb.sv
- hw/ip/entropy_src/rtl/entropy_src_pkg.sv
> [entropy_src/dv] adding push_pull_agents to env

- doc/security/specs/device_life_cycle/_index.md
> [doc] Fix cdgori username

- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl
> [otp_ctrl] Update the exclusion tags for CSR tests

- hw/Makefile
- hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
This PR has two commits:
1. Add entropy_src to Make flow
2. Regenerate RTL files for entropy_src
> [entropy_src] regression fix and re-generate RTL

- hw/dv/sv/cip_lib/cip_base_vseq.sv
When mem write is aborted, shouldn't update the address to the queue
which indicates write is done successfully
Add `tl_access_w_abort` to output status, rather than having `tl_access`
to output status as status isn't needed for most of cases
> [dv/common] Fix mem failure

- hw/top_earlgrey/rtl/top_earlgrey_verilator.sv
The `sw_test_status_if` was originally bound to the `sim_sram_if`
directly to probe the signals maintained there.
The SV bind keyword unfortunately does not play nice when tracing is
enabled (results in seg fault).
This fixes #3951 by instantiating `sw_test_status_if` instead and
manually connecting the signals from `sim_sram_if` instance.
> [verilator] Change how sw_test_status_if is instanced

- hw/ip/otbn/dv/otbnsim/stepped.py
Two small improvements to the ISS to make debugging code running in the stepped ISS slightly nicer.
* End simulation less verbose on keyboard interrupt
* Give more information in invalid memory read
> [otbn] Small ISS improvements

- hw/ip/pattgen/data/pattgen.prj.hjson
- hw/ip/pattgen/doc/checklist.md
> Pattgen D1 review

- .gitignore
Add `.vscode` directory to ignore list
> Add vscode to .gitignore

- hw/top_earlgrey/syn/asic.constraints.sdc
> Sdc update

- hw/ip/csrng/data/csrng_testplan.hjson
- hw/ip/csrng/doc/checklist.md
- hw/ip/csrng/doc/dv_plan/index.md
- hw/ip/csrng/dv/csrng_sim.core
- hw/ip/csrng/dv/csrng_sim_cfg.hjson
- hw/ip/csrng/dv/env/csrng_env.core
- hw/ip/csrng/dv/env/csrng_env.sv
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_env_cov.sv
- hw/ip/csrng/dv/env/csrng_env_pkg.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/csrng_virtual_sequencer.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_common_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_sanity_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_vseq_list.sv
- hw/ip/csrng/dv/sva/csrng_bind.sv
- hw/ip/csrng/dv/sva/csrng_sva.core
- hw/ip/csrng/dv/tb.sv
- hw/ip/csrng/dv/tests/csrng_base_test.sv
- hw/ip/csrng/dv/tests/csrng_test.core
- hw/ip/csrng/dv/tests/csrng_test_pkg.sv
- hw/ip/entropy_src/dv/env/entropy_src_env.core
- util/uvmdvgen/sim_cfg.hjson.tpl
> [csrng/dv] Initial dv environment

- hw/top_earlgrey/data/top_earlgrey.h.tpl
- hw/top_earlgrey/sw/autogen/top_earlgrey.h
- util/topgen/c.py
> [top] Generate reset request headers

- sw/otbn/code-snippets/modexp.s
- sw/otbn/code-snippets/rsa_1024_dec_test.s
- sw/otbn/code-snippets/rsa_1024_enc_test.s
Two small fixes that actually were supposed to be part of the PR for the self-contained RSA tests but apparently I missed.
> [otbn] fix self-contained RSA tests

- hw/dv/tools/dvsim/vcs.hjson
- hw/ip/aes/dv/env/aes_seq_item.sv
Make the VCS more strict, so that we can avoid seeing this kind of issue #3968
> [dv/common] Upgrade some VCS warnings to errors

- sw/otbn/code-snippets/modexp.s
- sw/otbn/code-snippets/rsa_1024_dec_test.s
- sw/otbn/code-snippets/rsa_1024_enc_test.s
This implements the improvements for the assembly of modexp as described in  #3776
> [otbn] some improvements for modexp assembly

- hw/ip/otbn/rtl/otbn_controller.sv
- hw/ip/otbn/rtl/otbn_decoder.sv
This is related to lowRISC/OpenTitan#3773.
> [otbn] Remove auto-inferred latch in controller

- hw/ip/otbn/dv/model/otbn_core_model.sv
- hw/ip/otbn/dv/model/otbn_rf_snooper_if.sv
- hw/ip/otbn/dv/model/otbn_stack_snooper_if.sv
- hw/ip/otbn/otbn.core
Looks like we're now running Verible in CI and it's catching a couple of silly problems.
> [otbn] Minor lint fixes for the OTBN model

- hw/ip/keymgr/rtl/keymgr.sv
> [keymgr] Add known asserts

- hw/formal/tools/jaspergold/fpv.tcl
Add a few comments to improve the JG tcl script:
1. Add a -enable_sva_isunknown switch to support isunknown checks in FPV
2. Add a timeout for compile time
3. Add a timeout for coverage collection time
> [fpv] JG script improvement

- hw/ip/kmac/data/kmac.hjson
- hw/ip/kmac/kmac.core
- hw/ip/kmac/lint/kmac.waiver
- hw/ip/kmac/lint/sha3.waiver
- hw/ip/kmac/rtl/keccak_2share.sv
- hw/ip/kmac/rtl/kmac.sv
- hw/ip/kmac/rtl/kmac_core.sv
- hw/ip/kmac/rtl/kmac_keymgr.sv
- hw/ip/kmac/rtl/kmac_reg_pkg.sv
- hw/ip/kmac/rtl/kmac_reg_top.sv
- hw/ip/kmac/rtl/sha3pad.sv
- hw/ip/prim/rtl/prim_packer.sv
- hw/ip/prim/rtl/prim_slicer.sv
Fix lint errors. This PR fixes lint errors that do not prevent synthesizing.
> [kmac] Fix Lint

- hw/ip/kmac/data/kmac.prj.hjson
- hw/ip/kmac/doc/checklist.md
As KMAC meets D1 checklist items, it is moved to D1 in this commit.
> [kmac] Reaching D1 stage.

- hw/ip/clkmgr/data/clkmgr.sv.tpl
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
> [clkmgr] Add asserts known

- hw/_index.md
- hw/ip/kmac/fpv/sha3pad_fpv.core
- hw/ip/padctrl/fpv/padctrl_fpv.core
- hw/ip/pinmux/fpv/pinmux_fpv.core
- hw/ip/prim/fpv/prim_alert_rxtx_async_fpv.core
- hw/ip/prim/fpv/prim_alert_rxtx_fpv.core
- hw/ip/prim/fpv/prim_arbiter_fixed_fpv.core
- hw/ip/prim/fpv/prim_arbiter_ppc_fpv.core
- hw/ip/prim/fpv/prim_arbiter_tree_fpv.core
- hw/ip/prim/fpv/prim_esc_rxtx_fpv.core
- hw/ip/prim/fpv/prim_fifo_sync_fpv.core
- hw/ip/prim/fpv/prim_keccak_fpv.core
- hw/ip/prim/fpv/prim_lfsr_fpv.core
- hw/ip/prim/fpv/prim_packer_fpv.core
- hw/ip/rv_plic/fpv/rv_plic_generic_fpv.core
- hw/top_earlgrey/ip/rv_plic/fpv/rv_plic_fpv.core
- hw/top_earlgrey/lint/top_earlgrey_fpv_lint_cfgs.hjson
- util/fpvgen/fusesoc.core.tpl
This PR adds lint checking for FPV testbench.
> [lint] Add lint checking to FPV tb

- sw/device/lib/dif/dif_otp_ctrl.c
- sw/device/lib/dif/dif_otp_ctrl.h
- sw/device/tests/dif/dif_otp_ctrl_unittest.cc
- sw/device/tests/dif/meson.build
~~Tests will go in a followup PR.~~ I lied this PR also contains tests woo!
> [dif/otp_ctrl] Implement DIFs for otp_ctrl

- hw/ip/keymgr/data/keymgr.prj.hjson
- hw/ip/keymgr/doc/checklist.md
> [keymgr] Move to D1 milestone

- hw/top_earlgrey/util/opentitan_earlgrey_flash_size_check.py
- hw/top_earlgrey/util/opentitan_earlgrey_flash_size_reduce.py
- meson.build
- sw/device/lib/flash_ctrl.c
- sw/device/lib/flash_ctrl.h
- sw/device/tests/flash_ctrl_test.c
Update fpga size reduce/check scripts for new flash templating.
Also update how size information is exposed in `flash_ctrl.c` to make things more self contained.
> [flash_ctrl] fpga flash shrink

- hw/ip/otbn/lint/otbn.vlt
- hw/ip/otbn/rtl/otbn_alu_base.sv
- hw/ip/otbn/rtl/otbn_alu_bignum.sv
- hw/ip/otbn/rtl/otbn_controller.sv
- hw/ip/otbn/rtl/otbn_core.sv
- hw/ip/otbn/rtl/otbn_decoder.sv
- hw/ip/otbn/rtl/otbn_instruction_fetch.sv
- hw/ip/otbn/rtl/otbn_loop_controller.sv
- hw/ip/otbn/rtl/otbn_lsu.sv
- hw/ip/otbn/rtl/otbn_pkg.sv
- hw/ip/otbn/rtl/otbn_stack.sv
This removes a catch-all lint waiver that was in place for early development and fixes the issues it was hiding. There's also a few small bug fixes.
> [OTBN] Lint and bug fixes

- hw/ip/otp_ctrl/data/otp_ctrl.prj.hjson
- hw/ip/otp_ctrl/doc/checklist.md
Update OTP testbench status to V1.
This PR is based on PR: https://github.com/lowRISC/opentitan/pull/3990 and https://github.com/lowRISC/opentitan/pull/3987
> [dv/otp] OTP V1 status

- util/reggen/uvm_reg.sv.tpl
Fixes #4058.
Fixes #1953.
And also update some indents
> [dv/common] Fix regwen issue

- doc/rm/c_cpp_coding_style.md
This came up in #3986 and is useful just to write down, given that mixing different approaches can be error-prone.
> [docs] Provide Guidance on Referring to Linker Symbols

- hw/ip/kmac/rtl/kmac_core.sv
- hw/ip/kmac/rtl/sha3pad.sv
While moving sha3.sv state to sha3_pkg, I didn't change sha3pkg.sv and
kmac_core.sv to have unique enum name for the internal state machine.
This commit is to make sha3pad, kmac_core state machine to have unique
name so that DC tool does not complain.
> [kmac] Fix Duplicated enum error

- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_sanity_vseq.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
> [otp_ctrl] Reverse bitslice assignment to the status register

- hw/dv/tools/dvsim/dsim.hjson
> [dv] Fix library paths for dsim

- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
- hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
- hw/dv/sv/dv_lib/dv_base_env_cfg.sv
- hw/ip/aes/dv/env/aes_scoreboard.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
- hw/ip/gpio/dv/env/gpio_scoreboard.sv
- hw/ip/hmac/dv/env/hmac_env.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_sanity_vseq.sv
- hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
- hw/ip/rv_timer/dv/env/rv_timer_scoreboard.sv
- hw/ip/spi_device/dv/env/spi_device_env_cfg.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
- hw/ip/uart/dv/env/uart_scoreboard.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- util/uvmdvgen/scoreboard.sv.tpl
- These address few of the suggestions made in #3971.
- It updates some of the dv_base_reg_block methods to be free from reg
map assumptions.
> [dv common] Minor enhancements to dv_reg_block

- doc/project/checklist.md
- hw/ip/aes/doc/checklist.md
- hw/ip/alert_handler/doc/checklist.md
- hw/ip/csrng/doc/checklist.md
- hw/ip/entropy_src/doc/checklist.md
- hw/ip/flash_ctrl/doc/checklist.md
- hw/ip/gpio/doc/checklist.md
- hw/ip/hmac/doc/checklist.md
- hw/ip/i2c/doc/checklist.md
- hw/ip/keymgr/doc/checklist.md
- hw/ip/kmac/doc/checklist.md
- hw/ip/otp_ctrl/doc/checklist.md
- hw/ip/padctrl/doc/checklist.md
- hw/ip/pattgen/doc/checklist.md
- hw/ip/pinmux/doc/checklist.md
- hw/ip/rv_plic/doc/checklist.md
- hw/ip/rv_timer/doc/checklist.md
- hw/ip/spi_device/doc/checklist.md
- hw/ip/sram_ctrl/doc/checklist.md
- hw/ip/uart/doc/checklist.md
- hw/ip/usbdev/doc/checklist.md
- hw/top_earlgrey/ip/xbar/doc/checklist.md
- util/uvmdvgen/checklist.md.tpl
Add lint requirements to FPV and DV V1 status checklist.
> [doc] Add lint requirements to V1 checklist

- hw/ip/keymgr/dv/env/keymgr_env.core
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_direct_to_disabled_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_op_at_wipe_state_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_vseq_list.sv
- hw/ip/keymgr/dv/keymgr_sim_cfg.hjson
Also add minor update for issuing random command before init
> [keymgr/dv] Add direct_to_disabled sequence

- hw/dv/sv/dv_lib/dv_base_scoreboard.sv
This avoids spurious (and confusing) error messages from the
scoreboard's check phase if the build phase failed. For example,
`cip_base_scoreboard`'s `check_phase` assumes that its `build_phase` has
run, and you get strange messages about using null FIFOs if it hasn't.
> [dv] Only check scoreboard from pre_abort if we were in run phase

- hw/dv/tools/vcs/xprop.cfg
- hw/ip/prim/dv/prim_lfsr/data/prim_lfsr_cover.cfg
- hw/ip/prim/dv/prim_lfsr/data/prim_lfsr_cover_assert.cfg
- hw/ip/prim/dv/prim_present/data/prim_present_cover.cfg
- util/lowrisc_misc-linters.lock.hjson
- util/lowrisc_misc-linters/licence-checker/README.md
- util/lowrisc_misc-linters/licence-checker/licence-checker.py
Instead of squeezing in #3921, I make a separate PR for license checker update
It contains 2 commits
1. Fix license header for some cfg files
2. Vendor in update from lowrisc_misc-linters
> Update license checker

- hw/ip/csrng/data/csrng_testplan.hjson
- hw/ip/keymgr/data/keymgr_testplan.hjson
- hw/ip/kmac/data/kmac_testplan.hjson
- hw/ip/usbdev/data/usbdev_testplan.hjson
- util/uvmdvgen/testplan.hjson.tpl
Thanks, Weicai, for spotting this in #4117.
> Fix typo in testplan template

- hw/ip/otbn/dv/uvm/env/otbn_env.core
- hw/ip/otbn/dv/uvm/env/otbn_env_pkg.sv
- hw/ip/otbn/dv/uvm/env/otbn_test_helpers.cc
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sanity_vseq.sv
It's a bit ridiculous how much code is needed for this (a combination
of problems: SV can't list directories plus there's no way to pass a
string back to SV and say "hey, you look after this memory now"), but
at least it seems to work now.
> [otbn] Pick a random binary in the UVM testbench

- hw/ip/otbn/util/rig/model.py
We'll need similar alignment checks on the wide side too. However,
`BN.LID` and `BN.SID` are more complicated: I'm not sure they'll be using
this function to pick targets, so am avoiding any clever generality
here for now.
> [otbn] Make sure sw/lw addresses are word-aligned in otbn-rig

- hw/ip/otbn/rtl/otbn_decoder.sv
> [otbn] Flags should be written for logical ops

- util/reggen/fpv_csr.sv.tpl
FPV regression found corner case where regen signal was updated during
TLUL write's data phase. Current assertion check regen at data phase,
but design check it during address phase.
This PR fix the assertion issue by split it into two assertions:
1. If regen is enabled, then check wr data is updated
2. If regen is not enabled, check wr data is stable
W1C register is still WIP with a TODO because they might be updated by
internal HW regs. I will clean them up together in a separate PR.
> [fpv] fix regen regression failure

- hw/ip/csrng/dv/env/csrng_env.sv
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_env_pkg.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/csrng_virtual_sequencer.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_sanity_vseq.sv
- hw/ip/csrng/dv/tb.sv
> [csrng/dv] dv environment modifications

- hw/ip/flash_ctrl/data/flash_ctrl.hjson
- hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl
- hw/ip/flash_ctrl/data/flash_ctrl_pkg.sv.tpl
- hw/ip/flash_ctrl/doc/_index.md
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_vseq.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_prog.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_pkg.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_pkg.sv
- sw/device/lib/flash_ctrl.c
- util/topgen/validate.py
Add program resolution support.
This means a flash program beat can only be up to a certain boundary / size.
Unfortunately all the software and dv changes had to be in this PR otherwise CI won't work.
> [flash_ctrl] Add flash_ctrl program resolution / window

- hw/ip/keymgr/keymgr.core
- hw/ip/keymgr/lint/keymgr.waiver
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_kmac_if.sv
- hw/ip/keymgr/rtl/keymgr_sideload_key.sv
- hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
- Obey valid/ready handshake even during error case when sending random data
- Re-organize each module to contain its own lfsr_en
> [keymgr] Minor keymgr fixes

- hw/ip/flash_ctrl/rtl/flash_phy_core.sv
- hw/ip/flash_ctrl/rtl/flash_phy_prog.sv
- hw/ip/flash_ctrl/rtl/flash_phy_rd.sv
- hw/ip/prim_generic/rtl/prim_generic_flash.sv
- Change behavior to valid / ready / dvalid, although the names are kept as req / ack / done for integration purposes.
- commands are accepted on valid / ready (req / ack) handshake, whereas transaction completion is indicated via dvalid (done)
- Update program / read to support new interface
> [flash] Update flash wrapper behavior. 

- hw/ip/keymgr/keymgr.core
- hw/ip/prim/prim_lfsr.core
> [keymgr/prim_lfsr] Correct minor errors in core files

- hw/ip/clkmgr/data/clkmgr.prj.hjson
- hw/ip/clkmgr/doc/_index.md
- hw/ip/clkmgr/doc/checklist.md
> [clkmgr] Clkmgr D1 paperwork

- hw/ip/otbn/doc/checklist.md
This updates the checklist for what's been done so far: there are
still some jobs to do.
> [otbn] Documentation for existing V1 progress

- hw/ip/flash_ctrl/flash_ctrl.core
- hw/ip/flash_ctrl/rtl/flash_phy_core.sv
- hw/ip/flash_ctrl/rtl/flash_phy_erase.sv
Erase operation interfacing is now consistent with read and program
> [flash_ctrl] Add flash_phy_erase for consistency

- sw/device/lib/dif/dif_otp_ctrl.md
> [dif/otp_ctrl] Bring otp_ctrl to S1

- hw/ip/otp_ctrl/data/otp_ctrl.prj.hjson
This should have been caught by #4216 but I missed it before I hit merge.
> [sw] Update OTP Status

- hw/ip/prim/util/sparse-fsm-encode.py
This PR contains two changes:
- One to avoid using complementary encodings
- One to change how we represent these enums using Rust types.
<details><summary>Example <code>--language=rust</code> Output</summary>
```
------------------------------------------------
| COPY PASTE THE CODE TEMPLATE BELOW INTO YOUR |
| RUST FILE, INLUDING THE COMMENT IN ORDER TO  |
| EASE AUDITABILITY AND REPRODUCIBILITY.       |
------------------------------------------------
///```text
/// Encoding generated with
/// $ ./sparse-fsm-encode.py -d 10 -m 3 -n 16 \
///     -s 2855134562 --language=rust
///
/// Hamming distance histogram:
///
///  0: --
///  1: --
///  2: --
///  3: --
///  4: --
///  5: --
///  6: --
///  7: --
///  8: --
///  9: --
/// 10: |||||||||||||||||||| (100.00%)
/// 11: --
/// 12: --
/// …
> [sparse-fsm-encode] Improvements for Software

- hw/dv/tools/dvsim/vcs.hjson
Change build opt CFLAGS from `--std=c99 to `--std=c++11`
> [dv] Fix VCS compile error

- hw/ip/otp_ctrl/rtl/otp_ctrl_scrmbl.sv
- hw/ip/prim/doc/prim_present.md
- hw/ip/prim/rtl/prim_present.sv
> [prim_present/otp_ctrl] Add support for iterative full-round PRESENT

- util/build_docs.py
Tested and this works on my own machine - I'm not sure who else is using a Mac, but the existing behaviour of `--force-global` was driving me mad, and this is the simpler fix.
> [docs] Add Local Hugo Support for macOS

- azure-pipelines.yml
- ci/run-riscv-compliance.yml
- doc/ug/install_instructions/index.md
- util/get-toolchain.py
See first commit for the list of changes. The second commit just performs a lint cleanup. 
- Fixes #4219
> [toolchain] Added `--dest-dir` switch

- hw/dv/sv/dv_utils/dv_macros.svh
- hw/dv/sv/dv_utils/dv_utils.core
- hw/dv/sv/dv_utils/dv_utils_pkg.sv
- hw/dv/sv/dv_utils/dv_vif_wrap.sv
- hw/dv/tools/dvsim/vcs.hjson
- hw/dv/tools/dvsim/xcelium.hjson
- hw/ip/uart/dv/cov/uart_core_cov_if.sv
- hw/ip/uart/dv/cov/uart_cov.core
- hw/ip/uart/dv/cov/uart_cov_bind.sv
- hw/ip/uart/dv/cov/uart_cov_if.sv
- hw/ip/uart/dv/uart_sim.core
- hw/ip/uart/dv/uart_sim_cfg.hjson
- Implements functional coverage for UART in an interface
- Proof of concept to drive a designer-led functional coverage
implementation methodology
- See link below for more details:
https://docs.google.com/presentation/d/1rUFpWzktORuBZNyG6eSG68kWxEWmxMkMaWdSCadhbQI
This PR is only meant to show how this approach works. How to write covergroups in various different way can be looked up from the LRM (that is not the goal of this PR). The sample covergroup will be removed and replaced with useful covergroups later. 
> [cov methodology] Functional coverage prototype

- hw/ip/csrng/rtl/csrng_pkg.sv
- hw/ip/edn/data/edn_testplan.hjson
- hw/ip/edn/doc/checklist.md
- hw/ip/edn/doc/dv_plan/index.md
- hw/ip/edn/dv/edn_sim.core
- hw/ip/edn/dv/edn_sim_cfg.hjson
- hw/ip/edn/dv/env/edn_env.core
- hw/ip/edn/dv/env/edn_env.sv
- hw/ip/edn/dv/env/edn_env_cfg.sv
- hw/ip/edn/dv/env/edn_env_cov.sv
- hw/ip/edn/dv/env/edn_env_pkg.sv
- hw/ip/edn/dv/env/edn_scoreboard.sv
- hw/ip/edn/dv/env/edn_virtual_sequencer.sv
- hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_common_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_sanity_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_vseq_list.sv
- hw/ip/edn/dv/sva/edn_bind.sv
- hw/ip/edn/dv/sva/edn_sva.core
- hw/ip/edn/dv/tb.sv
- hw/ip/edn/dv/tests/edn_base_test.sv
- hw/ip/edn/dv/tests/edn_test.core
- hw/ip/edn/dv/tests/edn_test_pkg.sv
- hw/ip/edn/rtl/edn_pkg.sv
- hw/ip/entropy_src/rtl/entropy_src_pkg.sv
- hw/top_earlgrey/lint/top_earlgrey_dv_lint_cfgs.hjson
> [edn/dv] Initial dv environment

- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_sanity_vseq.sv
> [csrng/dv] Removed ack register to match latest rtl

- hw/ip/entropy_src/dv/tb/tb.sv
- hw/ip/otbn/dv/uvm/env/otbn_env_cfg.sv
- hw/ip/otbn/dv/uvm/env/otbn_env_pkg.sv
- hw/ip/otbn/dv/uvm/tb.sv
- hw/ip/otp_ctrl/dv/tb.sv
These TBs were added before I merged the PR that created this macro
And they were not generated by the latest uvmdvgen
> [dv] Use macro for alert connection in tb

- util/otbn_build.py
This option is currently unused.
> [otbn] Add the option to pass a linker script to otbn_build

- hw/ip/otbn/doc/_index.md
- hw/ip/otbn/doc/isa.md
- hw/ip/otbn/util/yaml_to_doc.py
There's a little bit of extra text at the top of the new `isa.md`, but this is intended to be a pretty trivial "split up the giant file" commit.
> [otbn] Split out ISA into a separate document

- hw/formal/tools/dvsim/common_fpv_cfg.hjson
- hw/formal/tools/jaspergold/parse-fpv-report.py
The new jaspergold version updated coverage txt file display.
This PR updates the coverage parsing script to reflect the change.
> [fpv] update jaspergold parse script

- hw/ip/keymgr/data/keymgr_testplan.hjson
Add preliminary testplan, will update when design reaches D1
> [keymgr/dv] Add testplan

- hw/dv/tools/dvsim/xcelium.hjson
> [dv/keymgr] Disable some warnings from xcelium

- hw/dv/sv/cip_lib/cip_base_vseq.sv
In current nightly regression, the `chip_same_csr_outstanding` has
timeout issue. The reason is because that looping through each csr
within the chip, we issue a reset to make sure current csr value does
not affect others.
However, chip level dut_init takes a long time, thus caused the timeout.
The solution here is to: only issue reset after each iteration, or after
written enable_register.(same_csr_outstanding_access uses tl_access to
read and write rather than UVM build-in RAL method. So it could not
automatically predict enable-regs' behavior)
This PR also removes a little bit redundant logic from the sequence
> [dv/top] fix same_csr_outstanding timeout issue

- sw/device/mask_rom/docs/index.md
- sw/device/mask_rom/docs/module.md.tpl
This is a minor consolidation, so we can start integrating the other Mask ROM documents into a single place.
> [sw,docs] Mask ROM Docs

- doc/ug/dv_methodology/index.md
> [dv] Add UNR in DV methodology

- hw/ip/otbn/doc/_index.md
- hw/ip/otbn/dv/otbnsim/sim/csr.py
- hw/ip/otbn/dv/smoke/smoke_test.s
- hw/ip/otbn/rtl/otbn_controller.sv
- hw/ip/otbn/rtl/otbn_pkg.sv
> [otbn] Add seperate FG0 & FG1 CSRs

- hw/dv/tools/dvsim/sim.mk
- hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson
- util/dvsim/Deploy.py
- util/dvsim/Modes.py
- util/dvsim/SimCfg.py
The first commit enhances DVSim to be able to add pre/post build and run commands art various levels. 
The second updates OTBN DV to add the binary generation as a pre-run step.
> [dvsim, OTBN] Ability to execute arbitrary pre/post build/run commands & working OTBN smoke test 

- hw/ip/edn/dv/env/edn_env.sv
- hw/ip/edn/dv/env/edn_env_cfg.sv
- hw/ip/edn/dv/env/edn_scoreboard.sv
- hw/ip/edn/dv/env/edn_virtual_sequencer.sv
- hw/ip/edn/dv/tb.sv
> [edn/dv] csrng_agent is only genbits, not cmd

- hw/ip/csrng/dv/env/csrng_env.sv
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/csrng_virtual_sequencer.sv
- hw/ip/csrng/dv/tb.sv
> [csrng/dv] push_pull_agent parameter .DataWidth->.HostDataWidth

- util/reggen/data.py
- util/reggen/gen_dv.py
- util/reggen/uvm_reg.sv.tpl
- util/topgen.py
First commit is just to fix style error by running lintpy. can skip reviewing it
Send commit is to address #4211 and #2482
> [dv/common] Update ral generation to support IP with multi-instance

- hw/ip/lc_ctrl/data/lc_ctrl_testplan.hjson
- hw/ip/lc_ctrl/doc/checklist.md
- hw/ip/lc_ctrl/doc/dv_plan/index.md
- hw/ip/lc_ctrl/dv/env/lc_ctrl_env.core
- hw/ip/lc_ctrl/dv/env/lc_ctrl_env.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_env_cfg.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_env_cov.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_env_pkg.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_if.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_virtual_sequencer.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_base_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_common_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_smoke_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_vseq_list.sv
- hw/ip/lc_ctrl/dv/lc_ctrl_sim.core
- hw/ip/lc_ctrl/dv/lc_ctrl_sim_cfg.hjson
- hw/ip/lc_ctrl/dv/sva/lc_ctrl_bind.sv
- hw/ip/lc_ctrl/dv/sva/lc_ctrl_sva.core
- hw/ip/lc_ctrl/dv/tb.sv
- hw/ip/lc_ctrl/dv/tests/lc_ctrl_base_test.sv
- hw/ip/lc_ctrl/dv/tests/lc_ctrl_test.core
- hw/ip/lc_ctrl/dv/tests/lc_ctrl_test_pkg.sv
- hw/top_earlgrey/lint/top_earlgrey_dv_lint_cfgs.hjson
- util/build_docs.py
This PR:
1. Add a dv testbench for LC using uvmdvgen.
2. Add pins to trigger LC init.
3. Add LC testplan in build_doc.py
> [dv/lc_ctrl] initial dv testbench for LC

- hw/ip/kmac/doc/checklist.md
- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
1) Update V1 checklist with current progress.
> [kmac/dv] update checklist

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/doc/_index.md
- hw/ip/entropy_src/rtl/entropy_src.sv
- hw/ip/entropy_src/rtl/entropy_src_ack_sm.sv
- hw/ip/entropy_src/rtl/entropy_src_adaptp_ht.sv
- hw/ip/entropy_src/rtl/entropy_src_bucket_ht.sv
- hw/ip/entropy_src/rtl/entropy_src_cntr_reg.sv
- hw/ip/entropy_src/rtl/entropy_src_core.sv
- hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
- hw/ip/entropy_src/rtl/entropy_src_markov_ht.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
- hw/ip/entropy_src/rtl/entropy_src_repcnt_ht.sv
- hw/ip/entropy_src/rtl/entropy_src_watermark_reg.sv
Added ERR_CODE register and supporting logic.
General style cleanup.
Doc signal typo fixed.
> [entropy_src/rtl] fixes to address issue #3511

- hw/ip/lc_ctrl/rtl/lc_ctrl.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv
> [lc_ctrl] Fix transition command error checking

- hw/ip/csrng/rtl/csrng_core.sv
> [csrng/rtl] fix for csrng smoke test

- hw/ip/lc_ctrl/data/lc_ctrl.hjson
- hw/ip/lc_ctrl/rtl/lc_ctrl.sv
- util/reggen/validate.py
This came up in https://github.com/lowRISC/opentitan/pull/4242#discussion_r528905590.
> [lc_ctrl] Update transition interface regwen behavior

- hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson
This was almost there, but there were a couple of paths that weren't being set properly.
> [otbn] Get dvsim + OTBN dv code working properly

- hw/dv/sv/cip_lib/cip_base_vseq__tl_errors.svh
- hw/dv/sv/dv_base_reg/dv_base_reg_block.sv
> [dv] Fix tl_err due to no unmapped address

- hw/dv/tools/dvsim/common_sim_cfg.hjson
- hw/dv/tools/dvsim/sim.mk
- hw/dv/tools/dvsim/vcs.hjson
- hw/dv/tools/vcs/unr.cfg
- hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- util/dvsim/Deploy.py
- util/dvsim/SimCfg.py
- util/dvsim/dvsim.py
Set up VCS UNR flow. For detail refer to [slides](https://docs.google.com/presentation/d/13FwwSeBaxtHZkLMmW3TI0YGO93_BTPZZFnIpX2kQhHI/edit#slide=id.p)
Remaining TODO
1. Some module doesn’t use tb.dut as dut hierarchy, may need separate
cfg file
2. Make sure all IPs pass with UNR flow (need solution for issue 3)
3. Document the flow
4. set up UNR flow with xcelium
> [dv/common] VCS UNR flow

- hw/Makefile
- hw/ip/csrng/rtl/csrng_reg_pkg.sv
- hw/ip/csrng/rtl/csrng_reg_top.sv
- hw/ip/edn/rtl/edn_reg_pkg.sv
- hw/ip/edn/rtl/edn_reg_top.sv
> [csrng/edn] add entropy IP to hw/Makefile

- hw/ip/csrng/csrng.core
- hw/ip/csrng/rtl/csrng.sv
- hw/ip/csrng/rtl/csrng_core.sv
> [csrng/rtl] assert support added

- hw/ip/aes/dv/aes_sim_cfg.hjson
- hw/ip/aes/dv/env/aes_env.core
- hw/ip/aes/dv/env/aes_env_cfg.sv
- hw/ip/aes/dv/env/aes_env_pkg.sv
- hw/ip/aes/dv/env/aes_message_item.sv
- hw/ip/aes/dv/env/aes_scoreboard.sv
- hw/ip/aes/dv/env/aes_seq_item.sv
- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_clear_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_vseq_list.sv
- hw/ip/aes/dv/tests/aes_clear_test.sv
- hw/ip/aes/dv/tests/aes_test.core
- hw/ip/aes/dv/tests/aes_test_pkg.sv
added clear reg test case to test this
cleaned up aes_base_vseq
converted error_types and cfg_error_type into structs
Signed-off-by: Rasmus Madsen <rasmus.madsen@wdc.com>
> [aes/dv] created functionality to verify the clear functionality 

- sw/device/rom_exts/rom_ext_manifest_parser.h
Minor grammatical fixes in descriptions...
> [sw, rom_ext] Minor grammatical fixes in descriptions

- sw/device/rom_exts/manifest.hjson
- sw/device/rom_exts/manifest.md
- sw/device/rom_exts/rom_ext_manifest_parser.c
- sw/device/rom_exts/rom_ext_manifest_parser.h
- sw/device/tests/rom_ext/rom_ext_parser_unittest.cc
Just some nits regarding RSA terminology
> [rom_ext] Update RSA terms in rom_ext mainfest doc

- hw/ip/otp_ctrl/rtl/otp_ctrl_dai.sv
This adds a second read access check to the DAI FSM as discussed in the consultancy meeting.
Note that this check is continuously performed as long as the OTP controller waits for a response from the macro.
> [otp_ctrl] Add second read access check to DAI FSM

- hw/ip/edn/edn.core
- hw/ip/edn/rtl/edn.sv
> [edn/rtl] asserts added for edn outputs

- hw/ip/entropy_src/entropy_src.core
- hw/ip/entropy_src/rtl/entropy_src.sv
Fixed up asserts by adding the include statement.
> [entropy_src/rtl] asserts expanded

- hw/ip/otbn/rtl/otbn_controller.sv
> [otbn] Factor insn_valid into base RF read enables

- hw/ip/entropy_src/data/entropy_src.prj.hjson
- hw/ip/entropy_src/doc/checklist.md
> [entropy_src/checklist] D1 signoff for entropy_src

- hw/ip/edn/rtl/edn_core.sv
> [edn/rtl] fix for ascentlint lint

- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_kmac_if.sv
> [keymgr] bug fixes

- hw/ip/edn/doc/edn_top_diag.svg
> [edn/doc] topology diagram to show all endpoint buses as 32b

- sw/device/sca/aes_serial/aes_serial.c
This PR reorders the execution of some operations when performing SCA captures (e.g. first provide input data, then start wakeup timer), and it reduces the sleep time of Ibex from 5000 to 200 clock cycles. This should slightly improve capture performance.
> [aes_serial] Change order of operations, reduce sleep time

- hw/dv/tools/dvsim/common_sim_cfg.hjson
> [dvsim] Add support for UVM_FULL over cmd line

- hw/ip/edn/data/edn.prj.hjson
- hw/ip/edn/doc/checklist.md
> [edn/checklist] D1 signoff for EDN

- hw/ip/otbn/dv/otbnsim/sim/sim.py
This makes debugging things much easier.
> [otbn] Print PC as part of trace in standalone.py

- doc/security/_index.md
- doc/security/specs/_index.md
- doc/security/specs/attestation/_index.md
- doc/security/specs/device_life_cycle/_index.md
- doc/security/specs/device_provisioning/index.md
- doc/security/specs/firmware_update/index.md
- doc/security/specs/identities_and_root_keys/_index.md
- doc/security/specs/ownership_transfer/_index.md
- doc/security/specs/secure_boot/index.md
Content presentation updates
*   Remove contributors sections from spec docs.
*   Remove doc versions from spec docs.
*   Update spec section title to OpenTitan Security Model Specification
> [docs/security] CSM doc updates

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/ip/prim/util/gen-lfsr-seed.py
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey_rnd_cnst_pkg.sv.tpl
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv
Address #4292 and also connect random compile time constants.
> [keymgr] bug fix and updates

- hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv
Signed-off-by: Arnon Sharlin <arnon.sharlin@opentitan.org>
> [ast] fixed nested pragmas

- util/dvsim/dvsim.py
> [dvsim] Add alias for --run-only

- hw/dv/sv/dv_base_reg/csr_excl_item.sv
Address Questa warning for #4377
Remove unused var for #4398
> [dv] Fix Questa warning and remove unused var

- hw/data/common_project_cfg.hjson
- util/dvsim/FlowCfg.py
- util/dvsim/FpvCfg.py
- util/dvsim/LintCfg.py
- util/dvsim/OneShotCfg.py
- util/dvsim/SimCfg.py
- util/dvsim/SynCfg.py
- util/dvsim/dvsim.py
The first commit is an update that I forgot to add in PR #4429. 
The second prints the scratch path at the end again to make it easy for the user to get to it. 
The third is a cosmetic update to how the revision is retrieved and printed.
> [dvsim] Some cosmetic updates 

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/dv/env/keymgr_env.core
- hw/ip/keymgr/dv/env/keymgr_env.sv
- hw/ip/keymgr/dv/env/keymgr_env_cfg.sv
- hw/ip/keymgr/dv/env/keymgr_env_pkg.sv
- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/env/keymgr_virtual_sequencer.sv
- hw/ip/keymgr/dv/tb.sv
- hw/ip/keymgr/keymgr.core
- hw/ip/keymgr/keymgr_pkg.core
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
- hw/ip/keymgr/rtl/keymgr_reg_top.sv
- hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv
- hw/ip/prim/rtl/prim_sync_reqack.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
Please review last two commits only, the other commits are from #4444
> [keymgr] edn support

- hw/ip/keymgr/data/keymgr_testplan.hjson
- hw/ip/keymgr/doc/dv_plan/index.md
Add item keymgr_random, keymgr_stress_all
Enable testplan in dv_plan
> [keymgr/dv] Update testplan

- hw/ip/keymgr/data/keymgr.prj.hjson
- hw/ip/keymgr/doc/checklist.md
> [keymgr/dv] Update checklist and move to V1

- sw/device/rom_exts/docs/manifest.md
Signed-off-by: Silvestrs Timofejevs <silvestrst@lowrisc.org>
> [sw, rom_exts] manifest.md SHA-265 => SHA-256 typo fix

- hw/ip/i2c/rtl/i2c_fsm.sv
> [i2c, rtl] Fixed Lint warnings

- hw/ip/aes/data/aes_testplan.hjson
- hw/ip/aes/dv/env/aes_message_item.sv
- hw/ip/aes/dv/env/aes_scoreboard.sv
- hw/ip/aes/dv/env/aes_seq_item.sv
- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/env/seq_lib/aes_clear_vseq.sv
This fixed a few corners for the random start in random mode.
it also fixed a corner for clearing input and output data 
the second commit is just adding the test to the regression
Signed-off-by: Rasmus Madsen <rasmus.madsen@wdc.com>
> [aes/dv] updated aes to fix some corner cases in the clearing

- hw/ip/otp_ctrl/data/otp_ctrl_testplan.hjson
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env.core
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cfg.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_virtual_sequencer.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_lc_vseq.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_smoke_vseq.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_vseq_list.sv
- hw/ip/otp_ctrl/dv/otp_ctrl_sim_cfg.hjson
- hw/ip/otp_ctrl/dv/tb.sv
This PR add a push-pull agent for otp_lc_program req.
Later PR will add more functionality to otp_lc_vseq.
To pass this test, it depends on #4488 
> [dv/otp] Add sequence for LC transition

- hw/ip/lc_ctrl/dv/env/lc_ctrl_env_pkg.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_if.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_base_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_common_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_smoke_vseq.sv
- hw/ip/lc_ctrl/dv/tb.sv
- hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
- hw/top_earlgrey/fpv/top_earlgrey_fpv_cfgs.hjson
There are two commits in this PR:
1. Initial work on LC_CTRL smoke test.
It exercise a legal SW request change.
2. Add lc_ctrl to DV and FPV regression script.
> [dv/lc_ctrl] initial commit on LC_CTRL smoke test

- hw/ip/flash_ctrl/data/flash_ctrl.hjson
- hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl
- hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl
- hw/ip/flash_ctrl/data/flash_ctrl_pkg.sv.tpl
- hw/ip/flash_ctrl/dv/tb/flash_ctrl_wrapper.sv
- hw/ip/flash_ctrl/dv/tb/tb.sv
- hw/ip/flash_ctrl/flash_ctrl.core
- hw/ip/flash_ctrl/rtl/flash_ctrl.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_reg_top.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_pkg.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_pkg.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_pkg.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_top.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv
Connect scrambling key interface between flash and otp
> [flash_ctrl] Connect flash / otp key interface

- hw/ip/gpio/data/gpio.prj.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/lib/dif/dif_gpio.md
- sw/device/tests/dif/dif_gpio_smoketest.c
- sw/device/tests/dif/meson.build
- test/systemtest/config.py
This PR adds a smoke test for GPIO and updates the SW checklist and stage file.
> [sw/dif_gpio] Add GPIO smoke test

- util/uvmdvgen/checklist.md.tpl
This appears to be out of sync with the checklist items on https://docs.opentitan.org/doc/project/checklist/
> [doc] Fix checklist items in V1

- hw/ip/edn/lint/edn.waiver
> [edn/rtl] update waiver file for arbiter_ppc

- hw/top_earlgrey/dv/env/seq_lib/chip_sw_gpio_smoke_vseq.sv
> [dv] address 4518 comment

- hw/ip/pattgen/dv/tb.sv
- hw/ip/pattgen/rtl/pattgen.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/data/xbar_peri.hjson
- hw/top_earlgrey/dv/autogen/tb__xbar_connect.sv
- hw/top_earlgrey/dv/autogen/xbar_env_pkg__params.sv
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_pkg.sv
- hw/top_earlgrey/ip/rv_plic/data/autogen/rv_plic.hjson
- hw/top_earlgrey/ip/rv_plic/rtl/autogen/rv_plic.sv
- hw/top_earlgrey/ip/rv_plic/rtl/autogen/rv_plic_reg_pkg.sv
- hw/top_earlgrey/ip/rv_plic/rtl/autogen/rv_plic_reg_top.sv
- hw/top_earlgrey/ip/xbar_peri/data/autogen/xbar_peri.gen.hjson
- hw/top_earlgrey/ip/xbar_peri/data/autogen/xbar_peri.hjson
- hw/top_earlgrey/ip/xbar_peri/dv/autogen/tb__xbar_connect.sv
- hw/top_earlgrey/ip/xbar_peri/dv/autogen/xbar_env_pkg__params.sv
- hw/top_earlgrey/ip/xbar_peri/dv/autogen/xbar_peri_bind.sv
- hw/top_earlgrey/ip/xbar_peri/rtl/autogen/tl_peri_pkg.sv
- hw/top_earlgrey/ip/xbar_peri/rtl/autogen/xbar_peri.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey_pkg.sv
- hw/top_earlgrey/sw/autogen/top_earlgrey.c
- hw/top_earlgrey/sw/autogen/top_earlgrey.h
- hw/top_earlgrey/top_earlgrey.core
- sw/device/lib/dif/dif_plic.c
- sw/device/tests/dif/dif_plic_unittest.cc
Initial attempt at adding Pattgen.   Added to Peri xbar.
TODO: connect interrupts & pinmux.
> Add Pattgen to EarlGrey

- doc/security/specs/device_life_cycle/_index.md
> [lc_ctrl] Fix nvm_debug_en discrepancy in DEV

- hw/ip/lc_ctrl/data/lc_ctrl.prj.hjson
- hw/ip/lc_ctrl/doc/checklist.md
To be merged once #4386 and #4464 are in.
> [lc_ctrl] Move lc_ctrl into D1

- hw/ip/entropy_src/data/entropy_src_testplan.hjson
- hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson
- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
- hw/ip/entropy_src/dv/tests/entropy_src_base_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_smoke_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_test.core
- hw/ip/entropy_src/dv/tests/entropy_src_test_pkg.sv
> [entropy_src/dv] efuse changes

- hw/dv/sv/keymgr_kmac_agent/keymgr_kmac_monitor.sv
- hw/ip/keymgr/dv/env/keymgr_env.sv
- hw/ip/keymgr/dv/env/keymgr_env_cfg.sv
- hw/ip/keymgr/dv/env/keymgr_env_pkg.sv
- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_cfgen_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_direct_to_disabled_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_smoke_vseq.sv
Connect keymgr_kmac_monitor to scb and add following checks
1. Add adv data check
2. Add kmac key check, sw_share_output check
3. Add WORKING_STATE, OP_STATUS check
minor update in base_seq to reduce redundency
> [keymgr/dv] Update scoreboard

- azure-pipelines.yml
- tool_requirements.py
> [verible] Update Verible version to 0.0-808-g1e17daawq

- hw/ip/flash_ctrl/data/flash_ctrl.hjson
- hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl
- hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl
- hw/ip/flash_ctrl/data/flash_ctrl_pkg.sv.tpl
- hw/ip/flash_ctrl/lint/flash_ctrl.waiver
- hw/ip/flash_ctrl/rtl/flash_ctrl.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_reg_top.sv
- hw/ip/flash_ctrl/rtl/flash_phy.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_pkg.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_pkg.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_top.sv
- util/reggen/validate.py
- util/topgen/validate.py
- update parameters to production values and fix related lint warnings
- only remaining parameter not updated is the number of pages due to
fpga size constraints.
-  This will be finalized after #4329 is concluded
> [flash_ctrl] Update flash parameters to near production values

- hw/ip/otbn/util/otbn-rig
- hw/ip/otbn/util/rig/gens/jump.py
- hw/ip/otbn/util/rig/init_data.py
- hw/ip/otbn/util/rig/model.py
- hw/ip/otbn/util/rig/program.py
- hw/ip/otbn/util/rig/rig.py
I finally got around to generating 100 sequential streams and... crashed into a load of assertions. These commits fix them (sigh).
> [otbn] Fix silly bugs in random instruction generator

- hw/ip/edn/dv/env/edn_env.core
- hw/ip/edn/dv/env/edn_env.sv
- hw/ip/edn/dv/env/edn_env_cfg.sv
- hw/ip/edn/dv/env/edn_env_pkg.sv
- hw/ip/edn/dv/env/edn_scoreboard.sv
- hw/ip/edn/dv/env/edn_virtual_sequencer.sv
- hw/ip/edn/dv/tb.sv
> [edn/dv] parameter names/usage, fips bit

- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
Address failure mentioned at #4566
> [keymgr/dv] wait for cfgen=1 after reset to fix CSR failures

- hw/ip/csrng/data/csrng_testplan.hjson
- hw/ip/csrng/doc/checklist.md
- hw/ip/csrng/doc/dv/index.md
- hw/ip/csrng/dv/env/csrng_env.core
- hw/ip/csrng/dv/env/csrng_env.sv
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_env_pkg.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/csrng_virtual_sequencer.sv
- hw/ip/csrng/dv/tb.sv
- hw/ip/entropy_src/dv/tb/tb.sv
- hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
- util/build_docs.py
Changes for parameter move in entropy_src.
Updated links in dv_plan.
> [csrng/dv] parameter move, dv plan

- hw/ip/lc_ctrl/dv/env/lc_ctrl_env_pkg.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_if.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_smoke_vseq.sv
- hw/ip/lc_ctrl/dv/tb.sv
This PR checks LC output that enables other IPs/Functionalities.
This PR currently relies on Issue #4550 
> [dv/lc_ctrl] LC broadcast output checking

- hw/ip/aes/rtl/aes_pkg.sv
- hw/ip/aes/rtl/aes_sbox_canright_masked_noreuse.sv
This is a follow-up PR of #4185 .
> [aes] Clarify comments in "noreuse" version of masked Canright S-Box

- hw/ip/otbn/README.md
Realised this didn't reflect reality any more. This should bring it up to date. We could add some documentation on using OTBN within earlgrey (or at least point to the software examples/tests and DIF documentation) but we can deal with that later.
> [otbn] Update README

- hw/ip/keymgr/dv/env/keymgr_env.core
- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_direct_to_disabled_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_random_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_sideload_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_smoke_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_vseq_list.sv
- hw/ip/keymgr/dv/keymgr_sim_cfg.hjson
- hw/ip/keymgr/dv/tb.sv
Also update
1. Have change to randomize HW input before operation in random_vseq
2. Remove some unnecessary code in disabled_vseq
> [keymgr/dv] Add sideload vseq

- hw/ip/lc_ctrl/dv/env/lc_ctrl_env_pkg.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_if.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/lc_ctrl/dv/tb.sv
Recent LC_CTRL added a few new outputs, this PR added all outputs in
tb.sv and check their value via scb.
> [dv/lc_ctrl] update tb with new lc outputs

- hw/ip/prim/rtl/prim_ram_1p_adv.sv
- hw/ip/prim/rtl/prim_ram_2p_async_adv.sv
> [prim_ram*_adv] Qualify error output signals with rvalid

- hw/ip/aes/rtl/aes_prng_clearing.sv
- hw/ip/aes/rtl/aes_prng_masking.sv
> [aes] Add missing includes in PRNGs

- util/dvsim/dvsim.py
If we use `--remote` switch, the result summary path is not correct.
This is because to remove the root directory and get `rel_path` in
FlowCfg, we used
```
if self.rel_path == "":
self.rel_path = os.path.dirname(self.flow_cfg_file).replace(
self.proj_root + '/', '')
```
For this one, if remote switch is on, the self.proj_root is remote
repo_top. However, `self.flow_cfg_file` still uses the local abs path,
so the rel_path ended up still include the absolute path.
This PR fixed it by using the remote `cfg_path` if --remote is turned
on.
> [dvsim] Fix regression publish result link with --remote switch

- hw/ip/pattgen/data/pattgen_testplan.hjson
- hw/ip/pattgen/dv/env/pattgen_env.core
- hw/ip/pattgen/dv/env/seq_lib/pattgen_base_vseq.sv
- hw/ip/pattgen/dv/env/seq_lib/pattgen_perf_vseq.sv
- hw/ip/pattgen/dv/env/seq_lib/pattgen_vseq_list.sv
- hw/ip/pattgen/dv/pattgen_sim_cfg.hjson
[pattgen, dv] Add pattgen performance test
- add pattgen_perf_vseq
- update testplan, sim_cfg
> [pattgen, dv] Add pattgen performance test

- hw/ip/sram_ctrl/data/sram_ctrl.prj.hjson
- hw/ip/sram_ctrl/doc/checklist.md
Can be merged once #4647 is in.
> [sram_ctrl] Move into D1

- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
After a successfully LC state transition req, the LC will turn off all
its output. This check is implemented in scb.
> [dv/lc_ctrl] check lc_ctrl output after a successful state req

- hw/dv/sv/cip_lib/cip_base_vseq.sv
- hw/dv/sv/i2c_agent/i2c_device_driver.sv
- hw/dv/sv/i2c_agent/i2c_if.sv
- hw/dv/sv/i2c_agent/i2c_monitor.sv
- hw/ip/i2c/dv/env/i2c_env_cfg.sv
- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_error_intr_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_fifo_full_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_fifo_overflow_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_fifo_watermark_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_override_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_rx_tx_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_stress_all_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_stretch_timeout_vseq.sv
- hw/ip/i2c/dv/i2c_sim_cfg.hjson
This PR enables stress test with random reset issued.
> [i2c, dv] Add i2c_stress_with_rand_reset test

- doc/security/specs/_index.md
- hw/_index.md
- hw/ip/rv_core_ibex/doc/_index.md
- hw/top_earlgrey/doc/_index.md
- sw/device/lib/runtime/pmp.h
Signed-off-by: Michael Munday <mike.munday@lowrisc.org>
> [all] Fix remaining broken Ibex documentation links

- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
> [keymgr] Minor fixes

- hw/dv/sv/common_ifs/pins_if.sv
- hw/dv/sv/sim_sram/sim_sram.sv
- hw/ip/flash_ctrl/dv/tb/tb.sv
- hw/ip/gpio/dv/tb/tb.sv
- hw/top_earlgrey/dv/tb/tb.sv
Signed-off-by: ¨Srikrishna <¨sriyer@google.com¨>
> [DV] Cleanup lint warnings with Verible lint

- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/doc/_index.md
- hw/ip/csrng/rtl/csrng_core.sv
- hw/ip/csrng/rtl/csrng_reg_pkg.sv
- hw/ip/csrng/rtl/csrng_reg_top.sv
- hw/ip/csrng/rtl/csrng_state_db.sv
This debug feature is enabled with lc_hw_debug.
> [csrng/rtl] internal state observed from TLUL register

- hw/dv/sv/cip_lib/cip_base_env_cfg.sv
- hw/dv/sv/push_pull_agent/push_pull_agent_cfg.sv
- hw/dv/sv/push_pull_agent/push_pull_device_driver.sv
- hw/dv/sv/push_pull_agent/push_pull_host_driver.sv
> [dv] Add control to hold data until next req in push_pull_agent

- hw/ip/entropy_src/data/entropy_src.prj.hjson
- hw/ip/entropy_src/data/entropy_src_testplan.hjson
- hw/ip/entropy_src/doc/checklist.md
- hw/ip/entropy_src/doc/dv/index.md
Completed all V1 requirements/reviews
> [entropy_src/dv] dv doc, testplan, checklist, V1

- hw/ip/keymgr/dv/env/keymgr_env.core
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_direct_to_disabled_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_lc_disable_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_vseq_list.sv
- hw/ip/keymgr/dv/keymgr_sim_cfg.hjson
- hw/ip/keymgr/dv/tb.sv
1. Also fix gen_id check and fix unexpected version error in vseq
2. update scb for lc disabled
> [keymgr/dv] Add keymgr_lc_disable_vseq

- hw/dv/tools/dvsim/xcelium.hjson
> [DV, Xcelium] Fix for #4690

- hw/ip/otbn/rtl/otbn_controller.sv
If we execute a JAL or JALR from address `0xffc` (the top word in
memory), we want to store a link address of `0x1000` rather than zero.
> [otbn] Don't wrap link register values to size of dmem

- hw/ip/entropy_src/rtl/entropy_src_core.sv
> [entropy_src/rtl] gate fifo_err

- hw/ip/edn/doc/edn_top_diag.svg
- hw/ip/edn/rtl/edn_core.sv
> [edn/rtl] gate fifo_err, update topology diagram

- hw/ip/otp_ctrl/doc/_index.md
> [otp_ctrl/doc] Minor update of OTP wrapper interface waves

- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_kmac_if.sv
> [keymgr] Minor fix

- hw/ip/otbn/util/rig/model.py
This PR has two commits, but the first is copied from PR #4724, on which it depends. Following is the text for the second commit.
Before this patch, `Model.update_for_insn` updated the model
"generically", based on the instruction's operands and their types and
then it called any specific update function.
The problem is that we don't explicitly keep "before" and "after"
versions of registers (as done by the `commit()` methods in the ISS), so
the specific updater function could get a stale version of an input
argument. This doesn't matter for most operands (because, at worst,
writing an indeterminate value to the operand just forgets its value),
but does matter for `x`1, where something like
addi x2, x1, 123
ended up using the element immediately below the top of the stack when
calculating …
> [otbn] Fix ordering problems in RIG model update logic

- hw/ip/otbn/util/rig/program.py
This was supposed to be useful for adding instructions to the "current
section", but we don't actually use it, so it's probably better to
ditch it.
> [otbn] Remove the OpenSection logic in the RIG's Program class

- hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
> [sensor_ctrl / ast] slightly tweak alert handling in sensor_ctrl

- hw/ip/lc_ctrl/data/lc_ctrl.hjson
> [lc_ctrl] Add a few csr exclusions

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/doc/_index.md
- hw/ip/keymgr/dv/env/keymgr_env_pkg.sv
- hw/ip/keymgr/lint/keymgr.waiver
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_cfg_en.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
- hw/ip/keymgr/rtl/keymgr_reg_top.sv
> [keymgr] keymgr updates and cleanup

- hw/ip/clkmgr/data/clkmgr.hjson.tpl
- hw/ip/clkmgr/data/clkmgr.sv.tpl
- hw/ip/prim/lint/prim_clock_div.waiver
- hw/ip/prim/prim_clock_div.core
- hw/ip/prim/rtl/prim_clock_div.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/clkmgr/clkmgr.core
- hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
- hw/top_earlgrey/lint/top_earlgrey.waiver
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
Add divider step down for lc_ctrl state transitions
> [clkmgr] clkmgr updates

- hw/ip/prim/rtl/prim_lc_sync.sv
> [prim_lc_sync] Add AsyncOn parameter to enable/disable the sync flops

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/doc/_index.md
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_kmac_if.sv
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/ip/keymgr/rtl/keymgr_sideload_key.sv
- hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv
This should make the erorr behavior during Init / Disabled more consistent.
> [keymgr] Additional updates for error behavior consistency

- hw/ip/otp_ctrl/rtl/otp_ctrl_dai.sv
> [otp_ctrl] Do not descramble digest values when read through the DAI

- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_common_vseq.sv
After reset, need to wait for 2 cycles before accessing csr
> [keymgr/dv] Fix csr_mem_rw_with_rand_reset

- hw/ip/keymgr/data/keymgr.hjson
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv
> [keymgr / top] fix hjson wrong width

- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
Move err_code check from seq to scb
Add several updates for scb
1. update checking for  error cases to match with design change #4778
2. simplify logic to update current_state and current_op_state at the
end of operation
3. remove local intr_exp and update ral model predict value directly
> [keymgr/dv] Update scoreboard for error cases

- sw/device/lib/dif/dif_otbn.c
- sw/device/tests/dif/dif_otbn_unittest.cc
Address review comments in a related PR regarding the OTBN DIF.
> [dif/otbn] Minor code style cleanups

- sw/device/lib/dif/dif_lc_ctrl.c
- sw/device/lib/dif/dif_lc_ctrl.md
- sw/device/tests/dif/dif_lc_ctrl_unittest.cc
- sw/device/tests/dif/meson.build
This change is a roll-forward of an incorrectly-merged commit, so that it can be reviewed correctly.
> [dif/lc_ctrl] Implement LC DIFs.

- hw/ip/keymgr/rtl/keymgr_ctrl.sv
> [keymgr] Fix keymgr key valid stuck high

- hw/ip/otbn/util/rig/model.py
This wasn't quite right, because we call `_inc_gpr` after
`_generic_update_for_insn`. As usual, that's fine for everything except
`x1`. For `x1`, the `get_reg()` call inside `_inc_gpr` was causing a double
pop.
> [otbn] Fix RIG model's _inc_gpr logic

- hw/ip/prim/doc/prim_flash.md
Signed-off-by: Dana Agur <dana.agur@opentitan.com>
> [prim_flash] update according to implementation

- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
This PR add a key output checking from OTP to SRAMs
> [dv/otp] Add key output checking for sram

- util/uvmdvgen/tb.sv.tpl
> [dv] Fix a typo in tb.sv.tpl

- hw/ip/otbn/doc/_index.md
Split the "Programming" sections into two parts: a section about writing
software running on OTBN itself, and a section about writing software
running on the host CPU (Ibex). In particular, I made the following
changes:
* Move the general information about IMEM and DMEM to the "Design
Details" sections.
* Expand the "High-level operation sequence" section.
* Add a "Driver" section, mentioning the existence of the newly added
"high-level" driver.
* Add a section "Writing OTBN applications" with new subsections on
toolchain support, data passing, and returning from an OTBN
application.
Fixes #2804
> [otbn/doc] Expand programming sections

- hw/ip/edn/rtl/edn_core.sv
> [edn/rtl] enable added for ERR_CODE reg

- hw/ip/csrng/rtl/csrng_core.sv
> [csrng/rtl] enable added for ERR_CODE reg

- hw/ip/keymgr/doc/_index.md
Minor documentation fixes, thanks to @alphan for catching them. 
> [keymgr] keymgr documentation fixes

- hw/syn/tools/dc/run-syn.tcl
- hw/top_earlgrey/syn/top_earlgrey_syn_cfg.hjson
> [syn] Minor updates

- hw/ip/otp_ctrl/rtl/otp_ctrl_dai.sv
> [otp_ctrl] Fix digest read accesses in DAI

- sw/device/lib/dif/dif_uart.c
- sw/device/lib/dif/dif_uart.h
- sw/device/tests/dif/dif_uart_unittest.cc
Please see #4277 for the background information.
> [sw, uart] HW usage reviewed comment actions

- hw/ip/uart/doc/_index.md
- hw/top_earlgrey/rtl/top_earlgrey_verilator.sv
- sw/device/lib/arch/device_sim_verilator.c
- sw/device/lib/runtime/log.c
A series of tiny fixes for things I stumbled across when looking at the UART code and documentation today.
> [uart] Editorial fixes

- hw/ip/prim/prim_lc_dec.core
- hw/ip/prim/rtl/prim_lc_dec.sv
> [prim] - Add new prim_lc_dec

- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
As discussed at #4826
1. Add checking for kmac data during gen-out
2. Update kmac key checking
> [keymgr/dv] Add checking for kmac data during gen-out

- hw/dv/sv/keymgr_kmac_agent/keymgr_kmac_intf.sv
> [dv/keymgr_kmac_agent] Add 2 assertions to check last and done

- hw/ip/kmac/data/kmac.prj.hjson
- hw/ip/kmac/doc/checklist.md
> [kmac/dv] move to V1 status

- hw/ip/otbn/lint/otbn.waiver
- hw/ip/otbn/otbn.core
- hw/ip/otbn/rtl/otbn.sv
- hw/ip/otbn/rtl/otbn_alu_base.sv
- hw/ip/otbn/rtl/otbn_alu_bignum.sv
- hw/ip/otbn/rtl/otbn_controller.sv
- hw/ip/otbn/rtl/otbn_decoder.sv
- hw/ip/otbn/rtl/otbn_mac_bignum.sv
- hw/ip/otbn/rtl/otbn_stack.sv
Resolve all lint warnings produced by AscentLint. Most of them are
"fixed" in RTL, some of them are waived.
Fixes #4252
> [otbn] Resolve AscentLint warnings/errors

- hw/dv/sv/spi_agent/spi_agent_cfg.sv
- hw/dv/sv/uart_agent/uart_agent_cfg.sv
- hw/ip/spi_device/dv/tests/spi_device_base_test.sv
these variables have been defined in the base class
> [dv] Remove unnecessary variables in agents

- hw/ip/sram_ctrl/data/sram_ctrl_base_testplan.hjson
This PR is for the initial draft of the `sram_ctrl` testplan.
Marking as a draft until the testplan review meeting, no need to review until then.
> [dv/sram] initial sram_ctrl testplan

- hw/ip/otbn/dv/otbnsim/sim/isa.py
- hw/ip/otbn/dv/otbnsim/sim/sim.py
- hw/ip/otbn/util/otbn-objdump
- hw/ip/otbn/util/rig/program.py
- hw/ip/otbn/util/shared/insn_yaml.py
- hw/ip/otbn/util/shared/operand.py
- hw/ip/otbn/util/shared/syntax.py
I've spent a while looking at traces in the last few days and these bugs were annoying me!
> [otbn] Assorted improvements to trace/disassembly generation

- hw/ip/keymgr/dv/env/keymgr_env.core
- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_common_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_stress_all_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_vseq_list.sv
- hw/ip/keymgr/dv/keymgr_sim_cfg.hjson
also enable stress_all with reset
Fix some variables which are not re-initialized correctly after reset
> [keymgr/dv] Add stress_all test

- hw/ip/otbn/rtl/otbn_controller.sv
- hw/ip/otbn/rtl/otbn_loop_controller.sv
When an instruction is stalled the loop controller must not alter its
state or trigger certain actions. In particular at the loop end
instruction if it stalls (e.g. it is a load) the loop controller must
wait until the stall ends before commmanding the loop jump.
Fixes #4941
> [otbn] Loop controller must factor in stall

- hw/ip/csrng/doc/checklist.md
- hw/ip/edn/doc/checklist.md
- hw/ip/entropy_src/doc/checklist.md
Status update for entropy_src, csrng, and edn.
> [entropy/checklists] D2 checklist updated for entropy components'

- hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rand_ops_vseq.sv
Signed-off-by: Eitan Shapira <eitan.shapira@nuvoton.com>
Hi,
Following Sri request this is my PR for flash_ctrl.
> [dv/flash_ctrl] mass erase en fix & bkdr if data type change

- hw/lint/tools/ascentlint/parse-lint-report.py
- hw/lint/tools/veriblelint/parse-lint-report.py
- hw/lint/tools/verilator/parse-lint-report.py
- util/dvsim/LintCfg.py
This can be removed due to #1033.
> [lint] Remove Fusesoc-related message waivers

- sw/otbn/code-snippets/barrett384.s
This PR addresses issues:
#4549 
#4548 
#4112
> [otbn] Improve barrett384

- hw/ip/prim/rtl/prim_packer_fifo.sv
AST RNG request for feature to connect EDN bus.
> [prim_packer_fifo/rtl] reset to disable output controls

- hw/ip/csrng/data/csrng_testplan.hjson
- hw/ip/csrng/rtl/csrng_pkg.sv
> [csrng/dv] testplan

- util/dvsim/Scheduler.py
This PR fixes the comment in PR #4993. Thanks @rswarbrick  for the
suggestion.
> [dv/dvsim] Fix when next_item does not have dependency

- util/topgen.py
- Temporary solution to #2083
- This is an UBER hack
- This is needed because the generation process has dependencies on itself.  Normally this can be worked around, but for tops such as top_englishbreakfast that are generated on the fly, it becomes probelmatic.
- The basic idea is that for each dependency the generation process is invoked again to make sure updated information is used to generate new correct modules.
- The final run is the one that is actually used for final merging and deployed by the rest of the script.
[util] slightly tweak topgen multi-pass
> [util] make topgen run multiple passes

- hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl
- hw/ip/flash_ctrl/rtl/flash_ctrl.sv
- hw/ip/prim/rtl/prim_fifo_sync.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
> [prim] Update fifo behavior during reset

- hw/dv/sv/push_pull_agent/push_pull_device_driver.sv
- hw/dv/sv/push_pull_agent/push_pull_host_driver.sv
This PR solves a corner case encountered in nightly regression. When
async edn clock has smaller frequence and did not detect reset in a
clock edge, it causes edn driver to still send response after the
request is being reset.
Here is a screenshot of the corner case:
> [dv/push-pull-agent] async reset in push_pull_drivers

- hw/ip/prim/dv/prim_lfsr/prim_lfsr_sim.core
- hw/ip/prim/dv/prim_lfsr/tb/prim_lfsr_tb.sv
- hw/ip/prim/dv/prim_present/prim_present_sim.core
- hw/ip/prim/dv/prim_present/tb/prim_present_tb.sv
- hw/ip/prim/dv/prim_prince/prim_prince_sim.core
- hw/ip/prim/dv/prim_prince/tb/prim_prince_tb.sv
- hw/ip/trial1/dv/trial1_sim.core
- hw/ip/trial1/dv/trial1_test.sv
Changes made to the tb to use common DV utils tasks / macros.
> [dv] Minor updates to prim tbs

- hw/ip/otbn/rtl/otbn_controller.sv
- hw/ip/otbn/rtl/otbn_core.sv
- hw/ip/otbn/rtl/otbn_loop_controller.sv
- hw/ip/otbn/rtl/otbn_rf_base.sv
> [otbn] Prevent instruction actions on error

- hw/ip/otp_ctrl/doc/_index.md
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv.tpl
This addresses two issues reported in https://github.com/lowRISC/opentitan/issues/5072
> [otp_ctrl] Minor OTP alignments and fixes

- hw/ip/keymgr/dv/env/keymgr_env_pkg.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_cfgen_vseq.sv
Steal some good ideals from Cindy's PR #5005 to improve cfgen
> [keymgr/dv] Enhance cfgen sequence and scb

- hw/ip/entropy_src/rtl/entropy_src_core.sv
Slight variation on the port order for the sync fifo.
> [entropy_src/rtl] variation on fifo port add

- hw/ip/aes/data/aes_testplan.hjson
- hw/ip/aes/dv/env/aes_env_pkg.sv
- hw/ip/aes/dv/env/aes_message_item.sv
- hw/ip/aes/dv/env/aes_scoreboard.sv
- hw/ip/aes/dv/env/aes_seq_item.sv
- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/tests/aes_clear_test.sv
updates to DV to accommodate the changes in #4848 
reinserts clear test into regression.
> [aes/dv] updated dv to support RTL changes

- doc/ug/rust_for_c.md
Signed-off-by: Dan Nussbaum <dansn@google.com>
> Fix typo: impl {MyType==>Counter}.

- hw/ip/otp_ctrl/rtl/otp_ctrl_lfsr_timer.sv
This fixes a minor issue with external check triggers.
Previously, they have not been latched, which could lead to situations where both checks were triggered simultaneously via the external trigger register, but only one of them would actually run.
> [otp_ctrl] Latch external check triggers

- hw/ip/otbn/rtl/otbn_controller.sv
This trigger warnings from AscentLint. The only non-formatting change
is to define a named variable for the thing that's replicated as part
of `ispr_base_wr_en_o`.
> [otbn] Break long lines in otbn_controller.sv

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/rtl/keymgr_reg_top.sv
> [keymgr] fix sw_binding regwen

- hw/ip/prim_generic/rtl/prim_generic_flash.sv
> [prim] fix flash sram adapter use for configuration space

- hw/ip/otbn/dv/rig/otbn-rig
- hw/ip/otbn/dv/rig/rig/config.py
- hw/ip/otbn/dv/rig/rig/configs/README.md
- hw/ip/otbn/dv/rig/rig/configs/base.yml
- hw/ip/otbn/dv/rig/rig/configs/default.yml
- hw/ip/otbn/dv/rig/rig/configs/loopy.yml
- hw/ip/otbn/dv/rig/rig/gens/branch.py
- hw/ip/otbn/dv/rig/rig/gens/ecall.py
- hw/ip/otbn/dv/rig/rig/gens/jump.py
- hw/ip/otbn/dv/rig/rig/gens/loop.py
- hw/ip/otbn/dv/rig/rig/gens/straight_line_insn.py
- hw/ip/otbn/dv/rig/rig/rig.py
- hw/ip/otbn/dv/rig/rig/snippet_gen.py
- hw/ip/otbn/dv/rig/rig/snippet_gens.py
> [otbn] Add support for customisable configurations in random instruction generator

- hw/dv/sv/pattgen_agent/pattgen_agent_cfg.sv
- hw/dv/sv/pattgen_agent/pattgen_monitor.sv
- hw/ip/pattgen/data/pattgen_testplan.hjson
- hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
- hw/ip/pattgen/dv/env/pattgen_seq_cfg.sv
- hw/ip/pattgen/dv/env/seq_lib/pattgen_base_vseq.sv
- hw/ip/pattgen/dv/env/seq_lib/pattgen_stress_all_vseq.sv
- hw/ip/pattgen/dv/pattgen_sim_cfg.hjson
This PR supports the last test of pattgen V2
> [pattgen, dv] Add stress_all_with_rand_reset test

- hw/formal/tools/jaspergold/fpv.tcl
- hw/ip/pwrmgr/pwrmgr.core
- hw/ip/rv_core_ibex/rv_core_ibex.core
- hw/ip/sram_ctrl/sram_ctrl.core
- hw/ip/usbdev/usbdev.core
- hw/top_earlgrey/top_earlgrey_asic.core
This PR fixes a few included IPs core files from top-level, in order to
let FPV fusesoc build passes in top-level FPV connectivity test.
> [fpv] top_level updates

- hw/ip/otp_ctrl/dv/env/otp_ctrl_if.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
According to PR #5072, here updates the interface checkings in
testbench.
> [dv/otp_ctrl] update interface checkings

- hw/top_earlgrey/fpv/top_earlgrey_fpv_cfgs.hjson
This PR fixes a small typo from fpv batch script
> [fpv] Fix typo in fpv batch script

- hw/ip/alert_handler/alert_handler_component.core
- hw/ip/alert_handler/data/alert_handler.hjson
- hw/ip/alert_handler/data/alert_handler.hjson.tpl
- hw/ip/alert_handler/dv/env/alert_handler_env_cfg.sv
- hw/ip/alert_handler/dv/tb/tb.sv
- hw/ip/alert_handler/rtl/alert_handler.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/alert_handler/data/autogen/alert_handler.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- util/topgen/intermodule.py
> [top] wire up edn peripherals

- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
due to #5105, sw_binding_en wasn't actually verified before
After solved that issue, found some issues in scb (which is fixed in this PR)
and design issue at #5124
> [keymgr/dv] Update scb for sw_binding_en

- hw/ip/pattgen/doc/checklist.md
Update checklist.md for pattgen v2. This PR should be merge after PR #5127 
> [pattgen, dv] Update pattgen checklist.md

- hw/ip/prim_generic/rtl/prim_generic_otp.sv
> [prim/otp_ctrl] Fix ECC correctable bug in generic OTP wrapper

- azure-pipelines.yml
> [ci] skip fpga builds when only DV changes

- hw/ip/kmac/dv/env/kmac_env_pkg.sv
- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_smoke_vseq.sv
This PR adds basic scoreboarding functionality to kmac TB,
allowing us to compare the computed digest with the DPI model.
> [dv/kmac] basic scoreboard functionality

- util/uvmdvgen/env_pkg.sv.tpl
> [dv] add dv_base_reg_pkg to env_pkg template

- hw/ip/kmac/dv/env/kmac_env.core
- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/kmac/dv/env/kmac_sideload_if.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_sideload_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_smoke_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_vseq_list.sv
- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
This PR implements the `kmac_sideload_test` as detailed in the testplan.
> [dv/kmac] kmac_sideload_test

- hw/ip/pwrmgr/rtl/pwrmgr_slow_fsm.sv
> [pwrmgr] change boot state expectation for main power domain

- hw/ip/clkmgr/data/clkmgr.hjson.tpl
- hw/ip/clkmgr/data/clkmgr.sv.tpl
- hw/ip/flash_ctrl/rtl/flash_phy.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl.sv
- hw/ip/prim_generic/rtl/prim_generic_flash.sv
- hw/ip/rstmgr/data/rstmgr.sv.tpl
- hw/ip/spi_device/data/spi_device.hjson
- hw/ip/spi_device/dv/tb/tb.sv
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spi_device_pkg.sv
- hw/ip/spi_device/spi_device.core
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/data/top_earlgrey.sv.tpl
- hw/top_earlgrey/ip/clkmgr/clkmgr.core
- hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr_reg_pkg.sv
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr_reg_top.sv
- hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr.sv
- hw/top_earlgrey/ip/xbar_main/rtl/autogen/xbar_main.sv
- hw/top_earlgrey/ip/xbar_main/xbar_main.core
- hw/top_earlgrey/ip/xbar_peri/rtl/autogen/xbar_peri.sv
- hw/top_earlgrey/ip/xbar_peri/xbar_peri.core
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/top_earlgrey_asic.sv
- util/tlgen/xbar.core.tpl
- util/tlgen/xbar.rtl.sv.tpl
- connect jitter enable
- connect differential scanmode signal
- also connect reset bypass structure in `spi_device`
> [top] Complete various connections to ast

- sw/otbn/code-snippets/rsa.s
Editorial-only change.
Signed-off-by: Philipp Wagner <phw@lowrisc.org>
> [otbn/sw] Improve consistency of comments in rsa.s

- hw/ip/rv_dm/rtl/rv_dm.sv
- hw/ip/rv_dm/rv_dm.core
- hw/ip/tlul/rtl/tlul_adapter_sram.sv
- hw/ip/uart/rtl/uart_core.sv
A series of small fixes to unbreak VeribleLint and fix some findings.
> Small lint fixes

- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- hw/top_englishbreakfast/data/xbar_main.hjson
- hw/top_englishbreakfast/data/xbar_peri.hjson
- hw/top_englishbreakfast/rtl/top_englishbreakfast_cw305.sv
- hw/top_englishbreakfast/util/prepare_sw.py
This PR contains two commits to address #5242 .
> [top_englishbreakfast] Re-align config with recent changes in top_earlgrey

- hw/ip/kmac/dv/env/seq_lib/kmac_smoke_vseq.sv
> [dv/kmac] fix CI compile issue in kmac tb

- util/reggen/validate.py
> [reggen] Minor fix to REGWEN error message

- util/difgen/gen_dif_listing.py
Currently the text produced for the DIF description stops at the first
subelement. This is apparent if the description contains a variable
enclosed in backticks. The text up to this variable is returned but not
the rest.
Instead of using the `text` member of the element, which only contains
the text up to the first subelement according to the ET documentation,
create proper HTML for the description.
All tags are transformed into `span` HTML tags with
`@class='doxygentag-ORIGINALTAGNAME'` set to retain the original tag
information from the Doxygen schema. To give us a bit more semantic
HTML, the `<computeroutput>` tag is transformed into a `<code>` HTML tag.
Fixes #5001
> [site] Generate complete DIF description

- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
> [keymgr/dv] update scb to remove non-block assignment

- hw/dv/sv/test_vectors/test_vectors_pkg.sv
- hw/ip/kmac/data/kmac_base_testplan.hjson
- hw/ip/kmac/dv/env/kmac_env_cfg.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_smoke_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_test_vectors_base_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_test_vectors_sha3_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_test_vectors_shake_vseq.sv
- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
This PR contains a few updates/fixes for the test_vector tests,
and adds a few helpful display messages during simulation.
> [dv/kmac] fixes/updates for kmac_test_vector tests

- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
The nightly regression failure is due to recent change in `reset`
function. When reset is issued at posedge of `rst_n`, previous otp_scb
code causes a race condition. This PR moves the ral prediction after
`reset` function to avoid the race condition.
> [dv/otp] Fix regression regwen failure

- hw/ip/csrng/data/csrng.prj.hjson
- hw/ip/csrng/doc/checklist.md
Successful V1 review so updates checklist and hjson file to reflect V1
> [csrng/dv] V0->V1

- hw/ip/rv_dm/rtl/rv_dm.sv
- hw/top_earlgrey/data/top_earlgrey.sv.tpl
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
> [jtag/scan] Connect scanmode signal of RV DM TAP

- doc/security/specs/device_life_cycle/_index.md
- hw/ip/lc_ctrl/doc/_index.md
- hw/ip/lc_ctrl/doc/lc_ctrl_flash_accessibility.md
- hw/ip/usbdev/data/usbdev.hjson
- util/reggen/multi_register.py
- util/topgen/intermodule.py
@moidx  or @msfschaffner  could you review the life cycle change please?
> Fix spelling and copy paste errors

- hw/ip/otbn/data/otbn.hjson
- hw/ip/otbn/dv/verilator/otbn_top_sim.sv
- hw/ip/otbn/otbn.core
- hw/ip/otbn/rtl/otbn.sv
- hw/ip/otbn/rtl/otbn_core.sv
- hw/ip/otbn/rtl/otbn_pkg.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
> [otbn] Hookup EDN connection

- hw/ip/aes/syn/aes_syn_cfg.hjson
- hw/ip/otbn/syn/otbn_syn_cfg.hjson
- hw/syn/tools/dc/parse-syn-report.py
- hw/syn/tools/dvsim/dc.hjson
- hw/top_earlgrey/syn/asic.constraints.sdc
- hw/top_earlgrey/syn/top_earlgrey_asic_syn_cfg.hjson
- hw/top_earlgrey/syn/top_earlgrey_syn_cfg.hjson
- util/dvsim/SynCfg.py
This adds constraints that make sure that clock networks driven by hand-inserted, architectural clock gates are treated as ideal in synthesis.
Also, the area result parsing is improved such that multiple hierarchies can be reported.
The area result table now also displays logic and macro totals plus percentages now.
> [syn/dvsim] Update synthesis ASIC constraints and area result parsing

- sw/otbn/code-snippets/p256.s
- sw/otbn/code-snippets/p256_curve_point_test.s
- sw/otbn/code-snippets/p256_ecdsa_sign_test.s
- sw/otbn/code-snippets/p256_ecdsa_verify_test.s
- sw/otbn/code-snippets/p256_scalar_mult_test.s
This adds documentation to the ECC P-256 code and improves style
This finishes #4000
> [otbn] ECC p256 documentation and style improvement

- hw/ip/lc_ctrl/lc_ctrl.core
- hw/ip/lc_ctrl/rtl/lc_ctrl.sv
- hw/ip/rv_dm/rtl/rv_dm.sv
- hw/ip/rv_dm/rv_dm.core
> [jtag/scanmode] Add clock mux on TCK for scanmode

- hw/top_earlgrey/data/clocks.xdc
- hw/top_earlgrey/rtl/clkgen_xil7series.sv
- hw/top_earlgrey/rtl/top_earlgrey_nexysvideo.sv
- hw/top_earlgrey/rtl/top_earlgrey_verilator.sv
- hw/top_earlgrey/top_earlgrey_verilator.cc
- hw/top_earlgrey/top_earlgrey_verilator.core
- hw/top_englishbreakfast/rtl/top_englishbreakfast_cw305.sv
- hw/top_englishbreakfast/rtl/top_englishbreakfast_verilator.sv
- hw/top_englishbreakfast/top_englishbreakfast_verilator.cc
> [top] slow down clk_aon for verilator and fpga

- hw/ip/kmac/data/kmac_base_testplan.hjson
- hw/ip/kmac/dv/env/kmac_env.core
- hw/ip/kmac/dv/env/kmac_env_pkg.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_burst_write_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_smoke_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_vseq_list.sv
- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
This PR implements the kmac_burst_wr test as described in the testplan.
> [dv/kmac] kmac_burst_write test

- hw/top_earlgrey/data/top_earlgrey.sv.tpl
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
> [top] Hardcode rv_dm hw_debug_en

- hw/ip/flash_ctrl/data/flash_ctrl.hjson
- hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl
- hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl
- hw/ip/flash_ctrl/data/flash_ctrl_pkg.sv.tpl
- hw/ip/flash_ctrl/dv/tb/flash_ctrl_wrapper.sv
- hw/ip/flash_ctrl/flash_ctrl_pkg.core
- hw/ip/flash_ctrl/rtl/flash_ctrl.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
- hw/ip/flash_ctrl/rtl/flash_phy.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/data/top_earlgrey.sv.tpl
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_pkg.sv
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_pkg.sv
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_top.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/sw/autogen/top_earlgrey.h
The jtag ports are passed through `flash_ctrl` to `pinmux`.
> [flash] Hookup jtag ports to pinmux

- hw/top_earlgrey/rtl/top_earlgrey_asic.sv
- hw/top_earlgrey/rtl/top_earlgrey_nexysvideo.sv
- hw/top_earlgrey/rtl/top_earlgrey_verilator.sv
> [top] Correct top level parameters for sram execution

- hw/ip/prim/rtl/prim_packer_fifo.sv
There are two changes here. The first is to explicitly zero-extend
`wdata_i` from `InW` up to `OutW` when computing `wdata_shifted` in pack mode.
The second is to slice out just the bits we need from `MaxW / MinW` when
comparing `depth_q` against it (otherwise Verilator complains that we're
comparing a small bitvector against a 32-bit int).
> [prim_packer] Silence verilator width warnings

- hw/ip/sram_ctrl/data/sram_ctrl.prj.hjson
- hw/ip/sram_ctrl/doc/checklist.md
Draft PR to prepare moving the SRAM controller into D2.
> [sram_ctrl] Transition into D2

- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
> [otp_ctrl] Make error interrupts non-sticky

- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/ip/rv_core_ibex/rv_core_ibex.core
- hw/top_earlgrey/data/top_earlgrey.sv.tpl
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
Blocked by #5356 for completion
> [top] Convert fetch_enable to lc ctrl based

- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
This PR finishes a TODO in alert cip_base_scb check: if user cannot
accurately predict when alert happens, we have a input signal called
`max_delay` to check alert within the max delay.
But note this variable cannot be used it there is any on-going alert
handshakes, because we cannot accurately predict if two alerts should be
merged or not.
I am adding this support because OTP_CTRL'S ECC uncorrectable alert is
triggered when OTP memory read the cell and finished ECC check, scb
cannot accurately predict at which clock cycle the reading and checking
are finished.
> [dv/cip_scb] alert check with a delay

- hw/dv/sv/keymgr_kmac_agent/keymgr_kmac_agent.sv
- hw/dv/sv/keymgr_kmac_agent/keymgr_kmac_agent_cfg.sv
- hw/dv/sv/keymgr_kmac_agent/keymgr_kmac_host_driver.sv
- hw/dv/sv/keymgr_kmac_agent/keymgr_kmac_intf.sv
- hw/dv/sv/keymgr_kmac_agent/keymgr_kmac_item.sv
- hw/dv/sv/keymgr_kmac_agent/keymgr_kmac_sequencer.sv
- hw/dv/sv/keymgr_kmac_agent/seq_lib/keymgr_kmac_host_seq.sv
this PR implements the host-side of the keymgr_kmac_agent.
> [dv/keymgr_kmac_agent] implement host protocol

- hw/ip/kmac/dv/env/kmac_env.core
- hw/ip/kmac/dv/env/kmac_env.sv
- hw/ip/kmac/dv/env/kmac_env_cfg.sv
- hw/ip/kmac/dv/env/kmac_env_pkg.sv
- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/kmac/dv/env/kmac_virtual_sequencer.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_kdf_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_smoke_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_vseq_list.sv
- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
- hw/ip/kmac/dv/tb.sv
this PR implements the `kmac_kdf_test` as specified in the testlist
this PR depends on #5302 and #5300 to be merged first.
> [dv/kmac] KDF test

- hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
> [dvsim] Alphabetize top_earlgrey_sim_cfgs.hjson

- hw/ip/prim/rtl/prim_secded_22_16_dec.sv
- hw/ip/prim/rtl/prim_secded_28_22_dec.sv
- hw/ip/prim/rtl/prim_secded_39_32_dec.sv
- hw/ip/prim/rtl/prim_secded_64_57_dec.sv
- hw/ip/prim/rtl/prim_secded_72_64_dec.sv
- hw/ip/tlul/lint/tlul_socket_1n.vlt
- hw/ip/tlul/rtl/tlul_err_resp.sv
- util/design/secded_gen.py
@tomroberts-lowrisc: I stole the secded changes from the decoder in the Ibex repository. Did you hand-edit this to avoid the Verilator warning, or is there another version of the generator that I haven't seen?
> Verilator lint fixes

- hw/ip/aon_timer/aon_timer.core
- hw/ip/aon_timer/lint/aon_timer.vlt
- hw/ip/aon_timer/lint/aon_timer.waiver
- hw/ip/aon_timer/rtl/aon_timer.sv
- hw/top_earlgrey/lint/top_earlgrey_lint_cfgs.hjson
Minor lint updates plus adding AON Timer to the nightly lint runs.
Also added ASSET_KNOWN on outputs
> AON Timer updates to reach D1 status

- hw/ip/aon_timer/data/aon_timer.prj.hjson
- hw/ip/aon_timer/doc/checklist.md
The IP is already instantiated in top_earlygrey and all checklist items
are complete.
> [aon_timer] Advance to D1 status

- hw/ip/aon_timer/lint/aon_timer.waiver
- hw/ip/aon_timer/rtl/aon_timer.sv
Fix a few signal warnings picked up by Ascent lint.
> [aon_timer] Lint fixes

- hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_fifo_full_vseq.sv
- hw/ip/i2c/dv/env/seq_lib/i2c_fifo_watermark_vseq.sv
Update fifo_watermark and fifo_fall test to address Weicai's comments (PR #5379)
> [i2c, dv] Update fifo_watermark and fifo_fall test

- hw/ip/prim_generic/lint/prim_generic_clock_gating.waiver
- hw/ip/rv_core_ibex/lint/rv_core_ibex.waiver
- hw/lint/tools/ascentlint/common.waiver
Other issues are being fixed in the Ibex RTL (https://github.com/lowRISC/ibex/pull/1285), there may be a delay whilst those are merged and vendored across into the OT repository
> Ibex lint fix

- util/dvsim/Deploy.py
- util/dvsim/SimCfg.py
The `SimCfg` prunes the number of builds if there is no uniqueness among
the existing build objects. If a simulation is rerun with --run-only
switch (the assumption here being there is no need to rebuild the
simulation executables since the source code did not change), with the
old code, the build pruning is not performed, causing the tests to
reference non-existent builds and fail. This commit fixes that issue.
If `--cov --build-only` is passed on the command line (with the intent
to pass `--cov --run-only` later), builds get prematurely pruned out
because we turn off the coverage switch. This prevents us from  doing
`--cov --build-only` and `--cov --run-only` as two separate steps.
Also, the coverage table and summary table end up throwing errors. This
change fixes that.
In addition, …
> [dvsim] Fix --cov + --build|run-only bugs 

- hw/dv/sv/dv_utils/dv_fcov_macros.svh
> [dv] Add DV_FCOV_SVA back

- hw/ip/lc_ctrl/doc/_index.md
- hw/ip/lc_ctrl/doc/lc_ctrl_function_signals_table.md
- hw/ip/lc_ctrl/dv/env/lc_ctrl_env_pkg.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_signal_decode.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv
> [lc_ctrl] Several life cycle updates

- hw/ip/otp_ctrl/rtl/otp_ctrl_lci.sv
> [otp_ctrl] Always attempt to program all LC words in presence of errors

- hw/top_earlgrey/data/top_earlgrey.sv.tpl
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
This solution is not complete, please see #5446
> [top] Correct memory connection bit widths

- hw/ip/alert_handler/doc/_index.md
- hw/ip/alert_handler/rtl/alert_handler_reg_wrap.sv
> [alert_handler] Delete stale comment

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_multiple_keys_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_smoke_vseq.sv
this PR fixes a few unaligned statements and includes some minor style fixes
> [dv/sram] minor updates to sram tb

- hw/dv/sv/cip_lib/cip_base_vseq.sv
workaround for #5262
Also change num_access to only count read access
> [dv] only read mem which is written with full word data

- sw/otbn/code-snippets/barrett384_p384.s
- sw/otbn/code-snippets/p256.s
- sw/otbn/code-snippets/p256_proj_add_test.s
- sw/otbn/code-snippets/p384_proj_add.s
- sw/otbn/code-snippets/p384_proj_add_test.s
- sw/otbn/code-snippets/rules.mk
This adds the code for the curve point addition for curve P-384. Also adds simple standalone test with hardcoded example points.
This is related to #2982
> [otbn] P-384 curve point addition routines

- hw/ip/spi_device/data/spi_device.hjson
- hw/ip/spi_device/rtl/spi_cmdparse.sv
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/spi_device/rtl/spi_device_pkg.sv
- hw/ip/spi_device/spi_device.core
This commit implements SPI Flash command process block. It decodes first
8bit of received data and triggers proper downstream module to handle
the received commands.
> [spi_device] Command Process block

- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_bijection_vseq.sv
- hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_vseq_list.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_env.core
- hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
this PR implements the bijection test as described in the testplan.
> [dv/sram] bijection test

- hw/ip/aes/rtl/aes_prng_masking.sv
- hw/ip/prim/rtl/prim_ram_1p_scr.sv
- hw/ip/rv_plic/rtl/rv_plic_target.sv
- hw/top_earlgrey/ip/xbar_main/rtl/autogen/xbar_main.sv
- hw/top_earlgrey/ip/xbar_peri/rtl/autogen/xbar_peri.sv
- util/tlgen/xbar.rtl.sv.tpl
> [lint] Fix a bunch of lint warnings related to long lines (>100 chars)

- hw/top_earlgrey/ip/ast/rtl/aon_osc.sv
- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv
- hw/top_earlgrey/ip/ast/rtl/io_osc.sv
- hw/top_earlgrey/ip/ast/rtl/rng.sv
- hw/top_earlgrey/ip/ast/rtl/rng_osc.sv
- hw/top_earlgrey/ip/ast/rtl/sys_osc.sv
- hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
> [AST] AscentLint & Spyglass fixes

- hw/ip/prim/rtl/prim_secded_pkg.sv
- util/design/data/secded_cfg.hjson
- util/design/secded_gen.py
this PR does a few things with secded_gen.py:
- adds a seed value to data/secded_cfg.hjson for reproducibility
- adds decoding functions to prim_secded_pkg
- minor spacing updates throughout if generating the pkg functions
> [util] minor updates to secded_gen

- hw/ip/aon_timer/data/aon_timer.hjson
- hw/ip/aon_timer/rtl/aon_timer.sv
- hw/ip/aon_timer/rtl/aon_timer_reg_pkg.sv
- hw/ip/aon_timer/rtl/aon_timer_reg_top.sv
@tjaychen DV update is done, so that I remove the temporary hack in design.
> [aon_timer] Remove temporary intr_enable for #5260

- hw/ip/clkmgr/data/clkmgr.sv.tpl
- hw/ip/prim/rtl/prim_clock_div.sv
- hw/top_earlgrey/data/clocks.xdc
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
- hw/top_earlgrey/syn/asic.constraints.sdc
Addresses #5452 and #5453
- force step_down_req to 0 when in test mode
- remove test mode bypass mux 
> [clkmgr] Fix dft issues

- hw/ip/otp_ctrl/rtl/otp_ctrl_lfsr_timer.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_buf.sv
> [otp_ctrl] Fix some corner cases

- hw/ip/aon_timer/data/aon_timer_testplan.hjson
- hw/ip/aon_timer/doc/dv_plan/index.md
- hw/ip/aon_timer/dv/aon_timer_sim.core
- hw/ip/aon_timer/dv/aon_timer_sim_cfg.hjson
- hw/ip/aon_timer/dv/env/aon_timer_env.core
- hw/ip/aon_timer/dv/env/aon_timer_env.sv
- hw/ip/aon_timer/dv/env/aon_timer_env_cfg.sv
- hw/ip/aon_timer/dv/env/aon_timer_env_cov.sv
- hw/ip/aon_timer/dv/env/aon_timer_env_pkg.sv
- hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
- hw/ip/aon_timer/dv/env/aon_timer_virtual_sequencer.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_common_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_smoke_vseq.sv
- hw/ip/aon_timer/dv/env/seq_lib/aon_timer_vseq_list.sv
- hw/ip/aon_timer/dv/sva/aon_timer_bind.sv
- hw/ip/aon_timer/dv/sva/aon_timer_sva.core
- hw/ip/aon_timer/dv/tb.sv
- hw/ip/aon_timer/dv/tests/aon_timer_base_test.sv
- hw/ip/aon_timer/dv/tests/aon_timer_test.core
- hw/ip/aon_timer/dv/tests/aon_timer_test_pkg.sv
- hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
- hw/top_earlgrey/lint/top_earlgrey_dv_lint_cfgs.hjson
- Add basic DV tb that only tests CSR.
> [aon_timer] Basic DV smoke tests

- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.sv.tpl
- hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv
- util/reggen/signal.py
- util/topgen.py
- util/topgen/intermodule.py
- util/topgen/merge.py
This is a cleanup patch to make it easier to do the changes needed to support multiple device interfaces on a block (this PR is all about reducing the number of places things get repeated, so that the multi-device changes don't need to change so much in parallel).
> [topgen] Some simplifications in how we instantiate stuff in topgen

- hw/ip/edn/data/edn.hjson
- hw/ip/edn/rtl/edn.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- sw/device/tests/aes_test.c
- sw/device/tests/dif/dif_aes_smoketest.c
> [top] Change edn hook-up

- hw/dv/sv/csrng_agent/csrng_agent.core
- hw/dv/sv/csrng_agent/csrng_agent.sv
- hw/dv/sv/csrng_agent/csrng_agent_cfg.sv
- hw/dv/sv/csrng_agent/csrng_agent_pkg.sv
- hw/dv/sv/csrng_agent/csrng_device_driver.sv
- hw/dv/sv/csrng_agent/csrng_if.sv
- hw/dv/sv/csrng_agent/csrng_item.sv
- hw/dv/sv/csrng_agent/csrng_monitor.sv
- hw/dv/sv/csrng_agent/csrng_sequencer.sv
- hw/dv/sv/csrng_agent/seq_lib/csrng_base_seq.sv
- hw/dv/sv/csrng_agent/seq_lib/csrng_device_seq.sv
- hw/dv/sv/csrng_agent/seq_lib/csrng_host_seq.sv
- hw/dv/sv/csrng_agent/seq_lib/csrng_seq_list.sv
- hw/ip/edn/dv/env/edn_env.sv
- hw/ip/edn/dv/env/edn_env_cfg.sv
- hw/ip/edn/dv/env/edn_virtual_sequencer.sv
- hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv
- hw/ip/edn/dv/tb.sv
csrng_agent device_mode/edn_dv/edn_smoke_test changes
> [edn/dv] csrng_agent device mode, edn_smoke_test

- hw/dv/sv/uart_agent/uart_agent_cfg.sv
- hw/dv/sv/uart_agent/uart_agent_pkg.sv
- hw/dv/sv/uart_agent/uart_driver.sv
- hw/ip/uart/dv/env/seq_lib/uart_base_vseq.sv
- hw/ip/uart/dv/env/uart_env_cov.sv
- hw/ip/uart/dv/env/uart_env_pkg.sv
- hw/ip/uart/dv/env/uart_scoreboard.sv
- sw/device/lib/arch/device_sim_dv.c
> [uart/dv] Update uart baud rate and add coverage

- util/dvsim/dvsim.py
Ignore `--remote` if `--dry-run` is passed.
Fixed #5527. 
> [dvsim] Fix for #5527

- hw/ip/keymgr/rtl/keymgr_kmac_if.sv
> [keymgr] latch one-hot error when it happens

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/keymgr.core
- hw/ip/keymgr/keymgr_pkg.core
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
> [keymgr] Widen sw_binding and salt registers

- hw/ip/aon_timer/aon_timer.core
- hw/ip/aon_timer/rtl/aon_timer.sv
> [aon_timer/lint] Minor lint fixes

- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_parallel_lc_req_vseq.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_smoke_vseq.sv
This PR adds support for err_code register checking
> [dv/otp_ctrl] support err_code checking

- hw/dv/tools/dvsim/sim.mk
- hw/formal/tools/dvsim/fpv.mk
- hw/lint/tools/dvsim/lint.mk
- hw/syn/tools/dvsim/syn.mk
> [dvsim] Use bash when running make underneath

- hw/ip/rbox/data/rbox.hjson
- hw/ip/rbox/rtl/rbox_reg_pkg.sv
- hw/ip/rbox/rtl/rbox_reg_top.sv
> [rbox] update hjson to use bus_interfaces

- hw/ip/aes/dv/aes_sim.core
- hw/ip/aes/dv/aes_sim_cfg.hjson
- hw/ip/aes/dv/cov/aes_cov.core
- hw/ip/aes/dv/cov/aes_cov.vRefine
- hw/ip/aes/dv/cov/aes_cov_bind.sv
- hw/ip/aes/dv/cov/aes_cov_if.sv
- hw/ip/aes/dv/env/aes_env.core
- hw/ip/aes/dv/env/aes_env_pkg.sv
- hw/ip/aes/dv/env/aes_message_item.sv
- hw/ip/aes/dv/env/aes_scoreboard.sv
- hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
- hw/ip/aes/dv/tb/tb.sv
- hw/ip/aes/dv/tests/aes_smoke_test.sv
- hw/ip/aes/rtl/aes_pkg.sv
This has the initial steps for functional and code coverage for aes.
no attempt has been done to close coverage at this point and should only serve as the skeleton for AES - and as an example for the other xcelium driven IP
> Aes func cover

- hw/ip/prim/rtl/prim_fifo_async.sv
Various lint and style updates plus some extra parameterization to allow the module to be used with Depth < 3. Also added some assertions to confirm gray coding works correctly.
> Asynchronous FIFO updates

- hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
this minor patch updates how the scoreboard does address comparisons in
case of read-after-write hazards to handle data forwarding.
we add a function to properly mask off the address widths and compare,
which allows for better reuse in the scoreboard if needed.
> [dv/sram] add address comparison function in SCB

- hw/ip/aes/data/aes.hjson
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.sv.tpl
- hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
This hookup was still missing. Should address #5589.
> [alerts] Fully connect alert async on parameters

- hw/dv/sv/csrng_agent/README.md
- hw/ip/csrng/doc/checklist.md
- hw/ip/edn/data/edn_testplan.hjson
- hw/ip/edn/doc/checklist.md
- hw/ip/edn/doc/dv/index.md
- hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_smoke_vseq.sv
- hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
> [edn/dv] dv doc, testplan, checklist, regression, csrng_agent mod

- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_env_pkg.sv
- hw/ip/csrng/dv/tb.sv
> [csrng/dv] Added alerts

- hw/top_earlgrey/dv/chip_sim_cfg.hjson
> [dv] temporarily disable mem test in chip-level

- hw/ip/spi_host/data/spi_host_testplan.hjson
Add spi_host_testplan.hjson
This PR should be merged after PR #5007 and #5149 
> [spi_host, dv] Add spi_host_testplan.hjson

- hw/ip/hmac/dv/env/hmac_scoreboard.sv
This PR fixes hmac illegal bin error. The error is due to hmac scb
sampling issue.
When we do a intr_test write, and then intr_test write, the interrupt
could be cleared. Then if we read intr_test, the interrupt test still
expects the test bits to be set.
This PR fixes the issue by sampling it on intr_test.
> [dv/hmac] Fix illegal bin failure

- hw/dv/sv/csrng_agent/csrng_agent.sv
The update #5532 had null pointer error, somehow, CI didn't fail
This should fix it
> [dv] Fix CI failure at EDN

- util/dvsim/Deploy.py
- util/dvsim/Launcher.py
- util/dvsim/LauncherFactory.py
- util/dvsim/LocalLauncher.py
- util/dvsim/LsfLauncher.py
- util/dvsim/SimCfg.py
- util/dvsim/dvsim.py
This commit extends the Launcher to implement LsfLauncher, which brings in better support for dispatching with LSF. This is still a first cut implementation - there are several things to improve, which will be done in subsequent PRs.
> Dvsim LsfLauncher implementation

- hw/dv/tools/dvsim/xcelium.hjson
> [dv] Xcelium UNR typo

- hw/ip/rv_dm/rtl/rv_dm.sv
Having those asserts is a requirement for D1.
> [rv_dm] Add known asserts to outputs

- hw/ip/csrng/dv/csrng_sim_cfg.hjson
- hw/ip/edn/dv/edn_sim_cfg.hjson
- hw/ip/edn/dv/env/edn_env_cfg.sv
- hw/ip/edn/dv/env/edn_env_pkg.sv
- hw/ip/edn/dv/tb.sv
> [edn/dv] Added alerts

- hw/ip/pwm/data/pwm_testplan.hjson
Add pwm_testplan.md file for dv
Signed-off-by: Hoang Tung <Hoang.Tung@wdc.com>
> [pwm, dv] Add testplan for PWM

- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_parallel_lc_req_vseq.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_smoke_vseq.sv
This PR enables error code check in lc_sequence.
> [dv/otp_ctrl] enable error code check in lc sequence

- util/reggen/bits.py
- util/reggen/field.py
- util/reggen/gen_fpv.py
- util/reggen/ip_block.py
- util/reggen/multi_register.py
- util/reggen/params.py
- util/reggen/reg_block.py
- util/reggen/register.py
- util/reggen/top.py
- util/reggen/window.py
See the individual commit messages for more details.
None of the changes should influence existing behavior.
> [reggen] Refactorings in preparation for ipgen

- hw/ip/edn/data/edn.prj.hjson
- hw/ip/edn/data/edn_testplan.hjson
- hw/ip/edn/doc/checklist.md
> [edn/dv] V0->V1

- hw/top_earlgrey/ip/ast/data/ast.hjson
- hw/top_earlgrey/ip/ast/rtl/aon_clk.sv
- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv
- hw/top_earlgrey/ip/ast/rtl/ast_reg_top.sv
- hw/top_earlgrey/ip/ast/rtl/io_clk.sv
- hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv
- hw/top_earlgrey/ip/ast/rtl/rng.sv
- hw/top_earlgrey/ip/ast/rtl/rng_osc.sv
- hw/top_earlgrey/ip/ast/rtl/sys_clk.sv
- hw/top_earlgrey/ip/ast/rtl/usb_clk.sv
- hw/top_earlgrey/rtl/top_earlgrey_asic.sv
> [AST] AscentLint, HJSON fixes, and rng_fips_i port

- util/dvsim/Launcher.py
- util/dvsim/LocalLauncher.py
- util/dvsim/LsfLauncher.py
- Rearranged APIs to make them uniform
- Updated `_has_passed()`
- Renamed to `_check_status()`
- Returns a tuple as opposed to bool
- Tuple returned is status, err_msg, where status is "P" or "F"
- Makes it easy to pick the 'right' error message to report
especially when there are multiple points of failure in more complex
launcher system such as LSF
- _post_finish() now takes err_msg as additional arg to reuse more code
- LsfLauncher:
- Renamed some vars / methods
- Removed the bsub output file existence check since it adds runtime
overhead and is not needed.
- Some more cosmetic changes
> [dvsim] Cosmetic updates to launcher methods

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
- hw/ip/keymgr/rtl/keymgr_reg_top.sv
> [keymgr] Actually increase salt / sw binding sizes

- hw/ip/pinmux/data/pinmux.hjson
- hw/ip/pinmux/data/pinmux.hjson.tpl
- hw/ip/pinmux/rtl/pinmux.sv
- hw/ip/pinmux/rtl/pinmux_strap_sampling.sv
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
> [pinmux] Add JTAG reset mux

- sw/device/tests/otbn/otbn_ecdsa_p256_test.c
The ECDSA signature verification step requires the R value as input.
In the OTBN test code, a signing is done followed by a verification.
Because the correct R value already exists in OTBN memory,
we get a successful signature verification. However when clearing
OTBN memory between the signing and verification step, the
verification step fails. Adding the R value to verification step
solves problem. Fix for #5626
Signed-off-by: Thomas Rosted Jensen <thomas@rosted.net>
> [otbn/sw] Add missing OTBN ECDSA sign R value to test verification

- sw/device/tests/aes_test.c
- sw/device/tests/dif/dif_aes_smoketest.c
> [sw] remove entropy_src work arounds for aes

- hw/ip/keymgr/dv/env/keymgr_env.core
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_random_vseq.sv
align with design change #5578
> [keymgr/dv] Update tb for wider salt and sw_binding

- hw/ip/tlul/rtl/tlul_pkg.sv
> [TLUL] Add ecc calculation functions

- hw/ip/otbn/doc/dv/index.md
- util/build_docs.py
Also fix up some stale text about how we generate binaries for
testing and remove some stale TODOs.
> [otbn,dv] Generate the OTBN testplan for documentation

- hw/ip/keymgr/rtl/keymgr_ctrl.sv
> [keymgr] Fix advance state consistency

- hw/ip/otbn/data/base-insns.yml
- hw/ip/otbn/data/bignum-insns.yml
- hw/ip/otbn/dv/otbnsim/sim/dmem.py
- hw/ip/otbn/dv/otbnsim/sim/insn.py
- hw/ip/otbn/dv/otbnsim/sim/isa.py
- hw/ip/otbn/dv/otbnsim/sim/sim.py
- hw/ip/otbn/dv/otbnsim/sim/state.py
- hw/ip/otbn/util/shared/insn_yaml.py
- hw/ip/otbn/util/yaml_to_doc.py
This is a prelude to changes to support the RND stalling behaviour.
> Otbn iss stall

- hw/ip/otbn/dv/rig/rig/gens/straight_line_insn.py
A previous version of the OTBN spec said that the instructions
BN.LID, BN.SID and BN.MOVR would just look at the bottom 5 bits of the
value of the GPR used to choose the WDRs they'd read or write. We're
changing the spec so that an invalid index causes an error; teach the
RIG about this to avoid generating lots of spurious streams.
Fixes #5731.
> [otbn] Teach RIG not to choose GPRs pointing at invalid WDRs

- hw/top_earlgrey/ip/ast/data/ast.hjson
- hw/top_earlgrey/ip/ast/doc/ast_regs.html
- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/ast_reg_pkg.sv
- hw/top_earlgrey/ip/ast/rtl/ast_reg_top.sv
> [AST] Add registers block to AST for OTP/ROM write checks

- util/reggen/top.py
- util/reggen/top_uvm_reg.sv.tpl
- util/topgen.py
Add a dict `attrs` in top to contain modules' attr
Update based on new reggen #5564, and close previous fix #5558
> [dv] Fix AST hdl path

- hw/ip/kmac/kmac_pkg.core
> [kmac] Add kmac_pkg.core

- util/build_docs.py
> [util] Fix some minor indent issues

- hw/ip/aes/dv/env/aes_env.core
- hw/ip/aes/dv/env/aes_env_cfg.sv
- hw/ip/aes/dv/env/aes_env_pkg.sv
- hw/ip/aes/dv/tb/tb.sv
added edn to AES DV this is a fairly small update adds the push pull agent and the end_if to aes dv
something was off with the first branch I couln't push updates it just claimed they where at the same level
> [aes/dv] added EDN to aes dv

- hw/ip/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv
> [otp_ctrl] Return bus errors when FSM is in error state

- hw/ip/clkmgr/clkmgr_components.core
- hw/ip/clkmgr/data/clkmgr.hjson.tpl
- hw/ip/clkmgr/data/clkmgr.sv.tpl
- hw/ip/clkmgr/data/clkmgr_pkg.sv.tpl
- hw/ip/clkmgr/rtl/clkmgr_byp.sv
- hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/clkmgr/clkmgr.core
- hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson
- hw/top_earlgrey/ip/clkmgr/lint/clkmgr.vlt
- hw/top_earlgrey/ip/clkmgr/lint/clkmgr.waiver
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr_pkg.sv
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr_reg_pkg.sv
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr_reg_top.sv
- hw/top_earlgrey/lint/top_earlgrey_lint_cfgs.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/top_earlgrey_asic.sv
- hw/top_earlgrey/rtl/top_earlgrey_nexysvideo.sv
- hw/top_earlgrey/rtl/top_earlgrey_verilator.sv
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- hw/top_englishbreakfast/rtl/top_englishbreakfast_cw305.sv
- util/topgen-fusesoc.py
Address #5566
Allow software to request for external clock during specific life cycle states.
> [top, clkmgr] Add external clock switch support

- azure-pipelines.yml
- ci/jobs/quick-lint.sh
- ci/scripts/mypy.sh
- hw/ip/otbn/dv/otbnsim/sim/dmem.py
- python-requirements.txt
This won't affect code that isn't written to use mypy (there's an opt-in list of directories where it should run).
> [ci] Add a mypy lint check for code that uses it

- hw/ip/otbn/doc/_index.md
The "Loop nesting" section in the OTBN documentation is targeting
programmers. Move it from the "Processor state" section to the
"Programmers guide" section.
> [otbn] Move loop nesting into programmers guide

- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv
This PR fixes regression ECC error. If there is an ACCESS ERROR, OTP
won't detect ECC error because the read is blocked.
> [dv/otp_ctrl] fix regression otp ecc error

- hw/ip/aes/rtl/aes_prng_masking.sv
- hw/ip/otbn/rtl/otbn_controller.sv
Just things I stumbled across today.
> Minor comment and style fixes

- hw/ip/kmac/rtl/keccak_round.sv
Fixes minor nits that cause Verilator lint errors.
> [kmac] Fix width mismatches in keccak_round.sv

- hw/ip/aon_timer/doc/_index.md
- hw/ip/aon_timer/doc/dv/domains.svg
- hw/ip/aon_timer/doc/dv/index.md
- hw/ip/aon_timer/doc/dv/tb.svg
This fills out the document template, describing the overall structure
of the DV environment and the rough plan of how things will work.
Details are likely to change as we come to implement the scoreboard
and test sequences.
> [aon_timer,dv] Initial DV document

- hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
> [dv/kmac] rework prefix calculation to fix #5755

- hw/ip/otp_ctrl/rtl/otp_ctrl_part_buf.sv
Solve issue #5870
Thanks Michael for the quick confirmation.
> [rtl/otp_ctrl] Fix otp_ctrl consistency check false alert

- hw/ip/keymgr/rtl/keymgr_ctrl.sv
> [keymgr] Treat operations as invalid during wipe

- hw/ip/rstmgr/data/rstmgr.hjson.tpl
- hw/ip/rstmgr/doc/_index.md
- hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson
- hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr_reg_pkg.sv
- hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr_reg_top.sv
- finish up documentation
- add regwen for debug dumping
> [rstmgr] clean-up for d2 preparation

- hw/dv/sv/push_pull_agent/push_pull_host_driver.sv
- hw/ip/entropy_src/data/entropy_src_testplan.hjson
- hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson
- hw/ip/entropy_src/dv/env/entropy_src_env.sv
- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
- hw/ip/entropy_src/dv/tests/entropy_src_base_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_rng_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_test.core
- hw/ip/entropy_src/dv/tests/entropy_src_test_pkg.sv
> [entropy_src/dv] Adding entropy_src_rng_test

- hw/formal/formal_conn.sh
This PR fixes connectivity script folder name and fix on auto-exit in GUI mode.
> [fpv] Fix connectivity script folder name

- hw/formal/tools/dvsim/common_formal_cfg.hjson
- hw/formal/tools/dvsim/formal.mk
- hw/formal/tools/jaspergold/fpv.tcl
- hw/formal/tools/jaspergold/jaspergold.hjson
- hw/lint/tools/ascentlint/parse-lint-report.py
- hw/lint/tools/dvsim/common_lint_cfg.hjson
- hw/lint/tools/dvsim/verilator.hjson
- hw/lint/tools/veriblelint/parse-lint-report.py
- hw/lint/tools/verilator/parse-lint-report.py
- hw/syn/tools/dvsim/common_syn_cfg.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- hw/top_earlgrey/dv/env/chip_env_cfg.sv
- hw/top_earlgrey/formal/top_earlgrey_fpv_cfgs.hjson
- hw/top_earlgrey/lint/top_earlgrey_fpv_lint_cfgs.hjson
- util/dvsim/Deploy.py
- util/dvsim/FormalCfg.py
- util/dvsim/Launcher.py
- util/dvsim/LsfLauncher.py
- util/dvsim/OneShotCfg.py
- util/dvsim/utils.py
These issues were found when adding support for the Google-internal cloud launcher.  Each unique and unrelated fix is made into its own commit.
> [dvsim] Minor fixes

- hw/ip/clkmgr/data/clkmgr.sv.tpl
- hw/ip/clkmgr/doc/_index.md
- hw/ip/clkmgr/rtl/clkmgr_byp.sv
- hw/top_earlgrey/ip/clkmgr/lint/clkmgr.vlt
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
- Add documentation on exteranl clock switch
- Add missing assertions
> [clkmgr] Cleanup for D2

- hw/ip/clkmgr/data/clkmgr.prj.hjson
- hw/ip/clkmgr/data/clkmgr.sv.tpl
- hw/ip/clkmgr/doc/_index.md
- hw/ip/clkmgr/doc/checklist.md
- hw/ip/clkmgr/rtl/clkmgr_byp.sv
- hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
First commit will be rebased away.
> [clkmgr] Advance to D2

- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
Two regression errors to fix:
1. LC_req regression failure: This is due to my previous
misunderstanding of PR #5433. I thought even if there are access errors,
LC partition will still do byte write for the non-error memory
addresses. Actually this PR only works for ECC correctable error.
2. This is a OTBN edn key mismatch. In current simulation, there won't
be more than 1 background check between reset and key request. However,
this won't work with stress_all test. Because stress_all test we
re-randomized the `do_apply_reset` bit.
The solution is to ignore any edn key request that could potentially
contain more than one background check, and use coverage to ensure the
key request is compared in scb.
> [dv/otp_ctrl] Fix regression failure

- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_lci.sv
> [otp_ctrl] correct state/counter address mapping

- util/dvsim/Deploy.py
- util/dvsim/LocalLauncher.py
- util/dvsim/utils_test.py
> [dvsim] Fix remaining comments  from #5876

- hw/ip/adc_ctrl/adc_ctrl.core
- hw/ip/adc_ctrl/rtl/adc_ctrl_core.sv
- hw/ip/lc_ctrl/lint/lc_ctrl.waiver
- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_dai.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_lci.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_buf.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv.tpl
- hw/ip/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv
- hw/ip/pattgen/pattgen.core
- hw/ip/prim_generic/rtl/prim_generic_otp.sv
- hw/ip/rv_timer/lint/rv_timer.waiver
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_combo.sv
- hw/ip/sysrst_ctrl/sysrst_ctrl.core
This cleans up a couple of ascentlint errors.
Note that some of the diffs are due to regeneration of the top.
> Ascentlint fixes

- hw/ip/rom_ctrl/rtl/rom_ctrl.sv
It seems that I managed one register top but not the other one, or the
SRAM adapter. Oops!
> [rom_ctrl] Hook up the other bus integrity error signals in rom_ctrl

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/entropy_src.core
- hw/ip/entropy_src/rtl/entropy_src_core.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
- hw/ip/entropy_src/rtl/entropy_src_repcnts_ht.sv
An additional symobl-based repetition count health test is added.
> [entropy_src/rtl] symbol-based repetition count health test

- hw/ip/pinmux/data/pinmux.hjson.tpl
- hw/ip/spi_device/rtl/spi_device.sv
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_pkg.sv
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_top.sv
Minor lint fixes. 
The pinmux fix might be in another PR already, so just let me know and I can take it out.
@eunchan I'm not really sure if the combo loop fix is right.  I think it makes sense, but you'll probably know best.
> [top] lint fixes

- hw/ip/csrng/rtl/csrng_block_encrypt.sv
Original equation reforming needed fixing.
> [csrng/rtl] correction for AES quiet equation

- hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
this PR increases the timeout period for the bijection test,
fixing some nightly regression timeout failures.
> [dv/sram] increase timeout for bijection test

- hw/ip/tlul/rtl/tlul_adapter_sram.sv
- output integrity error is persistent
- bus integrity error is transactional
> [tlul] Complete adapter sram todo's

- hw/ip/flash_ctrl/rtl/flash_phy_rd.sv
When buffer is not enabled, the flash_phy_rd may erroneously return data
to back to back transactions when it is not supposed to.
This happens because even when buffers are not enabled, the read data is
written into the holding FIFO between read and descramble stages.  As a
result, the return path falsely thinks the data is available and returns
it.
This causes an issue because even though the data is returned, the front door
logic has already created 2 transactions to the flash, and a result, we have
extra data returning.
The buffer not enabled case can be caused by otp_ctrl not returning the
flash controller's request for a key.  This in turn can happen because
entropy is not yet enabled.  This latter point deserves a wider discussion
as to the right solution.
To fix this, the forward …
> [flash_ctrl] Correct behavior when buffer not enabled.

- hw/dv/sv/cip_lib/cip_base_env_cfg.sv
- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
- hw/dv/sv/dv_lib/dv_base_env_cfg.sv
- hw/ip/adc_ctrl/dv/env/adc_ctrl_scoreboard.sv
- hw/ip/aes/dv/env/aes_scoreboard.sv
- hw/ip/alert_handler/dv/env/alert_handler_scoreboard.sv
- hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv
- hw/ip/clkmgr/dv/env/clkmgr_scoreboard.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/edn/dv/env/edn_scoreboard.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv
- hw/ip/gpio/dv/env/gpio_scoreboard.sv
- hw/ip/hmac/dv/env/hmac_scoreboard.sv
- hw/ip/i2c/dv/env/i2c_scoreboard.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
- hw/ip/pwm/dv/env/pwm_scoreboard.sv
- hw/ip/rv_timer/dv/env/rv_timer_scoreboard.sv
- hw/ip/spi_device/dv/env/spi_device_scoreboard.sv
- hw/ip/spi_host/dv/env/spi_host_scoreboard.sv
- hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
- hw/ip/uart/dv/env/uart_scoreboard.sv
- hw/ip/usbdev/dv/env/usbdev_scoreboard.sv
- util/uvmdvgen/scoreboard.sv.tpl
Update mem/csr and tl_err seq to support multi-ral
Update scb for tl_err with multi_ral
Need to merge #5951 first
> [dv] Support multi-ral (part 3)

- hw/ip/rom_ctrl/doc/_index.md
- hw/ip/rom_ctrl/doc/connections.svg
- hw/ip/rom_ctrl/doc/rom_check_fsm.svg
- hw/ip/rom_ctrl/doc/rom_ctrl_blockdiag.svg
- util/build_docs.py
This commit adds a technical specification and wires it into
`build_docs.py` so that it appears in the documentation.
> [rom_ctrl] Initial technical specification

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
- hw/dv/sv/dv_lib/dv_base_env_cfg.sv
The failure is due to #5991
Thanks @cindychip for finding this
> [dv] Fix tl_error failure

- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/dv/tb/tb.sv
- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_pkg.sv
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_top.sv
- hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.hjson
- hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_nexysvideo.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey_pkg.sv
- hw/top_earlgrey/sw/autogen/top_earlgrey.h
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- util/topgen/templates/chiplevel.sv.tpl
> [top] Connect raw pad outputs to ast

- hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
this PR adds support to the mem_bkdr_if for parity error injection.
this is done by flipping a single bit in the byte data and backdoor
writing this corrupted data after calculating the parity based off of
the uncorrupted data value.
note that parity error injection will only work if the `MEM_PARITY`
parameter is enabled.
> [dv/mem_bkdr_if] inject parity errors

- hw/top_earlgrey/rtl/autogen/chip_earlgrey_nexysvideo.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- util/topgen/templates/chiplevel.sv.tpl
- util/topgen/templates/toplevel.sv.tpl
> [top] Turn on secure ibex for asic

- hw/ip/edn/rtl/edn_core.sv
- hw/ip/prim_generic/lint/prim_generic_pad_wrapper.waiver
- hw/ip/prim_generic/rtl/prim_generic_pad_wrapper.sv
- hw/ip/spi_device/rtl/spi_device.sv
- hw/ip/sram_ctrl/rtl/sram_ctrl.sv
- hw/top_earlgrey/lint/top_earlgrey.waiver
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey_pkg.sv
- hw/top_earlgrey/rtl/padring.sv
- util/topgen/templates/chiplevel.sv.tpl
- util/topgen/templates/toplevel.sv.tpl
- util/topgen/templates/toplevel_pkg.sv.tpl
See individual commits for more information.
> [Various] lint fixes

- hw/ip/otbn/doc/_index.md
- hw/ip/otbn/dv/tracer/rtl/otbn_trace_if.sv
- hw/ip/otbn/rtl/otbn_alu_bignum.sv
- hw/ip/otbn/rtl/otbn_controller.sv
- hw/ip/otbn/rtl/otbn_core.sv
> [otbn] Clear CSRs/WSRs to 0 on start

- hw/ip/edn/lint/edn.waiver
> [edn/lint] removing arbiter related lint msgs

- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- util/topgen/templates/chiplevel.sv.tpl
> [top] update ast connections

- hw/ip/kmac/dv/env/kmac_scoreboard.sv
this PR fixes recent failures in the `kmac_smoke_test` in nightly regressions.
specifically, these failures were all subtle edge cases relating to msgfifo/prim_packer flush transitions that all found their way through existing scb logic.
> [dv/kmac] fix kmac_smoke nightly failures

- hw/ip/kmac/lint/sha3.waiver
> [sha3/lint] added waivers for sha3 lint msgs

- hw/lint/doc/README.md
This readme covers local runs only, hence the added switch.
> [lint/docs] Update ascentlint dvsim command in readme

- util/dvsim/Launcher.py
Signed-off-by: Eunchan Kim <eunchan@opentitan.org>
> [dvsim] Fix local run error.

- hw/ip/spi_host/data/spi_host.hjson
- hw/ip/spi_host/doc/_index.md
- hw/ip/spi_host/rtl/spi_host.sv
- hw/ip/spi_host/rtl/spi_host_byte_merge.sv
- hw/ip/spi_host/rtl/spi_host_byte_select.sv
- hw/ip/spi_host/rtl/spi_host_cmd_pkg.sv
- hw/ip/spi_host/rtl/spi_host_command_cdc.sv
- hw/ip/spi_host/rtl/spi_host_core.sv
- hw/ip/spi_host/rtl/spi_host_data_cdc.sv
- hw/ip/spi_host/rtl/spi_host_fsm.sv
- hw/ip/spi_host/rtl/spi_host_reg_pkg.sv
- hw/ip/spi_host/rtl/spi_host_reg_top.sv
- hw/ip/spi_host/rtl/spi_host_shift_register.sv
- hw/ip/spi_host/rtl/spi_host_window.sv
- hw/ip/spi_host/spi_host.core
Initial implementation of SPI host core and CDCs
This PR contains three commits:
1. Changes to the HJSON that arose due to implementation complexities
2. An autogen commit
3. The SPI_HOST implementation RTL
At the time of this PR there are no verilator warnings from this commit, all widths, assignments, and unused signal warnings have been checked.
> [spi_host] Initial Core Implementation

- hw/ip/edn/dv/edn_sim_cfg.hjson
- hw/ip/edn/dv/env/edn_env_cfg.sv
- hw/ip/edn/dv/env/edn_env_pkg.sv
- hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv
- hw/ip/edn/dv/tests/edn_base_test.sv
- hw/ip/edn/dv/tests/edn_smoke_test.sv
- hw/ip/edn/dv/tests/edn_test.core
- hw/ip/edn/dv/tests/edn_test_pkg.sv
> [edn/dv] Added cfg variables/knobs

- hw/top_earlgrey/formal/conn_csvs/top_earlgrey_conn.csv
> [dv/clkmgr] Adds connectivity to be formally checked.

- hw/syn/README.md
- hw/syn/tools/dc/run-syn.tcl
- The steps are still pretty manual and not ideal, but at least we can do it for now.
- Long term it may be good to have this built directly into dvsim with some kind of -interactive command.
> [tools] simple instructions for interactive synth

- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_autoblock.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_combofsm.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_keyfsm.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_timerfsm.sv
Signed-off-by: Eric Shiu <eshiu@google.com>
> [sysrst_ctrl] cleaned up unused lint errors

- hw/ip/aes/lint/aes.waiver
- hw/ip/lc_ctrl/lint/lc_ctrl.waiver
- hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
- hw/ip/prim/lint/prim_clock_div.waiver
- hw/ip/prim/lint/prim_flop_en.waiver
- hw/ip/prim/lint/prim_pad_attr.waiver
- hw/ip/prim/prim_pad_attr.core
- hw/ip/prim_generic/rtl/prim_generic_usb_diff_rx.sv
- hw/ip/pwm/rtl/pwm_cdc.sv
- hw/ip/pwm/rtl/pwm_core.sv
- hw/ip/rv_dm/lint/rv_dm.waiver
- hw/ip/spi_device/lint/spi_device.waiver
- hw/ip/spi_device/rtl/spi_fwmode.sv
- hw/ip/spi_host/rtl/spi_host.sv
- hw/ip/spi_host/rtl/spi_host_byte_select.sv
- hw/ip/spi_host/rtl/spi_host_command_cdc.sv
- hw/ip/spi_host/rtl/spi_host_core.sv
- hw/ip/spi_host/rtl/spi_host_data_cdc.sv
- hw/ip/spi_host/rtl/spi_host_fsm.sv
- hw/ip/spi_host/rtl/spi_host_window.sv
- hw/top_earlgrey/lint/padring.waiver
- hw/top_earlgrey/padring.core
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_englishbreakfast/lint/padring.waiver
- util/topgen/templates/chiplevel.sv.tpl
This is a first pass of lint fixes and adding waivers.
More to come...
> [lint] Lint fixes waivers

- hw/syn/tools/dc/run-syn.tcl
- hw/top_earlgrey/syn/asic.constraints.sdc
> [sdc] Correct the clock group constraint

- hw/dv/sv/csrng_agent/csrng_agent.sv
- hw/dv/sv/csrng_agent/csrng_agent_cfg.sv
- hw/dv/sv/csrng_agent/csrng_if.sv
- hw/dv/sv/csrng_agent/csrng_monitor.sv
- hw/dv/sv/csrng_agent/csrng_sequencer.sv
- hw/ip/csrng/dv/csrng_sim_cfg.hjson
- hw/ip/csrng/dv/env/csrng_env.core
- hw/ip/csrng/dv/env/csrng_env.sv
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_virtual_sequencer.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_smoke_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_vseq_list.sv
- hw/ip/csrng/dv/tb.sv
- hw/ip/csrng/dv/tests/csrng_base_test.sv
- hw/ip/csrng/dv/tests/csrng_cmds_test.sv
- hw/ip/csrng/dv/tests/csrng_smoke_test.sv
- hw/ip/csrng/dv/tests/csrng_test.core
- hw/ip/csrng/dv/tests/csrng_test_pkg.sv
> [csrng/dv] Added initial csrng_cmds test

- hw/ip/rstmgr/rtl/rstmgr_ctrl.sv
> [rstmgr] Correctly connect scan bypassed reset

- hw/ip/keymgr/doc/dv/index.md
- hw/ip/kmac/doc/dv/index.md
- hw/ip/lc_ctrl/doc/dv/index.md
- hw/ip/otp_ctrl/doc/dv/index.md
- hw/ip/sram_ctrl/doc/dv/index.md
- util/uvmdvgen/index.md.tpl
This PR fixes a missing ")" in dv doc and template.
> [dv/doc] Minor fix on dv_doc

- util/dvsim/LauncherFactory.py
> [dvsim] update edacloudlauncher imports

- hw/ip/pwrmgr/data/pwrmgr.hjson.tpl
- hw/ip/pwrmgr/pwrmgr.core
- hw/ip/pwrmgr/rtl/pwrmgr.sv
- hw/ip/pwrmgr/rtl/pwrmgr_cdc.sv
- hw/ip/pwrmgr/rtl/pwrmgr_fsm.sv
- hw/ip/pwrmgr/rtl/pwrmgr_pkg.sv
- hw/ip/rom_ctrl/rtl/rom_ctrl_pkg.sv
- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- util/topgen/templates/toplevel.sv.tpl
- connect rom_ctrl check output into pwrmgr
- if check is successful, pwrmgr allows cpu to execute
- FI hardening to follow later
> [rom_ctrl, pwrmgr, top] Connect rom_ctrl check into pwrmgr

- hw/ip/rom_ctrl/data/rom_ctrl.hjson
- hw/syn/tools/dc/run-syn.tcl
- hw/syn/tools/dvsim/common_syn_cfg.hjson
- hw/syn/tools/dvsim/dc.hjson
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_nexysvideo.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/syn/chip_earlgrey_asic_syn_cfg.hjson
- util/topgen/templates/chiplevel.sv.tpl
`SkipCheck` is currently set to 1.
> [top] hook-up rom_ctrl to kmac

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/rtl/entropy_src_core.sv
- hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/lib/dif/dif_entropy.c
- sw/device/tests/dif/dif_entropy_smoketest.c
- test/systemtest/config.py
- for now do not disable boot bypass as it causes boot health checks to get stuck
> [entropy_src] add smoketest back to CI

- hw/dv/sv/cip_lib/cip_base_env.sv
- hw/dv/sv/cip_lib/cip_base_env_cfg.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
fix all ral models connected to the same adapter
and fix shadow reg ony from defaul ral and a similar issue in mem test
> [dv] fix some multi-ral issues

- hw/ip/otbn/dv/otbnsim/sim/state.py
- hw/ip/otbn/dv/otbnsim/sim/wsr.py
> [otbn] Fix flake8 lint issues

- util/reggen/fpv_csr.sv.tpl
This PR has a few improvement regarding csr assertions:
1. Reduce exp_vals size as Issue #5583 recommanded.
2. Constrain a_source value to avoid FPV running for too long
> [fpv/csr_assert] Improve CSR assertions

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/tb.sv
- hw/ip/keymgr/keymgr.core
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_kmac_if.sv
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
Only the second commit is valid.
> [keymgr, rom_ctrl] Hookup rom_ctrl digest to keymgr

- hw/ip/csrng/rtl/csrng_block_encrypt.sv
- hw/ip/csrng/rtl/csrng_cmd_stage.sv
- hw/ip/csrng/rtl/csrng_core.sv
- hw/ip/csrng/rtl/csrng_ctr_drbg_gen.sv
- hw/ip/csrng/rtl/csrng_ctr_drbg_upd.sv
- hw/ip/csrng/rtl/csrng_main_sm.sv
- hw/ip/csrng/rtl/csrng_state_db.sv
- hw/ip/edn/rtl/edn_ack_sm.sv
- hw/ip/edn/rtl/edn_core.sv
- hw/ip/entropy_src/data/entropy_src.hjson
The module enable is used for halt the edn and csrng such that is acts like a reset.
> [edn/csrng/rtl] fixes #5941

- hw/ip/aes/dv/cov/aes_cov_if.sv
- hw/ip/csrng/dv/tb.sv
- hw/ip/entropy_src/dv/tb/tb.sv
- hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
- hw/ip/kmac/dv/tb.sv
- hw/ip/lc_ctrl/dv/tb.sv
- hw/ip/otp_ctrl/dv/tb.sv
These are longer than 100 characters. Wrap as necessary to get them
below (to allow us to start checking for this with Verible lint).
> [dv] Break various long lines in DV code

- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- util/topgen/templates/toplevel.sv.tpl
> [ibex] Connect dft bypass controls

- util/dvsim/SimCfg.py
The DV Summary report is located here:
https://reports.opentitan.org/hw/top_earlgrey/dv/summary.html
The header row is skewed by 1 to the right and the center alignment is
broken. This commit fixes it.
> [dvsim] Fix column bug in DV summary report

- hw/ip/clkmgr/data/clkmgr_testplan.hjson
Adds a few more entries in the test plan.
> [dv/clkmgr] Expands test plan.

- hw/ip/kmac/rtl/kmac_entropy.sv
This commit revises entropy module FSM encoding into sparse encoding
with `util/design/sparse-fsm-encode.py`.
> [kmac] Convert entropy fsm to sparse encode

- hw/syn/README.md
> [syn] Add some more example commands to the readme

- hw/ip/tlul/rtl/tlul_adapter_sram.sv
> [rtl/tlul_adapter_sram] fix bug with ifetch enable

- hw/dv/sv/csrng_agent/csrng_if.sv
Take 2, after the approach in #6254 turned out to be a bit silly.
> [csrng,dv] Whitespace shuffling to avoid >100 character lines

- hw/ip/pinmux/pinmux.core
- hw/ip/pinmux/pinmux_reg.core
- hw/ip/pinmux/syn/constraints.sdc
- hw/ip/pinmux/syn/pinmux_syn_cfg.hjson
- hw/top_earlgrey/ip/ast/ast.core
- hw/top_earlgrey/ip/pinmux/pinmux_reg.core
- hw/top_earlgrey/lint/top_earlgrey_lint_cfgs.hjson
- hw/top_earlgrey/top_earlgrey.core
> [pinmux] Add block level synth setup

- hw/top_earlgrey/ip/ast/rtl/ast.sv
> [AST] Fix analog out contention

- hw/ip/pwrmgr/data/pwrmgr.prj.hjson
- hw/ip/pwrmgr/doc/checklist.md
> [pwrmgr] advance to d2

- sw/device/sca/aes_serial.c
- sw/device/sca/meson.build
Switch to SCA simple serial to use AES DIF.
> [sw/sca] Switch AES to use dif_aes

- hw/ip/flash_ctrl/data/flash_ctrl.prj.hjson
- hw/ip/flash_ctrl/doc/checklist.md
> [flash] Advance to d2

- util/reggen/ip_block.py
This fixes the chip level nightly breakage.
> [reggen] Prefer explicit utf-8 encoding

- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl
This PR temp fixes CI failure on PR #6314. We will discuss further if
this behavior is intended. Thanks @tjaychen for finding this.
> [dv/otp_ctrl] Temp fix CI issue

- hw/ip/otbn/rtl/otbn_lsu.sv
Previously the LSU relied upon the controller keeping the incoming
address stable the cycle following a load request so base word loads
could select the correct word from the WLEN data. When the load uses the
call stack as a base address register this is violated. Flopping the
bits for the word select avoids the need for the controller to keep the
address stable.
Fixes #6295
> [otbn] Flop address bits to select 32-bit word in LSU

- hw/vendor/lint/pulp_riscv_dbg.vlt
> [dm] Waive unused bits of addr_i input to debug_rom

- hw/ip/csrng/data/csrng.hjson
- hw/ip/csrng/rtl/csrng_core.sv
- hw/ip/csrng/rtl/csrng_reg_pkg.sv
- hw/ip/csrng/rtl/csrng_reg_top.sv
Moving REGWEN to an HW-based implemenation.
> [csrng/rtl] REGWEN is rtl based

- hw/ip/sysrst_ctrl/data/sysrst_ctrl.hjson
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr.hjson
- hw/top_earlgrey/ip/pwrmgr/rtl/autogen/pwrmgr_reg_pkg.sv
- hw/top_earlgrey/ip/pwrmgr/rtl/autogen/pwrmgr_reg_top.sv
- hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson
- hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr_reg_pkg.sv
- hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr_reg_top.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/sw/autogen/top_earlgrey.h
- sw/device/lib/dif/dif_pwrmgr.c
- sw/device/lib/dif/dif_pwrmgr.h
- sw/device/lib/dif/dif_pwrmgr_unittest.cc
- sw/device/lib/dif/dif_rstmgr.h
- sw/device/tests/dif/dif_pwrmgr_smoketest.c
Integrate `sysrst_ctrl` with `pwrmgr/rstmgr`
> [top] Integrate sysrst_ctrl to pwrmgr/rstmgr

- hw/ip/kmac/dv/env/kmac_scoreboard.sv
this PR contains several fixes for the KMAC cycle accurate model:
- most are related to KDF transactions, in particular backpressure
scenarios where the msgfifo fills up while KDF transactions are still
being continually sent to the DUT.
- fixed a potential race condition where `fifo_empty` could be sampled
on the same timestep that it is updated internally
> [dv/kmac] cycle-accurate model bugfixes - pt 1

- sw/device/lib/dif/dif_kmac.h
Update the result types used by the KMAC DIF to follow the latest
guidance.
> [sw, dif_kmac] Simplify KMAC DIF result types

- hw/ip/otbn/doc/dv/index.md
This text should eventually be the thing that gets signed off as
describing all the relevant coverage points. We'll either keep this
document, and connect it up to automatic coverage collection, or move
the guts of this document somewhere else when there's a better place
for it.
So far, there are a couple of general notes, plus some
specific (architectural) coverage points for the base instruction set.
This works towards #5959 (but I ended up doing things in a slightly different order from what I expected). Still probably better to mark this as fixes #5959, and then separately track groups of functional coverage that need defining.
> [otbn] Some initial notes about functional coverage

- .github/CODEOWNERS
- COMMITTERS
Thanks @gkelly and @sjgitty for all your contributions!
> [github] Remove gkelly and sjgitty from CODEOWNERS and COMMITTERS

- hw/ip/spi_device/rtl/spi_passthrough.sv
This commit revises the CSb output signal's clock domain. It was
originally latched by the posedge of SCK.
> [spi_device] csb_deassert latched in clk_out_i

- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
This PR fixes a corner case on regression: The status is checked during
lc_program_req, and we could not accurate predict in scb if the error is
expected. I added a logic to ignore the checking whe lc_program_req is
in progress.
> [dv/otp_ctrl] regression corner case fix

- hw/ip/kmac/dv/env/kmac_scoreboard.sv
this PR fixes some issues in the cycle accurate model:
- data overflow during msgfifo flushing
- use a nonblocking forked process to update fifo_empty interrupt
as if it is blocking we can miss updates to the fifo pointers
and cause weird errors later in simulation
> [dv/kmac] cycle-accurate model bugfixes - pt 2

- hw/top_earlgrey/ip/ast/ast.core
- hw/top_earlgrey/ip/ast/rtl/aon_osc.sv
- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv
- hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv
- hw/top_earlgrey/ip/ast/rtl/io_osc.sv
- hw/top_earlgrey/ip/ast/rtl/sys_osc.sv
- hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- util/topgen/templates/chiplevel.sv.tpl
> [AST] Alerts and ast_init_done_o

- hw/syn/README.md
> [syn] Add additional instructions

- hw/ip/flash_ctrl/rtl/flash_phy_scramble.sv
- Do not allow key changes to happen during a transaction
as this can lead to timing issues.
- Technically we do not care if the results become garbage, but
this forces synthesis to work harder than necessary
- Another alternative is to explicitly false path, but this change
is small and touches fewer things.
> [flash_ctrl] Update key change timing for scramble

- hw/ip/flash_ctrl/data/flash_ctrl.prj.hjson
> [flash_ctrl] Forgot to update design stage to D2

- hw/ip/flash_ctrl/rtl/flash_phy.sv
- hw/ip/otp_ctrl/data/otp_ctrl.hjson
- hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl
- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
- hw/ip/prim_generic/prim_generic_flash.core
- hw/ip/prim_generic/rtl/prim_generic_flash.sv
- hw/ip/prim_generic/rtl/prim_generic_otp.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- util/reggen/ip_block.py
- util/topgen/templates/toplevel.sv.tpl
This matches the latest foundry release from Nuvoton.
> [flash / otp] Updates to match silver release

- hw/ip/spi_host/rtl/spi_host_fsm.sv
Cleans up a problem discussed in a similar PR #6326 
The `spi_host` register `cmd_len_q` is never used and gets optimized away at synthesis. This commit explicitly
removes that register (and comments the code as such) to clean up the logs.
> [ spi_host ] Remove cmd_len_q register to clean up DC logs

- sw/otbn/code-snippets/p384.s
- sw/otbn/code-snippets/p384_ecdsa_sign_test.s
- sw/otbn/code-snippets/rules.mk
Adds subroutine for ECDSA signature generation + test
This finishes #5940
> [otbn] add ECDSA signature generation subroutine

- hw/ip/lc_ctrl/dv/env/lc_ctrl_env_pkg.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_if.sv
- hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_smoke_vseq.sv
This PR enhances LC_ctrl token by:
1. Add a checking in scb.
2. Move some common functions to lc_ctrl_env_pkg so we can shared among
other compononent.
> [dv/lc_ctrl] lc_ctrl token enhancement

- hw/ip/lc_ctrl/dv/env/lc_ctrl_env.core
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_base_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_common_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_errors_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_smoke_vseq.sv
- hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_vseq_list.sv
- hw/ip/lc_ctrl/dv/lc_ctrl_sim_cfg.hjson
This PR adds the lc token mismatch error sequence.
> [dv/lc_ctrl] Add lc_token mismatch error

- hw/ip/kmac/dv/env/kmac_scoreboard.sv
this PR fixes a subtle edge case bug with small input message sizes
(less than 8 bytes) in KMAC mode where:
- CmdProcess is seen the cycle after prefix and keys finish processing
- fifo write pointer increments on same cycle
> [dv/kmac] cycle accurate model bugfixes - pt 4

- util/uvmdvgen/uvmdvgen.py
The positional argument should name an ip, not the path to it.
> [dv/uvmdvgen] Flag error for paths in block name

- util/dvsim/SimCfg.py
Within each bucket collect failures per unqualified test name.
Cap the failures shown to 5 per unqualified test name.
Show the number of failures per bucket and per test.
Use a trailing backslash to separate the line and log info from the
qualified test name.
> [dv/dvsim] Group failures per test in buckets

- hw/ip/otbn/rtl/otbn_controller.sv
This refactors the use of `rd_base_rd_commit_o` vs `rd_base_rd_en_a_o`
and `rd_base_en_b_o`. Previously for any instruction that was stalled,
`rd_base_en_a_o` and `rd_base_en_b_o` would remain asserted for the
whole instruction, with `rd_base_rd_commit_o` used to indicate the cycle
the read actually occurred (in particular when to pop the call stack if
`x1` was being a read).
This caused an issue with `call_stack_err_o` as it doesn't factor in
`rd_base_rd_commit_o` to avoid a combinational loop. `call_stack_err_o`
could be asserted the second cycle of a load or store where
`rd_base_commit_o` isn't asserted but `rd_base_en_a_o` or
`rd_base_en_b_o` could be.
Now `rd_base_en_a_o` and `rd_base_en_b_o` will only be asserted the
cycle the read actually occurrs, assuming no errors. …
> [otbn] Fix error when using the last x1 value as a base address

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_multi_vseq.sv
It's probably better to set the variable before trying to print it
out...
> [otbn,dv] Fix debug print line

- hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
> [mem_bkdr_if] fix the ecc_read() return types

- hw/dv/sv/jtag_agent/jtag_agent_pkg.sv
- hw/dv/sv/jtag_agent/jtag_if.sv
- hw/dv/sv/jtag_agent/jtag_monitor.sv
This PR addes support for the jtag agent monitor.
> [dv/jtag] add jtag_agent monitor

- hw/top_earlgrey/ip/ast/rtl/ast.sv
Signed-off-by: Arnon Sharlin <arnon.sharlin@opentitan.org>
> [ast] fixed ifdef typo in ast2pad outputs

- hw/ip/rom_ctrl/rtl/rom_ctrl_counter.sv
Split up the `always_ff` blocks to match "industry standard"
style (where we don't trust our synthesis tools to spot clock enables
properly).
Also, change the trivial `always_comb` block into a bunch of assigns.
> [rom_ctrl] Minor style changes in rom_ctrl code

- hw/ip/otbn/doc/dv/index.md
> [otbn] Add coverage points in the DV plan for big number ISA

- hw/ip/otbn/dv/otbnsim/sim/insn.py
> [otbn] Fix incorrect handling of negative JAL offset in ISS

- hw/dv/sv/mem_bkdr_if/mem_bkdr_if.sv
This function re-uses much of the SRAM scrambling logic, but is slightly
different due to the ROM using ECC rather than byte parity.
> [dv/mem_bkdr_if] Add scrambled ROM read function

- hw/ip/adc_ctrl/data/adc_ctrl.prj.hjson
- hw/ip/flash_ctrl/data/flash_ctrl.prj.hjson
- hw/ip/sysrst_ctrl/data/sysrst_ctrl.prj.hjson
- hw/ip/usbdev/data/usbdev.prj.hjson
Clarify DV on some blocks have not yet begun due to pending resource
allocation.
> [hw dashboard] Clarify status of some IPs

- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
This PR fixes a regression corner case where lc_esc signal is issued
during otp_init. Then scb predicted the wrong digest CSR values.
The solution is to ignore checking digest CSRs if this case happened,
because scb cannot accurately predict how many partitions have finished
inialization when lc_esc comes.
> [dv/otp_ctrl] Fix regression error

- hw/ip/otbn/dv/otbnsim/sim/insn.py
- hw/ip/otbn/dv/otbnsim/sim/loop.py
- hw/ip/otbn/dv/otbnsim/sim/sim.py
- hw/ip/otbn/dv/otbnsim/sim/state.py
- hw/ip/otbn/dv/otbnsim/sim/stats.py
- hw/ip/otbn/dv/otbnsim/standalone.py
- hw/ip/otbn/dv/otbnsim/stepped.py
- hw/ip/otbn/dv/otbnsim/test/simple_test.py
- hw/ip/otbn/dv/otbnsim/test/state_test.py
- hw/ip/otbn/dv/otbnsim/test/stats_test.py
- hw/ip/otbn/dv/otbnsim/test/testutil.py
- hw/ip/otbn/util/docs/get_impl.py
A large set of small changes to improve otbnsim in various ways. These are random things I found when trying to generate more statistics from simulation runs. (The actual PR implementing that will come shortly after a bit more testing.)
Please have a look at the individual commit messages for more details.
> [otbnsim] Assorted improvements

- hw/ip/otbn/dv/otbnsim/sim/stats.py
- hw/ip/otbn/dv/otbnsim/test/stats_test.py
*Note: Only the last commit in the series matters for this PR, everything else is already covered by #6591.*
Calculate the length of basic blocks and extended basic blocks and
present the findings as histogram when asked to dump statistics about
the execution.
Also include unit tests to check the counting behavior on small
examples.
Example:
```
$ hw/ip/otbn/dv/otbnsim/standalone.py build-out/sw/otbn/rsa_1024_enc_test.elf --dump-stats=-
[some output omitted]
Basic block statistics
----------------------
Number of instructions within a basic block
-------------  -----------
1         3250
2         2367
3         6274
4           40
5         6720
6         1381
7         1362
8            3
9           84
10         2049
12            1
13          255
17          757
Number of …
```
> [otbnsim] Collect statistics about basic blocks

- hw/dv/sv/csrng_agent/csrng_if.sv
- hw/dv/sv/csrng_agent/csrng_item.sv
- hw/ip/csrng/dv/env/csrng_env_pkg.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
- hw/ip/csrng/dv/tb.sv
Implemented NIST algorithms in sequences to verify, but will be moving prediction to scoreboard.
> [csrng/dv] Verifying csrng_cmds, aes_disabled

- hw/ip/otp_ctrl/rtl/otp_ctrl_kdi.sv
> [otp_ctrl] Make sure KDI observes EDN req/ack protocol at all times

- doc/ug/design.md
This updates the project lint guidance per [this document](https://docs.google.com/document/d/1t_hR5z5JbVwVdGjD9hczf_VVVxe9nFtue2Um0j15oFA/).
> [doc/lint] Update lint guidance

- util/verible-format.sh
This slightly modifies the `verible-format.sh` helper script and adds an option to specify individual files.
> [verible] Add option to run on specified files to verible-format.sh

- util/build_docs.py
This commit adds an additional --bind-wan argument to build_docs.py.
This forces the hugo server to bind the http server a port on the global
interface (as opposed to just on localhost, which is the default).
For other use unforeseen use-cases this also adds a `--hugo-opts` option to pass additional arguments directly to hugo.
This is important when using hugo on build farms with older (or no) browser
support, and no support for ssh tunneling.
> [ doc, build_doc ] Optionally bind to global wan when previewing

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
This PR fixes the following issue:
```
while (var > 0) begin
fork
do_something();
if (read_mem) begin
var --;
end
join_none
wait_outstanding_access();
end
```
If `var` is small, it will cause var underflow. (In otp_ctrl case, the var is 15)
So I reverted the logic back to use `repeat(var)`. Originally, the code was 
changed to while loop with the concern that memory is too small and does
not have enough mem_read. So here I added a `min_accesses`.
> [dv/mem_partial_access] Fix fork join_none inside while loop issue

- hw/ip/pwm/data/pwm.prj.hjson
> [pwm, doc] Fix paths of pwm documents

- ci/scripts/verible-format.sh
> [format/ci] Correct Verible format CI cmd

- util/device_sw_utils/extract_sw_logs.py
> Handle ro_data not ending with NUL properly in extract_sw_logs.py

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
this PR updates how the tl_errors_vseq enables and disable TL assertions
to correctly support multi-RAL IP blocks.
Currently there are race conditions where one thread may disable the
assertions, but another thread may enable them right afterwards, which
causes constant assertion errors.
We also add a call to wait_no_outstanding_access() at the end to prevent
any race conditions there as well (with nonblocking accesses).
> [dv/tl_errors] enable tl assertions correctly

- hw/ip/otp_ctrl/data/otp_ctrl_testplan.hjson
This PR updates the otp_ctrl's testplan for V2 review.
> [dv/otp_ctrl] Update testplan for V2 review

- hw/ip/hmac/lint/hmac.vlt
- hw/ip/hmac/rtl/sha2.sv
Waived a lint warning of verilator and fixed errors of ascentlint.
> [hmac] Lint fix

- hw/ip/otp_ctrl/data/otp_ctrl_testplan.hjson
This PR adds functional coverage plan to the OTP_CTRL testplan.
> [dv/otp_ctrl] Add functional coverage plan

- hw/top_earlgrey/data/chip_testplan.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
Review notes are captured here:
This first round of reviews focused on UART, GPIO, HMAC and the PLIC
blocks.
This PR contains updates based on review feedback in addition to some
minor fixes.
> [chip testplan] Updates based on initial review

- hw/ip/otbn/doc/dv/index.md
These address on follow-up comments to PR #6491 (which came in after
the PR was merged).
> [otbn,dv] Updates to planned fcov for BN instruction set

- hw/ip/spi_device/lint/spi_device.waiver
- hw/ip/spi_device/rtl/spi_cmdparse.sv
> [spi_device/lint] Fix unused assignments and remove waivers

- hw/ip/rom_ctrl/data/rom_ctrl_testplan.hjson
- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov.core
- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_bind.sv
- hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_if.sv
- hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv
- hw/ip/rom_ctrl/dv/rom_ctrl_sim.core
- hw/ip/rom_ctrl/dv/rom_ctrl_sim_cfg.hjson
First commit addresses a minor lint issue
Second commit adds functional coverage to the testplan and implements it.
> [rom_ctrl/dv] Add functional coverage

- hw/ip/csrng/rtl/csrng_block_encrypt.sv
- hw/ip/csrng/rtl/csrng_cmd_stage.sv
- hw/ip/csrng/rtl/csrng_core.sv
- hw/ip/csrng/rtl/csrng_ctr_drbg_cmd.sv
- hw/ip/csrng/rtl/csrng_ctr_drbg_gen.sv
- hw/ip/csrng/rtl/csrng_state_db.sv
Fixes rtl problems that now enable instantiate and generate to work.
> [csrng/rtl] instantiate and generate bug fixes

- hw/ip/otbn/dv/model/otbn_model.cc
- hw/ip/otbn/dv/tracer/rtl/otbn_trace_if.sv
- hw/ip/otbn/rtl/otbn.sv
- hw/ip/otbn/rtl/otbn_alu_bignum.sv
- hw/ip/otbn/rtl/otbn_lsu.sv
- hw/ip/otbn/rtl/otbn_pkg.sv
- hw/ip/otbn/rtl/otbn_rf_base.sv
- hw/ip/otbn/rtl/otbn_rf_bignum.sv
- hw/ip/otbn/rtl/otbn_start_stop_control.sv
This keeps creeping in: maybe we need a CI job :-)
> [otbn] Fix spelling of separate

- util/dvsim/Testplan.py
- A small fix to allow testplans to be recursively imported.
- Useful for the foundry repo to import the chip level testplan (which
imports other sub-testplans).
> [dvsim] Allow recursive testplan import

- .svlint.toml
Updated [svls](https://github.com/dalance/svls) and corresponding [svlint](https://github.com/dalance/svlint) .
> [svls] Update svlint/ svls rule to latest

- hw/ip/otbn/doc/dv/index.md
- hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv
- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
- hw/ip/otbn/dv/uvm/env/otbn_trace_item.sv
- hw/ip/otbn/dv/uvm/env/otbn_trace_monitor.sv
- hw/ip/otbn/dv/uvm/otbn_model_agent/otbn_model_monitor.sv
There are a couple of helper commits first, but the big change is the last commit in the PR.
> [otbn,dv] Add "toggle" coverage for source register operands

- python-requirements.txt
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>
> python-requirements.txt: Bump the supported version of meson

- hw/top_earlgrey/lint/top_earlgrey_lint_cfgs.hjson
Created as last requirement for PWM D1
> [ pwm, lint ] Create new lint configuration for PWM

- hw/ip/alert_handler/data/alert_handler.hjson
- hw/ip/alert_handler/data/alert_handler.hjson.tpl
- hw/ip/alert_handler/doc/_index.md
- hw/ip/alert_handler/dv/tb/tb.sv
- hw/ip/alert_handler/rtl/alert_handler.sv
- hw/ip/alert_handler/rtl/alert_handler_esc_timer.sv
- hw/ip/alert_handler/rtl/alert_handler_ping_timer.sv
- hw/ip/alert_handler/rtl/alert_pkg.sv
- hw/top_earlgrey/ip/alert_handler/data/autogen/alert_handler.hjson
This addresses https://github.com/lowRISC/opentitan/issues/6674
> [alert_handler] Sparsely encode the FSMs

- hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
> [dv/sram] fix UNR .el file pathname

- hw/ip/otbn/doc/dv/index.md
This document was trying avoid duplication, so it tried to say things
like "ADDI has the same addition-related coverage points as ADD". This
has confused one reviewer already, and probably makes things harder to
track. Do the copy-paste.
> [otbn,dv] Copy, rather than reference, insn-specific coverage points

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_fsm.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
Fixed Lint errors and warnings related to FIFO depth
> [i2c, rtl] Fixes to Lint Errors and Warnings

- hw/ip/kmac/data/kmac_base_testplan.hjson
- hw/ip/kmac/dv/env/kmac_env.core
- hw/ip/kmac/dv/env/kmac_scoreboard.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_stress_all_vseq.sv
- hw/ip/kmac/dv/env/seq_lib/kmac_vseq_list.sv
- hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
> [dv/kmac] add stress tests

- hw/dv/tools/dvsim/testplans/tl_device_access_types_testplan.hjson
> [dv] fix a typo in tl_device_access_types_testplan

- hw/ip/pwm/data/pwm.prj.hjson
- hw/ip/pwm/doc/checklist.md
- hw/ip/pwm/rtl/pwm.sv
Formalizing transition of PWM to D1 status.
> [PWM] PWM D1

- hw/ip/otp_ctrl/dv/env/otp_ctrl_env.core
- hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv
- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv
This PR reverts back PR #6749. Seems like it is a rebase issue.
> [dv/otp_ctrl] revert part of PR #6749

- hw/ip/keymgr/data/keymgr_testplan.hjson
- hw/ip/keymgr/dv/keymgr_sim_cfg.hjson
> [keymgr/dv] Fix unmapped tests

- hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv
This PR fixes a corner case where tb might write sw digests more than
once, which might cause a unwanted write_blank_error in dai_lock_vseq.sv
> [dv/otp_ctrl] support write_blank_error [PART5]

- hw/ip/uart/data/uart_testplan.hjson
Updated testplan to add an item for long_b2b_transfer
> [uart/dv] Fix unmapped test

- hw/ip/rom_ctrl/doc/_index.md
- hw/ip/rom_ctrl/doc/rom_ctrl_blockdiag.svg
There are no substantive changes here; just tweaks to signal names and the removal of a "hey we might do this in the future" that we probably won't do.
> [rom_ctrl,doc] Update docs to match RTL implementation

- hw/top_earlgrey/data/chip_testplan.hjson
- This commit addresses the comments and updates from the testplan
review meeting held on 6/03/2021.
- The meeting notes are below:
- Updated SPI host, I2c, pwm and pattgen sections of the testplan
> [chip, testplan] Update chip testplan (SPI Host, I2C, PWM, Pattgen)

- hw/ip/rom_ctrl/data/rom_ctrl.hjson
- hw/ip/rom_ctrl/dv/tb.sv
- hw/ip/rom_ctrl/rtl/rom_ctrl.sv
- hw/ip/rom_ctrl/rtl/rom_ctrl_compare.sv
- hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv
- hw/ip/rom_ctrl/util/Makefile
- hw/ip/rom_ctrl/util/scramble_image.py
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_nexysvideo.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/syn/chip_earlgrey_asic_syn_cfg.hjson
- util/topgen/templates/chiplevel.sv.tpl
This should complete integration into the rest of the chip.
> [rom_ctrl] Add cSHAKE hash to rom generation script and remove SkipCheck bodge

- hw/ip/spi_device/data/spi_device_testplan.hjson
> [spi_device/dv] fix unmapped tests

- hw/ip/keymgr/rtl/keymgr.sv
> [keymgr] Wire up integrity alert

- hw/top_earlgrey/data/chip_testplan.hjson
This PR adds the SRAM chip-level tests as per the previous testplan
review meeting.
> [chip/dv] add SRAM chip-level tests

- hw/ip/otp_ctrl/data/otp_ctrl.prj.hjson
- hw/ip/otp_ctrl/doc/checklist.md
This PR claims the V2 status for OTP_CTRL testbench.
This PR is depended on PR #6474 
> [dv/otp_ctrl] otp reaches V2

- util/reggen/reg_block.py
This PR updates the exclusions added to all intr_state CSRs to disable
most checks on it.
This addresses #6888.
> [dv/common] update intr_state CSR exclusions

- hw/top_earlgrey/data/chip_testplan.hjson
- This commit addresses the comments and updates from the testplan
review meeting held on 6/07/2021.
- The meeting notes are below:
- Updated SYSRST ctrl and ADC ctrl sections of the testplan
> [chip, testplan] Update SYSRST_CTL and ADC

- sw/device/silicon_creator/lib/error.h
- sw/device/silicon_creator/lib/manifest.h
- sw/device/silicon_creator/lib/sigverify_rsa_key.h
- sw/device/silicon_creator/mask_rom/mask_rom.c
- sw/device/silicon_creator/mask_rom/meson.build
- sw/device/silicon_creator/mask_rom/mock_sigverify_mod_exp.h
- sw/device/silicon_creator/mask_rom/sigverify.c
- sw/device/silicon_creator/mask_rom/sigverify.h
- sw/device/silicon_creator/mask_rom/sigverify_keys.c
- sw/device/silicon_creator/mask_rom/sigverify_keys.h
- sw/device/silicon_creator/mask_rom/sigverify_mod_exp.h
- sw/device/silicon_creator/mask_rom/sigverify_mod_exp_ibex.c
- sw/device/silicon_creator/mask_rom/sigverify_mod_exp_ibex_unittest.cc
- sw/device/silicon_creator/mask_rom/sigverify_unittest.cc
We plan to move most of the signature verification code to `sw/device/silicon_creator/lib` to be able to use it in multiple boot stages. Once this work is completed, the only difference between boot stages should be the public keys that they use to verify manifest signatures (`sigverify_keys.c`).
This change:
- Renames sigverify files to be consistent with mask ROM guidelines, e.g. `sig_verify_*` -> `sigverify_*` and `rsa_verify` -> `sigverify_mod_exp`.
- Moves the struct definitions that will be shared across boot stages from `silicon_creator/mask_rom/sigverify_keys.h` to `silicon_creator/lib/sigverify_rsa_key.h`.
- Makes `mont_mul` and `calc_r_square` static, and
- Updates return values of some functions to use `rom_error_t`.
Reviewing individual commits will probably be easier. I will …
> [sw/silicon_creator] sigverify cleanup

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_fsm.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
- hw/ip/i2c/rtl/i2c_reg_top.sv
- sw/device/lib/dif/dif_i2c_unittest.cc
Fixes to Ascent and Verilator errors and warnings
> [i2c, rtl] Lint Fixes

- hw/ip/clkmgr/doc/checklist.md
> [dv/clkmgr] Update V1 checklist

- hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
If the block gets reset, we want `run_otbn()` to exit immediately. In
practice, this already happens (because `csr_wr` and `csr_spinwait` both
exit immediately). But we make the early exit explicit to avoid
checking the end address: that check will fail if there is a reset in
the middle of the first execution of a binary.
Spotted when responding to @weicaiyang's review comments on #5728: thanks!
> [otbn,dv] Fix early exits in otbn_base_vseq::run_otbn() on reset

- hw/ip/keymgr/rtl/keymgr_kmac_if.sv
- Tweak width setting to satisfy both ascentlint / verilator
> [keymgr] Width fixes

- tool_requirements.py
VCS 2020.12-SP2 contains fixes for critical issues in our verification
environment.
> Require VCS 2020.12-SP2

- hw/ip/flash_ctrl/rtl/flash_phy.sv
> [flash_ctrl] update stale comments for flash_phy

- util/reggen/fpv_csr.sv.tpl
Signed-off-by: ayann-snps <ayann@synopsys.com>
> [fpv] Fix template

- hw/formal/tools/vcformal/fpv.tcl
- hw/formal/tools/vcformal/parse-formal-report.py
- hw/formal/tools/vcformal/vcf.hjson
- hw/formal/tools/vcformal/vcf_dvsim_report.tcl
- hw/formal/tools/vcformal/vcf_message_config.tcl
Signed-off-by: ayann-snps <ayann@synopsys.com>
> [vcformal] Support VC Formal in dvsim

- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
- hw/dv/sv/cip_lib/seq_lib/cip_tl_seq_item.sv
d_user integrity should be always right as it's generated by DUT
This PR depends on #6942
> [dv] Add d_user integrity check

- hw/ip/clkmgr/data/clkmgr_testplan.hjson
Fix a punctuation issue raised on a prior PR.
> [dv/clkmgr] Fix doc punctuation

- hw/dv/sv/cip_lib/seq_lib/cip_tl_seq_item.sv
- hw/ip/otbn/rtl/otbn.sv
- hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
- hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv
- hw/ip/tlul/rtl/tlul_pkg.sv
- hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
Address #6887.
This is needed for two reasons right now
1. hosts that do not generate data integrity (debug module)
2. hosts that will later generate data integrity but do not currently
do so (ibex)
> [tlul] Add data integrity generation for host

- hw/ip/clkmgr/data/clkmgr.prj.hjson
> [dv/clkmgr] Move clkmgr to V1

- hw/ip/uart/dv/env/uart_scoreboard.sv
add alert_test in scb to avoid failure
> [uart/dv] Fix regression failure

- hw/ip/tlul/rtl/tlul_adapter_sram.sv
This reverts commit 9bb11ef5b872146c6cf545a20275ca0a04c327ef. The
problem is that some blocks make `gnt_i` dependent on `req_o` so an
erroring access just stalls. This is probably not great behaviour, and
maybe we should fix that in the future, but doing so would mean
renaming the signals (to e.g. `rdy`/`vld`, rather than `gnt`/`req`).
Fixes #7056.
> Revert "[tlul] Drop the "quick fail" path from tlul_adapter_sram.sv"

- hw/ip/sysrst_ctrl/data/sysrst_ctrl.hjson
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_inv.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_pin.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_reg_pkg.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_reg_top.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_ulp.sv
- hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_ulpfsm.sv
- hw/ip/sysrst_ctrl/sysrst_ctrl.core
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_pkg.sv
- hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_top.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey_pkg.sv
- hw/top_earlgrey/sw/autogen/top_earlgrey.h
I have some new pins like z3_wakeup and lid_open at sysrst_ctrl level.
It's based on the https://github.com/lowRISC/opentitan/issues/5550
> [sysrst_ctrl] ULP wakeup feature 

- hw/ip/flash_ctrl/data/flash_ctrl.hjson
- hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl
- hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl
- hw/ip/flash_ctrl/data/flash_ctrl_pkg.sv.tpl
- hw/ip/flash_ctrl/dv/tb/flash_ctrl_wrapper.sv
- hw/ip/flash_ctrl/dv/tb/tb.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
- hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv
- hw/ip/flash_ctrl/rtl/flash_phy.sv
- hw/ip/flash_ctrl/rtl/flash_phy_core.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_core_reg_top.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_pkg.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_pkg.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_englishbreakfast/data/top_englishbreakfast.hjson
Address #7011 and allow both hw / sw to completely stop flash transactions.
> [flash_ctrl] Add hw / sw escalate_en controls

- hw/ip/pwrmgr/rtl/pwrmgr_fsm.sv
- hw/ip/rstmgr/data/rstmgr.sv.tpl
- hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr.sv
Address #6819
Also fix some errors on reset condition reporting when the
main power domain is not turned off.
> [pwrmgr] Fix fallthrough fsm states

- hw/ip/i2c/data/i2c.hjson
- hw/ip/i2c/rtl/i2c_core.sv
- hw/ip/i2c/rtl/i2c_reg_pkg.sv
> [i2c, rtl] FIFO Depth Parameterization

- hw/ip/pwm/doc/dv/index.md
Minor update the DV markdown file of the PWM IP
> [pwm, dv] Update dv markdown file for PWM IP

- hw/ip/rom_ctrl/dv/env/rom_ctrl_env_pkg.sv
> [rom_ctrl dv] Fix for xcelium

- hw/ip/otbn/rtl/otbn.sv
- hw/ip/otbn/rtl/otbn_pkg.sv
- hw/ip/otbn/rtl/otbn_scramble_ctrl.sv
> [otbn] Fix lint introduced by scrambling

- hw/ip/entropy_src/dv/env/entropy_src_env.sv
- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
- hw/ip/entropy_src/dv/tests/entropy_src_base_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_rng_test.sv
- hw/ip/entropy_src/dv/tests/entropy_src_smoke_test.sv
Passing rng_test depends on rtl fixes in PR #7099 
> [entropy_src/dv] rng_test, scoreboard prediction

- hw/ip/entropy_src/data/entropy_src.hjson
- hw/ip/entropy_src/rtl/entropy_src_core.sv
- hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
- hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
- sw/device/tests/dif/dif_entropy_smoketest.c
RTL updates made to support the boot, startup, and continuous test phases.
Fixes #6085.
> [csrng/rtl] update for health test phases

- hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
- util/topgen/merge.py
Fixes https://github.com/lowRISC/opentitan/pull/7075#pullrequestreview-692183922 and https://github.com/lowRISC/opentitan/pull/7063#discussion_r658246304
> [lc_ctrl/alerts] Fix a typo

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
- hw/dv/sv/cip_lib/seq_lib/cip_tl_seq_item.sv
Enable it as #6887 is resolved
Add constraint that data intg check only applies to write
> [dv] Enable tl intg error on data

- hw/ip/clkmgr/data/clkmgr.hjson.tpl
- hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson
> [clkmgr] update documentation

- hw/ip/otbn/dv/otbnsim/sim/state.py
Normally, as part of executing an instruction, we also check that the
next instruction's PC is valid. However, we should only do that check
if there will actually be a next instruction. That is, we should skip
the check if this instruction is already causing the processor to
stop.
This came up in a randomly generated test, which happened to generate
a branch to `0xffc` (the top word in memory) which contained an ECALL.
The fall-through address would be invalid, but that shouldn't matter
because we're stopping anyway.
> [otbn,dv] Correct "next PC" checks on stopping instructions

- hw/dv/sv/cip_lib/cip_base_env_cov.sv
- hw/dv/sv/cip_lib/cip_base_pkg.sv
- hw/dv/sv/cip_lib/cip_base_scoreboard.sv
- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
- hw/dv/sv/cip_lib/seq_lib/cip_tl_seq_item.sv
- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
1. Add intg test for mem
2. Add functional coverage for tl_errors and intg error
3. Add RO mem write error for tl_errors
> [dv] Add intg test for mem and add coverage

- hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv
Hi,
This small PR is for adding flexibility with the flash initiation, which can give ability to choose initiation scheme and partition by changing knobs in **flash_ctrl_seq_cfg**. 
Thanks!
Signed-off-by: Eitan Shapira <eitan.shapira@nuvoton.com>
> [flah_ctrl/dv] Small addition and change in flash_ctrl_seq_cfg & flash_ctrl_base_vseq

- hw/dv/sv/tl_agent/dv/env/seq_lib/tl_agent_base_vseq.sv
- hw/dv/sv/tl_agent/dv/env/tl_agent_env_cfg.sv
- hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
We have a small TB to test TL agent same cycle response.
And we brought couple issues to this TB which are fixed in this PR.
It's good to add it into our CI and regression to uncover this kind of issue
> [dv] Fix errors in tl_agent DV and add it to CI

- hw/ip/entropy_src/doc/_index.md
Added a few minor documentation updates in preparation for D2.
> [entropy_src/doc] minor documentation cleanup

- hw/ip/adc_ctrl/rtl/adc_ctrl.sv
> [adc_ctrl] Minor formatting fix

- doc/project/checklist.md
- doc/project/development_stages.md
- doc/project/sw_checklist.md.tpl
- doc/rm/device_interface_functions.md
This PR updates the DIF development stages to reflect the changes in #5918. There are other updates / corrections to the DIF documentation to be made, but I've kept this PR tightly scoped scoped to focus on the development stage changes so we can discuss it at the OpenTitan Technical Committee tomorrow.
> [doc] Update DIF development stages

- hw/ip/adc_ctrl/rtl/adc_ctrl.sv
- hw/ip/pwm/dv/env/pwm_env_pkg.sv
- hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
Verible formatter version: v0.0-1213-g9e5c085b
> formatting: Reformat files from allowlist

- sw/host/opentitanlib/opentitantool_derive/Cargo.toml
- sw/host/opentitanlib/opentitantool_derive/src/lib.rs
- sw/host/opentitanlib/src/app/command.rs
- sw/host/opentitanlib/src/app/mod.rs
- sw/host/opentitantool/Cargo.toml
- sw/host/opentitantool/src/backend/mod.rs
- sw/host/opentitantool/src/command/hello.rs
- sw/host/opentitantool/src/command/mod.rs
- sw/host/opentitantool/src/main.rs
1. Establish the basic `opentitantool` framework.
2. Create a procedural macro for deriving `CommandDispatch` for interior
nodes in the command hierarchy.
3. Create some sample `hello` commands in `hello.rs`.
> [opentitantool] Base opentitantool application

- hw/top_earlgrey/ip/ast/doc/_index.md
- hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.prj.hjson
- hw/top_earlgrey/ip/sensor_ctrl/doc/_index.md
- hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
- util/build_docs.py
- Add sensor_ctrl doc and prj.hjson
- Update ast title header
- Minor fix for sensor_ctrl alert clearing
> [sensor_ctrl, ast] Preparation for sensor_ctrl d2

- hw/ip/rv_core_ibex/rtl/rv_core_addr_trans.sv
- hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
- hw/ip/rv_core_ibex/rv_core_ibex.core
- hw/ip/rv_core_ibex_peri/data/rv_core_ibex_peri.hjson
- hw/ip/rv_core_ibex_peri/rtl/rv_core_ibex_peri.sv
- hw/ip/rv_core_ibex_peri/rtl/rv_core_ibex_peri_pkg.sv
- hw/ip/rv_core_ibex_peri/rtl/rv_core_ibex_peri_reg_pkg.sv
- hw/ip/rv_core_ibex_peri/rtl/rv_core_ibex_peri_reg_top.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- hw/top_earlgrey/sw/autogen/top_earlgrey_memory.ld
- meson.build
- sw/device/boot_rom/boot_rom.c
- sw/device/boot_rom/meson.build
- sw/device/boot_rom/rom_link.ld
- sw/device/exts/common/flash_link.ld
- sw/device/lib/ibex_peri.c
- sw/device/lib/ibex_peri.h
- sw/device/lib/meson.build
- util/topgen/templates/toplevel.sv.tpl
- util/topgen/templates/toplevel_memory.ld.tpl
- Add initial hardware
- Add proof of concept edits
Don't look at the first two commits as they will be rebased away.
> [ibex] Add simple address translation

- sw/device/silicon_creator/lib/shutdown_unittest.cc
shutdown_unittest is brittle with respect to the number of alert
sources: any time the HW folks change the sources, the test will break.
This brittleness is unnecessary because the unittest doesn't care about
the specifics of the alert configuration, just that a given
configuration gets applied.
1. Define a full alert configuration up to the current limit of
OTP-defined alert configuration (80 alerts).
2. Refactor the test cases to check that the applied configuration
length matches the number of alert config registers rather than the size
of the test's alert configuration structure.
> [mask_rom] Reduce the brittleness of shutdown_unittest

- sw/device/silicon_creator/lib/sigverify_functest.c
- sw/device/silicon_creator/lib/sigverify_mod_exp_ibex.c
- sw/device/silicon_creator/lib/sigverify_mod_exp_ibex_unittest.cc
- sw/device/silicon_creator/lib/sigverify_rsa_key.h
- sw/device/silicon_creator/mask_rom/sigverify_keys.c
> [sw/silicon_creator] Make sigverify_rsa_key_t.n0_inv 8 words for OTBN

- hw/ip/pwrmgr/dv/env/pwrmgr_env_cfg.sv
- hw/ip/pwrmgr/dv/env/pwrmgr_if.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
- hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_smoke_vseq.sv
- hw/ip/pwrmgr/dv/tb.sv
Drive inputs to the pwrmgr based on output changes.
> [dv/pwrmgr] Drive pwrmgr inputs based on outputs

- hw/ip/aon_timer/rtl/aon_timer.sv
When aon_timer triggers JUST before we enter low power, the wakeup
request is missed because sleep_mode is not yet asserted.
This causes the system to go into low power and never wakeup.
Instead we should always latch the wakeup reason, and only show it
as a wakeup signal when we are in low power mode.
> [aon_timer] Always capture wakeup cause.

- hw/ip/pattgen/data/pattgen.prj.hjson
- hw/ip/pattgen/doc/checklist.md
Modulo a few questions about CDC signoff and FPGA Area, this block is ready to advance to D2
> [ pattgen ] Transition to D2

- hw/top_earlgrey/dv/chip_mask_rom_tests.hjson
- hw/top_earlgrey/dv/chip_sim_cfg.hjson
- sw/device/silicon_creator/lib/drivers/keymgr_functest.c
- sw/device/silicon_creator/lib/drivers/meson.build
Update `keymgr_functest` and enable it to run in DV.
> [dv, sw] Various updates to enable keymgr_functest

- hw/ip/flash_ctrl/flash_ctrl_pkg.core
- hw/ip/flash_ctrl/lint/flash_ctrl.waiver
- hw/ip/flash_ctrl/lint/flash_ctrl_pkg.vlt
- hw/ip/flash_ctrl/lint/flash_ctrl_pkg.waiver
- hw/ip/kmac/lint/kmac.waiver
This commit clears out remaining lint errors in KMAC.
> [kmac] Lint fix

- hw/top_earlgrey/data/chip_testplan.hjson
Fix a few small nit and wording on chip testplan for otp_lc_transition
test.
> [dv/top-level] small fix on chip testplan

- hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
- util/design/lib/LcStEnc.py
> [lc_ctrl] Fix the cshake byte order in the constants generation script

- hw/ip/usbuart/data/usbuart.hjson
- hw/ip/usbuart/rtl/usbuart.sv
- hw/ip/usbuart/rtl/usbuart_reg_pkg.sv
- hw/ip/usbuart/rtl/usbuart_reg_top.sv
> [usbuart] Wire up integ alert

- hw/ip/spi_host/data/spi_host.prj.hjson
- hw/ip/spi_host/doc/checklist.md
- hw/ip/spi_host/rtl/spi_host.sv
This IP is largely ready for transition to D1.  Please reach out to me if you need a review.
> [ spi_host ] Transition to D1

- hw/ip/otbn/doc/_index.md
> [doc/otbn] Documented instruction count feature.

- hw/top_earlgrey/ip/ast/ast.core
- hw/top_earlgrey/ip/ast/data/ast.hjson
- hw/top_earlgrey/ip/ast/rtl/adc.sv
- hw/top_earlgrey/ip/ast/rtl/aon_clk.sv
- hw/top_earlgrey/ip/ast/rtl/aon_osc.sv
- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/ast_alert.sv
- hw/top_earlgrey/ip/ast/rtl/ast_bhv_pkg.sv
- hw/top_earlgrey/ip/ast/rtl/ast_dft.sv
- hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv
- hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv
- hw/top_earlgrey/ip/ast/rtl/io_clk.sv
- hw/top_earlgrey/ip/ast/rtl/io_osc.sv
- hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv
- hw/top_earlgrey/ip/ast/rtl/sys_clk.sv
- hw/top_earlgrey/ip/ast/rtl/sys_osc.sv
- hw/top_earlgrey/ip/ast/rtl/usb_clk.sv
- hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- util/topgen/templates/chiplevel.sv.tpl
> [ast] Mostly updates to internal code

- hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv
> [lc_ctrl] Correct  counter next state computation logic

- hw/ip/keymgr/data/keymgr.hjson
- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_random_vseq.sv
- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_ctrl.sv
- hw/ip/keymgr/rtl/keymgr_pkg.sv
- hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
- hw/ip/keymgr/rtl/keymgr_reg_top.sv
- sw/device/lib/dif/dif_keymgr.c
- sw/device/lib/dif/dif_keymgr_unittest.cc
- sw/device/silicon_creator/lib/drivers/keymgr.c
- sw/device/silicon_creator/lib/drivers/keymgr_unittest.cc
ignore first 1 commit, will be rebased away. 
- Add second internal key for DICE.
- Various hacks to DV to allow smoketest to pass for now.
> [keymgr] Keymgr DICE support

- hw/ip/pattgen/rtl/pattgen_core.sv
- hw/ip/pwm/rtl/pwm_cdc.sv
- hw/ip/pwm/rtl/pwm_core.sv
- hw/ip/uart/rtl/uart_core.sv
These are just some low hanging fruit lint fixes in preparation for `rv_core_ibex` full templating.
> [top] Various lint fixes

- hw/ip/otp_ctrl/dv/tb.sv
Signed-off-by: Dror Kabely <dror.kabely@opentitan.org>
Reopening of PR #6952
> [dv/otp_ctrl] conditioned mem_bkdr_util creation on PRIM_DEFAULT_IMPL

- hw/dv/sv/csrng_agent/csrng_item.sv
- hw/dv/sv/csrng_agent/csrng_monitor.sv
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
> [csrng/dv] csrng_cmds_test/instantiate cmd

- hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
There are two commits in this PR. The first is a slight tidy-up to make it a bit more obvious how everything is supposed to work. The second is the actual bugfix. Commit message below:
> The bug here happens if a reset is asserted just after the write to
> the CMD register that starts OTBN. Specifically, there was a problem
> if the reset arrived after the negedge of the clock after `start_i`
> signal is asserted but before the following posedge.
> 
> In this case, we would have converted `saw_start_tl_trans` into
> `waiting_for_model` and then would see the `DV_CHECK` fail on the
> following cycle (by which time, we were in reset) because the reset
> would have arrived before the model started.
> 
> To fix things, we make the check conditional on not being in reset and
> also clear the …
> [otbn,dv] Fix handling of the start signal around resets

- hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv
- hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
> [entropy_src/dv] Add fips predict/compare, multiple reqs

- hw/ip/otbn/data/otbn.hjson
- hw/ip/otbn/dv/uvm/tb.sv
- hw/ip/otbn/dv/verilator/otbn_top_sim.sv
- hw/ip/otbn/otbn.core
- hw/ip/otbn/rtl/otbn.sv
- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
The signal doesn't trigger any action yet, but I thought it would be good to have the top-level wiring in place earlier.
> [otbn] Connect lifecycle escalation signal

- hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
- hw/ip/otp_ctrl/rtl/otp_ctrl.sv
This PR fixes #7294 in both DV and RTL.
> [otp_ctrl] Fix rma valid signal

- hw/ip/pinmux/rtl/pinmux_strap_sampling.sv
While it is useful for the TAP straps to be sampled continuously in DFT-enabled life cycle states such that test sequences can dynamically change between TAPs, this is not so much the case for the DFT-mode straps.
I.e., from a test perspective it would be better if these DFT-mode straps were sampled only once such that the corresponding pins do not have to be constantly held at a specific value throughout the test sequence. This would also free them up such that they can be used as regular GPIOs.
This commit changes the strap sampling logic accordingly.
> [pinmux] Always sample DFT mode straps only once at boot

- hw/ip/entropy_src/data/entropy_src.prj.hjson
- hw/ip/entropy_src/doc/checklist.md
All major features and functions have been integrated and documented for achieving D2 for the entropy_src block.
> [entropy_src/doc] moving to D2

- hw/ip/aes/dv/env/aes_env_cfg.sv
same rational as #7142
intg_err will trigger design to update a CSR
> [aes/dv] Fix tl_intg_err

- sw/otbn/code-snippets/modexp.s
This commmit will revolutionize the way we do computation on OTBN.
> [otbn] Fix typos in software comments

- hw/ip/csrng/dv/env/csrng_env.sv
- hw/ip/csrng/dv/env/csrng_env_cfg.sv
- hw/ip/csrng/dv/env/csrng_env_pkg.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/csrng_virtual_sequencer.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
- hw/ip/csrng/dv/tb.sv
But csrng_cmds_vseq to test multiple hw_apps still under development.
> [csrng/dv] Added support for multiple hw_apps

- util/reggen/gen_cheader.py
@silvestrst: Is this the sort of thing you were imagining for #1977?
(Assuming so...), closes #1977.
> [reggen] Expose reset values to SW

- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- util/topgen/templates/toplevel.sv.tpl
Commit c5d3078 bumped these over the 100 character threshold, causing
CI failures.
> [top] Split long parameter lines in toplevel.sv.tpl

- hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv
- hw/ip/entropy_src/dv/env/seq_lib/entropy_src_smoke_vseq.sv
- hw/ip/entropy_src/dv/tests/entropy_src_smoke_test.sv
> [entropy_src/dv] Modify smoke_test to be ptrng-based

- hw/ip/otbn/doc/_index.md
Add two pieces of documentation:
* Document what kind of randomness software developers can expect when
reading from RND or URND.
* Document what requirements OTBN has on the EDN to provide appropriate
randomness.
For high-quality random numbers made available through RND we went for
PTG.3 for now in line with current thinking, but might need to update
that if our plans change.
The goal is still to specify what software developers get when using
RND. If we don't do that, software written for OTBN has an additional
dependency on the configuration of the EDN, which is has no insight to.
Also note that we don't give any guarantees at the moment for the URND
randomness drawn from a local LFSR. There are plans to remove the shift
register with another construction that provides stronger …
> [otbn] Document randomness properties

- hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
- hw/top_earlgrey/data/top_earlgrey.hjson
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
- util/topgen/templates/chiplevel.sv.tpl
> [top] Correct parameter defaults in top_earlgrey

- hw/ip/prim/rtl/prim_fifo_async.sv
> [prim] Fix typo that caused fifo_async to get stuck

- hw/ip/otbn/doc/_index.md
- site/docs/layouts/shortcodes/otbnInsnRef.html
See individual commit messages for details.
> [otbn] Various specificaton cleanups

- hw/top_earlgrey/dv/tb/tb.sv
- if the translation units are not reset, they can trigger
known assertion failrues if a random register write happens
to turn on address translation.
> [dv] Minor tb modification to handle assertions

- hw/ip/keymgr/dv/env/keymgr_env_pkg.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
- hw/ip/keymgr/dv/env/seq_lib/keymgr_random_vseq.sv
For design update at #7207
1. randomize CDI_SEL and both sw_binding in seq
2. remove hack code. store and check both CDI internal data
> [keymgr/dv] Update scb/seq for DICE support

- hw/ip/keymgr/rtl/keymgr.sv
- hw/ip/keymgr/rtl/keymgr_input_checks.sv
> [keymgr] Add input data checks for rom_digest

- hw/ip/pwrmgr/rtl/pwrmgr_fsm.sv
> [pwrmgr] Disable cpu fetch enable when entering low power

- util/dvsim/FlowCfg.py
- util/dvsim/Launcher.py
- util/dvsim/utils.py
Add a `latest` directory under `reports` to symlink the latest result.
This will make it easier for other script to send emails and publish the
results.
> [script/dvsim] Separate publish report from dvsim flow [PART2]

- hw/ip/keymgr/rtl/keymgr_ctrl.sv
> [keymgr] Fix the cdi selection for keys

- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
Address #7346
Have tested all other input, but missed the rom digest
> [keymgr/dv] Add missing rom digest all 1s/0s test

- hw/ip/flash_ctrl/data/flash_ctrl_pkg.sv.tpl
- hw/ip/flash_ctrl/doc/_index.md
- hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
- hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_pkg.sv
> [flash_ctrl] Update partitions wiped during RMA entry

- hw/ip/otbn/data/otbn.hjson
- hw/ip/otbn/doc/_index.md
- hw/ip/otbn/rtl/otbn_reg_pkg.sv
- hw/ip/otbn/rtl/otbn_reg_top.sv
Added specification of the secure wipe mechanism.
Modified otbn.hjson to include register interface.
> [otbn/doc] Secure Wipe documentation update.

- hw/ip/pwm/rtl/pwm_chan.sv
- Fixes #7375
- Address a few lint errors
> [pwm] Minor fixes

- hw/ip/spi_device/rtl/spi_readcmd.sv
[spi_device] Use Sfdp parameter for Address
Read command block recevies Read SFDP command too. Now if the command
parser recognizes the SFDP command and selects the datapath to
DpReadSFDP, the read command sends out SFDP Base address rather than
Buffer address or Mailbox Address.
As mentioned in #7380 , please ignore the first commit and only review the second.
> [spi_device] Use Sfdp parameter for Address

- hw/ip/otbn/doc/_index.md
> [otbn] Specify life cycle escalation reaction

- hw/ip/rstmgr/data/rstmgr.hjson
- hw/ip/rstmgr/data/rstmgr.hjson.tpl
- hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson
> [doc/rstmgr] Remove redundant "!"s in hjson

- hw/top_earlgrey/ip/ast/ast.core
- hw/top_earlgrey/ip/ast/rtl/adc.sv
- hw/top_earlgrey/ip/ast/rtl/aon_clk.sv
- hw/top_earlgrey/ip/ast/rtl/aon_osc.sv
- hw/top_earlgrey/ip/ast/rtl/ast.sv
- hw/top_earlgrey/ip/ast/rtl/ast_dft.sv
- hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv
- hw/top_earlgrey/ip/ast/rtl/io_clk.sv
- hw/top_earlgrey/ip/ast/rtl/io_osc.sv
- hw/top_earlgrey/ip/ast/rtl/rng.sv
- hw/top_earlgrey/ip/ast/rtl/sys_clk.sv
- hw/top_earlgrey/ip/ast/rtl/sys_osc.sv
- hw/top_earlgrey/ip/ast/rtl/usb_clk.sv
- hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
- hw/top_earlgrey/ip/ast/rtl/vcaon_pok.sv
- hw/top_earlgrey/ip/ast/rtl/vcc_pok.sv
- hw/top_earlgrey/ip/ast/rtl/vcmain_pok.sv
- hw/top_earlgrey/ip/ast/rtl/vio_pok.sv
- hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
- util/topgen/templates/chiplevel.sv.tpl
> [ast] Add support for external clocks for FPGA/VERILATOR

- hw/ip/keymgr/dv/env/keymgr_if.sv
- hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
kmac key checker was disabled due to recent DICE update
Enable it by introducing `current_cdi` to store internal key in an
associative array
> [keymgr/dv] update scb and enable KMAC key check

- hw/ip/rstmgr/doc/_index.md
Fix some "regref" instances.
Update description of reset state.
> [doc/rstmgr] Improve functional spec

- hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
Signed-off-by: Dror Kabely <dror.kabely@opentitan.org>
PR for issue #7399
> [dv/cip_base_vseq] fixed extract_common_csrs for multi-RAL

- hw/dv/sv/csrng_agent/csrng_item.sv
- hw/ip/csrng/dv/env/csrng_scoreboard.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
- hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
> [csrng/dv] Generate cmds for multiple hw_apps

- doc/security/specs/secure_boot/index.md
Signed-off-by: Michael Tempelmeier <michael.tempelmeier@gi-de.com>
> [doc] Fix link to Ibex PMP

- hw/ip/edn/data/edn.hjson
- hw/ip/edn/dv/env/edn_env_cfg.sv
- hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv
- hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv
- hw/ip/edn/dv/tests/edn_smoke_test.sv
> [edn/dv] Modify for multi-bit enables

- hw/ip/rstmgr/data/rstmgr_testplan.hjson
- hw/ip/rstmgr/doc/dv/index.md
- hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv
- hw/ip/rstmgr/dv/env/seq_lib/rstmgr_smoke_vseq.sv
- hw/ip/rstmgr/dv/sva/rstmgr_bind.sv
- hw/ip/rstmgr/dv/tests/rstmgr_base_test.sv
Create a smoke test checking the response to various reset requests.
Update dv spec and testplan for smoke test.
> [dv/rstmgr] Create smoke test
