util/dvsim/FlowCfg.py
Small fixes:
1). Add a missing symlink for publish.html.
2). Skip `clean_odirs` if the directory already exists.
=> [dvsim] Separate publish report from dvsim flow [PART3]

hw/top_earlgrey/data/chip_testplan.hjson
- This commit addresses the comments and updates from the testplan
review meeting held on 7/21/2021.
- The meeting notes are below:
- Updated flash ctrl sections of the testplan
=> [dv, chip level] Update chip testplan: flash ctrl

hw/ip/otbn/rtl/otbn_loop_controller.sv
The previous code separated out two cases depending on whether IMEM
was small or large compared to the 12-bit bodysize from the ISA.
Even with a large IMEM width, we still have the possibility of an
overflow in the addition (because the loop instruction might be at the
top of the address space). The existing code was correct, but I think
both branches of the `if` block did the same thing in the "big IMEM"
case: the unary OR in the first branch ends up operating on a single
bit.
Simplify things by getting rid of the `if` block and just using the
first branch. Also, increment `LoopEndAddrWidth` by 1 so that the name
is accurate and write a comment explaining why this is the right
calculation.
There's a small optimisation opportunity here: If we taught
`otbn_loop_controller` about the size …
=> [otbn] Simplify loop end calculation logic

sw/host/opentitanlib/src/transport/verilator/subprocess.rs
1. Write tests to check the regex passed to the `find` method.
=> [opentitantool] Correct an error in the verilator transport

hw/ip/rstmgr/dv/env/rstmgr_env_pkg.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_smoke_vseq.sv
=> [dv/rstmgr] Randomize smoke test

util/topgen.py, util/topgen/merge.py
=> [topgen] Relocate instance check to clarify intent

hw/ip/clkmgr/dv/env/clkmgr_env.sv, hw/ip/clkmgr/dv/env/clkmgr_env_cfg.sv, hw/ip/clkmgr/dv/env/clkmgr_env_cov.sv, hw/ip/clkmgr/dv/env/clkmgr_env_pkg.sv, hw/ip/clkmgr/dv/env/clkmgr_if.sv, hw/ip/clkmgr/dv/env/clkmgr_scoreboard.sv, hw/ip/clkmgr/dv/env/clkmgr_virtual_sequencer.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_common_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_extclk_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_smoke_vseq.sv, hw/ip/clkmgr/dv/sva/clkmgr_bind.sv, hw/ip/clkmgr/dv/tb.sv, hw/ip/clkmgr/dv/tests/clkmgr_base_test.sv
=> [dv/clkmgr] Fix formatting for verible

hw/top_earlgrey/ip/ast/ast.core, hw/top_earlgrey/ip/ast/rtl/adc.sv, hw/top_earlgrey/ip/ast/rtl/adc_ana.sv, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_dft.sv, hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv, hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv, hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv, hw/top_earlgrey/ip/ast/rtl/rng.sv, hw/top_earlgrey/ip/ast/rtl/sys_osc.sv, hw/top_earlgrey/ip/ast/rtl/usb_clk.sv, hw/top_earlgrey/ip/ast/rtl/usb_osc.sv, hw/top_earlgrey/ip/ast/rtl/vcaon_pgd.sv, hw/top_earlgrey/ip/ast/rtl/vcc_pgd.sv, hw/top_earlgrey/ip/ast/rtl/vcmain_pgd.sv, hw/top_earlgrey/ip/ast/rtl/vio_pgd.sv, sw/device/tock/tock/Cargo.toml
=> [ast] Add Fix AscentLint Errors

hw/ip/edn/data/edn.hjson, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_common_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv
=> [edn/dv] Add do_edn_init

hw/ip/csrng/data/csrng.hjson, hw/ip/csrng/dv/env/csrng_env_cfg.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_common_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_smoke_vseq.sv, hw/ip/csrng/dv/tests/csrng_base_test.sv, hw/ip/csrng/dv/tests/csrng_smoke_test.sv
=> [csrng/dv] Modify for multi-bit enables

hw/top_earlgrey/formal/conn_csvs/top_earlgrey_conn.csv
=> [formal/conn] Check pwrmgr to rtstmgr connections

hw/top_earlgrey/ip/ast/lint/ast.waiver
After this, AST should be lint-clean.
=> [ast/lint] Waive remaining lint errors

util/topgen.py
Address ral model issue in #7218
We have 2 types of sram in top_earlgrey. we use memory size from sram
block level hjson to create ral model. now we want to override the memory
in the top hjson. This PR enables this support
This is block level sram_ctrl.hjson
```
{ name: "sram_ctrl",
registers: {
regs: [
...
]
ram: [
// no CSRs defined here.
]
}
```
This is in top_earlgrey.hjson, we want to specify the 2 RAM with different configurations.
```
{ name: "sram_ctrl_main",
type: "sram_ctrl",
... 
memory: {
ram: {
swaccess: "rw",      
size:     "0x20000" 
}
}
{ name: "sram_ctrl_ret",
type: "sram_ctrl",
... 
memory: {
ram: {
swaccess: "rw",      
size:     "0x10000"   
}
}
```
------
update topgen as follows
// initial database:
```
name_to_block["sram_ctrl"] = ram_type …
```
=> [dv] Override mem with info in the top hjson for RAL

hw/top_earlgrey/data/chip_testplan.hjson
We can go over this in the review meeting
=> [chip/dv] Add keymgr testplan for chip-level

hw/top_earlgrey/data/chip_testplan.hjson
Update testplan as we discussed in the meeting
=> [chip/dv] Update spi_device top-level testplan

hw/ip/i2c/doc/checklist.md
=> [i2c, doc] Checklist Update for D2 Sign-off

hw/ip/pinmux/rtl/pinmux.sv
#5198 has been addressed and closed.
=> [pinmux] Remove todo that has been addressed

hw/dv/sv/csr_utils/csr_seq_lib.sv, hw/dv/sv/dv_base_reg/dv_base_reg.sv
This PR alignes issue #7417 with two fixes:
1). Allow shadow register to be updated by field rather than the entire
register.
2). In `csr_rw`, wait until no non-blocking access then read shadow
register.
=> [dv/shadow_reg] Align shadow_reg field update behavior

hw/ip/otbn/data/otbn.hjson, hw/ip/otbn/doc/_index.md, hw/ip/otbn/rtl/otbn_reg_pkg.sv, hw/ip/otbn/rtl/otbn_reg_top.sv
Removed user-initiated secure wipe of internal state.
This resolves issue #7468 .
=> [otbn/doc] Updated secure wipe specification.

hw/top_earlgrey/ip/ast/lint/ast.waiver, hw/top_earlgrey/lint/chip_earlgrey_asic.waiver, hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv, util/topgen/templates/chiplevel.sv.tpl
=> [chip_earlgrey_asic/lint] Fix/waive remaining AST-related lint messages

hw/dv/tools/dvsim/dsim.hjson
Remove buggy optimization until dsim fixes a bug:
https://gitlab.metrics.ca/google/google/-/issues/242.
=> [dv/dsim] Add dsim workaround for issue 242

hw/ip/rstmgr/dv/env/seq_lib/rstmgr_smoke_vseq.sv
=> [dv/rstmgr] Fix code for verible format

hw/dv/sv/dv_utils/dv_utils_pkg.sv
Signed-off-by: Dror Kabely <dror.kabely@opentitan.org>
=> [dv/utils] added 6MHz to clk_freq_mhz_e

hw/ip/otbn/dv/rig/rig/model.py
The existing code was only correct if no operand is both a source and
a destination... which isn't true any more! In particular, we could
generate `BN.MULQACC` instructions that wrote to constant registers.
=> [otbn,dv] Properly handle operands that are both src and dst in RIG

hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_loop_controller.sv
The previous code wouldn't trigger if there was a branch that wasn't
taken.
=> [otbn] Fix logic for detecting branch/jumps at end of loop

hw/ip/gpio/dv/env/gpio_scoreboard.sv, hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
1. Hmac remove a comment as it is implemented already.
2. GPIO fix two small typos
=> [dv/ips] Fix a few small items in gpio and hmac

hw/ip/gpio/dv/env/seq_lib/gpio_filter_stress_vseq.sv
This PR fixes gpio_filter_stress test timeout issue.
The reason is due to a `wait_fork` did not have an isolation fork to
wrap around it.
=> [dv/gpio] Fix filter_stress test timeout

hw/ip/keymgr/data/keymgr.hjson, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_random_vseq.sv, hw/ip/keymgr/rtl/keymgr.sv, hw/ip/keymgr/rtl/keymgr_ctrl.sv, hw/ip/keymgr/rtl/keymgr_pkg.sv, hw/ip/keymgr/rtl/keymgr_reg_pkg.sv, hw/ip/keymgr/rtl/keymgr_reg_top.sv, sw/device/lib/dif/dif_keymgr.c, sw/device/lib/dif/dif_keymgr_unittest.cc, sw/device/silicon_creator/lib/drivers/keymgr.c, sw/device/silicon_creator/lib/drivers/keymgr_unittest.cc
This PR adds a select few keymgr registers as "shadowed" variety.
=> [keymgr] keymgr hardening part 2

hw/ip/clkmgr/dv/env/clkmgr_if.sv, hw/ip/clkmgr/dv/env/clkmgr_scoreboard.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_extclk_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_peri_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_smoke_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_trans_vseq.sv, hw/ip/clkmgr/dv/tb.sv
Avoid most checking during reset.
=> [dv/clkmgr] Enhance reset handling for stress test

hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv
There was an off-by-one error because of the "+1" in the encoding of
`bodysize`. And also a factor of 4 because I'd forgotten to convert from
"number of instructions" to "bytes". Oops...
=> [otbn,dv] Fix calculation of loop end address in coverage

hw/ip/i2c/data/i2c.prj.hjson
=> [i2c, rtl] Update i2c.prj.hjson for D2 completion

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.sv, hw/top_earlgrey/dv/env/chip_env_cfg.sv, hw/top_earlgrey/dv/env/chip_env_pkg.sv, hw/top_earlgrey/dv/env/chip_scoreboard.sv, hw/top_earlgrey/dv/env/chip_virtual_sequencer.sv, hw/top_earlgrey/dv/env/seq_lib/chip_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_stub_cpu_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_uart_tx_rx_vseq.sv, hw/top_earlgrey/dv/tb/tb.sv, hw/top_earlgrey/dv/tests/chip_base_test.sv, sw/device/tests/sim_dv/meson.build, sw/device/tests/sim_dv/uart_tx_rx_test.c
Randomly pick a uart to test, backdoor modify memory to let SW test the
uart we pick.
Update pinmux to enable the other 3 uarts
Remove uart mon connection with scb, which is unused
=> [dv/top] Test uart multiple instances

sw/device/lib/dif/dif_pwrmgr.c, sw/device/lib/dif/dif_pwrmgr.h, sw/device/lib/dif/dif_pwrmgr_unittest.cc
=> [dif/pwrmgr] add alert test functionality

hw/ip/aon_timer/data/aon_timer.prj.hjson, hw/ip/aon_timer/doc/_index.md, hw/ip/aon_timer/doc/checklist.md, hw/ip/aon_timer/rtl/aon_timer.sv
Documentation updates and a checklist update to move to D2.
=> [aon_timer] Move to D2

hw/ip/spi_device/data/spi_device.hjson, hw/ip/spi_device/lint/spi_device.waiver, hw/ip/spi_device/rtl/spi_device.sv, hw/ip/spi_device/rtl/spi_device_reg_pkg.sv, hw/ip/spi_device/rtl/spi_device_reg_top.sv, hw/ip/spi_device/rtl/spi_readcmd.sv, hw/ip/spi_device/rtl/spid_readbuffer.sv, hw/ip/spi_device/spi_device.core
This commit implements the buffer management logic. It checks the flip
and watermark events.
Spec: https://docs.google.com/document/d/1VkSKz0egXQoBwwfI9vaHjIzzECHNn9GK1uI3tkGVIsw/edit#heading=h.jr52hvfrjwpv
=> [spi_device] ReadCmd: Double Buffer Manager

hw/ip/entropy_src/dv/tests/entropy_src_smoke_test.sv
=> [entropy_src/dv] Fix for issue #7660

hw/ip/pwrmgr/data/pwrmgr_testplan.hjson, hw/ip/pwrmgr/doc/_index.md, hw/ip/pwrmgr/doc/dv/index.md
Also fix minor glitches in the documentation.
=> [dv/pwrmgr] Add feedback from testplan review

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv, util/reggen/uvm_reg_base.sv.tpl
related to #5852
Use an array for multi-field in RAL model
refer to this [slide](https://docs.google.com/presentation/d/1VV1pok-OQSAgxCwbDa5BFKEQmGf4O2hMt-225n_Vwsk/edit#slide=id.ge50c4a4256_0_9)
=> [dv] enhance multi-field in RAL model

hw/dv/sv/csr_utils/csr_utils_pkg.sv, hw/dv/sv/dv_base_reg/dv_base_reg.sv
@tjaychen found an issue that shadow reg prediction doesn't work with scb.
we update some internal variable after each write for shadow regs or regwen, 
which was done at post_write. In the scb, `csr.predict` is invoked before this 
post_write, which causes the issue.
Change post_write to pre_do_predict and call it at the beginning of do_predict.
I end up also adding following enhancements.
1. move the 2nd shadow write to csr_utils_pkg and call predict after each write, otherwise,
one write and one predict are done in dv_base_reg, the other write and predict are done in csr_pkg_utils
2. remove one semaphore for shadow reg and couple other variables as not needed now
3. use csr_wr in csr_update to avoid many replicated codes
=> [dv] Fix shadow reg predict

hw/ip/gpio/dv/env/gpio_scoreboard.sv
This PR fixes intr_test failure in gpio.
The root cause is the recent change in intr_test procedure.
We used to:
1). write all interrupt related registers.
2). read all interrupt related registers, and compare the value with
mirrored vale from scb prediction.
The recent changes step 2).
Now 2). Get mirrored value from RAL, then read all interrupt registers
and compare the read value with stored mirrored value.
This change makes sense but does not work for GPIO, because GPIO
scoreboard has a cycle accurate model and it won't update intr_state
values until next TL read's address phase.
To solve this issue, we ignore the cycle accurate model and just call
csr predict right after csr write operation.
Thanks Weicai for helping out with this issue.
Signed-off-by: Cindy Chen …
=> [dv/gpio] fix intr_test regression failure

hw/ip/prim/util/primgen.py
Two small fixes to primgen to make the generated output more stable (no functional change), and to actually enable the use of Verible.
=> [primgen] Small fixes

hw/top_earlgrey/data/chip_testplan.hjson
Update full chip testplan for clkmgr and pwrmgr from the notes of the
test review.
=> [dt/top_earlgrey] Update testplan

hw/ip/keymgr/rtl/keymgr.sv, hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_entropy.sv, hw/ip/kmac/rtl/kmac_pkg.sv, hw/ip/prim/prim_lfsr.core, hw/ip/prim/rtl/prim_lfsr.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv
Address items in #1920 
[keymgr] Enable non-linear lfsr outputs
[kmac] Update lfsr configurations
- Add permutation
- Add non-linear output transformation
=> [keymgr, kmac] LFSR updates 

hw/dv/tools/dvsim/common_sim_cfg.hjson, hw/dv/tools/xcelium/cov_report.tcl, hw/dv/tools/xcelium/cover.ccf, util/dvsim/sim_utils.py
Ignore the first commit - its a part of another PR. 
THe second commit makes minor fixes and enables branch and statement coverage to be collected with Xcelium.
=> Xcelium cov statement score

hw/ip/aon_timer/rtl/aon_timer.sv, hw/ip/pinmux/rtl/pinmux.sv, hw/ip/usbdev/rtl/usbdev_aon_wake.sv
=> [wkup] Add assertion to ensure latching of wakeup signals

hw/ip/keymgr/doc/checklist.md
Advance keymgr to D2.
Pending on #7562
=> [keymgr] Advance to D2

hw/ip/rstmgr/doc/_index.md
=> [doc/rstmgr] Fix typo in functional spec

hw/ip/pwrmgr/dv/env/pwrmgr_env_pkg.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
Make necessary changes to enable xcelium simulator.
=> [dv/pwrmgr] Enable xcelium

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv, hw/ip/keymgr/dv/env/keymgr_if.sv, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv, hw/ip/keymgr/dv/keymgr_sim_cfg.hjson
Also add shadow error test in hjson
=> [dv] Add checks for Aes, Otbn sideload

hw/ip/csrng/dv/env/csrng_env_cfg.sv
=> [csrng/dv] Fix for issue #7703

hw/dv/sv/cip_lib/doc/index.md
Update doc to reflect recent changes
=> [dv] Update doc for TLUL integrity

hw/dv/tools/dvsim/testplans/stress_all_with_reset_testplan.hjson
=> [dv] Change stress_all_with_rand_reset to V3

hw/_index.md
=> [doc] Capitalize DV in links

hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
- Fixes #7745
- Make sure clearing of one key does not block another key from being used
=> [keymgr] Fix sideload key clear

hw/ip/spi_host/rtl/spi_host_fsm.sv
This commit handles two FSM bugs in the SPI_HOST TX path.
1. This commit adds a separate "prestall" copy of the FSM state to
prevent commands being dropped when no data is avaiable in the TX queue.
Since a stall prevents the FSM from updating command_valid signals were
previously being ignored during stall conditions, as the state machine
would not transition at this time.   This is solved by queuing an update
of the FSM in the "prestall" state variable, and performing the state
transition once the stall has been resolved.
NOTE: the simpler solution of deasserting command_ready during stalls does
not work, because the stall condition depends on the state, which in turn
depends on command_ready.  Making the FSM state directly dependent on
stall creates an unresolvable logical cycle.
2. …
=> [spi_host,design] Properly handle TX "stall" and "flush" conditions

hw/ip/csrng/dv/env/csrng_scoreboard.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
Fix so commands on both channels run in parallel. Added uninstantiate command.
=> [csrng/dv] Fix for multiple commands in parallel

hw/ip/otbn/dv/rig/rig/model.py
This commit includes a bug fix for implementing increments in the
model. The mask argument is removed and now is hard-coded in the
function body for 32 bits.
Fixes: #7805
=> [otbn,dv] Model Bug Fix for Instructions with Increment

hw/ip/pwrmgr/dv/sva/pwrmgr_clock_enables_if.sv
Compare usb_clk_en against the captured value of usb_clk_en_active_i
since the latter value can change anytime.
=> [dv/pwrmgr] Fix assertion for usb_clk_en_active

hw/ip/otbn/dv/rig/rig/gens/bad_at_end.py
This crashed into several assertions (running out of fuel, generating
things with the wrong PC, and then leaving the model at the wrong PC).
Most of the confusion is because `Jump.gen_tgt()` behaves differently
from `Loop._pick_head` and `Branch.gen_head`.
Fixes #7777.
=> [otbn,dv] Fix BadAtEnd generator when generating jumps

hw/dv/tools/dvsim/xcelium.hjson
=> [dv] Fix timescale issue with Xcelium

hw/top_earlgrey/data/chip_testplan.hjson
- This commit addresses the comments and updates from the testplan
review meeting held on 08/27/2021.
- The meeting notes are below:
- Updated the sysrst-ctrl section of the testplan based on new design
changes.
=> [doc, testplan] Update chip testplan for sysrst_ctrl

hw/ip/kmac/data/kmac_base_testplan.hjson, hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
=> [dv/kmac] add alert tests to .hjson files

hw/top_earlgrey/ip/xbar_main/dv/autogen/xbar_cover.cfg, util/tlgen/xbar_cover.cfg.tpl
Thanks Sri for pointing out, fixed excluding one more bit.
=> [xbar/dv] Fix exclusion

hw/top_earlgrey/ip/ast/data/ast.hjson, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv, util/topgen/templates/chiplevel.sv.tpl
=> [ast] Add POKs 3.3V

azure-pipelines.yml
=> [ci] remove nexysvideo build

hw/ip/tlul/rtl/tlul_sram_byte.sv
With the previous version, the `a_ack_q` flop was dead zero if
`EnableIntg` was false. This caused AscentLint warnings about a constant
flop. Re-jig things so that the flop is only generated when it will be
used and the output signal (`a_ack_q`) is a constant zero if not.
@msfschaffner: Does this look sensible to you? If a waiver would be a better way to go, happy to do that (or let you do it) instead.
=> [tlul,rtl] Rewrite a_ack_q computation to avoid lint warnings

hw/ip/pwrmgr/data/pwrmgr.prj.hjson, hw/ip/pwrmgr/data/pwrmgr_testplan.hjson, hw/ip/pwrmgr/doc/checklist.md
Add stress as a testpoint for V3.
=> [dv/pwrmgr] Declare V1

sw/device/lib/dif/dif_lc_ctrl.c, sw/device/lib/dif/dif_lc_ctrl.h, sw/device/lib/dif/dif_lc_ctrl_unittest.cc
=> [dif/lc_ctrl] add support for new test states

hw/ip/otbn/dv/otbnsim/sim/insn.py
=> [otbn,dv] Cast new address to u32 for BEQ/BNE in ISS

doc/project/_index.md, doc/project/contributing.md, doc/project/detailed_contribution_guide/_index.md, doc/project/detailed_contribution_guide/contributing_code_flow_chart.svg
This document gives detailed guidance on contributing to the OpenTitan
project. It has gone through many rounds of review in GDoc form (and
this PR simply converts that to Markdown, with the odd grammatical fix
along the way).
The contribution guide effort was kicked off by Pirmin and has since
seen suggestions, edits, and commits from a wide number of people across
the project. Thank you to everyone for your input.
=> [doc] Add detailed contribution guide

doc/project/detailed_contribution_guide/_index.md
=> [doc] Hotfix for broken link

sw/device/silicon_creator/lib/irq_asm.S, sw/device/silicon_creator/lib/irq_asm_functest.c, sw/device/silicon_creator/lib/meson.build, sw/device/silicon_creator/mask_rom/mask_rom_start.S, sw/device/silicon_creator/mask_rom/meson.build, test/systemtest/earlgrey/config.py
=> [mask_rom] Add pre-CRT safe exception handler

hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_random_vseq.sv, hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv, hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_init_fail_vseq.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_smoke_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_smoke_vseq.sv, hw/ip/rv_timer/dv/env/seq_lib/rv_timer_cfg_update_on_fly_vseq.sv, hw/ip/rv_timer/dv/env/seq_lib/rv_timer_disabled_vseq.sv, hw/ip/rv_timer/dv/env/seq_lib/rv_timer_random_vseq.sv, util/reggen/uvm_reg_base.sv.tpl
Even if the multi-reg only contains one item, so that it's eaiser to use
when the size of multi-reg is parameterized
This PR will solve issue #7836
=> [dv] Update RAL-gen to make all multi-reg to arrays

hw/ip/otbn/rtl/otbn_decoder.sv
When an instruction attempted to do multiple increments with indirect
register addressing (which produces an illegal instruction error),
multiple increment signals got set violating a unique constrait for the
case statement used to mux the possible increments.
Fixes #7884
=> [otbn] Fix multiple increment signals from decoder

hw/ip/prim/lint/prim_fifo.waiver, hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv, hw/ip/spi_device/data/spi_device.hjson, hw/ip/spi_device/lint/spi_device.waiver, hw/ip/spi_device/rtl/spi_device.sv, hw/ip/spi_device/rtl/spi_device_pkg.sv, hw/ip/spi_device/rtl/spi_device_reg_pkg.sv, hw/ip/spi_device/rtl/spi_device_reg_top.sv, hw/ip/spi_device/rtl/spid_upload.sv
This PR includes #7742 and #7794  #7815
=> [spi_device] Instantiate Upload submodule

hw/ip/keymgr/data/keymgr.hjson, hw/ip/keymgr/doc/_index.md, hw/ip/keymgr/dv/env/keymgr_if.sv, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv, hw/ip/keymgr/rtl/keymgr.sv, hw/ip/keymgr/rtl/keymgr_ctrl.sv, hw/ip/keymgr/rtl/keymgr_kmac_if.sv, hw/ip/keymgr/rtl/keymgr_pkg.sv, hw/ip/keymgr/rtl/keymgr_reg_pkg.sv, hw/ip/keymgr/rtl/keymgr_reg_top.sv
This PR started off as an attmempt to fix #7902,
however in the process of doing so, it was discovered there
are more issues with how keymgr handled dummy transactions
in the disabled state.
This PR attempts to fix those issues.
The first commit will be rebased away once #7941 is merged.
=> [keymgr] Clean-up and bug fix for keymgr

hw/ip/rstmgr/data/rstmgr_testplan.hjson, hw/ip/rstmgr/doc/checklist.md, hw/ip/rstmgr/doc/dv/index.md
=> [dv/rstmgr] Update DV docs for V1

doc/ug/directory_structure.md
=> [doc] Add pre_dv area to directory structure doc

sw/device/lib/dif/dif_rv_timer.c, sw/device/lib/dif/dif_rv_timer.h, sw/device/lib/dif/dif_rv_timer_unittest.cc
=> [dif/rv_timer] add function to write to counter

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
This PR fixes regression error on same_csr_outstanding. This sequence
uses tl_access instead of csr_wr thus did not perform two writes for
shadow regs.
=> [dv/shadow_reg] Fix same_csr_outstanding shadow reg issue

hw/ip/keymgr/data/keymgr.hjson, hw/ip/keymgr/doc/_index.md, hw/ip/keymgr/dv/env/keymgr_env_cfg.sv, hw/ip/keymgr/dv/env/keymgr_if.sv, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv, hw/ip/keymgr/rtl/keymgr.sv, hw/ip/keymgr/rtl/keymgr_ctrl.sv, hw/ip/keymgr/rtl/keymgr_pkg.sv, hw/ip/keymgr/rtl/keymgr_reg_pkg.sv, hw/ip/keymgr/rtl/keymgr_reg_top.sv, sw/device/lib/dif/dif_keymgr.c, sw/device/lib/dif/dif_keymgr_unittest.cc
=> [keymgr] Fix for error capture

hw/ip/otp_ctrl/dv/env/otp_ctrl_env.core, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_base_vseq.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_callback_vseq.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_vseq_list.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_wake_up_vseq.sv
This PR adds a callback virtual sequence for close source to extend.
=> [dv/otp_ctrl] Add a callback sequence

hw/ip/aes/rtl/aes_core.sv
This PR inserts a mux between the masked cipher core output and the data output register/feedback path to: 
1. Avoid SCA leakage occuring from unmasking intermediate cipher core outputs.
2. Increase the difficulty for extracting intermediate data via FI.
Adding this additional mux has been on my list for a very long time now but I couldn't do it as the SCA setup wasn't working. I have an SCA experiment running to verify that this is working as intended, but I think it can still be reviewed in the meantime.
=> [aes] Only unmask final cipher core output

hw/ip/aes/pre_syn/syn_yosys.sh, hw/ip/prim/rtl/prim_subreg_shadow.sv
This PR contains some minor modifications to re-enable Yosys synthesis for AES.
=> [aes] Re-enable Yosys synthesis

hw/ip/otbn/dv/rig/rig/configs/base.yml, hw/ip/otbn/dv/rig/rig/gens/bad_branch.py, hw/ip/otbn/dv/rig/rig/snippet_gens.py
This commit includes branch instructions that has out of bounds
addresses
=> [otbn,dv] Implemented Bad Branch Snippet Generator

hw/ip/alert_handler/data/alert_handler.hjson, hw/ip/alert_handler/data/alert_handler.hjson.tpl, hw/ip/alert_handler/dv/env/alert_handler_scoreboard.sv, hw/ip/alert_handler/dv/env/seq_lib/alert_handler_base_vseq.sv, hw/ip/alert_handler/rtl/alert_handler_reg_pkg.sv, hw/ip/alert_handler/rtl/alert_handler_reg_top.sv, hw/ip/alert_handler/rtl/alert_handler_reg_wrap.sv, hw/ip/prim/rtl/prim_subreg_shadow.sv, hw/top_earlgrey/ip/alert_handler/data/autogen/alert_handler.hjson, hw/top_earlgrey/ip/alert_handler/rtl/autogen/alert_handler_reg_pkg.sv, hw/top_earlgrey/ip/alert_handler/rtl/autogen/alert_handler_reg_top.sv, sw/device/lib/dif/dif_alert_handler.c, sw/device/lib/dif/dif_alert_handler_unittest.cc, util/reggen/reg_top.sv.tpl, util/reggen/register.py
This partially addresses #7748
=> [alert_handler] Make the CLR register shadowed

hw/ip/otbn/dv/rig/rig/gens/small_val.py
This was causing bugs where we tried to express 2048 (= 64 << 5) as a
12-bit signed value. Refactor things a bit to make it more obvious how
everything works, and also squash down the unshifted range a bit again
to make it more likely we'll see values like -1 or -2.
=> [otbn,dv] Fix overflow in small value generator

hw/dv/verilator/cpp/dpi_memutil.cc
This ensures that NOBITS sections, which may have a LMA in RAM, are
not included in the final binary image.
Fixes #8075.
=> [verilator] Use FileSz rather than MemSz when flattening ELF files

hw/ip/csrng/dv/env/csrng_env.sv, hw/ip/csrng/dv/env/csrng_env_cfg.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv, hw/ip/csrng/dv/tb.sv, hw/ip/csrng/dv/tests/csrng_smoke_test.sv
=> [csrng/dv] Changed efuse to otp interface

hw/ip/alert_handler/data/alert_handler.hjson, hw/ip/alert_handler/data/alert_handler.hjson.tpl, hw/top_earlgrey/ip/alert_handler/data/autogen/alert_handler.hjson
=> [alert_handler] Minor description fix in Hjson

hw/ip/keymgr/rtl/keymgr_ctrl.sv
- Make the behavior of lc disable during init consistent with others.
- When an lc disable is encountered during init, do not complete
the init transaction and instead go to wipe key and report
invalid operation.
=> [keymgr] Fix for lc disable during init.

hw/ip/clkmgr/doc/_index.md
=> [clkmgr, doc] Update hardware assumptions in docs.

hw/ip/keymgr/dv/env/keymgr_if.sv, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
Fix a few issues and these 2 tests are passing now
1. loose 2 cycle key check when we start to wipe key
2. Fix hw input valid check
3. Fix to unlock sw_binding_regwen only when advance is done
successfully
4. clean up is_fault_err
=> [keymgr/dv] Fix keymgr_kmac_rsp_err and keymgr_hwsw_invalid_input

hw/ip/pwrmgr/doc/_index.md, hw/top_earlgrey/doc/_index.md
- clarify pwrmgr handling for both fall-through / abort
- Add references in top level documentation
=> [pwrmgr, top] Update documentation regarding flash / reset

hw/ip/alert_handler/rtl/alert_handler_reg_wrap.sv, hw/ip/sram_ctrl/rtl/sram_ctrl.sv, hw/ip/tlul/rtl/tlul_adapter_host.sv
=> [alert_handler] Add new signals to alert aggregation

hw/ip/keymgr/rtl/keymgr_ctrl.sv
=> [keymgr] Align spec and implementation

hw/ip/keymgr/rtl/keymgr_ctrl.sv
=> [keymgr] Distinguish disabled / invalid for fault purposes

hw/ip/otbn/dv/rig/rig/gens/bad_load_store.py
There was a bug before, where the second branch could pick a `tgt_addr`
that was much smaller than `val + min_offset` (if `val` was very big
compared with `model.dmem_size`).
Also, force correct alignment most of the time.
(To reproduce the problem we were seeing, run `hw/ip/otbn/dv/rig/otbn-rig gen --size 1500 --seed 42 -o /dev/null` on the parent of this commit).
=> [otbn,dv] Sort out address selection in bad_load_store.py

util/check_dif_statuses.py
Added ability to aggregate and report alert and IRQ DIFs per IP
block. This will enable one to get a global view of all of these
interfaces so we can move towards more code re-use between DIFs.
=> [util] added features to DIF status check tool

hw/ip/keymgr/dv/env/keymgr_if.sv
=> [keymgr/dv] Add checking 2 shares of key are different after wipe

hw/ip/csrng/doc/_index.md
All input options to csrng app interface commands have been added to make it clear what capabilites are supported.
=> [csrng/doc] options added to csrng app commands

hw/ip/rstmgr/data/rstmgr_testplan.hjson, hw/ip/rstmgr/dv/env/rstmgr_env.core, hw/ip/rstmgr/dv/env/rstmgr_env_cov.sv, hw/ip/rstmgr/dv/env/rstmgr_if.sv, hw/ip/rstmgr/dv/env/rstmgr_scoreboard.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_por_stretcher_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_smoke_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_vseq_list.sv, hw/ip/rstmgr/dv/rstmgr_sim_cfg.hjson, hw/ip/rstmgr/dv/sva/rstmgr_cascading_sva_if.sv, hw/ip/rstmgr/dv/tb.sv
Also fix cascading reset assertions defects revealed by this test.
=> [dw/rstmgr[ Add POR stretching test and covergroup

hw/ip/otbn/dv/otbnsim/sim/insn.py, hw/ip/otbn/dv/otbnsim/sim/state.py
Put in an explicit check on the various places where we could specify
a bad next PC and then put an assertion in `set_next_pc()` to make sure
we don't use it wrongly.
This should improve the documentation for JAL, JALR, BEQ and BNE.
What's more, it means we can represent things like the current RTL
behaviour on a branch or jump to an invalid address that occurs as the
final instruction of a loop body. In these cases, the RTL signals both
`ErrBits.LOOP` and `ErrBits.BAD_INSN_ADDR`, which seems like a sensible
behaviour. Match it!
This is related to https://github.com/lowRISC/opentitan/issues/7809 (because it's an example where we can trigger multiple errors at once and want to correctly model what should happen).
=> [otbn] Change how the ISS checks jump/branch destinations

hw/dv/tools/dvsim/vcs.hjson
=> [dv] Only enable VCS -kdb when dumping waves

hw/ip/otbn/dv/verilator/otbn_top_sim.cc
The `verilator_top.reset()` line was only being run when we exited
successfully. If not, we ended up destructing the `std::unique_ptr` and
thus its contents somewhere inside the CRT's `run_exit_handlers`.
It turns out that there's a race where a singleton in the Verilator
library *must* exist when you run the constructor or destructor and
you get a segfault if `verilator_top` happens to have a longer lifetime
than the singleton.
Fix things by being stupider: use a raw pointer to pass the object to
`OtbnTopApplyLoopWarp` (the DPI function that needs it). This will be
dangling after we exit `main()` and have destroyed the object, but we
don't really care.
Arguably, it would be nice if this sort of race didn't matter at all. I've opened https://github.com/verilator/verilator/issues/3121 on …
=> [otbn,dv] Fix segfault when otbn_top_sim exited with failure

hw/ip/pwm/rtl/pwm.sv, hw/ip/pwm/rtl/pwm_chan.sv, hw/ip/pwm/rtl/pwm_core.sv
- Try to run the sv formatter on PWM RTL codes
- Some of the code arrangements are weird after running the sv formatter in pwm_chan.sv, I don't think the code format after running the formatter is optimal. What do you think?
=> [WIP][pwm, rtl] SV formatter trial

doc/ug/getting_started_fpga.md, hw/top_earlgrey/data/placement.xdc
=> [fpga] Update documentation based on #8138 analysis

doc/rm/register_tool/index.md, hw/ip/prim/rtl/prim_subreg_shadow.sv, util/reggen/register.py
=>  [prim_subreg_shadow] Disallow phase updates when storage err is present 

hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.hjson
=> [sensor_ctrl] Exclude ast status from csr tests

hw/ip/otbn/rtl/otbn_controller.sv
The read and write enables going to the base register file now factor in
whether or not an illegal instruction encoding was used, or if the
instruction performs an illegal CSR/WSR access. This prevents a call
stack error occurring when such an illegal instruction is seen.
Errors caused by indirect register accesses also cause illegal
instruction errors but cannot be factored into the register enables to
avoid a combinational loop.
Discussion in https://github.com/lowRISC/opentitan/pull/8180 to be resolved before this is merged.
=> [otbn,rtl] Prevent illegal instructions causing call stack errors

hw/ip/keymgr/dv/env/seq_lib/keymgr_common_vseq.sv
Change csr_vseq_done flag default value to 1
=> [keymgr/dv] Fix shadow reg timeout

hw/ip/entropy_src/data/entropy_src_testplan.hjson, hw/ip/entropy_src/dv/env/entropy_src_env.sv, hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv, hw/ip/entropy_src/dv/env/entropy_src_env_pkg.sv, hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv, hw/ip/entropy_src/dv/tb/tb.sv, hw/ip/entropy_src/dv/tests/entropy_src_base_test.sv, hw/ip/entropy_src/dv/tests/entropy_src_rng_test.sv
=> [entropy_src/dv] Removed LFSR mode, changed efuse to otp interface

hw/dv/tools/dvsim/vcs.hjson
Address Sri's comment at #8195
=> [dv] Use sed to add -elfile for each excl file

hw/top_earlgrey/ip/ast/ast.core, hw/top_earlgrey/ip/ast/data/ast.hjson, hw/top_earlgrey/ip/ast/doc/ast_regs.html, hw/top_earlgrey/ip/ast/rtl/aon_clk.sv, hw/top_earlgrey/ip/ast/rtl/aon_osc.sv, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_reg_pkg.sv, hw/top_earlgrey/ip/ast/rtl/ast_reg_top.sv, hw/top_earlgrey/ip/ast/rtl/io_clk.sv, hw/top_earlgrey/ip/ast/rtl/io_osc.sv, hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv, hw/top_earlgrey/ip/ast/rtl/sys_clk.sv, hw/top_earlgrey/ip/ast/rtl/sys_osc.sv, hw/top_earlgrey/ip/ast/rtl/usb_clk.sv, hw/top_earlgrey/ip/ast/rtl/usb_osc.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv, util/topgen/templates/chiplevel.sv.tpl
=> [ast] Add clocks, resets, & minor changes

hw/dv/sv/csrng_agent/csrng_item.sv, hw/dv/sv/csrng_agent/csrng_monitor.sv, hw/ip/csrng/dv/env/csrng_env_cfg.sv, hw/ip/csrng/dv/env/csrng_scoreboard.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv, hw/ip/csrng/dv/tb.sv, hw/ip/csrng/dv/tests/csrng_base_test.sv
=> [csrng/dv] Modified cmd randomization, Cleaned up knobs/constraints

hw/ip/keymgr/rtl/keymgr_ctrl.sv
=> [keymgr] Latch async faults such that they are permanent

hw/ip/adc_ctrl/adc_ctrl.core, hw/ip/flash_ctrl/flash_ctrl_pkg.core, hw/ip/otp_ctrl/otp_ctrl.core, hw/ip/prim_generic/prim_generic_flash.core, hw/top_earlgrey/dv/chip_sim.core
Signed-off-by: Sharon Topaz <sharon.topaz@nuvoton.com>
Adding an option to use partner ast_pkg instead of open source ast_pkg
=> option to use partner ast_pkg

hw/ip/otbn/dv/model/iss_wrapper.cc, hw/ip/otbn/dv/otbnsim/stepped.py
This commit includes an addition of re-initializing OTBNSim when
reset happens.
=> [otbn,dv] OTBN Reset Re-Initializes OTBNSim Class

hw/ip/rstmgr/data/rstmgr_testplan.hjson, hw/ip/rstmgr/dv/env/rstmgr_env.core, hw/ip/rstmgr/dv/env/rstmgr_if.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_smoke_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_sw_rst_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_vseq_list.sv, hw/ip/rstmgr/dv/rstmgr_sim_cfg.hjson, hw/ip/rstmgr/dv/tb.sv
Also update tb.sv for multibit por_n_i.
=> [dv/rstmgr] Add sw_rst test

hw/ip/pattgen/data/pattgen_testplan.hjson, hw/ip/pattgen/doc/dv/index.md
- Updated test plan to include tests for all signals from CSR registers including corner cases
- Extended the range of test stimulus to exercise the full range of relevant operational values
- Updated covergroups to provide coverage for all tests stimulus including stimulus targeting corner cases
=> [pattgen dv] V1 updated testplan and index.md

hw/dv/sv/dv_base_reg/dv_base_reg.sv
In one of the previous PR, I accidentally committed some display
message. This PR removes them. 
Sorry about that.
=> [dv/dv_base_reg] remove debug display

hw/ip/keymgr/dv/env/keymgr_env_cfg.sv, hw/ip/keymgr/dv/env/keymgr_env_cov.sv, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_direct_to_disabled_vseq.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_sideload_vseq.sv
Also adjust some sequence to hit covergroups
Will update testplan in the next PR
=> [dv] Add functional coverage

hw/ip/otbn/doc/dv/index.md, hw/ip/otbn/doc/dv/model.svg
This is a bit complicated and I've explained it in person a couple of
times so it probably makes sense to document properly.
=> [otbn,doc] Add a diagram showing how the SV <-> Python bridge works

sw/device/silicon_creator/lib/shutdown.c, sw/device/silicon_creator/lib/shutdown_unittest.cc
=> [sw/silicon_creator] Enable local alerts in shutdown_init.

hw/top_earlgrey/ip/ast/ast.core, hw/top_earlgrey/ip/ast/rtl/aon_clk.sv, hw/top_earlgrey/ip/ast/rtl/aon_osc.sv, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_dft.sv, hw/top_earlgrey/ip/ast/rtl/io_clk.sv, hw/top_earlgrey/ip/ast/rtl/io_osc.sv, hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv, hw/top_earlgrey/ip/ast/rtl/sys_clk.sv, hw/top_earlgrey/ip/ast/rtl/sys_osc.sv, hw/top_earlgrey/ip/ast/rtl/usb_clk.sv, hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
=> [ast] FPGA prim support & integrity error alert

sw/host/opentitanlib/src/spiflash/flash.rs, sw/host/opentitanlib/src/spiflash/sfdp.rs, sw/host/opentitanlib/src/transport/ultradebug/mod.rs, sw/host/opentitanlib/src/util/parse_int.rs, sw/host/opentitantool/src/backend/mod.rs, sw/host/opentitantool/src/command/console.rs, sw/host/opentitantool/src/command/gpio.rs, sw/host/opentitantool/src/command/spi.rs
Run `cargo clippy`; heed its advice.
=> [opentitantool] Clean up lint

sw/device/silicon_creator/lib/shutdown.c, sw/device/silicon_creator/lib/shutdown_unittest.cc
=> [sw/silicon_creator] Disable flash during shutdown.

hw/ip/otbn/doc/dv/index.md
We are going to add a coverage point for each. The first step is to
carefully write down what we're trying to cover.
This is a tidied-up version of the list at https://github.com/lowRISC/opentitan/issues/7809#issuecomment-917008650.
=> [otbn,dv] Document insns that can cause multiple errors in DV doc

hw/ip/otbn/doc/_index.md, hw/ip/otbn/dv/verilator/otbn_top_sim.sv, hw/ip/otbn/rtl/otbn.sv, hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_pkg.sv, sw/device/lib/runtime/otbn.c, sw/device/silicon_creator/lib/drivers/otbn.c
=> [otbn, rtl] Implemented LOCKED state

hw/ip/kmac/doc/_index.md
=> [kmac/doc] Fix legacy register references

hw/ip/rstmgr/data/rstmgr.sv.tpl, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_smoke_vseq.sv, hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr.sv
- Fixes #7918
- Remove unnecessary dump capture
=> [rstmgr] Fix dump capture conditions

.bazelrc, WORKSPACE, sw/device/lib/base/BUILD, sw/device/lib/base/testing/BUILD, sw/device/lib/dif/BUILD
This will replace https://github.com/lowRISC/opentitan/pull/8096 for now as it uses a different branch than master as it's source.
I'll rebase to a single commit before it gets merged in
=> [bazel] Rules for DIFs and DIF unittests

hw/ip/keymgr/data/keymgr.prj.hjson
This file should actually be updated in PR #7564
=> [keymgr] Move to D2

hw/ip/otbn/data/otbn_testplan.hjson, hw/ip/otbn/doc/dv/index.md, hw/ip/otbn/dv/uvm/env/otbn_env.core, hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sequential_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_smoke_vseq.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_vseq_list.sv, hw/ip/otbn/dv/uvm/gen-binaries.py, hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson, hw/ip/otbn/dv/verilator/run-some.py
=> [otbn,dv] Add coverage points for multi-error cases and hit them

hw/ip/keymgr/rtl/keymgr.sv, hw/ip/keymgr/rtl/keymgr_cfg_en.sv
=> [keymgr] Minor fix to external regwen

hw/ip/prim/rtl/prim_count.sv
1. Add assertions to check error case, these can be used in assertion
coverage for DV.
2. Update an assertion to cover both set_i and clr_i case.
=> [fpv/prim_count] Small update on prim_count assertions

hw/ip/keymgr/dv/env/keymgr_if.sv, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_cmd_invalid_vseq.sv
Also fix a corner case that operation didn't occur to trigger the state
to transition to StInvalid
=> [dv] Add testing CTRL_FSM_INTG and CTRL_FSM_CNT

hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
Remove write limit of sw_binding_regwen 
This small update for design change in #8323
=> [keymgr/dv] Update scb for sw_binding_regwen

hw/dv/tools/dvsim/testplans/harden_countermeasures_testplan.hjson, hw/ip/keymgr/data/keymgr_testplan.hjson, hw/ip/keymgr/dv/env/keymgr_env_cov.sv, hw/ip/keymgr/dv/env/keymgr_env_pkg.sv, hw/ip/keymgr/dv/env/keymgr_if.sv, hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
We can review this on V2 review meeting
=> [keymgr/dv] Update testplan and covergroup plan

hw/top_earlgrey/data/chip_testplan.hjson, sw/device/tests/meson.build, sw/device/tests/pwrmgr_smoketest.c
Add rstmgr RESET_INFO CSR checks.
Cross-reference test from aon_timer and rstmgr testpoints.
=> [dv/chip] Enhance pwrmgr_smoketest

hw/ip/keymgr/data/keymgr.hjson
Updated comments to make it more clear
=> [keymgr/dv] Update CSR exclusion comments

hw/ip/keymgr/rtl/keymgr_ctrl.sv, hw/ip/keymgr/rtl/keymgr_kmac_if.sv, hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv, hw/ip/prim/rtl/prim_count.sv
- clarify set_cnt_i usasge
- add step_i input
- adjust downcnt usage with step_i
=> [prim] Minor fix and clarification to prim_count

hw/ip/rstmgr/data/rstmgr.prj.hjson, hw/ip/rstmgr/doc/checklist.md
=> [dv/rstmgr] Declare V1

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh, hw/ip/keymgr/data/keymgr_testplan.hjson, hw/ip/keymgr/dv/env/keymgr_env.core, hw/ip/keymgr/dv/env/keymgr_env_cov.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_sync_async_fault_cross_vseq.sv, hw/ip/keymgr/dv/env/seq_lib/keymgr_vseq_list.sv, hw/ip/keymgr/dv/keymgr_sim_cfg.hjson
This is requested from V2 review.
Also added covergroup and updated testplan
=> [keymgr/dv] Add sync_async_fault_cross_vseq

hw/formal/tools/jaspergold/jaspergold.hjson, hw/formal/tools/vcformal/vcformal.hjson, util/dvsim/FormalCfg.py
This PR supports GUI for FPV runs on dvsim.
=> [fpv/tool] Support GUI mode on dvsim

hw/ip/spi_device/rtl/spi_tpm.sv
In previous design TPM sees `sck_p2s_sent` signal that is latched in SCK
posedge of `isck_p2s_sent`.
Problem:
`sck_p2s_sent` is half clock delayed signal of `isck_p2s_sent`. The
signal is not visible at the last beat of Address phase. After
moving to StartByte (if FIFO is ready), the state machine sees the
`p2s_sent` right away. Then moves to the next state without sending
StartByte.
To avoid this behavior, two options are possible:
1. Use `isck_p2s_sent` signal directly. Then, the logic sees the valid
`p2s_sent` the last half of the SCK. It requires the timing to be
less than half of SCK period. It is already one of the SPI_DEVICE
constraint.
2. Compute p2s_sent in SCK domain. Running another `bitcnt` in SCK, the
SCK also can compute when p2s_sent is asserted.
This commit chooses Option …
=> [spi_device] Adjust timing of p2s_sent

hw/ip/otbn/dv/otbnsim/sim/decode.py, hw/ip/otbn/dv/otbnsim/sim/isa.py
=> [otbn,dv] Add missing newlines to fix flake8 errors

hw/ip/rstmgr/data/rstmgr.hjson, hw/ip/rstmgr/data/rstmgr.hjson.tpl, hw/ip/rstmgr/data/rstmgr_testplan.hjson, hw/ip/rstmgr/doc/dv/index.md, hw/ip/rstmgr/dv/sva/rstmgr_attrs_sva_if.sv, hw/ip/rstmgr/dv/sva/rstmgr_bind.sv, hw/ip/rstmgr/dv/sva/rstmgr_sva.core, hw/ip/rstmgr/dv/sva/rstmgr_sva_ifs.core, hw/ip/rstmgr/rtl/rstmgr_reg_pkg.sv, hw/ip/rstmgr/rtl/rstmgr_reg_top.sv, hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson
Also make minor fixes to docs.
Remove common CSR test exclusion from sw_rst_regwen.
=> [dv/rstmgr] Add alert and cpu_info_attr assertions

hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_englishbreakfast/data/top_englishbreakfast.hjson
=> [top*.hjson] Fix minor typo

hw/ip/prim/rtl/prim_count.sv
=> [prim] Correct assertion valid term

hw/ip/otbn/dv/rig/rig/configs/base.yml, hw/ip/otbn/dv/rig/rig/gens/misaligned_load_store.py, hw/ip/otbn/dv/rig/rig/snippet_gens.py
Misaligned load-store generates valid but misaligned address which
results with an error.
Co-authored-by: Rupert Swarbrick <rswarbrick@lowrisc.org>
=> [otbn,dv] Misaligned load/store snippet

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/data/flash_ctrl_pkg.sv.tpl, hw/ip/flash_ctrl/flash_ctrl.core, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv, hw/ip/prim/rtl/prim_count.sv, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_core_reg_top.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_pkg.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_pkg.sv
Earlier PRs need to be merged first. 
- sparsely encode RMA transition FSM
- Add hardened count for RMA processing
- TODO: Shadow registers for flash pmp (#8295)
=> [flash_ctrl] Flash_ctrl hardening

hw/ip/clkmgr/data/clkmgr_testplan.hjson, hw/ip/clkmgr/dv/clkmgr_sim_cfg.hjson, hw/ip/clkmgr/dv/env/clkmgr_env.core, hw/ip/clkmgr/dv/env/clkmgr_env_cfg.sv, hw/ip/clkmgr/dv/env/clkmgr_env_pkg.sv, hw/ip/clkmgr/dv/env/clkmgr_scoreboard.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_frequency_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_vseq_list.sv
Also update the testplan for this and new features of clock dividing.
=> [dv/clkmlgr] Add test for frequency measurements

hw/ip/keymgr/data/keymgr.prj.hjson, hw/ip/keymgr/doc/checklist.md
=> [keymgr/dv] Sign off V2

hw/ip/spi_device/rtl/spi_tpm.sv
Previous TPM state machine missed the control signal of
`latch_locality`. It should be asserted when the logic receives
addr[12] (`cmdaddr_bitcnt` equals to `19`).
This PR contains #8404 change too (to avoid conflict when merge)
=> [spi_device] Adding latch_locality condition

util/ipgen/lib.py, util/ipgen/renderer.py, util/topgen/intermodule.py, util/topgen/resets.py
To prepare the use of ipgen to generate rv_plic (and then other IP templates) we need to make some improvements to it. This PR contains a series of commits which were developed and tested on the rv_plic conversion.
=> [ipgen] Various improvements

hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr_reg_top.sv
Seems like a mid-air collision happened in merging, causing master CI to
fail.
=> [clkmgr] Regenerate clkmgr

hw/dv/sv/csrng_agent/csrng_item.sv, hw/ip/csrng/dv/cov/csrng_cov.core, hw/ip/csrng/dv/cov/csrng_cov_bind.sv, hw/ip/csrng/dv/cov/csrng_cov_if.sv, hw/ip/csrng/dv/csrng_sim.core, hw/ip/csrng/dv/csrng_sim_cfg.hjson, hw/ip/csrng/dv/env/csrng_scoreboard.sv, hw/ip/csrng/dv/tb.sv
=> [csrng/dv] Added initial coverage files/code

hw/ip/spi_host/doc/_index.md
This update highlights a number of behavioral details that were noticed when writing
the implementation Design Details section.
For example, this update documents
- The specific idle/delay behavior when updating configuration settings between commands
- The definition of stall events.
=> [spi_host doc] Minor updates to Theory of Operation

hw/lint/tools/ascentlint/comportable.waiver
=> [lint] Add lint waiver for IP regfiles with shadow resets

hw/ip/rv_dm/lint/rv_dm.waiver
=> [rv_dm/lint] Minor lint fix

hw/ip/spi_host/rtl/spi_host_fsm.sv
=> [spi_host/lint] Minor lint fix

hw/dv/tools/dvsim/testplans/sec_cm_testplan.hjson, hw/ip/keymgr/data/keymgr_testplan.hjson
Also update keymgr testplan to add additional check for sec_cm
=> [dv] Update sec_cm testplan

hw/ip/rstmgr/data/rstmgr.sv.tpl, hw/ip/rstmgr/rtl/rstmgr.sv, hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr.sv
=> [rtl/rstmgr] Remove redundant import

hw/ip/alert_handler/rtl/alert_handler.sv
=> [alert_handler] Add missing output assertion

hw/ip/prim/rtl/prim_lfsr.sv
=> [prim_lfsr] Minor lint fix

doc/rm/ipgen_tool.md, doc/rm/topgen_tool.md, util/ipgen.py, util/ipgen/renderer.py
Some more commits which are split out of the rv_plic ipgen conversion to keep the PR small(er).
=> [ipgen] More preparations for ipgen and switching IP cores to templates

hw/ip/entropy_src/dv/env/entropy_src_env_cfg.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_common_vseq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv, hw/ip/entropy_src/dv/tests/entropy_src_base_test.sv, hw/ip/entropy_src/dv/tests/entropy_src_smoke_test.sv, hw/ip/entropy_src/rtl/entropy_src_pkg.sv
=> [entropy_src/dv] Added/Modified enable-type knobs

hw/ip/pattgen/data/pattgen_testplan.hjson, hw/ip/pattgen/dv/cov/pattgen_cov_bind.sv, hw/ip/pattgen/dv/cov/pattgen_cov_if.sv
Signed-off-by: alex <alex.sapozhnikov@wdc.com>
=> added pattgen_testplan.hjson pattgen_cov_bind.sv pattgen_cov_if.sv

util/fpga/splice_rom.sh
Parameterize the splice script, and add support for splicing ROM production images. 
=> [util] Splice for prod ROM

sw/device/meson.build, sw/device/silicon_creator/rom_exts/meson.build, sw/device/tests/meson.build
Enable signing of the ROM_EXT with test keys.
=> [sw/rom_ext] Sign ROM_EXT images with test keys

hw/ip/flash_ctrl/rtl/flash_phy.sv, hw/ip/spi_device/rtl/spi_cmdparse.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_gpio_smoke_vseq.sv
Fix type mismatches.
There is a linkage error pending, but isolates that pending problem.
=> [dv/dsim] Get dsim to work at full chip

hw/ip_templates/alert_handler/data/alert_handler.prj.hjson, hw/ip_templates/alert_handler/doc/checklist.md, hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.prj.hjson, hw/top_earlgrey/ip_autogen/alert_handler/doc/checklist.md
~~This should not be merged before #8490 and #8518 have landed.~~ PR's have landed.
~~Also, we still need to converge on the question whether #2049 and #8037 is actually enough on the escalation side, or whether some more clock / reset checking is needed.~~ It has been decided to handler this at the integration level and not inside the escalation sender / receiver modules.
=> [alert-handler/doc] Move into D2

hw/ip/spi_host/rtl/spi_host_core.sv, hw/ip/spi_host/rtl/spi_host_fsm.sv, hw/ip/spi_host/rtl/spi_host_shift_register.sv
- Update the cmd_end_o logic to fix the issue #8643
- Spit the cmd_end_o to last_read_o and last_write_o to handle read and write separately
- Fixes #8643
=> [spi_host, rtl] SPI_HOST RTL update to fix issue #8643

sw/device/lib/base/meson.build, sw/device/lib/base/multibits.h, sw/device/lib/dif/dif_entropy_src.c, sw/device/lib/dif/dif_entropy_src_unittest.cc, util/design/data/multibits.h.tpl, util/design/data/prim_mubi_pkg.sv.tpl, util/design/mubi/prim_mubi.py, util/reggen/field.py
Standardize mubi values to be used with mubi declared types.
=> [sw] Add mubi header enums

hw/ip/spi_host/rtl/spi_host_fsm.sv
- Fixes a bug in which there was no wait counter associated with the
CSBSwitch state (it was using the wait_idle counter, but this
counter was not being appropriately reset on entering CSBSwitch)
- Refactors the wait_idle, wait_lead, and wait_trail counters
into a single wait_cntr that can be commonly managed
- wait_cntr is properly reset up entering the WaitIdle, WaitLead,
WaitTrail and CSBSwitch states
=> [spi_host, rtl] Fix/Refactor state wait counters in SPI_HOST FSM

hw/dv/tools/dvsim/xcelium.hjson
=> [dv,xcelium] minor cleanup

hw/top_earlgrey/formal/top_earlgrey_fpv_cfgs.hjson
This PR updates the core file name for alert_handler related FPV
targets.
=> [fpv] alert template corefile update

hw/ip_templates/alert_handler/doc/_index.md, hw/top_earlgrey/ip_autogen/alert_handler/doc/_index.md
This PR fixes a register naming.
=> [doc/alert_handler] Update register naming

util/check_dif_statuses.py
To make `check_dif_statuses.py` more consistent with existing Python tooling, this PR:
-(Commit 1): deprecates the requirement to pass the REPO_TOP in as a cmd line arg
-(Commit 2): deprecates the use of `os.path`module in favor of the `pathlib` module
**Note:** this PR depends on #8931, please only review the last two commits. (The duplicate from #8931 will be removed when merged.)
=> [util] Cleanup `check_dif_statuses.py` to prep for autogen DIF changes.

hw/top_earlgrey/data/chip_testplan.hjson
=> [top] Add missing sensor_ctrl test plan item.

sw/device/lib/dif/dif_aes.c, sw/device/lib/dif/dif_aes.h, sw/device/lib/dif/dif_aes_unittest.cc
This PR only contains:
- Implements new functions for CFB and OFB modes.
- Implements unit tests for ECB, CBC, CFB, CTK and OFB modes.
=> [dif] Implements the AES OFB and CFB modes

hw/ip_templates/alert_handler/rtl/alert_pkg.sv, hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_pkg.sv
=> [alert_handler] Minor lint fix

hw/ip/sram_ctrl/rtl/sram_ctrl.sv
Sorry, this fell between the cracks. The two integ failures from both TL-UL ports are now connected and OR'd together for triggering the alert and setting the error bit.
Let me know if you think there is value in splitting the error bit out into two error bits.
Fix #8970
=> [sram_ctrl] Connect second bus integ failure

hw/ip/edn/data/edn.hjson, hw/ip/edn/rtl/edn_core.sv
=> [edn] Convert to mubi usage.

sw/device/silicon_creator/rom_exts/docs/manifest.md
=> Add usage constraints to the manifest format documentation

hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
In previous design, the cmdfifo, addrfifo in the spid_upload module
reports the not empty status. The status bits are connected to the
UPLOAD_STATUS CSR for SW to read and check the status.
The not empty status, however, assert one clock earlier than the actual
`rvalid` signals.
The reason is due to the SRAM read latency. The upload module adopts
SRAM FIFO interface to maintain the cmd, addr FIFOs. When the logic in
SCK domain pushes entries, the pointer is increased. This triggers the
FIFO logic in the bus clock domain fetches data from SRAM.
The pointer crosses the clock boundary. It takes usually two cycles (in
the receiver side). Then, as the read and write pointer in the bus clock
domain has a gap by 1, the FIFO not empty status is raised.
At this time, the logic just sent the read …
=> [spi_device] Upload Cmd/Addr FIFO status revision

hw/ip/spi_device/rtl/spi_cmdparse.sv
cmd_info & cmd_info_idx are registered output in the cmdparse module.
The upload module in SPI_DEVICE uses cmd_info to determine if the
address field exists or not.
The cmd_info value arrives to the rest of the module one clock late. It
results in the upload module to assume the command does not have the
address field.
This commit pulls in the cmd_info one clock early. It leads to longer
datapath as cmdparse cannot register the data.
=> [spi_device] One clock early for the cmd_info timing

hw/dv/sv/key_sideload_if/key_sideload_if.core, hw/dv/sv/key_sideload_if/key_sideload_if.sv, hw/ip/kmac/dv/env/kmac_env.core, hw/ip/kmac/dv/env/kmac_env_pkg.sv, hw/ip/kmac/dv/tb.sv
Also changed to a parameterized interface so that it can be resued for
otbn
Addressed #8944
=> [dv] change kmac_sideload_if to a common sideload if

hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv, hw/ip/spi_device/pre_dv/spid_upload.core, hw/ip/spi_device/pre_dv/spid_upload_sim_cfg.hjson, hw/ip/spi_device/pre_dv/tb/spid_common.sv, hw/ip/spi_device/pre_dv/tb/spid_upload_tb.sv, hw/top_earlgrey/formal/top_earlgrey_fpv_cfgs.hjson
This commit implements a TB runs simple upload function. It uploads a
couple of commands and checks the content inside the SRAM.
- Command only
- Command and Address
- Command and Payload
- Command / Address / Payload
=> [spi_device] Add Upload TB

.github/CODEOWNERS
I am getting too much review requests that I am no longer having knowledge on them. So, I become ignoring any requests even the PRs & Issues that I should participate. 
This PR is to reduce the notifications so that I can focus on what I need to review.
=> Remove eunchan from CODEOWNERS for a few IPs

hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/formal/chip_conn_cfg.hjson, hw/top_earlgrey/formal/conn_csvs/clkmgr_ast.csv, sw/device/lib/dif/dif_clkmgr.c, sw/device/lib/dif/dif_clkmgr.h, sw/device/lib/dif/dif_clkmgr_unittest.cc, sw/device/lib/testing/clkmgr_testutils.h, sw/device/tests/clkmgr_jitter.c, sw/device/tests/clkmgr_smoketest.c, sw/device/tests/meson.build
Add dif support for the jitter enable csr.
Add dif unittest support for jitter enable csr.
=> [dv/full_chip] Add clkmgr jitter test

hw/ip/prim/rtl/prim_count.sv, hw/ip/prim/rtl/prim_reg_cdc.sv
=> [all] updated assert rtl ifdef

hw/ip/rstmgr/dv/env/rstmgr_env_cfg.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv
1. Added super.post_apply_reset as Cindy did in #8997
2. Added associated err_code for intg error in cfg
=> [dv] Fix rstmgr intg test

hw/top_earlgrey/ip/ast/ast.core, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_dft.sv, hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv, hw/top_earlgrey/ip/ast/rtl/gfr_clk_mux2.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_nexysvideo.sv, hw/top_earlgrey/rtl/chip_earlgrey_verilator.sv, hw/top_earlgrey/rtl/top_pkg.sv, util/topgen/templates/chiplevel.sv.tpl
=> [ast] Update Mubi and add all clocks bypass

hw/ip/sysrst_ctrl/data/sysrst_ctrl.hjson, hw/ip/sysrst_ctrl/doc/_index.md
=> [sysrst_ctrl/doc] Fix stale register references

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/ast_supply_if.sv, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_full_aon_reset_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_main_power_glitch_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, hw/top_earlgrey/dv/tb/tb.sv, sw/device/tests/meson.build, sw/device/tests/rstmgr_smoketest.c, sw/device/tests/sim_dv/meson.build, sw/device/tests/sim_dv/pwrmgr_main_power_glitch_test.c
Similar to existing power glitch test, which is renamed main power glitch.
=> [dv/full_chip] Add aon power glitch test

hw/ip/prim/rtl/prim_assert_standard_macros.svh
=> [dv] Fix ASSERT_INIT race condition

hw/ip_templates/alert_handler/dv/env/alert_handler_env.core, hw/ip_templates/alert_handler/dv/env/alert_handler_env.sv, hw/ip_templates/alert_handler/dv/env/alert_handler_env_cfg.sv, hw/ip_templates/alert_handler/dv/env/alert_handler_env_pkg.sv, hw/ip_templates/alert_handler/dv/env/alert_handler_if.sv, hw/ip_templates/alert_handler/dv/env/seq_lib/alert_handler_base_vseq.sv, hw/ip_templates/alert_handler/dv/tb/tb.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/alert_handler_env.core, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/alert_handler_env.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/alert_handler_env_cfg.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/alert_handler_env_pkg.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/alert_handler_if.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/seq_lib/alert_handler_base_vseq.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/tb/tb.sv
This PR adds an alert_handler_if drive lpg inputs.
=> [dv/alert_handler] Add an alert_handler_if

hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_nexysvideo.sv, hw/top_earlgrey/rtl/scan_role_pkg.sv, hw/top_englishbreakfast/data/top_englishbreakfast.hjson, util/topgen/gen_top_docs.py, util/topgen/templates/chiplevel.sv.tpl, util/topgen/validate.py
This is a first proposal to address #9046.
We may have to update it depending on some pending clarifications regarding pad attributes - see below.
=> [top/usb] Instantiate second pair of USB pads

util/design/secded_gen.py
Add a generic function in secded_gen to encode ECC for a particular value. 
This function should be re-used by otp / rom_ctrl generation so that if the ECC inversion is done in the future, all the resulting scripting can remain the same. 
The method used in this function is inspired by both `scramble_image.py` from `otp_ctrl` and `common.py` from otp image generation.
=> [util] Add generic ecc encode function for re-use

sw/device/tests/sim_dv/spi_tx_rx_test.c
When the interrupt keeps firing, PC can not go back to the main program,
Changed to disable the interrupt in interrupt routine instead of in the
main program
Thanks Sri for helping debug this issue.
=> [top/dv] Fix spi device failure

hw/ip/prim/fpv/tb/prim_alert_rxtx_async_fatal_tb.sv, hw/top_earlgrey/formal/top_earlgrey_fpv_cfgs.hjson
This PR fixes some typos that causes regression failure.
=> [fpv] Fix regression failures

hw/ip/spi_device/data/spi_device.hjson, hw/ip/spi_device/rtl/spi_cmdparse.sv, hw/ip/spi_device/rtl/spi_device.sv, hw/ip/spi_device/rtl/spi_device_pkg.sv, hw/ip/spi_device/rtl/spi_device_reg_pkg.sv, hw/ip/spi_device/rtl/spi_device_reg_top.sv, hw/ip/spi_device/rtl/spi_passthrough.sv, hw/ip/spi_device/rtl/spi_readcmd.sv, hw/ip/spi_device/rtl/spid_upload.sv
This commit implements the data manipulation feature in the passthrough                                                                                                                                        
mode.                                                                                                                                                                                                          
The data manipulation in the passthrough let SW change any bit of the                                                                                                                                          
first write data to the downstream flash device. …
=> [spi_device] Data manipulation logic in Passthrough mode

hw/ip/sram_ctrl/data/sram_ctrl.hjson
Signed-off-by: Silvestrs Timofejevs <silvestrst@lowrisc.org>
=> [hw, hjson] SRAM Controller use `multibits.h` in register desc

hw/ip/pwrmgr/dv/env/pwrmgr_if.sv, hw/ip/pwrmgr/dv/env/pwrmgr_scoreboard.sv
Avoid shadowing in update_control_enables.
=> [dv/pwrmgr] Fix sampling of control_cg

hw/ip_templates/alert_handler/dv/env/seq_lib/alert_handler_smoke_vseq.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/seq_lib/alert_handler_smoke_vseq.sv
This PR fixes the error from PR #9123 where the regwen write is
duplicated.
=> [dv/alert_handler] Fix merge duplicated error

hw/dv/sv/csrng_agent/seq_lib/csrng_device_seq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv, hw/ip/edn/dv/edn_sim_cfg.hjson, hw/ip/edn/dv/env/edn_env.core, hw/ip/edn/dv/env/edn_env.sv, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_vseq_list.sv, hw/ip/edn/dv/tests/edn_genbits_test.sv, hw/ip/edn/dv/tests/edn_test.core, hw/ip/edn/dv/tests/edn_test_pkg.sv
=> [edn/dv] Added genbits test/sequence, randomized genbits

hw/ip/prim/rtl/prim_count.sv
Fixed a Lint error found by Tim at #9099
=> [prim] Remove extra semicolon

hw/ip/otp_ctrl/dv/env/otp_ctrl_if.sv, hw/ip/otp_ctrl/dv/tb.sv
This PR fixes xcelium compile error in OTP regarding the types.
=> [dv/otp_ctrp] Fix xcelium error

hw/ip/otbn/dv/rig/rig/gens/bad_ispr.py
bad_ispr generated instructions with valid csr / wsr addresses. This
commit fixes the code.
=> [otbn, dv] Fixes bad_ispr issue of picking valid csr / wsr addr

hw/ip/prim/rtl/prim_mubi12_dec.sv, hw/ip/prim/rtl/prim_mubi16_dec.sv, hw/ip/prim/rtl/prim_mubi4_dec.sv, hw/ip/prim/rtl/prim_mubi8_dec.sv, util/design/data/prim_mubi_dec.sv.tpl
=> [prim] Add missing include to prim_mubi_dec*

.bazelrc, WORKSPACE, rules/bugfix.bzl, rules/opentitan.bzl, sw/device/BUILD, sw/device/examples/BUILD, sw/device/examples/hello_world/BUILD, sw/device/exts/common/BUILD, sw/device/lib/BUILD, sw/device/lib/arch/BUILD, sw/device/lib/arch/device.h, sw/device/lib/base/BUILD, sw/device/lib/crt/BUILD, sw/device/lib/runtime/BUILD, sw/device/lib/testing/BUILD
build files for the hello world example to run on riscV under verilator
=> [bazel] Hello world

util/design/gen-mubi.py
=> [util] Add missing file

hw/ip_templates/alert_handler/dv/env/alert_handler_scoreboard.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/alert_handler_scoreboard.sv
This PR fixes a race condition between crashdump change and reset.
=> [dv/alert_handler] Fix crashdump with reset

hw/ip/otbn/dv/otbnsim/sim/dmem.py
Following methdos were modified:
1. load_u32: It reads 32 bit data and returns it.
2. load_u256: It reads 32 bits of data 8 times, packs it into 256 bits
and returns it.
3. _commit_store: It unpacks 256 bits of data into eight 32 bits of data
and writes it into the memory.
=> [otbn,dv] Changed dmem width to 32 bits from 256 bits

util/reggen/field.py
=> [util] Document default resval for non-hwext registers

util/ipgen.py, util/ipgen/lib.py
=> [ipgen] Plumb TemplateParams through correctly

hw/ip/prim/rtl/prim_count.sv
- delay activation of check by 1 cycle to ensure it is not checked
immediately out of reset
=> [prim] quick patch to prim_count assertion

hw/ip/entropy_src/data/entropy_src.hjson, hw/ip/entropy_src/rtl/entropy_src.sv, hw/ip/entropy_src/rtl/entropy_src_adaptp_ht.sv, hw/ip/entropy_src/rtl/entropy_src_bucket_ht.sv, hw/ip/entropy_src/rtl/entropy_src_core.sv, hw/ip/entropy_src/rtl/entropy_src_markov_ht.sv, hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv, hw/ip/entropy_src/rtl/entropy_src_reg_top.sv, hw/ip/entropy_src/rtl/entropy_src_repcnt_ht.sv, hw/ip/entropy_src/rtl/entropy_src_repcnts_ht.sv
There are a number of critical health test counters that are to be replaced with a hardened version.
=> [entropy_src/rtl] health test counters hardening

hw/dv/sv/alert_esc_agent/alert_monitor.sv, hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv, hw/dv/sv/alert_esc_agent/alert_sender_driver.sv
Before alert_init finish, there might be another reset happen.
Previous code only handled the monitor part, this PR fixes the driver
part as well.
This PR also create a separate thread for alert_init from reset_thread.
Thanks @weicaiyang for finding this issue.
=> [dv/alert] Fix alert init

util/topgen.py, util/topgen/lib.py
=> [util] Add alternate hjson paths for reggen_only modules

hw/ip/otp_ctrl/data/otp_ctrl_img_dev.hjson, hw/ip/otp_ctrl/data/otp_ctrl_img_rma.hjson, test/systemtest/earlgrey/config.py
=> [ci] re-enable entropy and pwrmgr smoke tests

hw/ip/entropy_src/data/entropy_src.hjson, hw/ip/spi_host/data/spi_host.hjson
This fixes a couple of register references in the Hjsons.
Please take a look whether this is correct.
=> [entropy_src/spi_host/doc] Register reference fixes

hw/ip/prim/rtl/prim_count.sv
This PR fixes some assumptions in prim_count for cross mode.
1). The down counter underflow assumption used `%` that could be very
complex for FPV. I slightly change the assumption to avoid `%`.
2). Underflow and overflow assumptions should apply to all cross
counters because they have up and down counters.
3). ASSERT_INIT for FPV is only used for parameters and constants, thus
does not apply to the wire. Excluded that assertion check for simulation
only.
=> [fpv] Fix some assumptions in prim_count

doc/rm/otbn_style_guide.md
Add some advice on inline data, and update the variable-time example to show good practice with regard to the OTBN loop stack.
See discussion on #9141 for context on the inline data advice. The loop rearranging is because I re-read the [loop nesting](https://docs.opentitan.org/hw/ip/otbn/doc/#loop-nesting) advice and realized that the example, in trying to leave the loop early, would actually result in the loop not being cleared from the loop stack, which is not good practice.
=> [doc] Update OTBN style guide.

doc/project/development_stages.md
Some naming cleanup and addition of V2S milestone to FPV table.
=> [doc] Minor dev stages cleanup

hw/ip/spi_device/rtl/spi_cmdparse.sv, hw/ip/spi_device/rtl/spi_device.sv
This commit revises cmdparse state machine to raise `intercept` signal
when SW configures INTERCEPT_EN bit and receives specific commands (Read
Status, Read JEDEC, Read SFDP).
Mailbox is processed inside Read Command submodule not inside cmdparse.
=> [spi_device] Cmdparse to intercept Passthrough

hw/ip/spi_device/rtl/spi_device.sv, hw/ip/spi_device/rtl/spi_readcmd.sv
Mailbox is processed in readcmd submodule. If the received address falls
into the mailbox region, the logic raises the intercept signal to assume
the SPI and return data internally regardless of spi Flash or
Passthrough mode.
=> [spi_device] Mailbox Intercept Logic

hw/top_englishbreakfast/util/sw_sources.patch, sw/device/lib/dif/dif_csrng.c, sw/device/lib/dif/dif_csrng.h, sw/device/sca/lib/meson.build, sw/device/sca/lib/sca.c
This PR only contains:
- Implementation of the `dif_csrng_stop` function
- Application of the `dif_csrng_stop` on the `sca` module
=> [dif] Implement function dif_csrng_stop

hw/dv/sv/cip_lib/cip_base_pkg.sv, hw/dv/sv/cip_lib/cip_macros.svh
Just realized mubi_pkg has mubi12 as well
=> [dv] Add dv macro and function for mubi12

hw/ip/clkmgr/data/clkmgr_testplan.hjson
=> [dv/clkmgr] Add clkmgr_frequency test

hw/ip/spi_device/doc/_index.md
This commit revises the SPI_DEVICE TPM spec to explain how
TPM_ACCESS_x.activeLocality and received Locality affects the return
value of the Return-by-HW registers.
=> [spi_device] Add Locality related section in TPM

sw/device/silicon_creator/lib/base/sec_mmio_unittest.cc
Ran into these while measuring off-target coverage using `clang-13`. This PR removes unused lambda captures and adds a missing `static_assert` message.
=> [sw/silicon_creator] Minor fixes in sec_mmio_unittest.cc

hw/ip/sysrst_ctrl/data/sysrst_ctrl_testplan.hjson, hw/ip/sysrst_ctrl/doc/dv/index.md, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_common_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_smoke_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_vseq_list.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.core, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_cfg.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_cov.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_pkg.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_virtual_sequencer.sv, hw/ip/sysrst_ctrl/dv/sva/sysrst_ctrl_bind.sv, hw/ip/sysrst_ctrl/dv/sva/sysrst_ctrl_sva.core, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim.core, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson, hw/ip/sysrst_ctrl/dv/tb.sv, hw/ip/sysrst_ctrl/dv/tests/sysrst_ctrl_base_test.sv, hw/ip/sysrst_ctrl/dv/tests/sysrst_ctrl_test.core, hw/ip/sysrst_ctrl/dv/tests/sysrst_ctrl_test_pkg.sv, util/build_docs.py
Signed-off-by: Madhuri.Patel <madhuri.patel@ensilica.com>
=> [sysrst_ctrl] Added sysrst_ctrl testbench environment template

hw/dv/sv/cip_lib/cip_base_pkg.sv, hw/dv/tools/vcs/cover.cfg, hw/ip/aon_timer/dv/tb.sv, hw/ip/clkmgr/dv/env/clkmgr_if.sv, hw/ip/clkmgr/dv/env/clkmgr_scoreboard.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/lc_ctrl/dv/env/lc_ctrl_env_pkg.sv, hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv, hw/ip/otp_ctrl/dv/cov/otp_ctrl_cov_if.sv, hw/ip/otp_ctrl/dv/env/otp_ctrl_ast_inputs_cfg.sv, hw/ip/rstmgr/dv/env/rstmgr_if.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv, hw/ip/rstmgr/dv/sva/rstmgr_cascading_sva_if.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_executable_vseq.sv, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_earlgrey/rtl/padring.sv, util/topgen/templates/toplevel.sv.tpl
=> [Cleanup] Remove lc_tx_e type and replace it with lc_tx_t

hw/dv/sv/kmac_app_agent/kmac_app_agent.sv, hw/dv/sv/kmac_app_agent/kmac_app_agent_cfg.sv, hw/dv/sv/kmac_app_agent/kmac_app_intf.sv, hw/dv/sv/push_pull_agent/push_pull_agent.sv, hw/dv/sv/push_pull_agent/push_pull_agent_cfg.sv, hw/dv/sv/push_pull_agent/push_pull_agent_pkg.sv, hw/dv/sv/push_pull_agent/push_pull_driver_lib.sv, hw/dv/sv/push_pull_agent/push_pull_if.sv, hw/dv/sv/push_pull_agent/push_pull_item.sv, hw/dv/sv/push_pull_agent/push_pull_monitor.sv, hw/dv/sv/push_pull_agent/seq_lib/push_pull_base_seq.sv, hw/dv/sv/push_pull_agent/seq_lib/push_pull_device_seq.sv, hw/dv/sv/push_pull_agent/seq_lib/push_pull_host_seq.sv, hw/ip/keymgr/dv/tb.sv
- Add support for 4-phase req-ack
- add `pull_handshake_e` type
- Update cfg, agent, monitor, driver and interface to support this
- Refactor and minor fixups in monitor and sequences
=> [dv, push pull agent] Support for 4-phase req-ack

hw/ip/kmac/dv/env/kmac_scoreboard.sv, hw/ip/kmac/rtl/kmac_msgfifo.sv
Reverts lowRISC/opentitan#9302
=> Revert "Revert "[kmac] Use Empty signal from FIFO""

hw/ip/pwrmgr/data/pwrmgr.hjson.tpl, hw/ip/pwrmgr/pwrmgr.core, hw/ip/pwrmgr/rtl/pwrmgr.sv, hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr.hjson, hw/top_earlgrey/ip/pwrmgr/rtl/autogen/pwrmgr_reg_pkg.sv, hw/top_earlgrey/ip/pwrmgr/rtl/autogen/pwrmgr_reg_top.sv
- Added timeout check to escalation network clock/resets
- Fixes #8658
=> [pwrmgr] Enhance pwrmgr escalation network check

hw/ip/prim/rtl/prim_mubi12_sync.sv, hw/ip/prim/rtl/prim_mubi16_sync.sv, hw/ip/prim/rtl/prim_mubi4_sync.sv, hw/ip/prim/rtl/prim_mubi8_sync.sv, hw/ip/pwrmgr/rtl/pwrmgr.sv, hw/ip/pwrmgr/rtl/pwrmgr_cdc.sv, hw/ip/pwrmgr/rtl/pwrmgr_fsm.sv, hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_if.sv, hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv, hw/ip/rom_ctrl/rom_ctrl_pkg.core, hw/ip/rom_ctrl/rtl/rom_ctrl.sv, hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv, hw/ip/rom_ctrl/rtl/rom_ctrl_pkg.sv, util/design/data/prim_mubi_sync.sv.tpl
- This fixes #8981 but only addresses the issue on pwrmgr side.
- rom_ctrl may be further enhanced.
- First commit will be rebased away.
=> [pwrmgr, rom_ctrl] Enhance done/good signaling to mubi

hw/top_englishbreakfast/util/sw_sources.patch, sw/device/lib/dif/dif_edn.c, sw/device/sca/lib/meson.build, sw/device/sca/lib/sca.c
This PR only contains:
- Implementation of the dif_edn_stop function;
- Application of the dif_edn_stop on the sca module;
- Change the sw_sources.patch to suport the changes in the sca module.
=> [dif] Implement function dif_edn_stop

hw/ip/spi_device/rtl/spi_device.sv, hw/ip/spi_device/rtl/spid_upload.sv
[spi_device] Connect SPI Flash Upload interrupts
This commit connects the interrupts in SPI Device Flash mode.
- cmdfifo_not_empty: Event occurs when SPI Flash device receives a
command byte and the matched command information entry's upload bit is
set.
- payload_not_empty: If the received command has payload field, the
upload module stores the incoming payload into DPSRAM Payload buffer.
It then updates the payload size when SPI transaction is completed.
The logic reports this event when the payload size is non-zero.
This PR has #9293 inside. Please review the last commit only.
=> [spi_device] Connect upload interrupt

hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_if.sv, hw/ip/flash_ctrl/dv/tb/tb.sv
=> [flash_ctrl] Adding Interface at Environment,fix analog inputs

hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv
Reverts #6823
Per Tom's comment on issue #6821, we are going to revert this temp fix and see if we can reproduce the assertion error.
=> [dv/aon_timer] rever temp fix regression error

sw/host/opentitanlib/src/bootstrap/legacy.rs, sw/host/opentitanlib/src/bootstrap/mod.rs, sw/host/opentitantool/config/h1dx_devboard.json, sw/host/opentitantool/config/h1dx_devboard_ultradebug.json
Implement the bootstrapping protocol used by previous generations of
Google Titan chips.
=> [opentitantool] Support bootstrap protocol of legacy chips

hw/ip/spi_device/data/spi_device_testplan.hjson
merged similar tests & added covergroups.
Signed-off-by: Jason Hoddinett <jason.hoddinett.ensilica@opentitan.org>
=> [spi_device/testplan] Added TPM specific testpoints

hw/ip/flash_ctrl/data/flash_ctrl.prj.hjson, hw/ip/flash_ctrl/doc/checklist.md
- Previous PR forgot to change the actual design stage
=> [flash_ctrl] Officially move flash_ctrl to D2.

sw/device/silicon_creator/lib/shutdown.c, sw/device/silicon_creator/lib/shutdown_unittest.cc
Follow up addressing comments on PR #8289.
=> [sw/silicon_creator] Minor cleanups to shutdown code.

hw/dv/sv/common_ifs/clk_rst_if.sv
Hi,
This PR is changing the usage of jitter to allow 2 different values for each the + and the - jitters (as in +2%/-3% jitter).
This change is required by flash clock which can have the above scenario.
Thanks!
=> [dv/clk_rst_if] Split clk_rst_if jitter to 2 different values

hw/ip/spi_host/rtl/spi_host_fsm.sv
Issue #9285 uncovers a bug whereby back-to-back segments are not being properly handled in the rtl.
The issue is that when processing back to back segments, the FSM needs to carefully choose which copy
of the segment parameters to look at.  For anything initializing states for the following segment the
FSM needs to look at the new incoming segment parameters.  For finalizing processing of the previous segment
(e.g., flushing data out of the shift register) the FSM needs to look at the previous parameters.
This commit manages this subtlety.
Fixes #9285 (with patch to test bench in @rasmus-madsen's offline TB, see issue for patch)
=> [ spi_host, rtl ] Properly handle back-to-back segments

hw/ip/otbn/dv/model/iss_wrapper.cc, hw/ip/otbn/dv/model/iss_wrapper.h, hw/ip/otbn/dv/model/otbn_core_model.sv, hw/ip/otbn/dv/model/otbn_model.cc, hw/ip/otbn/dv/model/otbn_model.h, hw/ip/otbn/dv/model/otbn_model_dpi.h, hw/ip/otbn/dv/model/otbn_model_pkg.sv, hw/ip/otbn/dv/otbnsim/sim/csr.py, hw/ip/otbn/dv/otbnsim/sim/sim.py, hw/ip/otbn/dv/otbnsim/sim/standalonesim.py, hw/ip/otbn/dv/otbnsim/sim/state.py, hw/ip/otbn/dv/otbnsim/sim/wsr.py, hw/ip/otbn/dv/otbnsim/stepped.py, hw/ip/otbn/dv/rig/rig/model.py, hw/ip/otbn/dv/uvm/tb.sv, hw/ip/otbn/dv/verilator/otbn_top_sim.sv, hw/ip/otbn/rtl/otbn.sv
This commit includes:
- "Flush EDN" feature for resetting values inside model in the case of `edn_rst_n` being low
- Model of new URND PRNG (xoshiro256pp) inside `wsr.py`
- Processing of URND EDN connection inside model and using it as seed in PRNG 
Resolves #8084
=> [otbn,dv] Full URND Implementation in ISS

hw/ip/rom_ctrl/doc/_index.md, hw/ip/rom_ctrl/doc/checklist.md
(This is the final checklist item before D2)
=> [rom_ctrl,doc] Document planned security countermeasures

hw/dv/sv/jtag_agent/jtag_monitor.sv, hw/dv/sv/jtag_riscv_agent/jtag_riscv_agent.core, hw/dv/sv/jtag_riscv_agent/jtag_riscv_agent.sv, hw/dv/sv/jtag_riscv_agent/jtag_riscv_agent_cfg.sv, hw/dv/sv/jtag_riscv_agent/jtag_riscv_agent_pkg.sv, hw/dv/sv/jtag_riscv_agent/jtag_riscv_driver.sv, hw/dv/sv/jtag_riscv_agent/jtag_riscv_item.sv, hw/dv/sv/jtag_riscv_agent/jtag_riscv_monitor.sv, hw/dv/sv/jtag_riscv_agent/jtag_riscv_reg_adapter.sv, hw/dv/sv/jtag_riscv_agent/seq_lib/jtag_riscv_csr_seq.sv
- Added jtag_riscv_driver
- Added jtag_riscv_register_adapter
- Implemented jtag_riscv_monitor
- Fixed jtag_monitor (DR and IR were << 1)
=> [jtag_riscv_agent] Added driver and register adapter

hw/ip/otbn/dv/otbnsim/sim/sim.py
This commit includes a change in `sim.py` so that when we are out of PRE_EXEC state, URND would step
no matter what.
Fixes: #9407
=> [otbn,dv] Bug Fix of Delayed URND

hw/ip/rom_ctrl/data/rom_ctrl.prj.hjson
=> [rom_ctrl] Mark rom_ctrl as D2

hw/ip/otbn/dv/model/iss_wrapper.cc, hw/ip/otbn/dv/model/iss_wrapper.h, hw/ip/otbn/dv/model/otbn_core_model.sv, hw/ip/otbn/dv/model/otbn_model.cc, hw/ip/otbn/dv/model/otbn_model.h, hw/ip/otbn/dv/model/otbn_model_dpi.h, hw/ip/otbn/dv/model/otbn_model_pkg.sv, hw/ip/otbn/dv/otbnsim/sim/csr.py, hw/ip/otbn/dv/otbnsim/sim/ext_regs.py, hw/ip/otbn/dv/otbnsim/sim/sim.py, hw/ip/otbn/dv/otbnsim/sim/state.py, hw/ip/otbn/dv/otbnsim/sim/wsr.py, hw/ip/otbn/dv/uvm/tb.sv, hw/ip/otbn/dv/verilator/otbn_top_sim.sv, hw/ip/otbn/rtl/otbn.sv
This commit includes changes in OTBN DV environment to support
modelling EDN requests by RND and URND. 
Closes #8504
=> [otbn,dv] Modelling EDN Requests in OTBN

doc/ug/getting_started_fpga.md
This fixed an issue I was having getting the FPGA board set up, and it seems like a good idea to document it.
Thanks to @moidx for suggesting the fix!
=> [doc] Add troubleshooting note to FPGA user guide.

doc/ug/getting_started_hw_design.md
This commit adds a section in Getting Started HW.
The section describes how-to add/revise the interrupts.
Currently, the designer needs to revise many parts (DV, SW, unittest)
when updating the interrupts.
=> [doc] How to add interrupts to IP

hw/dv/sv/spi_agent/spi_agent_cfg.sv, hw/dv/sv/spi_agent/spi_host_driver.sv, hw/dv/sv/spi_agent/spi_monitor.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv, hw/ip/spi_device/dv/tb/tb.sv
Added implementation of csb selection as discussed in issue #9377. Modified spi_device tb to include tpm_csb and fixed csb_sel to 0 in spi_init sequence.
Signed-off-by: kosta-kojdic <kosta.kojdic@ensilica.com>
=> [spi_agent/spi_device] CSB Selection Implemented

hw/ip/clkmgr/dv/env/clkmgr_env_cov.sv, hw/ip/clkmgr/dv/env/clkmgr_if.sv, hw/ip/clkmgr/dv/env/clkmgr_scoreboard.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_extclk_vseq.sv, hw/ip/clkmgr/dv/sva/clkmgr_bind.sv, hw/ip/clkmgr/dv/sva/clkmgr_div_sva_if.sv, hw/ip/clkmgr/dv/tb.sv
Update the test to track updates in the RTL.
=> [dv/clkmgr] Fix clkmgr_extclk test

hw/ip/adc_ctrl/rtl/adc_ctrl_fsm.sv
- Fixes #9312
- Ensure valid is dropped before moving to ensure we don't accidentally
sample the same value multiple times.
=> [adc_ctrl] Make handshake more robust

hw/ip/otbn/rtl/otbn.sv
These changes are to match 299ab26, which actually lets us drop an ECC
decoder. Awesome! :-)
=> [otbn] Fix recently added lint errors

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh
Following fixes have been made in this commit:
1. reset is done after run_tl_intg_err_vseq task finishes for both ral
models. Earlier, reset was asserted after the shortest task ended.
2. tl_access in issue_tl_access_w_intg_err is made to run on respective
ral model's sequencer. Earlier it was running only on default sequencer
=> [rom_ctrl, dv] Fix for rom_ctrl_tl_intg_err regression failure

hw/ip/clkmgr/dv/env/clkmgr_env_cov.sv, hw/ip/clkmgr/dv/env/clkmgr_scoreboard.sv
Fix minor verible formatting issue.
=> [dv/clkmgr] Ignore impossible cover crosses

hw/ip/lc_ctrl/data/lc_ctrl.hjson, hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
This corrects the behavior of the invalid state error, and updates the docs to be consistent.
Fixes #9431
=> [lc_ctrl] Correct invalid state error indication

hw/ip/spi_device/dv/env/seq_lib/spi_device_byte_transfer_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_perf_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv, hw/ip/spi_device/dv/env/spi_device_env.core, hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
Added Perf and Byte access scenarios. Content is the same as #9376 which is closed due to commits conflict.
Signed-off-by: kosta-kojdic <kosta.kojdic@ensilica.com>
=> [spi_device] Perf and Byte Access added

hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_bijection_vseq.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_lc_escalation_vseq.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_smoke_vseq.sv, hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cfg.sv
1. Fix sram address check
2. minor update on task `req_scr_key`
=> [sram/dv] Fix bijection test

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson
=> [flash_ctrl] Adding initial testplan

sw/host/opentitanlib/src/bootstrap/legacy.rs
This newly added code has a few bugs.
1. A bug was introduced during review, when the code to set the
"final" flag on the last frame was move out of the loop.  The hash of
the block needs to be computed after the flag is set.  (This bug would
have been caught had I run the one and only unit test in this file.)
2. The above lead to the discovery that the existing logic (also in
primitive.rs) does not attempt to verify the ack of the very last
block, leading to the false claim of successful bootstrapping.
3. Further real-life testing revealed more shortcomings of the
existing logic.  Ordinarily, the bidirectional transaction is used
such that the boot rom will ack the previously transmitted frame, at
the same time as receiving the next one.  I.e. the Rust code will look
for ack of frame 3 …
=> [opentitantool] Fixes to bootstrap of legacy Titan

hw/ip/rstmgr/rtl/rstmgr_cnsty_chk.sv
=> [dv/rstmgr] Use localparam for MaxSyncDelay

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
=> [flash_ctrl] status bits for init excluded from CSR checks

hw/dv/sv/alert_esc_agent/alert_esc_agent_cfg.sv, hw/dv/sv/alert_esc_agent/alert_esc_agent_cov.sv, hw/dv/sv/alert_esc_agent/alert_monitor.sv, hw/dv/sv/cip_lib/cip_base_env_cfg.sv, hw/ip_templates/alert_handler/dv/env/alert_handler_if.sv, hw/top_earlgrey/ip_autogen/alert_handler/dv/env/alert_handler_if.sv
Add coverage on alert and ping's lpg.
=> [dv/alert_esc_agent] Add alert_esc lpg coverage

util/reggen/countermeasure.py
This is in preparation for the first D2S reviews (follow up from #9240).
The names are tentative and have been proposed by @tjaychen.
The idea is to start with this initial set and refine as needed.
=> [reggen] Add tentative list of assets and cm types

hw/ip/otbn/dv/verilator/otbn_top_sim.sv, hw/ip/otbn/rtl/otbn.sv, hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_core.sv
=> [otbn, rtl] Wire up recoverable alert

hw/top_earlgrey/syn/chip_earlgrey_asic.sdc
=> [syn] Fix SDC constraint

hw/ip/prim/lint/prim_sparse_fsm.waiver, hw/ip/prim/prim_sparse_fsm.core
=> [prim] Add a lint waiver for dv-only code / ifdefs

hw/ip/spi_device/data/spi_device_testplan.hjson
Remove mem_ecc and mode as not needed
Update tx/rx_async_fifo_reset
=> [spi_device/dv] Update testplan for FW mode

hw/ip/clkmgr/dv/env/seq_lib/clkmgr_base_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_clk_status_vseq.sv, hw/ip/clkmgr/dv/env/seq_lib/clkmgr_extclk_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_smoke_vseq.sv
=> [dv/clkmgr,rstmgr] Simplify mubi4 and lc_tx_t randomization

hw/ip/sysrst_ctrl/data/sysrst_ctrl_testplan.hjson
=> [doc] Added initial draft of system reset controller verification plan

hw/ip/pwrmgr/data/pwrmgr.hjson.tpl, hw/ip/pwrmgr/dv/tb.sv, hw/ip/pwrmgr/rtl/pwrmgr.sv, hw/ip/pwrmgr/rtl/pwrmgr_fsm.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
=> [pwrmgr] Fix missing production state qualification on rom checks

hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_reset_vseq.sv
=> [dv/pwrmgr] Remove unnecessary "rand" attribute

hw/ip/otbn/dv/verilator/otbn_top_sim.sv, hw/ip/otbn/rtl/otbn.sv, hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_decoder.sv, hw/ip/otbn/rtl/otbn_pkg.sv
Note this includes commit from #9479 so will need to be rebased and merged once that is merged.
=> Otbn todo cleanup

hw/dv/sv/mem_model/mem_model.core, hw/dv/sv/mem_model/mem_model.sv, hw/dv/sv/mem_model/mem_model_pkg.sv
1. mask width should just depend on data width
2. Added necessary dependency
=> [dv] Minor update on mem_model

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_combo_detect_ec_rst_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_common_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_in_out_inverted_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_smoke_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_vseq_list.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.core, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_cfg.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_pkg.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_if.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_virtual_sequencer.sv, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson, hw/ip/sysrst_ctrl/dv/tb.sv, hw/ip/sysrst_ctrl/dv/tests/sysrst_ctrl_base_test.sv
=> Added in_out_inverted and directed combo_detect testcase for V1 milestone

hw/dv/sv/jtag_agent/jtag_driver.sv, hw/dv/sv/jtag_agent/jtag_if.sv, hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_base_vseq.sv, hw/ip/lc_ctrl/dv/tests/lc_ctrl_base_test.sv, hw/top_earlgrey/dv/tb/tb.sv
Add sysrst_n to conect with the main reset
Once sys reset occurs, finish the item immediately and re-issue jtag reset
after sys reset is released
=> [dv] Support reset for jtag_driver

hw/syn/tools/dc/run-syn.tcl, util/dvsim/verixcdc-report-parser.py
I shot myself in the foot when merging the CDC PR (the PR was so old it got out of date with other scripts in the repo).
This should fix synthesis and the CDC regression.
=> [syn/cdc] Minor flow fixes in CDC and syn scripts

hw/ip/aon_timer/data/aon_timer_testplan.hjson
This commit includes updates on the testplan of AON Timer.
=> [aon_timer,dv] Testplan Update for AON Timer

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
This PR modifies the post_start alert check. It adds a 200 cycle delays
before checking for fatal alert, because we allows recoverable alert to
fire once.
=> [dv/cip_base_seq] allow recoverable alert in dut test

hw/ip/otbn/data/otbn.hjson, hw/ip/otbn/doc/_index.md, hw/ip/otbn/dv/verilator/otbn_top_sim.sv, hw/ip/otbn/rtl/otbn.sv, hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_reg_pkg.sv, hw/ip/otbn/rtl/otbn_reg_top.sv
Specification for clearing INSN_CNT and ERR_BITS registers.
=> [doc/otbn] Clear external CSRs

hw/dv/sv/csrng_agent/csrng_agent_cfg.sv, hw/dv/sv/csrng_agent/csrng_device_driver.sv, hw/dv/sv/csrng_agent/csrng_monitor.sv, hw/dv/sv/csrng_agent/seq_lib/csrng_device_seq.sv, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/edn_env_pkg.sv, hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv, hw/ip/edn/dv/tests/edn_base_test.sv, hw/ip/edn/dv/tests/edn_smoke_test.sv
=> [edn/dv] Modified ack for GEN command

hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
The main state machine was starting to process the sha3 messages, but the last message was being missed due to pulse assignment.
Fixes #9551.
=> [entropy_src/rtl] fixed main sm for sha3 operation

hw/ip/rom_ctrl/data/rom_ctrl_testplan.hjson, hw/ip/rom_ctrl/dv/env/rom_ctrl_env.core, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_stress_all_vseq.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_vseq_list.sv, hw/ip/rom_ctrl/dv/rom_ctrl_sim_cfg.hjson
Added necessary changes in common files and rom_ctrl_multiple_reset_vseq
to execute rom_ctrl_multiple_reset
=> [rom_ctrl, dv] Added rom_ctrl_stress_all testcase

hw/ip/otbn/doc/_index.md, hw/ip/otbn/rtl/otbn.sv
=> [otbn, rtl] Only calculate CRC for 32-bit aligned writes

hw/ip/otbn/dv/otbnsim/sim/sim.py, hw/ip/otbn/dv/otbnsim/sim/standalonesim.py, hw/ip/otbn/dv/otbnsim/sim/state.py, hw/ip/otbn/dv/otbnsim/sim/wsr.py, hw/ip/otbn/dv/otbnsim/stepped.py, hw/ip/otbn/util/check_call_stack.py, hw/ip/otbn/util/check_loop.py, hw/ip/otbn/util/shared/check.py, hw/ip/otbn/util/shared/decode.py
=> [otbn] Tidy up long lines and unnecessary imports in Python code

hw/ip/otp_ctrl/otp_ctrl.core, hw/ip/otp_ctrl/rtl/otp_ctrl.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_dai.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_kdi.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_lci.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_lfsr_timer.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_part_buf.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_scrmbl.sv
=> [otp_ctrl] Switch to standardized prim_count

hw/ip/otbn/rtl/otbn.sv, hw/ip/prim/rtl/prim_crc32.sv
=> [otbn, rtl] Lint fixes

hw/ip/rom_ctrl/util/mem.py, util/design/secded_gen.py
This is equivalent to calling ecc_encode lots of times in succession
but avoids having to pick a code and calculate bitmasks each time.
For the `rom_ctrl` usage in the second patch, using this instead of calling `ecc_encode` for each word means we run over an 8kB memory in ~4 seconds (mostly spent doing scrambling) rather than ~9 seconds.
=> [secded_gen] Add an ecc_encode_some function

hw/ip/rom_ctrl/dv/tb.sv
Following assertions have been added in this commit:
1. Assertion to ensure kmac_data_o.valid is never aserted after
pwrmgr_data_o.done is asserted.
=> [rom_cntrl, dv] Assertion to validate rom controller outputs to KMAC

hw/ip/prim/dv/prim_esc/tb/prim_esc_tb.sv, hw/ip/prim/lint/prim_count.vlt, hw/ip/prim/lint/prim_count.waiver, hw/ip/prim/prim_count.core, hw/ip/prim/prim_esc.core, hw/ip/prim/rtl/prim_count.sv, hw/ip/prim/rtl/prim_esc_receiver.sv, hw/ip_templates/alert_handler/alert_handler_component.core, hw/ip_templates/alert_handler/rtl/alert_handler_accu.sv, hw/ip_templates/alert_handler/rtl/alert_handler_esc_timer.sv, hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv, hw/top_earlgrey/ip_autogen/alert_handler/alert_handler_component.core, hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_accu.sv, hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_esc_timer.sv, hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
As title says.
See also #8612 for context.
=> [alert_handler] Switch to standardized prim_count 

hw/ip/otbn/doc/_index.md, hw/ip/otbn/doc/otbn_blockarch.svg
=> [otbn, doc] Add prefetcher details

hw/ip/lc_ctrl/data/lc_ctrl.hjson
Minor doc updates.
CC @NigelScales 
=> [lc_ctrl/doc] Update register descriptions

hw/ip/aes/aes.core, hw/ip/aes/pre_syn/syn_yosys.sh, hw/ip/aes/rtl/aes.sv, hw/ip/aes/rtl/aes_cipher_control_fsm.sv, hw/ip/aes/rtl/aes_control_fsm.sv, hw/ip/aes/rtl/aes_ctr_fsm.sv, hw/ip/csrng/rtl/csrng.sv
This is related to #9447 .
I will need to rebase this once #9621 is in. Please review the last commit only.
=> [aes] Switch to prim_sparse_fsm_flop

hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
Sram init is actually a bunch of write, which may affect the next
transactions.
Update scb to consider init to trigger 1<<AddrWidth write strobe
=> [sram/dv] Fix init followed by sram transactions

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_eflash_ral_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_virtual_sequencer.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_smoke_hw_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson, hw/ip/flash_ctrl/dv/tb/tb.sv, hw/ip/flash_ctrl/dv/tools/xcelium/xfile
adding test V1 Host Direct Read, adding file (xfile) for override
Xcelium XPROP settings (which are currently not working)
=> [flash_ctrl] Adding MULTIRAL, Test V1 Host Direct Read

hw/dv/sv/spi_agent/spi_agent_cfg.sv, hw/dv/sv/spi_agent/spi_host_driver.sv, hw/ip/spi_device/data/spi_device_testplan.hjson, hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_write_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv, hw/ip/spi_device/dv/env/spi_device_env.core, hw/ip/spi_device/dv/env/spi_device_env_pkg.sv, hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
TPM Write Scenario with 4 bytes payload. Checking of Address+Command FIFO content and write FIFO content.
Signed-off-by: kosta-kojdic <kosta.kojdic@ensilica.com>
=> [spi_device] TPM Write Scenario

hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv, hw/ip/hmac/rtl/hmac_reg_top.sv, hw/ip/kmac/rtl/kmac_reg_top.sv, hw/ip/otbn/rtl/otbn_reg_top.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_core_reg_top.sv, hw/ip/spi_device/rtl/spi_device_reg_top.sv, hw/ip/spi_host/rtl/spi_host_reg_top.sv, hw/ip/usbdev/rtl/usbdev_reg_top.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_core_reg_top.sv, util/reggen/reg_top.sv.tpl
=> [reggen] Resolve a TODO in the window address decoding logic

hw/ip/csrng/data/csrng.hjson, hw/ip/csrng/doc/checklist.md, hw/ip/edn/data/edn.hjson, hw/ip/edn/doc/checklist.md, hw/ip/entropy_src/data/entropy_src.hjson, hw/ip/entropy_src/doc/checklist.md
Updates are based on the Opentitan D2S Milestone - Sign-off Process.
=> [entropy_complex/d2s] updated checklist with security items

hw/ip/sram_ctrl/data/sram_ctrl_base_testplan.hjson, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_throughput_vseq.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_vseq_list.sv, hw/ip/sram_ctrl/dv/env/sram_ctrl_env.core, hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
2 tests are added. One is without partial write, the other is with
partial write.
=> [sram/dv] Test sram max throughput

hw/dv/sv/alert_esc_agent/alert_esc_agent_cov.sv, hw/dv/sv/alert_esc_agent/alert_monitor.sv, hw/dv/sv/alert_esc_agent/data/alert_agent_additional_testplan.hjson, hw/dv/sv/alert_esc_agent/data/alert_agent_basic_testplan.hjson, hw/dv/sv/alert_esc_agent/data/esc_agent_additional_testplan.hjson, hw/dv/sv/alert_esc_agent/data/esc_agent_basic_testplan.hjson, hw/dv/sv/alert_esc_agent/esc_monitor.sv, hw/ip_templates/alert_handler/data/alert_handler_testplan.hjson, hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler_testplan.hjson
This PR adds coverplan to alert_esc_agent.
=> [dv/alert_esc_agent] Add coverplan

hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/rtl/sram_ctrl.sv, hw/ip/sram_ctrl/sram_ctrl.core
=> [sram_ctrl] Switch to duplicated counter primitive

util/uvmdvgen/checklist.md.tpl
This PR removes an extra item in checklist template.
=> [doc/checklist] Template fix

hw/ip/sram_ctrl/data/sram_ctrl_base_testplan.hjson, hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
Imported mem_test to fix unmapped tests
=> [sram/dv] Fix unmapped tests

util/fpga/splice_rom.sh
The upload process defined in ci/upload-artifacts-template.yml uses an
rsync command that keeps track of the upstream dependencies of the CI
step. This commit updates the splice script so that it generates the new
bitstream using a new filename so that it can be picked up in the upload
script.
Other changes: add additional error checking to the splice script.
=> [fpga] Fix splice CI export files step.

hw/dv/sv/jtag_agent/jtag_monitor.sv, hw/dv/sv/kmac_app_agent/kmac_app_monitor.sv, hw/dv/sv/pwm_agent/pwm_monitor.sv, hw/dv/sv/rng_agent/rng_monitor.sv, hw/dv/sv/usb20_agent/usb20_monitor.sv, util/uvmdvgen/monitor.sv.tpl
This has been there since the start! :-D
=> [dv] Fix typo in uvmdvgen comment

hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv
Make sure tests start after at least one full aon cycle out of reset,
otherwise the SVA will miss sampling reset.
Delay the pwrmgr rst_lc_req and rst_sys_req to be more realistic and to
visit more of the state space.
=> [dv/rstmgr] Fix POR reset and increase coverage

hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_lc_escalation_vseq.sv, hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
Simplify the lc_escalation_vseq and fix several seq and scb issues
This test should pass now.
=> [sram_ctrl/dv] Fix escalation test failures

hw/dv/sv/csrng_agent/csrng_item.sv, hw/ip/csrng/dv/env/csrng_env_cfg.sv, hw/ip/csrng/dv/env/csrng_env_pkg.sv, hw/ip/csrng/dv/env/csrng_scoreboard.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_smoke_vseq.sv, hw/ip/csrng/dv/tests/csrng_base_test.sv, hw/ip/csrng/dv/tests/csrng_cmds_test.sv
=> [csrng/dv] Add SW_APP to tests/sequences, internal_state prediction

hw/ip/adc_ctrl/adc_ctrl.core, hw/ip/flash_ctrl/flash_ctrl_pkg.core, hw/ip/otp_ctrl/otp_ctrl.core, hw/ip/prim_generic/prim_generic_flash.core, hw/top_earlgrey/chip_earlgrey_asic.core, hw/top_earlgrey/ip/sensor_ctrl/sensor_ctrl_pkg.core, hw/top_earlgrey/top_earlgrey.core
This reverts commit e85d2449e0cc25f88f828f4b06c1ec3364b89598.
=> Revert "[dv] Replace fileset_partner flag with fileset_ast flag"

hw/ip/pwm/rtl/pwm_chan.sv
- Update the pwm_chan.sv to fix the duty cycle issue
- Fixes #9765
=> [pwm, rtl] PWM RTL update to fix the duty cycle issue

hw/ip/pwrmgr/dv/env/pwrmgr_env_cov.sv, hw/ip/pwrmgr/dv/env/pwrmgr_if.sv, hw/ip/pwrmgr/dv/env/pwrmgr_scoreboard.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_aborted_low_power_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_wakeup_race_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_reset_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_smoke_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_vseq.sv, hw/ip/pwrmgr/dv/sva/pwrmgr_bind.sv, hw/ip/pwrmgr/dv/sva/pwrmgr_clock_enables_sva_if.sv
Enhance wakeup interrupt covergroup.
=> [dv/pwrmgr] Check wakeup interrupts

hw/ip/pwrmgr/doc/_index.md
companion PR to #9555 and clarifies `pwrmgr` and `rom_ctrl` interaction.
=> [pwrmgr] Documentation update

hw/ip/pinmux/fpv/tb/pinmux_bind_fpv.sv, hw/ip/pinmux/fpv/tb/pinmux_tb.sv, hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
This PR added new ports to the pinmux FPV testbench, and fixes a few
naming to avoid the compilation error.
=> [fpv/pinmux] Fix pinmux testbench

hw/ip/csrng/rtl/csrng_core.sv
Always de-assert ready status after every cmd word write.
The tilelink poll should not see a false ready indication.
=> [csrng/rtl] improved cmd rdy status bit

hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv
=> [csrng/dv] Removed double cmd_rdy spin_waits. rtl fix in PR#9802

hw/ip/pwrmgr/dv/env/pwrmgr_env_cfg.sv, hw/ip/pwrmgr/dv/env/pwrmgr_env_cov.sv, hw/ip/pwrmgr/dv/env/pwrmgr_env_pkg.sv, hw/ip/pwrmgr/dv/env/pwrmgr_if.sv, hw/ip/pwrmgr/dv/env/pwrmgr_scoreboard.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_aborted_low_power_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_wakeup_race_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_smoke_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_vseq.sv
Predict the interrupt.
Add interrupt coverage.
=> [dv/pwrmgr] Add more checking into scoreboard

hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
This PR updates the currect assertions to consider two more cases: sleep
and jtag.
=> [fpv/pinmux] Update pinmux existing assertions

hw/ip/csrng/dv/env/csrng_env_cfg.sv, hw/ip/csrng/dv/env/csrng_env_pkg.sv, hw/ip/csrng/dv/env/csrng_scoreboard.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv
Created a centralized "get_seeds" function which gathers all the seeds and distributes them according to which APP won arbitration. This was done to get rid of errors caused by the seed going to the "wrong" APP.
=> [csrng/dv] Modify seed generation/handling

hw/ip_templates/alert_handler/data/alert_handler.prj.hjson, hw/ip_templates/alert_handler/doc/checklist.md, hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.prj.hjson, hw/top_earlgrey/ip_autogen/alert_handler/doc/checklist.md
This PR completes alert_handler V2 checklist.
=> [dv/alert_handler] V2 checklist

hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
This PR adds assertions on jtag ports in pinmux based on internal
variable `tap_strap`.
Next PR will write assertions to ensure `tap_strap` is correct.
=> [fpv/pinmux] Update jtag pinmux assertion

hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
Fix variable types due to changes in #9806
=> [sram/dv] Fix sram executable test

hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
This PR adds sleep mode assertions and DIO assertions.
A few failures filed an issue #9850 to clarify.
=> [fpv/pinmux] Sleep mode and dio related assertions

hw/ip/sysrst_ctrl/data/sysrst_ctrl.hjson
=> [sysrst_ctrl] Update Hjson

hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
This addresses #9847 and #9848.
=> [lc_ctrl] Mutex and idle status fixes

hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
As issue #9850 clarifed, it is a misunderstanding on my verification
side, I updated the failed assertions according to the comment
from #9850.
=> [fpv/pinmux] Fix assertions for issue #9850

hw/ip/pwrmgr/data/pwrmgr_testplan.hjson, hw/ip/pwrmgr/dv/env/pwrmgr_env_cov.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv
=> [dv/pwrmgr] Add covergroup for cycles between wakeup and reset

hw/ip/spi_device/rtl/spi_passthrough.sv
While adding `payload_swap_en` field in CMD_INFO, I missed to add
`addr_swap_en` to the swap enable condition. This commit revises to use
the config in CMD_INFO.
This issue is reported by @arnonsha (Thanks!)
=> [spi_device] Add `addr_swap_en` to the swap condition

hw/ip/sram_ctrl/data/sram_ctrl_base_testplan.hjson, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_smoke_vseq.sv, hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_stress_all_vseq.sv, hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv, hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
Also fix some failures in stress_all and stress_all with reset
=> [sram/dv] Enable stress test

hw/formal/tools/jaspergold/fpv.tcl, hw/ip/pinmux/doc/_index.md
Two commits in this PR:
1). Fix a typo in pinmux doc
2). Add aon_clk_i and aon_rst_ni to the fpv.tcl file
=> [fpv/pinmux] Update pinmux tcl file

hw/ip/uart/dv/env/uart_scoreboard.sv
=> [dv/uart] Fix typo in scoreboard

hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv, hw/dv/sv/spi_agent/spi_device_driver.sv, hw/dv/sv/spi_agent/spi_monitor.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_smoke_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_vseq_list.sv, hw/ip/spi_host/dv/env/spi_host_env.core, hw/ip/spi_host/dv/env/spi_host_env.sv, hw/ip/spi_host/dv/env/spi_host_env_cfg.sv, hw/ip/spi_host/dv/env/spi_host_env_pkg.sv, hw/ip/spi_host/dv/env/spi_host_scoreboard.sv, hw/ip/spi_host/dv/env/spi_host_seq_cfg.sv, hw/ip/spi_host/dv/env/spi_host_virtual_sequencer.sv, hw/ip/spi_host/dv/env/spi_segment_item.sv, hw/ip/spi_host/dv/env/spi_transaction_item.sv, hw/ip/spi_host/dv/spi_host_sim_cfg.hjson, hw/ip/spi_host/dv/tb.sv, hw/ip/spi_host/dv/tests/spi_host_base_test.sv, hw/ip/spi_host/spi_host.core
this PR pr contains a minor update to the spi agent
then it contains a commit that largely rewrites what was in place for the SPI host environment.
including the sequences for spi_smoke. which is the reason for the size of the PR.
this PR is currently blocked by #9775 
But I think review can start while waiting for the fix
=> [spi_smoke/dv] added env and sequences for spi_host V1

hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_ctrl_integrity_check_vseq.sv
This code come from PR 9740 (commit c1cf4a8), which needed updating
for commit 28b1ab1451, merged in the meantime.
=> [chip,dv] Fix compilation for private CI

doc/ug/design.md
Signed-off-by: Palmer Dabbelt <palmer@rivosinc.com>
=> [doc] Fix a grammatical error in ug/design

hw/ip/csrng/data/csrng_testplan.hjson, hw/ip/csrng/dv/csrng_sim_cfg.hjson, hw/ip/csrng/dv/env/csrng_env.core, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_smoke_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_stress_all_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_vseq_list.sv, hw/ip/csrng/dv/tests/csrng_smoke_test.sv, hw/ip/csrng/dv/tests/csrng_stress_all_test.sv, hw/ip/csrng/dv/tests/csrng_test.core, hw/ip/csrng/dv/tests/csrng_test_pkg.sv
=> [csrng/dv] Updated testplan, Create/debug stress_all_vseq/test

hw/ip/pinmux/data/pinmux.hjson.tpl, hw/ip/pinmux/rtl/pinmux.sv, hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
=> [pinmux] Fix wakeup detector MIO selection mux

hw/ip/edn/rtl/edn_core.sv
The ready status bit for csrng command requests will de-assert immediately so that the status bit reflects status accurately.
Same idea as #9802.
=> [edn/rtl] improved cmd rdy status bit

hw/ip/aon_timer/doc/dv/domains.svg, hw/ip/aon_timer/doc/dv/index.md, hw/ip/aon_timer/doc/dv/tb.svg, hw/ip/aon_timer/dv/env/aon_timer_env_cov.sv
Also includes a minor naming fix in a coverage point
=> [aon_timer,dv] DV Document Updates

hw/ip/csrng/dv/env/csrng_env_cfg.sv, hw/ip/csrng/dv/env/csrng_scoreboard.sv, hw/ip/csrng/dv/tests/csrng_base_test.sv
=> [csrng/dv] Modify for efuse, certain enables off

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh, hw/dv/tools/dvsim/testplans/passthru_mem_intg_testplan.hjson
Clean up some unused codes from #9871
=> [dv] intg_err test cleanup and change passthru_mem_tl_intg_err to V2S

hw/ip/sram_ctrl/doc/dv/index.md
Update the memory scb checkings
=> [sram/dv] Update DV doc

hw/ip/prim/rtl/prim_assert_standard_macros.svh
In this context, an if condition and assert statement exhibit the same
behavior. For some strange reason, the fix made in #9017 for Xcelium
(addition of #0 delay) worked for IP level testbenches but not the chip
level. The chip level tests returned the same error (race condition
causing the signal value to reflect an X, failing the assertion). This
may very well be a tool bug, where Xcelium is sampling the preponed
value of the signal when it shouldn't, but this seems to not be
reproducible in a standalone testcase (given that IP level testbenches
work fine). So in the interest of time, we just switch this out to a if
condition, which has an added advantage of begin immune to assert
control system tasks.
=> [prim_assert,dv] Use if condition in assert_init

sw/device/lib/dif/dif_alert_handler.c, sw/device/lib/dif/dif_alert_handler.h, sw/device/lib/dif/dif_alert_handler_unittest.cc
The locking DIFs only lock / check the status of the ping timer REGWEN.
This commit renames these DIFs to make this more obvious. This partially
addresses #9899. In the future, additional locking DIFs will be added to
configure other lockable CSRs for the alert handler.
=> [dif/alert_handler] Rename `*_is_locked` and `*_lock` DIFs.

hw/ip/tlul/rtl/tlul_adapter_sram.sv
This removes a comment that has gotten out of date - see #5512.
=> [tlul_adapter_sram] Remove out-of-date comment

hw/dv/sv/mem_bkdr_util/mem_bkdr_util__rom.sv, hw/ip/rom_ctrl/data/rom_ctrl_testplan.hjson, hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_common_vseq.sv, hw/ip/rom_ctrl/dv/rom_ctrl_sim_cfg.hjson
Added all the necessary changes to include
rom_ctrl_passthru_mem_tl_intg_err for rom controller module
=> [rom_ctrl, dv] Added passthru mem test

hw/ip/sram_ctrl/doc/dv/index.md
1. added prim_prince, prim_lfsr are verified separately
2. added using different INSTR_EXEC parameter for ret and main sram
=> [sram/dv] Minor DV doc update

hw/ip/pinmux/doc/_index.md, hw/ip/pinmux/rtl/pinmux_wkup.sv
=> [pinmux] Fix minor opens

hw/ip/otbn/dv/verilator/otbn_top_sim.sv, hw/ip/otbn/otbn.core, hw/ip/otbn/rtl/otbn.sv, hw/ip/otbn/rtl/otbn_controller.sv, hw/ip/otbn/rtl/otbn_core.sv, hw/ip/otbn/rtl/otbn_pkg.sv, hw/ip/otbn/rtl/otbn_scramble_ctrl.sv, hw/ip/otbn/rtl/otbn_start_stop_control.sv
=> [otbn] Added sparse FSM encoding

hw/ip/pwrmgr/data/pwrmgr_testplan.hjson, hw/ip/pwrmgr/doc/checklist.md, hw/ip/pwrmgr/doc/dv/index.md
=> [dv/pwrmgr] Update documentation and checklist

hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv, hw/dv/sv/spi_agent/spi_agent_cfg.sv, hw/ip/spi_host/data/spi_host_testplan.hjson, hw/ip/spi_host/doc/checklist.md, hw/ip/spi_host/doc/dv/index.md, hw/ip/spi_host/dv/cov/spi_host_cov.core, hw/ip/spi_host/dv/cov/spi_host_cov_bind.sv, hw/ip/spi_host/dv/cov/spi_host_cov_if.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_base_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv, hw/ip/spi_host/dv/env/spi_host_env_cfg.sv, hw/ip/spi_host/dv/env/spi_host_env_pkg.sv, hw/ip/spi_host/dv/env/spi_host_scoreboard.sv, hw/ip/spi_host/dv/env/spi_segment_item.sv, hw/ip/spi_host/dv/env/spi_transaction_item.sv, hw/ip/spi_host/dv/spi_host_sim_cfg.hjson
this PR is gated by #8856 
this commit contains two  commits
the first adds the coverage interface for future coverage work.
the second updates the the documentation, testplan and checklist to reflect the current state of the DV.
once #8856 goes in this PR will be the basis of an V1 review with the listed reviewers
=> [spi_host /dv] added coverage framework and updated documentation for V1

hw/ip/prim/rtl/prim_alert_receiver.sv
=> [prim_alert_receiver] Fix ping during init sequence bug

hw/ip/flash_ctrl/rtl/flash_phy_rd.sv, hw/ip/flash_ctrl/rtl/flash_phy_scramble.sv
- Fixes #9842
- primarily needed to handle cases where there are back to
back requests for prim_prince
=> [flash_ctrl] Small shimming logic around prim_prince

hw/ip/aes/rtl/aes_core.sv
Previously, we were feeding zero into the cipher output unmasking logic to avoid leaking intermediate state whenever the cipher core output isn't valid. However, this may still leak information on the final cipher core output when it becomes valid (mux output changes from deterministic value to cipher output). To avoid that, this commit feeds different PRD for both shares into the unmasking logic whenever the output isn't valid.
This supersedes  #9776.
=> [aes/rtl] Don't feed zero into cipher output unmasking logic

hw/ip/pinmux/doc/_index.md
=> [pinmux/doc] Update sleep mode terminology

ci/scripts/check-generated.sh
If the auto-generation command itself fails, say so (rather than
saying that the generated files are not up to date).
Inspired by rather unhelpful messages in the CI logs for #9996.
=> [ci] Improve error message in check-generated.sh

hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv, hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
Some sequences of operations could cause a problem where we ran two
back-to-back operations, each of which causing a recoverable alert,
where the second operation finished while before the handshake of the
first alert finished. If this happened, we would essentially drop the
second alert, causing the scoreboard to complain.
The fix is to expose the "waiting for an alert" state from the
scoreboard and wait in the vseq for that, then for any following
recoverable alert handshake to finish. This way, we can't start the
second operation too early.
=> [otbn,dv] Avoid "double recov alert" problem

hw/ip/edn/dv/env/edn_env.sv, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/edn_env_pkg.sv, hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/edn_virtual_sequencer.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv, hw/ip/edn/dv/tb.sv, hw/ip/edn/dv/tests/edn_genbits_test.sv
=> [edn/dv] Support multiple endpoints

hw/ip/spi_host/data/spi_host.prj.hjson, hw/ip/spi_host/data/spi_host_testplan.hjson, hw/ip/spi_host/doc/checklist.md, hw/ip/spi_host/doc/dv/index.md, hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv, hw/ip/spi_host/dv/env/spi_host_scoreboard.sv, hw/ip/spi_host/dv/env/spi_segment_item.sv, hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
This PR has two commits
1 to address the few documentation comments made in the review
2 A commit that fixes some compile issues seen on VCS only
This sets the DV status to V1
=> SPI Host V1 sign-off

hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
The fix in #9708 is fine, but this one makes the tool
issue more clear.
Also confirmed multiple times there SHOULD NOT be a real
combinational loop inside flash controller at the moment.
=> [flash_ctrl] Alternative fix to #9708

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/doc/_index.md, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
- clarify behavior and usage of flash read buffers
=> [flash_ctrl] Documentation update

hw/ip/spi_device/rtl/spi_passthrough.sv
As described in the issue #9741 , the configs that affect the output
path directly should be latched in the output clock (inverted SCK).
As of now, address swap and payload swap affect the output datapath.
=> [spi_device] latch swap configs at outclk

hw/ip/usbdev/lint/usbdev.waiver
=> [usbdev] Add lint waiver

hw/ip/pinmux/data/pinmux_fpv_testplan.hjson
This PR updates pinmux testplan.
=> [pinmux/doc] Add pinmux testplan

hw/ip/pinmux/rtl/pinmux_wkup.sv
This re-applies the original commit.
=> [pinmux_wkup] Change comparison to GE to stay on the safe side

doc/rm/comportability_specification/index.md
I should note that I think there are some slightly dubious entries here. For example, I can't see a situation where the (open source) OpenTitan project is going to use `GLITCH_DETECT`. But this PR is intended to match the current list of countermeasure names (as used in the product-specific Google Sheet). I propose any bikeshedding about names should be in a separate PR :-D
Closes #9985.
=> [doc] Describe countermeasure keys in comportability spec

hw/top_earlgrey/dv/chip_sim.core, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/chip_env_pkg.sv, hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv, hw/top_earlgrey/dv/tb/tb.sv
=> [dv] Fix sram backdoor loading

hw/ip/spi_host/doc/checklist.md, hw/ip/spi_host/rtl/spi_host.sv
- Indicate remaining PR's blocking D2
- Mark all V1 and V2 items as IN PROGRESS
- Mark D2S, V2S sections as N/A
=> [ spi_host, prj ] Update SPI_HOST checklist

hw/ip/sram_ctrl/data/sram_ctrl.prj.hjson, hw/ip/sram_ctrl/doc/checklist.md
=> [sram/dv] Sign off V2

hw/ip/pwm/data/pwm.prj.hjson, hw/ip/pwm/data/pwm_testplan.hjson, hw/ip/pwm/doc/checklist.md, hw/ip/pwm/dv/env/pwm_scoreboard.sv, hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
this PR contains a commit to move PWM to V1 and add it to the nightly regression.
it also addresses the few comments in 
https://docs.google.com/document/d/1KAMccGRvX0Jms6P50PFkE7DlqfkVrDCuLugoknxXBKA/edit#heading=h.xkag959c5d75
lastly it fixes a few compile issues that came to surface with VCS
=> PWM V1 sign-off

hw/ip/edn/dv/env/edn_env.sv, hw/ip/edn/dv/env/edn_env_pkg.sv, hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv, hw/ip/edn/dv/tests/edn_smoke_test.sv
=> [edn/dv] Add scoreboard checking

hw/top_earlgrey/dv/chip_smoketests.hjson
=> [ci] Add pwrmgr_smoketest to private CI

hw/ip/flash_ctrl/doc/_index.md, hw/ip/tlul/doc/_index.md
- update to explain instruction type attribute in tlul user bits.
- update to explain how flash execution contro makes use of the
instruction type bits.
- Companion PR to #10035 and #10022
=> [doc] update tlul and flash documentation

hw/ip/pinmux/data/pinmux.prj.hjson, hw/ip/pinmux/doc/checklist.md
This PR updates V1 checklist and status.
=> [fpv/pinmux] V1 checklist

hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson, hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
=> Added sysrst_ctrl to nightly regression

hw/ip/clkmgr/data/clkmgr.sv.tpl, hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
=> [clkmgr] Connect timeout error to recoverable alerts

doc/project/checklist.md
As discussed in SRAM Ctrl V2 review, updated these checklist
1. Updated the description for “pre_verified_sub_modules_v2”
2. Updated V2S checklist to add an item for FPV
=> [dv] Update checklist

hw/ip/spi_device/rtl/spi_device.sv
SW access port (TL-UL) can handle the grant signal. Other requesters
from the HW can't handle. The assertion catches the case but the better
approach is to lower the SW access priority in prim_sram_arbiter and
also block the requeset when SPI transaction is active.
=> [spi_device] Connect SRAM arbiter grant signal

hw/ip/spi_host/data/spi_host.prj.hjson, hw/ip/spi_host/dv/spi_host_sim.core, hw/ip/spi_host/dv/spi_host_sim_cfg.hjson, hw/ip/spi_host/spi_host.core
- Update SPI_HOST to D2
- Update version to 1.0 for SPI_HOST design and DV
=> [ spi_host, proj ] SPI_HOST D2 milestone completion

hw/ip/otbn/doc/dv/fcov.md, hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv, hw/ip/otbn/dv/uvm/env/otbn_trace_item.sv, hw/ip/otbn/dv/uvm/env/otbn_trace_monitor.sv
@prajwalaputtappa: Since I know you've thought about this interface a bit: anything you can think of that I've missed?
=> [otbn,dv] Add functional coverage for the key sideload interface

hw/ip/otbn/doc/dv/fcov.md, hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv, hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
=> [otbn,dv] Add coverage for scratchpad memory

hw/ip/aon_timer/data/aon_timer_testplan.hjson, hw/ip/aon_timer/dv/aon_timer_sim_cfg.hjson, hw/ip/aon_timer/dv/env/aon_timer_env_cov.sv, hw/ip/aon_timer/dv/env/aon_timer_scoreboard.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_base_vseq.sv, hw/ip/aon_timer/dv/env/seq_lib/aon_timer_smoke_vseq.sv
Split into 3 different commits to make reviewing easier, this PR includes changes to AON Timer DV testplan and it's smoke test. Also includes some changes to model writing to count registers of both timers.
=> [aon_timer,dv] AON Timer, V1 Review Action Items

hw/top_earlgrey/dv/tb/tb.sv
=> [chip/dv] Add missing analog port to TB

hw/ip/rom_ctrl/data/rom_ctrl.hjson, hw/ip/rom_ctrl/rtl/rom_ctrl.sv, hw/ip/rom_ctrl/rtl/rom_ctrl_compare.sv, hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv, hw/ip/rom_ctrl/rtl/rom_ctrl_mux.sv
This is going to be the starting point for both the D2S review and
also any extra testplan items that go into V2S. Try to explicitly list
all the extra tricks we're playing.
=> [rom_ctrl,doc] Expand countermeasure list

hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/xbar_main.hjson, hw/top_earlgrey/dv/autogen/xbar_env_pkg__params.sv, hw/top_earlgrey/ip/xbar_main/data/autogen/xbar_main.gen.hjson, hw/top_earlgrey/ip/xbar_main/dv/autogen/xbar_env_pkg__params.sv, hw/top_earlgrey/ip/xbar_main/rtl/autogen/xbar_main.sv
- Fixes #10153
- Also re-arrange the entries to be the same as hjson declaration
so it is easier to audit in the future.
=> [top] Add spi_hosts to sba access

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/doc/_index.md, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_core_reg_top.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_pkg.sv, sw/device/lib/flash_ctrl.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.c, sw/device/silicon_creator/lib/drivers/flash_ctrl.h, sw/device/silicon_creator/lib/drivers/flash_ctrl_unittest.cc
- Will address #10022 when the constant value is determined.
=> [flash_ctrl] flash exec value update

hw/dv/sv/csrng_agent/csrng_item.sv, hw/ip/edn/dv/cov/edn_cov.core, hw/ip/edn/dv/cov/edn_cov_bind.sv, hw/ip/edn/dv/cov/edn_cov_if.sv, hw/ip/edn/dv/edn_sim.core, hw/ip/edn/dv/edn_sim_cfg.hjson, hw/ip/edn/dv/env/edn_env.sv, hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv, hw/ip/edn/dv/tb.sv
=> [edn/dv] Add initial coverage

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_pin_override_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_vseq_list.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.core, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_if.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_scoreboard.sv, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson
This test will verify the sysrst_ctrl pin override module.
=> [sysrst_ctrl,dv] Added sysrst_ctrl_pin_override_test

hw/ip/entropy_src/dv/cov/entropy_src_cov.core, hw/ip/entropy_src/dv/cov/entropy_src_cov_bind.sv, hw/ip/entropy_src/dv/cov/entropy_src_cov_if.sv, hw/ip/entropy_src/dv/entropy_src_sim.core, hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson, hw/ip/entropy_src/dv/env/entropy_src_env.core, hw/ip/entropy_src/dv/env/entropy_src_env.sv, hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_rng_vseq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_smoke_vseq.sv, hw/ip/entropy_src/dv/tb/tb.sv
=> [entropy_src/dv] Add initial coverage

hw/ip/otp_ctrl/data/otp_ctrl.hjson, hw/ip/otp_ctrl/data/otp_ctrl_img_rma.hjson, hw/ip/otp_ctrl/data/otp_ctrl_mmap.hjson, hw/ip/otp_ctrl/doc/otp_ctrl_mmap.md, hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv, sw/device/silicon_creator/lib/drivers/BUILD, sw/device/silicon_creator/lib/drivers/meson.build, sw/device/silicon_creator/lib/drivers/rnd.c, sw/device/silicon_creator/lib/drivers/rnd.h, sw/device/silicon_creator/lib/drivers/rnd_functest.c, sw/device/silicon_creator/mask_rom/BUILD, sw/device/silicon_creator/mask_rom/mask_rom.c, sw/device/silicon_creator/mask_rom/meson.build
This PR introduces a lightweight RNG driver to be used in the implementation of countermeasures.
=> [sw/rom] Add RNG driver

hw/ip/csrng/data/csrng_testplan.hjson, hw/ip/csrng/dv/cov/csrng_cov_if.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_smoke_vseq.sv
=> [csrng/dv] Updated testplan, Added cfg cover group

hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
Verification works best when the main fsm alert signal is a pulse.
Fixes #10134.
=> [entropy_src/rtl] create a pulse for alert signal

hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_aborted_low_power_vseq.sv
Fix constraint for *idle signals.
Increase the chances of abort, to sample more *idle combinations.
=> [dv/pwrmgr] Fix constraints

hw/ip/aes/pre_syn/tcl/yosys_run_synth.tcl, hw/ip/aes/rtl/aes_sbox_dom.sv
This resolves lowRISC/OpenTitan#10180.
=> [aes] Remove hierarchical paths in DOM S-Box

hw/ip/aes/syn/aes_gtech_syn_cfg.hjson, hw/ip/aes/syn/aes_syn_cfg.hjson
=> [aes] update AES version in synthesis configs

hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
Fix missing isolation fork in process_low_power_hint.
The check_wake_status task compares read from CSR wake_status against
expected wakeups.
=> [dv/pwrmgr] Add isolation fork and check_wake_status

hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
As part of #10188, it was realized that rma entry is currently gated
by flash initilization.
This may not be a good idea because if flash initlization were to ever
stall (ROM could not program it for whatever reason), then rma entry
could never be done.
This PR allows RMA entry to happen even if initilization has not been
called.  If initilization has not been called, it is possible that
entropy is not properly behaving as part of the ROM routine, so the
reseeding is also skipped so that the flash can be directly wiped.
=> [flash_ctrl] Allow rma entry even if flash has not been initialized.

hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_aborted_low_power_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_reset_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv
=> [dv/pwrmgr] Stimulate the rom inputs

hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_aborted_low_power_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_lowpower_wakeup_race_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_reset_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_smoke_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv, hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_vseq.sv
=> [dv/pwrmgr] Use status check tasks

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/doc/_index.md, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson
- Addresses the questions from #10188 and #10189.
=> [flash_ctrl] Documentation updates

hw/ip/sysrst_ctrl/data/sysrst_ctrl.prj.hjson, hw/ip/sysrst_ctrl/doc/checklist.md, hw/ip/sysrst_ctrl/doc/dv/index.md, hw/ip/sysrst_ctrl/doc/dv/sysrst_ctrl_tb_block_diagram.svg
This pull request is to declare V1 signoff.
- Completed Draft DV_doc
- Updated the checklist
- Changed the verification stage
=> [sysrst_ctrl,doc] V1 signoff

hw/ip/adc_ctrl/data/adc_ctrl.prj.hjson
- Updated adc_ctrl.prj.hjson to move ADC_CTRL to verification stage V1
=> [adc_ctrl] Updated ADC_CTRL to verification stage V1

hw/ip/pwrmgr/dv/sva/pwrmgr_clock_enables_sva_if.sv
Expect all clocks off in deep sleep.
=> [dv/pwrmgr] Fix SVA assertion for spec changes

hw/ip/pwrmgr/data/pwrmgr.hjson, hw/ip/pwrmgr/data/pwrmgr.hjson.tpl, hw/ip/pwrmgr/pwrmgr.core, hw/ip/pwrmgr/rtl/pwrmgr.sv, hw/ip/pwrmgr/rtl/pwrmgr_fsm.sv, hw/ip/pwrmgr/rtl/pwrmgr_slow_fsm.sv, hw/ip/rstmgr/data/rstmgr.hjson, hw/ip/rstmgr/data/rstmgr.hjson.tpl, hw/ip/rstmgr/data/rstmgr.sv.tpl, hw/ip/rstmgr/rstmgr.core, hw/ip/rstmgr/rtl/rstmgr_cnsty_chk.sv, hw/ip/rstmgr/rtl/rstmgr_leaf_rst.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr.hjson, hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson, hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr.sv, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_englishbreakfast/data/top_englishbreakfast.hjson
- convert to new sparse fsms
- add addidiontal sparse fsms to reset
=> [pwrmgr, rstmgr] Various D2S prep steps

util/dashboard/gen_dashboard_entry.py
=> [doc] Add D2S as valid entry in dashboard script

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/data/flash_ctrl_pkg.sv.tpl, hw/ip/flash_ctrl/flash_ctrl.core, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_arb.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_core_reg_top.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_pkg.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_pkg.sv
- fully covnert to new sparse fsm
- add additional fsms as needed
=> [flash_ctrl] D2S preparation steps

azure-pipelines.yml, ci/install-package-dependencies.sh, doc/ug/install_instructions/index.md, meson.build, sw/device/lib/arch/BUILD, sw/device/silicon_creator/lib/BUILD, sw/device/tests/BUILD, util/container/Dockerfile
=> [bazel] Add bazel to lists of required packages and to CI

sw/device/tests/autogen/plic_all_irqs_test.c, util/topgen/templates/plic_all_irqs_test.c.tpl
...and FPGA.
The logging mechanism which uses UART0 in Verilator and FPGA setups
messes up this test, which is meant to enable and test ALL interrupts
from all peripherals in the device, including UART0. The fix is to skip
testing UART0 interrupts for Verilator and FPGA.
Fixes #8656.
=> [chip dv] Fix plic_all_irqs_test for Verilator

hw/ip/adc_ctrl/rtl/adc_ctrl.sv, hw/ip/aon_timer/rtl/aon_timer.sv, hw/ip/gpio/rtl/gpio.sv, hw/ip/hmac/rtl/hmac.sv, hw/ip/i2c/rtl/i2c.sv, hw/ip/pattgen/rtl/pattgen.sv, hw/ip/pinmux/data/pinmux.hjson, hw/ip/pinmux/rtl/pinmux.sv, hw/ip/pwm/rtl/pwm.sv, hw/ip/rv_dm/rtl/rv_dm.sv, hw/ip/rv_timer/rtl/rv_timer.sv, hw/ip/spi_device/rtl/spi_device.sv, hw/ip/spi_host/rtl/spi_host.sv, hw/ip/sysrst_ctrl/rtl/sysrst_ctrl.sv, hw/ip/uart/rtl/uart.sv, hw/ip/usbdev/rtl/usbdev.sv, hw/ip/usbuart/rtl/usbuart.sv, hw/ip_templates/rv_plic/rtl/rv_plic.sv.tpl, hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic.sv, util/ipgen/renderer.py, util/reggen/countermeasure.py, util/topgen.py
=> [ipgen] Add countermeasure check for generated IPs (IPgen and legacy style)

azure-pipelines.yml, ci/install-package-dependencies.sh, doc/ug/install_instructions/index.md, meson.build, sw/device/lib/arch/BUILD, sw/device/silicon_creator/lib/BUILD, sw/device/tests/BUILD, util/container/Dockerfile
This reverts commit bc4274a6c61dc642785e7f3f82b6c13a358aa5b4.
https://github.com/lowRISC/opentitan/pull/10307 didn't have the Signed-off-by line and I can't figure out how to update the commit message since it wasn't published through the normal path.
=> Revert "[bazel] Add bazel to CI and containers"

hw/ip/entropy_src/rtl/entropy_src.sv, hw/ip/entropy_src/rtl/entropy_src_core.sv, hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/kmac.core, hw/ip/kmac/rtl/keccak_round.sv, hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_core.sv, hw/ip/kmac/rtl/kmac_reg_pkg.sv, hw/ip/kmac/rtl/kmac_reg_top.sv, hw/ip/kmac/rtl/sha3.sv, hw/ip/kmac/rtl/sha3pad.sv, sw/device/lib/dif/autogen/dif_kmac_autogen.h
This PR addresses the critical counters with in #8982
=> [kmac/entropy_src] added prim_count for sent_message, key_index and round counter

hw/ip/entropy_src/rtl/entropy_src.sv, hw/ip/entropy_src/rtl/entropy_src_bucket_ht.sv
Fixes #10226.  See that issue for motivation.
=> [entropy_src] Fix 1-clk timing error in Bucket Test output

hw/ip/rstmgr/dv/env/rstmgr_env_pkg.sv, hw/ip/rstmgr/dv/env/rstmgr_if.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_smoke_vseq.sv
=> [dv/rstmgr] Add missing interface signals

hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/doc/_index.md, hw/ip/sram_ctrl/rtl/sram_ctrl.sv, hw/ip/tlul/rtl/tlul_adapter_sram.sv
=> [sram_ctrl] Address pending D2S items

hw/ip_templates/alert_handler/data/alert_handler.prj.hjson, hw/ip_templates/alert_handler/doc/checklist.md, hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.prj.hjson, hw/top_earlgrey/ip_autogen/alert_handler/doc/checklist.md
This PR should not be merged before #10272 has landed.
=> [alert_handler] Move into D2S

hw/ip/rom_ctrl/data/rom_ctrl.prj.hjson, hw/ip/rom_ctrl/doc/checklist.md
Follow-up after the D2S review meeting on 18th Jan.
=> [rom_ctrl] Update checklist and mark as D2S

hw/ip/kmac/data/kmac.prj.hjson
As security review items are in D2S. KMAC IP has been reached D2.
=> [kmac] Reaching D2

hw/ip/pwrmgr/data/pwrmgr.hjson, hw/ip/pwrmgr/data/pwrmgr_testplan.hjson, hw/ip/pwrmgr/doc/checklist.md
=> [dv/pwrmgr] Update documentation

hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_wakeup_reset_vseq.sv
The pwrmgr_wakeup_reset sequence occasionally fails because
twirl_rom_response waits conflict with other waits for checking
wakeup status.
=> [dv/pwrmgr] Fix failure due to timing conflicts

hw/ip/spi_device/data/spi_device.prj.hjson, hw/ip/spi_device/doc/checklist.md
Missed the update of prj.hjson in previous PR.
Also the checklist added CDC item waived
=> [spi_device] Update prj.hjson to D2

hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv, hw/ip/otp_ctrl/dv/env/otp_ctrl_env_pkg.sv, hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv, hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_init_fail_vseq.sv
This PR aligns the behavior for vendor_test partition with design
change #10317
=> [dv/otp_ctrl] Align vendor_test partition with design

hw/dv/sv/csrng_agent/csrng_agent_cfg.sv, hw/dv/sv/csrng_agent/seq_lib/csrng_device_seq.sv, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv, hw/ip/edn/dv/tests/edn_base_test.sv, hw/ip/edn/dv/tests/edn_smoke_test.sv
=> [edn/dv] Verify boot_req_mode

hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_if.sv
Updates made to coverage interface as design has evolved more.
Removed cp_rom_invalid_condition covergroup as there is no
pwrmgr_data_o.invalid bit. Corrupting good and done signals to get the
invalid coverage doesn't make sense for the design at this stage.
=> [rom_ctrl, dv] Upgrades to collect functional coverage

hw/ip/csrng/dv/env/csrng_env.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv, hw/ip/entropy_src/dv/env/seq_lib/entropy_src_base_vseq.sv
=> [csrng/entropy_src/dv] Move otp signal drive so before reset

hw/ip/pwrmgr/data/pwrmgr.prj.hjson
=> [dv/pwrmgr] Declare v2

hw/ip/pinmux/doc/_index.md
=> [pinmux/doc] Fix a TODO in the docs

hw/ip/keymgr/doc/dv/index.md
=> [keymgr/dv] Fix a broken link in dv_doc

hw/ip/tlul/data/tlul.prj.hjson, hw/ip/tlul/doc/dv/index.md
All common TLUL verification items have been completed.
Xbar coverage has reached V2 status
SCORE	LINE	COND	TOGGLE	FSM	BRANCH	ASSERT	GROUP
98.47	100.00	95.59	98.47	--	97.30	99.50	100.00
=> [tlul] Move to V2

sw/device/silicon_creator/lib/error.h, sw/device/silicon_creator/lib/irq_asm.S, sw/device/silicon_creator/lib/sigverify.c, sw/device/silicon_creator/lib/sigverify_unittest.cc, sw/device/silicon_creator/mask_rom/mask_rom.c
This PR fixes a couple of minor issues that we identified during the walkthrough meeting. Please see the individual commits for descriptions of the changes.
=> [sw/silicon_creator] Minor updates to mask rom code from the walkthrough meeting

sw/device/lib/dif/dif_alert_handler.c
Several CSRs for both alerts and local alerts are organized as multiregs, enabling easy DIF development. However, there is currently no mechanism to indicate if the multireg layout of said CSRs ever changes. This commit adds static asserts to check these multireg layouts.
This partially addresses a task in #9899.
**_Note: this PR depends on #10320, and contains duplicate commits that will be removed when #10320 merges._**
=> [dif/alert_handler] Add static asserts for multireg layouts.

hw/ip/keymgr/keymgr.core, hw/ip/keymgr/rtl/keymgr.sv, hw/ip/keymgr/rtl/keymgr_ctrl.sv, hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
- update specific signal to mubi
=> [keymgr] D2S preparation

hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv, hw/ip/prim/rtl/prim_count.sv
- should address #10378
- add a parameter option when a custom max value is not required
=> [prim, otp] update prim_count handling of max value

hw/ip/aon_timer/data/aon_timer.prj.hjson, hw/ip/aon_timer/doc/checklist.md
All action items from V1 review have been finished and PRs have been merged.
=> [aon_timer,dv] V1 Signoff

sw/host/opentitanlib/BUILD, sw/host/opentitanlib/Cargo.toml, sw/host/opentitanlib/src/crypto/mod.rs, sw/host/opentitanlib/src/crypto/sha256.rs, third_party/cargo/crates.bzl, third_party/cargo/remote/BUILD.block-buffer-0.10.0.bazel, third_party/cargo/remote/BUILD.cpufeatures-0.2.1.bazel, third_party/cargo/remote/BUILD.crypto-common-0.1.1.bazel, third_party/cargo/remote/BUILD.digest-0.10.1.bazel, third_party/cargo/remote/BUILD.generic-array-0.14.5.bazel, third_party/cargo/remote/BUILD.sha2-0.10.1.bazel, third_party/cargo/remote/BUILD.typenum-1.15.0.bazel
This PR adds the sha256 module for computing sha256 digests.
=> [opentitantool] Add sha256

sw/device/silicon_creator/lib/drivers/BUILD
=> [bazel] pwrmgr_testutils 2 keymgr_functest deps

hw/ip/lc_ctrl/data/lc_ctrl.hjson, hw/ip/lc_ctrl/doc/_index.md, hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_signal_decode.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_earlgrey/rtl/autogen/top_earlgrey_rnd_cnst_pkg.sv
This addresses #10303.
Note that the system integration diagram is still pending.
~~Will pile it onto this PR once completed.~~
I will add that one in a separate PR.
=> [lc_ctrl] Address D2S opens

hw/ip/rstmgr/doc/_index.md
=> [rstmgr] Update reset info to include software reset

hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/kmac.core, hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_entropy.sv, sw/device/lib/dif/autogen/dif_kmac_autogen.h
=> [KMAC] replaced prim_lfsr with prim_double_lfsr as suggested in #8629

hw/ip/sram_ctrl/data/sram_ctrl.prj.hjson, hw/ip/sram_ctrl/doc/checklist.md
~~This should not be merged before #10274 has landed.~~
=> [sram_ctrl] Move into D2S

hw/ip/edn/data/edn.hjson, hw/ip/edn/doc/_index.md, hw/ip/edn/rtl/edn_ack_sm.sv, hw/ip/edn/rtl/edn_core.sv, hw/ip/edn/rtl/edn_main_sm.sv
Feedback from the D2S review reflected back into the design.
=> [edn/rtl] D2S review updates

hw/ip/lc_ctrl/rtl/lc_ctrl.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_kmac_if.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_state_decode.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv, hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv.tpl
=> [lc_ctrl] Annotate RTL with CM labels

hw/top_earlgrey/dv/verilator/chip_sim_tb.cc, hw/top_earlgrey/rtl/chip_earlgrey_verilator.sv
- companion commit to #10403
- verilator specific updates to allow ast to reset correctly.
=> [top] verilator updates for new ast por model

hw/ip/pwrmgr/dv/sva/pwrmgr_ast_sva_if.sv, hw/top_earlgrey/ip/ast/ast.core, hw/top_earlgrey/ip/ast/data/ast.hjson, hw/top_earlgrey/ip/ast/doc/ast_regs.html, hw/top_earlgrey/ip/ast/rtl/aon_osc.sv, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv, hw/top_earlgrey/ip/ast/rtl/ast_dft.sv, hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv, hw/top_earlgrey/ip/ast/rtl/ast_pulse_sync.sv, hw/top_earlgrey/ip/ast/rtl/ast_reg_pkg.sv, hw/top_earlgrey/ip/ast/rtl/ast_reg_top.sv, hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv, hw/top_earlgrey/ip/ast/rtl/io_osc.sv, hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv, hw/top_earlgrey/ip/ast/rtl/rng.sv, hw/top_earlgrey/ip/ast/rtl/sys_osc.sv, hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
=> [AST] Deep sleep & POR_NI logic update2

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_seq_cfg.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_base_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
adding randomization for scramble,ecc and he,
modifying scb for eflash ral checking support
=> [flash_ctrl] Adding test host direct read,

doc/rm/comportability_specification/index.md, hw/ip/otp_ctrl/data/otp_ctrl.hjson, hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl, hw/ip/otp_ctrl/doc/_index.md, hw/ip/otp_ctrl/rtl/otp_ctrl.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_dai.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_kdi.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_lci.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_lfsr_timer.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_part_buf.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv.tpl, hw/ip/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv, hw/ip/otp_ctrl/rtl/otp_ctrl_scrmbl.sv, hw/ip/prim/rtl/prim_mubi12_sender.sv, hw/ip/prim/rtl/prim_mubi16_sender.sv, hw/ip/prim/rtl/prim_mubi4_sender.sv, hw/ip/prim/rtl/prim_mubi8_sender.sv, util/design/data/prim_mubi_sender.sv.tpl, util/reggen/countermeasure.py
This is a follow-up for #10435. See also #10420 for context.
=> [otp_ctrl] Second round of D2S opens

hw/ip/aes/data/aes.hjson, hw/ip/aes/rtl/aes.sv, hw/ip/aes/rtl/aes_reg_top.sv
This should be a quick one to review.
=> [aes] Minor RTL modifications based on D2S review

hw/ip/entropy_src/data/entropy_src.hjson, hw/ip/entropy_src/doc/_index.md, hw/ip/entropy_src/rtl/entropy_src.sv, hw/ip/entropy_src/rtl/entropy_src_ack_sm.sv, hw/ip/entropy_src/rtl/entropy_src_cntr_reg.sv, hw/ip/entropy_src/rtl/entropy_src_core.sv, hw/ip/entropy_src/rtl/entropy_src_main_sm.sv, sw/device/lib/dif/autogen/dif_entropy_src_autogen.h
RTL changes based on D2S review made.
Doc text updated with security description.
=> [entropy_src/rtl] d2s review updates

hw/ip/kmac/dv/env/kmac_scoreboard.sv
This PR aligns a fifo empty interrupt related behavior:
If the read and write pointers are equal, and next clock cycle a write
is issued and accepted, the fifo empty interrupt won't fire.
=> [dv/kmac] fifo empty interrupt behavior

azure-pipelines.yml, ci/scripts/quick-bazel.sh
=> [bazel] Add a quick-bazel script to rerun CI

hw/ip/kmac/data/kmac_base_testplan.hjson, hw/ip/kmac/dv/env/kmac_env_cfg.sv, hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
This PR adds shadow reg common tests to kmac.
=> [dv/kmac] Shadow reg common test

hw/dv/sv/cip_lib/cip_base_pkg.sv
@msfschaffner: Looks like we missed one! :-)
=> [dv] Fix randomisation of lc_tx_t values

hw/ip/edn/data/edn.hjson, hw/ip/edn/rtl/edn_core.sv
Fix for number of gen commands between reseed commands.
=> [edn/rtl] Add auto-request mode bug fix

hw/ip/clkmgr/data/clkmgr.hjson.tpl, hw/ip/clkmgr/data/clkmgr.sv.tpl, hw/ip/clkmgr/doc/_index.md, hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson, hw/top_earlgrey/ip/clkmgr/rtl/autogen/clkmgr.sv
=> [clkmgr] D2S checklist preparation

hw/ip/adc_ctrl/rtl/adc_ctrl_core.sv, hw/ip/adc_ctrl/rtl/adc_ctrl_fsm.sv
=> [adc_ctrl] Tweak timing of when sample checks are made

hw/ip/flash_ctrl/rtl/flash_phy_rd.sv
Do not begin mask calculation request until read
trasnaction has been accepted.
=> [flash_ctrl] Fix mask calculation request timing

hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
=> [flash_ctrl] Add sva to check for rma prog / rd data match

hw/ip/lc_ctrl/data/lc_ctrl.prj.hjson, hw/ip/lc_ctrl/doc/checklist.md
This should not be merged before #10360 and #10392 have landed.
=> [lc_ctrl/doc] Update checklist and move to D2S

hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__tl_errors.svh, hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv, hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
=> [tlul] enable checking a_data integrity for read 

hw/ip/rstmgr/data/rstmgr.hjson, hw/ip/rstmgr/data/rstmgr.hjson.tpl, hw/ip/rstmgr/data/rstmgr.sv.tpl, hw/ip/rstmgr/data/rstmgr_pkg.sv.tpl, hw/ip/rstmgr/doc/_index.md, hw/ip/rstmgr/rtl/rstmgr_cnsty_chk.sv, hw/ip/rstmgr/rtl/rstmgr_leaf_rst.sv, hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson, hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr.sv, hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr_pkg.sv
- Add countermeasure list and annotate design
=> [rstmgr] Prepare d2s items

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson, hw/ip/flash_ctrl/dv/env/flash_ctrl_env.core, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_buff_evict_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_vseq_list.sv, hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson
First pull request #10052 should be merged since it has environment changes for fifo evicition test.
=> [flash_ctrl] Flash ctrl rd buffer eviction

hw/cdc/tools/verixcdc/run-cdc.tcl, hw/top_earlgrey/cdc/cdc_waivers.gpio.tcl, hw/top_earlgrey/cdc/cdc_waivers.tcl
Add submodules and generate report per module.
=> [cdc] Add submodules

hw/ip/keymgr/data/keymgr.hjson, hw/ip/keymgr/doc/_index.md
=> [keymgr] Remove unnecessary line in doc

hw/ip/spi_device/data/spi_device.hjson
Flash and Passthrough modes are added into CFG.MODE CSR.
Issue is reported by @tjaychen in #10524
=> [spi_device] Add flash/passthrouh modes in CFG.MODE

hw/ip/keymgr/data/keymgr.hjson, hw/ip/keymgr/rtl/keymgr.sv, hw/ip/keymgr/rtl/keymgr_ctrl.sv, hw/ip/keymgr/rtl/keymgr_kmac_if.sv, hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv
=> [keymgr] Prep d2s list and annotate design

hw/ip/otp_ctrl/data/otp_ctrl.prj.hjson, hw/ip/otp_ctrl/doc/checklist.md
~~This should not be merged before #10473 has landed.~~
See https://github.com/lowRISC/opentitan/issues/10420 for D2S review actions items.
=> [otp_ctrl] Move to D2S 

hw/ip/hmac/doc/_index.md
=> [hmac] Clarify hmac module security capability

hw/ip/prim/rtl/prim_count.sv
- Addresses final comment in #10378
=> [prim] update prim_count comment

hw/ip/kmac/rtl/kmac.sv, hw/ip/otp_ctrl/rtl/otp_ctrl.sv, hw/ip/prim/rtl/prim_double_lfsr.sv, hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv, hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
Also update all IPs to add an assertion for double_lfsr
=> [dv] Add assertion to check double_lfsr err triggers an alert

hw/dv/sv/key_sideload_agent/key_sideload_monitor.sv
just a very small syntax error that kept bugging me
=> [key_manager_agent/dv] fixed small formating issue

hw/ip/csrng/data/csrng.hjson, hw/ip/csrng/data/csrng_testplan.hjson, hw/ip/csrng/doc/_index.md, hw/ip/csrng/dv/tb.sv, hw/ip/csrng/rtl/csrng.sv, hw/ip/csrng/rtl/csrng_block_encrypt.sv, hw/ip/csrng/rtl/csrng_cmd_stage.sv, hw/ip/csrng/rtl/csrng_core.sv, hw/ip/csrng/rtl/csrng_ctr_drbg_gen.sv, hw/ip/csrng/rtl/csrng_ctr_drbg_upd.sv, hw/ip/csrng/rtl/csrng_main_sm.sv
RTL and documentation updates based on D2S review feedback.
=> [csrng/rtl] d2s review updates

hw/dv/sv/jtag_riscv_agent/jtag_riscv_monitor.sv
- Small bug injected by PR #10415
We need to record the operation field from the initial DMI request
as the same field is used by the status transaction to indicate
the access has succeded failed or is still in progress.
=> [jtag_riscv_agent] Fixed bug in jtag_riscv_monitor

hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
extract the write functions from #10566
scrambled address may locate across the tiles, need some special handle
in order to backdoor write to the correct location
Tested this update in foundry repo and test chip_sw_pwrmgr_smoketest is passing.
=> [top/dv] create sram bkdr write functions

hw/ip/pwrmgr/data/pwrmgr.hjson, hw/ip/pwrmgr/data/pwrmgr.hjson.tpl, hw/ip/pwrmgr/doc/_index.md, hw/ip/pwrmgr/rtl/pwrmgr.sv, hw/ip/pwrmgr/rtl/pwrmgr_fsm.sv, hw/ip/pwrmgr/rtl/pwrmgr_slow_fsm.sv, hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr.hjson
=> [pwrmgr] Prepare d2s countermeasure list and annotations

hw/ip/flash_ctrl/dv/env/flash_ctrl_env_cfg.sv, hw/ip/flash_ctrl/dv/env/flash_ctrl_scoreboard.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_host_dir_rd_vseq.sv, hw/ip/flash_ctrl/dv/env/seq_lib/flash_ctrl_rd_buff_evict_vseq.sv
Add small knob change for control of host read operations.
Change name of knob and invert value.
=> [flash_ctrl] SMALL SCOREBOARD KNOB CHANGE

hw/ip/sysrst_ctrl/doc/_index.md
This adds some more detail to the spec regarding the combo actions.
=> [sysrst_ctrl] Add some more details regarding combo actions

hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/doc/_index.md, sw/device/lib/dif/autogen/dif_kmac_autogen.h
Slightly change kmac doc to fix some typos and styles.
=> [doc/kmac] Small updates on kmac typos

hw/ip/hmac/doc/checklist.md, hw/ip/usbdev/doc/checklist.md
Just stumbled accross an old issue #8397 and fixed up some of the SEC items in non-security IP.
=> Checklist cleanup

hw/dv/tools/xcelium/common.ccf
=> [dv] Enable xcelium to include X for toggle coverage

hw/ip/rom_ctrl/rom_ctrl.core, hw/ip/rom_ctrl/rtl/rom_ctrl.sv
=> [rom_ctrl] Add force point for reset glitch tests

hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
=> [tlul] Remove unused signal

hw/dv/sv/csrng_agent/csrng_device_driver.sv, hw/dv/sv/csrng_agent/csrng_monitor.sv, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/edn_env_pkg.sv, hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_smoke_vseq.sv, hw/ip/edn/dv/tests/edn_base_test.sv, hw/ip/edn/dv/tests/edn_genbits_test.sv
=> [edn/dv] Verify auto_req_mode

hw/ip/tlul/rtl/tlul_adapter_sram.sv
=> [tlul] Return all-one upon all data read errors

hw/ip/spi_device/data/spi_device_testplan.hjson
Added tests for flash and passthrough modes. This can be starting point for review discussion. Please add remarks.
=> [spi_device] Updated testplan for flash and passthrough

hw/ip/rom_ctrl/data/rom_ctrl_testplan.hjson, hw/ip/rom_ctrl/dv/env/rom_ctrl_env.core, hw/ip/rom_ctrl/dv/env/rom_ctrl_env_cfg.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_stress_all_vseq.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_throughput_vseq.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_vseq_list.sv, hw/ip/rom_ctrl/dv/rom_ctrl_sim_cfg.hjson
Added max_trhoughput_chk test and all the necessary changes required to
run it.
=> [rom_ctrl, dv] max_trhoughput_chk testcase added

.gitignore
Add iDebug related files to the ignore list
=> .gitignore to ignore iDebug results

hw/ip/rstmgr/doc/checklist.md, hw/ip/rstmgr/doc/dv/index.md
=> [dv/rstmgr] Update dv doc and checklist

hw/ip/flash_ctrl/rtl/flash_phy_core.sv
- Due to the way arbitration count is cleared, it is possible
that when controller wins the arbitration its flash transaction
is not yet accepted.  This gives the host an opportunity to come
back and re-win the arbitration.  This is not correct behavior.
- Clear arbitration count only when controller has won and completed the
the transaction.
=> [flash_ctrl] Fix host / controller arbitration

doc/security/implementation_guidelines/_index.md, doc/security/implementation_guidelines/hardware/index.md
Commits the first version of the Secure Hardware Design Guidelines
authored by @cdgori and @tjaychen with various contributions from the
OpenTitan community.
=> [doc] Introduce Secure Hardware Design Guidelines

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/doc/_index.md, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_core_reg_top.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl_reg_pkg.sv
- harden rma_wipe_idx with prim_count
- connect seed_err
- minor documentation clean-up
- fixes #10396 
=> [flash_ctral] Various security item clean-up

hw/ip/pwrmgr/rtl/pwrmgr_cdc.sv
=> [pwrmgr] Update default value

hw/ip/aes/pre_sca/alma/README.md, hw/ip/kmac/pre_sca/alma/cpp/testbench.h, hw/ip/kmac/pre_sca/alma/cpp/verilator_tb_keccak_2share.cpp, hw/ip/kmac/pre_sca/alma/verify_kmac.sh, hw/ip/kmac/pre_syn/.gitignore, hw/ip/kmac/pre_syn/README.md, hw/ip/kmac/pre_syn/kmac.nangate.sdc, hw/ip/kmac/pre_syn/kmac_abc.nangate.sdc, hw/ip/kmac/pre_syn/kmac_lr_synth_conf.tcl, hw/ip/kmac/pre_syn/python, hw/ip/kmac/pre_syn/syn_setup.example.sh, hw/ip/kmac/pre_syn/syn_yosys.sh, hw/ip/kmac/pre_syn/tcl/flow_utils.tcl, hw/ip/kmac/pre_syn/tcl/lr_synth_flow_var_setup.tcl, hw/ip/kmac/pre_syn/tcl/sta_common.tcl, hw/ip/kmac/pre_syn/tcl/sta_open_design.tcl, hw/ip/kmac/pre_syn/tcl/sta_run_reports.tcl, hw/ip/kmac/pre_syn/tcl/sta_utils.tcl, hw/ip/kmac/pre_syn/tcl/yosys_common.tcl, hw/ip/kmac/pre_syn/tcl/yosys_post_synth.tcl, hw/ip/kmac/pre_syn/tcl/yosys_pre_map.tcl, hw/ip/kmac/pre_syn/tcl/yosys_run_synth.tcl, hw/ip/kmac/pre_syn/translate_timing_rpts.sh, hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_errchk.sv, util/licence-checker.hjson
For ES, we want to experimentally verify the correctness of the masking employed inside KMAC. This PR adds the required infrastructure to perform formal masking verification of KMAC using the Alma tool. This will become very handy once we start optimizing the masking together with the FPGA experiments.
=> [kmac, pre_syn, pre_sca] Add experimental Yosys synthesis flow and support files for formal masking verification

hw/ip/pwm/rtl/pwm_chan.sv
This commit simplifies (and corrects) the duty_cycle rounding 
arithmetic in pwm_chan. The solution (as before) is to zero out 
unused bits in either the commanded phase_delay or the actual
duty cycle.
Fixes #10062
=> [pwm/rtl] Handle rounding errors in pwm_chan

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/data/flash_ctrl_sec_cm_testplan.hjson, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_arb.sv, hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv, hw/ip/flash_ctrl/rtl/flash_phy_core.sv, hw/ip/flash_ctrl/rtl/flash_phy_rd.sv, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl_sec_cm_testplan.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
=> [flash_ctrl] flash_ctrl countermeasure list and annotation

doc/project/checklist.md
This commit clarifies what this checklist item indicates.
=> [dv] Updated SIM_FW_SIMULATED V2 checklist wording

hw/ip/usbdev/rtl/usbdev_reg_top.sv
=> [usbdev, rtl] Fix auto-generated files

hw/ip/aes/rtl/aes_control_fsm.sv, hw/ip/aes/rtl/aes_core.sv, hw/ip/aes/rtl/aes_pkg.sv
This is related to lowRISC/OpenTitan#8460.
=> [aes] Stop clearing status and trigger register to zero on fatal alerts

hw/ip/clkmgr/rtl/clkmgr_byp.sv, hw/ip/prim/rtl/prim_mubi12_sender.sv, hw/ip/prim/rtl/prim_mubi16_sender.sv, hw/ip/prim/rtl/prim_mubi4_sender.sv, hw/ip/prim/rtl/prim_mubi8_sender.sv, hw/ip/prim_generic/rtl/prim_generic_flop_en.sv, hw/ip/prim_xilinx/rtl/prim_xilinx_flop_en.sv, util/design/data/prim_mubi_sender.sv.tpl
=> [prim] Add anchor buffers

hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv
this commit should hopefully take care of the failing v2 test in the nightly regression
=> [aes/dv] fixed compile errors introduced with new rtl

sw/device/silicon_creator/lib/drivers/meson.build, sw/device/silicon_creator/lib/drivers/watchdog.c, sw/device/silicon_creator/lib/drivers/watchdog.h, sw/device/silicon_creator/lib/drivers/watchdog_unittest.cc, sw/device/silicon_creator/mask_rom/BUILD, sw/device/silicon_creator/mask_rom/mask_rom.c, sw/device/silicon_creator/mask_rom/primitive_bootstrap.c, sw/device/silicon_creator/mask_rom/primitive_bootstrap.h
This PR addresses some open points from (#10632). Please see individual commits for details.
=> [sw/silicon_creator] Watchdog updates

hw/ip/aes/dv/sva/aes_bind.sv, hw/ip/aes/dv/sva/aes_idle_check.sv, hw/ip/aes/dv/sva/aes_sva.core
This PR addresses the AI raised in the V2 review #10757 
Signed-off-by: Rasmus Madsen <rasmus.madsen@wdc.com>
=> [aes/dv] added idle assert check

hw/ip/adc_ctrl/data/adc_ctrl_testplan.hjson, hw/ip/adc_ctrl/dv/adc_ctrl_sim_cfg.hjson, hw/ip/adc_ctrl/dv/env/adc_ctrl_env.core, hw/ip/adc_ctrl/dv/env/adc_ctrl_env_cfg.sv, hw/ip/adc_ctrl/dv/env/adc_ctrl_env_pkg.sv, hw/ip/adc_ctrl/dv/env/adc_ctrl_scoreboard.sv, hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_base_vseq.sv, hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_filters_polled_vseq.sv, hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_random_ramp_vseq.sv, hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_vseq_list.sv, hw/ip/adc_ctrl/dv/tb.sv, hw/ip/adc_ctrl/dv/tests/adc_ctrl_base_test.sv
- Added sequences
- adc_ctrl_random_ramp_vseq.sv
- adc_ctrl_filters_polled_vseq.sv
=> [adc_ctrl/dv] Added adc_ctrl_filters_polled test

hw/ip/keymgr/doc/dv/index.md, hw/ip/kmac/doc/dv/index.md, sw/README.md, sw/_index.md
Fix a few broken links throughout the doc.
Fix #10813
=> [doc] Fix broken links in the documentation

hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/data/kmac_sec_cm_testplan.hjson, hw/ip/kmac/rtl/keccak_round.sv, hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_app.sv, hw/ip/kmac/rtl/kmac_core.sv, hw/ip/kmac/rtl/kmac_entropy.sv, hw/ip/kmac/rtl/kmac_errchk.sv
What this commit does:
Added countermeasures implemented in KMAC into Hjson
Why is it valuable:
The `kmac.hjson` now  lists the countermeasures to help
understanding of possible attacks and protections.
Co-Authored-by: Michael Tempelmeier <michael.tempelmeier@gi-de.com>
=> [kmac] Countermeasures asset in Hjson

hw/ip/prim_generic/prim_generic_flop_en.core
=> [prim_flop_en] Dependency fix

hw/dv/tools/xcelium/common_cov_excl.tcl
=> [dv] exclude d_user.rsp_intg[6] for xcelium

hw/dv/sv/cip_lib/doc/index.md
described how to verify this countermeasure
=> [dv/doc] Update document for MUBI type CSRs/ports

hw/ip/lc_ctrl/data/lc_ctrl.prj.hjson, hw/ip/lc_ctrl/doc/checklist.md
- Updated project to V2
- Updated note regarding RV_TAP
- Added caveat regarding condition coverage to checklist
=> [lc_ctrl] Moved to V2

hw/ip/aes/rtl/aes_cipher_control.sv, hw/ip/aes/rtl/aes_cipher_core.sv, hw/ip/aes/rtl/aes_control.sv, hw/ip/aes/rtl/aes_core.sv, hw/ip/aes/rtl/aes_ctr.sv, hw/ip/aes/rtl/aes_key_expand.sv, hw/ip/aes/rtl/aes_sel_buf_chk.sv, hw/ip/aes/rtl/aes_sub_bytes.sv
=> [aes] Add prim_sec_anchor_buf

sw/device/lib/dif/dif_aes.c, sw/device/lib/dif/dif_aes.h, sw/device/lib/dif/dif_aes_unittest.cc, sw/device/sca/aes_serial.c, sw/device/tests/aes_smoketest.c
This PR Refators the dif_aes. 
To have a better understanding, please look at each commit individually.
=> [sw,dif,aes] dif aes refactoring

hw/ip/rv_dm/data/rv_dm.hjson, hw/ip/rv_dm/data/rv_dm_sec_cm_testplan.hjson, hw/ip/rv_dm/rtl/rv_dm.sv
Fixes https://github.com/lowRISC/opentitan/issues/109.
=> [rv_dm] Enumerate all countermeasure IDs and annotate RTL

hw/top_earlgrey/doc/_index.md
Add a short summary of top_earlgrey's interconnect topology and the
access latency.
Signed-off-by: Alexander Williams <awill@google.com>
=> [doc] Add a small note about the interconnect

hw/ip/rv_core_ibex/lint/rv_core_ibex.waiver
Some more errors need to be fixed in the RTL upstream. The corresponding lint errors will vanish once we vendor in Ibex the next time.
=> [ibex] Fix AscentLint errors

hw/ip/flash_ctrl/rtl/flash_mp.sv, hw/ip/prim_generic/rtl/prim_generic_flash.sv
- correctly generate eraes_done
- update model to correctly absorb erase_suspend input
- fixes #10748
=> [flash_ctrl] Fixes for erase suspend

hw/ip/adc_ctrl/data/adc_ctrl.prj.hjson, hw/ip/aes/data/aes.prj.hjson, hw/ip/aon_timer/data/aon_timer.prj.hjson, hw/ip/clkmgr/data/clkmgr.prj.hjson, hw/ip/csrng/data/csrng.prj.hjson, hw/ip_templates/alert_handler/data/alert_handler.prj.hjson, hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.prj.hjson, sw/device/lib/dif/dif_adc_ctrl.md, sw/device/lib/dif/dif_aes.md, sw/device/lib/dif/dif_alert_handler.md, sw/device/lib/dif/dif_aon_timer.md, sw/device/lib/dif/dif_clkmgr.h, sw/device/lib/dif/dif_clkmgr.md, sw/device/lib/dif/dif_csrng.md
This PR updates the DIF milestones and development stages for the following IPs:
- adc_ctrl
- aes
- alert_handler
- aon_timer
- clkmgr
- csrng
This partially addresses #10504.
=> [dif] Update DIF milestones and development stages

hw/ip/rom_ctrl/data/rom_ctrl_testplan.hjson, hw/ip/rom_ctrl/dv/env/rom_ctrl_env.core, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_kmac_err_chk_vseq.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_stress_all_vseq.sv, hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_vseq_list.sv, hw/ip/rom_ctrl/dv/rom_ctrl_sim_cfg.hjson
This is a draft PR until #10514 and #10719 are merged
=> Added Kmac err chk testcase

hw/dv/sv/spi_agent/spi_agent_cfg.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv, hw/ip/spi_device/dv/env/spi_device_env.sv, hw/ip/spi_device/dv/env/spi_device_env_cfg.sv, hw/ip/spi_device/dv/env/spi_device_env_pkg.sv, hw/ip/spi_device/dv/env/spi_device_virtual_sequencer.sv, hw/ip/spi_device/dv/tb/tb.sv, hw/ip/spi_device/dv/tests/spi_device_base_test.sv
Added workaround @weicaiyang proposed for Xcelium issue. This is replacing PR #10647 which will be closed now.
=> New SPI Device agent for passthrough connection

hw/ip/rv_dm/data/rv_dm.hjson, hw/ip/rv_dm/data/rv_dm_sec_cm_testplan.hjson, hw/ip/rv_dm/doc/_index.md, hw/ip/rv_dm/rtl/rv_dm.sv, hw/ip/sram_ctrl/doc/_index.md, util/build_docs.py
This addresses the review opens listed on https://github.com/lowRISC/opentitan/issues/10860.
@arnonsha: it would be good to get your feedback on the JTAG signal gating (last commit).
=> [rv_dm] Address D2S review action items

hw/ip/csrng/dv/env/csrng_env.sv, hw/ip/csrng/dv/env/csrng_env_cfg.sv, hw/ip/csrng/dv/env/csrng_env_pkg.sv, hw/ip/csrng/dv/env/csrng_scoreboard.sv, hw/ip/csrng/dv/env/csrng_virtual_sequencer.sv, hw/ip/csrng/dv/env/seq_lib/csrng_base_vseq.sv, hw/ip/csrng/dv/env/seq_lib/csrng_cmds_vseq.sv, hw/ip/csrng/dv/tb.sv, hw/ip/csrng/dv/tests/csrng_base_test.sv, hw/ip/csrng/dv/tests/csrng_cmds_test.sv
Be able to control above IOs and verify function as expected.
=> [csrng/dv] Verify lc_hw_debug_en and cs_aes_halt

hw/ip/rom_ctrl/data/rom_ctrl.prj.hjson
=> [rom_ctrl, dv] V2 sign off done

hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_app.sv, hw/ip/kmac/rtl/kmac_pkg.sv
This PR addresses https://github.com/lowRISC/opentitan/issues/6544
=> [kmac] hardened data output

hw/ip/pwrmgr/data/pwrmgr_testplan.hjson
=> [dv/pwrmgr] Rectify stress testpoint in testplan

hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_entropy.sv
This PR addresses the AI from the D2S to harden the hash counter
=> [kmac] added prim_count for hash_counter as suggested in D2S

hw/ip/kmac/rtl/keccak_2share.sv, hw/ip/kmac/rtl/keccak_round.sv
=> [kmac] made keccak sel_i/sel_mux mubi

hw/ip/rv_core_ibex/rtl/ibex_pmp_reset.svh, hw/ip/rv_core_ibex/rv_core_ibex.core, hw/top_earlgrey/chip_earlgrey_asic.core, hw/top_earlgrey/chip_earlgrey_cw310.core, hw/top_earlgrey/chip_earlgrey_verilator.core, hw/top_earlgrey/top_earlgrey.core, hw/top_englishbreakfast/chip_englishbreakfast_cw305.core
- add alternate pmp reset file
=> [ibex] Allow alternate epmp reset values

hw/top_earlgrey/data/chip_testplan.hjson
=> [dv] Add rv_core_ibex chip level tests to testplan

hw/ip/kmac/dv/env/kmac_env_pkg.sv, hw/ip/kmac/dv/env/kmac_scoreboard.sv, hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
This PR drives entropy related CSRs to refresh entropy.
=> [dv/kmac] Drive entropy related CSRs

hw/ip/aes/dv/env/aes_env.sv, hw/ip/aes/dv/env/aes_env_cfg.sv, hw/ip/aes/dv/env/aes_env_pkg.sv, hw/ip/aes/dv/env/seq_lib/aes_alert_reset_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_stress_vseq.sv, hw/ip/aes/dv/tb/tb.sv, hw/ip/aes/dv/tests/aes_alert_reset_test.sv, hw/ip/aes/dv/tests/aes_base_test.sv
this PR is a fairly small update to add verification to LC escalate.
the interface has been added and the knobs to inject errors have been updated to include pulling lc escalate.
=> Aes lc escalate

hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv, hw/ip/spi_host/data/spi_host_testplan.hjson, hw/ip/spi_host/dv/env/seq_lib/spi_host_smoke_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_speed_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_tx_rx_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_vseq_list.sv, hw/ip/spi_host/dv/env/spi_host_env.core, hw/ip/spi_host/dv/env/spi_segment_item.sv, hw/ip/spi_host/dv/spi_host_sim_cfg.hjson
=> [spi_host/dv] Enhanced Smoke Test

COMMITTERS
Add Jade Philipoom to the committers list as agreed by the
technical committee.
Thanks for all your contributions Jade!
=> [COMMITTERS] Update committers list

hw/formal/tools/jaspergold/conn.tcl
Remove quote characters, since they give trouble for ot_launch.
Log each csv file being processed.
=> [formal/jaspergold] Fix setting for conn_csvs

hw/ip/flash_ctrl/data/flash_ctrl.hjson, hw/ip/flash_ctrl/data/flash_ctrl.hjson.tpl, hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_phy.sv, hw/ip/otp_ctrl/data/otp_ctrl.hjson, hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl, hw/ip/otp_ctrl/rtl/otp_ctrl.sv, hw/ip/prim_generic/rtl/prim_generic_flash.sv, hw/ip/prim_generic/rtl/prim_generic_otp.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_earlgrey/ip/flash_ctrl/data/autogen/flash_ctrl.hjson, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv, hw/top_earlgrey/rtl/autogen/chip_earlgrey_nexysvideo.sv, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_englishbreakfast/data/top_englishbreakfast.hjson, util/topgen/templates/chiplevel.sv.tpl
=> [top] Hook-up flash/otp control and observation bus to ast

hw/ip/aon_timer/data/aon_timer.prj.hjson, hw/ip/aon_timer/data/aon_timer_testplan.hjson, hw/ip/aon_timer/doc/checklist.md
All action items from V2 review have been finished and PRs have been merged.
=> [aon_timer,dv] V2 Signoff

hw/ip/aes/rtl/aes.sv
This is related to lowRISC/OpenTitan#10991.
=> [aes] Allow de-asserting EDN request upon fatal alerts

hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
No real function update. Only remove unused functions and create a
function `reset_key_nonce` to reduce replication
=> [sram/dv] Update scb

hw/ip/otbn/dv/uvm/env/otbn_env_cov.sv
This says that we want to see each instruction (mnemonic) followed by
every other instruction. The only exception is that ECALL isn't
followed by anything else.
A quick run of 10 seeds for otbn-single hits roughly 20% of the cross.
Hopefully a full overnight run will do a bit better.
This is one of the items tracked at https://github.com/lowRISC/opentitan/issues/10705.
=> [otbn,dv] Define coverage for pairwise instruction mnemonics

hw/ip/kmac/data/kmac.prj.hjson, hw/ip/kmac/doc/checklist.md
This PR finishes the checklist for KMAC V2 status.
=> [dv/kmac] KMAC reaches V2

hw/top_earlgrey/data/chip_testplan.hjson, sw/device/silicon_creator/mask_rom/e2e_tests/mask_rom_e2e_testplan.hjson
This commit adds the initial list of testpoints for end-to-end testing
of the Mask ROM.
=> [mask_rom/e2e_tests] Mask ROM E2E testplan

hw/ip/flash_ctrl/data/flash_ctrl_testplan.hjson
Add label V2S for tests. Add new fetch test. Remove obb error test.
=> [flash_ctrl] ADD V2+V2S TESTS

hw/dv/tools/xcelium/common_cov_excl.tcl
This PR fixed the issue in #10962 
Signed-off-by: Rasmus Madsen <rasmus.madsen@wdc.com>
=> [tools/xcelium] updated common coverage exclusions 

hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_cmd_filtering_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv, hw/ip/spi_device/dv/env/spi_device_env.core, hw/ip/spi_device/dv/env/spi_device_env.sv, hw/ip/spi_device/dv/env/spi_device_env_pkg.sv, hw/ip/spi_device/dv/env/spi_device_scoreboard.sv, hw/ip/spi_device/dv/spi_device_sim_cfg.hjson, hw/ip/spi_device/dv/tests/spi_device_base_test.sv
Command filtering according to testplan description. Start of scoreboard implementation for passthrough mode.
=> Command filtering passthrough and start of scb for it

hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/data/kmac_sec_cm_testplan.hjson, hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_app.sv
Adding LC_ESCALATE_EN / KEY / REGWEN countermeasures to the doc and RTL.
=> [kmac] Document additional Countermeasures

hw/ip/kmac/rtl/kmac.sv
as suggested in D2S #10823 "LC escalate input is MUBI"
=> [kmac] added multiple copies for lc_escalate_en

hw/ip/kmac/rtl/kmac.sv, hw/ip/kmac/rtl/kmac_app.sv, hw/ip/kmac/rtl/kmac_entropy.sv
Issue #10952 is reported by @arnonsha
=> [kmac] Fix DC Lint of Enum assignment

hw/ip/usbdev/rtl/usbdev_aon_wake.sv
=> [usbdev] Remove aon_usb_events_active from async reset

hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/doc/_index.md
Doc update follow-on from https://github.com/lowRISC/opentitan/pull/10943.
=> [sram_ctrl] Update docs

hw/ip/lc_ctrl/rtl/lc_ctrl_state_decode.sv, hw/ip/otp_ctrl/rtl/otp_ctrl.sv
Spun out from https://github.com/lowRISC/opentitan/pull/10968#issuecomment-1046188256
=> [otp_ctrl/lc_ctrl] Fix VCS ENUMASSIGN warnings

hw/ip/aes/data/aes.prj.hjson, hw/ip/aes/doc/checklist.md
All D2S AI have been resolved (see #10422). There is one more PR to convert the Masking and SBoxImpl parameters to Sec parameters to reduce the risk of accidentally disable masking for tapeout here #10844. Once this is in, everything should be there to move to D2S.
=> [aes] D2S sign-off

hw/ip/rv_dm/data/rv_dm.prj.hjson
~~This should not be merged before #10866 has landed.~~
Closes https://github.com/lowRISC/opentitan/issues/10860
=> [rv_dm] Move to D2S

hw/ip/tlul/rtl/tlul_err_resp.sv
=> [tlul] socket error responder generates correct integrity

hw/ip/sram_ctrl/data/sram_ctrl_sec_cm_testplan.hjson
Add details in description and link tests
=> [sram/dv] Update sec_cm testplan

hw/ip/rstmgr/doc/_index.md, hw/ip/rv_core_ibex/doc/_index.md, hw/top_earlgrey/data/chip_testplan.hjson
- Added two tests for double fault testing
=> [doc] Documentation and testplan update for double fault

hw/ip/pinmux/fpv/tb/pinmux_bind_fpv.sv, hw/ip/pinmux/fpv/tb/pinmux_tb.sv, hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
This PR updates pinmux testbench IOs related to usb change.
=> [fpv/pinmux] Update pinmux IOs

hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_base_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_ec_pwr_on_rst_vseq.sv, hw/ip/sysrst_ctrl/dv/env/seq_lib/sysrst_ctrl_vseq_list.sv, hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env.core, hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson, hw/ip/sysrst_ctrl/dv/tests/sysrst_ctrl_base_test.sv
This test will verify the EC and power-on-reset feature.
=> [Sysrst_ctrl] Added EC and power-on-reset testcase

hw/dv/sv/cip_lib/doc/index.md
Update docs regarding to REGWEN test
Update pkg name cip_lib_pkg -> cip_base_pkg
=> [dv/docs] Small wording update in sec_cm section

hw/dv/sv/cip_lib/cip_base_scoreboard.sv, hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
This PR fixes OTP memory access error. OTP has to override
`is_tl_mem_access_allowed` because in two other cases we will see a
d_error in memory access:
1). Memory read access is locked because the `read_lock` register is
set.
2). Memory read access is locked because read has ECC uncorrectble
error.
To make sure these two errors are reflected in `exp_d_error`, I added
another output `customized_err`
=> [dv/otp] fix memory access error

hw/ip/kmac/data/kmac.hjson, hw/ip/kmac/rtl/kmac_core.sv, hw/ip/kmac/rtl/sha3pad.sv
As suggested in the D2S review #10823
=> [kmac] Declaring CTR.REDUN for key index and sentmsg counter

hw/ip/rstmgr/dv/rstmgr_cnsty_chk/data/rstmgr_cnsty_chk_testplan.hjson, hw/ip/rstmgr/dv/rstmgr_cnsty_chk/rstmgr_cnsty_chk_sim.core, hw/ip/rstmgr/dv/rstmgr_cnsty_chk/rstmgr_cnsty_chk_sim_cfg.hjson, hw/ip/rstmgr/dv/rstmgr_cnsty_chk/tb.sv, hw/ip/rstmgr/rstmgr.core, hw/ip/rstmgr/rstmgr_cnsty_chk.core, hw/ip/rstmgr/rtl/rstmgr_cnsty_chk.sv, hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson
Enable better testability of this V2S module.
=> [dv/rstmgr] Add dv environment for rstmgr_cnsty_chk

hw/ip/pwrmgr/dv/env/pwrmgr_if.sv
=> [dv/pwrmgr] Fix simple typo

hw/ip/rv_dm/rtl/rv_dm.sv
=> [rv_dm] Wire up debug memory byte write mask

hw/ip/flash_ctrl/doc/_index.md
=> [doc/flash_crtl] Fix some of the wording

hw/ip/rstmgr/data/rstmgr.hjson.tpl, hw/ip/rstmgr/doc/_index.md, hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson
- there is a separate readability feedback that will be done in a different PR.
=> [rstmgr] documentation updates based on d2s feedback

hw/dv/sv/cip_lib/doc/index.md
I missed this one last time. Now add it.
=> [dv/doc] Document security verification for memory integrity

hw/dv/sv/spi_agent/spi_agent_cfg.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_addr_translation_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_data_translation_vseq.sv, hw/ip/spi_device/dv/env/seq_lib/spi_device_vseq_list.sv, hw/ip/spi_device/dv/env/spi_device_env.core, hw/ip/spi_device/dv/env/spi_device_env_pkg.sv, hw/ip/spi_device/dv/spi_device_sim_cfg.hjson
Added address and payload swap scenarios in passthrough mode according to testplan. Removed passthrough from spi agent config.
=> [spi_device] Address and payload passthrough swap scenarios

hw/ip/otp_ctrl/dv/env/otp_ctrl_env_cov.sv, hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
This PR fixes illegal bin error when number of srams increased.
=> [dv/otp_ctrl] Fix regression illegal bin

hw/dv/sv/cip_lib/cip_base_scoreboard.sv, hw/ip/otp_ctrl/dv/env/otp_ctrl_scoreboard.sv
This PR updates the naming and comments regarding custom error from
PR #11085
=> [dv/cip] Update naming and comments for mem custom error

hw/top_earlgrey/data/chip_testplan.hjson, hw/top_earlgrey/dv/chip_sim_cfg.hjson, hw/top_earlgrey/dv/env/chip_env.core, hw/top_earlgrey/dv/env/seq_lib/chip_sw_pwm_pulses_vseq.sv, hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv, sw/device/tests/meson.build, sw/device/tests/pwm_test.c
Add initial place holder for pwmtest
=> [dv,top,pwm] Add initial place holders for pwm test

util/reggen/fpv_csr.sv.tpl
=> [fpv] support read on wr0c reg

hw/top_earlgrey/formal/chip_conn_cfg.hjson, hw/top_earlgrey/formal/conn_csvs/flash_ast.csv, hw/top_earlgrey/formal/conn_csvs/spi_device_ast.csv
This PR adds two connectivity tests between ast and flash, ast and
spi_device.
=> [conn] Add two AST related connectivity tests

hw/ip/aes/data/aes_testplan.hjson, hw/ip/aes/dv/aes_base_sim_cfg.hjson, hw/ip/aes/dv/env/aes_env.core, hw/ip/aes/dv/env/aes_env_cfg.sv, hw/ip/aes/dv/env/aes_message_item.sv, hw/ip/aes/dv/env/aes_seq_item.sv, hw/ip/aes/dv/env/seq_lib/aes_base_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_deinit_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_manual_config_err_vseq.sv, hw/ip/aes/dv/env/seq_lib/aes_vseq_list.sv, hw/ip/aes/dv/tests/aes_manual_config_err_test.sv, hw/ip/aes/dv/tests/aes_test.core, hw/ip/aes/dv/tests/aes_test_pkg.sv
This PR adds a directed test requested by the security group -clearing the registers then manually trying to trigger an operation without new configuration.
this can only be merged after #10988 is merged
=> Illegal mode

hw/ip/aes/rtl/aes.sv
Previously, AES would drop a potentially asserted EDN request signal in case of a fatal alert which could leave the EDN interface including CDC in a weird state. With this PR, the request signal is always kept asserted until acknowledgment which is similar to what other entropy consumers do.
This is related to lowRISC/OpenTitan#10991.
=> [aes] Hold EDN request until acknowledgment in case of fatal alerts

hw/ip/tlul/rtl/tlul_sram_byte.sv
=> [tlul_sram_byte] Fix width mismatch

hw/ip/tlul/doc/_index.md
Signed-off-by: Jayesh Patel <jayesh@aarishtech.com>
=> Correct documentation typo

hw/ip/adc_ctrl/dv/adc_ctrl_sim_cfg.hjson, hw/ip/adc_ctrl/dv/cov/adc_ctrl_core_cov_if.sv, hw/ip/adc_ctrl/dv/cov/adc_ctrl_cov.core, hw/ip/adc_ctrl/dv/cov/adc_ctrl_cov_bind.sv, hw/ip/adc_ctrl/dv/env/adc_ctrl_env_cov.sv
- Added functional coverage
- Added whitebox functional coverage
=> [adc_ctrl/dv] Added ADC functional coverage

hw/ip/adc_ctrl/data/adc_ctrl_testplan.hjson, hw/ip/adc_ctrl/dv/adc_ctrl_sim_cfg.hjson, hw/ip/adc_ctrl/dv/env/adc_ctrl_env.core, hw/ip/adc_ctrl/dv/env/adc_ctrl_env_cfg.sv, hw/ip/adc_ctrl/dv/env/adc_ctrl_scoreboard.sv, hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_filters_wakeup_vseq.sv, hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_vseq_list.sv
-Added tests:
- adc_ctrl_filters_wakeup
- adc_ctrl_filters_wakeup_fixed
- Added sequence adc_ctrl_filters_wakeup_vseq
- Added monitor_wakeup_proc task to scoreboard
=> [adc_ctrl/dv] Added adc_ctrl_filters_wakeup test

hw/dv/sv/spi_agent/seq_lib/spi_device_cmd_rsp_seq.sv, hw/dv/sv/spi_agent/spi_monitor.sv, hw/ip/spi_host/data/spi_host_testplan.hjson, hw/ip/spi_host/dv/env/seq_lib/spi_host_performance_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_sw_reset_vseq.sv, hw/ip/spi_host/dv/env/seq_lib/spi_host_vseq_list.sv, hw/ip/spi_host/dv/env/spi_host_env.core, hw/ip/spi_host/dv/env/spi_host_env_pkg.sv, hw/ip/spi_host/dv/env/spi_host_scoreboard.sv, hw/ip/spi_host/dv/spi_host_sim_cfg.hjson
- Added Speed Test
- Added Constraints to Segment Item
- Added Quad And Dual To Device Resp Seq
- Added Tag For Cover Points To Speed Test
- Added Sw Reset Test
=> [spi_host/dv] Sw Reset Test

hw/ip/rstmgr/dv/cov/rstmgr_cover.cfg
=> [dv/rstmgr] Add port toggle coverage for rstmgr_cnsty_chk

hw/ip/adc_ctrl/doc/_index.md
- clarify language around debounce counter
- clarify language around wakeup status
- companion PR to #10946 
- should fix #10884
=> [adc_ctrl] documentation update

hw/ip/flash_ctrl/data/flash_ctrl.sv.tpl, hw/ip/flash_ctrl/rtl/flash_ctrl.sv, hw/ip/flash_ctrl/rtl/flash_phy.sv, hw/ip/flash_ctrl/rtl/flash_phy_core.sv, hw/ip/flash_ctrl/rtl/flash_phy_erase.sv, hw/ip/flash_ctrl/rtl/flash_phy_pkg.sv, hw/ip/flash_ctrl/rtl/flash_phy_rd.sv, hw/ip/prim_generic/rtl/prim_generic_flash_bank.sv, hw/top_earlgrey/ip/flash_ctrl/rtl/autogen/flash_ctrl.sv
=> [flash_ctrl] Correct erase suspend interface behavior

hw/ip/rstmgr/data/rstmgr_testplan.hjson, hw/ip/rstmgr/dv/env/rstmgr_env_cov.sv, hw/ip/rstmgr/dv/env/rstmgr_if.sv, hw/ip/rstmgr/dv/env/rstmgr_scoreboard.sv
Also fix related dv doc mistakes.
=> [dv/rstmgr] Add missing covergroups

hw/ip/edn/data/edn.hjson, hw/ip/edn/rtl/edn_core.sv, hw/ip/edn/rtl/edn_reg_pkg.sv, hw/ip/edn/rtl/edn_reg_top.sv
Removing excess exclusion tags to increase coverage.
=> [edn/data] Remove exclusions from edn hjson file

hw/ip/rstmgr/data/rstmgr.hjson.tpl, hw/ip/rstmgr/data/rstmgr.sv.tpl, hw/ip/rstmgr/rtl/rstmgr_cnsty_chk.sv, hw/ip/rstmgr/rtl/rstmgr_leaf_rst.sv, hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson, hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr.sv
- fixes https://github.com/lowRISC/opentitan/issues/11121
- remove software checks for leaf resets that do not require it.
=> [rstmgr] unr review clean up

hw/dv/sv/csrng_agent/csrng_agent_cfg.sv, hw/dv/sv/csrng_agent/csrng_monitor.sv, hw/ip/csrng/dv/env/csrng_env_pkg.sv, hw/ip/edn/dv/env/edn_env_cfg.sv, hw/ip/edn/dv/env/edn_scoreboard.sv, hw/ip/edn/dv/env/seq_lib/edn_base_vseq.sv, hw/ip/edn/dv/env/seq_lib/edn_genbits_vseq.sv
Modifications to csrng_agent/vseqs to generate/account for additional command data.
=> [edn/dv] Allow/generate additional command data

hw/ip/prim/rtl/prim_lc_sender.sv, hw/ip/prim/rtl/prim_lc_sync.sv
=> [prim] Minor lint fixes for unused clocks / resets

hw/ip/sysrst_ctrl/dv/env/sysrst_ctrl_env_pkg.sv, hw/ip/sysrst_ctrl/dv/tb.sv
This PR will fix the intr_test failing in the regression
=> [sysrst_ctrl,dv] Connect interrupt to fix intr_test

hw/ip/pwrmgr/data/pwrmgr.hjson, hw/ip/pwrmgr/data/pwrmgr.hjson.tpl, hw/ip/pwrmgr/data/pwrmgr_sec_cm_testplan.hjson, hw/ip/pwrmgr/doc/_index.md, hw/ip/pwrmgr/rtl/pwrmgr.sv, hw/ip/pwrmgr/rtl/pwrmgr_fsm.sv, hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr.hjson, hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr_sec_cm_testplan.hjson
- convert entire rom_ctrl logic to mubi4
- change countermeasure name
=> [pwrmgr] Address several d2s review items

hw/ip/rstmgr/data/rstmgr.hjson.tpl, hw/ip/rstmgr/data/rstmgr.sv.tpl, hw/ip/rstmgr/dv/tb.sv, hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson, hw/top_earlgrey/data/top_earlgrey.hjson, hw/top_earlgrey/ip/rstmgr/data/autogen/rstmgr.hjson, hw/top_earlgrey/ip/rstmgr/rtl/autogen/rstmgr.sv, hw/top_earlgrey/rtl/autogen/top_earlgrey.sv, hw/top_englishbreakfast/data/top_englishbreakfast.hjson
=> [rstmgr] remove first_reset variable

hw/ip/rstmgr/dv/env/seq_lib/rstmgr_base_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_reset_vseq.sv, hw/ip/rstmgr/dv/env/seq_lib/rstmgr_smoke_vseq.sv
Minor coverage tuning for reset_req mubi.
=> [dv/rstmgr] Simplify reset checking

hw/top_earlgrey/dv/chip_sim.core, hw/top_earlgrey/dv/chip_sim_cfg.hjson
=> [full_chip,clkmgr] Bind clkmgr SVA in full chip

hw/ip/sram_ctrl/data/sram_ctrl.prj.hjson, hw/ip/sram_ctrl/doc/checklist.md
=> [sram/dv] Sign off V2S

hw/top_earlgrey/ip/ast/rtl/aon_osc.sv, hw/top_earlgrey/ip/ast/rtl/ast.sv, hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv, hw/top_earlgrey/ip/ast/rtl/io_osc.sv, hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv, hw/top_earlgrey/ip/ast/rtl/sys_osc.sv, hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
=> [AST] Fix Oscillators models instability

hw/ip/hmac/dv/env/hmac_scoreboard.sv
This isn't technically allowed by the IEEE 1800 LRM (see the start of
section 11.4.14). In particular Xcelium doesn't allow it! So tweak
things so that we only use it as the full right hand side of an
assignment.
=> [hmac,dv] Don't use streaming concatenation in a ternary

hw/ip/clkmgr/rtl/clkmgr_byp.sv, hw/ip/prim/lint/prim_clock_div.waiver, hw/ip/prim/lint/prim_double_lfsr.waiver, hw/ip/prim/prim_double_lfsr.core, hw/ip/prim/rtl/prim_double_lfsr.sv, hw/ip/rom_ctrl/rtl/rom_ctrl_rom_reg_top.sv, hw/ip/rstmgr/lint/rstmgr.waiver, hw/ip/rv_dm/rtl/rv_dm_rom_reg_top.sv, hw/ip/sram_ctrl/data/sram_ctrl.hjson, hw/ip/sram_ctrl/rtl/sram_ctrl_reg_pkg.sv, hw/ip/sram_ctrl/rtl/sram_ctrl_regs_reg_top.sv, hw/ip/tlul/rtl/tlul_sram_byte.sv, hw/ip/usbdev/data/usbdev.hjson, hw/ip/usbdev/rtl/usbdev_reg_pkg.sv, hw/ip/usbdev/rtl/usbdev_reg_top.sv, hw/top_earlgrey/ip/clkmgr/lint/clkmgr.waiver, hw/top_earlgrey/lint/top_earlgrey.waiver, util/reggen/reg_top.sv.tpl
- add waviers from prim modules
- add waiver for apparent tool limitation
- work around an apparent tool limitation
- add unused qualifiers
- add work arounds for unused clocks and resets
=> [all] variety of minor lint fixes

hw/ip/entropy_src/data/entropy_src_testplan.hjson
- Update the entropy_src interrupt, alert and error test covergroup
=> [entropy_src, dv] Update entropy_src testplan covergroup
